core/trino-main/src/main/java/io/trino/testing/TestingPageSinkId.java, core/trino-main/src/main/java/io/trino/testing/TestingPageSinkProvider.java, core/trino-main/src/test/java/io/trino/connector/MockConnector.java, core/trino-main/src/test/java/io/trino/operator/TestTableWriterOperator.java, core/trino-spi/pom.xml, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorPageSinkProvider.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorPageSinkProvider.java, plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/io/AccumuloPageSinkProvider.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSinkProvider.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPageSinkProvider.java, plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHolePageSinkProvider.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPageSinkProvider.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSinkProvider.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSinkProvider.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSinkProvider.java, plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaPageSinkProvider.java, plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduPageSinkProvider.java, plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPageSinkProvider.java, plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryPagesStore.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSinkProvider.java, plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorPageSinkProvider.java, plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/TestRaptorConnector.java
```markdown
* Remove deprecated methods from ConnectorPageSinkProvider. ({issue}`14959`)
```
fixes https://github.com/trinodb/trino/issues/14705
=> Remove deprecated page sink creation methods

plugin/trino-delta-lake/pom.xml, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogParser.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAnalyze.java
d_date column in TPCDS table date_dim has minimum value of `1900-01-02` 
This change allows delta lake to provide the correct lower bound instead of NULL in columns statistics to the CBO. 
This fixes the query plan for TPCDS q72.
Improve statistics for DATE columns in delta lake
```markdown
* Improve statistics for DATE columns in delta lake. ({issue}`15005`)
```
=> Reduce margin for START_OF_MODERN_ERA in delta lake stats

.github/workflows/ci.yml, docs/src/main/sphinx/connector/delta-lake.rst, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeDatabricks113.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLakeDatabricks113.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCheckpointsCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksInsertCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeTransactionLogCache.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DatabricksVersion.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DeltaLakeTestUtils.java
=> Add Databricks 11.3 test environment to Delta Lake

core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java, core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java
When theres's an expression such as:
CAST('2022-01-01') AS date) BETWEEN CAST(start_date AS date) AND CAST(end_date AS date)
There's a call to visitComparisonExpression with the term:
DATE '2022-01-01' >= CAST(start_date AS date)
Inside that method, the expression is normalized to have the symbol on the left and the constant on the right. However, the createVarcharCastToDateComparisonExtractionResult pulls the elements from the unnormalized ComparisonExpression node and expects the left subexpression to be cast, which results in a failure due to ClassCastException
Fixes #14954 
```markdown
* Fix failure for queries involving BETWEEN predicates over `varchar` columns that contain temporal data. ({issue}`14954`)
```
=> Fix ClassCastException in DomainTranslator

plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
The 2nd commit isn't very useful IMO. Just the first one should be fine.
=> Make SQLServer deadlock query retries reusable

.github/DEVELOPMENT.md, docs/README.md, docs/src/main/sphinx/appendix/from-hive.rst, docs/src/main/sphinx/connector/accumulo.rst, docs/src/main/sphinx/connector/iceberg.rst, docs/src/main/sphinx/connector/sqlserver.rst, docs/src/main/sphinx/develop/connectors.rst, docs/src/main/sphinx/develop/example-http.rst, docs/src/main/sphinx/develop/functions.rst, docs/src/main/sphinx/functions/json.rst, docs/src/main/sphinx/overview/concepts.rst, docs/src/main/sphinx/release/release-0.113.rst, docs/src/main/sphinx/release/release-0.166.rst, docs/src/main/sphinx/release/release-0.205.rst
Rather than take a side on whether it's "a SQL" or "an SQL," we can simply avoid the issue and any correctness concerns related to it by rewriting things. The only time we're losing any meaning is changing "an SQL query" to "a query" (which is redundant IMO), and in all other situations, it's either neutral or even an improvement/correction over what is currently written.
In principle, I am happy to admit that is an extremely terrible thing to do, but in practice, it does solve the problem!
solving the war of "a SQL statement" vs. "an SQL statement"
=> Reword docs to avoid mention of a/an SQL

core/trino-spi/src/main/java/io/trino/spi/type/Timestamps.java
Optimize `SqlTimestamp` and `SqlTimestampWithTimeZone` string formatting by calculating the exact required buffer size and avoiding a call to `String.format("%0" + precision + "d", ...)` on a per-row basis.
No non-technical explanation should be necessary since this is an internal implementation detail.
=> Optimize Timestamp Formatting

.github/workflows/ci.yml, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite2.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite6NonGeneric.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite7NonGeneric.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteCassandra.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteClickhouse.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteClients.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteFunctions.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteIceberg.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteKafka.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteMysql.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteStorageFormatsDetailed.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteTpch.java
Suite 6 and 7 total run time is nearly 1 hour so split them up. Check the running times at the end of the product tests step at https://github.com/trinodb/trino/actions/runs/3343271418/jobs/5537463265
n/a
=> Extract some product tests into a separate suites

plugin/trino-bigquery/pom.xml, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryUtil.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadSessionCreator.java
After some code investigation I found out that we have some logic of retries in bigquery connector. But as far as I understand this retry logic is applied only after we successfully create read session and executing read itself (during getting next page) :
```
@Overridepublic ReadRowsResponse next()
{
do {
try {
ReadRowsResponse response = serverResponses.next();
...
}
catch (Exception e) {
// if relevant, retry the read, from the last read position            
if (BigQueryUtil.isRetryable(e) && retries < helper.maxReadRowsRetries) {
log.debug("Request failed, retrying: %s", e);
serverResponses = helper.fetchResponses(nextOffset);
retries++;
}
...
}
}
while (serverResponses.hasNext());
```
Similar exception could occur during Read Session creation.
So this PR introduce exact same retry …
=> Big query retries during create read session

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapCastInComparison.java, core/trino-main/src/test/java/io/trino/sql/planner/TestUnwrapCastInComparison.java, core/trino-main/src/test/java/io/trino/sql/query/TestUnwrapCastInComparison.java
Fixes #5798
```markdown
* Improve performance of specific queries which compare table columns of type 
`date` with `timestamp with time zone` literals. ({issue}`5798`)
```
=> Support unwrap date to timestamp with time zone

docs/src/main/sphinx/appendix/from-hive.rst
Hive uses a non-ANSI SQL syntax for date and time INTERVAL expressions. This PR contains a brief explanation of these differences and an example for comparison.
Added documentation to the Hive migration docs page
=> Documented differences between INTERVAL expression on Trino versus Hive

docs/src/main/sphinx/connector/googlesheets.rst, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsConfig.java, plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/SheetsQueryRunner.java, plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestSheetsConfig.java, plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestSheetsPlugin.java
Rename config properties in Google Sheets
```markdown
* Rename config properties from `credentials-path` to `gsheets.credentials-path`, 
from `metadata-sheet-id` to `gsheets.metadata-sheet-id`, 
from `sheets-data-max-cache-size` to `gsheets.max-data-cache-size` and 
from `sheets-data-expire-after-write` to `gsheets.data-cache-ttl`. ({issue}`15042`)
```
=> Rename config properties in Google Sheets

core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorNodePartitioningProvider.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeNodePartitioningProvider.java
Remove deprecated `ConnectorNodePartitioningProvider.getBucketNodeMap()` method.
```markdown
* Remove deprecated `ConnectorNodePartitioningProvider.getBucketNodeMap()` method. ({issue}`14067`)
```
=> Remove deprecated getBucketNodeMap method

core/trino-main/src/main/java/io/trino/execution/CommentTask.java, core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java, core/trino-main/src/main/java/io/trino/execution/SetPropertiesTask.java, core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, testing/trino-testing-services/src/main/java/io/trino/testng/services/Listeners.java
The `semanticException` factory method is a format method - it takes a format string and format arguments - so it shoule be called as one. A future PR will enforce that using Error Prone, this PR collects fixes for the less trivial cases that need to be converted.
Better code quality.
```markdown
```
=> Call semanticException method as a format method in several places

core/trino-main/src/main/java/io/trino/connector/system/AbstractPropertiesSystemTable.java, core/trino-main/src/main/java/io/trino/connector/system/AnalyzePropertiesSystemTable.java, core/trino-main/src/main/java/io/trino/connector/system/ColumnPropertiesSystemTable.java, core/trino-main/src/main/java/io/trino/connector/system/MaterializedViewPropertiesSystemTable.java, core/trino-main/src/main/java/io/trino/connector/system/SchemaPropertiesSystemTable.java, core/trino-main/src/main/java/io/trino/connector/system/TablePropertiesSystemTable.java, core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java, core/trino-main/src/test/java/io/trino/connector/MockConnector.java, core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java, testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
This PR filter out values using configured access control from tables:
- `analyze_properties`
- `column_properties`
- `materialized_view_properties`
- `schema_properties`
- `table_properties`
- Fixes https://github.com/trinodb/trino/issues/14000
Do not leak configured catalogs names when user does not have an access to them
( ) This is not user-visible and no release notes are required.
```markdown
* Filter out values from system.metadata tables using access control ({issue}`14000`)
```
=> Filter out values from system.metadata tables using access control

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetastoreClosure.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/ForwardingHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/BridgingHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
```markdown
* Only allow creating ACID tables with the Thrift metastore. Improve error message when
attempting to modifying existing ACID tables with a non-Thrift metastore. ({issue}`14673`)
```
=> Only allow Hive ACID tables for Thrift metastore

core/trino-main/src/main/java/io/trino/execution/UseTask.java, core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java, testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
This PR add checks  if user has an access to catalog and schema in `USE` statement.
- Fixes https://github.com/trinodb/trino/issues/14208
There was a lack of check in `USE` statement if user has an access to catalog or schema.
```markdown
* Check access to catalog and schema during execution of USE statement. ({issue}`14208`)
```
=> Check catalog & schema access in USE statement

core/trino-spi/pom.xml, core/trino-spi/src/main/java/io/trino/spi/Unstable.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/ColumnDetail.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/ColumnInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/OutputColumnMetadata.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryCompletedEvent.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryContext.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryCreatedEvent.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryFailureInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryIOMetadata.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryInputMetadata.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryMetadata.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryOutputMetadata.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryStatistics.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/RoutineInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/SplitCompletedEvent.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/SplitFailureInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/SplitStatistics.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageCpuDistribution.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageGcStatistics.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageOutputBufferUtilization.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/TableInfo.java, core/trino-spi/src/main/java/io/trino/spi/metrics/Metrics.java
Some SPI elements are not meant for backward compatibility, because they
are not meant for being invoked by plugins at all. Ideally we would make
them inaccessible to plugins, but that is not possible.
This commit introduces an annotation to mark these APIs as such. It
doesn't change the development practice, since we would just change
these APIs without a notice, but it makes it clear to the consumers that
they cannot rely on these APIs being stable. Moreover, it excepts these
APIs frmo revapi backward compatibility checks (note that the exclusion
is effective starting from the next release).
=> Exempt certain APIs from SPI backward compatibility check

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
=> Delta Lake: Improve error message related to storage layers which allow write collisions

core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/JoinOperator.java, plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java, plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
In [Implement Join pushdown for JDBC connectors](https://github.com/trinodb/trino/pull/6874) we implemented join pushdown for JDBC connectors.
As part of that a test BaseJdbcConnectorTest#testJoinPushdown was added which verifies that LEFT, RIGHT and FULL joins get pushed down with all possible operators (=, !=, <, <=, >, >=, IS DISTINCT FROM, IS NOT DISTINCT FROM).
This PR is initial attempt to add more test cases for outer join pushdowns
```markdown
```
=> Add additional tests for outer join push downs

.github/workflows/milestone.yml
There can be situation where the latest milestone is closed but there are still some PRs for which this workflow is pending. The  API by default only lists open milestones. This commit changes it to list all milestones so that even if the target milestone is closed it can be found and the PR added to it.
Fix occasional set-milestone failure.
=> Fix set-milestone failure when latest milestone is closed

core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java, core/trino-main/src/test/resources/catalog_impersonation.json, docs/src/main/sphinx/security/file-system-access-control.rst, docs/src/main/sphinx/security/user-impersonation.json, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ImpersonationRule.java
Allow replacement string to substitute against original user in impersonation
Support replacement string in `new_user` to substitute against `original_user` in impersonation rules. E.g., the following rule allows a user in the form team_backend to impersonate the team_backend_sandbox user, but not arbitrary users:
```
{
"impersonation": [
{
"original_user": "team_(.*)",
"new_user": "team_$1_sandbox",
"allow": true
}
]
}
```
Relevant Trino doc on impersonation: https://trino.io/docs/current/security/file-system-access-control.html#impersonation-rules
```markdown
* Fix some …
```
=> Allow replacement string to substitute against original user in impersonation

core/trino-main/src/main/java/io/trino/execution/resourcegroups/IndexedPriorityQueue.java, core/trino-main/src/main/java/io/trino/operator/exchange/LocalExchange.java, core/trino-main/src/main/java/io/trino/operator/exchange/ScaleWriterPartitioningExchanger.java, core/trino-main/src/main/java/io/trino/operator/exchange/UniformPartitionRebalancer.java, core/trino-main/src/main/java/io/trino/sql/planner/PartitioningHandle.java, core/trino-main/src/main/java/io/trino/sql/planner/PartitioningScheme.java, core/trino-main/src/main/java/io/trino/sql/planner/SystemPartitioningHandle.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddLocalExchanges.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/HashGenerationOptimizer.java, core/trino-main/src/main/java/io/trino/sql/planner/sanity/ValidateScaledWritersUsage.java, core/trino-main/src/test/java/io/trino/operator/exchange/TestLocalExchange.java, core/trino-main/src/test/java/io/trino/operator/exchange/TestUniformPartitionRebalancer.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddLocalExchangesForTaskScaleWriters.java, core/trino-main/src/test/java/io/trino/sql/planner/sanity/TestValidateScaledWritersUsage.java
Issue: https://github.com/trinodb/trino/issues/13379
- Improve the performance of partitioned writes specifically in case writers/partitions are skewed.
- Known issue: https://github.com/trinodb/trino/issues/10791
- Relevant slack thread: https://trinodb.slack.com/archives/CFLB9AMBN/p1642961339264200
- Right now, prefer-partitioning only works if you have statistics and the number of partitions is greater than preferred-write-partitioning-min-number-of-partitions (default to 50). However, we know that stats are not always guaranteed to be present in which case partitioned writes will go through from an inefficient route. But with scaling, we could enable prefer-partitioning for any number of partitions thus we don't have to rely on statistics.
Cluster with 6 worker nodes
- Without …
=> Mitigate Writer skewness when writing partitioned data with preferred partitioning enabled

docs/src/main/sphinx/connector/clickhouse.rst, docs/src/main/sphinx/connector/druid.rst, docs/src/main/sphinx/connector/jdbc-authentication.fragment, docs/src/main/sphinx/connector/mariadb.rst, docs/src/main/sphinx/connector/mysql.rst, docs/src/main/sphinx/connector/oracle.rst, docs/src/main/sphinx/connector/postgresql.rst, docs/src/main/sphinx/connector/redshift.rst, docs/src/main/sphinx/connector/sqlserver.rst
Document credential providers introduced in #1124 and #1521
n/a
Fixes #1910, #1911
=> Document additional credential providers for JDBC connectors

core/trino-main/src/main/java/io/trino/execution/buffer/PagesSerde.java, core/trino-main/src/main/java/io/trino/execution/buffer/SpoolingExchangeOutputBuffer.java
The `AribitraryDistributionSplitAssigner` creates tasks based on the data size obtained from the `ExchangeSourceHandle` while the `HashDistributionSplitAssigner` creates tasks based on the data size estimates collected in SpoolingExchangeOutputBuffer. This introduces inconsistent meaning of `fault_tolerant_execution_target_task_input_size`, when depending on the stage it can either mean "physical compressed size" and in other cases "logical" size. 
It feels like it requires more work and we should probably revert this change for now.
```markdown …
```
=> Revert "Collect uncompressed data size for output statistics"

.github/actions/setup/action.yml, .github/actions/upload/action.yml, .github/workflows/ci.yml
=> Reduce recurring steps in CI workflow

.github/workflows/ci.yml, plugin/trino-bigquery/README.md, plugin/trino-bigquery/pom.xml, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClientFactory.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryWithDifferentProjectIdConnectorSmokeTest.java
This commit addresses an issue where multiple catalogs using the same service credentials but different project IDs attempt to create schemas and tables in either catalog. The project ID attached to the credential is used, ignoring the project ID specified in the connector configuration.
```markdown
* Fixed an issue creating schemas and tables when using multiple catalogs with the same credentials key but different project IDs
```
Fixes https://github.com/trinodb/trino/issues/14083
=> Fix use of project ID in BigQuery connector

docs/src/main/sphinx/admin/fault-tolerant-execution.rst, docs/src/main/sphinx/installation.rst, docs/src/main/sphinx/installation/query-resiliency.rst
Create a simplified guide on how to configure Trino with fault-tolerant execution, emphasizing the most common use case with an AWS S3 bucket for exchange storage. This is a companion to the existing `/admin/fault-tolerant-execution` reference material.
Add a guide explaining how to configure fault-tolerant execution on a Trino cluster, simplifying the feature for the average reader.
```markdown
```
=> Add guided walkthrough on configuring fault-tolerant execution

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
Fix https://github.com/trinodb/trino/issues/14746
As per offline discussion due to difficulties which may be caused by the fact that the permission policy for the Glue database which has `glue:GetTables` permission denied we've decided to put up this PR without corresponding tests. Do note however that the PR changes have been locally tested against AWS Glue.
```markdown
* Suppress access denied exception when listing all tables/views in a Glue database
```
=> Suppress access denied exception when listing all tables/views in a Glue database

lib/trino-parquet/src/main/java/io/trino/parquet/ParquetTypeUtils.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/ShortDecimalColumnReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ApacheParquetValueDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/DelegateDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BinaryBuffer.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BinaryColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FlatColumnReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/Int128ColumnAdapter.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/AbstractColumnReaderBenchmark.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkBinaryColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkLongDecimalColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkShortDecimalColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestBinaryColumnBenchmark.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestData.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestShortDecimalColumnReaderBenchmark.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/flat/TestBinaryBuffer.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/AbstractTestParquetReader.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetDecimalScaling.java
Support UUID, time, decimals, varchar, char in batched parquet reader
Improve performance of reading parquet files for column of type UUID, time, decimal, varchar and char.
```markdown
* Improve performance of reading parquet files for column of type UUID, time, decimal, varchar and char. ({issue}`14667`)
```
=> Support more types in batched parquet reader

core/trino-main/src/test/java/io/trino/metadata/TestInformationSchemaMetadata.java, testing/trino-tests/src/test/java/io/trino/connector/informationschema/BenchmarkInformationSchema.java, testing/trino-tests/src/test/java/io/trino/tests/TestMetadataManager.java
`listTables` is never called with a null schema name.
=> Fix param name in MockConnector listTables lambdas

core/trino-server/src/main/provisio/trino.xml, plugin/trino-mysql-event-listener/pom.xml, plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListener.java, plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListenerConfig.java, plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListenerFactory.java, plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListenerPlugin.java, plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/QueryDao.java, plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/QueryEntity.java, plugin/trino-mysql-event-listener/src/test/java/io/trino/plugin/eventlistener/mysql/TestMysqlEventListener.java, plugin/trino-mysql-event-listener/src/test/java/io/trino/plugin/eventlistener/mysql/TestMysqlEventListenerConfig.java, pom.xml, testing/trino-server-dev/etc/config.properties
MySQL based event listener allows to log detailed information about queries running on a Trino cluster directly into a MySQL table
New feature
New plugin
A plugin that allows to log information about queries running on a Trino cluster in MySQL table. The information include query text, query plan, detailed statistics and more. This information is useful for workload analysis and optimization.
`-`
( ) Documentation PR is available with …
=> Implement MySQL based event listener

docs/src/main/sphinx/connector/hive-s3.rst, docs/src/main/sphinx/connector/hive.rst
Documentation updates following up changes on Hive connector with Amazon S3: fix for Select pushdown for uncompressed files, addition of JSON support to Amazon S3 Select and usage of S3 Select scan range requests.
Relevant PRs: 
- [https://github.com/trinodb/trino/pull/12633](https://github.com/trinodb/trino/pull/12633)
- [https://github.com/trinodb/trino/pull/13354](https://github.com/trinodb/trino/pull/13354)
- [https://github.com/trinodb/trino/pull/13477](https://github.com/trinodb/trino/pull/13477)
- [https://github.com/trinodb/trino/pull/13754](https://github.com/trinodb/trino/pull/13754)
- [https://github.com/trinodb/trino/pull/14040](https://github.com/trinodb/trino/pull/14040) …
=> Hive Connector with Amazon S3 documentation updates

pom.xml
Update the JDBC driver for the SQL Server connector to the new major release (11) and also use the Java 17 version instead of the Java 11 version. The new driver is fully 4.2. JDBC spec compliant among other improvements.
Improvement.
SQL Server connector only.
Update to new JDBC driver mostly for maintenance reasons. 
* Release notes https://docs.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver16#112
(x) Sufficient documentation is included in …
=> Update MS SQL Server JDBC driver

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoInsertTableHandle.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoOutputTableHandle.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSink.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSinkProvider.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoTableHandle.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/RemoteTableName.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ptf/Query.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTableHandle.java
Introduce `RemoteTableName` class to MongoDB
```markdown
```
=> Introduce RemoteTableName class to MongoDB

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConnectorTest.java
This workaround can be removed once https://github.com/trinodb/trino/issues/14981 is addressed (I'm on it).
=> Fix flaky BigQuery testInsertSameValues

core/trino-main/src/main/java/io/trino/cost/TableScanStatsRule.java, core/trino-main/src/test/java/io/trino/cost/StatsCalculatorAssertion.java, core/trino-main/src/test/java/io/trino/cost/TestTableScanStatsRule.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java, plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseTestMySqlTableStatisticsTest.java
If a connector provides NDV but is missing nulls fraction statistic for a column
(e.g. Delta Lake after "delta.dataSkippingNumIndexedCols" columns and MySql), populate a
10% guess value so that the CBO can still produce some estimates rather than
failing to make any estimates due to lack of nulls fraction.
```markdown
* Improve CBO estimates when the nulls fraction statistic is not available for some columns. ({issue}`15132`)
```
=> Populate a nulls fraction when NDV is known in TableScanStatsRule

core/trino-spi/src/main/java/io/trino/spi/type/SqlTime.java, core/trino-spi/src/main/java/io/trino/spi/type/SqlTimeWithTimeZone.java, core/trino-spi/src/test/java/io/trino/spi/type/TestSqlTime.java, core/trino-spi/src/test/java/io/trino/spi/type/TestSqlTimeWithTimeZone.java
When a time value overflows it should not overflow into the maximum picos per day as this is not a valid value. However currently Trino rounding can return this value. 
```
trino> select time '24:00:00.000';
Query 20221121_151354_00001_cya5k failed: line 1:8: '24:00:00.000' is not a valid time literal
select time '24:00:00.000'
```
```markdown
* Fix rounding of TIME and TIME WITH TIME ZONE to return a zero time in case of overflow.
```
=> Fix rounding of `SqlTime` and `SqlTimeWithTimeZone` overflow

.github/workflows/ci.yml, docs/src/main/sphinx/admin/fault-tolerant-execution.rst, docs/src/main/sphinx/connector/mongodb.rst, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoInsertTableHandle.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoOutputTableHandle.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSink.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSinkProvider.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoQueryRunner.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoServer.java, pom.xml, testing/trino-faulttolerant-tests/pom.xml, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/mongodb/BaseMongoFailureRecoveryTest.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/mongodb/TestMongoQueryFailureRecoveryTest.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/mongodb/TestMongoTaskFailureRecoveryTest.java
This provides support for FTE with the Mongo connector. It uses the same paradigm as my [previous](https://github.com/trinodb/trino/pull/14730) PR. We only use this new paradigm with retries enabled, otherwise we use the old paradigm. This is important because this also increases our minimum mongo version from 4.0 to 4.2, but _only_ when FTE is enabled - this allows clients using Mongo on 4.0 to continue upgrading their trino version without having to upgrade their mongo, so long as they can live without FTE.
This provides support for fault tolerant execution on MongoDB. If you want to enable FTE, we require a minimum of Mongo version 4.2, otherwise we still support 4.0.
( ) Release notes are required, please …
=> Fault tolerant execution for Mongo connector

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
Increase the performance of the finishing step while inserting into existing partitions.
```
Benchmarks:
Query: Insert into test_table select * FROM tpch_sf100_orc_part.lineitem
Total partitions: 2000+
Total rows: 600M
Before:
Writing time: 2:31 mins
Finishing time: 9:01 mins
Total time: 11:32 mins
After:
Writing time: 2:30 mins
Finishing time: 1:21 mins
Total time: 3:51 mins
```
```markdown
```
=> Batch metastore calls in finishInsertIntoExistingPartitions

core/trino-main/src/main/java/io/trino/execution/CreateSchemaTask.java, core/trino-main/src/main/java/io/trino/security/AccessControl.java, core/trino-main/src/main/java/io/trino/security/AccessControlManager.java, core/trino-main/src/main/java/io/trino/security/AllowAllAccessControl.java, core/trino-main/src/main/java/io/trino/security/DenyAllAccessControl.java, core/trino-main/src/main/java/io/trino/security/ForwardingAccessControl.java, core/trino-main/src/main/java/io/trino/security/InjectedConnectorAccessControl.java, core/trino-main/src/main/java/io/trino/testing/AllowAllAccessControlManager.java, core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java, core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorAccessControl.java, core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingConnectorAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java, lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestAllowAllAccessControl.java, lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestAllowAllSystemAccessControl.java, lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedAccessControl.java, lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/LegacyAccessControl.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/security/TestLegacyAccessControl.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/security/TestSqlStandardAccessControl.java
Pass properties when checking access for CREATE SCHEMA
=> Pass properties when checking access for CREATE SCHEMA

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
This is similar change to #13242
Fixes #15174
```markdown
* Store query ID when creating a new schema. ({issue}`15174`)
* Fix incorrect `schema already exists` error caused by a client timeout when
creating a new schema. ({issue}`15174`)
```
=> Store query id and fix `schema already exists` error when creating a schema in Hive

.github/actions/compile-commit/action.yml, .github/workflows/ci.yml
Previous compilation check had a design flaw.
It used environment definitions from the HEAD of the PR for all commits in the PR.
In our CI pipeline we want to test if all commits of a PR would compile if checked out individually.
This ensures commits don't have dependencies on changes added afterwards. 
This makes it possible to automate git bisect.
Previous approach used a step in the main CI workflow, which is loaded when a CI workflow starts.
This means that the method of compiling each commit in the entire PR branch will be the one used for the PR HEAD.
This may cause problems if the PR changes any Maven parameters in any commit except the first one. 
Consider for example adding a `settings.xml` file to Maven parameters in a second commit of a PR.
Since the environment variables from …
=> Run compilation check as a composite action

core/trino-main/src/main/java/io/trino/execution/buffer/ArbitraryOutputBuffer.java, core/trino-main/src/main/java/io/trino/execution/buffer/BroadcastOutputBuffer.java
A buffer may be transitioned to ABORTED while in process of setting final OutputBuffers (with noMoreBuffers flag set to true).
Fixes https://github.com/trinodb/trino/issues/14814#issuecomment-1324249939
```markdown
```
=> Fix race condition in Arbitrary/BroadcastOutputBuffer

core/trino-main/src/main/java/io/trino/sql/gen/JoinFilterFunctionCompiler.java
Per code style, fields should be declared above the constructors.
=> Move JoinFilterFunctionCompiler constructor below fields

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PropertyDerivations.java, testing/trino-testing/src/main/java/io/trino/testing/AbstractTestWindowQueries.java
LocalExchange will preserve single stream property only if:
1. global partitioning is either on coordinator or single-node
2. LocalExchange is gathering
```markdown
* Fix a correctness bug for queries with certain complex window operators used in sequence 
```
=> Fix derivation of LocalExchange single stream property

core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java, core/trino-main/src/main/java/io/trino/execution/executor/TaskExecutor.java
Add code comment for StuckSplitTasksInterrupter race condition.
More details at https://github.com/trinodb/trino/pull/13272
https://github.com/trinodb/trino/pull/13272
```markdown
```
=> Add code comment for StuckSplitTasksInterrupter race condition

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConnectorFactory.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/InternalDeltaLakeConnectorFactory.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeRegisterTableProcedureTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePerTransactionMetastoreCache.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeRegisterTableProcedureWithFileMetastore.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakePlugin.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreAccessOperations.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestingDeltaLakeMetastoreModule.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeRegisterTableProcedureWithGlue.java
Testing infrastructure change.
Add the ability to inject the metastore into the Delta Lake connector. This change is mainly done to enable more testing scenarios:
-  reuse within the test scope the metastore used by the Delta Lake connector.
- change the functionality of the underlying metastore of the connector simulate a specific failure scenario.
=> Provide injection mechanism for the metastore in the Delta Lake connector

plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Fixes #15226
```markdown
* Delete a MongoDB field from collections when dropping a column. 
Previously, the connector dropped only metadata. ({issue}`15226`)
```
=> Remove MongoDB field from collections when dropping a column

client/trino-client/src/main/java/io/trino/client/FixJsonDataUtils.java, client/trino-client/src/main/java/io/trino/client/Row.java
Avoids a per-data cell switch over client type signatures when fixing query result data by converting the type specific behaviors into an interface instead.
Avoids a per-data cell switch over client type signatures when adapting query result data from JSON based on client type signature.
Also includes minor efficiency improvements to `Row` construction by sharing the same `Optional<String>` field name instance across all rows instead of constructing a per-row `Optional` wrapping.
No non-technical explanation should be necessary as this is an internal implementation detail for client value decoding. …
=> Improve client JSON value adapters

.github/workflows/ok-to-test.yml
The name of the app was not representing what it was used for, so we changed it. We also had to change names of the secrets to match it.
=> Use correct secret names in the ok-to-test workflow

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java, core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java, core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenTaskSourceFactory.java, core/trino-main/src/main/java/io/trino/execution/scheduler/FaultTolerantPartitioningSchemeFactory.java, core/trino-main/src/main/java/io/trino/execution/scheduler/HashDistributionSplitAssigner.java, core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedQueryScheduler.java, core/trino-main/src/main/java/io/trino/execution/scheduler/StageTaskSourceFactory.java, core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmenter.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyPreferredTableExecutePartitioning.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyPreferredTableWriterPartitioning.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java, core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java, core/trino-main/src/test/java/io/trino/execution/scheduler/TestHashDistributionSplitAssigner.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/BaseFaultTolerantExecutionTest.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/delta/TestDeltaFaultTolerantExecutionTest.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionConnectorTest.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionTest.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/iceberg/TestIcebergFaultTolerantExecutionTest.java
Implement skew mitigation to avoid running into low write concurrency when the number of output partitions is small
Some connectors (such as Hive) have limit on the number of partitions that can be written to in a single task. The default strategy for writes is to have all tasks (workers) to write to all partitions while distributing the data between each workers in a random (round-robin) fashion. This way it is not possible to write to more than 100 partitions by default. 
To allow the engine insert into more than 100 partitions in a single query the `preferred_write_partitioning` feature was introduced  https://github.com/trinodb/trino/pull/2358 as an opt-in feature and a cost-based optimization was added later to enable the feature based on statistics …
=> Enable preferred write partitioning for FTE by default

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPartitionEvolution.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
=> Improve error message for partitioning by nested field in Iceberg

docs/src/main/sphinx/connector/mongodb.rst, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientConfig.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientModule.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoClientConfig.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoPlugin.java
```markdown
* Rename config properties from `mongodb.ssl.enabled` to `mongodb.tls.enabled`. ({issue}`15240`)
* Add support for setting file path and password for truststore and keystore. ({issue}`15240`)
```
=> Add support for setting TLS context in MongoDB

client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/ColumnJdbcTable.java, testing/trino-product-tests/src/main/resources/io/trino/tests/product/jdbc/get_nation_columns.result
`DatabaseMetaData.getColumns` reports nullability in two result columns
- NULLABLE, a number (0, 1, 2)
- IS_NULLABLE, a varchar column ("YES", "NO", "")
This fixes the `TrinoDatabaseMetaData` so that information returned in
those two ways is consistent.
=> Fix DatabaseMetaData.getColumns nullability inconsistency

core/trino-main/src/main/java/io/trino/event/QueryMonitor.java, core/trino-main/src/main/java/io/trino/operator/ExplainAnalyzeOperator.java, core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java, core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java, core/trino-main/src/test/java/io/trino/execution/TaskTestUtils.java, docs/src/main/sphinx/sql/explain-analyze.rst, testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java
Output of EXPLAIN ANALYZE VERBOSE is often
shared for troubleshooting therefore it's
useful to print Trino version there.
** NO RELEASE NOTES **
=> Print Trino version to EXPLAIN ANALYZE VERBOSE

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientConfig.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientModule.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoClientConfig.java
These properties have been deprecated since 1 year ago.
https://github.com/trinodb/trino/commit/0ae5f2a6ebe76cf56984ca5b69e979e64d1003f6
```markdown
* Remove deprecated `mongodb.seeds` and `mongodb.credentials` config properties. ({issue}`15263`)
```
=> Remove `mongodb.seeds` and `mongodb.credentials` config properties

core/trino-main/src/main/java/io/trino/server/protocol/Query.java
When we finish reading data for a query we can
safely null reference to PagesSerde used for deserializing query results. This allow GCing buffer references stored in PagesSerde.
=> Reclaim PagesSerde memory in Query

core/trino-main/src/main/java/io/trino/operator/project/DictionaryAwarePageFilter.java, core/trino-main/src/main/java/io/trino/operator/project/DictionaryAwarePageProjection.java, core/trino-main/src/test/java/io/trino/operator/project/TestDictionaryAwarePageFilter.java, core/trino-main/src/test/java/io/trino/operator/project/TestDictionaryAwarePageProjection.java
When last dictionary was not effective but incoming dictionary size is not bigger than the block size, enable dictionary processing. Earlier this logic would apply only to the next dictionary through the existing `lastDictionaryUsageCount >= lastInputDictionary.getPositionCount()` condition. This change makes the heuristic more consistent by applying the same logic to the incoming dictionary page as well.
Minor improvement, not significant enough to RN.
=> Improve heuristic of using dictionary in project and filter

lib/trino-filesystem/pom.xml, lib/trino-filesystem/src/main/java/io/trino/filesystem/MemoryAwareFileSystem.java, lib/trino-filesystem/src/main/java/io/trino/filesystem/fileio/ForwardingOutputFile.java, lib/trino-filesystem/src/main/java/io/trino/filesystem/hdfs/HdfsOutputFile.java, lib/trino-orc/pom.xml, lib/trino-orc/src/main/java/io/trino/orc/OutputStreamOrcDataSink.java, lib/trino-orc/src/test/java/io/trino/orc/OrcTester.java, lib/trino-orc/src/test/java/io/trino/orc/TestOrcWriter.java, lib/trino-orc/src/test/java/io/trino/orc/TestStructColumnReader.java, plugin/trino-delta-lake/pom.xml, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriterManager.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/AzureTransactionLogSynchronizer.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/NoIsolationSynchronizer.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3TransactionLogSynchronizer.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcFileWriterFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetFileWriter.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/StandardFileFormats.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestHdfsParquetDataSource.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystem.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java, plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/OrcFileWriter.java
Account for memory allocated by TrinoS3FileSystems
Fixes: https://github.com/trinodb/trino/issues/14023
Some queries that previously killed cluster should be gracefully terminated now
```markdown
* Account for memory allocated by TrinoS3FileSystems. ({issue}`14023`)
```
=> Account for memory allocated by trino s3 staging output stream

core/trino-spi/src/main/java/io/trino/spi/predicate/SortedRangeSet.java, lib/trino-parquet/src/main/java/io/trino/parquet/ParquetEncoding.java, lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java
Improved logic for constructing domain from dictionary values in TupleDomainParquetPredicate by using the faster code path for constructing ValueSet from singleton values rather than Ranges.
Benchmark                                                  Mode  Cnt  Score Before      Score After     Units
BenchmarkTupleDomainParquetPredicate.domainFromDictionary  avgt   10  354.194 ± 29.631  211.831 ± 8.793 ms/op
```markdown
* Improve performance of reading parquet filter for queries with filters. ({issue}`issuenumber`)
```
=> Improve performance of parquet dictionary to domain conversion

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePartitionManager.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTableHandle.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/PartitionsSystemTableProvider.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveTableHandle.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestNodeLocalDynamicSplitPruning.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/AbstractFileFormat.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestConnectorPushdownRulesWithHive.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHiveProjectionPushdownIntoTableScan.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableHandle.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergProjectionPushdownPlans.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/optimizer/TestConnectorPushdownRulesWithIceberg.java
Add builders to Iceberg and Hive table handles.
Those will also be used outside of Trino.
=> Add builders to Iceberg and Hive table handles

plugin/trino-mongodb/pom.xml, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/AuthenticatedMongoServer.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoPrivileges.java
Enable authorizedDatabases & authorizedCollections for fetching metadata in MongoDB
https://github.com/trinodb/trino/issues/1398
```markdown
* Fix failure when an unauthorized exception happens while listing schemas or tables. ({issue}`1398`)
```
=> Enable authorizedDatabases & authorizedCollections for fetching metadata in MongoDB

core/trino-main/src/main/java/io/trino/execution/scheduler/policy/PhasedExecutionSchedule.java, core/trino-main/src/test/java/io/trino/TestSystemSessionProperties.java, core/trino-main/src/test/java/io/trino/execution/TestCommentTask.java, core/trino-spi/src/main/java/io/trino/spi/metrics/Metrics.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestingColumnReader.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java, plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestBingTileFunctions.java, plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHivePlugin.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveWriterFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/rubix/RubixInitializer.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java, plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpEventListener.java, plugin/trino-memory/src/main/java/io/trino/plugin/memory/TableInfo.java, plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java, plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/storage/organization/TestShardOrganizerUtil.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DeltaLakeTestUtils.java, testing/trino-tests/src/test/java/io/trino/tests/TestGracefulShutdown.java
Use `.collect(onlyElement())` to get the only element from the stream instead of `findAny` or `findFirst`. Use the latter only when it's expected that the stream can contain multiple elements and it is not important which one is chosen.
=> Deterministically get only element from the stream

core/trino-main/src/main/java/io/trino/connector/CoordinatorDynamicCatalogManager.java, core/trino-main/src/main/java/io/trino/connector/StaticCatalogManager.java, core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
When plugin concurrent loading was added
(c5ac103ede428edbbe02f6394dc6d38ce4422ee2), the catalogs could be loaded concurrently easily, because `ConnectorManager.createCatalog` was synchronized. The code has evolved since then, reducing contention significantly and thus allowing for parallel startup.
Fixes https://github.com/trinodb/trino/issues/15234
Follows https://github.com/trinodb/trino/pull/9521
=> Load catalogs concurrently

core/trino-main/src/main/java/io/trino/operator/scalar/timestamptz/TimestampWithTimeZoneOperators.java, core/trino-main/src/test/java/io/trino/operator/scalar/timestamptz/TestOperators.java
Fixes #15103
```markdown
* Fix incorrect results when adding or subtracting `interval` from `timestamp with time zone` type. ({issue}`15103`)
```
=> Fix incorrect result when add/subtract interval with timestamptz

core/trino-spi/pom.xml, core/trino-spi/src/main/java/io/trino/spi/predicate/Range.java, core/trino-spi/src/main/java/io/trino/spi/predicate/SortedRangeSet.java
Follows https://github.com/trinodb/trino/pull/15281,  https://github.com/trinodb/trino/pull/10239, https://github.com/trinodb/trino/pull/15268
=> Avoid operator lookup in Range.span

testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/utils/HadoopTestUtils.java
Should alleviate failure like this
2022-12-05 19:03:57 INFO: Test io.trino.tests.product.hive.TestHiveViews.testUnionDistinctViews took 38.65s
2022-12-05 19:03:57 INFO: FAILURE     /    io.trino.tests.product.hive.TestHiveViews.testUnionDistinctViews (Groups: hive_views) took 39.2 seconds
2022-12-05 19:03:57 SEVERE: Failure cause:
io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. Error caching map.xml: java.nio.channels.ClosedByInterruptException
at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:119)
at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
at …
=> Mark testUnionDistinctViews as `@Flaky`

core/trino-main/src/main/java/io/trino/operator/scalar/time/TimeOperators.java, core/trino-main/src/main/java/io/trino/operator/scalar/timetz/TimeWithTimeZoneToTimestampWithTimeZoneCast.java, core/trino-main/src/main/java/io/trino/operator/scalar/timetz/TimeWithTimeZoneToVarcharCast.java, core/trino-main/src/main/java/io/trino/type/ColorType.java, core/trino-main/src/main/java/io/trino/type/DateTimes.java, core/trino-main/src/test/java/io/trino/operator/scalar/timestamp/BenchmarkCastTimestampToVarchar.java, core/trino-main/src/test/java/io/trino/type/TestColorType.java, core/trino-spi/src/main/java/io/trino/spi/type/SqlTime.java, core/trino-spi/src/main/java/io/trino/spi/type/SqlTimeWithTimeZone.java, core/trino-spi/src/main/java/io/trino/spi/type/TimeZoneKey.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java
Replaces usages of `String.format` in expected codepaths to improve performance. In particular `time` / `timestamp` related JSON serializers and casts to `varchar` improve dramatically with `timestamp(3)` casting throughput improving 2x, `time(3)` improving more than 30x, and `time with time zone(3)` improving ~40x (benchmark results: [jmh.morethan.io](https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/pettyjamesm/706f34955e580d054606741ad41d3e3c/raw/2a905702d120ddb0a5b4ba58f28cfc60721b60fc/baseline-full.json,https://gist.githubusercontent.com/pettyjamesm/706f34955e580d054606741ad41d3e3c/raw/2a905702d120ddb0a5b4ba58f28cfc60721b60fc/improved-full.json)).
( ) Release notes are required, please …
=> Avoid String.format usages in hot paths

docs/src/main/sphinx/security/file-system-access-control.rst, docs/src/main/sphinx/security/overview.rst
Adds a verification step to the Trino security overview page with a link to the steps to verify system-level rules file.
```markdown
```
=> Add verification step for authorization docs

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
MongoCursor implement Closeable and should be closed in MongoSession#getTableMetadataNames
N/A
```markdown
```
=> Close mongo cursor in MongoSession#getTableMetadataNames

core/trino-main/src/main/java/io/trino/execution/CreateMaterializedViewTask.java, core/trino-main/src/main/java/io/trino/execution/CreateSchemaTask.java, core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java, testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Do not pass default properties to access control checks
=> Do not pass default properties to access control checks

docs/src/main/sphinx/connector/googlesheets.rst, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsClient.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsConfig.java, plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestGoogleSheets.java, plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestSheetsConfig.java
Hopefully, fixes #2941
```markdown
* Add support for setting read timeout using the `gsheets.read-timeout` config property. ({issue}`15322`)
```
=> Support setting read timeout in Google Sheets

core/trino-main/src/main/resources/webapp/src/components/StageDetail.jsx
In addition to Wall Time and Blocked Time
```markdown
* Display operator CPU time in Stage Performance tab
```
=> Display operator CPU time in Stage Performance tab

plugin/trino-delta-lake/pom.xml, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadataFactory.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeSharedMetastoreViewsTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedFileMetastoreViews.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedGlueMetastoreViews.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreAccessOperations.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastore.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeViewsGlueMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/TrinoViewHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/TrinoViewUtil.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalogFactory.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMergeAppend.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcMetricsCollection.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestTrinoHiveCatalogWithFileMetastore.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestTrinoHiveCatalogWithHiveMetastore.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeCompatibility.java
Support views in Delta lake connector
Improvement
Delta lake connector
* Fixes #11609 , fixes #15231
```markdown
* Add support for views. ({issue}`11763`)
```
=> Support views in Delta lake Connector

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/IndexJoinOptimizer.java, testing/trino-testing/src/main/java/io/trino/testing/AbstractTestIndexedQueries.java
Mitigates https://github.com/trinodb/trino/issues/15334
https://github.com/prestodb/presto/pull/1785
() Release notes are required, please propose a release note for me.
```markdown
* Disable reduced index push-down optimization that could result into some queries using index join occasionally return incorrect results
```
=> Disable reduced index pushdown for IndexJoin

core/trino-main/src/main/java/io/trino/FeaturesConfig.java, core/trino-main/src/main/java/io/trino/memory/MemoryManagerConfig.java, core/trino-main/src/main/java/io/trino/memory/NodeMemoryConfig.java, core/trino-main/src/main/java/io/trino/server/security/KerberosConfig.java
=> Inline configuration property value

core/trino-main/src/main/java/io/trino/sql/analyzer/AggregationAnalyzer.java, core/trino-main/src/test/java/io/trino/sql/planner/BenchmarkPlanner.java
See commit message
Replaces https://github.com/trinodb/trino/pull/14983
```markdown
* Improve performance of analysis of queries with a lot of GROUP BY clauses
```
=> Prevent redundant collection rewriting in AggregationAnalyzer

core/trino-main/src/main/java/io/trino/execution/buffer/ArbitraryOutputBuffer.java
Set output buffer overutilized when new pages are allowed. When a task is completed, its output buffer state is changed to FLUSHING and even if there is 0 output rows, it is considered as overutilized. This PR makes ArbitraryOutputBuffer's overutilized setting to be the same as BroadcastOutputBuffer.
```markdown
```
=> Set output buffer overutilized when new pages are allowed

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsMaker.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q19.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q24.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q27.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q29.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q30.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q31.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q57.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q72.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q83.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q19.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q24.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q27.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q29.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q30.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q31.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q57.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q72.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpch/iceberg/parquet/partitioned/q05.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpch/iceberg/parquet/partitioned/q07.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpch/iceberg/parquet/partitioned/q08.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpch/iceberg/parquet/unpartitioned/q05.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpch/iceberg/parquet/unpartitioned/q07.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpch/iceberg/parquet/unpartitioned/q08.plan.txt
These stats are used by CBO that expects sizes of data while it resides in memory.
The idea is to use column-sizes from Iceberg metadata stored there by parquet writer. From some tests I ran it looks like multiplying by 10 looks like a good heuristic. 
```markdown
```
=> Multiply on disk column sizes of iceberg data files by 4 for column stats

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcRecordCursor.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
=> Propagate table information when creating Connection for RecordCursor

.github/workflows/ci.yml, plugin/trino-hive/pom.xml, plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/BaseTestTrinoS3FileSystemObjectStorage.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystemAwsS3.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystemMinio.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/SuiteDeltaLakeDatabricks.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDropTableCompatibility.java
Speed up the deletion of an S3 "directory" ( a path prefix which corresponds to multiple S3 objects) by using  batch deletion  requests.
Fix
Hive, Delta, Iceberg (Lakehouse connectors)
Speed up the deletion of an S3 "directory" ( a path prefix which corresponds to multiple S3 objects) by using  batch deletion  requests.
Fixes #13017 
( ) Documentation issue #issuenumber is filed, and can …
=> Perform S3 directory deletion with batch requests

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcTableHandle.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcRecordSetProvider.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcTableHandle.java, plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
Additional details can be used for tracking/debugging purpose
```markdown
```
=> Allow capturing authorization details in JdbcTableHandle

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePartitionManager.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTableHandle.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/PartitionsSystemTableProvider.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveTableHandle.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestNodeLocalDynamicSplitPruning.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/AbstractFileFormat.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestConnectorPushdownRulesWithHive.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHiveProjectionPushdownIntoTableScan.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableHandle.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergProjectionPushdownPlans.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/optimizer/TestConnectorPushdownRulesWithIceberg.java
Revert https://github.com/trinodb/trino/pull/15217
=> Revert table handle builders in hive and iceberg

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapDateTruncInComparison.java
The `endExclusive` variable is derived from `dateTime` which has `0` nanoseconds.
=> Remove unnecessary computation

plugin/trino-redshift/README.md, plugin/trino-redshift/pom.xml, plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/ImplementRedshiftAvgBigint.java, plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/ImplementRedshiftAvgDecimal.java, plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java, plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClientModule.java, plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftTableStatisticsReader.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/RedshiftQueryRunner.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftAutomaticJoinPushdown.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorTest.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftTableStatisticsReader.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftTypeMapping.java
This PR contains many improvements for Redshift with a full test suite.  Currently the test suite must be run manually.
I have run the test manually and they all pass.
Fixes #14697
```markdown
* Add aggregation, join, and top N pushdown ({issue}`15365`)
* Implement DELETE ({issue}`15365`)
* Implement full type mapping ({issue}`15365`)
* Add schema, table and column name length checks ({issue}`15365`)
```
=> Improve Redshift

client/trino-client/src/main/java/io/trino/client/StatementClientFactory.java, client/trino-client/src/main/java/io/trino/client/StatementClientV1.java, core/trino-main/src/main/java/io/trino/Session.java, core/trino-main/src/main/java/io/trino/testing/TestingSession.java, testing/trino-testing/src/main/java/io/trino/testing/AbstractTestingTrinoClient.java, testing/trino-tests/src/test/java/io/trino/tests/TestServer.java
=> Test SET PATH support by clients 

core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiAuthenticationFilter.java, core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
When refresh token is retrieved for UI, currently we were sending HTTP Status 303, assuming that all the request will just repeat the call on the Location header. When this works for GET/PUT verbs, it does not for non-idempotent ones like POST, as every JS HTTP client should do a GET on LOCATION after 303 on POST. Due to that I change it to 307, that should force every client to repeat the exactly the same request, no matter the verb.
This PR replaces https://github.com/trinodb/trino/pull/15184
```markdown
* Fix HTTP redirect after OAuth2 token refresh. ({issue}`15336`)
```
=> Fix HTTP_Status on OAuth2 refresh token redirect

core/trino-main/src/main/java/io/trino/operator/project/PageProcessor.java
Actual work is done in `pageProjectWork.process()` call while `projection.project` only performs setup of projection. 
So both `expressionProfiler` and `metrics.recordProjectionTime` needed to be around that method.
```markdown
* Fix recording of `Projection CPU time` in EXPLAIN ANALYZE VERBOSE. ({issue}`15364`)
```
=> Fix recording of projection metrics

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveType.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveTypeTranslator.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestReadUniontype.java
Support dereferencing  using field names such as "field0", "field1", "tag" for Hive's Union Type. 
https://github.com/trinodb/trino/pull/15017,
https://github.com/trinodb/trino/pull/3483,
https://github.com/trinodb/trino/commit/e071da402efb4b95f6c8b13b2a241e86e446e2a8
```markdown
*  Fix queries referencing nested fields in union typed columns. ({issue}`15278`)
```
=> Fix dereference operations for union type in Hive Connector

core/trino-main/src/main/java/io/trino/operator/exchange/PartitioningExchanger.java
Removes outdated comments and unnecessary methods in local exchange PartitioningExchanger since the operator is no longer implemented in a way that attempts to be thread-safe after https://github.com/trinodb/trino/pull/13834
=> Cleanup PartitioningExchanger

plugin/trino-iceberg/pom.xml, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergAvroPageSource.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java, pom.xml, testing/trino-faulttolerant-tests/pom.xml, testing/trino-tests/pom.xml
Testing the new release of Iceberg 1.1.0 against the Trino tests. This shouldn't be merged
```markdown
```
=> Update to Iceberg 1.1.0

docs/src/main/sphinx/optimizer/pushdown.rst
=> Document Top-N pushdown

core/trino-main/src/main/java/io/trino/connector/system/SystemTablesMetadata.java, core/trino-main/src/main/java/io/trino/testing/TestingMetadata.java, plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloMetadata.java, plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopMetadata.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java, plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java, plugin/trino-example-http/src/main/java/io/trino/plugin/example/ExampleMetadata.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsMetadata.java, plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxMetadata.java, plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaMetadata.java, plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisMetadata.java, plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileMetadata.java, plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java, plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusMetadata.java, plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisMetadata.java, plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftMetadata.java, plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsMetadata.java
Remove identical override to the default `getTableProperties` method from `ConnectorMetadata`:
https://github.com/trinodb/trino/blob/cd8eac64e3e427be45fc5df5b5a61110245479ec/core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java#L1036-L1038
=> Remove unnecessary override for `getTableProperties` method

core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java, core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/UnaliasSymbolReferences.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/TableFunctionNode.java, core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java, core/trino-main/src/main/java/io/trino/sql/planner/sanity/ValidateDependenciesChecker.java, core/trino-main/src/test/java/io/trino/connector/TestingTableFunctions.java, core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java, core/trino-spi/src/main/java/io/trino/spi/ptf/ConnectorTableFunction.java, core/trino-spi/src/main/java/io/trino/spi/ptf/TableFunctionAnalysis.java, docs/src/main/sphinx/develop/table-functions.rst
Add support for declaring required input columns by a table function.
Only the SPI and analyzer parts. Table arguments are not supported, so this change is not meaningful to the user.
Docs change included.
=> Analyze input columns required by a table function

core/docker/default/etc/jvm.config, core/trino-server-rpm/src/main/resources/dist/config/jvm.config, docs/src/main/sphinx/installation/deployment.rst
Preventive GC was added in 17, but has issues so JDK 20 disables it by default (plans to [completely remove it in JDK 21](https://bugs.openjdk.org/browse/JDK-8297639))
Users should be aware that until Trino uses java 20+, they should not use preventive GC as it could lead to unexpected OOM
- close https://github.com/trinodb/trino/issues/15379
- https://trinodb.slack.com/archives/C01TEP0HJTH/p1670817191607989
```markdown
```
=> Disable preventive GC

core/trino-main/src/main/java/io/trino/operator/DirectExchangeClient.java, core/trino-main/src/main/java/io/trino/operator/HttpPageBufferClient.java, core/trino-main/src/main/java/io/trino/operator/PageBufferClientStatus.java, core/trino-main/src/test/java/io/trino/operator/TestDirectExchangeClient.java, core/trino-main/src/test/java/io/trino/operator/TestHttpPageBufferClient.java
Let's define the class of queries that are run on skewed data and as a result on some downstream stage there is one (or few nodes) that gather data from empty or nearly empty nodes at upstream stage - i.e. at some upstream stage most nodes are empty (serving no data) or nearly empty (serving little data). We observed that such queries are executed very poorly on Trino.
This PR addresses that issue.
The query listed below is a representant of that class:
```
SELECT
count(*),
cc.cc_name,
cc.cc_class,
cc.cc_manager,
cc.cc_mkt_desc,
cc.cc_market_manager,
cc.cc_division_name
FROM catalog_sales cs
RIGHT JOIN call_center cc ON cc.cc_call_center_sk =  cs.cs_call_center_sk
RIGHT JOIN store s ON cc.cc_closed_date_sk = s.s_closed_date_sk
GROUP BY 2, 3, 4, 5, 6, 7
ORDER BY 1, 2, 3, 4, 5, 6, 7
LIMIT …
```
=> Decide number of clients basing on average request size of client

core/trino-main/src/main/java/io/trino/server/security/oauth2/NimbusOAuth2Client.java
According to https://www.rfc-editor.org/rfc/rfc6749#section-4.1.3 scope parameter in the get token request is actually redundant as it was already provided in the authorization request. Refresh token request on the other hand should still provide it.
=> Remove redundant scope parameter

plugin/trino-atop/src/test/java/io/trino/plugin/atop/TestAtopPlugin.java
Add test create Atop connector
Fixes #15419
=> Add test create Atop connector

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
The Paruqet reader does not support pushdown on fields of a Row type. The checks in `IcebergPageSourceProvider#getParquetTupleDomain` used to prevent this, but they stopped working when dereference pushdown was implemented.
If a row field had the same name as a top level column this would have resulted in a correctness issue.
Deref/projection pushdown was implemented in: https://github.com/trinodb/trino/pull/8129
=> Fix error in Iceberg predicate pushdown to Parquet files

core/trino-parser/src/main/java/io/trino/sql/tree/QualifiedName.java
A small performance tweak.
I noticed that about 1% of analysis time in some of my huge queries was spent in the constructor of `QualifiedName` in stream logic.
```markdown
```
=> Speed up `QualifiedName` constructor

docs/src/main/sphinx/connector/mysql.rst, plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java, plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClientModule.java, plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlJdbcConfig.java, plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java, plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlConnectorTest.java, plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlLegacyConnectorTest.java, pom.xml, testing/trino-product-tests/src/main/resources/tempto-configuration.yaml
Update MySQL JDBC driver to 8.0.29
Fixes #15332 Closes #12692
Update MySQL JDBC driver to 8.0.29
```markdown
* Update MySQL JDBC driver to 8.0.29. This fixes failure when `query` table function contains `WITH` clause. ({issue}`15332`)
```
=> Update MySQL JDBC driver to 8.0.29

core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java
Shuts down the yield executor in the SqlTaskManager during the pre destroy workflow.
Found an executor that is not being shutdown who threads were found during a stack dump on a hung worker. 
```markdown
```
=> Shutdown yield executor

lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/TransformingValueDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoder.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BinaryBuffer.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BinaryColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BooleanColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ByteColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/DictionaryDecoder.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FlatColumnReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/Int128ColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/Int96ColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/IntColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/LongColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ShortColumnAdapter.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestTimestamp.java
Uses batched decoders to resolve dictionary ids into actual values instead of going through `Dictionary#decodeXXX` methods
=> Optimize reading dictionary encoded parquet columns

plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java
This is a follow-up of https://github.com/trinodb/trino/pull/14737. I confirmed that the query runner starts correctly and TPCH tables are accessible without the VM arguments.
=> Remove obsolete comment from Hudi S3 query runner

docs/src/main/sphinx/connector/elasticsearch.rst
Provide proper documentation and example usage of the `raw_query` table function in the Elasticsearch connector documentation
Resolves https://github.com/trinodb/trino/issues/13007
```markdown
```
=> Document raw_query table function in Elasticsearch connector

plugin/trino-delta-lake/pom.xml, plugin/trino-hive/pom.xml
Move configuration of maven plugins to top level
so it is applied also when non-default build profile is used
=> Move plugin configurations to top level

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ObjectIdFunctions.java
Set deterministic as false in MongoDB `ObjectId` function because 
the function may return different results in a query.
```markdown
* Fix potential incorrect results when `objectid` function is used more than once. ({issue}`15426`)
```
=> Set deterministic as false in MongoDB `ObjectId` function

.github/workflows/ci.yml
Since 93f4cfc429677c1b8ef18fcadb4a89c3c663f4b7 (#12817) the concurrency group also handles repository dispatch events, but it incorrectly includes the SHA, making it too specific. SHA should only be used for events other than pull requests or repository dispatch.
n/a
=> Make concurrency group in CI less specific

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateSchemaInternalRetry.java
Add test for https://github.com/trinodb/trino/pull/13242 which was merged without a test as we didn't have an infrastructure for such tests at that time.
https://github.com/trinodb/trino/issues/15282
=> Test Delta Lake metadata handling when schema already exists

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java
=> retry to connect to hive metastore with new delegation token.

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java, core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
fixes: https://github.com/trinodb/trino/issues/14459
```markdown
* Validate that configured number of task retries is not larger than 126. ({issue}`14459`)
```
=> Enforce no more than 126 task retries

testing/trino-testing-services/src/main/java/io/trino/testng/services/ProgressLoggingListener.java
Before the change it would log something like
> [CONFIGURATION] TestOrcPageSourceMemoryTracking.setUp()[pri:0,
> instance:io.trino.plugin.hive.TestOrcPageSourceMemoryTracking@7ef9c8a5]
> 2130299045 for
> io.trino.plugin.hive.TestOrcPageSourceMemoryTracking.setUp
Follows https://github.com/trinodb/trino/pull/15165
=> Fix test configuration method duplicated logging

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/DefaultThriftMetastoreClientFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
An alternative approach to https://github.com/trinodb/trino/pull/15433
The connection is being closed and created again after an alternative call ends up with an exception.
```markdown
```
=> Recreate thrift client during alternate calls

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableWithCustomLocationUsingHiveMetastore.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreAccessOperations.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreStatistics.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestConnectorPushdownRulesWithHive.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHivePlans.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHiveProjectionPushdownIntoTableScan.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMergeAppend.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataListing.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcMetricsCollection.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithCustomLocation.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithExternalLocation.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestSharedHiveMetastore.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/optimizer/TestConnectorPushdownRulesWithIceberg.java
Use `createTestingFileHiveMetastore` method in tests
=> Use createTestingFileHiveMetastore method in tests

lib/trino-parquet/src/main/java/io/trino/parquet/ParquetReaderUtils.java, lib/trino-parquet/src/main/java/io/trino/parquet/ParquetTypeUtils.java, lib/trino-parquet/src/main/java/io/trino/parquet/dictionary/IntegerDictionary.java, lib/trino-parquet/src/main/java/io/trino/parquet/dictionary/LongDictionary.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/SimpleSliceInputStream.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ApacheParquetValueDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/PlainByteArrayDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/PlainValueDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ShortDecimalFixedWidthByteArrayBatchDecoder.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BitPackingUtils.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FlatColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkBinaryColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkShortDecimalColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestData.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/AbstractValueDecodersTest.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestBooleanValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestByteArrayValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestByteValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestDoubleValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestFixedWidthByteArrayValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestFloatValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestIntValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestLongValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestShortValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/flat/TestBitPackingUtils.java
Optimize PLAIN values decoders in parquet reader
```markdown
* Improve performance of reading parquet files. ({issue}`15308`)
```
=> Optimize PLAIN values decoders in parquet reader

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ExpressionConverter.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Iceberg doesn't support filters on struct types. 
Closes #8759
=> Remove TODO comment about predicates on struct type in Iceberg

core/trino-main/src/main/java/io/trino/execution/SetTimeZoneTask.java, core/trino-main/src/test/java/io/trino/execution/TestSetTimeZoneTask.java
This is a PR to solve the #15314 issue.
`SET TIME ZONE LOCAL` statement means to reflect the TimeZone initially set on the client. Currently, if TimeZone information is not checked in the syntax (LOCAL), the default TimeZone of the server is reflected.
In the case of LOCAL, rather than setting the client TimeZone in `SessionProperties`, the code was modified to invalidate the TIME_ZONE_ID set in `SessionProperties` and use the client's TimeZoneKey.
Based on the changed code, it works as follows.
* Server's timezone: `America/Los_Angeles`
* Client's timezone: `Europe/Warsaw`
```
trino> select current_timestamp;
_col0                 
---------------------------------------
2022-12-08 07:47:48.873 Europe/Warsaw 
(1 row)
Query 20221208_064748_00005_yxge6, FINISHED, 1 node
Splits: 1 total, 1 …
```
=> Fix SET TIME ZONE LOCAL works appropriate

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Exceptions in HiveMetadata class contain the name of the problematic column. That was not the case for timestamp validation exception.
```markdown
* 
```
=> Provide more verbose exception messages

docs/src/main/sphinx/connector/googlesheets.rst, plugin/trino-google-sheets/pom.xml, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsClient.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsConfig.java, plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestSheetsConfig.java
Allows the google sheets connector to be configured by base64 encoded string (instead of file). Simplifies deployments of trino since you do not need to configure a file. This is similar to what is supported for the bigquery connector: https://github.com/trinodb/trino/blob/master/plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/StaticCredentialsConfig.java#L27
Also updates the google sheets dependency version, the current version: https://mvnrepository.com/artifact/com.google.apis/google-api-services-sheets/v4-rev516-1.23.0 is multiple years old and has a dependency on `google-api-client` with a security vulnerability.
N/A
(x) …
=> Add support for base64 encoded secrets in Google Sheets connector

client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java, core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalAverageAggregation.java, core/trino-main/src/test/java/io/trino/operator/aggregation/AbstractTestDecimalAverageAggregation.java, core/trino-main/src/test/java/io/trino/operator/aggregation/AbstractTestDecimalSumAggregation.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java, testing/trino-testing/src/main/java/io/trino/testing/H2QueryRunner.java
BigDecimal constants are deprecated from Java 9.
NA
```markdown
```
=> Use RoundingMode enum instead of deprecated BigDecimal constant

.github/workflows/ci.yml
#15157 introduced a composite job for compiling every commit of a PR.
Before running check-commits dispatcher it's important to check that the PR branch contains the definition of the `compile-commit` composite job.
A bug was also discovered in the job responsible for selecting commits to be compiled. 
The `rev-list` query by default returns the list of commit hashes in **reverse** chronological order.
The last `rev-list` entry removed by the `jq` pipeline expression was the oldest PR commit, not the newest one.
This commit fixes the problem by using the `rev-list` expression instead of `jq` pipeline to filter out PR HEAD. …
=> Run check-commits dispatcher only if PR branch has `compile-commit` job

plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViewsLegacy.java
Given the following scenario:
`hive`
```
create table test1 (id char(1))
create view v_test1 as select * from test1;
```
In Trino `hive.properties`
```
hive.translate-hive-views=true
```
When selecting in Trino from the hive view, the following exception is encountered:
```
View 'hive.default.v_test1' is stale or in invalid state: column [id] of type char(1) projected from query view at position 0 cannot be coerced to column [id] of type varchar stored in view definition
```
Instead of falling back in case of dealing with hive view `char` columns to `varchar`, use `char(x)` type for these columns and avoid therefore issues related to #9031
(x) …
=> Use `char(x)` representation for Hive `char` view columns

core/trino-main/src/test/java/io/trino/execution/TestDropTableTask.java
Add test for DROP TABLE IF EXISTS statement with non-existing object
NA
```markdown
```
=> Add test for DROP TABLE IF EXISTS statement with non-existing object

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TrinoMetricsReporter.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
Iceberg's new feature, metrics reporting, by default logs quite long log lines at INFO level for every table scanned in the query. This is quite verbose, potentially affecting log rotation on production installations and affecting Trino CI Github Actions logs.
Move the metrics reporting to DEBUG log level, at least for table instances instantiated directly in Trino code.
Hopefully fixes https://github.com/trinodb/trino/issues/15492
=> Reduce Iceberg metrics reporting verbosity in logs

plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystemStats.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/S3SelectLineRecordReader.java
```markdown
* Improve resilience of insert queries. ({issue}`issuenumber`)
```
=> Retry initiateMultipartUpload

docs/src/main/sphinx/connector/iceberg.rst, plugin/trino-iceberg/pom.xml, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/IcebergCatalogModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/IcebergRestCatalogConfig.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/IcebergRestCatalogModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/NoneSecurityModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/NoneSecurityProperties.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/OAuth2SecurityConfig.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/OAuth2SecurityModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/OAuth2SecurityProperties.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/SecurityProperties.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/RestCatalogTestUtils.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConfig.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestOAuth2SecurityConfig.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalogConnectorTest.java, plugin/trino-iceberg/src/test/java/org/apache/iceberg/rest/DelegatingRestSessionCatalog.java, pom.xml, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergRest.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteIceberg.java, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-rest/iceberg.properties, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-rest/spark-defaults.conf, testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
This PR adds and the REST Catalog implementation for Iceberg.
New Feature / Improvement
Connector:  Iceberg
This allows Trino to access any data source that supports the Iceberg REST Catalog spec.
() Release notes entries required with the following suggested text:
```markdown …
```
=> Add Iceberg RESTSessionCatalog Implementation

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/RollbackToSnapshotProcedure.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java
Fixes https://github.com/trinodb/trino/issues/15399
Check procedure argument for NULL in RollbackToSnapshotProcedure to prevent NPE
=> Check procedure argument for NULL in RollbackToSnapshotProcedure

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
=> Simplify cache constructor

plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java, plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClientModule.java, plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftConfig.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConfig.java
```markdown
* Implement full type mapping, which can be disable with the `redshift.use-legacy-type-mapping` configuration property ({issue}`15365`)
```
=> Add config property to disable new Redshift type mappings

core/trino-spi/src/main/java/io/trino/spi/connector/CatalogHandle.java
=> Add missing CatalogVersion INSTANCE_SIZE constant

lib/trino-parquet/src/main/java/io/trino/parquet/AbstractParquetDataSource.java, lib/trino-parquet/src/main/java/io/trino/parquet/DiskRange.java, lib/trino-parquet/src/main/java/io/trino/parquet/ParquetDataSource.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/ChunkedInputStream.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/PageReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetColumnChunkIterator.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/PrimitiveColumnReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/TrinoColumnIndexStore.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FlatColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/AbstractColumnReaderBenchmark.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestChunkedInputStream.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestInt96Timestamp.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestPageReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetDataSource.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestingChunkReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestingParquetDataSource.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/flat/TestFlatColumnReader.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetReaderConfig.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkippingWithOptimizedReader.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetDataSource.java
Currently, `ParquetReader` will read the entire row group at once. This means that:
* `limit N` queries will take longer time than needed because the reader might read hundreds of megabytes before returning a few rows.
* Reader might allocate and read hundreds of megabytes at once. This is problematic because:
* memory accounting for the reader happens after data is already read and arrays are created. This can lead to OOM and general system instability (e.g. GC) because such allocations will not be accounted for
* peak memory usage is higher than needed (e.g. GBs vs MBs)
The issue can especially be seen when Parquet row group size is large.
This PR fixes this by reading parquet column chunks in small (8MB by default) pieces.
* fixes https://github.com/trinodb/trino/issues/5729
( ) This …
=> Read parquet column chunks in small steps

testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Fix the behavior validation in BaseConnectorTest#testCreateTableAsSelect, should check wether the connector has `SUPPORTS_CREATE_TABLE_WITH_DATA` instead. After this fix, this method would be the first test method that check the CTAS, remove the CTAS behavior check in the BaseConnector#testCreateTableAsSelectNegativeDate.
https://trinodb.slack.com/archives/CP1MUNEUX/p1671771959129119
=> Fix the behavior validation for CTAS test

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergAvroDataConversion.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergInputInfo.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergOrcFileWriter.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergParquetColumnIOConverter.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
Use pattern matching for `instanceof` in iceberg connector
Pattern matching for `instanceof` introduced in Java 16 (https://openjdk.org/jeps/394)
**Motivation** (copied from https://openjdk.org/jeps/394)
Nearly every program includes some sort of logic that combines testing if an expression has a certain type or structure, and then conditionally extracting components of its state for further processing. For example, all Java programmers are familiar with the instanceof-and-cast idiom:
```
if (obj instanceof String) {
String s = (String) obj;    // grr...
...
}
```
There are three things going on here: a test (is obj a String?), a conversion (casting obj to String), and the declaration of a new local variable (s) so that we can use the string value. This pattern is straightforward and …
=> Use pattern matching for instanceof in iceberg connector

core/trino-main/src/main/java/io/trino/connector/system/KillQueryProcedure.java, docs/src/main/sphinx/connector/system.rst, plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/CreateEmptyPartitionProcedure.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/DropStatsProcedure.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/RegisterPartitionProcedure.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/SyncPartitionMetadataProcedure.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/UnregisterPartitionProcedure.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestSyncPartitionMetadata.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAbfsSyncPartitionMetadata.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHdfsSyncPartitionMetadata.java, testing/trino-tests/src/test/java/io/trino/connector/system/runtime/TestKillQuery.java
Add procedure argument check for NULL value. Added test cases for respective procedure class.
=> Add procedure argument check for NULL value

core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddLocalExchanges.java, core/trino-main/src/test/java/io/trino/connector/MockConnector.java, core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddLocalExchangesForTaskScaleWriters.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePreferredPartitioning.java
After this change (https://github.com/trinodb/trino/pull/14718) we can always use preferred partitioning for local exchange which is more reliable in terms of memory usage.
```markdown
```
=> Always use preferred partitioning for local exchanges

docs/src/main/sphinx/installation/kubernetes.rst
Fixing small typos in the documentation of the Trino Kubernetes install with Helm, as well as a wrong Kubernetes label in the query example
Simply a docs-related PR which I noticed while deploying Trino in my Kubernetes cluster
```markdown
```
=> Fix typos in Trino Kubernetes install docs

core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
The `assertFormattedSql` assertion was invoked twice in one of the createPlan methods.
```markdown
```
=> Remove redundant testing code in LocalQueryRunner

testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveMerge.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Before this commit, TestHiveTransactionalTable.verifySelectForTrinoAndHive accepted separate string arguments for the SELECT portion of the query and the WHERE clause.  In practice this convention was confusing.
This commit removes the extra argument to verifySelectForTrinoAndHive specifying the WHERE clause, updating the SELECT strings to include the WHERE clause.
```markdown
```
=> Improve Hive test verify method

docs/README.md
#15018 adjusted our docs to address the issue of "a/an SQL" in this way, and we should formalize that approach so it's clear for future contributors and docs writers.
N/A
=> Add note to docs README on use of a/an SQL

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Do not pass default properties to CTAS access control check
This is follow-up https://github.com/trinodb/trino/pull/15202 where CTAS
was omitted by mistake.
=> Do not pass default properties to CTAS access control check

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java, plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/BaseKuduConnectorSmokeTest.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/delta/TestDeltaFaultTolerantExecutionTest.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionTest.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/iceberg/TestIcebergFaultTolerantExecutionTest.java, testing/trino-testing/src/main/java/io/trino/testing/sql/TestTable.java
Remove deprecated randomTableSuffix use randomNameSuffix instead
=> Remove deprecated randomTableSuffix use randomNameSuffix instead

core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java
There is no assumption that `TRUE_LITERAL` and `FALSE_LITERAL` are the only instances of the `BooleanLiteral` class.
=> Compare with true literal appropriately

lib/trino-parquet/src/main/java/io/trino/parquet/AbstractParquetDataSource.java, lib/trino-parquet/src/main/java/io/trino/parquet/ParquetDataSource.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/ChunkedInputStream.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/TrinoColumnIndexStore.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestChunkedInputStream.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetDataSource.java
Avoid reading data in parquet ChunkedInputStream constructor
Fixes a perf regression in lazy reading of data from https://github.com/trinodb/trino/pull/15374
```markdown
* Fixes a bug which could lead to more data than necessary getting read from parquet files for queries with filters. ({issue}`15552`)
```
=> Avoid reading data in parquet ChunkedInputStream constructor

plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/S3SelectLineRecordReader.java
Follow up of https://github.com/trinodb/trino/pull/15476
NO RELEASE NOTES
=> Abort AWS operation retry in AbortedException

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveCreateSchemaInternalRetry.java
HiveMetadata used SemiTransactionalHiveMetastore which delays method executions until commit is invoked.
Due to that catching SchemaAlreadyExistsException in HiveMetadata::createSchema was not enough as exception was not thrown there.
Proposed solution moves schema already exists error handling to SemiTransactionalHiveMetastore class.
Fixes #15174
```markdown
* Fix incorrect `schema already exists` error caused by a client timeout when
creating a new schema. ({issue}`15174`)
```
=> Move handling of internal retry error when schema already exist for Hive

lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/PageReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BinaryBuffer.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BinaryColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BooleanColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ByteColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/DictionaryDecoder.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FlatColumnReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/Int128ColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/Int96ColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/IntColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/LongColumnAdapter.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ShortColumnAdapter.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/AbstractColumnReaderBenchmark.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnReaderFactory.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestInt96Timestamp.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetReaderMemoryUsage.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/flat/TestFlatColumnReader.java
Added accounting of memory usage to batched column readers.
This takes into account the dictionary retained for decoding
dictionary data pages and the extra memory usage of decompressed
values from data pages.
Fixes https://github.com/trinodb/trino/issues/10061
```markdown
* Improve accounting of memory usage by parquet reader. ({issue}`15554`)
```
=> Account for memory usage of parquet column readers

lib/trino-parquet/src/main/java/io/trino/parquet/ParquetReaderUtils.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/IntBitUnpacker.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/IntBitUnpackers.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/RleBitPackingHybridDecoder.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/DictionaryDecoder.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkReadFixedWidthInt.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestData.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetReaderUtils.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetReaderUtilsBenchmarks.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/ApacheParquetIntUnpacker.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/BenchmarkRleBitPackingDecoder.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestBitUnpackers.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestRleBitPackingDecoderBenchmark.java
```
Benchmark                      (bitWidth)               (dataSet)   Mode Cnt  parquet-mr decoder  optimized decoder
BenchmarkRleBitPackingDecoder           1                  RANDOM  thrpt  10  48.439 ± 10.260     329.209 ± 21.345  ops/s
BenchmarkRleBitPackingDecoder           1  MIXED_AND_GROUPS_SMALL  thrpt  10  43.804 ±  3.277     135.929 ±  2.441  ops/s
BenchmarkRleBitPackingDecoder           1  MIXED_AND_GROUPS_LARGE  thrpt  10  54.062 ± 12.215     319.990 ±  8.851  ops/s
BenchmarkRleBitPackingDecoder           1   MIXED_AND_GROUPS_HUGE  thrpt  10  62.038 ±  5.931     554.925 ± 83.815  ops/s
BenchmarkRleBitPackingDecoder           3                  RANDOM  thrpt  10  47.090 ±  2.948     379.213 ± 26.552  ops/s
BenchmarkRleBitPackingDecoder           3  MIXED_AND_GROUPS_SMALL …
```
=> Implement optimized decoder for RLE encoding in parquet

.github/workflows/ci.yml, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteCompatibility.java, testing/trino-test-jdbc-compatibility-old-driver/bin/run_tests.sh, testing/trino-test-jdbc-compatibility-old-server/src/test/java/io/trino/TestJdbcResultSetCompatibilityOldServer.java
This version has not been released.  Currently (when working on 406 SNAPSHOT) the ci does not failV, because we test with some granularity, and 404 isn't getting picked up for the test, but would fail after a release or two.
=> Skip 404 in Trino compatibility tests

plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/rcfile/RcFilePageSourceFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/InternalHiveSplitFactory.java
The `schema` field can grow quite large as it includes the full set of table and serde properties as well as columns, types and many other things. Storing, serializing and transferring it can be quite costly. Luckily it is possible to avoid it for the natively supported formats.
https://github.com/trinodb/trino/issues/15511
```markdown
```
=> Reduce HiveSplit size for ORC, Parquet and RCFile tables

core/trino-main/src/main/java/io/trino/security/GroupProviderManager.java, core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java, core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java, core/trino-main/src/main/java/io/trino/testing/QueryRunner.java, core/trino-main/src/main/java/io/trino/testing/TestingGroupProviderManager.java, plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/ThriftQueryRunner.java, testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java, testing/trino-testing/src/main/java/io/trino/testing/StandaloneQueryRunner.java, testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
=> Allow setting group provider in tests

core/trino-parser/src/main/java/io/trino/sql/tree/QueryPeriod.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Fix failure when the subquery contains time travel. 
I added a test to only Iceberg because tests in the planner fails early due to unsupported time travel in tpch connector. 
```markdown
* Fix failure when a subquery contains time travel. ({issue}`15607`)
```
=> Fix failure when subquery contains time travel

core/trino-main/src/main/java/io/trino/operator/DynamicFilterSourceOperator.java, testing/trino-testing/src/main/java/io/trino/testing/AbstractTestJoinQueries.java
In FTE for a query shape like below, DynamicFilterSourceFactory may need to be duplicated by LocalExecutionPlanner#addLookupOuterDrivers
```
RightJoin[criteria = ("orderkey" = "orderkey_0"), hash = [$hashvalue, $hashvalue_17], distribution = PARTITIONED]
│   Layout: [orderkey:bigint]
│   Distribution: PARTITIONED
├─ RemoteSource[sourceFragmentIds = [1]]
│      Layout: [orderkey:bigint, $hashvalue:bigint]
└─ LocalExchange[partitioning = HASH, hashColumn = [$hashvalue_17], arguments = ["orderkey_0"]]
│   Layout: [orderkey_0:bigint, $hashvalue_17:bigint]
└─ RemoteSource[sourceFragmentIds = [2]]
Layout: [orderkey_0:bigint, $hashvalue_18:bigint]
Fragment 2 [HASH]
Output layout: [orderkey_0, $hashvalue_24]
Output partitioning: HASH [orderkey_0][$hashvalue_24] …
```
=> Fix query failure for outer join with DFs in fault tolerant execution

docs/src/main/sphinx/connector/hive.rst, lib/trino-parquet/src/main/java/io/trino/parquet/BloomFilterStore.java, lib/trino-parquet/src/main/java/io/trino/parquet/ParquetReaderOptions.java, lib/trino-parquet/src/main/java/io/trino/parquet/predicate/PredicateUtils.java, lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/MetadataReader.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSinkProvider.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeUpdatablePageSource.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TableSnapshot.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTableSnapshot.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointEntryIterator.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointWriter.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/statistics/TestDeltaLakeFileStatistics.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetReaderConfig.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveTestUtils.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestBloomFilterStore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetReaderConfig.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestHiveBucketing.java, plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSourceProvider.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveSparkCompatibility.java
Enable hive connector to read parquet file's bloomfilter statistics. Related RB: https://github.com/apache/parquet-mr/commit/806037c080dc477798d157cd4a54a81240a85d37#diff-8da24c84aef62e6e836d073938f7843d289785baaeddf446f3afeae6d4ef4b10.
This feature can be controlled via hive config: "parquet.use-bloom-filter"
Implementation limitations:
1. Limited types supported: Will add more trino types once this merged in.
2. Only support Hive connector. hudi, delta-lake and iceberg can be supported after this merged in.
Enable hive connector to read parquet file's bloomfilter statistics. For more details: https://github.com/apache/parquet-format/blob/master/BloomFilter.md. 
( ) Release notes are required, please propose a …
=> Enable reading Parquet's bloomfilter statistics for hive connector

core/trino-main/src/main/java/io/trino/execution/scheduler/BinPackingNodeAllocatorService.java, core/trino-main/src/main/java/io/trino/execution/scheduler/ErrorCodes.java, core/trino-main/src/main/java/io/trino/memory/MemoryManagerConfig.java, core/trino-main/src/test/java/io/trino/execution/scheduler/TestBinPackingNodeAllocator.java, core/trino-main/src/test/java/io/trino/execution/scheduler/TestExponentialGrowthPartitionMemoryEstimator.java, core/trino-main/src/test/java/io/trino/memory/TestMemoryManagerConfig.java
When a task fails due to a suspected worker crash this may indicate (with a high likelihood) a potential memory accounting problem. Increasing memory requirement would essentially decrease overall cluster load allowing those problematic tasks to finish with a higher chance.
When a task fails due to a suspected worker crash this may indicate
(with a high likelihood) a potential memory accounting problem.
Increasing memory requirement would essentially decrease overall cluster
load allowing those problematic tasks to finish with a higher chance.
```markdown …
```
=> Increase memory requirement for tasks failed due to worker crash

pom.xml
To exclude the possibility of GCLocker and PreventiveGC related issues
https://github.com/trinodb/trino/issues/15293
```markdown
```
=> Adjust GC related settings for tests

lib/trino-orc/src/test/java/io/trino/orc/OrcTester.java, lib/trino-orc/src/test/java/io/trino/orc/TestCachingOrcDataSource.java, lib/trino-orc/src/test/java/io/trino/orc/TestOrcLz4.java
Add test ORC multi column data generator.
Fixes: #15420
=> Add test ORC multi column data generator.

docs/src/main/sphinx/admin/properties-http-client.rst
Fix redundant backquote from HTTP client documentation
=> Fix redundant backquote from HTTP client documentation

core/trino-main/src/main/java/io/trino/operator/window/matcher/Matcher.java, core/trino-main/src/test/java/io/trino/sql/query/TestRowPatternMatching.java
Before this change, killing threads in the Matcher was incorrectly implemented. When a thread was killed, it still persisted in the `threadsAtInstructions` structure. However, all other thread's data was cleared, so accessing the thread caused failure.
The simplest solution would be to remove the thread from the `threadsAtInstructions` structure while killing the thread. However, that would be a costly operation, because there might be multiple entries for the thread across the structure. Additionally, by removing the thread eagerly, we would miss the opportunity to early kill other threads, equivalent to the removed thread.
The chosen solution is to delay killing threads until the end of the iteration of the main loop of the matching algorithm. Instead of killed, the invalidated threads …
=> Fix killing threads in Matcher

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
There was a return missing. This case is hard to test, since both Trino & Spark create an initial empty snapshot, when creating a table.
=> Fix failure when analyzing table with no snapshots

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeParquetStatisticsUtils.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
Fixes #15496
```markdown
* Fix failure when converting JSON statistics to Parquet format. ({issue}`15496`)
```
=> Fix failure when converting json stats to parquet in Delta Lake

core/trino-main/src/main/java/io/trino/cost/ScalarStatsCalculator.java, core/trino-main/src/test/java/io/trino/cost/TestScalarStatsCalculator.java
In visitArithmeticBinary we can set the high and low value to NaN for unknown input stats. 
This gets treated as an empty range by SymbolStatsEstimate constructor with 1.0 nullsFraction. 
This can result in 0 row count estimate with a filter that selects non-null values.
Fixes https://github.com/trinodb/trino/issues/15605
```markdown
* Fix planner estimates for queries with filters on columns without statistics. ({issue}`15642`)
```
=> Fix handling of unknown stats in ScalarStatsCalculator

core/trino-main/src/main/java/io/trino/cost/TopNStatsRule.java, core/trino-main/src/test/java/io/trino/cost/TestTopNStatsRule.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestShowStats.java
Provide estimates for partial and final topN in TopNStatsRule
https://trinodb.slack.com/archives/C0305TQ05KL/p1671020850646689?thread_ts=1669977747.493179&cid=C0305TQ05KL
```markdown
* Improve planner estimates for queries containing outer joins over a topN operation. ({issue}`15428`)
```
=> Provide estimates for partial and final topN in TopNStatsRule

core/trino-main/src/main/java/io/trino/execution/StageStateMachine.java, core/trino-main/src/main/java/io/trino/operator/PipelineContext.java
In `PipelineContext`, changes provide estimated keys and list sizes for the operator stats `ArrayListMultimap` when producing `PipelineStats`. Also avoids a per-key `TreeMap` traversal when combining existing operator stats with running operator stats by using `TreeMap#compute` instead of `get` / `put` pairs.
In `StageStateMachine`, merge `OperatorStats` in a single batch across all tasks instead of performing operator by operator merging when producing `StageStats`.
=> Minor PipelineStats performance improvement

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Fixes https://github.com/trinodb/trino/issues/15583
```markdown
* Fix query failure when column masking or row filter involves columns. ({issue}`15583`)
```
=> Propagate group information when analyzing row filter and column masks

core/trino-main/src/main/java/io/trino/operator/scalar/ArrayFilterFunction.java, core/trino-main/src/test/java/io/trino/sql/planner/TestDeterminismEvaluator.java
Mark `filter()` function as deterministic function to enable more optimization opportunities such as predicate pushdown through projection.
Fixes [#15604 ](https://github.com/trinodb/trino/issues/15604)
(O) Release notes are required, with the following suggested text: Mark `filter()` function as deterministic function to enable more optimization opportunities such as predicate pushdown through projection
=> Mark filter() function as deterministic

core/trino-main/src/main/java/io/trino/security/InjectedConnectorAccessControl.java, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorAccessControl.java, core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingConnectorAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/LegacyAccessControl.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
Retaining the deprecated method was not sufficient for maintaining compatibility, because the new method did not delegate to the old one. Thus, if an implementor kept implementing only the old method, the CREATE SCHEMA would get denied, irrespective of the implemented logic. Removing the deprecated method makes the incompatibility clearer, as it fails at the compilation time.
Follows https://github.com/trinodb/trino/pull/15153#discussion_r1062617378
=> Remove deprecated checkCanCreateSchema

core/trino-main/src/main/java/io/trino/execution/scheduler/FaultTolerantPartitioningScheme.java, core/trino-main/src/main/java/io/trino/execution/scheduler/FaultTolerantPartitioningSchemeFactory.java, core/trino-main/src/main/java/io/trino/sql/planner/MergePartitioningHandle.java, core/trino-main/src/main/java/io/trino/sql/planner/NodePartitioningManager.java
Do not limit the number of tasks (partitions) by the number of nodes available in the cluster
This PR still limits the number of processing tasks by the number of configured partitions, however in certain cases it may not be necessary. This is left as a future improvement.
```markdown
```
=> Increase number of partitions for bucketed processing in FTE

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
When performing `rollback_to_snapshot` procedure calls with the latest snapshot of the table as parameter, the operation used to fail in Trino `403` while it depended on Iceberg `1.0.0`:
```
Caused by: java.lang.IllegalStateException: Cannot commit transaction: last operation has not committed
at org.apache.iceberg.relocated.com.google.common.base.Preconditions.checkState(Preconditions.java:502)
at org.apache.iceberg.BaseTransaction.commitTransaction(BaseTransaction.java:252)
at org.apache.iceberg.SnapshotManager.commit(SnapshotManager.java:158)
at io.trino.plugin.iceberg.RollbackToSnapshotProcedure.rollbackToSnapshot(RollbackToSnapshotProcedure.java:80)
````
With Iceberg `1.1.0` the problem was fixed in  https://github.com/apache/iceberg/pull/5536 .
This extra check is a regression test …
=> Check `rollback_to_snapshot` accuracy when it does not do any changes

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
Fix inconsistent `pageSinkId` column naming causing problems with case-sensitive databases where lower case is not the default.
Example: `EXPLAIN ANALYZE` would fail due to unrecognised column name (only on source systems where uppercase is the default, like Snowflake).
```json
INSERT INTO "TMP_SEP_CICD_TEST_MHPT0EER6T"."TEST_SCHEMA_2"."TMP_TRINO_D4C971E39EE3431C86C9E2515A8D059F" ("NATIONKEY", "NAME", "REGIONKEY", "COMMENT", "trino_page_sink_id") VALUES (?,?,?,?, ?)
```
```markdown
```
=> Fix inconsistent pageSinkId column naming

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/logging/FormatBasedRemoteQueryModifier.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/logging/TestFormatBasedRemoteQueryModifier.java
Previously only letters, digits and underscores are considered as a valid values for source and trace token to be tracked in query comment for jdbc based connectors. This PR adds hyphen to the list of valid values.  
https://github.com/trinodb/trino/pull/14500
```markdown
```
=> Allow hyphen as a valid value for sanitization checks

docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Updating FTE docs to add HDFS as exchange manager type and for spooling. Added details about configs needed to configure HDFS exchange manager.
Refer [PR](https://github.com/trinodb/trino/pull/15160) for relevant code changes.
=> Update FTE docs to add HDFS as exchange type

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/logging/FormatBasedRemoteQueryModifier.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/logging/TestFormatBasedRemoteQueryModifier.java
Previously the sanitization checks were applied for source and trace token even if they are not specified in the `query.comment-format` - now we are applying them if configured.
https://github.com/trinodb/trino/pull/15691
https://github.com/trinodb/trino/pull/14500
```markdown
```
=> Apply sanitization checks only for entity specified in comment-format

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/type/ShortTimestampEncoder.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/type/TrinoTimestampEncoderFactory.java
The current TimestampEncoders performs some operations with overflow.  I do not know if this this problem is visible in the current code base, but it makes using the encoder library error prone.
```markdown
```
=> Use exact math for timestamp calculations

lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java, lib/trino-parquet/src/test/java/io/trino/parquet/TestTupleDomainParquetPredicate.java
Nulls count may be absent for the column index in the file.
This case is now handled instead of failing the query.
E.g. failure
```
io.trino.spi.TrinoException: Corrupted statistics for column "name" in Parquet file "data.parquet". Corrupted column index: [Boudary order: UNORDERED
null count  min                                       max                                     
page-0                    <none>                                                                                    
page-1                    <none>  @colors/colors                            zlib-devel                              
page-2                    <none>  iconv-lite                                range-parser                            
page-3                    <none>  adduser …
```
=> Fix reading parquet column indexes without nulls count

lib/trino-orc/src/main/java/io/trino/orc/reader/FloatColumnReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/FloatColumnReader.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Fixes #15650
```markdown
* Fix failure when reading columns whose type was changed from `float` to `double` by other query engines. ({issue}`15650`)
```
=> Support reading float as double in ORC and Parquet for Iceberg type change

plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoQueryRunner.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoCaseInsensitiveMapping.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
Extract case insensitive name mapping test in MongoDB
=> Extract case insensitive name mapping test in MongoDB

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
Trino now requires a minimum of JDK 17 to run and this is verified in TrinoSystemRequirements already.
=> Remove obsolete check in BigQuery connector

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java, core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
During analysis, a table function declares required input columns by choosing indexes from visible columns list.
Before this change, the function got columns with those indexes from the input relation type. It was not correct, because the hidden input columns were not taken into account. After this change, the required column indexes are remapped to skip hidden columns.
Table arguments are not yet supported.
=> Fix incorrect input columns passed to table function

core/trino-main/src/main/java/io/trino/operator/WorkProcessorUtils.java, core/trino-main/src/test/java/io/trino/operator/TestWorkProcessor.java
A common patter across operators is calling WorkProcessor#blocking to report memory usage:
.blocking(() -> memoryContext.setBytes(localAggregatedMemoryContext.getBytes()));
However, before this change lambda wasn't called when upstream processor yielded or was blocked.
This change makes lambda to be always called which makes reporting of operator memory usage more accurate.
Fixes https://github.com/trinodb/trino/issues/15679
```markdown
* Make table scan memory usage reporting more accurate. ({issue}`issuenumber`)
```
=> Make WorkProcessor#blocking always execute futureSupplier

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoCaseInsensitiveMapping.java
Fixes #15716
```markdown
* Fix bug when dropping schemas and `mongodb.case-insensitive-name-matching` is enabled.
Previously, the statement succeeded, but the schema wasn't dropped. ({issue}`15716`)
```
=> Fix case insensitive matching when dropping MongoDB schema 

.github/actions/compile-commit/action.yml
Maven repositories communication (e.g. downloading dependencies from
Maven Central) has been observed to be unreliable and requires retries.
=> Retry maven when building individual commits

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Improve the error message while dropping the partitioned column **or** support dropping the partitioned column.
```sql
CREATE TABLE test (id INTEGER, name VARCHAR) WITH (partitioning = ARRAY['id', 'truncate(name, 5)']);
ALTER TABLE test DROP COLUMN id;
-- Failed to drop column: Cannot find source column for partition field: 1000: id: identity(1
ALTER TABLE test DROP COLUMN name;
-- Failed to drop column: Cannot find source column for partition field: 1001: name_trunc: truncate[5](2)
```
=> Improve error message when trying to drop partitioned columns in Iceberg

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Fixes #15723
Both `floatValue` & `doubleValue` methods in Jackson JsonNode class methods return 0.0 for non-number nodes.
`SqlJsonLiteralConverter` also calls those methods, but `NaN` value was handled as `JsonNodeType.STRING` and it returns the expected value (`TestSqlJsonLiteralConverter` already ensures the value).  
```markdown
* Fix incorrect results when reading or writing `NaN` with `real` or `double` types on partitioned columns. ({issue}`15723`)
```
=> Fix wrong handling for NaN on partitioned columns in Iceberg

lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/TransformingValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestingColumnReader.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/AbstractTestParquetReader.java
Support reading FLOAT as a double in batched parquet reader
Follow-up on https://github.com/trinodb/trino/pull/15681
=> Support reading FLOAT as a double in batched parquet reader

.github/actions/compile-commit/action.yml
This fixes the issue introduced in
bc4e1afb3e8bd9dc4b58c0f24d93d3b00f155f95.
This fixes broken CI.
=> Fix assignment of environment variable in compile-commit action

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java, plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java, plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOraclePoolRemarksReportingConnectorSmokeTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Quote column name when setting column comment in BigQuery. 
=> Quote column name when setting column comment in BigQuery

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalogConnectorTest.java
For easier auditing and debugging, Trino should persist the query ID into each Iceberg [snapshot's summary.](https://iceberg.apache.org/spec/#snapshots) This would allow tracing back each table update (inserts, deletes, etc.) to a specific query ID in case we need to track down issues or ascertain that table updates are executed by those with proper permissions, etc. 
Note: This additional metadata is not added for those operations which do not produce a new snapshot, such as schema/spec evolution, property updates or analyze statements. 
Thanks @kbendick for kicking this off!
Fixes https://github.com/trinodb/trino/issues/11292
Earlier PR (closed): https://github.com/trinodb/trino/pull/11298 …
=> Persist the Trino query ID into the snapshot summary

.github/actions/compile-commit/action.yml
It's not uncommon that checkstyle fixups are associated with not the right commit. A person reviewing commit-by-commit may notice them, and face the dilemma whether to comment on the nit, or ignore. Have the CI check alleviate the dilemma, by preventing such situations.
=> Check each commit code style

core/trino-main/src/main/java/io/trino/operator/scalar/DateTimeFunctions.java, core/trino-main/src/main/java/io/trino/type/DateOperators.java, core/trino-main/src/main/java/io/trino/util/DateTimeUtils.java, core/trino-main/src/test/java/io/trino/util/BenchmarkParseDate.java, core/trino-main/src/test/java/io/trino/util/TestDateTimeUtils.java
Optimize the performance of date parsing if the date is in standard format (yyyy-MM-dd).
The following functions are impacted:
```
date(str)
cast(str as date)
date_parse(str, '%Y-%m-%D')
```
After:
Benchmark                      Mode  Cnt    Score    Error   Units
BenchmarkParseDate.parseDate  thrpt   10  762.769 ± 35.198  ops/ms
Before:
Benchmark                      Mode  Cnt   Score   Error   Units
BenchmarkParseDate.parseDate  thrpt   10  48.887 ± 3.222  ops/ms
```markdown
* Fix some things. ({issue}`15229`)
```
=> Optimize date parsing for format yyyy-MM-dd

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcFailureRecoveryTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaFailureRecoveryTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveFailureRecoveryTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergFailureRecoveryTest.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoFailureRecoveryTest.java, testing/trino-testing-services/src/main/java/io/trino/testng/services/Listeners.java, testing/trino-testing-services/src/main/java/io/trino/testng/services/LogTestDurationListener.java, testing/trino-testing-services/src/main/java/io/trino/testng/services/ProgressLoggingListener.java, testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java, testing/trino-testing/src/main/java/io/trino/testing/ExtendedFailureRecoveryTest.java
This parallelizes the test methods for all FailureRecovery tests. As far as @arhimondr and I could tell, the only other way to do this is using the TestNG XML descriptor, designating the class with `parallel="methods"`, but since we do not use that XML descriptor, this appears to be the only available option. These tests can take upwards of 20, 30, even 50 minutes for some connectors. This suite of tests benefitted greatly from parallelism.
The primary goal here is to speed up FailureRecoveryTests, improving the iteration cycle time, and preventing CI timeouts. I observed a roughly 40-50% improvement (depending on the connector) with this change.
( ) Release notes are required, please propose a release note for …
=> Add parallelism to FailureRecovery tests

client/trino-client/src/main/java/io/trino/client/JsonResponse.java, client/trino-client/src/main/java/io/trino/client/StatementClientV1.java, core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
All versions of Trino (since c0bcc9bbcde2d4850ddf81ca962b5d7c16b1e109) send the error message in the response body. The reason phrase does not exist in HTTP/2.
```markdown
* Improve authentication error messages when accessing the server over HTTP/2. ({issue}`15720`)
* Improve authentication error messages when accessing the server over HTTP/2. ({issue}`15720`)
```
=> Use authentication error message from response body

core/trino-main/src/main/java/io/trino/security/AccessControl.java, core/trino-main/src/main/java/io/trino/security/AccessControlManager.java, core/trino-main/src/main/java/io/trino/security/ForwardingAccessControl.java, core/trino-main/src/main/java/io/trino/security/InjectedConnectorAccessControl.java, core/trino-main/src/main/java/io/trino/security/ViewAccessControl.java, core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java, core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java, core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java, core/trino-main/src/test/java/io/trino/connector/MockConnectorAccessControl.java, core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java, core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java, core/trino-spi/pom.xml, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorAccessControl.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/ColumnInfo.java, core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingConnectorAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java, lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedConnectorAccessControlTest.java, lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedSystemAccessControlTest.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/LegacyAccessControl.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java, testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
Fix aliasing of fields in mask expressions
This causes two problems:
* Masks can inadvertently refer to columns that appear earlier
in the list of columns as the projection is planned. This
causes the mask expression to see the masked value of other columns
instead of the underlying value
* A possible bug in other optimizers causes mask expressions to be
lost when the result of a such an expression is of type ROW
and there's a dereference of a field downstream
Fixes #15659
Relates to #14420
```markdown
* TBD
```
=> Fix issues due to mask aliasing

docs/src/main/sphinx/connector/atop.rst, docs/src/main/sphinx/connector/googlesheets.rst, docs/src/main/sphinx/connector/thrift.rst, docs/src/main/sphinx/connector/tpcds.rst, docs/src/main/sphinx/connector/tpch.rst
Clarifies example names in connector docs for the TPCH, TPCDS, Thrift, Google Sheets, and Atop connectors. 
Continuation of: https://github.com/trinodb/trino/pull/13964
Other connector PRs:
* [Acumulo, BigQuery, Black Hole, Cassandra, Clickhouse](https://github.com/trinodb/trino/pull/15494)
* [Delta Lake, Druid, Elastisearch, Hudi, Iceberg ](https://github.com/trinodb/trino/pull/15530)
* [JMX, Kafka, Kinesis, Kudu, Local File](https://github.com/trinodb/trino/pull/15597)
* [MariaDB, Memory, MongoDB, MYSQL, Oracle, Phoenix, Pinot](https://github.com/trinodb/trino/pull/15599)
* [PostgreSQL, Prometheus, Redis, Redshift, Singlestore, SQLServer](https://github.com/trinodb/trino/pull/15600) …
=> Update docs for connector catalog examples-1

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSource.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveCoercionPolicy.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestReadUniontype.java
Allow Coercion between hive Union and hive struct, at LinkedIn we have the need to declare the table schema as struct and reading some partitions in union definition. 
Since Trino internally treat union as struct, this PR allows coercions between struct and union(after union get converted to Struct)
Related PR:
https://github.com/trinodb/trino/pull/3483
https://github.com/trinodb/trino/commit/e071da402efb4b95f6c8b13b2a241e86e446e2a8
Allow Coercion between hive Union and hive  struct
```markdown
*Allow Coercion between Union and Struct typed columns.
```
=> Allow Coercion between hive Union and hive  struct for Hive ORC table

.github/workflows/ci.yml, core/trino-main/src/main/java/io/trino/dispatcher/DecoratingListeningExecutorService.java, core/trino-main/src/test/java/io/trino/sql/planner/TestUnwrapCastInComparison.java, core/trino-main/src/test/java/io/trino/type/TestArrayOperators.java, core/trino-main/src/test/java/io/trino/type/TestDecimalCasts.java, core/trino-main/src/test/java/io/trino/type/TestMapOperators.java, testing/trino-testing-services/src/main/java/io/trino/testng/services/ManageTestResources.java
In order to future-proof us for Java update, run selected tests (`trino-main`) with JDK 19 too.
=> Run selected tests with Java 19

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
UDPATE/DELETE on Hive ACID transactional tables when using the non-MERGE
implementation can lead to correctness issues as shown by the tests
added to TestHiveTransactionalTable.
To prevent these issues we now disallow UPDATE/DELETE on Hive ACID
tables when using the legacy implementation (by setting
`deprecated.legacy-update-delete-implementation` to true).
This adds test coverage and fix for https://github.com/trinodb/trino/issues/12731
```markdown
* Disallow UPDATE/DELETE on Hive ACID transactional tables to prevent correctness
issues when `deprecated.legacy-update-delete-implementation` is set to true.
```
=> Disallow legacy UPDATE/DELETE on Hive ACID tables

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
1. We use test timeouts as a safety measure only for tests that involve explicit concurrently. We do not use them in regular tests.
2. Connector tests are run against various different connectors, so different systems. Some connectors/systems are slower than others, so a timeout value may or may not be appropriate for them.
=> Remove test timeouts from connector tests

core/trino-main/src/main/java/io/trino/operator/PagesIndex.java, core/trino-main/src/main/java/io/trino/operator/join/ArrayPositionLinks.java, core/trino-main/src/main/java/io/trino/operator/join/BigintPagesHash.java, core/trino-main/src/main/java/io/trino/operator/join/DefaultPagesHash.java, core/trino-main/src/main/java/io/trino/operator/join/JoinHash.java, core/trino-main/src/main/java/io/trino/operator/join/JoinHashSupplier.java, core/trino-main/src/main/java/io/trino/operator/join/JoinUtils.java, core/trino-main/src/main/java/io/trino/operator/join/SortedPositionLinks.java, core/trino-main/src/main/java/io/trino/operator/join/unspilled/HashBuilderOperator.java, core/trino-main/src/main/java/io/trino/operator/project/PageProcessor.java, core/trino-main/src/main/java/io/trino/sql/gen/JoinCompiler.java, core/trino-main/src/test/java/io/trino/operator/TestPagesIndex.java, core/trino-main/src/test/java/io/trino/operator/join/unspilled/TestHashBuilderOperator.java, core/trino-spi/src/main/java/io/trino/spi/Page.java
=> Improve join index memory accounting

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Support changing column types in Iceberg
Relates to #15515
```markdown
* Add support for changing column types. ({issue}`15515`)
```
=> Support changing column types in Iceberg

plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetRecordWriter.java, plugin/trino-hive/src/main/java/org/apache/parquet/hadoop/DisabledMemoryManager.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/ParquetTester.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetDecimalScaling.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/write/TestingMapredParquetOutputFormat.java
Disable hadoop MemoryManager in hive parquet writer
to prevent it from making decisions about resizing row groups 
based on global context about active writers and JVM max heap size.
Fixes https://github.com/trinodb/trino/issues/13633
```markdown
```
=> Disable hadoop MemoryManager in hive parquet writer

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java
Inspired from https://github.com/trinodb/trino/pull/14869#discussion_r1073208221
=> Use Failsafe to retry instead iceberg's Tasks in iceberg connector

docs/src/main/sphinx/connector/iceberg.rst, plugin/trino-iceberg/pom.xml, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/IcebergCatalogModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcCatalogModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcClient.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcConfig.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcConnectionFactory.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcTableOperations.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcTableOperationsProvider.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalogFactory.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergIcebergJdbcConfig.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestingIcebergJdbcServer.java, plugin/trino-iceberg/src/test/java/org/apache/iceberg/jdbc/TestingTrinoIcebergJdbcUtil.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergJdbcCatalog.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteIceberg.java, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-jdbc-catalog/apply-hive-config-for-iceberg.sh, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-jdbc-catalog/create-table.sql, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-jdbc-catalog/hive-site-overrides.xml, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-jdbc-catalog/iceberg.properties, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-jdbc-catalog/spark-defaults.conf, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-jdbc-catalog/tpch.properties, testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Support JDBC catalog in Iceberg connector. 
Fixes #9968
```markdown
* Add support for JDBC catalog. ({issue}`9968`)
```
=> Support JDBC catalog in Iceberg connector

core/trino-main/src/main/java/io/trino/operator/DynamicFilterSourceOperator.java, core/trino-main/src/test/java/io/trino/operator/TestDynamicFilterSourceOperator.java, testing/trino-tests/src/test/java/io/trino/execution/AbstractTestCoordinatorDynamicFiltering.java
Up to this point, when dynamic filter went beyond the threshold all channels fall back to the min/max range predicate. Now the biggest channel falls back, while the rest continue to be gathered as a set of values. This way if a single channel is too big, it won't prevent other, smaller ones to be used as a dynamic filter.
Fixes https://github.com/trinodb/trino/issues/14797
```markdown
* Improve performance of queries with selective joins. ({issue}`15569`)
```
=> Account for DF limits per channel in DynamicFilterSourceOperator

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcCatalogConfig.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcCatalogModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalogFactory.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConfig.java
Catalog config classes follow `IcebergXxxCatalogConfig` naming pattern. This also fixes test class name, was a bit off.
=> Rename Iceberg JDBC catalog config class

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/metrics/TDigestHistogram.java
TDigest#valueAt can mutate digest state,
therefore all methods that access digest
should be synchronized.
* NO RELEASE NOTES *
=> Add missing synchronization

docs/src/main/sphinx/admin/fault-tolerant-execution.rst, plugin/trino-bigquery/pom.xml, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryInsertTableHandle.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryOutputTableHandle.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPageSink.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPageSinkProvider.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryUtil.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryFailureRecoveryTest.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryQueryRunner.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryQueryFailureRecoveryTest.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryTaskFailureRecoveryTest.java
This PR introduces FTE for BigQuery.
This differs slightly from previous FTE PRs in that the FailureRecoveryTests are executed within the `-Pcloud-tests`, rather than a separate profile like the others. This _may_  cause problems by running up against the 1 hour time limit, in which case, we'll have to separate the FailureRecoveryTests from cloud-tests.
```markdown
```
=> BigQuery FTE

plugin/trino-tpcds/pom.xml, plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsConfig.java, plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsConnector.java, plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsConnectorFactory.java, plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsModule.java, plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsNodePartitioningProvider.java, plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsSessionProperties.java, plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsSplitManager.java, plugin/trino-tpcds/src/test/java/io/trino/plugin/tpcds/TestTpcdsConfig.java
Some tables (such as store_returns, store_sales) change the number of
rows based on the number of splits generated. While it is unclear
whether this is expected behavior (as the same is observed in the
reference implementation from TPC) for now it was decided to allow
specifying the number of splits explicitly to allow generating
deterministic data sets.
```markdown
```
=> Allow specifying exact desired split count in TPC-DS connector

plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTypeManager.java, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Fixes #15771
```markdown
* Fix incorrect results when Cassandra `list`, `map` and `set` types contain user defined types. ({issue}`15771`)
```
=> Fix result when complex type contains user defined type in Cassandra

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/SharedHiveMetastoreCache.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
=> Introduce CachingHiveMetastoreBuilder

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
Recent change which added FTE support broke insert flow for tables in schemas which used mixec case. This came from the fact that `schemaExists` method is used with `datasetName`, while it expects Trino schema name which is always lowercased.
The whole schemaExists check can be removed as schema existence was checked before `beginInsert` was called when table handle was resolved.
https://github.com/trinodb/trino/pull/15620 - PR which introduced a regression
Release notes should not be requried as this fixes a regression which was not released yet.
=> Fix insert into BigQuery tables

core/trino-main/src/main/java/io/trino/operator/DirectExchangeClient.java, core/trino-main/src/main/java/io/trino/operator/DirectExchangeClientStatus.java, core/trino-main/src/main/java/io/trino/operator/HttpPageBufferClient.java, core/trino-main/src/test/java/io/trino/operator/TestDirectExchangeClient.java
It adds the metric that measures distribution of requests duration sent by `HttpPageBufferClient`. It was found that it is very useful during investigation. Example of metric:
"requestDuration" : {
"@class" : "io.trino.plugin.base.metrics.TDigestHistogram",
"digest" : "AAAAAAAAAPA/AAAAAABQn0AAAAAAAABZQAAAAABgBSBBRAAAAAAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPwAAAAAAAPA/AAAAAAAA8D8AAAAAAADwPw8kWmFzIPE/AAAAAAAAAEAAAAAAAAAAQAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAQJOJjp9HYwBAflSXmLVQBkAAAAAAAAAIQAAAAAAAAAhAQRqkQRqkCUCV6nxySRMQQHwhOSXlhhNAaXLKm4AVGUCMA9mskrIhQLUSoGvY6ihA7IqcjXMJLkAKcUXV8qYzQBCGrIvLHT1ARWDCAj0zRkCxNfFQVk9RQFqY6MDxaVhAnhyE1M6oYECKjrKuk7ZoQPQShZFIWXpACO0ltJeskEAjFd6gGOKTQHbjwWniV5ZA7fWUUSR9mEDr5MHDOO2ZQP …
=> Add metric to measure requests duration of HttpPageBufferClient

docs/src/main/sphinx/connector/delta-lake.rst, docs/src/main/sphinx/connector/druid.rst, docs/src/main/sphinx/connector/elasticsearch.rst, docs/src/main/sphinx/connector/hudi.rst, docs/src/main/sphinx/connector/iceberg.rst, docs/src/main/sphinx/connector/table-redirection.fragment
Clarifies example names in connector docs for the Delta Lake, Druid, Elastisearch, Hudi, and Iceberg connectors. 
Continuation of: https://github.com/trinodb/trino/pull/13964
Other connector PRs:
* [TPCH, TPCDS, Thrift, Google Sheets, Atop](https://github.com/trinodb/trino/pull/15465)
* [Acumulo, BigQuery, Black Hole, Cassandra, Clickhouse](https://github.com/trinodb/trino/pull/15494)
* [JMX, Kafka, Kinesis, Kudu, Local File](https://github.com/trinodb/trino/pull/15597)
* [MariaDB, Memory, MongoDB, MYSQL, Oracle, Phoenix, Pinot](https://github.com/trinodb/trino/pull/15599)
* [PostgreSQL, Prometheus, Redis, Redshift, Singlestore, SQLServer](https://github.com/trinodb/trino/pull/15600) …
=> Update docs for connector catalog examples-3

docs/src/main/sphinx/connector/alter-table-limitation.fragment, docs/src/main/sphinx/connector/mariadb.rst, docs/src/main/sphinx/connector/memory.rst, docs/src/main/sphinx/connector/mongodb.rst, docs/src/main/sphinx/connector/mysql.rst, docs/src/main/sphinx/connector/oracle.rst, docs/src/main/sphinx/connector/phoenix.rst, docs/src/main/sphinx/connector/pinot.rst
Clarifies example names in connector docs for the MariaDB, Memory, MongoDB, MYSQL, Oracle, Phoenix, and Pinot connectors.
Continuation of: https://github.com/trinodb/trino/pull/13964
Other connector PRs:
* [TPCH, TPCDS, Thrift, Google Sheets, Atop](https://github.com/trinodb/trino/pull/15465)
* [Acumulo, BigQuery, Black Hole, Cassandra, Clickhouse](https://github.com/trinodb/trino/pull/15494)
* [Delta Lake, Druid, Elastisearch, Hudi, Iceberg ](https://github.com/trinodb/trino/pull/15530)
* [JMX, Kafka, Kinesis, Kudu, Local File](https://github.com/trinodb/trino/pull/15597)
* [PostgreSQL, Prometheus, Redis, Redshift, Singlestore, SQLServer](https://github.com/trinodb/trino/pull/15600) …
=> Update docs for connector catalog examples-5

docs/src/main/sphinx/connector/memsql.rst, docs/src/main/sphinx/connector/postgresql.rst, docs/src/main/sphinx/connector/prometheus.rst, docs/src/main/sphinx/connector/redis.rst, docs/src/main/sphinx/connector/redshift.rst, docs/src/main/sphinx/connector/sqlserver.rst
Clarifies example names in connector docs for the PostgreSQL, Prometheus, Redis, Redshift, Singlestore, and SQLServer connectors.
Continuation of: https://github.com/trinodb/trino/pull/13964
Other connector PRs:
* [TPCH, TPCDS, Thrift, Google Sheets, Atop](https://github.com/trinodb/trino/pull/15465)
* [Acumulo, BigQuery, Black Hole, Cassandra, Clickhouse](https://github.com/trinodb/trino/pull/15494)
* [Delta Lake, Druid, Elastisearch, Hudi, Iceberg ](https://github.com/trinodb/trino/pull/15530)
* [JMX, Kafka, Kinesis, Kudu, Local File](https://github.com/trinodb/trino/pull/15597)
* [MariaDB, Memory, MongoDB, MYSQL, Oracle, Phoenix, Pinot](https://github.com/trinodb/trino/pull/15599) …
=> Update docs for connector catalog examples-6

docs/src/main/sphinx/connector/delta-lake.rst, docs/src/main/sphinx/connector/hive.rst, docs/src/main/sphinx/connector/iceberg.rst
Add `parquet.max-read-block-row-count` property for parquet optimized connectors
```markdown
```
=> Add parquet.max-read-block-row-count property

core/trino-main/src/main/java/io/trino/metadata/DisabledSystemSecurityMetadata.java, core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java, core/trino-main/src/main/java/io/trino/metadata/SystemSecurityMetadata.java, testing/trino-tests/src/test/java/io/trino/security/TestingSystemSecurityMetadata.java
Add methods in SystemSecurityMetadata to provide
notification of adding, dropping and renaming columns.
```markdown
```
=> Add column add/drop/rename events

core/trino-main/src/main/java/io/trino/operator/join/NestedLoopJoinOperator.java
Minor change that adds `sealed` / `permits` modifiers to `NestedLoopJoinOperator.NestedLoopOutputIterator` to enforce the bi-morphic constraint that was previously only described by an inline comment added before migrating to JDK17.
=> Make NestedLoopOutputIterator sealed

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyPreferredTableExecutePartitioning.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyPreferredTableWriterPartitioning.java
Currently, preferred write/execute will
be chosen when stats are broken or missing.
Hence, extra if condition is no longer needed
NO RELEASE NOTES
=> Remove redundant if condition

core/trino-main/src/main/java/io/trino/execution/executor/TaskExecutor.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/RetryDriver.java
This PR includes two changes to Thread interrupt handling:
1. In `trino-hive`, modify `RetryDriver` to stop attempting retries if `InterruptedException` is caught or the current thread is interrupted and immediately throw the current exception. Otherwise, `RetryDriver` might interfere with drivers terminating in a timely manner after tasks are terminated via a cancel, failure, or abort.
2. In `trino-main`, check and clear thread interrupt status at the end of processing a split in `TaskRunner` before looping back to start processing a new split. Otherwise, a split that is interrupted (eg: because the task was cancelled) would leave the thread interrupted flag set which would cause the `TaskRunner` to stop processing and unnecessarily submit a new instance from which could cause additional …
=> Handle interruption in RetryDriver and TaskRunner

lib/trino-hdfs/pom.xml, lib/trino-hdfs/src/main/java/io/trino/hdfs/TrinoFileSystemCache.java, lib/trino-hdfs/src/test/java/io/trino/hdfs/BenchmarkGetFileSystem.java, lib/trino-hdfs/src/test/java/io/trino/hdfs/TestFSDataInputStreamTail.java, lib/trino-hdfs/src/test/java/io/trino/hdfs/TestFileSystemCache.java
Hadoop's implementation of filesystem cache ([hadoop 3.2 filesystem cache](https://github.com/apache/hadoop/blob/release-3.2.0-RC1/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/fs/FileSystem.java#L3342)) creates the filesystem object outside of synchronized block. A side effect to this (in addition to reduced locking duration for slow-to-create filesystem implementations) is that there is no interaction between the lock in caching infrastructure and locks internal to a filesystem implementation (during filesystem object creation). We would like to bring this approach to `TrinoFileSystemCache`
A secondary motivation is to improve the concurrency of `TrinoFileSystemCache` operations by avoiding synchronized blocks.
- Use ConcurrentHashMap to cache filesystem objects - …
=> Update TrinoFileSystemCache to represent latest hadoop implementation

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Restrict the user to drop a column that is used in older partition spec or void partition column in iceberg connector until the below issues got fixed.
This PR changes the older behavior for the void partition column. As earlier users could drop a void partition column. But now it is not permissible. CC: @ebyhr 
https://github.com/trinodb/trino/issues/15729
https://github.com/trinodb/trino/issues/15738
=> Restrict user to drop a column that is used in older partition spec or void partition column in iceberg connector

core/trino-spi/src/main/java/io/trino/spi/predicate/TupleDomain.java, plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/index/Indexer.java, plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/serializers/LexicoderRowSerializer.java, plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/serializers/StringRowSerializer.java
Guava's `Table` is a good class solving two-level hashing well. For SPI we cannot avoid Map-of-Map, but we can at least use `Map.computeIfAbsent` to make the code more readable.
=> Update code using Map-of-Map

core/trino-main/src/test/java/io/trino/execution/buffer/TestPagesSerde.java, core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlockEncoding.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHivePlans.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/BaseFaultTolerantExecutionTest.java
Currently, when block `VariableWidthBlock` is encoded it is writing an array of offsets for all positions regardless of the fact whether a position is null or not. Instead we could save the lengths only for non-null positions and compute offsets from an array of lengths and the array of nullability (array that determines whether position is `null` or not).
This change should be tested by `io.trino.spi.block.TestVariableWidthBlockEncoding`.
The difference was tested on query with different value of `X` to have a control on null frequency
```
with cs as (select *,  case when rand(100) < X then null else '0' end nullek from catalog_sales cs)
SELECT  count_if(cs.nullek is null), count(*), cs.nullek FROM cs
RIGHT JOIN call_center cc ON cc.cc_call_center_sk =  cs.cs_call_center_sk
GROUP BY 3 …
```
=> Optimize null representation in encoded VariableBlockWidthBlock

.github/workflows/ci.yml
For a PR that has several commits, it makes sense to check all of them. The idea is the same as we do in testing tasks.
Fixes "cancellation" part of https://github.com/trinodb/trino/issues/15793
=> Continue commits checks when one fails

core/trino-main/src/main/java/io/trino/connector/ConnectorContextInstance.java, core/trino-main/src/main/java/io/trino/connector/DefaultCatalogFactory.java, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorContext.java
Add CatalogHandle to ConnectorContext.
This makes the catalog handle available to the connector factory when creating a new connector instance
This builds upon the PR to add CatalogHandle to the SPI: https://github.com/trinodb/trino/pull/15425
=> Add CatalogHandle to ConnectorContext

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
BaseJdbcClient.beginInsertTable adds additional column when in FTE mode. This will allow connectors to override the way this column is added  (e.g. a part of remote table name) without overriding whole beginInsertTable method.
```markdown
```
=> Provide extra extension point for adding column in BaseJdbcClient

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetConnectorTest.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Add support for changing fields in `row` type in Iceberg. The supported operations:
* Add a new field
* Update an existing field type
* Delete an existing field
* Reorder fields
(x) Release notes are required, with the following suggested text if this PR isn't merged in 406:
```markdown
* Add support for changing fields in `row` type . ({issue}`15808`)
```
=> Add support for changing row type in Iceberg

docs/src/main/sphinx/connector/iceberg.rst, docs/src/main/sphinx/release.rst, docs/src/main/sphinx/release/release-406.md
Assemble the release notes for the upcoming Trino 406 release. Fixes #15563  
@hashhar #15542 ✅ rn ✅ docs
@ebyhr #15553 ✅ rn ✅ docs
@ebyhr #15538 ✅ rn ✅ docs
@ebyhr #15566 ✅ rn ✅ docs
@ebyhr #15570 ✅ rn ✅ docs
@ebyhr #15544 ✅ rn ✅ docs
@findepi #15573 ✅ rn ✅ docs
@findepi #15574 ✅ rn ✅ docs
@raunaqmorarka #15552 ✅ …
=> Add Trino 406 release notes

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConnectorSmokeTest.java
Test failure message when executing `register_table` procedure in Iceberg REST and JDBC catalogs
=> Test failure message when executing `register_table` procedure in Iceberg REST and JDBC catalogs

docs/src/main/sphinx/admin/fault-tolerant-execution.rst
See title
I ran into this when looking at #15620
=> Fix spelling in FTE docs

docs/src/main/sphinx/connector/mongodb.rst
Removing documentation for a deprecated property from MongoDB connector that was finally removed in 405, but documentation update was missed.
Missed doc update from https://github.com/trinodb/trino/pull/15263/files 
=> Remove unsupported properties from MongoDB documentation

core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaPageSource.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Fixes https://github.com/trinodb/trino/issues/8207
Supersedes #10745
```markdown
* fixes #8207 
* Materialized Views now show up within information_schema.tables with the table_type of `MATERIALIZED VIEW`
```
=> Unified Materialized View Table Type in information_schema

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, core/trino-main/src/main/java/io/trino/testing/TestingMetadata.java, core/trino-main/src/test/java/io/trino/connector/MockConnector.java, core/trino-main/src/test/java/io/trino/execution/TestCreateMaterializedViewTask.java, core/trino-spi/src/main/java/io/trino/spi/connector/MaterializedViewFreshness.java, testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
Extracted from https://github.com/trinodb/trino/pull/15842
=> Small code fixes 

.github/workflows/ci.yml
Usually "a dispatcher" is the entity defining tasks to be done rather
than the entity doing an individual task.
The change has the additional benefit that the matrix task checking
individual commits has a shorter name, so the matrix parameter is
slightly more visible in the GitHub actions UI.
=> Fix check-commits task names

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Call `purgeTable` in Iceberg REST catalog
=> Call purgeTable in Iceberg REST catalog

core/trino-main/src/main/java/io/trino/type/TypeCoercion.java, core/trino-main/src/test/java/io/trino/type/TestTypeCoercion.java
Fixes https://github.com/trinodb/trino/issues/15861
Fixes https://github.com/trinodb/trino/issues/15865
=> Fix precision loss when coercing TIME to TIME TZ and fix abundant precision when coercing DATE to TIMESTAMP TZ

core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java, core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveTrivialFilters.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/CorrelatedJoinNode.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/FilterNode.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/JoinNode.java, core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java, core/trino-main/src/test/java/io/trino/sql/planner/TestUnwrapCastInComparison.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/BasePlanTest.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/CorrelatedJoinMatcher.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/ExpressionMatcher.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/PlanMatchPattern.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestImplementLimitWithTies.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestImplementOffset.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestMergeLimitOverProjectWithSort.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushLimitThroughProject.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushTopNThroughProject.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveTrivialFilters.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformUncorrelatedSubqueryToJoin.java
When predicate is not of boolean type (e.g. `null` literal being of
`unknown` type), the `Analysis` holds a coercion that should be applied
to it.  Before the change, the coercion was not getting applied though.
=> Apply coercions when creating FilterNode

testing/trino-tests/src/test/java/io/trino/memory/TestMemoryManager.java, testing/trino-tests/src/test/java/io/trino/tests/TestDistributedSpilledQueries.java
FileSingleStreamSpillerFactory#cleanupOldSpillFiles() will cleanup spill files, which means there is a race condition when multiple spill tests are running
using same spill path.
* no release notes *
Fixes: https://github.com/trinodb/trino/issues/13288
=> Fix flaky spill tests

core/trino-parser/src/main/java/io/trino/sql/parser/ErrorHandler.java, core/trino-parser/src/main/java/io/trino/sql/parser/SqlParser.java, core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParserErrorHandling.java
When the parsing failure occurs in the middle of a rule (as opposed to at the start of a rule), do not suppress the candidate tokens even if the rule is marked as suppressed.
For instance, if the parsing fails immediately when recursing into primaryExpression, the candidates from that rule will be suppressed to avoid polluting the error message with all the possible prefixes of that rule (EXISTS, CASE, TRY_CAST, CURRENT_XXX, etc).
However, if the parsing fails after <identifier> is matched within the <identifier> <string> alternative, include <string> in set of expected candidates.
Fixes https://github.com/trinodb/trino/issues/15044
=> Do not suppress candidate tokens in the middle of a rule

core/trino-main/src/main/java/io/trino/type/TypeCoercion.java
=> Use enhanced switch expressions

core/trino-main/src/main/java/io/trino/metadata/TableFunctionHandle.java, core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java, core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java, core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ImplementTableFunctionSource.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/SymbolMapper.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/UnaliasSymbolReferences.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/PlanNode.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/PlanVisitor.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/TableFunctionNode.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/TableFunctionProcessorNode.java, core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java, core/trino-main/src/main/java/io/trino/sql/planner/sanity/ValidateDependenciesChecker.java, core/trino-main/src/test/java/io/trino/connector/TestingTableFunctions.java, core/trino-main/src/test/java/io/trino/sql/planner/TestTableFunctionInvocation.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/PlanMatchPattern.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/TableFunctionMatcher.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/TableFunctionProcessorMatcher.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestImplementTableFunctionSource.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java, core/trino-spi/src/main/java/io/trino/spi/function/SchemaFunctionName.java, core/trino-spi/src/main/java/io/trino/spi/ptf/TableArgumentSpecification.java
This PR adds an iterative rule `ImplementTableFunctionSource` which transforms (potentially) multiple sources of a `TableFunctionNode` into a single source. The rule joins the sources according to their partitioning, ordering, co-partitioning and prune when empty properties.
This PR also introduces a new PlanNode to represent the table function invocation with pre-processed source: `TableFunctionProcessingNode`.
note: the rule is quite complicated, so the implementation was split into three steps, each covering some area. I meant to squash them after the review, but it would be also correct to merge them separately.
(x ) This is not user-visible or docs only and no release notes are required. …
=> Implement table function source

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
This allows to split statistics cache from metadata cache because loading of partition statistics doesn't require yet another fetch of Table and Partition objects which might not be cached.
* no release notes *
=> Remove extra cache backreferences when loading part and part stats

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
Add support for changing column types in MongoDB connector
Relates to #15515
```markdown
* Add support for changing column types. ({issue}`15515`)
```
=> Add support for changing column types in MongoDB connector

docs/src/main/sphinx/security/ldap.rst
This config option was moved to legacy and replaced by a truststore path, so we should update our example
N/A
=> Fix docs for LDAP truststore

core/trino-main/src/main/java/io/trino/cost/AggregationStatsRule.java, core/trino-main/src/test/java/io/trino/cost/TestAggregationStatsRule.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestShowStats.java
Global aggregation always produces a single row, and it does not depend on input stats. 
Global aggregation could produce `NaN` output rows count if source stats were unavailable, which could cause choosing of suboptimal plan during query execution.
=> Fix row output estimation for global aggregation

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
Use records for various cache key in CachingJdbcClient
~Preparatory commit for this PR - https://github.com/trinodb/trino/pull/15813.~
=> Use records for cache key in CachingJdbcClient

docs/src/main/sphinx/admin/fault-tolerant-execution.rst, testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
Follow-up of https://github.com/trinodb/trino/commit/920d14c82c5adefd2f06feadfac1a0a96f9ff5ac
=> Remove unused FTE config property

.github/workflows/ci.yml
This job is not supposed to download all dependencies, so it should not be saving the local Maven repository in the GitHub Actions cache. Since it can run quicker than other jobs that do a full build, it can generate an incomplete cache entry, preventing bigger cache entries from being saved.
=> Avoid saving cache in the build-test-matrix CI job

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastoreConfig.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/SharedHiveMetastoreCache.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreConfig.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/IcebergFileMetastoreCatalogModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/IcebergHiveMetastoreCatalogModule.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestingIcebergFileMetastoreCatalogModule.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestingIcebergHiveMetastoreCatalogModule.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestExternalHiveTable.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTableStatistics.java
Split caching into metadata and stats cache. Stats
pulling puts significant pressure on metastore. However,
stats don't have to be always up to date in order
to get good query plance. Therefore, stats can
be cached by default.
RELEASE NOTES:
```
Hive/Delta
* Reduce query latency by caching partition and table statistics by default. {}
```
=> Cache metastore (table and partition) stats by default

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/DeltaLakeMetastore.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java
Advise the metastore to delete table data only when dealing with managed tables.
Delta Lake same as Hive works with `MANAGED` and `EXTERNAL` table types. In case of dealing with `MANAGED` tables, the engine is responsible (either through delegating internally this responsibility to the metastore - HMS or doing this operation itself in case of AWS) to remove the content of the table when executing `DROP TABLE table_name` statements.
=> Adjust the drop table logic for Delta Lake managed tables

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
Closes  #14822 
Allow Iceberg writes to use either append or fastAppend. Users in certain use cases may want to do compaction of Manifests async from writes. We should allow configuring fastAppend for that situation on a session level basis.
New IcebergSessionProperty _iceberg.merge_manifests_on_write_ . Default value - "true". 
_SET SESSION iceberg.merge_manifests_on_write = false_ to force fastAppend()
_SET SESSION iceberg.merge_manifests_on_write = true_ to force append()
* Allow to do compaction of Manifests asynchronously from writes by configuring property …
=> Allow Iceberg writes to use either append or fastAppend

lib/trino-parquet/src/main/java/io/trino/parquet/reader/SimpleSliceInputStream.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/DeltaLengthByteArrayDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkBinaryColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/AbstractValueDecodersTest.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestByteArrayValueDecoders.java
Optimize DELTA_LENGTH_BYTE_ARRAY decoder in parquet
```
Benchmark                         (positionLength)                             (type)   Mode  Cnt    Before             After              Units
BenchmarkBinaryColumnReader.read    VARIABLE_0_100                          UNBOUNDED  thrpt   10    1.795 ±  0.793     87.765 ±    6.190  ops/s
BenchmarkBinaryColumnReader.read    VARIABLE_0_100          VARCHAR_ASCII_BOUND_EXACT  thrpt   10    2.065 ±  0.539     96.691 ±   13.081  ops/s
BenchmarkBinaryColumnReader.read    VARIABLE_0_100              CHAR_ASCII_BOUND_HALF  thrpt   10    2.401 ±  0.134      5.792 ±    1.579  ops/s
BenchmarkBinaryColumnReader.read    VARIABLE_0_100  CHAR_BOUND_HALF_PADDING_SOMETIMES  thrpt   10    2.607 ±  0.113      7.328 ±    2.045  ops/s …
```
=> Optimize DELTA_LENGTH_BYTE_ARRAY decoder in parquet

.mvn/modernizer/violations.xml, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueToTrinoConverter.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestGlueToTrinoConverter.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergTableOperations.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDatabricksWithGlueMetastoreCleanUp.java
`Glue.getTableType` is nullable.
=> Fix NPE when Glue table has no type

pom.xml
Upgrading benchto-driver to 0.23 version
( *) This is not user-visible or docs only and no release notes are required.
=> Dependency benchto-driver was upgraded from 0.22 to 0.23

core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java, core/trino-main/src/main/java/io/trino/operator/DeduplicatingDirectExchangeBuffer.java, core/trino-main/src/test/java/io/trino/execution/scheduler/TestEventDrivenTaskSource.java, core/trino-spi/src/main/java/io/trino/spi/exchange/Exchange.java, plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchange.java, plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/AbstractTestExchangeManager.java
It is not always possible for exchange implementation to
provide an immediate return for calls to:
* `Exchange.instantiateSink `and
* `Exchange.updateSinkInstanceHandle`
depending on exchange implementation sometimes there needs to be a network
the communication involved or another lengthy process. To allow for such
exchange implementations and not block engine threads this PR changes
SPI so the two methods listed above now return
`CompletableFuture<ExchangeSinkInstanceHandle>`.
=> Obtain and refresh sink instance handle asynchronously

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcConnectorTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Extracted from https://github.com/trinodb/trino/pull/15842
=> Fix materialized view failure mode when base table gone

lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ApacheParquetValueDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/DeltaByteArrayDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/TransformingValueDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkLongDecimalColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkShortDecimalColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkUuidColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnReaderBenchmark.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestShortDecimalColumnReaderBenchmark.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/AbstractValueDecodersTest.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestByteArrayValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestFixedWidthByteArrayValueDecoders.java
Optimize DELTA_BYTE_ARRAY decoder in parquet reader for BINARY and FIXED_LEN_BYTE_ARRAY parquet types
```markdown
* Improve performance of reading string data types from parquet files. ({issue}`15923`)
```
=> Optimize DELTA_BYTE_ARRAY decoder in parquet reader

core/trino-main/src/main/java/io/trino/operator/output/RowPositionsAppender.java, core/trino-main/src/test/java/io/trino/operator/output/TestPositionsAppender.java
In case of null projection with UnknownType,
Rle with null ByteArrayBlock value is created.
This breaks RowPositionsAppender assumption
about incoming block type.
```markdown
```
=> Fix null projects handling in RowPositionsAppender

docs/src/main/sphinx/connector/delta-lake.rst, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/UnregisterTableProcedure.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeRegisterTableProcedureTest.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeProceduresCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeCompatibility.java
Relates to https://github.com/trinodb/trino/issues/15784
```markdown
* Add support for `unregister_table` procedure. ({issue}`15784`)
```
=> Add support for unregister_table procedure in Delta Lake

plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/ExchangeS3Config.java, plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/s3/TestExchangeS3Config.java
Fail-fast in case that the file referenced in the configuration does not exist.
=> Add `@FileExists` validation

core/trino-main/src/main/java/io/trino/operator/output/PagePartitioner.java, core/trino-main/src/main/java/io/trino/operator/output/PagePartitionerPool.java, core/trino-main/src/test/java/io/trino/operator/output/TestPagePartitioner.java, core/trino-main/src/test/java/io/trino/operator/output/TestPagePartitionerPool.java
Memory has to be released to the memory pool
even if the flush fails e.g. due to a bug
```markdown
```
=> Free PagePartitioner memory even if flush fails

core/trino-main/src/main/java/io/trino/operator/output/BytePositionsAppender.java, core/trino-main/src/main/java/io/trino/operator/output/Int128PositionsAppender.java, core/trino-main/src/main/java/io/trino/operator/output/Int96PositionsAppender.java, core/trino-main/src/main/java/io/trino/operator/output/IntPositionsAppender.java, core/trino-main/src/main/java/io/trino/operator/output/LongPositionsAppender.java, core/trino-main/src/main/java/io/trino/operator/output/PagePartitioner.java, core/trino-main/src/main/java/io/trino/operator/output/PositionsAppender.java, core/trino-main/src/main/java/io/trino/operator/output/PositionsAppenderPageBuilder.java, core/trino-main/src/main/java/io/trino/operator/output/RleAwarePositionsAppender.java, core/trino-main/src/main/java/io/trino/operator/output/RowPositionsAppender.java, core/trino-main/src/main/java/io/trino/operator/output/ShortPositionsAppender.java, core/trino-main/src/main/java/io/trino/operator/output/SlicePositionsAppender.java, core/trino-main/src/main/java/io/trino/operator/output/TypedPositionsAppender.java, core/trino-main/src/main/java/io/trino/operator/output/UnnestingPositionsAppender.java, core/trino-main/src/test/java/io/trino/operator/output/TestPositionsAppender.java
The row-based approach in `PagePartitioner` is faster than the columnar one when the number of positions in a page is smaller than the partition count.
For this reason, we currently maintain two buffers in PagePartitioner, one for a columnar approach and one for row-based.
This has the downside of possibly doubling the amount of memory we use to buffer the outgoing pages before there are flushed to the `OutputBuffer`.
This change switches to only `PositionsAppender` buffers without much performance impact by adding efficient single position append in `PositionsAppender` implementations.
The average difference is around 0 but there are a few cases with some degradation, usually 5-10% but also some with higher, mostly for the extreme 10 positions per page case.
In general, I think this …
=> Use only PositionsAppender buffers in PagePartitioner

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
Suppress permission denied when listing materialized views in Iceberg Glue
Similar fixes as #14971
```markdown
* Fix failure when access denied exceptions happened during listing materialized views in a Glue. ({issue}`issuenumber`)
```
=> Suppress permission denied when listing materialized views in Iceberg Glue

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
- Clean up those tests resources after test execution
- Randomize the resource names of the created mongo test resources
- system.views is not queryable collection hence included in the system tables to be filtered before returning the available collection in the database
- System database to be filtered before returning the list of available databases
=> Randomize table names in MongoDB tests

lib/trino-parquet/src/main/java/io/trino/parquet/ParquetTimestampUtils.java, lib/trino-parquet/src/main/java/io/trino/parquet/dictionary/DoubleDictionary.java, lib/trino-parquet/src/main/java/io/trino/parquet/dictionary/FloatDictionary.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ApacheParquetValueDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/PlainValueDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/RleBitPackingHybridBooleanDecoder.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkBooleanColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkInt96ColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnReaderBenchmark.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/AbstractValueDecodersTest.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestBooleanValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestInt96ValueDecoder.java
Optimize decoders for INT96 and booleans in parquet
This completes the work of moving to optimized decoders from the parquet-mr based ones in optimized parquet reader.
```markdown
* Improve performance of reading timestamp and boolean type columns from parquet files. ({issue}`15954`)
```
=> Optimize decoders for INT96 and BOOLEAN in parquet

plugin/trino-delta-lake/pom.xml, plugin/trino-delta-lake/src/main/antlr4/io/trino/plugin/deltalake/expression/SparkExpressionBase.g4, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/BooleanLiteral.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/CaseInsensitiveStream.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/ComparisonExpression.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/Identifier.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/Literal.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/LogicalExpression.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/LongLiteral.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/ParsingException.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpression.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionBuilder.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionConverter.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionParser.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionTreeVisitor.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/StringLiteral.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/expression/TestSparkExpressionParser.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/expression/TestSparkExpressions.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCheckConstraintCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksInsertCompatibility.java
Supported expressions are intentionally limited in this PR. 
~The 1st commit came from #14964. Please leave review comments for the 1st commit in #14964.~
```markdown
* Support inserting into tables having `CHECK` constraints. ({issue}`15396`)
```
=> Support inserting into table having CHECK constraint in Delta Lake 

core/trino-main/src/main/java/io/trino/operator/output/PagePartitioner.java, core/trino-main/src/main/java/io/trino/operator/output/RowPositionsAppender.java
```markdown
* Improve query memory tracking. ({issue}`issuenumber`)
```
=> Track retained memory usage in PagePartitioner

core/trino-main/src/main/java/io/trino/sql/planner/plan/JoinNode.java, core/trino-parser/src/main/java/io/trino/sql/tree/ComparisonExpression.java, core/trino-parser/src/main/java/io/trino/sql/tree/Join.java
That makes it easier to understand how the class is parameterized. Consistent with code style in `LogicalExpression`.
We could also choose to place such enums at the bottom (not my preference). In any case, they should not be somewhere in the middle, mixed between instance methods.
cc @trinodb/maintainers for code style related
=> Move parameterizing enums to the top of enclosing class

.github/DEVELOPMENT.md
This PR formalizes the release process into the Trino DEVELOPMENT.md file.
Updating DEVELOPMENT.md.
=> Add release process section to DEVELOPMENT.md

plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestHiveUtil.java
Avoids creating unnecessary String copies when attempting to escape and unescape path name parts that have no special characters in them. Also avoids the unnecessary overhead of using String.format when unescaping is necessary and pre-computes the `CharMatcher` (which results in a faster, 16 byte bitset).
Similar code was contributed to Hive in [HIVE-26685](https://issues.apache.org/jira/browse/HIVE-26685) (pull request: https://github.com/apache/hive/pull/3721), but was further improved here for Trino to use `java.util.HexFormat` which is not available in JDK8.
=> Improve HiveUtils name escaping

docs/src/main/sphinx/installation/containers.rst
So that when you search for pages that mention Docker, you end up in the right place.
From this thread on the Trino slack: https://trinodb.slack.com/archives/CP1MUNEUX/p1672858775220719
```markdown
```
=> Update title of container docs to mention Docker

lib/trino-orc/src/main/java/io/trino/orc/OrcRecordReader.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
Pass a row position predicate to the delete file reader when loading ORC data files.
Initial support for Parquet was done here: https://github.com/trinodb/trino/pull/13395
```markdown
* Improve performance of reading position delete files with ORC data.
```
=> Filter Iceberg position delete reads for ORC

testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
Maybe fixes: https://github.com/trinodb/trino/issues/15809
=> Limit concurrency of parallel FTE tests execution

lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetReaderMemoryUsage.java
Test can sometimes fail due to random input
```
io.trino.parquet.reader.TestParquetReaderMemoryUsage.testColumnReaderMemoryUsage  Time elapsed: 0.283 s  <<< FAILURE!
2023-02-06T20:14:38.2933047Z java.lang.AssertionError: 
2023-02-06T20:14:38.2933574Z 
2023-02-06T20:14:38.2933892Z Expecting value to be false but was true
2023-02-06T20:14:38.2934661Z 	at io.trino.parquet.reader.TestParquetReaderMemoryUsage.lambda$testColumnReaderMemoryUsage$0(TestParquetReaderMemoryUsage.java:75)
```
=> Fix flakiness from random input in TestParquetReaderMemoryUsage

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseAutomaticJoinPushdownTest.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Use smaller tables or smaller data sets in general, where appropriate. This should speed up tests for some connectors considerably.
```markdown
```
=> Downscale base connector tests

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedSingleRowSubqueryToProject.java, core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedSingleRowSubqueryToProject.java, core/trino-main/src/test/java/io/trino/sql/query/TestMergeProjectWithValues.java, core/trino-main/src/test/java/io/trino/sql/query/TestSelectAll.java, core/trino-main/src/test/java/io/trino/sql/query/TestSubqueries.java
Before this change, the rule `TransformCorrelatedSingleRowSubqueryToProject` matched a CorrelatedJoinNode with arbitrary number of ProjectNodes in the subquery. It supported identity projections and at most one non-identity projection.
After this change, the rule supports 0 or 1 projection. Projections can be inlined by the rule `InlineProjections`.
This change also extends the rule to handle more kinds of ValuesNode: after the change any single-row values is supported provided that the values row is an expression of type `Row`.
This change can be also considered a preparatory step before the rule `MergeProjectWithValues` is used more widely. It removes dependency between the `MergeProjectWithValues` rule and the de-correlating rules.
```markdown
* Support correlated queries involving …
```
=> Decorrelate single-row values

core/trino-main/src/main/java/io/trino/metadata/DisabledSystemSecurityMetadata.java, core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java, core/trino-main/src/main/java/io/trino/metadata/SystemSecurityMetadata.java, testing/trino-tests/src/test/java/io/trino/security/TestingSystemSecurityMetadata.java
Reverts trinodb/trino#15225
The current implementation has the following problems
- does not work for Hive connector with `hive.security=system` (https://github.com/trinodb/trino/pull/15225#discussion_r1093300534)
- notifications are propagated even if transaction doesn't end up committing the DDL changes (https://github.com/trinodb/trino/pull/15225#discussion_r1094648449)
- notification propagation may disrupt transaction finish even if changes already applied in the external system (https://github.com/trinodb/trino/issues/12535#issuecomment-1417684880), for any connector that's using SYSTEM security (Iceberg, Delta with system security, or any JDBC connector)
The revert is only temporary, the functionality will be reintroduced soon.
Fixes https://github.com/trinodb/trino/issues/12535
=> Revert "Add column add/drop/rename events"

core/trino-main/src/main/java/io/trino/operator/DeleteAndInsertMergeProcessor.java, core/trino-main/src/main/java/io/trino/sql/planner/MergePartitioningHandle.java, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMergeSink.java, core/trino-spi/src/main/java/io/trino/spi/connector/MergePage.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DataFileInfo.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeCdfPageSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSinkProvider.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/CdfFileEntry.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeTransactionLogEntry.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogWriter.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java, plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduPageSink.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksChangeDataFeedCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksInsertCompatibility.java
Adds support for CDF write in delta lake connector.
Change Data Feed allows to track low level changes between versions of delta lake table.
Details [here](https://docs.databricks.com/delta/delta-change-data-feed.html).
Originally the idea was to implement CDF write separately for UPDATE, DELETE and MERGE operations but it turned out that they are so interconnected that it turned out to be impossible and thus all are implemented in the same PR. 
Please note that currently there is no possibility to enable CDF from trino. It has to be enabled using databricks engine.
```markdown …
```
=> Write Change Data Feed in Delta Lake

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/authentication/KerberosAuthentication.java
A bugfix to make authentication work correctly on a Kerberized Kudu cluster. Old Kerberos tickets may be used to make Kudu connections, it may lead to Kudu `UnrecoverableException` being raised when query Kudu's data even though relogin recently. Besides, next ticket refresh time is calculated based on the ticket's `startTime` and `endTime`, a wrong result will lead to frequent access to the KDC. Remove old tickets after relogin can fix the issue.
This PR fixes #14372
fixes https://github.com/trinodb/trino/issues/14441
Remove old Kerberos ticket to avoid authentication check failures when access Kerberized Kudu clusters.
(x) Release notes are …
=> remove old Kerberos ticket after relogin to make Kudu authentication work correctly

core/trino-parser/src/main/java/io/trino/sql/parser/ErrorHandler.java, core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParserErrorHandling.java
Exception:
```
Unexpected failure when handling parsing error. This is likely a bug in the implementation
java.util.ConcurrentModificationException
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
at io.trino.sql.parser.ErrorHandler$Analyzer.process(ErrorHandler.java:216)
```
This was happening because after the first iteration of the while loop,
`endTokens` is a reference to `nextTokens`, so when we iterate through
`endTokens`, we are actually iterating through `nextTokens`. So since we are
iterating through `nextTokens` and also adding to `nextTokens` at the same
time, we end up with a `ConcurrentModificationException`.
( …
=> Fix ConcurrentModificationException in parser error handler

core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
Fixes [15931](https://github.com/trinodb/trino/issues/15931) which was introduced in https://github.com/trinodb/trino/pull/15721 and could cause split assignment updates that are empty after filtering previously acknowledged splits to trigger a sanity check validation in `DriverSplitRunnerFactory#enqueueSplits` and fail.
This change should not require release notes because the issue being fixed has not yet shipped with a release.
=> Fix SplitAssignment filtering

core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java, plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java
It was always the original intention, let's enforce it with the type system.
=> Require 1+ retained node for isNotFullyPushedDown check

core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RewriteTableFunctionToTableScan.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/Patterns.java
This is an optimization. Currently it has no impact on users because table functions with table arguments are not yet supported.
We should add release notes only if this goes in after https://github.com/trinodb/trino/pull/15575
=> Optimize table function source

lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/ProtobufUtils.java, plugin/trino-kafka/pom.xml, plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/encoder/protobuf/ProtobufSchemaParser.java, plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/protobuf/TestKafkaProtobufWithSchemaRegistryMinimalFunctionality.java, plugin/trino-kafka/src/test/resources/protobuf-sources/unsupported_recursive.proto, plugin/trino-kafka/src/test/resources/protobuf/structural_datatypes.proto
Kafka connector throws a StackOverflowError when the protobuf schema
includes self referenced object types.
To improve user experience the schema parsing now throws TrinoException
saying that the type is unsupported.
```markdown
* Improve error message in Kafka connector when parsing recursive protobuf schemas. ({issue}`issuenumber`)
```
=> Improve error message in Kafka connector when parsing recursive protobuf schemas

.github/DEVELOPMENT.md, .github/actions/compile-commit/action.yml, .github/actions/setup/action.yml, .github/bin/download-maven-dependencies.sh, .github/workflows/ci.yml, core/trino-spi/pom.xml, pom.xml
A call to `dependency:go-offline` was recently added to download all dependencies into the local Maven cache.
Unfortunately it turns out the goal has some problems with multi-module projects, and Maven will still attempt to download any missing artifacts during build.
The purpose of this PR is to improve this situation by caching MORE dependencies, as every cached artifact decreases the chance of a Maven Central download failure breaking Maven builds. 
Downloading ALL dependencies is NOT a requirement, although it would be ideal.
Other jobs will now depend the `maven-checks` job as they now need to unpack the cache artifact left by it.
CI workers sometimes fail to download dependencies in the middle of a build.
A workaround was proposed to download as many dependencies as possible at the …
=> Download more dependencies to decrease the chance of network errors

docs/src/main/sphinx/admin/event-listeners-http.rst
=> Fix http event listener doc

core/trino-main/src/main/java/io/trino/server/Server.java
Configuration errors are always fatal and non-recoverable, so it helps to have a unique exit code.
```markdown
```
=> Use identifiable exit code for application configuration errors

core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java, core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
The keyword COPARTITION is specific to table function invocation. It is not a reserved keyword. In some cases, the word COPARTITION can be ambiguously interpreted: either as table argument alias, or as part of the COPARTITION clause.
To solve the ambiguity, we decided to fail queries using the word "copartition" as table argument alias, while keeping the word non-reserved and available to be used as identifier in other contexts.
No docs or release notes required, because table function table arguments are not yet supported.
=> Fix potential ambiguity while parsing queries involving table functions

plugin/trino-kafka/pom.xml
Necessary for the build to be reproducible.
=> Pin protoc-jar-maven-plugin version

core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionTest.java, testing/trino-testing/src/main/java/io/trino/testing/FaultTolerantExecutionConnectorTestHelper.java
Split enumeration is stopped when there are enough tasks to be scheduled in the task queue. However split enumeration should continue for stages that have at least one "open" task (task that doesn't have the complete set of splits assigned). Otherwise there is a chance that "open" tasks may never finish and split enumeration process may never get resumed.
https://github.com/trinodb/trino/issues/16029
```markdown
```
=> Fix potential deadlock in FTE scheduler

plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java, plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java
Fix https://github.com/trinodb/trino/issues/16027
=> Return NULL when zero date with convertToNull in Mysql

core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlockEncoding.java
Follows up from https://github.com/trinodb/trino/pull/15760 to further optimize `VariableWidthBlockEncoding#readBlock` to avoid allocating an unnecessary additional lengths array, since the final offsets array can temporarily store the serialized lengths of non-null positions and transform them back into valid offsets in-place.
Avoiding the extra array allocation does not reduce CPU throughput, and generally also improve as a result of being able to trigger CMOV optimizations a special path for the "no-nulls" case.
Benchmarks:
```
Benchmark                                  (nulls)  Mode  Before         After          Units 
BenchmarkBlockSerde.deserializeSliceDirect       0  avgt  4.174 ± 0.455  3.700 ± 0.092  ns/op
BenchmarkBlockSerde.deserializeSliceDirect     .01  avgt  4.943 ± 0.340 …
```
=> Improve VariableWidthBlock deserialization

docs/src/main/sphinx/connector/iceberg.rst, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcCatalogConfig.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcCatalogModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcConnectionFactory.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalogFactory.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConfig.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestingIcebergJdbcServer.java, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-jdbc-catalog/iceberg.properties
Add user and password properties for Iceberg JDBC catalog to hide password
from the error message by Iceberg library. 
```markdown
* Add `iceberg.jdbc-catalog.connection-user` and `iceberg.jdbc-catalog.connection-password` config properties
to JDBC catalog. ({issue}`issuenumber`)
```
=> Add user and password properties for Iceberg JDBC catalog

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, core/trino-main/src/test/java/io/trino/connector/TestingTableFunctions.java
For compliance with SQL standard.
No release notes required because table arguments to table functions are not yet supported.
=> Enforce non-empty returned relation type of table function

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
On the Iceberg connector when trying to see the tables from within information_schema schema while working with AWS Glue metastore:
```
SHOW TABLES FROM s3.information_schema;
```
The following exception occurs:
```
"io.trino.plugin.iceberg.catalog.glue.TrinoGlueCatalog.listMaterializedViews(TrinoGlueCatalog.java:782)"
"io.trino.plugin.iceberg.IcebergMetadata.listMaterializedViews(IcebergMetadata.java:2477)"
"io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.listMaterializedViews(ClassLoaderSafeConnectorMetadata.java:961)"
"io.trino.plugin.objectstore.ObjectStoreMetadata.listMaterializedViews(ObjectStoreMetadata.java:317)"
"io.trino.metadata.MetadataManager.listMaterializedViews(MetadataManager.java:1296)"
"io.trino.metadata.MetadataListing.listMaterializedViews(MetadataLis …
```
=> Ignore Hive system schema when listing views/materialized views

plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
Fixes `MemoryMetadata#streamTableColumnNames` by returning am iterator over a fully materialized collection evaluated fully before returning from the method and releasing the object monitor. The previous implementation returned a lazy iterator over the contents of the tables map which could throw a `ConcurrentModificationException` if another thread modified the map before the caller fully consumed the iterator.
Run failure: https://github.com/trinodb/trino/actions/runs/4138831198/jobs/7158842747
```markdown
* Fix a race condition failure that could occur when reading table …
```
=> Fix MemoryMetadata#streamTableColumnNames

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAbfsConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergGcsConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogAccessOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConnectorSmokeTest.java
Fixes https://github.com/trinodb/trino/issues/15779
```markdown
* Prevent creating the table when the specified schema does not exist. ({issue}`15788`)
```
=> Prevent creating the table when the specified schema does not exist

core/trino-main/src/main/java/io/trino/execution/SqlTask.java, core/trino-main/src/main/java/io/trino/execution/SqlTaskExecution.java, core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java, core/trino-main/src/main/java/io/trino/execution/buffer/LazyOutputBuffer.java, core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedStageExecution.java, core/trino-main/src/main/java/io/trino/server/TaskResource.java, core/trino-main/src/test/java/io/trino/execution/TestSqlTaskManager.java, testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
Fixes the sequence of operations around `TaskResource` checking for task failure until after the buffer response future is completed. Otherwise, tasks could inappropriately announce completion rather than failure to consumers which can yield incorrect query results. 
Discovered while attempting to debug a swath of test failures producing incorrect results in https://github.com/trinodb/trino/pull/15478 which made the sequence of interleaving operations necessary to trigger the correctness bug more likely to occur.
```markdown
* Fix a race condition that could allow queries to …
```
=> Fix task failure signal race condition

core/trino-main/src/main/java/io/trino/server/PluginInstaller.java, core/trino-main/src/main/java/io/trino/server/PluginManager.java, core/trino-main/src/main/java/io/trino/server/ServerMainModule.java, core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
=> Introduce PluginInstaller

plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java, pom.xml, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercion.java
This reverts this cdafc868e62827ef722732081bc0edfa1195e4dd.
Starting from Hive 3.0+ this configuration property `hive.metastore.disallow.incompatible.col.type.changes` has been enabled by default - so some of the coerions tests were disabled. Now we have disabled this configuration property allowing us to run those test case on all Hive distributions. 
=> Enable certain schema evolution tests

testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Refactor the mock connector init process to be more flexible to different types of overriding by dependent test classes. Will allow dependent classes to decide when, what, and how they install in the mock connector plugin with most code reuse. 
```markdown
```
=> Refactor mock catalog init in BaseConnectorTest

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
Sometimes it is necessary to allow a higher number of partitions to be loaded eagerly to enable predicate pushdown while the total number of partitions to be scanned might be needed to be restricted.
https://github.com/trinodb/trino/pull/14225
```markdown
* Allow setting `hive.max-partitions-per-scan` to a value lover than a value set in `hive.max-partitions-for-eager-load`
```
=> Remove assertion restricting hive.max-partitions-per-scan

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalogFactory.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java
Support `register_table` and `unregister_table` procedures in Iceberg JDBC catalog
Fixes #15853
```markdown
* Add support for `register_table` and `unregister_table` procedures in JDBC catalog. ({issue}`15853`)
```
=> Support `register_table` and `unregister_table` procedures in Iceberg JDBC catalog

docs/src/main/sphinx/connector/iceberg.rst
Fixes #15971 by adding documentation around REST and JDBC catalog limitations with views.
n/a
=> Specify view limitations of REST and JDBC catalogs

docs/src/main/sphinx/connector/delta-lake.rst, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeHistoryTable.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableName.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableType.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/CommitInfoEntry.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeTransactionLogEntry.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TransactionLogTail.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/util/PageListBuilder.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableName.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
Provide the ability to query the history of changes performed on a Delta Lake table.
The documentation from https://docs.databricks.com/delta/history.html `DESCRIBE HISTORY` command was used as reference.
Same as in case of Iceberg tables, the history content can be retrieved by doing the query:
```
SELECT * from "table_name$history";
```
Fixes #15683
```markdown
* Add `$history` system table which can be queried to inspect Delta Lake table history. ({issue}`15683`)
```
=> Add delta history metadata table

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestConstraintExtractor.java
Fix wrong class name in `TestConstraintExtractor` comment
=> Fix wrong class name in `TestConstraintExtractor` comment

core/trino-main/src/main/java/io/trino/execution/SqlStage.java, core/trino-main/src/main/java/io/trino/execution/SqlTaskExecutionFactory.java, core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java, core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedQueryScheduler.java, core/trino-main/src/main/java/io/trino/sql/planner/PlanFragment.java, core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmenter.java, core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java, core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java, core/trino-main/src/test/java/io/trino/execution/MockRemoteTaskFactory.java, core/trino-main/src/test/java/io/trino/execution/TaskTestUtils.java, core/trino-main/src/test/java/io/trino/execution/TestSqlStage.java, core/trino-main/src/test/java/io/trino/execution/TestStageStateMachine.java, core/trino-main/src/test/java/io/trino/execution/scheduler/TestScaledWriterScheduler.java, core/trino-main/src/test/java/io/trino/execution/scheduler/TestSourcePartitionedScheduler.java, core/trino-main/src/test/java/io/trino/execution/scheduler/policy/PlanUtils.java, core/trino-main/src/test/java/io/trino/server/TestDynamicFilterService.java, core/trino-main/src/test/java/io/trino/sql/planner/TestPlanFragmentPartitionCount.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
Instead of using output partitioning scheme's partitionCount, use the input partitionCount for selecting the number of nodes for that stage.
```markdown
```
=> Use stage input partitioning partitionCount instead of output partitioning

docs/src/main/sphinx/connector/cassandra.rst, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClientModule.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraConnector.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraNamedRelationHandle.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPartitionManager.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraQueryRelationHandle.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraRecordCursor.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraRecordSet.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraRecordSetProvider.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraRelationHandle.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSession.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSplitManager.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTable.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTableHandle.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/ptf/Query.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/util/CassandraCqlUtils.java, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnector.java, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraTableHandle.java, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestJsonCassandraHandles.java, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/util/TestCassandraClusteringPredicatesExtractor.java, plugin/trino-cassandra/src/test/resources/cu-cassandra.yaml
Add `query` table function for query pass-through to Cassandra connector
```markdown
* Add `query` table function for query pass-through to the connector. ({issue}`15973`)
```
=> Add `query` table function for query pass-through to Cassandra connector

core/trino-main/src/main/java/io/trino/execution/DynamicFilterConfig.java, core/trino-main/src/main/java/io/trino/operator/DynamicFilterSourceOperator.java, core/trino-main/src/test/java/io/trino/operator/TestDynamicFilterSourceOperator.java
Implemented memory accounting in DynamicFilterSourceOperator.
With memory accounting added to DynamicFilterSourceOperator there
is no longer a reason to put a limit on the max size per driver
allowed in config.
Fixes https://github.com/trinodb/trino/issues/16100
```markdown
* Improved memory usage accounting for queries with dynamic filters. ({issue}`16110`)
```
=> Remove limits on dynamic-filtering.large-*.max-size-per-driver

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ReusableConnectionFactory.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestReusableConnectionFactory.java
It can happen that the connection will be closed during the query execution, either by the JDBC driver or the connection pooling manager. When connection is closed, it shouldn't be available for reuse by the next getConnection caller.
Replaces https://github.com/trinodb/trino/pull/16115
=> Do not mark already closed connection as to be reused

.github/actions/setup/action.yml, .github/workflows/ci.yml
Cache should not be restored in the `pt` job, since it doesn't build anything with Maven, and it makes it unnecessary longer by 2–3 minutes. The issue is caused by a boolean input actually being a string: https://github.com/actions/runner/issues/1483
=> Fix disabling cache in the setup action

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePartitionManager.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
The `hive.max-partitions-for-eager-load` is needed to avoid allocating too many `HivePartition` objects that could lead to an OOM on coordinator. This change ensures the limit is applied after the partition filter is applied and not before.
https://github.com/trinodb/trino/pull/16111
https://github.com/trinodb/trino/pull/14225
```markdown
* Improve predicate pushdown to partitioned columns of tables with high number of partitions
```
=> Apply hive.max-partitions-for-eager-load after applying predicate

plugin/trino-iceberg/pom.xml, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergTableOperations.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/AbstractMetastoreTableOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreCreateTableFailure.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCreateTableFailure.java
Fixes https://github.com/trinodb/trino/issues/14798
Iceberg connector creates a new metadata file when we do DDL/DML operation. In such case, if the operation gets fails then the metadata file does not get cleanup. Metastore Table Operation can fail in various cases like permission denied, and not having valid credentials. This fix will cleanup the metadata file if gets it is created.
The fix is inspired from https://github.com/apache/iceberg/blob/3cddc9f28c93b9231060ecb6b90e2d524bd5d160/aws/src/main/java/org/apache/iceberg/aws/glue/GlueTableOperations.java#L142
NA
```markdown
* …
```
=> Cleanup metadata file when `commitNewTable` fails for the Iceberg table

core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaPageSource.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
This reverts commit ba5beab7003f54d21d11c6c4037f8ebe8aa9e257, which introduces a change that's incompatible with the SQL specification. It's unclear why this is needed and no conclusion was reached on other possible alternatives. It needs further analysis and consideration.
(x) This is not user-visible or docs only and no release notes are required -- it reverts an unreleased change.
=> Do not use materialized view in information schema

docs/src/main/sphinx/functions/aggregate.rst
As described in the related issue, for some weird reason sphinx renders the arrow wrongly or completely drops the arrow and what is afterwards. This is probably a side effect of the fact that the "function" keyword in sphinx is designed for Python function, not SQL functions. 
I chose to use [] for the output at this stage and it work nicely. Other sections of the docs also seem to use that .. and others again use <>. That works as well. I am happy to use either @martint @electrum 
* Fixes https://github.com/trinodb/trino/issues/16030
=> Fix output rendering for map aggregate functions

docs/release-template.md, docs/src/main/sphinx/release.rst, docs/src/main/sphinx/release/release-407.md
Assemble the release notes for the upcoming Trino 407 release. Fixes #15854 
@ebyhr #15806 ✅ rn ✅ docs
@ebyhr #15852 ✅ rn ✅ docs
@ebyhr #15851 ✅ rn ✅ docs
@findepi #15350 ✅ rn ✅ docs
@raunaqmorarka #15713 ✅ rn ✅ docs
@ebyhr #15807 ✅ rn ✅ docs
@ebyhr #15857 ✅ rn ✅ docs
@findepi #15841 ✅ rn ✅ docs
@findepi #15844 ✅ …
=> Add Trino 407 release notes

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAnalyze.java
Collect delta lake statistics for INSERT.
```markdown
* Improve query performance on tables written by Trino with `INSERT`. ({issue}`16026 `)
```
=> Collect Delta extended statistics during insert

core/trino-main/src/main/java/io/trino/operator/output/PositionsAppenderFactory.java, core/trino-main/src/main/java/io/trino/operator/output/RleAwarePositionsAppender.java, core/trino-main/src/test/java/io/trino/operator/output/TestPositionsAppender.java
`RleAwarePositionsAppender` uses an equality check to
support producing RLE block if all incoming blocks are RLE with the same value. `BlockPositionEqual`
does not support nested nulls like array
or row with `NULL` elements, so it's both semantically better and avoids potential issues to use the
`NOT DISTINCT FROM` operator.
Fixes https://github.com/trinodb/trino/issues/16140
```markdown
* Fix failures for queries with remote partitioning exchange on a complex type (ROW, ARRAY, MAP) with values containing NULL elements. ({issue}`https://github.com/trinodb/trino/issues/16140`) …
```
=> Fix RLE support for complex types with null element

core/trino-spi/src/main/java/io/trino/spi/connector/InMemoryRecordSet.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/FilesTable.java
Fixes https://github.com/trinodb/trino/issues/15991
The RR is an alternative approach to fix https://github.com/trinodb/trino/issues/15991. another approach https://github.com/trinodb/trino/pull/16063 to fix https://github.com/trinodb/trino/issues/15991
```markdown
* Reduce memory usage when reading `$files` system tables. ({issue}`16112`)
```
=> Avoid materializing all results in Iceberg `$files` system table at once

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksChangeDataFeedCompatibility.java
Before this change MERGE that made both UPDATE and DELETE could create CDF entries with rows marked as delete when in fact there were update_preimage and other way around
```markdown
* Fix change data feed entries for `MERGE` queries. ({issue}`16127`)
```
=> Fix delta lake CDF entries for MERGE queries

docs/src/main/sphinx/connector/bigquery.rst, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTypeUtils.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryTypeMapping.java
Support writing NUMERIC and BIGNUMERIC types in BigQuery
```markdown
* Add support for writing BigQuery `numeric` and `bignumeric` types. ({issue}`16145`)
```
=> Support writing NUMERIC and BIGNUMERIC types in BigQuery

plugin/trino-hive-hadoop2/pom.xml, plugin/trino-hive-hadoop2/src/main/java/io/trino/plugin/hive/HivePlugin.java, plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHivePlugin.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeCompatibility.java, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-compatibility/hive-hadoop2.properties
Drop support for deprected `hive-hadoop2` connector name.  This name has been deprecated since June 2021.
```markdown
* Drop support for deprected `hive-hadoop2` connector name. ({issue}`16166`)
```
=> Remove support for legacy hive-hadoop2 connector name

plugin/trino-hive-hadoop2/src/main/java/io/trino/plugin/hive/HivePlugin.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConnectorFactory.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorFactory.java
=> Remove unused name customization from HiveConnectorFactory

.github/workflows/stale.yml
This PR hooks into the [Close Stale Issues](https://github.com/marketplace/actions/close-stale-issues) action with some custom configuration to allow us to monitor & track staling PRs. A couple things to note:
* We'll need to add `stale` and `no-stale` (maybe `ignore-stale` would be better?) labels to the Trino project to support the bot.
* It will only run for PRs created this year, but we could remove that config option and extend this to the existing backlog once we're completely done manually sifting through it.
The goal here is to make sure that PRs get the attention they need. The initial message will ping myself, @bitsondatadev, and @mosabua, and we'll be reviewing these mentions, triaging these PRs, working with the contributor who posted them, and finding maintainers/reviewers …
=> Add stale tracking action

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaHiveTypeTranslator.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveCoercionRecordCursor.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSource.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveTypeTranslator.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/ParquetTester.java
=> Remove deprecated type methods from HiveUtil

client/trino-cli/src/main/java/io/trino/cli/AutoTablePrinter.java, client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java, client/trino-cli/src/main/java/io/trino/cli/Console.java, client/trino-cli/src/main/java/io/trino/cli/Query.java, client/trino-cli/src/test/java/io/trino/cli/TestAutoTablePrinter.java, docs/src/main/sphinx/client/cli.rst
Make CLI automatically switch from aligned to vertical format when the output wouldn't fit the current terminal's width. Currently, users can terminate the query with `\G`, but this has a few drawbacks:
* users need to run the query twice if they notice it's too wide
* a table that's too wide will be opened in the pager and won't remain on the screen when writing a follow-up query - users might want to refer to the values from the first query, so they'd need to interrupt writing the second one
* users have to notice the output is too wide - check out the output of `SHOW FUNCTIONS` where the second column is so wide you might not notice there are more
* it's kinda hard to type - backslash is unusual and `G` has to be upper-case
This PR introduces a new `AUTO` output format that …
=> Make CLI automatically switch from aligned to vertical format

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java, plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java, plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
Enable Equal/Not Equal and IN predicate pushdown for varchar, nvarchar columns. 
It requires, that column should have case sensitive collation.
```markdown
```
=> SqlServer Equal/Not Equal/In predicate support for case sensitive varchar columns

docs/src/main/sphinx/glossary.rst
There is a dead link on the Glossary page here:
https://trino.io/docs/407/glossary#:~:text=data%20sources%20with-,catalogs,-that%20connect%20to
I'm not familiar with the .rst format and just hope this will fix the problem.
=> Fix a dead link in Glossary

docs/src/main/sphinx/connector/delta-lake.rst, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeOutputTableHandle.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableProperties.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/MetadataEntry.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksChangeDataFeedCompatibility.java
https://github.com/trinodb/trino/issues/16129
enable_change_data_feed table property enables writing delta lake CDF entries.
```markdown
* Support creating a table with `change_data_feed_enabled` table property. ({issue}`16129`)
```
=> Support creating a table with `change_data_feed_enabled` table property

plugin/trino-delta-lake/pom.xml, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeConcurrentModificationGlueMetastore.java, plugin/trino-hive/pom.xml, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueClientUtil.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/HiveGlueClientProvider.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestingGlueIcebergTableOperationsProvider.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCheckConstraintCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksChangeDataFeedCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCheckpointsCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksInsertCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksPartitioningCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksUpdates.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDropTableCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeSelectCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeRedirect.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DeltaLakeTestUtils.java
Retry dropping the delta table, in the unlikely situation that the Databricks cluster may be calling 
asynchronously in the background `glue:UpdateTable` (e.g.: update table schema) on AWS Glue.
Fixes https://github.com/trinodb/trino/issues/13199
```
Hive, Delta
* Retry dropping delta tables registered on AWS Glue in case of failures due to concurrent modifications
```
=> Retry dropping delta tables registered on AWS Glue

docs/src/main/sphinx/connector/iceberg.rst, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/IcebergRestCatalogConfig.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConfig.java
This PR adds support for configuring the `warehouse` [catalog property](https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/CatalogProperties.java#L29) for the REST Catalog which is part of the [REST Spec](https://github.com/apache/iceberg/blob/master/open-api/rest-catalog-open-api.yaml#L88).
N/A
=> Add support for Iceberg catalog warehouse property in REST

.github/actions/compile-commit/action.yml, .github/bin/prepare-check-commits-matrix.py, .github/workflows/ci.yml
Use GitHub cache to mark which workspace states compiled successfully.
For each successfully compiled tree hash we create a GH cache entry.
We use tree hashes instead of commit hashes to reuse cache when changes in commits are reorganized without changing the workspace.
This is the same as #15966
=> Improve check-commits and decrease build times

plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
Remove unnecessary override test in Phoenix connector test, Phoenix client could handle the `rowkey` by default.
Guess this test is added before the `CTAS` was supported in the client.
=> Remove unnecessary override test in Phoenix connector

core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Config.java, core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java, core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2Config.java, docs/src/main/sphinx/security/oauth2.rst, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oauth2-http-proxy/config.properties, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oauth2-https-proxy/config.properties, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oauth2-refresh/config.properties, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oauth2/config.properties, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oidc-refresh/config.properties, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oidc/config.properties, testing/trino-product-tests/src/main/java/io/trino/tests/product/jdbc/TestExternalAuthorizerOAuth2.java
Deprecate getting groups in Oauth2 authentication
This feature is not working properly and it is not possible to fix it.
The problem is widely understood impersonation:
- view SECURITY DEFINER
- sessionUser JDBC parameter
- identity from view expression for column masking and row filtering
Using Oauth2 is able to provide groups only during authentication.
However it is unable to provide groups for any impersonated user.
- Configuration property ``http-server.authentication.oauth2.groups-field`` got deprecated and it is about to be removed. In order to discourage the usage of it, it was renamed to ``deprecated.http-server.authentication.oauth2.groups-field``.
=> Deprecate getting groups in Oauth2 authentication

plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestHiveParquetWithBloomFilters.java
Implement Hive parquet bloomfilter prune test. 
This unit test can help to verify whether enabling hive parquet's parquet.use-bloom-filter option will help Trino to load fewer blocks(row-groups)
More details: https://github.com/trinodb/trino/pull/14428#discussion_r1042142774
```markdown
```
=> Implement Hive parquet bloomfilter prune test

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcMetadata.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcQueryBuilder.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcCachingConnectorSmokeTest.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingDatabase.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcClient.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java, plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupConfigurationManager.java, plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestResourceGroupsDao.java, pom.xml, testing/trino-testing/src/main/java/io/trino/testing/AbstractTestAggregations.java, testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java, testing/trino-testing/src/main/java/io/trino/testing/H2QueryRunner.java, testing/trino-tests/src/test/java/io/trino/execution/resourcegroups/db/H2TestUtil.java, testing/trino-tests/src/test/java/io/trino/tests/TestLocalQueries.java
Update H2 to 2.1.214
There are couple of significant changes to the H2 semantics:
- "key" and "value" are restricted keywords in H2 2.x as per: http://www.h2database.com/html/advanced.html#keywords
- maximum length of identifier (schema, table, colum name) is now 256: http://www.h2database.com/html/grammar.html#name
- maximum length of a varchar/char types is 1_000_000_000: http://www.h2database.com/html/datatypes.html#character_varying_type
- decimal(p, s) without scale is decimal(p, 0): http://www.h2database.com/html/datatypes.html#numeric_type
- arrays with mixed types elements are not longer supported: http://www.h2database.com/html/migration-to-v2.html
This version update solves also two critical CVEs:
- https://www.cvedetails.com/cve/CVE-2022-23221/
- …
=> Update H2 to 2.1.214

core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryStatistics.java
Simple clean up to the QueryStatistics class to have the POJO field names match the getters.
```markdown
```
=> Use matching field names in QueryStatistics

docs/src/main/sphinx/connector/delta-lake.rst, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeOutputTableHandle.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableProperties.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCheckpointsCompatibility.java
Fixes https://github.com/trinodb/trino/issues/15932
```markdown
* Allow updating `reader_version` and `writer_version` table properties. ({issue}`16165`)
```
=> Allow updating `reader_version` and `writer_version` properties for Delta tables

client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java, client/trino-cli/src/main/java/io/trino/cli/Console.java, client/trino-cli/src/main/java/io/trino/cli/InputReader.java, client/trino-cli/src/main/java/io/trino/cli/Pager.java, client/trino-cli/src/main/java/io/trino/cli/Query.java, client/trino-cli/src/test/java/io/trino/cli/TestInsecureQueryRunner.java, client/trino-cli/src/test/java/io/trino/cli/TestQueryRunner.java, docs/src/main/sphinx/client/cli.rst
Add CLI options for pager and history file, which previously could only be set using environmental variables. Having them available as options allows setting them in the configuration file.
Extracted from #12208 
=> Add CLI options for history file and pager

core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
There is incorrect indentation when there is  a `partitionCount` in a printed plan (look at screen). This PR addresses it.
=> Fix indent formatting in a printed plan

docs/release-template.md, docs/src/main/sphinx/release.rst, docs/src/main/sphinx/release/release-408.md
Assemble the release notes for the upcoming Trino 408 release. Fixes #16147 
@ebyhr #16026 ✅ rn ✅ docs
@raunaqmorarka #16141 ✅ rn ✅ docs
@ebyhr #16112 ✅ rn ✅ docs
@ebyhr #16127 ✅ rn ✅ docs
@martint #16157 ✅ rn ✅ docs
@ebyhr #16154 ✅ rn ✅ docs
@ebyhr #16168 ✅ rn ✅ docs
@ebyhr #16145 ✅ rn ✅ docs
@martint #15887 ✅ rn …
=> Add Trino 408 release notes

core/trino-main/src/main/java/io/trino/likematcher/DFA.java, core/trino-main/src/main/java/io/trino/likematcher/DenseDfaMatcher.java, core/trino-main/src/main/java/io/trino/likematcher/LikeMatcher.java, core/trino-main/src/main/java/io/trino/likematcher/Matcher.java, core/trino-main/src/main/java/io/trino/likematcher/NFA.java, core/trino-main/src/main/java/io/trino/likematcher/NfaMatcher.java, core/trino-main/src/main/java/io/trino/likematcher/Pattern.java, core/trino-main/src/main/java/io/trino/type/LikeFunctions.java, core/trino-main/src/test/java/io/trino/likematcher/TestLikeMatcher.java, core/trino-main/src/test/java/io/trino/operator/scalar/BenchmarkLike.java
Improve performance of LIKE matchers.
* Improves performance when compiling the NFA and DFA for the LIKE matcher
* Introduces an NFA-based matcher that's cheaper to construct to use when matching dynamic patterns.
Before this change, compilation times for the DFA vs Joni:
compileDFA    %abc%def%    1484095.662 ± 13372.922  ns/op
compileJoni   %abc%def%        767.662 ±     6.783  ns/op
Performance after this change (note that compilation for the DFA is now lazy, so that paid for on first match and amortized over multiple matches:
compileDFA     %abc%def%       128.121 ± 1.557  ns/op
compileNFA     %abc%def%       212.063 ± 3.552  ns/op
compileJoni    %abc%def%       779.040 ± 9.597  ns/op
Additionally, this is the relative amortized performance for calls to match in each of the …
=> Improve performance of LIKE matchers

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadSessionCreator.java
This issue appears when upgrading from `403` to `405`. 
BigQuery client session should use parent project id when creating a session. 
Fixes #15867
```markdown
```
=> Fix: use parent project id in BigQuery session

docs/src/main/sphinx/connector/delta-lake.rst, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadataFactory.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableProperties.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java
Follow up of https://github.com/trinodb/trino/pull/16165#discussion_r1113247631
```markdown
* Support setting default reader and writer versions using the `delta.default-reader-version` and 
`delta.default-writer-version` config properties. ({issue}`16208`)
```
=> Expose `delta.default-reader-version` and `delta.default-writer-version` delta lake configuration properties

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/TemporaryTables.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnector.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadataFactory.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTransactionHandle.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTransactionManager.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/DefaultBigQueryMetadataFactory.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java, plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java, testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
@hashhar discovered that BigQuery tests are leaving behind tmp_trino_* tables.
To start, I'm only pushing the enhancement to BaseFailureRecoveryTest that verifies there are no temporary tables left behind. This is so I can run the BigQuery FTE tests (which require secrets), to verify the test finds the temporary tables left behind, so I can verify the change to the BigQueryConnector fix the problem. I will add more context to this PR when I push that commit.
```markdown
```
=> Fix BigQuery FTE leaving temporary tables behind

testing/trino-product-tests-launcher/pom.xml, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/TestRun.java
After #15833 we saw a big increase in the duration of product tests jobs. Starting tests got stuck for 2–3 minutes before loading the tempto configuration. This only happens on amd64 hosts with 7 GB of memory. I found this section that explains why we set it to 10% before: https://docs.oracle.com/en/java/javase/17/gctuning/factors-affecting-garbage-collection-performance.html#GUID-7FB2D1D5-D75F-4AA1-A3B1-4A17F8FF97D0
I chose to increase `MaxHeapFreeRatio` to 50% because this is the lowest value when tests didn't get stuck. 
=> Allow product tests' framework to use more memory

lib/trino-hive-formats/src/main/java/io/trino/hive/formats/compression/CompressionKind.java, lib/trino-hive-formats/src/test/java/io/trino/hive/formats/FormatTestUtils.java
Add missing support for Hadoop `DefaultCodec` (a.k.a., `DEFLATE`) to Hive formats.
Fixes #16250
```markdown
* Add support for Hadoop `DefaultCodec` to Hive formats. ({issue}`16250`)
```
=> Add deflate codec to Hive formats

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
This patch fixes #16075 
I have taken the reference from the DefaultJdbcMetadata and it works with that approach.
Another workaround without the fix is always to alias the column names to be lowercase.
=> Fix failure when non-lowercase column exists in BigQuery query function

plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java, plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClientModule.java, plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseConfig.java, plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/TrinoToClickHouseWriteChecker.java, plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConfig.java, plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestingClickHouseServer.java, pom.xml
* Remove support for legacy driver in ClickHouse since it took more than 1 year after becoming the deprecation
* Upgrade ClickHouse JDBC driver to 0.4.1. Even the latest driver doesn't provide `ResultSetMetaData` for `query` pass-through table function
Fixes #16188
```markdown
* Remove support for legacy JDBC driver. ({issue}`16193`)
```
=> Remove support for legacy driver and upgrade to 0.4.1 in ClickHouse connector

plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/PhoenixQueryRunner.java, plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java, plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixTypeMapping.java, plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestingPhoenixServer.java
Update TestingPhoenixServer using SharedResource
```markdown
```
=> Update TestingPhoenixServer using SharedResource

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantDateTrunc.java
When simplifying `date_trunc` on date values, check it's indeed the date before evaluating the first operand. I.e. do cheaper check first.
=> Check argument type before evaluating expression

core/trino-main/src/main/resources/webapp/src/utils.js
Trino Web UI displays "EXTERNAL ERROR - ErrorCode Name" even if the query fails with an INTERNAL ERROR due to a missing break keyword in the switch case. 
Fixes #16249
=> Fix incorrect error message in Trino UI

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
In Hive it may well happen that a partition value
is written by the writer process as a string,
e.g. : `month=02`, even though the column is registered in Hive as an integer.
When updating the table or when doing `ANALYZE`, the output in Trino of the statistics computation though for the partition from the example above will be though `2`.
While creating/changing table statistics, the partition values are parsed to Trino `NullableValue`s in order to match, independently of canonicalization, the partition column grouping values from the output of the statistics computation.
Assume the following scenario:
- a Spark job outputs content grouped by month on the storage - the months smaller than `10` are prefixed with `0`
- an external table is created in hive using the `integer` type for the …
=> Fix ANALYZE when Hive partition has non-canonical value

plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Enable testAddAndDropColumnName test for ClickHouse connector
Added `createTableSqlForAddingAndDroppingColumn` in `BaseConnectorTest` for allowing connector to prepare the create table sql for test `testAddAndDropColumnName`.
=> Enable testAddAndDropColumnName test for ClickHouse

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveStorageFormat.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTableProperties.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/line/RegexFileWriterFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveClassNames.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveTestUtils.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestRegexTable.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
```markdown
* Add `regex` and `regex_case_insensitive` table properties for REGEX format . ({issue}`16271`)
```
=> Add REGEX to storage formats and missing table properties

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
`verifyUnsupportedTypeException` should be applied only to `CREATE TABLE` failures.
=> Fix testSetColumnTypes nested catch+verify

.github/workflows/ci.yml, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/DockerContainer.java, testing/trino-testing-containers/src/main/java/io/trino/testing/containers/ConditionalPullPolicy.java
The `build-pt` job needs to run `ptl suite describe` for all test suites to get a complete list of features used in every test environment. This does not require pulling all Docker images, but `testcontainers` do so by default. This PR allows to disable pulling images before starting containers. It should reduce the run time of the `build-pt` job by ~2 minutes and avoid running out of disk space on the node. No other PT job downloads all images.
=> Don't pull PT env images in build-pt job

.github/actions/compile-commit/action.yml
Export variables used by the download script in check-commits action. Otherwise, it'll use variables from the workflow from the latest commit instead of the checked out version of the `check-commits` action, which can cause failures.
=> Export variables used by the download script in check-commits action

docs/src/main/sphinx/connector/hive-security.rst, docs/src/main/sphinx/connector/hive.rst
This is one of 11 planned PRs to update object storage connector docs that modernize and organize object storage documentation. This first PR is a key reorganization that brings the Hive connector and Hive security page organization and table formats inline with other newer connectors, and stages information for further organization.
There are no content changes except to address headers with no introductory sentence.
```markdown
```
=> Reorganize Hive connector and Hive security documentation

client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java, client/trino-jdbc/src/test/java/io/trino/jdbc/BaseTestJdbcResultSet.java
As JDBC specification, if a data conversion fails, then a SQLException will be raised. But getBoolean will cause a ClassCastException.
Fixes #16296
=> Fix jdbc ResultSet getBoolean throw ClassCastException

plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java, plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java
Fix for ClickHouse sql injection
by removing ability to have expression in table options
```markdown
* Remove support for specifying expressions in `sample_by` table properties to prevent SQL injection. ({issue}`16261`)
```
=> Fix for ClickHouse sql injection by removing ability to have expression in table options

.github/bin/prepare-check-commits-matrix.py, .github/workflows/ci.yml
Allow the check-commits to be marked as success instead of skipped, so the list of checks in the web view of a PR can be collapsed by default.
=> Allow the check-commits to be marked as success instead of skipped

core/trino-main/src/main/java/io/trino/sql/analyzer/AggregationAnalyzer.java, core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, core/trino-main/src/test/java/io/trino/sql/planner/BenchmarkPlanner.java
Complementary to https://github.com/trinodb/trino/pull/16198.
Instead of creating `AggregationAnalyzer` for verifying each source column we reuse the analyzer for all source columns. Similar approach has been implemented for orderby column as well.
```markdown
```
=> Reuse AggregtaionAnalyzer when verifying source and orderby aggregations

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
=> Increase timeout to 1 minute for BigQuery access policy tests

core/trino-main/src/main/java/io/trino/cost/AggregationStatsRule.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestShowStats.java, testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchDistributedStats.java, testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchLocalStats.java
Show stats for final aggregation in EXPLAIN/EXPLAIN ANALYZE when partial aggregation is present.
Fixes https://github.com/trinodb/trino/issues/6323
```markdown
* Improve output of EXPLAIN queries to show statistics when the query contains aggregations. ({issue}`16201`)
```
=> Show stats in EXPLAIN/EXPLAIN ANALYZE with partial aggregation

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java, core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java, core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/MultipleDistinctAggregationToMarkDistinct.java, core/trino-main/src/test/java/io/trino/cost/TestOptimizerConfig.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestMultipleDistinctAggregationToMarkDistinct.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesPlans.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestOptimizeMixedDistinctAggregations.java, docs/src/main/sphinx/admin/properties-optimizer.rst
MarkDistinct is beneficial only when there is
a limited parallelism in query (e.g. global distinct aggregation is handled by a single thread).
For cases where there is enough parallelism, MarkDistinct hurts performance due to excessive data shuffle
and introducing multiple stages in case of
multiple distinct aggregations.
This PR also changes the type of `use_mark_distinct` session property and `optimizer.use-mark-distinct` config property from `Boolean` to `Varchar`. The new property still accepts `true` and `false` values to keep backwards compatibility but those have to be specified as Varchars (e.g. single quotes in the cli)
To test different possible approaches I used queries that use different count of distinct values in a group by and 1 or 2 distinct aggregations + one non distinct …
=> Use MarkDistinct only in limited cases

docs/src/main/sphinx/connector/delta-lake.rst, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadataFactory.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableProperties.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/MetadataEntry.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksChangeDataFeedCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCheckpointsCompatibility.java
Rather than require users upgrade the protocol version on their tables before using features which require newer versions of the spec, automatically determine which protocol version is required and upgrade the table to it.
Includes one commit from @homar's https://github.com/trinodb/trino/pull/16221
```markdown
* Infer required Delta Lake version when creating new tables or enabling new table features.
```
=> Infer required Delta Lake version from table features

core/trino-main/src/main/java/io/trino/cost/StatsNormalizer.java, core/trino-main/src/test/java/io/trino/cost/TestAggregationStatsRule.java, core/trino-main/src/test/java/io/trino/cost/TestStatsNormalizer.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/statistics/MetastoreHiveStatisticsProvider.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestShowStats.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/statistics/TestMetastoreHiveStatisticsProvider.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTableStatistics.java
```markdown
* Calculate ndv, min and max stats for partitioned columns when stats are unavailable in metastore. ({issue}`16229`)
```
=> Estimate hive partitioned column stats without row count stats

lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/PlainValueDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestData.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestingColumnReader.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/BinaryApacheParquetValueDecoder.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestByteArrayValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestFixedWidthByteArrayValueDecoders.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/AbstractTestParquetReader.java
Parquet files produced by Kafka Connect may contain FIXED_LEN_BYTE_ARRAY parquet type without any logical type annotation due to `org.apache.parquet.avro.AvroSchemaConverter` translating the FIXED Avro type into FIXED_LEN_BYTE_ARRAY.
Reading a FIXED_LEN_BYTE_ARRAY without logical type annotation as string/binary type is already supported in Apache Hive and Apache Spark.
```markdown
* Fix query failures on reading parquet files generated by Kafka Connect. ({issue}`16264`)
```
=> Support reading FIXED_LEN_BYTE_ARRAY as varchar/varbinary columns

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Support inserting default values in BigQuery
```markdown
* Add support for inserting default values. ({issue}`16327`)
```
=> Support inserting default values in BigQuery

docs/src/main/sphinx/security/kerberos.rst
- Fixes a small typo in the `access-control.properties` title on the Kerberos page
=> Fix typo in access control properties title

.github/workflows/stale.yml
We're having the stale bot running in Trino forks when the pull request isn't submitted to the main Trino, which... is bad and awkward.
=> Make stale action only run in Trino repo

core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java, docs/src/main/sphinx/sql/explain-analyze.rst, testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java
Add additional summary statistics on top level of EXPLAIN ANALYZE output
Example:
```
explain analyze select max(extendedprice) from lineitem;
Query Plan
--------------------------------------------------------------------------------------
Trino version: version
Queued: 3.00ms, Analysis: 485.81ms, Planning: 268.07ms, Execution: 7.37s
Fragment 1 [SINGLE]
(...)
```
```
* Show query queued, analysis, planning and execution time in EXPLAIN ANALYZE output. ({issue}`16329`)
```
=> Expose top level statistics in EXPLAIN ANALYZE

testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DeltaLakeTestUtils.java
Extend the retry policy used to drop Delta tables backed by AWS Glue via Databricks JDBC Driver to handle the case described in https://github.com/trinodb/trino/issues/13199#issuecomment-1447787619
Fixes https://github.com/trinodb/trino/issues/13199
=> Extend retry policy for dropping delta tables backed by AWS Glue on Databricks

core/trino-main/src/main/java/io/trino/operator/exchange/UniformPartitionRebalancer.java, core/trino-main/src/test/java/io/trino/operator/exchange/TestUniformPartitionRebalancer.java
Signed-off-by: zombee0 <flylucas_10@163.com>
We can assume that there were originally two writers and now there are three writers, so the load of each old writer is reduced by 1/3, and the load of the new writer is increased by 2/3.
before: writer0->100, writer1->100;
after:writer0->66, writer1->66; writer2->66;
```markdown
```
=> fix estimatedWrittenBytes bug

docs/src/main/sphinx/connector/cassandra.rst, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPageSink.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraRecordCursor.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraType.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTypeManager.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTypes.java, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraTypeMapping.java
Fixes #13063
```markdown
* Add support for `time` type. ({issue}`13063`)
```
=> Add support for time type in Cassandra

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcConfig.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestBaseJdbcConfig.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java
Missing table metadata can be configured to not get cached (`cacheMissing`), but that doesn't apply to schema and table name lists.
In certain cases it might be beneficial to shorten the list cache ttl for them to reflect the added schemas/tables faster, while specific table caches will automatically reload tables that were missing before.
```markdown
```
=> Allow different jdbc metadata cache ttls for schema and tables lists

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConnectorSmokeTest.java, plugin/trino-iceberg/src/test/resources/hdp3.1-core-site.xml.gcs-template
=> Add tests for trailing space in location for iceberg

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/InMemoryThriftMetastore.java, plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java
Cleanup of the codebase, prepare for https://github.com/airlift/airbase/pull/341
```markdown
```
=> Prefer qualified builder to static import

plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java, plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
=> Fix get tables not escape the wildcard chars in IgniteClient

plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java
Update Ignite table properties raw sql, we can get the primary key directly from sys.indexes.
=> Update Ignite getTableProperties implementation

plugin/trino-hive/src/main/java/io/trino/plugin/hive/aws/athena/PartitionProjectionService.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
Fix handling of `partition_projection_location_template` table property mapped from `storage.location.template` hive table property.
When template contained upper case characters S3 List Objects operations was not returning any objects which resulted in 0 results queries. This was caused by lowercasing Trino table property during convertion to Hive table property.
```markdown
* Fix handling of `partition_projection_location_template` table property when uppercase characters are used
```
=> Fix Partition Projection storage location

client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java, core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java, core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushPredicateIntoTableScan.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestRemoveEmptyUnionBranches.java, core/trino-main/src/test/java/io/trino/sql/planner/planprinter/TestJsonRepresentation.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestConnectorPushdownRulesWithHive.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/optimizer/TestConnectorPushdownRulesWithIceberg.java, testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
`PushPredicateIntoTableScan` rule invokes `pushFilterIntoTableScan` with `pruneWithPredicateExpression=false`. AddExchanges invokes this with pushFilterIntoTableScan=true, seems like the reason being that we've more control over the # of times such a potentially expensive optimization is invoked through a visitor based optimizer. 
Because of this - there can be cases where predicate-expression based pruning only happens during AddExchanges - leaving us with empty values node at this stage. And if that ends up on the left side of a replicated join - we end up in a situation where a single task is doing a join with LHS being local empty values node and RHS being a remote scan.
This PR adds an invocation of `pushFilterIntoTableScan` with `pruneWithPredicateExpression=true` before …
=> Remove empty values node after predicate-expression based pruning

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadataFactory.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/RegisterTableProcedure.java
Origin of this change is to migrate to `TrinoFileSystem`
Relates to https://github.com/trinodb/trino/issues/16020
(x ) This is not user-visible or docs only and no release notes are required.
```markdown
```
=> Remove unnecessary directory checks in delta lake

docs/src/main/sphinx/connector/googlesheets.rst, plugin/trino-google-sheets/pom.xml, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetNotFoundException.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsClient.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsConfig.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsConnector.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsConnectorTableHandle.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsMetadata.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsModule.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsNamedTableHandle.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsSheetTableHandle.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsSplit.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsSplitManager.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsTable.java, plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/ptf/Sheet.java, plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/SheetsQueryRunner.java, plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestGoogleSheets.java, plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestGoogleSheetsWithoutMetadataSheetId.java, plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestSheetsConfig.java, plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestSheetsConnectorTableHandle.java, plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestSheetsPlugin.java
Supports `sheet` table function for the google sheets connector. 
Allows querying google sheets directly by id instead of requiring a metadata sheet mapping. 
Also makes the `gsheets.metadata-sheet-id` config optional since the sheet table function makes it no longer strictly required.  
N/A
```markdown
* Add `sheet` table function to the connector. ({issue}`12502`)
```
=> Support sheet table function for google sheets connector

docs/src/main/sphinx/connector/hive.rst
=> Improve Hive documentation

plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/TrinoS3ClientFactory.java
For now, when [S3 Select Pushdown](https://trino.io/docs/current/connector/hive-s3.html#s3-select-pushdown) is enabled, we could not access data by assume role, this is because TrinoS3ClientFactory doesn't support STSAssumeRoleSessionCredentialsProvider. However in some scenarios we need the both features, so it would be nice to support sts-assume for S3 select, furthermore, maybe [S3 Security Mapping](https://trino.io/docs/current/connector/hive-s3.html#s3-security-mapping) could be added to TrinoS3ClientFactory too.
#5947 
```markdown
* Fix Add Support AWS STS for S3 Select. …
```
=> Add Support AWS STS for S3 Select

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
Fixes https://github.com/trinodb/trino/issues/6295
```markdown
* Respect `hive.timestamp-precision` in Hive views ({issue}`issuenumber`)
```
=> Respect `hive.timestamp-precision` in Hive views

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
While computing the statistics, it may very well happen that the number of partitions in the table will change (partitions get added/dropped). Avoid failing the `ANALYZE` operation because of inequality of the number of computed partition statistics vs existing table partitions.
In some situations it may happen that `ANALYZE table` operation is failing with the message
```
All computed statistics must be used
```
If the number of the partitions of the table changes between the time when the computing of the partitions  stats has started and when it ended, this exception is likely to appear.
Avoid the failure of the operation by dropping the verification for the  equality of the number of computed partition statistics vs existing table partitions.
(x) This is not user-visible or docs only …
=> Drop the check regarding the presence of all computed partition statistics

client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java, core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java, testing/trino-tests/src/test/java/io/trino/tests/TestInformationSchemaConnector.java
=> Filter `information_schema` within engine

core/trino-spi/src/main/java/io/trino/spi/function/FunctionProvider.java, testing/trino-tests/src/test/java/io/trino/tests/TestTableFunctionInvocation.java
For example, a connector providing table functions needs to implement only the `FunctionProvider.getTableFunctionProcessorProvider` method.
=> Make FunctionProvider interface methods optional

core/trino-main/src/main/java/io/trino/operator/Operator.java, core/trino-main/src/main/java/io/trino/operator/OrderByOperator.java, core/trino-main/src/main/java/io/trino/operator/PagesIndex.java
The `Operator.startMemoryRevoke` API promises that no processing methods
are called before memory revoking is done (`finishMemoryRevoke`).  Since
8c9df8268c2fa215ada65c67dad15d22e108871e, 7d1157312873e83d9fa662855416bc21427cdf42 and cf50577d755c943f70dc9de01cfd6c2545c8fb3d `finish` is the only processing
method that can be called between `startMemoryRevoke` and
`finishMemoryRevoke`.
`OrderByOperator` had a concurrency-like bug because it did not handle
well the case when invocation order is `startMemoryRevoke`, spill
completes, `finish`, `finishMemoryRevoke`. During `finish` the operator
gets an iterator over `PagesIndex` which becomes invalidated when
`finishMemoryRevoke` clears the `PagesIndex`.
The commit fixes that by adding explicit wait for `finishMemoryRevoke`
inside …
=> Fix OrderByOperator.finish to wait for finishMemoryRevoke

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableName.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableName.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergRedirectionToHive.java
This is a small usability improvement which aims to provide a more meaningful error message to the user in case that the user asks for an invalid metadata table corresponding to an existing Iceberg table.
```
assertQueryFailure(() -> onTrino().executeQuery("TABLE iceberg.default.\"" + tableName + "$invalid\""))
.hasMessageMatching("\\QQuery failed (#\\E\\S+\\Q): Table '" + icebergTableName + "$invalid' redirected to '" + hiveTableName + "$invalid', but the target table '" + hiveTableName + "$invalid' does not exist");
```
=> Retrieve the table handle only when dealing with a system table

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapCastInComparison.java, core/trino-main/src/test/java/io/trino/sql/planner/AbstractPredicatePushdownTest.java, core/trino-main/src/test/java/io/trino/sql/planner/TestUnwrapCastInComparison.java
Coerce `NullLiteral` to boolean type in `UnwrapCastInComparison` otherwise `PredicatePushDown` rule could throw an error while creating `FilterNode` with `NullLiteral` as a predicate. This is because `FilterNode` cannot be created with just `NullLiteral` without proper coercions.
Steps to reproduce the issue in the current version:
```
CREATE TABLE sample_table_1 (a smallint, b varchar);
CREATE TABLE sample_table_2 (a smallint, b varchar);
WITH t AS (SELECT a,
CASE 
WHEN b = 'ABCD' THEN 'ABC'
ELSE 'CDB' END AS channel 
FROM sample_table_2 t2)
SELECT * FROM sample_table_1 t1 JOIN t ON t1.a = t.a WHERE channel = 'TESTING';
```
Error: `Query 20230308_141912_00008_fy4xb failed: Predicate must be an expression of boolean type: null`
( ) This is not user-visible or docs only and no release …
=> [FIX] Coerce NullLiteral to boolean in UnwrapCastInComparison

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorSmokeTest.java
Support inserting into Delta Lake table having invariants
```markdown
* Add support for inserting into tables having [column invariants](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#column-invariants). ({issue}`16136`)
```
=> Support inserting into Delta Lake table having invariants

core/trino-main/src/main/java/io/trino/operator/LeafTableFunctionOperator.java, core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ImplementTableFunctionSource.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddLocalExchanges.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/SymbolMapper.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/UnaliasSymbolReferences.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/TableFunctionNode.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/TableFunctionProcessorNode.java, core/trino-main/src/test/java/io/trino/connector/TestingTableFunctions.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java, core/trino-spi/src/main/java/io/trino/spi/ptf/TableFunctionProcessorProvider.java
Add ConnectorSession as an argument to `TableFunctionProcessorProvider. getSplitProcessor`
and initialize it correctly in `LeafTableFunctionOperator`
```markdown
```
=> Add ConnectorSession to TableFunctionProcessorProvider#getSplitProcessor

plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java, plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
Fix [16396](https://github.com/trinodb/trino/issues/16396)
```markdown
* Support predicate pushdown with like in Ignite. ({issue}`16396`)
```
=> Support predicate pushdown with like in Ignite

plugin/trino-bigquery/pom.xml
The existing maven-surefire-plugin plugin overrides configurations in root pom.xml.
Same as https://github.com/trinodb/trino/pull/16449 but for BigQuery.
=> Use air.test.jvm.additional-arguments in BigQuery

.github/bin/redshift/delete-aws-redshift.sh, .github/bin/redshift/setup-aws-redshift.sh, .github/workflows/ci.yml, .gitignore, plugin/trino-redshift/README.md, plugin/trino-redshift/pom.xml, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/RedshiftQueryRunner.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorSmokeTest.java
Use an ephemeral/throw-away Redshift cluster for running integration tests on `trino-redshift` connector.
Once the tests are run, the testing Redshift cluster is being reclaimed.
The Redshift cluster is publicly accessible in order to be accessible from the general purpose Github runners.
=> Add CI infrastructure for `trino-redshift`

plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java, plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
Throw TableNotFoundException when SQLServer error is 208. Relates to #10846. 
=> Throw `TableNotFoundException` when SQLServer error is 208

.github/workflows/ci.yml, plugin/trino-redshift/pom.xml
Fix CI failure on master https://github.com/trinodb/trino/actions/runs/4374451893/jobs/7653896692
=> Fix test-other-modules failure due to lack of Redshift secrets

core/trino-main/src/main/java/io/trino/operator/join/BigintPagesHash.java, core/trino-main/src/main/java/io/trino/operator/join/DefaultPagesHash.java, core/trino-main/src/main/java/io/trino/operator/join/JoinHashSupplier.java
Just a simple refactoring
```markdown
```
=> Extract meaningful methods in join operator

.github/workflows/annotate.yml
Fixes `huge input` errors. This workflow doesn't run in PRs so we can merge this as is.
=> Update action-surefire-report to fix processing large report files

.github/bin/download-maven-dependencies.sh
Avoid printing ~130k lines like
```
2023-03-10T03:46:16.0638139Z [INFO] Resolved plugin: maven-compiler-plugin-3.11.0.jar
```
=> Avoid CI log spam when downloading dependencies

core/trino-main/src/main/java/io/trino/json/PathEvaluationVisitor.java, core/trino-main/src/test/java/io/trino/json/TestJsonPathEvaluator.java
Previously, separate IDs were generated for each member.
Note that the tests pass without this fix due to an AssertJ bug that seems to cause the assertion comparisons not to work. This is fixed by upgrading AssertJ in #16420.
```markdown
* Fix generation of IDs for `keyvalue()` methods in [JSON path](json-path-language).
Previously, separate IDs were generated for each member. ({issue}`16482`)
```
=> Fix generation of JSON path keyvalue() IDs

core/trino-main/src/main/java/io/trino/json/PathEvaluationVisitor.java, core/trino-main/src/test/java/io/trino/json/TestJsonPathEvaluator.java, plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHive.java, pom.xml, testing/trino-tests/src/test/java/io/trino/tests/BaseQueryAssertionsTest.java, testing/trino-tests/src/test/java/io/trino/tests/TestLocalQueryAssertions.java
=> Update to Airbase 134

plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveTestUtils.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/rubix/TestRubixCaching.java
The `rubixEnabledConfig` was ignored.
=> Remove bogus overload in tests

testing/trino-tests/src/test/java/io/trino/sql/planner/BaseCostBasedPlanTest.java
Engineers will typically check out the repo into a local folder named the same way: `trino`. This, however, doesn't work when an engineer needs to do a second checkout, or wants to make a backup of the repo for whatever purposes. The build and tests should not assume any particular name of the folder the repo is checked out into.
=> Don't enforce top-level repo name in BaseCostBasedPlanTest

core/trino-main/src/main/java/io/trino/sql/planner/CompilerConfig.java
- Within Config class, `@ConfigDescription` should be used, not `@Description`
=> Correct misuse of Description annotation in Config

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
When supplying a partition predicate on a Delta table which has column mapping set to 'name' to the `DeltaLakeSplitManager` the values of the partition predicate are not resolved to the physical name but the name of the column. 
Without the above patch, any query with a where clause on the partition column will fail with the following stack-trace:
https://pastebin.com/PcK3WG8P
=> Deserialize partition value by physical name for Delta connector

plugin/trino-redshift/pom.xml, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorTest.java
Changelog
https://github.com/aws/amazon-redshift-jdbc-driver/blob/master/CHANGELOG.md#v21011-2023-02-03
This new version of the JDBC AWS Redshift driver includes relevant bug fixes for Trino specific scenarios:
- https://github.com/aws/amazon-redshift-jdbc-driver/pull/74
- https://github.com/aws/amazon-redshift-jdbc-driver/pull/75
Thank you @ssheikin  for your contribution.
=> Bump redshift-jdbc42 to 2.1.0.12

testing/trino-testing-services/src/test/java/io/trino/testng/services/TestSharedResource.java
Add test for https://github.com/trinodb/trino/pull/16260
=> Add test for SharedResource

lib/trino-hive-formats/src/main/java/io/trino/hive/formats/compression/CompressionKind.java, lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/text/TextLineReaderFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/line/LinePageSourceFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
Do not verify length when determining if a file is split and instead only check that start offset is zero.  This is because Hive supports replacing files during a query, and users take advantage of this.  This check is still correct, because a split file necessarily has second split that will have a non-zero start offset.
For all native file formats, hardcode the handling of the isSplittable check as it is a behavior of the code and not the file format.
Fixes #16492 
Fixes #16510 
```markdown
* Fix support for text formats with single header row when the file is split. …
```
=> Fix overly restrictive correctness checks in native line readers

plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
=> Add Hive tests for trailing space in location

docs/src/main/sphinx/connector/iceberg.rst, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-iceberg/pom.xml, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/IcebergFileMetastoreCatalogModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/IcebergGlueCatalogModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/IcebergHiveMetastoreCatalogModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMigrateProcedure.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java
Add support for `migrate` procedure in Iceberg.
Spark implementation is https://github.com/apache/iceberg/blob/dbb8a404f6632a55acb36e949f0e7b84b643cede/spark/v3.1/spark/src/main/java/org/apache/iceberg/spark/actions/BaseMigrateTableSparkAction.java
Fixes #13196
```markdown
* Add support for `migrate` procedure that converts a Hive table to a Iceberg table. ({issue}`13196`)
```
=> Add support for `migrate` procedure in Iceberg

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java, core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java, core/trino-main/src/test/java/io/trino/sql/planner/TestMaterializedViews.java, core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java, core/trino-main/src/test/java/io/trino/sql/query/TestFilterInaccessibleColumns.java, core/trino-main/src/test/java/io/trino/sql/query/TestRowFilter.java, core/trino-spi/src/main/java/io/trino/spi/security/ViewExpression.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/CatalogTableAccessControlRule.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/TableAccessControlRule.java, lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedConnectorAccessControlTest.java, lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedSystemAccessControlTest.java, testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Allow ViewExpression use session user explicitly
Before the change if access control is not returning any dedicated user to evaluate
the view expression they just pass the session user. However for the
engine it is not clear that is a session user and so engine needs to
retrieve groups for that user again and possibly some session roles are
lost.
After this change access control may decide to return empty identity.
That would be in line of view SECURITY INVOKER. Then engine can simply
reuse the session identity.
=> Allow ViewExpression use session user explicitly

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
This allows to connect to the running Trino instance using JDK Mission Control and capture Java Flight Recorder recordings.
```markdown
```
=> Expose JMX RMI in product tests

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/FilesTable.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Fixes https://github.com/trinodb/trino/issues/16473
```markdown
* Fix failure when `$files` system table contains non-null values on `key_metadata`, `split_offsets`, and `equality_ids` columns. ({issue}`16473`)
```
=> Fix FilesTable for non-null key_metadata, split_offsets, equality_ids

core/trino-main/src/main/java/io/trino/operator/scalar/MathFunctions.java, core/trino-main/src/test/java/io/trino/operator/scalar/TestMathFunctions.java, docs/src/main/sphinx/functions/list-by-topic.rst, docs/src/main/sphinx/functions/list.rst, docs/src/main/sphinx/functions/math.rst, testing/trino-product-tests/src/main/resources/sql-tests/testcases/math_functions/checkMathFunctionsRegistered.result
Fixes #16494
```markdown
* Add {func}`sinh` function. ({issue}`16494`)
```
=> Add `sinh` function to return hyperbolic sine

docs/src/main/sphinx/security/file-system-access-control.rst
Cole logged a Trino ticket for docs but they were already done as part of the code PR listed below. Reviewed that with Cole and made his suggested edits to the new text (release in 405).
https://github.com/trinodb/trino/pull/14962/files
=> Impersonation string edits

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/TestRun.java
Log impacted features
This is helpful in CI to understand the context on how tests are
executed.
Impacted features are passed as a log file and then they are passed from
suite to test run, so logging them here make sure if everything is
passed correctly.
=> Log impacted features

testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
This fixes the issue described in https://github.com/trinodb/trino/issues/16277
Because `information_schema` is not strictly consistent with recently dropped tables among all connectors, but _querying_ recently dropped tables _is_ consistent, this no longer relies on `SHOW TABLES LIKE` returning no results, but instead, actually attempts to query the recently dropped temporary table, and expects there to be a "does not exist" exception.
```markdown
```
=> Fix BaseFailureRecoveryTest temp table checking flakiness #16277

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetastoreClosure.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTableHandle.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/statistics/MetastoreHiveStatisticsProvider.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/MockThriftMetastoreClient.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/statistics/TestMetastoreHiveStatisticsProvider.java
`HiveTableHandle` contains the list of projected columns. Since only projected columns will be available to the engine, `HiveMetadata.getTableStatistics` can return statistics limited to those columns.
This also requires `CachingHiveMetastore` to support caching statistics for a subset of table columns.
I tested the change on the glue metastore and table with 100 columns (details below) with caching stats disabled (`hive.metastore-stats-cache-ttl=0s)` and a simple query (`select count(c1)  from test_col_stats_part`) where planning dominates.
There is a difference of about 20% for planning time/elapsed (so visible)
baseline 2.251s on average and only required stats 1.853s
This would have a potentially higher impact on a metastore under heavy load.
The table used:
```
create table …
```
=> Get stats from hive metastore only for the necessary columns 

core/trino-main/src/main/java/io/trino/metadata/MetadataListing.java, core/trino-main/src/test/java/io/trino/connector/MockConnector.java, core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseCaseInsensitiveMappingTest.java, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java, plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java, testing/trino-tests/src/test/java/io/trino/tests/TestInformationSchemaConnector.java
Depending on the client that initiated a metadata query, error messages returned from `ConnectorMetadata` can be confusing for users. For example, a query to `system.jdbc` tables with no catalog predicate, on exceptions in the catalog, will propagate those exceptions, with no way for the user to know which catalog has thrown that exception.
When there are a lot of catalogs, this makes investigating the issue very hard for Trino admins. We can make it easier by always including the problematic catalog's name in the error message.
```markdown
* Improve error message on exceptions thrown by connector while querying metadata. ({issue}`issuenumber`)
```
=> Improve error message for catalog errors when listing metadata

client/trino-cli/pom.xml, client/trino-client/pom.xml, client/trino-jdbc/pom.xml, pom.xml
Updates airlift units dependency to version 1.8, which now requires JDK11+. As a result, a minor improvement to reduce allocations during JSON serialization / deserialization was made possible.
Unfortunately, since Trino clients still currently support JDK 8- airlift units version 1.7 is still used in `trino-client`, `trino-cli`, and `trino-jdbc`.
No non-technical explanation should be necessary.
=> Update airlift units to 1.8

plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduSplitManager.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotLegacyDataFetcher.java, plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/DatabaseShardManager.java, plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/DatabaseShardRecorder.java
Ensures that the current thread's interrupted state is reset when an `InterruptedException` is caught and a different exception is re-thrown in `KuduSplitManager`, `PinotLegacyDataFetcher`, and legacy raptor `DatabaseShardManager`/`DatabaseShardRecorder`.
=> Fix InterruptedException in miscellaneous connectors

lib/trino-phoenix5-patched/pom.xml, plugin/trino-phoenix5/pom.xml, plugin/trino-pinot/pom.xml, pom.xml
=> Update to Jersey 2.39

docs/src/main/sphinx/connector/iceberg.rst, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/RefsTable.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableType.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/PageListBuilder.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Support refs system table in Iceberg
Users can query the system table with:
```
SELECT * FROM "table$refs"
```
The schema is the same as the one in Iceberg repo: https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/RefsTable.java
=> Support Iceberg refs system table

core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ReplaceJoinOverConstantWithProject.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestReplaceJoinOverConstantWithProject.java, core/trino-main/src/test/java/io/trino/sql/query/TestJoin.java
fixes https://github.com/trinodb/trino/issues/16512
The incorrect result was caused by the Optimizer rule `ReplaceJoinOverConstantWithProject`, which inlined a non-deterministic expression (in this case, `uuid()`), causing it to be evaluated separately for every row.
```markdown
* Fix potential incorrect result in queries involving join and a non-deterministic value. ({issue}`16512`)
```
=> Do not inline non-deterministic expressions as projection

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableHandle.java
Remove unused methods from `DeltaLakeTableHandle`
=> Remove unused methods from `DeltaLakeTableHandle`

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAnalyze.java
=> Add clean up for DeltaLake ANALYZE tests

core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapYearInComparison.java, core/trino-main/src/test/java/io/trino/sql/planner/TestUnwrapYearInComparison.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ConstraintExtractor.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestConstraintExtractor.java
Simplify predicates involving `year` function likes `UnwrapDateTruncInComparison`. 
Continuation of #15306
```markdown
* Improve performance of queries that contain predicates involving `year` function. ({issue}`14078`)
```
=> Simplify predicates involving year function

core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java, plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java, plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java, plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java, plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
Fixes #16225
```markdown
* Fix failure when `query` table function contains column alias. ({issue}`16225`)
```
=> Fix failure when query table function contains column alias in JDBC connectors

docs/src/main/sphinx/client/cli.rst
Specifically the usage of quotes seems necessary since we hear from users stumbling over password values with $ and other values. 
=> Add example for TRINO_PASSWORD usage

plugin/trino-hive/src/main/java/io/trino/plugin/hive/GenericHiveRecordCursor.java
Even when no columns are accessed for a scan, GenericHiveRecordCursor pays the cost of deserializing the record - which is never used to get values out. This change avoids that deserialization and improves performance for count(const) or count(*) queries on formats that use GenericHiveRecordCursor. 
Practically observed ~3x-4x improvement in CPU consumption for some queries. 
We still need to fetch the data as long as we're dependent on RecordReader API since it doesn't provide a way to get counts.
Test exists in `BaseHiveConnectorTest#testReadNoColumns`
```markdown
* Improve …
```
=> Avoid deserialization when no columns are needed

docs/src/main/sphinx/develop/table-functions.rst, docs/src/main/sphinx/functions/table.rst
This change adds information about all types of arguments supported by table functions to both developer guide and user guide. Also, the developer guide is updated with the new way of executing table functions involving the operator.
Follow-up to: https://github.com/trinodb/trino/pull/15575
No release notes required. Only docs change.
=> Update documentation for table functions

core/trino-main/src/main/java/io/trino/operator/output/PagePartitioner.java, plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleNodePartitioningProvider.java
It ignored `position` and didn't check for null, so could fail.
Even if this doesn't matter for blackhole connector, the code could be used as inspiration for other bucketing function implementations.
=> Fix hashing in BlackHoleNodePartitioningProvider

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
=> Prevent Hive from returning table handles for Hudi tables

core/trino-main/src/main/java/io/trino/operator/OrderByOperator.java
Changes `OrderByOperator#getOutput()` to use `Page#getColumns(outputChannels)` instead of building an array of output blocks itself, which avoids an extra allocation.
=> Avoid extra allocation in OrderByOperator#getOutput()

docs/src/main/sphinx/connector/hive.rst
This changes the catalog name examples in the Hive documentation to "example". This change makes the Hive connector page in line with the other connector pages and their catalog examples.
```markdown
```
=> Update Hive catalog example name documentation

core/trino-main/src/main/java/io/trino/spiller/FileSingleStreamSpiller.java, core/trino-main/src/test/java/io/trino/spiller/TestFileSingleStreamSpiller.java
Avoids retaining spill to disk encryption keys as part of `FileSingleStreamSpiller` instances after they are closed or the final read-back begins, making them unreachable and eligible for garbage collection sooner.
=> Eagerly discard FileSingleStreamSpiller encryption keys

core/trino-main/src/main/java/io/trino/execution/buffer/PageDeserializer.java, core/trino-main/src/test/java/io/trino/execution/buffer/TestPagesSerde.java
Previously we were not accounting for bytesPreserved.
With recent check added to aircompressor code
(https://github.com/airlift/aircompressor/commit/127b7f3c6330e6cc595f10648b68a197974b50bf)
it started manifesting as java.lang.IllegalArgumentException.
This is strictly validation fix. The passed array was not filled beyond
allocated size.
fixes: https://github.com/trinodb/trino/issues/16541
```markdown
```
=> Set maxOutputLength correctly

core/trino-main/src/test/java/io/trino/connector/MockConnector.java, core/trino-spi/src/main/java/io/trino/spi/connector/FixedSplitSource.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSplitManager.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java, plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchSplitManager.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitManager.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSplitManager.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotSplitManager.java
=> Add FixedSplitSource constructors

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/SharedHiveMetastoreCache.java
Some deployments might had hive.metastore-cache-ttl already set. https://github.com/trinodb/trino/pull/15811 introduced new config hive.metastore-stats-cache-ttl which could be lower (by default) for such deployments. However, hive.metastore-cache-ttl should take precedense over hive.metastore-stats-cache-ttl as it's more generic (affects whole metastore cache).
```markdown
* Make `hive.metastore-stats-cache-ttl` always greater or equal to `hive.metastore-cache-ttl`. ({issue}`issuenumber`)
```
=> Make hive.metastore-stats-cache-ttl >= to hive.metastore-cache-ttl

core/trino-main/src/main/java/io/trino/operator/aggregation/LongDoubleState.java, core/trino-main/src/main/java/io/trino/operator/aggregation/LongLongState.java, testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerWithSplits.java
Previously row(bigint, boolean, bigint, boolean)] was used for long sum serde (and similar for doubles).
Now it's row(bigint, bigint)
The extra bigint (row count) is still only required for WINDOW function but this PR slighly improves serde.
We can remove extra booleans because Long and Decimal aggregations use row count to determine if null should be outputted.
RN
```
General
* Improve `sum` aggregtion query performance. ({issue})
```
```markdown
```
=> Improve LongSumAggregation and DoubleSumAggregation serde

core/trino-main/src/main/java/io/trino/execution/QueryManagerStats.java
=> Remove unused method from QueryManagerStats

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/RegisterTableProcedure.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/MetaDirStatisticsAccess.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/MissingTransactionLogException.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TableSnapshot.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogParser.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogUtil.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriterManager.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TransactionLogTail.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogWriter.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeRegisterTableProcedureTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakeUtils.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTableSnapshot.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTransactionLogParser.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointWriter.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestTransactionLogTail.java
Origin of this change is to migrate to TrinoFileSystem
Relates to https://github.com/trinodb/trino/issues/16020
Some hadoop.fs.Path will be migrated in following PR as it needs some additional path resolution functions.
=> Replace usage of hadoop.fs.Path with String in Delta Lake

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAnalyze.java
Currently when column is added when statistics are present total size is not collected for newly added column.
NDV statistics works fine.
Currently:
```
create table test (varchar_1 VARCHAR);
insert into test values ('a');
analyze test;
alter table test add column varchar_2 varchar;
insert into test values ('b','c');
analyze test;
show stats for test;
```
```
column_name | data_size | distinct_values_count | nulls_fraction | row_count | low_value | high_value
-------------+-----------+-----------------------+----------------+-----------+-----------+------------
varchar_1   |       2.0 |                   2.0 |            0.0 |      NULL | NULL      | NULL
varchar_2   |      NULL |                   1.0 |            0.1 |      NULL | NULL      | NULL
NULL        |      NULL | …
```
=> Add statistics collection for added column

plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java, plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
Adds a check to validate that the column names defined in primary_key table property exists as column names in the table definition.
Fixes #16215
=> [trino-ignite] Ensure primary_key columns exist while creating table

docs/src/main/sphinx/connector/hudi.rst, plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java, plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiSplitSource.java, plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiTableName.java, plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiUtil.java, plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/TableType.java, plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/TimelineTable.java, plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiSystemTables.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeHudi.java, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hudi/hive.properties, testing/trino-product-tests/src/main/java/io/trino/tests/product/hudi/TestHudiSparkCompatibility.java
Fix #16149
+ add the Timeline table to show commits in Hudi connector
```markdown
* Add a `$timeline` system table which can be queried to inspect Hudi table timeline. ({issue}`16149`)
```
=> Add a metadata table showing commits in Hudi connector

core/trino-main/src/test/java/io/trino/sql/planner/AbstractPredicatePushdownTest.java
https://github.com/trinodb/trino/pull/16444#issuecomment-1461108134
=> Refactor PredicatePushdown test with simpler query

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
Add generated expression to extra info in Delta Lake
```markdown
* Add generated expression to `Extra` column in `DESCRIBE` and `SHOW COLUMNS` results. ({issue}`16631`)
```
=> Add generated expression to extra info in Delta Lake

testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
The expected exception message pattern needs to match the one used in `StatementAnalyzer.Visitor#visitTable`, e.g. the table name should be expected in apostrophes.
This should fix errors on CI like the one below (https://github.com/trinodb/trino/actions/runs/4467931974/jobs/7848093602)
```
Error:  io.trino.plugin.bigquery.TestBigQueryTaskFailureRecoveryTest.testParallel[testExplainAnalyze](9)  Time elapsed: 107.3 s  <<< FAILURE!
java.lang.AssertionError:
[There should be no remaining tmp_trino tables that are queryable. They are:
For queryId [20230320_124434_00162_6w4f2] (prefix [tmp_trino_3a3f1a6f_]) remaining tables: [tmp_trino_3a3f1a6f_e3d45e3f]
With errors: [
Expecting throwable message:
"line 1:15: Table 'bigquery.tpch.tmp_trino_3a3f1a6f_e3d45e3f' does not exist"
to contain: …
```
=> Fix BaseFailureRecoveryTest temp table checking message pattern

testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
Add test for identity column in Delta Lake connector
=> Add test for identity column in Delta Lake connector

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSource.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/CharCoercer.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveCoercionPolicy.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnPartitionedTable.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnUnpartitionedTable.java
Add support  for coercing from 
- char to bigger char
- char to smaller char
Similar to #5530
```
* Support coercion between `char` types of different lengths.
```
=> Support coercing char types of different lengths in hive

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoTableHandle.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ptf/Query.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTableHandle.java
Fix incorrect result when MongoDB query function contain helper function
```markdown
* Fix incorrect result when MongoDB `query` table function contains helper functions. ({issue}`16626`)
```
=> Fix incorrect result when MongoDB `query` table function contains helper functions

docs/src/main/sphinx/connector/jdbc-common-configurations.fragment
We had a [Slack question](https://trinodb.slack.com/archives/C0305TQ05KL/p1679065255177109) about the unclear way to configure one of the properties in this fragment. I've linked to the docs on what a duration is to make things more clear.
=> Add link to duration prop type in JDBC config fragment

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryAvroConnectorTest.java
Some column names started to fail because of BigQuery internal change
~ between
18:00 16 of March 2023 GMT and
00:00 17 of March 2023 GMT,
first noticed when 90d6f0737a1f8dd4fbb8b85c2d95b20093d1b4ba merged to
master.
Fixes #16603
=> Fix BigQuery tests for column names with special characters

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java
Under concurrently, H2 sometimes returns null table name in `DatabaseMetaData.getTables`'s `ResultSet`.
Fixes https://github.com/trinodb/trino/issues/16658
=> Disable testReadMetadataWithRelationsConcurrentModifications on H2 because of flakes

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcClient.java, plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java, plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java, plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java, plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java, plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java, plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java, plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClient.java, testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
- BaseJdbcClient cleanup
- Make FTE test concurrency customizable
=> BaseJdbcClient and FTE test cleanup

docs/src/main/sphinx/connector/delta-lake.rst, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/DeltaLakeMetastore.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/DeltaLakeMetastoreModule.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/DropExtendedStatsProcedure.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/FlushMetadataCacheProcedure.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFlushMetadataCacheProcedure.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestingDeltaLakeMetastoreModule.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/DecoratedHiveMetastoreModule.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveMetastoreModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/IcebergFileMetastoreCatalogModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/IcebergHiveMetastoreCatalogModule.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestingIcebergFileMetastoreCatalogModule.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestingIcebergHiveMetastoreCatalogModule.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeActiveFilesCache.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DeltaLakeTestUtils.java
Relates to https://github.com/trinodb/trino/issues/13737
```markdown
* Flush internal caches of table snapshots and active data files with `flush_metadata_cache` procedure. ({issue}`16466`)
```
=> Flush transaction log cache in Delta `flush_metadata_cache` procedure

docs/src/main/sphinx/connector/pinot.rst, plugin/trino-pinot/pom.xml, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotDataFetcher.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotDataTableWithSize.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotGrpcDataFetcher.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotLegacyDataFetcher.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotExpressionRewriter.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotPatterns.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotSqlFormatter.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotTransformFunctionTypeResolver.java, plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java, plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java, pom.xml
Upgrade pinot libraries to the latest version.
=> Upgrade to Pinot 0.12.1

core/trino-main/src/main/java/io/trino/operator/aggregation/MaxDataSizeForStats.java, core/trino-main/src/main/java/io/trino/operator/aggregation/SumDataSizeForStats.java
Block#getEstimatedDataSizeForStats is well defined for null positions. 
We can use this to replace NullableLongState with LongState.
=> Simplify MaxDataSizeForStats and SumDataSizeForStats

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueToTrinoConverter.java
```markdown
* Skip listing Glue tables with invalid column types. ({issue}`16677`)
```
=> Skip listing Glue tables with invalid column types

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
DefaultJdbcMetadata#applyProjection already excludes the delete row id from validation. Same is now done for the merge row id column as well.
=> Exclude all synthetic columns in applyProjection validation

plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetPageSourceFactory.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/predicate/TestParquetPredicateUtils.java
Test parquet column mapping using name based and index based mapping
```markdown
```
=> Test parquet column mapping using name based and index based mapping

plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileFormats.java
In the case of t_char, even though it is not a partition key, it was created and tested as a partition_key, so it was modified.
```markdown
```
=> Change t_char of AbstractTestHiveFileFormats from partition key to general column

core/trino-main/src/main/java/io/trino/execution/SqlQueryManager.java, core/trino-main/src/test/java/io/trino/execution/scheduler/TestEventDrivenTaskSource.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinode.java
Before the change, the DDL tasks where being executed with a thread name of `dispatch-query-%d`.
=> Set thread name for DDL queries

core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java, core/trino-main/src/main/java/io/trino/testing/MaterializedResult.java, core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcTableStatisticsTest.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcConnectorTest.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorTest.java, testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java, testing/trino-tests/src/test/java/io/trino/tests/BaseQueryAssertionsTest.java
For better readability, replace `projected(int... columns)` with `projected(String... columnNamesToInclude)` and introduce `exceptColumns(String... columnNamesToExclude)` leveraging `MaterializedResult.getColumnNames`
=> Introduce new methods projected & exceptColumns take string varargs in QueryAssertions

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/utils/HadoopTestUtils.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Refactor `testRenameTableToLongTableName` test so that Iceberg tests do not have to override the test method.
Also fixes https://github.com/trinodb/trino/issues/7535 per https://github.com/trinodb/trino/issues/7535#issuecomment-1482463855
=> Refactor testRenameTableToLongTableName to remove Iceberg override

testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergInsert.java
The test seems dominated by `finishInsert` time. since bf04a72875f27d43301d7896b6e04f0bc1199a6d `finishInsert` is slower as we commit twice (first committing data then statistics).
Fixes https://github.com/trinodb/trino/issues/16652
=> Fix TestIcebergInsert.testIcebergConcurrentInsert timeout on CI

plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java, plugin/trino-session-property-managers/src/test/java/io/trino/plugin/session/TestSessionPropertyManagerInTransaction.java
Make setup of bucketed tables in HiveQueryRunner optional
Bucketed tables are unnecessary in many tests
=> Make setup of bucketed tables in HiveQueryRunner optional

plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
Remove duplicate getParquetType method from ParquetPageSourceFactory
```markdown
```
=> Remove duplicate getParquetType method from ParquetPageSourceFactory

core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalAverageAggregation.java, core/trino-main/src/main/java/io/trino/operator/aggregation/state/LongDecimalWithOverflowAndLongState.java, core/trino-main/src/main/java/io/trino/operator/aggregation/state/LongDecimalWithOverflowAndLongStateFactory.java, core/trino-main/src/main/java/io/trino/operator/aggregation/state/LongDecimalWithOverflowAndLongStateSerializer.java, core/trino-main/src/main/java/io/trino/operator/aggregation/state/LongDecimalWithOverflowStateFactory.java, core/trino-main/src/test/java/io/trino/operator/aggregation/TestDecimalAverageAggregation.java, core/trino-main/src/test/java/io/trino/operator/aggregation/state/TestLongDecimalWithOverflowAndLongStateSerializer.java, lib/trino-array/src/main/java/io/trino/array/LongBigArray.java
Remove redundant boolean state from LongDecimalWithOverflowAndLongState
=> Remove redundant boolean state from LongDecimalWithOverflowAndLongState

core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedStageExecution.java
Removes synchronization from `beginScheduling()` and `transitionToSchedulingSplits()` both of which only perform state machine updates (if necessary) and do not require accessing synchronized state.
Follows up from https://github.com/trinodb/trino/pull/16585
=> Reduce synchronization on PipelinedStageExecution

core/trino-main/src/main/java/io/trino/operator/aggregation/SumDataSizeForStats.java
Avoids an extra null check as block.getEstimatedDataSizeForStats will also check for null
Missed making this change in https://github.com/trinodb/trino/pull/16675 , but it doesn't affect correctness.
=> Add NullablePosition to SumDataSizeForStats

plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/partition/HiveHudiPartitionInfo.java, plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/partition/HudiPartitionInfo.java
=> Remove unused `HiveHudiPartitionInfo.getTable` method

docs/src/main/sphinx/connector/ignite.rst, plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java, plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
Support DELETE statement in Ignite connector
```markdown
* Add support for {doc}`/sql/delete`. ({issue}`16720`)
```
=> Support DELETE statement in Ignite connector

docs/src/main/sphinx/develop.rst, docs/src/main/sphinx/develop/example-jdbc.rst, plugin/trino-example-jdbc/pom.xml, plugin/trino-example-jdbc/src/main/java/io/trino/plugin/example/ExampleClient.java, plugin/trino-example-jdbc/src/main/java/io/trino/plugin/example/ExampleClientModule.java, plugin/trino-example-jdbc/src/main/java/io/trino/plugin/example/ExamplePlugin.java, plugin/trino-example-jdbc/src/test/java/io/trino/plugin/example/ExampleQueryRunner.java, plugin/trino-example-jdbc/src/test/java/io/trino/plugin/example/TestExampleQueries.java, pom.xml
Add an example JDBC plugin and a new section in the docs. My main intention is to have a docs section where we could start capturing nuances of correct type mapping (rounding, validation, etc.). 
This is **not** related to #2910
An example JDBC plugin can be used as an example when creating a new third-party JDBC connector.
=> Add an example JDBC connector plugin

client/trino-client/src/main/java/io/trino/client/ClientTypeSignature.java, client/trino-client/src/main/java/io/trino/client/NamedClientTypeSignature.java, client/trino-client/src/main/java/io/trino/client/Row.java, client/trino-client/src/main/java/io/trino/client/Warning.java, client/trino-client/src/main/java/io/trino/client/auth/kerberos/SpnegoHandler.java, core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java, core/trino-main/src/main/java/io/trino/sql/gen/AndCodeGenerator.java, core/trino-main/src/main/java/io/trino/sql/gen/BytecodeUtils.java, core/trino-main/src/main/java/io/trino/sql/gen/OrCodeGenerator.java, core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java, core/trino-main/src/main/java/io/trino/type/TypeUtils.java, core/trino-main/src/main/java/io/trino/util/StatementUtils.java, core/trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java, core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java, core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java, core/trino-parser/src/main/java/io/trino/sql/tree/PathElement.java, core/trino-parser/src/main/java/io/trino/sql/tree/UpdateAssignment.java
Follow up from https://github.com/trinodb/trino/pull/15258 to replace other usages of `String.format` in non-exceptional code paths where simple string concatenations are equally clear (but more performant). These changes are not expected to be nearly as significant in terms of performance as the linked previous PR.
No additional context should be necessary. 
=> More string format removals

core/trino-main/src/main/java/io/trino/sql/gen/BytecodeUtils.java
This change [/pull/7014] was trying to fix a bad parameter count issue when there are too many parameters for code generators, and this change makes sure when there are 100 or below number of parameters, BLOCK_POSITION will not be used to prevent issues. However, 100 is not enough especially when it comes to double slots type like Long. Double slots for long plus a nullable flag will cause the number of parameters surpass the max of 255 and causing query compiler error. This change further limits it down so double slots types with number of parameters between 85 to 100 will not throw error
/pull/7014
( X) Release notes are required, with the …
=> Fix bad parameter count in code generator when column uses double slots

docs/src/main/sphinx/connector/hive.rst
Per issue #16240, queries where getting the error HIVE_EXCEEDED_SPLIT_BUFFERING_LIMIT (256MB). Changing the limit through hive.max-outstanding-splits-size resolved this. The hive.max-outstanding-splits-size property was not in the Performance Tuning Configuration Properties section of the Hive documentation, however. 
```markdown
```
=> Add max-outstanding-splits-size to Hive configuration doc

testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java
Add missing groups to `TestIcebergProcedureCalls.testMigrateHiveBucketedOnMultipleColumns`
=> Add missing groups to `TestIcebergProcedureCalls.testMigrateHiveBucketedOnMultipleColumns`

core/trino-main/pom.xml
=> Remove OkHttp as a runtime dependency for the engine

lib/trino-hdfs/src/main/java/io/trino/hdfs/authentication/CachingKerberosHadoopAuthentication.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/HadoopKerberos.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite2.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite5.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite7NonGeneric.java, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop-kerberos/create_kerberos_credential_cache_files.sh, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop-kerberos/krb5.conf, testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveConnectorKerberosSmokeTest.java
The Hadoop UGI class handles ticket refresh only if the Subject is not provided externally. For external Subject UGI expects the refresh will be handled by the creator of the Subject which in our case we did not do.
Because of this before this change any Trino query which ran longer than the ticket_lifetime failed with errors like
GSS initiate failed [Caused by GSSException: No valid credentials
provided (Mechanism level: Failed to find any Kerberos tgt)].
In Hadoop code the UGI instance also gets re-used in some places (e.g. DFSClient) which means we cannot just create a new UGI with refreshed credentials and return that since other parts of code will keep using the old UGI with expired credentials. So the fix is to create a new UGI, extract the credentials from it and update the …
=> Fix Kerberos ticket refresh

plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHiveAlluxioMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
=> Add test for trailing space in location in hive metadata

core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java, plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
Column names coming out of the query are not necessarily related to the column names in the table function. These tests are testing behavior that is not necessarily expected or guaranteed, so they are brittle and can break at any time.
=> Remove unnecessary and brittle tests

lib/trino-record-decoder/pom.xml, lib/trino-record-decoder/src/main/java/io/trino/decoder/avro/AvroColumnDecoder.java, plugin/trino-kafka/pom.xml, plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ClassLoaderSafeSchemaRegistryClient.java, plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentModule.java, plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestAvroConfluentRowDecoder.java, plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestConfluentSchemaRegistryTableDescriptionSupplier.java, plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java, plugin/trino-mongodb/pom.xml, pom.xml, testing/trino-product-tests-launcher/pom.xml, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Kafka.java, testing/trino-product-tests/pom.xml, testing/trino-product-tests/src/main/java/io/trino/tests/product/kafka/TestKafkaAvroReadsSmokeTest.java, testing/trino-testing-kafka/src/main/java/io/trino/testing/kafka/TestingKafka.java, testing/trino-testing-services/src/main/java/io/trino/testing/TestingProperties.java, testing/trino-testing-services/src/main/resources/trino-testing.properties
Updates transitive dependencies for Avro and ZooKeeper. Wire 4.x is required for Confluent 7.3.1 and is updated in the modules that need it, but leaves Wire at 3.x for the remaining modules.
Continuation for https://github.com/trinodb/trino/pull/16130
=> Upgrade Confluent version to 7.3.1

plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java
=> Explicitly set input dir in job conf instead of FileInputFormat.setInputPath which makes an IO call

core/trino-main/src/main/java/io/trino/operator/scalar/ArrayFilterFunction.java, core/trino-main/src/test/java/io/trino/operator/scalar/BenchmarkArrayFilter.java
In the original implementation of `ArrayFilterFunction.filter*`, an additional copy of the filtered block is adopted. The speed, especially for some nested column types such as `RowType` is not perfect.  
So we improved the implementation to record the block index position, then directly call `Block.copyPositions()` after the filtering is completed, in order to reduce unnecessary block copies such as `Type.appendTo()` and `BlockBuilder.build()`.
```
Benchmark                             (name)  Mode  Cnt   Score   Error  Units  
BenchmarkArrayFilter.benchmark        filter  avgt   20  22.543 ± 0.979  ns/op  
BenchmarkArrayFilter.benchmarkObject  filter  avgt   20  42.045 ± 2.088  ns/op 
``` 
```
Benchmark                             (name)  Mode  Cnt   Score   Error  Units …
```
=> Improve the performance of filter functions

core/trino-main/src/main/java/io/trino/operator/scalar/QuantileDigestFunctions.java, core/trino-main/src/test/java/io/trino/operator/aggregation/TestQuantileDigestFunctions.java, docs/src/main/sphinx/functions/qdigest.rst
```markdown
* Add quantile_at_value function
```
=> Add quantile_at_value function

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeRegisterTableProcedureTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeSharedMetastoreViewsTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeRegisterTableProcedureWithFileMetastore.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedFileMetastoreViews.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedGlueMetastoreViews.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedGlueMetastoreWithTableRedirections.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableWithCustomLocationUsingGlueMetastore.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeConcurrentModificationGlueMetastore.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeRegisterTableProcedureWithGlue.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeRenameToWithGlueMetastore.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeViewsGlueMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCreateTableFailure.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueTableOperationsInsertFailure.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestSharedGlueMetastore.java
Fix CI failures on master. 
* https://github.com/trinodb/trino/actions/runs/4547183930/jobs/8019663576
* https://github.com/trinodb/trino/actions/runs/4547183930/jobs/8019664306
=> Use URI path for Glue location in tests

.github/workflows/ci.yml
=> Test trino-main with JDK 20

lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/csv/CsvSerializer.java, lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/csv/TestCsvFormat.java
Hive OpenCSV writer will disable quoting and escaping behavior if the quote or escape character is zero.  This can result in data that does not round trip, but is an expected feature (bug?) of the writer.
Fixes #16710
```markdown
*  In the native CSV writer, Disable quoting when quote character is zero, and disable escaping when escape character is zero. ({issue}`16710`)
```
=> Add support for Hive OpenCSV no-quoting and no-escaping behavior

lib/trino-collect/src/main/java/io/trino/collect/cache/EvictableCache.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/Table.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
putIfAbsent method is not implemented in the EvictableCache because of race condition with invalidation so to avoid the race condition we use AtomicReference that at some cases can be thrown away, but it makes cached value fresh even if invalidation happens during value load
fixes https://github.com/trinodb/trino/issues/16653
```markdown
```
=> Fix race condition in the hive table stats cache

docs/src/main/sphinx/release.rst, docs/src/main/sphinx/release/release-411.md
Assemble the release notes for the upcoming Trino 411 release. Fixes #16453 
* #16136 ✅ rn ✅ docs
* #16449 ✅ rn ✅ docs
* #16443 ✅ rn ✅ docs
* #16440 ✅ rn ✅ docs
* #16398 ✅ rn ❌  docs
* #13390 ✅ rn ✅ docs
* #16467 ✅ rn ✅ docs
* #16463 ✅ rn ✅ docs
* #16142 ✅ rn ✅ docs
* #16050 ❌ rn ✅ docs
* #16471 ✅ rn ✅ docs
* #16487 ✅ rn ✅ docs
* #16493 ✅ rn ✅ docs
* #16119 ✅ rn ✅ docs
* #16484 ✅ rn ✅ docs
* #16468 ✅ rn ✅ docs
* #16498 ✅ rn ✅ docs
* #16288 ✅ rn ✅ …
=> Add Trino 411 release notes

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
This PR improves the `testCorruptedTableLocation` to verify for managed and external delta table locations
Follow up of https://github.com/trinodb/trino/pull/16651#discussion_r1147377727
=> Enhance test for managed and external delta table location validation

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentUp.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentOptions.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
=> Rename method to use Trino terminology

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMigrateProcedure.java
Fix incorrect result when table location contains a hidden directory in Iceberg `migrate` procedure
Thank @krvikash for finding the issue. 
```markdown
* Fix incorrect result when table location contains a hidden directory in `migrate` procedure. ({issue}`16779`)
```
=> Fix incorrect result when table location contains a hidden directory in Iceberg `migrate` procedure

plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMetadata.java, plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
Add support for `ADD COLUMN` in Ignite connector
```markdown
* Add support for `ALTER TABLE ... ADD COLUMN` statement. ({issue}`16755`)
```
=> Add support for `ADD COLUMN` in Ignite connector

.github/workflows/ci.yml, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteAllConnectorsSmoke.java
`SuiteAll` is too generic and does not reflect it only tests if the cluster starts at all, with all connectors being enabled.
=> Use a more specific name for all connectors smoke test suite

core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PruneTableFunctionProcessorColumns.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PruneTableFunctionProcessorSourceColumns.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantTableFunction.java, core/trino-main/src/test/java/io/trino/sql/planner/TestTableFunctionInvocation.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/TableFunctionProcessorMatcher.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestImplementTableFunctionSource.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneTableFunctionProcessorColumns.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneTableFunctionProcessorSourceColumns.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveRedundantTableFunction.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/TableFunctionProcessorBuilder.java, testing/trino-tests/src/test/java/io/trino/tests/TestTableFunctionInvocation.java
This PR introduces optimizer rules for column pruning and redundant node pruning of `TableFunctionProcessorNode`.
Docs not needed.
```markdown
* Optimize queries involving table functions with table arguments.
```
=> Optimize plans involving table functions

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePerTransactionMetastoreCache.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreAccessOperations.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/CountingAccessHiveMetastoreUtil.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
=> Simplify `TestDeltaLakePerTransactionMetastoreCache` with `CountingAccessHiveMetastore`

core/trino-main/src/test/java/io/trino/execution/BaseDataDefinitionTaskTest.java, core/trino-main/src/test/java/io/trino/execution/TestCreateCatalogTask.java, core/trino-main/src/test/java/io/trino/execution/TestDropCatalogTask.java, plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHivePlugin.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/rubix/TestRubixCaching.java, plugin/trino-kinesis/src/test/java/io/trino/plugin/kinesis/TestMinimalFunctionality.java, testing/trino-testing-services/src/main/java/io/trino/testng/services/ReportAfterMethodNotAlwaysRun.java, testing/trino-testing-services/src/main/resources/META-INF/services/org.testng.ITestNGListener, testing/trino-testing-services/src/test/java/io/trino/testng/services/TestReportAfterMethodNotAlwaysRun.java
Turns out that the `@AfterX` methods do not get executed by default if any of the previous methods failed or were skipped - and that includes the test methods as well. So if any of the tests is skipped, cleanup for the test may also be skipped. The `alwaysRun = true` annotation enforces that the cleanup method always gets executed.
The failure to run the cleanup method may cause the resource leak detector to trigger and mask the actual cause the test was skipped.
```markdown
```
=> Add a check to enforce alwaysRun = true on test after-methods

docs/src/main/sphinx/connector/hive.rst
Instead of the code font .. normal font and quotes were rendered since a space was missing in the source.
=> Fix output rendering issue in docs

docs/src/main/sphinx/glossary.rst
Some of the Trino glossary entries were not in alphabetical order.
I moved them so that they are alphabetized correctly.
```markdown
```
=> Alphabetize glossary entries

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java, core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java, core/trino-main/src/test/java/io/trino/cost/TestOptimizerConfig.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesPlans.java, docs/src/main/sphinx/admin/properties-optimizer.rst
Use use_cost_based_partitioning instead of use_exact_partitioning to control the cost-based optimization to prefer parent partitioning. The motivation is to be able to disable the optimization if the NDV statistics are overestimated and the optimization would hurt parallelism.
```markdown
* Add `optimizer.use-cost-based-partitioning` configuration property and `use_cost_based_partitioning` session property to allow disabling usage of cost based optimizer for determining partitioning of a stage. ({issue}`16781`)
```
=> Add use_cost_based_partitioning

.github/actions/compile-commit/action.yml, .github/workflows/ci.yml, .github/workflows/docs.yml, .mvn/wrapper/maven-wrapper.properties
```
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: /Users/mateuszgajewski/.m2/wrapper/dists/apache-maven-3.9.1-bin/6e2gfsmef58top79hk1hgrm2ot/apache-maven-3.9.1
Java version: 17.0.6, vendor: Eclipse Adoptium, runtime: /Users/mateuszgajewski/.sdkman/candidates/java/17.0.6-tem
Default locale: en_PL, platform encoding: UTF-8
OS name: "mac os x", version: "13.2.1", arch: "aarch64"
```
The problem with the 10% performance regression introduced in 3.9.0 is solved in 3.9.1. It should be safe to upgrade.
=> Update maven to 3.9.1

core/trino-main/src/main/java/io/trino/operator/LeafTableFunctionOperator.java, core/trino-main/src/test/java/io/trino/connector/TestingTableFunctions.java, testing/trino-tests/src/test/java/io/trino/tests/TestTableFunctionInvocation.java
While trying to apply this comment https://github.com/trinodb/trino/pull/16205#issuecomment-1487373782 I figured out that there is a problem with a case when there is no data for the current function invocation and EmptySplit is provided to the `TableFunctionSplitProcessor` which should not happen 
```markdown
```
=> Make LeafTableFunctionOperator handle EmptySplit correctly

core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ImplementTableFunctionSource.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PruneTableFunctionProcessorColumns.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PruneTableFunctionProcessorSourceColumns.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddLocalExchanges.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/SymbolMapper.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/UnaliasSymbolReferences.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/TableFunctionProcessorNode.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/TableFunctionProcessorBuilder.java
There is no need to store CatalogHandle directly in TableFunctionProcessorNode as it is present in TableFunctionHandle
```markdown
```
=> Remove CatalogHandle from TableFunctionProcessorNode

plugin/trino-elasticsearch/pom.xml
It's a transitive dependency of elasticsearch-x-content, which we use in ElasticsearchLoader to load tpch data to Elasticsearch with json encoding. Yaml support is not needed at all.
```markdown
```
=> Exclude snakeyaml from elasticsearch dependencies

docs/src/main/sphinx/connector/hive.rst
Document avro.schema.literal property use for interpreting table data
https://github.com/trinodb/trino/pull/14426
```markdown
```
=> Document avro.schema.literal property use for interpreting table data

client/trino-jdbc/pom.xml, plugin/trino-oracle/pom.xml, plugin/trino-resource-group-managers/pom.xml, pom.xml
Update Oracle JDBC driver version to 21.9.0.0
This upgrade supports additional config properties using connection url.
For instance, #16812 can be:
```
jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=host)(PORT=5521))(CONNECT_DATA= (SERVICE_NAME=servicename))(Security=(ENCRYPTION_CLIENT=REQUESTED)))
```
https://docs.oracle.com/en/database/oracle/oracle-database/21/jajdb/oracle/jdbc/OracleConnection.html#CONNECTION_PROPERTY_THIN_NET_ENCRYPTION_LEVEL
Fixes #16812
=> Update Oracle JDBC driver version to 21.9.0.0

core/trino-main/src/test/java/io/trino/execution/BaseDataDefinitionTaskTest.java, core/trino-main/src/test/java/io/trino/execution/TestRenameColumnTask.java, core/trino-parser/src/main/java/io/trino/sql/tree/RenameColumn.java, core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
Add test for RenameColumnTask and migrate assertStatement in TestSqlParser.testRenameColumn
=> Add test for RenameColumnTask and migrate assertStatement in TestSqlParser.testRenameColumn

client/trino-jdbc/src/main/java/io/trino/jdbc/ConnectionProperties.java, client/trino-jdbc/src/main/java/io/trino/jdbc/DnsResolver.java, client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDriverUri.java, client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriver.java
Provide a way to configure a custom DNS resolver for the JDBC driver.
Adds 2 new new JDBC URL parameters:
- `dnsResolver` - the name of the class implementing interface `io.trino.jdbc.DnsResolver`
- `dnsResolverContext` - a string argument to be passed to the constructor of the above class (if this parameter is not provided, `null` will be used)
```markdown
```
=> Allow configuring a custom DNS resolver for the JDBC driver

docs/src/main/sphinx/connector/hudi.rst
**THERE ARE NO TECHNICAL CONTENT CHANGES TO EXISTING MATERIAL IN THIS PR**
This PR is a follow-on to PR#15637. It reorganizes the Hudi connector documentation to match the structure of the Hive connector documentation and, as with the Hive PR, does the following:
- Formats a table in the old format to the list table format (and of course adds table titles). 
Here is a possibly helpful screen cap showing how the Hudi doc org lines up with the Hive doc org now:
```markdown
```
=> Reorganize Hudi connector documentation

core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
Migrate some deprecated `assertExpression` method in `TestSqlParser`
=> Migrate some deprecated `assertExpression` method in `TestSqlParser`

client/trino-client/src/main/java/io/trino/client/ProtocolHeaders.java, client/trino-client/src/test/java/io/trino/client/TestProtocolHeaders.java
Change the logic to detect a non-Trino protocol to stop relying on the X-<protocol>-User HTTP header.
Trino detects alternative protocols (e.g. Presto) by looking whether the X-<protocol>-User HTTP header exists. In some cases however no such header is provided. So change the logic to avoid relying on that particular HTTP header and instead look for any X-<protocol>-* HTTP header.
```markdown
```
=> Do not rely on the X-<protocol>-User HTTP header to detect a protocol

pom.xml
New version brings following improvements:
* new Opcodes.V21 constant for Java 21
* new readBytecodeInstructionOffset hook in ClassReader
* more detailed exception messages
* Javadoc improvements and fixes
* bug fixes:
* 317989: Silent removal of zero-valued entries from the line-number table
```markdown
```
=> Update ASM to 9.5

docs/src/main/sphinx/connector/delta-lake.rst
**THERE ARE NO TECHNICAL CONTENT CHANGES INCLUDED IN THIS PR.**
This PR is a follow-on to PR#15637. It reorganizes the Delta Lake connector documentation to match the structure of the Hive connector documentation and, as with the Hive PR, does the following:
- Fixes problematic verb tenses as per Google Developer Style Guide (must use present tense only). These included would, should, could, needs to, will be; there were not many instances.
- Adds intro blurbs where there were none for the following section headers:
- Security (used same language as in Iceberg PR#16451)
- SQL support - (copied from Iceberg PR#16451. **Please check that all listed are indeed supported**)
- Procedures (used same language as the Hive blurb)
- Schema and table management (used same language as the Hive blurb) …
=> Reorganize Delta Lake connector documentation

plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/AcidTables.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestAcidTables.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestHiveAcidUtils.java
Fixes #16715
```markdown
* Fix reading Hive ACID tables with locations containing hidden directories. ({issue}`16773`)
```
=> Fix handling of Hive ACID tables with hidden directories

plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteTypeMapping.java
=> Test `CREATE TABLE AS SELECT` in Ignite type mapping 

plugin/trino-delta-lake/src/main/antlr4/io/trino/plugin/deltalake/expression/SparkExpressionBase.g4, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/ArithmeticBinaryExpression.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/Identifier.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionBuilder.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionConverter.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionTreeVisitor.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/expression/TestSparkExpressionParser.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/expression/TestSparkExpressions.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCheckConstraintCompatibility.java
Support arithmetic binary in Delta check constraints
```markdown
* Add support for arithmetic binary expressions in check constraints. ({issue}`16721`)
```
=> Support arithmetic binary in Delta check constraints

core/trino-main/src/main/java/io/trino/connector/system/GlobalSystemConnector.java, core/trino-main/src/main/java/io/trino/connector/system/SystemConnectorModule.java, core/trino-main/src/main/java/io/trino/metadata/GlobalFunctionCatalog.java, core/trino-main/src/main/java/io/trino/operator/table/ExcludeColumns.java, core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java, core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java, core/trino-spi/src/main/java/io/trino/spi/ptf/Descriptor.java, core/trino-spi/src/main/java/io/trino/spi/ptf/DescriptorArgument.java, core/trino-spi/src/main/java/io/trino/spi/ptf/DescriptorArgumentSpecification.java, core/trino-spi/src/main/java/io/trino/spi/ptf/EmptyTableFunctionHandle.java, core/trino-spi/src/main/java/io/trino/spi/ptf/TableFunctionAnalysis.java, docs/src/main/sphinx/functions/table.rst, testing/trino-tests/src/test/java/io/trino/tests/TestExcludeColumnsFunction.java
Adds a new table function `exclude_columns` as a built-in table function.
```
SELECT *
FROM TABLE(exclude_columns(
input => TABLE(orders),
columns => DESCRIPTOR(clerk, comment)))
```
This function is a replacement for syntax `SELECT * EXCEPT(...)`. Such syntax, in a few variants, is supported by different databases (as discussed here https://stackoverflow.com/questions/413819/select-except). However, it is not part of the SQL standard, and so Trino does not support it.
There is a related optimization PR submitted for review: https://github.com/trinodb/trino/pull/16012. Technically, the optimization is not a prerequisite, but it could affect the performance a lot by enabling column pruning. …
=> Add table function exclude_columns

lib/trino-orc/src/main/java/io/trino/orc/OrcReader.java, lib/trino-orc/src/test/java/io/trino/orc/TestReadBloomFilter.java
Previous value 8196 was bigger than PageProcessor#MAX_BATCH_SIZE causing PageProcessor to create small, 4 position pages every other page.
```markdown
```
=> Use OrcReader#MAX_BATCH_SIZE = 8 * 1024

client/trino-client/src/main/java/io/trino/client/JsonResponse.java, client/trino-client/src/main/java/okhttp3/internal/tls/DistinguishedNameParser.java, client/trino-client/src/main/java/okhttp3/internal/tls/LegacyHostnameVerifier.java, client/trino-client/src/test/java/io/trino/client/auth/external/TestExternalAuthenticator.java, plugin/trino-http-event-listener/pom.xml, plugin/trino-pinot/pom.xml, pom.xml, testing/trino-product-tests/pom.xml
=> Upgrade okhttp to 4.10.0

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
Fix `testTableWithNonNullableColumns` to update NOT NULL column in Delta Lake connector. 
The `col2` is nullable column, so those UPDATE statement **_shouldn't_** fail in my understanding.
I guess it's a typo of the column name. 
=> Fix `testTableWithNonNullableColumns` to update NOT NULL column in Delta Lake connector

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java, plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java, plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
This is a preparation about supporting setting comment for connectors who does not support setting comment directly when creating the table.
Allow the connector that need using extra sql command to set comment by return the list of the extra sql commands in new added method `getExtraTableAndColumnComments`. eg: `Postgresql` can not set command while creating comment, but support `comment on` syntax to set comment on table, but can return the list of `comment on table xxx is 'comments'` to set comment.
In this PR only talking about the table comment, but actually the column comments also can be supported in this way, plan to separate the PR if this get approved.
```
* Allow to create a table with a comment.
* Allow to set a comment for table.
```
=> Add  for support creating table with comment for more Jdbc based connectors

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/ImplementSum.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java, plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteClient.java, plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbClient.java, plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlClient.java, plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java, plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlClient.java, plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerClient.java
Fix https://github.com/trinodb/trino/issues/16452
Main changes:
- Update the `ImplementSum` to support both `sum(x)` and `sum(DISTINCT x)`
- Added test for `sum(DISTINCT x)` pushdown in `BaseJdbcConnectorTest`, I added those tests closes to the `SUPPORTS_AGGREGATION_PUSHDOWN_COUNT_DISTINCT` tests.
- Adjust some connectors client tests.
```markdown
* Support sum(distinct) pushdown for jdbc connectors ({issue}`16452`)
```
=> Support sum(distinct) pushdown for jdbc connectors

docs/src/main/sphinx/release.rst, docs/src/main/sphinx/release/release-412.md
Assemble the release notes for the upcoming Trino 412 release. Fixes #16798  
* #16764 ✅ rn ✅ docs
* #16760 ✅ rn ✅ docs
* #16779 ✅ rn ✅ docs
* #16755 ✅ rn ✅ docs
* #16673 ✅ rn ✅ docs
* #16012 ✅ rn ✅ docs
* #16730 ✅ rn ✅ docs
* #16741 ✅ rn ✅ docs
* #16791 ✅ rn ✅ docs
* #16787 ✅ rn ✅ docs
* #16719 ✅ rn ✅ docs
* #16799 ✅ rn ✅ docs
* #16816 ✅ rn ✅ docs
* #16810 ✅ rn ✅ docs
* #16781 ✅ rn ✅ docs
* #16784 ✅ rn ✅ docs
* #16807 ✅ rn ✅ docs
* #16777 ✅ rn ✅ …
=> Add Trino 412 release notes

docs/src/main/sphinx/connector/iceberg.rst
* Adds a table with a description of the `iceberg.glue.skip-archive` property to the Iceberg connector page 
* Provides documentation for a configuration property mentioned in: https://github.com/trinodb/trino/pull/14336
```markdown
```
=> Add docs for property to skip glue archive

core/trino-main/src/test/java/io/trino/execution/scheduler/TestBinPackingNodeAllocator.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeCdfPageSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSinkProvider.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTypes.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestDeltaLakeSchemaSupport.java
Support nested timestamp with time zone in Delta Lake
```markdown
* Support writing `timestamp with time zone` type in `array`, `map` and `row` types. ({issue}`16826`)
```
=> Support writing nested timestamp with time zone in Delta Lake

plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java, plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
Fix https://github.com/trinodb/trino/issues/16898
```markdown
* Add support for creating a table with a table comment. ({issue}`16898`)
* Add support for commenting on tables. ({issue}`16898`)
```
=> Support table comment for oracle connector

plugin/trino-pinot/pom.xml, pom.xml
Impersonating a dependabot here.
Also removes unnecessary `dependencyManagement` in `trino-pinot`. Unless it's very important to keep it at a lower version?
```markdown
```
=> Bump Protobuf version

core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaMetadata.java, core/trino-main/src/main/java/io/trino/metadata/TableProperties.java, core/trino-main/src/main/java/io/trino/sql/planner/Partitioning.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/ActualProperties.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PreferredProperties.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PropertyDerivations.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/StreamPropertyDerivations.java, core/trino-main/src/test/java/io/trino/sql/planner/TestEffectivePredicateExtractor.java, core/trino-main/src/test/java/io/trino/sql/planner/TestTableScanNodePartitioning.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushPredicateIntoTableScan.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestColocatedJoin.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestPartialTopNWithPresortedInput.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestRemoveEmptyUnionBranches.java, core/trino-spi/pom.xml, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorTablePartitioning.java, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorTableProperties.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java, plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java, plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorMetadata.java, plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchMetadata.java
Remove stream partitioning in favor of `StreamPropertyDeriviations`. Further down the road the plan is to merge `PropertyDeriviations` and `StreamPropertyDeriviation` into a single thing that can do both and use it for both, `AddExchanges` and `AddLocalExchanges`.
```markdown
```
=> Remove stream partitioning

plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorSmokeTest.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java, plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/BaseKuduWithDisabledInferSchemaConnectorSmokeTest.java, plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Don't lowercase `name` in `TrinoPrincipal` when `PrincipalType` is `USER`. 
Fixes #16116
```markdown
* Fix failure when creating a schema with a username containing uppercase characters on Iceberg Glue catalog. ({issue}`16116`)
```
=> Fix failure when creating a schema with non-lowercase username on Iceberg Glue catalog

plugin/trino-pinot/pom.xml, pom.xml, testing/trino-benchto-benchmarks/pom.xml, testing/trino-product-tests-launcher/pom.xml, testing/trino-product-tests/pom.xml
It's used transitively by calcite to load model definitions
```markdown
```
=> Exclude snakeyaml from pinot dependencies

core/trino-main/src/main/java/io/trino/operator/PositionSearcher.java, core/trino-main/src/main/java/io/trino/operator/TableFunctionOperator.java, core/trino-main/src/main/java/io/trino/operator/WindowOperator.java, core/trino-main/src/test/java/io/trino/operator/TestWindowOperator.java
This change applies to `WindowOperator` and `TableFunctionOperator`, and affects the way that input is split into partitions.
Binary search is replaced with exponential search.
First, the search range is limited with exponential search, and then binary search is applied within the limited range. It should improve performance in case of many small partitions.
Benchmarks needed.
```markdown
```
=> Optimize partition end search for small partitions

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
=> Add Iceberg query runner with MinIO and file metastore

docs/src/main/sphinx/admin/properties-logging.rst
Document compression configuration for server log
```markdown
```
=> Document compression configuration for server log

lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/Int32ShortDecimalColumnReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/TransformingValueDecoders.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestingColumnReader.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/AbstractTestParquetReader.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/ParquetTester.java
Optimized parquet reader is improved to handle reading INT32 values into a short decimals of lower precision than 10 if the value does not overflow the decimal.
Unoptimized parquet reader is fixed to apply overflow checks when reading INT32 values into a short decimal.
```markdown
* Fix reading INT32 values without decimal logical annotation in parquet files as a DECIMAL type in Trino. ({issue}`16938`)
```
=> Fix reading parquet INT32 values as short decimal

.github/workflows/ci.yml, core/trino-spi/pom.xml
When Maven is run in offline mode, Revapi can't resolve the previous SPI version and compares against an empty JAR, which makes the intended check against the previous verison ineffective.
=> Run SPI Revapi separately in non-offline mode

plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/HiveFileIterator.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/TestHiveFileIterator.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveHiddenFiles.java
Ignore in Hive only the files which have their names or the names of 
their ancestor beginning with `.` or `_` characters.
As agreed on Slack with @dprophet , this PR is a mere spin-off from https://github.com/trinodb/trino/pull/16387 used just to illustrate the creation of product tests corresponding for the initial PR.
@dprophet feel free to use the product tests in the original PR. No need for co-authoring.
Fixes #16386
The newly added product tests can be executed with 
```
testing/bin/ptl test run --environment singlenode-hdp3 --  -t io.trino.tests.product.hive.TestHiveHiddenFiles
``` …
=> Avoid ignoring files visible in Hive

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
Disallow using reserved column names for Delta CDF tables
Fixes #16913
```markdown
* Disallow using reserved column names `_change_type`, `_commit_version` and `_commit_timestamp` 
when creating a table or add a column with change data feed. ({issue}`16913`)
* Disallow enabling change data feed when the table contains 
`_change_type`, `_commit_version` and `_commit_timestamp` columns. ({issue}`16913`)
```
=> Disallow using reserved column names for Delta CDF tables

plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
Fixes https://github.com/trinodb/trino/issues/16980
=> Fix flaky testAddColumnConcurrently Ignite test

lib/trino-hdfs/src/main/java/io/trino/hdfs/HdfsConfig.java
If the config 'hive.fs.cache.max-size' is set to 0, and when the Filesystem object is loaded the first time, we get an exception "FileSystem max cache size has been reached: 0".
```markdown
```
=> Set min validation to 1 for config 'hive.fs.cache.max-size'

testing/trino-tests/src/test/java/io/trino/tests/TestDistributedSpilledQueries.java
The test is very unreliable when run locally.
=> Remove flaky test

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionParser.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/expression/TestSparkExpressions.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCheckConstraintCompatibility.java
Fixes #16865
```markdown
* Fix query failure when unsupported expressions exist in check constraints. ({issue}`16865`)
```
=> Fix query failure when unsupported check constraint exists in Delta

docs/src/main/sphinx/release.rst, docs/src/main/sphinx/release/release-413.md
Assemble the release notes for the upcoming Trino 413 release. Fixes #16895 
* #16896 ✅ rn ✅ docs
* #16808 ✅ rn ✅ docs
* #16880 ✅ rn ✅ docs
* #16826 ✅ rn ✅ docs
* #16485 ✅ rn ✅ docs
* #16899 ✅ rn ❌ docs
* #16693 ✅ rn ❌ docs
* #16849 ✅ rn ✅ docs
* #16890 ✅ rn ✅ docs
* #16902 ✅ rn ✅ docs
* #16870 ✅ rn ✅ docs
* #15378 ✅ rn ✅ docs
* #16918 ✅ rn ✅ docs
* #16124 ✅ rn ✅ docs
* #16901 ✅ rn ✅ docs
* #16906 ✅ rn ✅ docs
* #16811 ✅ rn ✅ docs
* #16914 ✅ rn ✅ …
=> Add Trino 413 release notes

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
Fixes [#11297](https://github.com/trinodb/trino/issues/11297)
=> Remove filtering of unsupported column names in Delta

plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/CountingAccessHiveMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestHiveMetastoreAccessOperations.java
Add test for access count in Hive metastore
=> Add test for access count in Hive metastore

core/docker/container-test.sh, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/DecoratedHiveMetastoreModule.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/procedure/FlushMetadataCacheProcedure.java
Name it consistently with the procedure name.
=> Rename class implementing Hive's flush_metadata_cache

lib/trino-collect/src/test/java/io/trino/collect/cache/TestEmptyCache.java, lib/trino-collect/src/test/java/io/trino/collect/cache/TestEvictableCache.java, lib/trino-collect/src/test/java/io/trino/collect/cache/TestEvictableLoadingCache.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
For example `BaseSqlServerConnectorTest` overrides
`testReadMetadataWithRelationsConcurrentModifications`. Before the
change, the test invocation could leave background task running,
eventually leading to failure during `AbstractTestQueryFramework.close`
(in `checkQueryInfosFinal()`).
Fixes https://github.com/trinodb/trino/issues/15430
=> Ensure test threads termination even when test overridden

core/trino-main/src/main/java/io/trino/json/PathEvaluationVisitor.java, core/trino-main/src/main/java/io/trino/json/ir/IrDescendantMemberAccessor.java, core/trino-main/src/main/java/io/trino/json/ir/IrJsonPathVisitor.java, core/trino-main/src/main/java/io/trino/json/ir/IrPathNode.java, core/trino-main/src/main/java/io/trino/sql/analyzer/JsonPathAnalyzer.java, core/trino-main/src/main/java/io/trino/sql/planner/JsonPathTranslator.java, core/trino-main/src/test/java/io/trino/json/TestJsonPathEvaluator.java, core/trino-main/src/test/java/io/trino/sql/planner/PathNodes.java, core/trino-main/src/test/java/io/trino/sql/query/TestJsonQueryFunction.java, core/trino-main/src/test/java/io/trino/type/TestJsonPath2016TypeSerialization.java, core/trino-parser/src/main/antlr4/io/trino/jsonpath/JsonPath.g4, core/trino-parser/src/main/java/io/trino/sql/jsonpath/PathTreeBuilder.java, core/trino-parser/src/main/java/io/trino/sql/jsonpath/tree/DescendantMemberAccessor.java, core/trino-parser/src/main/java/io/trino/sql/jsonpath/tree/JsonPathTreeVisitor.java, core/trino-parser/src/test/java/io/trino/sql/jsonpath/TestPathParser.java, docs/src/main/sphinx/functions/json.rst
This is an extension to SQL standard.
The standard SQL/JSON path language does not support loops or recursion. This method traverses the structure of input JSON and returns a collection of items associated with the given key from all levels of nesting.
```markdown
* Add recursive member accessor `..<field>` to JSON path language. ({issue}`issuenumber`)
```
Docs included.
=> Add recursive member accessor `..<field>` to JSON path language

docs/src/main/sphinx/connector/iceberg.rst
Deleted old Migrate Existing Tables section, as we now have the newer Migrate Tables section
Changed "An SQL procedure" to "A SQL procedure," as docs have standardized on pronouncing SQL as a word
Clarified explanation of "recursive_directory" argument 
```markdown
```
=> Update Migrate Table section on Iceberg doc

plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaRecordSet.java, plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java
Kafka tombstone message support
```markdown
* Fix query failure when a Kafka topic contains tombstone messages, that is messages with a ``NULL`` value. ({issue}`16962`)
```
=> Kafka tombstone message support

core/trino-main/src/test/java/io/trino/sql/query/TestRecursiveCte.java, core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionTreeRewriter.java
Consistently rewrite both lambda arguments and lambda body.
fixes https://github.com/trinodb/trino/issues/16989
```markdown
* Fix failure of recursive queries involving lambda. ({issue}`16989`)
```
=> Rewrite lambda arguments in ExpressionTreeRewriter

core/trino-main/src/main/java/io/trino/execution/buffer/PagesSerdeUtil.java, core/trino-main/src/main/java/io/trino/execution/buffer/SpoolingExchangeOutputBuffer.java
When exchange data is compressed heavily allocating tasks based on the compressed data size may significantly increase latency.
This effect is visible in tpcds/q24 when the inputs of a joins are well compressible and expand significantly after decompression. Yet the engine doesn't allocate enough tasks to achieve necessary level of parallelism.
https://github.com/trinodb/trino/pull/16719
```markdown
```
=> Collect uncompressed data size for output statistics

core/trino-main/src/main/java/io/trino/connector/system/GlobalSystemConnector.java, core/trino-main/src/main/java/io/trino/connector/system/SystemConnectorModule.java, core/trino-main/src/main/java/io/trino/metadata/GlobalFunctionCatalog.java, core/trino-main/src/main/java/io/trino/operator/table/Sequence.java, docs/src/main/sphinx/functions/table.rst, testing/trino-tests/src/test/java/io/trino/tests/TestSequenceFunction.java
Adds a table function `sequence` for generating a column of sequential bigint values.
```
SELECT *
FROM TABLE(sequence(
start => 1000000,
stop => -2000000,
step => -3))
```
Based on https://github.com/trinodb/trino/pull/16584 for collocated changes in connector.
```markdown
* Add a built-in table function sequence().
```
Documentation is included.
=> Add table function sequence

core/trino-main/src/main/java/io/trino/testing/MaterializedResult.java, core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Move `AbstractTestQueries.testShowTables` to
`AbstractTestEngineOnlyQueries`.
Add `BaseConnectorTest.testShowTables` testing `SHOW TABLES` with a
connector after a table or view is created in the connector.
=> Test SHOW TABLES after relation creation

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/fileio/ForwardingInputFile.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/fileio/ForwardingOutputFile.java
While dealing with failure scenarios, it is helpful to see what file is causing the issue
```
io.trino.testing.QueryFailedException: Failed to read file: ForwardingInputFile{inputFile=s3://test-bucket/tpch/corrupt_table_y4fjmbitkt-a9f1d9ebba684cd8b19ddcdc58725c68/metadata/00002-c9681ed7-843a-4484-92ed-606ef7c07e75.metadata.json}
```
instead of 
```
io.trino.testing.QueryFailedException: Failed to read file: io.trino.plugin.iceberg.fileio.ForwardingInputFile@2cdc22bb
```
=> Add `toString()` method for `ForwardingInputFile` and `ForwardingOutputFile`

core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
In write statistics tests verify that connector not reporting stats
indeed does not report them, i.e. that the
`ConnectorMetadata.supportsReportingWrittenBytes` is correct.
=> Validate correctness of supportsReportingWrittenBytes

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapCastInComparison.java, core/trino-main/src/test/java/io/trino/sql/query/TestUnwrapCastInComparison.java
Skip literal vs round tripped comparison for non-orderable types in UnwrapCastInComparison
- Non-orderable type allows only equality checks, so round tripped comparison cannot be applicable
(v ) This is not user-visible or docs only and no release notes are required.
```markdown
```
=> Skip literal vs round tripped comparison for non-orderable types in UnwrapCastInComparison

core/trino-main/src/main/java/io/trino/connector/DefaultCatalogFactory.java, core/trino-main/src/main/java/io/trino/server/PluginClassLoader.java
Fix some issues with plugin class loaders when the experimental dynamic catalogs feature is enabled.
=> Plugin class loader fixes

.github/workflows/ci.yml, docs/src/main/sphinx/connector/delta-lake.rst, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/ProtocolEntry.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointSchemaManager.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestProtocolEntry.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTableSnapshot.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointBuilder.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointEntryIterator.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointWriter.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeDatabricks122.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLakeDatabricks104.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLakeDatabricks122.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCheckpointsCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksDelete.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeProceduresCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DatabricksVersion.java
Support Databricks 12.2 LTS and disallow unsupported reader versions and features in Delta Lake
Fixes #16884
```markdown
* Add support for Databricks 12.2 LTS. ({issue}`16905`)
* Disallow reading tables with [deletion vectors](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#deletion-vectors). Previously, it returned incorrect results. ({issue}`16884`)
```
=> Support Databricks 12.2 LTS and disallow unsupported reader versions and features in Delta Lake

lib/trino-hive-formats/pom.xml, lib/trino-hive-formats/src/main/java/io/trino/hive/formats/compression/ChunkedSliceOutput.java, lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/openxjson/TestJsonReader.java, lib/trino-orc/src/main/java/io/trino/orc/ChunkedSliceOutput.java
Previously, the buffer allocation would remove first element of an `ArrayList`, causing a shift of all elements. This is rather ignorable: buffers get allocated bigger and bigger, so there aren't many buffer allocations. Still, it can be avoided, by keeping buffers on one list instead of two.
=> Avoid array list shift in ChunkedSliceOutput

core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveEmptyMergeWriterRuleSet.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java, core/trino-main/src/test/java/io/trino/sql/planner/sanity/TestValidateScaledWritersUsage.java
Add tests for `RemoveEmptyMergeWriterRuleSet`.
=> Add tests for RemoveEmptyMergeWriterRuleSet

plugin/trino-hive/pom.xml, plugin/trino-hudi/pom.xml, plugin/trino-iceberg/pom.xml, pom.xml, testing/trino-product-tests/pom.xml
Update the avro library to the latest, and use it in place of the shaded version previously supplied by `io.trino.hive:hive-apache`
This is in support of work to remove hive dependencies from Trino. Hive Avro reading replacement will need avro dependency passed through to be able to make switchover cleanly. 
```markdown
```
=> Update Avro Deps

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMigrateProcedure.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java
Allow migrating external tables in Iceberg
```markdown
* Add support for Hive external tables in `migrate` procedure. ({issue}`16704`)
```
=> Allow migrating external tables in Iceberg

pom.xml
This version introduces Loom-friendly synchronization (https://github.com/pgjdbc/pgjdbc/pull/2635)
=> Update Postgres JDBC driver to 42.6.0

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
Relates to #12638
```markdown
* Add support for DML operations on tables with `name` column mapping. ({issue}`12638`)
```
=> Support DML operations on Delta tables with `name` column mapping

core/trino-main/src/test/java/io/trino/connector/MockConnector.java, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java, plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableHandle.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMetadata.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreStatistics.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableHandle.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/optimizer/TestConnectorPushdownRulesWithIceberg.java, plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java, plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java, plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorMetadata.java
The table handle describes reads and retries do not matter for reads.
=> Remove table handle retriesEnabled field

core/trino-main/src/main/java/io/trino/operator/output/UnnestingPositionsAppender.java, core/trino-main/src/test/java/io/trino/operator/output/TestPositionsAppender.java, core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlockEncoding.java, core/trino-spi/src/test/java/io/trino/spi/block/TestDictionaryBlockEncoding.java
Dictionary-encoded blocks are currently flatened by the partitioned exchange operator. This prevents dictionary based optimizations from taking advantage of the encoded blocks (or results in additional overhead).
This PR adds support for dictionary encoded blocks through partitioned exchange for a case where the same dictionary (the same java object) is used by subsequent Blocks sent through `PartitionedOutputOperator`
Other than possible CPU optimizations, transmitting `DictionaryBlock`s over network reduces is more efficient than flat blocks.
As an example for query on tpch schema (sf10) encoded in orc files
```
explain analyze verbose select mktsegment from customer c, nation n where c.nationkey = n.nationkey;
```
**mktsegment** is dictionary encoded.
so when we look at the customer …
=> Push DictionaryBlock through remote partitioned exchange

pom.xml
json-smart <= 2.4.9 is affected by CVE-2023-1370
```markdown
```
=> Update and pin json-smart to 2.4.10

core/trino-main/src/main/java/io/trino/execution/executor/PrioritizedSplitRunner.java
=> Minor PrioritizedSplitRunner cleanups

core/trino-main/src/main/java/io/trino/operator/DynamicFilterSourceOperator.java
Current initial size of 8 is very small and leads to unnecessary amount of rehashing
```
Benchmark                                                  (collectionLimits)  (positionsPerPage)  Mode  Cnt  Before Score   After Score     Units
BenchmarkDynamicFilterSourceOperator.dynamicFilterCollect              5000,0                1024  avgt   45   0.663 ± 0.133  0.257 ± 0.017  ms/op
BenchmarkDynamicFilterSourceOperator.dynamicFilterCollect             50000,0                1024  avgt   45   6.420 ± 0.956  3.703 ± 0.139  ms/op
BenchmarkDynamicFilterSourceOperator.dynamicFilterCollect           1000000,0                1024  avgt   45  38.821 ± 2.883 32.224 ± 1.992  ms/op
```
( ) Release notes are required, please …
=> Increase TypedSet expectedSize in DynamicFilterSourceOperator

core/trino-main/src/main/java/io/trino/operator/scalar/SequenceFunction.java, core/trino-main/src/main/java/io/trino/operator/scalar/timestamp/SequenceIntervalDayToSecond.java, core/trino-main/src/main/java/io/trino/operator/scalar/timestamp/SequenceIntervalYearToMonth.java, core/trino-main/src/test/java/io/trino/type/TestArrayOperators.java
Fix https://github.com/trinodb/trino/issues/16742
```markdown
* Fix long overflow for scalar function sequence. ({issue}`16742`)
```
=> Fix long overflow for scalar function sequence

core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java, core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java, core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushPredicateIntoTableScan.java, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ExpressionConverter.java, plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
Fixes https://github.com/trinodb/trino/issues/15555, fixes https://github.com/trinodb/trino/issues/16515.
For queries such: `SELECT * FROM nation WHERE nationkey = null AND regionkey = 4`, the pushed down constraint in `applyFilter()` is `Constraint[summary=<...>, expression=null::boolean]`.
This fix avoids the pushdown and replaces the filter with empty values.
Blocking https://github.com/trinodb/trino/pull/16206
( X ) Release notes are required, with the following suggested text:
```markdown
* Avoid null predicate pushdown. ({issue}`15555`, {issue}`16515`)
```
=> Handle cast null in domain translator

.github/workflows/ci.yml, plugin/trino-redshift/pom.xml, plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/BaseRedshiftFailureRecoveryTest.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/RedshiftQueryRunner.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftQueryFailureRecoveryTest.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftTaskFailureRecoveryTest.java
Adds support for fault tolerant execution to Redshift connector
These tests can be prone to timing out based on the region that the GHA runner is spun up in.
May reduce the FTE test suite size just for Redshift if this is a problem. Will need to run the tests multiple times in order to verify.
```markdown
* Add support for [fault-tolerant execution](/admin/fault-tolerant-execution). ({issue}`16860 `)
```
=> Add support for Redshift fault tolerant execution

core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/DefaultSystemAccessControl.java
Make checkCanWriteSystemInformation to deny by default
This is in order to prevent accidental access to modify the worker state
in case there was no configured access control on worker.
=> Make checkCanWriteSystemInformation to deny by default

core/trino-spi/src/main/java/io/trino/spi/block/MapBlock.java, lib/trino-parquet/src/main/java/io/trino/parquet/ParquetTypeUtils.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/ListColumnReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/StructColumnReader.java
Avoids a few unnecessary operations when reading nested types in parquet
```markdown
```
=> Improve nulls and offsets calculations in parquet reader

pom.xml, testing/trino-product-tests/src/main/resources/tempto-configuration.yaml
1/9 failed without this fix. https://github.com/trinodb/trino/actions/runs/4726186779/jobs/8386368706?pr=17060
More than 30 attempts succeeded with this change. 
Requires https://github.com/trinodb/tempto/pull/111
Fixes #12818
=> Increase timeouts in Cassandra product test environment 

.github/workflows/ci.yml
Verify JDBC driver, server RPM and Docker image in separate job. These checks don't need to run for each Java version. The Docker image step often fails due to timeouts, so this makes it easy to retry, and doesn't make it appear that the Maven checks step failed (which is usually due to an error in the PR).
=> Verify artifacts in separate CI job

.github/bin/download-maven-dependencies.sh, pom.xml
This includes an update of the Maven Surefire plugin to 3.0.0 and requires additional dynamic dependencies.
Follow up to #16976 and #16940. FYI, we had some issues previously when attempting to update Surefire: #11900 and #12758
=> Update airbase to 136

plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestDynamicTable.java
This is due to differences in how Pinot handles IEEE-754 approximate numerics pre/post Pinot 0.12.1.
See https://github.com/apache/pinot/issues/10637
```markdown
```
=> Fix testFilterWithUdf

lib/trino-phoenix5-patched/pom.xml, plugin/trino-phoenix5/pom.xml, plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java, plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixTypeMapping.java
=> Upgrade Phoenix to 5.1.3

docs/src/main/sphinx/connector/bigquery.rst, docs/src/main/sphinx/connector/druid.rst, docs/src/main/sphinx/connector/elasticsearch.rst, docs/src/main/sphinx/connector/mariadb.rst, docs/src/main/sphinx/connector/mysql.rst, docs/src/main/sphinx/connector/oracle.rst, docs/src/main/sphinx/connector/postgresql.rst, docs/src/main/sphinx/connector/query-passthrough-warning.fragment, docs/src/main/sphinx/connector/redshift.rst, docs/src/main/sphinx/connector/sqlserver.rst
Create fragment and warning callout for query passthrough workaround
(s) This is not user-visible or docs only and no release notes are required.
```markdown
```
=> Add warning for query passthrough

core/trino-main/src/main/java/io/trino/operator/LeafTableFunctionOperator.java, core/trino-main/src/main/java/io/trino/operator/WorkProcessorPipelineSourceOperator.java, core/trino-main/src/main/java/io/trino/operator/WorkProcessorSourceOperatorAdapter.java, core/trino-main/src/main/java/io/trino/operator/table/Sequence.java, core/trino-main/src/test/java/io/trino/connector/TestingTableFunctions.java, core/trino-spi/pom.xml, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorSplitManager.java, core/trino-spi/src/main/java/io/trino/spi/ptf/TableFunctionProcessorProvider.java, core/trino-spi/src/main/java/io/trino/spi/ptf/TableFunctionProcessorState.java, core/trino-spi/src/main/java/io/trino/spi/ptf/TableFunctionSplitProcessor.java
The `TableFunctionSplitProcessor` is used for one split only and then
new instance of `TableFunctionSplitProcessor` is created.
Provide the split directly to
`TableFunctionProcessorProvider.getSplitProcessor` and do not provide it
to `TableFunctionProcessor.process`. This removes conditionality of
argument presence in the `process` method and so makes things simpler.
=> Simplify TableFunctionSplitProcessor interface

core/trino-main/src/test/java/io/trino/operator/TestDriver.java
Avoids asserting that driver destroyed future is not complete in `TestDriver` tests that do not block on `BrokenOperator#close()`. Otherwise the assertion is subject to a simple race condition causing sporadic test failures.
Fixes https://github.com/trinodb/trino/issues/16925
=> Remove flaky race-prone assertions in TestDriver

plugin/trino-hive/src/main/java/io/trino/plugin/hive/GenericHiveRecordCursor.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveType.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
A few minor cleanups to HiveType and HiveUtil
=> Minor improvements to HiveType and HiveUtil

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java, core/trino-main/src/main/java/io/trino/cost/TaskCountEstimator.java, core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java, core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java, core/trino-main/src/main/java/io/trino/execution/scheduler/FaultTolerantPartitioningSchemeFactory.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RewriteSpatialPartitioningAggregation.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/DeterminePartitionCount.java, core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestLimitMaxWriterNodesCount.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionConnectorTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java, testing/trino-testing/src/main/java/io/trino/testing/FaultTolerantExecutionConnectorTestHelper.java
Extend adaptive partitioning to fault-tolerant execution. Testing on tpcds-sf100 shows 4% improvement on wall time and 8% improvement on CPU time. Testing on tpcds-sf1000 shows 4.2% improvement on wall time and 1.9% improvement on CPU time.
https://github.com/trinodb/trino/pull/15489
```markdown
```
=> Implement adaptive partitioning for FTE

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ptf/Query.java
Include exception when failed to parse filter in MongoDB so that we can realize the wrong place of the argument. 
=> Include exception when failed to parse filter in MongoDB

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeCompatibility.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDatabricksCompatibility.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeOssDeltaLakeCompatibility.java
Extract a test to verify Databricks and OSS Delta TPCH tables and merge connector tests into one
=> Extract a test to verify Databricks and OSS Delta TPCH tables and merge connector tests into one

plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/DynamicTablePqlExtractor.java, plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotConnectorSmokeTest.java, plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestDynamicTable.java
Use uppercase for SQL keywords
```markdown
```
=> Fix SQL formatting in TestDynamicTable

core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaMetadata.java
There was a tight coupling between the method implementation and its caller.
=> Remove apparent correctness issue with calculatePrefixesWithTableName

core/trino-main/src/main/java/io/trino/operator/TableWriterOperator.java
Avoids an additional unnecessary copy of the `Block[]` array for each input page in `TableWriterOperator` by using the Page helper method instead of constructing the block array externally (which incurs an defensive copy when passed into the Page constructor).
=> Use Page#getColumns in TableWriterOperator

docs/src/main/sphinx/connector/mariadb.rst, docs/src/main/sphinx/connector/mysql.rst
Document how unsigned numeric types from MySQL and MariaDB are mapped to Trino.
As discussed in https://github.com/trinodb/trino/discussions/14679
https://github.com/trinodb/trino/blob/1be256c678f78e58a18adf519ba87cbfc1605e5c/plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java#L616-L634
https://github.com/trinodb/trino/blob/1be256c678f78e58a18adf519ba87cbfc1605e5c/plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java#L371-L379
```markdown
```
=> Document unsigned numeric type MySQL/MariaDB to Trino mapping

.github/workflows/ci.yml
Remove trino-main tests against JDK 19 since we already test against JDK 20
=> Remove trino-main tests against JDK 19 since we already test against JDK 20

core/trino-main/src/main/resources/webapp/src/components/QueryDetail.jsx
A Follow-up to #15318 . Looking back at the UI it seems a CPU time stat should be placed in the `Resource Utilization Summary` section.
Example screenshot:
=> Move planning CPU time to resource utilization summary
