- core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
Convert parser tests for CREATE MATERIALIZED VIEW statement to the
`ParserAssert` framework, since this is what is expected from parser
tests to use. This is in preparation to adding new test cases in that
method.
Extracted from https://github.com/trinodb/trino/pull/15104 to reduce the scope there.
Based on https://github.com/trinodb/trino/pull/15359, so please review only the new commit(s) here.
> Convert CREATE MV parser tests to `ParserAssert`

- core/trino-main/src/main/java/io/trino/sql/gen/ExpressionCompiler.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestLocalExecutionPlanner.java
> Improve error message when `TrinoException` happened in `ExpressionCompiler`

- core/trino-main/src/test/java/io/trino/execution/TestDropTableTask.java
Fix table name in TestDropTableTask
NA
```markdown
```
> Fix table name in TestDropTableTask

- core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
Remove unused method from AstBuilder
> Remove unused method from AstBuilder

- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplit.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTableHandle.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ptf/Query.java
> Fix projection pushdown when unsupported column exists in BigQuery

- lib/trino-geospatial-toolkit/src/main/java/io/trino/geospatial/serde/GeometrySerde.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
> Use enhanced switch statement

- docs/src/main/sphinx/connector/delta-lake.rst
> Add Delta Lake views docs

- pom.xml
> Upgrade tempto version to 190

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueToTrinoConverter.java
Follows https://github.com/trinodb/trino/pull/10044
> Support Glue database with empty location string

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java
Remove redundant RegisterTableProcedure field
similar to https://github.com/trinodb/trino/pull/15398/commits/29201c9f71f30bc64806af9ef629243950459227
NA
```markdown
```
> Remove redundant RegisterTableProcedure field

- plugin/trino-delta-lake/pom.xml
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedGlueMetastoreViews.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedGlueMetastoreWithTableRedirections.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableWithCustomLocationUsingGlueMetastore.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeRegisterTableProcedureWithGlue.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeViewsGlueMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueTableOperationsInsertFailure.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestSharedGlueMetastore.java
Extract a method to create testing `GlueHiveMetastore`
> Extract a method to create testing GlueHiveMetastore

- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Add test with predicate on top level and nested field
Improves test coverage for fix #15408
Fixes #15393
> Add test with predicate on top level and nested field

- core/trino-main/src/test/java/io/trino/sql/query/TestRowFilter.java
> Fix malformed test javadoc

- core/trino-main/src/test/java/io/trino/execution/TestNodeScheduler.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/TestUniformNodeSelector.java
Fixing incontinence in comments
> Adjusting scheduler assignment queue clean up

- pom.xml
See code level comment for details.
Maybe fixes https://github.com/trinodb/trino/issues/14248
> Tune GC in tests to improve heap saturation

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitManager.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithCustomLocation.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithExternalLocation.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Migrate more code to TrinoFileSystem in Iceberg
> Migrate more code to TrinoFileSystem in Iceberg

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
Remove unused methods from `BaseDeltaLakeConnectorSmokeTest`
> Remove unused methods from BaseDeltaLakeConnectorSmokeTest

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointSchemaManager.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsStorage.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePlugin.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastore.java
Minor code cleanup in Delta lake connector
NA
```markdown
```
> Minor code cleanup in Delta lake connector

- pom.xml
> Update benchto to newest version

- docs/src/main/sphinx/connector/clickhouse.rst
- docs/src/main/sphinx/connector/mariadb.rst
- docs/src/main/sphinx/connector/memsql.rst
- docs/src/main/sphinx/connector/mysql.rst
- docs/src/main/sphinx/connector/oracle.rst
- docs/src/main/sphinx/connector/pinot.rst
- docs/src/main/sphinx/connector/postgresql.rst
- docs/src/main/sphinx/connector/pushdown-correctness-behavior.fragment
- docs/src/main/sphinx/connector/redis.rst
- docs/src/main/sphinx/connector/sqlserver.rst
Provide more detail around pushdown decisions.
In order to better set expectations around when pushdown can occur (or not occur) but without going unnecessarily in depth around every pushdown decision, it may be beneficial to point out that connectors prioritize correctness over performance.
```markdown
```
> Describe join pushdowns prioritizing correctness over performance

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftHiveMetastoreClient.java
https://github.com/trinodb/trino/pull/15462
```markdown
```
> Add unit test for ThriftHiveMetastoreClient::alternativeCall

- .github/workflows/ci.yml
- plugin/trino-bigquery/pom.xml
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
Adds runtime checks for required JVM arguments.
https://github.com/trinodb/trino/pull/14972
The proper RNs were already added as part of https://github.com/trinodb/trino/pull/14972 - no additional notes required.
> BigQuery improvements related to experimental Arrow serialization support

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
> Do not update the metastore when setting Iceberg table/column comment

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
Add main method for Iceberg REST catalog query runner
> Add main method for Iceberg REST catalog query runner

- docs/src/main/sphinx/connector/kafka.rst
- docs/src/main/sphinx/release.rst
- docs/src/main/sphinx/release/release-404.md
- docs/src/main/sphinx/release/release-405.md
Assemble the release notes for the upcoming Trino 405 release. Fixes #15058 
Where's release 404? 😉 (if we think this is too fun for Trino, I can fix it...)
@findepi #15015 ✅ rn ✅ docs
@martint #15039 ✅ rn ✅ docs
@hashhar #14818 ✅ rn ✅ docs
@findepi #15057 ✅ rn ✅ docs
@arhimondr #15060 ❓ rn (we don't usually do …
> Add Trino 405 release notes

- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
When the BigQuery connector noticed an empty projection or a query which can be answered without adding any projections then it uses the TableInfo in case of tables (not views or other table types) to find the row count and generate pages instead of actually querying BigQuery.
The row count as shown in TableInfo for tables written using the insertAll/streaming API is incorrect until the streaming buffer is flushed and there's no mechanism to trigger an on-demand flush which can lead to incorrect results.
To fix this we now execute a COUNT(*) query (similar to what was already done for views) when we want to generate pages for empty projections.
```markdown
* Fix possible incorrect results for certain queries like …
```
> Fix incorrect results with empty projections in BigQuery

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
Remove unused throws IOException in BaseTrinoCatalogTest
> Remove unused throws IOException in BaseTrinoCatalogTest

- plugin/trino-hudi/pom.xml
- pom.xml
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hudi/TestHudiSparkCompatibility.java
> Upgrade Hudi version to 0.12.2

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystemMinio.java
Cleanup TestTrinoS3FileSystemMinio
> Cleanup TestTrinoS3FileSystemMinio

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/FilesTable.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ManifestsTable.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergBucketing.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestPartitionTransforms.java
Update calls to deprecated iceberg Transform and Transforms's API
Deprecated API whose usage is updated
1. org.apache.iceberg.transforms.Transforms#identity, #bucket, #truncate, #year, #month, #day, #hour
2. org.apache.iceberg.transforms.Transform#apply, #toHumanString
> Update calls to deprecated iceberg Transform and Transforms 's API

- core/trino-main/src/main/java/io/trino/execution/scheduler/policy/PhasedExecutionSchedule.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/policy/TestPhasedExecutionSchedule.java
> Migrate phased scheduler to Guava graphs

- core/trino-main/src/main/java/io/trino/execution/scheduler/TaskDescriptorStorage.java
> Log when query killed due to lack of task descriptor storage memory

- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
> Add additional checks for authorization field in JdbcTableHandle

- core/trino-main/src/main/java/io/trino/sql/planner/sanity/DynamicFiltersChecker.java
- core/trino-main/src/main/java/io/trino/sql/planner/sanity/PlanSanityChecker.java
> Print query plan if plan sanity checker fails

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogParser.java
See commit message
```markdown
```
> Throw exception instead of returning it

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
The mechanics are the same. This also improves the wording.
> Align extended stats config descriptions in Delta and Iceberg

- docs/src/main/sphinx/connector/iceberg.rst
Remove extra `
N/A
```markdown
```
> Fix typo in iceberg.rst

- core/trino-main/src/main/java/io/trino/operator/aggregation/state/LongDecimalWithOverflowAndLongStateFactory.java
> Fix memory accounting in GroupedLongDecimalWithOverflowAndLongState

- pom.xml
Update airlift dependency to version 221.
This includes a fix to the logging framework that can cause JVM hang on shutdown under certain race conditions.
> Update airlift dependency to version 221

- core/trino-main/src/main/java/io/trino/execution/executor/PrioritizedSplitRunner.java
Disables collecting user CPU time with CpuTimer in `PrioritizedSplitRunner#process()` since it is not used and doing so is significantly more expensive than simply collecting current thread CPU on linux hosts. Also removes one redundant call to `ticker.read()` in the same method.
Follows up from https://github.com/airlift/airlift/pull/1024 which added the option to `CpuTimer`. 
> Avoid PrioritizeSplitRunner CPU user time overhead

- pom.xml
Upgrade tempto version to 191
Contains https://github.com/trinodb/tempto/pull/108
> Upgrade tempto version to 191

- docs/src/main/sphinx/connector/elasticsearch.rst
Document the fact that ES supports a list of hosts instead of just one.
#12530, resolves #12528
> Document ElasticSearch hosts being a list

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeS3Module.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3NativeTransactionLogSynchronizer.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorSmokeTest.java
Make it clear it's different than Delta's old one based on DynamoDB.
> Give better name to S3 log synchronizer: S3 Native

- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultQueryBuilder.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcQueryBuilder.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcClient.java
- plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbClient.java
- plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlClient.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleClient.java
- plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlClient.java
- plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerClient.java
Defensive check to ensure that classes that extend `DefaultQueryBuilder`  requires `RemoteQueryModifier` to be injected/specified during creation. 
https://github.com/trinodb/trino/pull/14500
```markdown
```
> Minor cleanups in DefaultQueryBuilder

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
> Further cleanup of CachingHiveMetastore constructor

- core/trino-main/src/main/java/io/trino/operator/BigintGroupByHash.java
- core/trino-main/src/main/java/io/trino/operator/MultiChannelGroupByHash.java
- core/trino-main/src/test/java/io/trino/operator/GroupByHashYieldAssertion.java
- core/trino-main/src/test/java/io/trino/operator/TestGroupByHash.java
While rehash is in process both current and expanded hash tables are retained
```markdown
```
> Account for current and expanded tables in tryRehash

- client/trino-jdbc/pom.xml
- core/trino-main/pom.xml
- lib/trino-plugin-toolkit/pom.xml
- plugin/trino-elasticsearch/pom.xml
- plugin/trino-example-http/pom.xml
- plugin/trino-google-sheets/pom.xml
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/TokenFetchingMetastoreClientFactory.java
- plugin/trino-iceberg/pom.xml
- plugin/trino-prometheus/pom.xml
- plugin/trino-raptor-legacy/pom.xml
- pom.xml
- service/trino-proxy/pom.xml
> Update to Airbase 132

- core/trino-spi/src/main/resources/io/trino/spi/type/zone-index.properties
- core/trino-spi/src/test/java/io/trino/spi/type/TestTimeZoneKey.java
- pom.xml
> Update Joda to 2.12.2

- core/trino-main/src/main/java/io/trino/operator/scalar/DateTimeFunctions.java
- core/trino-main/src/main/java/io/trino/util/DateTimeUtils.java
- core/trino-main/src/test/java/io/trino/util/TestDateTimeUtils.java
- core/trino-spi/src/main/resources/io/trino/spi/type/zone-index.properties
- core/trino-spi/src/test/java/io/trino/spi/type/TestTimeZoneKey.java
- pom.xml
Context: i made a mistake in https://github.com/trinodb/trino/pull/15548
> Fix wrong ISO standard number for date format

- core/trino-main/src/main/java/io/trino/operator/DriverYieldSignal.java
- core/trino-main/src/main/java/io/trino/operator/aggregation/ApproximateMostFrequentHistogram.java
- core/trino-main/src/main/java/io/trino/operator/scalar/ColorFunctions.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
- core/trino-main/src/main/java/io/trino/util/HeapTraversal.java
- core/trino-main/src/test/java/io/trino/sql/planner/assertions/ExpectedValueProvider.java
- core/trino-spi/src/main/java/io/trino/spi/block/Block.java
- core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlock.java
- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMergeSink.java
- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
- core/trino-spi/src/main/java/io/trino/spi/function/LongVariableConstraint.java
- core/trino-spi/src/main/java/io/trino/spi/function/Signature.java
- core/trino-spi/src/main/java/io/trino/spi/function/TypeVariableConstraint.java
- lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoFileSystem.java
- lib/trino-orc/src/main/java/io/trino/orc/stream/LongInputStreamV2.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FilteredRowRangesIterator.java
- lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetSchemaConverter.java
- lib/trino-phoenix5-patched/src/main/java/org/apache/phoenix/shaded/org/apache/zookeeper/client/StaticHostProvider.java
- lib/trino-record-decoder/src/main/java/io/trino/decoder/csv/CsvRowDecoder.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/aggregation/BaseImplementAvgBigint.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogSynchronizer.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestPredicatePushdown.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java
- plugin/trino-kudu/src/main/java/org/apache/kudu/client/KuduOperationApplier.java
- plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
This is preparation to enable more checkstyle checks: https://github.com/airlift/airbase/pull/338
> Javadoc style fixes

- core/trino-main/src/main/java/io/trino/execution/SqlTaskExecution.java
- core/trino-main/src/main/java/io/trino/execution/executor/TaskExecutor.java
- core/trino-main/src/main/java/io/trino/execution/executor/TaskHandle.java
- core/trino-main/src/main/java/io/trino/operator/OperatorContext.java
Minor improvements to `TaskHandle` and related classes to reduce worker side lock contention associated with driver and task lifecycle components. Extracted from https://github.com/trinodb/trino/pull/15478 to simplify the review process by separating the more significant changes in that PR from the more minor improvements in this one.
> Minor TaskHandle Improvements

- .github/workflows/ci.yml
Sometimes timeout occurs during BugQuery tests (https://github.com/trinodb/trino/actions/runs/3844470384/jobs/6547614598), we need to separate run for arrow tests
> Separate BigQuery arrow test

- core/trino-main/src/main/java/io/trino/operator/PagesIndex.java
- core/trino-main/src/main/java/io/trino/operator/PagesRTreeIndex.java
- core/trino-main/src/main/java/io/trino/operator/PagesSpatialIndexSupplier.java
- core/trino-main/src/main/java/io/trino/operator/SimplePagesHashStrategy.java
- core/trino-main/src/main/java/io/trino/operator/StreamingAggregationOperator.java
- core/trino-main/src/main/java/io/trino/operator/join/BigintPagesHash.java
- core/trino-main/src/main/java/io/trino/operator/join/DefaultPagesHash.java
- core/trino-main/src/main/java/io/trino/operator/join/JoinHashSupplier.java
- core/trino-main/src/main/java/io/trino/operator/join/JoinUtils.java
- core/trino-main/src/main/java/io/trino/sql/gen/JoinCompiler.java
- core/trino-main/src/test/java/io/trino/operator/TestPagesIndex.java
- core/trino-main/src/test/java/io/trino/operator/TestSimplePagesHashStrategy.java
- core/trino-main/src/test/java/io/trino/operator/join/TestPositionLinks.java
- core/trino-main/src/test/java/io/trino/sql/gen/TestJoinCompiler.java
Account for allocated channel arrays (similarly to how it is done in PagesIndex)
```markdown
```
> Improve LookupSource memory accounting

- docs/src/main/sphinx/functions/json.rst
- docs/src/main/sphinx/functions/list-by-topic.rst
- docs/src/main/sphinx/functions/list.rst
Add a clarifying sentence and update the title for the JSON functions section and add missing entries into the list pages.
* https://trinodb.slack.com/archives/CP1MUNEUX/p1674102698927119
> Update JSON functions

- plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Wait until created tables become visible in Cassandra tests
> Wait until created tables become visible in Cassandra tests

- docs/src/main/sphinx/client/cli.rst
Add descriptions to keystore and truststore types
Add descriptions to keystore and truststore types
```markdown
```
> Add description to keystore and truststore types

- docs/src/main/sphinx/connector/hive-s3.rst
Added anchors so that docs can link to sections.
> Add anchors for linking purposes

- lib/trino-collect/src/main/java/io/trino/collect/cache/EmptyCache.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
no release notes,
approved as prefix in https://github.com/trinodb/trino/pull/15811
> Cleanup of caching metastore

- core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
> Put dynamic filtering comment before right PredicatePushDown call

- docs/src/main/sphinx/connector/iceberg.rst
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/CountingAccessHiveMetastore.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/TrinoCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/UnregisterTableProcedure.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergGcsConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConnectorSmokeTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
- testing/trino-testing-containers/src/main/java/io/trino/testing/minio/MinioClient.java
Relates to #15784
```markdown
* Add support for `unregister_table` procedure. ({issue}`15784`)
```
> Add unregister_table procedure to Iceberg connector

- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetSchemaConverter.java
> `ParquetSchemaConverter` code cosmetics

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
> Disallow using of single-entry loader in bulk cache

- pom.xml
> Update to Jetty 10

- core/trino-spi/pom.xml
Extracted from https://github.com/trinodb/trino/pull/15842
> Remove outdated SPI revapi exclusions

- .github/workflows/ci.yml
- plugin/trino-iceberg/pom.xml
> Separate profile for Iceberg REST and JDBC catalog tests

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
Use optional binding for `GlueHiveMetastoreFactory`.
```markdown
```
> Use optional binding for GlueHiveMetastoreFactory

- core/trino-main/src/main/java/io/trino/operator/exchange/UniformPartitionRebalancer.java
Prevent potential division by zero
> Prevent division by 0

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeColumnHandle.java
> `trino-delta-lake` Remove unused field

- pom.xml
> Update docker-images to version 76

- .github/workflows/ci.yml
As requested in https://github.com/trinodb/trino/pull/15926#discussion_r1093421371
> Make titles of check commit jobs more readable

- docs/src/main/sphinx/connector/sqlserver.rst
Update SQL Server connector document `database -> databaseName`
Ref: [SQL Server JDBC Example](https://learn.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver16#connection-examples)
```markdown
```
> Update SQL Server connector document `database -> databaseName`

- docs/src/main/sphinx/client/cli.rst
- docs/src/main/sphinx/client/jdbc.rst
- for the CLI and the JDBC driver
Discussed on slack at https://trinodb.slack.com/archives/C01TEP0HJTH/p1673554134517209
> Add version compatibility information

- docs/src/main/sphinx/develop/connectors.rst
> Dev guide for WHERE predicate pushdown

- core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantWindow.java
- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/QueryCardinalityUtil.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
- core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveRedundantWindow.java
```markdown
* Optimize certain queries involving window.
```
> Add optimizer rule to prune redundant WindowNode

- pom.xml
Update trino-maven-plugin to 12
> Update trino-maven-plugin to 12

- core/trino-spi/src/main/java/io/trino/spi/PageBuilder.java
The actual method name is `newPageBuilderLike` which is wrongly referenced in the comment as `createPageBuilderLike`.
> Fix typo in PageBuilder

- .github/workflows/ci.yml
- plugin/trino-iceberg/pom.xml
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAbfsConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/resources/hdp3.1-core-site.xml.abfs-template
> Run ConnectorSmokeTests against Iceberg with Azure ABFS

- core/trino-main/src/main/java/io/trino/operator/StreamingDirectExchangeBuffer.java
- core/trino-main/src/test/java/io/trino/operator/TestStreamingDirectExchangeBuffer.java
All threads in ExchangeOperator are woken up when a single page is available for processing.  PR limits this so the number of threads waking up matches the number of pages available.  
Concurrency benchmark results (how many queries Trino can perform with 32 clients):
|  | Queries per hour |
| ------------- | ------------- |
| Baseline  | 8016  |
| PR  | 8534  |
> Avoid unblocking more ExchangeOperators than necessary in exchange buffer

- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTableStatistics.java
Fixes flaky issue:
https://github.com/trinodb/trino/actions/runs/4163493963/jobs/7205919211
> Add `@Flaky` annotation to TestHiveTableStatistics

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAnalyze.java
> Improve analyze error message in Delta Lake connector

- core/trino-main/src/main/java/io/trino/server/Server.java
Use a dedicated exit status code for all Trino start up crashes to help distinguish Trino start up issues from container and environment failures.
Based on conversation with @electrum, this supercedes the changes in #16049
> Use exit status code 100 for Trino start up crashes

- core/trino-main/pom.xml
- core/trino-main/src/main/java/io/trino/server/Server.java
- core/trino-main/src/main/java/io/trino/server/security/ServerSecurityModule.java
- pom.xml
This adds support to Trino for scraping metrics via openmetrics. This includes Prometheus.
( X ) Release notes are required, please propose a release note for me.
```markdown
```
> Add openmetrics to Trino for exposing metrics

- .github/workflows/ci.yml
I wanted to see if the `test (plugin/trino-iceberg, additional-catalog-tests)` job runs the same tests that are in `test (plugin/trino-iceberg)` but we don't have a report for it, only
`test report test (plugin_trino-iceberg)`.
> Include test profile and jdk in CI artifact name

- docs/src/main/sphinx/release/release-407.md
> Fix typo in 407 release notes

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCheckpointsCompatibility.java
> Adjust delta lake product tests to collect statistics on write changes

- core/trino-spi/src/main/java/io/trino/spi/security/AccessDeniedException.java
> Add AccessDeniedException.denySetViewComment

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaHiveTypeTranslator.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveTypeTranslator.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java
> Remove usages of HiveChar and HiveVarchar

- lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoOutputFile.java
- lib/trino-filesystem/src/main/java/io/trino/filesystem/fileio/ForwardingOutputFile.java
- lib/trino-orc/src/main/java/io/trino/orc/OutputStreamOrcDataSink.java
- plugin/trino-delta-lake/pom.xml
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSchemaProperties.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriterManager.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/AzureTransactionLogSynchronizer.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/NoIsolationSynchronizer.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3NativeTransactionLogSynchronizer.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointWriter.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetFileWriter.java
> Use native ParquetWriter in Delta CheckpointWriter

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/MetaDirStatisticsAccess.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreStatistics.java
Migrate more code to `TrinoFileSystem` in Delta Lake
Relates to #16020
> Migrate more code to `TrinoFileSystem` in Delta Lake

- lib/trino-parquet/src/main/java/io/trino/parquet/ParquetCompressionUtils.java
- lib/trino-parquet/src/main/java/io/trino/parquet/predicate/PredicateUtils.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/PageReader.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetCompressor.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriters.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/AbstractColumnReaderBenchmark.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/AbstractColumnReaderRowRangesTest.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestInt96Timestamp.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestPageReader.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetReaderMemoryUsage.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/flat/TestFlatColumnReader.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveCompressionCodec.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetFileWriter.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetFileWriterFactory.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/ParquetTester.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestBloomFilterStore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestTimestamp.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergParquetFileWriter.java
> Use Parquet CompressionCodec instead of CompressionCodecName

- plugin/trino-hive/pom.xml
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveToTrinoTranslator.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/KerberosHiveMetastoreAuthentication.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/rcfile/RcFilePageSourceFactory.java
> Replace various Hive usages

- docs/src/main/sphinx/connector/iceberg.rst
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcCatalogConfig.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcCatalogModule.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcConnectionFactory.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConfig.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcConnectorTest.java
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-jdbc-catalog/iceberg.properties
Require driver class in Iceberg JDBC catalog. 
```markdown
* Require `iceberg.jdbc-catalog.driver-class` config property to prevent driver not found error after the initialization ({issue}`16196`)
```
> Require driver class in Iceberg JDBC catalog 

- testing/trino-testing-containers/pom.xml
- testing/trino-testing-containers/src/main/java/io/trino/testing/containers/PlatformChecks.java
- testing/trino-testing-containers/src/main/resources/testcontainers.properties
> Warn users if Docker arch does not match host arch

- core/trino-main/src/main/java/io/trino/sql/planner/planprinter/NodeRepresentation.java
- core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
What is says in the title, really :)
Extracted from #14933.
```markdown
```
> Annotate NodeRepresentation#appendDetails as a format method

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftMetastoreUtil.java
Use HiveColumnStatistics builder with assertions.
> Assertion cleanup in TestThriftMetastoreUtil

- docs/src/main/sphinx/admin/properties-query-management.rst
- Adds documentation for adaptive remote task request size to Query management properties
- first pass at documentation for: https://github.com/trinodb/trino/pull/15721
```markdown
```
> Add config props for adaptive remote task req size

- docs/src/main/sphinx/connector/bigquery.rst
- docs/src/main/sphinx/connector/druid.rst
- docs/src/main/sphinx/connector/elasticsearch.rst
- docs/src/main/sphinx/connector/mariadb.rst
- docs/src/main/sphinx/connector/mysql.rst
- docs/src/main/sphinx/connector/oracle.rst
- docs/src/main/sphinx/connector/postgresql.rst
- docs/src/main/sphinx/connector/redshift.rst
- docs/src/main/sphinx/connector/sqlserver.rst
Adds additional catalog context to the table function sections in supporting connectors.
```markdown
```
> Add additional catalog context to table function docs

- plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
- plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
Join pushdown for case sensitive columns in SqlServer
With this change trino will be able to perform join pushdown on case sensitive varchar/nvarchar columns.
```markdown
```
> Join pushdown for case sensitive columns in SqlServer

- core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryContext.java
Fix typo in QueryContext message
```markdown
```
> Fix typo in QueryContext message

- core/trino-main/src/main/java/io/trino/server/PluginInstaller.java
- core/trino-main/src/main/java/io/trino/server/PluginManager.java
- core/trino-main/src/main/java/io/trino/server/Server.java
- core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
- core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
Allow to override PluginManager
> Allow to override PluginManager

- testing/trino-testing-containers/src/main/java/io/trino/testing/containers/PlatformChecks.java
> Do not try to pull image if it exists

- plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java
> Enable the ClickHouse testAddColumnConcurrently and testInsertRowConcurrently

- plugin/trino-ignite/pom.xml
- plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClientModule.java
- plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteJdbcConfig.java
- plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteJdbcConfig.java
Fixes #16148
Add Ignite jdbc config file.
> Add Ignite jdbc config class to deny invalid connection URL

- plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/PhoenixQueryRunner.java
https://github.com/trinodb/trino/pull/16292
We should not close the testing server while success starting the local query server for testing.
```markdown
```
> Remove error closing TestingPhoenixServer

- .github/config/labeler-config.yml
Update `labeler-config.yml` to add some connectors
>  Update `labeler-config.yml` to add some connectors

- lib/trino-parquet/src/main/java/io/trino/parquet/reader/AbstractColumnReader.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/FilteredRowRanges.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/MetadataReader.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/NestedColumnReader.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FlatColumnReader.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/AbstractColumnReaderTest.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestNestedColumnReader.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/flat/TestFlatColumnReader.java
A few small cleanups, addition of debug logs and minor improvements
> Minor improvements in parquet reader

- docs/src/main/sphinx/connector/delta-lake.rst
> Move `VACUUM` under `SQL support` section

- docs/src/main/sphinx/connector/hive.rst
Document how to create separators in Hive csv files.
(s) This is not user-visible or docs only and no release notes are required.
```markdown
```
> Document separator examples for csv files

- lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoInput.java
- lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoInputFile.java
- lib/trino-filesystem/src/main/java/io/trino/filesystem/local/FileSeekableInputStream.java
- lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalInput.java
- lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalInputFile.java
- lib/trino-filesystem/src/main/java/io/trino/filesystem/memory/MemoryInput.java
- lib/trino-filesystem/src/main/java/io/trino/filesystem/memory/MemoryInputFile.java
- lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsInput.java
- lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsInputFile.java
- lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsSeekableInputStream.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/sequence/SequenceFileReader.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/text/TextLineReaderFactory.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/rcfile/RcFileReader.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/MetaDirStatisticsAccess.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogParser.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TransactionLogTail.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3NativeTransactionLogSynchronizer.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/AccessTrackingFileSystemFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/MonitoredTrinoInputFile.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/line/LinePageSourceFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/rcfile/RcFilePageSourceFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/AcidTables.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/fileio/ForwardingInputFile.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TrackingFileSystemFactory.java
> Move InputStream from TrinoInput to TrinoInputFile

- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSchemaLiteral.java
> Use text blocks to define `SCHEMA_LITERAL`

- plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java
> Remove ClickHouse test 'testAddColumn' by override the 'tableDefinitionForAddColumn'

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeTableWithCustomLocation.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/FileTestingTransactionLogSynchronizer.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeGcsConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableWithCustomLocationUsingGlueMetastore.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableWithCustomLocationUsingHiveMetastore.java
Relates to https://github.com/trinodb/trino/issues/16020
> Migrate to TrinoFileSystem

- plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java
The original test implementation did not drop the created table when finished.
Update the create table statement and move the `assertQueryFails` tests above
Also fix the typo in comment 'order_by/order_by'
> Update ClickHouse 'testDropColumn' test

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
> Fix typo in TestIcebergV2

- docs/src/main/sphinx/connector/clickhouse.rst
> Remove note about legacy Clickhouse driver

- plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorTest.java
> Remove unnecessary override method testColumnName in ClickHouse

- docs/src/main/sphinx/connector/ignite.rst
We do not support join pushdown in Ignite yet
> Remove supports join pushdown doc in Ignite 

- plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/ImplementAvgBigint.java
> Update Ignite 'ImplementAvgBigint' implementation

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeRegisterTableProcedureTest.java
- plugin/trino-delta-lake/src/test/resources/io/trino/plugin/deltalake/hdp3.1-core-site.xml.gcs-template
> Add tests for trailing space in location in delta lake

- lib/trino-filesystem/src/main/java/io/trino/filesystem/FileEntry.java
- lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoInputFile.java
- lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalInputFile.java
- lib/trino-filesystem/src/main/java/io/trino/filesystem/memory/MemoryInputFile.java
- lib/trino-filesystem/src/test/java/io/trino/filesystem/TestFileEntry.java
- lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsFileIterator.java
- lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsInputFile.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/AccessTrackingFileSystemFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/MonitoredTrinoInputFile.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/TrinoFileStatus.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TrackingFileSystemFactory.java
> Use Instant for Trino FileSystem last modified time

- plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java
- plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteClient.java
- plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
Finish https://github.com/trinodb/trino/issues/16342
```markdown
* Support aggeration count(distinct) pushdown in Ignite (`16342`)
```
> Support pushdown count(distinct) in Ignite

- core/trino-main/src/test/java/io/trino/execution/BaseDataDefinitionTaskTest.java
- core/trino-main/src/test/java/io/trino/execution/TestAddColumnTask.java
- core/trino-main/src/test/java/io/trino/execution/TestDropColumnTask.java
> Add TestAddColumnTask and TestDropColumnTask

- pom.xml
> Update Aircompressor to 0.24

- plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
> Rearrange connectorBeahvior branch order in TestIgniteConnectorTest

- plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java
- plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
Fix https://github.com/trinodb/trino/issues/16428
```markdown
* Support Ignite (inner, left, right) join push down. ({issue}`16428`)
```
> Support Ignite (inner, left, right) join pushdown

- docs/src/main/sphinx/connector/hive-azure.rst
- Reorder Azure storage in the Hive-Azure docs
- Add legacy label to titles for minimally supported storage options
- Add more explicit ADLS Gen2 recommendation, since others will be removed in future
https://github.com/trinodb/trino/issues/16352
```markdown
```
> reorder azure storage

- plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTypeConverter.java
- plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
- plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotIntegrationConnectorSmokeTest.java
- plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java
- plugin/trino-pinot/src/test/resources/hybrid_offlineSpec.json
- plugin/trino-pinot/src/test/resources/hybrid_realtimeSpec.json
- plugin/trino-pinot/src/test/resources/hybrid_schema.json
- plugin/trino-pinot/src/test/resources/pinot-controller/pinot-controller-secured.conf
- plugin/trino-pinot/src/test/resources/pinot-server/pinot-server-secured.conf
Fix time boundary handling for server queries
```markdown
```
> Fix Pinot Timeboundary handling

- core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
Fix validation of session variable MAX_HASH_PARTITION_COUNT
( *) This is not user-visible or docs only and no release notes are required.
> Fix validation of session variable MAX_HASH_PARTITION_COUNT

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogAccessOperations.java
Fix CI failure: https://github.com/trinodb/trino/actions/runs/4432270702/jobs/7777374729?pr=16564
> Add REFS to TestIcebergGlueCatalogAccessOperations.testSelectSystemTable

- core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
Fix logic stage scheduling logic in FTE mode
fixes https://github.com/trinodb/trino/issues/16577
> Fix stage scheduling logic in FTE mode

- docs/src/main/sphinx/functions/aggregate.rst
See PR title. As discussed with user and @martint on slack.
> Improve docs for skewness function

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java
> Allow to disable transactional directory listing cache

- docs/src/main/sphinx/admin/spill.rst
- docs/src/main/sphinx/client/cli.rst
- docs/src/main/sphinx/client/jdbc.rst
- docs/src/main/sphinx/connector/bigquery.rst
- docs/src/main/sphinx/connector/hive-azure.rst
- docs/src/main/sphinx/connector/sqlserver.rst
- docs/src/main/sphinx/functions/binary.rst
- docs/src/main/sphinx/functions/datetime.rst
- docs/src/main/sphinx/functions/geospatial.rst
- docs/src/main/sphinx/functions/hyperloglog.rst
- docs/src/main/sphinx/functions/setdigest.rst
- docs/src/main/sphinx/functions/string.rst
- docs/src/main/sphinx/glossary.rst
- docs/src/main/sphinx/installation/kubernetes.rst
- docs/src/main/sphinx/language/types.rst
- docs/src/main/sphinx/security/jwt.rst
- docs/src/main/sphinx/security/tls.rst
* Removes language codes from external URLs in multiple files to better accommodate a global audience
```markdown
```
> Remove language codes from external URLs

- docs/src/main/sphinx/develop/supporting-merge.rst
> Fix merge doc written demo value error

- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/rcfile/RcFileReader.java
> Use existing variable for file length

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeBucketFunction.java
Align hashing implementation with the one in
`BlackHoleNodePartitioningProvider`.
> Avoid boxing in DeltaLakeBucketFunction

- docs/src/main/sphinx/connector/hudi.rst
- Adds a minimum version number to the **Requirements** section for the Hudi connector
```markdown
```
> Add version requirement for Hudi connector

- plugin/trino-bigquery/pom.xml
> Fix test class name in BigQuery cloud-tests profile

- core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
- core/trino-main/src/main/java/io/trino/metadata/OperatorNameUtil.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ImplementLimitWithTies.java
> Fix import of wrong Preconditions class

- testing/trino-product-tests/src/main/java/io/trino/tests/product/TestImpersonation.java
Example failure: https://github.com/trinodb/trino/actions/runs/4492207167/jobs/7903860899?pr=16651
> Add retries in TestImpersonation

- plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
> Remove unnecessary override method in phoenix metadata

- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSinkProvider.java
> Make queryModifier final

- core/trino-spi/src/main/java/io/trino/spi/metrics/Metrics.java
- lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/metrics/TestMetrics.java
Remove superfluous accumulator add function 
- Enhance the test case as well
```markdown
```
> Remove superfluous accumulator add function

- pom.xml
These are not used in embedded mode.
> Remove unused dependencies from discovery-server

- pom.xml
> Update to ASM 9.4

- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentDescribe.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/ContainerListener.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/DockerContainer.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Environment.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentListener.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/util/ConsoleTable.java
> Allow listening for single container events

- docs/src/main/sphinx/connector/hive.rst
> fix typo in hive parquet doc

- core/trino-main/src/test/java/io/trino/server/security/oauth2/TestingHydraIdentityProvider.java
> Ensure that TestingHydraIdentityProvider is releasing resources

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
> Make construction parameters final

- plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
- plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
https://github.com/trinodb/trino/issues/16732
```markdown
* Support arithmetic predicate pushdown. ({issue}`16732`)
```
> Support arithmetic predicate pushdown for Phoenix

- docs/src/main/sphinx/connector/iceberg.rst
**THERE ARE NO TECHNICAL CONTENT CHANGES TO EXISTING MATERIAL IN THIS PR**
This PR is a follow-on to PR#15637. It reorganizes the Iceberg connector documentation to match the structure of the Hive connector documentation and, as with the Hive PR, does the following:
- Fixes problematic verb tenses as per Google Developer Style Guide (must use present tense only).
These included would, should, could, needs to, will be; there were not many instances.
- Formats the few tables remaining in the old format to the list table format (and of course adds table titles). 
- Adds intro blurbs where there were none for the following section headers:
- Metastores
- Security
- Procedures (used same language as the Hive blurb)
- Table properties (used same language as the Hive blurb)
- View management …
> Reorganize Iceberg connector documentation

- pom.xml
Airbase already has `4.7.3`
```markdown
```
> Bump spotbugs-annotations version

- docs/src/main/sphinx/connector/ignite.rst
> Add doc for ignite join pushdown

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveAnalyzeCorruptStatistics.java
Add test for duplicated partition statistics on Thrift metastore. `PART_COL_STATS` is another table storing statistics in metastore database.
> Add test for duplicated partition statistics on Thrift metastore

- core/trino-main/src/main/java/io/trino/sql/planner/DeterminismEvaluator.java
> Early stop searching when meet the condition in visitor

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
CacheFactory has only one, annonymous implementation so it only adds complexity.
```markdown
```
> Drop redundant CacheFactory interface

- lib/trino-orc/src/main/java/io/trino/orc/TupleDomainOrcPredicate.java
- plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/Statistics.java
> Replace lambda with identity function

- core/trino-spi/src/main/java/io/trino/spi/QueryId.java
> Simplify the QueryId code

- core/trino-main/src/main/java/io/trino/execution/scheduler/BinPackingNodeAllocatorService.java
- core/trino-main/src/main/java/io/trino/operator/aggregation/ApproximateDoublePercentileArrayAggregations.java
- core/trino-main/src/main/java/io/trino/operator/scalar/TDigestFunctions.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/metrics/TDigestHistogram.java
- lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/metrics/TestMetrics.java
> Minor cleanups around TDigest

- core/trino-main/src/main/java/io/trino/sql/gen/PageFunctionCompiler.java
This PR hoists creating `MethodHandle` that refers to `PageProjection`'s constructor. Currently, for most queries, 
for every created `PageProjection` engine creates a `MethodHandle` that refers to a `PageProjectionWork`'s constructor, even when it is cached. Creating (possibly many) `MethodHandles` for every query is not a correct approach because it is a heavy operation for JVM:
1.  Create `MethodHandle` and find a proper `LambaForm` for this `MethodHandle`.
2. If `MethodHandle` will be called sufficient number of times, customize this `LambdaForm` - generate bytecode for customized LambdaForms (!)
3. After some time, JIT needs to compile every class. (!)
4. It repeats and repeats for every query.
It can be avoided, so let's do it. 
Currently, for every executed query (with projections …
> Hoist a creating MethodHandle to PageProjection constructor

- pom.xml
Changelog: https://github.com/testcontainers/testcontainers-java/releases/tag/1.18.0
```markdown
```
> Update testcontainers to 1.18.0

- pom.xml
> Update AWS SDK to 1.12.445

- pom.xml
> Update JDBI to 3.37.1

- docs/src/main/sphinx/glossary.rst
Three glossary entries were in title case vs sentence case
I changed these for consistency (we use sentence case across all docs)
Small change
```markdown
```
> Change all glossary entries to sentence case

- docs/src/main/sphinx/release/release-408.md
> Add missing connector renames to 408 release notes

- core/trino-main/pom.xml
- pom.xml
> Update oshi to 6.4.1

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java
Don't retry table metadata read when cause is FileNotFoundException
> Don't retry table metadata read when cause is FileNotFoundException

- pom.xml
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergRest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeChangeDataFeedCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergPartitionEvolution.java
Update docker-images to version 79
> Update docker-images to version 79

- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientConfig.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientModule.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientSettingConfigurator.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSslConfig.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSslModule.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoClientConfig.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoSslConfig.java
We introduce `MongoClientSettingConfigurator` which allows us extract SSL related changes to a dedicated module. 
> Minor cleanup in MongoDB connector

- lib/trino-filesystem/pom.xml
- lib/trino-filesystem/src/main/java/io/trino/filesystem/Locations.java
- lib/trino-filesystem/src/test/java/io/trino/filesystem/TestLocations.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/GcsStorageFactory.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/AzureTransactionLogSynchronizer.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/GcsTransactionLogSynchronizer.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/NoIsolationSynchronizer.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3NativeTransactionLogSynchronizer.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogSynchronizer.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogSynchronizerManager.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogWriter.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogWriterFactory.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/FileTestingTransactionLogSynchronizer.java
Origin of this change is to migrate to TrinoFileSystem
Relates to https://github.com/trinodb/trino/issues/16020
```markdown
```
> Replace usage hadoop.fs.Path with String in Delta part 2

- core/trino-main/src/test/java/io/trino/operator/scalar/TestStringFunctions.java
Remove unnecessary TODO comments
```markdown
```
> Remove unnecessary TODO comments

- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduPageSink.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Fix https://github.com/trinodb/trino/issues/16848
```markdown
* Fix Kudu merge error between two tables that created by CTAS. ({issue}`16848`)
```
> Fix Kudu merge error between two CTAS table

- core/trino-main/src/main/java/io/trino/metadata/InMemoryNodeManager.java
- core/trino-main/src/main/java/io/trino/metadata/InternalNodeManager.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/TestBinPackingNodeAllocator.java
> Fix test flakiness

- pom.xml
Upgrading benchto-driver to 0.24 version
Release notes
( *) This is not user-visible or docs only and no release notes are required.
> Update Benchto dependency to 0.24 ver

- lib/trino-orc/src/test/java/io/trino/orc/TestFullOrcReader.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileFormats.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestFullParquetReader.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestOptimizedParquetReader.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetReader.java
Fixes https://github.com/trinodb/trino/issues/17021
> Fix TestHiveFileFormats flakiness due to Apache Parquet reader

- pom.xml
This version is faster and should speed up the CI, reducing the queue.
> Update TPCH generator library version

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
> Show `partitioned_by` property only for partitioned tables

- core/trino-main/src/main/java/io/trino/execution/SqlQueryExecution.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/Analyzer.java
- core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveEmptyMergeWriterRuleSet.java
- core/trino-main/src/main/java/io/trino/sql/rewrite/DescribeInputRewrite.java
- core/trino-main/src/main/java/io/trino/sql/rewrite/DescribeOutputRewrite.java
- core/trino-main/src/main/java/io/trino/sql/rewrite/ShowStatsRewrite.java
* Fix an error message across multiple files.
* Add a missing node to a rule pattern's documentation.
> Fix an error message and a documentation

- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
> Disable testInsertRowConcurrently in BigQuery

- pom.xml
> Update nimbus dependencies

- core/trino-main/src/main/java/io/trino/sql/gen/PageFunctionCompiler.java
References to blocks can be stored as fields in the generated page projection class instead doing an array lookup inside the per position projection evaluation
JMH run of BenchmarkPageProcessor is with filterExpression commented out to focus only on projection performance
```
Benchmark                         Mode  Cnt  Before Score         Units  After Score          Units
BenchmarkPageProcessor.compiled  thrpt   50  16895.908 ± 220.957  ops/s  18559.615 ± 395.478  ops/s
```
```markdown
```
> Reduce Page#getBlock calls in page projection

- plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
Fix https://github.com/trinodb/trino/issues/17061
> Returns empty stats for table without stats on Postgres 14+

- plugin/trino-iceberg/pom.xml
> Remove unnecessary enforcer configuration for Iceberg

- core/trino-main/src/main/java/io/trino/connector/FileCatalogStore.java
> Minor FileCatalogStore improvements

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastore.java
> Add missing Tracer binding in Delta Lake Glue tests

- lib/trino-hdfs/pom.xml
- lib/trino-hdfs/src/main/java/io/trino/hdfs/FileSystemFinalizerService.java
- lib/trino-hdfs/src/main/java/io/trino/hdfs/HdfsEnvironment.java
- lib/trino-hdfs/src/main/java/io/trino/hdfs/TrinoFileSystemCache.java
- plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsConnector.java
> Cleanup Hadoop file systems on connector shutdown

- core/trino-main/src/test/java/io/trino/sql/TestExpressionInterpreter.java
- docs/src/main/sphinx/functions/comparison.rst
> Fix comparison documentation for BETWEEN and NULL

- plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/systemtables/ShardMetadataRecordCursor.java
This caused `BaseRaptorConnectorTest.testShardsSystemTable` to be flaky due to other tables being concurrently dropped.
> Fix spurious failure for Raptor system.shards table

- core/trino-main/src/main/java/io/trino/connector/system/SystemConnector.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnector.java
- plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisConnector.java
- plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryConnector.java
- plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisConnector.java
Follows https://github.com/trinodb/trino/pull/17110 / https://github.com/trinodb/trino/pull/17110/commits/1c7aa974e5fdf34c7d557fe2c931259a76712188
> Shutdown BigQuery, Kinesis, Redis and Memory connectors

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
Follow up of https://github.com/trinodb/trino/pull/17085#discussion_r1172430382
Remove unnecessary schema conversion in DeltaLakeMetadata#setTableComment
There is no need to convert ConnectorTableMetadata -> DeltaLakeColumnHandle -> SchemaAsString. We can directly get the schemaAsString from MetadataEntry.
> Use MetadataEntry#getSchemaString in DeltaLakeMetadata#setTableComment

- pom.xml
This version includes a much newer version of Jackson in its shaded JAR.
```markdown
```
> Bump calcite-core

- docs/src/main/sphinx/connector/ignite.rst
- plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java
- plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestingIgniteContainer.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeIgnite.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Fix https://github.com/trinodb/trino/issues/16380
Fix https://github.com/trinodb/trino/issues/16882
Update Ignite support version from 2.8 to 2.9
https://github.com/trinodb/trino/pull/17102
> Upgrade Ignite test container version to 2.9

- lib/trino-hdfs/src/main/java/io/trino/hdfs/FileSystemFinalizerService.java
- lib/trino-hdfs/src/main/java/io/trino/hdfs/HdfsEnvironment.java
> Avoid starting thread if no file systems were created

- pom.xml
> Update to Airbase 137 and Airlift 230

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveColumnProjectionInfo.java
Inspired from the changes in the PR https://github.com/trinodb/trino/pull/17085
> Small improvements on `HiveColumnProjectionInfo`

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/CorruptedDeltaLakeTableHandle.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadataFactory.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableHandle.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/LocatedTableHandle.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/DeltaLakeMetastore.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/DeltaMetastoreTable.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/DropExtendedStatsProcedure.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/FlushMetadataCacheProcedure.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/RegisterTableProcedure.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/UnregisterTableProcedure.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/DeltaLakeTableStatisticsProvider.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/FileBasedTableStatisticsProvider.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePerTransactionMetastoreCache.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreAccessOperations.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreStatistics.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/statistics/TestDeltaLakeFileBasedTableStatisticsProvider.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBackgroundHiveSplitLoader.java
relates to https://github.com/trinodb/trino/issues/13198
> Decouple Delta's metastore and transaction log access

- docs/src/main/sphinx/functions/json.rst
Link from the JSON_EXTRACT function section to the JSON_QUERY function section.
```markdown
```
> Add link to JSON_QUERY function

- docs/src/main/sphinx/connector/delta-lake.rst
> Document logical file statistics for Delta Lake

- client/trino-client/src/test/java/io/trino/client/auth/external/TestExternalAuthenticator.java
- core/trino-main/src/main/java/io/trino/server/security/oauth2/JweTokenSerializer.java
- core/trino-parser/src/main/java/io/trino/sql/tree/QualifiedName.java
- lib/trino-parquet/src/main/java/io/trino/parquet/ParquetWriteValidation.java
- plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSession.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoQueryRunner.java
- plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotExpressionRewriter.java
Previous edition: 9e5542c5eb6c687f19b1989c6a87b14e1dfedab4
One year's worth of raw types :)
```markdown
```
> Clean up raw types

- pom.xml
- testing/trino-product-tests-launcher/pom.xml
- testing/trino-product-tests/pom.xml
This brings snakeyaml 2.0 dependency and better support for Java records
> Update airbase to 138 (and jackson to 2.15.0)

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeRegisterTableProcedureTest.java
Delta Lake CI is failing in master branch: https://github.com/trinodb/trino/actions/runs/4834281639/jobs/8616983788
Fixes #17295
> Fix Delta Lake CI failure

- core/trino-main/src/main/java/io/trino/operator/table/ExcludeColumns.java
- core/trino-main/src/main/java/io/trino/operator/table/Sequence.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- core/trino-main/src/test/java/io/trino/connector/TestingTableFunctions.java
- core/trino-spi/src/main/java/io/trino/spi/ptf/AbstractConnectorTableFunction.java
- core/trino-spi/src/main/java/io/trino/spi/ptf/ConnectorTableFunction.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorTableFunction.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ptf/Procedure.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ptf/Query.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ptf/Query.java
- plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/ptf/Query.java
- plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ptf/RawQuery.java
- plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/ptf/Sheet.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ptf/Query.java
- testing/trino-tests/src/test/java/io/trino/tests/TestTableFunctionInvocation.java
Adds access control capabilities to PTF on table and column levels.
```markdown
* Adds access control to PTF ({issue}`issuenumber`)
```
> Add AccessControl io.trino.spi.ptf.ConnectorTableFunction#analyze

- core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
```markdown
* Fix resource accounting leak which could result blocking queries when run with `retry-mode` set to `TASK`. ({issue}`issuenumber`)
```
> Fix node allocation account leak on race condition

- docs/src/main/sphinx/functions/datetime.rst
Improved the documentation for at_timezone and with_timezone to clarify the difference between those two functions
Added examples to both functions
```markdown
```
> Improve docs for at_timezone and with_timezone

- pom.xml
Upgrade Alluxio to 2.9.3
Bug fixing and enable local cache support in the future
> Upgrade alluxio to 2.9.3

- pom.xml
> Upgrade okhttp to 4.11 (from 4.10)

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/BenchmarkFileFormat.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/BenchmarkHiveFileFormat.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/StandardFileFormats.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/TestHiveFileFormatBenchmark.java
These are not necessary anymore as we use native
Trino readers for orc, parquet and rcfile
> Remove hive record reader JMH benchmarks

- .github/workflows/milestone.yml
> Print milestone command output for debug

- core/trino-main/src/main/java/io/trino/execution/SetTimeZoneTask.java
- core/trino-main/src/main/java/io/trino/operator/scalar/DateTimeFunctions.java
- core/trino-main/src/main/java/io/trino/operator/scalar/time/TimeFunctions.java
- core/trino-main/src/main/java/io/trino/operator/scalar/timetz/DateAdd.java
- core/trino-main/src/main/java/io/trino/operator/scalar/timetz/DateDiff.java
- core/trino-main/src/main/java/io/trino/operator/scalar/timetz/DateTrunc.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
- core/trino-main/src/main/java/io/trino/type/DateTimes.java
- core/trino-main/src/test/java/io/trino/execution/TestSetTimeZoneTask.java
- core/trino-main/src/test/java/io/trino/operator/scalar/interval/TestIntervalDayTime.java
- core/trino-main/src/test/java/io/trino/operator/scalar/interval/TestIntervalYearMonth.java
- core/trino-main/src/test/java/io/trino/operator/scalar/time/TestTime.java
- core/trino-main/src/test/java/io/trino/operator/scalar/timestamp/TestTimestamp.java
- core/trino-main/src/test/java/io/trino/operator/scalar/timestamptz/TestTimestampWithTimeZone.java
- core/trino-main/src/test/java/io/trino/operator/scalar/timetz/TestTimeWithTimeZone.java
- core/trino-main/src/test/java/io/trino/type/TestDate.java
- core/trino-spi/src/main/java/io/trino/spi/type/Decimals.java
- core/trino-spi/src/test/java/io/trino/spi/type/TestDecimals.java
- testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java
These are SQL keywords and we should make their usage consistent
Release notes not needed
> Make type names upper case

- docs/src/main/sphinx/security/ldap.rst
line 100，keystore shuold be truststore
> Fix typo in ldap.rst

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeProjectionPushdownPlans.java
Due to merge conflicts.
https://github.com/trinodb/trino/pull/17085
https://github.com/trinodb/trino/pull/17190
> Fix reference to createTestingFileHiveMetastore in test

- docs/.vale/Vocab/Base/accept.txt
- docs/src/main/sphinx/connector.rst
- docs/src/main/sphinx/functions.rst
- docs/src/main/sphinx/glossary.rst
- docs/src/main/sphinx/language.rst
- docs/src/main/sphinx/sql.rst
- Use section instead of chapter
- Use Oxford comma
- Fix spelling
> Improve writing style in top-level pages

- docs/src/main/sphinx/language/sql-support.rst
- docs/src/main/sphinx/sql.rst
- docs/src/main/sphinx/sql/deny.rst
- docs/src/main/sphinx/sql/grant.rst
- docs/src/main/sphinx/sql/revoke.rst
This PR documents `DENY` statement.
Fixes #11306
> Document DENY statement

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java
> Remove unused bindings from DeltaLakeModule

- pom.xml
Upgrade benchto version to 0.25
( *) This is not user-visible or docs only and no release notes are required.
> Upgrade benchto version to 0.25

- docs/src/main/sphinx/connector/hive-gcs-tutorial.rst
- docs/src/main/sphinx/connector/hive.rst
Make Google Cloud Storage page a reference page that is not Hive-centric.
```markdown
```
> Re-cast Google Cloud Storage Tutorial as reference page

- docs/src/main/sphinx/connector/mysql.rst
> Fix Mysql doc typo

- plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
> Fix Ignite connector test name typo

- docs/src/main/sphinx/connector/phoenix.rst
> Add sql merge support in Phoenix doc

- docs/src/main/sphinx/release.rst
- docs/src/main/sphinx/release/release-417.md
Assemble the release notes for the upcoming Trino 417 release. Fixes #17339 
* #17340 ✅ rn ✅ docs
* #17301 ✅ rn ✅ docs
* #17335 ✅ rn ✅ docs
* #17282 ✅ rn ✅ docs
* #17336 ✅ rn ✅ docs
* #17249 ✅ rn ✅ docs
* #17251 ✅ rn ✅ docs
* #17349 ✅ rn ✅ docs
* #17337 ✅ rn ✅ docs
* #17345 ✅ rn ✅ docs
* #17244 ✅ rn ✅ docs
* #17354 ✅ rn ✅ docs
* #17356 ❌ rn ✅ docs
* #16670 ✅ rn ✅ docs
* #17364 ✅ rn ✅ docs
* #17190 ✅ rn ✅ docs
* #17363 ✅ rn ✅ docs
* #17078 ✅ rn ✅ …
> Add Trino 417 release notes

- pom.xml
This updates RoaringBitmap to the latest version, which is 0.9.44
> Update RoaringBitmap from 0.9.35 to 0.9.44

- docs/src/main/sphinx/connector/delta-lake.rst
Add the configuration properties to the general configuration properties section to have all of them centralised.
> Add documentation for Delta Lake configuration properties

- docs/src/main/sphinx/connector/clickhouse.rst
- pom.xml
Update the ClickHouse JDBC driver to the latest patch release to fix a security issue (client certificate password exposure) and a severe deserialization issue when handling nested arrays.
Fixes #17020.
```markdown
```
> Bump ClickHouse driver to 0.4.6 and fix broken link

- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/util/Functions.java
- plugin/trino-delta-lake/pom.xml
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeColumnHandle.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConnector.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeFunctionProvider.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/InternalDeltaLakeConnectorFactory.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesFileType.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesFunction.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesFunctionProcessor.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesFunctionProvider.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesProcessorProvider.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesSplit.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesSplitSource.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesTableFunctionHandle.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/AddFileEntry.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/CdfFileEntry.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeTransactionLogEntry.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogUtil.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeChangeDataFeedCompatibility.java
Adds table_changes function to delta lake. 
It allows reading CDF entries from table for which CDF is enabled. 
This PR requires https://github.com/trinodb/trino/pull/15575 to be merged first.
Commits 5th and 6th adds some additional things to TableFunction implementation that I found necessary while working on table_changes function.
```markdown
* Add table_changes function. ({issue}`issuenumber`)
```
> Implement table changes function for delta lake

- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
> Update Oracle date type mapping test cases

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogSynchronizerManager.java
> Remove usages of Path from Delta Lake

- plugin/trino-accumulo/pom.xml
- plugin/trino-bigquery/pom.xml
- plugin/trino-delta-lake/pom.xml
- plugin/trino-exchange-filesystem/pom.xml
- plugin/trino-hive/pom.xml
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hudi/pom.xml
- plugin/trino-iceberg/pom.xml
- plugin/trino-phoenix5/pom.xml
- pom.xml
- testing/trino-benchto-benchmarks/pom.xml
- testing/trino-faulttolerant-tests/pom.xml
- testing/trino-tests/pom.xml
> Various code and POM cleanups

- plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Check table existence in Cassandra query table function tests
Fixes #17523
> Check table existence in Cassandra query table function tests

- client/trino-jdbc/pom.xml
- core/trino-server-rpm/pom.xml
- pom.xml
> Update maven failsafe plugin to 3.1.0

- lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HadoopPaths.java
- lib/trino-hdfs/src/test/java/io/trino/hdfs/s3/TestS3HadoopPaths.java
> Fix handling of non-normalized paths for S3

- core/trino-main/src/test/java/io/trino/operator/scalar/timestamptz/TestCurrentTimestamp.java
Test for https://github.com/trinodb/trino/pull/17455
> Add rounding test for current_timestamp

- core/trino-main/src/main/java/io/trino/operator/output/SkewedPartitionRebalancer.java
> Change rebalancing log to debug

- docs/src/main/sphinx/language/sql-support.rst
- docs/src/main/sphinx/sql.rst
- docs/src/main/sphinx/sql/deallocate-prepare.rst
- docs/src/main/sphinx/sql/execute-immediate.rst
- docs/src/main/sphinx/sql/execute.rst
- docs/src/main/sphinx/sql/prepare.rst
Docs for #17341. Simple example, also added links in the "see also" sections among prepare, execute, and deallocate prepare.
> Add docs for EXECUTE IMMEDIATE

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFlushMetadataCacheProcedure.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeLegacyCreateTableWithExistingLocation.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePartitioning.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreAccessOperations.java
Rename catalog name in Delta Lake query runner
> Rename catalog name in Delta Lake query runner

- pom.xml
```markdown
* Removes the 5MB limit for string columns in JSON serialization
```
> Update airlift to 231

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
> Fix DeltaLake write operation when location is with trailing slash

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
> Use `Location` method for doing path concatenation

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeInsertTableHandle.java
Add DeltaLakeInsertTableHandle.toString() which is printed out in query plans.
```markdown
```
> Add DeltaLakeInsertTableHandle.toString()

- lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedConnectorAccessControlTest.java
- lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedSystemAccessControlTest.java
Extracted this from https://github.com/trinodb/trino/pull/16691
> File based access control tests cleanup

- core/trino-main/src/main/java/io/trino/execution/resourcegroups/IndexedPriorityQueue.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
- core/trino-main/src/test/java/io/trino/execution/resourcegroups/TestUpdateablePriorityQueue.java
> Simplify priority handling in EventDrivenFaultTolerantQueryScheduler 

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeActiveFilesCache.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeChangeDataFeedCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeRedirect.java
Retry dropping Delta tables in product test to avoid flaky tests. 
https://github.com/trinodb/trino/actions/runs/5011014700/jobs/8981743554?pr=17236
> Retry dropping Delta tables in product test

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java
Follows https://github.com/trinodb/trino/pull/17393#discussion_r1197761786 
> Add parquet writer session property validations

- docs/src/main/sphinx/admin/properties-logging.rst
see commit messages
doc build verified locally
Fixes #17588
> Update log properties documentation

- lib/trino-hdfs/src/main/java/io/trino/hdfs/TrinoFileSystemCache.java
> Make GC prevention logic in TrinoFileSystemCache more obvious

- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSourceProvider.java
Moved creation of ParquetReaderOptions to the caller to ensure that the same options are used consistently
> Refactor HudiPageSourceProvider#createPageSource

- docs/src/main/sphinx/connector/bigquery.rst
- docs/src/main/sphinx/connector/hive-s3.rst
Docs for https://github.com/trinodb/trino/pull/17067
Docs for https://github.com/trinodb/trino/pull/17067
> BigQuery proxy docs

- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
This helps with BigQuery for example since number of metadata operations per second is limited.
Other tests also benefit with being slightly faster.
> Refactor BaseConnectorTest#testComment* to reduce queries

- pom.xml
Fixes:
- https://github.com/antlr/antlr4/issues/4226 (unicode, comp:performance)
> Upgrade antlr version to 4.13.0

- core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalAverageAggregation.java
- core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalSumAggregation.java
- core/trino-main/src/test/java/io/trino/operator/aggregation/TestDecimalSumAggregation.java
This way addWithOverflow won't be called
even though state.getLong() == 0 (row count == 0)
> Update row counter at end of combine

- core/trino-main/src/test/java/io/trino/operator/aggregation/BenchmarkDecimalAggregation.java
Makes the benchmark more stable by using the same random seed 
Also includes some nulls in the input
> Avoid ThreadLocalRandom in BenchmarkDecimalAggregation

- lib/trino-parquet/src/main/java/io/trino/parquet/ParquetCompressionUtils.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/PageReader.java
Minor improvement for snappy decompression in parquet
These changes are based on existing code from ORC reader
> Minor improvement for snappy decompression in parquet

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergAvroPageSource.java
Remove obsolete comment and code from `IcebergAvroPageSource`
> Remove obsolete comment and code from `IcebergAvroPageSource`

- plugin/trino-hudi/pom.xml
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/table/HudiTableFileSystemView.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/timeline/TimelineLayout.java
> Remove unnecessary dependency in Hudi connector

- .github/workflows/ci.yml
> Fix CI job for trino-filesystem-s3

- pom.xml
> Update AWS SDK v2 to 2.20.78

- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
> Fix flaky testCommentColumn in BigQuery

- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
No need to drop schema in docker setup.
> Create `test` schema only if not exists in TestMongoConnectorTest

- core/trino-spi/src/main/java/io/trino/spi/function/table/Descriptor.java
- core/trino-spi/src/main/java/io/trino/spi/function/table/DescriptorArgument.java
- core/trino-spi/src/main/java/io/trino/spi/function/table/TableFunctionAnalysis.java
> Import checkArgument statically

- .github/workflows/ok-to-test.yml
This fixes broken workflow file introduced in
c5534814867da43f10c22367afde4c1fc79cacb7
I didn't notice the double `if` in the original PR 😞
> Fix invalid workflow file for ok-to-test

- docs/src/main/sphinx/connector/bigquery.rst
Document bigquery.rpc-proxy.enabled
This was missed in e2e3d761b5dcfdd30f456f876b71cd7005b5b91b
> Document bigquery.rpc-proxy.enabled

- plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
> Implement tail char test for Phoenix

- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIceberg.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergJdbcCatalog.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergRest.java
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/spark/log4j2.properties
Reduce Spark log in Iceberg product tests
Relates to #16813
> Reduce Spark log in Iceberg product tests

- core/trino-main/src/main/java/io/trino/sql/planner/SplitSourceFactory.java
Make `visitScanAndFilter` function without side effects and rename it to more telling `createSplitSource`
```markdown
```
> Extract pure createSplitSource and drop visitScanAndFilter

- .github/workflows/ci.yml
- client/trino-jdbc/pom.xml
- service/trino-verifier/pom.xml
Previously without verify goal, the test was failing but build success was reported.
Fix after #17770 was merged
```markdown
```
> Relocate javax classes in trino-jdbc

- plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
> Fix filterDataMappingSmokeTestData in ClickHouse

- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java
It should return null. Previously it threw when invoking `Location.of("")`.
Fixes behavioral regression introduced in https://github.com/trinodb/trino/pull/17392
> Fix HudiMetadata.getTableMetadata for views

- docs/src/main/sphinx/admin/fault-tolerant-execution.rst
> Fix typo in config 'exchange.source-concurrent-readers' doc

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
Follow up of https://github.com/trinodb/trino/pull/17710#discussion_r1231865458
> Modify projection pushdown config description

- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
This is same as in `testProjectionPushdown`.
> Skip detailed project pushdown tests with CTAS not supported

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiErrorCode.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/table/HudiTableMetaClient.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/ResourceHudiTablesInitializer.java
Extracted from https://github.com/trinodb/trino/pull/17955
> Minor Hudi code cleanup

- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/DatabaseMetaDataRemoteIdentifierSupplier.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/DefaultIdentifierMapping.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/IdentifierMappingModule.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/RemoteIdentifierSupplier.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcClient.java
- plugin/trino-druid/pom.xml
- plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
- plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClientModule.java
- plugin/trino-druid/src/test/java/io/trino/plugin/druid/BaseDruidConnectorTest.java
- plugin/trino-druid/src/test/java/io/trino/plugin/druid/DruidCreateAndInsertDataSetup.java
- plugin/trino-druid/src/test/java/io/trino/plugin/druid/DruidQueryRunner.java
- plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestDruidCaseInsensitiveMapping.java
- plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestDruidConnectorTest.java
- plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestDruidLatestConnectorTest.java
- plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestDruidTypeMapping.java
- plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestingDruidServer.java
- plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteClient.java
- plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbClient.java
- plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlClient.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleClient.java
- plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlClient.java
- plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerClient.java
This is reviving the PR https://github.com/trinodb/trino/pull/7197 for fixing #6850 . I have addressed the comments from the original PR (see fixup commit)
Fixes #6850 
```markdown
* Support tables with non-lowercase names in Druid . ({issue}`7197`)
```
> Support tables with non-lowercase names in Druid

- .github/actions/update-check/action.yml
> Fix syntax error in update checks action

- pom.xml
> Update to Hadoop 3.3.5

- pom.xml
Your daily dose of dependency upgrades has arrived!
> Update AWS SDK v1 to 1.12.493

- plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/KafkaQueryRunner.java
- plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/KafkaQueryRunnerBuilder.java
> Allow setting catalog in Kafka query runner

- .mvn/wrapper/maven-wrapper.properties
https://maven.apache.org/docs/3.9.3/release-notes.html
> Update maven to 3.9.3

- plugin/trino-mongodb/pom.xml
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ObjectIdType.java
Remove unused code from MongoDB ObjectIdType
> Remove unused code from MongoDB ObjectIdType

- pom.xml
> Enable Error Prone check: GetClassOnEnum

- testing/trino-tests/src/test/java/io/trino/tests/TestAggregations.java
Split a test into two, in order to distinguish between testing with a filter and without.
> Split a test into two

- pom.xml
> Enable Error Prone check: UnnecessaryLambda

- pom.xml
There are no functional changes.
No release notes needed.
> Update JDBI to 3.39.1

- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSource.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/TypeUtils.java
Minor refactoring in MongoDB connector
> Minor refactoring in MongoDB connector

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
Support OPTIMIZE procedure in Delta Lake column mapping table
```markdown
* Add support for `OPTIMIZE` procedure for column mapping tables. ({issue}`17527`)
```
> Support OPTIMIZE procedure in Delta Lake column mapping table

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesFunctionProcessor.java
Minor code clean up and refactoring.
> Code clean up in Delta Lake table_change function

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceProvider.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/AvroHivePageSourceFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/line/LinePageSourceFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/rcfile/RcFilePageSourceFactory.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/AbstractFileFormat.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPageSourceFactory.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestOnlyNulls.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestTimestampMicros.java
> Remove Configuration argument from HivePageSourceFactory

- core/trino-main/src/test/java/io/trino/operator/scalar/TestJsonExtract.java
> Add smoke test to verify Jackson read constraints

- docs/src/main/sphinx/connector/hive.rst
Provide documentation and examples for the metadata tables exposed by the Hive connector.
```markdown
```
> Extend documentation for Hive metadata tables

- core/trino-main/src/test/java/io/trino/util/TestDateTimeUtils.java
- core/trino-server-main/pom.xml
- core/trino-server-main/src/test/java/io/trino/server/TestDummy.java
- lib/trino-array/pom.xml
- lib/trino-array/src/test/java/io/trino/array/TestBlockBigArray.java
- lib/trino-array/src/test/java/io/trino/array/TestBooleanBigArray.java
- lib/trino-array/src/test/java/io/trino/array/TestByteBigArray.java
- lib/trino-array/src/test/java/io/trino/array/TestDoubleBigArray.java
- lib/trino-array/src/test/java/io/trino/array/TestIntBigArray.java
- lib/trino-array/src/test/java/io/trino/array/TestLongBigArray.java
- lib/trino-array/src/test/java/io/trino/array/TestObjectBigArray.java
- lib/trino-array/src/test/java/io/trino/array/TestShortBigArray.java
- lib/trino-array/src/test/java/io/trino/array/TestSliceBigArray.java
- plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestExtractSpatialInnerJoin.java
- plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestExtractSpatialLeftJoin.java
- plugin/trino-teradata-functions/src/test/java/io/trino/plugin/teradata/functions/dateformat/TestDateFormatParser.java
- plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/TestThriftConnectorConfig.java
- plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/TestThriftIndexPageSource.java
- plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/TestThriftPlugin.java
- plugin/trino-tpcds/pom.xml
- plugin/trino-tpcds/src/test/java/io/trino/plugin/tpcds/TestTpcdsConfig.java
- plugin/trino-tpcds/src/test/java/io/trino/plugin/tpcds/TestTpcdsMetadata.java
- plugin/trino-tpcds/src/test/java/io/trino/plugin/tpcds/TestTpcdsMetadataStatistics.java
- plugin/trino-tpch/pom.xml
- plugin/trino-tpch/src/test/java/io/trino/plugin/tpch/TestTpchMetadata.java
> Migrate some tests to JUnit

- core/trino-main/src/test/java/io/trino/operator/project/TestPageProcessor.java
> Migrate TestPageProcessor to JUnit

- core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
> Migrate analyzer tests to JUnit

- core/trino-main/src/test/java/io/trino/TestHiddenColumns.java
- core/trino-main/src/test/java/io/trino/dispatcher/TestDecoratingListeningExecutorService.java
- core/trino-main/src/test/java/io/trino/exchange/TestExchangeSourceOutputSelector.java
- core/trino-main/src/test/java/io/trino/execution/TestDeallocateTask.java
- core/trino-main/src/test/java/io/trino/execution/TestQueryStats.java
- core/trino-main/src/test/java/io/trino/execution/TestSetTimeZoneTask.java
- core/trino-main/src/test/java/io/trino/execution/resourcegroups/TestResourceGroups.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/TestArbitraryDistributionSplitAssigner.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/policy/TestPhasedExecutionSchedule.java
- core/trino-main/src/test/java/io/trino/operator/TestHttpPageBufferClient.java
- core/trino-main/src/test/java/io/trino/operator/join/TestNestedLoopBuildOperator.java
- core/trino-main/src/test/java/io/trino/operator/output/TestSkewedPartitionRebalancer.java
- core/trino-main/src/test/java/io/trino/server/TestDynamicFilterService.java
- core/trino-main/src/test/java/io/trino/server/protocol/TestQueryResultRows.java
- core/trino-main/src/test/java/io/trino/sql/analyzer/TestScope.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestSchedulingOrderVisitor.java
- core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestCardinalityExtractorPlanVisitor.java
- core/trino-main/src/test/java/io/trino/sql/planner/planprinter/TestJsonRepresentation.java
- core/trino-main/src/test/java/io/trino/sql/planner/rowpattern/TestRowPatternSerialization.java
- core/trino-main/src/test/java/io/trino/sql/planner/sanity/TestVerifyOnlyOneOutputNode.java
> Migrate tests to JUnit

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java
> Avoid extreme undersizing of row groups in iceberg tests

- core/trino-main/src/test/java/io/trino/type/AbstractTestType.java
- core/trino-main/src/test/java/io/trino/type/TestBooleanType.java
- core/trino-main/src/test/java/io/trino/type/TestCastDependencies.java
- core/trino-main/src/test/java/io/trino/type/TestCharType.java
- core/trino-main/src/test/java/io/trino/type/TestColorType.java
- core/trino-main/src/test/java/io/trino/type/TestDoubleType.java
- core/trino-main/src/test/java/io/trino/type/TestFunctionType.java
- core/trino-main/src/test/java/io/trino/type/TestIpAddressType.java
- core/trino-main/src/test/java/io/trino/type/TestJsonPath2016TypeSerialization.java
- core/trino-main/src/test/java/io/trino/type/TestLongTimestampType.java
- core/trino-main/src/test/java/io/trino/type/TestRealType.java
- core/trino-main/src/test/java/io/trino/type/TestRowParametricType.java
- core/trino-main/src/test/java/io/trino/type/TestSingleAccessMethodCompiler.java
- core/trino-main/src/test/java/io/trino/type/TestTypeCoercion.java
- core/trino-main/src/test/java/io/trino/type/TestTypeRegistry.java
- core/trino-main/src/test/java/io/trino/type/TestUuidType.java
- core/trino-main/src/test/java/io/trino/type/setdigest/TestSetDigest.java
- testing/trino-testing-services/src/main/java/io/trino/testng/services/ReportBadTestAnnotations.java
> Migrate type tests to JUnit

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/RetryDriver.java
> Remove unused onRetry method from RetryDriver

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/acid/AcidOperation.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
> Simplify code in AcidOperation

- docs/src/main/sphinx/release/release-416.md
Extra release note for #16802 to go along with the docs in #17609
> Add missing write partitioning release note

- docs/src/main/sphinx/connector/iceberg.rst
> Update default file format in Iceberg docs

- lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java
- lib/trino-filesystem-s3/pom.xml
- lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemMinIo.java
- lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java
- lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsFileSystemFactory.java
MinIO is important deployment context, so let's test S3 filesystem with MinIO as well.
> Test Trino S3 filesystem with MinIO

- core/trino-main/src/main/java/io/trino/execution/querystats/PlanOptimizersStatsCollector.java
Fixes https://github.com/trinodb/trino/issues/18284
```markdown
* TBD
```
> Fix race condition in getTopRuleStats

- docs/src/main/sphinx/release/release-422.md
Updates to 422 release notes due to a few blockers.
* #18233 ✅ rn ✅ docs
* #18207 ✅ rn ✅ docs
* #17945 ✅ rn ✅ docs
* #18148 ✅ rn ✅ docs
* #17863 ✅ rn ✅ docs
* #18184 ✅ rn ✅ docs
* #18258 ✅ rn ✅ docs
* #18260 ✅ rn ✅ docs
* #18250 ✅ rn ✅ docs
* #18211 ✅ rn ✅ docs
* #18249 ✅ rn ✅ docs
> Update Trino 422 release notes

- core/trino-main/src/main/java/io/trino/execution/StateMachine.java
-- Mark the appropriate option with an (x). Propose a release note if you can. -->
> Catch exceptions for initial call to state change listener

- lib/trino-hive-formats/pom.xml
Updated version comments out a diagnostics line in the code with e.printStackTrace which resulted in flood of logs being generated during TestJsonReader execution
```markdown
```
> Update openx serde used for testing.

- plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPageSourceProvider.java
- plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPagesStore.java
- plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryPagesStore.java
Minor code cleanup
```markdown
```
> Reuse Page#getColumns in MemoryPagesStore

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksDelete.java
> Fix broken `testDeletionVectors` in Delta Lake

- core/trino-main/src/test/java/io/trino/sql/query/TestCheckConstraint.java
> Add test for UPDATE with multiple columns check constraint

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
> Remove unused code

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksInsertCompatibility.java
> Test NULL handling compatibility for partition values

- core/trino-main/src/main/java/io/trino/execution/scheduler/policy/PhasedExecutionSchedule.java
There is just one output stage, therefore
PhasedExecutionSchedule can be simplified.
> Simplify PhasedExecutionSchedule

- pom.xml
> Update Airlift to 235

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesFunction.java
Remove unused line of code
```markdown
```
> Remove unused line from TableChangesFunction

- plugin/trino-exchange-filesystem/pom.xml
- pom.xml
> Update Azure SDK to 1.2.14

- pom.xml
> Update airlift/discovery-server to 1.36

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesSplitSource.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestCdfWithNumberOfSplitsGreaterThanMaxBatchSizeInSplitSource.java
Fixes: https://github.com/trinodb/trino/issues/17182
() Release notes are required, please propose a release note for me.
```markdown
```
> Respect maxSize in TableChangesSplitSource.getNextBatch

- core/trino-spi/src/main/java/io/trino/spi/function/AggregationFunction.java
- core/trino-spi/src/main/java/io/trino/spi/function/InputFunction.java
- core/trino-spi/src/main/java/io/trino/spi/function/OutputFunction.java
- core/trino-spi/src/main/java/io/trino/spi/function/RemoveInputFunction.java
- core/trino-spi/src/main/java/io/trino/spi/function/ScalarFunction.java
- core/trino-spi/src/main/java/io/trino/spi/function/ScalarOperator.java
> Mark SPI function annotations with Error Prone keep

- .github/pull_request_template.md
> Change wording to clear any misunderstanding

- pom.xml
> Update error-prone to 2.21.1

- pom.xml
> Update oauth2-oidc-sdk to 10.13

- core/trino-main/src/main/java/io/trino/annotation/UsedByGeneratedCode.java
- core/trino-main/src/main/java/io/trino/operator/scalar/FormatFunction.java
> Format function cleanup

- docs/src/main/sphinx/connector/iceberg.rst
Fix Iceberg docs after https://github.com/trinodb/trino/pull/18170
```markdown
```
> Fix default file format in Iceberg doc

- pom.xml
> Update JDBI to 3.40.0

- docs/src/main/sphinx/sql/drop-schema.md
Add an example for using the RESTRICT keyword.
```markdown
```
> Add example for RESTRICT keyword

- .mvn/wrapper/maven-wrapper.properties
> Update maven to 3.9.4

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/IcebergGlueCatalogModule.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestingIcebergGlueCatalogModule.java
> Rename variable in Glue catalog modules

- docs/src/main/sphinx/connector/kafka.md
- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentSchemaRegistryConfig.java
Fix minor errors to reflect the new EmptyFieldStrategy enum values.
```markdown
```
> Update kafka connector documentation

- docs/src/main/sphinx/release.md
- docs/src/main/sphinx/release/release-423.md
Assemble the release notes for the upcoming Trino 423 release. Fixes #18288 
* #18157 ✅ rn ✅ docs
* #18276 ✅ rn ✅ docs
* #18261 ✅ rn ✅ docs
* #18003 ✅ rn ✅ docs
* #18263 ✅ rn ✅ docs
* #18212 ✅ rn ✅ docs
* #18278 ✅ rn ✅ docs
* #18257 ✅ rn ✅ docs
* #18246 ✅ rn ✅ docs
* #18165 ✅ rn ✅ docs
* #18252 ✅ rn ✅ docs
* #18253 ✅ rn ✅ docs
* #18251 ✅ rn ✅ docs
* #18206 ✅ rn ✅ docs
* #18205 ✅ rn ✅ docs
* #18195 ✅ rn ✅ docs
* #18292 ✅ rn ✅ docs
* #18179 ✅ rn ✅ …
> Add Trino 423 release notes

- core/trino-grammar/pom.xml
> Update parent version in trino-grammar pom

- pom.xml
> Update dropwizard metrics to 4.2.19

- plugin/trino-exchange-filesystem/pom.xml
- pom.xml
> Update Azure SDK to 1.2.15

- pom.xml
> Update snakeyaml to 2.1

- plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/s3select/S3SelectTestHelper.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
> Use Hive native writers for creating empty bucket files

- docs/src/main/sphinx/connector/delta-lake.rst
- docs/src/main/sphinx/connector/hive.rst
- docs/src/main/sphinx/connector/hudi.rst
- docs/src/main/sphinx/connector/iceberg.rst
- docs/src/main/sphinx/connector/object-storage-file-formats.rst
This PR pulls information from connector pages and centralizes it.
```markdown
```
> Create object storage file formats page

- docs/src/main/sphinx/admin.md
> Remove Event listeners from main docs navigation

- plugin/trino-exchange-hdfs/pom.xml
- plugin/trino-exchange-hdfs/src/test/java/io/trino/plugin/exchange/hdfs/TestExchangeHdfsConfig.java
> Migrate exchange-hdfs to JUnit

- plugin/trino-accumulo-iterators/pom.xml
- plugin/trino-accumulo-iterators/src/test/java/io/trino/server/TestDummy.java
> Migrate accumulo-iterators to JUnit

- core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java
- plugin/trino-jmx/pom.xml
- plugin/trino-jmx/src/test/java/io/trino/plugin/jmx/TestJmxColumnHandle.java
- plugin/trino-jmx/src/test/java/io/trino/plugin/jmx/TestJmxConnectorConfig.java
- plugin/trino-jmx/src/test/java/io/trino/plugin/jmx/TestJmxHistoricalData.java
- plugin/trino-jmx/src/test/java/io/trino/plugin/jmx/TestJmxMetadata.java
- plugin/trino-jmx/src/test/java/io/trino/plugin/jmx/TestJmxQueries.java
- plugin/trino-jmx/src/test/java/io/trino/plugin/jmx/TestJmxSplit.java
- plugin/trino-jmx/src/test/java/io/trino/plugin/jmx/TestJmxSplitManager.java
- plugin/trino-jmx/src/test/java/io/trino/plugin/jmx/TestJmxTableHandle.java
> Migrate jmx connector tests to JUnit

- docs/src/main/sphinx/admin.md
- docs/src/main/sphinx/admin/event-listeners-mysql.md
> Add documentation for MySQL event listener

- core/trino-main/src/main/java/io/trino/operator/TaskContext.java
```markdown
* Fix reporting of cumulative memory. ({issue}`issuenumber`)
```
> Initialize lastTaskStatCallNanos correctly

- core/trino-main/src/main/java/io/trino/execution/buffer/PageSerializer.java
- core/trino-main/src/main/java/io/trino/operator/DeduplicatingDirectExchangeBuffer.java
- core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
- core/trino-main/src/test/java/io/trino/block/BlockAssertions.java
- core/trino-main/src/test/java/io/trino/block/TestVariableWidthBlock.java
- core/trino-main/src/test/java/io/trino/operator/BenchmarkGroupByHashOnSimulatedData.java
- core/trino-main/src/test/java/io/trino/operator/TestOperationTimer.java
- core/trino-main/src/test/java/io/trino/operator/aggregation/TestApproximateCountDistinctIpAddress.java
- core/trino-main/src/test/java/io/trino/operator/aggregation/TestApproximateCountDistinctVarchar.java
- core/trino-main/src/test/java/io/trino/operator/aggregation/TestApproximateSetGenericIpAddress.java
- core/trino-main/src/test/java/io/trino/operator/output/TestPositionsAppender.java
- core/trino-main/src/test/java/io/trino/operator/scalar/BenchmarkStringFunctions.java
- core/trino-spi/pom.xml
- core/trino-spi/src/main/java/io/trino/spi/block/AbstractVariableWidthBlock.java
- core/trino-spi/src/main/java/io/trino/spi/block/BlockUtil.java
- core/trino-spi/src/test/java/io/trino/spi/block/BenchmarkCopyPositions.java
- lib/trino-array/src/main/java/io/trino/array/SliceBigArray.java
- lib/trino-array/src/test/java/io/trino/array/BenchmarkReferenceCountMap.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/TestDataOutputStream.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/TestReadWriteUtils.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/simple/TestSimpleFormat.java
- lib/trino-orc/src/main/java/io/trino/orc/OrcRecordReader.java
- lib/trino-orc/src/main/java/io/trino/orc/metadata/Footer.java
- lib/trino-orc/src/main/java/io/trino/orc/metadata/OrcMetadataReader.java
- lib/trino-orc/src/main/java/io/trino/orc/metadata/statistics/StringStatisticsBuilder.java
- lib/trino-orc/src/test/java/io/trino/orc/stream/BenchmarkLongBitPacker.java
- lib/trino-orc/src/test/java/io/trino/orc/stream/TestLongDecode.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/io/ChunkedSliceOutput.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/GenericHiveRecordCursor.java
- pom.xml
> Update to Slice 2.1

- client/trino-cli/src/main/java/io/trino/cli/CsvPrinter.java
Mark fields of `CsvPrinter.CsvOutputFormat` as `final`
> Mark fields of CsvPrinter.CsvOutputFormat as final

- client/trino-jdbc/pom.xml
- pom.xml
> Update OTEL instrumentation to 1.29.0

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
> Fix testWriterTasksCountLimitUnpartitioned test

- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
> Bind GrpcChannelOptionsConfigurer in BigQuery connector

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
Fix for issue introduced by #18332
```markdown
```
> Check if DELETE pushdown write operation is feasible

- pom.xml
Fixes BigQuery arrow support for JDK 21 which fails with the following exception while using arrow 12.0.1:
```
Caused by: java.lang.UnsupportedOperationException: sun.misc.Unsafe or java.nio.DirectByteBuffer.<init>(long, int) not available
at org.apache.arrow.memory.util.MemoryUtil.directBuffer(MemoryUtil.java:174)
at org.apache.arrow.memory.ArrowBuf.getDirectBuffer(ArrowBuf.java:229)
at org.apache.arrow.memory.ArrowBuf.nioBuffer(ArrowBuf.java:224)
at org.apache.arrow.vector.ipc.ReadChannel.readFully(ReadChannel.java:87)
at org.apache.arrow.vector.ipc.message.MessageSerializer.readMessageBody(MessageSerializer.java:728)
at org.apache.arrow.vector.ipc.message.MessageSerializer.deserializeRecordBatch(MessageSerializer.java:363)
at io.trino.plugin.bigquery.BigQueryStorageArrowPageSource.deser …
```
> Update Arrow to 13.0.0

- docs/src/main/sphinx/release.md
- docs/src/main/sphinx/release/release-425.md
Assemble the release notes for the upcoming Trino 425 release. Fixes #18725
* #18714 ✅ rn ✅ docs
* #18722 ✅ rn ✅ docs
* #18629 ✅ rn ✅ docs
* #18623 ✅ rn ✅ docs
* #18690 ✅ rn ✅ docs
* #18106 ✅ rn ✅ docs
* #18737 ✅ rn ✅ docs
* #18683 ✅ rn ✅ docs
* #18740 ✅ rn ✅ docs
* #18741 ✅ rn ✅ docs
* #18751 ✅ rn ✅ docs
* #18735 ✅ rn ✅ docs
* #18736 ✅ rn ✅ docs
* #18746 ✅ rn ✅ docs
* #18724 ✅ rn ✅ docs
* #16743 ✅ rn ✅ docs
* #18574 ✅ rn ✅ docs
* #18759 ✅ rn ✅ docs …
> Add Trino 425 release notes

- pom.xml
https://github.com/apache/iceberg/releases/tag/apache-iceberg-1.3.1
> Update iceberg to 1.3.1

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Fixes: https://github.com/trinodb/trino/issues/18697
> Increase page delay in runOptimizeDuringWriteOperations

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
For https://github.com/trinodb/trino/issues/16782
> Test unpartitioned Delta table access costs

- docs/src/main/sphinx/connector/metastores.md
> Document batch fetch config property

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestHiveMetastoreMetadataQueriesAccessOperations.java
The result is no longer variable.
> Simplify assertion in testSelectColumnsFilterByTableName

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplit.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveSplit.java
> Do not serialize addresses in HiveSplit when sending to workers

- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestReadUniontype.java
For https://github.com/trinodb/trino/issues/5427
follow-up to https://github.com/trinodb/trino/pull/15879
> Retry Hive/map reduce failures in TestReadUniontype

- docs/src/main/sphinx/connector/delta-lake.md
Document ALTER TABLE RENAME TO limitations.
```markdown
```
> Document ALTER TABLE RENAME TO limitations

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplit.java
Fixup for https://github.com/trinodb/trino/commit/bcbfd39f96b6e9629d49d2b21bce9cbd88f01f34
> Fix compile issue

- lib/trino-array/pom.xml
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreAccessOperations.java
extracted from https://github.com/trinodb/trino/pull/18956
> Test cost of information_schena.columns for Delta 

- core/trino-main/src/main/java/io/trino/metadata/MetadataListing.java
Make it clearer that we either exit or propagate exception when to-be-redirected table redirects incorrectly or does not redirect at all.
extracted from https://github.com/trinodb/trino/pull/18956
> Simplify redirection handling code in column listing

- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/DefaultMongoMetadataFactory.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientModule.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoConnector.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadataFactory.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ptf/Query.java
Introduce MongoMetadataFactory to create MongoMetadata
> Introduce MongoMetadataFactory to create MongoMetadata

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java
> Test file access count on partitioned tables in Iceberg

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/util/DeltaLakeWriteUtils.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/util/TestDeltaLakeWriteUtils.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java
> Extract utility class for creating partition values in Delta Lake

- core/trino-main/src/test/java/io/trino/server/protocol/TestQueryResultRows.java
- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryFailureRecoveryTest.java
- plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
TestNG 7 will try to instatiate it instead of skipping it
```markdown
```
> Test cleanups

- docs/src/main/sphinx/connector/metastores.md
Fix `metastores.md`.
Ref:
https://github.com/trinodb/trino/blob/cabc7c7ae89ac00ba278a0fafb235fac5f59e2ea/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/CatalogType.java#L23
> Fix metastores doc

- docs/src/main/sphinx/connector/delta-lake.md
- Removed duplicate content and rearranged SQL section.
```markdown
```
> Rework SQL support section

- core/trino-main/src/main/java/io/trino/metadata/FunctionResolver.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
Previously IllegalArgumentException was translated to GENERIC_INTERNAL_ERROR.
(s) This is not user-visible or is docs only, and no release notes are required.
> Use MISSING_CATALOG_NAME error code

- core/trino-main/src/test/java/io/trino/type/AbstractTestType.java
- core/trino-main/src/test/java/io/trino/type/TestArrayOfMapOfBigintVarcharType.java
> Test read FLAT to block builder

- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/TestDistributedFaultTolerantEngineOnlyQueries.java
> Harden testMetadataOnlyQueries

- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/TestDistributedFaultTolerantEngineOnlyQueries.java
Migrate test to blackhole connector for better control of used
resources.
> Migrate testMetadataOnlyQueries to blackhole connector

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
> Move special character column mapping mode product tests to integration

- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcFlushMetadataCacheProcedure.java
- pom.xml
> Update various dependencies

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
Following Iceberg's OPTIMIZE's logic for same problem.
> Optimize Delta files with deletions

- plugin/trino-base-jdbc/pom.xml
- plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/BasePostgresFailureRecoveryTest.java
- plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/BaseRedshiftFailureRecoveryTest.java
> Fix incorrect banned imports

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java
> Cosmetic enhancements in DeltaLakeWriter

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java
Move cache invalidation by CREATE TABLE to TestDeltaLakeConnectorTest
Relates to https://github.com/trinodb/trino/pull/19128#issuecomment-1731632429
> Move cache invalidation by CREATE TABLE to TestDeltaLakeConnectorTest

- plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPartitionManager.java
- plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraType.java
- plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTypeManager.java
- plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Minor refactoring in Cassandra connector
> Minor refactoring in Cassandra connector

- core/trino-main/src/main/java/io/trino/operator/FlatHash.java
Fixes #19119
```markdown
* Fix out of memory error in group by hash. ({issue}`19119`)
```
> Fix numeric overflow computing temp rehash size

- .github/bin/s3/delete-s3-bucket.sh
- .github/bin/s3/setup-empty-s3-bucket.sh
- .github/workflows/ci.yml
- lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemAwsS3.java
Create an empty bucket to run the native s3 filesystem cloud tests in
```markdown
```
> Create empty bucket to run s3 filesystem cloud tests

- docs/src/main/sphinx/admin/properties-query-management.md
This PR adds documentation for the config that was introduced.
Updates the internal documentation to provide details on query info URI template configuration.
```markdown
* Closes the ({issue}`8029`)
```
Closes #8029
> Added documentation for a query config

- lib/trino-cache/src/main/java/io/trino/cache/EvictableCacheBuilder.java
Extracted from https://github.com/trinodb/trino/pull/19128
> EvictableCacheBuilder code cleanup

- pom.xml
Pin logback to 1.4.8 as newer version causes product tests to fail
> Update airbase and dependencies

- pom.xml
> Update ASM, zstd

- docs/src/main/sphinx/connector/delta-lake.md
- docs/src/main/sphinx/connector/hive.md
- docs/src/main/sphinx/connector/iceberg.md
- docs/src/main/sphinx/connector/optimize.fragment
* Create fragment for optimize command.
* Arrange hierarchy in Delta Lake ALTER TABLE EXECUTE section to match hierarchy in Hive and Iceberg. 
* Update reference links.
```markdown
```
> Create optimize fragment

- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
There was observed test flakyness due to
double inaccuracy
```markdown
```
> Make testMergeLarge more stable

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDelete.java
Fix deletes which trigger file rewrites in partitions with special characters.
Fixes https://github.com/trinodb/trino/issues/18922
```markdown
* Fix deletes in Delta tables with partitions with special characters. ({issue}`18922`)
```
> Fix deletes which trigger file rewrites in partitions with special characters

- core/trino-main/pom.xml
- plugin/trino-bigquery/pom.xml
- plugin/trino-elasticsearch/pom.xml
- plugin/trino-exchange-filesystem/pom.xml
- plugin/trino-iceberg/pom.xml
- plugin/trino-pinot/pom.xml
- plugin/trino-prometheus/pom.xml
- plugin/trino-redis/pom.xml
- pom.xml
> Major dependencies upgrade

- testing/trino-product-tests/src/main/java/io/trino/tests/product/TestParquet.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/TpcTestUtils.java
Extract `TpcUtils` class in product tests
> Extract TpcUtils class in product tests

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
Extract function Iceberg::getPartitionValues for further reuse.
> Extract function Iceberg::getPartitionValues

- docs/src/main/sphinx/release.md
- docs/src/main/sphinx/release/release-428.md
Assemble the release notes for the upcoming Trino 428 release. Fixes #19171  
* #19159  ✅ rn ✅ docs
* #19128 ✅ rn ✅ docs
* #19174 ✅ rn ✅ docs
* #19135 ✅ rn ✅ docs
* #19181 ✅ rn ✅ docs
* #19166 ✅ rn ✅ docs
* #19170 ✅ rn ✅ docs
* #19183 ✅ rn ✅ docs
* #19185 ✅ rn ✅ docs
* #19182 ✅ rn ✅ docs
* #19127 ✅ rn ✅ docs
* #19165 ✅ rn ✅ docs
* #19184 ✅ rn ✅ docs
* #19176 ✅ rn ✅ docs
* #19187 ✅ rn ✅ docs
* #18185 ✅ rn ✅ docs
* #19060 ✅ rn ✅ docs
* #19192 ✅ rn ✅ …
> Add Trino 428 release notes

- docs/src/main/sphinx/connector/iceberg.md
Removing some old stuff that is from Hive connector, and wrong in Iceberg.
> Update file format docs for Iceberg

- docs/src/main/sphinx/connector/object-storage-file-formats.md
Link to data size and fix grammar issues. Follow up to #19127 
> Improve parquet.small-file-threshold documentation

- core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
> Move logic for handling REFRESH MATERIALIZED VIEW memory allocation

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaFailureRecoveryTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaQueryFailureRecoveryTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaTaskFailureRecoveryTest.java
It was missing explicit tests.
> Add query retry failure recovery tests for Delta Lake

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDatabricksWithGlueMetastoreCleanUp.java
The example failure: https://github.com/trinodb/trino/actions/runs/6399221839/job/17372625111
> Ignore EntityNotFoundException when cleaning Glue in product tests

- plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestDruidTypeMapping.java
This change shortens 20 minutes in Druid CI. 
Fixes #19250
> Improve speed of TestDruidTypeMapping.testTimestamp

- plugin/trino-google-sheets/pom.xml
Addresses https://scout.docker.com/vulnerabilities/id/CVE-2021-22573
> Update google-oauth-client to 1.33.3

- lib/trino-geospatial-toolkit/pom.xml
- lib/trino-geospatial-toolkit/src/main/java/io/trino/geospatial/GeometryUtils.java
- plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestGeoFunctions.java
This was omitted on the https://github.com/trinodb/trino/pull/19293 due to the test being skipped :(
> Fix test cases valid for new JTS

- core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
> Convert to most succinct time unit before printing physical read time

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/TableToPartitionMapping.java
Using Int2IntArrayMap instead of ImmutableMap<Integer, Integer> uses arund 8 times less memory. This is important for tables with lots of partitions and lots of columns.
> Use Int2IntArrayMap in TableToPartitionMapping

- pom.xml
Validated locally against a GCS test bucket
> Switch to Hadoop3 GCS connector

- lib/trino-parquet/src/main/java/io/trino/parquet/ParquetReaderOptions.java
> Remove unused flags from ParquetReaderOptions

- core/trino-main/src/main/java/io/trino/connector/system/TableCommentSystemTable.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataListing.java
Enforce that the mandatory relationFilter is indeed applied.
> Add a safety check for relationFilter application

- pom.xml
> Update jose-jwt to 9.36

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Follow-up for https://github.com/trinodb/trino/pull/13981
> Fix compilation issue

- pom.xml
> Update protobuf to 3.24.4

- pom.xml
> Import and update to grpc bom 1.58.0

- client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverAuth.java
- core/trino-main/src/main/java/io/trino/server/security/jwt/FileSigningKeyResolver.java
- core/trino-main/src/main/java/io/trino/server/security/jwt/JwkSigningKeyResolver.java
- core/trino-main/src/main/java/io/trino/server/security/oauth2/JweTokenSerializer.java
- core/trino-main/src/main/java/io/trino/server/security/oauth2/ZstdCodec.java
- core/trino-main/src/test/java/io/trino/server/security/jwt/TestJwkDecoder.java
- core/trino-main/src/test/java/io/trino/server/security/oauth2/BaseOAuth2WebUiAuthenticationFilterTest.java
- core/trino-main/src/test/java/io/trino/server/security/oauth2/TestJweTokenSerializer.java
- core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithOpaque.java
- core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
- pom.xml
> Update jjwt to 0.12.2

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAbfsConnectorSmokeTest.java
Left-over from the migration to JUnit. 
> Fix TestIcebergAbfsConnectorSmokeTest failure

- pom.xml
> Update airlift to 237

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
> Fix testPartitionFilterRequired for cloud test environment

- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Extracted from https://github.com/trinodb/trino/pull/19392 and approved there
> Replace test annotation for overriden test

- lib/trino-matching/src/main/java/io/trino/matching/Captures.java
> Simplify captures equals method

- pom.xml
Includes fix for stalled streams: https://github.com/square/okhttp/pull/7801
> Update okhttp to 4.12.0 and okio to 3.6.0

- plugin/trino-redshift/pom.xml
> Update redshift jdbc to 2.1.0.20

- plugin/trino-singlestore/pom.xml
> Update singlestore-jdbc-client to 1.2.0

- docs/src/main/sphinx/security/file-system-access-control.md
> Update function security documentation

- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryInstanceCleaner.java
> Add missing JUnit lifecycle annotation

- docs/src/main/sphinx/functions.md
- docs/src/main/sphinx/language.md
- docs/src/main/sphinx/language/comments.md
- docs/src/main/sphinx/sql.md
- docs/src/main/sphinx/sql/comment.md
- docs/src/main/sphinx/sql/select.md
As requested and discussed with @electrum and @martint 
> Improve SQL language landing pages

- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ClassLoaderSafeSchemaRegistryClient.java
- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentModule.java
- pom.xml
- testing/trino-product-tests/src/main/java/io/trino/tests/product/kafka/TestKafkaAvroReadsSmokeTest.java
Extracted from https://github.com/trinodb/trino/pull/18623
> Update confluent to 7.4.1

- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AccessControlRules.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/CatalogProcedureAccessControlRule.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControlModule.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControlRules.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ProcedureAccessControlRule.java
- lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedConnectorAccessControlTest.java
- lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedSystemAccessControlTest.java
- lib/trino-plugin-toolkit/src/test/resources/file-based-system-access-visibility.json
- lib/trino-plugin-toolkit/src/test/resources/visibility-with-json-pointer.json
- lib/trino-plugin-toolkit/src/test/resources/visibility.json
Enables file-based access control for procedures on system and connector level.
fixes https://github.com/trinodb/trino/issues/19416
```markdown
* Support defining rules for procedures in file-based access control. ({issue}`19416`)
```
> Add file-based access control for procedures

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeHistoryTable.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePropertiesTable.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/RegisterTableProcedure.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakeUtils.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/statistics/TestDeltaLakeFileBasedTableStatisticsProvider.java
Move snapshost loading to query level should reduce possibility of race condition
( z) This is not user-visible or is docs only, and no release notes are required.
```markdown
```
> Move Delta snapshot loading to DeltaLakeMetadata

- client/trino-jdbc/src/test/java/io/trino/jdbc/JdbcDriverIT.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestAbstractTrinoResultSet.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcConnection.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcExternalAuthentication.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcStatement.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcVendorCompatibility.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcWarnings.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestProgressMonitor.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriver.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverAuth.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverImpersonateUser.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverUri.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoResultSet.java
> Migrate JDBC driver tests to JUnit

- core/trino-main/src/test/java/io/trino/block/BlockAssertions.java
- lib/trino-hive-formats/pom.xml
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/FormatTestUtils.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/TestDataOutputStream.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/TestHiveFormatUtils.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/TestReadWriteUtils.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/TestTrinoDataInputStream.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroBase.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroPageDataReaderWithAvroNativeTypeManagement.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroPageDataReaderWithoutTypeManager.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroPageDataWriterWithoutTypeManager.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestLongFromBigEndian.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/compression/TestBufferedOutputStreamSliceOutput.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/AbstractTestLineReaderWriter.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/TestFooterAwareLineReader.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/TestLineBuffer.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/csv/TestCsvFormat.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/json/TestJsonFormat.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/openxjson/TestJsonReader.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/openxjson/TestOpenxJsonFormat.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/regex/TestRegexFormat.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/sequence/TestSequenceFileReaderWriter.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/sequence/TestSequenceFileWriterFactory.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/simple/TestSimpleFormat.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/text/TestLineReader.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/text/TestTextLineReaderFactory.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/text/TestTextLineReaderWriter.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/rcfile/AbstractTestRcFileReader.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/rcfile/RcFileTester.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/rcfile/TestRcFileReaderManual.java
> Migrate hive-file-formats to JUnit

- lib/trino-cache/pom.xml
- lib/trino-cache/src/test/java/io/trino/cache/Invalidation.java
- lib/trino-cache/src/test/java/io/trino/cache/TestEmptyCache.java
- lib/trino-cache/src/test/java/io/trino/cache/TestEvictableCache.java
- lib/trino-cache/src/test/java/io/trino/cache/TestEvictableLoadingCache.java
- lib/trino-cache/src/test/java/io/trino/cache/TestSafeCaches.java
> Migrate trino-cache to JUnit

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateTableStatistics.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestReadJsonTransactionLog.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestSplitPruning.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestDeltaLakeSchemaSupport.java
> Migrate some trino-delta tests to JUnit

- core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
Fixes #19561 
```markdown
* Fix usage of inline functions in some queries. ({issue}`19561`)
```
> Fix handling of inline functions in pushdown

- plugin/trino-kafka/pom.xml
- pom.xml
I am not able to compile the trino-kafka module on Mac M2 
Meet the error https://trinodb.slack.com/archives/CP1MUNEUX/p1698747502481569
> Fix kafka protoc compile error

- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Relates to issue https://github.com/trinodb/trino/issues/19561
> Add tests for inline function

- client/trino-cli/pom.xml
Fixes https://github.com/trinodb/trino/issues/19549
> Update JLine to 3.24.1

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointSchemaManager.java
> Static import type constants in CheckpointSchemaManager

- docs/src/main/sphinx/release.md
- docs/src/main/sphinx/release/release-432.md
Assemble the release notes for the upcoming Trino 432 release. Fixes #19552   
* #19543 ✅ rn ✅ docs
* #19535 ✅ rn ✅ docs
* #19038 ✅ rn ✅ docs
* #19550 ✅ rn ✅ docs
* #19479 ✅ rn ✅ docs
* #19556 ✅ rn ✅ docs
* #19558 ✅ rn ✅ docs
* #19559 ✅ rn ✅ docs
* #19563 ✅ rn ✅ docs
* #19545 ✅ rn ✅ docs
* #19565 ✅ rn ✅ docs
* #19573 ✅ rn ✅ docs
* #19575 ✅ rn ✅ docs
* #19591 ✅ rn ✅ docs
* #19594 ✅ rn ✅ docs
* #19585 ✅ rn ✅ docs
* #19553 ✅ rn ✅ docs
* #19601 ✅ rn ✅ …
> Add Trino 432 release notes

- pom.xml
Arrow 14.0.0 is tested against JDK 21
> Update arrow to 14.0.0

- lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java
Add filename to metadata missing exception in parquet
> Add filename to metadata missing exception in parquet

- core/trino-main/src/main/java/io/trino/operator/scalar/CharacterStringCasts.java
> Update usage of deprecated APIs

- .github/workflows/ci.yml
- lib/trino-hdfs/pom.xml
- lib/trino-hdfs/src/test/java/io/trino/hdfs/s3/AbstractTestTrinoS3FileSystem.java
- lib/trino-hdfs/src/test/java/io/trino/hdfs/s3/TestTrinoS3FileSystemAwsS3.java
- lib/trino-hdfs/src/test/java/io/trino/hdfs/s3/TestTrinoS3FileSystemMinio.java
- plugin/trino-hive/pom.xml
> Move Hadoop S3 filesystem tests to HDFS module

- .github/workflows/ci.yml
- lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystem.java
- lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/AbstractTestS3FileSystem.java
- plugin/trino-hive-hadoop2/bin/run_hive_s3_tests.sh
- plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHiveThriftMetastoreWithS3.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHive3OnDataLake.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveQueryFailureRecoveryTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveTaskFailureRecoveryTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/S3HiveQueryRunner.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/query/HudiReadOptimizedDirectoryLister.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java
> Test Hive and Hudi on native S3

- docs/src/main/sphinx/develop/connectors.md
Update the developer guide after last SPI changes.
> Update the developer guide after last SPI changes

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
Left-over from https://github.com/trinodb/trino/pull/18423
```markdown
```
> Remove outdated TODO comment

- plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/BackpressureRestClient.java
- plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/BackpressureRestHighLevelClient.java
> Remove usage of deprecated methods in elasticsearch client

- .github/workflows/ci.yml
> Fix incorrect activation of HDFS file system tests

- core/trino-server/src/main/provisio/trino.xml
> Sort plugins in server provisio configuration

- plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftAutomaticJoinPushdown.java
Adds missing Test annotation for Redshift test
> Add missing Test annotation for Redshift test

- lib/trino-orc/pom.xml
- lib/trino-orc/src/main/java/io/trino/orc/OrcCorruptionException.java
- lib/trino-orc/src/main/java/io/trino/orc/OrcReader.java
- lib/trino-orc/src/main/java/io/trino/orc/OrcRecordReader.java
- lib/trino-orc/src/main/java/io/trino/orc/metadata/ExceptionWrappingMetadataReader.java
- lib/trino-parquet/pom.xml
- lib/trino-parquet/src/main/java/io/trino/parquet/ParquetCompressionUtils.java
- lib/trino-parquet/src/main/java/io/trino/parquet/ParquetCorruptionException.java
- lib/trino-parquet/src/main/java/io/trino/parquet/ParquetValidationUtils.java
- lib/trino-parquet/src/main/java/io/trino/parquet/predicate/PredicateUtils.java
- lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/MetadataReader.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/PageReader.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetColumnChunkIterator.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java
- lib/trino-parquet/src/test/java/io/trino/parquet/TestTupleDomainParquetPredicate.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/AbstractColumnReaderBenchmark.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/AbstractColumnReaderRowRangesTest.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/AbstractColumnReaderTest.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestInt96Timestamp.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestPageReader.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/flat/TestFlatColumnReader.java
- lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java
> Require filename for Parquet corruption exceptions

- .github/workflows/ci.yml
- lib/trino-filesystem-gcs/pom.xml
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/DefaultGcsStorageFactory.java
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileIterator.java
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystem.java
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemFactory.java
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemModule.java
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsInput.java
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsInputFile.java
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsInputStream.java
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsLocation.java
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsOutputFile.java
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsOutputStream.java
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsStorageFactory.java
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsUtils.java
- lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/AbstractTestGcsFileSystem.java
- lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemConfig.java
- lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java
- lib/trino-filesystem-manager/pom.xml
- lib/trino-filesystem-manager/src/main/java/io/trino/filesystem/manager/FileSystemConfig.java
- lib/trino-filesystem-manager/src/main/java/io/trino/filesystem/manager/FileSystemModule.java
- lib/trino-filesystem-manager/src/test/java/io/trino/filesystem/manager/TestFileSystemConfig.java
- pom.xml
> Add GCS filesystem

- lib/trino-filesystem-gcs/pom.xml
> Fix trino-filesystem-gcs tests

- core/trino-main/src/main/java/io/trino/memory/MemoryManagerConfig.java
- core/trino-main/src/test/java/io/trino/memory/TestMemoryManagerConfig.java
Reorder fields and methods so ordering match and related config properties are grouped together.
> Rerder fields and methods in MemoryManagerConfig

- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PropertyDerivations.java
- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/StreamPropertyDerivations.java
Significantly reduces planning times for queries with lots of local exchanges, reported in https://github.com/trinodb/trino/issues/18491 by adding a specific mode of `StreamPropertyDerivations` that avoids calling back into `PropertyDerivations` to populate `StreamingProperties.otherActualProperties` which was causing exponential plan visitor traversal behavior in the presence of certain local exchanges.
Supersedes https://github.com/trinodb/trino/pull/19503
```markdown
* Fix long query planning times for queries with many local exchanges ({issue}`18491`)
```
> Fix long planning times for LocalExchange plans

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
Use dedicated schemas in Delta Lake smoke tests
> Use dedicated schemas in Delta Lake smoke tests

- docs/src/main/sphinx/release.md
- docs/src/main/sphinx/release/release-433.md
Assemble the release notes for the upcoming Trino 433 release. Fixes #19618 
* #19571 ✅ rn ✅ docs
* #19617 ✅ rn ✅ docs
* #19568 ✅ rn ✅ docs
* #19622 ✅ rn ✅ docs
* #19635 ✅ rn ✅ docs
* #19634 ✅ rn ✅ docs
* #19630 ✅ rn ✅ docs
* #19642 ✅ rn ✅ docs
* #19426 ✅ rn ✅ docs
* #19073 ✅ rn ✅ docs
* #19589 ✅ rn ✅ docs
* #19644 ✅ rn ✅ docs
* #19612 ✅ rn ✅ docs
* #19646 ✅ rn ✅ docs
* #19639 ✅ rn ✅ docs
* #19647 ✅ rn ✅ docs
* #19567 ✅ rn ✅ docs
* #19648 ✅ rn ✅ …
> Add Trino 433 release notes

- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-delta-lake-oss/spark-defaults.conf
Hopefully, fixes #19602
- ✅ 5 attempts https://github.com/trinodb/trino/actions/runs/6845200793/job/18610294347?pr=19714
- ✅ 5 attempts https://github.com/trinodb/trino/actions/runs/6845200793/job/18611379376?pr=19714
> Increase Spark memory in Delta product test

- plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
> Remove unnecessary override method in PhoenixMetadata

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMetadata.java
- plugin/trino-hive/pom.xml
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/DecoratedHiveMetastoreModule.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveMetastoreDecorator.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/tracing/MetastoreAttributes.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/tracing/Tracing.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/tracing/TracingHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/tracing/TracingHiveMetastoreDecorator.java
```markdown
* Add tracing to metastore access. ({issue}`19712`)
```
> Add TracingHiveMetastore

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConnector.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java
Add support for table functions in hive connector
```markdown
```
> Add table functions to hive connector

- docs/src/main/sphinx/admin/session-property-managers.md
`writer_min_size` doesn't exist anymore.
https://github.com/trinodb/trino/pull/18005/files#diff-0b009419d5443d34f62f03e2134a26573dac16c7db81c6bfba4b0f3271a54c50L87
```markdown
```
> Remove obsoleted config from doc

- lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java
https://github.com/trinodb/trino/issues/19785
> Disable TestGcsFileSystemGcs temporarily

- plugin/trino-iceberg/pom.xml
- plugin/trino-prometheus/pom.xml
- plugin/trino-raptor-legacy/pom.xml
- plugin/trino-redshift/pom.xml
- pom.xml
> November dependency upgrades

- docs/src/main/sphinx/connector/iceberg.md
Document which kind of operations are supported for changing column types in Iceberg.
https://github.com/trinodb/trino/pull/15651
```markdown
```
> Document schema evolution for Iceberg

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastore.java
- plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHiveFileSystemS3.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveColumnHandle.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/TrinoViewHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/Column.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveLocal.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/TestTransactionScopeCachingDirectoryLister.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestSemiTransactionalHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/file/TestFileHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestGlueInputConverter.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestingMetastoreObjects.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestHiveMetastoreMetadataQueriesAccessOperations.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiPartitionManager.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/ResourceHudiTablesInitializer.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/TpchHudiTablesInitializer.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java
also update some occurrences of "Presto" in tests
> Remove deprecated Hive internal Column constructor

- core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
- core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
- core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
- core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestLimitMaxWriterNodesCount.java
- docs/src/main/sphinx/admin/properties-query-management.md
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionConnectorTest.java
Change property from `max_writer_tasks_count` to `max_writer_task_count` in session properties and docs. 
(* ) Release notes are required. Please propose a release note for me.
> Change property from `max_writer_tasks_count` to `max_writer_task_count`

- pom.xml
> Update testcontainers to 1.19.3

- pom.xml
Supposedly it got misplaced when the properties were sorted.
```markdown
```
> Move a comment to its right place

- docs/src/main/sphinx/connector/jdbc-common-configurations.fragment
see title. 
Addressed feedback and adjusted layout and grammar in table to avoid weird rendering on three columns.
Docs was missed in #19859 and prior PRs for these properties.
> Add docs for JDBC metadata caching props

- plugin/trino-cassandra/pom.xml
- pom.xml
> Fix typo in pom.xml

- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Hopefully, fix timeout https://github.com/trinodb/trino/actions/runs/7014935239/job/19083505662
> Run BigQuery connector test concurrently

- docs/src/main/sphinx/static/trino.css
As discussed with @electrum .. thanks for debugging with me @cindyngo44 
We should also merge the related PR https://github.com/trinodb/release-scripts/pull/9
> Fix vertical alignment for anchor links

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
> Make method private

- .mvn/wrapper/maven-wrapper.properties
> Update Maven to 3.9.6

- core/trino-main/src/main/java/io/trino/server/remotetask/ContinuousTaskStatusFetcher.java
- core/trino-main/src/main/java/io/trino/server/remotetask/DynamicFiltersFetcher.java
> Cleanup JSON response from fetchers

- lib/trino-parquet/src/main/java/io/trino/parquet/ParquetWriteValidation.java
- lib/trino-parquet/src/main/java/io/trino/parquet/predicate/PredicateUtils.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/RowGroupInfo.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
- lib/trino-parquet/src/test/java/io/trino/parquet/ParquetTestUtils.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSourceProvider.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
Extract common logic for filtering row groups in parquet
```markdown
```
> Extract common logic for filtering row groups in parquet

- core/trino-main/src/main/java/io/trino/memory/QueryContext.java
> Do not synch on getting memory pool since it's final

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueToTrinoConverter.java
When using CSV serde, data columns are known to be Hive string, irrespective of what metastore says about that. However, the partitioning columns are whatever type they are declared with.
Fixes regression from https://github.com/trinodb/trino/pull/7059 when reading CSV tables having non-varchar partitioning columns.
> Respect Glue partition column type with CSV

- docs/src/main/sphinx/functions/conditional.md
- docs/src/main/sphinx/functions/list-by-topic.md
- docs/src/main/sphinx/functions/list.md
- docs/src/main/sphinx/routines/case.md
- docs/src/main/sphinx/routines/examples.md
- docs/src/main/sphinx/routines/if.md
Add example SQL routines for truncating strings
> Add example SQL routines for truncating strings

- pom.xml
> Update AWS SDK v1 to 1.12.610

- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/TypeHelper.java
> Minor cleanup in Kudu connector

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
Avoid exceptions like:
```
IllegalArgument addStatsMinMaxColumnFilter must be provided when reading ADD entries from Checkpoint files
```
when doing `VACUUM` or `ADD COLUMN` while `checkpoint_filtering_enabled` session is enabled within the Delta Lake connector.
Bugfix following f6f76462
```markdown
```
> Use default stats column filter for the retrieval of active files in Delta Lake

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Fixes https://github.com/trinodb/trino/issues/20046
```markdown
```
> Disallow changing the location of a table in CREATE OR REPLACE  statement

- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/DockerContainer.java
> Make logPaths and listeners final

- core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
> Log finalQueryInfo when FTE scheduler stalled

- plugin/trino-redshift/pom.xml
- pom.xml
> Upgrade dependencies

- docs/src/main/sphinx/routines/examples.md
Add example SQL routines for charts
> Add example SQL routines for charts

- plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java
> Add comment why disabling pushdown on MariaDB REAL type

- plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
> Randomize identifiers in BaseSqlServerConnectorTest

- core/trino-main/src/test/java/io/trino/execution/scheduler/TestUniformNodeSelector.java
DRY some lines that are identical across all tests.  Makes adding new tests easier.
```markdown
```
> Factor out common code in TestUniformNodeSelector

- core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java
We observed duplicate attempts to drop `spoolingOutputStats` in some logs.  These warnings will help diagnose what's going on.
The code dealing with remote-task updates makes certain assumptions that weren't checked at runtime.  It appears that some of these assumptions are occasionally violated.  This patch adds a few checks to help us catch the violations.
```markdown
```
> Warn about unexpected task updates

- docs/src/main/sphinx/routines/examples.md
Add example SQL routines for formatting topn results
Currently query does not complete when used as catalog routine - filed as #19997 
> Add example SQL routines for formatting topn results

- client/trino-client/src/main/java/io/trino/client/ClientTypeSignature.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/BaseTestJdbcResultSet.java
Fixes https://github.com/trinodb/trino/issues/5317
```markdown
```
> Fix placement of precision parameter of WITH TIME ZONE types

- client/trino-cli/pom.xml
> Update JLine to 3.25.0

- README.md
- docs/src/main/sphinx/installation/deployment.md
Update docs for java requirements to 17.0.5+
- https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java#L97
```markdown
```
> Update docs for java 17.0.5

- pom.xml
This e.g. fixes data loss on retried commit under some circumstances.
```markdown
* Fixes data loss on contended commit to a table under some circumstances.
```
Fixes https://github.com/trinodb/trino/issues/20092
> Update to Iceberg 1.4.3

- plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftTypeMapping.java
> Fix TestRedshiftTypeMapping

- README.md
- core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java
- docs/src/main/sphinx/installation/deployment.md
- pom.xml
Previous versions are affected by https://bugs.openjdk.org/browse/JDK-8294677
> Upgrade required JVM version to 17.0.8

- core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4
Closes https://github.com/trinodb/trino/issues/20271
> Remove redundant ? from SHOW COLUMNS in SqlBase.g4

- core/trino-main/src/main/java/io/trino/sql/DynamicFilters.java
- core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
> Use isDynamicFilterFunction in ConnectorExpressionTranslator

- core/trino-main/src/main/java/io/trino/dispatcher/DispatchExecutor.java
- core/trino-main/src/main/java/io/trino/execution/QueryExecutionMBean.java
- core/trino-main/src/main/java/io/trino/execution/QueryExecutorInternal.java
- core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
- core/trino-main/src/main/java/io/trino/util/DecoratingListeningExecutorService.java
- core/trino-main/src/main/java/io/trino/util/Executors.java
- core/trino-main/src/test/java/io/trino/util/TestDecoratingListeningExecutorService.java
For https://github.com/trinodb/trino/issues/20268
> Embed version in scheduler stacktraces

- docs/src/main/sphinx/admin/properties-query-management.md
While i was searching for some options, i noticed some trivial typos :) 
```markdown
```
> Fix typos in query management doc

- docs/src/main/sphinx/connector/metastores.md
Also improve wording and links for other catalogs.
Update replacement for https://github.com/trinodb/trino/pull/18987
> Add note about Nessie catalogs for views

- core/trino-main/src/main/java/io/trino/metadata/FunctionManager.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- core/trino-main/src/test/java/io/trino/dispatcher/TestLocalDispatchQuery.java
- core/trino-main/src/test/java/io/trino/metadata/TestGlobalFunctionCatalog.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestingPlannerContext.java
- core/trino-spi/src/main/java/io/trino/spi/exchange/ExchangeSourceOutputSelector.java
- core/trino-spi/src/main/java/io/trino/spi/predicate/TupleDomain.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultQueryBuilder.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
- plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteClient.java
- plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
- plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlClient.java
> Revert "Fix auto formatting of throwing blocks"

- docs/src/main/sphinx/routines/introduction.md
This PR fixes a typo in the documentation for SQL routines. 
```markdown
```
> Fix sentence in SQL routines docs

- core/trino-spi/src/main/java/io/trino/spi/type/Int128Math.java
> Use JDK's unsignedMultiplyHigh in Int128Math

- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java
- lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemConfig.java
> Increase retries for trino-filesystem-gcs

- core/trino-main/src/main/java/io/trino/operator/VariableWidthData.java
- core/trino-main/src/main/java/io/trino/operator/aggregation/AbstractMapAggregationState.java
- core/trino-main/src/main/java/io/trino/operator/aggregation/arrayagg/GroupArrayAggregationState.java
- core/trino-main/src/main/java/io/trino/operator/aggregation/histogram/TypedHistogram.java
- core/trino-main/src/main/java/io/trino/operator/aggregation/listagg/GroupListaggAggregationState.java
- core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxn/TypedHeap.java
- core/trino-main/src/main/java/io/trino/operator/aggregation/multimapagg/AbstractMultimapAggregationState.java
- lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureInputStream.java
- lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsInputStream.java
- lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3OutputStream.java
- lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalInputStream.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/LineBuffer.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/split/SizeBasedSplitWeightProvider.java
> Use JDK Math.clamp

- docs/src/main/sphinx/release/release-436.md
> Fix typo in 436 release notes

- core/trino-main/src/main/java/io/trino/likematcher/DenseDfaMatcher.java
- core/trino-main/src/main/java/io/trino/likematcher/FjsMatcher.java
- core/trino-main/src/main/java/io/trino/likematcher/LikeMatcher.java
- core/trino-main/src/main/java/io/trino/likematcher/NfaMatcher.java
- core/trino-main/src/main/java/io/trino/operator/table/json/execution/ExecutionPlanner.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/openxjson/JsonWriter.java
> Use pattern matching for switch for sealed classes

- core/trino-main/src/test/java/io/trino/operator/BenchmarkPagesIndexOrdering.java
> Add sort benchmarks

- core/trino-main/src/main/java/io/trino/metadata/Metadata.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
- core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
- core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java
- core/trino-main/src/main/java/io/trino/sql/planner/plan/TableWriterNode.java
- core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
- core/trino-main/src/main/java/io/trino/tracing/TracingMetadata.java
- core/trino-main/src/test/java/io/trino/connector/MockConnector.java
- core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
- core/trino-spi/pom.xml
- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedView.java
Fixes: https://github.com/trinodb/trino/issues/19904
```markdown
* Fix materialized views based on PTFs being always stale ({issue}`issuenumber`)
```
> Fix materialized views based on PTFs being always stale

- docs/src/main/sphinx/connector/elasticsearch.md
- docs/src/main/sphinx/connector/opensearch.md
- same as OpenSearch recently in https://github.com/trinodb/trino/pull/20332
> Clean up Elasticsearch docs

- docs/src/main/sphinx/connector/elasticsearch.md
- docs/src/main/sphinx/connector/opensearch.md
- Wrong default value
- Wrong indent
- Move default value into column
Follow up to https://github.com/trinodb/trino/pull/20355 since I forgot to push .. sigh
> Correct minor doc issues

- .github/actions/setup/action.yml
- .github/actions/update-check/action.yml
- .github/workflows/annotate.yml
- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/milestone.yml
The new artifacts upload action claims to be almost 100% faster. This should free up the CI queue a bit.
This is another attempt after #20156, where there were 2/2 failures.
> Update GitHub action versions

- docs/src/main/sphinx/connector/metastores.md
Fixes https://github.com/trinodb/trino/issues/17744
> Document warning about JDBC catalog tables in Iceberg

- client/trino-cli/pom.xml
No release notes needed.
Changelog: https://github.com/jline/jline3/releases/tag/jline-parent-3.25.1
> Update JLine to 3.25.1

- docs/src/main/sphinx/installation/deployment.md
Fixes https://github.com/trinodb/trino/issues/20447
```markdown
```
> Add details for tarball install

- core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java
- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryFailureRecoveryTest.java
- plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/BenchmarkSTArea.java
I stumbled upon them by accident.
```markdown
```
> Fix some minor issues with test methods

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMinioAndHmsConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergReadVersionedTableByTemporal.java
> Use native S3 for connector tests

- lib/trino-parquet/pom.xml
> Make Hadoop a test dependency for Parquet

- plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/BenchmarkSTArea.java
> Add test for BenchmarkSTArea

- docs/src/main/sphinx/admin/properties-optimizer.md
- docs/src/main/sphinx/admin/properties-query-management.md
Fix doc
https://github.com/trinodb/trino/blob/8791dced888c74ebfadb03a2fdfd79226aa36f34/core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java#L65
https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
```markdown
```
> Align documentation with implementation

- core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
- core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
- core/trino-main/src/main/java/io/trino/testing/StandaloneQueryRunner.java
- core/trino-main/src/test/java/io/trino/execution/TestCreateCatalogTask.java
- core/trino-main/src/test/java/io/trino/execution/TestDropCatalogTask.java
- core/trino-main/src/test/java/io/trino/execution/TestResetSessionTask.java
- core/trino-main/src/test/java/io/trino/execution/TestSetSessionTask.java
- core/trino-main/src/test/java/io/trino/operator/scalar/AbstractTestRegexpFunctions.java
- core/trino-main/src/test/java/io/trino/sql/query/TestFilterInaccessibleColumns.java
> Convert more tests to StandaloneQueryRunner

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
In Hive connector, if the user config timezone using GMT+/- , there is a error.
Also if we don't config time-zone param, the default value is also risky. 
TimeZone.getDefault().getID() may returns GMT+8.
Please see the code:
io.trino.plugin.hive.HiveConfig.java [](url)
TimeZone.getDefaultRef() --call--> TimeZone.setDefaultZone() --call--> 
--call--> private static native String getSystemTimeZoneID(String javaHome);
if the native function returns null, the timezone is GMT format
(GMT_ID= "GMT";)
After this PR，it supports GMT as below. The trino can startup normally.
cat  etc/catalog/hive1.properties 
> connector.name=hive
> hive.metastore.uri=thrift://kc1:9083
> hive.config.resources=/etc/core-site.xml,/etc/hdfs-site.xml
> hive.orc.time-zone=GMT+8
(X) This is not user-visible or is docs …
> Support orc/parquet/rcfile GMT+/- type timezone in Hive

- docs/src/main/sphinx/routines/examples.md
- Identical to the routine shown in the SQL training
> Add human readable days routine example

- pom.xml
> Update testcontainers to 1.19.4

- docs/src/main/sphinx/security/file-system-access-control.md
> Fix docs in file-based access control

- core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java
- core/trino-main/src/main/java/io/trino/execution/executor/dedicated/ConcurrencyController.java
- core/trino-main/src/main/java/io/trino/execution/executor/dedicated/TaskEntry.java
- core/trino-main/src/main/java/io/trino/execution/executor/dedicated/ThreadPerDriverTaskExecutor.java
- core/trino-main/src/main/java/io/trino/execution/executor/timesharing/SplitConcurrencyController.java
- core/trino-main/src/main/java/io/trino/execution/executor/timesharing/TimeSharingTaskHandle.java
- core/trino-main/src/test/java/io/trino/execution/TestTaskManagerConfig.java
- core/trino-main/src/test/java/io/trino/execution/executor/timesharing/TestSplitConcurrencyController.java
> Implement adaptive concurrency in thread-per-driver scheduler

- .gitignore
- .mvn/maven.config
This PR introduces `.mvn/maven.config`.
Changes:
* remove it from `.gitignore`
* add file with some sensible content
> Introduce .mvn/maven.config

- core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/ArbitraryDistributionSplitAssigner.java
- core/trino-main/src/main/java/io/trino/operator/FilterAndProjectOperator.java
- core/trino-main/src/main/java/io/trino/operator/TableWriterOperator.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/JsonPathAnalyzer.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/WindowFunctionValidator.java
- core/trino-main/src/main/java/io/trino/sql/planner/LiteralInterpreter.java
- core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyTableScanRedirection.java
- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/OptimizeMixedDistinctAggregations.java
- core/trino-main/src/main/java/io/trino/sql/planner/rowpattern/LogicalIndexExtractor.java
- core/trino-main/src/test/java/io/trino/operator/TestAnnotationEngineForAggregates.java
- core/trino-main/src/test/java/io/trino/sql/planner/assertions/PatternRecognitionExpressionRewriter.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/filter/UtcConstraintExtractor.java
- lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedSystemAccessControlTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDynamicFiltering.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestRegexTable.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiConnectorTest.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiCopyOnWriteMinioConnectorSmokeTest.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiMergeOnReadMinioConnectorSmokeTest.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/TpchHudiTablesInitializer.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
- pom.xml
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeGcs.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergJdbcCatalog.java
Enforce ErrorProne UnusedVariable
> Enforce ErrorProne UnusedVariable

- docs/src/main/sphinx/admin/properties-spilling.md
Requested and approved in #20383
> Improve wording for worker only config

- core/trino-main/src/main/java/io/trino/operator/OperatorContext.java
- core/trino-spi/src/main/java/io/trino/spi/Page.java
> Assert that block/page size is non-negative

- core/trino-main/src/test/java/io/trino/execution/executor/scheduler/TestFairScheduler.java
There was a race between context.maybeYield() and scheduler.removeGroup(group) that caused the task to yield before the cancellation occurred.
Fixes https://github.com/trinodb/trino/issues/20510
> Fix race condition in testCancelWhileYielding

- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Example failure https://github.com/trinodb/trino/actions/runs/7717756946/job/21038289251
> Fix broken testNoDataSystemTable in BigQuery

- .github/workflows/ci.yml
> Skip hive tests if module was not impacted

- client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
- client/trino-client/src/test/java/io/trino/client/TestRetry.java
Retry on timeouts when making the initial request to start a query.
A follow-up to #19411.
> Handle timeouts on initial query request

- lib/trino-filesystem-cache-alluxio/pom.xml
Logical merge conflict after release
> Fix Alluxio POM version

- core/trino-main/src/main/java/io/trino/metadata/DisabledSystemSecurityMetadata.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
- core/trino-main/src/main/java/io/trino/metadata/SystemSecurityMetadata.java
- testing/trino-tests/src/test/java/io/trino/security/TestingSystemSecurityMetadata.java
SystemSecurityMetadata interface method to notify about column type change
> Add SystemSecurityMetadata interface method for column type change

- core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOidcDiscovery.java
> Increase test metadata server startup delay

- docs/src/main/sphinx/release/release-438.md
> Add missing 438 release note

- docs/src/main/sphinx/security/built-in-system-access-control.md
Add OPA to built-in system access control doc.
```markdown
```
> Add OPA to built-in system access control doc

- core/trino-main/src/main/java/io/trino/cost/FilterStatsCalculator.java
- core/trino-main/src/main/java/io/trino/cost/ValuesStatsRule.java
- core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
- core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
- core/trino-main/src/main/java/io/trino/sql/planner/IrExpressionInterpreter.java
- core/trino-main/src/main/java/io/trino/sql/planner/IrTypeAnalyzer.java
- core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/SimplifyCountOverConstant.java
- core/trino-main/src/test/java/io/trino/cost/TestValuesNodeStats.java
> Various IrTypeAnalyzer cleanups

- client/trino-jdbc/pom.xml
- core/trino-main/pom.xml
- plugin/trino-elasticsearch/pom.xml
- plugin/trino-google-sheets/pom.xml
- plugin/trino-iceberg/pom.xml
- pom.xml
No release notes needed (or maybe we should start listing these? Opinions are welcome @mosabua @colebow)
> Upgrade minor dependencies

- plugin/trino-bigquery/pom.xml
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorFactory.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ProxyTransportFactory.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/TracingOptionsConfigurer.java
> Add support for OpenTelemetry in BigQuery

- pom.xml
> Update alluxio to 308

- pom.xml
tzdata updated to 2024agtz
No release notes needed
> Update joda-time to 2.12.7

- testing/trino-tests/src/test/java/io/trino/execution/resourcegroups/db/TestQueuesDb.java
Makes failure from https://github.com/trinodb/trino/issues/20551 more visible
> Expose actual failure when not the expected one

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionConnectorTest.java
> Reduce memory consumption of scale writers tests

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestingHiveConnectorFactory.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestingIcebergConnectorFactory.java
To avoid errors in case the wrapped module uses configuration binder.
```markdown
```
> Use configuration aware module as a wrapper for another module

- docs/src/main/sphinx/develop/client-protocol.md
> Fix typo in REST API docs

- client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcConnection.java
- core/trino-main/src/main/java/io/trino/Session.java
- core/trino-main/src/main/java/io/trino/execution/UseTask.java
- core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
- core/trino-main/src/main/java/io/trino/transaction/InMemoryTransactionManager.java
- core/trino-main/src/main/java/io/trino/transaction/TransactionManager.java
- core/trino-spi/src/main/java/io/trino/spi/security/Identity.java
- testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java
- testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
I found a few more stragglers that I had missed previously as a part of #20470
#20470
> Unify remaining catalog not found error messages and types

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
Small follow up to update the vended credential header based on the [Iceberg REST Spec](https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml#L1460C13-L1460C40).
[PR](https://github.com/trinodb/trino/pull/20186) that introduced vended credential support.
```markdown
```
> Update iceberg access delegation header to REST spec

- client/trino-jdbc/pom.xml
- core/trino-main/pom.xml
- core/trino-main/src/main/java/io/trino/operator/scalar/Re2JRegexpFunctions.java
- core/trino-main/src/main/java/io/trino/operator/scalar/Re2JRegexpReplaceLambdaFunction.java
- core/trino-main/src/main/java/io/trino/type/Re2JRegexp.java
- plugin/trino-bigquery/pom.xml
- plugin/trino-exchange-filesystem/pom.xml
- plugin/trino-geospatial/pom.xml
- plugin/trino-hudi/pom.xml
- plugin/trino-session-property-managers/pom.xml
- pom.xml
Requires https://github.com/trinodb/re2j/pull/4
> Switch to io.trino.re2j usage

- plugin/trino-bigquery/pom.xml
- pom.xml
> Update json to 20240205

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConnectorFactory.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeRegisterTableProcedureTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeSharedMetastoreViewsTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakePlugin.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeConcurrentModificationGlueMetastore.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeViewsGlueMetastore.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConnectorFactory.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergRegisterTableProcedure.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestingIcebergConnectorFactory.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestingIcebergPlugin.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueTableOperationsInsertFailure.java
> Cleanup Iceberg and Delta Lake test initialization

- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSink.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSinkProvider.java
Avoid using config objects as member variables and add non null checks. 
```markdown
```
> Minor cleanups in MongoDB connector

- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java
> Use existing createSchemaSql method for creating schema

- .github/actions/compile-commit/action.yml
- .github/actions/process-test-results/action.yml
- .github/actions/setup/action.yml
- .github/workflows/ci.yml
- .github/workflows/cleanup.yml
- .github/workflows/docs.yml
Extract processing test results to an action to reuse it in multiple jobs.
Also update most actions to remove warnings about Node.js version deprecation that show up in the run summary view, obstructing other annotations.
> Reduce duplication in ci workflow file

- docs/src/main/sphinx/admin/resource-groups.md
Indicate that resource group selector rules use Java regex
```markdown
```
> Specify Java regex in selector rules

- docs/src/main/sphinx/connector/iceberg.md
* This PR fixes a small typo in Iceberg's Materialized Views section for creating a materialized view using ORC format. 
```markdown
```
> Fix column name typo in Iceberg MV example

- core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
For robustness in CI 
```markdown
```
> Update for scheduler http client timeouts

- docs/src/main/sphinx/functions/list-by-topic.md
- docs/src/main/sphinx/functions/table.md
> Add table functions to list page

- core/trino-main/src/test/java/io/trino/json/TestJsonPathEvaluator.java
- pom.xml
> Update airbase to 150

- core/trino-main/src/main/java/io/trino/sql/gen/PageFunctionCompiler.java
- core/trino-main/src/main/java/io/trino/testing/assertions/TrinoExceptionAssert.java
- core/trino-main/src/test/java/io/trino/operator/scalar/TestConcatWsFunction.java
- core/trino-main/src/test/java/io/trino/operator/scalar/TestStringFunctions.java
- core/trino-main/src/test/java/io/trino/operator/scalar/TestVarbinaryFunctions.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestLocalExecutionPlanner.java
- core/trino-main/src/test/java/io/trino/sql/query/TestListagg.java
- lib/trino-cache/src/main/java/io/trino/cache/CacheUtils.java
Fixes https://github.com/trinodb/trino/issues/20663
> Fix error message for invalid concat use

- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Fixes https://github.com/trinodb/trino/issues/20627
```markdown
* Fix failure when pushing predicates on BigQuery views. ({issue}`20627`)
```
> Fix failure with predicate pushdown on BigQuery views

- docs/src/main/sphinx/connector/filesystem-cache.md
- docs/src/main/sphinx/connector/hive.md
Docs for incoming code PR from @amoghmargoor and @osscm 
Part of https://github.com/trinodb/trino/issues/20550
> Add docs for fs caching with Hive

- plugin/trino-redshift/pom.xml
- pom.xml
> Dependency updates feb 13 edition

- lib/trino-filesystem-cache-alluxio/pom.xml
- plugin/trino-delta-lake/pom.xml
- pom.xml
> Exclude amqp-client from alluxio-core-common

- plugin/trino-prometheus/pom.xml
- plugin/trino-raptor-legacy/pom.xml
> Remove aspectj from tests

- pom.xml
This version comes with a bunch of improvements around dependencies resolution.
Thanks @cstamas !
> Update provisio to 1.0.21

- plugin/trino-google-sheets/pom.xml
- pom.xml
> Update google auth libraries

- docs/src/main/sphinx/connector/filesystem-cache.md
- docs/src/main/sphinx/connector/iceberg.md
Docs for incoming code PR from @amoghmargoor  #20602
Part of https://github.com/trinodb/trino/issues/20550
> Add docs for fs caching with Iceberg

- lib/trino-filesystem-cache-alluxio/pom.xml
- plugin/trino-delta-lake/pom.xml
As discussed on slack with @electrum and @wendigo 
https://trinodb.slack.com/archives/CP1MUNEUX/p1706892319598769
> Clean up exclusions on alluxio dep

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueColumnStatisticsProvider.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveS3AndGlueMetastoreTest.java
Fixes https://github.com/trinodb/trino/issues/20625
> Fix fetching statistics for table with partition

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
> Fix formatting

- docs/src/main/sphinx/connector.md
- docs/src/main/sphinx/connector/delta-lake.md
- docs/src/main/sphinx/connector/hive.md
- docs/src/main/sphinx/connector/hudi.md
- docs/src/main/sphinx/connector/iceberg.md
- docs/src/main/sphinx/index.md
- docs/src/main/sphinx/object-storage.md
- docs/src/main/sphinx/object-storage/file-system-azure.md
- docs/src/main/sphinx/object-storage/file-system-cache.md
- docs/src/main/sphinx/object-storage/file-system-gcs.md
- docs/src/main/sphinx/object-storage/file-system-s3.md
> Add object storage documentation 

- docs/src/main/sphinx/connector/metastores.md
Update doc for https://github.com/trinodb/trino/pull/19862
> Update doc for metastore

- .github/workflows/ci.yml
Impact analysis works well, and there's no reason not to enable it on all PRs.
> Enable impact analysis for product tests on PRs in this repo

- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
The elapsed time when listing columns became 50% in my manual testing. 
> Improve speed when listing BigQuery columns

- plugin/trino-delta-lake/pom.xml
- pom.xml
- testing/trino-faulttolerant-tests/pom.xml
> Remove Rubix leftovers

- client/trino-cli/pom.xml
- client/trino-cli/src/main/java/io/trino/cli/CsvPrinter.java
- lib/trino-record-decoder/pom.xml
- lib/trino-record-decoder/src/main/java/io/trino/decoder/csv/CsvRowDecoder.java
- plugin/trino-kafka/pom.xml
- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/encoder/csv/CsvRowEncoder.java
- pom.xml
Fixes https://github.com/trinodb/trino/issues/17367
> Update opencsv to 5.9

- lib/trino-filesystem-cache-alluxio/src/test/java/io/trino/filesystem/alluxio/IncompleteStreamMemoryFileSystem.java
- lib/trino-filesystem-cache-alluxio/src/test/java/io/trino/filesystem/alluxio/TestAlluxioCacheFileSystem.java
- lib/trino-filesystem-cache-alluxio/src/test/java/io/trino/filesystem/alluxio/TestFuzzAlluxioCacheFileSystem.java
Adds tests coverage for the bug fixed in b2df2f3f8ef312527ebb1a0b3ce2f09e2aa91ea1
```markdown
```
> Test incomplete stream reads in Alluxio caching

- docs/src/main/sphinx/release.md
- docs/src/main/sphinx/release/release-439.md
Assemble the release notes for the upcoming Trino 439 release.
* #16589 ✅ rn ✅ docs
* #20539 ✅ rn ✅ docs
* #20531 ✅ rn ✅ docs
* #18719  ✅ rn ✅ docs
* #20545 ✅ rn ✅ docs
* #20537 ✅ rn ✅ docs
* #20547 ✅ rn ✅ docs
* #20541 ✅ rn ✅ docs
* #20553 ✅ rn ✅ docs
* #19717 ✅ rn ✅ docs
* #19132 ✅ rn ✅ docs
* #20559 ✅ rn ✅ docs
* #20560 ✅ rn ✅ docs
* #20528 ✅ rn ✅ docs
* #20549 ✅ rn ✅ docs
* #20563 ✅ rn ✅ docs
* #20562 ✅ rn ✅ docs
* #20568 ✅ rn ✅ docs
* #20561 ✅ rn ✅ docs
* …
> Add Trino 439 release notes

- core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestExponentialGrowthPartitionMemoryEstimator.java
DRY some copy-pasted code in TestExponentialGrowthPartitionMemoryEstimator.
```markdown
```
> Factor out TestExponentialGrowthPartitionMemoryEstimator.makeFactory

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/StaticTokenAwareMetastoreClientFactory.java
Remove unused constructor from StaticTokenAwareMetastoreClientFactory
> Remove unused constructor from StaticTokenAwareMetastoreClientFactory

- .github/workflows/ci.yml
- .mvn/extensions.xml
- .mvn/maven.config
This is temporary solution until a better one is found.
Follows https://github.com/trinodb/trino/pull/20504
> Fix builds with maven daemon

- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionConnectorTest.java
> Remove redundant prefix

- plugin/trino-accumulo-iterators/pom.xml
- plugin/trino-accumulo/pom.xml
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloMetadata.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloMetadataFactory.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloMetadataManager.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloModule.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloSplitManager.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloTableManager.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/index/ColumnCardinalityCache.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/index/IndexLookup.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/index/Indexer.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/io/AccumuloPageSink.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/io/AccumuloPageSinkProvider.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/io/AccumuloRecordSet.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/io/AccumuloRecordSetProvider.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/serializers/MapLexicoder.java
- plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/AccumuloQueryRunner.java
- plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
- plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloMetadataManager.java
- plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestingAccumuloServer.java
- plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/index/TestIndexer.java
- pom.xml
Requires https://github.com/trinodb/docker-images/pull/186.
Passes for me reliably locally :tada:
Fixes https://github.com/trinodb/trino/issues/7297
> Update Accumulo to 3.0.0

- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduClientConfig.java
> Kudu code refactoring

- docs/src/main/sphinx/object-storage/file-system-cache.md
> Add documentation for monitoring filesystem caching

- core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4
- core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionInterpreter.java
- core/trino-main/src/main/java/io/trino/sql/planner/DeterminismEvaluator.java
- core/trino-main/src/main/java/io/trino/sql/planner/TranslationMap.java
- core/trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
- core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
- core/trino-parser/src/main/java/io/trino/sql/tree/AstVisitor.java
- core/trino-parser/src/main/java/io/trino/sql/tree/CurrentDate.java
- core/trino-parser/src/main/java/io/trino/sql/tree/CurrentTimestamp.java
- core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionRewriter.java
- core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionTreeRewriter.java
- core/trino-parser/src/main/java/io/trino/sql/tree/LocalTime.java
- core/trino-parser/src/main/java/io/trino/sql/tree/LocalTimestamp.java
- core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
> Improve modeling of special date/time functions

- pom.xml
For maven 4.0.0-alpha-12 compatibility
> Update maven-exec-plugin to 3.2.0

- plugin/trino-pinot/pom.xml
These dependencies are actually needed
> Remove redundant exclusions for pinot

- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DriverConnectionFactory.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectionCreation.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestLazyConnectionFactory.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingDatabase.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcModule.java
- plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClientModule.java
- plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClientModule.java
- plugin/trino-example-jdbc/src/main/java/io/trino/plugin/example/ExampleClientModule.java
- plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClientModule.java
- plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClientModule.java
- plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClientModule.java
- plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClientModule.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java
- plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClientModule.java
- plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlConnectionFactoryModule.java
- plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlJdbcConnectionCreation.java
- plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClientModule.java
- plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftTableStatisticsReader.java
- plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClientModule.java
- plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClientModule.java
Add builder to DriverConnectionFactory for avoiding new constructors anymore.
> Add builder to DriverConnectionFactory

- .github/workflows/labeler.yml
> Update actions/labeler to v5

- docs/src/main/sphinx/connector/metastores.md
Adjust to markdown syntax and fix content. There are a bunch of questions I have to allow me to turn the existing docs into something more useful for readers .. please check @vihangk1 @findinpath and @ebyhr 
Follow up to #20371 
> Improve docs for HTTP client config with Thrift metastore

- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
- core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
- core/trino-main/src/test/java/io/trino/sql/query/TestUnnest.java
```markdown
* Support subqueries inside UNNEST. ({issue}`17953`)
```
> Support subqueries in UNNEST

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcWithBloomFilters.java
Address
https://github.com/trinodb/trino/pull/20433#discussion_r1508515039
https://github.com/trinodb/trino/pull/20433#discussion_r1508515053
> Cleanup tests in Iceberg

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
> Update protocol when adding timestamp column in Delta Lake

- docs/src/main/sphinx/connector/hive-security.md
CredentialCacheLocation can be configured for HDFS and HMS.
This was added in here https://github.com/trinodb/trino/pull/13482
```markdown
```
> Fix docs for hive-security.md

- core/trino-main/src/main/java/io/trino/operator/HttpPageBufferClient.java
Fix assert in HttpPageBufferClient.
In anonymous class, `HttpPageBufferClient.this` should be used instead of `this`.
This error was introduced by: https://github.com/trinodb/trino/commit/61ff7d087b2cd4679df00e6a0fda5856d8d61ab0
Also see: https://github.com/trinodb/trino/commit/b424695316eb1207166fb96c6cd4d5a77dcfdb51
> Fix assert in HttpPageBufferClient

- pom.xml
See title, not sure if this is the correct place .. it could also be .mvn/jvm.config but thats global .. not tests only.
* #20942
* #20891
> Enable dynamic JOL agent load for tests

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMaterializedViewMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/NoneHiveMaterializedViewMetadata.java
Follow up of https://github.com/trinodb/trino/commit/ebc74b79acabcd4547bcd5ea411cab8572e1c5c5
```markdown
```
> Add getter for properties to HiveMaterializedViewMetadata

- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
- core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
- core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesScaledWriters.java
- core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddLocalExchangesForTaskScaleWriters.java
- core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestLimitMaxWriterNodesCount.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSink.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/BaseFaultTolerantExecutionTest.java
- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/delta/TestDeltaFaultTolerantExecutionTest.java
- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/iceberg/TestIcebergFaultTolerantExecutionTest.java
> Scale Writer Fixes

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergRegisterTableProcedure.java
Move of utility method which belongs to IcebergUtil
```markdown
```
> Move getLatestMetadataLocation to IcebergUtil

- .github/workflows/ci.yml
> Enable Azure native file system tests

- core/trino-main/pom.xml
- plugin/trino-bigquery/pom.xml
- pom.xml
> Update AWS SDK v2 to 2.25.2

- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
Specify schema name in testInsertInPresenceOfNotSupportedColumn considering SaaS connectors.
> Specify schema name in testInsertInPresenceOfNotSupportedColumn

- plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/OpenSearchMetadata.java
Same as https://github.com/trinodb/trino/pull/20987
> Suppress index not found when listing OpenSearch columns

- docs/src/main/sphinx/connector/hive.md
- docs/src/main/sphinx/connector/iceberg.md
see title, now all like the Delta Lake one
> Make fs cache sections consistent

- docs/src/main/sphinx/connector/delta-lake.md
- docs/src/main/sphinx/connector/hive.md
- docs/src/main/sphinx/object-storage.md
- docs/src/main/sphinx/object-storage/legacy-azure.md
- docs/src/main/sphinx/object-storage/legacy-cos.md
- docs/src/main/sphinx/object-storage/legacy-gcs.md
- docs/src/main/sphinx/object-storage/legacy-s3.md
- docs/src/main/sphinx/redirects.txt
- docs/src/main/sphinx/release/release-401.md
See commit message. As discussed with @electrum 
> Move Hive file system docs to legacy

- client/trino-jdbc/pom.xml
- core/trino-main/pom.xml
- lib/trino-plugin-toolkit/pom.xml
- plugin/trino-elasticsearch/pom.xml
- plugin/trino-example-http/pom.xml
- plugin/trino-example-jdbc/pom.xml
- plugin/trino-google-sheets/pom.xml
- plugin/trino-hive/pom.xml
- plugin/trino-iceberg/pom.xml
- plugin/trino-opensearch/pom.xml
- plugin/trino-prometheus/pom.xml
- plugin/trino-raptor-legacy/pom.xml
- pom.xml
- service/trino-proxy/pom.xml
Requires https://github.com/airlift/airlift/pull/1089
> Update to airlift 241 and Jetty 12.0.7

- .github/workflows/ci.yml
- core/docker/build.sh
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/jdk/Temurin22EaJdkProvider.java
Adds some basic JDK 22-ea support
> Allow building docker with early access JDKs

- plugin/trino-delta-lake/pom.xml
- plugin/trino-kudu/pom.xml
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/KuduTabletWaitStrategy.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestingKuduServer.java
- pom.xml
- testing/trino-testing-containers/pom.xml
Fixes https://github.com/trinodb/trino/issues/20697
> Wait until tablet server is registered in Kudu

- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/TracingDataSource.java
Use JdbcTelemetry in TracingDataSource because OpenTelemetryDataSource constructor is deprecated.
> Use JdbcTelemetry in TracingDataSource

- core/trino-main/src/main/java/io/trino/sql/analyzer/AggregationAnalyzer.java
- core/trino-main/src/test/java/io/trino/sql/query/TestAggregation.java
> Fix failure with special datetime functions in aggregation queries

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TableSnapshot.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TransactionLogTail.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestTransactionLogTail.java
Remove redundant TransactionLogTail.loadNewTail
> Remove redundant TransactionLogTail.loadNewTail

- plugin/trino-accumulo/pom.xml
- pom.xml
Remove redundant exclusions for jakarta.servlet-api and version overrides
```markdown
```
> Update airbase to 152

- core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
- pom.xml
Each module has tests, so it's redundant.
> Remove failIfNoTests maven property

- .github/workflows/ci.yml
- testing/trino-tests/pom.xml
- testing/trino-tests/src/test/java/io/trino/tests/ci/TestCiWorkflow.java
> Upload test results on Snowflake test failures

- plugin/trino-snowflake/pom.xml
Remove unused dependencies from Snowflake
> Remove unused dependencies from Snowflake

- plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/OpenSearchClient.java
Import OpenSearchErrorCode statically
> Import OpenSearchErrorCode statically

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergCreateTable.java
Fixes https://github.com/trinodb/trino/issues/17884
> Change testCreateExternalTableWithInaccessibleSchemaLocation to integration test

- core/trino-main/src/main/java/io/trino/connector/CoordinatorDynamicCatalogManager.java
- core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
- plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
- testing/trino-testing-services/src/main/java/io/trino/testing/services/junit/LogTestDurationListener.java
- testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
- testing/trino-testing/src/main/java/io/trino/testing/QueryAssertions.java
> Reduce logging in tests

- core/trino-main/src/test/java/io/trino/execution/TestCreateCatalogTask.java
- core/trino-main/src/test/java/io/trino/execution/TestCreateMaterializedViewTask.java
- core/trino-main/src/test/java/io/trino/execution/TestCreateTableTask.java
- core/trino-main/src/test/java/io/trino/execution/TestDropCatalogTask.java
- core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOidcDiscovery.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConnectorFactory.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConnectorFactory.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiConnectorFactory.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConnectorFactory.java
- service/trino-verifier/src/main/java/io/trino/verifier/VerifyCommand.java
> Cleanup usages of Guice Key

- core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java
It now takes ~3s instead of 3 minutes 40 seconds.
> Improve performance of TestDomainTranslator

- docs/release-template.md
- docs/src/main/sphinx/release.md
- docs/src/main/sphinx/release/release-440.md
- docs/src/main/sphinx/release/release-442.md
Assemble the release notes for the upcoming Trino 442 release.
* #21059 ✅ rn ✅ docs
* #21063 ✅ rn ✅ docs
* #21070 ✅ rn ✅ docs
* #21057 ✅ rn ✅ docs
* #21067 ✅ rn ✅ docs
* #21030 ✅ rn ✅ docs
* #21080 ✅ rn ✅ docs
* #21079 ✅ rn ✅ docs
* #21054 ✅ rn ✅ docs
* #21074 ✅ rn ✅ docs
* #21082 ✅ rn ✅ docs
* #21062 ✅ rn ✅ docs
* #21086 
* #21092
> Add Trino 442 release notes

- plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClientModule.java
> Using builder create DriverConnectionFactory in Snowflake

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/FileBasedTableStatisticsProvider.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakeUtils.java
Code cosmetics PR for Delta Lake connector.
> Disambiguate `getActiveFiles()` methods in TransactionLogAccess

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
Access control is consulted after accessing the table. When it tries to load privileges information, it may not find the table, as it could have been just deleted concurrently. This is especially likely to occur during metadata listing operations (e.g. columns listing).
Fixes https://github.com/trinodb/trino/issues/21109
> Fix sql-standard AC failure when table gone

- core/trino-main/src/main/java/io/trino/sql/ir/IrUtils.java
- core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ExtractCommonPredicatesExpressionRewriter.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownNegationsExpressionRewriter.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveDuplicateConditions.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveUnsupportedDynamicFilters.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/SimplifyExpressions.java
Remove unused argument from IrUtils.combinePredicates
> Remove unused argument from IrUtils.combinePredicates

- core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/SimplifyExpressions.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java
- core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushdownFilterIntoRowNumber.java
- core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushdownFilterIntoWindow.java
> Remove expression interpreter from DomainTranslator 

- core/trino-spi/src/main/java/io/trino/spi/predicate/SortedRangeSet.java
- core/trino-spi/src/test/java/io/trino/spi/predicate/TestSortedRangeSet.java
handle better unbounded ranges in sortedRangeSet hash code
(* ) This is not user-visible or is docs only, and no release notes are required.
```markdown
```
> Improve SortedRangeSet hash quality

- core/trino-main/src/main/java/io/trino/sql/ir/ArithmeticBinaryExpression.java
- core/trino-main/src/main/java/io/trino/sql/ir/ArithmeticNegation.java
- core/trino-main/src/main/java/io/trino/sql/ir/BetweenPredicate.java
- core/trino-main/src/main/java/io/trino/sql/ir/BindExpression.java
- core/trino-main/src/main/java/io/trino/sql/ir/Cast.java
- core/trino-main/src/main/java/io/trino/sql/ir/CoalesceExpression.java
- core/trino-main/src/main/java/io/trino/sql/ir/ComparisonExpression.java
- core/trino-main/src/main/java/io/trino/sql/ir/Constant.java
- core/trino-main/src/main/java/io/trino/sql/ir/Expression.java
- core/trino-main/src/main/java/io/trino/sql/ir/FunctionCall.java
- core/trino-main/src/main/java/io/trino/sql/ir/InPredicate.java
- core/trino-main/src/main/java/io/trino/sql/ir/IsNullPredicate.java
- core/trino-main/src/main/java/io/trino/sql/ir/LambdaExpression.java
- core/trino-main/src/main/java/io/trino/sql/ir/LogicalExpression.java
- core/trino-main/src/main/java/io/trino/sql/ir/NotExpression.java
- core/trino-main/src/main/java/io/trino/sql/ir/NullIfExpression.java
- core/trino-main/src/main/java/io/trino/sql/ir/Row.java
- core/trino-main/src/main/java/io/trino/sql/ir/SearchedCaseExpression.java
- core/trino-main/src/main/java/io/trino/sql/ir/SimpleCaseExpression.java
- core/trino-main/src/main/java/io/trino/sql/ir/SubscriptExpression.java
- core/trino-main/src/main/java/io/trino/sql/ir/SymbolReference.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestConnectorExpressionTranslator.java
- core/trino-main/src/test/java/io/trino/sql/planner/sanity/TestDynamicFiltersChecker.java
> Make IR nodes records

- client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
- core/trino-main/src/test/java/io/trino/server/security/oauth2/TestingHydraIdentityProvider.java
- core/trino-spi/src/test/java/io/trino/spi/block/TestBlockRetainedSizeBreakdown.java
- plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestingDruidServer.java
( *) This is not user-visible or is docs only, and no release notes are required.
```markdown
```
> Fix compilation warnings

- core/trino-main/src/main/java/io/trino/operator/JoinDomainBuilder.java
- core/trino-spi/src/main/java/io/trino/spi/block/BlockUtil.java
- core/trino-spi/src/main/java/io/trino/spi/type/ArrayType.java
> Use switch case expressions for processing by Block type

- plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
- plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftErrorCode.java
Throw TrinoException when varchar size not present in Redshift
> Throw TrinoException when varchar size not present in Redshift

- plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
- plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
> Disable rename column in Phoenix connector

- plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
> Remove depercated dep in phoenix client

- core/trino-main/src/main/java/io/trino/operator/JoinDomainBuilder.java
- core/trino-spi/src/main/java/io/trino/spi/block/BlockUtil.java
- core/trino-spi/src/main/java/io/trino/spi/type/ArrayType.java
Follow-up from https://github.com/trinodb/trino/pull/21181
```markdown
```
> Explicitly handle LazyBlock in switch expressions

- core/trino-main/src/main/java/io/trino/metadata/DisabledSystemSecurityMetadata.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
- core/trino-main/src/main/java/io/trino/metadata/SystemSecurityMetadata.java
- testing/trino-tests/src/test/java/io/trino/security/TestingSystemSecurityMetadata.java
Follow up of https://github.com/trinodb/trino/pull/20366 and https://github.com/trinodb/trino/pull/20491
```markdown
```
> Add SystemSecurityMetadata interface method for drop column's not null

- plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
Fixes https://github.com/trinodb/trino/issues/21198
> Enable LIMIT pushdown test in Snowflake

- core/trino-main/src/test/java/io/trino/execution/buffer/TestPagesSerde.java
- core/trino-main/src/test/java/io/trino/operator/BenchmarkDynamicFilterSourceOperator.java
- core/trino-main/src/test/java/io/trino/operator/BenchmarkGroupedTopNRankBuilder.java
- core/trino-main/src/test/java/io/trino/operator/BenchmarkGroupedTopNRowNumberBuilder.java
- core/trino-main/src/test/java/io/trino/operator/BenchmarkTopNOperator.java
- core/trino-main/src/test/java/io/trino/operator/spiller/BenchmarkBinaryFileSpiller.java
- core/trino-main/src/test/java/io/trino/sql/gen/BenchmarkPageProcessor.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPageSourceFactory.java
- plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchRecordSetProvider.java
- pom.xml
TPCH was switched to JDK 21. 
1.3 was burned due to a bug introduced during refactoring.
> Update tpch to 1.4

- core/trino-main/src/main/java/io/trino/cost/FilterStatsCalculator.java
- core/trino-main/src/main/java/io/trino/cost/StatsCalculatorModule.java
- core/trino-main/src/main/java/io/trino/cost/ValuesStatsRule.java
- core/trino-main/src/main/java/io/trino/sql/planner/IrExpressionInterpreter.java
- core/trino-main/src/main/java/io/trino/testing/PlanTester.java
- core/trino-main/src/test/java/io/trino/cost/TestValuesNodeStats.java
- core/trino-main/src/test/java/io/trino/sql/TestExpressionInterpreter.java
> Remove unnecessary calls to interpreter

- docs/src/main/sphinx/object-storage/file-system-gcs.md
- docs/src/main/sphinx/object-storage/file-system-s3.md
> Add missing documentation table headers

- plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
fixes https://github.com/trinodb/trino/issues/21247
> Isolate testKeyspaceNameAmbiguity Cassandra test

- plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
> Fix Snowflake test name typo

- docs/src/main/sphinx/release/release-443.md
Correcting Delta Lake connector release note (... **`timestamp(6)`**  ...).
https://github.com/trinodb/trino/pull/21178#discussion_r1536565429
https://github.com/trinodb/trino/pull/20814
> Fix 443 release notes

- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java
Follow-up from https://github.com/trinodb/trino/pull/18506
The bug in the current version of Trino should not affect any existing functionality.
It gets relevant only in `MERGE` scenarios.
Discovered while working on https://github.com/trinodb/trino/pull/18521
```markdown
```
> Disregard nodes which are update targets when selecting source tables

- docs/src/main/sphinx/connector/snowflake.md
- plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java
- plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
```markdown
* Add support for `stddev`, `stddev_pop` pushdown. ({issue}`21338`)
```
> Support stddev, stddev_pop pushdown for Snowflake

- testing/trino-testing/src/main/java/io/trino/testing/sql/SqlExecutor.java
- testing/trino-testing/src/main/java/io/trino/testing/sql/TestTable.java
- testing/trino-testing/src/main/java/io/trino/testing/sql/TestView.java
> Add `@Language` to TestTable, TestView and SqlExecutor

- client/trino-jdbc/pom.xml
- plugin/trino-oracle/pom.xml
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/AbstractTestOracleTypeMapping.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
- plugin/trino-resource-group-managers/pom.xml
- pom.xml
> Update Oracle JDBC to 23.3.0.23.09

- core/trino-main/src/main/java/io/trino/sql/ir/Bind.java
The Bind expression takes values (plural).
> Update Bind javadoc for multiple values

- docs/src/main/sphinx/connector/snowflake.md
- plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java
- plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
```markdown
* Support statistical aggregation pushdown. ({issue}`21384`)
```
> Implement statistical aggregation pushdown for Snowflake connector

- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ColumnMapping.java
- plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
- plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java
> Make ColumnMapping constructor private

- core/trino-main/src/main/java/io/trino/operator/aggregation/AggregationMaskCompiler.java
- core/trino-main/src/test/java/io/trino/operator/aggregation/TestAggregationMaskCompiler.java
> Improve AggregationMaskCompiler tests with dictionary blocks

- plugin/trino-mongodb/pom.xml
- pom.xml
> Update SDKs + flyway + mongodb

- plugin/trino-hive/pom.xml
- plugin/trino-iceberg/pom.xml
- pom.xml
https://downloads.apache.org/httpcomponents/httpcore/RELEASE_NOTES-4.4.x.txt
+ https://github.com/aws/aws-sdk-java-v2/issues/2831#issuecomment-1977272827
> Update httpcore to 4.4.16

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesFunction.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
> Add table_changes test for replaced tables

- docs/src/main/sphinx/develop/example-jdbc.md
Fixes a spelling error in the JDBC doc. Same as https://github.com/trinodb/trino/pull/21267, which I closed by mistake.
> Fix spelling in JDBC doc

- core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenTaskSource.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestEventDrivenTaskSource.java
> Avoid endless loop on EventDrivenTaskSource

- core/trino-main/src/main/java/io/trino/util/Long2LongOpenBigHashMap.java
- core/trino-main/src/main/java/io/trino/util/LongLong2LongOpenCustomBigHashMap.java
- core/trino-main/src/test/java/io/trino/operator/scalar/TestBitwiseFunctions.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnIndexBuilder.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/index/Indexer.java
- pom.xml
The checkers enabled in this commit are warning by default, but judging
by their description, the code should obey by their expectations.
> Enable couple well-meaning error-prone checkers 

- docs/src/main/sphinx/sql/alter-table.md
This PR updates syntax and wrapping in the alter-table.md documentation file.
> Fix ALTER TABLE documentation syntax

- core/trino-main/src/main/java/io/trino/execution/buffer/OutputBufferMemoryManager.java
It was observed that with high concurrency threads get highly congested on getBufferBlockedFuture. This commit introduces double checked lock to reduce that from happening.
```markdown
```
> Use double checked lock in getBufferBlockedFuture to reduce congestion

- core/trino-main/src/main/java/io/trino/operator/aggregation/state/StateCompiler.java
- core/trino-main/src/test/java/io/trino/operator/aggregation/state/TestStateCompiler.java
It didn't account for memory retained in `value` and `valueIdNull` fields.
Now the generated class looks like this:
```
public final class GroupedInOut_20240405_170804_120 implements InOut, GroupedAccumulatorState, InternalDataAccessor {
private int groupId;
private final LongBigArray value = new LongBigArray();
private final BooleanBigArray valueIdNull = new BooleanBigArray(true);
private static final long INSTANCE_SIZE = (long)SizeOf.instanceSize(GroupedInOut_20240405_170804_120.class);
public long getEstimatedSize() {
long size = INSTANCE_SIZE;
size += this.value.sizeOf();
size += this.valueIdNull.sizeOf();
return size;
}
```
All credit goes to @lukasz-stec
> Fix GroupedInOut estimatedSizeOf method definition

- plugin/trino-snowflake/pom.xml
- pom.xml
> Update google-libraries to 26.37.0

- core/trino-main/src/main/java/io/trino/FeaturesConfig.java
- core/trino-main/src/main/java/io/trino/execution/DynamicFilterConfig.java
- core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
- core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java
Remove configs deprecated in 2022 or earlier.
> Remove long deprecated configs

- pom.xml
This effectively updates git-commit-id-plugin to 8.0.1
```markdown
```
> Remove redundant version definition

- plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
Relates to https://github.com/trinodb/trino/issues/21157
> Specify schema name in Snowflake testInformationSchemaFiltering

- pom.xml
https://github.com/Alluxio/alluxio/compare/v311...v312
> Update Alluxio to 312

- docs/src/main/sphinx/connector/iceberg.md
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
Logical prep for https://github.com/trinodb/trino/pull/21370
> Deprecate iceberg.materialized-views.hide-storage-table

- core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
- core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
- core/trino-main/src/main/java/io/trino/transaction/InMemoryTransactionManagerModule.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/ClosingBinder.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcModule.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestCloseIdleWriters.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheFileOperations.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePlugin.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeRenameToWithGlueMetastore.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaS3AndGlueMetastoreTest.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/StaticMetastoreConfig.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreModule.java
- plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClientModule.java
Extracted from https://github.com/trinodb/trino/pull/21470
> Closing binder cleanup

- core/trino-main/src/main/java/io/trino/FeaturesConfig.java
- core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestMaterializedViews.java
- core/trino-spi/src/main/java/io/trino/spi/type/DecimalConversions.java
- core/trino-spi/src/main/java/io/trino/spi/type/Decimals.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
`legacy.materialized-view-grace-period` got deprecated in 411.
> Remove deprecated legacy materialized view grace period config property

- client/trino-client/src/main/java/io/trino/client/auth/kerberos/LoginBasedUnconstrainedContextProvider.java
- core/trino-spi/src/main/java/io/trino/spi/block/MapHashTables.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/authentication/CachingKerberosAuthentication.java
- plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchange.java
- plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeSink.java
Extracted from https://github.com/trinodb/trino/pull/21482
> Fix synchronization in SPI, client, plugin toolkit, filesystem-exchange

- core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroup.java
- core/trino-main/src/main/java/io/trino/server/DynamicFilterService.java
Extracted from https://github.com/trinodb/trino/pull/21482
> Fix InternalResourceGroup synchronization

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
- plugin/trino-hudi/pom.xml
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiModule.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiSplitManager.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
fixes extracted from https://github.com/trinodb/trino/pull/21470 while I continue making the test great
> Fix thread leaks in Hive, Iceberg, Delta and Hudi connectors

- pom.xml
- testing/trino-benchto-benchmarks/pom.xml
> Update maven plugins to support reproducible builds

- core/trino-main/src/main/java/io/trino/sql/planner/EffectivePredicateExtractor.java
- core/trino-main/src/test/java/io/trino/sql/query/TestIssue21457.java
Fixes #21457 
```markdown
* TBD. ({issue}`21457`)
```
> Fix incorrect derivation of effective predicate

- plugin/trino-elasticsearch/pom.xml
- pom.xml
> Update AWS SDK v1 to 1.12.698

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableWithCustomLocationUsingGlueMetastore.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/S3ClientFactory.java
> Avoid hard-coded region name in tests

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSecurityModule.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/HiveSecurityModule.java
This is a common convention with the "redundant" comma at the end.
```markdown
```
> Reformat security enums to make them easier to extend

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
Change exception thrown from `TrinoRestCatalog::listTables` to TrinoException in case of external error.
```markdown
```
> Adjust Iceberg RestCatalog exception handling

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitSource.java
Throw exception with error code taken from cause instead of always throwing `GENERIC_INTERNAL_ERROR`
```markdown
```
> Adjust DeltaLakeSplitSource error code based on cause

- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowToPageConverter.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryColumnHandle.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryFilterQueryBuilder.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPageSourceProvider.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageArrowPageSource.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageAvroPageSource.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ptf/Query.java
> Make BigQueryColumnHandle record

- core/trino-main/src/main/java/io/trino/dispatcher/DispatchManager.java
- core/trino-main/src/main/java/io/trino/dispatcher/FailedDispatchQuery.java
- core/trino-main/src/main/java/io/trino/dispatcher/LocalDispatchQuery.java
- core/trino-main/src/main/java/io/trino/execution/DataDefinitionExecution.java
- core/trino-main/src/main/java/io/trino/execution/QueryStateMachine.java
- core/trino-main/src/main/java/io/trino/execution/QueryTracker.java
- core/trino-main/src/main/java/io/trino/execution/SqlQueryExecution.java
- core/trino-main/src/main/java/io/trino/execution/SqlQueryManager.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
- core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
Extracted from https://github.com/trinodb/trino/pull/21475
> Add QueryTracker stats
