- docs/src/main/sphinx/connector/kafka.rst
- lib/trino-record-decoder/pom.xml
- lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/ProtobufColumnDecoder.java
- lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/ProtobufRowDecoder.java
- lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/ProtobufRowDecoderFactory.java
- lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/ProtobufValueProvider.java
- lib/trino-record-decoder/src/test/java/io/trino/decoder/protobuf/TestProtobufDecoder.java
- lib/trino-record-decoder/src/test/resources/decoder/protobuf/test_oneof.proto
- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/encoder/protobuf/ProtobufSchemaParser.java
- plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/protobuf/TestKafkaProtobufWithSchemaRegistryMinimalFunctionality.java
- plugin/trino-kafka/src/test/resources/protobuf/test_oneof.proto
This adds Kafka connector support for Protobuf  `oneOf` data types by encoding them as a JSON object.
Protobuf `oneOf` data types are a single field in the message that can hold one value of multiple fields (of varying types) per the schema definition. This adds support for these data types by encoding the entire `oneOf` field as a JSON object where each field name is a key in the JSON object where all values, except one, are `null`. The value that is set corresponds to the set value in the `DynamicMessage` that is processed in the message.
```markdown
* Added support for …
```
> Add oneof support for Protobuf via Confluent Schema Registry

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeCdfPageSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSinkProvider.java
Let the caller of `DeltaLakeCdfPageSink` constructor add the `_change_type` CDF column handle.
This is a mere refactoring - no functionality change should come with this change.
> Remove `AbstractDeltaLakePageSink.addSpecialColumns` method

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
As can be seen in the snippets below:
- the physical input is the same for both queries `Physical input: 1.20kB` 
- the query selecting a nested field has `Input: 1 row (5B)` which is much less than the query doing the selection of the whole row `Input: 1 row (50B)`
```
trino:tiny> explain analyze select b.c3.d2.e2.f2 from iceberg.tiny.itest2;
Query Plan                                       >
------------------------------------------------------------------------------------------------------------------------------>
Trino version: dev                                                                                                           >
Queued: 761.02us, Analysis: 27.10ms, Planning: 33.96ms, Execution: 536.67ms                                                  >
Fragment 1 [SOURCE] …
```
> Showcase dereference pushdown limited effectiveness in Iceberg

- lib/trino-record-decoder/src/main/java/io/trino/decoder/avro/AvroColumnDecoder.java
- lib/trino-record-decoder/src/test/java/io/trino/decoder/avro/TestAvroDecoder.java
If decoding to a REAL then getLong is called.
```markdown
```
> Remove unused codepath in AvroColumnDecoder

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/FlushMetadataCacheProcedure.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFlushMetadataCacheProcedure.java
- testing/trino-testing/src/main/java/io/trino/testing/QueryAssertions.java
Support following scenario
- table was checked via Trino, so Delta connector knows table doesn't
exist and cached that (`CachingMetastore` caches also misses).
- table is created externally
- `flush_metadata_cache` is used so that table becomes accessible via
Trino
> Allow Delta flush_metadata_cache after table creation

- core/trino-main/src/main/java/io/trino/execution/StageStateMachine.java
- core/trino-main/src/main/java/io/trino/operator/DirectExchangeClientStatus.java
- core/trino-main/src/main/java/io/trino/operator/OperatorStats.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/metrics/TDigestHistogram.java
> Use bulk merging of TDigestHistogram

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/CorruptedIcebergTableHandle.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergErrorCode.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/TrinoCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergTrinoRestCatalogConnectorSmokeTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Fixes https://github.com/trinodb/trino/issues/12318
Follow up of https://github.com/trinodb/trino/pull/16651 for corrupted Iceberg Tables
```markdown
* Support Iceberg's DROP TABLE for corrupted tables. ({issue}`16674`)
```
> Support Iceberg's DROP TABLE for corrupted tables

- docs/src/main/sphinx/admin/graceful-shutdown.rst
- docs/src/main/sphinx/release/release-414.md
- docs/src/main/sphinx/security/built-in-system-access-control.rst
- docs/src/main/sphinx/security/file-system-access-control.rst
- Update release note for 414
- Clarify for system access controls
- Update affected graceful shutdown documentation
Replaces #17142
Release note and doc updates included. No new entry needed.
> Document changes in default access control

- core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
- docs/src/main/sphinx/admin/fault-tolerant-execution.rst
- docs/src/main/sphinx/admin/properties-query-management.rst
Add documentation for adaptive partitioning and adaptive task sizing of FTE
Add docs for https://github.com/trinodb/trino/pull/16719 and https://github.com/trinodb/trino/pull/17024
```markdown
```
> Add documentation for adaptive partitioning and adaptive task sizing of FTE

- core/trino-main/src/main/java/io/trino/dispatcher/DispatchManager.java
- core/trino-main/src/main/java/io/trino/execution/QueryManager.java
- core/trino-main/src/main/java/io/trino/execution/QueryTracker.java
- core/trino-main/src/main/java/io/trino/execution/SqlQueryManager.java
- core/trino-main/src/main/java/io/trino/server/protocol/ExecutingStatementResource.java
Add a method to QueryTracker to test if query is still within history without need to allocate new Optional each time. 
> Improve code readability with QueryTracker#hasQuery

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDropTableCompatibility.java
Fixes https://github.com/trinodb/trino/issues/13199
Relates to https://github.com/trinodb/trino/issues/13199#issuecomment-1518745331
> Use enhanced routine when dropping Delta tables backed by AWS Glue on Databricks

- pom.xml
By default Maven just logs a warning if a non-existent profile is specified with . Enforcer plugin has a rule to fail the build in such cases. This avoids cases where a typo or incorrect ci.yml makes the build appear green even though some expected profile wasn't used.
I noticed this while working on https://github.com/trinodb/trino/pull/17167
> Fail the build if a non-existent Maven profile is used

- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcCachingConnectorSmokeTest.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcFlushMetadataCacheProcedure.java
Extract JDBC's `flush_metadata_cache` procedure tests into separate class and run it sequentially.  These tests interfered with each other when running in parallel.
Fixes https://github.com/trinodb/trino/issues/17210
> Test JDBC flush_metadata_cache sequentially

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastoreConfig.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/SharedHiveMetastoreCache.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreConfig.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/MockThriftMetastoreClient.java
Table absence is harder to less interesting to cache and sometimes undesirable at all. This is similar to `metadata.cache-missing` config we have for JDBC connectors.
> Allow disabling caching missing tables in CachingMetastore

- docs/src/main/sphinx/connector/iceberg.rst
- lib/trino-parquet/src/main/java/io/trino/parquet/BloomFilterStore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestHiveParquetWithBloomFilters.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetWithBloomFilters.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseTestParquetWithBloomFilters.java
Related HIVE PR: https://github.com/trinodb/trino/pull/14428 and https://github.com/trinodb/trino/pull/15633. 
This brings the same change to the Iceberg connector. 
Enable hive connector to read parquet file's bloomfilter statistics. For more details: https://github.com/apache/parquet-format/blob/master/BloomFilter.md. 
```markdown
* Improve performance of queries with filters when bloom filter indexes are present in parquet files. Usage of bloom filters from parquet files can be disabled using the catalog configuration property `parquet.use-bloom-filter` or the catalog session …
```
> Enable reading Parquet's bloomfilter statistics for Iceberg connector

- core/trino-main/src/main/java/io/trino/metadata/ResolvedFunction.java
The mismatch of "nullability" and "functionNullability" could cause
failure of JSON deserialization for ResolvedFunction
(This PR is to replace https://github.com/trinodb/trino/pull/13402 which had merge issue)
The symptom is query that involves function usages fails with error message like:
java.lang.IllegalArgumentException: Invalid JSON bytes for [simple type, class io.trino.metadata.ResolvedFunction]
Root cause is https://github.com/trinodb/trino/pull/10183, and specifically https://github.com/trinodb/trino/commit/2c1ebd61f2a017563ba27a2e7a19e51e66ae472d
The problem is exposed starting from https://github.com/trinodb/trino/pull/11217
Repro steps:
1. Create a file-based access control policy for a table with row filter or column mask that uses a function "filter": "name LIKE 'A%'"
2. …
> Make functionNullability property consistent in ResolvedFunction

- docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Add links to data type definitions for fault-tolerant execution configuration property descriptions
https://github.com/trinodb/trino/pull/17179#discussion_r1174157915
```markdown
```
> Add property type links to fault-tolerant execution properties

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DeltaLakeTestUtils.java
Support commenting on table and column with `id` and `name` column mapping mode in Delta Lake
```markdown
* Support commenting on table and column with `id` and `name` column mapping mode. ({issue}`issuenumber`)
```
> Support commenting on table and column with `id` and `name` column mapping mode in Delta Lake

- plugin/trino-delta-lake/src/main/antlr4/io/trino/plugin/deltalake/expression/SparkExpressionBase.g4
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/BetweenPredicate.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/NullLiteral.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionBuilder.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionConverter.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionTreeVisitor.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/expression/TestSparkExpressions.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCheckConstraintCompatibility.java
> Support BETWEEN in Delta check constraints

- core/trino-main/src/main/java/io/trino/failuredetector/FailureDetectorModule.java
- core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
- core/trino-main/src/main/java/io/trino/server/InternalCommunicationHttpClientModule.java
- core/trino-main/src/main/java/io/trino/server/InternalCommunicationModule.java
- core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
- core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticatorSupportModule.java
- core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2ServiceModule.java
- core/trino-main/src/test/java/io/trino/failuredetector/TestHeartbeatFailureDetector.java
- core/trino-main/src/test/java/io/trino/server/TestGenerateTokenFilter.java
The previous approach was dangerous, as it was modifying configuration for all HTTP clients and adding global filters even for HTTP clients there were not supposed to be used for internal communication.
With this change, it's now intentional which HTTP clients are supposed to use secured internal communication.
```markdown
```
> Refactor internal http client usage

- plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListener.java
- plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/QueryDao.java
- plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/QueryEntity.java
- plugin/trino-mysql-event-listener/src/test/java/io/trino/plugin/eventlistener/mysql/TestMysqlEventListener.java
* Follow-up PR to https://github.com/trinodb/trino/pull/15318. This PR makes the DAO in `trino-mysql-event-listener` account for planning CPU time.
> Expose planning CPU time for MYSQL event listener

- docs/src/main/sphinx/security/oauth2.rst
OAuth 2.0 documentations improvements requested by @bendemott Resident Solutions Architect. Incorporated more details provided by @lukasz-walkiewicz.
> OAuth refresh token clarification

- docs/src/main/sphinx/connector/delta-lake.rst
Edits to make corrections for:
- Improper grammar
- Typos
- Improper capitalization
- Incorrect punctuation, such as comma usage 
- Add adjectives to make subjects clear
- Formatting for default values
- Line wrapping to 80 char where possible per conventions
Noticed these last year while working on fixing the description of the delta.domain-compaction-threshold export config property.
- https://github.com/trinodb/trino/pull/12965
- https://github.com/trinodb/trino/pull/13039
> Documentation copy and style edits Delta Lake

- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorSession.java
> Remove deprecated getStartTime method from ConnectorSession

- core/trino-main/src/main/java/io/trino/server/InternalCommunicationModule.java
Master is broken because of the https://github.com/trinodb/trino/pull/17187. This PR fixes the discovery client configuration that was missing.
> Add missing discovery client TLS configuration

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
The main purpose is quickly accessing product test environments using the new `DeltaLakeExternalQueryRunnerMain`.
> Allow accessing external environments in Delta Lake query runner

- docs/src/main/sphinx/connector/delta-lake.rst
- docs/src/main/sphinx/connector/iceberg.rst
`$data` metadata table was [removed in v411](https://trino.io/docs/current/release/release-411.html#iceberg-connector) in [this PR](https://github.com/trinodb/trino/pull/16650) for both Iceberg and Delta Lake
Remove reference to it in the docs
```markdown
```
> Remove doc reference to $data metadata table

- lib/trino-record-decoder/pom.xml
#16836 added `io.confluent:kafka-protobuf-provider:jar:7.3.1` as a dependency of the `trino-record-decoder` module, but didn't add the Confluent repository. The CI in the PR might have passed if it used a cached local Maven repository, but now is failing on master and other branches. Fixes #17230
> Add missing Confluent repo in record decoder module

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/iceberg/TestIcebergParquetFaultTolerantExecutionConnectorTest.java
- testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
- testing/trino-tests/src/test/java/io/trino/tests/TestDistributedQueriesNoHashGeneration.java
- testing/trino-tests/src/test/java/io/trino/tests/TestOptimizeMixedDistinctAggregations.java
> Improve DistributedQueryRunner.Builder

- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Since table functions with table inputs were introduced in 409, we did not perform access control checks on columns used by the table function.
In 412, `exclude_columns` was introduced, being the first, and so far the only built-in table function in Trino which uses input table. Due to lack of security checks, this function could be used to bypass access control.
This fix applies proper security checks. It secures the `exclude_columns` function as well as any other existing or future table functions using table inputs.
```markdown
* Check read permissions for input columns used …
```
> Check read permission for columns required by table function

- lib/trino-hdfs/pom.xml
- lib/trino-hdfs/src/test/java/io/trino/hdfs/TestFSDataInputStreamTail.java
- lib/trino-hdfs/src/test/java/io/trino/hdfs/TestFileSystemCache.java
The tests verify global (static) state, e.g.
`TrinoFileSystemCache.INSTANCE.getFileSystemCacheStats().getCacheSize()`, so test classes cannot be run in parallel.
This also removes `@Test(singleThreaded = true)` from test classes. This becomes redundant, and may create false impression as to how test concurrency is managed in this module.
hopefully fixes https://github.com/trinodb/trino/issues/17158
> Run trino-hdfs tests single-threaded

- core/trino-main/src/main/java/io/trino/execution/TableInfo.java
- core/trino-main/src/main/java/io/trino/metadata/Metadata.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
- core/trino-main/src/main/java/io/trino/sql/planner/InputExtractor.java
- core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyTableScanRedirection.java
- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java
- core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java
- core/trino-main/src/main/java/io/trino/sql/planner/planprinter/TableInfoSupplier.java
- core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
- core/trino-main/src/main/java/io/trino/tracing/TracingMetadata.java
- core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
- core/trino-main/src/test/java/io/trino/metadata/CountingAccessMetadata.java
- core/trino-main/src/test/java/io/trino/sql/planner/assertions/ColumnReference.java
- core/trino-main/src/test/java/io/trino/sql/planner/assertions/IndexSourceMatcher.java
- core/trino-main/src/test/java/io/trino/sql/planner/assertions/TableScanMatcher.java
- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java
- plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
- plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMetadata.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
- plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
- testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
- testing/trino-tests/src/test/java/io/trino/sql/planner/BaseCostBasedPlanTest.java
This retrofits existing `ConnectorMetadata.getSchemaTableName`. The method remains deprecated, because a new name, `getTableName` is better.
As a benefit of this change, the `ConnectorMetadata`'s `getTableMetadata` and `getTableSchema` no longer need to support synthetic table handles. This fixes a bug in connectors that support advanced pushdown. For example, `HiveMetadata.getTableMetadata` called for `HiveTableHandle` having `projectedColumns` should return column metadata for the projected columns, but it did not do that.
> Remove redundant table metadata calls

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/BlockLocation.java
```markdown
* Reduce coordinator memory usage when caching of file metadata is enabled ({issue}`issuenumber`)
```
> Intern hostnames in caching directory lister

- pom.xml
The version resolves security issue:
> [SPARKJ-632] The credentials leaked by the driver are passed into error messages.
I haven't observed such credential leak in Trino CI, but it would be better to upgrade the driver. 
> Upgrade Databricks JDBC driver to 2.6.32

- docs/src/main/sphinx/security/ldap.rst
- docs/src/main/sphinx/security/tls.rst
This change updates property descriptions and examples with supported file formats for password authentication.
```markdown
```
> Update supported file formats

- docs/src/main/sphinx/installation/deployment.rst
Long overdue .. there is more info in the book but this should be a good starting point. 
Keeps coming up in slack and other questions.
> Add info for memory setting

- docs/src/main/sphinx/connector/iceberg.rst
Inline `$ref` with other metadata tables, same as [`$files` above it](https://github.com/trinodb/trino/blame/master/docs/src/main/sphinx/connector/iceberg.rst#L1029-L1030)
Its currently out of alignment:
```markdown
```
> Inline $ref with other metadata tables

- core/trino-main/src/main/java/io/trino/likematcher/FjsMatcher.java
- core/trino-main/src/main/java/io/trino/likematcher/LikeMatcher.java
- core/trino-main/src/test/java/io/trino/likematcher/TestLikeMatcher.java
- core/trino-main/src/test/java/io/trino/operator/scalar/BenchmarkLike.java
When the pattern contains only literals and %, use substring
search for each of the tokens, via an implementation of the
FJS algorithm: https://cgjennings.ca/articles/fjs/
Benchmark results follow:
* dynamicXXX measures the end-to-end performance of compiling
the matcher and calling it.
* matchXXX measures the performance of the match call after
the matcher has been compiled
* xxxNonOptimized vs xxxOptimized measures the performance
when LikeMatcher is constructed with optimize = true/false
```
Benchmark                            Pattern                     Before                          After
dynamicNonOptimized               SHORT_TOKENS_1       3206.181 ±    16.858  ns/op     1301.583 ±  6.762  ns/op
dynamicNonOptimized               SHORT_TOKENS_2       3534.404 ±    20.939  ns/op …
```
> Improve performance for LIKE patterns involving %

- core/trino-main/src/main/java/io/trino/operator/scalar/MathFunctions.java
- core/trino-main/src/test/java/io/trino/operator/scalar/TestMathFunctions.java
Fix an edge case with Round function when the scaled number exceeds Double.MAX_VALUE
This issue was caused by PR https://github.com/trinodb/trino/pull/14620.
Before this PR, select round(123.4, 10000000) would return 0.0 incorrectly.
After this PR, select round(123.4, 10000000) would cause issue "input is infinite or NaN"
After this fix, it would return correctly 123.4. 
In general this PR fixes an edge case for round(a, b) if a*b^10 is exceeds Double.MAX_VALUE
> Fix an edge case with Round function when the scaled number exceeds Double.MAX_VALUE

- docs/src/main/sphinx/connector/iceberg.rst
Added mention as requested of the requirement to manually run REFRESH MV after creating it.
> Improve Iceberg documentation for refresh new materialized view

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSource.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceProvider.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/TimestampCoercer.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/TypeCoercer.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSource.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcTypeTranslator.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveCoercionPolicy.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestTimestampCoercer.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/configs/ConfigHdp3.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnPartitionedTable.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnUnpartitionedTable.java
Add support for timestamp to varchar coercer in hive tables. In case of partitioned table it is supported by most of the format and in case of unpartitioned tables only ORC format is supported as of now. 
The coercion that was supported as of current master for unpartitioned tables are inherently supported by the `ColumnReader` and this PR introduces a framework which maps a `OrcTypeKind` to a corresponding `TrinoType` and also re-uses the `TypeCoercer` used by partitioned tables. 
```markdown
* Add support for timestamp to varchar coercer in hive tables
```
> Add support for timestamp to varchar coercer in hive tables

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
Added in 89eab99bb83aef1f469f6de6e6958b8012d15a5b, became obsolete in a96aa9cfe904194ca4752baf99b8702b5472f162.
> Remove left-over TODO comment

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java
It currently probably doesn't fail, because maps being written here are `map(varchar, varchar)` (same key and value type).
thanks @dain for spotting this
> Fix typo in CheckpointWriter

- core/trino-main/src/main/java/io/trino/dispatcher/LocalDispatchQuery.java
- core/trino-main/src/main/java/io/trino/server/protocol/Query.java
- core/trino-main/src/test/java/io/trino/dispatcher/TestLocalDispatchQuery.java
Currently, `/v1/statement/queued/{queryId}/{slug}/{token}` get request returns queued query state even if the query is already planning. It will not be redirected to `/v1/statement/executing/{queryId}/{slug}/{token}` get request until all planning tasks including plan distribution is completed. When planning takes long time or fails during planning, it can mislead callers because of this. So, it needs to set `submitted` when transitioning to `PLANNING`.
(v) This is not user-visible or docs only and no release notes are required.
```markdown
```
> Transition to executing when begin planning

- .github/workflows/stale.yml
- Update to v8
- Ignore drafts for the stale bot
- Remove unused label
> Ignore draft PRs in stale action

- testing/trino-server-dev/etc/catalog/tpch.properties
> Use standard TPCH configs in development server

- plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftTableStatisticsReader.java
Materialized Views are analyzed automatically in AWS Redshift now.
> Remove `ANALYZE` call on materialized view

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
Fix typo in HiveMetadata. There's no same typo `spported` in this repository.
> Fix typo in HiveMetadata

- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadataFactory.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiUtil.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/split/HudiBackgroundSplitLoader.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/split/HudiSplitFactory.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiUtil.java
This cleans up usages of `FileSplit` and `InputFormat` from `org.apache.hadoop.mapred`. 
Additionally also added a small change to get rid of Hudi's `FsUtils`. Note that `isDirectory` check for the tableLocation is replaced with a check to look for at least one file.
Relates to https://github.com/trinodb/trino/issues/17228
```markdown
```
> Clean up `hadoop.mapred` usages in Hudi

- docs/src/main/sphinx/release.rst
- docs/src/main/sphinx/release/release-416.md
Assemble the release notes for the upcoming Trino 416 release. Fixes #17290 
* #17262 ✅ rn ✅ docs
* #17092 ✅ rn ✅ docs
* #17241 ❌  rn ✅ docs
* #17266 ✅ rn ✅ docs
* #17269 ✅ rn ✅ docs
* #17270 ✅ rn ✅ docs
* #16802 ✅ rn ✅ docs
* #17277 ✅ rn ✅ docs
* #16424 ✅ rn ✅ docs
* #17250 ✅ rn ✅ docs
* #17271 ✅ rn ✅ docs
* #16888 ✅ rn ✅ docs
* #17273 ✅ rn ✅ docs
* #17297 ✅ rn ✅ docs
* #17220 ✅ rn ✅ docs
* #17298 ✅ rn ✅ docs
* #16167 ✅ rn ✅ docs
* #17306 ✅ rn ✅ …
> Add Trino 416 release notes

- plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java
Method is identical to its super method.
> Remove useless `getInfo()` override in Pinot

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java
`beginBlockEntry()` and `closeEntry` should be used for non-null values, the `appendNull` should be used alone for null values.
thanks @dain for spotting this
> Fix potential failure when writing null min/max/null count into checkpoint

- docs/src/main/sphinx/connector/alter-table-limitation.fragment
Improve header to be more specific to its content.
> Improve title for alter table limitation fragment

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePartitionManager.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/statistics/TestMetastoreHiveStatisticsProvider.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiUtil.java
Refactors `HiveSplitManager`s to avoid redundant repeated work when creating `HivePartitionMetadata` instances for each partition enumerated by eagerly extracting session properties, avoiding unnecessary intermediate collection copies, and making methods static where possible.
> Refactor HiveSplitManager

- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorSplitSource.java
Note that some existing implementations are not thread-safe. For example `IcebergSplitSource.scannedFiles` is accessed without any synchronization.
> Document ConnectorSplitSource thread-safety requirements

- core/trino-main/src/test/java/io/trino/metadata/CountingAccessMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePerTransactionMetastoreCache.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreAccessOperations.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/CountingAccessHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/CountingAccessHiveMetastoreUtil.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestHiveMetastoreAccessOperations.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestHiveMetastoreMetadataQueriesAccessOperations.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergGetTableStatisticsOperations.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
- testing/trino-tests/src/test/java/io/trino/tests/TestGetTableStatisticsOperations.java
The class name is "entity name", should generally be singular.
> Fix enum name in CountingAccessHiveMetastore

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsReader.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergStatistics.java
Previously getting stats would fail with NPE:
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.apache.iceberg.Snapshot.parentId()" because the return value of "org.apache.iceberg.Table.snapshot(long)" is null
at io.trino.plugin.iceberg.TableStatisticsReader$2.computeNext(TableStatisticsReader.java:328)
at io.trino.plugin.iceberg.TableStatisticsReader$2.computeNext(TableStatisticsReader.java:322)
at com.google.common.collect.AbstractSequentialIterator.next(AbstractSequentialIterator.java:74)
at io.trino.plugin.iceberg.TableStatisticsReader$1.computeNext(TableStatisticsReader.java:305)
at io.trino.plugin.iceberg.TableStatisticsReader$1.computeNext(TableStatisticsReader.java:284)
at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
at …
```
> Fix Iceberg statistics loading after snapshot expiration

- plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
- plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleConfig.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleConfig.java
- plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
- plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlConfig.java
- plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConfig.java
- plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
- plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftConfig.java
- plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConfig.java
The configuration toggles `xxx.disable-automatic-fetch-size` were
introduced only temporarily, as a kill-switch.
To be merged after some time since https://github.com/trinodb/trino/pull/16644 is merged and released (in 411).
> Remove kill-switch to disable automatic fetch-size selection

- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/encodings/text/StructEncoding.java
The text reader for structs does not exit once all fields has been read and additional fields are simply read into the existing row builder. The additional fields are supposed to be ignored.
```markdown
* Fix over read in TEXTFILE decoder for structs that contain more columns in the file than are mapped in the schema.
```
> Fix over read in TEXTFILE struct reader

- plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupsPostgresqlFlywayMigration.java
The test is supposed to run single-threaded.
> Fix TestDbResourceGroupsPostgresqlFlywayMigration flakiness

- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriterOptions.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java
- lib/trino-parquet/src/test/java/io/trino/parquet/ParquetTestUtils.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetReaderMemoryUsage.java
- lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/BenchmarkFileFormatsUtils.java
Fix calculation of checking for current page size so that
parquet page sizes don't keep reducing with increasing number 
of compressed pages buffered in memory. Small parquet pages
can reduce parquet reader performance by forcing decoding
and decompression on smaller chunks of data.
```
Benchmark                        (benchmarkFileFormat)  (compression)  (dataSet)   Mode  Cnt  Before score    After score
BenchmarkHiveFileFormat.read   TRINO_OPTIMIZED_PARQUET         SNAPPY   LINEITEM  thrpt   20  15.767 ± 0.155  16.652 ± 0.113  ops/s
Before
read  LINEITEM  SNAPPY  TRINO_OPTIMIZED_PARQUET   788.4MB/s ±  7931.1kB/s ( 0.98%) (N = 20, α = 99.9%)
After
read  LINEITEM  SNAPPY  TRINO_OPTIMIZED_PARQUET   832.7MB/s ±  5808.6kB/s ( 0.68%) (N = 20, α = 99.9%)
```
E.g. page sizes before
```
Column: …
```
> Fix under-sizing of parquet pages in writer 

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/TrinoViewHiveMetastore.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java
Support for comments on views for Delta Lake
```markdown
* Add support for comments on views.
```
> Support for comments on views for Delta Lake

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetReaderConfig.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
These descriptions across iceberg/hive control the same logical configuration, make them consistent. 
N/A
```markdown
* N/A.
```
> Make 'parquet_use_bloom_filter' session property descriptions consistent

- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
- lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
Modified parquet writer to store columns in order of their size inside row groups 
so that the reader can fetch small columns in fewer filesystem requests
Based on similar logic in ORC writer at https://github.com/trinodb/trino/blob/a13e45170c95fb6d4f498c51c26d160e2a619874/lib/trino-orc/src/main/java/io/trino/orc/OrcWriter.java#L420
```markdown
* Improve the layout of data in parquet files for faster reads. ({issue}`17404`)
```
> Group small columns together in parquet files

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/SnapshotsTable.java
This will avoid using custom code to populate the Snapshot metadata table. This improvement will use the Iceberg's metadata `table.scan`, hence any changes to the underlying Iceberg's metadata table's scan logic will be used here. Spark engine also uses the Iceberg's metadata `table.scan` instead of custom code, so this will also help to reduce regression between Trino and Spark engines.
Improvement
Iceberg connector
No change in the syntax or the usage of the `$snapshots` metadata table
* Fixes …
> Use Iceberg Metadata table's API for snapshot metadata table

- core/docker/Dockerfile
- core/trino-spi/pom.xml
- plugin/trino-bigquery/pom.xml
- pom.xml
Spring cleaning in progress :)
> Update various dependencies (both libraries and plugins)

- docs/src/main/sphinx/admin/fault-tolerant-execution.rst
- docs/src/main/sphinx/connector/bigquery.rst
- docs/src/main/sphinx/connector/delta-lake.rst
- docs/src/main/sphinx/connector/hive.rst
- docs/src/main/sphinx/connector/iceberg.rst
- docs/src/main/sphinx/connector/mongodb.rst
- docs/src/main/sphinx/connector/mysql.rst
- docs/src/main/sphinx/connector/postgresql.rst
- docs/src/main/sphinx/connector/redshift.rst
- docs/src/main/sphinx/connector/sqlserver.rst
The fault-tolerant execution doc's previous assertion that read operations are supported by all connectors is false, as is the assertion that the QUERY retry policy does not cause any queries to fail. This PR adjusts the language for fault-tolerant execution accordingly, and adds sections to connectors describing FTE support (allowing for easier documentation if future connectors only support TASK vs QUERY, or retries of read vs write operations).
```markdown
```
> Expand details of per-connector FTE support

- docs/src/main/sphinx/connector/bigquery.rst
- docs/src/main/sphinx/connector/cassandra.rst
- docs/src/main/sphinx/connector/druid.rst
- docs/src/main/sphinx/connector/elasticsearch.rst
- docs/src/main/sphinx/connector/mariadb.rst
- docs/src/main/sphinx/connector/mysql.rst
- docs/src/main/sphinx/connector/oracle.rst
- docs/src/main/sphinx/connector/polymorphic-table-function-ordering.fragment
- docs/src/main/sphinx/connector/postgresql.rst
- docs/src/main/sphinx/connector/query-table-function-ordering.fragment
- docs/src/main/sphinx/connector/redshift.rst
- docs/src/main/sphinx/connector/sqlserver.rst
Follow up to discussion https://github.com/trinodb/trino/pull/14505#discussion_r1006963928
Modify the documentation fragment describing row ordering not being preserved by some table functions to not focus on polymorphic table functions specifically
```markdown
```
> Remove PTF mention from table function ordering fragment

- docs/src/main/sphinx/admin/properties-node-scheduler.rst
* Adds `include-coordinator` to the node scheduler properties reference documentation
```markdown
```
> Add include-coordinator to node scheduler properties docs

- docs/src/main/sphinx/sql/show-columns.rst
Document example of `SHOW COLUMNS` result
> Document example of `SHOW COLUMNS` result

- docs/src/main/sphinx/connector/mongodb.rst
- For the MongoDB connector
Fixes #17322
> Document decimal type mapping in MongoDB connector

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
Reorder schema string entry in Delta Lake to improve readability when checking diff between Trino and Delta. 
> Reorder schema string entry in Delta Lake

- docs/src/main/sphinx/connector/hive.rst
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTableProperties.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
This PR allows us to pass through additional properties to Hive when creating table in Trino. 
The additional properties can provided in the following format 
```
extra_properties = map_from_entries(ARRAY[ROW('extra.property.one', 'one'),ROW('extra.property.two', 'two')]
```
In the initial version, the additional properties will not be exposed in `SHOW CREATE`. 
Fixes https://github.com/trinodb/trino/issues/954
Extension of https://github.com/trinodb/trino/pull/9475
```markdown
* Introduce `extra_properties` for adding arbitrary properties to hive table. ({issue}`954`)
```
> Add extra_properties to hive table properties

- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/BaseKuduConnectorSmokeTest.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationDecimalColumns.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationDynamicFilter.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationHashPartitioning.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationIntegerColumns.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationRangePartitioning.java
Use `closeAfterClass` instead of explicitly closing Kudu server.
> Minor cleanup in Kudu tests

- lib/trino-orc/src/main/java/io/trino/orc/OrcWriter.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSink.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
Call `getRegion` once per chunk written. Previously `getRegion` was called twice per chunk written.
relates to https://github.com/trinodb/trino/pull/17373/files#r1187310938 and https://github.com/trinodb/trino/pull/17385
> Avoid doubled getRegion calls in page sinks

- docs/src/main/sphinx/functions/list.rst
- docs/src/main/sphinx/functions/table.rst
> Add table functions to function list

- core/trino-main/src/test/java/io/trino/execution/scheduler/TestBroadcastPipelinedOutputBufferManager.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/TestPartitionedPipelinedOutputBufferManager.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/TestScaledPipelinedOutputBufferManager.java
- Fix incorrect test logic of setting `noMoreBuffers` again for `Broadcast` and `Partitioned` `OutputBufferManager`.
- It seems that we don't have test case for `ScaledPipelinedOutputBufferManager`. This PR introduce test case for it.
```markdown
```
> Fill in missing unit test for ScaledPipelinedOutputBufferManager

- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
Output of `parquet-tools meta`
Before
Row group 25:  count: 2240892  26.32 B records  start: 1479039171  total(compressed): 56.243 MB total(uncompressed):56.243 MB
After
Row group 25:  count: 2244256  26.34 B records  start: 1479178837  total(compressed): 56.370 MB total(uncompressed):167.418 MB
```markdown
```
> Fix reporting of row group size by parquet writer

- core/trino-main/src/main/java/io/trino/util/DateTimeUtils.java
- core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
> Remove unused methods and code

- plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotConnectorSmokeTest.java
> Correct illegal import from shaded code

- plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
- plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorTest.java
> Fix TestRedshiftConnectorTest and deny adding not columns explicitly

- .github/workflows/ci.yml
- plugin/trino-oracle/pom.xml
- plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleFailureRecoveryTest.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/OracleQueryRunner.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleQueryFailureRecoveryTest.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleTaskFailureRecoveryTest.java
Fixes https://github.com/trinodb/trino/issues/17199
```markdown
* Add support for writes when [fault-tolerant
execution](/admin/fault-tolerant-execution) is enabled. ({issue}`17200`)
```
> Add support for Oracle fault tolerant execution

- docs/src/main/sphinx/admin/fault-tolerant-execution.rst
- docs/src/main/sphinx/connector/oracle.rst
> Document fault tolerant execution for Oracle connector

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetastoreClosure.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/ForwardingHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/alluxio/AlluxioHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/SharedHiveMetastoreCache.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/recording/HiveMetastoreRecording.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/recording/RecordingHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/DefaultThriftMetastoreClientFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/FailureAwareThriftMetastoreClient.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreClient.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/CountingAccessHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/UnimplementedHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/InMemoryThriftMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/MockThriftMetastoreClient.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestHiveMetastoreMetadataQueriesAccessOperations.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftHiveMetastoreClient.java
This PR replaces https://github.com/trinodb/trino/pull/16847 but drops last commits because of a regression - I will try to reintroduce that with a fix in separate PR.
```markdown
```
> Fetch all table/view names across schemas with one Hive metastore call (when Hive views enabled)

- client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcConnection.java
- plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/s3select/S3SelectTestHelper.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveLocationService.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSinkProvider.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveWriterFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveLocationService.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java
Users should not have the ability to write files into arbitary locations.
Extracted first commit into https://github.com/trinodb/trino/pull/17389
```markdown
* Remove session property overrides for `temporary-staging-directory-enabled` and `temporary-staging-directory-path`
```
> Remove session property overrides for Hive staging location

- docs/src/main/sphinx/connector/hudi.rst
- plugin/trino-hudi/pom.xml
- pom.xml
Upgrade Hudi version to 0.12.3
> Upgrade Hudi version to 0.12.3

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableHandle.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMetadata.java
It's a collection of Delta column handles.
> Fix type of DeltaLakeTableHandle.projectedColumns

- core/docker/build.sh
This reverts commit c68b03011300b33d97e7ed0c3c71f0e4993d751e.
The Docker build script in `core/docker` should be standalone and not depend on `.github/bin` which is intended for CI usage.
> Revert "Retry docker build"

- docs/src/main/sphinx/connector/hive.rst
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriterOptions.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/session/PropertyMetadataUtil.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDelete.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePreferredPartitioning.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeUpdate.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetWriterConfig.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestParquetPageSkipping.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkippingWithOptimizedReader.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetWriterConfig.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveSparkCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
```markdown
* Enable the optimized Parquet writer by default. This can be disabled using
the `parquet.optimized-writer.enabled` configuration property or
the `parquet_optimized_writer_enabled` session property. ({issue}`17393`)
```
> Enable Hive optimized Parquet writer by default

- core/trino-main/src/main/java/io/trino/type/DateTimes.java
When the number of nanoseconds in the current instant is such that it needs to round up to the nearest millisecond, the calculation doesn't properly compute the carryover.
```markdown
* Fix failure when invoking `current_timestamp`. ({issue}`17455`)
```
> Fix current_timestamp failure due to improper rounding

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/FileBasedTableStatisticsProvider.java
Follow up of https://github.com/trinodb/trino/pull/17085#discussion_r1189871261
> Ensure statistics predicate only for base column in delta connector

- .github/workflows/ci.yml
We observed CI instability with 20. We should reintroduce testing with 20 in a way that doesn't break the CI builds.
Motivation / context: https://github.com/trinodb/trino/issues/16933#issuecomment-1546718406
stress test on the CI with further evidence: https://github.com/trinodb/trino/pull/17490
Hopefully fixes https://github.com/trinodb/trino/issues/16987
Hopefully fixes https://github.com/trinodb/trino/issues/16933
> Put testing with with JDK 20 on hold

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/HistoryTable.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
In the current version of Iceberg library, when not all the snapshots are initially loaded (for the REST session catalog), the `snapshotsLog` does not get reinitialized, causing to expose only the current snapshots in the `history()` method of the Iceberg table.
Related Iceberg code
https://github.com/apache/iceberg/blob/8865be48bcb20ce07972bf5176955d03a1347d27/core/src/main/java/org/apache/iceberg/TableMetadata.java#L497-L516
```markdown
```
> Fix Iceberg $history table when using REST Catalog

- docs/src/main/sphinx/connector/delta-lake.rst
Avoid confusion for users trying to use the properties as global config or session properties.
User report from Starburst customer.
> Clarify catalog property usage in Delta Lake docs

- docs/src/main/sphinx/connector/hive.rst
- plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/s3select/S3SelectTestHelper.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/TransactionDirectoryListingCacheKey.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/TransactionScopeCachingDirectoryLister.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/TransactionScopeCachingDirectoryListerFactory.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/TestTransactionScopeCachingDirectoryLister.java
This allows to cap cache size independently of query concurrency.
This will be added to exiting RN (if it lands in this Trino version) or new RN will be created
> Use shared cache for per transaction file listing cache

- core/trino-main/src/main/java/io/trino/memory/LeastWastedEffortTaskLowMemoryKiller.java
- core/trino-main/src/main/java/io/trino/memory/TotalReservationOnBlockedNodesTaskLowMemoryKiller.java
- core/trino-main/src/test/java/io/trino/memory/TestLeastWastedEffortTaskLowMemoryKiller.java
- core/trino-main/src/test/java/io/trino/memory/TestTotalReservationOnBlockedNodesTaskLowMemoryKiller.java
> Prefer killing speculative tasks

- client/trino-client/src/main/java/io/trino/client/auth/external/CompositeRedirectHandler.java
- client/trino-client/src/main/java/io/trino/client/auth/external/SystemOutPrintRedirectHandler.java
- core/trino-main/src/main/java/io/trino/server/security/HeaderAuthenticator.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/TestBinPackingNodeAllocator.java
- docs/pom.xml
- lib/trino-hdfs/src/test/java/io/trino/hdfs/TestFileSystemCache.java
- lib/trino-phoenix5-patched/src/main/java/org/apache/phoenix/shaded/org/apache/zookeeper/client/StaticHostProvider.java
- plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeStorage.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMergeAppend.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestIcebergHiveMetastoreTableOperationsReleaseLockFailure.java
- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduClientWrapper.java
- pom.xml
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentDescribe.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/kudu/TestKuduConnectoKerberosSmokeTest.java
This brings following improvements:
* Replace checkstyle illegal imports with `RestrictImports` enforcer rules
* Checkstyle updates:
- Require throws keyword to be on a new line.
* Dependency updates:
- JUnit 5.9.3 (from 5.9.2)
- Kotlin 1.8.21 (from 1.8.20)
- Opentelemetry 1.26.0 (from 1.25.0)
- Opentelemetry Instrumentation 1.25.1 (from 1.24.0)
- Logback 1.4.7 (from 1.4.6)
- Checkstyle 10.11.0 (from 10.9.3)
- Guice 6.0.0 (from 5.1.0)
* Plugin updates:
- Surefire 3.1.0 (from 3.0.0)
- maven-clean-plugin 3.2.0 (from 3.0.0)
- maven-install-plugin 3.1.1 (from 2.5.2)
- maven-enforcer-plugin 3.3.0 (from 3.2.1)
- maven-resources-plugin 3.3.1 (from 3.2.0)
- maven-assembly-plugin 3.5.0 (from 3.3.0)
- maven-javadoc-plugin 3.5.0 (from 3.2.0)
- maven-jar-plugin 3.3.0 (from 3.2.0)
- migrate to …
> Update airbase to 139

- core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java
Trino deployments on ARM are common enough that it shouldn't be considered experimental anymore
> Remove warning about experimental ARM support

- client/trino-jdbc/pom.xml
- plugin/trino-oracle/pom.xml
- plugin/trino-resource-group-managers/pom.xml
Could also update to 23.2.0.0 but that is a "Developer release"
Our required runtime is Java 17 .. we should at least use the JDBC driver for Java 11/17 .. not the one for Java 8/11.
Fixes https://github.com/trinodb/trino/issues/6714
> Update to Java 11/17 Oracle JDBC driver

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeCdfPageSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSinkProvider.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeParquetSchemaMapping.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeParquetSchemas.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeParquetSchemas.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
This PR is a follow-up of https://github.com/trinodb/trino/pull/16183 and relates to https://github.com/trinodb/trino/issues/12638
https://books.japila.pl/delta-lake-internals/DeltaConfigs/#COLUMN_MAPPING_MODE
id | A column ID is the identifier of a column. This mode is used for tables converted from Iceberg and parquet files in this mode will also have corresponding field Ids for each column in their file schema.
-- | --
I intended to test this column mapping mode for tables migrated from Iceberg and used
https://docs.databricks.com/sql/language-manual/delta-convert-to-delta.html
Apply `CLONE` on an Iceberg table created by Trino was causing internal error issues on Databricks, so I used Spark with Iceberg to create the table on AWS and then applied `CLONE` via Databricks.
```
CREATE OR …
```
> Support DML operations on Delta Lake tables with `id` column mapping

- lib/trino-hdfs/src/main/java/io/trino/hdfs/s3/TrinoS3FileSystem.java
Fixes #16546
```markdown
* Fix query failure for S3 objects with empty `Content-Type` header. ({issue}`16546`)
```
> Handle parsing of invalid S3 content type

- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
- plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
This is in response to https://github.com/trinodb/trino/issues/16277
The issue appears to be due to Oracle's recycling bin, which holds onto dropped tables for a period of time.
This has caused issues in our BaseFailureRecoveryTest, which expects there to be no remaining temporary tables after each test case. The solution implemented here is to `PURGE` trino's temporary tables (`tmp_trino_*`), which bypasses the recycling bin, dropping the table immediately.
We _could_ `PURGE` all dropped tables, but this code path is also used when an end user explicitly drops one of their own tables, so that may be unexpected behavior. …
> Oracle purges dropped temp tables

- core/trino-main/src/main/java/io/trino/execution/scheduler/BinPackingNodeAllocatorService.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/NodeAllocator.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/TestBinPackingNodeAllocator.java
> Prioritize non-speculative tasks in scheduler and node allocator

- plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
Fix https://github.com/trinodb/trino/issues/16671
> Fix Ignite schema change operation tests failure

- core/trino-main/src/main/java/io/trino/execution/QueryPreparer.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- core/trino-main/src/test/java/io/trino/execution/TestQueryPreparer.java
- core/trino-main/src/test/java/io/trino/sql/query/TestExecuteImmediate.java
- core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
- core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
- core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
- core/trino-parser/src/main/java/io/trino/sql/parser/SqlParser.java
- core/trino-parser/src/main/java/io/trino/sql/tree/AstVisitor.java
- core/trino-parser/src/main/java/io/trino/sql/tree/ExecuteImmediate.java
- core/trino-parser/src/test/java/io/trino/sql/TestSqlFormatter.java
- core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/jdbc/TestPreparedStatements.java
- testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java
Fixes #17353 
Syntax:
```
EXECUTE IMMEDIATE
'SELECT * FROM t WHERE a = ? and b = ?'
USING 'foo', 42
```
The semantics are the same as:
```
PREPARE stmt1 FROM SELECT * FROM t WHERE a = ? and b = ?
EXECUTE stmt1 USING 'foo', 42
DEALLOCATE PREPARE stmt1
```
```markdown
```
> Add support for EXECUTE IMMEDIATE statement

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesSplitSource.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/CdcEntry.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeTransactionLogEntry.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogWriter.java
> Rename CdfFileEntry to CdcEntry

- core/docker/Dockerfile
This speeds up the build significantly and makes the CI more reliable.
Fixes #17512
> Use jvmkill Docker image when building Trino image

- .gitignore
It is generated by maven-shade-plugin and it shouldn't be checked into the repository
> Add dependency-reduced-pom.xml files to .gitignore

- pom.xml
https://github.com/trinodb/trino/pull/17484 switched git-commit-id plugin to new coordinates but the configuration in the parent pom wasn't updated properly.
> Fix improper maven plugin configuration

- core/trino-main/src/main/java/io/trino/operator/TrinoOperatorFactories.java
- core/trino-main/src/main/java/io/trino/operator/join/JoinOperatorInfo.java
- core/trino-main/src/main/java/io/trino/operator/join/JoinStatisticsCounter.java
- core/trino-main/src/main/java/io/trino/operator/join/unspilled/JoinProbe.java
- core/trino-main/src/main/java/io/trino/operator/join/unspilled/LookupJoinPageBuilder.java
- core/trino-main/src/main/java/io/trino/operator/join/unspilled/PageJoiner.java
- core/trino-main/src/test/java/io/trino/operator/join/TestJoinOperatorInfo.java
- core/trino-main/src/test/java/io/trino/operator/join/unspilled/TestHashJoinOperator.java
- core/trino-main/src/test/java/io/trino/operator/join/unspilled/TestLookupJoinPageBuilder.java
JoinProbe will now perform only a single row join when parsing an RLE page
Optimize joins performance for RLE pages.
```markdown
* Improve performance of joins on partitioned columns. ({issue}`14493`)
```
> Support RLE Pages in JoinProbe

- docs/src/main/sphinx/connector/hive.rst
> Fix typo in Hive docs

- docs/src/main/sphinx/release.rst
- docs/src/main/sphinx/release/release-418.md
- docs/src/main/sphinx/sql/deallocate-prepare.rst
Assemble the release notes for the upcoming Trino 418 release. Fixes #17450 
* #17425 ✅ rn ✅ docs
* #17445 ✅ rn ✅ docs
* #17448 ✅ rn ✅ docs
* #17443 ✅ rn ✅ docs
* #17441 ✅ rn ✅ docs
* #17381 ✅ rn ✅ docs
* #17200 ✅ rn ✅ docs
* #17456 ✅ rn ✅ docs
* #17318 ✅ rn ✅ docs
* #17442 ✅ rn ✅ docs
* #17332 ✅ rn ✅ docs
* #17431 ✅ rn ✅ docs
* #17347 ✅ rn ✅ docs
* #17127 
* #17469 ✅ rn ✅ docs
* #16205 ✅ rn ❌ docs
* #17409 ✅ rn ✅ docs
* #17390 ✅ rn ✅ docs
* #17222 …
> Add Trino 418 release notes

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsReader.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsWriter.java
The goal of this change is to improve performance of reading stats, also older stats files may have skewed data which is not optimal for CBO.  
```markdown
* Use only latest puffin file for statistics. ({issue}`issuenumber`)
```
> Use only latest Puffin files for Iceberg stats

- pom.xml
This version includes some relevant bug-fixes, see release notes at https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15.1 particularly the ones about deserialization issues and interaction with Java records.
Follow-up to https://github.com/trinodb/trino/commit/c4d1a2deaa65c55d30422ec33cf4ed1174fc4afc
> Update jackson to 2.15.1

- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduRecordCursor.java
Sometimes happens that we got 
```
Caused by: java.lang.NullPointerException
at org.apache.kudu.shaded.com.google.protobuf.ByteString$LiteralByteString.<init>(ByteString.java:1315)
at org.apache.kudu.shaded.com.google.protobuf.ByteString.wrap(ByteString.java:391)
at org.apache.kudu.shaded.com.google.protobuf.UnsafeByteOperations.unsafeWrap(UnsafeByteOperations.java:75)
at org.apache.kudu.client.AsyncKuduScanner$ScanRequest.createRequestPB(AsyncKuduScanner.java:1137)
at org.apache.kudu.client.RpcProxy.rpcToMessage(RpcProxy.java:199)
at org.apache.kudu.client.RpcProxy.sendRpc(RpcProxy.java:153)
at org.apache.kudu.client.AsyncKuduClient.closeScanner(AsyncKuduClient.java:1252)
at org.apache.kudu.client.AsyncKuduScanner.close(AsyncKuduScanner.java:747)
... 17 more
```
During scanner close,
as …
> Attempt to close kudu scanner only one time

- .github/workflows/ci.yml
- lib/trino-hdfs/pom.xml
- lib/trino-hdfs/src/test/java/io/trino/hdfs/TestFSDataInputStreamTail.java
- lib/trino-hdfs/src/test/java/io/trino/hdfs/TestFileSystemCache.java
`TrinoFileSystemCache` holds the global cache of filesystem objects within a running server. `TestFileSystemCache` expects that this singleton instance is available to itself and validates the number of entries in the cache accordingly. This is not a valid assumption as other threads running concurrently in the same JVM can add and delete filesystem objects in `TrinoFileSystemCache`. To avoid this interference between `TestFileSystemCache` and other threads running in the same JVM, we move the former to run in a separate runner instance in CI. This should avoid the flakiness reported in https://github.com/trinodb/trino/issues/17158
Fixes https://github.com/trinodb/trino/issues/17158 …
> Isolate TestFileSystemCache to fix its flakiness

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java
Coral may throw AssertionError internally
Fixes #17568
> Catch Throwable when Coral failed to convert views

- core/trino-main/src/main/java/io/trino/metadata/PolymorphicScalarFunction.java
- core/trino-main/src/main/java/io/trino/sql/gen/JoinCompiler.java
- core/trino-main/src/main/java/io/trino/type/BlockTypeOperators.java
- core/trino-main/src/test/java/io/trino/type/AbstractTestType.java
- core/trino-spi/src/main/java/io/trino/spi/function/InvocationConvention.java
- core/trino-spi/src/main/java/io/trino/spi/function/ScalarFunctionAdapter.java
- core/trino-spi/src/main/java/io/trino/spi/predicate/EquatableValueSet.java
- core/trino-spi/src/main/java/io/trino/spi/predicate/NullableValue.java
- core/trino-spi/src/main/java/io/trino/spi/predicate/SortedRangeSet.java
- core/trino-spi/src/test/java/io/trino/spi/function/TestScalarFunctionAdapter.java
PagesHashStrategy#positionEqualsPositionIgnoreNulls can avoid the overhead of ValueConversions.boxBoolean for primitive types.
This PR introduces a new DEFAULT_ON_NULL method return convention which is used to create an adapted equals method handle where equals methods with nullable return value are adapted to return `false` on java `null` and equals methods with primitive return value are used without adaptation.
> Avoid boxing booleans for equals on primitive types

- testing/trino-product-tests-launcher/pom.xml
Disable creation of reduced pom during shading
Maven-shade-plugin after
https://issues.apache.org/jira/browse/MSHADE-321 by default creates
reduced pom. So all dependencies are removed. This works well when you
want when you only provide shaded binary as the target artifact.
Here we use shading to generate executable jar, and still we would like to
provide regular jar artifact so it can be used as a library. In library
case reduced pom is undesired.
> Disable creation of reduced pom during shading

- core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
Currently, `AccumulatorFactory` instances are flushed after one hour has elapsed. It can cause a lot of deoptimzation as an side effect. We observie it in benchmarks (that takes more one hour). Anyway, user's queries (repeated, dashboard queries) can experiance same issue.  
(*) This is not user-visible or docs only and no release notes are required.
> Cache AccumulatorFactory instances basing on last access time

- .github/workflows/ci.yml
The checks for secrets presence are there for the benefit of forks,
otherwise we would just check for PR vs push and PR source branch. As a
result, however, the checks are error-prone -- lack of a secret may be
unintentional, e.g. result of a secret name typo. This change adds
another secret, CI_SKIP_SECRETS_PRESENCE_CHECKS, that would trigger all
jobs requiring secrets. Anyone willing to attempt really all tests
should define that new secret to a non-empty value.
> Make it easy to run all secrets-requiring tests

- lib/trino-hdfs/src/main/java/io/trino/hdfs/TrinoFileSystemCache.java
Add wrapper around RemoteIterarator obtained from
FileSystemWrapper.listFiles. Using wrapper ensures that there is strong referenct to FileSystemWrapper object while RemoteIterarator is in use. Otherwise it was possible that FileSystemWrapper and underlying FileSystem were garbage collected in the meantime which rendered RemoteIterarator unusable.
In case of TrinoS3FileSystem it manifested itself in closed http pool deep down the stack.
Thanks to @findepi for helping understanding what is the root cause of the problem.
```markdown
* Fix bug where spurious query failures could …
```
> Ensure FileSystem not GCed while RemoteIterator in use

- .github/workflows/ci.yml
The commit in https://github.com/trinodb/trino/pull/17539 broke ci.yml.
This reverts commit 437486ae12d3855ad99652621ea5a7a723f4807a.
> Revert "Make it easy to run all secrets-requiring tests"

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
It seems Databricks 12.2 changed the behavior recently. 
https://github.com/trinodb/trino/actions/runs/5028373638/jobs/9019175717
```
tests               | 2023-05-20 03:45:33 INFO: FAILURE     /    io.trino.tests.product.deltalake.TestDeltaLakeAlterTableCompatibility.testIdentityColumn (Groups: profile_specific_tests, delta-lake-exclude-91, delta-lake-databricks, delta-lake-exclude-73) took 15.8 seconds
tests               | 2023-05-20 03:45:33 SEVERE: Failure cause:
tests               | java.lang.AssertionError: Could not find rows:
tests               | [0, 2]
tests               | 
tests               | actual rows:
tests               | [0, 1]
```
> Fix testIdentityColumn in Delta Lake product tests

- core/trino-main/src/main/java/io/trino/metadata/SystemFunctionBundle.java
- core/trino-main/src/main/java/io/trino/operator/aggregation/histogram/SingleTypedHistogram.java
- core/trino-main/src/main/java/io/trino/operator/scalar/ArrayHistogramFunction.java
- core/trino-main/src/test/java/io/trino/operator/aggregation/TestTypedHistogram.java
- core/trino-main/src/test/java/io/trino/operator/scalar/TestArrayHistogramFunction.java
- docs/src/main/sphinx/functions/array.rst
Adds the `array_histogram` function along with tests and documentation for it.
Fixes https://github.com/trinodb/trino/issues/14725
The `array_histogram` function was requested in [issue 14725](https://github.com/trinodb/trino/issues/14725). `martint` suggested the name `array_histogram` to make it consistent with the existing `histogram` function. I've implemented this as a scalar function with the behavior shown below (the input to the function is an array and the output is a map, nulls are ignored).
```sql
SELECT array_histogram(a) FROM (VALUES (ARRAY[1, 2, 1]), (ARRAY[42, 7, 42, null])) t(a);
_col0
-------------
{1=2, 2=1}
{42=2, 7=1}
```
This is my first attempt to contribute to Trino (got the CLA confirmation email and org invite yesterday), feedback is very welcome and I will …
> Add the `array_histogram` operator

- docs/src/main/sphinx/admin/properties-write-partitioning.rst
* Removes `preferred-write-partitioning-min-number-of-partitions` from properties reference.
* Removes reference to defunct property in description of `use-preferred-write-partitioning`.
* This commit removed the property in Trino 416 release: https://github.com/trinodb/trino/pull/16802/commits/f6a8eb2ded4155d3457bea1a78844099860656de
```markdown
```
> Remove defunct write partitioning property

- plugin/trino-base-jdbc/pom.xml
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseCaseInsensitiveMappingTest.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/MetadataUtil.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestBaseJdbcConfig.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcMetadata.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcQueryBuilder.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcClient.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcDynamicFilteringSplitManager.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcRecordSet.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcRecordSetProvider.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcSplit.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcTableProperties.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJmxStats.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestRemoteTableName.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestRetryingConnectionFactory.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/credential/TestCredentialProvider.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/credential/TestExtraCredentialProvider.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/expression/TestExpressionMappingParser.java
This was achieved with the https://github.com/PicnicSupermarket/error-prone-support TestNGToAssertJRules rules and IntelliJ's optimize imports (refaster leaves behind unused imports).
The only manual change was the fix `assertEquals` in one of the files that weren't refactored automatically.
```markdown
```
> Migrate trino-base-jdbc to AssertJ

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMigrateProcedure.java
Set default file format in Iceberg migrate procedure.
Otherwise, the mgirated tables' table definition always shows `format = 'PARQUET'`
> Set default file format in Iceberg migrate procedure

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMigrateProcedure.java
Deny array, map and row types in Iceberg migrate procedure to avoid correctness issue #17583.
```markdown
* Disallow migrating Hive tables with `array`, `map` and `row` types. 
Previously, it returned incorrect results after the migration. ({issue}`17587`)
```
> Deny array, map and row types in Iceberg migrate procedure

- lib/trino-hdfs/src/main/java/io/trino/hdfs/s3/TrinoS3FileSystem.java
- lib/trino-hdfs/src/test/java/io/trino/hdfs/TestFSDataInputStreamTail.java
- lib/trino-hdfs/src/test/java/io/trino/hdfs/s3/TestTrinoS3FileSystem.java
This commit migrates trino-hdfs off `@Test(expectedExceptions`, which revealed `TrinoS3FileSystem.close` problem, where the method fails if the instance hasn't been correctly initialized.
> Fix TrinoS3FileSystem.close when initialization fails

- lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/IntBitUnpackers.java
- lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ShortDecimalFixedWidthByteArrayBatchDecoder.java
```
Benchmark                                                 (bitWidth)  (dataSet)   Mode  Cnt      Before score       After score  Units
BenchmarkRleBitPackingDecoder.rleBitPackingHybridDecoder           1     RANDOM  thrpt   10  427.729 ±  8.350  419.174 ±  6.382  ops/s
BenchmarkRleBitPackingDecoder.rleBitPackingHybridDecoder           2     RANDOM  thrpt   10  410.621 ± 11.578  436.604 ±  8.031  ops/s
BenchmarkRleBitPackingDecoder.rleBitPackingHybridDecoder           4     RANDOM  thrpt   10  288.063 ±  3.352  475.684 ± 14.693  ops/s
BenchmarkRleBitPackingDecoder.rleBitPackingHybridDecoder           8     RANDOM  thrpt   10  327.834 ±  4.273  560.916 ± 12.079  ops/s
Benchmark                               (byteArrayLength)  (encoding)   Mode  Cnt      Before score        After score …
```
> Improve integer and short decimal decoders in parquet

- core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java
An exception wasn't thrown until today because of rule ordering. For example, `double NaN` can't be cast to `smallint`. Given the query `SELECT * FROM (VALUES SMALLINT '1') t(a) WHERE a IS DISTINCT FROM nan()`, the filter's predicate is replaced with `TRUE` by
`UnwrapCastInComparison.FilterExpressionRewrite` before hitting `DomainTranslator`. When manually disabling this rule, a `TrinoException` with the message `Unable to cast double NaN to smallint` is thrown by `DoubleOperators#saturatedFloorCastToLong`.
Blocking https://github.com/trinodb/trino/pull/16206
> Add error handling for saturated floor cast

- core/trino-main/src/main/java/io/trino/sql/planner/EffectivePredicateExtractor.java
- core/trino-main/src/main/java/io/trino/sql/planner/EqualityInference.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ReorderJoins.java
- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestEffectivePredicateExtractor.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestEqualityInference.java
Extracting symbols and subexpressions from expression is a relatively expensive operation. `CachingSymbolExtractor` and `CachingSubExpressionExtractor` were added to memoize result for this operations.
This is `Method Profile` for master
There is a lot of top methods related to extracting symbols and sub-expressions. 
Results for microbenchmark: `BenchmarkReorderChainedJoins`
```
BenchmarkReorderChainedJoins.benchmarkReorderJoins                 AUTOMATIC  avgt   40  362.936 ? 0.832  ms/op (before)
BenchmarkReorderChainedJoins.benchmarkReorderJoins                 AUTOMATIC  avgt   40  288.576 ? 0.741  ms/op (after)
```
Macrobenchmark results:
5% difference in total tpcds planning time is more or less stable. 
(*) This is not user-visible or docs only and no release notes are required.
( …
> Cache symbols and subexpressions for expression

- docs/src/main/sphinx/connector/delta-lake.rst
Docs changes for https://github.com/trinodb/trino/pull/16205
> Add doc for table_changes function

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetWriterConfig.java
Some tests need the ability to set a small row group size. Using small row group size works, so the validation is not strictly necessary
> Remove PARQUET_WRITER_MIN_BLOCK_SIZE config validation

- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryProxyConfig.java
- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryProxyConfig.java
- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryWithProxyConnectorSmokeTest.java
> Rename BigQueryProxyConfig properties names

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
> Use Location API for path concatenation when cleaning extra output files after DML in Delta

- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcTableProperties.java
- plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/TestBlackHoleSmoke.java
- plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/util/TestCassandraClusteringPredicatesExtractor.java
- testing/trino-testing-services/src/test/java/io/trino/testng/services/TestReportPrivateMethods.java
In some places before-test-method and in some before-class was apparently meant.
`TestReportPrivateMethods`is changed too to limit proliferation of this annotation.
TestNG method invocation order example
```
Test class 1: @BeforeTest
Test class 2: @BeforeTest
Test class 1: @BeforeCass
Test class 1: @BeforeMethod
Test class 1: a test 1
Test class 1: @AfterMethod
Test class 1: @BeforeMethod
Test class 1: a test 2
Test class 1: @AfterMethod
Test class 1: @afterclass
Test class 2: @BeforeCass
Test class 2: @BeforeMethod
Test class 2: a test 1
Test class 2: @AfterMethod
Test class 2: @BeforeMethod
Test class 2: a test 2
Test class 2: @AfterMethod
Test class 2: @afterclass
Test class 1: @AfterTest
Test class 2: @AfterTest
```
> Fix incorrect @BeforeTest usages

- core/trino-main/src/main/java/io/trino/execution/scheduler/HashDistributionSplitAssigner.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/TestHashDistributionSplitAssigner.java
Instead of lazily creating tasks, we create tasks all at once on first assignment of HashDistributionSplitAssigner, and also trigger `setNoMorePartitions` early
Benchmark on tpcds-sf1000: wall time -5.98%, cpu time +2.6%
```markdown
```
> Create tasks all at once on first assignment of HashDistributionSplitAssigner

- core/trino-main/src/main/java/io/trino/server/ui/WebUiAuthenticationModule.java
- core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
Just a quick update to allow uppercase setup as well. Maybe we want to add some test case as well.
Essentially I would also like to standardize for the authentication type to be standardized in the documentation to be either uppercase or lowercase .. is there a preferred choice @martint ?
* Fixes #17334
```markdown
* Allow uppercase or mixed case for `web-ui.authentication.type` ({issue}`17334`)
```
> Allow web ui authentication type in uppercase

- docs/src/main/sphinx/connector/iceberg.rst
- plugin/trino-iceberg/pom.xml
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/IcebergCatalogModule.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieCatalogConfig.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieCatalogModule.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieTableOperations.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieTableOperationsProvider.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieUtil.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/TrinoNessieCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/TrinoNessieCatalogFactory.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestIcebergNessieCatalogConfig.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestIcebergNessieCatalogConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestTrinoNessieCatalog.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteIceberg.java
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-nessie/iceberg.properties
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-nessie/spark-defaults.conf
- testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
This PR integrates the (Nessie catalog functionality)[https://github.com/apache/iceberg/tree/master/nessie/src/main/java/org/apache/iceberg/nessie] to the Iceberg connector. It adds the following new things:
* a new `CatalogType` called `NESSIE`
* an `IcebergNessieCatalogModule` that sets up all necessary dependencies (including a client to connect to the Nessie server)
* a `NessieConfig` that includes configuration settings required for Nessie
* `TrinoNessieCatalog` + `NessieIcebergTableOperations` that implement the main behavior of the catalog
* some unit and integration tests that verify that the Iceberg connector works with Nessie (note that the integration test requires a Nessie server to be started, which is being done via the `nessie-apprunner-maven-plugin`prior to the …
> Support Nessie Catalog in Iceberg connector

- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ArrayColumnWriter.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ColumnChunk.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/MapColumnWriter.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/StructColumnWriter.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/repdef/RepLevelWriterProvider.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/repdef/RepLevelWriterProviders.java
- lib/trino-parquet/src/test/java/io/trino/parquet/ParquetTestUtils.java
- lib/trino-parquet/src/test/java/io/trino/parquet/writer/NullsProvider.java
- lib/trino-parquet/src/test/java/io/trino/parquet/writer/RepLevelIterable.java
- lib/trino-parquet/src/test/java/io/trino/parquet/writer/RepLevelIterables.java
- lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestDefinitionLevelWriter.java
- lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestRepetitionLevelWriter.java
- lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestingValuesWriter.java
Avoid iterators and streams and take advantage of Block#mayHaveNull
when writing repetition levels to improve performance.
BenchmarkHiveFileFormat Before
```
write  MAP_VARCHAR_DOUBLE        NONE  TRINO_OPTIMIZED_PARQUET   98.6MB/s ±  1587.5kB/s ( 1.57%) (N = 20, α = 99.9%)
write  LARGE_MAP_VARCHAR_DOUBLE  NONE  TRINO_OPTIMIZED_PARQUET  121.4MB/s ±   548.9kB/s ( 0.44%) (N = 20, α = 99.9%)
write  MAP_INT_DOUBLE            NONE  TRINO_OPTIMIZED_PARQUET  107.8MB/s ±  1137.4kB/s ( 1.03%) (N = 20, α = 99.9%)
write  LARGE_MAP_INT_DOUBLE      NONE  TRINO_OPTIMIZED_PARQUET  110.1MB/s ±   901.0kB/s ( 0.80%) (N = 20, α = 99.9%)
write  LARGE_ARRAY_VARCHAR       NONE  TRINO_OPTIMIZED_PARQUET   91.7MB/s ±  1004.9kB/s ( 1.07%) (N = 20, α = 99.9%)
```
BenchmarkHiveFileFormat After
```
write …
```
> Optimize writing of repetition levels in parquet writer

- docs/src/main/sphinx/connector/iceberg.rst
Fix confusion about connector name vs catalog name and generally improve the section for clarity.
Need clarification a bit more.. also do we need to warn the user that this might take a while .. or very long depending on table size? Or is this essentially just rejigging metadata and therefore actually fast .. well actually. Even if that the case .. thats potentially a lot of metadata to get from the HMS and pump into the Iceberg metadata files... do we have any experience how long this can take .. for example for a 1GB, 100GB, or 1TB table? 
Any idea here @ebyhr @findinpath @alexjo2144 @findepi 
> Improve migrate procedure docs for Iceberg

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksUpdates.java
Use `containsExactlyInOrder` in `TestDeltaLakeDatabricksUpdates` to avoid deprecated `containsExactly` method. 
> Use `containsExactlyInOrder` in `TestDeltaLakeDatabricksUpdates`

- .github/actions/setup/action.yml
- .github/workflows/docs.yml
- core/docker/Dockerfile
(s) This is not user-visible or docs only and no release notes are required.
> Move CI to use temurin

- core/trino-main/src/main/java/io/trino/operator/scalar/ChoicesSpecializedSqlScalarFunction.java
- core/trino-spi/pom.xml
- core/trino-spi/src/main/java/io/trino/spi/function/InvocationConvention.java
- core/trino-spi/src/main/java/io/trino/spi/function/ScalarFunctionAdapter.java
- core/trino-spi/src/main/java/io/trino/spi/type/TypeOperators.java
- core/trino-spi/src/test/java/io/trino/spi/function/TestScalarFunctionAdapter.java
The `DEFAULT_ON_NULL` return convention should not cause the function to
be invoked when there is a null passed to a never null argument.
Instead, as with `NULLABLE_RETURN`, the invocation should be
short- circuited and the default value should be returned.
Additionally, this PR removed the unused `NullAdaptationPolicy`
```markdown
* Fix adaptation of a function argument from`NEVER_NULL` to a nullable type when using the `DEFAULT_ON_NULL`, to short-circuit the function invocation. ({issue}`issuenumber`)
* Remove unused `NullAdaptationPolicy` from `ScalarFunctionAdapter`. ({issue}`issuenumber`)
```
> Fix DEFAULT_ON_NULL return convention to short circuit on null argument

- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViewsLegacy.java
> Retry Hive view tests on HS2 failure

- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/StaticBigQueryCredentialsSupplier.java
Replaces `com.google.api.client.util.Base64` usage with `java.util.Base64` which seems to be favored throughout the codebase.
```markdown
```
> Remove deprecated google Base64 class usage

- plugin/trino-iceberg/pom.xml
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieCatalogModule.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
- pom.xml
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java
This updates Iceberg from 1.2.1 to 1.3.0 and also updates Nessie to the respective version that Iceberg is using.
Release notes can be found [here](https://iceberg.apache.org/releases/#130-release)
```markdown
```
> Bump Iceberg from 1.2.1 to 1.3.0

- docs/src/main/sphinx/release/release-411.md
Fix 411 release notes for repeated phrases and incorrect verbiage (columns, not rows) in Oracle, PostgreSQL, and Redshift connectors.
> Fix 411 release notes for incorrect issue verbiage, removed repeated phrases

- plugin/trino-bigquery/pom.xml
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryRpcConfig.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/DefaultBigQueryMetadataFactory.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/RetryOptionsConfigurer.java
- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryQueryRunner.java
- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java
- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryRpcConfig.java
`SELECT * FROM information_schema.columns WHERE table_catalog = 'bigquery'` goes from 17s to 3s in my testing (for just a minor number of tables)
`BaseConnectorTest.testSelectInformationSchemaColumns` completes under 45s instead of 2m
```markdown
```
> Improve BigQuery metadata retrieval performance

- client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java
- core/trino-main/src/main/java/io/trino/type/DateTimes.java
- core/trino-main/src/test/java/io/trino/operator/scalar/timestamptz/TestTimestampWithTimeZone.java
This PR is a suggestion to require a space in front of timezone if there is no time information in casting string to timestamp. 
This is because one of special case of "YYYY-MM-DD.*": YYYY-MM-DD-XX is ambiguous. Some of users would use XX as hour, and result is inconsistent behavior: 
- when XX is 01, 02, it would parse it as if it is YYYY-MM-DD at timezone with -01, -02 offset
- when XX is 20, 21, it would throw an error because there is no timezone with -20 or -21 offset
Either case, it would be better not to use 'YYYY-MM-DD-XX' pattern. 
This change is simply require that there is at least one space before timezone if there is no time information
Other options considered but not picked:
- Make HH:mm required while keeping seconds and fraction optional. 
- Reason not to pick: breaks …
> require a space in front of timezone if there is no time information in casting string to timestamp

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/HiveFileIterator.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/TestCachingDirectoryListerRecursiveFilesOnly.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/TestHiveFileIterator.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/BaseTestTrinoS3FileSystemObjectStorage.java
Fixes https://github.com/trinodb/trino/issues/17621
```markdown
* Fix query failure for paths containing special characters. ({issue}`17621`)
```
> Fix decode of URI path

- docs/src/main/sphinx/connector/iceberg.rst
Iceberg connector copy edits and format improvements
> Iceberg connector copy edits and format improvements

- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcWriteConfig.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcWriteConfig.java
Increase max possible value for write.batch-size
In some cases it is desired to have bigger batches.
> Increase max possible value for write.batch-size

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileBasedSecurity.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/S3HiveQueryRunner.java
`hive.security` can be configured just as any other properties.
> Remove redundant configuration in HiveQueryRunner: setSecurity

- plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
This is hopefully the final battle with Oracle to drop our temporary tables correctly, related to https://github.com/trinodb/trino/issues/16277
In my last PR, I forgot about the whole concept of auto commit. The result was the lock we acquired before the drop table was immediately released and had no effect.
```markdown
```
> Oracle turns off auto commit to drop temporary table

- testing/trino-test-jdbc-compatibility-old-driver/pom.xml
The default value of `dep.presto-jdbc-under-test` is hardcoded to the current version. Instead `${project.version}` can be used.
> Refer ${project.version} instead of hardcoded version in trino-test-jdbc-compatibility-old-driver pom.xml

- docs/src/main/sphinx/client/cli.rst
* Updates code example and text for CLI password authentication after setting `TRINO_PASSWORD` environment variable
* Current behavior requires `--password` in CLI code snippet even after setting the `TRINO_PASSWORD` environment variable. If `--password` is not provided, trino CLI will appear to start without CLI prompt for password, but running SQL results in "Error running command: Authentication failed: Authentication required"
* https://github.com/trinodb/trino/issues/17402
```markdown
```
> Correct code example for CLI auth with env variable

- pom.xml
This version includes improvements from versions:
- https://github.com/testcontainers/testcontainers-java/releases/tag/1.18.1
- https://github.com/testcontainers/testcontainers-java/releases/tag/1.18.2
- https://github.com/testcontainers/testcontainers-java/releases/tag/1.18.3
> Update testcontainers to 1.18.3

- core/trino-main/src/main/java/io/trino/FeaturesConfig.java
- core/trino-main/src/main/java/io/trino/execution/SetViewAuthorizationTask.java
- core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
- docs/src/main/sphinx/security/authorization.json
- docs/src/main/sphinx/security/file-system-access-control.rst
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AccessControlRules.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AuthorizationRule.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControlModule.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControlRules.java
- lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedConnectorAccessControlTest.java
- lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedSystemAccessControlTest.java
- lib/trino-plugin-toolkit/src/test/resources/authorization-no-roles.json
- lib/trino-plugin-toolkit/src/test/resources/authorization.json
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop-kerberos/config.properties
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestSqlStandardAccessControlChecks.java
- testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
With this pull request we are going to assume from all pluggable access control to make sure that SET AUTHORIZATION statements are secure to be performed. Previously it was not clear if it is engine or access control responsibility. Hence we had `legacy.allow-set-view-authorization ` config property.
To accomplish that now:
- `hive.security=sql-standard` requires admin role privilege to perform `ALTER ... SET AUTHORIZATION...` statements
- File based access control have now new authorization rules that verify to whom AUTHORIZATION can be set.
Thanks to the above `legacy.allow-set-view-authorization` can be removed.
**Release notes:**
Hive
-  The hive.security=sql-standard` securty requires admin role privilege to perform `ALTER ... SET AUTHORIZATION...` statements
Security:
- Introduce …
> Verify authorization access for SET AUTHORIZATION statements

- core/trino-main/src/main/java/io/trino/operator/aggregation/ArbitraryAggregationFunction.java
- core/trino-main/src/test/java/io/trino/operator/aggregation/TestAnyValueAggregation.java
As defined in SQL 2023.
```markdown
* Add support for any_value aggregation function
```
> Add support for any_value aggregation function

- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPseudoColumn.java
Remove unused method from BigQueryPseudoColumn
> Remove unused method from BigQueryPseudoColumn

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Fix tests for underestimating size of partitioned Glue hive tables introduced by https://github.com/trinodb/trino/pull/17677.
> Fix tests for underestimating size of partitioned Glue hive tables

- core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
If speculative flag for task partition changes while task is already running we need to propagate the information to RemoteTask
> Update speculative flag for running tasks

- core/trino-main/src/main/java/io/trino/execution/scheduler/ArbitraryDistributionSplitAssigner.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/HashDistributionSplitAssigner.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/SingleDistributionSplitAssigner.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/SplitAssigner.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/TestEventDrivenTaskSource.java
Now we create all tasks upfront and we schedule them immediately. This PR changes to only schedule a task when it has actually received non-replicated splits
https://github.com/trinodb/trino/pull/17596
```markdown
```
> Only schedule FTE task if it received non-replicated splits

- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
Running individual test fails if `test` schema is accessed using create table before running the test case which creates `test` schema during document insertion (eg: `testMaps`).
> Create `test` schema explicitly in TestMongoConnectorTest

- docs/src/main/sphinx/language/types.rst
- docs/src/main/sphinx/sql/show-stats.rst
Date and time support was missing. You can verify that some of these at least work with 
```
SHOW STATS FOR tpch.sf1.orders
```
> Improve details in SHOW STATS documentation

- docs/src/main/sphinx/sql.md
- docs/src/main/sphinx/sql/set-path.rst
Trying to document the command that clearly exists .. looking at the parser setup and such. Not clear yet what it is supposed to do and how it works.
The test codebase does not have any useful examples. 
Fixed #17657
> Add documentation for SET PATH

- plugin/trino-bigquery/pom.xml
- plugin/trino-exchange-filesystem/pom.xml
- plugin/trino-pinot/pom.xml
- pom.xml
- testing/trino-benchto-benchmarks/pom.xml
> Ban javax.annotation dependency

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
The default format version for Iceberg tables in the Trino Iceberg connector is now `2`.
> Remove redundant migration to table format version `2`

- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSchemaUrl.java
The test failed in https://github.com/trinodb/trino/actions/runs/5215544242/jobs/9413753076
```
2023-06-08T23:12:25.6411240Z tests | 2023-06-09 04:57:25 INFO: FAILURE / io.trino.tests.product.hive.TestAvroSchemaUrl.testHiveCreatedTable [/user/hive/warehouse/TestAvroSchemaUrl/schemas/original_schema.avsc] (Groups: storage_formats, avro) took 1.7 seconds
2023-06-08T23:12:25.6425792Z tests | 2023-06-09 04:57:25 SEVERE: Failure cause:
2023-06-08T23:12:25.6427078Z tests | io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Error while processing statement: FAILED: Execution Error, return code 1 from org.apache.hadoop.hive.ql.exec.mr.MapRedTask. Error caching map.xml: java.nio.channels.ClosedByInterruptException
2023-06-08T23:12:25.6428750Z tests | at …
```
> Retry test on TestAvroSchemaUrl

- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoIndex.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSource.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoQueryRunner.java
Remove unused code from MongoDB
> Remove unused code from MongoDB

- .github/workflows/ci.yml
This reverts commit dc8d3faac3a3810c82c80fe30712d046b6def184.
The job is not unnecessary since the default profile includes all tests which don't need Redshift - `TestRedshiftConfig`, `TestRedshiftPlugin` etc.
> Revert "Remove unnecessary separate CI job for Redshift"

- plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
Create test table with remote executor should use `PhoenixTestTable` instead, current the tests work because all the inputs row is empty, once the rows is not empty, the test would (potentially) broken. 
> Fix Phoenix create test table with remote executor error

- core/trino-server-rpm/pom.xml
The configuration uses a legacy option, which results in the following warning:
[WARNING]    * Mojo license:check (com.mycila.maven.plugin.license.LicenseCheckMojo)
[WARNING]      - Parameter 'legacyConfigExcludes' (user property 'license.excludes') is deprecated: use LicenseSet.excludes
> Fix deprecation warning for license checker plugin

- core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
- core/trino-main/src/main/java/io/trino/sql/relational/optimizer/ExpressionOptimizer.java
* `MetadataManager#getFunctionMetadata` fails on worker nodes when `resolvedFunction` is not in the system function namespace.
* Since `deterministic` is carried in `ResolvedFunction`, we can use that instead
* Related to #17644 
> Use ResolvedFunction#isDeterministic

- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeOss.java
This PR reduces log size from 75.3M to 4.6M.
> Reduce Spark log in Delta Lake OSS product tests

- core/trino-main/src/main/java/io/trino/operator/ScanFilterAndProjectOperator.java
- core/trino-main/src/main/java/io/trino/operator/TableScanOperator.java
- core/trino-main/src/main/java/io/trino/operator/WorkProcessorPipelineSourceOperator.java
- core/trino-main/src/main/java/io/trino/operator/WorkProcessorSourceOperatorAdapter.java
- core/trino-main/src/main/java/io/trino/operator/WorkProcessorSourceOperatorFactory.java
- core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorPipelineSourceOperator.java
- core/trino-main/src/test/java/io/trino/operator/TestWorkProcessorSourceOperatorAdapter.java
Since `WorkProcessorSourceOperator` is only used in the context of an operator, it seems feasible to pass `OperatorContext` to its factory.
```markdown
```
> Add OperatorContext to WorkProcessorSourceOperatorFactory.create

- docs/src/main/sphinx/security/file-system-access-control.rst
A small PR to fix formatting issue for an example file in file-based access control.
The example for `security.config-file` should be a valid JSON file.
```markdown
```
> fix JSON formatting issue in file-based access control docs

- core/trino-main/src/main/java/io/trino/operator/output/RleAwarePositionsAppender.java
- core/trino-main/src/main/java/io/trino/operator/output/UnnestingPositionsAppender.java
`DictionaryBlock.dictionary` will not be RLE in normal circumstances,
but since there is no precondition in the constructor, we cannot
rely on this to be always the case
Fixes https://github.com/trinodb/trino/issues/17861
```markdown
* Fix query failure due to an exception from PartitionedOutputOperator. ({issue}`17861`)
```
> Support RLE DictionaryBlock.dictionary in UnnestingPositionsAppender

- core/trino-main/src/main/java/io/trino/execution/scheduler/ArbitraryDistributionSplitAssigner.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/TestArbitraryDistributionSplitAssigner.java
With growth factor 1.2:
sequence: 512MB, 614.4MB, 737.28MB, 884.736MB, 1061.6832MB
Previous: 512MB, 1024MB, 1536MB, 2048MB, 2560MB
With the change: 512MB, 512MB, 512MB, 1024MB, 1024MB
With some adjustments, sf1000 stays mostly unchanged, sf100 improved wall time around 3.6%
https://github.com/trinodb/trino/pull/16719/commits/4561f0cc8d76e614ddf75f8d7f21bc4946d90775
```markdown
```
> Round targetPartitionSizeInBytes to a multiple of minTargetPartitionSizeInBytes

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
Older version of HMS are more permissive in terms of names allowed for schemas/tables. Disallow directly in Trino object names that may eventually cause inaccuracies in the location of the schema/table saved in HMS.
```markdown
```
> Disallow the usage of invalid object names in HMS

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
`IcebergSplitSource` could fail with `Split source must be finished before TableExecuteSplitsInfo is read` in the following scenario
- `getNextBatch` called, initializing `fileScanIterator` and `fileTasksIterator`, but not consuming them fully
- dynamic filters completes
- `getNextBatch` called, crossing dynamic filter with table predicate, concluding it's none, calling `finish()` and returning NO_MORE_SPLITS_BATCH (signalling the source is finished)
- `getTableExecuteSplitsInfo` is called by `SourcePartitionedScheduler`. The invocation fails because `isFinished` returns false, as `fileTasksIterator` isn't consumed.
> Fix Iceberg scheduling failure due to dynamic filters

- docs/src/main/sphinx/connector/delta-lake.rst
> Place `Updating data` section on the same level as `Procedures` section

- docs/src/main/sphinx/functions/aggregate.rst
- docs/src/main/sphinx/functions/list-by-topic.rst
- docs/src/main/sphinx/functions/list.rst
I tested the example query with a build of 420-SNAPSHOT. 
* Adds documentation for #17777
Ensure the release notes entry for the linked ticket is modified to link to the function docs added here.
> Add docs for any_value aggregation function

- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
Add support for RENAME COLUMN in MongoDB
```markdown
* Add support for `RENAME COLUMN`. ({issue}`17874`)
```
> Add support for RENAME COLUMN in MongoDB

- docs/src/main/sphinx/admin/properties-web-interface.rst
- docs/src/main/sphinx/admin/web-interface.rst
Update documentation to use uppercase for authentication types for web ui to be consistent with other authentication types. This was implemented to work in the linked ticket and should only be merged after a release was cut as agreed with @electrum and @Praveen2112 .
Not sure if we should update any of the tests. Wdyt?
Follow up to #17360 
> Use uppercase for web ui authentication types in docs

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/TrinoViewHiveMetastore.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java
Support view column comments for DeltaLake
This closes #17773
```markdown
* Add support for commenting on view columns ({issue}`17773`)
```
> Support view column comments for DeltaLake

- docs/src/main/sphinx/connector/delta-lake.rst
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AnalyzeHandle.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeAnalyzeProperties.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAnalyze.java
fixes: https://github.com/trinodb/trino/issues/15968 
```markdown
* Add support for recalculating all statistics in `ANALYZE` statement. ({issue}`15968`)
```
> Allow forcing delta lake to recalculate all statistics

- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleFailureRecoveryTest.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
We have been [fighting](https://github.com/trinodb/trino/issues/16277) with Oracle FailureRecovery tests, so until we identify the solution, we have decided to mark this test as flaky.
```markdown
```
> Mark Oracle FailureRecovery tests as flaky

- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryFailureRecoveryTest.java
These tests sometimes face transient issue of BigQuery during CTAS setup.
We could reuse `TestingConnectorBehavior`, but choosing simple approach in this PR. 
Fixes #16803
> Skip unsupported tests in BaseBigQueryFailureRecoveryTest

- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentDescribe.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentList.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/Launcher.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/SuiteDescribe.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/SuiteList.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Environment.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentOptions.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/jdk/TarDownloadingJdkProvider.java
- testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/cli/TestInvocations.java
Replaces https://github.com/trinodb/trino/pull/17873
> Test product tests launcher

- docs/README.md
* https://github.com/trinodb/trino/pull/17778
> Add info about docs container

- docs/src/main/sphinx/installation/kubernetes.rst
Fixing a few typos and errors in the kubernetes documentation.
```markdown
```
> Fix kubernetes doc typos

- lib/trino-filesystem/src/main/java/io/trino/filesystem/Location.java
- lib/trino-filesystem/src/main/java/io/trino/filesystem/Locations.java
- lib/trino-filesystem/src/test/java/io/trino/filesystem/TestLocations.java
- lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsFileIterator.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/DirectoryListingFilter.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
In case that a user decides to dedicate an S3 bucket for a Hive table, this PR adds the required handling to support reading from such a table.
```
CREATE TABLE myhivetable (c integer) WITH (external_location='s3://myhivetable/');
```
The hadoop  `Path` corresponding to 's3://myhivetable/' has the string representation `'s3://myhivetable/'`.
The hadoop `Path` corresponding to `'s3://myhivetable/somedir/' has the string representation `'s3://myhivetable/somedir' (note that in this case the `/` at the end of the string representation is not present).
Specific handling has to be done in such a case to find the data files at the top level of the bucket.
Not present in the tests provided with this PR, but still a valid scenario is the usage of `hive.recursive-directories=true` hive setting. …
> Fix reading from Hive table with location being S3 bucket itself

- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/LauncherModule.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentDescribe.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentList.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentUp.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/Launcher.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/LauncherCommand.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/SuiteDescribe.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/SuiteList.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/SuiteRun.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/TestRun.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Environment.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentFactory.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentProvider.java
- testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/cli/TestInvocations.java
This is required because using `System.out` will result in output being intercepted by the `io.airlift.log.Logging#rewireStdStreams`
> Pass and use provided OutputStream in every Launcher command

- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaConnectorFactory.java
- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaConnectorModule.java
- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/encoder/protobuf/ProtobufSchemaParser.java
- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentModule.java
- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ForwardingSchemaParser.java
- plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestForwardingSchemaParser.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Kafka.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeConfluentKafka.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteKafka.java
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-kafka-confluent-license/kafka.properties
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-kafka-confluent-license/kafka_schema_registry.properties
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-kafka-confluent-license/tempto-configuration.yaml
- testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/kafka/TestKafkaAvroReadsSmokeTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/kafka/TestKafkaProtobufReadsSmokeTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/kafka/TestKafkaProtobufWritesSmokeTest.java
Fixes https://github.com/trinodb/trino/issues/17299
Add product tests for Kafka connector with Confluent licensed libraries
The older approach was to copy the Confluent licensed libraries to the
Kafka connector classpath for all product environments extending from
`Kafka`. This meant that it was not possible to detect changes which
introduce a hard-dependency on the Confluent licensed libraries for
Kafka connector startup.
02cc332319a00e8fec5096921f96cb9e0aceacc1 inadvertently made it so that
the Confluent libraries became required for the Kafka connector to start
up and was not caught by tests because all the product test environments
already had the Confluent libraries present on the Kafka connector
classpath.
This commit instead introduces a new product test environment …
> Do not require Confluent libraries for Kafka connector if Protobuf features are not being used

- core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
- core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
To ensure the session property isn't accidentally set to an overwhelming number.
N/A
```markdown
```
> Enforce limit on FTE max partition count

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeTimeTravelCompatibility.java
Make sure that Delta tables restored to a previous version are read accurately via Trino.
> Test accuracy of reading from Delta tables restored to previous version

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
More close to how it was before
6729fedef2b8be1407294eda00420f32a0ede757.
> Make expected failure message self-explanatory

- core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
- core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java
- core/trino-main/src/main/java/io/trino/execution/Input.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/Output.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- core/trino-main/src/main/java/io/trino/sql/planner/InputExtractor.java
- core/trino-main/src/test/java/io/trino/execution/TestInput.java
- core/trino-main/src/test/java/io/trino/execution/TestQueryInfo.java
- core/trino-main/src/test/java/io/trino/execution/TestQueryStateMachine.java
- core/trino-main/src/test/java/io/trino/sql/analyzer/TestOutput.java
- core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryInputMetadata.java
- core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryOutputMetadata.java
- plugin/trino-mysql-event-listener/src/test/java/io/trino/plugin/eventlistener/mysql/TestMysqlEventListener.java
As a follow-up on @dain 's work for adding `version` to the `CatalogHandle`, this PR adds `catalogVersion` to the `inputs` and `output` fields from `QueryIOMetadata` to eventually distinguish the catalog version from the output sent to the event listener for the tables involved in Trino queries.
> Add `catalogVersion` into `QueryInputMetadata` & `QueryOutputMetadata`

- lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java
- lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/AbstractTestS3FileSystem.java
- lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3Location.java
- lib/trino-filesystem/pom.xml
- lib/trino-filesystem/src/main/java/io/trino/filesystem/Location.java
- lib/trino-filesystem/src/test/java/io/trino/filesystem/TestLocation.java
- lib/trino-filesystem/src/test/java/io/trino/filesystem/TestLocations.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestHiveS3MinioQueries.java
Locations like `s3://bucket` aren't consistently supported in Trino yet
and will cause compatibility issues with other software (e.g. Athena),
so forbid them. They may be allowed later.
Fixes https://github.com/trinodb/trino/issues/17921
> Forbid scheme://authority locations (without trailing slash)

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Don't retry table metadata read when fails with ValidationException
> Don't retry table metadata read when fails with ValidationException

- .github/workflows/ci.yml
- plugin/trino-delta-lake/pom.xml
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaS3AndGlueMetastoreTest.java
- plugin/trino-hive/pom.xml
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseS3AndGlueMetastoreTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/S3Assert.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveS3AndGlueMetastoreTest.java
- plugin/trino-iceberg/pom.xml
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergS3AndGlueMetastoreTest.java
Add test for S3 and Glue metastore
> Add test for S3 and Glue metastore

- pom.xml
This is the first version supporting JDK 21
```markdown
```
> Update error-prone to 2.20.0

- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSource.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
Fix correctness issue due to dbref field order in MongoDB
```markdown
* Fix correctness issue when the field order of [dbref type](https://www.mongodb.com/docs/manual/reference/database-references/#dbrefs) is different from `databaseName`, `collectionName` and `id`. ({issue}`issuenumber`)
```
> Fix correctness issue due to dbref field order in MongoDB

- testing/trino-testing-containers/src/main/java/io/trino/testing/containers/ConditionalPullPolicy.java
- testing/trino-testing-containers/src/main/java/io/trino/testing/containers/TestContainers.java
Prevents unwanted image pulls like one fixed by f0b8a4b13cdc58e04ebad35d584895610d7a8241 (https://github.com/trinodb/trino/pull/17936).
> Prevent accidental image pulls in getDockerArchitectureInfo

- .github/workflows/ci.yml
Make it possible for a contributor (or anyone else with a fork) to run tests of AWS S3 related Trino components.
> Externalize configuration of testing AWS resources

- plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
https://github.com/trinodb/trino/actions/runs/5299189833/jobs/9592021346
```
Error:    TestSqlServerConnectorTest>BaseSqlServerConnectorTest.testReadMetadataWithRelationsConcurrentModifications:171 
Expecting message:
"io.trino.testing.QueryFailedException: Error listing tables for catalog sqlserver: Lock request time out period exceeded."
to match regex:
"(?s).*(No task completed before timeout|was deadlocked on lock resources with another process and has been chosen as the deadlock victim|Expecting actual not to be empty).*"
but did not.
```
> Add another failure pattern in SQL Server concurrent modification test

- pom.xml
The default of this property changed from `false` to `true` in 5.0.0; since we're now at 6.0.0, this property is redundant.
```markdown
```
> Remove redundant property in git-commit-id-maven-plugin

- core/trino-server-rpm/pom.xml
This version removes usage of the deprecated maven-compat dependency.
> Update redlinerpm-maven-plugin to 2.1.8

- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeOss.java
`EnvSinglenodeDeltaLakeOss` was not working when PR's CI build is
triggered from the fork. The secrets and variables are not present, and
this resulted in `S3_BUCKET` env variable being defined but empty.
However, the environment doesn't need to be parameterized with the
bucket name at all.
> Fix CI runs from forks

- client/trino-jdbc/pom.xml
- lib/trino-phoenix5-patched/pom.xml
- pom.xml
* Remove redundant declaration of `createDependencyReducedPom`, because `true` is the default
* Move declaration of `dependencyReducedPomLocation` to the parent POM
The latter change makes it so the dependency-reduced POM is not placed in an "obnoxious" place. It's still there, but is not reported as a new file by git.
```markdown
```
> Clean up maven-shade-plugin configurations

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveS3AndGlueMetastoreTest.java
Hive connector does not support table locations containing double slashes. On S3 this leads to correctness issues (e.g. INSERT works, but SELECT does not find any data).
This commit
- restores normalization of implicit table location during CREATE TABLE. There used to be such normalization until 8bd9f754fb2aec61ffa353adfb421b460b60d947.
- rejects explicit table locations containing double slash during `CREATE TABLE .. WITH (external_location = ...)`. Before 8bd9f754fb2aec61ffa353adfb421b460b60d947 there used to be normalization also during this flow, but rejecting such unsupported locations is deemed more correct.
Alternative to https://github.com/trinodb/trino/pull/17947
Stop gap solution until we fix all problems related to double slashes in Hive connector …
> Avoid creating Hive tables with double slashed location

- client/trino-client/src/main/java/io/trino/client/ProtocolHeaders.java
Avoids unnecessary repeated string concatenation for HTTP header names in `ProtocolHeaders` which also enables `String#hashCode()` caching to work instead of having to re-compute it when constructing HTTP request/response headers multimaps.
> Reduce string concatenation in ProtocolHeaders

- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
- lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
Some files produced by this optimization were ignored by Apache Spark.
Related to https://trinodb.slack.com/archives/CGB0QHWSW/p1687254718875619
Some versions of Databricks Runtime produce an exception when reading files with re-ordered columns.
Related to https://trinodb.slack.com/archives/CP1MUNEUX/p1685685945379909
Original PR https://github.com/trinodb/trino/pull/17404
The files produced after this change were found to be sometimes ignored by Apache Spark
and produce exceptions on DBR 12.2 LTS.
Apache Hive and trino parquet reader did not have problems reading any of the new files.  …
> Revert optimization to reorder columns in parquet writer

- core/trino-main/src/main/java/io/trino/operator/scalar/ArrayToJsonCast.java
- core/trino-main/src/main/java/io/trino/operator/scalar/JsonOperators.java
- core/trino-main/src/main/java/io/trino/operator/scalar/JsonToArrayCast.java
- core/trino-main/src/main/java/io/trino/operator/scalar/JsonToMapCast.java
- core/trino-main/src/main/java/io/trino/operator/scalar/JsonToRowCast.java
- core/trino-main/src/main/java/io/trino/operator/scalar/MapToJsonCast.java
- core/trino-main/src/main/java/io/trino/operator/scalar/RowToJsonCast.java
- core/trino-main/src/main/java/io/trino/operator/scalar/timestamp/TimestampToJsonCast.java
- core/trino-main/src/main/java/io/trino/type/DecimalCasts.java
- core/trino-main/src/main/java/io/trino/util/JsonUtil.java
Prep for https://github.com/trinodb/trino/pull/17854
For https://github.com/trinodb/trino/issues/17843
> Prevent modifications of static JsonFactory instances

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystemMinio.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeOss.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeHiveHudiRedirections.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeHudi.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveRedirectionToHudi.java
`trino-ci-test` is the bucket currently used by the CI. For buckets that have nothing to do with this `trino-ci-test` S3 testing bucket, use different names.
> Change MinIO bucket names not to look like S3's

- .github/workflows/ci.yml
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaS3AndGlueMetastoreTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseS3AndGlueMetastoreTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveS3AndGlueMetastoreTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergS3AndGlueMetastoreTest.java
- testing/trino-testing/src/main/java/io/trino/testing/sql/TestTable.java
Extracted from https://github.com/trinodb/trino/pull/17958
For https://github.com/trinodb/trino/issues/17966, but does not fix it fully.
> Fix Delta INSERT when schema OR table location ends with two slashes

- .mvn/modernizer/violations.xml
- client/trino-cli/src/main/java/io/trino/cli/JsonPrinter.java
- core/trino-main/src/main/java/io/trino/operator/scalar/JsonExtract.java
- core/trino-main/src/main/java/io/trino/operator/scalar/JsonFunctions.java
- core/trino-main/src/main/java/io/trino/util/JsonUtil.java
- core/trino-main/src/test/java/io/trino/operator/scalar/TestJsonExtract.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonDeserializer.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/util/JsonTypeUtil.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/util/JsonUtils.java
- lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/util/TestJsonUtils.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java
- plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusQueryResponseParse.java
- service/trino-proxy/pom.xml
- service/trino-proxy/src/main/java/io/trino/proxy/ProxyResource.java
- service/trino-verifier/pom.xml
- service/trino-verifier/src/main/java/io/trino/verifier/JsonEventClient.java
- testing/trino-benchmark/pom.xml
- testing/trino-benchmark/src/main/java/io/trino/benchmark/JsonBenchmarkResultWriter.java
- testing/trino-benchmark/src/main/java/io/trino/benchmark/OdsBenchmarkResultWriter.java
```markdown
```
Fixes https://github.com/trinodb/trino/issues/17843
> Disable Jackson default JSON processing limits

- docs/src/main/sphinx/connector/kafka.rst
Document a manual workaround per @hashhar for Kafka Confluent Schema Registry error on startup.
https://github.com/trinodb/trino/issues/17299
> Add workaround for Kafka Confluent Schema Registry error on startup

- .github/actions/update-check/action.yml
- .github/workflows/ci.yml
When starting the CI run with all secrets, add a comment to the original PR with a link to that run, instead of only adding a comment after such run would fail. Update the comment with the status once it finishes.
> Improve feedback from CI runs with all secrets

- plugin/trino-hudi/pom.xml
Increase parallel build speed by building Hudi module as soon as Hive module is done.
> Remove build module dependency

- testing/trino-test-jdbc-compatibility-old-driver/pom.xml
The release fails with:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5:prepare (default-cli) on project trino-root: The artifact (io.trino:trino-jdbc) requires a different version (420) than what is found (${project.version}) for the expression (dep.presto-jdbc-under-test) in the project (io.trino:trino-test-jdbc-compatibility-old-driver). -> [Help 1]
This reverts commit 56083aac50bacc2775b8512e00bd477b2d22f1ea.
> Fix broken release process

- core/trino-main/src/main/java/io/trino/server/security/oauth2/JweTokenSerializer.java
- core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java
- core/trino-main/src/main/java/io/trino/server/security/oauth2/RefreshTokensConfig.java
- core/trino-main/src/main/java/io/trino/server/security/oauth2/TokenPairSerializer.java
- core/trino-main/src/main/java/io/trino/server/security/oauth2/TokenRefresher.java
- core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiAuthenticationFilter.java
- core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
- core/trino-main/src/test/java/io/trino/server/security/oauth2/TestJweTokenSerializer.java
- core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
> Fix JWE encryption with user provided secret key

- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageAvroPageSource.java
> Add missing return in BigQueryStorageAvroPageSource

- core/trino-main/src/test/java/io/trino/sql/gen/BenchmarkPageProcessor.java
- core/trino-spi/src/main/java/io/trino/spi/type/TypeOperators.java
- core/trino-spi/src/main/java/io/trino/spi/type/VarcharType.java
Avoids overhead of creating a Slice from VariableWidthBlock for LESS_THAN and LESS_THAN_OR_EQUAL comparisions with constant strings
```
Before
Benchmark                          Mode  Cnt     Score    Error  Units
BenchmarkPageProcessor.compiled   thrpt   50  3956.935 ± 96.529  ops/s
BenchmarkPageProcessor.handCoded  thrpt   50  4515.943 ± 35.327  ops/s
After
Benchmark                          Mode  Cnt     Score     Error  Units
BenchmarkPageProcessor.compiled   thrpt   50  6258.105 ± 172.675  ops/s
BenchmarkPageProcessor.handCoded  thrpt   50  7024.419 ± 116.318  ops/s
``` …
> Use Block#bytesCompare for comparisions with strings

- testing/trino-testing/src/main/java/io/trino/testing/AbstractTestAggregations.java
- testing/trino-tests/src/test/java/io/trino/tests/TestOptimizeMixedDistinctAggregations.java
Dropped unnecessary override in `TestOptimizeMixedDistinctAggregations` and separated and extended `testMixedDistinctAndZeroOnEmptyEmptyInputAggregations` to cover all aggregations for this case
Second commit extracted from https://github.com/trinodb/trino/pull/17963
```markdown
```
> Small improvement in distinct aggregation tests

- core/trino-main/src/main/java/io/trino/operator/aggregation/partial/SkipAggregationBuilder.java
The  `consecutive` method is not used anymore after https://github.com/trinodb/trino/pull/17688
```markdown
```
> Drop unused `consecutive` method

- docs/src/main/sphinx/connector/clickhouse.rst
- docs/src/main/sphinx/connector/druid.rst
- docs/src/main/sphinx/connector/ignite.rst
- docs/src/main/sphinx/connector/mysql.rst
- docs/src/main/sphinx/connector/oracle.rst
- docs/src/main/sphinx/connector/phoenix.rst
- docs/src/main/sphinx/connector/postgresql.rst
- docs/src/main/sphinx/connector/query-comment-format.fragment
- docs/src/main/sphinx/connector/redshift.rst
- docs/src/main/sphinx/connector/singlestore.rst
- docs/src/main/sphinx/connector/sqlserver.rst
Document added support for appending queries with context in sql based connectors.
https://github.com/trinodb/trino/pull/14500
```markdown
```
> Add support for appending queries in sql based connectors

- core/trino-main/src/main/java/io/trino/operator/aggregation/multimapagg/MultimapAggregationFunction.java
- core/trino-main/src/main/java/io/trino/operator/scalar/ArrayDistinctFunction.java
- core/trino-main/src/main/java/io/trino/operator/scalar/ArrayExceptFunction.java
- core/trino-main/src/main/java/io/trino/operator/scalar/ArrayIntersectFunction.java
- core/trino-main/src/main/java/io/trino/operator/scalar/ArrayUnionFunction.java
- core/trino-main/src/main/java/io/trino/operator/scalar/BlockSet.java
- core/trino-main/src/main/java/io/trino/operator/scalar/MapConcatFunction.java
- core/trino-main/src/main/java/io/trino/operator/scalar/MapToMapCast.java
- core/trino-main/src/main/java/io/trino/operator/scalar/MathFunctions.java
- core/trino-main/src/main/java/io/trino/operator/scalar/MultimapFromEntriesFunction.java
- core/trino-main/src/test/java/io/trino/operator/scalar/BenchmarkArrayDistinct.java
- core/trino-main/src/test/java/io/trino/operator/scalar/TestBlockSet.java
- core/trino-main/src/test/java/io/trino/type/TestArrayOperators.java
`BlockSet` does not copy values out of the input blocks, and instead a direct reference is kept. This improves performance for cases where the set is a temporary data structure.
Most uses of `TypedSet` can be replaced with `BlockSet`, because the set is used in a single lexical scope.
> Replace TypedSet with new BlockSet

- core/trino-main/src/main/java/io/trino/type/JsonType.java
- core/trino-spi/pom.xml
- core/trino-spi/src/main/java/io/trino/spi/type/AbstractVariableWidthType.java
- core/trino-spi/src/main/java/io/trino/spi/type/CharType.java
- core/trino-spi/src/main/java/io/trino/spi/type/TypeOperatorDeclaration.java
- core/trino-spi/src/main/java/io/trino/spi/type/VarbinaryType.java
- core/trino-spi/src/main/java/io/trino/spi/type/VarcharType.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ObjectIdType.java
Add reusable implementations of comparable and ordering operator for variable width types.
> Add reusable implementations of comparable and ordering operator for variable width types.

- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryQueryPageSource.java
> Add missing return in BigQueryQueryPageSource

- core/trino-spi/src/main/java/io/trino/spi/type/SqlTimestampWithTimeZone.java
Fix an error message in `SqlTimestampWithTimeZone`
> Fix error message in SqlTimestampWithTimeZone

- .github/actions/setup/action.yml
- .github/workflows/ci.yml
> Explicitly disable maven repo caching for selected jobs

- core/trino-main/src/main/java/io/trino/metadata/InternalFunctionBundle.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
Disallow aggregation function as UNNEST parameter and add similar check as here: https://github.com/trinodb/trino/pull/17988/commits/ad637f702ef272f4b96eca006fb047379f4d0604#diff-bd8fefc1e4638b7f65e377b75c16b46a2c541a24a64993860663507351917230R106
> Disallow aggregation function as `UNNEST` parameter

- docs/src/main/sphinx/admin/fault-tolerant-execution.rst
Clarify the need for exchange manager configuration for query result sets >32MB
```markdown
```
> Clarify need for exchange manager configuration

- core/trino-main/src/main/java/io/trino/operator/WindowInfo.java
- core/trino-main/src/test/java/io/trino/operator/TestWindowOperator.java
```markdown
* Prevent window operator from failing when query is cancelled. ({issue}`issuenumber`)
```
Fixes: https://github.com/trinodb/trino/issues/18030
> Prevent window operator from failing when it's aborted

- docs/src/main/sphinx/connector/iceberg.rst
Add Avro to "File formats" in Iceberg documentation
> Add Avro to "File formats" in Iceberg documentation

- client/trino-client/pom.xml
- core/trino-main/src/main/java/io/trino/server/security/oauth2/NimbusOAuth2Client.java
- core/trino-spi/pom.xml
- lib/trino-filesystem-s3/pom.xml
- lib/trino-hive-formats/pom.xml
- lib/trino-orc/pom.xml
- plugin/trino-bigquery/pom.xml
- plugin/trino-redis/pom.xml
- plugin/trino-resource-group-managers/pom.xml
- plugin/trino-sqlserver/pom.xml
- plugin/trino-thrift/pom.xml
- pom.xml
- service/trino-proxy/pom.xml
- testing/trino-product-tests-launcher/pom.xml
- testing/trino-test-jdbc-compatibility-old-driver/pom.xml
> Update to Airbase 143

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceProvider.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcTypeTranslator.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/rcfile/RcFilePageSourceFactory.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveTestUtils.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/StandardFileFormats.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnPartitionedTable.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnUnpartitionedTable.java
Previously MILLISECONDS precision was leaked when corecion applied on complex column even if coercion was not applied on timestamp column.
```markdown
* Respect timestamp precision when coercing complex column
```
> Respect timestamp coercion when coercing complex column

- docs/src/main/sphinx/connector/delta-lake.rst
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceProvider.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java
Increase domain compaction limits for hive and delta.
Makes the default limit consistent with iceberg.
> Increase domain compaction limits for hive and delta

- core/trino-main/src/main/java/io/trino/server/protocol/ExecutingStatementResource.java
- core/trino-main/src/main/java/io/trino/server/protocol/Query.java
- core/trino-main/src/main/java/io/trino/server/protocol/QueryResultsResponse.java
Reduces sources of lock contention associated with `Query#waitForResults` and it's usage by `ExecutingStatementResource`, largely by passing the additional protocol header fields along with the `QueryResults` payload in a single record class.
> Reduce query lock contention

- pom.xml
> Enable Error Prone check: BadComparable

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/aws/athena/PartitionProjectionService.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
When running `SHOW CREATE TABLE` include column properties present for Hive partition projection.
```markdown
* Display Hive partition projection column properties in `SHOW CREATE TABLE` output.
```
> Display Hive partition projection column properties

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionConnectorTest.java
Simplify the creation of `HiveQueryRunner` by the Hive connector tests:
1. No need to override `createQueryRunner` anymore.
2. Add more flexibility by using a builder instead of passing specific arguments to the base class.
> Simplify the creation of HiveQueryRunner

- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/metadata/ZooKeeperMetadataManager.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java
- pom.xml
> Enable Error Prone check: OrphanedFormatString

- core/trino-main/src/main/java/io/trino/operator/scalar/ConcatFunction.java
- core/trino-main/src/main/java/io/trino/operator/scalar/ConcatWsFunction.java
- core/trino-main/src/test/java/io/trino/operator/scalar/TestConcatWsFunction.java
concat_ws function support argument with string concatenation and array type. They use the public method `Slice concatWs(Slice separator, SliceArray values)` for processing. This method limit string concatenation to 254. But the array type should not limit the length of the parameter.
```markdown
* Fix failures for queries involving ``concat_ws`` function on large arrays. ({issue}`17816`)
```
> Fix concat_ws with array type don't support length exceed 254

- docs/src/main/sphinx/connector/iceberg.rst
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMigrateProcedure.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java
Support migrating Hive bucketed table as non-bucketed Iceberg table
```markdown
* Support migrating Hive bucketed table as non-bucketed Iceberg table. ({issue}`issuenumber`)
```
> Support migrating Hive bucketed table as non-bucketed Iceberg table

- core/trino-server/pom.xml
- pom.xml
Update provisio-maven-plugin to 1.0.20
> Update provisio-maven-plugin to 1.0.20

- client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/BaseTestJdbcResultSet.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcPreparedStatement.java
Fixes https://github.com/trinodb/trino/issues/6242
```markdown
```
> Fix 'Illegal instant due to time zone offset transition'

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesFunctionProcessor.java
> Fix potential premature finish in Delta CDF function

- docs/src/main/sphinx/connector/kafka.rst
- lib/trino-record-decoder/pom.xml
- lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/DescriptorProvider.java
- lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/DummyDescriptorProvider.java
- lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/FileDescriptorProvider.java
- lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/ProtobufColumnDecoder.java
- lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/ProtobufDecoderModule.java
- lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/ProtobufRowDecoder.java
- lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/ProtobufRowDecoderFactory.java
- lib/trino-record-decoder/src/test/java/io/trino/decoder/protobuf/TestProtobufDecoder.java
- lib/trino-record-decoder/src/test/resources/decoder/protobuf/any/all_datatypes/schema
- lib/trino-record-decoder/src/test/resources/decoder/protobuf/test_any.proto
- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/encoder/protobuf/ProtobufSchemaParser.java
- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/ProtobufAnySupportConfig.java
- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentDescriptorProvider.java
- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentModule.java
- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/file/FileTableDescriptionSupplierModule.java
- plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/protobuf/TestKafkaProtobufWithSchemaRegistryMinimalFunctionality.java
- plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/KafkaWithConfluentSchemaRegistryQueryRunner.java
- plugin/trino-kafka/src/test/resources/protobuf/any/structural_datatypes/schema
- plugin/trino-kafka/src/test/resources/protobuf/test_any.proto
This adds support for the `any` Protobuf data type, converting the message type to JSON. The default implementation uses the `ProtobufUtils` mechanism for parsing the `Descriptor`. There is a separate implementation that uses Confluent's `ProtobufSchemaProvider` which is used instead when the `ConfluentModule` is enabled and uses caching when accessing the types.
This PR needs user-facing documentation which will be added as another commit.
The Protobuf `any` type contains two fields, one `type_url` field and another being any serialized Protobuf message. The `type_url` is expected to be a URL that resolves to a serialized descriptor of the message. This change uses a `java.net.URL` of the `type_url` to open a stream and read the bytes of the descriptor which is then converted into a …
> Add Protobuf 'any' type support to Kafka connector

- plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
- plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorTest.java
Fix https://github.com/trinodb/trino/issues/16900
```markdown
* Add support for creating a table with a table comment. ({issue}`16900`)
* Add support for [`COMMENT ON TABLE`](/sql/comment). ({issue}`16900`)
```
> Support table comment for redshift connector

- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
- core/trino-main/src/test/java/io/trino/sql/query/TestCheckConstraint.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMinioAndHmsConnectorSmokeTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCheckConstraintCompatibility.java
Support check constraints for UPDATE statement in engine and Delta Lake connector
```markdown
* Add support for check constraints in `UPDATE` statement. ({issue}`17195`)
* Add support for check constraints and column invariants in `UPDATE` statements. ({issue}`17195`)
```
> Support check constraints for UPDATE statement in engine and Delta Lake connector

- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/projection/ApplyProjectionUtil.java
- lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/projection/TestApplyProjectionUtil.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveApplyProjectionUtil.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestHiveParquetComplexTypePredicatePushDown.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientConfig.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientModule.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoColumnHandle.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoConnector.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSink.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSource.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSessionProperties.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoTableHandle.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ptf/Query.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoConnectorSmokeTest.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoClientConfig.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoComplexTypePredicatePushDown.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoProjectionPushdownPlans.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoSession.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTableHandle.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseComplexTypesPredicatePushDownTest.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
This PR implements dereference pushdown for Mongodb connector(similar to https://github.com/trinodb/trino/pull/17085).
This adds significant performance improvements for queries accessing nested fields inside struct/row columns. They have been optimized through the pushdown of dereference expressions. With this feature, the query execution prunes structural data eagerly, extracting the necessary fields.
More Details about dereference pushdown: https://trino.io/blog/2020/08/14/dereference-pushdown.html
Note: This PR merges the work of https://github.com/trinodb/trino/pull/14467 and https://github.com/trinodb/trino/pull/16790
The feature is enabled by default.
The feature can be disabled by setting `mongodb.projection-pushdown-enabled` configuration property or …
> Implement dereference pushdown for MongoDB connector

- core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/BinPackingNodeAllocatorService.java
- core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java
There were some remaining routines called via scheduleWithFixedDelay which were not guarded with try...catch all clause. It is important to have such clause so routine is not silently unscheduled in case of unexpected error.
> Add exception guards for scheduleWithFixedDelay

- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/Versions.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloConnectorFactory.java
- plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopConnectorFactory.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcConnectorFactory.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorFactory.java
- plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleConnectorFactory.java
- plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraConnectorFactory.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConnectorFactory.java
- plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchConnectorFactory.java
- plugin/trino-example-http/src/main/java/io/trino/plugin/example/ExampleConnectorFactory.java
- plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsConnectorFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConnectorFactory.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiConnectorFactory.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConnectorFactory.java
- plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxConnectorFactory.java
- plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaConnectorFactory.java
- plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisConnectorFactory.java
- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduConnectorFactory.java
- plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileConnectorFactory.java
- plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryConnectorFactory.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoConnectorFactory.java
- plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixConnectorFactory.java
- plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConnectorFactory.java
- plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusConnectorFactory.java
- plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorConnectorFactory.java
- plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisConnectorFactory.java
- plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftConnectorFactory.java
- plugin/trino-tpcds/src/main/java/io/trino/plugin/tpcds/TpcdsConnectorFactory.java
- plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchConnectorFactory.java
- testing/trino-testing/src/main/java/io/trino/testing/tpch/IndexedTpchConnectorFactory.java
It was observed that people are inclined to change version check behavior rather than stop calling that method when they maintain 3rd party plugins.
Follows eg https://github.com/trinodb/trino/pull/18072
> Rename version checking method for more clarity

- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoSession.java
Currently, _id field is retrieved even when it's not necessary. We can exclude by https://www.mongodb.com/docs/drivers/java/sync/current/fundamentals/builders/projections/#exclusion-of-_id.
Fixes https://github.com/trinodb/trino/issues/17970
> Don't project _id field in Mongo DB connector when it's not required

- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapCastInComparison.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapDateTruncInComparison.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapYearInComparison.java
`defaultRewrite` is generic, returns same type as provided.
> Remove redundant casts

- lib/trino-filesystem/src/main/java/io/trino/filesystem/Location.java
- lib/trino-filesystem/src/test/java/io/trino/filesystem/TestLocation.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveWriterFactory.java
It's common for staging path to contain `${USER}` placeholder and be on
local file system. When username contains an AT sign (`name@domain`),
the `setSchemeToFileIfAbsent` used to fail, because `Location` couldn't
parse e.g. `file:///tmp/user@example.com`, treating the `@` sign as
userInfo separator. The parsing logic (split by `@ first or split by `/`
first) was different than in the URI class. This PR makes them more
similar.
Fixes https://github.com/trinodb/trino/issues/18132
> Fix Hive sorted write failure when user identity contains @ sign (v2)

- client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java
The existing try-catch fallback approach is not needed.
Follow-up to https://github.com/trinodb/trino/pull/18010
```markdown
```
> Simplify TrinoResultSet.parseDate

- client/trino-client/src/main/java/io/trino/client/OkHttpUtil.java
- client/trino-jdbc/src/main/java/io/trino/jdbc/ConnectionProperties.java
- client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDriverUri.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverAuth.java
adds hostnameInCertificate connection property for JDBC driver.
Our system requires calling one of multiple separate servers with a different hostname than the final Trino host. For maximum security we still want the benefits of full SSL verification with hostname validation and do not want to use CA validation only.
This property is available in other JDBC drivers such as SqlServer and SAP HANA - documentation linked below.
* [SqlServer JDBC Documentation with hostNameInCertificate](https://learn.microsoft.com/en-us/sql/connect/jdbc/setting-the-connection-properties?view=sql-server-ver16)
* [SAP HANA JDBC Documentation with hostNameInCertificate](https://help.sap.com/docs/SAP_HANA_CLIENT/f1b440ded6144a54ada97ff95dac7adf/109397c2206a4ab2a5386d494f4cf75e.html)
JDBC
- Allow verification of …
> Add hostnameInCertificate JDBC property

- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcWriteConfig.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcWriteSessionProperties.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcWriteConfig.java
Added an option query.max-writer-nodes-count to QueryManagerConfig and
a session option that limits number of tasks that take part in writing
nodes.
```markdown
```
> Make JDBC write parallelism configurable

- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/jdk/Temurin21EaJdkProvider.java
Internal change. No release notes needed.
> Update Temurin JDK 21 to 21-29-ea-beta

- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapYearInComparison.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestUnwrapYearInComparison.java
(*) This is not user-visible or docs only and no release notes are required.
```markdown
* Improve query performance for queries involving `year` function within `IN` predicate.
```
> Unwrap year in comparison also for IN predicate

- .github/workflows/ci.yml
- plugin/trino-hive/pom.xml
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/IonSqlQueryBuilder.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/S3SelectRecordCursorProvider.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3select/csv/S3SelectCsvRecordReader.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestS3SelectQueries.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3select/TestIonSqlQueryBuilder.java
- testing/trino-testing-containers/src/main/java/io/trino/testing/containers/Minio.java
The IonSqlQueryBuilder would produce select queries which were not proper transormations of the given TupleDomain, leading to incorrect results when S3 Select was enabled.
When reading JSON files predicates like `x IS NULL` or `x IS NOT NULL` were evaluated as `x = ''` or `x <> ''`.
When reading TextFile data the query builder ignores the table's `null_format` field, instead assuming that null fields are encoded as the empty string.
```markdown
* Fix incorrect query results when s3 Select is used with `IS NULL` or `IS NOT NULL` predicates.
* Fix incorrect query results when …
```
> Fix correctness issues in S3 Select pushdown

- core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
- core/trino-main/src/test/java/io/trino/dispatcher/TestLocalDispatchQuery.java
- core/trino-main/src/test/java/io/trino/execution/TestCreateTableTask.java
- core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
- core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
- core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
- core/trino-parser/src/main/java/io/trino/sql/tree/CreateTable.java
- core/trino-parser/src/main/java/io/trino/sql/tree/CreateTableAsSelect.java
- core/trino-parser/src/main/java/io/trino/sql/tree/SaveMode.java
- core/trino-parser/src/test/java/io/trino/sql/TestSqlFormatter.java
- core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
- service/trino-verifier/src/main/java/io/trino/verifier/QueryRewriter.java
Grammar changes to support CREATE OR REPLACE
```markdown
```
> Support `CREATE OR REPLACE` in parser

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DeltaLakeTestUtils.java
Relates to https://github.com/trinodb/trino/issues/12638
```markdown
* Add support for dropping columns. ({issue}`15792`)
```
> Add support for dropping column in Delta Lake

- docs/src/main/sphinx/release.md
- docs/src/main/sphinx/release/release-421.md
Assemble the release notes for the upcoming Trino 421 release. Fixes #18021 
* #18009 ✅ rn ✅ docs
* #17623 ✅ rn ✅ docs
* #17869 ✅ rn ✅ docs
* #18007 ✅ rn ✅ docs
* #17342 ✅ rn ✅ docs
* #18015 ❌ rn ✅ docs
* #18037 ✅ rn ✅ docs
* #17995 ✅ rn ✅ docs
* #18008 ✅ rn ✅ docs
* #18043 ✅ rn ✅ docs
* #16308 ✅ rn ✅ docs
* #18034 ✅ rn ✅ docs
* #18039 ✅ rn ✅ docs
* #18048 ✅ rn ✅ docs
* #18049 ✅ rn ✅ docs
* #18042 ✅ rn ✅ docs
* #18044 ✅ rn ✅ docs
* #17988 ✅ rn ✅ …
> Add Trino 421 release notes

- lib/trino-parquet/src/main/java/io/trino/parquet/reader/AbstractColumnReader.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/AbstractColumnReaderTest.java
Date columns are usually low cardinality
```markdown
```
> Allow dictionary processing for date type in parquet

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableCompatibility.java
Fixes https://github.com/trinodb/trino/issues/12638
Fixes #13538
```markdown
* Add support for renaming columns. ({issue}`15821 `)
```
> Add support for renaming column in Delta Lake

- core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java
Add testing for JDK 19 to complement maven-checks running on 19.
```markdown
```
> Make ServerIT work with different Temurin JDK versions

- client/trino-cli/src/main/java/io/trino/cli/QueryRunner.java
- client/trino-client/src/main/java/io/trino/client/JsonResponse.java
- client/trino-client/src/main/java/io/trino/client/StatementClientFactory.java
- client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
- client/trino-jdbc/pom.xml
- client/trino-jdbc/src/main/java/io/trino/jdbc/NonRegisteringTrinoDriver.java
- client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java
- testing/trino-tests/src/test/java/io/trino/execution/TestFinalQueryInfo.java
Because trino-jdbc is using a shaded version of okhttp, it does not get automatically instrumented when using an OTEL Java agent.
Thanks to this, both client and server traces can be correlated, with JDBC traces as the root.
This is a follow-up to #16950.
> Manually instrument okhttp with OTEL in trino-jdbc

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetConnectorTest.java
Fixes Parquet dereference pushdown on the physical level on https://github.com/trinodb/trino/issues/17156
ORC still open
PoC is the implementation for Hive
https://github.com/trinodb/trino/blob/adef5f4754eb0edbeed23790d8520ead38ae0ad9/plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java#L316-L330
What happens in the code:
- only sufficient columns (if doing `SELECT parent.child, child` only `parent` field will actually be selected) will be selected
- for each column, only the necessary information will be selected from the file schema sent to parquet reader
If `nested.nested1level1.field4` gets selected and the column type hierarchy looks like this:
```
nested
field 1
field 2
nested1level1
field3
field4
nested2level1
field5
field6 
``` 
for creating …
> Apply the dereference pushdown at the physical level on parquet in Iceberg

- core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
Make the query span child of the current span and avoid using links, because there's always a single query that exists only in the context of a series of client requests. If the client propagates a root span, the query should be a child of that span.
This is also needed, because some tools, like DataDog, don't support OTEL span links at all.
Thanks to this, the whole query is visible along with the client span:
Without this, only the server requests are visible:
> Avoid using trace span links

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointEntryIterator.java
Fixes https://github.com/trinodb/trino/issues/17405
Instead of a not null filter on the entry type column, which is a complex type for which null filters are NOOPs, we use a not null filter on a primitive required field of the entry type. This enables data skipping in the Parquet reader.
Please see https://github.com/trinodb/trino/issues/17405
```markdown
* Improve performance of reading from tables with a large number of checkpoint entries. ({issue}`17405`)
```
> Use predicates which are pushed down to Parquet reader in CheckpointEntryIterator

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergInputInfo.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcMetricsCollection.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcSystemTables.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcWithBloomFilters.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetSystemTables.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergStatistics.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergS3AndGlueMetastoreTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestIcebergNessieCatalogConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergTrinoRestCatalogConnectorSmokeTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveRedirectionToIceberg.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergPartitionEvolution.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Use parquet as the default file format for iceberg
Parquet writer has comparable performance to ORC.
[Hive insert benchmark ORC vs parquet.pdf](https://github.com/trinodb/trino/files/11980809/Hive.insert.benchmark.ORC.vs.parquet.pdf)
Parquet reader has comparable or better performance to ORC.
[Iceberg unpartitioned sf1k orc vs parquet.pdf](https://github.com/trinodb/trino/files/11980825/Iceberg.unpartitioned.sf1k.orc.vs.parquet.pdf)
[Iceberg partitioned sf1k orc vs parquet.pdf](https://github.com/trinodb/trino/files/11980816/Iceberg.partitioned.sf1k.orc.vs.parquet.pdf)
Since there are no longer major performance benefits to staying on ORC and parquet is the popular format,
we can switch the default to parquet
( ) …
> Use parquet as the default file format for iceberg

- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryType.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTypeUtils.java
- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryTypeMapping.java
- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryType.java
Relates to https://github.com/trinodb/trino/issues/13741
```markdown
* Add support for writing `timestamp with time zone` type. ({issue}`17793`)
```
> Support writing timestamp with timezone in BigQuery

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergUtil.java
Use Pattern for code simplicity. Uniformly return when pattern not
found. Previously either exception was raised or empty returned, but
this could lead to problems like `AbstractIcebergTableOperations`
incorrectly resetting version to 0.
Relates to: https://github.com/trinodb/trino/pull/17863
> Simplify version parsing from metadata file name

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/HiveFileIterator.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/TestCachingDirectoryListerRecursiveFilesOnly.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/TestHiveFileIterator.java
Fix query failure when `hive.recursive-directories` is used and the partition directory contains any url-encoded characters, i.e. when partition value contains pretty much anything other than letters/digits.
Fixes https://github.com/trinodb/trino/issues/18149
> Fix recursive listing from Hive partitions containing non-alphabetic values

- lib/trino-orc/src/main/java/io/trino/orc/metadata/OrcType.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/TempFileWriter.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Fix `SortingFileWriter` to support all types used by Iceberg.
fixes https://github.com/trinodb/trino/issues/18136
> Fix Iceberg sorted writes on tables with time or uuid

- core/trino-main/src/main/java/io/trino/likematcher/LikeMatcher.java
- core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
- core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
- core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
- core/trino-main/src/main/java/io/trino/type/LikeFunctions.java
- core/trino-main/src/main/java/io/trino/type/LikePattern.java
- core/trino-main/src/main/java/io/trino/type/LikePatternType.java
- core/trino-main/src/test/java/io/trino/likematcher/TestLikeMatcher.java
- core/trino-main/src/test/java/io/trino/operator/scalar/TestLikeFunctions.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java
- core/trino-main/src/test/java/io/trino/type/TestLikePatternType.java
Compiled filter/projections can currently contain LikeMatcher as a
ConstantExpression. Added a new wrapper class LikePatternMatcher
which defines hashCode/equals to avoid recompiling classes and
filling up compiled classes cache
```markdown
```
> Fix caching of expressions with like pattern

- docs/src/main/sphinx/connector/hive.rst
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveType.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveTypeTranslator.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Resolves #1240 by mapping Hive TIMESTAMP WITH LOCAL TIME ZONE to TIMESTAMP WITH TIME ZONE with UTC zone. 
Mapping to UTC is a bit of a judgement call (see #1240), but I believe is better than the alternatives (like using session zones) and the direction Trino maintainers want to take (see e.g. #8680). 
In addition to the new automated test, I have tested reading the timestamps from Parquet files. Notably, Hive Avro serde doesn't support TIMESTAMP WITH TIME ZONE.
A new feature.
Hive connector
Adds support for TIMESTAMP …
> Support for reading TIMESTAMP WITH LOCAL TIME ZONE in Hive connector

- docs/src/main/sphinx/connector/hive-alluxio.rst
We haven't maintained this section of the Alluxio docs in Trino, and it's out of date and inaccurate. Alluxio has their own documentation for running their platform with Trino, and it's been kept up to date much more effectively, so it's simpler, easier, and more accurate to direct users to that page to ensure that they're getting up-to-date information.
> Simplify Alluxio docs with a redirect

- docs/src/main/sphinx/installation/deployment.rst
* Adds a recommended healthy setting for `nproc` parameter to ensure adequate headroom for creating processes
```markdown
```
> Add recommended nproc setting

- docs/src/main/sphinx/functions/list-by-topic.rst
- docs/src/main/sphinx/functions/list.rst
- docs/src/main/sphinx/sql/match-recognize.rst
I missed these in https://github.com/sql-formatter-org/sql-formatter/pull/297 and added them in https://github.com/sql-formatter-org/sql-formatter/pull/333 also needed this for https://github.com/codemirror/codemirror5/pull/6962
> Add row pattern recognition functions to list of functions

- docs/src/main/sphinx/release/release-332.md
This fixes a build failure introduced by https://github.com/trinodb/trino/pull/18022
> Remove invalid reference to Alluxio Catalog Service docs

- core/trino-main/src/main/java/io/trino/execution/DropSchemaTask.java
- core/trino-main/src/main/java/io/trino/metadata/Metadata.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
- core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
- core/trino-main/src/main/java/io/trino/tracing/TracingMetadata.java
- core/trino-main/src/test/java/io/trino/execution/BaseDataDefinitionTaskTest.java
- core/trino-main/src/test/java/io/trino/execution/TestDropSchemaTask.java
- core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
- core/trino-main/src/test/java/io/trino/metadata/CountingAccessMetadata.java
- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
- docs/src/main/sphinx/sql/drop-schema.rst
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
- plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
- plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
- plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
- testing/trino-testing/src/main/java/io/trino/testing/TestingConnectorBehavior.java
Pushing cascading option to connectors for avoiding failure on the way during deleting child objects under the schema (e.g. access denied in specific table). Also, the remote database may contain objects that Trino engine isn't aware of. 
I didn't touch access control because I couldn't find the difference between cascade and restrict option in SQL standard. 
```markdown
* Support `CASCADE` option for `DROP SCHEMA` statement. ({issue}`17855`)
```
> Support CASCADE option for DROP SCHEMA statement in engine and BigQuery connector

- docs/src/main/sphinx/client/jdbc.rst
add hostnameInCertificate to JDBC Client Docs.
Adding changes pushed in https://github.com/trinodb/trino/pull/17939.
> add hostnameInCertificate to JDBC Client Docs

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java
Check writer version in Delta Lake `vacuum` procedure considering future changes in Delta protocol (e.g. UniForm)
Fixes #18095
```markdown
* Disallow executing `vacuum` procedure when the max writer version is higher than 5. ({issue}`18095`)
```
> Check writer version in Delta Lake `vacuum` procedure

- plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
- plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorTest.java
We should not fall back to legacy behavior,
the mappings should be explicit (the legacyToWriteMapping is just a
copy of some generic default mappings that used to exist)
Remove fall back to legacy type mapping in Redshift.
```markdown
```
> Remove fall back to legacy type mapping in Redshift

- core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
With current logic in HttpRemoteTask.fatalUnacknowledgedFailure() it was possible that we only set `FAILED` status in TaskStatus in ContinuesTaskStatusFetcher but TaskInfo in TaskInfoFetcher will not be updated.
It happened when we entered the `else` branch for
`(cause instanceof TrinoTransportException)` condition. The `TaskInfoFetcher.taskInfo` was not updated then. Subsequent calls to `fatalUnacknowledgedFailure` where then no-op due to `!taskStatus.getState().isDone()` condition at the top. While at this time `TaskInfoFetcher` may no longer be able to update task Info (worker node can be gone already) and it will remain stale forever.
It resulted in a split brain scenario that parts of the system observe Task as failed while others (those depending on TaskInfo) reported that task is …
> Ensure final task info set on worker node failure

- core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java
- core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
OAuth2 implementation should ignore JWT tokens that does not contain required principal claim as these tokens may be intended for other authentication methods.
```markdown
* Fix error when using `http-server.authentication.type=oauth2,jwt` and different values for `principal-field`
```
> Ignore tokens without required principal claim

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java
Tests related change
Previously the retrieval failure was being verified on the exception message, which made the assertion to fail when that AWS Glue API change the exception message.
AWS Glue API slightly changed the error message when getting a table which doesn't exist.
https://github.com/trinodb/trino/actions/runs/5514809101/jobs/10055380071
```
Error:    TestIcebergGlueCatalogConnectorSmokeTest>BaseIcebergConnectorSmokeTest.testRegisterTableWithTrailingSpaceInLocation:349->dropTableFromMetastore:157 [Table in metastore should not exist] 
Expecting message:
"Entity Not Found (Service: AWSGlue; Status Code: 400; Error Code: EntityNotFoundException; Request ID: d1f68d62-e638-42d5-b7b7-08ccd1d23cf6; Proxy: null)"
to match regex:
".*Table (.*) not found.*"
but did not.
Throwable that …
```
> Verify table information retrieval failure based on exception class

- core/trino-spi/pom.xml
- core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlockBuilder.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroCompressionKind.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroFileReader.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroFileWriter.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroPagePositionDataWriter.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroTypeManager.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroTypeUtils.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/NativeLogicalTypesAvroTypeManager.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/NoOpAvroTypeManager.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroBase.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroPageDataReaderWithAvroNativeTypeManagement.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroPageDataReaderWithoutTypeManager.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroPageDataWriterWithoutTypeManager.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestLongFromBigEndian.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveCompressionCodec.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveCompressionCodecs.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveFormatsConfig.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/AvroHiveFileWriter.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/AvroHiveFileWriterFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/AvroHivePageSourceFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/HiveAvroTypeManager.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/CompressionConfigUtil.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AvroSchemaGenerationTests.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFormatsConfig.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
A native implementation of Avro file writer
As part of the broader effort to decouple from the hive/hadoop libraries, this PR implements a custom DatumWriter that will encode positions of a given page set once and iterated over. Implements a plugin specific way to overwrite the behavior of the writer especially for given Avro Logical types.
Key classes:
- `io.trino.hive.formats.avro.AvroPagePositionDataWriter` 
```markdown
New Native Avro file writer is enabled by default in the Hive plugin. 
Disable via config `avro.native-writer.enabled=false`
or via session `SET SESSION …
```
> Native Avro File Writer

- core/trino-spi/src/main/java/io/trino/spi/connector/EmptyPageSource.java
> Remove deprecated methods from EmptyPageSource

- pom.xml
Explicitly configure the `dotGitDirectory` used by the `git-commit-id-maven-plugin` to be the root of the (multi-module) project using the `air.main.basedir` property.
This is needed when using git worktrees, as the plugin incorrectly detects the wrong directory in which to run git commands. If https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/639 _or_ https://github.com/git-commit-id/git-commit-id-maven-plugin/issues/215 are resolved, this will become unnecessary. When Trino upgrades to Maven 4.0.0, assuming the workaround is still needed, we can update to using the new `project.rootDirectory` property (see [MNG-7038](https://issues.apache.org/jira/browse/MNG-7038)) instead of the Airbase one.
This fixes #18027; see the discussion there for more details.
(X) This is not …
> Fix build inside git worktrees by working around git-commit-id #639

- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduClientSession.java
- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/BaseKuduConnectorSmokeTest.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
This PR adds support for trino-kudu to create table with table comment using the Java Kudu Client.
This change allows users to use Trino to create tables with table comments when using our Apache Kudu connector.
Fixes the table comment part of #12469 , another PR will be made for create table with column comments.
```markdown
* Add support for table comments when creating tables. ({issue}`17945`)
```
> Support table comments on create table in Kudu 

- core/trino-main/src/main/java/io/trino/testing/TestingConnectorContext.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadataFactory.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableHandle.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/InternalIcebergConnectorFactory.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedView.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestTrinoGlueCatalog.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestTrinoNessieCatalog.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/optimizer/TestConnectorPushdownRulesWithIceberg.java
Iceberg Materialized View implementation relies on classloader isolation
to distinguish between tables coming from current catalog (for which
table changes can be inspected) and tables from other catalogs. This
PR prepares the check for classloader isolation removal.
Relates to https://github.com/trinodb/trino/issues/15921
> Prepare Iceberg MV for lack of classloader isolation

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergRegisterTableProcedure.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergUtil.java
Fixes #16363
There are a couple of points to note:
- After hadoop table is registered with any catalog in Trino, `version-hint.text` won't be used or updated on any commit.
- Data should not be inserted using Iceberg's `HadoopTable` API after registering the table in Trino. Those data won't be visible to Trino.
After creating the Iceberg HadoopTable and commiting a `COMMENT` on it, before `register_table`:
```
[root@hadoop-master /]# hdfs dfs -ls -R /user/hive/warehouse/test_register_hadoop_table_hadoop_table_parquet_0x4hdoexi6/
drwxrwxrwx   - marius supergroup          0 2023-06-29 22:54 /user/hive/warehouse/test_register_hadoop_table_hadoop_table_parquet_0x4hdoexi6/metadata
-rw-r--r--   3 marius supergroup       1254 2023-06-29 22:54 …
```
> Support iceberg `register_table` procedure to register hadoop tables

- testing/trino-testing-containers/src/main/java/io/trino/testing/containers/BaseTestContainer.java
- testing/trino-testing-containers/src/main/java/io/trino/testing/containers/OpenTracingCollector.java
- testing/trino-testing/pom.xml
- testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
This change makes it easier to access tracing information while using `DistributedQueryRunner`-s to work with tests.
Trace search link is printed to the console so it's easier to access trace information directly:
The standard Jeager ui is used:
> Add opentracing to DistributedQueryRunner

- docs/src/main/sphinx/release.md
- docs/src/main/sphinx/release/release-422.md
Assemble the release notes for the upcoming Trino 422 release. Fixes #18161  
* #18156 ✅ rn ✅ docs
* #15821 ✅ rn ✅ docs
* #18158 ✅ rn ✅ docs
* #18005 ✅ rn ✅ docs
* #18152 ✅ rn ✅ docs
* #18124 ✅ rn ✅ docs
* #17101 ✅ rn ✅ docs
* #18180 ✅ rn ✅ docs
* #18141 ✅ rn ✅ docs
* #17387 ✅ rn ✅ docs
* #18115 ✅ rn ✅ docs
* #17501 ✅ rn ✅ docs
* #18164 ✅ rn ✅ docs
* #17996 ✅ rn ✅ docs
* #17408 ✅ rn ✅ docs
* #18170 ✅ rn ✅ docs (#18250)
* #18192 ✅ rn ✅ docs
* #18190 …
> Add Trino 422 release notes

- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/text/TextLineReader.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/text/TextLineReaderFactory.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/text/TestLineReader.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/text/TestTextLineReaderWriter.java
Previously the uncompressed size was reported as the number of bytes read for text tiles.
```markdown
* Fix reporting of bytes read for compressed text files. ({issue}`issuenumber`)
```
> Fix reporting of bytes read for compressed text files

- pom.xml
Fixes #18223
```markdown
* Fix missing data when reading concatenated GZIP compressed text files. ({issue}`18223`)
```
> Fix reading concatenated GZIP streams

- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/LineReader.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/sequence/SequenceFileReaderFactory.java
- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/text/TextLineReaderFactory.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/sequence/TestSequenceFileWriterFactory.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/text/TestTextLineReaderFactory.java
This is an alternative to #18255.  
This PR throws if a test or sequence file is created with a start off and multiple header rows, or any footer rows.  This should never happen because the split generator does not split files that have multiple header or any footer rows.
The main problem where the single header row is skipped for all splits of a file is fixed for both TEXTFILE and sequence file.
```markdown
* Fix missing data when reading large text and sequence files with a single header row. ({issue}`18255`)
```
Fixes https://github.com/trinodb/trino/issues/18273
> Fix header footer

- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/encodings/text/StringEncoding.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/simple/TestSimpleFormat.java
Fixes #18215
```markdown
* Fix TEXTFILE and RCTEXT handling of an escaped escape character. ({issue}`18215`)
```
> Fix TEXTFILE and RCTEXT string escape of an escape character

- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
- When window functions are used with `OVER()`, we fail to detect them in `analyzeHaving()` which results in compiler failed errors instead of TrinoException.
- This pull request uses the previous changes in `extractWindowFunctions()` that were added as part of this [commit](https://github.com/trinodb/trino/commit/7b6c079850d9e6b51972c57cbc8b8190e22e81ce) to handle the same case in `HAVING` clause.
- To highlight the issue, I ran the following queries on cli
1. before the change (unwanted behaviour)
```
trino> SELECT 1 FROM (VALUES 1) HAVING rank() > 1;
Query 20230712_221743_00003_76sak failed: java.lang.RuntimeException: java.lang.IllegalArgumentException: rank():bigint is not a scalar function
```
2. after the change (wanted behaviour)
```
trino> SELECT 1 FROM (VALUES 1) HAVING rank() > …
```
> Fix error reporting when window functions are used in HAVING clause.

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableName.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableName.java
Simplify getRawSystemTable in Delta Lake. After this change, we can avoid a new field for `DeltaLakeTableHandle` in #17592
> Simplify getRawSystemTable in Delta Lake

- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectionCreationTest.java
Fix TASK_SCALE_WRITERS_MAX_WRITER_COUNT in test
If this session property is not fixed then running this locally most
likely will fail as number of writers depends on number of CPUs and so
expected number of created connections will be different.
> Fix TASK_SCALE_WRITERS_MAX_WRITER_COUNT in test

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSource.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceProvider.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/CharCoercer.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/CoercionUtils.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/DecimalCoercers.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/TimestampCoercer.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/VarcharCoercer.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcTypeTranslator.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestTimestampCoercer.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnPartitionedTable.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnUnpartitionedTable.java
This will be irrespective of the precision configured or specified as
session property.
Depends on https://github.com/trinodb/trino/pull/17900.
```markdown
* Treat precision as NANOSECONDS for timestamp to be coerced.
```
> Treat precision as NANOSECONDS for timestamp to be coerced 

- core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java
- core/trino-main/src/test/java/io/trino/execution/TestTaskManagerConfig.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
This change will help increase the performance of writes when local exchange is used either due to partitioning the data or scaling the writers.
Benchmarks for unpartitioned write:
Before:ku
Input Size: 6B rows
Time: 4:46 mins
Peak Mem: 59.9GB
After:
Input Size: 6B rows
Time: 3:45 mins
Peak Mem: 61.2GB
Benchmarks for partitioned write:
Before:
Input Size: 3B rows (3 skewed partitions)
Time: 2:33 mins
Peak Mem: 89.8GB
After:
Input Size: 3B rows (3 skewed partitions)
Time: 1:57 mins
Peak Mem: 92.3GB
```markdown
```
> Increase maxLocalExchangeBufferSize to 128MB

- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/SymbolMapper.java
- core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestUnaliasSymbolReferences.java
Original grouping sets are deduplicated in the
`StatementAnalyzer.Visitor.analyzeGroupBy`. Optimizer rules can create GroupIdNode that contain duplicates unintentionally though, for example, before `UnaliasSymbolReferences` rule is run, but LocalExecutionPlanner.Visitor.visitGroupId expects unique symbols in each grouping-set.
```markdown
```
> Deduplicate symbols inside GroupIdNode grouping set

- .github/actions/update-check/action.yml
- .github/workflows/ci.yml
Don't use `always()` in step condition with additional predicates, because it ignores other predicates.
> Fix updating PR comments from tests with secrets workflow

- core/trino-main/src/main/java/io/trino/operator/scalar/UrlFunctions.java
- core/trino-main/src/test/java/io/trino/operator/scalar/TestUrlFunctions.java
It's not by (any document) design to silently ignore invalid input in URI extracting functions (url_extract_fragment, url_extract_host, url_extract_parameter, url_extract_path, url_extract_port, url_extract_protocol, url_extract_query).
This commit follows least surprise principle: invalid input is explicitly rejected. Users wanting to ignore invalid input should use `try(...)` expression around the invocations.
This commit does not change docs, since now the functions behave as documented.
```markdown
* Fix URI extraction functions (``uri_extract_*``) not to ignore input which is not valid URI.
Previously the functions undocumented behavior was to return ``NULL`` in such case.
```
> Reject invalid URIs in URI extract functions

- lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/AbstractTestS3FileSystem.java
- lib/trino-filesystem/src/main/java/io/trino/filesystem/Location.java
- lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java
- lib/trino-filesystem/src/test/java/io/trino/filesystem/TestLocation.java
Whitespace, and especially trailing whitespace, may have confusing consequences when used in file locations so it's not recommended. However, whitespace, including trailing whitespace, is valid part of file locations and Trino should be able to read such files (objects).
```markdown
* Fix query failure when table has a file with location ending with a whitespace. 
```
> Support files with locations ending with whitespace

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
Fixes https://github.com/trinodb/trino/issues/18203
> Fix Iceberg MV failure after table roll back

- lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsFileSystem.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java
Reduce the number of times Hive needs to call the file system listing API when using common file systems.
Relates to: https://github.com/trinodb/trino/pull/17323
> Reduce Hive file system listing

- plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/s3select/S3SelectTestHelper.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/AvroFileWriterFactory.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
> Use Hive native writers for creating empty bucket files

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
Extracted from https://github.com/trinodb/trino/pull/18299
> Test Iceberg operations for information_schema.columns

- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetSchemaConverter.java
Allows reader implementations to potentially produce smaller in-memory representations 
when reading data or skip bound checks from reading INT32 as smaller types.
Also useful for schema discovery tools to infer byte/short types from parquet INT32 types with annotation.
https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#signed-integers
```markdown
```
> Add IntLogicalTypeAnnotation in parquet writer

- client/trino-cli/src/main/java/io/trino/cli/QueryRunner.java
- client/trino-client/src/main/java/io/trino/client/OkHttpUtil.java
- client/trino-client/src/main/java/io/trino/client/auth/kerberos/AbstractUnconstrainedContextProvider.java
- client/trino-client/src/main/java/io/trino/client/auth/kerberos/BaseGSSContextProvider.java
- client/trino-client/src/main/java/io/trino/client/auth/kerberos/DelegatedConstrainedContextProvider.java
- client/trino-client/src/main/java/io/trino/client/auth/kerberos/DelegatedUnconstrainedContextProvider.java
- client/trino-client/src/main/java/io/trino/client/auth/kerberos/GSSContextProvider.java
- client/trino-client/src/main/java/io/trino/client/auth/kerberos/LoginBasedUnconstrainedContextProvider.java
- client/trino-client/src/main/java/io/trino/client/auth/kerberos/SpnegoHandler.java
- client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractConnectionProperty.java
- client/trino-jdbc/src/main/java/io/trino/jdbc/ConnectionProperties.java
- client/trino-jdbc/src/main/java/io/trino/jdbc/ConnectionProperty.java
- client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDriverUri.java
- docs/src/main/sphinx/client/jdbc.rst
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/HadoopKerberos.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite1.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite3.java
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop-kerberos/krb5_client.conf
- testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/jdbc/TestKerberosConstrainedDelegationJdbc.java
Adding constrained delegation support to trino JDBC driver
Now user can create GSSCredential on its own and just pass it as driver property to JDBC driver, smth like this:
```
Properties driverProperties = new Properties();
GSSCredential userCredential = [userCredential]
driverProperties.put("KerberosConstrainedDelegation", userCredential);
Connection conn = DriverManager.getConnection(CONNECTION_URI, driverProperties)
```
Adding constrained delegation support to trino JDBC driver
Now user can create GSSCredential on its own and just pass it as driver property to JDBC driver, …
> Kerberos delegation support

- lib/trino-orc/src/main/java/io/trino/orc/OrcWriteValidation.java
- lib/trino-orc/src/main/java/io/trino/orc/metadata/statistics/TimeMicrosStatisticsBuilder.java
- lib/trino-orc/src/main/java/io/trino/orc/reader/ColumnReaders.java
- lib/trino-orc/src/main/java/io/trino/orc/reader/LongColumnReader.java
- lib/trino-orc/src/main/java/io/trino/orc/writer/ColumnWriters.java
- lib/trino-orc/src/test/java/io/trino/orc/AbstractTestOrcReader.java
- lib/trino-orc/src/test/java/io/trino/orc/OrcTester.java
- lib/trino-orc/src/test/java/io/trino/orc/TestingOrcPredicate.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java
Fixes #15603 
Fixes issue where ORC files containing nullable Iceberg TIME columns could throw an exception when being read.  Also fixed an error in the ORC file validator where time columns did not validate correctly in order to add appropriate tests for the Time type.
```markdown
* Fix Iceberg query failure when reading ORC files with nullable `time` columns. ({issue}`15606`)
```
> Fix failure to read nullable time(6) columns

- core/trino-main/src/main/java/io/trino/cost/FilterStatsCalculator.java
- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PlanNodeSearcher.java
- core/trino-main/src/test/java/io/trino/cost/TestFilterStatsCalculator.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsReader.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
- testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
Speed up `testWriteTaskParallelismSessionProperty` for JDBC connectors.
fixes https://github.com/trinodb/trino/issues/18328
fixes https://github.com/trinodb/trino/issues/18330
```
```
> Avoid running expensive INSERT to assert on the plan and stats calculation fixes

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveType.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/CharTypeInfo.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/DecimalTypeInfo.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/ListTypeInfo.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/MapTypeInfo.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/PrimitiveTypeInfo.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/StructTypeInfo.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/TypeInfo.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/UnionTypeInfo.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/VarcharTypeInfo.java
The method used to ignore the type info field, since type infos used to be cached. Our copy of `TypeInfoFactory` does not cache, however.
> Fix HiveType.getRetainedSizeInBytes for caching removal

- core/trino-spi/pom.xml
- lib/trino-filesystem/src/main/java/io/trino/filesystem/Locations.java
- lib/trino-filesystem/src/test/java/io/trino/filesystem/TestLocations.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveBucketing.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
Avoid converting to metastore Column when checking for supported and unsupported types. This avoids a lookup in `TypeManager`.
Extracted from https://github.com/trinodb/trino/pull/18315
> Operate on column handle directly in checkPartitionTypesSupported and other cleanups

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/TrinoCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/TrinoNessieCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java
HiveCatalog sets data column types in metastore for an Iceberg table. This adds same behavior for register_table flow.
Extracted from https://github.com/trinodb/trino/pull/18299
> Set column types in Iceberg register_table

- docs/src/main/sphinx/connector/delta-lake.rst
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePropertiesTable.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableType.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeSharedMetastoreWithTableRedirectionsTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableName.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeSystemTableCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeRedirect.java
Adds a `$properties` system table for Delta Lake, similar to what exists for Iceberg.
The main motivation for adding the `$properties` system table is to be able to test `extra_properties` which will be added as part of https://github.com/trinodb/trino/issues/17428
Fixes https://github.com/trinodb/trino/issues/17294
Please see https://github.com/trinodb/trino/issues/17294
```markdown
* Add `$properties` system table which can be queried to inspect Delta Lake table properties. ({issue}`17294`)
```
> Add Delta Lake $properties system table

- docs/src/main/sphinx/connector/oracle.rst
- plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/AbstractTestOracleTypeMapping.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleClient.java
Now we can use any presicion for oracle timestamp(p),
p could be in range from 0 to 9.
```markdown
* Add support for Oracle timestamp with non-milliseconds precision
```
> Various precision for Oracle timestamp

- testing/trino-testing-containers/pom.xml
- testing/trino-testing-containers/src/main/java/io/trino/testing/containers/OpenTracingCollector.java
- testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
Follow-up to https://github.com/trinodb/trino/pull/18184
> OpenTracingCollector fixes

- plugin/trino-ignite/pom.xml
- plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteJdbcConfig.java
- plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteJdbcConfig.java
```markdown
* Upgrade JDBC thin driver to 2.15.0
```
> Update ignite to 2.15.0

- client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
- client/trino-cli/src/main/java/io/trino/cli/Console.java
- client/trino-cli/src/main/java/io/trino/cli/Trino.java
When an exception is raised either during query execution or parsing command line arguments in the CLI the output is now formatted:
`--debug` option is taken into the account to expand exception stack trace
Release notes:
```markdown
* Format error messages and hide stack traces behind `--debug` flag by default
```
> Format CLI error messages

- core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
- core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java
- core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionThroughExchange.java
- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/HashGenerationOptimizer.java
- core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionThroughExchange.java
- core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushTopNThroughProject.java
Refactoring with the purpose of reducing code duplication.
```markdown
```
> Use `putIdentity` method to reduce code duplication

- core/trino-server/pom.xml
- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
- plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHive.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveBasicStatistics.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConnector.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/PartitionStatistics.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/Partition.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- pom.xml
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java
In the absence of explicit documentation, the use place
(`io.trino.metadata.MetadataManager#listTableColumns`) defines
`streamTableColumns` contract as covering tables only.  This PR also
supplements explicit documentation in `ConnectorMetadata`.
This relates to a logic introduced in `HiveMetadata.doGetTableMetadata`
in aafe4797c34ecad00415691252e1a83b4207efba commit. It was practical for
hive views and when view translation is not enabled, but was not correct
for trino views.
> Fix HiveMetadata.streamTableColumns not to include views

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksInsertCompatibility.java
Fix https://github.com/trinodb/trino/issues/16822
```markdown
* Add support for writing `timestamp with time zone` type on partitioned columns. ({issue}`16822`)
```
> Support writing `timestamp with time zone` type on partitioned column in Delta

- lib/trino-filesystem/src/main/java/io/trino/filesystem/Location.java
- lib/trino-filesystem/src/test/java/io/trino/filesystem/TestLocation.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3NativeTransactionLogSynchronizer.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OriginalFilesUtils.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseS3AndGlueMetastoreTest.java
Alternative approach to https://github.com/trinodb/trino/pull/18155 for obtaining a sibling file location.
Fixes https://github.com/trinodb/trino/issues/17966
```markdown
```
> Support updates when Delta table location has two trailing slashes

- core/trino-main/src/main/java/io/trino/execution/SqlTask.java
This allows for newly created drivers
to get the most recent DFs.
> Add dynamic filter before splits

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableCompatibility.java
> Disallow creating Delta tables partitioned by array, map or row type

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMigrateProcedure.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java
Fixes https://github.com/trinodb/trino/issues/17946
```markdown
* Add support for `tinyint` and `smallint` types in `migrate` procedure. ({issue}`17946`)
```
> Support TINYINT and SMALLINT in migration proceure from hive to iceberg

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableCompatibility.java
Fixes #14001
I will send another PR for `DROP COLUMN` statement. Currently, OSS Delta Lake allows dropping the last data column https://github.com/delta-io/delta/issues/1929
> Disallow creating Delta tables partitioned by all columns

- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
BigQuery has limits on how many snapshots or clones can exist for a single table. It seems BigQuery is miscounting though because we occasionally see errors like below on CI even though all snapshots get dropped by their respective tests:
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
POST https://www.googleapis.com/bigquery/v2/projects/sep-bq-cicd/queries
{
"code": 400,
"errors": [
{
"domain": "global",
"message": "Cannot have more than 1000 active clones and snapshots of a table. Please use a deep copy, or remove some active clones or snapshots.",
"reason": "invalid"
}
],
"message": "Cannot have more than 1000 active clones and snapshots of a table. Please use a deep copy, or remove some active clones or snapshots.",
"status": …
> Fix flaky BigQuery tests using snapshot tables

- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/BaseHudiConnectorSmokeTest.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiConnectorTest.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiCopyOnWriteConnectorSmokeTest.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiCopyOnWriteMinioConnectorSmokeTest.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiMergeOnReadConnectorSmokeTest.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiMergeOnReadMinioConnectorSmokeTest.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/HudiTestUtils.java
> Migrate redundant connector test to smoke test in Hudi

- plugin/trino-hive/pom.xml
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestingHiveConnectorFactory.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestingHivePlugin.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystemAccessOperations.java
> Test S3 request count in Hive connector

- docs/src/main/sphinx/connector/avro-decoder.fragment
- docs/src/main/sphinx/connector/csv-decoder.fragment
- docs/src/main/sphinx/connector/json-decoder.fragment
- docs/src/main/sphinx/connector/kinesis.rst
- docs/src/main/sphinx/connector/raw-decoder.fragment
- docs/src/main/sphinx/connector/redis.rst
Added type mapping section to Kinesis and Redis connector docs.
Additional changes needed that are related to closed PRs:  https://github.com/trinodb/trino/pull/14331 and https://github.com/trinodb/trino/pull/14811.
```markdown
```
> Add type mapping section

- testing/trino-test-jdbc-compatibility-old-driver/bin/run_tests.sh
Update `first_tested_version` to 368 in JDBC driver test to avoid CI timeout. 
> Update `first_tested_version` to 18 month ago in JDBC driver test

- docs/src/main/sphinx/connector/jdbc-case-insensitive-matching.fragment
* Changes the heading level of the `jdbc-case-insensitive-matching.fragment` to be a direct subheading of **Configuration**.
*This fragment is currently nested under the `jdbc-procedures.fragment` but does not seem to be related to that section. If it's just another configuration property, and isn't a type of procedure, we should just nest it under Configuration.
* Heading was previously changed in https://github.com/trinodb/trino/pull/11967
```markdown
```
> Change heading level of case insensitive matching fragment

- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddLocalExchanges.java
- core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddLocalExchangesForTaskScaleWriters.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergOptimize.java
Currently, task writer scaling can lead to file sizes which are not controlled via OPTIMIZE command thus making it unreliable.
```markdown
* Fix `OPTIMIZE` to avoid creating files smaller than `file_size_threshold` due to task writer scaling. ({issue}`18388`)
```
> Disable task level writer scaling from TableExecute

- docs/src/main/sphinx/connector/hive.rst
Correct the sample call for `drop_stats`
The table `example.web.page_views` has a composed partition key, reason why we need `ARRAY[ARRAY[varchar, varchar]]` type for `partition_values` parameter in the `drop_stats` call.
https://github.com/trinodb/trino/blob/e1114ff98cfea94f8e8ca2db0d3a5279bd3b1349/docs/src/main/sphinx/connector/hive.rst?plain=1#L682-L694
```markdown
```
> Use correct value for `partition_values` argument in `drop_stats` sample

- testing/trino-test-jdbc-compatibility-old-driver/bin/run_tests.sh
This reverts #16701 and fixes the step instead. `tested_versions` will be like below:
```
...
tested_versions='352
362
372
382
392
402
412
422'
...
```
> Run JDBC driver compatibility test since 352 with dynamic step

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Fixes https://github.com/trinodb/trino/issues/18408
```markdown
```
> Fix iceberg optimize tests

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
Avoid providing misleading failure cause to the user when trying to drop the statistics for a partition which doesn't exist
```
Caused by: io.trino.spi.TrinoException: Metastore returned multiple partitions for name: p_varchar=partnotfound/p_integer=999
at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.updatePartitionStatistics(ThriftHiveMetastore.java:598)
at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.lambda$updatePartitionStatistics$1(BridgingHiveMetastore.java:136)
at com.google.common.collect.SingletonImmutableBiMap.forEach(SingletonImmutableBiMap.java:68)
at io.trino.plugin.hive.metastore.thrift.BridgingHiveMetastore.updatePartitionStatistics(BridgingHiveMetastore.java:136)
at io.trino.plugin.hive.metastore.HiveMetastore.updatePartitionStatistics(HiveMetast …
```
> Throw meaningful exception when intending to update statistics for missing partition

- docs/src/main/sphinx/sql/create-materialized-view.rst
> Small clarification in materialized views docs.

- docs/src/main/sphinx/connector/hive.rst
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetFileWriterFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetWriterConfig.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkippingWithOptimizedReader.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetWriterConfig.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCompression.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveSparkCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
```markdown
* Remove legacy Parquet writer. The configuration property `parquet.optimized-writer.enabled`
and session property `parquet_optimized_writer_enabled ` no longer exist. The configuration
property `parquet.optimized-writer.validation-percentage` is replaced by
`parquet.writer.validation-percentage`. ({issue}`18420`)
```
> Remove support for legacy Hive Parquet writer

- core/trino-main/src/main/java/io/trino/operator/PagesIndexPageSorter.java
- plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/BaseMariaDbConnectorTest.java
- plugin/trino-resource-group-managers/pom.xml
- pom.xml
> Update various dependencies

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/CoercionUtils.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/TimestampCoercer.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcTypeTranslator.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveCoercionPolicy.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestTimestampCoercer.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnPartitionedTable.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnUnpartitionedTable.java
Allows coerce a varchar type to timestamp in hive tables. 
Depends on https://github.com/trinodb/trino/pull/18004
```markdown
* Add support for varchar to timestamp coercion in hive tables 
```
> Add support for varchar to timestamp coercion in hive tables

- pom.xml
- testing/trino-product-tests/pom.xml
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksDelete.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/utils/DeltaQueryExecutors.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/utils/QueryExecutors.java
This upgrades Delta Lake version to 2.4.0. 
https://github.com/delta-io/delta/releases/tag/v2.4.0
> Install JDBC drivers for Delta product tests at runtime and upgrade `docker-images` to version 81

- plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystemS3.java
- plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHiveFileSystemS3.java
- plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/s3select/TestHiveFileSystemS3SelectPushdown.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/TestCachingDirectoryListerRecursiveFilesOnly.java
The test `testRecursiveDirectoriesWithSpecialCharacters()` is being
moved to `AbstractTestHiveFileSystem` for being able to test it on
multiple object storage file systems.
Contains cherry-pick from https://github.com/trinodb/trino/pull/18167
Fixes #18169
```markdown
```
> Move test to `AbstractTestHiveFileSystem`

- lib/trino-hdfs/src/main/java/io/trino/hdfs/azure/TrinoAzureConfigurationInitializer.java
https://github.com/apache/hadoop/commit/acffe203b8128989a1cde872dc5576c810e5a0f0 introduced logic to ABFS Output streams buffering blocks to disk (by default). This was introduced in Trino during Hadoop upgrade https://github.com/trinodb/trino/commit/343b908499683a75851125846be8eb5d0ca4512d. We want to disable this and stick with the legacy behavior of keeping the blocks in memory
```markdown
* Disable azure's buffer to disk functionality for output streams (write operations).
```
> Disable buffering to disk for Azure output streams

- docs/src/main/sphinx/connector/kudu.rst
- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduClientConfig.java
- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduClientSession.java
- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduSecurityModule.java
- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduSplit.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduClientConfig.java
For now the Hive Connector supports optimized local scheduling when Trino workers are deployed on the same nodes with HDFS, but Kudu doesn't,  which we can see from `KuduSplit.getAddresses()`:  
Kudu scanner clients fetch data from tablet leaders by default, so we add leaders' host addresses from `KuduScanToken` into `KuduSplit` to support this.
```markdown
* Support optimized local scheduling of kudu splits. ({issue}`18121`)
```
> Support optimized local scheduling of kudu splits

- plugin/trino-hive/pom.xml
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/CoralSemiTransactionalHiveMSCAdapter.java
- plugin/trino-iceberg/pom.xml
- pom.xml
- testing/trino-faulttolerant-tests/pom.xml
- testing/trino-product-tests/pom.xml
- testing/trino-tests/pom.xml
Depends on https://github.com/trinodb/trino-coral
> Use shaded version of Coral

- .github/workflows/ci.yml
This is needed to avoid running all product tests in PRs that only change the Iceberg plugin.
> Ignore regular tests when mapping impacted modules for product tests

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeConcurrentModificationGlueMetastore.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastore.java
- plugin/trino-hive/pom.xml
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueClientUtil.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/HiveGlueClientProvider.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
- plugin/trino-iceberg/pom.xml
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/IcebergGlueCatalogModule.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/SkipArchiveRequestHandler.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestingGlueIcebergTableOperationsProvider.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestingIcebergGlueCatalogModule.java
> Add support for OpenTelemetry in Glue metastore

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
Follow-up of #18354
Filed Delta Lake issue at https://github.com/delta-io/delta/issues/1929
> Disallow dropping last non-partition column in Delta Lake

- core/trino-spi/src/main/java/io/trino/spi/security/Identity.java
Removes a redundant `HashSet` copy from `Identity.Builder#withEnabledRoles`
> Remove redundant HashSet from Identity.Builder

- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Add additional checks for access control for queries on materialized views that don't touch underlying data. 
```markdown
```
> Improve access control check for MV

- plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
- plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
Enable Equal/Not Equal and IN  predicate pushdown for varchar/nvarchar columns.
It requires, that column should have case sensitive collation.
https://github.com/trinodb/trino/pull/15714
splited for like predicate https://github.com/trinodb/trino/pull/18441
Trino is able to perform predicate pushdown only for case sensitive varchar/nvarchar columns.
Supported operators: 
- equal
- not equal
- IN
- NOT IN  
User can manually change collation for specific column in MySql to enable such pushdowns.
Collation should be case sensitive (like _CS or _BIN) .
```markdown
* Fix some …
```
> MySql case sensitive collation varchar push down support

- testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Fix redundant whitespace added in https://github.com/trinodb/trino/pull/18371.
The PR was merged after a force push (with github not showing any changes), and after a green build, but apparently there was some glitch in the observations.
> Fix code style error

- core/trino-spi/src/main/java/io/trino/spi/function/ScalarFunctionAdapter.java
- core/trino-spi/src/test/java/io/trino/spi/function/TestScalarFunctionAdapter.java
Improve test coverage of scalar function adapter and fix minor latent bugs.
> Fix scalar function adapter

- core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
- core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
Avoid INTERNAL ERROR (COMPILER_ERROR) when non boolean expression is given as FILTER predicate. With this fix, the error will be USER ERROR (TYPE_MISMATCH).
```sql
select count(*) filter(where 0) from system.runtime.queries;
```
```
io.trino.spi.TrinoException: Compiler failed. Possible reasons include: the query may have too many or too complex expressions, or the underlying tables may have too many columns
at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitScanFilterAndProject(LocalExecutionPlanner.java:2110)
at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:1993)
at io.trino.sql.planner.LocalExecutionPlanner$Visitor.visitProject(LocalExecutionPlanner.java:906)
at io.trino.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
at …
```
> Check type of filter expression at statement analysis

- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/RewriteLikeEscapeWithCaseSensitivity.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/RewriteLikeWithCaseSensitivity.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/expression/BaseTestRewriteLikeWithCaseSensitivity.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/expression/TestRewriteLikeEscapeWithCaseSensitivity.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/expression/TestRewriteLikeWithCaseSensitivity.java
- plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
- plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
LIKE predicate pushdown for varchar/nvarchar columns.
splited from https://github.com/trinodb/trino/pull/18140
```markdown
```
> MySQL LIKE predicate pushdown for varchar/nvarchar columns.

- core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java
- core/trino-main/src/test/java/io/trino/execution/TestTaskManagerConfig.java
A high default for task.partitioned-writer-count and task.scale-writers.max-writer-count
can lead to queries running out of memory more often
Defaults were increased in https://github.com/trinodb/trino/pull/18005 in 422
and found to cause previously working INSERTs to OOM
```markdown
* Reduce defaults for `task.partitioned-writer-count` and `task.scale-writers.max-writer-count` to reduce memory requirements of write queries. ({issue}`18488`)
```
> Reduce max task writer scaling defaults

- lib/trino-array/pom.xml
- lib/trino-cache/pom.xml
- lib/trino-cache/src/main/java/io/trino/cache/NonEvictableCacheImpl.java
- lib/trino-cache/src/main/java/io/trino/cache/NonEvictableLoadingCacheImpl.java
- lib/trino-cache/src/main/java/io/trino/cache/NonKeyEvictableCacheImpl.java
- lib/trino-cache/src/main/java/io/trino/cache/NonKeyEvictableLoadingCacheImpl.java
- lib/trino-filesystem-azure/pom.xml
- lib/trino-filesystem-manager/pom.xml
- lib/trino-filesystem-s3/pom.xml
- lib/trino-filesystem/pom.xml
- lib/trino-filesystem/src/test/java/io/trino/filesystem/TestLocations.java
- lib/trino-hadoop-toolkit/pom.xml
- lib/trino-hive-formats/pom.xml
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/sequence/TestSequenceFileReaderWriter.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/rcfile/AbstractTestRcFileReader.java
- lib/trino-matching/pom.xml
- pom.xml
Ideally whole codebase would be warnings-free.
> Allow no compilation warnings in selected modules

- docs/src/main/sphinx/connector/delta-lake.rst
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableHandle.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeRequireQueryPartitionsFilter.java
For Delta partitioned tables, we should reject the table scan produced by the planner when the query does not have partition field.
```markdown
```
> Optional check for query partition filter for Delta

- docs/src/main/sphinx/admin/properties-general.md
- docs/src/main/sphinx/admin/properties-optimizer.md
- docs/src/main/sphinx/admin/properties-spilling.md
- docs/src/main/sphinx/admin/properties-task.md
- docs/src/main/sphinx/admin/properties-write-partitioning.md
- docs/src/main/sphinx/admin/properties-writer-scaling.md
Remove misleading sentence and use field consistently to document the session property identifier for properties.
Follow up from reviewing docs need for [#18488](https://github.com/trinodb/trino/pull/18488)
> Document session property value consistently

- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
Mitigate testDynamicFiltering* flakiness
`testDynamicFiltering*` reuses global `QueryTracker` state which can
`pruneExpiredQueries()`
`BaseJdbcConnectorTest` is huge. Test methods are executed in parallel.
There could be more than `query.max-history` queries between
`executeWithQueryId` and `SqlQueryManager.getFullQueryInfo` invocations.
Executing `testDynamicFiltering*` methods even in almost single threaded
environment (executing these methods after all other in the test class)
eliminates this issue.
```
    private static final int LAST = 1000;
    @Test(priority = LAST)
```
However, community is not ready to introduce TestNG specific magic as
test ordering via `priority`.
Retrying assertions for unknown reason mitigates this issue as well.
So adding @Flaky to make CI more solid.
(x) …
> Mitigate testDynamicFiltering* flakiness

- core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
- core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
- core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
- core/trino-main/src/test/java/io/trino/sql/query/TestWindow.java
Instead of planning each window function in a separate WindowNode, group them together as long as they have the same window specification.
This helps reduce deep plan trees and simplify the structure of the plan by removing redundant operations (e.g., projections to compute frame bounds, filters to ensure frame bounds are legal, etc.), that make it harder for optimizer rules to match and remove later.
Mitigates https://github.com/trinodb/trino/issues/18491
```markdown
* Improve performance when planning queries involving multiple window functions. ({issue}`18491`)
```
> Improve performance when planning multiple window functions

- core/trino-main/src/main/java/io/trino/server/ResourceGroupInfo.java
- core/trino-main/src/main/java/io/trino/sql/planner/plan/TableScanNode.java
- pom.xml
* Bump Error Prone to 2.21.0
* Enable check: `NullableOptional`
The check enabled is a new one in that release, and it looks like it complements `NullOptional` pretty nicely.
```markdown
```
> Error Prone 2.21.0, NullableOptional check

- plugin/trino-redshift/pom.xml
- plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftQueryFailureRecoverySmokeTest.java
Opt for a smoke test to verify basic functionality of a CTAS statement on the `trino-redshift` connector.
Running all the fault tolerant execution tests on the connector can occasionally lead to timeouts due to the random geographical positioning of the Github CI runner in relation to the ephemeral AWS Redshift instance.
Local test run of the fault tolerant smoke tests completed locally in ~ 4 minutes.
Fixes https://github.com/trinodb/trino/issues/18446
```markdown
```
> Create a fault tolerant execution smoke test for `trino-redshift`

- core/trino-spi/src/main/java/io/trino/spi/security/ConnectorIdentity.java
Removes redundant `HashSet` copy in `ConnectorIdentity.Builder#withEnabledSystemRoles`
> Remove redundant copy in ConnectorIdentity.Builder

- pom.xml
parameternames is not longer used.
> Remove redundant dependency

- core/trino-main/src/main/java/io/trino/server/ui/WebUiStaticResource.java
Remove the following warning caused by an extra `@Path` annotation.
```
pod/trino-coordinator-0: 2023-07-18T14:17:22.055Z	WARN	main	org.glassfish.jersey.internal.Errors	The following warnings have been detected: WARNING: The (sub)resource method getRoot in io.trino.server.ui.WebUiStaticResource contains empty path annotation.
```
For your information,
- https://docs.oracle.com/javaee/7/api/javax/ws/rs/Path.html
- https://stackoverflow.com/questions/33513654/warning-the-subresource-method-contains-empty-path-annotation
> Suppress warning generated by WebUiStaticResource#getRoot

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
This produces not worse error messages and additionally makes it easier to find places where we lowercase e.g. column names.
relates to https://github.com/trinodb/trino/pull/18123
> Remove redundant lowercasing in Delta error messages

- core/trino-main/src/main/java/io/trino/cost/FilterStatsCalculator.java
- core/trino-main/src/test/java/io/trino/cost/TestFilterStatsCalculator.java
- testing/trino-tests/src/test/resources/sql/presto/tpcds/hive/partitioned/q85.plan.txt
Estimate row count when BETWEEN value is an expression
```markdown
* Improve CBO estimates for queries with BETWEEN clause. ({issue}`18501`)
```
> Estimate row count when BETWEEN value is an expression

- core/trino-main/src/main/java/io/trino/sql/analyzer/Analyzer.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestOrderBy.java
ORDER BY without LIMIT / OFFSET is irrelevant unless it's in the top-level query.
Alternative to https://github.com/trinodb/trino/pull/18153
```markdown
* TBD
```
> Remove redundant ORDER BY from WITH and views

- core/trino-main/src/main/java/io/trino/operator/project/PageProcessor.java
- core/trino-main/src/test/java/io/trino/operator/project/TestPageProcessor.java
Orc and parquet readers are configured to produce upto 16MB pages by default.
PageProcessor thresholds should be consistent with orc/parquet readers to avoid
unnecessary reductions in projection processing batch size.
```markdown
```
> Increase PAGE_SIZE_IN_BYTES limits in PageProcessor

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
Small related cleanups for improving code maintainability in `TrinoGlueCatalog`
> Glue catalog cleanup

- docs/src/main/sphinx/connector/blackhole.md
- plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
- plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/TestBlackHoleSmoke.java
- testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
```markdown
* Add support for `COMMENT ON VIEW` statement. ({issue}`18516`)
```
> Add support for comment on view in blackhole connector

- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/BaseKuduConnectorSmokeTest.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestingKuduServer.java
Using 3 tablet servers is overkill and makes the tests take longer. This change reduces the runtime of Kudu tests from 9:40 min to 4 min on an Macbook Pro M1 laptop.
> Use single tablet server replica for Kudu tests

- docs/src/main/sphinx/connector/blackhole.md
Adding view and materialized view support. 
I am not sure we can claim this as correct since ALTER VIEW and ALTER MATERIALIZED view might not be supported.. if that is the case I have to list the supported commands separately.
Caused by missing docs in https://github.com/trinodb/trino/pull/18016
Release notes are already tackled with implementation PR.
> Update SQL support docs for Blackhole

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Fixes https://github.com/trinodb/trino/issues/17436
We have to increase the value from 32MB to 128MB because we have moved from tracking file size to tracking page size in writer scaling.
```markdown
```
> Increase writerScalingMinDataProcessed threshold for scaling test

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeHistoryTable.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePropertiesTable.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
The $history table does not need to lead the entire transaction log when a version filter is supplied.
```markdown
* Improve performance of the $history system table.
```
> Performance improvements for the Delta Lake history system table 

- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/TypeUtils.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
```markdown
* Support predicate pushdown on `char` and `decimal` type. ({issue}`18382`)
```
> Support predicate pushdown on char and decimal type in mongodb

- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
The test failed at https://github.com/trinodb/trino/actions/runs/5793009956/job/15700618792?pr=17477
> Add `@Flaky` annotation to testNonTransactionalMetadataDelete

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
> Extract a method to decide deleting database data in Hive metastore

- pom.xml
No release notes needed
Includes: https://github.com/RoaringBitmap/RoaringBitmap/pull/648
> Update roaringbitmap to 0.9.47

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
> Fix Delta ANALYZE for mixed case columns

- client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java
- core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
- core/trino-main/src/test/java/io/trino/connector/MockConnector.java
- core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
- testing/trino-testing/pom.xml
- testing/trino-testing/src/main/java/io/trino/testing/CountingMockConnector.java
- testing/trino-tests/src/test/java/io/trino/tests/TestInformationSchemaConnector.java
This refactors `TestInformationSchemaConnector.testMetadataCalls` to
leverage `TracingConnectorMetadata` instead of manually performed counts
within `CountingMockConnector. Among other things this exposes
`listViews` calls which were previously not counted.
The differences in expected counts in the test come from the fact how
the counting was done previously. For example
`MockConnectorMetadata.listTables` calls `listSchemaNames` before
`listTables`, so this single metadata call was being recorded as both
`listSchemaNames` and `listTables` (zero or more times).
Extracted from https://github.com/trinodb/trino/pull/18586
> Use tracing for testing ConnectorMetadata invocations 

- core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
- core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java
- core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmenter.java
- core/trino-main/src/test/java/io/trino/cost/TestOptimizerConfig.java
- core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestMultipleDistinctAggregationToMarkDistinct.java
- core/trino-main/src/test/java/io/trino/sql/query/TestDistinctAggregationsNoMarkDistinct.java
- docs/src/main/sphinx/admin/properties-optimizer.md
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
- testing/trino-testing/src/main/java/io/trino/testing/AbstractTestAggregations.java
It has been several months since `optimizer.use-mark-distinct` property was deprecated (as a part of https://github.com/trinodb/trino/pull/15927) so I think we can remove it and rely on the `optimizer.mark-distinct-strategy` only
```markdown
* Remove the deprecated `optimizer.use-mark-distinct` configuration property.
The `optimizer.mark-distinct-strategy`  should be used instead.
```
> Drop deprecated optimizer.use-mark-distinct

- plugin/trino-iceberg/pom.xml
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/CommitTaskData.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergColumnHandle.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMergeSink.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplit.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/IcebergPositionDeletePageSink.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergStatistics.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
This is an alternative to https://github.com/trinodb/trino/pull/18412 but with more minimal changes.
Fixes: https://github.com/trinodb/trino/issues/18393
```markdown
```
> Do not use metadata deletes during Iceberg writes

- .github/workflows/ci.yml
- pom.xml
Errorprone is only needed to impacted modules, not all
dependencies.
https://trinodb.slack.com/archives/CP1MUNEUX/p1691199541970659
> Don't build upstream dependencies with errorprone

- core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
- core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
The following query fails with INTERNAL_ERROR:
```sql
select count(*) filter(where NULL) from system.runtime.queries;
```
Full stacktrace:
```
java.lang.IllegalArgumentException: Predicate must be an expression of boolean type: null
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
at io.trino.sql.planner.plan.FilterNode.<init>(FilterNode.java:48)
at io.trino.sql.planner.optimizations.PredicatePushDown$Rewriter.visitTableScan(PredicatePushDown.java:1579)
at io.trino.sql.planner.optimizations.PredicatePushDown$Rewriter.visitTableScan(PredicatePushDown.java:168)
at io.trino.sql.planner.plan.TableScanNode.accept(TableScanNode.java:222)
at io.trino.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:81)
at …
```
> Coerce boolean type for filter expression

- core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
Removes a (probably) unintentional closing parenthesis in `QueryPlanner#orderingScheme` to make the logical expression grouping clearer and not rely on `&&` vs `||` operator precedence.
> Simplify boolean expression in QueryPlanner

- core/trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
- core/trino-parser/src/test/java/io/trino/sql/TestExpressionFormatter.java
- core/trino-parser/src/test/java/io/trino/sql/TestSqlFormatter.java
- core/trino-parser/src/test/java/io/trino/sql/parser/TestStatementBuilder.java
Fixes #5061
```markdown
* Show original characters for string literals. ({issue}`5061`)
```
> Show original characters for string literals instead of escaping

- core/trino-main/src/main/java/io/trino/operator/scalar/UrlFunctions.java
- core/trino-main/src/test/java/io/trino/operator/scalar/TestUrlFunctions.java
This reverts commit 3befdbb4736b034ca1bd876357ae5294dd426d48 which introduces a backward incompatible change to the behavior of those functions.
The original behavior was intentional, and dates back to when alternatives such as try() didn't exist. Changing their behavior requires more careful consideration and exploration of possible alternatives. If we decide to break compatibility, we may need a way to restore the legacy behavior during the transition.
> Restore original behavior for URI extract functions

- core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
The case where table name is present is handled earlier in the method (`prefix.asQualifiedObjectName().isPresent()` check). The connector is asked to list entities for given schema (or all entities if schema is `Optional.empty`), thus subsequent check for `prefix.matches` was redundant.
> Remove redundant QualifiedTablePrefix.matches checks

- client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java
- core/trino-main/src/main/java/io/trino/metadata/Metadata.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataListing.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
- core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
- core/trino-main/src/main/java/io/trino/tracing/TracingMetadata.java
- core/trino-main/src/test/java/io/trino/connector/MockConnector.java
- core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
- core/trino-main/src/test/java/io/trino/connector/MockConnectorTableHandle.java
- core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
- core/trino-spi/src/main/java/io/trino/spi/connector/RelationColumnsMetadata.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/TrinoCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/TrinoNessieCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogAccessOperations.java
- testing/trino-tests/src/test/java/io/trino/tests/TestInformationSchemaConnector.java
Introduce APIs necessary to implement `information_schema.columns` efficiently and implement it for Iceberg with Glue Catalog. This fully eliminates GetTable calls for individual tables (previously twice for each Glue table), and reduces number of table listings (from 7 to 1).
```
Iceberg
* Improve performance of ``information_schema.columns`` when using Glue catalog.
```
> Accelerate information_schema.columns with bulk retrieval

- plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotBrokerPageSource.java
> Get result iterator in PinotBrokerPageSource constructor

- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcClient.java
- plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
- plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
- plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java
- plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java
- plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
- plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
- plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
- plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
- plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
- plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
- plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
- plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorTest.java
- plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClient.java
- plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
- plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
```markdown
* Add support for `CASCADE` option in `DROP SCHEMA` statement. ({issue}`18305`)
```
> Add support for DROP SCHEMA CASCADE in JDBC connectors

- core/trino-main/src/main/java/io/trino/metadata/Metadata.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
- core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
- core/trino-main/src/main/java/io/trino/tracing/TracingMetadata.java
- core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
- testing/trino-testing/src/main/java/io/trino/testing/TestingConnectorBehavior.java
Extracted from https://github.com/trinodb/trino/pull/18561
```markdown
```
> Remove supportsReportingWrittenBytes from SPI

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
> Remove unused method from DeltaLakeMetadata

- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetCompressor.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetDataOutput.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java
- lib/trino-parquet/src/test/java/io/trino/parquet/ParquetTestUtils.java
- lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
Avoids separate calls to output stream for writing page headers and page data.
Avoids holding on to extra memory for each buffered page due to over-allocation by compressors.
Adds memory usage accounting for buffered pages.
Should help with the memory usage accounting problems described in https://github.com/trinodb/trino/issues/18557
```markdown
* Improve memory usage accounting of parquet writer. ({issue}`18564`)
```
> Use ChunkedSliceOutput to chunk and buffer writes in parquet

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/TrinoViewHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/TrinoViewUtil.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergTableOperations.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/AbstractMetastoreTableOperations.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
A "trino view" and "trino materialized view" need separate handling in
connectors (regardless what philosophical question whether materialized
view is also a view), so let this be expressed on utility function
level.
This changes
- `isTrinoMaterializedView` refactor-only change, no behavioral changes,
- `isPrestoView` - deprecated, replaced with `isTrinoView` which returns
false for materialized views; `isPrestoView` is equivalent of
`isTrinoView || isTrinoMaterializedView`,
- `isHiveOrTrinoView` - deprecated, replaced with `isSomeKindOfAView` which
still returns true for materialized views (but returns false for
Hive's own materialzied view which is treated as an ordinary table by
Trino),
- `isHiveView` - new method.
> Refactor is*View ViewReaderUtil methods 

- core/trino-main/src/main/java/io/trino/security/AccessControl.java
- core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
- core/trino-main/src/main/java/io/trino/security/AllowAllAccessControl.java
- core/trino-main/src/main/java/io/trino/security/DenyAllAccessControl.java
- core/trino-main/src/main/java/io/trino/security/ForwardingAccessControl.java
- core/trino-main/src/main/java/io/trino/security/InjectedConnectorAccessControl.java
- core/trino-main/src/main/java/io/trino/testing/AllowAllAccessControlManager.java
- core/trino-main/src/main/java/io/trino/tracing/TracingAccessControl.java
- core/trino-spi/pom.xml
- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorAccessControl.java
- core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingConnectorAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ReadOnlyAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ReadOnlySystemAccessControl.java
- lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedConnectorAccessControlTest.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/LegacyAccessControl.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
Remove unused checkCanShowRoleAuthorizationDescriptors
> Remove unused checkCanShowRoleAuthorizationDescriptors

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
The assertion was meant to verify at least one delete succeeded, but instead was validating that at least one delete failed.
> Fix assertion in BaseIcebergConnectorSmokeTest

- core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java
- docs/src/main/sphinx/installation/deployment.md
Java changed the default charset to UTF-8 in JEP 400 which is in Java 19
The error message is:
```
Trino requires that the default charset is UTF-8 (found XYZ). This can be set with the JVM command line option -Dfile.encoding=UTF-8
```
```markdown
* The JVM default charset is now required to be UTF-8. This can be set with the JVM command line option -Dfile.encoding=UTF-8. ({issue}`issuenumber`)
```
> Require the JVM default charset is UTF-8

- core/trino-grammar/src/main/antlr4/io/trino/grammar/type/TypeCalculation.g4
> Remove redundant character range in TypeCalculation

- core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
- core/trino-main/src/test/java/io/trino/sql/TestExpressionInterpreter.java
This pr is aimed at optimizing the body expressions in LambdaExpression using existing optimization capabilities.
```markdown
```
> Add a simple optimization of LambdaExpression

- core/trino-main/src/main/java/io/trino/dispatcher/DecoratingListeningExecutorService.java
- core/trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
- core/trino-parser/src/main/java/io/trino/sql/RowPatternFormatter.java
- core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
- core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
- core/trino-parser/src/main/java/io/trino/sql/parser/ErrorHandler.java
- core/trino-parser/src/main/java/io/trino/type/TypeCalculation.java
- core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
- pom.xml
Use enhanced switches, text blocks, etc.
#Release notes
> Update parser to modern Java syntax

- plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
- plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
```markdown
* Add support for `CASCADE` option in `DROP SCHEMA` statement. ({issue}`18663`)
```
> Add support for DROP SCHEMA CASCADE in PostgreSQL

- plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/s3select/S3SelectTestHelper.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Fixes https://github.com/trinodb/trino/issues/18667
Based on https://github.com/trinodb/trino/pull/18669, only two last commits should be reviewed here.
> Fix Hive write to bucketed table when native writers disabled

- client/trino-client/src/main/java/io/trino/client/StatementStats.java
- client/trino-jdbc/src/test/java/io/trino/jdbc/TestProgressMonitor.java
- core/trino-main/src/main/java/io/trino/server/protocol/ProtocolUtil.java
Includes the number of bytes written as part of the HTTP query result statistics.
Resolves https://github.com/trinodb/trino/issues/18651
```markdown
* Add number of bytes written to HTTP query results response. ({issue}`18651`)
```
> Add physicalWrittenBytes to StatementStats

- core/trino-main/src/main/java/io/trino/metadata/DiscoveryNodeManager.java
Avoid unnecessary nested loops O(N*N) on DiscoveryNodeManager#refreshNodesInternal
It does nested loop O(N*N) when services filter out failure nodes on DiscoveryNodeManager#refreshNodesInternal, it's no big deal on small clusters with few nodes, however it consumes quite a lot of cpu cycles on large cluster with over 1000 nodes, that will do 1,000,000 cycles per round of refreshNodeInternal. According to acutal cpu profiling, we found jvm does not optimize the code automatically, so this commit optimize it and avoid nested loop.
```markdown
* Reduce unnecessary nested loops …
```
> Avoid unnecessary nested loop O(N*N) on DiscoveryNodeManager#refreshNodesInternal

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
```markdown
* Add support for `CASCADE` option in `DROP SCHEMA` statement. ({issue}`18689`)
```
> Add support for DROP SCHEMA CASCADE in Iceberg connector

- docs/src/main/sphinx/admin/jmx.md
> Add JMX jvm config info to docs

- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/text/TextLineWriter.java
```markdown
* Fix reporting of written bytes for uncompressed text files. This prevented
the `target_max_file_size` session property from working. ({issue}`18701`)
```
> Fix Hive written bytes reporting for uncompressed text

- docs/src/main/sphinx/connector/delta-lake.rst
- docs/src/main/sphinx/connector/hive.rst
- docs/src/main/sphinx/connector/hudi.rst
- docs/src/main/sphinx/connector/iceberg.rst
- docs/src/main/sphinx/connector/metastores.rst
This PR pulls information from object storage pages and centralizes it.
```markdown
```
> Create object storage metastore page

- plugin/trino-hive/pom.xml
TestFullParquetReader already includes all the tests and it is run in separate test-parquet profile
> Exclude TestParquetReader from default test profile

- client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcVendorCompatibility.java
- docs/src/main/sphinx/connector/postgresql.md
- plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java
- plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupsPostgresqlFlywayMigration.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodePostgresql.java
Postgres 10 is end-of-life and also not available on any cloud providers. 11 will also be end-of-life in November 2023 though it makes sense to test with 11 for some time.
```markdown
* Drop support for Postgres versions older than 11. ({issue}`18696`)
```
> Update tests to oldest supported Postgres version

- plugin/trino-exchange-filesystem/pom.xml
- plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/AbstractTestExchangeManager.java
- plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/TestFileSystemExchangeConfig.java
- plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/TestFileSystemExchangeSource.java
- plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/azure/TestExchangeAzureConfig.java
- plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/s3/TestExchangeS3Config.java
- plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/s3/TestS3FileSystemExchangeManager.java
> Migrate exchange-filesystem to JUnit

- plugin/trino-blackhole/pom.xml
- plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/TestBlackHoleMetadata.java
- plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/TestBlackHoleSmoke.java
> Migrate blackhole tests to JUnit

- plugin/trino-atop/pom.xml
- plugin/trino-atop/src/test/java/io/trino/plugin/atop/TestAtopConnectorConfig.java
- plugin/trino-atop/src/test/java/io/trino/plugin/atop/TestAtopHang.java
- plugin/trino-atop/src/test/java/io/trino/plugin/atop/TestAtopPlugin.java
- plugin/trino-atop/src/test/java/io/trino/plugin/atop/TestAtopSecurity.java
- plugin/trino-atop/src/test/java/io/trino/plugin/atop/TestAtopSmoke.java
- plugin/trino-atop/src/test/java/io/trino/plugin/atop/TestAtopSplit.java
> Migrate atop tests to JUnit

- plugin/trino-elasticsearch/pom.xml
- plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestAwsSecurityConfig.java
- plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearchConfig.java
- plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearchMetadata.java
- plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearchQueryBuilder.java
- plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestPasswordAuthentication.java
- plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestPasswordConfig.java
- plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/client/TestExtractAddress.java
> Migrate Elasticsearch tests to JUnit

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Writer scaling no longer relies on physical written data size
```markdown
```
> Remove writer config overrides in scale writer tests

- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonDeserializer.java
Use a map to look up field names instead of a list.
```markdown
* Improve performance of native Hive JSON reader. ({issue}`18709`)
```
> Improve performance of native Hive JSON reader

- pom.xml
Despite the fact that <packages> child element name can be arbitrary, let's keep it a proper word.
```markdown
```
> Fix typo in the element name

- core/trino-main/src/main/java/io/trino/metadata/Metadata.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
- core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
- core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddLocalExchanges.java
- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java
- core/trino-main/src/main/java/io/trino/sql/planner/plan/TableWriterNode.java
- core/trino-main/src/main/java/io/trino/sql/planner/sanity/ValidateScaledWritersUsage.java
- core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
- core/trino-main/src/main/java/io/trino/tracing/TracingMetadata.java
- core/trino-main/src/test/java/io/trino/connector/MockConnector.java
- core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
- core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
- core/trino-main/src/test/java/io/trino/operator/TestTableWriterOperator.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestingWriterTarget.java
- core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveEmptyMergeWriterRuleSet.java
- core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
- core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesScaledWriters.java
- core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddLocalExchangesForTaskScaleWriters.java
- core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestLimitMaxWriterNodesCount.java
- core/trino-main/src/test/java/io/trino/sql/planner/sanity/TestValidateScaledWritersUsage.java
- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
- core/trino-spi/src/main/java/io/trino/spi/connector/WriterScalingOptions.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
> Add connector SPI for scale writers options

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionConnectorTest.java
Two changes:
- First, We need to use a large table (sf2) to see the
effect. Otherwise, a single writer will write the
entire data before ScaledWriterScheduler is able to
scale it to multiple machines.
- Second, since we now use page size to scale up instead
of physical written bytes, we don't have to test on different
file formats. This reduces the number of tests and overall
runtime.
fixes: https://github.com/trinodb/trino/issues/18670
> Simplify Hive connector scale writers test

- plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/local/LocalFileSystemExchangeStorage.java
- plugin/trino-exchange-hdfs/src/main/java/io/trino/plugin/exchange/hdfs/HadoopFileSystemExchangeStorage.java
When reading slices in HDFS and Local exchange storage, all input streams are not getting closed leading to connection leaks.
```markdown
```
> Close Input Streams in HDFS and Local Exchange storage

- core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
- core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/FaultTolerantPartitioningScheme.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/FaultTolerantPartitioningSchemeFactory.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/HashDistributionSplitAssigner.java
- core/trino-main/src/main/java/io/trino/sql/planner/PlanFragment.java
- core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmentIdAllocator.java
- core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmenter.java
- core/trino-main/src/main/java/io/trino/sql/planner/PlanNodeIdAllocator.java
- core/trino-main/src/main/java/io/trino/sql/planner/RuntimeAdaptivePartitioningRewriter.java
- core/trino-main/src/main/java/io/trino/sql/planner/TopologicalOrderSubPlanVisitor.java
- core/trino-main/src/main/java/io/trino/sql/planner/plan/RemoteSourceNode.java
- core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestPlanFragmentPartitionCount.java
- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/TestOverridePartitionCountRecursively.java
- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveRuntimeAdaptivePartitioningFaultTolerantExecutionAggregations.java
- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveRuntimeAdaptivePartitioningFaultTolerantExecutionJoinQueries.java
- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveRuntimeAdaptivePartitioningFaultTolerantExecutionWindowQueries.java
- testing/trino-testing/src/main/java/io/trino/testing/FaultTolerantExecutionConnectorTestHelper.java
Having high number of partitions hurts the performance of FTE quite seriously, which presents a tradeoff between scalability and performance. This PR tries address this problem by calculating the total input size of each stage at runtime, and change the number of partitions at runtime by inserting extra shuffles to upstream stages.
With this change, users should be able to make the best of both worlds --- majority of the queries can finish with a small partition count efficiently, and those huge queries will still be able to finish with a larger partition count.
TODO:
> Implement runtime adaptive partitioning for FTE

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeChangeDataFeedCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
Make tables with CDF enabled work with column mapping mode enabled
```markdown
* Add support for change data feed with `id` and `name` column mapping mode tables. ({issue}`18611`)
```
> Make CDF compatible with column mapping

- docs/src/main/sphinx/release.md
- docs/src/main/sphinx/release/release-424.md
Assemble the release notes for the upcoming Trino 424 release. Fixes #18638 
* #18640 ✅ rn ✅ docs
* #18570 ✅ rn ✅ docs
* #18592 ✅ rn ✅ docs
* #18559 ✅ rn ✅ docs
* #18641 ✅ rn ✅ docs
* #18646 ✅ rn ✅ docs
* #18648 ✅ rn ✅ docs
* #18624 ✅ rn ✅ docs
* #18471 ✅ rn ✅ docs
* #18639 ✅ rn ✅ docs
* #18657 ✅ rn ✅ docs
* #18556 ✅ rn ✅ docs
* #18057 ✅ rn ✅ docs
* #18652 ✅ rn ✅ docs
* #18663 ✅ rn ✅ docs
* #18493 ✅ rn ✅ docs
* #18588 ✅ rn ✅ docs
* #18669 ✅ rn ✅ …
> Add Trino 424 release notes

- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduClientSession.java
- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java
- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/schema/NoSchemaEmulation.java
- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/schema/SchemaEmulation.java
- plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/schema/SchemaEmulationByTableNameConvention.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/BaseKuduConnectorSmokeTest.java
- plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
Add support for DROP SCHEMA CASCADE in Kudu and MongoDB
```markdown
* Add support for `CASCADE` option in `DROP SCHEMA` statement. ({issue}`issuenumber`)
```
> Add support for DROP SCHEMA CASCADE in Kudu and MongoDB

- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonSerializer.java
Avoids dynamically switching over each field and nested field type for each row of input when writing JSON output files by constructing type specific field writers for each output field and using virtual dispatch instead.
```markdown
* Improve performance of native Hive JSON file writer 
```
> Improve Hive JSON writer performance

- docs/src/main/sphinx/admin/properties-node-scheduler.md
Default value of node-scheduler.include-coordinator property is true but in the documentation it is defined as false which causes confusion specially for multiple node cluster where user don't want coordinator node to act as worker. User have to manually set the value in config.properties to false.
Opened an issue https://github.com/trinodb/trino/issues/18749 for the same
```markdown
```
> Changed the default value of node-scheduler.include-coordinator as TRUE in the documenatation

- plugin/trino-base-jdbc/pom.xml
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DriverConnectionFactory.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcConnectorFactory.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/TracingDataSource.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectionCreation.java
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingDatabase.java
- plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClientModule.java
- plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClientModule.java
- plugin/trino-example-jdbc/src/main/java/io/trino/plugin/example/ExampleClientModule.java
- plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClientModule.java
- plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClientModule.java
- plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClientModule.java
- plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
- plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClientModule.java
- plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
- plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClientModule.java
- plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixConnectorFactory.java
- plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixSplitManager.java
- plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlConnectionFactoryModule.java
- plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlJdbcConnectionCreation.java
- plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClientModule.java
- plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClientModule.java
- plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClientModule.java
Support OpenTelemetry in JDBC connector. Attached the screenshot of SQL Server's example:
> Add support for OpenTelemetry in JDBC connectors

- plugin/trino-cassandra/pom.xml
- plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClientModule.java
- plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraConnectorFactory.java
- plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/ptf/Query.java
- plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Attached the example of tracing:
> Add support for OpenTelemetry in Cassandra connector

- plugin/trino-mongodb/pom.xml
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientModule.java
- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoConnectorFactory.java
Attached the screenshot of the example usage:
> Add support for OpenTelemetry in MongoDB connector

- docs/src/main/sphinx/connector/postgresql.md
Added in general postgreSQL connector configuration in the documentation for support for reading PostgreSQL system tables, e.g., pg_catalog relations. The functionality is disabled by default.
Fixes #15424 
Relates to https://trinodb.slack.com/archives/CGB0QHWSW/p1671165424335919
```markdown
```
> Document `postgresql.include-system-tables` config property

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
> Use smaller scale factor in writer tests

- plugin/trino-oracle/pom.xml
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleConnectorTest.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOraclePoolConnectorSmokeTest.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java
Ability to iterate faster on integration test development for Oracle by adding the support for TESTCONTAINERS_REUSE_ENABLE environment variable.
This is based on previous commit 
https://github.com/trinodb/trino/commit/fbd1de01bba0c896e6e584f26d128452fdf35bc1
by @kokosing, which adds the feature and enables it for SQL Server and MySQL. Based on further comments from @kokosing, enablement of this feature for specific database tests needs to be tested one-by-one as not all test containers seem to digest that change without problems. This justifies adding it iteratively for selected databases based on a need-to-use basis. …
> Allow re-using Oracle container in tests

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
```markdown
* Support `CASCADE` option for `DROP SCHEMA` statement. ({issue}`18320`)
```
> Support `CASCADE` option for `DROP SCHEMA` statement in Hive

- core/trino-main/src/main/java/io/trino/operator/BigintGroupByHash.java
- core/trino-main/src/main/java/io/trino/operator/ChannelSet.java
- core/trino-main/src/main/java/io/trino/operator/FlatGroupByHash.java
- core/trino-main/src/main/java/io/trino/operator/FlatSet.java
- core/trino-main/src/main/java/io/trino/operator/GroupByHash.java
- core/trino-main/src/main/java/io/trino/operator/HashSemiJoinOperator.java
- core/trino-main/src/main/java/io/trino/operator/MultiChannelGroupByHash.java
- core/trino-main/src/main/java/io/trino/operator/NoChannelGroupByHash.java
- core/trino-main/src/main/java/io/trino/operator/SetBuilderOperator.java
- core/trino-main/src/test/java/io/trino/operator/CyclingGroupByHash.java
- core/trino-main/src/test/java/io/trino/operator/TestGroupByHash.java
- core/trino-main/src/test/java/io/trino/operator/TestHashSemiJoinOperator.java
Convert ChannelSet used in SemiJoinOperator from GroupByHash to the new FlatSet.  The FlatSet is deisgned for the single write, multi-threaded read that ChannelSet uses. The FlatSet is much simpler as it only needs to hold a single column, and only needs to support a contains check, which vastly simplifies the implementation. 
This effectivly splits the use cases of GroupByHash, so the contains methods can be used.
Fixes #18752
> Add FlatSet for semi join

- client/trino-cli/src/main/java/io/trino/cli/AlignedTablePrinter.java
- client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
- client/trino-cli/src/main/java/io/trino/cli/CsvPrinter.java
- client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java
- client/trino-cli/src/main/java/io/trino/cli/JsonPrinter.java
- client/trino-cli/src/main/java/io/trino/cli/MarkdownTablePrinter.java
- client/trino-cli/src/main/java/io/trino/cli/Query.java
- client/trino-cli/src/main/java/io/trino/cli/TsvPrinter.java
- client/trino-cli/src/main/java/io/trino/cli/VerticalRecordPrinter.java
- client/trino-cli/src/test/java/io/trino/cli/TestMarkdownTablePrinter.java
- docs/src/main/sphinx/client/cli.md
Add Markdown output to avoid having to use external tools like `csv2md`.
Example usage:
```bash
./client/trino-cli/target/trino-cli-419-SNAPSHOT-executable.jar --output-format MARKDOWN \
--execute="select * from (values (1234567, 'some longer strin'), (123, 'aa')) as t(one, two)"
```
Prints:
```
|     one | two               |
| -------:| ----------------- |
| 1234567 | some longer strin |
|     123 | aa                |
```
where the default `ALIGNED` format looks like:
```
one   |        two        
---------+-------------------
1234567 | some longer strin 
123 | aa                
(2 rows)
``` …
> Add Markdown output format to the CLI

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Use random table names in tests
> Use random table names in tests

- .github/workflows/ci.yml
- core/trino-main/src/main/java/io/trino/execution/TaskId.java
This is suppose to mitigate #18272 when running on JDK 20 and 21-ea with `-XX:+CompactStrings` enabled (the default).
The bug report was submitted to JDK and we are waiting for triage.
```markdown
```
> Change TaskId.fullId creation to mitigate probable JDK bug

- plugin/trino-accumulo/pom.xml
- plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloClient.java
- plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/index/TestIndexer.java
- plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/model/TestAccumuloSplit.java
- plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/model/TestField.java
- plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/model/TestRow.java
- plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/model/TestSerializedRange.java
- plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/serializers/AbstractTestAccumuloRowSerializer.java
> Migrate Accumulo tests to JUnit

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeDelete.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDeleteCompatibility.java
Perform DELETE only on the metadata of the Delta Lake
table when the delete filter does not touch any data
columns.
Sample queries affected by this enhancement are:
```
DELETE FROM table 
DELETE FROM table WHERE true
DELETE FROM partitioned_table WHERE part1=value1 AND part2=value2
DELETE FROM partitioned_table WHERE part2=value2
```
Fixes #18331
The operation will not be performed on the metadata layer when
there are `add` file entries in the transaction log of the table
without statistics containing number of records.
Without `DELETE` pushdown
```
trino:default> create table delta.tiny.sforders100 as select * from tpch.sf100.orders;
CREATE TABLE: 150000000 rows
trino:default> delete from delta.tiny.sforders100 where true;
DELETE: 150000000 rows
Query 20230725_125258_00003_xfv9h, …
```
> Push down DELETE for enforceable filters on Delta Lake

- lib/trino-parquet/src/main/java/io/trino/parquet/ParquetEncoding.java
- lib/trino-parquet/src/main/java/io/trino/parquet/dictionary/BinaryDictionary.java
- lib/trino-parquet/src/main/java/io/trino/parquet/dictionary/Dictionary.java
- lib/trino-parquet/src/main/java/io/trino/parquet/dictionary/DictionaryReader.java
- lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/AbstractValueDecodersTest.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/DictionaryReader.java
Minor cleanups in parquet reader to reduce usage of org.apache.parquet.io.api.Binary
> Reduce usage of org.apache.parquet.io.api.Binary

- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSource.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
```markdown
* Fix failure when reading negative zero in `decimal` type. ({issue}`18777`)
```
> Support reading negative zero in MongoDB

- core/trino-main/src/main/java/io/trino/metadata/Metadata.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
- core/trino-main/src/main/java/io/trino/tracing/TracingMetadata.java
- core/trino-main/src/test/java/io/trino/execution/BaseDataDefinitionTaskTest.java
- core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
- docs/src/main/sphinx/connector/blackhole.md
- plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
- plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/TestBlackHoleSmoke.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/TrinoCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/TrinoNessieCatalog.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
- testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Some clean ups for this PR https://github.com/trinodb/trino/pull/18016
Correct method order, test adjustments
refactor test access control MV column comment to use mock connector
remove blackhole MV support
```markdown
* Remove materialized view support 
```
> Post merge clean up for materialized view column comment

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveCreateExternalTable.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveS3AndGlueMetastoreTest.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite2.java
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hdfs-impersonation/hive.properties
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hive-impersonation/hive.properties
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-impersonation-cross-realm/hive.properties
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-impersonation-with-wire-encryption/hive.properties
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-impersonation/hive.properties
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hdfs-no-impersonation/hive.properties
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hive-impersonation-with-credential-cache/hive.properties
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hive-impersonation/hive.properties
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kerberos-hive-no-impersonation-with-credential-cache/hive.properties
- testing/trino-product-tests/src/main/java/io/trino/tests/product/TestImpersonation.java
Create directory structure if it's not exists.
external location will be created if `writesToNonManagedTablesEnabled` flag is set
The same behaviour is on pure Hive as mentioned in  https://github.com/trinodb/trino/pull/17920#issuecomment-1597014375
With current change - external location will be created for Hive tables if flag hive.non-managed-table-writes-enabled is set,
otherwise exception will raised as it was before.
```markdown
* Create an empty directory if the external location doesn't exist
```
> Create external table location for Hive

- core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
Otherwise, a deadlock scenario is possible as `REFRESH MATERIALIZED VIEW` may take all the memory of the node, and the CTAS query it depends on might get stuck.
```markdown
```
> Set defaultTaskMmeory to 0 for REFRESH MATERIALIZED VIEW

- pom.xml
> Update testcontainers to 1.19.0

- core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
FunctionMetadata should only be fetched on the coordinator, as workers do not have FunctionMetadata for all functions.  The ExpressionAnalyzer issues warnings for deprecated functions, but this creates problems since the expression analyzer is also run on worker.  The PR works around this problem by only checking for deprecation when the `WarningCollector` is not the `NOOP` implementation.  Since the worker exclusively uses the `NOOP` collector, this effectively disables the code on workers.
Fixes #17661 
> Disable function deprecation checks on workers

- client/trino-cli/src/main/java/io/trino/cli/AlignedTablePrinter.java
- client/trino-cli/src/main/java/io/trino/cli/MarkdownTablePrinter.java
- client/trino-cli/src/test/java/io/trino/cli/TestAlignedTablePrinter.java
- client/trino-cli/src/test/java/io/trino/cli/TestMarkdownTablePrinter.java
This is only a refactor, there are no functional changes here. A follow-up to #17697
> Use more descriptive variable names in CLI table printers

- core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2ServiceModule.java
For some of the identity providers the default buffer sizes are too small to work out of the box, when authentication tokens size exceeds the default request buffer size of 4KB.
In these cases the default configuration will fail with:
```
io.trino.server.security.oauth2.NimbusAirliftHttpClient Received bad response from endpoint java.lang.IllegalArgumentException: Request header too large
at org.eclipse.jetty.client.http.HttpSenderOverHTTP$HeadersCallback.process(HttpSenderOverHTTP.java:182)
at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:232)
at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:214)
at org.eclipse.jetty.client.http.HttpSenderOverHTTP.sendHeaders(HttpSenderOverHTTP.java:79)
at …
```
> Increase default response/request buffer size for OAuth2 client

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
Fixes #18661
```markdown
* Fix writing incorrect transaction log in case of partitioned tables with `id` or `name` column mapping mode. ({issue}`18661`)
```
> Store physical partition name in Delta CREATE TABLE AS SELECT

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDeleteCompatibility.java
Fixes #18786
```markdown
* Add support for `TRUNCATE TABLE` statement. ({issue}`18786`)
```
> Add support for TRUNCATE TABLE statement in Delta Lake

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
```markdown
* Support `CASCADE` option for `DROP SCHEMA` statement. ({issue}`18333`)
```
Fixes #18333
> Support `CASCADE` option for `DROP SCHEMA` statement in Delta Lake

- core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
- core/trino-main/src/test/java/io/trino/connector/MockConnector.java
- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
- plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloMetadata.java
```markdown
* Remove deprecated `io.trino.spi.connector.ConnectorMetadata#dropSchema(ConnectorSession session, String schemaName)` method. ({issue}`18839`)
```
> Remove deprecated `ConnectorMetadata.dropSchema` method from SPI

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/SortingFileWriter.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Hive and Iceberg use the written bytes value to determine when a new file should be started. Without this value the `target-max-file-size` config property is ignored.
While writing, the returned value is an approximation. However, an accurate value is returned after the writter commits.
Doing this does reduce the sort window to one file rather than all the data the PageSink receives. Broadening the sort window while also splitting files into the right size can be done as follow up.
Fixes: https://github.com/trinodb/trino/issues/18653
Sorted writes added to Iceberg: https://github.com/trinodb/trino/pull/14891
(x) Release notes are required, …
> Approximate written bytes in Hive and Iceberg sorted writers

- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
- This PR fixes an issue where the query output columns were incorrectly not returning source columns for UPDATE statements with subqueries. For example:
```
UPDATE catalog.schema.test_table SET output_column = (SELECT test_column FROM catalog.schema.test_alt_table)
```
This query should set `test_alt_table.test_column` as a source column of `test_table.output_column`
```markdown
* Fix event listener to capture source columns for UPDATE statements with subqueries.
```
> Fix column lineage for UPDATE statements with subqueries

- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/TrinoDataInputStream.java
```markdown
* Fix reading large SequenceFile, RCFile, or Avro files. ({issue}`18837`)
```
Fixes https://github.com/trinodb/trino/issues/17890
> Fix reading large SequenceFile, RCFile, or Avro files

- core/trino-parser/src/main/java/io/trino/sql/jsonpath/PathParser.java
- core/trino-parser/src/main/java/io/trino/sql/parser/SqlParser.java
- core/trino-parser/src/main/java/io/trino/type/TypeCalculation.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ExpressionMappingParser.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionParser.java
> Fix parser fallback to LL mode

- docs/src/main/sphinx/connector/delta-lake.md
- docs/src/main/sphinx/connector/object-storage-file-formats.md
Removed docs in Delta Lake connector and moved to the new page that applies to all Parquet usage.
Follow up to https://github.com/trinodb/trino/pull/17510
> Remove duplicate property documentation

- docs/src/main/sphinx/admin/resource-groups.md
Fix wrong scheduling policy name from `weight` to `weighted`
> Fix wrong scheduling policy name from weight to weighted

- plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHive.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveBasicStatistics.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/PartitionStatistics.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Fixes https://github.com/trinodb/trino/issues/18798
The problem is specific to hive metastore and newer versions of HMS have fixed this https://issues.apache.org/jira/browse/HIVE-19254
```
* Fix failure in ANALYZE when row count stats are missing. ({issue}`18798`)
```
> Fix hive ANALYZE when row count stats are missing

- core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaMetadata.java
- testing/trino-tests/src/test/java/io/trino/tests/TestInformationSchemaConnector.java
When reading `information_schema.columns` with a filter on table name (either `=` or `IN`), the code was doing
`getRedirectionAwareTableHandle` call to check whether target table exists. However, the redirected tables are handled in `doListTableColumns` (also catching `TABLE_REDIRECTION_ERROR`), so the call inside `calculatePrefixesWithTableName` is redundant.
> Skip getTableHandle call in information_schema.columns with table filter

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveLocal.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveInMemoryMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/CountingAccessHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/InMemoryThriftMetastore.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
`AbstractTestHiveLocal` doesn't run some of `AbstractTestHive` tests
because it doesn't run setup. This sets up two tables, so that more
tests can be run. More setup to come.
> Enable more Hive metastore tests

- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryTestView.java
- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryViewCreateAndInsertDataSetup.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoCreateAndInsertDataSetup.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoTestTable.java
- plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleConnectorTest.java
- plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/PhoenixSqlExecutor.java
- plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/PhoenixTestTable.java
- testing/trino-testing/src/main/java/io/trino/testing/datatype/CreateAndInsertDataSetup.java
- testing/trino-testing/src/main/java/io/trino/testing/sql/SqlExecutor.java
- testing/trino-testing/src/main/java/io/trino/testing/sql/TestTable.java
Use single INSERT instead of multiple single-row inserts. Should be
faster, especially e.g. for Trino.
> Populate TestTable with multi-row INSERT

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeTransactionLogCache.java
The test purpose is verifying the behavior about remote changes.
OSS Delta Lake is sufficient.
Relates to #18805
> Don't run TestDeltaLakeTransactionLogCache in Databricks

- core/trino-main/src/main/java/io/trino/operator/PagesRTreeIndex.java
- plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestSpatialJoins.java
The failure started happening with the update to fastutil 8.5.12 in 5e9bb46e0a48fe94c1a7e0f9b726e1020a94c85b
Fixes #18860 
```markdown
* Fix failure when performing an outer join involving geospatial functions in the join clause. ({issue}`18860`)
```
> Fix NPE for spatial left join

- core/trino-main/src/main/java/io/trino/operator/aggregation/state/LongDecimalWithOverflowAndLongStateSerializer.java
- core/trino-main/src/main/java/io/trino/operator/aggregation/state/LongDecimalWithOverflowStateSerializer.java
Slice allocations in `Type#getSlice` cause significant CPU overhead on some decimal aggregation queries
```markdown
* Improve performance of decimal aggregations. ({issue}`18868`)
```
> Avoid Slice allocations in decimal aggregation

- core/trino-main/src/main/java/io/trino/connector/system/MaterializedViewSystemTable.java
- core/trino-main/src/main/java/io/trino/connector/system/TableCommentSystemTable.java
- Make table definitions public
- Extract materializedViewForCatalog() method so it can be reused
- Extract tableCommentForCatalog() so that it can be reused
n/a
> Make some table definitions public

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java
Fixes https://github.com/trinodb/trino/issues/18799
```markdown
```
> Flip the `TABLE_COMMENT` table parameter value comparison

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
Relates to https://github.com/trinodb/trino/pull/18847#issuecomment-1700424909
> Fix javadoc links

- plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotGrpcDataFetcher.java
bugfix fro trino-pinot connector
We maintain several Pinot Clusters. And some of clients use Trino as query engine due to the limitation of pinot (join or sub-query). And Trino Cluster enabled grpc to increase the speed of fetching data. But in some scenarios, some of clients report some incidents. Although the query is successful, They still couldn't fetch completed query result. We found some error log s about trino grpc that indicates some of servers didn't give the completed result. So we change trino codes to report error when pinot query result comes with exceptions, such timetoutexception.
So it can notify clients query result uncompleted which would drive clients to query again.
Please trino team help me to review.
> Throw exceptions when pinot grpc query incomplete

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeRedirect.java
Test against Delta Lake OSS gives enough certainty for the accuracy
of the Delta Lake connector.
> Do not run Hive and Delta compatibility tests on Databricks

- docs/src/main/sphinx/security/inspect-pem.md
- docs/src/main/sphinx/security/tls.md
Specifically add that password protected PEM files are not supported.
FYI [jdsjdk](https://github.com/jdsjdk)
Result of discussion in https://github.com/trinodb/trino/issues/17300
> Updated docs for PEM format support

- docs/src/main/sphinx/connector/hive.md
The current documentation is not explicit about any recommendation. I think it is fair to add the suggested paragraph. This keeps coming up in conversations with user as not being clear.
In addition I think we might have to update some of the limitations in the section about experimental mode .. but I am not sure about details.
Also ... could we rename the experimental mode to some other name?
> Add recommendation for Hive views

- core/trino-main/src/main/java/io/trino/sql/planner/LookupSymbolResolver.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
When the expression evaluated by LayoutConstraintEvaluator contains a lambda expression, it's incorrect to attempt to resolve a reference to a lambda expression argument as if it were a column.
Fixes #18865 
```markdown
* Fix failure when querying partitioned tables and the `WHERE` clause contains lambda expressions. ({issue}`18865`)
```
> Fix incorrect symbol resolution during predicate pushdown

- core/trino-main/src/test/java/io/trino/type/TestIntegerVarcharMapType.java
- core/trino-main/src/test/java/io/trino/type/TestSmallintVarcharMapType.java
- core/trino-main/src/test/java/io/trino/type/TestTinyintVarcharMapType.java
- core/trino-main/src/test/java/io/trino/type/TestVarcharArrayType.java
- core/trino-main/src/test/java/io/trino/type/TestVarcharVarcharMapType.java
- core/trino-spi/src/main/java/io/trino/spi/type/ArrayType.java
- core/trino-spi/src/main/java/io/trino/spi/type/MapType.java
- core/trino-spi/src/main/java/io/trino/spi/type/RowType.java
The MAP and ARRAY types were incorrectly adjusting the pointer for the variable width data by the fixed width size of the type.  Since the variable width and fixed with data are kept in different sections of the flat record, the adjustment is not needed and causes failures.
Fixes #18863
```markdown
* Fix index out of bounds exceptions in flat memory data structures using MAP and ARRAY types. ({issue}`18863`)
```
> Fix MAP and ARRAY flat write

- testing/trino-tests/src/test/java/io/trino/sql/planner/BaseCostBasedPlanTest.java
Fixes https://github.com/trinodb/trino/issues/18702. PR presents a workaround for differences in point arithmetic between ARM and x86. Change of single parameter reduce significantly differences in estimation of row output count by optimizer during enumeration of joins. 
```markdown
```
> Fix for Flaky TestIcebergParquet*TpcdsCostPlan for Q85

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueToTrinoConverter.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/util/Memoizers.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogAccessOperations.java
SerdeInfo is optional table field in Glue.
> Avoid NPE when Glue table SerdeInfo missing

- core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
- core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
- core/trino-main/src/main/java/io/trino/sql/planner/plan/GroupIdNode.java
Previously, `GroupIdNode` grouping set and output symbol orderings were potentially unstable for the same logical sub-plan due to the use of set constructions that were not order-preserving. While this did not affect correctness, it could result in different symbol orderings within grouping sets in differing branches of `UNION ALL` operations with the same query on both sides. For example, a query like:
```
(SELECT
shippriority, custkey, sum(totalprice)
FROM
orders
GROUP BY ROLLUP (shippriority, custkey))
UNION ALL
(SELECT
shippriority, custkey, sum(totalprice)
FROM
orders
GROUP BY ROLLUP (shippriority, custkey))
```
could result in logical plans with GroupIdNode grouping sets of either:
1. [[],[“tpch:shippriority$gid”],[“tpch:shippriority$gid”,“tpch:custkey$gid”]]
2. …
> Use stable grouping set symbol orderings

- .github/workflows/ci.yml
- docs/src/main/sphinx/connector/delta-lake.md
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeDatabricks133.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLakeDatabricks133.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java
```markdown
* Add support for [Databricks 13.3 LTS](https://docs.databricks.com/en/release-notes/runtime/13.3lts.html). ({issue}`issuenumber`)
```
> Add support for 13.3 LTS in Delta Lake connector

- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/table/HudiTableFileSystemView.java
In case of a Hudi metadata corruption during reading replace commits, the exact exception is not logged in the error message, making it difficult to diagnose the actual problem. This PR aims to fix that with a very small code extension.
When the filesystem view for a Hudi table is assembled in the Trino Hudi connector, replace commits need to be collected so that data is not read multiple times by the system. During this operation Hudi metadata for these commits is accessed and when it is not readable, the error message does not tell the actual reason. This PR is aiming to fix that. …
> Add causing exception to Hudi metadata parsing error

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestHiveMetastoreAccessOperations.java
Same logic as implemented in Iceberg. This should make certain
operations faster.
> Implement schemaExists for Hive

- docs/src/main/sphinx/installation/deployment.md
CI and Docker recently changed and documentation was accidentally left unchanged.
* https://github.com/trinodb/trino/pull/17685
* https://github.com/trinodb/trino/blob/398b64671cc2ecc1c23556d80eb20f29c4eca5eb/core/docker/Dockerfile#L17
```markdown
* Change recommended Java runtime distribution to Eclipse Temurin. ({issue}`18886`)
```
> Recommend Eclipse Temurin as Java runtime

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDeleteCompatibility.java
> Use 'contains' method in deletion vector tests

- core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java
- core/trino-main/src/main/java/io/trino/metadata/Metadata.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
- core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
- core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
- core/trino-main/src/main/java/io/trino/tracing/TracingMetadata.java
- core/trino-main/src/test/java/io/trino/connector/MockConnector.java
- core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
- core/trino-main/src/test/java/io/trino/execution/TestCreateTableColumnTypeCoercion.java
- core/trino-main/src/test/java/io/trino/execution/TestCreateTableTask.java
- core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
- plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
- plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
- plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlTypeMapping.java
Allow connectors to specify the actual Trino types that will be persisted and let the engine applies coercions as necessary.
The behaviour around type coercion and casts in a CREATE TABLE is different from the CTAS. For example: the user created a table with TIMESTAMP(6). On insert the table type is compared to the query type and casts or coercions from the same type are applied upon the supplied values (resulting in rounding if necessary)
```
create table catalog.default.test (a TIMESTAMP(6));
insert into catalog.default.test values TIMESTAMP '9999-12-31 23:59:59.999999999';
-- no error
select a from catalog.default.test;
-- value is rounded
```
In this PR similar logic is applied upon CTAS statements through distinguishing between the target table type and the query type. By default the …
> Support automatic type coercion for table creation

- .github/workflows/ci.yml
- .github/workflows/docs.yml
- .github/workflows/milestone.yml
> Update actions/checkout to v4

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
> Test checkpoint parquet file access count in Delta

- plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/BaseCassandraConnectorSmokeTest.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
> Remove redundant case from Cassandra and MongoDB tests

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeChangeDataFeedCompatibility.java
The remaining test cases cover column mapping mode with UPDATE, DELETE, MERGE, non-lowercase columns and partitioned table.
Relates to #18805
> Reduce column mapping mode usage in CDF tests

- core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
- core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
- core/trino-main/src/test/java/io/trino/dispatcher/TestLocalDispatchQuery.java
- core/trino-main/src/test/java/io/trino/execution/TestCommitTask.java
- core/trino-main/src/test/java/io/trino/execution/TestDeallocateTask.java
- core/trino-main/src/test/java/io/trino/execution/TestPrepareTask.java
- core/trino-main/src/test/java/io/trino/execution/TestQueryStateMachine.java
- core/trino-main/src/test/java/io/trino/execution/TestStartTransactionTask.java
- core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java
- core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java
- core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
- core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControlFactory.java
This is necessary for SystemAccessControl implementation to participate in tracing. Useful when the implementation does e.g. network communication when performing access control.
> Pass OpenTelemetry to SystemAccessControl

- plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryCaseInsensitiveMapping.java
Since #18730 metadata listing does not longer call getTableHandle so when listing columns or tables in BigQuery connector, ambiguous objects are filtered out.
Fixes https://github.com/trinodb/trino/issues/18889 and makes master happy :)
> Fix BigQuery metadata listing for ambiguous table names

- docs/src/main/sphinx/language/reserved.md
- docs/src/main/sphinx/language/types.md
- docs/src/main/sphinx/sql.md
- docs/src/main/sphinx/sql/comment.md
- docs/src/main/sphinx/sql/comments.md
Document lexical structure and add necessary updates to other pages. We should talk about how to proceed @martint since I believe the linked page for reserved keywords is also wrong by now and there are other things I have questions about how we want to document all this. 
* Triggered by #17776
* Replaces #18000 
> Expand docs for lexical structure

- core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
- core/trino-main/src/main/java/io/trino/server/testing/FactoryConfiguration.java
- core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
- core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
- testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
- testing/trino-tests/src/test/java/io/trino/execution/TestSetSessionAuthorization.java
- testing/trino-tests/src/test/java/io/trino/execution/TestUserImpersonationAccessControl.java
- testing/trino-tests/src/test/java/io/trino/security/TestFunctionsInViewsWithFileBasedSystemAccessControl.java
Provide tests with ability to use AccessControlManager's built-in access
control factory by its name. This provides coverage for factory
registration (otherwise possible only in product tests), and also allow
factories to take injected dependencies (e.g. for tracing).
> Allow tests to choose builtin access control factory

- docs/src/main/sphinx/release.md
- docs/src/main/sphinx/release/release-426.md
Assemble the release notes for the upcoming Trino 426 release. Fixes #18802 
* #18807 ✅ rn ✅ docs
* #18810 ✅ rn ✅ docs
* #18804 ✅ rn ✅ docs
* #18813 ✅ rn ✅ docs
* #18783 ✅ rn ✅ docs
* #18825 ✅ rn ✅ docs
* #18274 ✅ rn ❌ docs
* #18834 ✅ rn ✅ docs
* #18717 ✅ rn ✅ docs
* #18827 ✅ rn ✅ docs
* #18836 ✅ rn ✅ docs
* #18729 ✅ rn ✅ docs
* #18784 ✅ rn ✅ docs
* #18662 ✅ rn ✅ docs
* #18788 ✅ rn ✅ docs
* #18333 ✅ rn ✅ docs
* #18840 ✅ rn ✅ docs
* #18839 ✅ rn ✅ …
> Add Trino 426 release notes

- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnPartitionedTable.java
Additional coercion test coverage for Sequence file
> Add coercion test coverage for Sequence file

- core/trino-spi/src/main/java/io/trino/spi/predicate/SortedRangeSet.java
`SortedRangeSet.buildFromUnsortedRanges` constructs and returns instance of `SortedRangeSet` where field `sortedRanges` is an instance of `BlockBuilder`. Change this field to be instance of `Block`.
(*) This is not user-visible or is docs only, and no release notes are required.
> Fix return value from SortedRangeSet.buildFromUnsortedRanges

- core/trino-main/src/main/java/io/trino/connector/system/TableCommentSystemTable.java
- core/trino-main/src/test/java/io/trino/connector/MockConnector.java
- core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
- testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Consult access control when getting comments for redirected tables.
Fixes https://github.com/trinodb/trino/issues/18514
```markdown
* Added access control check to redirected tables when getting comments. ({issue}`#18514`)
```
> Use access control to filter out redirected tables

- core/trino-main/src/main/java/io/trino/execution/executor/dedicated/ThreadPerDriverTaskExecutor.java
In the thread-per-driver executor, splits were being added but not removed upon completion.
> Remove split when finished

- lib/trino-filesystem-azure/pom.xml
- lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemFactory.java
Switch to using the OkHttp client for the AzureFileSystem as it is lighter weight and serves the same purpose as the netty http client that is currently being used
> Use OkHttp client in AzureFileSystem

- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/csv/CsvDeserializerFactory.java
- lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/csv/TestCsvFormat.java
Hive has a bug that changes the escape character to backslash when it is explicitly set to a double quote during deserialization.  The native CSV reader is a bug for bug compatible reimplementation of the Hive OpenCSV reader, so this behavior must be replicated.
Fixes #18918 
```markdown
* Fix incompatibility with Hive OpenCSV deserialization.  When escape character is explicitly set to double quote, a backslash must be used instead. ({issue}`18918`)
```
> Change Hive CSV escape character to backslash when set to double quote

- core/trino-main/src/main/java/io/trino/connector/system/TableCommentSystemTable.java
- core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
Avoid logging for e.g. tables concurrently deleted.
> Ignore external errors when listing table columns/comments

- core/trino-main/src/main/java/io/trino/execution/executor/dedicated/ThreadPerDriverTaskExecutor.java
- core/trino-main/src/main/java/io/trino/execution/executor/scheduler/BlockingSchedulingQueue.java
- core/trino-main/src/main/java/io/trino/execution/executor/scheduler/FairScheduler.java
- core/trino-main/src/main/java/io/trino/execution/executor/scheduler/SchedulingQueue.java
- core/trino-main/src/main/java/io/trino/execution/executor/scheduler/TaskControl.java
- core/trino-main/src/test/java/io/trino/execution/executor/scheduler/TestFairScheduler.java
Tasks were not being removed from the FairScheduler scheduling queue upon completion. They were only being removed when the scheduling group was terminated.
> Cleanup scheduled tasks on completion

- core/trino-main/src/main/java/io/trino/metadata/MetadataListing.java
- core/trino-main/src/main/java/io/trino/security/AccessControl.java
- core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
- core/trino-main/src/main/java/io/trino/security/AllowAllAccessControl.java
- core/trino-main/src/main/java/io/trino/security/DenyAllAccessControl.java
- core/trino-main/src/main/java/io/trino/security/ForwardingAccessControl.java
- core/trino-main/src/main/java/io/trino/security/InjectedConnectorAccessControl.java
- core/trino-main/src/main/java/io/trino/security/ViewAccessControl.java
- core/trino-main/src/main/java/io/trino/testing/AllowAllAccessControlManager.java
- core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
- core/trino-main/src/main/java/io/trino/tracing/TracingAccessControl.java
- core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorAccessControl.java
- core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingConnectorAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ReadOnlyAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ReadOnlySystemAccessControl.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/LegacyAccessControl.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
Refactor information_schema.columns handling code.
> Filter table columns in bulk

- core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
- core/trino-main/src/main/java/io/trino/security/SecurityContext.java
- core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java
- core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
- core/trino-spi/pom.xml
- core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java
- core/trino-spi/src/main/java/io/trino/spi/security/SystemSecurityContext.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/DefaultSystemAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java
- lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ReadOnlySystemAccessControl.java
- lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedSystemAccessControlTest.java
Before the change, `SystemSecurityContext` was provided to every method in `SystemAccessControl`. This was problematic for implementations which need to be query-aware (e.g. for audit or caching purposes), because there was no type system support helping to determine whether ID is present or not. This commit makes `SystemSecurityContext.queryId` non-optional. For methods where query ID is not passed, simple `Identity` is now passed, since this is the only other field in the `SystemSecurityContext`. This is a breaking change because doing it in backwards compatible way would be quite laborious.
> Distinguish SystemAccessControl methods not exposing query id

- .github/workflows/ci.yml
- lib/trino-filesystem-azure/pom.xml
- lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemBlob.java
- lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemGen2Flat.java
- lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemGen2Hierarchical.java
Define separate profile for Azure cloud tests to keep how we handle tests which require external infrastructure consistent in the codebase.
As a consequence this drops EnabledIfEnvironmentVariable annotation. The benefit is that with expicit profile and the way how we build condition guarding if tests should be run in ci.yml (use of CI_SKIP_SECRETS_PRESENCE_CHECKS) makes it much less probable to have false confidence that we run tests, when they are skipped. With EnabledIfEnvironmentVariable we could easily skip tests if we secrets propageted to env variables were not set in github.
Remaining work item is to actually fill environment variables values in ci.yml.
( ) Release notes are required. Please propose a …
> Define separate profile for Azure cloud tests

- .github/workflows/ci.yml
CI is broken on master. https://github.com/trinodb/trino/actions/runs/6153633190
```
The workflow is not valid. .github/workflows/ci.yml (Line: 683, Col: 13): Unrecognized named-value: 'ABFS_FLAT_ACCESS_KEY'. Located at position 249 within expression: false && contains(matrix.modules, 'trino-filesystem-azure') && contains(matrix.profile, 'cloud-tests') && (env.CI_SKIP_SECRETS_PRESENCE_CHECKS != '' || env.ABFS_BLOB_ACCOUNT != '' || env.ABFS_BLOB_ACCESS_KEY != '' || env.ABFS_FLAT_ACCOUNT != '' || ABFS_FLAT_ACCESS_KEY != '' || ABFS_ACCOUNT != '' || ABFS_ACCESS_KEY != '')
```
> Fix broken Azure FileSystem Cloud Tests

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeColumnHandle.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSource.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplit.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/delete/PageFilter.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/delete/PositionDeleteFilter.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesFunctionProcessor.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/AddFileEntry.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TableSnapshot.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/Transaction.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointSchemaManager.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TransactionLogTail.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTableSnapshot.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointBuilder.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointEntryIterator.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointWriter.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDeleteCompatibility.java
Fixes #16903
```markdown
* Support reading tables with deletion vectors. ({issue}`16903`)
```
> Support reading deletion vectors in Delta Lake

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
Reduce access count of checkpoint parquet file in Delta
Relates to #18916
> Reduce access count of checkpoint parquet file in Delta

- core/trino-main/src/main/java/io/trino/split/ConnectorAwareSplitSource.java
`ConnectorSplitSource` implementation may hold on to considerable amounts of memory. For example, Iceberg split source keeps table metadata which can be arbitrarily large if table is not maintained.
Each `ConnectorSplitSource` is wrapped by `ConnectorAwareSplitSource`. To free connectors from hassle of freeing memory, the `ConnectorAwareSplitSource` releases the whole `ConnectorSplitSource` once it is finished or closed.
Relates to https://trinodb.slack.com/archives/CGB0QHWSW/p1694416588864109 
Complimentary to https://github.com/trinodb/trino/pull/19011. One does not obsolete the other.
> Release split source memory when finished

- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DriverConnectionFactory.java
We've observed NPE being thrown in the codepaths where connection was not expected to be null.
Alternative to https://github.com/trinodb/trino/pull/19010
```markdown
```
> Temporarily disable telemetry for JDBC connections

- docs/src/main/sphinx/connector/mysql.md
- plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
- plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClientModule.java
- plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
- plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTimeMappingsWithServerTimeZone.java
- plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestingMySqlServer.java
This PR changes the MySQL type mappings for MySQL's `TIMESTAMP` type to Trino's `TIMESTAMP WITH TIME ZONE` type. Note that MySQL `DATETIME` types are read as `TIMESTAMP` types and Trino `TIMESTAMP` types are inserted into MySQL as `DATETIME` types -- this behavior is unchanged.
In other words, for reads and writes:
|MySQL Type|Trino Type|
|-|-|
|DATETIME|TIMESTAMP|
|TIMESTAMP|TIMESTAMP WITH TIME ZONE|
Fixes https://github.com/trinodb/trino/issues/15668
* Changed read and write mappings for MySQL `TIMESTAMP` type to map to Trino `TIMESTAMP WITH TIME ZONE`
* The implementations were taken from the PostgreSQL connector -- I am open to any suggestions on implementation details here
* Added override of `getColumnDefinitionSql` to explicitly declare a column as `NULL` to satisfy an `Invalid …
> Map MySQL TIMESTAMP types to TIMESTAMP WITH TIME ZONE

- core/docker/default/etc/jvm.config
- core/trino-server-rpm/src/main/resources/dist/config/jvm.config
- docs/src/main/sphinx/installation/deployment.md
JDK 9 to 21 has a GCLocker bug which causes JVM to throw OOME too early, because the default value of `-XX:GCLockerRetryAllocationCount` is 2, most of Trino clusters in production environments has 8 to 16+ CPU physical cores(which mostly means 32 vcores), so threads may be starved from receiving memory by the GClocker. The relevant issue: https://bugs.openjdk.org/browse/JDK-8192647  
The principle flow chart of obtaining GCLocker in JVM is as follows:  
And this OOM phenomenon was also seen in our production environment:  
After investigating the JVM tuning articles shared by some companies, I found that `Tencent`(i.e. the parent company of `League of Legends`) also set this parameter to 100:  
I know our community will migrate to JDK 21 partially for auto vectorization in `Project …
> Increase GCLocker retry allocation count to avoid OOM too early

- core/trino-main/src/main/java/io/trino/execution/SqlQueryExecution.java
Previously, the `queryScheduler.set(null)` was only sometimes reached, leading to `QueryTracker.queries` containing references to query scheduler and thus to all split sources and lots of other objects.
Relates to https://trinodb.slack.com/archives/CGB0QHWSW/p1694416588864109
Complimentary to https://github.com/trinodb/trino/pull/19009. One does not obsolete the other.
> Fix releasing query scheduler on query completion

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergColumnHandle.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConnector.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitManager.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/InternalIcebergConnectorFactory.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/IcebergFunctionProvider.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesFunction.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesFunctionHandle.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesFunctionProcessor.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesFunctionProcessorProvider.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesFunctionProvider.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesSplit.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesSplitSource.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Adds a table function which, given a range of snapshot ids, will produce a table of the rows inserted and deleted between those two snapshots.
Currently only supports metadata deletes, not merge-on-read positional or equality deletes.
A document comparing the Iceberg and Delta Lake CDC implementations and how I think we should reconcile the differences is [here](https://docs.google.com/document/d/1e71DP0b9-NCecEqizgf22gJcGzOocnn2vGEZ_RTWmc4/edit?usp=sharing).
Support for positional and equality deletes depends on: https://github.com/apache/iceberg/pull/6182
This is still a draft …
> Add table function for generating Iceberg CDC records

- plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java
- plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
- plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearchMetadata.java
fix query elasticsearch using `like` operator when like content contains utf8 character like chinese
Fixes https://github.com/trinodb/trino/issues/18966
```markdown
Fix query failure when `LIKE` condition contains multi-byte characters. ({issue}`18966`)
```
> Fix elasticsearch like operator get utf8 character length error

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeHistoryTable.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
This PR handles the case when transaction logs are deleted because the retention time of the transaction log is over.
This issue will occur when initial transaction logs get deleted because of log retention interval is exceeded while writing a new checkpoint file.
```markdown
* Fix reading delta lake table history when initial transaction logs are removed. ({issue}`18845`)
```
> Read delta lake table history when initial transaction logs are deleted

- core/trino-main/src/main/java/io/trino/execution/scheduler/BinPackingNodeAllocatorService.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/NoMemoryPartitionMemoryEstimator.java
- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/TestDistributedFaultTolerantEngineOnlyQueries.java
If query does not scan any tables or only accesses information_schema do assume its tasks do not requrie any memory when allocating node for task execution.
That way metadata only queries can execute even if cluster is fully pre allocated.
> Do not allocate task memory for VALUES/metadata-only queries

- plugin/trino-singlestore/pom.xml
A follow-up to #18765 that allows `AbstractTestQueryFramework` to run with JUnit in the Singlestore plugin, which also have tests using that base class.
> Allow AbstractTestQueryFramework to run with JUnit

- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ColumnWriter.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
- lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java
- lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
When dictionary is present, dictionary_page_offset should be populated and data_page_offset should be 
offset of first data page. 
Setting these values correctly allows the parquet reader to avoid reading excess data in 
PredicateUtils#readDictionaryPage for checking if a predicate can prune a row group based on dictionary values.
```markdown
* Reduce data read from parquet files for queries with filters. ({issue}`19032`)
```
> Fix dictionary encoded page offsets in parquet writer

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
In order to reduce execution time instead of execute all possible combinations some scenarios are selected.
Relates to #18805
> Optimize column mapping mode tests

- core/trino-main/src/main/java/io/trino/operator/scalar/IpAddressFunctions.java
- core/trino-main/src/test/java/io/trino/operator/scalar/TestIpAddressFunctions.java
```markdown
* Add support for IPv4 mapped addresses in `contains`. ({issue}`18497`)
```
Fixes #18497
> Handle IPv4 mapped addresses in IP contains function

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeAwsConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeGcsConnectorSmokeTest.java
Fixes https://github.com/trinodb/trino/issues/19044
In the case of ADLS/GCS, I've observed no files in the MINIO bucket. Consequently, attempts to delete a file using `minio.removeObject` have no effect, although I could not find the underlying cause yet. To address this, I am introducing an abstract method `deleteFile(String filePath)`. This method will be implemented in the respective classes. This approach is intended to rectify issues in the CI build and ensure proper file deletion functionality.
The `testUnregisterBrokenTable` test requires an update since it currently relies on `minio.removeObject`.
> Fix delta-lake cloud tests

- core/trino-main/src/main/java/io/trino/sql/planner/iterative/IterativeOptimizer.java
The number for elapsed time should be changed back to milli-seconds from nanoseconds. This was an oversight caused by #16365.
```markdown
```
> Fix the wrong time unit used for reporting elapsed time in query planing

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
The goal of the PR is to auto-adjust column type from varchar(0) to varchar(1) for Hive connector.
The min len of the Trino SPI's VarchartType is 0 whereas the min len of Hive's varchar type is 1.
```
* Automatic type coercion from varchar(0) to varchar(1) for columns within Hive connector.
```
> Coerce column type varchar0 to varchar1 for hive table

- core/trino-main/src/main/java/io/trino/operator/FlatGroupByHash.java
- core/trino-main/src/main/java/io/trino/operator/FlatHash.java
- core/trino-main/src/main/java/io/trino/operator/VariableWidthData.java
> Use exact math in flat hash estimated size

- plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
Listing all tables in metastore in testHideDeltaLakeTables leads to clashes with other tests and/or users of metastore.
> Do not list all tables in testHideDeltaLakeTables

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveStorageFormat.java
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-hive/hive.properties
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveSparkCompatibility.java
Support for this was accidentally removed in scope of https://github.com/trinodb/trino/pull/18556 (424)
```markdown
* Add back support for ParquetHiveSerDe with TextInputFormat. ({issue}`issuenumber`)
```
> Add missing serde/inputFormat combination for Hive

- core/trino-main/src/main/java/io/trino/operator/scalar/timestamp/DateAdd.java
- core/trino-main/src/main/java/io/trino/operator/scalar/timestamptz/DateAdd.java
Currently, overflow error in DATE_ADD is treated as internal error, but it should be treated as user error.
> Treat overflow error in DATE_ADD as user error

- docs/src/main/sphinx/connector/no-inequality-pushdown-text-type.fragment
Corrects the header level of this docs fragment to H4, reflecting what it was before markdown conversion
See the unintended header level change in https://github.com/trinodb/trino/commit/fa23a09355f81ccd6f128b8c251e55d667cb796e#diff-c577586c459f509ce9b8317ab68628a55f2f394e65188480de34a5346010362f
```markdown
```
> Correct header level of inequality pushdown fragment

- lib/trino-filesystem/pom.xml
- lib/trino-filesystem/src/main/java/io/trino/filesystem/tracing/Tracing.java
- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DriverConnectionFactory.java
- pom.xml
> Update OpenTelemetry to 1.30.1

- .github/config/labeler-config.yml
> Add hive label to trino-filesystem-* changes

- core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
When `hide-inaccessible-columns` is enabled and table has N accessible columns, `filterInaccessibleFields` would have `O(N²)` running time.
> Avoid quadratic traversal when many columns accessible

- lib/trino-parquet/pom.xml
- plugin/trino-kinesis/pom.xml
This removes warnings generated by maven:
```
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.trino:trino-parquet:jar:427-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-surefire-plugin @ line 222, column 21
[WARNING]
[WARNING] Some problems were encountered while building the effective model for io.trino:trino-kinesis:trino-plugin:427-SNAPSHOT
[WARNING] 'build.plugins.plugin.(groupId:artifactId)' must be unique but found duplicate declaration of plugin org.apache.maven.plugins:maven-surefire-plugin @ line 213, column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build. …
```
> Collapse repeated surefire plugin entries

- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
This should mitigate flakiness.
Relates to f3c41a49d1a6cb288efe8097afad93207f59667e
https://github.com/trinodb/trino/pull/18323
https://github.com/trinodb/trino/issues/18499
```markdown
```
> Execute `testDynamicFiltering*` exclusively

- lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3InputStream.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/line/LinePageSourceFactory.java
Avoids calling `exists()` and `length()` on `TrinoInputFile` inside of `LinePageSourceFactory`, both of which will map to some API metadata lookups like S3's HeadObject which is unnecessary since:
1. Opening the stream will throw `FileNotFoundException` anyway if the file does not exist and issuing a `HeadObject` eagerly doesn't guarantee the object will still exist for a subsequent `GetObject` call
2. Adjusting the split length based on the exact file size doesn't prevent data corruption, since the file may change size between the two calls anyway and for line based text inputs, you can simply open the stream and read until an EOF is encountered without a separate call to lookup the size.
( ) Release notes …
> Reduce FileSystem calls in LinePageSourceFactory

- core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/TestBinPackingNodeAllocator.java
We need to updated speculative flag in NodeLease objects which were
already acquired. Flag impacts logic in BinPackingNodeAllocator.
Without this change task which got its node while it was
speculative still counted as speculative from NodeAllocator perspective
even if it was already sealed.
> Update speculative flag in NodeLease for running tasks

- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLakeDatabricks104.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLakeDatabricks113.java
- testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLakeDatabricks122.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/TestGroups.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCaseInsensitiveMapping.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeChangeDataFeedCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCheckpointsCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableAsSelectCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksInsertCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksUpdates.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDeleteCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeIdentityColumnCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeSelectCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeSystemTableCompatibility.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java
Reduce considerably the compatibility test coverage against the Databricks cluster versions:
- 10.4 LTS
- 11.3 LTS
- 12.2 LTS
This is done out of pragmatical reasons of test runtime and infrastructure cost and it is based on the assumption that there is enough testing done on the oldest and the newest LTS versions of Databricks.
> Reduce the test coverage for compatibility against Databricks

- docs/src/main/sphinx/connector/delta-lake.md
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeParquetSchemas.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/util/DeltaLakeWriteUtils.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksInsertCompatibility.java
Add support for writing timestamp_ntz type in Delta
Fixes #16927
```markdown
* Add support for writing `timestamp` type. ({issue}`16927`)
```
> Add support for writing timestamp_ntz type in Delta

- plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
- plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTypeMapping.java
Trying to read collections with fractional decimal values like `0.03` was throwing an exception.
Java's `BigDecimal.precision()` returns precision for the unscaled value, so it skips leading zeros. SQL decimal's precision must include leading zeros in values less than 1.
> Fix inferring type of decimals with leading zeros in MongoDB

- core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
- core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/BinPackingNodeAllocatorService.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/NodeAllocator.java
- core/trino-main/src/main/java/io/trino/execution/scheduler/TaskExecutionClass.java
- core/trino-main/src/main/java/io/trino/memory/MemoryManagerConfig.java
- core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/TestBinPackingNodeAllocator.java
- core/trino-main/src/test/java/io/trino/execution/scheduler/TestExponentialGrowthPartitionMemoryEstimator.java
- core/trino-main/src/test/java/io/trino/memory/TestMemoryManagerConfig.java
- core/trino-spi/src/main/java/io/trino/spi/exchange/Exchange.java
It is quite common to use
```
SELECT .... LIMIT N
```
queries for date exploration.
Currently such queries when run in FTE mode require completion of all (or almost) all
tasks which read source data, even though most of the time final answer
could be obtained much sooner.
This commit enables EAGER_SPECULATIVE tasks execution mode for stages
which have FINAL LIMIT operator. This will allow for returning final
results to user much faster (assuming exchange plugin in use supports
concurrent read and write)
> Eager speculative execution for final LIMIT stages

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableHandle.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
Fixes: https://github.com/trinodb/trino/issues/18645
```markdown
```
> Don't rewrite single small file per partition during Optimize

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
> Extract constants for table feature names in Delta Lake

- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergDynamicPartitionPruningTest.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseDynamicPartitionPruningTest.java
Since Iceberg supports bucketing, So enable testJoinDynamicFilteringMultiJoinOnBucketedTables.
> Enable testJoinDynamicFilteringMultiJoinOnBucketedTables in Iceberg

- core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
> Make the order of complex grouping key consistent

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDatabricksWithGlueMetastoreCleanUp.java
I suppose TestDatabricksWithGlueMetastoreCleanUp affected TestIcebergGlueCatalogAccessOperations. 
There were many Glue `DeleteDatabase` calls in CloudTrail when TestIcebergGlueCatalogAccessOperations was running. 
Fixes #19100
> Skip dropping testing Glue database when create time is within threshold

- core/trino-main/src/main/java/io/trino/split/ConnectorAwareSplitSource.java
Ensures that `ConnectorSplitSource#close()` is called from `ConnectorAwareSplitSource` before clearing the reference to it so that any cleanup that may need to happen in the underlying implementation can occur as would happen before https://github.com/trinodb/trino/pull/19009
> Ensure ConnectorSplitSource#close() is called

- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/model/HudiReplaceCommitMetadata.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/timeline/HudiActiveTimeline.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hudi/TestHudiSparkCompatibility.java
When submitting even a very simple query for certain types of Hudi tables (stored on S3) we were constantly receiving the following error:
```
SQL Error [65536]: Query failed (#20230710_093123_00000_bqjz2): No scheme for file system location: path/to/hudi/table/within/bucket/.hoodie
```
Stacktrace taken from the Trino coordinator:
```
...
Caused by: java.lang.IllegalArgumentException: No scheme for file system location: path/to/hudi/table/within/bucket/.hoodie
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
at io.trino.filesystem.Location.of(Location.java:74)
at io.trino.plugin.hudi.timeline.HudiActiveTimeline.getInstantFileNamePath(HudiActiveTimeline.java:88)
at io.trino.plugin.hudi.timeline.HudiActiveTimeline.getInstantDetails(HudiActiveTimeline.java:71) …
```
> Fix instant file name path retrieval in Hudi Active Timeline

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeAwsConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeGcsConnectorSmokeTest.java
MinIO is an object storage server compatible with the S3 cloud storage service. It is not specifically designed for ABFS or GCS. To list and delete files in ADLS and GCS, Use the respective file system APIs. It is unnecessary to start minio container for ADLS and GCS smoke tests.
> Don't start minio for Deltalake's ADLS and GCS smoke test

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
Fix comment in `DeltaLakePageSourceProvider.createPageSource`
( *) This is not user-visible or is docs only, and no release notes are required.
> Fix comment in `DeltaLakePageSourceProvider.createPageSource`

- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DeltaLakeTestUtils.java
Relates to https://github.com/trinodb/trino/actions/runs/6229707688/job/16908908655?pr=18913
> Retry on "HTTP Response code: 504" in Databricks tests

- lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/FileWriter.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSink.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveWriter.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/SortingFileWriter.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetFileWriter.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergParquetFileWriter.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSortingFileWriter.java
Currently we're reading parquet file footer back just after
writing it to file system for computing iceberg stats.
Since Trino parquet writer already has the file footer, there
is no need to perform an extra IO to get the footer again.
```markdown
* Improve performance of writing parquet files. ({issue}`19090`)
```
> Avoid re-reading parquet footer for iceberg stats in writer

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java
Relates to https://trinodb.slack.com/archives/C03E2DYAS0J/p1695295020667509
> Close ConnectorPageSource when exhausted in CheckpointEntryIterator

- plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
- pom.xml
- testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/cli/TestInvocations.java
We can finally remove the suppressions on `record`s for `UnusedVariable`.
Finally fixes google/error-prone#2713
```markdown
```
> Upgrade Error Prone to 2.22.0

- plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
Support altering column comments in Hive Glue catalogs.
Extracted from: https://github.com/trinodb/trino/pull/19073
```markdown
* Support altering column comments in Hive Glue catalogs.
```
> Support altering column comments in Hive Glue catalogs

- core/trino-main/src/main/java/io/trino/operator/join/DefaultPagesHash.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveMerge.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
fixes https://github.com/trinodb/trino/issues/19112
```markdown
```
> Handle empty positions in getAddressIndex

- docs/README.md
And remove RST info.
All conversion to Myst Markdown is completed so we can update the readme and remove rst mentions.
> Update docs readme for Myst Markdown

- docs/src/main/sphinx/security/inspect-pem.md
As requested by @electrum 
Follow up to https://github.com/trinodb/trino/pull/18635
> Document PEM format as file format

- docs/src/main/sphinx/connector/iceberg.md
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Support Iceberg version travel by reference name.
Note: This is a rebased version of https://github.com/trinodb/trino/pull/15646. I addressed some conflicts, added an additional test, and cleaned up a nit. @jackye1995 was the original author of this PR, I just marked myself as a co-author (let me know what is the practice followed in the Trino community).
```
SELECT * FROM table AS OF VERSION 'tag-name'
```
> Support Iceberg version travel by reference name

- lib/trino-parquet/src/main/java/io/trino/parquet/reader/MetadataReader.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
Currently we're reading parquet file footer back just after
writing it to file system for computing delta stats.
Since Trino parquet writer already has the file footer, there
is no need to perform an extra IO to get the footer again.
Similar to https://github.com/trinodb/trino/pull/19090 but for delta
```markdown
* Improve performance of writing parquet files. ({issue}`19122`)
```
> Avoid re-reading parquet footer for delta stats in writer

- core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java
- core/trino-main/src/main/java/io/trino/operator/output/SkewedPartitionRebalancer.java
- core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
- core/trino-main/src/test/java/io/trino/execution/TestTaskManagerConfig.java
- docs/src/main/sphinx/admin/properties-task.md
- docs/src/main/sphinx/admin/properties-writer-scaling.md
Follow-up to https://github.com/trinodb/trino/pull/18771
> Insert cleanups

- core/trino-main/src/main/java/io/trino/likematcher/LikeMatcher.java
- core/trino-main/src/test/java/io/trino/likematcher/TestLikeMatcher.java
When a pattern contains a % and a sequence of _ somewhere after it, it may produce a DFA with exponential number of states. In such cases, fall back to the NFA matcher.
Fixes #19146 
```markdown
* TBD. ({issue}`19146`)
```
> Avoid exponential DFA in LIKE matcher

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/EqualityDeleteFilter.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
Fixes #17114 
If a split with many delete file `RowPredicate.and` will create a deep stack, this pr compact all StructLikeSet to a collection to reduce stack depth.
The stack depth is only a hidden danger. The real problem is that multiple `StructLikeSet` of a split are not merged according to the ids, resulting in too many `StructLikeSet` being generated, which makes the filtering efficiency very lowly. 
The main content is to classify delete files according to id, and only use the same `StructLikeSet` to collect deletion data. 
```markdown
* Improve performance of reading …
```
> Improve performance of reading iceberg table with many delete files

- docs/src/main/sphinx/release.md
- docs/src/main/sphinx/release/release-427.md
Assemble the release notes for the upcoming Trino 427 release. Fixes #18939 
* #18921 ✅ rn ✅ docs
* #18738 ✅ rn ✅ docs
* #18241 ✅ rn ✅ docs
* #18940 ✅ rn ✅ docs
* #14214 ✅ rn ✅ docs
* #18650 ✅ rn ✅ docs
* #18942 ✅ rn ✅ docs
* #18920 ✅ rn ✅ docs
* #18930 ✅ rn ✅ docs
* #18958 ✅ rn ✅ docs
* #18875 ✅ rn ✅ docs
* #18952 ✅ rn ✅ docs
* #18970 ✅ rn ✅ docs
* #18971 ✅ rn ✅ docs
* #18972 ✅ rn ✅ docs
* #18978 ✅ rn ✅ docs
* #18968 ✅ rn ✅ docs
* #18956 ✅ rn ✅ …
> Add Trino 427 release notes

- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeHistoryTable.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePropertiesTable.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/RegisterTableProcedure.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TableSnapshot.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TransactionLogTail.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakeUtils.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/statistics/TestDeltaLakeFileBasedTableStatisticsProvider.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTableSnapshot.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestTransactionLogTail.java
Refactor `TransactionLogAccess` to ensure that a snapshot of given table
is loaded once during query. Previously, the snapshot was loaded
multiple times, so the observed table state could change during query
planning, and produce incorrect results.
Almost fixes the issue https://github.com/trinodb/trino/issues/16780, except for DELETE queries.
> Ensure consistent Delta table snapshot during query

- core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
- core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java
- core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
- core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
- core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddLocalExchanges.java
- core/trino-main/src/test/java/io/trino/execution/TestTaskManagerConfig.java
- core/trino-main/src/test/java/io/trino/sql/planner/TestInsert.java
- core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddLocalExchangesForPartitionedInsertAndMerge.java
- docs/src/main/sphinx/admin/properties-task.md
- docs/src/main/sphinx/admin/properties-writer-scaling.md
- plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectionCreationTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePreferredPartitioning.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcMetricsCollection.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestMetadataQueryOptimization.java
- testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/BaseFaultTolerantExecutionTest.java
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/standard-multinode/multinode-master-config.properties
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/standard-multinode/multinode-worker-config.properties
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/standard/config.properties
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergOptimize.java
Now, we have only two properties
task.min-writer-count:
Minimum number of local parallel table
writers per task when prefer partitioning and
task writer scaling are not used.
task.max-writer-count:
Maximum number of local parallel table writers
per task when either task writer scaling or prefer
partitioning is used.
```markdown
```
> Simplify writer count properties

- client/trino-client/src/main/java/io/trino/client/JsonCodec.java
- client/trino-client/src/test/java/io/trino/client/TestQueryResults.java
Right now both JDBC and the CLI won't be able do deserialize columns longer than 20_000_000 bytes (20 MB) due to the read constraints introduced in Jackson that we use. We've disabled these read constraints on the server side, but not in the client.
> Disable Jackson's read constraints 

- core/trino-main/src/main/java/io/trino/util/CompilerUtils.java
- core/trino-main/src/test/java/io/trino/type/TestSingleAccessMethodCompiler.java
Ensures that all class names generated by CompilerUtils are shorter than the `65535` byte length limit imposed on constant pool entries by the JVM language spec and by the asm library. This is done by truncating the provided base name while ensuring the suffixes that guarantee the class name is unique are preserved to avoid name collisions. This prevents code generation from failing when, for example particularly complex `ROW` types are used as part of the generated class name passed in.
None
> Truncate class names in CompilerUtils

- core/trino-main/src/main/java/io/trino/FeaturesConfig.java
Followup to https://github.com/trinodb/trino/pull/19166 -- forgot to push this change to that branch before merging.
> Mark parse-decimal-literals-as-double as defunct

- docs/src/main/sphinx/connector/object-storage-file-formats.md
- lib/trino-parquet/src/main/java/io/trino/parquet/ParquetReaderOptions.java
- lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetDataSource.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesFunctionProcessor.java
- plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java
- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/MemoryParquetDataSource.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
- plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetReaderConfig.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetReaderConfig.java
- plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystemAccessOperations.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSourceProvider.java
- plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiSessionProperties.java
- plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiSessionProperties.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
- testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop/hive.properties
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksMinioReads.java
- testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeOssDeltaLakeMinioReads.java
- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Read files below parquet.small-file-threshold size in a single file system request to avoid multiple small read requests
This is similar to `hive.orc.tiny-stripe-threshold` in ORC reader
```markdown
* Reduce read requests for scanning small parquet files. 
The catalog configuration property `parquet.small-file-threshold` or the corresponding
catalog session property can be used to change the default size of `3MB` below which files 
will be read entirely. Setting this configuration to `0B` disables the feature. ({issue}`19127`)
```
> Avoid multiple read requests on small parquet files

- plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
- plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java
- testing/trino-testing-services/src/main/java/io/trino/testng/services/ManageTestResources.java
Ability to iterate faster on integration test development for PostgreSQL by adding the support for TESTCONTAINERS_REUSE_ENABLE environment variable.
This is based on previous commit 
https://github.com/trinodb/trino/commit/fbd1de01bba0c896e6e584f26d128452fdf35bc1
by @kokosing, which adds the feature and enables it for SQL Server and MySQL. Based on further comments from @kokosing, enablement of this feature for specific database tests needs to be tested one-by-one as not all test containers seem to digest that change without problems. This justifies adding it iteratively for selected databases based on a need-to-use basis.
( ) Release notes …
> Allow re-using PostgreSQL container in tests

- core/trino-main/src/main/java/io/trino/operator/FlatHash.java
- core/trino-main/src/test/java/io/trino/operator/GroupByHashYieldAssertion.java
Use an incremental batched rehash of the group by hash.  This PR processes each of the underlying array segments one at a time, and only allocates segments in the new hash as needed.  After processing the segment the segment is freed. Since the flat group by hash is a power of 2 with a simple mask, the rehash of a value has only two possible starting bucket locations in the new map, so typically only 2 new segments are created for each old segment processed.  In practice, the system has 2 additional segments (one before the start and one after the end), due to collision chains.
The net result is the actual memory used during the rehash increases linearly from the old size to the new size.  Currently, we reserve all of the memory for the new hash (without an additional reservation for the …
> Incremental rehash for group by hash

- docs/src/main/sphinx/admin/fault-tolerant-execution.md
* Azure Data Lake Storage Gen2 is hierarchical. When using FTE with ADLS Gen2, batch operation errors can occur when deleting folders during blob cleanup. While the data is deleted, the file path remains. Because ADLS is hierarchical, folders need explicit deletion. This PR adds a line to FTE configuration documentation to make it clear that Azure Blob Storage should be used instead of ADLS.
```markdown
```
> Add requirement for Blob Storage instead of ALDS for FTE

- docs/src/main/sphinx/connector/tpch.md
Add a paragraph on `tpch.column-naming=STANDARD` to the documentation of the TPCH connector. Useful when trying to run TPC-H queries without modifications.
> Document tpch.column-naming

- core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java
The resource can't be loaded with a path reference, as the current working dir when running tests may vary across environments.
> Fix broken resource reference in test

- plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
In case that the dynamic filtering was finishing fast enough, the second scan on `test_self_join_table` was not being performed anymore because there was no purpose in doing so, given that the result was empty anyway. Adapt the content of the `test_self_join_table` to actually return a result so that the scanning of the data files is actually performed twice for each occurrence of the table in the JOIN operation.
Fixes #19198
```markdown
```
> Fix test flakiness

- plugin/trino-iceberg/pom.xml
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergParquetFileWriter.java
- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java
- plugin/trino-iceberg/src/main/java/org/apache/iceberg/parquet/TrinoParquetUtil.java
This is a temporal change until Iceberg 1.4.0 release. 
Relates to #19052
Cherry-pick https://github.com/apache/iceberg/pull/8559
```markdown
* Fix incorrect column statistics for Parquet file format in manifest files. ({issue}`19052`)
```
> Fix incorrect column statistics in manifest files for Parquet file format

- plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java
Allow registering an Iceberg table with register_table using s3:// address even when the table metadata / manifests use equivalent, s3a:// or s3n:// URIs. In metastore, the table gets registered using it's declared location, from the metadata. This ensures consistency for data files' paths stored in manifests.
> Allow register_table with s3:// when metadata uses s3a://

- plugin/trino-teradata-functions/pom.xml
- plugin/trino-teradata-functions/src/test/java/io/trino/plugin/teradata/functions/dateformat/TestDateFormatParser.java
The module was migrated to JUnit, so it shouldn't use TestNG.
> Remove testng from trino-teradata-functions test classpath

- lib/trino-filesystem/src/test/java/io/trino/filesystem/TrackingFileSystemFactory.java
- plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java
Tests checking count of I/O operations do not need to be concerned with `TrinoOutputFile.location` invocations, because it is always a cheap local operation.
> Skip tracking TrinoOutputFile.location in tests

- plugin/trino-atop/pom.xml
- plugin/trino-blackhole/pom.xml
- plugin/trino-jmx/pom.xml
- plugin/trino-teradata-functions/pom.xml
- plugin/trino-tpcds/pom.xml
- plugin/trino-tpch/pom.xml
- testing/trino-plugin-reader/pom.xml
- testing/trino-tests/pom.xml
- testing/trino-tests/src/test/resources/sql/presto/tpcds/hive/partitioned/q08.plan.txt
- testing/trino-tests/src/test/resources/sql/presto/tpcds/hive/unpartitioned/q08.plan.txt
- testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/orc/partitioned/q08.plan.txt
- testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/orc/unpartitioned/q08.plan.txt
- testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q08.plan.txt
- testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q08.plan.txt
- testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg_small_files/parquet/unpartitioned/q08.plan.txt
TestNG tests from at least `trino-tests` and `trino-tpcds` were not being run on CI, silently ignored.
This commit adds necessary configuration to make those tests running again.
```bash
function modules_with {
local dependency="$1"
./mvnw dependency:tree -T1 \
| grep '\[INFO\] --- dependency:3.6.0:tree (default-cli) @\|'"${dependency}" \
| grep -B1 "${dependency}" \
| sed -ne 's/.*dependency:3.6.0:tree.* @ \([^ ]\+\) ---/\1/p'
}
modules_with 'org.testng:testng' \
| grep -xf <( modules_with ':junit-jupiter-api' ) \
`# filter out those already having surefire-testng` \
| grep -vxf <( find -name pom.xml -exec grep '<artifactId>surefire-testng</artifactId>' -l {} + | sed -ne 's@.*/\(trino-[^/]\+\)/pom.xml@\1@p' )
```
Except that `trino-server-rpm` was skipped.
Note that this can have false …
> Fix running TestNG tests on CI

- testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Since 65ee08ab9abb8cd705ca923bf56cccc6b24a2d11, the test was passing only for connectors that store varchar(25) as varchar.  Make the test possible to pass also for connectors supporting varchar with bound length.
> Fix test to be varchar length agnostic

- docs/src/main/sphinx/functions/comparison.md
Add IN operator to the comparison section. This is a improvement for the documentation with examples.
Fixes https://github.com/trinodb/trino/issues/4791
> Document IN operator #18610

- lib/trino-hive-formats/src/main/java/io/trino/hive/formats/DistinctMapKeys.java
Corrected hashtable size. Earlier it was using older value.
Fixes the issue [19142](https://github.com/trinodb/trino/issues/19142)
```markdown
* Fix some things. ({issue}`19142`)
```
> Corrected hash table length for distinct map keys
