plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsReader.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

Exclude files that do not satisfy the metadata predicate while computing the table statistics in Iceberg.
While building the tableScan metadata predicates are ignored, it results scan files more than expectation.

Exclude files that do not satisfy the metadata predicate

---

core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryMetadata.java
core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryStatistics.java

1. Let's compute `QueryCompletedEvent` only once, even if there is multiple event listeners.
2. Let's compute `QueryMetadata#paylaod` and `QueryStatistics#operatorSummaries` lazily because of heaviness (CPU and memory) of these computation.
A lot of CPU cycles released
Fixes a regression introduced in https://github.com/trinodb/trino/commit/7f3047691383beb5320900b0adb94e684dbfe82a (https://github.com/trinodb/trino/pull/12968) -- `QueryCompletedEvent` was being created multiple times, and it's sometimes quite expensive.

Lazy computation of some fields in QueryMetadata and QueryStatistics

---

core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java
plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/AccumuloQueryRunner.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryQueryRunner.java
plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/BlackHoleQueryRunner.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/MemoryQueryRunner.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoQueryRunner.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/PinotQueryRunner.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/PrometheusQueryRunner.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/RaptorQueryRunner.java
plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/ThriftQueryRunner.java
plugin/trino-tpcds/src/test/java/io/trino/plugin/tpcds/TpcdsQueryRunner.java
testing/trino-tests/src/test/java/io/trino/tests/tpch/TpchQueryRunner.java

The thread leak matters for test execution. After
`DistributedQueryRunner.close()`, we expect all resources to be released
so that we can allocate resources for another query runner.

Fix threads leak in SqlTaskManager

---

core/trino-main/src/main/java/io/trino/connector/WorkerDynamicCatalogManager.java
core/trino-main/src/main/java/io/trino/execution/SqlTask.java
core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java

Block task updating on all catalogs being loaded. Currently the second request to task update will always update the task before waiting for the catalogs to be loaded. This will block all threads trying to update the task on waiting for catalogs to load. 
fixes https://github.com/trinodb/trino/issues/20326
```markdown
```

Block task execution on catalog loading flag

---

core/trino-main/src/main/java/io/trino/connector/WorkerDynamicCatalogManager.java
core/trino-main/src/main/java/io/trino/memory/ClusterMemoryManager.java

Extracted from https://github.com/trinodb/trino/pull/21470

Terminate WorkerDynamicCatalogManager's executor

---

core/trino-main/src/main/java/io/trino/sql/gen/RowConstructorCodeGenerator.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConnectorSmokeTest.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java

Reduces generated code size for rows with large number of fields. Earlier PageProjectionWork.evaluate method code generation used to work for ~900 columns. After [trino#17342](https://github.com/trinodb/trino/pull/17342), evaluate method runs into method too large issue for ~650 columns. Post this change RowConstructorCodeGenerator can generate byte code for ~850 columns.
(X ) Release notes are required, with the following suggested text: 
```markdown
* Increase the number of columns supported by MERGE queries before MethodTooLargeExceptions are encountered. ({issue}`issuenumber`)
```

Reduce generated code size for Row Constructors

---

client/trino-client/src/main/java/io/trino/client/uri/TrinoUri.java

Another approach to the solution present in #21027
Fix #21026 
OkHttp module changed the way it handles Authorization headers during HTTP redirects. Trino engine uses OkHttp's interceptors to inject the Authorization header. There are [two types of interceptors](https://square.github.io/okhttp/features/interceptors/) in OkHttp module. Currently, Trino uses Application interceptor and Authorization header gets cleared during redirects. Instead, if we use Network interceptor, the Authorization header token will be retained as it happens after OkHttp module clears the headers during redirects.  …

Retain authorization header during cross host client redirects

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java

We can stop listing files if the checkpoint file version is same as time travel version. 

Stop listing files when exact checkpoint found in Delta Lake time travel

---

core/trino-main/src/main/java/io/trino/operator/PagesIndex.java
core/trino-main/src/main/java/io/trino/operator/PagesRTreeIndex.java
core/trino-main/src/main/java/io/trino/operator/PagesSpatialIndexSupplier.java
core/trino-main/src/main/java/io/trino/operator/SpatialIndexBuilderOperator.java
core/trino-main/src/main/java/io/trino/sql/ir/IrExpressions.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ReorderJoins.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java
core/trino-main/src/main/java/io/trino/sql/planner/plan/JoinNode.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDetermineJoinDistributionType.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestJoinEnumerator.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneJoinChildrenColumns.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestReorderJoins.java
core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java
core/trino-main/src/test/java/io/trino/sql/query/TestJoin.java
plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestSpatialJoinOperator.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHivePlans.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java

Currently, only fixes inner joins. Outer joins are TODO.
```markdown
* TBD
```

Preserve order of evaluation of filters that may fail

---

plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraTable.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraTypeMapping.java

Stress test result of TestCassandraConnectorTest#testTimestampPartitionKey
* 31/100 failed before this change
* 100/100 passed after this change

Check table existence in Trino instead of Cassandra

---

pom.xml
testing/trino-faulttolerant-tests/pom.xml
testing/trino-product-tests-launcher/pom.xml

JUnit 4 remains in PTL, as we implement
`org.testcontainers.containers.Network` and that interface extends a JUnit 4 interface.

Remove JUnit 4 from FTE tests

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeHistoryTable.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePropertiesTable.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/RegisterTableProcedure.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakeUtils.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/statistics/TestDeltaLakeFileBasedTableStatisticsProvider.java

Remove deprecated TransactionLogAccess.loadSnapshot

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeRenameToWithGlueMetastore.java

Fix broken test: https://github.com/trinodb/trino/actions/runs/8638182101/job/23682452532
https://github.com/trinodb/trino/commit/5697711476278bdfda3a064266d176e09651f3db seems the cause. 

Use default catalog name in TestDeltaLakeRenameToWithGlueMetastore

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergStatistics.java

Fix `TestIcebergStatistics.testAnalyzeWithSchemaEvolution` when running locally. The estimated size for `name` and `info` apparently varies, compared to what is expected on CI. The reason for this is not currently known.
Fixes https://github.com/trinodb/trino/issues/19579

Fix TestIcebergStatistics when running locally

---

lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroPageDataReader.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroTypeUtils.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/ArrayReadAction.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/AvroReadAction.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/BooleanRead.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/BytesRead.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/DefaultValueFieldRecordFieldReadAction.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/DoubleRead.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/EnumReadAction.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/FixedRead.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/FloatRead.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/IntRead.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/LongRead.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/MapReadAction.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/NullRead.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/ReadErrorReadAction.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/ReadFieldAction.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/ReadingUnionReadAction.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/RecordFieldReadAction.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/RecordReadAction.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/SkipFieldRecordFieldReadAction.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/StringRead.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/model/WrittenUnionReadAction.java

Make a sealed version of the Avro Resolver Action
```markdown
```

Make sealed version of Avro Resolver Action

---

core/trino-main/src/main/java/io/trino/sql/planner/EffectivePredicateExtractor.java
core/trino-main/src/test/java/io/trino/sql/query/TestIssue21508.java

EffectivePredicateExtractor was incorrectly deriving an equality predicate for a type that's no comparable or orderable.
Fixes #21508 
```markdown
* TBD. ({issue}`21508`)
```

Fix incorrect effective predicate derivation for non-equatable type

---

plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java

Splitting https://github.com/trinodb/trino/pull/21012 into incremental ones. This is the first part of it.
Description:
1. Replace maps with switch/case statements to avoid repetitive building of the maps.
2. Re-order types so that the order is consistent with other connectors.
3. Inlining/renaming some methods for better readability.
```markdown
```

Clean up Snowflake type mapping code

---

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java
core/trino-main/src/test/java/io/trino/sql/query/TestJoin.java

Derived predicates from the left/right branch of an inner join that may fail during evaluation were being incorrectly pushed down to the other side.
```markdown
```

Fix invalid pushdown of predicate that may fail

---

testing/trino-testing-containers/pom.xml
testing/trino-testing-containers/src/main/java/io/trino/testing/minio/MinioClient.java

Our `MinioClient` wraps MinIO's own `MinioClient` (`io.minio.MinioClient`). The MinIO `MinioClient` builder creates a new `OkHttpClient` and previously we were not closing the HTTP client, which resulted in leaking threads (`OkHttpClient` has an executor service). There seems to be no way to dispose of MinIO's `MinioClient`'s resources, so create the HTTP client explicitly so that we can close it.

Fix thread leak in MinioClient

---

client/trino-jdbc/src/test/java/io/trino/jdbc/BaseTestJdbcResultSet.java

This line is the last usage of `@Test` with expectedExceptions. 
Fixes https://github.com/trinodb/trino/issues/6974

Use assertThatThrownBy in testMaxRowsExceedsLimit

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java

Fix error message in TrinoRestCatalog.listTables

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/SimplifyCountOverConstant.java
core/trino-main/src/test/java/io/trino/sql/query/TestAggregation.java

SimplifyCountOverConstant replaces count(constant_literal) with count(*). But this will give incorrect results when there is distinct aggregation. This CR fixes this issue by not applying this optimization when distinct clause is present.
```markdown
* Fix incorrect results for distinct count aggregation over a constant value. ({issue}`18562`)
```

Fix correctness bug in constant literal distinct aggregation

---

lib/trino-filesystem-cache-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioInputHelper.java
lib/trino-filesystem-cache-alluxio/src/test/java/io/trino/filesystem/alluxio/TestAlluxioCacheFileSystemAccessOperations.java

Fixes https://github.com/trinodb/trino/issues/21342 and https://github.com/trinodb/trino/issues/21147.
These exists a race condition in Alluxio cache which occurs when two different threads are trying to read a same file, 
then it fails to read the data file with the following message
```
Caused by: java.io.IOException: Read -1 bytes from cache
at io.trino.filesystem.alluxio.AlluxioInputHelper.doInternalCacheRead(AlluxioInputHelper.java:120)
at io.trino.filesystem.alluxio.AlluxioInputHelper.lambda$doCacheRead$0(AlluxioInputHelper.java:89)
at io.trino.filesystem.alluxio.AlluxioTracing.withTracing(AlluxioTracing.java:29)
at io.trino.filesystem.alluxio.AlluxioInputHelper.doCacheRead(AlluxioInputHelper.java:87)
at io.trino.filesystem.alluxio.AlluxioInput.readFully(AlluxioInput.java:79)
at …
```

Try reading data from underlying source if the data has been corrupted

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeOutputTableHandle.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/DeltaLakeMetastore.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheFileOperations.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMetadata.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreAccessOperations.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCreateOrReplaceTableAsSelectCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCreateTableAsSelectCompatibility.java

Introduces `CREATE OR REPLACE TABLE` operation for Delta lake connector.  It comes with some restrictions like we can't run CORTAS on table with cdc enabled or on cdc enabled roles.
```markdown
* Add support for CREATE OR REPLACE TABLE statements. ({issue}`issuenumber`)
```

Implement CREATE OR REPLACE TABLE for delta lake connector

---

plugin/trino-bigquery/pom.xml
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadSessionCreator.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java

Allow creating temp tables for BigQuery materialized views so that users can read the object using storage API. 
```markdown
* Create temporary tables and use BigQuery storage API by default when reading materialized views. ({issue}`21487`)
```

Allow creating temp tables for BigQuery materialized views

---

docs/src/main/sphinx/connector/bigquery.md
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryArrowSerialization.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryArrowTypeMapping.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java

It was experimental more than 1 year. I think we can remove experimental clarification now. 

Remove "experimental" from BigQuery Arrow config property

---

plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleFailureRecoveryTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java

We could not ensure that tmp tables are always promptly removed in Oracle. Checking if tmp_trino tables are deleted immediatelly after DML operation renders TestOracleQueryFailureRecoveryTest and TestOracleTaskFailureRecoveryTest test flaky.
fixes: https://github.com/trinodb/trino/issues/20309

Relax test assertion in BaseOracleFailureRecoveryTest

---

docs/src/main/sphinx/connector/mongodb.md
plugin/trino-mongodb/pom.xml
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientConfig.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSourceProvider.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSessionProperties.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSplitManager.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoTableHandle.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoClientConfig.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoDynamicFiltering.java

Add support of dynamic filter to mongodb connector.
Add the following configuration property:
- `dynamic-filtering.wait-timeout`
- Maximum [duration](prop-type-duration) for which Trino waits for dynamic
filters to be collected from the build side of joins before starting a
MongoDB query. Using a large timeout can potentially result in more detailed
dynamic filters. However, it can also increase latency for some queries.
Defaults to `5s`.
```markdown
* Improve performance of queries with selective joins. ({issue}`21355`)
```

Add mongodb dynamic filter support

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePartitionManager.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTableHandle.java

The `toString` is used by `EXPLAIN` to provide information for the user.
relates
- https://github.com/trinodb/trino/pull/21573

Indicate constraint in HiveTableHandle.toString 

---

core/trino-main/src/main/java/io/trino/connector/InternalMetadataProvider.java
core/trino-main/src/main/java/io/trino/connector/system/TableCommentSystemTable.java
core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java
core/trino-main/src/main/java/io/trino/execution/DropColumnTask.java
core/trino-main/src/main/java/io/trino/metadata/MetadataListing.java
core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
core/trino-main/src/main/java/io/trino/metadata/TableMetadata.java
core/trino-main/src/main/java/io/trino/metadata/TableSchema.java
core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
core/trino-main/src/test/java/io/trino/execution/TestAddColumnTask.java
core/trino-main/src/test/java/io/trino/execution/TestCommentTask.java
core/trino-main/src/test/java/io/trino/execution/TestDropColumnTask.java
core/trino-main/src/test/java/io/trino/execution/TestDropNotNullConstraintConstraintTask.java
core/trino-main/src/test/java/io/trino/execution/TestRenameColumnTask.java
core/trino-main/src/test/java/io/trino/execution/TestSetColumnTypeTask.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java

Convert TableMetadata to record

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-445.md

Assemble the release notes for the upcoming Trino 445 release.
* #21384 ✅ rn ✅ docs
* #21386 ✅ rn ✅ docs
* #21385 ✅ rn ✅ docs
* #21383 ✅ rn ✅ docs
* #21205 ✅ rn ✅ docs
* #21388 ✅ rn ✅ docs
* #21389 ✅ rn ✅ docs
* #21390 ✅ rn ✅ docs
* #21051 ✅ rn ✅ docs
* #21400 ✅ rn ✅ docs
* #21244 ✅ rn ✅ docs
* #21403 ✅ rn ✅ docs
* #21382 ✅ rn ✅ docs
* #21379 ✅ rn ✅ docs
* #20200 ✅ rn ✅ docs
* #21374 ✅ rn ✅ docs
* #21411 ✅ rn ✅ docs
* #21415 ✅ rn ✅ docs
* #21417 ✅ rn ✅ docs
* #20982 ✅ rn ✅ docs
* #21419 ✅ rn ✅ docs
* #21424 ✅ rn ✅ docs
* #21427 ✅ rn ✅ …

Add Trino 445 release notes

---

docs/src/main/sphinx/connector/clickhouse.md
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseTypeMapping.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestAltinityConnectorSmokeTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestingClickHouseServer.java

I'm going to invest some time into making ClickHouse connector more functional. This is the first PR in a (hopefully) longer series.
Changes:
- Upgrade ClickHouse docker images (both by ClickHouse and Altinity). I was picking lts/stable builds from both providers.
- Fix unit tests to let them work against newer version. I had to disable one case in `testDouble` due to [bug in ClickHouse itself](https://github.com/ClickHouse/ClickHouse/issues/60146).
- Changed the way IP addresses are casted upon ingestion from Trino. Previous implementation couldn't handle NULL values properly.
None.

Upgrade clickhouse image in tests

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeLocalConcurrentWritesTest.java

Avoid test flakiness on Azure generated a too small timeout
duration for slow rename concurrent operations.
On Azure, at the time of this writing, renaming concurrently
more than 2 files to the same target file at the same time
can cause on Azure some of the `rename` operations to take
even about 2 minutes.
Fixes #21554
Created Azure Storage follow-up https://github.com/Azure/azure-sdk-for-java/issues/39774

Delta Lake Azure Smoke Tests:Rewrite test to avoid flakiness

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java

Otherwise sanity check in setSpeculative method always failed if we wanted StageExecution to be initially speculative as it was assumed we are switchihng it from non-speculative to speculative, which is forbidden.

Set speculative flag at create time

---

docs/.vale/config/vocabularies/Base/accept.txt
docs/src/main/sphinx/security/salesforce.md

Stumbled into a spelling mistake of "Salesforce" and then just fixed all vale and source formatting issues in this page.

Fix spelling in Salesforce docs

---

core/trino-spi/src/main/java/io/trino/spi/predicate/SortedRangeSet.java
core/trino-spi/src/test/java/io/trino/spi/predicate/BenchmarkSortedRangeSet.java
core/trino-spi/src/test/java/io/trino/spi/predicate/TestSortedRangeSet.java

Improve performance of overlaps and intersect method for common use cases.
```
// baseline
Benchmark                                          Mode  Cnt   Score   Error  Units
BenchmarkSortedRangeSet.overlapsLarge              avgt         3,580          ms/op
BenchmarkSortedRangeSet.overlapsMediumOnVeryLarge  avgt        12,021          ms/op
BenchmarkSortedRangeSet.overlapsSmall              avgt        31,873          ms/op
BenchmarkSortedRangeSet.overlapsSmallOnVeryLarge   avgt       186,582          ms/op
```
```
// bin search
Benchmark                                          Mode  Cnt   Score   Error  Units
BenchmarkSortedRangeSet.overlapsLarge              avgt        3,647          ms/op
BenchmarkSortedRangeSet.overlapsMediumOnVeryLarge  avgt        6,708          ms/op …
```

Use binary search in SortedRangeSet overlaps

---

plugin/trino-redshift/pom.xml
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/BaseRedshiftFailureRecoveryTest.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/RedshiftQueryRunner.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftAutomaticJoinPushdown.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorSmokeTest.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorTest.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftTableStatisticsReader.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftTypeMapping.java

Avoid multiple overloads. Make setup easier to follow.

Add builders for Redshift query runner

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueToTrinoConverter.java

Change exception thrown in case of missing SerdeInfo to HIVE_UNSUPPORTED_FORMAT instead of NPE.
```markdown
```

Throw HIVE_UNSUPPORTED_FORMAT in case of missing SerdeInfo in Glue

---

core/trino-spi/src/main/java/io/trino/spi/predicate/SortedRangeSet.java
core/trino-spi/src/test/java/io/trino/spi/predicate/BenchmarkSortedRangeSet.java
core/trino-spi/src/test/java/io/trino/spi/predicate/TestSortedRangeSet.java

Improve performance of SortedRangeSet intersect for common usage patterns.
```
Benchmark                                                Mode  Cnt    Score     Error  Units
BenchmarkSortedRangeSet.binaryIntersectDiscreteOnLarge   avgt    3    2,291 ±   0,098  ms/op
BenchmarkSortedRangeSet.binaryIntersectLarge             avgt    3  368,274 ±  40,854  ms/op
BenchmarkSortedRangeSet.binaryIntersectRangeOnLarge      avgt    3    0,205 ±   0,018  ms/op
BenchmarkSortedRangeSet.binaryIntersectSmall             avgt    3   18,781 ±   0,846  ms/op
BenchmarkSortedRangeSet.binaryIntersectSmallOnVeryLarge  avgt    3    4,437 ±   0,299  ms/op
BenchmarkSortedRangeSet.linearIntersectDiscreteOnLarge   avgt    3  115,397 ± 239,691  ms/op
BenchmarkSortedRangeSet.linearIntersectLarge             avgt    3 …
```

Use binary search in SortedRangeSet intersect

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplit.java

In `IcebergSplit`, `addresses` was once removed in https://github.com/trinodb/trino/commit/037118255a08b45b7a061991cd22628ff3ce01d4 and resurrected in https://github.com/trinodb/trino/commit/102ce9df60c8df086a186aef41c8546a1c96d359 but without fixing `getRetainedSizeInBytes()`.
- https://github.com/trinodb/trino/pull/18006
- https://github.com/trinodb/trino/pull/20602
```markdown
```

Include addresses in retainedSize of IcebergSplit

---

plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilteringResult.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaMetadata.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaPageSinkProvider.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaRecordSet.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaSplit.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaSplitManager.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaTableHandle.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaTopicDescription.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaTopicFieldDescription.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaTopicFieldGroup.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/Range.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/AbstractContentSchemaProvider.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/file/FileTableDescriptionSupplier.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/KafkaQueryRunner.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaFilterManager.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/util/TestUtils.java

Convert some classes to record in Kafka

---

plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClusteringPredicatesExtractor.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPartitionManager.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPartitionResult.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSession.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSplitManager.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTable.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTokenSplitManager.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/ExtraColumnMetadata.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/SizeEstimate.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/util/CassandraCqlUtils.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/util/TestCassandraClusteringPredicatesExtractor.java

Convert some classes to record in Cassandra

---

.mvn/wrapper/maven-wrapper.properties
mvnw
plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java

Wrapper regenerated using: ./mwnv wrapper:wrapper -Dtype=script-only

Update maven-wrapper to 3.3.0 & dependencies

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeParquetStatisticsUtils.java

If the code does not support stats for given type, there is nothing a Trino operator can do about this, so logging a warning is not helpful.

Avoid non-actionable warnings logged in Delta writer stats

---

core/trino-main/src/main/java/io/trino/operator/aggregation/arrayagg/FlatArrayBuilder.java
core/trino-main/src/test/java/io/trino/operator/aggregation/TestArrayAggregation.java
core/trino-main/src/test/java/io/trino/operator/aggregation/arrayagg/TestFlatArrayBuilder.java

When record size is a multiple of RECORDS_PER_GROUP, the last group is skipped
example:
```
trino:default> with s as (SELECT * FROM TABLE(sequence(start => 1, stop=> 1024, step=>1)))
-> select ARRAY_AGG(sequential_number) from s;
_col0
-------
NULL
(1 row)
```
```markdown
```

Fix last openRecordGroup not processed in FlatArrayBuilder

---

core/trino-main/src/main/java/io/trino/operator/exchange/ScaleWriterPartitioningExchanger.java

For processed data getSizeInBytes should be used
```markdown
```

Use getSizeInBytes rather than getRetainedSizeInBytes

---

docs/src/main/sphinx/connector/prometheus.md

Convert config properties to list-table in Prometheus documentation

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/HashDistributionSplitAssigner.java

Current condition which governed if given partition can be split between multiple writer tasks allowed only SCALED_WRITER_HASH_DISTRIBUTION. This effectively disabled writing single partition from multiple writer tasks if connector based partitioning was used, like e.g. Icebergs
day(some_timestamp_column)
```markdown
```

Relax condition for allowing writer tasks splitting

---

plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java

Leave comment why testSelectInformationSchemaColumns is isolated in Cassandra

Leave comment why testSelectInformationSchemaColumns is isolated in Cassandra

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java

- extend automatic type coercion support in Iceberg table creation to `char` type
- refactor existing tests to reduce duplication (these were essentially the same)
https://github.com/trinodb/trino/pull/13981
https://github.com/trinodb/trino/pull/20611
```markdown
* Automatically use `varchar` as type during table creation when 
`char` is specified. ({issue}`19336`). ({issue}`21515`)
```

Extend automatic type coercion support in Iceberg table creation to char

---

docs/src/main/sphinx/object-storage/legacy-s3.md
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileIterator.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemAwsS3.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/FileEntry.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/S3StorageClassFilter.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/CachingDirectoryLister.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/TrinoFileStatusRemoteIterator.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBackgroundHiveSplitLoader.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/FileSystemDirectoryLister.java

This PR supersedes this one --> https://github.com/trinodb/trino/pull/18237
TrinoS3FileSystem contains logic/configuration for skipping Glacier objects found in S3.
This PR adds the missing functionality/configuration from TrinoS3FileSystem and also adds the capability to configure the filesystem to read restored Glacier objects.
Recently, S3 added the ```RestoreStatus``` to the result of ```ListObjectsV2``` - see https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-s3-restore-status-s3-glacier-objects-list-api/ for more details.
```markdown
* Add support for reading S3 …
```

Add glacier skipping logic

---

core/trino-main/src/main/java/io/trino/sql/planner/SymbolKeyDeserializer.java
core/trino-main/src/main/java/io/trino/sql/planner/SymbolKeySerializer.java
core/trino-main/src/test/java/io/trino/sql/planner/TestSymbolSerializer.java

Fix failure when symbol name ends in colon

---

core/trino-main/src/main/java/io/trino/server/Server.java

This uses the "well known" trick, used already elsewhere in the code, to use the anonymous inner class to force reification of type parameters, so that `Key` can get the exact type parameter information via reflection. This saves us a utility method and an unchecked cast.
-
```markdown
```

Replace uses of newParameterizedType

---

docs/src/main/sphinx/connector/snowflake.md
plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java
plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeTypeMapping.java

Second part of https://github.com/trinodb/trino/pull/21012.
Support config properties `unsupported-type-handling` and `jdbc-types-mapped-to-varchar`.
```markdown
* Support type mapping configuration properties `unsupported-type-handling` and `jdbc-types-mapped-to-varchar`. ({issue}`21528`)
```

Support type mapping configs in Snowflake Connector

---

plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java

Ran stress tests locally. 
Fixes https://github.com/trinodb/trino/issues/21247

Fix flaky TestCassandraConnectorTest

---

core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineCompiler.java
core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutinePlanner.java
core/trino-main/src/test/java/io/trino/sql/routine/TestSqlFunctions.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java

The labels are used for LEAVE, ITERATE inside LOOP, REPEAT or WHILE.
When generating function bytecode, the `SqlRoutineCompiler` relied on
identity of `IrLabel` objects, which is maintained by the
`SqlRoutinePlanner`. However, if the function IR is transferred to a
worker, the identity is lost which was resulting in function compilation
error. This commit fixes this by generating unique labels names in the
function planner and identifying IR labels by value in the function
compiler.
Fixes https://github.com/trinodb/trino/issues/21682

Fix compilation of SQL functions with labels

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/SkipArchiveRequestHandler.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseSharedMetastoreTest.java

Fixes #21391
```markdown
* Fix failure when executing `migrate` procedure with partitioned Hive tables on Glue. ({issue}`21391`)
```

Fix failure when migrating partitioned Hive table in Glue

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesFunction.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Deprecate 'schema' and 'table' arguments in Iceberg `table_changes` function as they are reserved keywords and Delta Lake connector uses 'schema_name' and 'table_name'. 
```markdown
```

Deprecate 'schema' and 'table' arguments in Iceberg `table_changes` function

---

core/trino-main/src/main/java/io/trino/memory/MemoryManagerConfig.java
core/trino-main/src/test/java/io/trino/memory/TestMemoryManagerConfig.java
docs/src/main/sphinx/admin/properties-query-management.md

```markdown
* Reduce delay in killing of queries when the cluster runs out of memory ({issue}`issuenumber`)
```

Decrease query.low-memory-killer.delay to 30s

---

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcModule.java

Example failure: https://github.com/trinodb/trino/actions/runs/8841476507/job/24278659109
```
Error:    TestJdbcCachingConnectorSmokeTest>BaseConnectorSmokeTest.testRenameSchema:418->AbstractTestQueryFramework.assertUpdate:405->AbstractTestQueryFramework.assertUpdate:410 » QueryFailed Timeout trying to lock table "SYS"; SQL statement:
DROP SCHEMA "TEST_RENAME_SCHEMA_TJNEG1VTKF_RENAMED" [50200-224]
```
H2 documentation: https://www.h2database.com/html/features.html

Increase lock timeout from 1s to 5s in H2

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/fileio/ForwardingFileIo.java
pom.xml

This change upgrades Iceberg to 1.5.1 in the project. 1.5.1 fixes the regression in the default FileIO implementation to do an extra head request for manifest reads. Trino was not impacted by this regression since we overrode the ForwardingFileIO implementation to avoid it. Now since 1.5.1 addresses this, we can simplify the implemenation.
There are other fixes in 1.5.1 as well. For more details see https://github.com/apache/iceberg/milestone/45
```markdown
```

Upgrade to Iceberg 1.5.1

---

core/trino-main/src/main/java/io/trino/operator/DriverFactory.java

It can happen that operator factories live longer than operators what can cause that considerable amount of memory is not freed. Specifically, `PartitionedLookupSourceFactory` (that retained size can be very big) is kept by chain of reference `JoinBridgeManager <- HashBuilderOperator <- operatorFactories <- driverFactory` even if operators are finished.
```markdown
```

Nullify DriverFactory#operatorFactories on noMoreDrivers

---

.mvn/wrapper/maven-wrapper.properties
client/trino-cli/pom.xml
client/trino-client/pom.xml
client/trino-jdbc/pom.xml
mvnw
pom.xml

This introduces following improvements:
- better support for JDK 21-23 due to upgraded maven plugins and dependencies (PMD finally working on JDK 21)
- [reproducible maven build support](https://maven.apache.org/guides/mini/guide-reproducible-builds.html) (out of the box)
- checkstyle improvements to allow for `unnamed variables & patterns` (see https://openjdk.org/jeps/443)
- updates to some dependencies

Update airbase to 155 and friends

---

core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java

In case of single view error (e.g Hive views are not supported) listing is failing.
This change filter outs views causing errors from lists returned when listing views or comments.
```markdown
* Suppress not supported view errors during metadata listing
```

Suppress single view errors during metadata listing. 

---

core/trino-main/src/main/java/io/trino/sql/relational/SpecialForm.java
core/trino-main/src/test/java/io/trino/sql/routine/TestSqlFunctions.java

This is causing some queries that are executed in a distributed fashion to fail.
Fixes https://github.com/trinodb/trino/issues/19820

Serialize function dependencies for SpecialForm

---

core/trino-main/src/main/java/io/trino/execution/executor/dedicated/SplitProcessor.java
core/trino-main/src/test/java/io/trino/execution/TestConnectorTracingContextPropagation.java

After migrating from Trino 435 to the current version, we noticed that the tracing context no longer propagated into our custom connectors. Connector spans are detached from the parent span and stored as separate traces.
**Trino 435**
**Trino 444**
This PR fixes span propagation. It also adds a test to cover any possible future regressions.
```markdown
* Fixed tracing context propagation in connector
```

Fix tracing context propagation during connector invocation

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesFunction.java

Documentation follow-up from https://github.com/trinodb/trino/pull/15677
Fixes https://github.com/trinodb/trino/issues/21227
Iceberg Spark counterpart https://iceberg.apache.org/docs/latest/spark-procedures/#create_changelog_view
Delta Lake `table_changes` table function documenation https://trino.io/docs/current/connector/delta-lake.html#table-changes

Document `table_changes` Iceberg table function

---

plugin/trino-mysql-event-listener/pom.xml
plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListenerFactory.java

mysql-jdbc-driver is not registered in mysql-event-listener plugin, resulting in the following error:
```
Unable to create injector, see the following errors:
1) Error notifying ProvisionListener LifeCycleModule$$Lambda$4541/0x0000000803c86238 of MysqlEventListener.
Reason: LifeCycleStartException: Exception in PostConstruct method MysqlEventListener::createTable()
at MysqlEventListenerFactory.lambda$create$0(MysqlEventListenerFactory.java:65)
while locating MysqlEventListener
...
Caused by: java.sql.SQLException: No suitable driver found for jdbc:[mysql://]...
```

Fix no suitable driver found in MySQL event listener

---

lib/trino-filesystem-cache-alluxio/pom.xml
lib/trino-filesystem-cache-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioCoordinatorFileSystemCache.java

If a connector does not support caching on a Coordinator, Trino instantiates Alluxio JMX statistics but quietly disables caching.  As a result, it appears that caching is instantiated and is operating.  Consequently, it's really confusing when caching doesn't work but there is no indication why.
This PR will issue a warning on startup to let the user know that caching has been disabled for the Coordinator.
Considering this is a trivial PR, I didn't create a ticket.  But if that is appropriate, I will open an issue.   
N/A
(x) This is just a logging message, and no release notes are required.

Log a message if file system caching is disabled on coordinator

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java

Having this additional piece of information about open writers would make tuning easier for users.

Add information about current open writers to Iceberg max open writers error message

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveMetadataListing.java

In case of view error (e.g Table StorageDescriptor is null) listing is failing.
After this change HiveMetadata::getViews will filter out such views.
```markdown
* Suppress not supported view errors during metadata listing
```

Ignore failing Hive views during listing

---

plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisMetadata.java
plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisSplitManager.java
plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisStreamDescription.java
plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisStreamFieldDescription.java
plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisStreamFieldGroup.java
plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisTableDescriptionSupplier.java
plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisTableHandle.java
plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/s3config/S3TableConfigClient.java
plugin/trino-kinesis/src/test/java/io/trino/plugin/kinesis/TestKinesisTableDescriptionSupplier.java
plugin/trino-kinesis/src/test/java/io/trino/plugin/kinesis/s3config/TestS3TableConfigClient.java

Convert some classes to record in Kinesis

---

core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4

Since EXECUTE is a keyword, in order to grant an
EXECUTE privilege using SQL, it must be in the
enumerated list of privileges in the grammar.
```markdown
```

Enumerate EXECUTE privilege

---

core/docker/build.sh

Added the verification of architectures parameters  during image build. 
Otherwise, directly building an image with the wrong parameters will result in the following error.
```
ERROR: failed to solve: ghcr.io/airlift/jvmkill:latest: no match for platform in manifest sha256:7297eb25c9011daee5f577784c82622e25d6c4ca16bbbb12079b56a186e8aebf: not found
```
(x ) This is not user-visible or docs only and no release notes are required.

Added the verification of architectures parameters.

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DeltaLakeTestUtils.java

In the commit 06633b96 there has been removed a source of flakiness in the tests involving Databricks infrastructure by empowering `FlakyTestRetryAnalyzer` to take care of them:
```
@Flaky(issue = DATABRICKS_COMMUNICATION_FAILURE_ISSUE, match = DATABRICKS_COMMUNICATION_FAILURE_MATCH)
```
However, in the `setup()` methods there may be also made calls to Databricks (see `io.trino.tests.product.deltalake.TestDeltaLakeCheckpointsCompatibility#setup`).
This PR is wrapping with a failsafe retry policy the calls to Databricks.
Follow-up from 06633b96
There has been taken into consideration changing `io.trino.tests.product.utils.QueryExecutors#onDelta` to contain a retry policy for communication failures. However this option has been discarded because we may have unexpected outcomes when retrying …

Retry queries on Databricks when dealing with a communication failure

---

docs/src/main/sphinx/routines/examples.md

This PR improves grammar and wrapping for the examples.md page for SQL routines.
```markdown
```

Improve grammar for SQL routine example docs

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestIcebergNessieCatalogConnectorSmokeTest.java

When multiple commits occur concurrently on the same branch, the Nessie backend will throw a `NessieReferenceConflictException` for the current commit. Subsequently, from Trino, 
`IcebergNessieTableOperations` will throw a `CommitFailedException`. Iceberg will then retry the commit from 
`BaseTransaction.commitSimpleTransaction` with the latest hash, and it should succeed if no other concurrent commits occurred.
Due to concurrent commits, the default retry count (4) may not be sufficient for the commits to succeed.
The `TestIcebergNessieCatalogConnectorSmokeTest`, inheriting concurrent execution mode from `AbstractTestQueryFramework` is the root cause of the problem. This was addressed by overriding
it to execute in a single thread.
Fixes https://github.com/trinodb/trino/issues/20323
(x) …

Fix flakiness in TestIcebergNessieCatalogConnectorSmokeTest

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-446.md

Assemble the release notes for the upcoming Trino 446 release.
* #21469 ✅ rn ✅ docs
* #21349 ✅ rn ✅ docs
* #21582 ✅ rn ✅ docs
* #21560 ✅ rn ✅ docs
* #21598 ✅ rn ✅ docs
* #21597 ✅ rn ✅ docs
* #21605 ✅ rn ✅ docs
* #21612 ✅ rn ✅ docs
* #21596 ✅ rn ✅ docs
* #21578 ✅ rn ✅ docs
* #21613 ✅ rn ✅ docs
* #21617 ✅ rn ✅ docs
* #21572 ✅ rn ✅ docs
* #21614 ✅ rn ✅ docs
* #21518 ✅ rn ✅ docs
* #21611 ✅ rn ✅ docs
* #21610 ✅ rn ✅ docs
* #21615 ✅ rn ✅ docs
* #21606 ✅ rn ✅ docs
* #21591 ✅ rn ✅ docs
* #21583 ✅ rn ✅ docs
* #21623 ✅ rn ✅ docs
* #21628 ✅ rn ✅ …

Add Trino 446 release notes

---

lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/sequence/TestSequenceFileReaderWriter.java
lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/text/TestTextLineReaderWriter.java
lib/trino-hive-formats/src/test/java/io/trino/hive/formats/rcfile/RcFileTester.java
pom.xml

Update to Hadoop 3.3.5-2

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Environment.java

Make logging about container.log to be less verbose
This logging entry can pollute test log sometimes that makes it more
challenging to diagnose issues.

Make logging about container.log to be less verbose

---

lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/BinaryValueWriter.java

Used Binary.fromReusedByteBuffer to ensure that DictionaryValuesWriter.PlainBinaryDictionaryValuesWriter copies specific positions rather than retaining entire underlying byte array from the Block
Fixes https://github.com/trinodb/trino/issues/21745
```markdown
* Fix under accounting of memory usage for writing strings in parquet. ({issue}`21745`)
```

Avoid over retaining memory for strings in parquet writer

---

core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/GatherPartialTopN.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestGatherPartialTopN.java
core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestPartialTopNWithPresortedInput.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java

Gathering TopN avoids unnecessary network overhead, especially when both the number of splits and the TopN limit are big.
```
* Improve performance of ORDER BY queries with LIMIT on large data sets. ({issue}`21761`)
```

Gather partial TopN results

---

client/trino-cli/pom.xml

Added a simple debug (not committed here) to check for the provider implementation:
```
JDK 22:
(base) ➜  trino git:(serafin/jline-fixes) ✗ ./client/trino-cli/target/trino-cli-447-SNAPSHOT-executable.jar
Provider is TerminalProvider[ffm]
Provider is TerminalProvider[ffm]
trino> exit
(base) ➜  trino git:(serafin/jline-fixes) ✗ sdk use java 21-tem
Using java version 21-tem in this shell.
JDK 21:
(base) ➜  trino git:(serafin/jline-fixes) ✗ ./client/trino-cli/target/trino-cli-447-SNAPSHOT-executable.jar
Provider is TerminalProvider[jni]
Provider is TerminalProvider[jni]
trino> exit
(base) ➜  trino git:(serafin/jline-fixes) ✗ sdk use java 8.0.402-zulu
Using java version 8.0.402-zulu in this shell.
JDK8:
(base) ➜  trino git:(serafin/jline-fixes) ✗ …
```

Switch to JNI/FFM terminal provider

---

core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsMetadata.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorMetadata.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchMetadata.java

Picking write layout based on read partitioning is a heuristic, but it's better to leave the responsibility to the connector. We don't have such heuristic for updates or execute and also connector still needs to pick the layout for new tables anyway.

Remove default insert layout inferred from table properties

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastoreConfig.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/SharedHiveMetastoreCache.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreConfig.java

Allow caching missing stats without caching missing tables.  This allows leveraging caching on un-analyzed Hive tables (with associated caching's trade-offs) without having to opt-in into caching missing tables, which has different set of trade-offs.

Finer grained cache missing control in caching hive metastore

---

core/trino-main/src/main/java/io/trino/execution/CreateFunctionTask.java
core/trino-main/src/main/java/io/trino/metadata/LanguageFunctionAnalysisException.java
core/trino-main/src/main/java/io/trino/metadata/LanguageFunctionManager.java
core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineAnalyzer.java
core/trino-main/src/test/java/io/trino/sql/routine/TestSqlRoutineAnalyzer.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Fixes #21357
```markdown
* Fix error location markers for SQL routines. ({issue}`21357`)
```

Fix error location markers for SQL routines

---

pom.xml

Reference: https://github.com/trinodb/trino-coral/pull/3
```Hive
* Fix failure when translating Hive views with `EXISTS`. ({issue}`21829`)
```

Update Coral to fix translation for views with EXISTS

---

pom.xml

Actual value doesn't matter as it will be updated when release:prepare is called.
```markdown
```

Define outputTimestamp for reproducible build

---

core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushFilterThroughBoolOrAggregation.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedGlobalAggregationWithProjection.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformExistsApplyToCorrelatedJoin.java
core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
core/trino-main/src/test/java/io/trino/sql/planner/assertions/JoinMatcher.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushFilterThroughBoolOrAggregation.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedGlobalAggregationWithProjection.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformExistsApplyToCorrelatedJoin.java
core/trino-main/src/test/java/io/trino/sql/query/TestCorrelatedAggregation.java
core/trino-main/src/test/java/io/trino/sql/query/TestSubqueries.java

Improve performance of correlated exists by replacing count aggregation with bool_or,
which reduced the need to use additional symbol with mask. As a result, aggregation can be
marked as streaming and join can be marked as may skip duplicates.
[after_q21.txt](https://github.com/trinodb/trino/files/15235050/after_q21.txt)
[before_q21.txt](https://github.com/trinodb/trino/files/15235051/before_q21.txt)
```
* Improve performance of non-equality correlated exists queries. ({issue}`issuenumber`)
```

Use boolean or aggregation in correlated exists

---

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeCommitSummary.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeLocalConcurrentWritesTest.java

Allow committing operations based on delete pushdown / truncate
in a concurrent context by placing these operations right after
any other previously concurrently completed write operations.
Disallow committing the operation in any of the following cases:
- table schema change has been committed in the meantime
- table protocol change has been committed in the meantime
- add files committed in the meantime should be read by
the current operation
- remove files committed in the meantime conflict with the
add files read by the current operation
The current changes also take into consideration the `delta.isolationLevel`
table property of the Delta Lake table for DELETE/TRUNCATE operations.
Relevant example taken from Databricks documentation in regards to the
distinction between …

Add concurrent writes reconciliation for `DELETE` pushdown/`TRUNCATE` in Delta Lake

---

core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedGlobalAggregationWithProjection.java

Make test naming in TestTransformCorrelatedGlobalAggregationWithProjection consistent across all methods.

Fix test naming in TransformCorrelatedGlobalAggregationWithProjection

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/RewriteExactNumericConstant.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlClient.java

Currently `RewriteExactNumericConstant` doesn't support rewriting expressions if they are of `DOUBLE` or `REAL` type. 
This would affect the JDBC connectors in general so should implement it for each of them or do we have a generic options for JDBC ?
```markdown
```

Allow complex expression rewrites with double and real constant

---

plugin/trino-geospatial/pom.xml
plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestExtractSpatialInnerJoin.java
plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestPruneSpatialJoinChildrenColumns.java
plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestPruneSpatialJoinColumns.java
plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestRewriteSpatialPartitioningAggregation.java

Set air.compiler.fail-warnings as true in geospatial

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ProxyOptionsConfigurer.java

Fix format of ProxyOptionsConfigurer and avoid using deprecated JdkSslContext constructor in BigQuery

---

core/trino-main/src/test/java/io/trino/sql/query/TestWindow.java

The previous timeout was not sufficient for the test not to be flaky on CI.
Fixes https://github.com/trinodb/trino/issues/20077

Increase testManyFunctionsWithSameWindow timeout

---

core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/predicate/SortedRangeSet.java
core/trino-spi/src/test/java/io/trino/spi/predicate/BenchmarkSortedRangeSet.java
core/trino-spi/src/test/java/io/trino/spi/predicate/TestSortedRangeSet.java

Large dynamic filters might be intersected with other large dynamic filters (e.g. when collecting DFs and in subquery cache context).
Hence performance of such operations is important:
```
Benchmark                                                       Mode  Cnt    Score    Error  Units
BenchmarkSortedRangeSet.linearDiscreteIntersectDiscreteOnLarge  avgt   10    0,149 ±  0,001  ms/op
BenchmarkSortedRangeSet.linearIntersectDiscreteOnLarge          avgt   10  106,509 ±  1,009  ms/op
```
A bit more context: Subquery cache utilizes `TupleDomain` (intersections/equality specifically) heavily to describe the cached data (enforced and unenforced predicates including DFs) and to perform cache lookups. Hence it's critical that `TupleDomin` performs well. DFs are naturally discrete sets and …

Improve performance of discrete linear intersections (e.g. large DFs)

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-447.md

Assemble the release notes for the upcoming Trino 447 release.
* #21675 ✅ rn ✅ docs
* #21782 ✅ rn ✅ docs
* #21790 ✅ rn ✅ docs
* #21801 ✅ rn ✅ docs
* #21761 ✅ rn ✅ docs
* #21806 ✅ rn ✅ docs
* #21805 ✅ rn ✅ docs
* #21807 ✅ rn ✅ docs
* #21752 ✅ rn ✅ docs
* #21812 ✅ rn ✅ docs
* #21524 ✅ rn ✅ docs
* #21817 ✅ rn ✅ docs
* #21703 ✅ rn ✅ docs
* #21809 ✅ rn ✅ docs
* #21816 ✅ rn ✅ docs
* #21639 ✅ rn ✅ docs
* #21822 ✅ rn ✅ docs
* #21436 ✅ rn ✅ docs
* #21819 ✅ rn ✅ docs
* #21713 ✅ rn ✅ docs
* #21815 ✅ rn ✅ docs
* #21827 ✅ rn ✅ docs
* #21818 ✅ rn ✅ …

Add Trino 447 release notes

---

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryAvroConnectorTest.java

Fix broken column name test in BigQuery

---

docs/src/main/sphinx/connector/hive.md

Stumbled into this gap in the docs on https://stackoverflow.com/questions/78447353/issue-with-insert-into-statement-in-trino-version-389-using-hive-connector-ve/

Add catalog session property doc

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcMetadata.java

Since `JdbcTableHandle.constraintExpressions` is not supported by the `TableScanRedirectApplicationResult` SPI, we cannot apply redirection if constraintExpressions is present to avoid silent correctness issue
( X) Release notes are required, with the following suggested text:
```markdown
* Fix incorrect results for queries with complex predicates on JDBC connectors that utilize table scan redirections
```

Handle constraintExpressions in table scan redirection

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/DefaultThriftMetastoreClientFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/HttpThriftMetastoreClientFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftHiveMetastoreClient.java

Fixes https://github.com/trinodb/trino/issues/21885
Http Thrift metastore stopped throwing `MetaException` for `getTableMeta`, but this call returns invalid values (no results when tables are present in schema).
Logic in `ThriftHiveMetastoreClient` uses alternative `1` in case `getTableMeta` throws `MetaException` for alternative `0`. This PR changes default alternative to 1 in case HttpThriftMetastore.
https://github.com/trinodb/trino/blob/21a7f37b3b4e83fecbcc8161b68c533e9e833589/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java#L180-L200 …

Change getTableMeta alternative for HttpThrift metastore

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java

Expired snapshot deletion can throw exception in case of Io problems, this PR wraps IOException into TrinoException for better observability.
```markdown
```

Throw TrinoException in case of problems with snapshot delete

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java

- convert column type to string when get metadata from partition if table is csv table
- fixes #21810

Ensure column type is always string for CSV partitioned tables

---

.github/workflows/ci.yml

Set a distinct timeout just for the setup phase. It should either finish in few minutes or fail, no need to wait 1 hour (a timeout for the jobs).
I have seen at least twice this week that a test lane failed during setup. It failed while trying to recreate cache. Might be a network problem, no idea.
```markdown
```

Add timeout for setup step

---

core/trino-main/src/main/java/io/trino/dispatcher/LocalDispatchQuery.java
testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java

`notificationSentOrGuaranteed` guards agains't publishing queryCompletedEvent twice.
Right now, when [startExecution()](https://github.com/trinodb/trino/blob/8e5ee08e525683bb471951d808aa16df46a2d63f/core/trino-main/src/main/java/io/trino/dispatcher/LocalDispatchQuery.java#L146) wins the race, there exists a case where FinalQueryInfoListener is never triggered due to [finalQueryInfo](https://github.com/trinodb/trino/blob/8e5ee08e525683bb471951d808aa16df46a2d63f/core/trino-main/src/main/java/io/trino/execution/QueryStateMachine.java#L1273) not being set.
This change force sets `finalQueryInfo` by calling `getFullQueryInfo()` regardless of notificationSentOrGuaranteed state, which internally calls [updateQueryInfo()](https://github.com/trinodb/trino/blob/8e5ee08e525683bb471951d808aa16df46a2d6 …

Fix missing QueryCompletedEvent race condition

---

plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/TestThriftProjectionPushdown.java
plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/ThriftQueryRunner.java
testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java

`ThriftTpchService` / `ThriftIndexedTpchService` needs to be closed.
Let's close them to prevent resource leak.

Shutdown ThriftTpchService in thrift connector tests 

---

plugin/trino-exchange-filesystem/pom.xml

I don't know why it was excluded in the first place.
```
(base) ➜  trino git:(serafin/do-not-exclude-protobuf) ✗ ./mvnw dependency:tree -pl ':trino-exchange-filesystem' | grep protobuf
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.25.3:compile
[INFO] |  +- com.google.protobuf:protobuf-java-util:jar:3.25.3:compile
[INFO] |  +- io.grpc:grpc-protobuf:jar:1.62.2:compile
[INFO] |  +- io.grpc:grpc-protobuf-lite:jar:1.62.2:runtime
(base) ➜  trino git:(serafin/do-not-exclude-protobuf) ✗ git checkout master
Switched to branch 'master'
Your branch is ahead of 'origin/master' by 25 commits.
(use "git push" to publish your local commits)
(base) ➜  trino git:(master) ✗ ./mvnw dependency:tree -pl ':trino-exchange-filesystem' | grep protobuf
[INFO] |  +- …
```

Do not exclude protobuf for trino-exchange-filesystem

---

core/trino-main/src/main/java/io/trino/server/Server.java
core/trino-main/src/main/java/io/trino/server/TaskResource.java
core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
testing/trino-testing/pom.xml
testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
testing/trino-tests/src/test/java/io/trino/tests/TestWorkerRestart.java

When worker node is restarted after a crash, coordinator may be still
unaware of the situation and may attempt to schedule tasks on it.
Ideally the coordinator should not schedule tasks on worker that is not
ready, but in pipelined execution there is currently no way to move a
task.  Accepting a request too early will likely lead to some failure
and HTTP 500 (INTERNAL_SERVER_ERROR) response. The coordinator won't
retry on this.  Send 503 (SERVICE_UNAVAILABLE) so that request is
retried.
Simpler alternative to https://github.com/trinodb/trino/pull/21744.
That other PR has the problem that after worker restarts queries fail for some time because the new instance ID is not propagated. 
The test being added here should prove that we can close https://github.com/trinodb/trino/issues/21735.

Reject task on worker still starting up

---

core/trino-main/src/main/java/io/trino/metadata/InternalNode.java

Comparing by just subset of properties may lead `DiscoveryNodeManager` to have wrong state of the world. In
`DiscoveryNodeManager.refreshNodesInternal` we build a set of internal nodes (the `AllNodes` class instance) and then check whether it is different than what we already had.
relates to https://github.com/trinodb/trino/pull/21744

Include all properties in InternalNode equals

---

core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
core/trino-main/src/test/java/io/trino/sql/planner/TestConnectorExpressionTranslator.java
core/trino-spi/src/main/java/io/trino/spi/expression/StandardFunctions.java

Fixes #21952
```markdown
* Fix potential failure when queries contain `try_cast`. ({issue}`21952`)
```

Fix failure when translating $try_cast to/from connector expression

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/DefaultBigQueryMetadataFactory.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryType.java

Fix metadata processing threads leak in Big Query

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/ExecutorUtil.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java

Glue metastore uses `runParallel` utility to parallelize getting statistics across partitions, but also for one partition to parallelize getting stats for column batches. The underlying executor is fixed size, to this may lead to a dead-lock. This commit avoids the dead-lock by work stealing, i.e. asking the calling thread to participate in the work.

Fix Glue metastore deadlock when getting statistics

---

.mvn/modernizer/violations.xml
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java

It might not be necessary, but it is also hard to verify it is not necessary, so it's better to set the TCCL. The TCCL is set in pretty much all other thread pools by virtue of default behavior of thread factories created with `io.airlift.concurrent.Threads`.

Set thread context class loader in Glue threads

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseSharedMetastoreTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestSharedHiveMetastore.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestSharedGlueMetastore.java

Some tests expect only region and nation tables exist in the schema
Fixes https://github.com/trinodb/trino/issues/21962

Separate schemas in BaseSharedMetastoreTest

---

lib/trino-filesystem-cache-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioCoordinatorFileSystemCache.java

Same as https://github.com/trinodb/trino/pull/20998 but for alluxio cache on the coordinator.

Fix Alluxio CacheManager leak on coordinator

---

core/trino-main/src/main/java/io/trino/server/HttpRemoteTaskFactory.java
core/trino-main/src/main/java/io/trino/server/remotetask/ContinuousTaskStatusFetcher.java
core/trino-main/src/main/java/io/trino/server/remotetask/DynamicFiltersFetcher.java
core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java
core/trino-main/src/test/java/io/trino/server/remotetask/TestHttpRemoteTask.java

Previously, DynamicFiltersFetcher would never stop
even if failure happens and HttpRemoteTask is cleaned.
In case of remote node restart, this would lead to
infinite loop of dynamic filters fetching, because
fresh node wouldn't have requested DF version.
Fixes https://github.com/trinodb/trino/issues/18329
```markdown
* Fix graceful shutdown hanging indefinitely due to infinite loop of dynamic filter requests. ({issue}`issuenumber`)
```

Stop fetching of dynamic filters after failure or task mismatch

---

core/trino-main/src/main/java/io/trino/sql/planner/NodePartitioningManager.java

We observed high skew in FTE tasks due to overly low bucket count.
```markdown
```

Improve default bucket count in FTE

---

lib/trino-orc/src/main/java/io/trino/orc/OrcDataSourceUtils.java

While merging small reads, if the first range and second range are more than 2
GB apart, mergeAdjacentDiskRanges() throw "interger overflow" ArithmeticException because
merging those two ranges is too big to fit in a DiskRange
There was similar fix for parquet already. https://github.com/trinodb/trino/pull/2761
```markdown
* Fix reading from large ORC files. ({issue}`21587`)
```

Fixed integer overflow for merged ORC diskRange

---

docs/src/main/sphinx/connector/bigquery.md

There's a minor typo in the parameter for Big query connector, I just found it because I had to use it. 
It's simply missing a "." between bigquery and view. in the `bigquery.view-materialization-with-filter`.
The right parameter can be seen here https://github.com/trinodb/trino/blob/master/plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java#L166

fixing typo in Big Query Connector docs -  "bigquery.view-materialization-with-filter"

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFlushMetadataCacheProcedure.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHive3OnDataLake.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestingThriftHiveMetastoreBuilder.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestBridgingHiveMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftHttpMetastoreClient.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestUnityMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/S3HiveQueryRunner.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAbfsConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergGcsConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestTrinoHiveCatalogWithHiveMetastore.java
testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java

Close thrift metastore client in tests

---

lib/trino-filesystem-azure/pom.xml
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemFactory.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java
plugin/trino-delta-lake/pom.xml
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java

Fix Azure http client leak in Azure filesystem

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieCatalogModule.java

This doesn't fix anything yet, because NessieIcebergClient.close calls HttpApiV1.close, which calls RestV1Client.close, which calls, JavaHttpClient.close, which nulls out JavaHttpClient.client, without closing it.

Close Nessie client

---

core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveMetadataListing.java

In case of table error (e.g Table SerdeInfo is null) listing is failing.
This change filter outs views causing errors from lists returned when listing tables.
```
"type": "io.trino.spi.TrinoException",
"message": "Table SerdeInfo is null for table 'table'
"stack":
"io.trino.plugin.hive.metastore.glue.converter.GlueToTrinoConverter.convertTable(GlueToTrinoConverter.java:167)",
"io.trino.plugin.hive.metastore.glue.GlueHiveMetastore.getTable(GlueHiveMetastore.java:282)",
"io.trino.plugin.hive.metastore.tracing.TracingHiveMetastore.lambda$getTable$2(TracingHiveMetastore.java:103)",
"io.trino.plugin.hive.metastore.tracing.Tracing.withTracing(Tracing.java:39)",
"io.trino.plugin.hive.metastore.tracing.TracingHiveMetastore.getTable(TracingHiveMetastore.java:103)", …
```

Suppress single table errors during metadata listing

---

core/trino-main/src/main/java/io/trino/sql/gen/RowConstructorCodeGenerator.java

Allows reusing temporary variables with the same on-stack type across fields in RowConstructorCodeGenerator. This approach is already taken in the large row codepath and can reduce the generated code size when multiple fields have the same matching type.
Related change in PR https://github.com/airlift/bytecode/pull/18 so that this style of variable reuse can be extended to share temp variables between different code generators producing code within the same method scope.

Reuse temp variables in Row Constructor code

---

core/trino-main/src/main/java/io/trino/sql/gen/RowConstructorCodeGenerator.java
pom.xml

Updates `airlift/bytecode` to 1.6 and then modifies `RowConstructorCodeGenerator` to reuse variables within the same
method scope instead of just locally within the same row constructor instance. This can significantly reduce the generated code size for complex expressions involving multiple row constructors within them.
Uses https://github.com/airlift/bytecode/pull/18 to reduce `RowConstructorCodeGenerator` code size

Reuse more variables in row constructors

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/DockerContainer.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java

This reverts commit ca209630136eabda2449594ef2b6a4d82fb9c2e5.
This causes PT flakiness from time to time.
```markdown
```

Revert "Limit product tests Trino nodes memory"

---

.mvn/jvm.config
core/docker/default/etc/jvm.config
core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java
core/trino-server-rpm/src/main/resources/dist/config/jvm.config
core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java
docs/src/main/sphinx/installation/deployment.md
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeCompatibility.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteCompatibility.java
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-all/jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-ignite/jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-snowflake/jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-master-jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-worker-jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/jvm-pre-jdk22.config

https://bugs.openjdk.org/browse/JDK-8329528
`G1NumCollectionsKeepPinned`: "After how many GCs a region has been found pinned G1 should  give up reclaiming it."
Fixes https://github.com/trinodb/trino/issues/21989
This flag defaults to 8: https://github.com/openjdk/jdk22u/blob/f5ce46f27e5489234d1305e0573e42898c9e9e32/src/hotspot/share/gc/g1/g1_globals.hpp#L327
More info:
https://github.com/openjdk/jdk22u/blob/f5ce46f27e5489234d1305e0573e42898c9e9e32/src/hotspot/share/gc/g1/g1CollectionSet.cpp#L370

Apply workaround for JDK-8329528

---

core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java
core/trino-main/src/main/java/io/trino/operator/exchange/LocalExchange.java
core/trino-main/src/main/java/io/trino/sql/planner/NodePartitioningManager.java

The default bucket count is used by both remote and local
exchanges to assign buckets to nodes and drivers.
Follow up of https://github.com/trinodb/trino/pull/21977
```markdown
```

Account for local exchanges in getDefaultBucketCount

---

docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/DefaultThriftMetastoreClientFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/HttpThriftMetastoreClientFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreConfig.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveCustomCatalogConnectorSmokeTest.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestHiveMetastoreCatalogs.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftHiveMetastoreClient.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftMetastoreConfig.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestingTokenAwareMetastoreClientFactory.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveMetastoreClientFactory.java

Currently Trino is constrained to utilize the default hive catalog (referred to as `"hive"`) when interfacing with the hive metastore. Consequently, users are confined to employing only a two-level hierarchy (`schema.table`) within a Trino catalog/connector. In contrast, Hive thrift allows for custom hive catalog names as the parent of the schema, enabling the utilization of a three-level hierarchy such as `hive-catalog.schema.table`.
Hive Thrift API supports custom catalog since [Hive3](https://issues.apache.org/jira/browse/HIVE-18685?jql=project%20in%20(THRIFT%2C%20HIVE)%20AND%20text%20~%20%22support%20catalog%22)
Therefore, at high level, this PR has the following changes
1. Customize the hive catalog name within Trino's catalog settings and transmit it via the factories to the Thrift …

Add support for the custom hive catalog to support Hive3

---

.github/workflows/milestone.yml

```
+ ./mvnw -v
Unrecognized VM option 'G1NumCollectionsKeepPinned=10000000'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Fix milestone workflow

---

core/trino-main/src/main/java/io/trino/operator/aggregation/state/StateCompiler.java
core/trino-main/src/main/java/io/trino/sql/gen/ArrayConstructorCodeGenerator.java
core/trino-main/src/main/java/io/trino/sql/gen/BetweenCodeGenerator.java
core/trino-main/src/main/java/io/trino/sql/gen/BytecodeUtils.java
core/trino-main/src/main/java/io/trino/sql/gen/DereferenceCodeGenerator.java
core/trino-main/src/main/java/io/trino/sql/gen/InCodeGenerator.java
core/trino-main/src/main/java/io/trino/sql/gen/LambdaBytecodeGenerator.java
core/trino-main/src/main/java/io/trino/sql/gen/NullIfCodeGenerator.java
core/trino-main/src/main/java/io/trino/sql/gen/SwitchCodeGenerator.java
core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineCompiler.java

Updates more code generators to use `Scope#getOrCreateTempVariable` to increase variable reuse opportunities and reduce overall generated code size.
Follows up on work done in https://github.com/trinodb/trino/pull/22004 on `RowExpressionCodeGenerator` and enabled by https://github.com/airlift/bytecode/pull/18

Reuse temp variables in other code generators

---

plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/IndexMetadata.java

Minor cleanup in Elasticsearch connector

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java

Avoid redundant path suffix check in `TrinoRestCatalog`
```markdown
```

Avoid redundant tail slash check in TrinoRestCatalog

---

docs/src/main/sphinx/connector/delta-lake.md
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableType.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/util/PageListBuilder.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeSharedMetastoreWithTableRedirectionsTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePartitioning.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeTableName.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeSystemTableCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeRedirect.java

Add partitions system table to Delta Lake Connector
This PR implements the `$partitions` system table in the Delta Lake Connector. 
Closes https://github.com/trinodb/trino/issues/18590. This PR iterates off a [previously closed PR](https://github.com/trinodb/trino/pull/20735/). I spoke with the original author and he is fine with me taking over where he has left off, so moving forward, I will add additional changes to closing out the issue.
In this PR, when querying `$partitions`, the returning columns are `partition`, `file_count`, and `total_size`, `data`.
cc @findinpath @ebyhr
```markdown
* Add support for `$partitions` system table ({issue}`18590`)
```

Add `$partitions` system table to Delta Lake Connector

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java

In case External REST catalog throws exception it should be wrapped into TrinoException and have more clear error type.
Example stack:
```
"type": "org.apache.iceberg.exceptions.ForbiddenException",
"message": "Forbidden: Access Denied",
"stack": [
"org.apache.iceberg.rest.ErrorHandlers$DefaultErrorHandler.accept(ErrorHandlers.java:212)",
"org.apache.iceberg.rest.ErrorHandlers$NamespaceErrorHandler.accept(ErrorHandlers.java:180)",
"org.apache.iceberg.rest.ErrorHandlers$NamespaceErrorHandler.accept(ErrorHandlers.java:166)",
"org.apache.iceberg.rest.HTTPClient.throwFailure(HTTPClient.java:201)",
"org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:313)",
"org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:252)", …
```

Throw TrinoException in dropNamespace when REST error

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java

The default page size is 50. Increasing it to 100 should reduce the overhead of making API calls without making the responses too big.

Increase the default page size for listing BigQuery schemas and tables

---

docs/src/main/sphinx/connector/clickhouse.md
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseTypeMapping.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java

This PR depends partially addresses https://github.com/trinodb/trino/issues/7100 (only textual types for now).
Type mapping unit tests were extended with more cases. In addition to `Type` and `Nullable(Type)` I'm testing whether `LowCardinality` modifier causes issues. In the past ClickHouse had some incompatibilities between regular and LowCardinality types, therefore it's worth putting them in the unit tests.
Only equality predicate is enabled for now as ClickHouse does not support collation. Respective unit tests were put into `TestClickHouseConnectorTest.testTextualPredicatePushdown`.
I hope to continue working on https://github.com/trinodb/trino/issues/7100 to support pushdown for more more types (enums, decimals, etc).
(X) Release notes are required, with the following suggested …

Enable varchar equality predicate pushdown for ClickHouse connector

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Fixes #21511
Supersedes #21055 with connector side approach
```markdown
* Automatically use `varchar` in struct types as a type during table creation when `char` is specified. ({issue}`21511`)
* Automatically use microsecond precision for temporal types in struct types as a type during table creation. ({issue}`21511`)
```

Support type coercion for structural types in Iceberg and Delta Lake

---

core/trino-main/src/main/java/io/trino/operator/join/SortedPositionLinks.java

It's implemented by the interface:
```
@Deprecated
@Override
default int compare(Integer ok1, Integer ok2) {
return compare(ok1.intValue(), ok2.intValue());
}
```

Unimplement deprecated fastutil method

---

core/trino-main/src/main/java/io/trino/server/InternalAuthenticationManager.java
core/trino-main/src/main/java/io/trino/server/security/jwt/FileSigningKeyLocator.java
core/trino-main/src/main/java/io/trino/server/security/jwt/JwkSigningKeyLocator.java
core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticator.java
core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticatorSupportModule.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Service.java
core/trino-main/src/main/java/io/trino/server/ui/FormWebUiAuthenticationFilter.java
core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
core/trino-main/src/test/java/io/trino/server/security/jwt/TestJwkDecoder.java
core/trino-main/src/test/java/io/trino/server/security/oauth2/BaseOAuth2WebUiAuthenticationFilterTest.java
core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithRefreshTokens.java
pom.xml
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/S3ClientFactory.java

Resolve jjwt deprecations

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java

Invalidate remoteDatasetIdCache when after creating or dropping a schema.
This PR improves `SHOW SCHEMAS` speed 60 seconds → ~1 second with 75 schemas.
```markdown
* Improve performance when listing schemas and `bigquery.case-insensitive-name-matching` is enabled. ({issue}`issuenumber`)
```

Improve speed when bigquery.case-insensitive-name-matching is enabled

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/DefaultBigQueryMetadataFactory.java

Hopefully, this change makes CI stable. 

Use storage API in BigQueryMetadata.finishInsert

---

docs/src/main/sphinx/object-storage/file-system-s3.md
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemConfig.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemFactory.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemConfig.java

The stress testing and benchmarking of the S3 filesystem revealed errors in Hive connector  as below:
```
Caused by: java.io.IOException: Failed to list location: s3://benchmark-sep-hive-us-east-2-tpcds-sf1000-01/sf1000/catalog_returns/cr_returned_date_sk=2451790
at io.trino.filesystem.s3.S3FileSystem.listFiles(S3FileSystem.java:195)
at io.trino.filesystem.manager.SwitchingFileSystem.listFiles(SwitchingFileSystem.java:110)
at io.trino.filesystem.tracing.TracingFileSystem.lambda$listFiles$4(TracingFileSystem.java:109)
at io.trino.filesystem.tracing.Tracing.withTracing(Tracing.java:47)
at io.trino.filesystem.tracing.TracingFileSystem.listFiles(TracingFileSystem.java:109)
at io.trino.filesystem.ForwardingTrinoFileSystem.listFiles(ForwardingTrinoFileSystem.java:89)
at …
```

Add configurable retry policy for S3 client

---

plugin/trino-thrift-testing-server/pom.xml

https://github.com/trinodb/trino/commit/8cfddff78bff6fab861cb847e3a74a147bd8ccfd#diff-1a33fdf426dd013a6e774e71e9ffcbd1a61a27ae2c57f1b1e239d416d5d6d00a removed testng from trino-testing module

Remove redundant testng exclusion from trino-thrift-testing-server

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueContext.java

`setCatalogId` method would always throw IllegalArgumentException if invoked.
```markdown
* Fixed a bug that caused exceptions when `hive.metastore.glue.catalogid` was set
```

Fix GlueContext when catalog ID is present

---

plugin/trino-hive/pom.xml
pom.xml

There are very few remaining tests that utilize TestNG.

Remove testng-specific configuration

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java

Remove REST, JDBC, Nessie from some tests in TestIcebergSparkCompatibility for reducing CI time. 
The average time is 48 minutes before this change: https://nineinchnick.github.io/trino-cicd/reports/ci-cd/ 
It's [33 minutes](https://github.com/trinodb/trino/actions/runs/9184738500/job/25257762363?pr=22062) after this PR.
Left simple read&write, concurrent insert, special characters tests. 

Remove REST, JDBC, Nessie from some tests in TestIcebergSparkCompatibility

---

plugin/trino-http-event-listener/pom.xml
plugin/trino-mysql-event-listener/pom.xml

Set air.compiler.fail-warnings as true in HTTP and MySQL event listeners

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java

Use Supplier to list datasets in BigQuery

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveMerge.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/jdbc/TestKerberosConstrainedDelegationJdbc.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/snowflake/TestSnowflake.java

Replace deprecated QueryAssert.assertThat with Assertions.assertThat

---

core/trino-main/src/main/java/io/trino/connector/StaticCatalogManager.java

In case not found catalog in catalog manager throw TrinoException with clear error type.
```
"type": "java.lang.IllegalArgumentException",
"message": "No catalog 'test'",
"stack": [
"com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)",
"io.trino.connector.StaticCatalogManager.getConnectorServices(StaticCatalogManager.java:229)",
"io.trino.connector.ConnectorCatalogServiceProvider.getService(ConnectorCatalogServiceProvider.java:40)",
"io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:57)",
```
( ) Release notes are required, with the following suggested …

Throw TrinoException in case of not found catalog

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java

In case external Glue failure in getTable function throw `TrinoException` with more clear error type.
```
"type": "com.amazonaws.services.glue.model.AccessDeniedException",
"message": "User:  is not authorized to perform: glue:GetTable on resource .... (Service: AWSGlue; Status Code: 400; Error Code: AccessDeniedException; Request ID: ; Proxy: null)",
"stack": [
"com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1879)",
"com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(AmazonHttpClient.java:1418)",
"com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1387)",
"com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClien …
```

Throw TrinoException for Glue external failures

---

core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaMetadata.java

Remove unused private fields and methods of `InformationSchemaMetadata`
The use of these members seem to have been dropped in https://github.com/trinodb/trino/pull/11341
```markdown
```

Remove unused members of InformationSchemaMetadata

---

plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java

Isolate tests that cause other tests to fail.
maybe fixes https://github.com/trinodb/trino/issues/21247

Isolate selected tests from TestCassandraConnectorTest

---

docs/src/main/sphinx/connector/iceberg.md
docs/src/main/sphinx/object-storage/metastores.md

Document Snowflake Iceberg catalog limitations
```markdown
```

Improve Snowflake Iceberg catalog docs 

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java

We could specify metastore type with JVM options before https://github.com/trinodb/trino/commit/ddf931f65c93f53ce46dfb70d3efa2cfc66b2b7a. 

Use hive.metastore of JVM options in DeltaLakeExternalQueryRunnerMain

---

lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/csv/CsvDeserializerFactory.java
lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/csv/TestCsvFormat.java

In case failing of argument checks in `CsvDeserializerFactory` and `CsvDeserializer` changing `IllegalArgumentException` to `TrinoException` with more clear error type.
```
"type": "java.lang.IllegalArgumentException",
"message": "CSV only supports VARCHAR columns: Column[name=.......],
"stack": [
"com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)",
"io.trino.hive.formats.line.csv.CsvDeserializer.lambda$new$0(CsvDeserializer.java:54)",
"com.google.common.collect.ImmutableList.forEach(ImmutableList.java:423)",
"io.trino.hive.formats.line.csv.CsvDeserializer.<init>(CsvDeserializer.java:54)",
"io.trino.hive.formats.line.csv.CsvDeserializerFactory.create(CsvDeserializerFactory.java:59)", …
```

Throw TrinoException for not supported CSV

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Fix #22071 
The exception appeared since a Iceberg value of `VARBINARY` was interpreted as a byte array (`io.trino.plugin.iceberg.IcebergPageSink#getIcebergValue`), but the Iceberg function (`org.apache.iceberg.transforms.Bucket.BucketByteBuffer`) of `bucket` requires a `ByteBuffer`.
To fix this, Iceberg value of `VARBINARY` was changed to byte buffer.
( ) Release notes are required, with the following suggested text

Fix Iceberg value for varbinary

---

docs/src/main/sphinx/connector/pinot.md
plugin/trino-pinot/pom.xml
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotLegacyDataFetcher.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotExpressionRewriter.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotSqlFormatter.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotTransformFunctionTypeResolver.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotConnectorSmokeTest.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/PinotQueryRunner.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestDynamicTable.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConnectorTest.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotLatestNoGrpcConnectorSmokeTest.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java
plugin/trino-pinot/src/test/resources/too_many_broker_rows_realtimeSpec.json

Fixes https://github.com/trinodb/trino/issues/19919
```markdown
```

Upgrade Pinot Libraries to 1.1.0

---

pom.xml

Update docker-images version to 95

---

core/trino-spi/src/main/java/io/trino/spi/type/ArrayType.java

The indeterminate operator was not checking the correct number of indexes in the dictionary. This could result in out of bounds exception or in rare situations checking too few indexes resulting in an incorrect result.
Fixes #21911
```markdown
* Fix rare out of bounds or incorrect result from indeterminate operator for array type when the data is dictionary encoded. ({issue}`21911`)
```

Fix ArrayType indeterminateOperator with a DictionaryBlock

---

plugin/trino-exchange-filesystem/pom.xml
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/azure/AzureBlobFileSystemExchangeStorage.java
plugin/trino-exchange-hdfs/pom.xml
plugin/trino-resource-group-managers/pom.xml
plugin/trino-session-property-managers/pom.xml
plugin/trino-teradata-functions/pom.xml
plugin/trino-thrift-api/pom.xml

Set air.compiler.fail-warnings as true in trino-exchange-filesystem and trino-exchange-hdfs modules

---

plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftTypeMapping.java

This reverts commit b061560d7c7b7b306e1dab06bb625f0c8e5173e9.
Since we know that CREATE TABLE succeeded the table exists when we drop it.
```markdown
```

Revert "Avoid flakiness in test when dropping table"

---

plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java

Update nessie to 0.83.2

---

lib/trino-parquet/src/main/java/io/trino/parquet/metadata/ColumnChunkMetadata.java
lib/trino-parquet/src/main/java/io/trino/parquet/metadata/IntColumnChunkMetadata.java
lib/trino-parquet/src/main/java/io/trino/parquet/metadata/LongColumnChunkMetadata.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/TrinoValuesWriterFactory.java

Avoid using some deprecated methods of Parquet

---

pom.xml

Update docker-images version to 96

---

core/trino-server-rpm/pom.xml
core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java

This makes build non-reproducible if building on different hosts. With the evalHostname set to false, localhost will be used instead.
See: https://github.com/ctron/rpm-builder/blob/master/src/main/java/de/dentrassi/rpm/builder/RpmMojo.java#L1331
```markdown
```

Do not add BUILDHOST to rpm

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java

Remove unused method from TransactionLogAccess in Delta Lake

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java

We don't need to check anything about vacuum protocol check when reading the table.
The connector already verifies unsupported writer features in VacuumProcedure:
https://github.com/trinodb/trino/blob/a5d93ee5109fc65294895a2b61acaa0ba65d8eee/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java#L190-L193
Relates to https://github.com/delta-io/delta/pull/2730
Fixes #21398
```markdown
* Add support for reading and writing tables with [VACUUM Protocol Check](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#vacuum-protocol-check). ({issue}`21398`)
```

Add support for vacuumProtocolCheck feature in Delta Lake

---

core/trino-main/src/main/java/io/trino/server/Server.java
core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java
core/trino-main/src/test/java/io/trino/server/TestTrinoSystemRequirements.java

The JVM args verification would take first argument matching, silently ignoring any subsequent matching arguments. It's unclear whether first one or last one is effective (or something else), so it's better to bail out on multiple matches.

Fail when multiple JVM args matching

---

lib/trino-filesystem-cache-alluxio/pom.xml
plugin/trino-opa/pom.xml
testing/trino-tests/pom.xml
testing/trino-tests/src/test/java/io/trino/tests/TestTestSetup.java

`junit-extensions` should be on classpath of every module using JUnit for tests.

Add junit-extensions to modules missing it

---

plugin/trino-http-server-event-listener/pom.xml
plugin/trino-http-server-event-listener/src/main/java/io/trino/plugin/httpquery/HttpServerEventListener.java
plugin/trino-http-server-event-listener/src/main/java/io/trino/plugin/httpquery/HttpServerEventListenerConfig.java
plugin/trino-http-server-event-listener/src/main/java/io/trino/plugin/httpquery/HttpServerEventListenerFactory.java
plugin/trino-http-server-event-listener/src/main/java/io/trino/plugin/httpquery/HttpServerEventListenerPlugin.java
plugin/trino-http-server-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpServerEventListener.java
pom.xml

Simple event listener exposing data via HTTP

---

core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java

The code was unnecessarily handling optional empty case in both `||`'s branches.

Simplify JVM flag checking logic

---

plugin/trino-clickhouse/pom.xml
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/ClickHouseQueryRunner.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestAltinityConnectorSmokeTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestAltinityLatestConnectorSmokeTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorSmokeTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseLatestConnectorSmokeTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseLatestTypeMapping.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java

Convert query runner to builder in ClickHouse

---

plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java

Partially addresses #7100.
This PR enables a pushdown of the following aggregation functions: `COUNT(DISTINCT)` (except varchars), `COVARIANCE`, and `CORRELATION`.
Implementation of the rest of the functions have certain nuances that require additional efforts:
- Decimal implementation truncates digits outside of the scale, while Trino rounds them up.
- Statistical functions return `NaN` values on empty sets, while Trino expects `NULL`.
I'll have a look whether limitations above can be workarounded to improve pushdown "coverage".
Continuous work on #7100.
```markdown
* Add support for pushing down execution of the `count(distinct)`, `corr`, `covar_samp`, `covar_pop` functions to the underlying database. ({issue}`7100`)
```

Enable pushdown of a few aggregation functions for ClickHouse Connector

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java

When running `CREATE [OR REPLACE] TABLE` statements for an existing table, the `finishCreate` method is currently not writing a checkpoint to the Delta Log. This PR makes it possible to write those checkpoints. It results in faster analysis times for queries that read from those tables.
We have noticed that tables recreated through this flow (`CREATE [OR REPLACE] TABLE`) have more than 2000 commits and no checkpoint, which leads to a very bad analysis time

Write checkpoint if necessary for CREATE OR REPLACE statements

---

client/trino-client/src/main/java/io/trino/client/OkHttpUtil.java
client/trino-client/src/main/java/io/trino/client/uri/TrinoUri.java

When Trino cluster is exposed through the proxy/LB that supports HTTP/2, OkHttp client can negotiate and use HTTP/2. Since we don't have support for HTTP/2 in the Trino itself, this lacks testing and therefore should be unsupported.
```markdown
```

Disable HTTP/2 negotiation for trino-client/jdbc

---

testing/trino-product-tests-groups/src/main/java/io/trino/tests/product/TestGroups.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeAzure.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeGcs.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteAzure.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteGcs.java
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-azure/delta.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-azure/iceberg.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-azure/spark-defaults.conf
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/core-site-overrides-template.xml
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/spark-defaults.conf
testing/trino-product-tests/src/main/java/io/trino/tests/product/BaseTestTableFormats.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAzure.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeGcs.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveAzure.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveGcs.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergAzure.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergGcs.java

Add more product tests coverage for native filesystem GCS and Azure

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java

Add extra diagnostics to pinpoint issue with missing spoolingOutputStats

---

lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriters.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/repdef/DefLevelWriterProvider.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/repdef/DefLevelWriterProviders.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/repdef/RepLevelWriterProvider.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/repdef/RepLevelWriterProviders.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/ColumnDescriptorValuesWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/DevNullValuesWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/RunLengthBitPackingHybridEncoder.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/RunLengthBitPackingHybridValuesWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/TrinoValuesWriterFactory.java
lib/trino-parquet/src/test/java/io/trino/parquet/BenchmarkParquetFormat.java
lib/trino-parquet/src/test/java/io/trino/parquet/BenchmarkParquetFormatUtils.java
lib/trino-parquet/src/test/java/io/trino/parquet/ParquetTestUtils.java
lib/trino-parquet/src/test/java/io/trino/parquet/TestParquetFormatBenchmark.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestData.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/BenchmarkRleBitPackingDecoder.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/TestRleBitPackingDecoderBenchmark.java
lib/trino-parquet/src/test/java/io/trino/parquet/writer/AbstractColumnWriterBenchmark.java
lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestRunLengthBitPackingHybridEncoder.java
lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestRunLengthBitPackingHybridValuesWriter.java
lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestTrinoValuesWriterFactory.java
lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestingValuesWriter.java

Optimize writing RLE runs in parquet column descriptors
Use information about nullability of Blocks to write RLE runs
for repetition and definition levels more efficiently in parquet writer
```
BenchmarkParquetFormat#write UNCOMPRESSED
Before                          After
LINEITEM                  293.0MB/s ± 2869.6kB/s (0.96%)  312.9MB/s ± 2869.2kB/s (0.90%) (N = 10, α = 99.9%)
MAP_VARCHAR_DOUBLE        345.4MB/s ± 3275.7kB/s (0.93%)  359.6MB/s ± 5555.4kB/s (1.51%) (N = 10, α = 99.9%)
LARGE_MAP_VARCHAR_DOUBLE  402.0MB/s ± 6815.6kB/s (1.66%)  448.6MB/s ± 4808.3kB/s (1.05%) (N = 10, α = 99.9%)
MAP_INT_DOUBLE            606.2MB/s ± 2136.1kB/s (0.34%)  676.1MB/s ± 5620.8kB/s (0.81%) (N = 10, α = 99.9%)
LARGE_ARRAY_VARCHAR       257.8MB/s ± 9303.4kB/s (3.52%)  275.7MB/s ± 2583.1kB/s (0.91%) …
```

Optimize writing RLE runs in parquet column descriptors

---

plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/AccumuloQueryRunner.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryQueryRunner.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraQueryRunner.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/ClickHouseQueryRunner.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchQueryRunner.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/HudiQueryRunner.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/KafkaQueryRunner.java
plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/MariaDbQueryRunner.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoQueryRunner.java
plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/OpenSearchQueryRunner.java
plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestingPhoenixServer.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/SqlServerQueryRunner.java

Warning and errors are rarely seen by engineers, but still it's better not to hide them, they may (now or in the future) contain some actionable information. When a library over-verbosely logs some warnings/errors, let's suppress these selectively.
Follows https://github.com/trinodb/trino/pull/19676

Enable warning/error logs from libraries in tests

---

docs/src/main/sphinx/connector/delta-lake.md
docs/src/main/sphinx/connector/iceberg.md

- Add info that it has to be enabled in the catalog
- Delta Lake and Iceberg connectors
This seems to have caught numerous users off guard. Maybe we should change the default to true in the longer run .. but at least this doc is required. Also I am only assuming that this also applies to unregister .. maybe @findinpath and @ebyhr can confirm?

Clarify register_table requirement

---

core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroup.java
docs/src/main/sphinx/admin/resource-groups.md
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupConfigurationManager.java
plugin/trino-resource-group-managers/src/test/resources/resource_groups_config.json

This reverts commit 74e3ffa65e18d2db7938d5e17b6036b8dac42efc.
After this change JMX metrics for resource groups were not exported at all.
Fixes https://github.com/trinodb/trino/issues/21343
```markdown
* Fix exporting JMX metrics for resource groups. ({issue}`21343`)
```

Revert "Enable JMX metrics for resource groups by default"

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/MetadataReader.java

`Statistics.setNumNulls` has been deprecated and recommended to use `Statistics.Builder`
https://github.com/apache/parquet-java/pull/458
```markdown
```

Use Statistics.Builder instead of mutating Statistics in Parquet MetadataReader

---

core/trino-main/src/main/java/io/trino/util/DateTimeUtils.java
plugin/trino-redis/pom.xml
plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisMetadata.java
plugin/trino-redis/src/test/java/io/trino/plugin/redis/util/RedisLoader.java

Set air.compiler.fail-warnings as true in Redis and remove deprecated DateTimeUtils.parseLegacyTime

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-449.md

Assemble the release notes for the upcoming Trino 448 release.
* #21980 ✅ rn ✅ docs
* #21982 ✅ rn ✅ docs
* #21991 ✅ rn ✅ docs
* #21994 ✅ rn ✅ docs
* #21996 ✅ rn ✅ docs
* #21981 ✅ rn ✅ docs
* #22003 ✅ rn ✅ docs
* #22002 ✅ rn ✅ docs
* #22004 ✅ rn ✅ docs
* #21987 ✅ rn ✅ docs
* #21944 ✅ rn ✅ docs
* #22009 ✅ rn ✅ docs
* #21999 ✅ rn ✅ docs
* #21502 ✅ rn ✅ docs
* #22012 ✅ rn ✅ docs
* #21755 ✅ rn ✅ docs
* #22011 ✅ rn ✅ docs
* #21986 ✅ rn ✅ docs
* #22019 ✅ rn ✅ docs
* #22017 ✅ rn ✅ docs
* #22016 ✅ rn ✅ docs
* #22014 ✅ rn ✅ docs
* #22015 ✅ rn ✅ …

Add Trino 449 release notes

---

plugin/trino-openlineage/pom.xml

Fix CI failure: https://github.com/trinodb/trino/actions/runs/9325542244/job/25672737398
```
Error:  Failures: 
Error:    TestTestSetup.testSetupOfTests:45 Errors: 
Missing dependency on io.airlift:junit-extensions in /home/runner/work/trino/trino/plugin/trino-openlineage/pom.xml
```

Add junit-extensions to OpenLineage

---

plugin/trino-openlineage/pom.xml
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListener.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/config/OpenLineageListenerConfig.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/MarquezServer.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/OpenLineageListenerQueryRunner.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineageClientHttpTransportConfig.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineageEventListenerMarquezIntegration.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineageListener.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineageListenerConfig.java

Minor fixes in OpenLineage

---

plugin/trino-openlineage/pom.xml

OpenLineage event listener fails to initialize with HTTP transport
```
2024-06-02 00:35:10 2024-06-02T07:35:10.985Z    INFO    main    io.trino.eventlistener.EventListenerManager     -- Loading event listener etc/openlineage-event-listener.properties --
2024-06-02 00:35:11 2024-06-02T07:35:11.031Z    INFO    main    org.hibernate.validator.internal.util.Version   HV000001: Hibernate Validator 8.0.1.Final
2024-06-02 00:35:11 2024-06-02T07:35:11.168Z    INFO    main    Bootstrap       PROPERTY                                              DEFAULT                                                                RUNTIME                                                                DESCRIPTION
2024-06-02 00:35:11 2024-06-02T07:35:11.168Z    INFO    main    Bootstrap …
```

fix open lineage runtime failure with HTTP transport

---

plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotSegmentPageSource.java

Simplify write methods in PinotSegmentPageSource

---

plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/config/http/OpenLineageClientHttpTransportConfig.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/transport/OpenLineageTransport.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/transport/http/OpenLineageHttpTransport.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineageClientHttpTransportConfig.java

Use URI type in OpenLineage config

---

core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java

This reverts commit 459fa066f2b3bb7d70e438c6610cd9101c41a89c. Records should be used for data carriers.

Convert QueryRunner to an ordinary class

---

plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSplitManager.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraSplitManager.java

This PR fixes `cassandra.partition-size-for-batch-select` behavior that uses one more partition than expected when executing CQLs.
Firstly, prepare a Cassandra table and records:
```console
$ cqlsh
Connected to Test Cluster at 127.0.0.1:9042
[cqlsh 6.1.0 | Cassandra 4.1.3 | CQL spec 3.4.6 | Native protocol v5]
Use HELP for help.
cqlsh> CREATE TABLE test_cassandra_split_manager_keyspace.single_partition_key_column_table (partition_key int, clustering_key text, PRIMARY KEY(partition_key, clustering_key));
cqlsh> INSERT INTO test_cassandra_split_manager_keyspace.single_partition_key_column_table (partition_key, clustering_key) VALUES (0, '0');
cqlsh> INSERT INTO test_cassandra_split_manager_keyspace.single_partition_key_column_table (partition_key, clustering_key) VALUES (1, '1');
cqlsh> …
```

Make cassandra.partition-size-for-batch-select work expectedly

---

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java
core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushFilterIntoValues.java
core/trino-main/src/test/java/io/trino/cost/TestOptimizerConfig.java
core/trino-main/src/test/java/io/trino/sql/planner/AbstractPredicatePushdownTest.java
core/trino-main/src/test/java/io/trino/sql/planner/TestDereferencePushDown.java
core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
core/trino-main/src/test/java/io/trino/sql/planner/TestRemoveDuplicatePredicates.java
core/trino-main/src/test/java/io/trino/sql/planner/TestSimplifyIn.java
core/trino-main/src/test/java/io/trino/sql/planner/TestUnwrapCastInComparison.java
core/trino-main/src/test/java/io/trino/sql/planner/TestUnwrapYearInComparison.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushFilterIntoValues.java
core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesPlans.java
core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestPartialTopNWithPresortedInput.java
core/trino-main/src/test/java/io/trino/sql/query/TestJoin.java
core/trino-main/src/test/java/io/trino/sql/query/TestSubqueries.java

Should unblock other optimizations, like inlining values into join as project.
Adds a new session property `optimizer.push-filter-into-values-max-row-count` wih default value 100. It should be documented.

Add optimizer rule to push filter into values

---

docs/src/main/sphinx/connector/hive.md
docs/src/main/sphinx/object-storage/file-formats.md

- Also rejig some file format stuff as side effect

Add docs for OpenX_JSON serde

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/FailingExecutor.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataConfig.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataSessionProperties.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcMetadataConfig.java
plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java
plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClientModule.java
plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClientModule.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClientModule.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/RedshiftQueryRunner.java
plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClient.java
plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClientModule.java

Before this change, when listing table columns, JDBC connectors would first list tables and then list columns of a table. Thus, when serving Trino's `information_schema.columns` or `system.jdbc.columns`, we would make O(#tables) calls to the remote database.
With this change, we utilize remote database's bulk column listing facilities to satisfy Trino's bulk column listing requests. This can be viewed as "`information_schema.columns` pass-through", although this works for both Trino's `information_schema.columns` and Trino's `system.jdbc.columns`
(`io.trino.jdbc.TrinoDatabaseMetaData.getColumns`), and does not use remote database's `information_schema.columns` directly. Instead, the commit leverages the fact that `DatabaseMetaData.getColumns` typically used to get columns of a table can …

Bulk fetch all columns from all tables in JDBC connectors

---

core/trino-main/src/main/java/io/trino/operator/DirectExchangeClient.java

The fix changes queuedClients to LinkedHashSet, this helps with the filter condition in scheduleRequestIfNecessary. In addition two for loops are modified to become one loop on Iterator.
We experienced some performance regression as a result of https://github.com/trinodb/trino/commit/1ef442738fc51d1d7cf167bf6ca413378d928026 and this is an attempt to fix the same.
(x ) Release notes are required. Please propose a release note for me.
```markdown
```

Fix a hot loop in DirectExchangeClient

---

core/trino-main/src/main/java/io/trino/metadata/Metadata.java
core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java
core/trino-main/src/main/java/io/trino/sql/planner/plan/TableWriterNode.java
core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
core/trino-main/src/main/java/io/trino/tracing/TracingMetadata.java
core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeLocalConcurrentWritesTest.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java

Spin-off from https://github.com/trinodb/trino/pull/18521
Allow committing operations based on:
-  merge mechanism (applies for regular UPDATE/DELETE/MERGE statements) 
in a concurrent context by placing these operations right after
any other previously concurrently completed write operations.
Disallow committing the operation in any of the following cases:
- table schema change has been committed in the meantime
- table protocol change has been committed in the meantime
- add files committed in the meantime should be read by
the current operation
- remove files committed in the meantime conflict with the
add files read by the current operation
The current changes also take into consideration the `delta.isolationLevel`
table property of the Delta Lake table for UPDATE/DELETE/MERGE …

Add concurrent writes reconciliation for UPDATE/MERGE/DELETE in Delta Lake

---

plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/PinotTpchTables.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConnectorSmokeTest.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java

I sometimes want to use these tables from PinotQueryRunner.main method.

Change Pinot table creator methods to static

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java

- extend automatic type coercion support in Iceberg table creation to `char` type
- generify existing test names
https://github.com/trinodb/trino/pull/21515
```markdown
```

Extend automatic type coercion support in Delta table creation to char

---

plugin/trino-pinot/pom.xml
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotSegmentPageSource.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableHandle.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotQueryBuilder.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConnectorSmokeTest.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotSplitManager.java
plugin/trino-pinot/src/test/resources/alltypes_nullable_realtimeSpec.json
plugin/trino-pinot/src/test/resources/alltypes_nullable_schema.json

Enable enableNullHandling query options in Pinot. 
* https://docs.pinot.apache.org/developers/advanced/null-value-support
* https://docs.pinot.apache.org/users/user-guide-query/query-options
```markdown
```

Enable enableNullHandling query options in Pinot

---

docs/src/main/sphinx/connector/bigquery.md
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClientFactory.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryCaseInsensitiveMapping.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java

Supersedes #19624
Fixes #10740
Test on a schema with 180 tables:
```
trino> select * from bigquery.test.test_ebi;
a
---
1
(1 row)
9.47 [1 rows, 2B] [0 rows/s, 0B/s]
trino> select * from bigquery.test.test_ebi;
a
---
1
(1 row)
2.27 [1 rows, 2B] [0 rows/s, 1B/s]
trino> select * from bigquery.test.test_ebi;
a
---
1
(1 row)
2.93 [1 rows, 2B] [0 rows/s, 1B/s]
```
```markdown
```

Add support for case insensitive name cache in BigQuery

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogParser.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java

Fixes #22184
```markdown
* TBD. ({issue}`22184`)
```

Fix failure when reading signed timestamp with time zone stats in Delta Lake

---

plugin/trino-pinot/pom.xml

https://trinodb.slack.com/archives/CGB0QHWSW/p1717675311599239
```markdown
* Fix failure when using dynamic tables. ({issue}`22301`)
```

Avoid org.locationtech.jts:jts-core exclusion in Pinot

---

docs/src/main/sphinx/release/release-449.md

Misc updates
* #22195 
* #21900 
* #22158 

Improve 449 release notes

---

docs/src/main/sphinx/object-storage/metastores.md

Docs for #21822 and the un-documented `cache-missing` property

Add docs for Hive metadata caching config

---

core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroupManager.java

The error message can be more significant which will help user to understand the query failure reason.
Fixes #21895
```markdown
* Fix some things. ({issue}`21895`)
```

Throw relevent error when query didn't match any selection rule

---

core/trino-main/src/main/java/io/trino/execution/RemoteTask.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java
core/trino-main/src/test/java/io/trino/execution/MockRemoteTaskFactory.java
core/trino-main/src/test/java/io/trino/execution/TestingRemoteTaskFactory.java

It is rare but possible to get empty spooling output stats for task which completed successfully. This may happen if we observe FINISHED task state based on received TaskStatus but are later on unable to successfully retrieve TaskInfo. In such case we are building final TaskInfo based on last known taskInfo, just updating the taskState field. The spooling output stats will not be present. As we need this information in FTE mode we need to fail such task artificially

Gracefully handle missing spooling output stats in FTE scheduler

---

client/trino-client/src/main/java/io/trino/client/uri/ConnectionProperties.java
client/trino-client/src/main/java/io/trino/client/uri/PropertyName.java
client/trino-client/src/main/java/io/trino/client/uri/TrinoUri.java
client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java
client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDatabaseMetaData.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java

This commit introduces fallback (disabled by default), which will try to use `catalog` value passed through JDBC connection when fetching Trino metadata like: `getTables`, `getColumns`, `getSchemas` with `catalog` set to `null`.
- https://github.com/trinodb/trino/issues/16361
- https://github.com/trinodb/trino/issues/1173
```
* Add a new connection property `assumeNullCatalogMeansCurrent`. Enabling this makes a `null` value for
`catalog` parameter in `DatabaseMetaData` methods to mean the current catalog. If no current catalog is
set the behaviour is unmodified.
```

Add JDBC connection current catalog fallback parameter

---

pom.xml

There is one breaking change in the update library that caused some trouble in the Airlift: https://github.com/google/guava/commit/3f61870ac6e5b18dbb74ce6f6cb2930ad8750a43. 
Let's see whether this affects Trino tests

Update airbase to 157

---

docs/src/main/sphinx/admin/properties-http-server.md
docs/src/main/sphinx/admin/properties.md
docs/src/main/sphinx/installation/deployment.md
docs/src/main/sphinx/security/authentication-types.md
docs/src/main/sphinx/security/internal-communication.md
docs/src/main/sphinx/security/ldap.md
docs/src/main/sphinx/security/tls.md

Originally just wanted to add docs for `http-server.process-forwarded` but found that the http-server.* properties are either not found at all or sprinkled across docs. This PR adds a new properties reference page that either documents the properties or links to relevant info. 
As a result I had to also clean up some related duplication.. but it all belongs together really. 
See for example chat in https://trinodb.slack.com/archives/CG9K9MX1V/p1715826092248509
I will also create a PR related Trino Gateway docs PR.

Improve docs for HTTP server config

---

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java

Otherwise, getPartitionBy and getOrderBy methods in TableArgument SPI returns quoted column names.

Use Identifier.getValue when analyzing table function arguments

---

core/trino-main/src/main/java/io/trino/operator/aggregation/AbstractMapAggregationState.java
core/trino-main/src/main/java/io/trino/operator/aggregation/arrayagg/FlatArrayBuilder.java
core/trino-main/src/main/java/io/trino/operator/aggregation/histogram/TypedHistogram.java
core/trino-main/src/main/java/io/trino/operator/aggregation/listagg/AbstractListaggAggregationState.java
core/trino-main/src/main/java/io/trino/operator/aggregation/multimapagg/AbstractMultimapAggregationState.java
lib/trino-orc/src/main/java/io/trino/orc/stream/AbstractDiskOrcDataReader.java

Checking null before calling `sizeOf()` is redundant because it's checked inside `sizeOf()`.
```markdown
```

Avoid redundant null check before sizeOf()

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMaterializedViewDefinition.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergNodePartitioningProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSinkProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplit.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergWritableTableHandle.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TrinoSortField.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/DeleteFile.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/DeleteManager.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/EqualityDeleteFilter.java

Convert some classes to record in Iceberg

---

plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryDataFragment.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryInsertTableHandle.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPageSinkProvider.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemorySplitManager.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConfig.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryMetadata.java

Convert some classes to record and add config test in Memory connector

---

lib/trino-orc/src/main/java/io/trino/orc/OrcWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/predicate/PredicateUtils.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/CommitTaskData.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergAvroFileWriter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergOrcFileWriter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergParquetFileWriter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSortingFileWriter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/IcebergPositionDeletePageSink.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/ParquetUtil.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

Offsets can be used by readers to align splits with row-group/stripe boundaries.
For data written this change, https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/OffsetsAwareSplitScanTaskIterator.java#L30 will be used to generate 1 split per parquet row-group or orc stripe.
Fixes https://github.com/trinodb/trino/issues/9018
```markdown
* Populate `split_offsets` in file metadata to allow faster reads. ({issue}`9018`)
```

Populate split offsets when writing orc/parquet files in iceberg

---

docs/src/main/sphinx/develop/tests.md

Fix example in test guideline

---

docs/src/main/sphinx/connector/memory.md
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java

Relates to #22208
```markdown
* Add support for `TRUNCATE` statement. ({issue}`22337`)
```

Add support for TRUNCATE statement in memory connector

---

plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSession.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSessionProperties.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/util/TestCassandraClusteringPredicatesExtractor.java

As per https://trino.io/docs/current/connector/cassandra.html#requirements, Cassandra connector supports version starting from 3.0. PR tends to remove traces of unsupported version.
```markdown
```

Remove unsupported version changes in Cassandra

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Spark implementation:
* https://github.com/apache/spark/blob/201df0d7ac81f6bd5c39f513b0a06cb659dc9a3f/sql/catalyst/src/main/java/org/apache/spark/sql/connector/catalog/SupportsDeleteV2.java#L76-L82
* https://github.com/apache/iceberg/blob/c7de6cb345995cb47312edbef6edae2f17fb8aba/spark/v3.4/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java#L366-L393
```markdown
* Add support for `TRUNCATE` statement. ({issue}`22340`)
```

Add support for truncate statement in Iceberg

---

plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java

Partially addresses #7100.
Enable TopN pushdown for non-textual types for clickhouse-connector: `ORDER BY col LIMIT N` shall now be executed by ClickHouse.
Next I'll try to add support for pushdown of joins.
```markdown
* Add support for `ORDER BY ... LIMIT` pushdown on non-textual types. ({issue}`22174`)
```

Enable TopN for non-textual types for clickhouse-connector

---

core/trino-main/src/main/java/io/trino/execution/scheduler/UniformNodeSelector.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/ArbitraryDistributionSplitAssigner.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/HashDistributionSplitAssigner.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/NodeRequirements.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/SingleDistributionSplitAssigner.java
core/trino-main/src/test/java/io/trino/execution/TestNodeScheduler.java
core/trino-main/src/test/java/io/trino/execution/scheduler/TestUniformNodeSelector.java
core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestArbitraryDistributionSplitAssigner.java
core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestBinPackingNodeAllocator.java
core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestEventDrivenTaskSource.java
core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestSingleDistributionSplitAssigner.java
core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestTaskDescriptorStorage.java

UniformNodeSelector or FTE scheduler will schedule remote accessible splits on selected nodes if such nodes are available and only fallback to other nodes is nodes are no longer part of cluster. Connector might have stalled node information while creating splits which could result in selecting nodes which are now offline. Additionally, in FTE mode nodes can go down so split addresses could no longer be valid then task is restarted.
Additionally, this commit simplifies UniformNodeSelector optimizedLocalScheduling which was hard to reason about and was not taking advantages of recent improvements like adaptive split queue length.
Extracted from: https://github.com/trinodb/trino/pull/21888 …

Make scheduling of remote accessible splits with addresses more strict

---

docs/src/main/sphinx/admin/fault-tolerant-execution.md
docs/src/main/sphinx/connector/mariadb.md
plugin/trino-mariadb/pom.xml
plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java
plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/BaseMariaDbFailureRecoveryTest.java
plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbQueryFailureRecovery.java
plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbTaskFailureRecovery.java

MariaDBClient is capable of supporting retried tasks and queries, so set that flag to `true`.  Add appropriate retry tests for it.
5579e701e126051ec34d50ba37d9d586a1015263 turned on this flag for MySQLClient but not MariaDBClient.  It added several tests to ensure that the affected clients behave correctly.  It turns out that MariaDB can also pass those tests, so it makes sense to mark it as `supportsRetries=true`.
```markdown
* The MariaDB JDBC client now supports both QUERY and TASK retry policies.
```

Enable query and task retries in MariaDbClient

---

docs/src/main/sphinx/object-storage/legacy-s3.md
lib/trino-hdfs/src/main/java/io/trino/hdfs/s3/TrinoS3FileSystem.java
lib/trino-hdfs/src/test/java/io/trino/hdfs/s3/TestTrinoS3FileSystem.java

Allow users to only use the `WebIdentityTokenCredentialsProvider` instead of the default credentials provider chain.
This is preferred over #22007. This at least makes the workaround for #15267 easier, I'm not sure if it will allow closing that issue. I haven't updated the docs yet, I'll wait for some initial feedback first.
```markdown
```

Allow pinning to WebIdentityTokenCredentialsProvider in legacy S3 client

---

core/trino-main/src/main/java/io/trino/util/JsonUtil.java

Avoid allocating heap ByteBuffer used by InputStreamReader and use StringReader for small inputs. (https://github.com/FasterXML/jackson-core/pull/1081)
Before change:
```
FilterProject[filterPredicate = (CASE WHEN (data <> varchar 'second') THEN contains(transform($internal$json_string_to_array_cast(data_0), (x) -> json_extract_scalar(x, JsonPath '$.name')), data) ELSE boolean 'false' END)]
│   Layout: [data:varchar]                                                                                                          
│   Estimates: {rows: ? (?), cpu: 216.78G, memory: 0B, network: 0B}/{rows: ? (?), cpu: ?, memory: 0B, network: 0B}                  
│   CPU: 35.08s (91.80%), Scheduled: 36.97s (87.41%), Blocked: 0.00ns (0.00%), Output: 3492632 rows (34.65MB)          
```
After:
``` …
```

Improve performance of json functions

---

core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java

We observed rare cases when we got non-JSON result in doScheduleAsyncCleanupRequest and current logging does not provide enough information to understand the root cause.

Verify body in doScheduleAsyncCleanupRequest

---

lib/trino-cache/src/main/java/io/trino/cache/CacheUtils.java

The `uncheckedCacheGet` will propagate `ExecutionError` if `Cache.get` throws it.
This reverts commit 3d0632d8a63ee5acd135984ddccda98ad6ebcbc2.

Fix uncheckedCacheGet javadoc

---

docs/src/main/sphinx/admin/fault-tolerant-execution.md
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/azure/AzureBlobFileSystemExchangeStorage.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/azure/ExchangeAzureConfig.java
plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/azure/TestExchangeAzureConfig.java

This option can be used instead of `exchange.azure.connection-string` and will use the default azure credentials when set.
If a user attempts to set up an ABFS-backed exchange manager without specifying a connection string, the plugin will fail when calling `blobServiceClientBuilder.buildAsyncClient()` as the builder does not have an endpoint set. That also means one cannot use the `DefaultAzureCredential` and is only able to use authentication methods allowed via connection strings (SAS Tokens and Account Keys). This PR aims to fix that code path by adding a configuration to supply an endpoint to be injected into the builder, and makes it mutually exclusive with `exchange.azure.connection-string`. 
Generally the use-cases would be like this: 
* Use `exchange.azure.connection-string` if …

Add `exchange.azure.endpoint` configuration option

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

We were getting the value from `descriptorsByPath` only when it's a primitive type before https://github.com/trinodb/trino/pull/19066.
Fixes #22347 
```markdown
* Fix failure when reading Parquet files that don't have `field-id` on structured types. ({issue}`22347`)
```

Fix failure when reading non-primitive Parquet fields in Iceberg

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeParquetStatisticsUtils.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestDeltaLakeParquetStatisticsUtils.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointWriter.java

Example of stats generated by Spark:
* transaction log has timestamp millis in stats, e.g. `2020-08-26T01:02:03.123`
* checkpoint has timestamp millis in stats, e.g. `2024-05-29T15:08:00.991Z`
* data file has timestamp micros, e.g. `2020-08-26T01:02:03.123987` with INT64
Both int96 and int64 are allowed in parquet files: https://github.com/delta-io/delta/blob/master/PROTOCOL.md#delta-data-type-to-parquet-type-mappings
Fixes #21878
```markdown
* TBD. ({issue}`21878`)
```

Add support for stats on timestamp type in Delta Lake

---

plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/PhoenixQueryRunner.java
plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java

Phoenix connector tests take [40 minutes](https://github.com/trinodb/trino/actions/runs/9486286121/job/26141094953) on average. This is the slowest plugin except for SaaS connectors. 
Test results:
1. 18m: https://github.com/trinodb/trino/actions/runs/9491852065/job/26158062589?pr=22372
2. 18m: https://github.com/trinodb/trino/actions/runs/9491852065/job/26159720377?pr=22372
3. 18m: https://github.com/trinodb/trino/actions/runs/9491852065/job/26160159614?pr=22372

Run TestPhoenixConnectorTest in parallel

---

docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieCatalogConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieCatalogModule.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestIcebergNessieCatalogConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestTrinoNessieCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-nessie/iceberg.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg-nessie/spark-defaults.conf

By default, Nessie API version will be inferred from Nessie URI. If the User has a custom URI which doesn't have version info in the URI, user can configure `iceberg.nessie-catalog.client-api-version`
Changes at Iceberg repo: https://github.com/apache/iceberg/pull/9459
( x) Release notes are required. Please propose a release note for me.
```markdown
```

Nessie: Support APIv2 client

---

core/trino-main/pom.xml
docs/src/main/sphinx/object-storage/file-system-s3.md
lib/trino-filesystem-s3/pom.xml
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemConfig.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemFactory.java
plugin/trino-druid/pom.xml
plugin/trino-exchange-filesystem/pom.xml
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/ExchangeS3Config.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorage.java
plugin/trino-exchange-filesystem/src/test/java/io/trino/plugin/exchange/filesystem/s3/TestExchangeS3Config.java
plugin/trino-hudi/pom.xml
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/TpchHudiTablesInitializer.java
plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
plugin/trino-mongodb/pom.xml
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java

New major AWS SDK v2 deprecated ADAPTIVE retry strategy and introduces ADAPTIVE_V2 instead.

Update AWS SDKs + Hudi

---

lib/trino-cache/src/main/java/io/trino/cache/EvictableCache.java

Before the change the following race was possible between threads A, B, C:
- A calls invalidate(K)
- A increments: invalidations++
- B changes state to be cached, and therefore calls invalidate(K) too
- B increments: invalidations++
- C calls get(K)
- C reads invalidations counter
- C retrieves current token T for key K
- C reads value V for T from cache
- A reads and removes token T (same) for key K
- B attempts to read and remove token for key K, not found
- B exits invalidate(K)
- C checks invalidations counter (didn't check)
- C revives, i.e. re-inserts token T for key K
- B calls get(K)
- B retrieves token T (same) for key K
- B reads value V for T from cache -- despite B having called invalidate(K)
At least in this situation the problem is transient. Thread A will momentarily …

Fix evictable cache invalidation race condition

---

.github/workflows/annotate.yml
.github/workflows/ci.yml
.github/workflows/cleanup.yml
.github/workflows/docs.yml
testing/trino-tests/src/test/java/io/trino/tests/ci/TestWorkflows.java

GitHub allows to delete and re-publish a tag, so referencing 3rd party action by tag name should be discouraged.

Pin 3rd party CI action versions

---

core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2CallbackResource.java
core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java

This PR adds add encoding to error code in OAuth2 callback handler. Error code that is passed as query parameter to `/oauth2/callback` endpoint is used in plain html. So if error contains malicious code it will be included in error page.
```markdown
* Add encoding to error code in OAuth2 callback handler
```

Add encoding to error code in OAuth2 callback handler

---

plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Avoid abort in testing helper method or for-loop

---

lib/trino-filesystem-cache-alluxio/pom.xml
pom.xml

2.9.4 is a more stable version and we would keep backporting changes from 3xx to 2.9.x line. With 2.9.4 we would have the same code of local cache manager as 3xx and compatibility with the stable Alluxio Filesystem interface. That's why we chose to have 2.9.4 here
https://github.com/trinodb/trino/pull/21603/files#r1628261795
```markdown
```

Modify alluxio version to stable 2.9.5

---

docs/src/main/sphinx/connector/iceberg.md
docs/src/main/sphinx/object-storage/metastores.md

The default value of `iceberg.catalog.type` is `hive_metastore` but it isn't mentioned in the docs clearly.
https://github.com/trinodb/trino/blob/7a863b30c1448024feb92bbd6119943d977f80b5/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java#L59
```markdown
```

Clarify the default value of iceberg.catalog.type in Iceberg docs

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SparkMetastoreUtil.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestSparkMetastoreUtil.java

Remove unused argument from getSparkTableStatistics

---

core/trino-main/src/main/java/io/trino/operator/scalar/DateTimeFunctions.java
core/trino-main/src/test/java/io/trino/operator/scalar/BenchmarkDateTimeFunctions.java

We have observed poor performance when using the `DATE_TRUNC` function. Profiling revealed that the function spends most of its time resolving date time units. The main bottleneck is in the `io.trino.operator.scalar.DateTimeFunctions#getDateField` method. This method contains 2 string allocations and a hash lookup, which takes a noticeable amount of CPU time.
The new approach doesn't create new strings and works directly with bytes. This is possible because the date time unit can only use ASCII symbols. Also, the hash lookup has been replaced with a simple loop, which works quite well with small amounts of values.
Here is the benchmark results. All the tests were performed on Apple Silicon M1 MAX, OpenJDK 64-Bit Server VM, 22.0.1+8.
```
Benchmark …
```

Optimize DATE_TRUNC, DATE_ADD and DATE_DIFF functions for DATE and TIMESTAMP types

---

core/trino-spi/pom.xml
plugin/trino-elasticsearch/pom.xml
plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java

google cloud SDK requires an override for the opentelemetry-version (this will be updated in airbase and removed latter on).

Update cloud SDKs

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java

I sometimes want to access coordinator data directory for investigating Iceberg and Delta Lake files. 

Set hive.metastore.catalog.dir in Iceberg and Delta query runners

---

docs/src/main/sphinx/functions/geospatial.md

Fix misleading argument order in [ST_Point()](https://trino.io/docs/current/functions/geospatial.html#ST_Point) docs when creating a point from geographical coordinates.
I ended up swapping the latitude and the longitude when computing the centroid of various coordinates due to the misleading argument order in the documentation.
The order should match the one documented in [PostGis/ST_Point()](https://postgis.net/docs/ST_Point.html).
Fixes https://github.com/trinodb/trino/issues/22419

Fix argument order in ST_Point() function docs

---

pom.xml

Update docker-image version to 97

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TypeConverter.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetConnectorTest.java

We should fix Delta Lake connector as a follow-up. 
Fixes #16273

Check duplicated field names in Iceberg

---

core/trino-main/src/main/java/io/trino/dispatcher/DispatchManager.java
core/trino-main/src/main/java/io/trino/execution/QueryManagerStats.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java

Expose driver execution stats via JMX

---

docs/src/main/sphinx/object-storage/file-system-cache.md

Reported by Tom Nats on slack
```
Caused by: IllegalArgumentException: Either fs.cache.max-sizes or fs.cache.max-disk-usage-percentages must be specified
```

Clarify required configuration for fs caching

---

core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java

When startup completes (`StartupStatus.startupComplete()`), a worker will accept tasks (`TaskResource.failRequestIfInvalid`). The plugins and functions need to be installed before that happens.
Fixes https://github.com/trinodb/trino/issues/22437

Install plugins in testing server before startup completes

---

docs/src/main/sphinx/connector/pinot.md
docs/src/main/sphinx/object-storage/file-system-s3.md
docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-450.md

Assemble the release notes for the upcoming Trino 450 release.
* #22225 ✅ rn ✅ docs
* #22224 ✅ rn ✅ docs
* #22223 ✅ rn ✅ docs
* #22226 ✅ rn ✅ docs
* #22228 ✅ rn ✅ docs
* #22230 ✅ rn ✅ docs
* #22234 ✅ rn ✅ docs
* #22236 ✅ rn ✅ docs
* #22212 ✅ rn ✅ docs
* #22237 ✅ rn ✅ docs
* #22239 ✅ rn ✅ docs
* #22238 ✅ rn ✅ docs
* #22242 ✅ rn ✅ docs
* #22235 ✅ rn ✅ docs
* #21940 ✅ rn ✅ docs
* #22092 ✅ rn ✅ docs
* #22105 ✅ rn ❌ docs
* #22245 ✅ rn ✅ docs
* #22243 ✅ rn ✅ docs
* #22251 ✅ rn ✅ docs
* #22252 ✅ rn ✅ docs
* #22253 ✅ rn ✅ docs
* #22241 ✅ rn ✅ …

Add Trino 450 release notes

---

core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
core/trino-main/src/main/java/io/trino/server/DisconnectionAwareAsyncResponse.java
core/trino-main/src/main/java/io/trino/server/TaskResource.java
core/trino-main/src/main/java/io/trino/server/protocol/ExecutingStatementResource.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2TokenExchangeResource.java

With the current Jersey and Jetty implementations @Suspended AsyncResponse can generate a lot of warnings that are caused by the fact that Jetty eagerly recycles request/response objects when the HTTP/2 RST_STREAM frame is sent by the client during request aborting.
We abort in-flight requests for different reasons: either timeout is reached or when the client is closed during cleanup.
For HTTP/1 that doesn't matter, but for HTTP/2 this will cause the AsyncResponse.resume to log an error, since the underlying request/response objects are already recycled and there is no client listening for the response.
This change also cancels Future<?> bound to the AsyncContext since there is no point in processing it anymore.
( ) This is not user-visible or is docs only, and no release notes are …

Make AsyncResponse aware of the client disconnection

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java

`catalogDir` will be deleted after the test execution.

Create tables under volatile directory in TestDeltaLakeBasic

---

docs/src/main/sphinx/release/release-450.md

Fix wrong entry in 450 release note

---

core/trino-main/src/main/java/io/trino/metadata/SystemFunctionBundle.java
core/trino-main/src/main/java/io/trino/operator/scalar/ArrayTransformFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/JsonExtract.java
core/trino-main/src/main/java/io/trino/operator/scalar/JsonStringArrayExtractScalar.java
core/trino-main/src/main/java/io/trino/sql/ir/optimizer/IrExpressionOptimizer.java
core/trino-main/src/main/java/io/trino/sql/ir/optimizer/rule/SpecializeTransformWithJsonParse.java
core/trino-main/src/test/java/io/trino/operator/scalar/BenchmarkArrayTransform.java
core/trino-main/src/test/java/io/trino/operator/scalar/TestJsonStringArrayExtractScalar.java
core/trino-main/src/test/java/io/trino/sql/ir/optimizer/TestSpecializeTransformWithJsonParse.java
core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java

Optimize common case of `transform(cast(json_parse), json_extract_scalar)` to be single and more performant call of `JsonStringArrayExtractScalar`.
Example query:
```SQL
WITH t AS (SELECT a.id as id, a.data AS data FROM table_a AS a) 
SELECT b.data FROM table_b AS b, t AS a 
WHERE b.id = a.id AND  
CASE WHEN b.data <> 'second' THEN contains(transform(cast(json_parse(a.data) as array<json>), (x) -> json_extract_scalar("x", '$.name')), b.data) 
ELSE false END;
```
With change:
```
│   CPU: 8.58s (94.13%), Scheduled: 8.93s (69.96%), Blocked: 1.89s (94.59%), Output: 3492632 rows (34.65MB)                                        
```
Without:
```
│   CPU: 16.49s (95.06%), Scheduled: 17.24s (82.05%), Blocked: 2.81s (92.72%), Output: 3492632 rows (34.65MB)            
```
( ) This is not …

Add JsonStringArrayExtractScalar function

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeMinioDataLake.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeMinioDataLakeCaching.java
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-minio-data-lake-cached/delta.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-minio-data-lake/delta.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-minio-data-lake/hive.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-minio-data-lake/iceberg.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-delta-lake-oss/delta.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-delta-lake-oss/hive.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hive-hudi-redirections/hudi.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-hudi/hudi.properties
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlluxioCaching.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeJmx.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeCompatibility.java

Tests that were migrated to native fs was still using hdfs. So migrating them completely to use native-fs

Fix product tests previously migrated to native fs to not use legacy fs

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3InputStream.java
lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java

Without the fix, the modified test fails with:
```
java.io.IOException: Failed to open S3 file: s3://test-bucket-test-s3-file-system-minio/inputStream/11ae5b01-23be-4eef-ba85-8666eb3d64f7
at io.trino.filesystem.s3.S3InputStream.seekStream(S3InputStream.java:207)
at io.trino.filesystem.s3.S3InputStream.read(S3InputStream.java:94)
at io.trino.filesystem.AbstractTestTrinoFileSystem.testInputFile(AbstractTestTrinoFileSystem.java:484)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
at …
```

Fix reading empty files when using native S3 FS

---

lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsUtils.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3InputStream.java

When reading an empty file from S3 as a stream, using the AWS SDK v2, it
incorrectly keeps reading the MD5 checksum included at the end of the
response. This has been reported upstream as
https://github.com/aws/aws-sdk-java-v2/issues/3538
For GCS, skip the boundary check for empty files.
> [!IMPORTANT]
> This is a follow-up to #22469 that was not tested with all secrets. Run a workflow with all secrets before merging.

Fix reading empty files from S3 and GCS

---

docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/IcebergRestCatalogConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java

REST catalog supports a `prefix` in the resource path as per the spec. But it is not exposed from Trino `IcebergRestCatalogConfig`. In Spark, this works by default because they accept generic property bag.
Iceberg side usage:
https://github.com/apache/iceberg/blob/cbd11d7aa54a3b531f59a5e83411a163f9126a0c/core/src/main/java/org/apache/iceberg/rest/ResourcePaths.java#L31
```md
* Add support for specifying a resource [prefix](https://github.com/apache/iceberg/blob/a47937c0c1fcafe57d7dc83551d8c9a3ce0ab1b9/open-api/rest-catalog-open-api.yaml#L1449-L1455) in REST catalog. 
```

Add support for prefix configuration in Iceberg REST catalog

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergBucketFunction.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSinkProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsReader.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesFunction.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPartitionEvolution.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergUtil.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestPartitionFields.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java

Fixes https://github.com/trinodb/trino/issues/15109
Support partitioning on nested ROW fields in Iceberg
```markdown
* Add support for partitioning on nested ROW fields. ({issue}`15712`)
```

Support partitioning on nested ROW fields in Iceberg

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java

The code introduced in https://github.com/trinodb/trino/pull/22298 was lacking rescheduling replacement tasks. As a result query execution got stuck after we observed missing spooling output stats for task.
```markdown
* Fix rare error condition where query execution could block when executing with task retries enabled.
```

Reschedule replacement tasks in case of artificial failure due to missing spooling output size

---

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystem.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
pom.xml

Azure SDK version 1.2.24 includes [Azure Storage Blob 12.26](https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/storage/azure-storage-blob/CHANGELOG.md#12260-beta1-2024-04-15), which introduces a breaking change (https://github.com/Azure/azure-sdk-for-java/pull/37711/), where blob names used to create a new blob client should not be URL-encoded anymore. Blob URLs in the storage don't change, so after adjusting the API usage, data written by older Trino versions should be readable by new Trino versions.
In https://github.com/trinodb/trino/pull/21586 we added tests for special characters. …

Update Azure SDK

---

docs/src/main/sphinx/object-storage/file-system-s3.md
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemConfig.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemFactory.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemConfig.java

To make the http proxy config options in parity with legacy implementation
```markdown
```

Add more http proxy configs for native S3 filesystem implementation

---

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java
core/trino-main/src/test/java/io/trino/sql/planner/AbstractPredicatePushdownTest.java

Push down deterministic filters on partitioning symbols through TopNRankingNode. Based on similar mechanism for WindowNode.
```markdown
* Improve performance of certain queries involving `row_number`, `rank` or `dense_rank` window functions with partitioning and filter.
```

Push filter through TopNRankingNode

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionFields.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestPartitionFields.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestSortFieldUtils.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java

Fixes #12668
```markdown
* Add support for uppercase characters in `partitioning` table property. ({issue}`12668`)
```

Add support for uppercase characters in `partitioning` table property

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestHiveS3MinioQueries.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java

Add special characters missing test coverage for native-fs s3 path

---

plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduClientSession.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/KuduCreateAndInsertDataSetup.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduTypeMapping.java

When a filter is applied on a varbinary column in Kudu, previously it used to fail with 
`Unexpected java value for column` this behavior is fixed by this PR. Additionally we have also added a TypeMapping test to ensure end-to-end coverage for other supported data types as well. 
```markdown
* Fix failure when filter operation is applied on varbinary column in Kudu
```

Fix failure when filter operation is applied on varbinary column in Kudu

---

docs/src/main/sphinx/connector/kudu.md
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduPageSink.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/TypeHelper.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduTypeMapping.java

Previously Date type was mapped to `VARCHAR` and Kudu has natively added supported for `DATE` from 1.15. This PR maps Kudu Date type to Trino's Date type.
Partially fixes https://github.com/trinodb/trino/issues/11009
This PR depends on https://github.com/trinodb/trino/pull/22496
```markdown
* Add date data type support for Kudu ({issue}`issuenumber`)
```

Add date data type support for Kudu 

---

core/trino-main/src/main/java/io/trino/operator/scalar/MathFunctions.java
core/trino-main/src/test/java/io/trino/operator/scalar/TestMathFunctions.java
docs/src/main/sphinx/functions/math.md

https://support.microsoft.com/en-us/office/t-dist-function-4329459f-ae91-48c2-bba8-1ead1c6c21b2

Add t_cdf, t_distribution scalar functions

---

docs/src/main/sphinx/functions/json.md
docs/src/main/sphinx/optimizer/pushdown.md

In this PR, I edited 3 typos in the pushdown.md documents. 
```markdown
```

Fix spelling errors in documentation

---

core/trino-main/src/main/java/io/trino/sql/ir/optimizer/rule/SimplifyRedundantCase.java
core/trino-main/src/test/java/io/trino/sql/ir/optimizer/TestSimplifyRedundantCase.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveRedundantPredicateAboveTableScan.java
core/trino-main/src/test/java/io/trino/sql/query/TestIssue22530.java

Expressions of the form:
```
CASE
WHEN <cond> THEN true
ELSE false
END
```
were being simplified to `<cond>`, which is
incorrect due to null handling. The original
form would return false, while the simplified
form returns null.
The correct transformation is: `<cond> ≡ true`.
Conversely, for an expression such as:
```
CASE
WHEN <cond> THEN false
ELSE true
END
```
The correct transformation is: `not(<cond> ≡ true)`.
Fixes #22530 
```markdown
* Fix incorrect results for CASE expressions of the form `CASE WHEN ... THEN true ELSE false END`. ({issue}`22530`)
```

Fix incorrect case optimization

---

core/trino-main/src/main/java/io/trino/connector/CatalogConnector.java
core/trino-main/src/main/java/io/trino/connector/DefaultCatalogFactory.java
core/trino-main/src/main/java/io/trino/memory/MemoryPool.java
core/trino-main/src/main/java/io/trino/testing/PlanTester.java
core/trino-main/src/test/java/io/trino/execution/TestSqlTaskManagerRaceWithCatalogPrune.java
core/trino-main/src/test/java/io/trino/memory/TestMemoryPools.java
core/trino-spi/src/main/java/io/trino/spi/connector/Connector.java

allocate specific memory for each connector

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-451.md

Assemble the release notes for the upcoming Trino 451 release.
* #22440 ✅ rn ✅ docs
* #22449 ✅ rn ✅ docs
* #22447 ✅ rn ✅ docs
* #22450 ✅ rn ✅ docs
* #22429 ✅ rn ✅ docs
* #20959 ✅ rn ❌ docs
* #22379 ✅ rn ✅ docs
* #22454 ✅ rn ✅ docs
* #22457 ✅ rn ✅ docs
* #22423 ✅ rn ✅ docs
* #22464 ✅ rn ✅ docs
* #22232 ✅ rn ✅ docs
* #22466 ✅ rn ✅ docs
* #22460 ✅ rn ✅ docs
* #22469 ✅ rn ✅ docs
* #22456 ✅ rn ✅ docs
* #22473 ✅ rn ✅ docs
* #22477 ✅ rn ✅ docs
* #22441 ✅ rn ✅ docs
* #15712 ✅ rn ✅ docs
* #21602 ✅ rn ✅ docs
* #22472 ✅ rn ✅ docs
* #22494 ✅ rn ✅ …

Add Trino 451 release notes

---

plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestDruidConnectorTest.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Extract order table columns definition to separate method allows easier use of `testSelectInformationSchemaColumns` in derived tests.
```markdown
```

Extract order table columns definition to separate method

---

docs/src/main/sphinx/connector/clickhouse.md
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClientModule.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
pom.xml

Fixes #16182
```markdown
* Add support for `query` pass-through table function. ({issue}`16182`)
```

Add support for `query` pass-through table function in ClickHouse connector

---

lib/trino-parquet/src/main/java/io/trino/parquet/BloomFilterStore.java
lib/trino-parquet/src/main/java/io/trino/parquet/ParquetWriteValidation.java
lib/trino-parquet/src/main/java/io/trino/parquet/metadata/BlockMetadata.java
lib/trino-parquet/src/main/java/io/trino/parquet/metadata/PrunedBlockMetadata.java
lib/trino-parquet/src/main/java/io/trino/parquet/predicate/PredicateUtils.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/MetadataReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/RowGroupInfo.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/TrinoColumnIndexStore.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetReader.java
lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestBloomFilterStore.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/ParquetUtil.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java

Reduces memory usage by keeping only the required columns metadata in memory.
Look-up of ColumnChunkMetadata is now through a Map rather than repeatedly
iterating over all columns metadata in the footer
Fixes https://github.com/trinodb/trino/issues/22434
```markdown
* Improve performance of reading from parquet files with large schemas. ({issue}`22434`)
```

Optimize lookups of ColumnChunkMetadata in large parquet schema

---

core/trino-main/src/main/java/io/trino/execution/SplitAssignment.java
core/trino-main/src/main/java/io/trino/execution/SqlTaskExecution.java
core/trino-main/src/main/java/io/trino/execution/scheduler/NodeScheduler.java
core/trino-main/src/main/java/io/trino/execution/scheduler/SourcePartitionedScheduler.java
core/trino-main/src/main/java/io/trino/execution/scheduler/TopologyAwareNodeSelector.java
core/trino-main/src/main/java/io/trino/execution/scheduler/UniformNodeSelector.java
core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java

```
In this we improve query execution determinism by
preserving split order when scheduling
in pipeline execution mode.
This is essentially needed such that splits coming out of CacheSplitSource preserve the order
between coordinator and workers. This way we
prevent scheduling two splits with same
CacheSplitId to reuse cache within a query.
```
```markdown
```

Improve determinism by preserving split order

---

plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduClientSession.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java

Trino: 451
When I try to add column, which type is decimal(14,4), to the kudu table, I encountered a java.lang.NullPointerException.
I found that when adding a decimal type field, **precision and scale were not passed in**, resulting in a java.lang.NullPointerException.
Then I fix this.
```
trino> ALTER TABLE catalog.default.table ADD COLUMN buyer_order_pay_price_2 DECIMAL(14,4);
Query 20240701_083955_00002_ysg8b failed: Cannot invoke "org.apache.kudu.ColumnTypeAttributes.getPrecision()" because "typeAttributes" is null
java.lang.NullPointerException: Cannot invoke "org.apache.kudu.ColumnTypeAttributes.getPrecision()" because "typeAttributes" is null
at org.apache.kudu.Type.getDataType(Type.java:97)
at org.apache.kudu.ColumnSchema$ColumnSchemaBuilder.build(ColumnSchema.java:492)
at …
```

Fix NullPointerException when adding decimal columns in Kudu

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/CoercionUtils.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcTypeTranslator.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnUnpartitionedTable.java

Allow coercion on complex/structural data types i.e list/map/struct for un-partitioned ORC tables.
Depends on https://github.com/trinodb/trino/pull/22325
```markdown
* Allow coercion on complex/structural data types i.e list/map/struct for un-partitioned ORC tables.
```

Allow coercion on complex types for unpartitioned ORC tables

---

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/projection/ProjectFunctionRewriter.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/projection/ProjectFunctionRule.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/JdbcClientStats.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
plugin/trino-postgresql/pom.xml
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/rule/RewriteStringReverseFunction.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java

This framework would allow us to pushdown specific functions closer to the JDBC datasource. We use this function to pushdown `reverse` function in case of PostgreSQL connector. In order to push down a specific function to the underlying JDBC datasource, we need two parts
- Client should implement `convertProjection`
- Write a `ProjectFunctionRule` specific to the function to be pushed down. 
We also support partial pushdown of expression i.e `LOWER(REVERSE(varchar_col))` will be translated into `LOWER(synthetic_col_from_query)` 
Spl thanks to @SemionPar for inspiring me to use `reverse` function for this framework. 
Without this change when we try to run a query like this 
```
explain select reverse(name) from nation
```
Current master
```
Query Plan …
```

Introduce projection pushdown framework for JDBC connectors

---

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemFactory.java

By default, OkHttp only allows 5 concurrent HTTP connections per host, and 64 total concurrent connections. Increase these values to avoid a performance degradation compared to the legacy FS, when executing queries with a large number of splits, on nodes with large number of split runner threads.
Fixes #22548 
```markdown
* Fix a performance regression in native FS for Azure, compared to legacy FS. ({issue}`issuenumber`)
```

Increase the max number of http connections in Azure native FS

---

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureInput.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureInputFile.java

Read block size should be needed only for sequential reads.
For positioned range reads from ORC/Parquet, we should use same read size as the buffer.
```markdown
```

Set Azure read block size to ranged read size

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

We need column nulls/min/max only for columns with predicate in IcebergSplitSource
Potentially reduces memory used by iceberg metadata objects during splits generation
```markdown
```

Use Scan#includeColumnStats to restrict metadata in IcebergSplitSource

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ViewMaterializationCache.java

`createDestinationTable` looks a little misleading because it doesn't create tables actually

Rename `createDestinationTable` to `buildDestinationTable`

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/SyncPartitionMetadataProcedure.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHive3OnDataLake.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestSyncPartitionMetadata.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHdfsSyncPartitionMetadata.java

The canonical partition name built from the column name and values of the partition may differ from the actual storage location of the partition. This can lead to inconsistencies when syncing partition metadata, like identifying a partition to add/remove when there is actually nothing to be done.
Rely on the partition name from the storage location for identifying the partitions to sync via the `sync_partition_metadata` procedure call.
This fix applies specifically where  there is a partition name case sensitive variation between the canonical name and the storage location of the partition.
See `io.trino.plugin.hive.TestHive3OnDataLake#testSyncPartitionCaseSensitivePathVariation` for details.
Follow-up from #21168 …

Use the actual partition name from the storage in syncing partition metadata

---

docs/src/main/sphinx/connector/hive.md
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceProvider.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/CoercionUtils.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/VarbinaryToVarcharCoercers.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcTypeTranslator.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveCoercionPolicy.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestBooleanCoercer.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestCharToVarcharCoercer.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestDateCoercer.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestDecimalCoercers.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestDoubleToVarcharCoercions.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestFloatToVarcharCoercions.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestIntegerNumberToDoubleCoercer.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestIntegerNumberToVarcharCoercer.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestTimestampCoercer.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestVarbinaryToVarcharCoercer.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestVarcharToCharCoercer.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestVarcharToDoubleCoercer.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestVarcharToFloatCoercer.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestVarcharToIntegralNumericCoercer.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnPartitionedTable.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnUnpartitionedTable.java

```markdown
* Allow varbinary to varchar coercion for hive tables
```

Allow varbinary to varchar coercion for hive tables

---

pom.xml

It conflicts with the JUL backend:
SLF4J(W): Class path contains multiple SLF4J providers.
SLF4J(W): Found provider [org.slf4j.jul.JULServiceProvider@69ec706d]
SLF4J(W): Found provider [ch.qos.logback.classic.spi.LogbackServiceProvider@a9f57d0]
SLF4J(W): See https://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J(I): Actual provider is of type [org.slf4j.jul.JULServiceProvider@69ec706d]

Exclude logback backend from benchto

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/TrinoNessieCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestIcebergNessieCatalogConnectorSmokeTest.java

The same table might still be live in other branches or tags. Therefore, dropping the table should not clean up the files as it is not reference-aware. Use the Nessie GC tool to clean up expired files. This behaviour is consistent with the Spark Nessie integration.
Spark integration:
https://github.com/apache/iceberg/blob/main/nessie/src/main/java/org/apache/iceberg/nessie/NessieIcebergClient.java#L557-L562
Docs: https://iceberg.apache.org/docs/1.5.1/nessie/#further-use-cases
```markdown
```

Drop table should not clean the folder for Nessie catalog

---

core/trino-main/src/main/java/io/trino/dispatcher/CoordinatorLocation.java
core/trino-main/src/main/java/io/trino/dispatcher/LocalCoordinatorLocation.java
core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
core/trino-main/src/main/java/io/trino/server/ExternalUriInfo.java
core/trino-main/src/main/java/io/trino/server/protocol/ExecutingStatementResource.java
core/trino-main/src/main/java/io/trino/server/protocol/Query.java
core/trino-main/src/main/java/io/trino/server/protocol/QueryInfoUrlFactory.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2CallbackResource.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Service.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2TokenExchangeResource.java
core/trino-main/src/main/java/io/trino/server/ui/DisabledWebUiAuthenticationFilter.java
core/trino-main/src/main/java/io/trino/server/ui/FormWebUiAuthenticationFilter.java
core/trino-main/src/main/java/io/trino/server/ui/LoginResource.java
core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiAuthenticationFilter.java
core/trino-main/src/main/java/io/trino/server/ui/WebUiStaticResource.java

This change allows the server to support routing with a path prefix,
enabling better compatibility with reverse proxies and load balancers
that use the "X-Forwarded-Prefix" header.
This feature is only enabled when `http-server.process-forwarded` is
true
NOTE: this does not add support to any of the client implementations, and may not work with any existing clients.
```markdown
* Add suppot for processing `X-Forwarded-Prefix` header when `http-server.process-forwarded` is enabled. ({issue}`issuenumber`)
```

Add support for path prefix routing using "X-Forwarded-Prefix" header

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionFields.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestPartitionFields.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java

Iceberg connector caused query failure when the hidden partition column name conflicts with other columns.
The approach is different from Spark. They throw an exception when conflicts happen:
```sql
CREATE TABLE test (ts timestamp, ts_day int) USING iceberg PARTITIONED BY (day(ts));
Failed in [create table test (ts timestamp, ts_day int) using iceberg partitioned by (day(ts))]
java.lang.IllegalArgumentException: Cannot create partition from name that exists in schema: ts_day
```
Fixes #22351
```markdown
* Fix failure when hidden partition name conflicted. ({issue}`22351`)
```

Fix failure when hidden partition column name conflicted in Iceberg

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestMetadataQueryOptimization.java

Use NullableValue.asNull for null values. 
Issue can be reproduced when query count distinct on partition with NULL value and optimize_metadata_queries session enabled.
```
Query 20240507_185319_10808_yp4pm failed: value is null
java.lang.NullPointerException: value is null
at java.base/java.util.Objects.requireNonNull(Objects.java:259)
at io.trino.spi.predicate.NullableValue.of(NullableValue.java:68)
at io.trino.plugin.iceberg.IcebergMetadata.lambda$getTableProperties$8(IcebergMetadata.java:671)
at com.google.common.collect.CollectCollectors.lambda$toImmutableMap$7(CollectCollectors.java:196)
```
```markdown
* Fix failure when reading tables with `null` on partition columns and 
`optimize_metadata_queries` session …
```

Fix reading NDV using Iceberg metadata on table with NULL partitions

---

plugin/trino-kafka/pom.xml

This allows to run plugin manually:
./mvnw protoc-jar:3.11.4:run  -pl :trino-kafka
```markdown
```

Extract protoc maven config to pluginManagement

---

plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java

TestCassandraConnectorTest.testNativeQueryCaseSensitivity causes TestCassandraConnectorTest.testSelectInformationSchemaColumns to fail
Apply similar changes to `TestCassandraConnectorTest.testNativeQueryCaseSensitivity` as done for other tests through https://github.com/trinodb/trino/pull/22080
Fixes https://github.com/trinodb/trino/issues/21247

Isolate selected test from TestCassandraConnectorTest

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/ImmutableLdapObjectDefinitions.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/cli/TestTrinoLdapCli.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/jdbc/BaseLdapJdbcTest.java

As a part of [this effort](https://github.com/trinodb/docker-images/pull/202) we are trying to move from CentOS to AlmaLinux and the OpenLDAP server is also updated - This PR cleans up the LDAP specific code (for testing) so as to be compatible with the OpenLDAP 2.6

Cleanup in LDAP Product Tests

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergTrinoRestCatalogConnectorSmokeTest.java

```markdown
* Fix failure when listing views with unsupported dialect in REST catalog. ({issue}`22598`)
```

Suppress failure when listing unsupported dialect views in Iceberg REST

---

plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java

```markdown
* Add support for renaming columns. ({issue}`22607`)
```

Add support for renaming columns in Memory connector

---

plugin/trino-password-authenticators/src/test/java/io/trino/plugin/password/ldap/TestingOpenLdapServer.java
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/StandardMultinode.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/AbstractEnvSinglenodeLdap.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeTls.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeLdapReferrals.java

This update allows to run the PTs and other tests on a Alma linux based instead of deprecated CentOS. 
Fixes https://github.com/trinodb/trino/issues/18824

Update docker-images version to 98

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryQueryRelationHandle.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTableHandle.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ViewMaterializationCache.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ptf/Query.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java

This PR now uses the storage api to execute native bigquery query.
~This PR adds an optional parameter `mode` for BigQuery query table function, which indicates which api should be used to run the native bigquery query.~
~By default when mode is not provided It will use `REST_API` to run the native bigquery query.~
~Parameter `mode` can be set as~
~1. `REST_API` (More Details: https://cloud.google.com/bigquery/docs/reference/rest)~
~2. `STORAGE_API` (More Details: https://cloud.google.com/bigquery/docs/reference/storage).~
While implementing this feature, we see that when native query result set is small then the `REST_API` performs better than `STORAGE_API`. But when native query result set is large then the `STORAGE_API` performs better than `REST_API`.
~
Here are some numbers:
``` …
```

Add storage api support for reading table for query function in bigquery

---

docs/src/main/sphinx/connector/prometheus.md
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusClient.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusConnectorConfig.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusConnectorConfig.java

Prometheus endpoint may require additional http headers. Adding the configuration properties for the same
Example of additional header "X-Scope-orgID" , "default"
Fixes https://github.com/trinodb/trino/issues/21394

Allowing users to provide additional http headers for Prometheus Client.

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java

In fault tolerant execution it was not enforced that source stages were marked as finished immediatelly after parent stages completes successfully. As a result the query which essentially compelted successfully could have been marked as failed if one of source stages failed.
```markdown
* Fix issue when queries could sometimes fail when run with `retry_policy` set to `TASK`. ({issue}`issuenumber`)
```

Mark source stages as finished when parent finishes

---

docs/src/main/sphinx/connector/hive.md
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java

- fix minor bug on `query-partition-filter-required-schemas` option to be compatible with `query-partition-filter-required`
- add minor test case for this fix
- add missing description about that config on Hive connector docs, copied from v362 release note. (REF: https://trino.io/docs/current/release/release-362.html )
- related PR: https://github.com/trinodb/trino/pull/9106 by @Praveen2112 
- I need to declare `query-partition-filter-required-schemas` on catalog configuration, and switch on/off `query-partition-filter-required` option, depending on source/session by using session property manager
- But, I found that `query-partition-filter-required-schemas` option is always applied even though `query-partition-filter-required=false`.
- It is just a minor matter of boolean equation …

Fix bug on `query_partition_filter_required_schemas` config property in Hive connector

---

.github/workflows/ci.yml

The JDK 22 job started failing recently in the post-setup step with a `System.IO.IOException: No space left on device` error.
Fixes #22615

Always cleanup node in Maven check jobs

---

docs/src/main/sphinx/security/opa-access-control.md

- Add info for row-level security
- Add info about column masking
This PR replaces the approved yet inactive PR https://github.com/trinodb/trino/pull/22424 and just applies some of the cosmetic suggestions.

Expand OPA docs

---

core/trino-main/src/main/java/io/trino/metadata/SystemFunctionBundle.java
core/trino-main/src/main/java/io/trino/operator/scalar/ArrayVectorFunctions.java
core/trino-main/src/test/java/io/trino/operator/scalar/BenchmarkArrayDotProduct.java
core/trino-main/src/test/java/io/trino/operator/scalar/TestArrayVectorFunctions.java
docs/src/main/sphinx/functions/array.md

Adds 3 functions calculating distance:
* euclidean_distance
* dot_product
* cosine_distance
```markdown
* Add support for `euclidean_distance`, `dot_product` and `cosine_distance` functions. ({issue}`22397`)
```

Add support for `euclidean_distance`, `dot_product`, `cosine_distance` functions

---

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureLocation.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureLocation.java

The base location scheme was incorrectly set to abfs always, irrespective of the objects' location scheme
```markdown
```

Use the correct scheme for azure native-fs location

---

docs/src/main/sphinx/connector/memory.md

- Add view mgt
Update for https://github.com/trinodb/trino/issues/22208 after testing view mgt with 451 locally.
Sort of related questions for @martint and others - when testing I noticed that there is no `SHOW VIEWS` command and instead the `SHOW TABLES` command lists the view. Is that a bug or a feature - if a feature .. we should probably update the docs for show tables and other sections.
Also @ebyhr .. if desired I can update other parts here for any ongoing PRs or any other issues.

Update SQL support docs for memory connector

---

docs/src/main/sphinx/security/opa-access-control.md

Just remove a warning in the docs build process. Fyi @vagaerg .. turns out that rego is not recognized and throws a warning on clean builds - so switching to no syntax highlighting.

Remove invalid syntax hint in docs

---

docs/src/main/sphinx/admin/properties-logging.md

See title, not sure we need to call out that it does not work for stdout.
And also .. maybe we should change how it works @electrum ?
https://trinodb.slack.com/archives/C059KUNPTSP/p1719430408571069

Clarify log annotation docs

---

core/trino-main/src/main/java/io/trino/server/security/oauth2/OidcDiscovery.java
core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOidcDiscovery.java
core/trino-main/src/test/resources/oidc/openid-configuration-without-end-session-url.json

Make OIDC `end_session_endpoint` optional.
Fix https://github.com/trinodb/trino/issues/19844
Although this field is mandatory in the spec [OpenID Connect RP-Initiated Logout 1.0 ](https://openid.net/specs/openid-connect-rpinitiated-1_0.html), the spec itself is not mandatory.
Some providers do not implement it:
*  https://accounts.google.com/.well-known/openid-configuration
* https://github.com/dexidp/dex/issues/1697
https://openid.net/developers/how-connect-works/

Make OIDC end_session_endpoint optional

---

client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java

This adds tests to ensure that when explicit filters are provided the driver behaves the same with or without assumeNullCatalogMeansCurrent.
Follow up to https://github.com/trinodb/trino/pull/20866

Improve test coverage for assumeNullCatalogMeansCurrent

---

core/trino-main/src/main/java/io/trino/metadata/LanguageFunctionManager.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

With this commit any TrinoExceptions with error code of USER_ERROR type will be propagated to the caller.
E.g. if query calls a function which calls to function which was dropped user will see FUNCTION_NOT_FOUND error instead of generic FUNCTION_IMPLEMENTATION_ERROR.
```markdown
```

Propagate USER_ERROR when alayzing function call

---

core/trino-main/src/main/java/io/trino/operator/aggregation/partial/SkipAggregationBuilder.java

Since SkipAggregationBuilder creates a unique groupId for each input row of each page, it can create significant ephemeral memory allocations inside of GroupedAggregator instances. This can be especially bad since SkipAggregationBuilder is only used for intermediate aggregations which can occur with very high concurrency.
In an attempt to mitigate the GC pressure that SkipAggregationBuilder can create, this change refactors the logic to evaluate each GroupedAggregator individually and make it eligible for GC immediately after producing its output.

Evaluate SkipAggregationBuilder column wise

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-423.md
docs/src/main/sphinx/release/release-450.md
docs/src/main/sphinx/release/release-452.md

Assemble the release notes for the upcoming Trino 452 release.
* #22534 ✅ rn ✅ docs
* #22539 ✅ rn ✅ docs
* #22545 ✅ rn ✅ docs
* #22546 ✅ rn ✅ docs
* #22538 ✅ rn ✅ docs
* #22542 ✅ rn ✅ docs
* #22475 ✅ rn ✅ docs
* #22399 ✅ rn ✅ docs
* #22558 ✅ rn ✅ docs
* #22326 ✅ rn ✅ docs
* #22550 ✅ rn ✅ docs
* #22560 ✅ rn ✅ docs
* #22203 ✅ rn ✅ docs
* #22549 ✅ rn ✅ docs
* #22561 ✅ rn ✅ docs
* #22551 ✅ rn ✅ docs
* #22555 ✅ rn ✅ docs
* #22499 ✅ rn ✅ docs
* #22567 ✅ rn ✅ docs
* #22484 ✅ rn ✅ docs
* #22322 ✅ rn ✅ docs
* #22564 ✅ rn ✅ docs
* #22562 ✅ rn ✅ …

Add Trino 452 release notes

---

core/trino-main/src/main/java/io/trino/server/PluginManager.java

When a plugin fails to load, the exception is batched and only shown after all plugin loading has completed. 
Normally, it should be obvious from the classpath which plugin has failed to load. However if the folder is empty this array will also be empty. This can occur if something has gone wrong during the build. 
This is quite confusing when new to trino.
This is a small PR that modifies the stacktrace to ensure that it _always_ includes the plugin path.
Before...
```
2024-06-08T20:48:53.399Z	INFO	main	io.trino.server.PluginManager	-- Loading plugin /data/trino/plugin/an-invalid-plugin --
2024-06-08T20:48:53.961Z	INFO	main	io.trino.server.PluginManager	-- Loading plugin /data/trino/plugin/tpch --
2024-06-08T20:48:53.964Z	INFO	main	io.trino.server.PluginManager	Installing …
```

Always show plugin path when service provider is missing on plugin load

---

docs/release-template.md
docs/src/main/sphinx/release/release-452.md

Accidentally missed in 452 release

Add Exasol connector to release notes

---

docs/src/main/sphinx/connector/postgresql.md
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlVectorType.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java

Add support for [pgvector](https://github.com/pgvector/pgvector) in PostgreSQL connector.
pgvector is a famous extension (10k favorites) for vector similarity search. 
This PR maps PostgreSQL `vector` type to Trino `array(real)`
Depends on https://github.com/trinodb/trino/pull/22397
```markdown
* Add support for reading `vector` type on pgvector. ({issue}`22630`)
```

Add support for reading `vector` type in PostgreSQL

---

core/trino-main/src/main/java/io/trino/operator/join/unspilled/HashBuilderOperator.java
core/trino-main/src/test/java/io/trino/operator/join/unspilled/TestHashBuilderOperator.java
lib/trino-memory-context/src/main/java/io/trino/memory/context/ThresholdLocalMemoryContext.java

Memory management in HashBuilderOperator.addInput caused significant
thread congestion. When memory tracking accuracy is traded for calling
delegate.setBytes() less frequently, we are getting better performance
for queries which tend to process tiny pages in HashBuilder operator.
Improvement is very much visible in couple TPC-DS queries run in FTE mode.
Queries run on unpartitioned iceberg, sf1000, 8 nodes cluseter.

Reduce thread congestion in HashBuilderOperator

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java

Suppress ForbiddenException when listing tables in Iceberg REST

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/SplitAssigner.java

Previously we used toString but it transitively calls out to
ConnectorSplit.toString which may be very verbose. We observed memory
pressure problems while logging diagnostics.

Use more compact representation of AssignmentResult in diagnostics

---

core/trino-main/src/main/java/io/trino/operator/WorkProcessorOperatorAdapter.java

Avoid capturing a local reference to "this" which can retain memory in the operator info supplier longer than intended.

Use static lambda in WorkProcessorOperatorAdapter

---

docs/src/main/sphinx/sql/grant-roles.md

* Fixed a typo on the GRANT roles SQL docs page. USER user_mame -> user_name.
```markdown
```

Fix typo in GRANT roles sql docs

---

docs/src/main/sphinx/admin/fault-tolerant-execution.md

Add note stating that we do not test all S3-compatible storage systems
```markdown
```

Add compatibility note to FTE exchange manager section

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueContext.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/v1/GlueCatalogIdRequestHandler.java

```markdown
* Add support for Glue catalog id with [SQL routine management](sql-routine-management). ({issue}`22717`)
```

Add support for Glue catalog-id with catalog routines

---

core/trino-main/src/main/java/io/trino/operator/scalar/ArrayReduceFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/ArrayTransformFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/MapFilterFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/MapTransformKeysFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/MapTransformValuesFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/MapZipWithFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/ZipWithFunction.java
core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/analyzer/WindowFunctionValidator.java
core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/ScopeAware.java
core/trino-main/src/main/java/io/trino/sql/planner/TranslationMap.java
core/trino-main/src/test/java/io/trino/operator/scalar/TestJsonStringArrayExtractScalar.java
core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java
core/trino-main/src/test/java/io/trino/sql/query/TestRandom.java
core/trino-main/src/test/java/io/trino/sql/routine/TestSqlFunctions.java

Fixes https://github.com/trinodb/trino/issues/22683
```markdown
* Fix incorrect evaluation of repeated non-deterministic functions. ({issue}`22683`)
```

Fix incorrect dedup of non-deterministic functions

---

core/trino-main/src/main/java/io/trino/operator/aggregation/builder/InMemoryHashAggregationBuilder.java
core/trino-main/src/main/java/io/trino/operator/aggregation/builder/MergingHashAggregationBuilder.java

Simple refactoring that prefers using pre-sized `ImmutableList.Builder` instances

Use builderWithExpectedSize in aggregation builder

---

client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
client/trino-cli/src/main/java/io/trino/cli/QueryRunner.java
client/trino-client/src/main/java/io/trino/client/ClientSession.java
client/trino-client/src/main/java/io/trino/client/uri/TrinoUri.java
client/trino-client/src/test/java/io/trino/client/TestRetry.java
client/trino-client/src/test/java/io/trino/client/uri/TestTrinoUri.java
client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDriverUri.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverUri.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestingTrinoClient.java

80/443 are standard HTTP ports Trino use. If the port is missing in the URI - assume default ones.

Allow portless URIs in the client/jdbc/cli

---

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java
core/trino-main/src/test/java/io/trino/sql/query/TestIssue22731.java

Complex conjuncts that might fails were being reordered before simpler conjuncts.
Fixes #22731 
```markdown
* Fix potential failure for queries involving `GROUP BY`, `UNNEST`, and filters over expressions that may produce an error for certain inputs. ({issue}`22731`)
```

Fix incorrect pushdown involving aggregations and unnest

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/MetastoreUtil.java

Remove obsolete Hive stats property

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushFilterThroughBoolOrAggregation.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushFilterThroughBoolOrAggregation.java
core/trino-main/src/test/java/io/trino/sql/query/TestCorrelatedAggregation.java

PushFilterThroughBoolOrAggregation optimizer may return more output symbol than original plan. 
and cause error
```
java.lang.IllegalArgumentException: io.trino.sql.planner.iterative.rule.PushFilterThroughBoolOrAggregation$PushFilterThroughBoolOrAggregationWithoutProject: transformed expression doesn't produce same outputs: [project::[varchar], bool_or::[boolean]] vs [project::[varchar], is_mocked::[boolean], bool_or::[boolean]]
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:466)
at io.trino.sql.planner.iterative.Memo.replace(Memo.java:117)
```
Fixing this issue by using output symbols from aggregation node instead of its source.
example query to reproduce:
```
SELECT *
FROM
(SELECT project, BOOL_OR(is_mocked) AS has_mocking
FROM schema.table
GROUP BY project) AS …
```

Fix output symbols of PushFilterThroughBoolOrAggregation optimizer

---

core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
core/trino-main/src/test/java/io/trino/server/testing/TestTestingTrinoServer.java

Currently, `TestingTrinoServer` hardcodes the catalog management strategy. This PR aims to make it configurable so that it can be set to `static`.
```markdown
```

Make catalog management configurable in TestingTrinoServer

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetastoreClosure.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSinkProvider.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HivePageSinkMetadataProvider.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveTransaction.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/CreateEmptyPartitionProcedure.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/DropStatsProcedure.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/RegisterPartitionProcedure.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/UnregisterPartitionProcedure.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java

`HiveMetastoreClosure` abstraction is no longer needed.  This interface was needed to handle the old statistics system.

Remove HiveMetastoreClosure

---

testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

It seems OR condition was accidentally deleted in https://github.com/trinodb/trino/commit/964e49609024d17584e96ca77dd213a48496ff96#diff-5ceb726fc5fef567f3ffbcae192ff58b1d00700d285db6369054e05cde0c52d2

Fix BaseConnectorTest.testMultipleRangesPredicate

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/TrinoCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergTrinoRestCatalogConnectorSmokeTest.java

Iceberg REST catalog threw the following an exception when executing `DROP SCHEMA ... CASCADE` statement against schema having views. 
```
io.trino.testing.QueryFailedException: Cannot invoke "io.trino.plugin.iceberg.IcebergTableHandle.getSchemaTableName()" because "tableHandle" is null
at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:134)
at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:558)
at io.trino.testing.DistributedQueryRunner.executeWithPlan(DistributedQueryRunner.java:547)
at io.trino.testing.QueryAssertions.assertDistributedUpdate(QueryAssertions.java:108)
at io.trino.testing.QueryAssertions.assertUpdate(QueryAssertions.java:62)
at io.trino.testing.AbstractTestQueryFramework.assertUpdate(AbstractTestQuer …
```

Fix failure when dropping schemas with cascade on Iceberg REST catalog

---

core/trino-main/src/test/java/io/trino/operator/scalar/interval/TestExtract.java

This change adds the `TestExtract` test class for testing the `interval` type.
Fixes #5627

Add TestExtract for interval type

---

core/trino-main/src/main/java/io/trino/sql/planner/SortExpressionExtractor.java
core/trino-main/src/test/java/io/trino/sql/planner/TestSortExpressionExtractor.java

reviving this [old PR](https://github.com/trinodb/trino/pull/14598)
visitBetweenPredicate  in SortExpressionVisitor can only handle one side of BETWEEN (GREATER_THAN_OR_EQUAL or LESS_THAN_OR_EQUAL), this pr optimize it and let it handle both sides of BETWEEN as conjunct expressions
Fixes one par of this issue: https://github.com/trinodb/trino/issues/22520
```markdown
```

Optimize BETWEEN predicate to include both the sides.

---

docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcCatalogConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcCatalogModule.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcClient.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalogFactory.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java

Add view support for iceberg JDBC catalog.
Iceberg now supports views. The iceberg REST catalog already supports views. This just brings things to parity.
```markdown
* Add support for views in JDBC catalog. ({issue}`22576`)
* Upgrade `jdbc.schema-version` to `V1` in JDBC catalog. ({issue}`22576`)
```

Add view support for iceberg jdbc catalog

---

core/trino-main/src/main/java/io/trino/operator/scalar/ArrayVectorFunctions.java
core/trino-main/src/test/java/io/trino/operator/scalar/TestArrayVectorFunctions.java

The cosine similarity between `ARRAY[4, 5, 6]` and `ARRAY[4, 5, 6]` becomes 0.9999999999999998 and `cosine_distance` function returned `2.220446049250313E-16`. 
```markdown
* Improve accuracy of `cosine_distance` function. ({issue}`22761`)
```

Improve accuracy of cosine distance calculation

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java

Instead of querying big query for all tables, query INFORMATION_SCHEMA only for ones matching name with trino table
Instead of querying big query for all tables, query
INFORMATION_SCHEMA only for ones matching name with
trino table
Closes https://github.com/trinodb/trino/issues/22770
```markdown
* Improve performance when getting table definitions
```

Optimize big query toRemoteTable

---

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/metrics/TDigestHistogram.java

`com.fasterxml.jackson.core:jackson-databind` dependency
`and com.fasterxml.jackson.databind.annotation` package
are not part of the SPI so they cannot work properly across
different classloaders.
Instead of using Json(De)Serialize annotations, use JsonCreator and JsonProperty
to serialize TDigest in a desired shape.

Fix TDigestHistogram serialization across classloaders 

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java

- add `query-partition-filter-required-schemas` config to iceberg connector, same as hive connector
- I need to define `query-partition-filter-required-schemas=our_raw_data_schema` to prevent unintended heavy queries from being submitted to those Bronze tier tables on Iceberg catalogs, same as Hive catalogs.
- related PR:
- https://github.com/trinodb/trino/pull/17263 by @rice668 
- https://github.com/trinodb/trino/pull/9106 by @Praveen2112  
- https://github.com/trinodb/trino/pull/22522
```markdown
* Add support for setting partition required schemas via `query-partition-filter-required-schemas` config property
```

Add `query-partition-filter-required-schemas` config property to Iceberg connector

---

docs/src/main/sphinx/connector/bigquery.md
docs/src/main/sphinx/connector/cassandra.md
docs/src/main/sphinx/connector/clickhouse.md
docs/src/main/sphinx/connector/delta-lake.md
docs/src/main/sphinx/connector/druid.md
docs/src/main/sphinx/connector/elasticsearch.md
docs/src/main/sphinx/connector/exasol.md
docs/src/main/sphinx/connector/googlesheets.md
docs/src/main/sphinx/connector/hive.md
docs/src/main/sphinx/connector/iceberg.md
docs/src/main/sphinx/connector/mariadb.md
docs/src/main/sphinx/connector/mongodb.md
docs/src/main/sphinx/connector/mysql.md
docs/src/main/sphinx/connector/opensearch.md
docs/src/main/sphinx/connector/oracle.md
docs/src/main/sphinx/connector/postgresql.md
docs/src/main/sphinx/connector/redshift.md
docs/src/main/sphinx/connector/snowflake.md
docs/src/main/sphinx/connector/sqlserver.md

* Move FTE support into Configuration
* Make Table functions subsection of SQL support
Follow up to #22730 

Improve connector docs around Config and SQL support

---

pom.xml

* https://github.com/trinodb/docker-images/pull/204
* https://github.com/trinodb/docker-images/pull/203

Update docker images to 99

---

core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4
core/trino-main/src/main/java/io/trino/execution/DropRoleTask.java
core/trino-main/src/test/java/io/trino/execution/TestRoleTasks.java
core/trino-main/src/test/java/io/trino/execution/TestSetRoleTask.java
core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
core/trino-parser/src/main/java/io/trino/sql/tree/DropRole.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
docs/src/main/sphinx/sql/drop-role.md

Add optional `IF EXISTS` to `DROP ROLE`, which suppresses the role-not-found error that you'd otherwise get.
Although this option isn't in the ANSI SQL, it's a UX improvement that Trino has traditionally admitted.
```markdown
* Extend `DROP ROLE` to allow `IF EXISTS`.
```

Add IF EXISTS to DROP ROLE

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java

`TestIcebergMinioOrcConnectorTest.testOptimizeTimePartitionedTable` is failing intermittently, where there's a congestion on HTTP connections in the S3 client. Slightly increasing the number of available connections should fix it.
Switching to a single thread doesn't make the tests slower.
Fixes #21736

Fix flaky TestIcebergMinioOrcConnectorTest

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoders.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestingColumnReader.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

Hive tables migrated to iceberg through Spark require the ability to read INT96 timestamps as LongTimestampWithTimeZoneType
Fixes https://github.com/trinodb/trino/issues/11338
```markdown
* Fix failure to read hive tables migrated to iceberg through Apache Spark. ({issue}`11338`)
```

Support reading INT96 timestamps as LongTimestampWithTimeZoneType

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PreAggregateCaseAggregations.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPreAggregateCaseAggregations.java
testing/trino-tests/src/test/java/io/trino/tests/TestAggregations.java

If the number of pre-aggregations is equal to number of case aggregations, then there is no performance gain in rule execution. Additionally, firing rule in such case could lead to infinite rule execution loop, since new pre-aggregations could be eligable for further optimization.
Alternative approach to: https://github.com/trinodb/trino/pull/22666
```markdown
* Fix optimizer timeout for certain queries involving aggregations and `CASE` expressions. ({issue}`22813`)
```

Skip PreAggregateCaseAggregations it aggregations are not reduced

---

docs/src/main/sphinx/object-storage/metastores.md

Requested by @electrum in https://trinodb.slack.com/archives/CGB0QHWSW/p1716587057716529
and expanded to remove all defunct properties from GlueHiveMetastoreConfig
v1 class still supports some but that is not documented and probably not desired to be documented at this stage either.

Remove defunct properties from docs

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java

When listing past table versions, correctly break iteration once we get to a file which no longer exists, e.g. removed by an external system.
Motivation: vacuum procedure call would otherwise fail with `NullPointerException` when setting the retention to a value which overlaps with externally deleted log file.
```markdown
```

Fix past table versions listing in vacuum procedure

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-453.md

Assemble the release notes for the upcoming Trino 453 release.
* #22653 ✅ rn ✅ docs
* #22655 ✅ rn ✅ docs
* #22332 ✅ rn ✅ docs
* #22671 ✅ rn ✅ docs
* #22673 ✅ rn ✅ docs
* #22630 ✅ rn ✅ docs
* #22556 ✅ rn ✅ docs
* #22668 ✅ rn ✅ docs
* #22680 ✅ rn ✅ docs
* #22681 ✅ rn ✅ docs
* #22682 ✅ rn ✅ docs
* #22344 ✅ rn ✅ docs
* #22689 ✅ rn ✅ docs
* #22696 ✅ rn ✅ docs
* #22690 ✅ rn ✅ docs
* #22687 ✅ rn ✅ docs
* #22685 ✅ rn ✅ docs
* #22705 ✅ rn ✅ docs
* #22714 ✅ rn ✅ docs
* #22711 ✅ rn ✅ docs
* #22688 ✅ rn ✅ docs
* #22717 ✅ rn ✅ docs
* #22425 ✅ rn ✅ …

Add Trino 453 release notes

---

testing/trino-product-tests-groups/src/main/java/io/trino/tests/product/SuiteGroups.java
testing/trino-product-tests-groups/src/main/java/io/trino/tests/product/TestGroups.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentContainers.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentModule.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/TaskRetriesMultinode.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeMinioDataLakeTaskRetriesFilesystem.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite7NonGeneric.java
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/task-retries-multinode/multinode-master-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/task-retries-multinode/multinode-worker-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-minio-data-lake-task-retries-filesystem/exchange-manager.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-minio-data-lake-task-retries-filesystem/iceberg.properties
testing/trino-product-tests/src/main/java/io/trino/tests/product/faulttolerant/TestTaskRetriesFilesystemSmoke.java

Add task retries smoke product test 

---

core/trino-main/src/main/java/io/trino/metadata/Metadata.java
core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java
core/trino-main/src/main/java/io/trino/sql/planner/PlanCopier.java
core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DistinctAggregationStrategyChooser.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/MultipleDistinctAggregationToMarkDistinct.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/MultipleDistinctAggregationsToSubqueries.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/OptimizeMixedDistinctAggregations.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/SingleDistinctAggregationToGroupBy.java
core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
core/trino-main/src/main/java/io/trino/tracing/TracingMetadata.java
core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDistinctAggregationStrategyChooser.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestMultipleDistinctAggregationToMarkDistinct.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestMultipleDistinctAggregationsToSubqueries.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
docs/src/main/sphinx/admin/properties-optimizer.md
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestAggregations.java
testing/trino-tests/src/test/java/io/trino/tests/TestDistinctToSubqueriesAggregations.java

Introduce new rule that splits distinct aggregations on different arguments to sub-queries and joins the grouped
results using grouping keys if any.
This allows `SingleDistinctAggregationToGroupBy` to kick in and improve parallelism and performance significantly when the grouped query is cheap to duplicate.
Benchmarks
Some queries (simple aggregation on top of table scan, with low cardinality group by) can be significantly improved like 5s vs 40s using MarkDistinct
```markdown
* Improve performance of queries with multiple distinct aggregations. ({issue}`22355`)
```

Split multiple distinct aggregations to sub queries

---

plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeSource.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeStorage.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/MetricsBuilder.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/azure/AzureBlobFileSystemExchangeStorage.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/local/LocalFileSystemExchangeStorage.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorage.java
plugin/trino-exchange-hdfs/src/main/java/io/trino/plugin/exchange/hdfs/HadoopFileSystemExchangeStorage.java

Reitroduce https://github.com/trinodb/trino/pull/22775.
Now safe after https://github.com/trinodb/trino/pull/22797

Expose FileSystemExchangeSource metrics

---

core/trino-main/src/main/java/io/trino/execution/DropCatalogTask.java
core/trino-main/src/test/java/io/trino/execution/TestDropCatalogTask.java

The example failure:
```sql
trino> CREATE CATALOG "t" USING tpch;
CREATE CATALOG
trino> DROP CATALOG "t";
Query 20240726_123547_00686_j342b failed: Catalog '"t"' not found
io.trino.spi.TrinoException: Catalog '"t"' not found
at io.trino.connector.CoordinatorDynamicCatalogManager.dropCatalog(CoordinatorDynamicCatalogManager.java:328)
at io.trino.execution.DropCatalogTask.execute(DropCatalogTask.java:63)
at io.trino.execution.DropCatalogTask.execute(DropCatalogTask.java:32)
at io.trino.execution.DataDefinitionExecution.start(DataDefinitionExecution.java:146)
at io.trino.execution.SqlQueryManager.createQuery(SqlQueryManager.java:272)
at io.trino.dispatcher.LocalDispatchQuery.startExecution(LocalDispatchQuery.java:145)
at io.trino.dispatcher.LocalDispatchQuery.lambda$waitForMinimumWorkers$2(Lo …
```

Normalize name when dropping catalogs

---

docs/src/main/sphinx/client/cli.md
docs/src/main/sphinx/client/jdbc.md

Add docs for client port optionality

---

docs/src/main/sphinx/conf.py

- Found out that users did not realize the meaning
- Also found out that users did not realize its a link to more explanation
- New approach is the same as in Trino Gateway 10 and onwards

Improve visibilty for Breaking change warning

---

docs/src/main/sphinx/release/release-449.md

The expected type is `timestamp` type:
https://github.com/trinodb/trino/pull/21721/files#diff-79f367e47040dda32ac81ecec46b27cfd7cc822858bc8c31fe435a15a47446dcR670

Fix wrong Delta Lake change in 449 release note

---

docs/src/main/sphinx/admin/spill.md

This keeps coming up... might as well make it official. 
https://trinodb.slack.com/archives/CLEDR9V7G/p1722011311628259

Add legacy note for spill to disk

---

core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
core/trino-main/src/test/java/io/trino/sql/planner/TestConnectorExpressionTranslator.java

These functions need to be resolved via getCoercion().
Fixes https://github.com/trinodb/trino/issues/22840
```markdown
* Fix failure for queries involving {func}`json_parse` and a cast to `array`, `map`, or `row`. ({issue}`22840`)
```

Fix translation of special cast+json_parse functions

---

core/trino-main/src/main/resources/webapp/src/utils.js

Currently on loading coordinator UI initially it shows NaN for some values because those values are still undefined yet this change will check for NaN and would return empty string in it's place making it more understandable that no value is available for those statistics yet.
Cherry pick from https://github.com/prestodb/presto/pull/23285
Currently it shows 
After this change it would look like 
```markdown
```

Replacing NaN on coordinator to value n/a

---

core/trino-main/src/main/java/io/trino/execution/QueryStateMachine.java
core/trino-main/src/main/java/io/trino/server/QueryResource.java
core/trino-main/src/main/resources/webapp/references.html
core/trino-main/src/main/resources/webapp/src/components/QueryHeader.jsx
core/trino-main/src/main/resources/webapp/src/components/ReferenceDetail.jsx
core/trino-main/src/main/resources/webapp/src/references.jsx
core/trino-main/src/main/resources/webapp/src/webpack.config.js
core/trino-main/src/test/java/io/trino/server/TestQueryResource.java

This PR extends the Info endpoint on QueryResource - with the boolean parameter `pruned` which returns a lightweight version of QueryInfo, by pruning the StageInfo object graph.
The QueryInfo object returned by the QueryInfo endpoint can be very big and take a lot of memory, as it contains the entire plan, all the tasks, and all the buffers involved in the tasks, even though this data may not always be relevant.
On the `QueryStateMachine` class there is already a method available to prune the `QueryInfo` object, which this new endpoint leverages.
An external system which is in charge of submitting queries to Trino can rely on this endpoint to understand which tables and routines have been used by each query, with a response that is manageable in terms of memory. This data powers …

Implement Query Info Pruned Endpoint

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSource.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceProvider.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSource.java

A bug related to [BucketValidator](https://github.com/trinodb/trino/blob/b63e75eb9e06a0018dc0c720e6696479cc5869e5/plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSource.java#L365) was causing select queries on certain column combination on Hive V1 bucketed table failed with HIVE_CURSOR_ERROR while it succeeded in the other column combination. 
**DDL of bucketed table**
```
CREATE EXTERNAL TABLE `example_table`(
`input_key` varchar(1), 
`metrics` struct<gauges:array<struct<name:string,value:bigint>>>)
PARTITIONED BY ( 
`run_id` varchar(1))
CLUSTERED BY ( 
input_key) 
INTO 8 BUCKETS
ROW FORMAT SERDE 
'org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe' 
STORED AS INPUTFORMAT 
'org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat' 
OUTPUTFORMAT …
```

Fix BucketValidator to validate on data page

---

docs/src/main/sphinx/security/opa-access-control.md

Follow up for https://github.com/trinodb/trino/pull/21997.

Add documentation for OPA batch column masking

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java

getAll is used by CachingHiveMetastore#getPartitionsByNames, which is expected to return the same number of entries as input partitionNames (see HiveSplitManager#getPartitionMetadata).

Fail when there are toLoad duplicates in getAll

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/ReentrantBoundedExecutor.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/InMemoryGlueCache.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestCachedHiveGlueMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestInMemoryGlueCache.java

This allows to use `hive.metastore-refresh-interval` property when using `hive.metastore=glue` with internal caching.
```markdown
* Added support for `hive.metastore-refresh-interval` when using Glue v2 Hive metastore
```

Add support for cache refresh interval to Glue v2 Hive metastore

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java

Returning duplicate partition names could be a correctness error on metastore side, because duplicate names could reference different logical partitions.

Fail if metastore returns duplicate partition names

---

docs/src/main/sphinx/object-storage/metastores.md

Correct header for Databricks Unity HMS

---

docs/src/main/sphinx/object-storage/legacy-s3.md

Adds the info about the default value for property hive.s3.streaming.enable  in the documentation
https://github.com/trinodb/trino/blob/2119eddcc89591795d5082589bc65f9d30a54a17/lib/trino-hdfs/src/main/java/io/trino/hdfs/s3/HiveS3Config.java#L74

Adds default value info for property hive.s3.streaming.enable in doc

---

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureOutputFile.java

Before this change, if an exception happens after opening the stream in `createOrOverwrite`, the stream will be properly closed, leaving behind an empty or partially written file.
I only tested the old behavior manually, I'm not sure how to invoke an exception when calling `blobClient.upload()`.

Make `createOrOverwrite` atomic for Azure FS

---

docs/src/main/sphinx/routines.md
docs/src/main/sphinx/routines/introduction.md

I hope to work against the assumption of some readers that routines can invoke other SQL statements and are more than simple functions with this addition. The Limitation section already details that but maybe this can help some more. 
There are also suggestions to say that a function operates from data from one row, but I think that is actually wrong. For example you could write a JOIN that combines multiple rows and then uses values from the different rows as input value for a function.
I was thinking about using "scalar function" .. but I am not 100% sure.. since I think it could return a JSON construct. Also .. not sure if readers necessary understand without defining it more.

Improve SQL routine description

---

docs/src/main/sphinx/connector/phoenix.md

Add missing udpate doc ref for phoenix connector

---

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureOutputFile.java

Throw `FileNotFoundException` instead of a `BlobStorageException`, since the latter doesn't extend `IOException`. This addresses a test failure missed in 1073b0836bf1fb560a3a4a664f67171f5047d086.
Follow-up to #22858 

Throw a better exception in Azure FS createOrOverwrite

---

core/trino-main/src/main/java/io/trino/server/Server.java

Instantiating event listeners on workers doesn't make sense even if event listener config is present. This makes deployment easier and less error prone.

Load event listeners on coordinator only

---

.mvn/modernizer/violations.xml
pom.xml

Enable https://errorprone.info/bugpattern/StringCaseLocaleUsage
I prefer compilation failure (earlier phase) to modernizer report. 

Enable errorprone StringCaseLocaleUsage

---

core/trino-main/src/main/java/io/trino/operator/DirectExchangeClientFactory.java
core/trino-main/src/main/java/io/trino/server/security/ServerSecurityModule.java
core/trino-main/src/test/java/io/trino/operator/TestMergeOperator.java
pom.xml
testing/trino-testing/pom.xml

Update airlift to 254

---

client/trino-client/src/main/java/io/trino/client/uri/TrinoUri.java
client/trino-client/src/test/java/io/trino/client/uri/TestTrinoUri.java
client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java

Fixes https://github.com/trinodb/trino/issues/22901

Fix username defaulting to user.name property

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergStatistics.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsReader.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergFileOperations.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

Restrict fetching of iceberg statistics to only the columns projected from a scan.
Relies on https://github.com/trinodb/trino/pull/22739 to cache multiple accesses to filesystem due to different columns being projected from same table through multiple scans

Use projected columns in iceberg getTableStatistics

---

core/trino-main/src/main/java/io/trino/execution/DistributionSnapshot.java
core/trino-main/src/main/java/io/trino/execution/QueryStats.java
core/trino-main/src/main/java/io/trino/execution/StageStats.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/metrics/Distribution.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/metrics/TDigestHistogram.java

Histogram digests can be of considerable size incresing
serialized strucutre size. QueryStats and StageStats are not mergable,
therefore digests can be trimmed from them.

Prune digests from OperatorInfo

---

lib/trino-filesystem-s3/pom.xml
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3Input.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3InputStream.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3Retries.java

Read the response inside a transformer lambda and throw a retryable
exception on IO errors to use the already configured SDK retry mechanism.

Retry on interrupted connections when reading from S3 in native FS library

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ValueDecoders.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/ParquetUtil.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestTimestamp.java

Parquet files having INT96 timestamps support `hive.parquet.time-zone` property for Hive connector. However, for UTC adjusted INT64 timestamps, setting `hive.parquet.time-zone` doesn't have any effect. This PR adds support for parquet reader to adjust INT64 timestamps to timezone defined by `hive.parquet.time-zone` when parquet logical annotation `isAdjustedToUTC` is set to true.
```markdown
* Use `hive.parquet.time-zone` when reading UTC adjusted INT64 timestamps in parquet files. ({issue}`22577`)
```

Use hive.parquet.time-zone when reading INT64 timestamps in hive

---

plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestingPolarisCatalog.java
pom.xml

```markdown
* Add support for [Polaris catalog](https://polaris.io/). ({issue}`issuenumber`)
```

Add support for Polaris catalog in Iceberg

---

docs/src/main/sphinx/admin.md
docs/src/main/sphinx/admin/preview-web-interface.md
docs/src/main/sphinx/admin/properties-web-interface.md

Provide minimal guidance about the new user interface to enable users to test and provide feedback and potentially help out. I am not sure about the timing for when to merge this. At a minimum we have to wait for the linked PR to be merged. Then I think we can merge this even though there will be nearly nothing to see.
#22869

Add docs for Preview Web UI

---

lib/trino-hive-formats/src/main/java/io/trino/hive/formats/HiveFormatUtils.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/HiveFormatsErrorCode.java
lib/trino-hive-formats/src/test/java/io/trino/hive/formats/TestHiveFormatUtils.java

HiveFormatUtils sometimes throw exceptions upon encountering schema errors.  These are not TrinoExceptions, so they get automatically converted to GENERIC_INTERNAL_ERROR code by QueryStateMachine.  This is not correct, as the error is external, coming from the Hive table schema.
Fix it by throwing TrinoException in those cases, with a new error code for Hive schema problems.
The new error code was added in the Hive plugin, where the HiveErrorCode enum lives.  This is, unfortunately, not visible from `io.trino.hive.formats`, so I added a new exception type there and tried to catch it along all call-chains in the Hive plugin to convert it to the new error code.
( ) Release notes are required. Please propose a …

Treat Hive schema errors as EXTERNAL

---

core/trino-main/src/main/java/io/trino/eventlistener/EventListenerConfig.java
core/trino-main/src/main/java/io/trino/eventlistener/EventListenerManager.java
core/trino-main/src/test/java/io/trino/eventlistener/TestEventListenerConfig.java
core/trino-main/src/test/java/io/trino/eventlistener/TestEventListenerManager.java
docs/src/main/sphinx/develop/event-listener.md

queryCompleted notifications are handled by unbounded executor, hence it could cause all sort of issues when there is spike in query traffic and event listener is slow to report events.
```markdown
* Skip query completed notifications when there are too many concurrent query completed request.
Maximum number of requests can be setup with `event-listener.max-concurrent-query-completed-events`. ({issue}`issuenumber`)
```

Prevent too many concurrent query completed notifications

---

core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
core/trino-main/src/main/java/io/trino/server/GoneException.java
core/trino-main/src/main/java/io/trino/server/HttpRequestSessionContextFactory.java
core/trino-main/src/main/java/io/trino/server/QueryResource.java
core/trino-main/src/main/java/io/trino/server/QueryStateInfoResource.java
core/trino-main/src/main/java/io/trino/server/ResourceGroupStateInfoResource.java
core/trino-main/src/main/java/io/trino/server/ServerInfoResource.java
core/trino-main/src/main/java/io/trino/server/TaskResource.java
core/trino-main/src/main/java/io/trino/server/ThrowableMapper.java
core/trino-main/src/main/java/io/trino/server/protocol/ExecutingStatementResource.java
core/trino-main/src/main/java/io/trino/server/protocol/Query.java
core/trino-main/src/main/java/io/trino/server/ui/UiQueryResource.java
core/trino-main/src/main/java/io/trino/server/ui/WebUiStaticResource.java
core/trino-main/src/main/java/io/trino/server/ui/WorkerResource.java
core/trino-web-ui/src/main/java/io/trino/web/ui/WebUiResources.java
core/trino-web-ui/src/test/java/io/trino/web/ui/TestWebUiResources.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/backup/TestingHttpBackupResource.java
pom.xml

Changes requires as now, errors are rendered using jax-rs, rather than by the servlet container (Jetty).
See: https://eclipse-ee4j.github.io/jersey.github.io/apidocs/3.1.1/jersey/org/glassfish/jersey/server/ServerProperties.html#RESPONSE_SET_STATUS_OVER_SEND_ERROR

Update airlift to 258

---

core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java

It seems to be better to use `parseError()` than `new ParsingException()` in `AstBuilder`.
```markdown
```

Use parseError() to throw ParsingException in AstBuilder.visitDateTimeType()

---

client/trino-client/src/test/java/io/trino/client/uri/TestTrinoUri.java
core/trino-main/src/test/java/io/trino/execution/TestQueryInfo.java

Fix test classes importing guava collections from shaded `org.weakref.jmx.$internal` package

Fix test imports

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/CoralSemiTransactionalHiveMSCAdapter.java

Closes #22801 
Fix the spammed coral log by _not_ passing the serialization lib to coral.
We noticed a spammed log from the Coral library every time we queried a Hive view:
`com.linkedin.coral.common.HiveTable`
`Failed to get columns using deserializer: java.lang.NoClassDefFoundError: com/linkedin/coral/$internal/org/apache/hadoop/fs/FileSystem`
We realized it happens due to a missing dependency which was removed as part of a project to [decouple Trino from Hadoop and Hive](https://github.com/trinodb/trino/issues/15921).
Since we don’t want Coral to use the Hadoop FileSystem code, we decided the best way to solve this is to make the code change.
[Link](https://trinodb.slack.com/archives/CGB0QHWSW/p1718975042473409) to Slack thread
(x) This is not user-visible or is docs only, and no …

don't pass serialization lib to coral

---

core/trino-main/src/main/java/io/trino/util/JsonUtil.java

Since https://github.com/FasterXML/jackson-core/pull/1081 this optimization does no longer make sense as it's applied internally by Jackson if needed.
Alternative to https://github.com/trinodb/trino/pull/22941

Remove no longer needed optimization

---

core/trino-main/src/main/java/io/trino/util/JsonUtil.java

Reverts trinodb/trino#22942
As pointed out by @Dith3r this is still a valid optimization that we need

Revert "Remove no longer needed optimization"

---

docs/src/main/sphinx/connector/bigquery.md
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnector.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/procedure/ExecuteProcedure.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java

Add support for `execute` procedure in BigQuery connector
Fixes #22692
```markdown
* Add support for `execute` procedure. ({issue}`22692`)
```

Add support for execute procedure in BigQuery connector

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java

Relates to https://github.com/trinodb/trino/issues/21862

Disable flaky testDeleteRowsConcurrently in Iceberg JDBC catalog

---

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectionCreation.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcTableProperties.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcClient.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcModule.java
plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java

Extracted from https://github.com/trinodb/trino/pull/21923
```markdown
```

Minor cleanups in JDBC connector

---

plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleConfig.java
plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleConfig.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlConfig.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConfig.java
plugin/trino-redshift/pom.xml
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftConfig.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConfig.java

trino specific heuristic is applied if empty or zero
```markdown
* Allow customising fetch size using `oracle.fetch-size`, `redshift.fetch-size` , `postgresql.fetch-size` respectively for each connector. 
```

Add oracle, redshift, postgresql jdbc fetch size

---

plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationDynamicFilter.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoDynamicFiltering.java

The assumption for waiting for build side only works for first join due to how Driver#processInternal works.
Fixes: https://github.com/trinodb/trino/issues/21724

Simplify testJoinDynamicFilteringBlockProbeSide tests

---

plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/rule/RewriteVectorDistanceFunction.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlVectorType.java

Follow-up of https://github.com/trinodb/trino/pull/22397
`dot_product` pushdown can be handled in follow-up PR. 
```markdown
* Improve performance when using `euclidean_distance` and `cosine_distance` functions on `vector` type. ({issue}`22618`)
```

Add support for euclidean and cosine distance pushdown to pgvector

---

plugin/trino-delta-lake/src/main/java/io/delta/kernel/internal/deletionvectors/RoaringBitmapArrays.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/delete/DeletionVectors.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/delete/PositionDeleteFilter.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/delete/TestDeletionVectors.java

Use delta-kernel for RoaringBitmapArray

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

Populate split offset in Iceberg OPTIMIZE procedure

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

Fixes https://github.com/trinodb/trino/issues/22986

Set task_min_writer_count as 1 in testOptimizePopulateSplitOffsets

---

core/trino-server-rpm/README.md
core/trino-server-rpm/src/main/resources/dist/config/secrets.toml
core/trino-server-rpm/src/main/resources/dist/etc/init.d/trino
core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java

This PR integrates our RPM build to use SecretsResolver
```markdown
```

Configure SecretsResolver in RPM

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TableSnapshot.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheFileOperations.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java

Improve reading v2 delta checkpoint by skipping reading `DATA` part when only `METADATA` or `PROTOCOL` is needed.
```markdown
```

Add optimization for Delta v2 checkpoint read

---

lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/BigintValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/BinaryValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/BooleanValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/DateValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/DoubleValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/FixedLenByteArrayLongDecimalValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/FixedLenByteArrayShortDecimalValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/Int32ShortDecimalValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/Int64ShortDecimalValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/Int96TimestampValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/IntegerValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/PrimitiveValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/RealValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/TimeMicrosValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/TimestampMillisValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/TimestampNanosValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/TimestampTzMicrosValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/TimestampTzMillisValueWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/UuidValueWriter.java

Refactors parquet `PrimitiveValueWriter` implementations to:
- use `Block#mayHaveNull()` to skip null checks when possible
- Remove redundant sub-class fields
- Reuse `Binary` instances where possible 

Parquet writer cleanups

---

lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GcsStorageFactory.java

We don't expect an exception here, and translation to `GENERIC_INTERNAL_ERROR` is not useful.

Remove usage of TrinoException from GcsStorageFactory

---

core/trino-main/src/main/java/io/trino/cost/ComparisonStatsCalculator.java

`PlanNodeStatsEstimate.addSymbolStatistics()` is a destructive method. It doesn't seem to need to reassign the result.
```markdown
```

Remove unnecessary reassignment in ComparisonStatsCalculator

---

core/trino-main/src/main/java/io/trino/memory/ClusterMemoryManager.java
core/trino-main/src/main/java/io/trino/memory/MemoryManagerConfig.java
core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
core/trino-main/src/test/java/io/trino/memory/TestMemoryManagerConfig.java
testing/trino-tests/src/test/java/io/trino/memory/TestMemoryManager.java

query.low-memory-killer.delay is not needed:
* It does not prevent cascades of query kills. That is achieved by isLastKillTargetGone check in ClusterMemoryManager
* OOM blocked worker cannot be unblocked by other means other than killing the query. Revocable memory (and spill to disk) also won't cause node to be considered out-of-memory. Hence low-memory-killer does not interfere with spill-to-disk.
Having query.low-memory-killer.delay causes reduced concurrency
on a cluster with higher concurrency and under low-memory situations.
```markdown
* Remove …
```

Remove query.low-memory-killer.delay

---

plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/rule/RewriteDotProductFunction.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/rule/RewriteVectorDistanceFunction.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlVectorType.java

```markdown
* Improve performance when the query contains `-dot_product` projections. ({issue}`23015`)
```

Rewrite `-dot_product` to pgvector `<#>` operator in PostgreSQL

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java

Various cleanups

---

core/trino-main/src/main/java/io/trino/execution/scheduler/TopologyAwareNodeSelectorModule.java

Configuring
```
node-scheduler.policy=topology
node-scheduler.network-topology.type=file
```
currently fails with
```
1) [Guice/JitDisabled]: Explicit bindings are required and FileBasedNetworkTopology is not explicitly bound.
while locating FileBasedNetworkTopology
at GuiceMBeanExporter.<init>(GuiceMBeanExporter.java:40)
at MBeanModule.configure(MBeanModule.java:39)
while locating GuiceMBeanExporter
1 error
======================
Full classname legend:
======================
FileBasedNetworkTopology: "io.trino.execution.scheduler.FileBasedNetworkTopology"
GuiceMBeanExporter:       "org.weakref.jmx.guice.GuiceMBeanExporter"
MBeanModule:              "org.weakref.jmx.guice.MBeanModule"
========================
End of classname legend:
========================
```
The failure occurs because …

Fix binding of FileBasedNetworkTopology

---

plugin/trino-kafka-event-listener/pom.xml
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/KafkaEventListener.java
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/KafkaEventPublisher.java
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/model/QueryCompletedEventWrapper.java
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/model/QueryCreatedEventWrapper.java
plugin/trino-kafka-event-listener/src/test/java/io/trino/plugin/eventlistener/kafka/TestKafkaEventListenerConfig.java
plugin/trino-kafka-event-listener/src/test/java/io/trino/plugin/eventlistener/kafka/TestKafkaEventListenerPlugin.java
plugin/trino-kafka-event-listener/src/test/java/io/trino/plugin/eventlistener/kafka/TestKafkaRecordBuilder.java
plugin/trino-kafka-event-listener/src/test/java/io/trino/plugin/eventlistener/kafka/TestUtils.java

Minor cleanup in Kafka event listener

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Fixes #19971
Supersedes #23033
```markdown
* TBD. ({issue}`19971`)
```

Support tinyint/smallint to integer type coercion in Iceberg

---

docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/OAuth2SecurityConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/OAuth2SecurityProperties.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestOAuth2SecurityConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestingPolarisCatalog.java

Add scope field to be used while communicating with Iceberg REST catalog server
Fixes https://github.com/trinodb/trino/issues/22947
```markdown
* Add `iceberg.rest-catalog.oauth2.scope` config for Iceberg REST catalog. ({issue}`22961`)
```

Add scope field for Iceberg REST metastore

---

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java
core/trino-main/src/test/java/io/trino/cost/TestOptimizerConfig.java

PR #21429 fixed an issue that might cause query failures due to aggressive pushdown of expressions that could fail on certain inputs.
Unfortunately, it resulted in a regression in use cases that were relying on this behavior (e.g., issue #22268). A proper fix is not trivial, so we introduce a temporary escape hatch to allow users to restore the old behavior until the final fix is in place.
```markdown
* TBD. ({issue}`...`)
```

Add temporary escape hatch to allow unsafe pushdowns

---

docs/src/main/sphinx/connector/clickhouse.md
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java

ClickHouse allows `ORDER BY tuple()` expression when no sorting is required with MergeTree engine.
Fixes #23048
```markdown
* TBD. ({issue}`23048`)
```

Use ORDER BY tuple() by default in ClickHouse MergeTree

---

docs/src/main/sphinx/connector/delta-lake.md

It is rather unclear the fact that enabling `delta.checkpoint-filtering.enabled` implies probably also decreased memory pressure on the coordinator because there is no need anymore for storing the active files of the tables in the cache.
Related property `delta.metadata.live-files.cache-size` property 
```markdown
```

Enhance documentation for `delta.checkpoint-filtering.enabled` setting

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaFailureRecoveryTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergFailureRecoveryTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java

If coordinator stage is processing data output by workers we want to enable retries.
Even if coordinator is working fine the task from coordinator stage may fail e.g. if
upstream task fails while data it produces is speculatively processed by coordinator stage task.
```markdown
```

Allow retrying tasks from coordinator stages

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java

Splits with deletes require more work to process than a comparable split without delete. 
This should be accounted in iceberg split weight
```markdown
```

Increase weight of splits with delete files in iceberg

---

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryQueryRunner.java

Increase retries in BigQueryQueryRunner
The hope is to make tests more stable.

Increase retries in BigQueryQueryRunner

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

In case Iceberg commit fails throw TrinoException with clear error type.
```
"type": "org.apache.iceberg.exceptions.ValidationException",
"message": "Cannot commit, found new delete for replaced data file: ",
"stack": [
"org.apache.iceberg.exceptions.ValidationException.check(ValidationException.java:49)",
"org.apache.iceberg.MergingSnapshotProducer.validateNoNewDeletesForDataFiles(MergingSnapshotProducer.java:481)",
"org.apache.iceberg.MergingSnapshotProducer.validateNoNewDeletesForDataFiles(MergingSnapshotProducer.java:413)",
"org.apache.iceberg.BaseRewriteFiles.validate(BaseRewriteFiles.java:140)",
"org.apache.iceberg.SnapshotProducer.apply(SnapshotProducer.java:233)",
"org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotProducer.java:384)" …
```

Throw TrinoException when Iceberg commit fails

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogConnectorSmokeTest.java

Related to https://github.com/trinodb/trino/issues/23082
Issue appears due to the fact that drop table collects only latest metatdata file but older metadata files remains untouched. Ideally `testRegisterTableWithDroppedTable` should not have to be overridden as all the functionalities are supported by the Polaris catalog.
---
Below shows that create and drop table leaves behind no metadata files.
```
trino:tpch> CREATE TABLE sample (a int, b varchar, c boolean);
CREATE TABLE
trino:tpch> show create table sample;
Create Table                                                                        
-----------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE TABLE iceberg.tpch.sample ( …
```

Disable `testRegisterTableWithDroppedTable` in Polaris

---

core/trino-main/src/main/java/io/trino/operator/aggregation/state/StateCompiler.java

Changes `StateCompiler` to use `SliceBigArray` instead of `ObjectBigArray` when generating `GroupedInOut` state values for slices. When `ObjectBigArray` is used, the size of the values themselves are not tracked which can lead to OOM's for aggregations over large strings.
Fixes https://github.com/trinodb/trino/issues/23105. This issue was partially fixed by https://github.com/trinodb/trino/pull/21425 in Trino 445, but only addressed the issue for fixed width primitive types and not variable width types that were previously backed backed by `ObjectBigArray`.
```markdown
* Fix …
```

Fix memory tracking for varchar grouped aggregations

---

docs/src/main/sphinx/connector/prometheus.md
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusConnector.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusModule.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusSessionProperties.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusSplitManager.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegration.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusSplit.java

Sizes of different metrics may differ, to run automated ETL pipelines efficiently we can set different values of session properties like query_chunk_size_duration and max_query_range_duration.
Fixes #22319

Add session properties for prometheus connector

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/ExponentialGrowthPartitionMemoryEstimator.java
core/trino-main/src/main/java/io/trino/memory/ClusterMemoryManager.java
testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionCoordinatorExcludedTest.java

The change to filter out coordinator from output of ClusterMemoryManager::getWorkerMemoryInfo was beneficial for how ExponentialGrowthPartitionMemoryEstimator behaves if coordiantor is differently sized than workers.
Yet it introduced regression as same method was used in BinPackingNodeAllocatorService and as a result COORDINATOR_ONLY tasks could not be scheduled at all if node-scheduler.include-coordinator was set to false.
Unfortunately we had node-scheduler.include-coordinator set to true in all the tests so it was not catch by automation.
This commit adds a regression test too. …

Fix logic obtaining workers memory in FTE execution

---

core/trino-main/src/main/java/io/trino/server/ServerMainModule.java

This is an attempt to fix #22905 which after #18118 the `TaskExecutor` class is moved to an abstract implementation with the detail used is now in the `TimeSharingTaskExecutor` class.  The intention of this PR is to add this class into the exposed jmx mbean.
Also, the `TaskExecutor` is exposed in the mbean with empty metrics so I've removed that as well. I'm unclear if `ThreadPerDriverTaskExecutor` should have any jmx metrics as an alternative TaskExecutor, but since JMX wasn't referenced, I didn't include that in the if block.
I did notice that beans are now also prefixed with `jmx.trino...` in the domains. Is that intended? Previous model was just `trino...`.  I may be mistaken but this is how they're surfaced in Datadog if I include the additional timesharing metrics from …

Add missing TaskExecutorResource to jmx

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergExceptions.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java

Previously if we got exception pointing out to missing metadata files
during split enumeration query was failing with GENERIC_INTERNAL_ERROR
instead of more appropriate, Iceberg specific error code.
```markdown
```

Use ICEBERG_MISSING_METADATA error code in IcebergSplitSource

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java

One method in Glue v2 Hive metastore is missing handling of `SdkException`

Throw TrinoException on AWS errors in GlueHiveMetastore.updateTable

---

docs/src/main/sphinx/functions/table.md

Was looking at the linked issues and found a fix that needed me to rejig both sections since the removal of the no-index flag breaks the build since there is another function called sequence in array.md.
Fixes https://github.com/trinodb/trino/issues/22975

Improve docs for built-in table functions

---

lib/trino-parquet/src/main/java/io/trino/parquet/ParquetTypeUtils.java
lib/trino-parquet/src/main/java/io/trino/parquet/metadata/PrunedBlockMetadata.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java

Parquet files may contain duplicate column names when written by case sensitive tools. 
We read the first case insensitive match from the file in this scenario.
Fixes query failures caused by https://github.com/trinodb/trino/pull/22538
```markdown
* Fixes query failures due to "Multiple entries with same key" when reading parquet files. ({issue}`23050`)
```

Fix handling of duplicate column names in parquet reader

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/glue/v1/DeltaLakeGlueV1MetastoreTableOperations.java

Otherwise, DeltaLakeTableMetadataScheduler fails internally. 
I manually tested and didn't add a test because this issue is specific to V1 (legacy). 

Keep last parameters when updating Glue in Delta

---

plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/PostgreSqlQueryRunner.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java

I want to make it configurable so that we can test pgvector quickly. 

Make docker image name in PostgreSQL query runner configurable

---

core/trino-web-ui/src/main/resources/webapp-preview/package.json
core/trino-web-ui/src/main/resources/webapp/src/package.json

Use `npm clean-install` to avoid modifying the `package-lock.json` file and ensure reproducible builds, especially in the CI.

Make web-ui module builds reproducible

---

docs/src/main/sphinx/object-storage/file-system-azure.md
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystem.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemConfig.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemFactory.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureLocation.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemConfig.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureLocation.java

Fixes #21307
```markdown
* Allow configuring endpoint for the native Azure filesystem. ({issue}`23071`)
* Allow configuring endpoint for the native Azure filesystem. ({issue}`23071`)
* Allow configuring endpoint for the native Azure filesystem. ({issue}`23071`)
* Allow configuring endpoint for the native Azure filesystem. ({issue}`23071`)
```

Allow configuring endpoint for Azure FS

---

core/trino-main/src/main/java/io/trino/connector/CatalogStoreManager.java
core/trino-main/src/main/java/io/trino/connector/DynamicCatalogManagerModule.java
core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
core/trino-main/src/test/java/io/trino/connector/TestCatalogStoreConfig.java
core/trino-main/src/test/java/io/trino/connector/TestCatalogStoreManager.java
core/trino-main/src/test/java/io/trino/server/testing/TestTestingTrinoServer.java

Currently a custom catalog store plugin cannot be used because the Guice bindings are incorrect.
Fixes https://github.com/trinodb/trino/issues/22554
Supercedes https://github.com/trinodb/trino/pull/22784
I couldn't think of any way to test this other than a product test - but that too would need me to add a custom plugin to the build just to test this - I manually tested this instead for now.
See https://github.com/trinodb/trino/issues/22554 for details. And https://github.com/trinodb/trino/pull/20489 for earlier changes.
```markdown
* Fix loading of custom `CatalogStore` …
```

Fix custom catalog store plugin loading (v2)

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/v1/GlueClientUtil.java

After merging https://github.com/trinodb/trino/pull/22814, @ebyhr reporter that `TestIcebergGlueCatalogConnectorSmokeTest#testDeleteRowsConcurrently` became flaky
After running it several times locally, I found that commit https://github.com/trinodb/trino/commit/4b28d9b5c009b061aa7043c6d41768fd83fae0ac seems to be problematic
Default retry strategy, which brings default backoff strategy, wasn't good enough when dealing with such concurrent use cases. After changing to exponential backoff strategy it feels much more stable now.
https://github.com/trinodb/trino/pull/22814 …

Use exponential backoff retry strategy for glue client

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcOutputTableHandle.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/RemoteTableName.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcOutputTableHandle.java
plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java
plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMetadata.java
plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteOutputTableHandle.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMergeSink.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixOutputTableHandle.java
plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java

The `catalogName` and `schemaName` members are annotated with nullable, but it's easy to miss the info when use getter. Instead, use `RemoteTableName`, which encapsulates the `catalogName` and `schemaName` within `Optional` wrapper.
```markdown
```

Use RemoteTableName in JdbcOutputTableHandle

---

plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/rule/RewriteVectorDistanceFunction.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlVectorType.java

Fixes #23152
```markdown
* Fix potential failure when pushdown `euclidean_distance`, `cosine_distance` and `dot_product` functions. ({issue}`23152`)
```

Fix failure when rewriting distance functions in PostgreSQL

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java

The test is slow and increases the possibility of CI failures due to BigQuery SLA because it contains 100 executions. 
Disabling this test should be safe since the connector doesn't support SAMPLE pushdown. 
I think we can make this test conditional with `TestingConnectorBehavior` in a follow-up. 
https://github.com/trinodb/trino/blob/90c48bba606135bb03f482bce2f616ce6a78025f/testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueries.java#L456-L476

Disable testTableSampleBernoulli in BigQuery

---

docs/src/main/sphinx/object-storage/file-system-s3.md
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java
lib/trino-filesystem-cache-alluxio/src/test/java/io/trino/filesystem/alluxio/TestAlluxioCacheFileSystem.java
lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/AbstractTestGcsFileSystem.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3Context.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemConfig.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3OutputFile.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3OutputStream.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/AbstractTestS3FileSystem.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemAwsS3.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemConfig.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemLocalStack.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemMinIo.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemS3Mock.java
lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java
lib/trino-filesystem/src/test/java/io/trino/filesystem/local/TestLocalFileSystem.java
lib/trino-filesystem/src/test/java/io/trino/filesystem/memory/TestMemoryFileSystem.java
lib/trino-filesystem/src/test/java/io/trino/filesystem/memory/TestMemoryFileSystemCache.java
lib/trino-hdfs/src/test/java/io/trino/filesystem/hdfs/TestHdfsFileSystemHdfs.java
lib/trino-hdfs/src/test/java/io/trino/filesystem/hdfs/TestHdfsFileSystemLocal.java
lib/trino-hdfs/src/test/java/io/trino/filesystem/hdfs/TestHdfsFileSystemS3Mock.java

This allows implementing exclusive write that will ensure that the next putObject won't override existing file.
This makes all three major cloud storage filesystem implementations support `createExclusive`
```markdown
```

Add support for S3 conditional writes

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java

We are keeping history of task failures which is appended to final failure of query if we run out of retries. The last task failure which caused the query to fail was not part of the history. It was root exception but task Id was missing. With this PR we will keep it both as root exception and as part of history.

Keep most recent task failure in failures history

---

docs/src/main/sphinx/connector/delta-lake.md
docs/src/main/sphinx/connector/hive.md
docs/src/main/sphinx/connector/hudi.md
docs/src/main/sphinx/connector/iceberg.md
docs/src/main/sphinx/object-storage/file-formats.md
docs/src/main/sphinx/release/release-396.md

* Moved `hive.orc.use-column-names` and `hive.parquet.use-column-names` are only relevant for Hive.
* Removed the `hive.` prefix from the ORC and Parquet config properties.
```markdown
```

Edit file formats properties

---

docs/src/main/sphinx/admin.md
docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-455.md

Assemble the release notes for the upcoming Trino 455 release.
* #23051 ✅ rn ✅ docs
* #23049 ✅ rn ✅ docs
* #23056 ✅ rn ✅ docs
* #22646 ✅ rn ✅ docs
* #23057 ✅ rn ✅ docs
* #23040 ✅ rn ✅ docs
* #23019 ✅ rn ✅ docs
* #23058 ✅ rn ✅ docs
* #23011 ✅ rn ✅ docs
* #23059 ✅ rn ✅ docs
* #23079 ✅ rn ✅ docs
* #22774 ✅ rn ✅ docs
* #23008 ✅ rn ✅ docs
* #23099 ✅ rn ✅ docs
* #23098 ✅ rn ✅ docs
* #23110 ✅ rn ✅ docs
* #23073 ✅ rn ✅ docs
* #22368 ✅ rn ✅ docs
No merges.
No merges.
* #23116 ✅ rn ✅ docs
* #23113 ✅ rn ✅ docs
* #23045 ✅ rn ✅ docs
* #22914 ✅ rn ✅ …

Add Trino 455 release notes

---

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
core/trino-main/src/main/java/io/trino/cost/PlanNodeStatsEstimateMath.java
core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
core/trino-main/src/main/java/io/trino/sql/planner/AdaptivePlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/AdaptiveReorderPartitionedJoin.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DetermineJoinDistributionType.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DetermineSemiJoinDistributionType.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/StreamPropertyDerivations.java
core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
core/trino-main/src/test/java/io/trino/sql/planner/TestAdaptivePlanner.java
core/trino-main/src/test/java/io/trino/sql/planner/assertions/PlanMatchPattern.java
core/trino-main/src/test/java/io/trino/sql/planner/assertions/RemoteSourceMatcher.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestAdaptiveReorderPartitionedJoin.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDetermineJoinDistributionType.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
lib/trino-matching/src/main/java/io/trino/matching/DefaultPrinter.java
lib/trino-matching/src/main/java/io/trino/matching/Pattern.java
lib/trino-matching/src/main/java/io/trino/matching/PatternVisitor.java
lib/trino-matching/src/main/java/io/trino/matching/pattern/OrPattern.java

Flip sides for partitioned join based on data size stats. This rule is only used during Adaptive Planning in FTE.
It helps fix the join order due to either missing or incorrect stats, or maybe wrong estimations caused by skewed distribution of filters, etc.
Example query using the TPCDS dataset. Here the last join has an incorrect order.
```
SELECT sum(c.c_current_cdemo_sk), max(c.c_birth_country),
sum(ss.ss_quantity), sum(ss.ss_list_price), sum(ss.ss_coupon_amt),
max(i.i_current_price), sum(cs.cs_wholesale_cost), sum(cs.cs_list_price),
sum(cs.cs_sales_price), sum(cs.cs_ext_sales_price),
sum(cs.cs_net_paid_inc_tax), sum(cs.cs_net_paid_inc_ship),
sum(cs.cs_net_profit), sum(cs.cs_ext_tax), sum(cs.cs_coupon_amt),
sum(cs.cs_ext_ship_cost), sum(cs.cs_net_paid), sum(cs.cs_net_paid_inc_tax), …
```

[FTE] Adaptive reorder partitioned join

---

docs/src/main/sphinx/admin/fault-tolerant-execution.md
docs/src/main/sphinx/object-storage/file-system-s3.md

Add same note as #22711 to S3 file system page, indicating that we do not test all S3-compatible storage systems
```markdown
```

Add compatibility note to S3 file system page

---

.github/workflows/ci.yml
plugin/trino-bigquery/pom.xml
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/CredentialsOptionsConfigurer.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryParentProjectId.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestCredentialsOptionsConfigurer.java

If `bigquery.parent-project-id` was specified in configuration it was set as `projectId` in `BigQueryOptions`. 
For queries without `TableId` or `DatasetId` specified `BigQueryOptions` was used resulting in using wrong projectId.
This problem is visible when using PTF with parent-proejct-id set, resulting in permission problem like:
```
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
POST https://bigquery.googleapis.com/bigquery/v2/projects/parent-project-id/jobs?prettyPrint=false
{
"code": 403,
"errors": [
{
"domain": "global",
"message": "Access Denied: Table parent-project-id:tpch.nation: User does not have permission to query table parent-project-id:tpch.nation, or perhaps it does not exist.",
"reason": "accessDenied"
}
],
"message": "Access …
```

Fix BigQuery configuration with parent-project-id

---

docs/src/main/sphinx/connector/delta-lake.md
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeOutputTableHandle.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableProperties.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/MetadataEntry.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheFileOperations.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDeleteCompatibility.java

Fixes #22104
```markdown
* Add support for creating tables with deletion vectors. ({issue}`22104`)
```

Add support for creating Delta tables with deletion vectors

---

client/trino-client/src/main/java/io/trino/client/uri/HttpClientFactory.java

~Remove dead code in OkHttpUtil.~
~I assume this isn't needed since we now support http2 (#21793).~
Fix regression on disabled HTTP/2 negotiation.
Added by:
https://github.com/trinodb/trino/commit/0de723656bce74d1c64050413a4e467fa43fab9e
Usage was gone in (unintentionally?):
https://github.com/trinodb/trino/commit/05bcba69b8651b7536ae1c1a4d99d8b5b309fbce#diff-2514cab429f6ab30764fd3c34e7318b2085145a670a206283497208b9547de40L617
(looks like the `- [x]` syntax triggers a task list)

Fix regression on disabled HTTP/2 negotiation

---

docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastoreConfig.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreConfig.java

Current default is not large enough to keep partitions metadata in cache for certain tpcds queries which access all the fact tables
```markdown
* Improve performance of queries which scan a large number of partitions. ({issue}`23194`)
```

Increase hive.metastore-cache-maximum-size to 20000

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java

When [null credential](https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java#L616) is passed, [the block refreshing token](https://github.com/apache/iceberg/blob/229d8f6fcd109e6c8943ea7cbb41dab746c6d0ed/core/src/main/java/org/apache/iceberg/rest/RESTSessionCatalog.java#L992-L1031) is not executed when creating a `newSession` in `RESTSessionCatalog`. ie further calls to `newSession` doesn't fetch a new token rather uses an existing token(created during initialization) causes request failure when using initially created token expires. PR aims to pass user provided credential which will be considered in `newSession` to create a new token.
Im not following on why `Map<String, String> credentials` is …

Pass credential when creating SessionContext in REST metastore

---

client/trino-jdbc/pom.xml
client/trino-jdbc/src/main/java/io/trino/jdbc/InMemoryTrinoResultSet.java
pom.xml

Produce nonshaded trino-jdbc

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogConnectorSmokeTest.java

Previously incorrect test was disabled. PR reverts https://github.com/trinodb/trino/pull/23099 and correctly disables `TestIcebergPolarisCatalogConnectorSmokeTest#testRegisterTableWithDroppedTable`

Disable testRegisterTableWithDroppedTable in Polaris

---

core/trino-main/src/main/java/io/trino/testing/TestingMetadata.java
core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloMetadata.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryMetadata.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorMetadata.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/metadata/TestRaptorMetadata.java

Using `checkArgument` method instead of TrinoException because 
unsupported view properties should be blocked in the engine. 
```markdown
* Remove deprecated `ConnectorMetadata.createView` method. ({issue}`23208`)
```

Remove deprecated ConnectorMetadata.createView from SPI

---

plugin/trino-pinot/pom.xml
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotModule.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotGrpcDataFetcher.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotExpressionRewriter.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/MetadataUtil.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConnectorSmokeTest.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java

Update to pinot 1.2.0
Attempted to push to #23143 but could not find the branch. I manually copied @wendigo's first commit.
```markdown
```

Update pinot to 1.2.0

---

core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java

```markdown
* Remove deprecated `ConnectorMetadata.beginRefreshMaterializedView` method without `RefreshType`. argument. ({issue}`issuenumber`)
```

Remove deprecated ConnectorMetadata.beginRefreshMaterializedView

---

core/trino-main/src/test/java/io/trino/execution/TestAddColumnTask.java
core/trino-main/src/test/java/io/trino/execution/TestCallTask.java
core/trino-main/src/test/java/io/trino/execution/TestCommentTask.java
core/trino-main/src/test/java/io/trino/execution/TestDropMaterializedViewTask.java
core/trino-parser/src/main/java/io/trino/sql/tree/AddColumn.java
core/trino-parser/src/main/java/io/trino/sql/tree/BinaryLiteral.java
core/trino-parser/src/main/java/io/trino/sql/tree/Call.java
core/trino-parser/src/main/java/io/trino/sql/tree/CaseStatementWhenClause.java
core/trino-parser/src/main/java/io/trino/sql/tree/Comment.java
core/trino-parser/src/main/java/io/trino/sql/tree/CommentCharacteristic.java
core/trino-parser/src/main/java/io/trino/sql/tree/DropFunction.java
core/trino-parser/src/main/java/io/trino/sql/tree/DropMaterializedView.java
core/trino-parser/src/main/java/io/trino/sql/tree/DropRole.java
core/trino-parser/src/main/java/io/trino/sql/tree/ElseClause.java
core/trino-parser/src/main/java/io/trino/sql/tree/EmptyPattern.java
core/trino-parser/src/main/java/io/trino/sql/tree/Except.java
core/trino-parser/src/main/java/io/trino/sql/tree/ExcludedPattern.java
core/trino-parser/src/main/java/io/trino/sql/tree/ExplainType.java
core/trino-parser/src/test/java/io/trino/sql/TestSqlFormatter.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParserRoutines.java

Remove redundant constructors from some classes in `io.trino.sql.tree` package

---

plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusClient.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusRecordCursor.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusRecordSet.java

Fixes https://github.com/trinodb/trino/issues/23013
Release notes: Fix reading large Prometheus responses

Lazily read Prometheus response

---

core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
docs/src/main/sphinx/admin/fault-tolerant-execution.md

With limit of 256 splits per task it was possible to end up with very small tasks and possibly even reach limit of number of tasks per stage (2^^15). The problem appeared when splits were very small. Task sizing should be mostly done based on split size; max number of splits should be treated as extra limit to be reached only in rare situations. This PR bumps default value 8x to 2048.
```markdown
```

Bump default value of max split count per task for FTE

---

core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java

```markdown
* Remove deprecated `ConnectorMetadata.finishInsert` method without `sourceTableHandles` argument. ({issue}`23213`)
```

Remove deprecated ConnectorMetadata.finishInsert without sourceTableHandles argument

---

plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotConnectorTest.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/PinotQueryRunner.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConnectorSmokeTest.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConnectorTest.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotPasswordAuthentication.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotPreviousConnectorTest.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java

Add test against Pinot 1.1.0 server

---

core/trino-main/src/main/java/io/trino/testing/TestingMetadata.java
core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloMetadata.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcMetadata.java
plugin/trino-example-http/src/test/java/io/trino/plugin/example/TestExampleMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMetadata.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryMetadata.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorMetadata.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/TestRaptorConnector.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/metadata/TestRaptorMetadata.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/metadata/TestRaptorSplitManager.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/storage/organization/TestShardOrganizerUtil.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/systemtables/TestShardMetadataRecordCursor.java

```markdown
* Remove deprecated `ConnectorMetadata.createTable(ConnectorSession session, ConnectorTableMetadata tableMetadata, boolean ignoreExisting)` method. ({issue}`issuenumber`)
```

Remove deprecated ConnectorMetadata.createTable with boolean ignoreExisting

---

core/trino-main/src/main/java/io/trino/testing/TestingMetadata.java
core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloMetadata.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcMetadata.java
plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMetadata.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryMetadata.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorMetadata.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/metadata/TestRaptorMetadata.java

```markdown
* Remove deprecated `ConnectorMetadata.beginCreateTable` method without `replace` argument. ({issue}`23211`)
```

Remove deprecated ConnectorMetadata.beginCreateTable without replace

---

core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroup.java
core/trino-main/src/test/java/io/trino/execution/resourcegroups/TestResourceGroups.java

Add missing information from `InternalResourceGroup` to the set of metrics exposed when `jmxExport = true` to provide a more complete picture of the state of each resource group.
[Resource groups](https://trino.io/docs/current/admin/resource-groups.html) allow us to enable monitoring by using `jmxExport = true` (recently enabled by default in #20810, though subsequent reverted in #22185). However currently the set of information exposed by the resource group is restricted to a set of fields that seems fairly arbitrary to me, limiting the value. I would break the information into two categories: config information (e.g. what are the configured limits) and runtime information (e.g. how many queries are currently running). For this to be really useful, you need both things, so you can …

Expose a more complete set of information from the JMX export of InternalResourceGroup

---

.github/workflows/stale.yml

Initially we had too many open PRs for that expanded timeframe that covers all open PRs. We are now at 300 so we can activate this. It will cause messages for the older open PRs and we can then triage them easier .. just like all the others that are live now.
Also a model for what we will do with issues soonish.

Expand stale PR timeframe

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSinkProvider.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/PrestoTemptoPlugin.java

Small random cleanups. Non functional changes.

Random non-functional cleanups

---

core/trino-main/src/test/java/io/trino/execution/TestCommitTask.java
core/trino-main/src/test/java/io/trino/execution/TestCreateCatalogTask.java
core/trino-main/src/test/java/io/trino/execution/TestDeallocateTask.java
core/trino-main/src/test/java/io/trino/execution/TestDropCatalogTask.java
core/trino-parser/src/main/java/io/trino/sql/tree/AnchorPattern.java
core/trino-parser/src/main/java/io/trino/sql/tree/Commit.java
core/trino-parser/src/main/java/io/trino/sql/tree/CreateCatalog.java
core/trino-parser/src/main/java/io/trino/sql/tree/CreateFunction.java
core/trino-parser/src/main/java/io/trino/sql/tree/CurrentCatalog.java
core/trino-parser/src/main/java/io/trino/sql/tree/CurrentPath.java
core/trino-parser/src/main/java/io/trino/sql/tree/CurrentSchema.java
core/trino-parser/src/main/java/io/trino/sql/tree/CurrentUser.java
core/trino-parser/src/main/java/io/trino/sql/tree/Deallocate.java
core/trino-parser/src/main/java/io/trino/sql/tree/Delete.java
core/trino-parser/src/main/java/io/trino/sql/tree/DescribeInput.java
core/trino-parser/src/main/java/io/trino/sql/tree/DescribeOutput.java
core/trino-parser/src/main/java/io/trino/sql/tree/DeterministicCharacteristic.java
core/trino-parser/src/main/java/io/trino/sql/tree/DropCatalog.java
core/trino-parser/src/test/java/io/trino/sql/TestSqlFormatter.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParserRoutines.java

Remove redundant constructors in a parser

Remove redundant constructors in a parser

---

core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorSplit.java

This method has been deprecated since version 445. 
```markdown
* Remove the deprecated `ConnectorSplit.getInfo method` method.
Use `getSplitInfo` method instead. ({issue}`23271`)
```

Remove deprecated `ConnectorSplit.getInfo` method

---

core/trino-spi/src/main/java/io/trino/spi/type/DecimalConversions.java

This method has been deprecated since version 415.
```markdown
* Remove deprecated `DecimalConversions.realToShortDecimal` method. 
Use `realToShortDecimal(float value, long precision, long scale)` instead. ({issue}`23275`)
```

Remove deprecated DecimalConversions.realToShortDecimal

---

docs/src/main/sphinx/optimizer.md

Fix broken build on master.  `./mvnw clean install -pl :trino-docs` was failing, and so the CI build.
Relates to https://github.com/trinodb/trino/pull/23270

Fix docs build

---

core/trino-spi/src/main/java/io/trino/spi/connector/ConstraintApplicationResult.java

This constructor has been deprecated since version 434. 
```markdown
* Remove the deprecated constructor from `ConstraintApplicationResult` class. ({issue}`23272`)
```

Remove deprecated constructor from ConstraintApplicationResult

---

plugin/trino-delta-lake/pom.xml
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSynchronizerModule.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3ConditionalWriteLogSynchronizer.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3LockBasedTransactionLogSynchronizer.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3NativeTransactionLogSynchronizer.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMinioAndHmsConnectorSmokeTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMinioAndLockBasedSynchronizerSmokeTest.java

https://docs.aws.amazon.com/AmazonS3/latest/userguide/conditional-requests.html#conditional-writes
This allows for the faster, concurrent write reconciliation without the custom locking mechanism
that was implemented for S3 when it lacked exclusive write support. Since this is now supported,
we should use faster path if possible.
Enabled in tests for S3 and Minio tests. Doesn't work in s3mock and ~local-stack~ (support added 29/08/2024).
Release notes: Add support for lock-less Delta Lake write reconciliation on S3

Delta lake S3 exclusive write reconciliation 

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

When creating an Iceberg table fails, for example with a permission error, it should be classified as an external error, not internal generic error.
Fixes #20695. Tested manually using the Iceberg query runner.

Classify errors as external when creating Iceberg tables

---

.github/workflows/ci.yml

Having a bit more output does not do a lot of harm and having --quite proved to mask some errors related to GIB, making debugging hard.

Drop --quite from most maven runs on CI

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSink.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSinkProvider.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/SinkSqlProvider.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMergeSink.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMergeTableHandle.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixPageSinkProvider.java

Refactor Phoenix MERGE implementation

---

docs/src/main/sphinx/client/jdbc.md

See title and changes.
Follow up to https://github.com/trinodb/trino/pull/22098

Add docs for non-shaded JDBC driver JAR

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3Context.java

SSE configuration is not applied correctly if we have a S3SecurityMapping which configures kmsKeyId for a given user and the default S3 Config has `s3.sse.type` set to NONE or S3.
```markdown
* Fix SSE configuration when using S3SecurityMapping with kmsKeyId configured
```

Update sseType when creating S3Context with KmsKeyId

---

core/trino-main/src/main/java/io/trino/metadata/TypeRegistry.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/type/TypeNotFoundException.java

This change fixes the error code that is reported when a TrinoView type cannot be parsed and causes a `ParsingException` within the TypeRegistry.  This will get converted to a generic `TrinoException` with GENERIC_INTERNAL_ERROR.  This change wraps the exception in a `TypeNotFoundException`, which will be handled by the `MetadataManager` with an existing catch block.
Issue: https://github.com/trinodb/trino/issues/23285

Wrap ParsingException in TypeRegistry in a TypeNotFoundException

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DriverConnectionFactory.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/credential/CredentialPropertiesProvider.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/credential/DefaultCredentialPropertiesProvider.java

Previously we used generics for injecting non String property, but it might not be required as all JDBC properties key are of String type and value could be generic Object type.
```markdown
```

Simplify CredentialPropertiesProvider

---

plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/KafkaEventListenerFactory.java

All other event listeners just use the short name without `-event-listener`. For consistency we should change while the plugin is still relatively new. Its a breaking change at this stage but with very limited impact since there are barely any users.
For now I just pushed this .. not sure if any other changes are necessary. Running tests locally now - and they passed.
Found during work on #23158
I will update docs PR or docs here .. depending on what merges first.
```markdown
* Breaking: Shorten the event-listener name for the Kafka event listener to `kafka`.Fix some things. ({issue}`23308`)
```

Shorten name for Kafka event listener

---

lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/openxjson/OpenXJsonDeserializer.java
lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/openxjson/TestOpenxJsonFormat.java

OpenX JSON supports decoding JSON lines containing a JSON array, as opposed to a JSON object. In this case the values are mapped to columns using the ordinal position instead of mapping by field name. The decoder was not using the Column ordinal and instead was just using the position in the output list, which resulted in data appearing in the wrong output column.
This bug has been present since the first version of the native OpenX JSON decoder.
Fixes #23120 
```markdown
* Fix OpenX JSON decoding a JSON array line that resulted in data being written to wrong output column. …
```

Fix OpenX JSON decoding of top level JSON array

---

docs/src/main/sphinx/client/jdbc.md
docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-456.md

Assemble the release notes for the upcoming Trino 456 release.
* #23046 ✅ rn ✅ docs
* #22755 ✅ rn ✅ docs 
* #23041 ✅ rn ✅ docs 
* #22448 ✅ rn ✅ docs 
* #23047 ✅ rn ✅ docs 
* #23189 ✅ rn ✅ docs 
* #23190 ✅ rn ✅ docs 
* #23191 ✅ rn ✅ docs 
* #23195 ✅ rn ✅ docs 
* #23198 ✅ rn ✅ docs 
* #23194 ✅ rn ✅ docs 
* #23060 ✅ rn ✅ docs 
* #23004 ✅ rn ✅ docs
* #22659 ✅ rn ✅ docs
* #22098 ✅ rn ✅ docs, docs in #23254
* #23202 ✅ rn ✅ docs
* #23204 ✅ rn ✅ docs
* #23208 ✅ rn ✅ docs
* #23210 ✅ rn ✅ docs
* #23212 ✅ rn ✅ docs
* #23219 ✅ rn ✅ docs
* #23218 ✅ …

Add Trino 456 release notes

---

core/trino-main/src/main/java/io/trino/sql/planner/plan/Assignments.java

Avoids redundant `containsKey` / `get` calls in favor of a direct call to `put`, followed by a check on the result.

Minor improvement to Assignments.Builder

---

core/trino-main/src/main/java/io/trino/operator/project/PageProcessor.java
core/trino-main/src/main/java/io/trino/operator/project/PageProcessorMetrics.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestDynamicRowFiltering.java

Dynamic filter evaluation can turn itself off when it's selectivity is low. 
So it is better to evaluate it before the static filter as only selective dynamic filters 
will be retained after processing a few input pages.
```markdown
```

Move dynamic filter evaluation ahead of static filter

---

docs/src/main/sphinx/connector/delta-lake.md
docs/src/main/sphinx/release/release-444.md

* Added documentation for support of shallow cloned tables - Delta Lake. 
* Edited the link on the 444 Release note.

Add shallow clone documentation

---

core/trino-main/src/main/java/io/trino/operator/DirectExchangeClient.java
core/trino-main/src/test/java/io/trino/operator/TestDirectExchangeClient.java

https://github.com/trinodb/trino/commit/8b6983ae7797669c62c40d31fd99dd54b877cfc9 has changed improved hot loop on list 
On the top of this, we could improve more by keeping running clients. So we don't have to loop through `allClients` every time.
I faced a case DirectExchangeClient had about 10k allClients. Looping on it every schedule caused lock contention.
( x ) Release notes are required. Please propose a release note for me.
```markdown
```

Reduce hot loop in DirectExchangeClient

---

core/trino-spi/src/main/java/io/trino/spi/type/CharType.java
core/trino-spi/src/main/java/io/trino/spi/type/VarcharType.java

The previous implementations for `VarcharType` and `CharType` would only hash the length parameter, which `Integer#hashCode()` defines to simply be the value itself. This resulted in a very poor distribution of hash code values while also incurring the overhead of boxing to `Integer` and constructing single element varargs arrays on each call.
The new implementation avoids the boxing and varargs overheads and includes the classes hashCode to achieve a better distribution of output values.

Improve hashCode() for char and varchar types

---

core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantDistinctAggregation.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveRedundantDistinctAggregation.java

This optimization removes the redundant Aggregation operator introduced by Distinct clause when the query contains Grouped Aggregation operator.
For context, we noticed a query failing due to OOM error where the query plan contained a Grouped Aggregation Operator followed by the Distinct Aggregation Operator. The Distinct Aggregation Operator is redundant for Grouping Aggregations. After removing the DISTINCT clause, the query succeeded. Adding an Optimizer Rule for the same.
```markdown
* Improve performance for queries with a redundant `DISTINCT` over already-distinct …
```

Add a new Optimizer Rule to Remove Distinct Aggregation for Queries containing Grouped Aggregation Operators

---

core/trino-spi/pom.xml
plugin/trino-elasticsearch/pom.xml
pom.xml

Update airbase, airlift and couple of dependencies

---

lib/trino-filesystem-gcs/pom.xml
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystem.java
lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/AbstractTestGcsFileSystem.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystem.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemFactory.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3SecurityMappingFileSystemFactory.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/AbstractTestS3FileSystem.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemLocalStack.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemS3Mock.java
lib/trino-filesystem/pom.xml
lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoFileSystem.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/UriLocation.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/tracing/TracingFileSystem.java
lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java

Allow generating presigned URIs for S3 and GCS

---

lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java

Sometimes the retrieval fails and we can't tell why

Debug direct segment retrieval

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ByteColumnAdapter.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/Fixed12ColumnAdapter.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/Int128ColumnAdapter.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/IntColumnAdapter.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/LongColumnAdapter.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ShortColumnAdapter.java

Avoids allocating intermediate nested arrays and implements primitive buffer concatenation directly. Also ensures that the ByteColumnAdapter checks for overflow on merged buffers, since guava's Bytes.concat did not previously check for that.

Improve parquet column adapter merge

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/projection/PartitionProjection.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveS3AndGlueMetastoreTest.java

If table location ends with `/` then, the partition location is incorrectly calculated when using partition projection in Hive leading to no data returned from the query.
PR aims to add slash between table location and partition name only if in case table location doesn't end with slash.
```markdown
```

Deduce correct partition location in Hive partition projection

---

core/trino-main/src/main/java/io/trino/type/VarcharOperators.java
core/trino-main/src/test/java/io/trino/type/TestVarcharOperators.java

Java has inconsistent behaviour of the [Primitive].parse* methods:
Long.parseLong(" 1337 ") throws the NumberFormatException, while Float.parseFloat(" 1337 ") parses successfully.
FloatingDecimal class has the following code:
```
in = in.trim(); // don't fool around with white space.
```
Let's not fool around and trim every varchar before parsing.
Fixes https://github.com/trinodb/trino/issues/23359
```markdown
```

Fix casting from varchar to numeric with spaces

---

.github/workflows/ci.yml

Packaging artifacts take significant time. Instead of running verify, let's compile `compile` and `test` scopes only.
```markdown
```

Speed up error_prone checks

---

docs/src/main/sphinx/connector/druid.md
docs/src/main/sphinx/connector/exasol.md
docs/src/main/sphinx/connector/mariadb.md
docs/src/main/sphinx/connector/mysql.md
docs/src/main/sphinx/connector/oracle.md
docs/src/main/sphinx/connector/postgresql.md
docs/src/main/sphinx/connector/redshift.md
docs/src/main/sphinx/connector/singlestore.md
docs/src/main/sphinx/connector/sqlserver.md
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataConfig.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcMetadataConfig.java

Reduces data transfer out of remote systems.
Most systems can handle IN lists of a few hundered values.
```markdown
* Reduce data transfer from remote systems for queries with large IN lists. ({issue}`23381`)
```

Raise default for jdbc domain-compaction-threshold

---

plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/backup/BackupManager.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/DatabaseMetadataModule.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/ShardRecoveryManager.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/organization/ShardOrganizer.java

Avoid test cleanup errors in Raptor

---

core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/analyzer/SemanticExceptions.java
core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/BaseOpenSearchConnectorTest.java

Fixes https://github.com/trinodb/trino/issues/23363
Release notes: improve error message while dereferencing an unknown row field

Fix error message on row dereference

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftMetastoreUtil.java

Currently in some cases when Hive partition metadata is corrupted such that a storage descriptor is present, but it doesn't have `columns` set, you will get an NPE thrown from Trino:
```
2024-09-06T21:31:06.172Z        ERROR   query-execution-2177492 io.trino.execution.scheduler.PipelinedQueryScheduler    Failure in distributed stage for query 20240906_213105_35785_ujj3t
io.trino.spi.TrinoException: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because "schema" is null
```
This PR adds a check to confirm the value is non-null, and throws `HIVE_INVALID_METADATA` in case it is corrupted instead of NPE, to give a more clear error message and provide more information on which partition's metadata is corrupted.
(X) This is not user-visible or is docs only, and no …

Fix NPE in ThriftMetastoreUtil to provide proper error message

---

core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorTableLayout.java

The constructor has been deprecated since version 446. 
```markdown
* Remove the deprecated constructor from `ConnectorTableLayout` class. ({issue}`23395`)
```

Remove deprecated constructor from ConnectorTableLayout

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java

Example failure: https://github.com/trinodb/trino/actions/runs/10669645490/job/29572078260
```
Error:  io.trino.plugin.iceberg.catalog.jdbc.TestIcebergJdbcCatalogConnectorSmokeTest.testUnsupportedViewDialect -- Time elapsed: 0.230 s <<< ERROR!
io.trino.testing.QueryFailedException: Error listing views for catalog iceberg: Namespace does not exist: test_schema_create_66vre8mc77
at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:134)
at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:558)
at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:541)
at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java:313)
at …
```

Suppress exceptions when listing identifiers in Iceberg JDBC catalog

---

lib/trino-filesystem-s3/pom.xml
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/AwsSdkV2ApiCallStats.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemFactory.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemModule.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemStats.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemAwsS3.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemLocalStack.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemMinIo.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemS3Mock.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergVendingRestCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/org/apache/iceberg/snowflake/TestTrinoSnowflakeCatalog.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/TestFileSystemSpoolingManager.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeJmx.java

This PR is implementation for the issue in https://github.com/trinodb/trino/issues/23177
(O) Release notes are required, with the following suggested text:
```markdown
* Added JMX monitoring support for native s3 filesystem
```

Add JMX support for native s3 filesystem

---

core/trino-main/src/main/java/io/trino/sql/planner/plan/AggregationNode.java

Fixes the `containsAll` check in `AggregationNode#producesDistinctRows` to be called on the `HashSet` instead of on the `List`.

Fix AggregationNode#producesDistinctRows check

---

docs/src/main/sphinx/connector/delta-lake.md
docs/src/main/sphinx/connector/hive.md
docs/src/main/sphinx/connector/hudi.md
docs/src/main/sphinx/connector/iceberg.md
docs/src/main/sphinx/object-storage.md
docs/src/main/sphinx/object-storage/file-system-azure.md
docs/src/main/sphinx/object-storage/file-system-gcs.md
docs/src/main/sphinx/object-storage/file-system-hdfs.md
docs/src/main/sphinx/object-storage/file-system-s3.md
docs/src/main/sphinx/object-storage/legacy-azure.md
docs/src/main/sphinx/object-storage/legacy-cos.md
docs/src/main/sphinx/object-storage/legacy-gcs.md
docs/src/main/sphinx/object-storage/legacy-s3.md

* Hadoop FS will now default to `false`.
* Removed "and deactivating all legacy support".
* Added a requirement to each object storage connector to state that selecting a filesystem is a requirement, and included example property. 
#23343

Docs changes for Hadoop FS default

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeJmx.java

Example failure https://github.com/trinodb/trino/actions/runs/10853271030/job/30121744630

Fix broken testJmxTablesExposedByDeltaLakeConnectorBackedByGlueMetastore

---

core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
core/trino-parser/src/main/java/io/trino/sql/tree/DropRole.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java

Fix round trip of DROP ROLE statement

Fix round trip of DROP ROLE statement

---

core/trino-main/src/test/java/io/trino/execution/TestDropColumnTask.java
core/trino-parser/src/main/java/io/trino/sql/tree/DropColumn.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java

Migrate assertStatement to ParserAssert + Remove redundant constructors from DropColumn

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java

Statistics without get prefix are not exposed.

Fix naming pattern for exposed statistics

---

client/trino-jdbc/pom.xml
docs/src/main/sphinx/client/jdbc.md
pom.xml

As agreed with @electrum and @wendigo 
fyi @gaeljw 
```markdown
* Remove publishing a JDBC driver JAR without bundled, third-party
dependencies. ({issue}`23452`)
```

Revert non-shaded jdbc driver

---

lib/trino-cache/pom.xml
lib/trino-cache/src/main/java/io/trino/cache/EvictableCache.java
lib/trino-cache/src/test/java/io/trino/cache/BenchmarkEvictableCache.java
lib/trino-cache/src/test/java/io/trino/cache/TestEvictableCache.java

Previously, dataCache.asMap().containsKey() reported false when cache entry was loaded for key, removing the token. Then after value was loaded, token didn't exist so next thread checking the cache had to regenerate the token itself, making cache less usable for long loading operations
Closes https://github.com/trinodb/trino/issues/23384

Fix race in EvictableCache#removeDangling

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java

For extra diagnostics visibility

Add nodeRequirements to BinPackingNodeLease toString

---

core/trino-main/src/main/java/io/trino/operator/output/SkewedPartitionRebalancer.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java

The rebalancing logic from SkewedPartitionRebalancer is already covered by partitions splitting/merging in HashDistributionSplitAssigner. Also the way remote SkewedPartitionRebalancer is configured does not match FTE behaviour as there is assumption that data will be consumed by N tasks where N is number of cluster nodes. This is not true for FTE.

Do not use SkewedPartitionRebalancer for remote exchange in FTE

---

client/trino-jdbc/pom.xml
client/trino-jdbc/src/main/java/io/trino/jdbc/NonRegisteringTrinoDriver.java
client/trino-jdbc/src/main/java/io/trino/jdbc/TracingTrinoDriver.java
client/trino-jdbc/src/test/java/io/trino/jdbc/JdbcDriverIT.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestTracingTrinoDriver.java

Fixes https://github.com/trinodb/trino/issues/21104 https://github.com/trinodb/trino/issues/21689 https://github.com/trinodb/trino/issues/18348 
Also related to #23452
```markdown
```

Do not shade opentelemetry in JDBC driver

---

docs/src/main/sphinx/connector/snowflake.md

I think we also need to add some of the other includes. I can add them in the PR but not sure which ones apply.
Typically this is what most of the JDBC connecters have:
```
{include} jdbc-common-configurations.fragment
{include} query-comment-format.fragment
{include} jdbc-domain-compaction-threshold.fragment
{include} jdbc-case-insensitive-matching.fragment
{include} non-transactional-insert.fragment
```
https://github.com/trinodb/trino/pull/23367
https://github.com/trinodb/trino/pull/23381

Add domain compaction to Snowflake docs

---

client/trino-jdbc/pom.xml
client/trino-jdbc/src/test/java/io/trino/jdbc/JdbcDriverIT.java

OkHttp is shaded which requires OkHttp instrumentation to be shaded too.
```markdown
```

Shade opentelemetry-okhttp-instrumentation

---

plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestingSqlServer.java

Same change as https://github.com/trinodb/trino/pull/23464
The example failure: https://github.com/trinodb/trino/actions/runs/10912509097/job/30287354222?pr=23471

Update SQL Server docker to 2017-latest

---

core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOidcDiscovery.java
core/trino-main/src/test/java/io/trino/server/security/oauth2/TestingHydraIdentityProvider.java
core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/util/TestingHttpServer.java
plugin/trino-example-http/src/test/java/io/trino/plugin/example/ExampleHttpServer.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestingThriftHttpMetastoreServer.java
plugin/trino-iceberg/src/test/java/org/apache/iceberg/rest/DelegatingRestSessionCatalog.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/PrometheusHttpServer.java
pom.xml
service/trino-proxy/src/main/java/io/trino/proxy/ProxyModule.java

Removes unused admin feature and servlet params.
```markdown
```

Update Airlift to 268

---

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemConfig.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemFactory.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemConfig.java

Max requests were increased from 5 to 2 * number of CPUs in
bd289dc4773baca88c94670f625538a4b98f8398 (#22561). With a very large number of
nodes in a cluster, this can cause throttling and result in failed
queries. Make it configurable allows to tune the value, if the default
one is too big.
This change also sets the max requests and max requests per host to the
same value, to limit the number of new configuration options.
Fixes #22915 
```markdown
* Allow configuring max requests in native FS for Azure. ({issue}`issuenumber`)
```

Make max requests configurable in Azure native FS

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeResult.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/delete/RoaringBitmapArray.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/RemoveFileEntry.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointBuilder.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointEntryIterator.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointWriter.java

Fixes #23229 
```markdown
* Fix incorrect results when writing deletion vectors. ({issue}`23229`)
```

Fix incorrect results when writing deletion vectors in Delta Lake

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowToPageConverter.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryColumnHandle.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPageSourceProvider.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPseudoColumn.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryQueryPageSource.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySessionProperties.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageAvroPageSource.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTypeManager.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadSessionCreator.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryAvroConnectorTest.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryMetadata.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQuerySplitManager.java

This PR implements dereference projection pushdown for BigQuery connector(similar to https://github.com/trinodb/trino/pull/17085).
This adds significant performance improvements for queries accessing nested fields inside struct/row columns. They have been optimized through the pushdown of dereference expressions. With this feature, the query execution prunes structural data eagerly, extracting the necessary fields.
I have a table having a nested field `root`. When perform selecting `root.f1`, we can see the difference in `Input` and `Physical Input` values in the query plan when running with and without dereference pushdown.
Table Schema as below:
```
trino:tpch> SHOW COLUMNS FROM test_projection_pushdown_f1xy74161o;
Column |           Type            | Extra | Comment …
```

Add projection push down for STRUCT field in big-query connector

---

core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java

Current `toConnectorSession` will lose catalog information, and cause exception if catalog uses any catalog properties.
With error message:
```
Unknown session property: null.session_property_name
```
```markdown
```

fix toConnectorSession conversion in BeginTableExecuteResult

---

plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java
plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/OpenSearchClient.java
plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/BaseOpenSearchConnectorTest.java

We've identified that when a COUNT(*) query was pushed down and contained special characters, the QueryBuilder string was being handled as ISO-8859-1 and causing parsing issues for Elasticsearch.
For example, this query:
```
SELECT COUNT(*) FROM catalog.default.users where country = 'Türkiye';
```
In case the "country" field is a keyword, would result in:
> {"error":{"root_cause":[{"type":"parsing_exception","reason":"Failed to parse","line":1,"col":53}],"type":"parsing_exception","reason":"Failed to parse","line":1,"col":53,"caused_by":{"type":"x_content_parse_exception","reason":"[1:53] [bool] failed to parse field [filter]","caused_by":{"type":"json_parse_exception","reason":"Invalid UTF-8 middle byte 0x73\n at [Source: (org.elasticsearch.common.io.stream.ByteBufferStreamInput); line: …

Fix encoding for Elasticsearch count pushdown

---

.github/workflows/ci.yml

The product tests job test step should have an ID used to check if it failed, so its test reports can be processed and annotations can be generated.

Fix annotating CI run when product tests fail

---

.github/workflows/ci.yml

Workaround for https://github.com/microsoft/mssql-docker/issues/899
```markdown
```

Switch Github runners to Ubuntu 20.04

---

client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
client/trino-cli/src/main/java/io/trino/cli/Console.java
client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java
client/trino-cli/src/main/java/io/trino/cli/Query.java
client/trino-cli/src/main/java/io/trino/cli/StatusPrinter.java
client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java
client/trino-cli/src/test/java/io/trino/cli/TestInsecureQueryRunner.java
client/trino-cli/src/test/java/io/trino/cli/TestQueryRunner.java
docs/src/main/sphinx/client/cli.md

The Trino CLI currently reports data size incorrectly, using the legacy, 1,024-based, values for K, M, G etc rather than the modern 1,000-based values.
Fix
CLI
This change corrects the display of data sizes in the CLI to use KiB, MiB for 1,024-based values and adds a command option, `--decimal-data-size` to display data sizes in 1,000-based units.
The CLI now shows data sizes and rates with binary …

Use correct abbreviations for data quantities. Fixes #13054

---

client/trino-cli/src/test/java/io/trino/cli/TestClientOptions.java
client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java

Fix incorrect assertions used

---

core/trino-main/src/main/java/io/trino/execution/buffer/SpoolingExchangeOutputBuffer.java
core/trino-main/src/main/java/io/trino/execution/buffer/SpoolingOutputStats.java

Makes `rowCount` final instead of a volatile `AtomicLong`, and avoids repeated atomic updates inside of `SpoolingExchangeOutputBuffer` in favor of a single final update outside of the loop.
```markdown
```

Cleanup SpoolingOutputStats

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/AdaptiveReorderPartitionedJoin.java
core/trino-main/src/main/java/io/trino/sql/planner/plan/ExchangeNode.java
core/trino-main/src/test/java/io/trino/sql/planner/assertions/ExchangeMatcher.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestAdaptiveReorderPartitionedJoin.java

Fix: https://github.com/trinodb/trino/issues/23407
```markdown
* Fix possible query failure when `retry_policy` is set to `TASK` and when adaptive join reordering is enabled . ({issue}`23407`)
```

Fix multiple sources build side in AdaptiveReorderPartitionedJoin

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Environment.java

When product tests fail, they produce an report, which is used to generate GitHub Actions annotations so it's easier to know the failure cause, without having to browse the failed job logs. Generate a similar annotation when the test environment fails to start, which is a common failure cause.
The original error is still produced, so it can be looked up in logs, for anyone that's used to doing it.

Generate a run annotation when test environment fails to start

---

docs/src/main/sphinx/object-storage/file-system-azure.md

see title 
Follow up to #22932

Add docs for azure.max-http-requests

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryCaseInsensitiveMapping.java

Right now `case-insensitive-cache` may contain only one value (in most cases) with `projectId` as key and names mapping as value. This causes cache to be build once and is never updated until it's invalidated. Also it's build with values available from one query only. It's not big problem for schema as for all queries we always supply cache from `client.listDatasetIds(projectId)`. 
For table it's buggy as some queries have limited information.
For example:
- select from single table will return only one list element with selected table from BigQuery, we will store only this table in cache mapping
- next select for another table will fetch mapping from cache and as new table is not present there it will return empty result
- empty result will cause table not found exception
This PR changes …

Fix BigQuery case-insensitive-cache

---

plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseTypeMapping.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java

- https://github.com/trinodb/trino/issues/9998
- https://github.com/trinodb/trino/pull/10000
```markdown
```

Test predicates pushdown to ClickHouse FLOAT type

---

plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java

ClickHouse collation is case-sensitive.
ClickHouse has same sort ordering as Trino.
Per https://clickhouse.com/docs/en/sql-reference/statements/show#show_columns
ClickHouse has no per-column collations
Clickhouse is UTF-8 encoded with byte-by-byte comparison.
https://clickhouse.com/docs/en/sql-reference/statements/select/order-by#collation-support
So exactly as trino.
https://github.com/airlift/slice/blob/2.2/src/main/java/io/airlift/slice/Slice.java#L1205
That’s why all operations on varchars may pushdown.
Addresses
- https://github.com/trinodb/trino/pull/22921#discussion_r1764535634
Extracted from
- https://github.com/trinodb/trino/pull/23460
( ) Release notes are required. Please propose a release note for …

Unconditionally pushdown varchar predicate to Clickhouse

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveDistributedAggregations.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java

Fix for cannot cast `SystemTableHandle` to `ConnectorTableHandle` in allowSplittingReadIntoMultipleSubQueries.

Fix for SystemTables in allowSplittingReadIntoMultipleSubQueries

---

docs/src/main/sphinx/connector/delta-lake.md
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/cache/DeltaLakeCacheKeyProvider.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeAlluxioCacheTestUtils.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheFileOperations.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheMutableTransactionLog.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java

Added a configuration option to disable object caching of files with /_delta_log/ in their path to avoid issues with Delta tables with mutable commits. This is useful in those scenarios when delta tables are deleted and re-created and the files inside the _delta_log folder cannot be considered immutable anymore, and thus are unsafe to cache.
Fixes [#21451](https://github.com/trinodb/trino/issues/21451)
```
* Add a configuration `delta.fs.cache.disable-transaction-log-caching` to allow disabling caching of delta transaction logs when filesystem caching is enabled. …
```

Add option to disable filesystem caching of /_delta_log/ directory

---

core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java
testing/trino-testing/src/main/java/io/trino/testing/LocalSpoolingManager.java
testing/trino-tests/src/test/java/io/trino/tests/tpch/TpchQueryRunner.java

Improve spooling performance and memory accounting

---

.github/actions/process-test-results/action.yml
.github/workflows/upload-test-results.yml

Upload CI test results to S3, so we can create reports aggregating most commont failure causes in https://github.com/trinodb/reports.
This will require setting up new vars and secrets with the S3 bucket name and credentials. We can reuse the same bucket where we already copy GHA REST API data scraped in https://github.com/trinodb/reports.

Upload CI test results to S3

---

docs/src/main/sphinx/connector/hive.md

In the Hive connector
Replacement for https://github.com/trinodb/trino/pull/22956 

Add docs for Hudi table redirection

---

core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
core/trino-main/src/main/java/io/trino/testing/PlanTester.java
core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java

`CALL` syntax allows `ConnectorAccessControl` in procedures, but `ALTER TABLE ... EXECUTE` syntax doesn't support it. This PR updates `ConnectorMetadata.getTableHandleForExecute` method so that developers can use the access control in their table procedures. Injecting the interface doesn't work well when system security is used. 
```markdown
* Add `ConnectorAccessControl` argument to `ConnectorMetadata.getTableHandleForExecute` method. ({issue}`23524`)
```

Add ConnectorAccessControl to ConnectorMetadata.getTableHandleForExecute

---

lib/trino-filesystem-azure/pom.xml
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureLocation.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureLocation.java
lib/trino-filesystem-manager/src/main/java/io/trino/filesystem/manager/FileSystemModule.java

Add support for WASB to native Azure file system implementation.  WASB urls can be supported by simply modifying the Azure location parsing code as the underlying Azure storage APIs are set by the storage account type.  The main difference to a ABFS url is the scheme is `wasb` and the `blob` endpoint is referenced instead of `dfs`.
Fixes #23511
```markdown
* Add support for WASB to native Azure file system implementation. ({issue}`23511`)
```

Add support for WASB to native Azure file system implementation

---

docs/src/main/sphinx/release/release-453.md

The issue link should be https://github.com/trinodb/trino/pull/22717

Fix wrong issue number in 453 release note

---

lib/trino-filesystem-s3/pom.xml
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystem.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3InputFile.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3OutputFile.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3OutputStream.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3SseCUtils.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/AbstractTestS3FileSystem.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemAwsS3WithEncryption.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemLocalStackWithEncryption.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoFileSystem.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/encryption/EncryptionEnforcingFileSystem.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/encryption/EncryptionKey.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/switching/SwitchingFileSystem.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/tracing/TracingFileSystem.java
lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java

Add support for server-side encryption with customer key to S3

---

core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java

It moves check from Metadata to MetadataManager as it could potentially cause problem for other connectors with DistinctAggregationStrategyChooser when accessing SystemTables.

Alter allowSplittingReadIntoMultipleSubQueries check for systemTables

---

core/trino-main/src/main/java/io/trino/server/ui/MultipartUiCookie.java
core/trino-main/src/main/java/io/trino/server/ui/OAuthIdTokenCookie.java
core/trino-main/src/main/java/io/trino/server/ui/OAuthWebUiCookie.java

Use upper bounded wildcard to read and delete cookie. It will help to use same api to read and delete `NewCookie`.

Use upper bounded wildcard to read and delete cookie

---

core/trino-main/src/main/java/io/trino/sql/ir/optimizer/rule/SimplifyContinuousInValues.java
core/trino-main/src/main/java/io/trino/util/FastutilSetHelper.java
core/trino-main/src/test/java/io/trino/sql/gen/BenchmarkDynamicPageFilter.java
core/trino-main/src/test/java/io/trino/sql/gen/TestBenchmarkDynamicPageFilter.java
core/trino-main/src/test/java/io/trino/sql/gen/TestColumnarFilters.java
core/trino-main/src/test/java/io/trino/sql/gen/TestDynamicPageFilter.java
core/trino-main/src/test/java/io/trino/util/DynamicFiltersTestUtil.java
core/trino-main/src/test/java/io/trino/util/TestFastutilSetHelper.java

Use a bitset based filter instead of a hash set when the range of
values is narrow enough. We use bitset only when it would occupy
lesser space than the equivalent open hash set.
This is useful for making evaluation of dynamic filter more efficient
as we often collect large integer sets in dynamic filters.
```
BenchmarkDynamicPageFilter.filterPages
(filterSize)   (inputDataSet)  (nonNullsSelectivity)   Mode  Cnt  Before score      After score
100  INT64_FIXED_32K                    0.2  thrpt   30  446.174 ? 10.598   449.113 ?  5.323 ops/s
1000  INT64_FIXED_32K                    0.2  thrpt   30  407.625 ?  3.139  1379.767 ? 19.318 ops/s
5000  INT64_FIXED_32K                    0.2  thrpt   30  426.413 ?  6.485  1254.731 ? 11.685 ops/s
```
(x) This is not user-visible or is docs only, and …

Optimize large IN filters on integer data types

---

core/trino-main/src/main/java/io/trino/operator/aggregation/ApproximateDoublePercentileAggregations.java
core/trino-main/src/main/java/io/trino/operator/aggregation/ApproximateDoublePercentileArrayAggregations.java
core/trino-main/src/main/java/io/trino/operator/aggregation/ApproximateLongPercentileAggregations.java
core/trino-main/src/main/java/io/trino/operator/aggregation/LegacyApproximateLongPercentileAggregations.java
core/trino-main/src/main/java/io/trino/operator/scalar/ArrayCombinationsFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/ArrayTrimFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/QuantileDigestFunctions.java
core/trino-main/src/main/java/io/trino/operator/scalar/TDigestFunctions.java
core/trino-main/src/main/java/io/trino/type/DecimalCasts.java
core/trino-main/src/main/java/io/trino/util/Failures.java
core/trino-main/src/test/java/io/trino/operator/aggregation/AggregationTestUtils.java
core/trino-main/src/test/java/io/trino/operator/aggregation/TestApproximatePercentileAggregation.java

Ensure that approx_percentile performs explicit input validation and throw TrinoException with proper error code.
Relates to https://github.com/trinodb/trino/issues/11156
```markdown
* Improve error reporting on input validation for `approx_percentile` function ({issue}`23546`)
```

Improve input validation for approx_percentile

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java

Add logging for get-functions failure in glue metastore

---

docs/src/main/sphinx/object-storage/file-system-azure.md
docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-459.md

Assemble the release notes for the upcoming Trino 459 release.
Also see https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A459
* #23475 ✅ rn ✅ docs
* #23476 ✅ rn ✅ docs
* #23478 ✅ rn ✅ docs
* #22932 ✅ rn ✅ docs
* #23231 ✅ rn ✅ docs
* #23482 ✅ rn ✅ docs
* #23443 ✅ rn ✅ docs
* #23472 ✅ rn ✅ docs
* #23487 ✅ rn ✅ docs
* #23469 ✅ rn ✅ docs
* #23425 ✅ rn ✅ docs
* #23499 ✅ rn ✅ docs
* #23494 ✅ rn ✅ docs
* #23504 ✅ rn ✅ docs
* #23506 ✅ rn ✅ …

Add Trino 459 release notes

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteCompatibility.java
testing/trino-test-jdbc-compatibility-old-server/src/test/java/io/trino/TestJdbcResultSetCompatibilityOldServer.java

Skip release 456 in compatibility checks

---

plugin/trino-clickhouse/pom.xml
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/expression/RewriteStringComparison.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseTypeMapping.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java

- https://github.com/trinodb/trino/issues/7100
- https://github.com/trinodb/trino/pull/22921
- https://github.com/trinodb/trino/pull/23496
- https://github.com/trinodb/trino/pull/23516
- https://github.com/trinodb/trino/pull/23455
- https://github.com/trinodb/trino/pull/23558
- https://github.com/trinodb/trino/pull/23459
```markdown
* Improve varchar comparison pushdown for complex expression ({issue}`23558`)
```

Support Clickhouse varchar comparison pushdown

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/AbstractRewriteCast.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcCastPushdownTest.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/CastDataTypeTestTable.java
plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/RewriteCast.java
plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleCastPushdownTest.java
plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleCastPushdown.java

This PR adds support for cast projection pushdown for the Oracle connector. This uses the framework introduced in https://github.com/trinodb/trino/pull/22203 for cast projection pushdown.
Currently, this PR only adds support for the `CHAR` and `VARCHAR` cast pushdown, which has the following limitations:
1. Pushdown is not supported with `Char` having length > 500
2. Pushdown is not supported with `Varchar` having length > 1000
3. Pushdown is not supported with unbounded varchar
4. Pushdown is not supported with `Char` cast to bounded `Varchar`
```markdown
* Add support for cast project pushdown with Char and Varchar data type. ({issue}`22728`

Support cast projection pushdown in oracle

---

client/trino-client/src/main/java/io/trino/client/spooling/encoding/CompressedQueryDataDecoder.java
client/trino-client/src/main/java/io/trino/client/spooling/encoding/JsonQueryDataDecoder.java
client/trino-client/src/main/java/io/trino/client/spooling/encoding/Lz4QueryDataDecoder.java
client/trino-client/src/main/java/io/trino/client/spooling/encoding/ZstdQueryDataDecoder.java
client/trino-jdbc/src/main/java/io/trino/jdbc/AbstractTrinoResultSet.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/encoding/Lz4QueryDataEncoder.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/encoding/ZstdQueryDataEncoder.java

This improves JDBC client throughput a bit.
Benchmarked using simple tool: https://github.com/wendigo/trino-jdbc-benchmark
Before:
```
Average time for 10 runs: 14371ms
```
After:
```
Average time for 10 runs: 13003ms
```

Client cleanup / improvements

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Environment.java

Right now it gets printed with the prefixes, and it doesn't create any annotations:
```
2024-09-26T11:11:42.821Z	INFO	main	io.trino.tests.product.launcher.env.Environment	::error title=Failed to start environment 'singlenode-compatibility'::org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=trinodb/trino:459, imagePullPolicy=io.trino.testing.containers.ConditionalPullPolicy@19b02dfd, imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@3dce6dd8)
2024-09-26T11:11:42.821Z	INFO	main	io.trino.tests.product.launcher.env.Environment	Environment 'singlenode-compatibility' failed to start in attempt(s): 6: 
```
from https://github.com/trinodb/trino/actions/runs/11050681149/job/30699574020
(x) …

Print GitHub errors without logging prefixes

---

testing/trino-server-dev/etc/catalog/cassandra.properties
testing/trino-server-dev/etc/catalog/hive.properties
testing/trino-server-dev/etc/catalog/iceberg.properties

These names were no longer correct
<details>
<summary>Click me</summary>
Caused by: java.lang.IllegalArgumentException: No environment with name 'singlenode'. Those do exist, however: [multinode, multinode-all-connectors, multinode-azure, multinode-cassandra, multinode-clickhouse, multinode-confluent-kafka, multinode-databricks-http-hms, multinode-exasol, multinode-gcs, multinode-hive-caching, multinode-iceberg-minio-caching, multinode-ignite, multinode-kafka, multinode-kafka-sasl-plaintext, multinode-kafka-ssl, multinode-kerberos-kudu, multinode-mariadb, multinode-minio-data-lake, multinode-minio-data-lake-caching, multinode-minio-data-lake-task-retries-filesystem, multinode-mysql, multinode-parquet, multinode-phoenix5, multinode-postgresql, multinode-postgresql-spooling, …

Fix environment name in dev server config

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectionAccesses.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectionCreation.java
plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMetadata.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestCredentialPassthrough.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlJdbcConnectionAccesses.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlJdbcConnectionCreation.java
plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClientModule.java
plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerConnectionFactoryModule.java
plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerPlugin.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerJdbcConnectionAccesses.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerJdbcConnectionCreation.java

Before this change table metadata was fetched when listing columns which
ended up fetching table properties for JDBC connectors which incurs I/O
in connectors which support them.
```markdown
* Improve performance of listing columns. ({issue}`23429`)
```

Optimize column listing to not require fetching table properties

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java

Currently, when `iceberg.glue.cache-table-metadata` is set to true, columns and table comment are either stored together in Glue or none of them is stored.
The goal of this change is to prevent `TrinoGlueCatalog` from not caching table columns in glue when table comment is too long. It seems wrong that a decision to cache columns depends on the length of the table comment.
This commit changes that and makes storing them in Glue independent from each other. 
Decouple storing columns definition from storing table comments in glue
```markdown …
```

Decouple caching columns from caching table comments in glue for Iceberg

---

lib/trino-filesystem-alluxio/pom.xml
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileIterator.java
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileSystem.java
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileSystemFactory.java
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileSystemInput.java
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileSystemInputFile.java
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileSystemModule.java
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileSystemOutputFile.java
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioTrinoInputStream.java
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioTrinoOutputStream.java
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioUtils.java
lib/trino-filesystem-alluxio/src/test/java/io/trino/filesystem/alluxio/AbstractTestAlluxioFileSystem.java
lib/trino-filesystem-alluxio/src/test/java/io/trino/filesystem/alluxio/TestAlluxioFileSystem.java
lib/trino-filesystem-alluxio/src/test/java/io/trino/filesystem/alluxio/TestAlluxioUtils.java
lib/trino-filesystem-manager/pom.xml
lib/trino-filesystem-manager/src/main/java/io/trino/filesystem/manager/FileSystemConfig.java
lib/trino-filesystem-manager/src/main/java/io/trino/filesystem/manager/FileSystemModule.java
lib/trino-filesystem-manager/src/test/java/io/trino/filesystem/manager/TestFileSystemConfig.java
pom.xml

Add `trino-filesystem-alluxio` module to implement the new interfaces (`TrinoFileSystem`, `TrinoInput`, `TrinoInputFile`, `TrinoOutputFile` ) and support native Alluxio. 
Docs in https://github.com/trinodb/trino/pull/23269

Add Alluxio file system

---

docs/src/main/sphinx/object-storage.md
docs/src/main/sphinx/object-storage/file-system-alluxio.md

Add docs for Alluxio file system.
Docs for https://github.com/trinodb/trino/pull/21603

Add docs for Alluxio file system

---

.github/DEVELOPMENT.md

* Migrate some info to website since it applies to other subprojects.
* Fix release process docsDetails in commit messages. 
trino.io PR - https://github.com/trinodb/trino.io/pull/702

Update dev docs

---

lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileIterator.java
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileSystem.java
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioUtils.java
lib/trino-filesystem-alluxio/src/test/java/io/trino/filesystem/alluxio/TestAlluxioUtils.java

Minor cleanup in AlluxioUtils and TestAlluxioUtils

Minor cleanup in AlluxioUtils and TestAlluxioUtils

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergUtil.java

Should fix https://github.com/trinodb/trino/issues/23451
Loading the only required fields in the map.
```markdown
* Fix Iceberg queries stuck in the planning phase for long time when there are large number of fields in the table. ({issue}`23451`)
```

Load only required projected columns in Iceberg connector

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceProvider.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplit.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveSplit.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/Schema.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/AvroPageSourceFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/line/LinePageSourceFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/rcfile/RcFilePageSourceFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/InternalHiveSplitFactory.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveSplit.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveSplitSource.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestNodeLocalDynamicSplitPruning.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestOrcPageSourceMemoryTracking.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPageSourceFactory.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPredicates.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/ParquetUtil.java

Extract the required properties for ORC, Parquet and RCFile into explicit fields and use a Map only when necessary.
This avoids repeated look-ups in schema Map and reduces size of HiveSplit for the more common cases.
```markdown
```

Simplify schema field in HiveSplit for ORC, Parquet and RCFile tables

---

lib/trino-filesystem/src/main/java/io/trino/filesystem/cache/DefaultCacheKeyProvider.java
lib/trino-filesystem/src/test/java/io/trino/filesystem/cache/TestCacheFileSystemAccessOperations.java

Fixes https://github.com/trinodb/trino/issues/22861
In case file is updated in the same millisecond cache key may collide. Adding length to key computation reduce chance of this collision.
It also caused flakiness of `TestHiveAlluxioCacheFileOperations.testCacheFileOperations` with about 10% rate, after this change it passed 20 times in row.
```markdown
```

Add length to file cache key to reduce collision possibility

---

.github/actions/setup/action.yml
.github/workflows/ci.yml
.gitignore
.mvn/maven.config
core/trino-web-ui/pom.xml

Cache NodeJS in GHA

---

lib/trino-parquet/src/main/java/io/trino/parquet/writer/ColumnWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/BloomFilterValuesWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/TrinoValuesWriterFactory.java
lib/trino-parquet/src/test/java/io/trino/parquet/writer/AbstractColumnWriterBenchmark.java
lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestColumnWriterBenchmark.java
lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestTrinoValuesWriterFactory.java
testing/trino-testing/src/main/java/io/trino/testing/BaseTestParquetWithBloomFilters.java

Current logic was failing to convert dictionary pages into bloom filter
when the fallback from dictionary to plain encoding happened after first page.
Bloom filter writing logic is changed to always collect a bloom filter and
discard it at the end if only dictionary encoded pages are present. This avoids
the need to depend on values writer fallback mechanism.
Fixes https://github.com/trinodb/trino/issues/22701
```markdown
* Fix writing of bloom filter columns in parquet files. ({issue}`22701`)
```

Fix writing of parquet bloom filters

---

docs/src/main/sphinx/object-storage/legacy-s3.md

The migration guide is not easy to find, but I'm not sure where to link it. It's only mentioned in the 458 release notes, and users have to browse release notes of multiple versions to find it.

Clarify the s3.endpoint is an URL in migration guide

---

.github/workflows/ci.yml
docs/src/main/sphinx/connector/delta-lake.md
testing/trino-product-tests-groups/src/main/java/io/trino/tests/product/TestGroups.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeDatabricks143.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeDatabricks154.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLakeDatabricks143.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLakeDatabricks154.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCaseInsensitiveMapping.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeChangeDataFeedCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCheckpointsCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCreateTableAsSelectCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeIdentityColumnCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeInsertCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeSelectCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DatabricksVersion.java

Add support for Databricks runtime 14.3 & 15.4 LTS

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java

Compaction of domain before pushdown into iceberg is unnecessary and potentially hinders pruning of metadata
Fixes https://github.com/trinodb/trino/issues/9743
```markdown
```

Remove domain compaction from iceberg split source

---

plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/expression/RewriteLike.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java

This PR improves ClickHouse LIKE pushdown for complex expressions in Trino. 
LIKE with ESCAPE is out of scope of this PR.
Trino syntax for LIKE without ESCAPE does not support escape characters.
However Clickhouse supports escape with \ is for escaping literals %, _ and \.
When Trino LIKE pattern contains '\' do not pushdown the expression to Clickhouse.
- https://github.com/trinodb/trino/issues/7100
- https://github.com/trinodb/trino/pull/23460
- https://github.com/trinodb/trino/pull/22921
- https://github.com/trinodb/trino/pull/23496
- https://github.com/trinodb/trino/pull/23516
- https://github.com/trinodb/trino/pull/23455
- https://github.com/trinodb/trino/pull/23558
- https://github.com/trinodb/trino/pull/23581
- https://github.com/trinodb/trino/pull/23591
- …

Improve ClickHouse LIKE pushdown for complex expression

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java

Add missing `changeDataFeed` writer feature when table version supports reader/writer features in Delta Lake

---

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureLocation.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureLocation.java
lib/trino-filesystem-manager/src/main/java/io/trino/filesystem/manager/FileSystemModule.java

As a follow up to https://github.com/trinodb/trino/pull/23535, this PR adds the `wasbs` scheme as an alias for the Azure native file system implementation as recommended [here](https://github.com/trinodb/trino/pull/23535#pullrequestreview-2323115868).
The `s` in `wasbs` implies that TLS will be used, similar to abfss or https.  The code will function the same if a path uses `wasb` or `wasbs` since it will still leverage the Azure Data Lake Storage Gen2 REST APIs
```markdown
```

Add support for WASBS to native Azure file system implementation

---

docs/src/main/sphinx/admin/resource-groups.md

* Adds `MERGE` and `ALTER_TABLE_EXECUTE` to list of queryType options for resource group selector rules.
* https://github.com/trinodb/trino/blob/460beff1f72c3056035f820e047d23c96fb90915/core/trino-spi/src/main/java/io/trino/spi/resourcegroups/QueryType.java#L16
```markdown
```

Update queryType list in selector rules docs

---

lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystem.java

This should make batch delete way faster as it won't resolve blob metadata.
```markdown
```

Do not retrieve Blob metadata on batch delete

---

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java

This PR is to fix the [issue][1]. Whenever a empty collection was created an entry was populated in default collection `_schema`.  Further upon populating the collection with documents the fields in `_schema` remained empty. So a workaround there is a check introduced to avoid populating `_schema` if collection is empty.
Fixes #20972

Avoid populating _schema if the collection is empty in MongoDB connector

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java

Error when deleting S3 files should be catagorized as file system error for accounting purposes.
Stack trace:
```
{
"type": "io.trino.spi.TrinoException",
"message": "Failure when vacuuming <table> with retention 7d: java.io.IOException: Exception while batch deleting paths",
"cause": {
"type": "java.lang.RuntimeException",
"message": "Failure when vacuuming <table> with retention 7d: java.io.IOException: Exception while batch deleting paths",
"cause": {
"type": "java.io.IOException",
"message": "Exception while batch deleting paths",
"cause": {
"type": "com.amazonaws.services.s3.model.MultiObjectDeleteException",
"message": "One or more objects could not be deleted (Service: null; Status Code: 200; Error Code: null; Request ID: <request_id>; S3 Extended Request ID: <request_id> ; Proxy: …
```

Handle Delta Lake vacuum file system error

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java

Store metadata when listing columns/comments in Delta Lake

Store metadata when listing columns/comments in Delta Lake

---

plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/FileSystemSegmentPruner.java
plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/FileSystemSpooledSegmentHandle.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/TestFileSystemSegmentPruner.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/TestFileSystemSpooledSegmentHandle.java

Spooling pruning tests

---

core/trino-main/src/main/java/io/trino/sql/planner/SymbolsExtractor.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestInlineProjections.java

```
* Fix query failures when complex symbols are referenced from within lambda expression. ({issue}`issuenumber`)
```

Extract outer symbols from lambda expressions

---

core/trino-spi/src/main/java/io/trino/spi/security/ConnectorIdentity.java

Remove constructors and methods that were deprecated for 3y+.

Remove deprecated constructs from ConnectorIdentity

---

plugin/trino-password-authenticators/src/main/java/io/trino/plugin/password/file/EncryptionUtil.java
plugin/trino-password-authenticators/src/test/java/io/trino/plugin/password/file/TestEncryptionUtil.java

Fixes https://github.com/trinodb/trino/issues/23648
```markdown
* Add support for BCrypt 2A, 2B, 2X versions ({issue}`issuenumber`)
```

Add support for more BCrypt versions

---

client/trino-client/src/main/java/io/trino/client/spooling/EncodedQueryData.java
client/trino-client/src/main/java/io/trino/client/spooling/encoding/CompressedQueryDataDecoder.java
client/trino-client/src/main/java/io/trino/client/spooling/encoding/JsonQueryDataAccess.java
client/trino-client/src/main/java/io/trino/client/spooling/encoding/Lz4QueryDataDecoder.java
client/trino-client/src/main/java/io/trino/client/spooling/encoding/ZstdQueryDataDecoder.java
client/trino-client/src/test/java/io/trino/client/spooling/encoding/TestCompressedQueryDataDecoder.java

Properly close input streams while decoding spooled data

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeKafkaSaslPlaintext.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeKerberosKudu.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodePhoenix5.java
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-kafka-sasl-plaintext/jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-kerberos-kudu/jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-phoenix5/jvm.config

Restore security manager allowance

---

pom.xml

Airbase brings compatibility with JDK 24 due to updated ASM.
```markdown
```

Update airbase, airlift, parquet and AWS SDK v2

---

core/trino-main/src/main/java/io/trino/FeaturesConfig.java
core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
core/trino-main/src/main/java/io/trino/execution/resourcegroups/IndexedPriorityQueue.java
core/trino-main/src/main/java/io/trino/execution/scheduler/NodeSchedulerConfig.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/ArbitraryDistributionSplitAssigner.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenTaskSourceFactory.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/HashDistributionSplitAssigner.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/NodeAllocator.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/NodeRequirements.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/SingleDistributionSplitAssigner.java
core/trino-main/src/main/java/io/trino/memory/MemoryManagerConfig.java
core/trino-main/src/test/java/io/trino/execution/TestNodeSchedulerConfig.java
core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
core/trino-main/src/test/java/io/trino/execution/resourcegroups/TestUpdateablePriorityQueue.java
core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/BenchmarkBinPackingNodeAllocator.java
core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestArbitraryDistributionSplitAssigner.java
core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestBinPackingNodeAllocator.java
core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestEventDrivenTaskSource.java
core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestHashDistributionSplitAssigner.java
core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestSingleDistributionSplitAssigner.java
core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestTaskDescriptorStorage.java
core/trino-main/src/test/java/io/trino/memory/TestMemoryManagerConfig.java
core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
docs/src/main/sphinx/admin/fault-tolerant-execution.md

Includes https://github.com/trinodb/trino/pull/23585
```markdown
```

FTE task scheduling improvements

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/PredicatePushdownController.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorTest.java

Redshift performs better for IN clause queries compared to range queries. PR aims to change the range queries to IN clause where applicable for the possible performance improvement.
```markdown
* Improve performance of queries with range filters on integers. ({issue}`23417`)
```

Convert range predicates to discrete set in Redshift

---

core/trino-main/src/main/java/io/trino/server/protocol/Query.java
core/trino-main/src/test/java/io/trino/block/TestDictionaryBlock.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/Page.java
core/trino-spi/src/main/java/io/trino/spi/block/ArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/Block.java
core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/MapBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/RunLengthEncodedBlock.java
core/trino-spi/src/test/java/io/trino/spi/TestPage.java
lib/trino-orc/src/main/java/io/trino/orc/OrcWriter.java
lib/trino-orc/src/main/java/io/trino/orc/writer/SliceDictionaryColumnWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java

This was only used in a few places, and was not implement correctly in several container block implementations.
```markdown
* Remove `Block.getLogicalSizeInBytes`. ({issue}`23688`)
```

Remove unnecessary Block getLogicalSizeInBytes

---

.github/workflows/upload-test-results.yml

To be able to process the TestNG reports uploaded to S3, when converting them to JSON, dashes in keys needs to be converted to underscores. Additionally, ensure all arrays with one item don't get converted to objects.
Tested manually.

Normalize TestNG reports uploaded to S3 as JSON

---

docs/src/main/sphinx/installation/kubernetes.md

Update the instructions to match changes done in the Trino Helm chart over the last few months. Related chart pull requests:
* https://github.com/trinodb/charts/pull/172
* https://github.com/trinodb/charts/pull/228

Update Kubernetes installation instructions

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveStorageFormat.java

As brought up in https://github.com/trinodb/trino/issues/21842, I am unable to query text based hive tables that use `org.apache.hadoop.mapred.lib.CombineTextInputFormat`. I get this error:
```
io.trino.spi.TrinoException: Unsupported storage format: mydatabase.mytable:<UNPARTITIONED> StorageFormat{serde=org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe, inputFormat=org.apache.hadoop.mapred.lib.CombineTextInputFormat, outputFormat=org.apache.hadoop.hive.ql.io.HiveIgnoreKeyTextOutputFormat}
```
This change was the suggestion from the linked issue. To test this out I tried to query with Trino 453 without the code change, and I get this error on the CLI:
```
$ ./trino https://localhost:8443 --catalog hive
trino> select count(*) from <my hive table>;
Query 20240819_203410_00002_cg577 failed: …
```

Add support for CombineTextInputFormat from Hive

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TypeConverter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/procedure/TestIcebergMigrateProcedure.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java

Fixes https://github.com/trinodb/trino/issues/17006
Hive:
It occurs that Hive takes the timestamp and adjust the timestamp to get UTC value according to the writer's TZ. It saves the timestamp in UTC and adds also the writer TZ info to the footer.
During read, it reads the timestamp in UTC and adjust it according to the writer's TZ.
Trino uses the following property hive.parquet.time-zone for setting Parquet reader's and Parquet writer's timezone when dealing with Hive.
Iceberg:
Trino always sets the UTC timezone for Parquet reader's and Parquet writer's timezone.
In this way, it always return UTC values.
The introduced change:
- For Orc the timestamp without timezone will be map as timestamp without timezone.
- For Parquet the timestamp without the timezone will be map to timestamp with …

Support timestamp type in Iceberg migrate procedure

---

docs/src/main/sphinx/object-storage/file-system-azure.md

For https://github.com/trinodb/trino/issues/23538
```markdown
```

Document accessing multiple azure storage accounts in single catalog

---

plugin/trino-bigquery/pom.xml
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryCaseInsensitiveMapping.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryCaseInsensitiveMapping.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryCaseInsensitiveMappingWithCache.java

When cache is disabled, all values put into cache are not persisted, causing cache-insensitive mapping failing
This PR decouples mapping from cache handling
```markdown
* Fix failure when `bigquery.case-insensitive-name-matching` is enabled and 
`bigquery.case-insensitive-name-matching.cache-ttl` is `0m`. ({issue}`23698`)
```

Fix BigQuery case-insensitive mapping when cache is disabled

---

docs/src/main/sphinx/connector/iceberg.md

Reword some aspects to make it more precise and ensure that it is clear that the catalog and system schema must be specified.
Feel free to also chime in @findinpath @raunaqmorarka @mayankvadariya @SemionPar and others from the original code PR. 
Follow up to docs from #22751

Improve docs for add file procedures in Iceberg

---

core/trino-main/src/main/java/io/trino/sql/gen/JoinCompiler.java

Move the code for calculating the retained size to a separate method implemented as a loop, instead of unrolling the calls.
Relates to https://github.com/trinodb/trino/issues/15848
```
* Fix failure when joining tables with large numbers of columns. ({issue}`23720`)
```

Reduce size of generated PagesHashStrategy constructor

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/RegisterTableProcedure.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergRegisterTableProcedure.java

This procedure is very similar to `CREATE TABLE`. We should call `AccessControl#checkCanCreateTable` in the procedure. 
```markdown
* Enforce access control for new tables in the `register_table` procedure. ({issue}`23728`)
```

Check permission when registering tables in Iceberg and Delta Lake

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrationUtils.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/procedure/TestIcebergAddFilesProcedure.java

Relates to #23677
Still disllowing the following situation:
* Partition column doesn't exist
* All source columns don't exist in the target table
* Source table has more columns than target table
* Probably, this can be allowed in the future after updating `MigrationUtils#loadMetrics` implementation

Tweak validation of missing data columns in Iceberg `add_files_from_table` procedure

---

core/trino-main/src/main/java/io/trino/sql/gen/BytecodeGeneratorContext.java
core/trino-main/src/main/java/io/trino/sql/gen/CursorProcessorCompiler.java
core/trino-main/src/main/java/io/trino/sql/gen/JoinFilterFunctionCompiler.java
core/trino-main/src/main/java/io/trino/sql/gen/LambdaBytecodeGenerator.java
core/trino-main/src/main/java/io/trino/sql/gen/PageFunctionCompiler.java
core/trino-main/src/main/java/io/trino/sql/gen/RowConstructorCodeGenerator.java
core/trino-main/src/main/java/io/trino/sql/gen/RowExpressionCompiler.java
core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineCompiler.java

Split the processing of fields into batches to reduce the size of a single generated method. This makes it possible to call ROW(...) with a large number of fields.
Relates to https://github.com/trinodb/trino/issues/15848
```markdown
* Fix failure for MERGE queries on tables with large numbers of columns. ({issue}`15848`)
```

Split construction of large rows into separate methods

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-461.md

Assemble the release notes for the upcoming Trino 461 release.
See https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A461
* #23668 ✅ rn ✅ docs
* #23672 ✅ rn ✅ docs
* #23670 ✅ rn ✅ docs
* #23594 ✅ rn ✅ docs
* #22751 ✅ rn ❌  docs (mosabua to review/edit)
* #23663 ✅ rn ✅ docs
* #23665 ✅ rn ✅ docs
* #23676 ✅ rn ✅ docs
* #23585 ✅ rn ✅ docs
* #23675 ✅ rn ✅ docs
* #23679 ✅ rn ✅ docs
* #23681 ✅ rn ✅ docs
* #23680 ✅ rn ✅ docs
* #23671 ✅ rn ✅ …

Add Trino 461 release notes

---

core/trino-web-ui/src/main/resources/webapp/assets/trino.css

In the query list to be the same height as the overview/stats display.
Before
After
Fixes #23746
The change it too minor .. users probably didnt notice the issue in the first place

Adjust height of query display box

---

core/trino-main/src/main/java/io/trino/testing/DirectTrinoClient.java
core/trino-main/src/main/java/io/trino/testing/StandaloneQueryRunner.java
core/trino-main/src/main/java/io/trino/testing/TestingDirectTrinoClient.java
testing/trino-tests/src/test/java/io/trino/tests/TestLocalQueries.java

The goal is to split query execution from the test code (results materialization).
The first commit fixes a bug that caused `DirectTrinoClient ` to hang indefinitely for queries that do not produce output.
```markdown
```

Extract TestingDirectTrinoClient

---

client/trino-client/src/main/java/io/trino/client/JsonResultRows.java
client/trino-client/src/main/java/io/trino/client/RawQueryData.java
client/trino-client/src/main/java/io/trino/client/ResultRows.java
client/trino-client/src/main/java/io/trino/client/StatementClient.java
client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestAsyncResultIterator.java
core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
core/trino-main/src/main/java/io/trino/util/FastutilSetHelper.java
lib/trino-orc/src/main/java/io/trino/orc/reader/MapColumnReader.java
pom.xml

Ban @Nonnull and @NotNull annotations + cleanup

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsReader.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAlluxioCacheFileOperations.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergFileOperations.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMemoryCacheFileOperations.java

For large tables going through statistics for all files can be slow.
The calling code in getStatisticsCollectionMetadataForWrite was not
using all the statistics and is simplified to only fetch NDVs.
```markdown
* Improve planning time for iceberg inserts. ({issue}`23757`)
```

Avoid reading min/max/null statistics for planning iceberg inserts

---

core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpooledBlock.java
core/trino-main/src/test/java/io/trino/server/protocol/spooling/TestSpooledBlock.java

Found in the https://github.com/trinodb/trino/pull/23768
The test was creating a Page that had two blocks with uneven number of positions (which is incorrect).
```markdown
```

Fix test and move it to proper package

---

docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/IcebergRestCatalogConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergUnityRestCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/UnityCatalogContainer.java

This PR supports only read operations because Iceberg REST interface in Unity catalog doesn't support creating tables yet. 
Note that Databricks Unity catalog provides HTTP interface, but it doesn’t return Iceberg UniForm tables. 
Example catalog config properties:
```properties
connector.name=iceberg
iceberg.catalog.type=rest
iceberg.rest-catalog.uri=https://dbc-12345678-9999.cloud.databricks.com/api/2.1/unity-catalog/iceberg
iceberg.security=read_only
iceberg.rest-catalog.security=OAUTH2
iceberg.rest-catalog.oauth2.token=***
iceberg.rest-catalog.parent-namespace=test_namespace
```
Fixes #22609
```markdown
* Add support for reading from Unity catalog with REST catalog. ({issue}`22609`)
```

Add support for reading from Unity catalog with Iceberg REST

---

core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroup.java
core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroupManager.java
core/trino-main/src/test/java/io/trino/execution/resourcegroups/TestResourceGroups.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/resourcegroups/ResourceGroup.java
core/trino-spi/src/main/java/io/trino/spi/resourcegroups/ResourceGroupConfigurationManager.java
plugin/trino-resource-group-managers/pom.xml
plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/db/DbResourceGroupConfigurationManager.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/TestingResourceGroup.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupConfigurationManager.java
testing/trino-tests/src/test/java/io/trino/execution/resourcegroups/db/TestQueuesDb.java

This PR addresses several issues with managing resource groups at runtime:
Consider the following sequence:
1. Create a root resource group (let’s call it `groupA`).
2. Run a query that matches the root group.
3. Add a subgroup to the root group.
4. While the query is either queued or running, run another query that matches the subgroup. You will get the following error: `Cannot add subgroup to groupA while queries are running`.
This means that a subgroup becomes operational only after all queries from its parent have finished. In some cases, this can take a considerable amount of time. Waiting until there are no queued queries assigned to the parent is understandable, as it prevents subgroups from starving. However, why can't we speed this up by allowing queries to be assigned to …

Improve managing resource groups at runtime

---

core/trino-spi/src/main/java/module-info.java

This is the first step to convert the SPI and generally the plugin system into Java modules.  This allows for better encapsulation of the plugins and Trino internals.  For example, as a module the SPI can have a non-exported package containing internal utility classes shared across SPI packages.  Additionally, in an automatic module, like the SPI, sealed class hiearchies can must be contained in a single package.

Add module info to SPI
