plugin/trino-oracle/pom.xml, plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClientModule.java, plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OraclePoolConnectionFactory.java
Support tracing when connection pool is enabled in Oracle. 
=> Support tracing when connection pool is enabled in Oracle

testing/trino-tests/src/test/java/io/trino/tests/BaseQueryAssertionsTest.java
The test `testWrongTypeWithEmptyResult` was removed in 21d74e125eaa0c098e96fa192ae55363fd4c32aa which looks incidental, given the commit was just migrating tests from TestNG to JUnit.
=> Restore test lost in migration

testing/trino-tests/src/test/java/io/trino/tests/TestLocalQueryAssertions.java
The test were not being run since the migration to JUnit. In TestNG, when a `@Test` method is overridden, it still runs. In JUnit 5, the overridden method needs to be annotated with `@Test` too, or else is ignored. Given the difference, and also given the fact tools like IntelliJ will generate `@Override` but won't copy annotations onto the overriding methods, this is a pitfall too easy to fall into.
=> Fix silently ignored tests in TestLocalQueryAssertions

core/trino-main/src/main/java/io/trino/execution/scheduler/TaskDescriptorStorage.java, core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java, core/trino-main/src/test/java/io/trino/execution/scheduler/TestTaskDescriptorStorage.java
=> Print biggest splits when running out of TaskDescriptorStorage space

plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/DynamicTable.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/DynamicTableBuilder.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/DynamicTablePqlExtractor.java, plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotConnectorSmokeTest.java, plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestDynamicTable.java
Adopted the idea introduced by (https://github.com/trinodb/trino/pull/17001#issuecomment-1594391322),
Support QueryOptions in Pinot DynamicTable.
label: pinot
Before:
After:
Server logs: 
```
2023-09-24T16:01:57.264-0700	INFO	20230924_230157_00003_92mfq.0.0.0-0-112	io.trino.plugin.pinot.client.PinotClient	Query 'SET skipUpsert = 'true';
SELECT "event_id", count(*) FROM upsertMeetupRsvp GROUP BY "event_id" LIMIT 10' on broker host 'http://192.168.1.248:8000/query/sql'
```
```markdown
* Add support for [query options](https://docs.pinot.apache.org/users/user-guide-query/query-options) in Dynamic tables
```
=> [pinot] Adding query option support for DynamicTable

core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaPageSource.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreAccessOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogAccessOperations.java, testing/trino-tests/src/test/java/io/trino/tests/TestInformationSchemaConnector.java
`ConnectorMetadata.listTables` returns all relations (tables, views,
materialzied views). Thus, when reading `information_schema.table` and
`table_type` column is not needed, the `getViews` call can be skipped.
`getViews` can be expensive as it pulls view information sometimes even
converting it (e.g. in case of Hive views).
=> Skip calculating table_type when not needed

docs/src/main/sphinx/connector/ignite.md, docs/src/main/sphinx/connector/mariadb.md, docs/src/main/sphinx/connector/mysql.md, docs/src/main/sphinx/connector/oracle.md, docs/src/main/sphinx/connector/postgresql.md, docs/src/main/sphinx/connector/redshift.md, docs/src/main/sphinx/connector/singlestore.md, docs/src/main/sphinx/connector/sqlserver.md, docs/src/main/sphinx/release/release-427.md
RN was slightly misleading and connector docs need to mention update support. Knock those both out.
=> Add docs for update statements to JDBC connectors

docs/src/main/sphinx/conf.py
Currently the sitemap for the docs uses the root context so links are like `/admin.html` .. however that is invalid and Google Analytics reports this as an issue. A correct URL is either relative to the sitemap or absolute. Sphinx however does not seem to support relative URL. If I leave the baseurl empty .. no sitemap is created at all. 
The current approach sets the full URL. We could also set `/docs/current/` and it would still be valid.
The problem of course in all cases is that the sitemap is now pointing at the current context .. where as the docs are version-specific in the path and "current" is just a changing symlink. This wrong generic sitemap is also part of the JAR that is deployed to Maven Central. However .. both of these items are not really a problem.
Alternatively we …
=> Use absolute URL for sitemap

testing/trino-test-jdbc-compatibility-old-server/pom.xml, testing/trino-test-jdbc-compatibility-old-server/src/test/java/io/trino/TestJdbcResultSetCompatibilityOldServer.java
So that we don't run out of the disk space
=> Remove docker image after test

core/trino-main/src/main/java/io/trino/connector/ConnectorServices.java, core/trino-main/src/main/java/io/trino/security/AccessControl.java, core/trino-main/src/main/java/io/trino/security/AccessControlManager.java, core/trino-main/src/main/java/io/trino/security/AllowAllAccessControl.java, core/trino-main/src/main/java/io/trino/security/DenyAllAccessControl.java, core/trino-main/src/main/java/io/trino/security/ForwardingAccessControl.java, core/trino-main/src/main/java/io/trino/security/InjectedConnectorAccessControl.java, core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java, core/trino-main/src/main/java/io/trino/tracing/TracingAccessControl.java, core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java, core/trino-spi/pom.xml, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorAccessControl.java, core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingConnectorAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ReadOnlySystemAccessControl.java, lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedConnectorAccessControlTest.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/LegacyAccessControl.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
After #19160 checkCanGrantExecuteFunctionPrivilege is no longer used and should be removed.  In the future we will likely add back a checkCanGrantExecuteFunctionPrivilege method, but it will have a different signature.
Release notes are not required as the previous PR #19160 covers this
=> Remove unused checkCanGrantExecuteFunctionPrivilege method

core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java, testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
Function security is enforced during function resolution, so these checks are duplicates
=> Remove duplicate function security checks in ExpressionAnalyzer

.github/bin/s3/setup-empty-s3-bucket.sh
Make the `LocationConstraint` create-bucket-configuration property optional depending on which aws region is used for ci. `LocationConstraint` can't be set if the AWS region used is `us-east-1`. This doesn't affect Trino, but could affect forks
```markdown
```
=> Don't set s3api create-bucket LocationConstraint configuration option for us-east-1 region

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/AuthenticatedMongoServer.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoPrivileges.java
This is a missing part for
https://github.com/ssheikin/trino/commit/43b55cba71bc7345977f292f91b1a082ada72fdf
`Support case insensitive identifiers in MongoDB`
Before:
When using custom roles in mongoDB only lowercase letter schemas are
accessible in Trino
After:
When using custom roles in mongoDB with lowercase and uppercase letter
schemas are accessible in Trino (`case-insensitive-name-matching=true`
is taken into account)
```markdown
* Fix mixed/upper case schemas with custom roles
```
=> Fix MongoDB mixed/upper case schemas with custom roles

plugin/trino-pinot/pom.xml, pom.xml
Fixes critical vulnerability in calcite: https://www.cve.org/CVERecord?id=CVE-2022-39135
=> Update calcite to 1.32.0

lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroFileWriter.java, lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroPagePositionDataWriter.java, lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroTypeUtils.java, lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroBase.java, lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroPageDataReaderWithAvroNativeTypeManagement.java, lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroPageDataWriterWithoutTypeManager.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/AvroHiveFileUtils.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/AvroHiveFileWriter.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/AvroPageSourceFactory.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/avro/camelCaseSchema.avsc, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSchemaUrl.java
Internally all Hive column names are stored and provided to the hive readers/writers as lowercase. The Native Avro File reader uses columns names to preform projection / selective decoding. This is not an issue for any table that generates its own schema, but for cases where the schema is provided via table property this could mean that the fields in the provided schema don't match the casing of the table metadata / columns passed in. This was not a problem in the previous reader when projection happened via row positions after a full read of the record.
This was missed due to:
1) A bug where the reader projection was silently ignoring requested columns it didn't have (only happening in cases where the provided schema has Upper casing)
2) No unit or product tests with upper casing in the …
=> Handle camelCase naming in externally provided Avro Schemas

plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestTrinoS3FileSystemAccessOperations.java
Avoid extra file status call in orc reader
```markdown
* Improve performance of reading ORC files. ({issue}`19295`)
```
=> Avoid extra file status call in orc reader

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/RegisterTableProcedure.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateTableInternalRetry.java
Ignore internal TableAlreadyExistsException in CREATE TABLE & register_table on Delta Lake connector
=> Ignore internal TableAlreadyExistsException in CREATE TABLE & register_table on Delta Lake connector

client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java, core/trino-main/src/main/java/io/trino/connector/system/MaterializedViewSystemTable.java, core/trino-main/src/main/java/io/trino/connector/system/TableCommentSystemTable.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/AttributeJdbcTable.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/CatalogJdbcTable.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/ColumnJdbcTable.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/FilterUtil.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/ProcedureColumnJdbcTable.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/ProcedureJdbcTable.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/PseudoColumnJdbcTable.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/SchemaJdbcTable.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/SuperTableJdbcTable.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/SuperTypeJdbcTable.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/TableJdbcTable.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/TableTypeJdbcTable.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/TypesJdbcTable.java, core/trino-main/src/main/java/io/trino/connector/system/jdbc/UdtJdbcTable.java, core/trino-main/src/main/java/io/trino/metadata/MetadataListing.java, core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java, core/trino-main/src/test/java/io/trino/connector/MockConnector.java, core/trino-spi/src/main/java/io/trino/spi/predicate/TupleDomain.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java, testing/trino-testing/src/main/java/io/trino/testing/CountingMockConnector.java, testing/trino-tests/src/test/java/io/trino/connector/informationschema/TestInformationSchemaConnector.java, testing/trino-tests/src/test/java/io/trino/connector/system/metadata/TestSystemMetadataConnector.java, testing/trino-tests/src/test/java/io/trino/connector/system/runtime/TestSystemRuntimeConnector.java, testing/trino-tests/src/test/java/io/trino/tests/FailingMockConnectorPlugin.java
Before the changes, `system.metadata.table_comments`, `system.metadata.materialized_views` queried with `schema_name IN ...`
predicate would first process all relations within catalog,
and only then filter by schema. This commit introduces filtering by
schema first. For now this is done on the engine side, but with
something like generified `Constraint` class we could give the connector
the opportunity to process the information even better.
=> Optimize table_comments with schema IN predicate

.github/workflows/ci.yml
`test-other-modules` is failing on CI for quite some time. This went unnoticed because apparently it was taking down the github actions worker, and the job was being marked as "Skipped".
Extract `trino-resource-group-managers` out of the problematic job. The module pulls a few docker containers.
See https://github.com/trinodb/trino/pull/19305
=> Extract trino-resource-group-managers from test-other-modules

.github/workflows/ci.yml
The Google Sheets connector tests are more flaky than average, probably because of how they interact with external resources. Extracting them to a separate job will make other failures in test-other-modules more apparent.
=> Extract trino-google-sheets from test-other-modules

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetConnectorTest.java
The connector can specify the actual Trino types that will be used to store the table for CTAS statements. This permits the core engine to perform the necessary coercions and casts.
Enhancement
Change to Iceberg connector
* Fixes #6658
( ) Release notes entries required with …
=> Support automatic type coercion in Iceberg table creation

core/trino-main/src/main/java/io/trino/operator/TableScanOperator.java, core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestOrcPageSourceMemoryTracking.java
BEFORE
├─ ScanFilter[table = tpch:sf1:nation, dynamicFilters = {"n_nationkey" = #df_307}]
│      Layout: [n_nationkey:bigint, n_name:varchar(25), n_regionkey:bigint, n_comment:varchar(152)]
│      Estimates: {rows: 25 (2.67kB), cpu: 2.67k, memory: 0B, network: 0B}/{rows: 25 (2.67kB), cpu: 2.67k, memory: 0B, network: 0B}
│      Dynamic filters:
│          - df_307, [ SortedRangeSet[type=bigint, ranges=25, {[0], ..., [24]}] ], collection time=1.19s
AFTER
├─ ScanFilter[table = tpch:sf1:nation, dynamicFilters = {"n_nationkey" = #df_307}]
│      Layout: [n_nationkey:bigint, n_name:varchar(25), n_regionkey:bigint, n_comment:varchar(152)]
│      Estimates: {rows: 25 (2.67kB), cpu: 2.67k, memory: 0B, network: 0B}/{rows: 25 (2.67kB), cpu: 2.67k, memory: 0B, network: 0B}
│      CPU: 1.00ms (0.10%), …
=> Report stats for dynamic-filter only ScanFilter

testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
For many test classes, this it the last method that is not converted. For example, running `TestInformationSchemaConnector` with TestNG will run only this method. Moving this will make tests like `TestInformationSchemaConnector` JUnit-only and improve test overall time (fewer `createQueryRunner` invocations).
Obviously, it can be the first JUnit test method for some other classes, but
- the train cannot be stopped. We do this sooner or later.
- `AbstractTestQueries` are already JUnit; `BaseConnectorTest` extends from `AbstractTestQueries` and `BaseConnectorTest` are most likely to most expensive setups, because they create dependant services.
=> Switch ensureTestNamingConvention to run in JUnit to reduce test setups

.mvn/wrapper/maven-wrapper.properties
No release notes needed.
Motivation: I'd like to keep maven up to date to make it easier to move to maven 4.0
=> Update to Maven 3.9.5

plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java, pom.xml
Upgrade ClickHouse JDBC driver to 0.5.0
https://github.com/ClickHouse/clickhouse-java/releases/tag/v0.5.0
=> Upgrade ClickHouse JDBC driver to 0.5.0

core/trino-main/src/main/java/io/trino/server/security/oauth2/NimbusOAuth2Client.java, core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Client.java, core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2ServerConfigProvider.java, core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Service.java, core/trino-main/src/main/java/io/trino/server/security/oauth2/OidcDiscovery.java, core/trino-main/src/main/java/io/trino/server/security/oauth2/StaticConfigurationProvider.java, core/trino-main/src/main/java/io/trino/server/security/oauth2/StaticOAuth2ServerConfiguration.java, core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiAuthenticationFilter.java, core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiLogoutResource.java, core/trino-main/src/main/java/io/trino/server/ui/OAuthIdTokenCookie.java, core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java, core/trino-main/src/test/java/io/trino/server/security/oauth2/BaseOAuth2WebUiAuthenticationFilterTest.java, core/trino-main/src/test/java/io/trino/server/security/oauth2/TestJweTokenSerializer.java, core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithJwt.java, core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithOpaque.java, core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithRefreshTokens.java, core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOidcDiscovery.java, core/trino-main/src/test/java/io/trino/server/security/oauth2/TestingHydraIdentityProvider.java, core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java, docs/src/main/sphinx/security/oauth2.md
When trying to logout from Trino WebUI, allows the user to be redirected to a specific end_session_endpoint thereby allowing user to logout from the IdP/OP.
Specification - https://openid.net/specs/openid-connect-rpinitiated-1_0.html
Will be sharing a video link on how it worked before and after this change. 
Fixes https://github.com/trinodb/trino/issues/13060
```markdown
* Implement session logout when logging out from Trino WebUI . ({issue}`13060`)
```
=> Implement session logout in OAuth2Authenticator

plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/CoercionUtils.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/DateCoercer.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/DecimalCoercers.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcTypeTranslator.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveCoercionPolicy.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestDateCoercer.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestDecimalCoercers.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnPartitionedTable.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnUnpartitionedTable.java
Hive connector was missing Varchar to Date and Decimal to integer types coercions.
This PR adds them, specifically:
- VARCHAR to DATE
- DECIMAL to TINYINT
- DECIMAL to SMALLINT
- DECIMAL to INTEGER
- DECIMAL to BIGINT
Coercions work only when they make sense:
- VARCHAR is a correctly formatted date in YYYY-MM-DD format. In case of overflows - too high value in days, months or years field  hive would do a strange conversion:
```
2023-09-50 => 2023-10-20
```
What Hive does is counterintuitive so I decided not to follow the logic and throw an exception.
Also Hive reads null when the value is not in a date format for example
```
'testValue' => null
```
This logic is also not followed and an exception is thrown.
We will only support dates no older than 1900-01-01 similarly to what we do with …
=> Add additional coercions for Hive

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Keep the mapping only for columns which are needed for query execution.
With big enough table the mapping alone could take 100kB+. With recent
change we reduced the size by order of ~8 by using Int2IntArrayMap
internally but still 10kB+ of memory per each split is noticable memory
pressure on coordinator.
=> Keep only needed mapping in TableToPartitionMapping

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
today we have lots of connectors which override entire beginInsert method for example even though they just want to change the generated query. And then over time the super impl improves to handle bugs or new features for example but the overridden code starts getting stale
```markdown
```
=> Refactor create/insert base jdbc client

testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
Reverts trinodb/trino#1932
Breaks master
=> Revert "Switch ensureTestNamingConvention to run in JUnit to reduce test setups"

docs/src/main/sphinx/release/release-428.md
Fix typo in 428 release notes: `tax_max_writer_count` -> `task_max_writer_count`
=> Fix typo: tax_max_writer_count -> task_max_writer_count

docs/src/main/sphinx/connector/mysql.md
This adds a note in the MySQL connector documentation about an error users may experience when using timestamptz types due to mismatches between JVM/time zone and what is installed on the MySQL server.
Relates to #18470 
=> Add docs for MySQL timestamptz handling

docs/src/main/sphinx/release.md, docs/src/main/sphinx/release/release-429.md
Assemble the release notes for the upcoming Trino 429 release. Fixes #19270  
* #19238 ✅ rn ✅ docs
* #19173 ✅ rn ✅ docs
* #19269 ✅ rn ✅ docs
* #19265 ✅ rn ✅ docs
* #19160 ✅ rn ✅ docs
* #19149 ✅ rn ✅ docs
* #19204 ✅ rn ✅ docs
* #19243 ✅ rn ✅ docs
* #19268 ✅ rn ✅ docs
* #19279 ✅ rn ✅ docs
* #19280 ✅ rn ✅ docs
* #19283 ✅ rn ✅ docs
* #19248 ✅ rn ✅ docs
* #19252 ✅ rn ✅ docs
* #19261 ✅ rn ✅ docs
* #19276 ✅ rn ✅ docs
* #19291 ✅ rn ✅ docs
* #19218 ✅ rn ✅ …
=> Add Trino 429 release notes

.github/workflows/ci.yml
21 temurin was released so we can move forward with additional testing
=> Switch to JDK 21 for forward compatibility testing

docs/src/main/sphinx/connector/ignite.md, docs/src/main/sphinx/connector/mariadb.md, docs/src/main/sphinx/connector/mysql.md, docs/src/main/sphinx/connector/oracle.md, docs/src/main/sphinx/connector/postgresql.md, docs/src/main/sphinx/connector/redshift.md, docs/src/main/sphinx/connector/singlestore.md, docs/src/main/sphinx/connector/sql-update-limitation.fragment, docs/src/main/sphinx/connector/sqlserver.md
* #19263 added support for `UPDATE` statements to docs pages for several JDBC connectors. This documentation is incomplete and more specific detail of `UPDATE` support is required. This PR creates a fragment detailing `UPDATE` support limitations. 
* https://github.com/trinodb/trino/pull/16445
```markdown
```
=> Clarify UPDATE statement support for JDBC connectors

docs/src/main/sphinx/connector/iceberg.md, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableHandle.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/optimizer/TestConnectorPushdownRulesWithIceberg.java
For iceberg partitioned tables, we should reject the table scan produced by the planner when the query does not have partition field.
Fixes https://github.com/trinodb/trino/issues/17239
```markdown
* Add an option to require all scans on partitioned tables to have a filter on a partitioned column. This can be enabled by setting the 
``iceberg.query-partition-filter-required`` catalog config property or the ``query_partition_filter_required`` catalog session property to ``true``.
```
=> Add config to reject Iceberg queries without partition filter

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowToPageConverter.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryQueryPageSource.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageAvroPageSource.java
=> Update BigQueryStorageAvroPageSource to SqlRow

testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
This is in efforts to speeding up the insert test for connectors
```markdown
```
=> Reduce written data size in insert test using nation table

core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
This allows using QueryRunner for manually diagnosing metrics exported via `/metrics`. This way the metrics exported in tests will have same names as ones exported in real deployment.
=> Apply PrefixObjectNameGeneratorModule in tests

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java
Add a test covering `DeltaLakeSplitManager` feature not to split up data files where we read only partitioning columns. I.e test for this line: https://github.com/trinodb/trino/blob/96a5d020c2421a2d8e8a74bf1cb1743f586eb751/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java#L169
=> Add Delta test for no redundant file splitting

core/trino-main/src/main/java/io/trino/execution/scheduler/EventDrivenFaultTolerantQueryScheduler.java, core/trino-main/src/main/java/io/trino/execution/scheduler/ExponentialGrowthPartitionMemoryEstimator.java, core/trino-main/src/main/java/io/trino/execution/scheduler/NoMemoryAwarePartitionMemoryEstimator.java, core/trino-main/src/main/java/io/trino/execution/scheduler/NoMemoryPartitionMemoryEstimator.java, core/trino-main/src/main/java/io/trino/execution/scheduler/PartitionMemoryEstimatorFactory.java, core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java, core/trino-main/src/test/java/io/trino/execution/scheduler/TestExponentialGrowthPartitionMemoryEstimator.java, core/trino-main/src/test/java/io/trino/execution/scheduler/TestNoMemoryAwarePartitionMemoryEstimator.java
=> Model no memory fragment handling as wrapper PartitionMemoryEstimator

core/trino-main/src/main/java/io/trino/execution/scheduler/TaskDescriptorStorage.java
=> Expose more stats for TaskDescriptorStorage

core/trino-main/src/main/java/io/trino/sql/planner/planprinter/BasicOperatorStats.java, core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanNodeStats.java, core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanNodeStatsSummarizer.java
Reduces memory allocations from merging of TDigestHistogram
```markdown
```
=> Use bulk merging of metrics in PlanNodeStatsSummarizer

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplit.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesFunctionProcessor.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
Avoid data files I/O when
- reading only partitioning columns
- doing `count(*)` queries on Iceberg tables (with no group by, or grouping by partitioning columns)
=> Accelerate Iceberg when reading partition columns only

plugin/trino-mariadb/pom.xml, plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java, plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClientModule.java, plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/BaseMariaDbTableIndexStatisticsTest.java, plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/BaseMariaDbTableStatisticsTest.java, plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbClient.java, plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbTableIndexStatistics.java, plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbTableIndexStatisticsLatest.java, plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestingMariaDbServer.java, plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseTestMySqlTableStatisticsTest.java, plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlAutomaticJoinPushdown.java, plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestingMySqlServer.java
Get table statistics for MariaDB tables.
=> Add MariaDB statistics support

lib/trino-filesystem/src/test/java/io/trino/filesystem/TrackingFileSystemFactory.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java
Getting last modified time usually requires a metadata call to the file system so is worth tracking.
Extracted from https://github.com/trinodb/trino/pull/18719
```markdown
```
=> Track INPUT_FILE_LAST_MODIFIED operations in TrackingFileSystemFactory

docs/src/main/sphinx/connector/delta-lake.md
The documentation currently states that checkpoint intervals are specified in seconds whereas it should specify the number of table writes. `delta.default-checkpoint-writing-interval` has the correct description.
=> Fix description of Delta Lake checkpoint intervals

docs/src/main/sphinx/admin/properties-task.md, docs/src/main/sphinx/admin/properties-writer-scaling.md
In the removal PR this was left behind instead of being removed from docs as well. Problem noticed by @kokosing 
cc @gaurav8297 @sopel39 
=> Remove deprecated task writer properties

client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java, client/trino-client/src/main/java/io/trino/client/uri/ConnectionProperties.java, client/trino-client/src/main/java/io/trino/client/uri/PropertyName.java, client/trino-client/src/main/java/io/trino/client/uri/TrinoUri.java, client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java, client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriver.java, client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverUri.java, docs/src/main/sphinx/client/jdbc.md
Add support for timezone parameter to JDBC driver
```markdown
* Add `timezone` parameter to set the session timezone. ({issue}``)
```
=> Add support for timezone parameter to JDBC driver

testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Having such cases would have caught a problem in the ongoing Iceberg aggregation pushdown PR, which means these are useful to have.
=> Add generic tests for filter after aggregation

core/trino-main/src/main/java/io/trino/execution/SqlQueryExecution.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/ByEagerParentOutputDataSizeEstimator.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BySmallStageOutputDataSizeEstimator.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/ByTaskProgressOutputDataSizeEstimator.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/CompositeOutputDataSizeEstimator.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/OutputDataSizeEstimator.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/OutputDataSizeEstimatorFactory.java, core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
Extract OutputDataSizeEstimator and model current logic
as a series of implementations of it wrapped in
CompositeOutputDataSizeEstimator.
=> Refactor stage output data size estimation

testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
The default implementation did not do anything, which is not suitable for the test.
=> Remove default implementation of withoutSmallFileThreshold

testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
Disable `AbstractTestQueryFramework.ensureTestNamingConvention` TestNG test to avoid redundant test setups.
For many test classes, this it the last method that is not converted. For example, running `TestInformationSchemaConnector` with TestNG will run only this method. Disabling this will make tests like `TestInformationSchemaConnector` JUnit-only and improve test overall time (fewer `createQueryRunner` invocations).
The test remains enabled for `BaseConnectorTest` and `BaseConnectorSmokeTest`, which already use JUnit and thus are either all-JUnit or do setup twice anyway.
This change also makes it easier to run all-JUnit test classes from an IDE, since now IDE will offer only the "Run with JUnit" option.
Alternative to https://github.com/trinodb/trino/pull/19400.
=> Avoid redundantly doubled test setup

core/trino-main/pom.xml, plugin/trino-bigquery/pom.xml, plugin/trino-druid/pom.xml, plugin/trino-mongodb/pom.xml, plugin/trino-pinot/pom.xml, pom.xml
=> Upgrade various dependencies

client/trino-client/src/main/java/io/trino/client/StatementClientV1.java, client/trino-client/src/test/java/io/trino/client/TestRetry.java
When a timeout happens when reading the response body, the JsonResponse will still be created with a correct response code of 200, but with an exception. The client should check for timeout exceptions and do a retry.
I've tested this manually, by setting a breakpoint when the response is decoded, and pausing a Trino container, so it stops responding. I'm not sure if we can write a regular test for this.
Here's an example stack trace:
```
Caused by: java.sql.SQLException: Error fetching results
at io.trino.jdbc.AbstractTrinoResultSet.next(AbstractTrinoResultSet.java:232)
at io.trino.jdbc.TrinoResultSet.next(TrinoResultSet.java:46)
at io.trino.plugin.jdbc.JdbcRecordCursor.advanceNextPosition(JdbcRecordCursor.java:185)
... 33 more
Caused by: java.lang.RuntimeException: Error fetching next at …
```
=> Handle timeouts in Trino client when decoding response body

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplit.java
Relates to https://github.com/trinodb/trino/pull/18719#discussion_r1359916168
```markdown
```
=> Add fileModifiedTime in DeltaLakeSplit Object methods

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
We use Trino to query and insert mysql tables, and one day we found that our MySQL appeared many temp tables which were created long time ago as shown below:  
```
mysql> show tables like 'tmp_trino_%';
......
| tmp_trino_fc833837bf0a4a0baec24baad3a2ddc0 |
| tmp_trino_fc8cc1be908142768c406450056d7132 |
| tmp_trino_fd6db0d078c048969758952a0cb5ecb3 |
| tmp_trino_fd8c62fc3b2443e5b06a27763f293f71 |
| tmp_trino_fe25d4a35c5c4033929cd7bafc8a09e9 |
| tmp_trino_feb573909ffd4e9a85cd5d7a74eb319e |
| tmp_trino_feb6e4bfb7f447c5a098eb6576a6c0d2 |
| tmp_trino_fefff60390e64f8988fb2a6cfaf23434 |
| tmp_trino_ff0bce6650c343ecb9c6e99b57d851f1 |
| tmp_trino_ff7ded0490974df1a46443777c1a5e9b |
| tmp_trino_ff93a57fc58447d2b4cf776ca3967774 |
+--------------------------------------------+
964 rows in set (0.00 …
```
=> Ensure that jdbc temp tables can be dropped if the insertions fail

core/trino-main/src/main/java/io/trino/dispatcher/DispatchManager.java
It's confusing when running queries represents something else than the queries in RUNNING state.
Let's capture current semantics (running & not blocked) as a separate metric with a different name.
=> Fix RunningQueries metric to represent all running queries

core/trino-main/src/main/java/io/trino/connector/system/MaterializedViewSystemTable.java, core/trino-main/src/main/java/io/trino/connector/system/SystemPageSourceProvider.java, core/trino-spi/src/main/java/io/trino/spi/connector/SystemTable.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeSystemTable.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/CountingAccessHiveMetastore.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetadataFileOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
Avoid `getMaterializedViewFreshness` call when reading `system.metadata.materialized_views` and `freshness`, `last_fresh_time` columns are neither predicated on, nor selected by the query.
=> Avoid redundant MV freshness calculation when result unused

core/trino-main/src/main/java/io/trino/sql/planner/SubqueryPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedScalarSubquery.java, core/trino-main/src/test/java/io/trino/sql/query/TestCorrelatedAggregation.java, core/trino-main/src/test/java/io/trino/sql/query/TestSubqueries.java, testing/trino-tests/src/test/resources/sql/presto/tpcds/hive/partitioned/q09.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/hive/partitioned/q54.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/hive/unpartitioned/q09.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/hive/unpartitioned/q54.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/orc/partitioned/q09.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/orc/partitioned/q54.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/orc/unpartitioned/q09.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/orc/unpartitioned/q54.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q09.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/partitioned/q54.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q09.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg/parquet/unpartitioned/q54.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg_small_files/parquet/unpartitioned/q09.plan.txt, testing/trino-tests/src/test/resources/sql/presto/tpcds/iceberg_small_files/parquet/unpartitioned/q54.plan.txt
INNER join is used in subqueryPlanner's planScalarSubquery. But it will result in incorrect results when the subquery returns zero rows.
Example query:
```
with test_a(id, type, col1) as( values ('123', 'a', 7), ('123', 'a', 8), ('456', 'a', 9)), 
base(claim_id, assess_id) as (values ('AAA', '123'), ('BBB', NULL), ('CCC', '456'), ('DDD', '789'))
select claim_id,
(select sum(col1) from test_a
where test_a.type = 'a' and base.assess_id = test_a.id
group by id 
) as cols
from base
```
Actual results:
```
claim_id | cols
----------+------
AAA      |   15
CCC      |    9
(2 rows)
```
Expected results:
```
claim_id | cols
----------+------
AAA      |   15
BBB      | NULL
CCC      |    9
DDD      | NULL
(4 rows)
``` …
=> Fix join type for correlated subquery

pom.xml
jjwt:
```
[0.12.3](https://github.com/jwtk/jjwt/blob/master/CHANGELOG.md#0123)
This patch release:
Upgrades the org.json dependency to 20231013 to address that library's [CVE-2023-5072](https://nvd.nist.gov/vuln/detail/CVE-2023-5072) vulnerability.
```
nimbus:
```
version 9.37 (2023-10-16)
* Adds JWTClaimsSet.getListClaim method.
```
=> Update jjwt and nimbus-jwt

core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
It was found to be confusing.
relates to https://github.com/trinodb/trino/pull/15832
=> Clarify global aggregation in applyAggregation

client/trino-client/src/main/java/io/trino/client/ClientCapabilities.java, core/trino-main/src/main/java/io/trino/execution/ResetSessionAuthorizationTask.java, core/trino-main/src/main/java/io/trino/execution/SetSessionAuthorizationTask.java, testing/trino-tests/src/test/java/io/trino/tests/TestServer.java
Given that `SET SESSION AUTHORIZATION` requires a client side changes we need to enforce and fail any client missing this capability. 
This Pull request is a follow up to https://github.com/trinodb/trino/pull/16067
Fixes Comment https://github.com/trinodb/trino/pull/16067#issuecomment-1720040698
```markdown
* Clients with version less than this release will fail when issuing commands `RESET / SET SESSION AUTHORIZIATION`. ({issue}`19217 `)
```
=> Enforce Client capabilities when Session Authorization is not supported

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoSession.java
Fixes #19404
```markdown
* Fix incorrect results when a query contains several `!=` or `NOT IN` predicates. ({issue}`19404`)
```
=> Fix correctness issue when query contains some not-equals in MongoDB

pom.xml, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDeleteCompatibility.java
Upgrade docker-images to version 87. 
This upgrades Delta Lake version to 3.0.0.
=> Upgrade docker-images to version 87

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/NoMemoryAwarePartitionMemoryEstimator.java, core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestNoMemoryAwarePartitionMemoryEstimator.java
Extend the logic to specially treat metadata queries and not allocate any memory for those, so they are scheduled immediatelly, to cover all schematas from system catalog (previously only jdbc schama was covered).
=> Do not allocate memory for all queries scanning system.* tables

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestEliminateSorts.java
`ORDER BY` doesn't work properly in the following case because optimizer eliminates Sort before LocalExchange is added.
```sql
trino> SELECT * FROM (
->   SELECT l_quantity, row_number() OVER (ORDER BY l_quantity) as row_number 
->   FROM tpch.sf1.lineitem
-> ) WHERE mod(row_number, 1000000) = 0 ORDER BY l_quantity;
l_quantity | row_number
------------+------------
26.00 |    3000000
50.00 |    6000000
17.00 |    2000000
9.00 |    1000000
42.00 |    5000000
34.00 |    4000000
(6 rows)
```
```markdown
```
Fixes …
=> Remove eliminating sort optimization

core/trino-main/src/main/java/io/trino/operator/FlatGroupByHash.java, core/trino-main/src/main/java/io/trino/operator/FlatHash.java, core/trino-main/src/main/java/io/trino/operator/FlatHashStrategy.java, core/trino-main/src/main/java/io/trino/operator/FlatHashStrategyCompiler.java, core/trino-main/src/main/java/io/trino/operator/aggregation/GroupedAggregator.java, core/trino-main/src/main/java/io/trino/operator/aggregation/builder/InMemoryHashAggregationBuilder.java, core/trino-main/src/test/java/io/trino/operator/TestFlatHashStrategy.java
Implements column-wise hash calculations in FlatHashCompiler and changes FlatGroupByHash to use it to implement a batched approach to first computing a range of position hashes and then attempting to insert those positions using the hashes that were precomputed.
By calculating position hashes in a columnar traversal, we can avoid repeated expensive bounds checking per access, allow the JIT to emit more efficient unrolled loops, and access the memory in a way that friendlier and more predictable for CPU caches.
Additionally, when attempting to insert the positions into the FlatGroupByHash after precomputing the hash code we can start loading the relevant portition of the hash table into memory sooner since we aren't intermixing computing the hash with the memory accesses.
Since re-hashing …
=> Vectorize Hashing in FlatGroupByHash

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java
The method `parseStatisticsFromParquet()` is being called for building each `add` file entry.
Avoid redundant calculation of `columnsWithMinMaxStats`.
```markdown
```
=> Avoid redundant calculation of columnsWithMinMaxStats

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Fixes #17867
Assuming there's a lag until the job appears in INFORMATION_SCHEMA.JOBS_BY_USER table. 
=> Use assertEventually in BigQuery assertLabelForTable

.github/DEVELOPMENT.md
Added a hint on when to split to multiple commits. Also improved wording of the whole paragraph.
=> Update DEVELOPMENT.md: Git merge strategy

.github/bin/s3/setup-empty-s3-bucket.sh
The tag with key "environment" and value "test" is needed so that the temporary S3 buckets used for testing can be cleaned up by the daily AWS resource cleanup job if they aren't deleted by the ci workflow run.
https://github.com/trinodb/trino/pull/19060
https://github.com/trinodb/trino/pull/19248
```markdown
```
=> Add "test" environment tag to temporary S3 test buckets used by CI

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
This is a minor change that modifies the error message when all columns in a select query get filtered out to be of `TABLE_NOT_FOUND` error code instead of `COLUMN_NOT_FOUND`. 
```markdown
* Switch error code to `TABLE_NOT_FOUND` if all columns filtered out from access control
```
=> Switch error code to TABLE_NOT_FOUND if all columns filtered out

plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
=> Add missing @Test annotation to overriden test for HiveGlueMetastore

plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlTableStatistics.java
The test is supposed to ensure that the table is not analyzed, but PostgreSQL analyzes tables automatically.
Therefore, the test is not applicable for it.
=> Remove unnecessary test

docs/src/main/sphinx/admin/event-listeners-http.md, docs/src/main/sphinx/admin/fault-tolerant-execution.md, docs/src/main/sphinx/admin/resource-groups.md, docs/src/main/sphinx/client/cli.md, docs/src/main/sphinx/client/jdbc.md, docs/src/main/sphinx/functions/comparison.md, docs/src/main/sphinx/functions/conversion.md, docs/src/main/sphinx/functions/decimal.md, docs/src/main/sphinx/functions/json.md, docs/src/main/sphinx/installation/deployment.md, docs/src/main/sphinx/installation/rpm.md, docs/src/main/sphinx/security/built-in-system-access-control.md, docs/src/main/sphinx/security/certificate.md, docs/src/main/sphinx/security/file-system-access-control.md, docs/src/main/sphinx/security/jwt.md, docs/src/main/sphinx/security/oauth2.md, docs/src/main/sphinx/sql/show-stats.md
Purely changing format of source to use myst markdown directly rather than an eval-rst escape block.
I did a folder compare of the HTML output prior and after the change. User facing changes resulting from this refactor are rare, similar to other conversion tickets I did before. When there are changes I reviewed and made sure that the changes are an improvement.
I will follow up with another PR for all the connector docs and a few minor others separately.
Follow up to various other conversion PRs.
=> Convert tables in docs to markdown source

plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java, plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
Close https://github.com/trinodb/trino/issues/19464
Ignite not support `like ... escape ...`
```markdown
* Fix failure when a query contains `LIKE` with `ESCAPE`. ({issue}`19464`)
```
=> Don't pushdown like expression with escape in Ignite connector

docs/src/main/sphinx/connector/mariadb.md
=> Add docs for table stats with MariaDB

docs/src/main/sphinx/release.md, docs/src/main/sphinx/release/release-430.md
Assemble the release notes for the upcoming Trino 430 release. Fixes #19366   
* #18948 ✅ rn ✅ docs
* #19361 ✅ rn ✅ docs
* #19375 ✅ rn ✅ docs
* #19364 ✅ rn ✅ docs
* #19335 ✅ rn ✅ docs
* #19381 ✅ rn ✅ docs
* #19341 ✅ rn ✅ docs
* #19386 ✅ rn ✅ docs
* #19358 ✅ rn ✅ docs
* #17263 ✅ rn ✅ docs
* #19388 ✅ rn ✅ docs
* #19383 ✅ rn ✅ docs
* #19393 ✅ rn ✅ docs
* #19394 ✅ rn ✅ docs
* #19398 ✅ rn ✅ docs
* #19346 ✅ rn ✅ docs
* #19318 ✅ rn ✅ docs
* #19316 ✅ rn ✅ …
=> Add Trino 430 release notes

core/trino-spi/pom.xml, core/trino-spi/src/main/java/io/trino/spi/block/ArrayBlock.java, core/trino-spi/src/main/java/io/trino/spi/block/Block.java, core/trino-spi/src/main/java/io/trino/spi/block/ByteArrayBlock.java, core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java, core/trino-spi/src/main/java/io/trino/spi/block/Fixed12Block.java, core/trino-spi/src/main/java/io/trino/spi/block/Int128ArrayBlock.java, core/trino-spi/src/main/java/io/trino/spi/block/IntArrayBlock.java, core/trino-spi/src/main/java/io/trino/spi/block/LazyBlock.java, core/trino-spi/src/main/java/io/trino/spi/block/LongArrayBlock.java, core/trino-spi/src/main/java/io/trino/spi/block/MapBlock.java, core/trino-spi/src/main/java/io/trino/spi/block/RowBlock.java, core/trino-spi/src/main/java/io/trino/spi/block/RunLengthEncodedBlock.java, core/trino-spi/src/main/java/io/trino/spi/block/ShortArrayBlock.java, core/trino-spi/src/main/java/io/trino/spi/block/ValueBlock.java, core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlock.java, lib/trino-orc/src/test/java/io/trino/orc/TestDictionaryBuilder.java
The synthetic dictionary, rle, and lazy blocks require special handling
in the codebase, and new synthetic blocks cannot reasonable be added
without updating the existing code. This commit blocks direct extensions
of Block, only allowing extensions to ValueBlock.
Major changes:
- Seal `Block` interface
- Mark `ValueBlock` interface `non-sealed`
- Mark all current `ValueBlock` implementations as `final`
This is part of Project Hummingbird #14237 
```markdown
* Implementations of `Block` must now implement `ValueBlock`. ({issue}`19480`)
```
=> Seal Block interface

docs/src/main/sphinx/connector/metastores.md, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/DefaultThriftMetastoreClientFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreConfig.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/Transport.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftMetastoreConfig.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestingTokenAwareMetastoreClientFactory.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAbfsConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestTrinoHiveCatalogWithHiveMetastore.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveMetastoreClientFactory.java
```markdown
* The Hive metastore configuration property `hive.metastore-timeout` has been
replaced by the `hive.metastore.thrift.client.connect-timeout`
and `hive.metastore.thrift.client.read-timeout` properties. ({issue}`19390`)
```
=> Split metastore timeout config for connect and read

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesFunctionProcessor.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeTransactionLogEntry.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointEntryIterator.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
Relates to https://github.com/trinodb/trino/issues/19156
Very much inspired from https://github.com/trinodb/trino/pull/19240
The problem this PR is solving is that it avoids working with `TupleDomain.all()` as tuple domain when there are more predicates specified for the `CheckpointEntryIterator`:
https://github.com/trinodb/trino/blob/d23921d86777fbf778e7c3f63edcbd293c501971/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java#L186-L187
What this means is that in such cases, all the entries from the Delta Lake Parquet checkpoint file will be returned as results even though the code flow is interested in a small subset of the entries.
A common use-case  of specifying more predicates (entry types) for the …
=> Support OR-ed condition in Delta checkpoint iterator

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/logging/SessionInterpolatedValues.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/logging/FormatBasedRemoteQueryModifier.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/logging/TestFormatBasedRemoteQueryModifier.java
Instead of failing the query in case a character NOT in the allowlist is detected, now we search for occurence of the closing comment '*/' and only then fail the query.
=> Simplify how SQL injection is detected when using query.comment-format

docs/src/main/sphinx/release/release-430.md
Reliability of connecting to data sources was improved in all JDBC based connectors by adding retries. The Oracle connector already supported retries, so the release notes should apply to all JDBC based connectors except Oracle.
( X ) This is not user-visible or is docs only, and no release notes are required.
=> Correct release notes

docs/src/main/sphinx/sql/grant-roles.md, docs/src/main/sphinx/sql/grant.md, docs/src/main/sphinx/sql/revoke-roles.md, docs/src/main/sphinx/sql/revoke.md
Clarify syntax for role grants. The current syntax has misled multiple readers to think that this is valid.
```
GRANT ROLE test TO jessie212;
```
We assume that readers think that the lowercase `role` is a typo.
I worked with @mosabua and confirmed in the antlr spec that this is wrong and the syntax is
```
GRANT test TO jessie212;
```
```markdown
```
=> Clarify syntax for role grants

lib/trino-hdfs/src/test/java/io/trino/filesystem/hdfs/TestHdfsFileSystemHdfs.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveLocal.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestSemiTransactionalHiveMetastore.java
=> Remove Hadoop usage from SemiTransactionalHiveMetastore

testing/trino-test-jdbc-compatibility-old-driver/bin/run_tests.sh
It was needed only until 406 release.
=> Remove dead code from test script

docs/src/main/sphinx/connector/hive.md
* This PR creates a matrix in the Hive connector's schema evolution section detailing supported type conversions. It adds additional conversions that were not listed in the documentation.
* Fixes #19459 
```markdown
```
=> Expand docs for Hive schema evolution type conversions

docs/src/main/sphinx/client/jdbc.md
Docs for #19022 
```markdown
```
=> Document the new JDBC legacyPreparedStatements flag

core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestEliminateSorts.java
Regression test for https://github.com/trinodb/trino/pull/19387
Sort elimination optimization was removed in https://github.com/trinodb/trino/pull/19387 because that optimization could produce a wrongly sorted query result. This PR adds a test case to prevent future regression.
=> Add regression test for sort elimination

docs/src/main/sphinx/admin/properties-sql-environment.md, docs/src/main/sphinx/admin/properties.md, docs/src/main/sphinx/connector/hive.md, docs/src/main/sphinx/connector/memory.md, docs/src/main/sphinx/index.md, docs/src/main/sphinx/language/sql-support.md, docs/src/main/sphinx/language/types.md, docs/src/main/sphinx/routines.md, docs/src/main/sphinx/routines/begin.md, docs/src/main/sphinx/routines/case.md, docs/src/main/sphinx/routines/declare.md, docs/src/main/sphinx/routines/examples.md, docs/src/main/sphinx/routines/function.md, docs/src/main/sphinx/routines/if.md, docs/src/main/sphinx/routines/introduction.md, docs/src/main/sphinx/routines/iterate.md, docs/src/main/sphinx/routines/leave.md, docs/src/main/sphinx/routines/loop.md, docs/src/main/sphinx/routines/repeat.md, docs/src/main/sphinx/routines/return.md, docs/src/main/sphinx/routines/set.md, docs/src/main/sphinx/routines/while.md, docs/src/main/sphinx/sql.md, docs/src/main/sphinx/sql/create-function.md, docs/src/main/sphinx/sql/drop-function.md, docs/src/main/sphinx/sql/select.md, docs/src/main/sphinx/sql/set-path.md, docs/src/main/sphinx/sql/show-functions.md
Add documentation for user-defined SQL functions including the following aspects:
* Overview
* Various docs for new keywords and such
* Examples
To do:
* reviews
* test all examples
* rebase after code PR is merged
* figure out how and where to document routine storage support in connectors (currently Hive and Memory)
Implementation: https://github.com/trinodb/trino/pull/19308
But this needs to be merged with the code PR which will make a big splash in the community and include a release notes entry or probably blog posts and more.
=> Add documentation for SQL routines

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/NormalizeOrExpressionRewriter.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestSimplifyExpressions.java
=> Normalize OR and IN expressions referencing the same symbol as IN

plugin/trino-hive/pom.xml, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConcurrentModificationGlueMetastore.java
Retry the updating the statistics of the AWS Glue table, in the situation that another query is also trying to perform concurrently the same action.
e.g. : two or more concurrent INSERT operations in a Hive table.
```
io.trino.spi.TrinoException: All operations other than the following update operations were completed: replace table parameters myschema.mytable
at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore$Committer.executeUpdateStatisticsOperations(SemiTransactionalHiveMetastore.java:2163)
at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commitShared(SemiTransactionalHiveMetastore.java:1567)
at io.trino.plugin.hive.metastore.SemiTransactionalHiveMetastore.commit(SemiTransactionalHiveMetastore.java:1264)
...
Caused by: …
```
=> Retry updating the table statistics in the context of concurrent modifications

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java
Fix syntax in `PredicatePushDown#createDynamicFilters` arguments list
(* ) This is not user-visible or is docs only, and no release notes are required.
=> Fix syntax in `PredicatePushDown#createDynamicFilters` arguments list

testing/trino-test-jdbc-compatibility-old-driver/bin/run_tests.sh
This not work with the current open telemetry being a dependency for the JDBC compatibility module
=> Skip testing JDBC compatibility for versions 422-424

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/ArbitraryDistributionSplitAssigner.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/HashDistributionSplitAssigner.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/SingleDistributionSplitAssigner.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/SplitAssigner.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/SplitsMapping.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/TaskDescriptor.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/TaskDescriptorStorage.java, core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/SplitAssignerTester.java, core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestArbitraryDistributionSplitAssigner.java, core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestEventDrivenTaskSource.java, core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestHashDistributionSplitAssigner.java, core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestSingleDistributionSplitAssigner.java, core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestSplitsMapping.java, core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestTaskDescriptorStorage.java
We need to preserve information which splits map to which source
partition id in task descriptor to be able to split task descriptor into
multiple ones. Splitting is important in case we made a scheduling
mistake and packed to many source partitions into single task descriptor
and execution of such task is not possible due to lack of resources.
=> Preserve sourcePartition to Splits mapping in task descriptor 

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergFileOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
Measure the access operations performed while running `CREATE OR REPLACE TABLE` command for :
- metastore
- object storage
```markdown
```
=> Test access operations for `CREATE OR REPLACE TABLE`  on Iceberg

client/trino-client/src/main/java/io/trino/client/uri/ConnectionProperties.java, client/trino-client/src/main/java/io/trino/client/uri/PropertyName.java, client/trino-client/src/main/java/io/trino/client/uri/TrinoUri.java, client/trino-jdbc/pom.xml, client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java, client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoPreparedStatement.java, client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcPreparedStatement.java, docs/src/main/sphinx/client/jdbc.md
=> Rename legacyPreparedStatements to explicitPrepare

plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java, pom.xml, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java
Bump coral to 2.2.14 to support Hive view translation cnsisting of a UNION between a char and a varchar field.
Due to wrong coercion between `varchar` and `char` in Trino, as described in trinodb/trino#9031
, a work-around needs to be applied in case of translating Hive views which contain a UNION dealing with char and varchar types. The work-around consists in the explicit cast of the field having char type towards varchar type corresponding of the set operation output type.
Fixes https://github.com/trinodb/trino/issues/18337
https://github.com/linkedin/coral/pull/442
https://github.com/trinodb/trino-coral/pull/2
(x) Release notes are …
=> Cast char fields, if necessary, to varchar type in Hive view translations

docs/src/main/sphinx/admin/properties-sql-environment.md
Added an actual full example with the properties after reading the docs and finding it is not explicit enough without the example
=> Add example for routine storage config

docs/src/main/sphinx/release.md, docs/src/main/sphinx/release/release-431.md
Assemble the release notes for the 431 release notes.
Fixes #19475 
* #19385 ✅ rn ✅ docs
* #19474 ✅ rn ✅ docs
* #19470 ✅ rn ✅ docs
* #19476 ✅ rn ✅ docs
* #19480 ✅ rn ✅ docs
* #19390 ✅ rn ✅ docs
* #19439 ✅ rn ✅ docs
* #19413 ✅ rn ✅ docs
* #19486 ✅ rn ✅ docs
* #19022 ✅ rn ✅ docs, see #19502 
* #19340 ✅ rn ✅ docs
* #19445 ✅ rn ✅ docs
* #19505 ✅ rn ✅ docs
* #19515 ✅ rn ✅ docs
* #19508 ✅ rn ✅ docs
* #19494 ✅ rn ✅ docs
* #19518 ✅ rn ✅ docs
* #19434 ✅ …
=> Add Trino 431 release notes

.github/bin/s3/delete-s3-bucket.sh
The s3api won't allow you to delete a bucket that still has objects in it, so we should delete all objects from the s3 bucket used for the S3FileSystem cloud tests before trying to delete the bucket
Fixes #19360 
```markdown
```
=> Delete all objects before deleting s3 bucket used for ci

lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetMetadataUtils.java, lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java, lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
Currently the logic in `org.apache.parquet.format.converter.ParquetMetadataConverter#toParquetStatistics` skips writing min/max row-group statistics if they are longer than 4Kb. This is changed to write stats with truncation to allow readers to perform row-group pruning based on query predicates.
Related issue https://github.com/trinodb/trino/issues/19052
Parquet spec updated at https://github.com/apache/parquet-format/pull/216 to clarify that truncation of min/max row-group stats is allowed
```markdown
* Improve performance of filtering on columns with long strings stored …
```
=> Write min/max statistics with truncation for strings in parquet

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/FileTestingTransactionLogSynchronizer.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
`FileTestingTransactionLogSynchronizer` was using default HadoopFileSystemFactory which doesn't track the FileOperations.
=> Add missing FileOperations for DeltaLakeFileOperations test

pom.xml
This PR remove `sortpom-maven-plugin` from pom.xml because this plugin already exists in airbase.
Having this plugin in pom.xml causes `air.check.skip-all` fail to work.
Ref:
https://github.com/airlift/airbase/blob/859b24e2a3daf450de5bf74614b646af635aad7f/airbase/pom.xml#L1499-L1500
`sortpom-maven-plugin` was introduced by:
https://github.com/trinodb/trino/pull/17994/commits/8a95a9cb295ae4415d85b8288300ff3cead100eb
Being added to airbase 147:
https://github.com/airlift/airbase/pull/370/commits/dbd07e08d65ec27ee84efa897c98522079dc7615
Didn't finished the cleanup when update to airbase 147:
https://github.com/trinodb/trino/commit/d2b9fb8581928508399a658c5598ae0f4eecd5b3
( ) Release notes are required. Please …
=> Remove sortpom-maven-plugin from pom.xml

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/TypeUtils.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
Support predicate pushdown on floating point types in mongodb
```markdown
* Add support for predicate pushdown on `real` and `double` types. ({issue}`19575`)
```
=> Support predicate pushdown on floating point types in mongodb

pom.xml
Released on Oct 18.
https://github.com/google/error-prone/releases/tag/v2.23.0
```markdown
```
=> Upgrade Error Prone to 2.23.0

core/trino-main/src/main/java/io/trino/security/AccessControlManager.java, core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java, core/trino-main/src/test/java/io/trino/dispatcher/TestLocalDispatchQuery.java, core/trino-main/src/test/java/io/trino/execution/TestCommitTask.java, core/trino-main/src/test/java/io/trino/execution/TestDeallocateTask.java, core/trino-main/src/test/java/io/trino/execution/TestPrepareTask.java, core/trino-main/src/test/java/io/trino/execution/TestQueryStateMachine.java, core/trino-main/src/test/java/io/trino/execution/TestStartTransactionTask.java, core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java, core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java, core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java, core/trino-spi/pom.xml, core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControlFactory.java
```markdown
* Add Trino version to SystemAccessControlContext. ({issue}`issuenumber`)
```
=> Add Trino version to SystemAccessControlContext

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergTrinoRestCatalogConnectorSmokeTest.java
```markdown
* Add support for `register_table` and `unregister_table` procedures in REST catalog. ({issue}`15512`)
```
Fixes #15512
=> Support register_table and unregister_table procedure in Iceberg REST catalog

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
```markdown
* Improve performance of `CREATE TABLE AS ...` queries that contain a redundant `ORDER BY` clause. ({issue}`19547`)
```
=> Remove redundant ORDER BY in CREATE TABLE AS queries

core/trino-main/src/test/java/io/trino/sql/query/TestInlineFunctions.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
It's unnecessary to test a core engine feature against every connector. It makes the tests suite take longer unnecessarily and doesn't provide additional value.
Relates to https://github.com/trinodb/trino/pull/19562
=> Move inline function test to dedicated class

docs/src/main/sphinx/connector/metastores.md, plugin/trino-iceberg/pom.xml, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieCatalogConfig.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieCatalogModule.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestIcebergNessieCatalogConfig.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestIcebergNessieCatalogWithBearerAuth.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/KeycloakContainer.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
Nessie server can be deployed with Auth mode like [keycloak](https://projectnessie.org/guides/keycloak/). 
So, need to expose the Nessie client configurations to handle the Auth. 
Along with that, some common Nessie server configurations like read-timeout-ms, 
connect-timeout-ms, and compression-enabled properties are exposed to have finer 
control over the Nessie commits. 
https://projectnessie.org/tools/client_config/
```markdown
* Add support for bearer authentication in the Nessie catalog. ({issue}`17725`)
```
=> Support additional configurations for Nessie catalog

core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java, core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
A formatter fix, not visible to the user.
No release notes or docs required.
=> Fix formatting of json_table columns in SqlFormatter

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/KeycloakContainer.java
It generates unnecessary clutter when running tests.
Follow up to https://github.com/trinodb/trino/pull/17725
=> Remove unnecessary logging

plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/BooleanCoercer.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/CoercionUtils.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcTypeTranslator.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveCoercionPolicy.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestBooleanCoercer.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnPartitionedTable.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnUnpartitionedTable.java
Add boolean to varchar coercion for hive.
Enable the Hive users to retrieve the information from their tables after performing queries which change `boolean` columns to `varchar`.
Hive sample DDL query:
```
ALTER TABLE mytable CHANGE COLUMN mycolumn mycolumn varchar(5);
```
Thanks to @findinpath for working on this. 
Overrides https://github.com/trinodb/trino/pull/19492
```markdown
* Add boolean to varchar coercion for hive. ({issue}`issuenumber`)
```
=> Add boolean to varchar coercion for hive

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestMetastoreUtil.java
When working with external tables, the types in HMS sometimes can be in uppercase. Cast them to lowercase to make sure they're recognized as supported types.
An alternative solution would be to only do the lookup in a case-insensitive way at https://github.com/trinodb/trino/blob/master/plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/TypeInfoUtils.java#L193 
=> Always use lowercase Hive types

core/trino-main/src/main/java/io/trino/operator/output/PagePartitioner.java, core/trino-main/src/main/java/io/trino/operator/output/PartitionedOutputOperator.java, core/trino-main/src/test/java/io/trino/operator/TestOperatorStats.java, core/trino-main/src/test/java/io/trino/operator/output/TestPagePartitioner.java, core/trino-main/src/test/java/io/trino/operator/output/TestPartitionedOutputOperator.java
`PartitionedOutputOperator` partition's input pages into
`PagePartitioner` shared between operators.
Since `PagePartitioner` can be flushed to output buffers
on `noMoreOperators`, and by that time all operators can
be finished, we need to update the operator metrics on
`addInput` to get them propagated to the `OperatorSummary`
inside the `PipelineStats`.
```markdown
```
=> Fix PartitionedOutputOperator metrics

lib/trino-orc/src/main/java/io/trino/orc/reader/DecimalColumnReader.java, lib/trino-orc/src/main/java/io/trino/orc/reader/UuidColumnReader.java
Fixes #19636
```markdown
* Fix reading ORC long DECIMAL column containing only nulls. ({issue}`19636`)
```
=> Fix reading ORC long decimal column containing only nulls 

docs/src/main/sphinx/admin/properties-catalog.md, docs/src/main/sphinx/admin/properties.md, docs/src/main/sphinx/language/sql-support.md, docs/src/main/sphinx/sql.md, docs/src/main/sphinx/sql/create-catalog.md, docs/src/main/sphinx/sql/drop-catalog.md
Document create/drop catalog with a lot of warnings about known issues.
This adds 3 pages:
* CREATE CATALOG
* DROP CATALOG
* Catalog management properties
There are more existing and undocumented catalog management properties, like `catalog.config-dir`, that can be added to the new properties page later.
I decided to repeat the same warnings on multiple pages, since they're very important.
=> Document create/drop catalog

testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
Increase
`TestMinWorkerRequirement.testMultipleRequiredWorkerNodesSessionOverride` timeout, hopefully fixing its flakiness.  Before the changes, running the test with `@Test(invocationCount = 20, threadPoolSize = 4)` would pretty deterministically reproduce the failure locally (with first 4 runs failing, other succeeding). It is up to future investigation to understand why it sometimes takes more time to register new worker node.
Hopefully maybe this fixes https://github.com/trinodb/trino/issues/19446
=> Increase timeout when scaling cluster in test

plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/BaseMariaDbTableStatisticsTest.java
With previous tolerance the test was observed failing on CI.
Fixes https://github.com/trinodb/trino/issues/19657
=> Increase tolerance in MariaDB testBasic stats tests

docs/src/main/sphinx/conf.py, docs/src/main/sphinx/release.md, docs/src/main/sphinx/release/release-432.md
* Centrally configure how the breaking changes symbol is used
* Add link to descriptive text
* Add descriptive text into releases page
=> Improve breaking change release notes render

testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCreateTableAsSelectCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TransactionLogAssertions.java
Probably, OPTIMIZE procedure ran in the background on Databricks side. 
Fixes #19580
=> Run testReplaceTableWithSchemaChangeOnCheckpoint only with OSS Delta

core/trino-main/src/main/java/io/trino/eventlistener/EventListenerManager.java, core/trino-main/src/main/java/io/trino/eventlistener/EventListenerModule.java
JMX bean EventListenerManager contains execution times of queryCompleted, queryCreated and splitCompleted methods.
```
trino:tiny> use jmx.current;
USE
trino:current> select node, object_name, "querycompletedtime.alltime.count" from  "trino.eventlistener:name=eventlistenermanager";
node      |                  object_name                  | querycompletedtime.alltime.count
---------------+-----------------------------------------------+----------------------------------
presto-master | trino.eventlistener:name=EventListenerManager |                             37.0
presto-worker | trino.eventlistener:name=EventListenerManager |                              0.0
(2 rows)
Query 20231108_141144_00037_6i9c6, FINISHED, 2 nodes
Splits: 2 total, 2 done (100.00%)
0.14 [2 rows, 132B] [13 rows/s, …
```
=> Expose EventListenerManager benchmarks through JMX

plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/AbstractResourceConfigurationManager.java, testing/trino-tests/src/test/java/io/trino/execution/resourcegroups/db/TestQueuesDb.java
When using database resource group manager, if softMemoryLimit was setup to 80% and then modified to 100MB. The softMemoryLimit in resource group is always 80% instead of 100MB.
The root cause is after using fraction(i.e. percentage) in softMemoryLimit in resource group, SqlQueryManager start updating softMemoryLimit to resource group per second. And the background update will not stop even if a static value is set in softMemoryLimit.
```markdown
```
=> Fix resource group keep setting incorrect softMemoryLimit

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreAccessOperations.java
Fix flaky test https://github.com/trinodb/trino/actions/runs/6808005835/job/18512273030
=> Add `@Execution(SAME_THREAD)` to TestDeltaLakeMetastoreAccessOperations

docs/src/main/sphinx/routines/case.md, docs/src/main/sphinx/routines/function.md, docs/src/main/sphinx/routines/return.md
Return null is required. Not sure if we should state that somehow .
=> Fix routine example for case

core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/LimitPushDown.java, core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesPlans.java, core/trino-main/src/test/java/io/trino/sql/planner/planprinter/TestJsonRepresentation.java, core/trino-main/src/test/java/io/trino/sql/query/TestSelectAll.java, testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java, testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
Fixes several issues with `LimitNode` pushdown logic that could result in extremely long planning time and unnecessary complex plans, especially in the presence of `UNION ALL`:
1. Prevents `PushLimitThroughUnion` from inserting partial limit nodes until after `MergeUnion` has a chance to run. Before this change, the inserted limit nodes would prevent merging of chained `UNION ALL` subplans.
2. Fixes `LimitPushDown` to correctly push partial instead of full limit nodes where appropriate
3. Prevents `AddExchanges` from inserting duplicate partial limit nodes that previously would result in multiple layers of local exchanges when a single gathering exchange should be preferred.
Given a query like:
```
SELECT col0 FROM (
SELECT n_nationkey as col0 FROM tpch.tiny.nation
UNION ALL
SELECT …
```
=> Improve Limit Pushdown

core/trino-spi/src/main/java/io/trino/spi/type/ArrayType.java
Fixes #19596
```markdown
*Fix ARRAY hash code when array value is dictionary encoded. ({issue}`19596`)
```
=> Fix ARRAY hash code when array value uses a dictionary block

lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/DeltaByteArrayDecoders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/ShortDecimalFixedWidthByteArrayBatchDecoder.java, lib/trino-parquet/src/test/java/io/trino/parquet/reader/decoders/AbstractValueDecodersTest.java
Some files may contain empty dictionaries which when read can cause plain value decoders to be read with 0 length
```markdown
* Fix JVM crash when reading short decimal columns in parquet files containing empty dictionaries. ({issue}`19697`)
```
=> Fix reads of 0 length on parquet decoders

lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java, lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemConfig.java
I didn't add `@LegacyConfig` annotation as the module isn't yet released. 
=> Rename `gcs.projectId` to `gcs.project-id` config property

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryQueryPageSource.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Fixes https://github.com/trinodb/trino/issues/19570
```markdown
* Fix incorrect results when query involving projections and `query` table function. ({issue}`19570`)
```
=> Fix incorrect result of query table function with projection in BigQuery

docs/src/main/sphinx/routines/begin.md, docs/src/main/sphinx/routines/loop.md
Seems lilke the docs for LOOP was left wrong from a copy of REPEAT. This PR updates the docs and fixes a small linking error in BEGIN.
Thanks @findepi for finding.
=> Improve routine docs for loop and begin

pom.xml
This property was lost in ab1e89b4aa07077f2c8e7ca61719a1034457fb20 and is causing the release process to attempt to run all the tests.
=> Restore release preparation goals

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/util/UncheckedCloseable.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesFunction.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/DropExtendedStatsProcedure.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/RegisterTableProcedure.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/UnregisterTableProcedure.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMetadata.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/CreateEmptyPartitionProcedure.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/DropStatsProcedure.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/RegisterPartitionProcedure.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/SyncPartitionMetadataProcedure.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/UnregisterPartitionProcedure.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseS3AndGlueMetastoreTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveS3AndGlueMetastoreTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergS3AndGlueMetastoreTest.java
Ensure `cleanupQuery` is called for cases when `ConnectorMetadata` is constructed outside of typical query processing
(`Connector.getMetadata`).
=> Ensure cleanupQuery gets called for procedures

plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaConnectorFactory.java, plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaPlugin.java, plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/KafkaQueryRunner.java, plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/KafkaQueryRunnerBuilder.java
There's an order-dependent initialization of Guice modules happening within the Kafka plugin when they are added indirectly via "install()" that causes ConfigurationAwareModule to not consume the expected configuration properties.
Fixes #19702
=> Fix non-deterministic construction of Kafka plugin

core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
`QueryCatalogs.finish` synchronizes within method body, so method-level synchronization looks redundant.
=> Remove redundant synchronization around cleanupQuery

plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/CoercionUtils.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/TimestampCoercer.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcTypeTranslator.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveCoercionPolicy.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestTimestampCoercer.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnPartitionedTable.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnUnpartitionedTable.java
Add schema evolution from `timestamp` to `date` column types for hive tables.
Enable the Hive users to retrieve the information from their tables after performing queries which change `timestamp` columns to `date`.
Hive sample DDL query for changing the type of a `timestamp` column towards `date`:
```
ALTER TABLE mytable CHANGE COLUMN mycolumn mycolumn date;
```
This change enables Hive users to read the column data as `date` type even if the underlying type of the data stored in the column from the storage  is `timestamp` .
This is a mere adaptation of https://github.com/trinodb/trino/pull/16869 to match `timestamp` to `date` coercion
() Release notes are required. Please propose a release note for me.
(x) …
=> Add timestamp to date schema evolution for hive

plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveTestUtils.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBackgroundHiveSplitLoader.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestNodeLocalDynamicSplitPruning.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/file/TestingFileHiveMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPageSourceFactory.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestAcidTables.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestHiveAcidUtils.java
=> Use memory file system in some Hive tests

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcFailureRecoveryTest.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryFailureRecoveryTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaFailureRecoveryTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveFailureRecoveryTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveQueryFailureRecoveryTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveTaskFailureRecoveryTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergFailureRecoveryTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergQueryFailureRecoveryTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTaskFailureRecoveryTest.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoFailureRecoveryTest.java, plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlFailureRecoveryTest.java, plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleFailureRecoveryTest.java, plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/BasePostgresFailureRecoveryTest.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/BaseRedshiftFailureRecoveryTest.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftQueryFailureRecoverySmokeTest.java, plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerFailureRecoveryTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java, testing/trino-testing/src/main/java/io/trino/testing/ExtendedFailureRecoveryTest.java
=> Migrate tests to JUnit

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryFailureRecoveryTest.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/BaseRedshiftFailureRecoveryTest.java
Add missing `@Test` annotation
=> Add missing `@Test` annotation

core/trino-main/src/main/java/io/trino/connector/CatalogPruneTask.java, core/trino-main/src/main/java/io/trino/connector/CoordinatorDynamicCatalogManager.java, core/trino-main/src/main/java/io/trino/connector/StaticCatalogManager.java, core/trino-main/src/main/java/io/trino/connector/WorkerDynamicCatalogManager.java, core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java, core/trino-main/src/main/java/io/trino/metadata/CatalogManager.java, core/trino-main/src/main/java/io/trino/sql/planner/PlanFragment.java, core/trino-main/src/test/java/io/trino/connector/TestingLocalCatalogPruneTask.java, core/trino-main/src/test/java/io/trino/execution/TestSqlTaskManagerRaceWithCatalogPrune.java
There is a possible race condition between SqlTaskManager and
CatalogPruneTask on workers. Before the catalogs for a Task are set it
is possible for a active catalogs from the prune task to arrive, fail to be agumentted by the catalogs of the task, but then prune the catalogs after they are set and loaded. This fix uses a ReadWriteLock to ensure mutual exclusion of task catalog setting and task scanning/pruning.
The included test fails with this in the stack trace without the Read Lock
```
Caused by: java.lang.IllegalArgumentException: No catalog 'catalog_grvijxxnvr'
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:218)
at io.trino.connector.WorkerDynamicCatalogManager.getConnectorServices(WorkerDynamicCatalogManager.java:160)
at …
```
=> Fix possible race condition in Worker SqlTaskManager

plugin/trino-hive/src/main/java/io/trino/plugin/hive/SchemaAlreadyExistsException.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/TableAlreadyExistsException.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
This will be beneficial in case of detecting retry issues.
Currently in case of failure after retry (e.g createTable, dropTable) we have no information that it was consecutive attempt. After this  change exceptions from previous attempts will be visible in stack trace.
Example in case 2 attemps:
1. `ClientException`
2. `NoSuchObjectException`
Before:
```
io.trino.spi.connector.TableNotFoundException: Table 'test.test' not found
at io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastore.dropTable(ThriftHiveMetastore.java:1103)
at io.trino.plugin.hive.TestTriftHiveMetastore.testDropTable(TestTriftHiveMetastore.java:194)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at …
```
=> Add cause of failures in ThriftHiveMetastore

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
It's covered by BaseConnectorTest#testCreateTable.
=> Remove testCreateTableIfNotExists in BigQuery

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/AbstractMetastoreTableOperations.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergCreateTableInternalRetry.java
Ignore internal TableAlreadyExistsException in CREATE TABLE & register_table on Iceberg connector
Fixes https://github.com/trinodb/trino/issues/18308
```markdown
```
=> Ignore internal TableAlreadyExistsException in Iceberg

plugin/trino-hive/pom.xml, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/DefaultThriftMetastoreClientFactory.java
Use SslUtils.createSSLContext in Hive connector
=> Use SslUtils.createSSLContext in Hive connector

plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchange.java
It is not enforced by engine that each created sink will be finished. Some tasks may be abandoned as not required for computing query result and siks for those tasks will not be finished.
=> Do not require all sinks to be finished in FileSystemExchange

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
=> Add missing Test annotations

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
In order to reduce memory stress in DeltaLake by remove storing TableSnapshot.
It can be removed when query requests multiple tables and we know that this information will be not used anymore.
```markdown
```
=> Remove storing TableSnapshot when multiple tables queried

core/trino-main/src/main/java/io/trino/operator/FlatHashStrategyCompiler.java, core/trino-main/src/test/java/io/trino/operator/TestFlatHashStrategy.java
Adds special case handling of `RunLengthEncodedBlock` in generated `FlatHashStrategy` implementations that hoists the hash calculation outside of the loop. This has the added benefit of making the normal compute loop at most bi-morphic between `DictionaryBlock` and the type-corresponding `ValueBock` subclass.
`FlatGroupByHash` already specializes hash calculations for `RunLengthEncodedBlock` at a higher level when _all_ group by input blocks are run-length encoded, so this change will only affect performance for mutli-column grouping operations with a mix of run length and dictionary/plain block inputs.
( ) Release notes are required, with …
=> Specialize batched column-wise hashing for RunLengthEncodedBlock

docs/src/main/sphinx/connector/metastores.md, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/IcebergGlueCatalogConfig.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConfig.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogSkipArchive.java
Slack discussion: https://trinodb.slack.com/archives/CJ6UC075E/p1699927658771409
https://github.com/trinodb/trino/pull/14336
```markdown
```
=> Skip archiving in Glue an old table version during a table update operation

core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaMetadata.java, core/trino-main/src/main/java/io/trino/connector/system/SystemTablesMetadata.java, core/trino-main/src/test/java/io/trino/sql/planner/TestTableScanRedirectionWithPushdown.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushPredicateIntoTableScan.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestRemoveEmptyUnionBranches.java, core/trino-spi/src/main/java/io/trino/spi/connector/ConstraintApplicationResult.java, plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloMetadata.java, plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopMetadata.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java, plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxMetadata.java, plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaMetadata.java, plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java, plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileMetadata.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java, plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusMetadata.java, plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorMetadata.java, plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisMetadata.java, plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftMetadata.java, plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchMetadata.java
The new `ConnectorExpression`-based API was introduced long ago and is stable.
=> Deprecate old ConstraintApplicationResult constructor

core/trino-main/src/main/java/io/trino/split/SplitManager.java, core/trino-main/src/test/java/io/trino/split/TestBufferingSplitSource.java
Follows up after https://github.com/trinodb/trino/pull/19369 and ensures that the new `SplitManager` executor is shut down during cleanup so that threads aren't kept around unnecessarily in test environments.
=> Shutdown SplitSource executors during cleanup

plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHivePlugin.java
This is apparently the last `Test*Plugin` class to migrate.
=> Migrate TestHivePlugin to JUnit

docs/src/main/sphinx/admin/fault-tolerant-execution.md, docs/src/main/sphinx/connector/delta-lake.md
Fix broken link in doc.
https://trino.io/docs/433/admin/fault-tolerant-execution.html
https://trino.io/docs/433/connector/delta-lake.html
```
$ grep --include=\*.md -rn docs/src/main/sphinx -e ':ref:'
docs/src/main/sphinx/admin/fault-tolerant-execution.md:185:  - Maximum :ref:`time <prop-type-duration>` that a failed query or task must
docs/src/main/sphinx/connector/delta-lake.md:1058:  - Sets the initial :ref:`prop-type-data-size` for a single read section
docs/src/main/sphinx/connector/delta-lake.md:1064:  - Sets the largest :ref:`prop-type-data-size` for a single read section
``` …
=> Fix broken link in doc

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryColumnHandle.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryFilterQueryBuilder.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPseudoColumn.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryType.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ColumnMapping.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/Conversions.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Pushdown predicates fully in BigQuery connector
=> Pushdown predicates fully in BigQuery connector

lib/trino-cache/src/main/java/io/trino/cache/CacheUtils.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/TrinoNessieCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
Metadata queries such as `information_schema.columns`,
`system.jdbc.columns` or `system.metadata.table_comments` may end up
loading arbitrary number of relations within single query (transaction).
It is important to bound memory usage for such queries.
In case of Iceberg Hive metastore based catalog, this is already done in
`TrinoHiveCatalogFactory` bu means of configuring per-query
`CachingHiveMetastore`. However, catalogs with explicit caching need
something similar.
=> Limit session state during metadata queries in Iceberg

client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcExternalAuthentication.java, client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcPreparedStatement.java, client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcWarnings.java, client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDatabaseMetaData.java, client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriver.java, client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverAuth.java, core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java, core/trino-main/src/test/java/io/trino/server/security/oauth2/BaseOAuth2WebUiAuthenticationFilterTest.java, core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithRefreshTokens.java, testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
=> Fix announcement delay for TestingTrinoServer

.github/workflows/ci.yml, plugin/trino-bigquery/pom.xml
Separate profile for BigQuery FTE tests to fix timeout issue on CI. 
e.g. https://github.com/trinodb/trino/actions/runs/6882906460/job/18722457149
=> Run BigQuery Arrow and FTE tests in a separated profile

testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
When `BaseConnectorTest` implementation declares that it does not have `SUPPORTS_CREATE_FUNCTION` behavior, verify this is true.
=> Verify negative SUPPORTS_CREATE_FUNCTION declarations

core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java, docs/src/main/sphinx/develop/client-protocol.md
There is no such header. Only `X-Trino-User` and `X-Trino-Original-User` exist.
Follows https://github.com/trinodb/trino/pull/16067
=> Fix X-Trino-Authorization-User typo

lib/trino-parquet/src/main/java/io/trino/parquet/Column.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java, lib/trino-parquet/src/test/java/io/trino/parquet/ParquetTestUtils.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointFieldReader.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSource.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
Extract fields by names in CheckpointEntryIterator
=> Extract fields by names in CheckpointEntryIterator

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryColumnHandle.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPseudoColumn.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/Conversions.java
Remove unused fields from BigQueryColumnHandle
=> Remove unused fields from BigQueryColumnHandle

client/trino-client/pom.xml, core/trino-server/pom.xml, lib/trino-filesystem-gcs/pom.xml, plugin/trino-atop/pom.xml, testing/trino-benchmark-queries/pom.xml
`junit-extensions` is necessary safety extensions to JUnit, preventing JUnit "UX trap" which makes overridden tests silently skipped. It should be on every module's classpath.
For the record, the modules were identified using
find -name pom.xml | grep -vFxf <(find -name pom.xml -exec grep -l junit-extensions {} +)
=> Add junit-extensions to test classpaths

core/trino-main/src/main/java/io/trino/metadata/InternalNode.java, core/trino-spi/src/main/java/io/trino/spi/Node.java, core/trino-spi/src/main/java/io/trino/spi/PageSorter.java, core/trino-spi/src/main/java/io/trino/spi/type/CharType.java, core/trino-spi/src/main/java/io/trino/spi/type/TimeWithTimeZoneType.java, core/trino-spi/src/main/java/io/trino/spi/type/VarbinaryType.java
Commit https://github.com/trinodb/trino/commit/d2289252054151d634e10311301c831d269c98d4 un-deprecated
`PageSorter` and it looks like an omission not to un-deprecate it's only
sorting method.
=> Mark PageSorter.sort supported method 

docs/src/main/sphinx/connector/iceberg.md
Unlike in the Delta Lake connector, `iceberg.extended-statistics.enabled` and `iceberg.extended-statistics.collect-on-write` and their respective session properties `extended_statistics_enabled` and `collect_extended_statistics_on_write` have not been documented yet.
=> Document missing extended-statistics properties in Iceberg connector

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsReader.java
Before Iceberg library gained Puffin stats, Trino would store table stats in Iceberg table properties. This became obsoleted in Trino 405 (released in Dec 2022).  Dropping support for old stats format means need to re-analyze tables that haven't been written to by Trino 405 or newer.
Follows https://github.com/trinodb/trino/pull/15400
Closes https://github.com/trinodb/trino/issues/15397
=> Remove support for pre-Puffin Iceberg stats

plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java
This assertion is very flaky. 
* https://github.com/trinodb/trino/actions/runs/6917923717/job/18819649888
* https://github.com/trinodb/trino/actions/runs/6915463195/job/18814547820
* https://github.com/trinodb/trino/actions/runs/6908111038/job/18796796145
* https://github.com/trinodb/trino/actions/runs/6902927701/job/18780927471
* https://github.com/trinodb/trino/actions/runs/6895970745/job/18761216931
* https://github.com/trinodb/trino/actions/runs/6887981728/job/18736205983
=> Remove flaky assertion in SQL Server testCreateTableAsSelectWriteBulkiness

core/trino-main/src/main/java/io/trino/operator/FlatHashStrategyCompiler.java, core/trino-main/src/main/java/io/trino/operator/scalar/CombineHashFunction.java
Refactors `RunLengthEncodedBlock` column-wise hash calculations to call a common implementation of the hash combination loop instead of directly embedding the same loop logic in each method of generated code. This reduces overall code size and JIT warm-up time for RLE hash handling.
Follows up from https://github.com/trinodb/trino/pull/19723
=> Refactor RunLengthEncodedBlock hash combination logic

core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/TrinoViewHiveMetastore.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
Table/view not found can be indicated by `TrinoException` with `TABLE_NOT_FOUND` error code, but also by `TableNotFoundException` or `ViewNotFoundException` exceptions (both using `NOT_FOUND` error code). The code catching "not found" exceptions should catch all three.
=> Catch all "not found" exceptions

core/trino-main/src/main/java/io/trino/operator/scalar/CombineHashFunction.java
Fixes a bug introduced in https://github.com/trinodb/trino/pull/19759 that would accidentally loop from `0` instead of `fromIndex`. This has no correctness implications because currently `fromIndex` is always `0`, but might cause issues in the future if other usages are added.
=> Fix loop index range in CombineHashFunction

docs/src/main/sphinx/sql/merge.md
A bit of formatting and some additional explanation.
=> Improve docs for MERGE

docs/src/main/sphinx/functions/window.md
The doc should make it clear that the `ORDER BY` clause in an aggregate function is not supported, if the aggregate function is used as a window function.
For example, this works:
```
SELECT ARRAY_AGG(phone) OVER (PARTITION BY custkey) FROM customer
```
while this one fails:
```
SELECT ARRAY_AGG(phone ORDER BY phone) OVER (PARTITION BY custkey) FROM customer
line 1:59: PARTITION BY expression 'custkey' must be an aggregate expression or appear in GROUP BY clause
```
=> Improve doc for Window functions

core/trino-main/src/main/java/io/trino/json/ir/IrLiteral.java, core/trino-main/src/main/java/io/trino/sql/planner/Partitioning.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/StatisticAggregationsDescriptor.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/TableScanNode.java, core/trino-main/src/main/java/io/trino/sql/relational/ConstantExpression.java, core/trino-spi/src/main/java/io/trino/spi/SplitWeight.java, core/trino-spi/src/main/java/io/trino/spi/function/FunctionDependencyDeclaration.java, core/trino-spi/src/main/java/io/trino/spi/function/FunctionMetadata.java, core/trino-spi/src/main/java/io/trino/spi/function/LongVariableConstraint.java, core/trino-spi/src/main/java/io/trino/spi/function/Signature.java, core/trino-spi/src/main/java/io/trino/spi/function/TypeVariableConstraint.java, core/trino-spi/src/main/java/io/trino/spi/function/table/ScalarArgument.java, core/trino-spi/src/main/java/io/trino/spi/predicate/NullableValue.java, core/trino-spi/src/main/java/io/trino/spi/predicate/SortedRangeSet.java, core/trino-spi/src/main/java/io/trino/spi/predicate/TupleDomain.java, core/trino-spi/src/main/java/io/trino/spi/statistics/ColumnStatisticMetadata.java, plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloSplitManager.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/QueryParameter.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/DeltaLakeColumnStatistics.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HivePageSinkMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableHandle.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/optimizer/TestConnectorPushdownRulesWithIceberg.java, plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduClientSession.java
The information was not correct when ANALYZE was invoked without
`columns` parameter -- instead of all columns, an empty set was there.
The information can be replaced with a single boolean.
=> Remove redundant analyzeColumns from IcebergTableHandle

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeSharedMetastoreViewsTest.java
testNonDeltaTablesCannotBeAccessed was flaky because BaseDeltaLakeConnectorSmokeTest uses metadata cache. 
Fixes #19799
=> Move testNonDeltaTablesCannotBeAccessed in Delta Lake

core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaPageSource.java, core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, testing/trino-tests/src/test/java/io/trino/connector/informationschema/TestInformationSchemaConnector.java
Prevent passing impossible names down to the connectors.
E.g. prevents failures if a connector chooses to convert input to
something that validates name is not impossible, like
`SchemaTablePrefix`.
=> Unify and supplement short-circuiting in MetadataManager

core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
Simplify MetadataManager::getMaterializedView
Mixing handling of absence of object and catalog security in one 'if'
block was misleading. These two things are separate and unrelated so
the best if they handled in separately.
=> Simplify MetadataManager::getMaterializedView

client/trino-jdbc/pom.xml, plugin/trino-oracle/pom.xml, plugin/trino-resource-group-managers/pom.xml, pom.xml
19.x series have long-term support and bugfixes
which isn't the case for the 21.x being "innovative release"
I believe this is my first "downgrade PR" :)
=> Downgrade Oracle JDBC driver to LTS 19.21.0.0

plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/storage/organization/TestShardOrganizationManager.java, plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/storage/organization/TestShardOrganizer.java
There was a race, the test job was sleeping for only 10ms. However, since GC pause is possible, sleeping "long enough" should be measured in seconds. Use a latch for synchronization instead of fixed sleep time.
Fixes https://github.com/trinodb/trino/issues/11252
=> Fix TestShardOrganizer.testShardOrganizerInProgress flakiness

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeTableFunctionProcessorProvider.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeTableFunctionSplitProcessor.java, lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/classloader/TestClassLoaderSafeWrappers.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeFunctionProvider.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesProcessorProvider.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConnector.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/NoopFunctionProvider.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/IcebergFunctionProvider.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesFunctionProcessorProvider.java
Adding missing ClassLoaderSafeTableFunctionProcessorProvider and ClassLoaderSafeTableFunctionSplitProcessor
Also refactoring ConnectorTableFunction binding in Hive.
Lack of usage of `ClassLoaderSafe..` may have resulted in queries failure when some criterias were met:
- data was stored on hdfs
- query involved table function that used either `TableFunctionProcessorProvider` or `TableFunctionSplitProcessor` or both
- query was the first query touching hdfs that was run on the node after it started
In such case trino would fail to instantiate specific FileSystem and query would fail
(x) Release notes are required, with the following suggested …
=> Add missing ClassLoaderSafe and refactor ConnectorTableFunction binding in Hive

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeViewsGlueMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueInputConverter.java
Avoid stripping the `comment` parameter for views and materialized views.
Fixes https://github.com/trinodb/trino/issues/19771
Fixes issue introduced by https://github.com/trinodb/trino/pull/19073
```markdown
```
=> Fix listing views in Delta with Glue

docs/src/main/sphinx/connector/mariadb.md, plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbConnectorTest.java, plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbLatestConnectorSmokeTest.java, plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestingMariaDbServer.java
Update the docker image version to remove support for old versions https://endoflife.date/mariadb
=> Change latest connector test to smoke test in MariaDB

core/trino-main/src/main/java/io/trino/operator/output/PositionsAppenderPageBuilder.java, core/trino-main/src/main/java/io/trino/operator/output/PositionsAppenderSizeAccumulator.java, core/trino-main/src/main/java/io/trino/operator/output/UnnestingPositionsAppender.java, core/trino-main/src/test/java/io/trino/operator/output/TestPositionsAppenderPageBuilder.java
Fixes a number of issues with the flushing behavior of `PositionsAppenderPageBuilder` and related classes. The fixes are:
1. To consider `PositionsAppenderPageBuilder` to be full after at least 4x `PageProcessor.MAX_BATCH_SIZE` (4 * 8192 = 32,768) positions have been inserted, regardless of the current size in bytes. The previous behavior of only considering the builder full when `declaredPositions == Integer.MAX_VALUE` was unsafe since `PositionsAppenderPageBuilder#isFull()` is only checked after inserting an entire page not after each row, so integer overflows could occur.
2. Accounting for the size of at least the current dictionary ids in `UnnestingPositionsAppender` when in dictionary mode, even though the size of the actually referenced entries is still not tracked. Previously, …
=> Fix partitioned output page flushing

core/docker/build.sh
=> Allow specifying custom JDK version for docker image build

core/trino-spi/src/main/java/io/trino/spi/function/ScalarFunctionAdapter.java
=> Fix invalid boolean expression in ScalarFunctionAdapter.adaptParameter

docs/src/main/sphinx/routines/examples.md
Removes duplicate 'are' in docs for sql routines
```markdown
```
=> Remove duplicate 'are' in docs for sql routine examples

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
Theoretically it is possible that all task partitions for a stage
complete before we get noMorePartitions signal from SplitAssigner.
In such case we should execute same finish routie as we do when last
task partition completes and noMorePartitions is already set.
This is cleanup, not a bugfix as currently no SplitAssigner
(even though it is not guaranteed by interface) would seal
all of the task partitions without returning noMorePartitions flag in
the same AssignmentResult object.
=> Properly finish stage on noMorePartitions signal

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcConfig.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadataFactory.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestBaseJdbcConfig.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java
Apply `CachingHiveMetastore` capabilities in JDBC. Allow turning on
statistics caching without having to use caching for all of the
metadata. In common case caching statistics has much fewer side effects
than caching other stuff.
=> Allow caching stats in JDBC but not metadata 

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastoreConfig.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/SharedHiveMetastoreCache.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastoreConfig.java
Remove the logic that would ignore `hive.metastore-stats-cache-ttl` set by the user, if the chosen value was less than the `hive.metastore-cache-ttl` value.
The logic's purpose was considered necessary to enable statistics cache by default, but the same goal can be achieved differently, by applying default value (fixed duration or `hive.metastore-cache-ttl` whichever is greater) only if the parameter was not set explicitly.
=> Respect hive.metastore-stats-cache-ttl is explicitly set

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcConnectorTest.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java, plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java, plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorTest.java, plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
This test covers an important aspect of Trino connectors -- metadata
listing should work also while tables/views/materialized views are being
created or dropped. It helped discover real problems, e.g.
- in Iceberg, that's why it was created
- in Kudu: https://github.com/trinodb/trino/issues/12974,
- in SQL Server https://github.com/trinodb/trino/blob/8edaa86c6b43e5f5fe03bb9427d3f26439a60d15/plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java#L151-L152
However, this turned out to be hard to test. The existing test is pretty complicated, takes a lot of time, has high timeout value and remains one of the more flaky tests. The test author does not know how to make it robust and perhaps does not want to remain as the author of the top flaky test in …
=> Remove testReadMetadataWithRelationsConcurrentModifications test

plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
Fix ArrayIndexOutOfBoundsException when using parquet ignore statistics. (https://github.com/trinodb/trino/issues/19760)
Add unit tests.
parquetTupleDomains and parquetPredicates are empty when ignore statistics is used, can cause exception. 
```markdown
* Fix some things. ({issue}`19760`)
```
=> Fix ArrayIndexOutOfBoundsException when parquet statistics are ignored

core/trino-spi/src/main/java/io/trino/spi/type/DoubleType.java, core/trino-spi/src/main/java/io/trino/spi/type/RealType.java, core/trino-spi/src/test/java/io/trino/spi/predicate/TestTupleDomain.java
Fixes https://github.com/trinodb/trino/issues/19828
```markdown
* Fix incorrect results for queries involving comparisons between `double` and `real` zero and negative zero. ({issue}`19828`)
```
=> Fix incorrect comparison for negative zero

lib/trino-cache/src/test/java/io/trino/cache/TestEvictableCache.java
For TestNG we have a detection reporting unannotated test methods (`ReportBadTestAnnotations`), but apparently the annotation disappeared when migrating to JUnit.
=> Add missing `@Test` annotations

docs/src/main/sphinx/functions/array.md
Add additional document for function `array_join(x, delimiter)`
Fix #17521
( x ) This is not user-visible or is docs only, and no release notes are required.
=> Add document for array_join(x, delimiter)

plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java
=> Fix TestMySqlTypeMapping.testTimeFromMySql

core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/filter/UtcConstraintExtractor.java, lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/filter/TestUtcConstraintExtractor.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ConstraintExtractor.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestConstraintExtractor.java, testing/trino-tests/src/test/java/io/trino/tests/BaseQueryAssertionsTest.java, testing/trino-tests/src/test/java/io/trino/tests/TestLocalQueryAssertions.java
Certain expressions involving TIMESTAMP WITH TIME ZONE can be optimized in Delta Lake connector based on the fact that columns of type TIMESTAMP WITH TIME ZONE are represented using the UTC time zone:
- `date_trunc('...', timeztamp_tz_column) <comparison> constant`
- `CAST(timestamp_tz_column AS DATE) <comparison> constant`
- `year(timestamp_tz_column) <comparison> constant`
The optimization is based on similar optimization in the Iceberg connector.
Fixes https://github.com/trinodb/trino/issues/18664
```markdown
* Pushdown filters involving columns of type TIMESTAMP WITH …
```
=> Push down predicate involving timestamp_tz in Delta Lake

core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java, core/trino-main/src/test/java/io/trino/execution/TestTaskManagerConfig.java
Partially revert #19487, reduce regressions in tpch q18/q21
```markdown
```
=> Partial revert of increase split scheduling config

docs/src/main/sphinx/sql/create-catalog.md
As result of testing and discussion slack https://trinodb.slack.com/archives/CGB0QHWSW/p1699634554649649
Turns out the env variable is not resolved and propagated to the workers, but the value of the properties is left as is .. so kinda less dynamic for this scenario. But maybe more secure... worth thinking about if this is by design or a bug maybe @dain .. I can think of pros and cons for each
```markdown
```
=> Correct secret usage with dynamic catalogs

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformUncorrelatedSubqueryToJoin.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformUncorrelatedSubqueryToJoin.java
It's possible to simplify outer join to inner
join when subquery side is at least scalar.
This makes sure dynamic filters are propagated
to left join side and more efficient (cross join)
implementaiton is used.
```markdown
* Fix performance regression caused by suboptimal scalar subquries planning. ({issue}`19922`)
```
=> Convert left correlated join to inner join during transformation

plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorTest.java
Redshift seems to have introduced a third kind of AUTO diststyle , so include that in the check where we evaluate the current diststyle for the table from Redshift
```markdown
```
=> Fix diststyle check in redshift test to include AUTO(KEY) kind

docs/src/main/sphinx/connector/iceberg.md
=> Remove misleading header in Iceberg docs

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreCreateTableFailure.java
```
Error:  io.trino.plugin.iceberg.catalog.file.TestIcebergFileMetastoreCreateTableFailure.testCreateTableFailureMetadataCleanedUp -- Time elapsed: 0.014 s <<< FAILURE!
java.lang.AssertionError: 
Expecting throwable message:
"Test-simulated metastore runtime exception"
to contain:
"Test-simulated metastore schema not found exception"
but did not.
```
https://github.com/trinodb/trino/actions/runs/7010135638/job/19071177674
=> Fix flaky TestIcebergFileMetastoreCreateTableFailure

plugin/trino-cassandra/pom.xml, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraServer.java, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestDatastaxConnectorSmokeTest.java, plugin/trino-cassandra/src/test/resources/cassandra-dse.yaml, plugin/trino-cassandra/src/test/resources/cu-cassandra-latest.yaml, plugin/trino-cassandra/src/test/resources/cu-cassandra.yaml
=> Use CassandraQueryWaitStrategy in CassandraServer

plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/BaseRaptorConnectorTest.java, plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/TestRaptorBucketedConnectorTest.java, plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/TestRaptorConnectorTest.java, plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/TestRaptorMySqlConnectorTest.java
=> Disable compaction in Raptor connector test

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSource.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSource.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSource.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSource.java, plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSource.java, plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiPageSource.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPageSource.java
Implement missing overrides in delegating ConnectorPageSource implementations
```markdown
```
=> Implement missing overrides in delegating ConnectorPageSource

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPageSink.java
https://cloud.google.com/java/docs/reference/google-cloud-bigquerystorage/latest/com.google.cloud.bigquery.storage.v1.BigQueryWriteClient
> Note: close() needs to be called on the BigQueryWriteClient object to clean up resources such as threads. In the example above, try-with-resources is used, which automatically calls close().
There were many error messages. 
```
2023-11-28T08:29:47.2348239Z 2023-11-28T02:29:47.167-0600	ERROR	Query-20231128_082946_00774_4nskn-4231	io.grpc.internal.ManagedChannelOrphanWrapper	*~*~*~ Previous channel {0} was not shutdown properly!!! ~*~*~*
2023-11-28T08:29:47.2349674Z     Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
2023-11-28T08:29:47.2350470Z java.lang.RuntimeException: ManagedChannel allocation site …
```
=> Close BigQueryWriteClient in BigQueryPageSink

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcMetadata.java, plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java, plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleConnectorTest.java, plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java, plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java, plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
Follow-up to https://github.com/trinodb/trino/commit/5e520fcea34149c223090b51f781e93f73165a76.
```markdown
* Fix possible query failures when join is pushed down.
```
=> Allow different synthetic column name length limits in JDBC connectors

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
The ISO_INSTANT use before the change does not render seconds fraction when it is zero, so the test failed when snapshot happened to be committed at a whole second.
Fixes https://github.com/trinodb/trino/issues/19242
=> Fix timestamp precision in Iceberg testTableChangesFunction

core/trino-main/src/main/java/io/trino/execution/SqlStage.java, core/trino-main/src/main/java/io/trino/execution/buffer/SpoolingOutputBuffers.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/ArbitraryDistributionSplitAssigner.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenTaskSource.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/FaultTolerantPartitioningScheme.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/HashDistributionSplitAssigner.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/SingleDistributionSplitAssigner.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/SplitAssigner.java, core/trino-main/src/main/java/io/trino/split/BufferingSplitSource.java, core/trino-main/src/main/java/io/trino/split/TracingSplitSource.java, core/trino-main/src/test/java/io/trino/exchange/TestExchangeSourceOutputSelector.java, core/trino-spi/src/main/java/io/trino/spi/exchange/ExchangeContext.java, core/trino-spi/src/main/java/io/trino/spi/exchange/ExchangeSourceOutputSelector.java, plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchange.java, plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeSinkInstanceHandle.java, testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
Add code which will dump log debug information in case FTE scheduler is not getting any events for 10 minutes. This is to track rare bug where we observe queries running with retry_policy set to FALSE stuck sometimes.
TODO:
=> Add diagnostics for stuck FTE scheduler

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
After Trino 423, Trino could not remove redundant ORDER BY in CREATE TABLE AS and INSERT queries.
For CTAS, https://github.com/trinodb/trino/commit/87f405abfda500a544ee399ca7dc768d1f165388 has fixed the issue. We should remove redundant ORDER BY in INSERT query also
```markdown
* Improve performance of INSERT ... SELECT queries that contain a redundant ORDER BY clause.
```
=> Remove redundant ORDER BY in INSERT queries

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalogFactory.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestTrinoGlueCatalog.java
In HiveCatalog we don't set owner for materialized views when system security is enabled. Here I am just making glue behave the same way
```markdown
* Don't set owner for glue materialized views when system security is enabled ({issue}`issuenumber`)
```
=> Don't set materialized view owner for IcebergGlueCatalog for system security

plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java, plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java, plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java, plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java, testing/trino-tests/src/test/java/io/trino/tests/TestQuerySerializationFailures.java
The `@Flaky` was honored by TestNG runner (via
`FlakyTestRetryAnalyzer`), but is ignored on JUnit tests, so should be removed.
This removes references and hopefully closes https://github.com/trinodb/trino/issues/4173
This removes references and hopefully closes https://github.com/trinodb/trino/issues/8691
Relates to https://github.com/trinodb/trino/issues/14391, https://github.com/trinodb/trino/issues/10846
=> Remove useless `@Flaky` from JUnit tests

core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestArbitraryDistributionSplitAssigner.java, core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestingConnectorSplit.java, core/trino-spi/src/main/java/io/trino/spi/SplitWeight.java
Prevent calls to a non-API method that exists for JSON serialization only.
=> Seal SplitWeight API

testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
This also updates links from
https://github.com/trinodb/trino/issues/4927 to
https://github.com/trinodb/trino/issues/16315, as the former was closed in favor of the latter.
=> Annotate more TestHiveTransactionalTable methods for retries 

docs/src/main/sphinx/routines/function.md, docs/src/main/sphinx/routines/introduction.md
Minor clean up and improvements while I work on the training material for SQL routines.
=> Improve SQL routine docs

docs/src/main/sphinx/functions.md, docs/src/main/sphinx/language/types.md
Provide more info for custom types and functions right in the overview. We don't have a concepts section for SQL support itself .. so this is probably better than adding something to  https://trino.io/docs/current/overview/concepts.html
na
=> Link to custom types and functions

docs/src/main/sphinx/functions/json.md
Result from https://trinodb.slack.com/archives/CGB0QHWSW/p1696370762782869
=> Clarify json_path requirement

docs/src/main/sphinx/release.md, docs/src/main/sphinx/release/release-434.md
Assemble the release notes for the 434 release.
Fixes #19704 
* #19692 ✅ rn ✅ docs
* #19703 ✅ rn ✅ docs
* #19680 ✅ rn ✅ docs
* #19691 ✅ rn ✅ docs
* #19676 ✅ rn ✅ docs
* #19513 ✅ rn ✅ docs
* #19664 ✅ rn ✅ docs
* #19709 ✅ rn ✅ docs
* #19713 ✅ rn ✅ docs
* #19714 ✅ rn ✅ docs
* #19683 ✅ rn ✅ docs
* #19655 ✅ rn ✅ docs
* #19718 ✅ rn ✅ docs
* #19650 ✅ rn ✅ docs
* #19711 ✅ rn ✅ docs
* #19667 ✅ rn ✅ docs
* #19667 ✅ rn ✅ docs
* #19728 ✅ rn ✅ docs
* #19734 …
=> Add Trino 434 release notes

plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotSegmentPageSource.java, plugin/trino-pinot/src/test/resources/pinot-server/pinot-server.conf
Pinot DataTableV4 has a different implementation for reading Bytes:
- V2/V3 uses hex string to represent bytes,
- V4 directly uses var length bytes encoding.
This PR will check the implementation of DataTable then pick the right method to read it.
=> [pinot connector]Support pinot connector to read DataTableV4 bytes

docs/src/main/sphinx/connector/delta-lake.md
Enhance description for `delta.checkpoint-filtering.enabled`
```markdown
```
=> Enhance description for `delta.checkpoint-filtering.enabled`

core/trino-main/src/main/java/io/trino/eventlistener/EventListenerManager.java, core/trino-main/src/test/java/io/trino/eventlistener/TestEventListenerManager.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/EventListener.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeEventListener.java
@PreDestroy and @PostCreate annotations are processed on EventListener methods.
( X ) This is not user-visible or is docs only, and no release notes are required.
=> Add shutdown to EventListener

docs/src/main/sphinx/connector/hive.md, docs/src/main/sphinx/release/release-0.153.md, lib/trino-hive-formats/src/main/java/io/trino/hive/formats/rcfile/RcFileWriter.java, lib/trino-hive-formats/src/test/java/io/trino/hive/formats/rcfile/RcFileTester.java, plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/conf/AccumuloTableProperties.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateSchemaInternalRetry.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateTableInternalRetry.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/RcFileFileWriterFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/TrinoViewUtil.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/acid/AcidSchema.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/AvroFileWriterFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HivePrincipal.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcFileWriterFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/RegisterPartitionProcedure.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/SyncPartitionMetadataProcedure.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveLocal.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveCreateSchemaInternalRetry.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergCreateTableInternalRetry.java, plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/ImplementRedshiftAvgDecimal.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHivePropertiesTable.java
```markdown
* Rename `presto_version` table property to `trino_version`. ({issue}`issuenumber`)
* Rename `presto_query_id` table property to `trino_query_id`. ({issue}`issuenumber`)
```
=> Rename some legacy presto items to trino

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemFactory.java
S3FileSystemFactory STSClient does not use the trino configured AWS access key/secret to connect to STS.
This is an [unintentional] change in behavior from TrinoS3Filesystem which uses the configured trino AWS access key/secret to connect to STS.
I was able to manually test this fix locally by:
- creating an AWS user with permissions to assume a role, but no other permissions
- creating a role with permissions to read/write to an s3 bucket
- configuring the iceberg connector to use the native-s3 filesystem with the above user access credentials and role and then successfully reading/writing tables to the s3 bucket
() Release notes are …
=> Make S3FileSystemFactory use configured AWS access keys for STS calls

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryOptionsConfigurer.java
When reading through the BigQuery metadata class, it's hard to spot where exactly we map Trino schemas to BigQuery datasets, especially with the code that disambiguates them. This refactor is supposed to make it more explicit.
=> Make mapping of Trino schema to BigQuery dataset more explicit

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
```markdown
* Fix incorrect removal of statistics files when executing `remove_orphan_files`. ({issue}`19965`)
```
=> Fix removal of stats files in Iceberg orpan file cleanup

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
Ignore failure within stage execution if it already done. This is to work around the problem which was introduced with https://github.com/trinodb/trino/commit/39b04491c05. With that change we close EventDrivenTaskSource when stage completes, and as a result of that it may emit an failure event due to internall processes being cancelled.
Handling of event in `StageExecution.fail()` did close a number of objects needed for query completion (see createStageExecutionCloser()). As a result the query could hang.
=> Do not fail stage after already done

docs/src/main/sphinx/functions/datetime.md
Somehow the output is currently not displayed. 
Changing to js:function fixes the render but makes the output parameter italics.
The upper approach gets rid of using of a Sphinx domain and just hardcodes the output. But then we need to add an anchor and also the indent of the function gets lost.
If we truly want to control this stuff we need to add a new SQL or even Trino SQL domain as extensions or even as contribution to sphinx. Thats quite a lot of work though.. 
https://www.sphinx-doc.org/en/master/usage/domains/index.html
https://github.com/sphinx-doc/sphinx/tree/master/sphinx/domains
=> Fix docs render for date_parse

core/docker/build.sh
While running the docker image build on a new fresh laptop, I just noticed that `build.sh` script requires `jq` to be installed. Added a `jq` existence check in the earlier portion of the build script, so that the build fails faster and it is more obvious that it's required.
With the change the script outputs the following when `jq` doesn't exist.
```
+++ dirname ./build.sh
++ cd .
++ pwd
+ SCRIPT_DIR=<trino-base-dir>/trino/core/docker
+ cd <trino-base-dir>/trino/core/docker
+ SOURCE_DIR=<trino-base-dir>/trino/core/docker/../..
+ ARCHITECTURES=(amd64 arm64 ppc64le)
+ TRINO_VERSION=
++ cat <trino-base-dir>trino/core/docker/../../.java-version
+ JDK_VERSION=21.0
+ getopts :a:h:r:j: o
+ shift 0
+ check_environment
+ command -v jq
+ echo 'Please install jq'
Please install jq
+ exit 1
``` …
=> Ensure jq exists before executing the script

core/trino-main/src/main/java/io/trino/sql/planner/SubqueryPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedScalarSubquery.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PlanNodeDecorrelator.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedJoinToJoin.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedScalarSubquery.java
EnforceSingleRowNode guarantees that exactly single row is produced. Therefore, PlanNodeDecorrelator was incorrectly removing EnforceSingleRowNode even if decorrelated subplan could produce 0 rows.
Additionally, TransformCorrelatedJoinToJoin was completing with TransformCorrelatedScalarSubquery to decorrelate EnforceSingleRowNode.
This changes removes support for EnforceSingleRowNode from PlanNodeDecorrelator and makes TransformCorrelatedScalarSubquery the only rule that (correctly) decorrelates that node.
=> Remove EnforceSingleRowNode support from PlanNodeDecorrelator

core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java
=> Cleanup JSON response from TaskInfoFetcher

core/trino-main/src/main/java/io/trino/execution/QueryStateMachine.java
outputTaskFailureListeners were referencing QueryScheduler which are retaining references to HttpRemoteTask instances and other query runtime objects. This was considered a memory leak.
Before:
After this PR references to `HttpRemoteTask` are gone
=> Cleanup outputTaskFailureListeners on query complete

docs/src/main/sphinx/routines/examples.md
This PR adds a new example to the Trino Routines Examples page.
The new example routine is named `from_date_string`. It takes a date string represented by `VARCHAR` and tries to best effort parse it into `TIMESTAMP`. 
The parsing logic assumes the date string is in one of the `YYYYmmdd`, `YYYYmmddHH`, or ISO 8601 formats.
Use case: Hive table partitions are typically represented in one of these formats. It's cumbersome to figure out which date string format is used on a specific table. This routine takes care of the date string parsing regardless of the format. 
Saw https://trino.io/blog/2023/11/09/routines and wanted to give the new routines a try
( ) Release notes are required. Please propose a release note …
=> Add `from_date_string` as example Trino routine

core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedQueryScheduler.java, core/trino-main/src/main/java/io/trino/metadata/GlobalFunctionCatalog.java, core/trino-main/src/main/java/io/trino/metadata/InternalFunctionBundle.java, core/trino-main/src/main/java/io/trino/metadata/LanguageFunctionManager.java, core/trino-main/src/main/java/io/trino/operator/TaskContext.java, core/trino-main/src/main/java/io/trino/operator/window/matcher/IrRowPatternToProgramRewriter.java, core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java, core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedGlobalAggregationWithProjection.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedGlobalAggregationWithoutProjection.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedScalarSubquery.java, core/trino-main/src/main/java/io/trino/sql/planner/rowpattern/LogicalIndexPointer.java, core/trino-main/src/main/java/io/trino/util/StatementUtils.java, core/trino-main/src/test/java/io/trino/block/BlockAssertions.java, core/trino-parser/src/main/java/io/trino/sql/tree/FunctionCall.java, core/trino-parser/src/main/java/io/trino/sql/tree/PlanSiblings.java, core/trino-parser/src/main/java/io/trino/sql/tree/SkipTo.java, core/trino-parser/src/main/java/io/trino/sql/tree/WindowOperation.java, lib/trino-orc/src/main/java/io/trino/orc/reader/ColumnReaders.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/NestedColumnReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FlatColumnReader.java, lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FlatDefinitionLevelDecoder.java, lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetTypeVisitor.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSource.java, testing/trino-testing/src/main/java/io/trino/testing/statistics/StatsContext.java
Replaces string concatenation with message formatting for usages of `checkArgument` throughout the codebase.
=> Avoid concatenation in checkArgument messages

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Remove a condition that can potentially lead to an infinite loop at `IterativeOptimizer`.
When this condition was added, `constraint.getPredicateColumns()` was always empty when the rule was running within iterative optimizer (see discussion at https://github.com/trinodb/trino/pull/17263/files#r1189575899) but this is not the case since https://github.com/trinodb/trino/pull/16019/files#diff-624ea155d75175ba8802d5f93af759bdb88c6f63f1ca9660d6704892e1033f1dR814-R825. According to my check, we don't see an infinite loop only because `io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan#arePlansSame` returns `true` and stops the iterative process. If in the future `io.trino.plugin.iceberg.IcebergTableHandle#equals` will return `false` when comparing 2 tables of 2 different …
=> Fix potential infinite loop at IterativeOptimizer with Iceberg

core/trino-main/src/main/java/io/trino/memory/MemoryPool.java, core/trino-main/src/main/java/io/trino/memory/QueryContext.java
This will increase the performance of `getQueryMemoryReservation(queryId)` method since that is called from every different local exchange thread.
Extracted from https://github.com/trinodb/trino/pull/19649
```markdown
```
=> Use concurrent hash map for tracking query memory

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointEntryIterator.java
Test used to ensure that the partition filtering is working also when using composed partition keys.
Follow-up for https://github.com/trinodb/trino/pull/19588
```markdown
```
=> Test checkpoint filtering on table with multiple partition fields

README.md
Update README to suggest turning SELinux off, to get rid of errors like this:
```
Configuration error:
config directory doesn't contain a conf.py file (/docs/src/main/sphinx)
```
```markdown
```
=> Mention SELinux in README Docker section

docs/build
If SELinux is protecting the host directory where trino/docs resides, the build container cannot mount it, and we get this error:
```
Configuration error:
config directory doesn't contain a conf.py file (/docs/src/main/sphinx)
```
This patch makes Docker explicitly disable security policies that protect the host, eliminating the error.
https://github.com/trinodb/trino/pull/19938#issuecomment-1830864510
```markdown
```
=> Turn off SELinux in doc build container

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/TracingDataSource.java
Currently, when using a JDBC URL with an invalid schema, a vague error like this is produced:
> io.trino.spi.TrinoException: Error listing schemas for catalog xxx: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException: Cannot invoke "java.sql.Connection.getMetaData()" because "this.delegate" is null
After #18735, the connection is wrapped in `io.opentelemetry.instrumentation.jdbc.internal.OpenTelemetryConnection` so it's not null when checking in https://github.com/trinodb/trino/blob/master/plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DriverConnectionFactory.java#L79, but the delegate inside this wrapper is null. The underlying `JdbcDataSource` should never return a null connection, since it's always used with a specific JDBC driver. …
=> Produce a more actionable error on wrong JDBC URL

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
Prep for https://github.com/trinodb/trino/pull/19996
=> Test code cleanup around testJoinPushdown

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
In order to avoid a potential infinite loop at IterativeOptimizer with Iceberg
Rely on the data in the table handle instead of `Constraint` for stopping condition.
According to my check, we don't see an infinite loop only because `io.trino.sql.planner.iterative.rule.PushPredicateIntoTableScan#arePlansSame` returns `true` and stops the iterative process. If in the future `io.trino.plugin.iceberg.IcebergTableHandle#equals` will return `false` when comparing 2 tables of 2 different iterations, then we'll see an infinite loop. That's while `io.trino.spi.connector.ConnectorTableHandle` is an empty interface that doesn't declare `equals()`.
This is another case in continue to https://github.com/trinodb/trino/pull/20007 and https://github.com/trinodb/trino/issues/19876.
( X ) This is not …
=> Rely only on table handle for stopping condition

lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GcsAccessTokenProvider.java, lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GcsStorageFactory.java, lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GoogleGcsConfigurationInitializer.java, pom.xml
On previous version:
```
public static final ImmutableList<String> DEFAULT_SCOPES = ImmutableList.of("https://www.googleapis.com/auth/cloud-platform");
```
=> Upgrade GCS connector to 3.0.0

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/AddFileEntry.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointSchemaManager.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java
In case that there is checkpoint filtering applied and there are partition constraints which do not
match the partition values of the entry, avoid early to create the `AddFileEntry` instance.
Split the loading for the `add` entries from the Parquet checkpoint in two channels:
- one channels contains the `partitionValues` information
- the other channel contains everything else related to `add`
When building the `add` entry, check first the partition constraint to match against the partition values and only then load the `add` block to avoid unecessary resources spent on deserialization.
Used for testing a multi-part checkpoint file (25 parts , each around 12MB ~ 300MB in total) for testing this feature while storing the checkpoint in local MinIO and came up with the following results:
``` …
```
=> Construct AddFileEntry instance only if necessary while reading the Delta Lake checkpoint

core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java
checkValidRegion already validates that
region is correct. Therefore copyRegion
for postiion 42 and length 0 shoudn't
fail for dictionary with 42 positions.
=> Support for 0 length dictionary copyRegion

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientModule.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoConnector.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoTransactionManager.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ptf/Query.java
Minor cleanups in Mongo connector which introduces `MongoTransactionManager`  
```markdown
```
=> Introduce MongoTransactionManager

docs/src/main/sphinx/connector/hive.md, plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/CoercionUtils.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/DateCoercer.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcTypeTranslator.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveCoercionPolicy.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestDateCoercer.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnPartitionedTable.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnUnpartitionedTable.java
Add date to varchar coercion for hive.
Enable the Hive users to retrieve the information from their tables after performing queries which change `date` columns to `varchar`.
Hive sample DDL query:
```
ALTER TABLE mytable CHANGE COLUMN mycolumn mycolumn varchar(12);
```
After changing the column type, dates to far in the future are displayed as expected in Trino, but not in Hive:
```
0: jdbc:hive2://localhost:10000/default> select * from test2;
+-------------+
|   test2.d   |
+-------------+
| 2023-01-10  |
| 000-01-24  |
+-------------+
```
```
trino> select * from hive.default.test2;
d       
--------------
+10000-01-24 
2023-01-10   
(2 rows)
```
In any case, dates to far in the future seem not to be queryable anyway even when working with `date` column type in Hive
```
0: …
```
=> Add date to varchar coercion for hive

plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java
Previously we were using `NoopHostnameVerifier` which turns off hostname verification, and if the HostnameVerifier is not set it uses `DefaultHostnameVerifier` which performs hostname verification
```markdown
* Use correct HostnameVerifier when verify-hostnames set to true.
```
=> Use correct HostnameVerifier when verify-hostnames set to true

docs/src/main/sphinx/routines/examples.md
Add example SQL routines for formatting bytes
=> Add example SQL routines for formatting bytes

plugin/trino-hudi/pom.xml, plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/TpchHudiTablesInitializer.java
This PR upgrades Hudi version to 0.14.0 to make sure the Hudi connector can read tables with new Hudi table version created by Hudi 0.14.0 release.
Hudi metadata table (MDT) is disabled in the tests as the support of reading MDT is broken after the removal of Hudi dependencies from compile time (which happened some time back #17392).
Hudi tables written by 0.14.0 with the new table version can be read.
=> Upgrade Hudi version to 0.14.0

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientConfig.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientModule.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoServerDetailsProvider.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSplitManager.java, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/SessionBasedMongoServerDetailsProvider.java, plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoClientConfig.java
Additionally disable local scheduling of Mongo splits
```markdown
* Add a config to toggle local scheduling of Mongo splits. ({issue}`issuenumber`)
```
=> Add a config to toggle local scheduling of Mongo splits

lib/trino-filesystem-gcs/pom.xml, lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java, lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsStorageFactory.java, lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemConfig.java, lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java, plugin/trino-bigquery/pom.xml, pom.xml
Resolves #19943 
```markdown
```
=> Configure retries for trino-filesystem-gcs

core/trino-main/src/main/java/io/trino/likematcher/FjsMatcher.java, core/trino-main/src/test/java/io/trino/likematcher/TestLikeMatcher.java
After the initial KMP mismatch, the next match was being skipped at position i == longest match.
Fixes #20089
```markdown
* Fix incorrect results for LIKE with some strings containing repeated substrings. ({issue}`20089`)
```
=> Fix incorrect LIKE for patterns with repeating substrings

docs/src/main/sphinx/connector/mongodb.md, plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientConfig.java
See title and discussion in linked PR.
Add missing docs for #20078
=> Add docs for mongodb.allow-local-scheduling

docs/src/main/sphinx/connector/elasticsearch.md
See title
Found to be missing with #20076 
=> Add docs for elasticsearch.tls.verify-hostnames

docs/src/main/sphinx/release.md, docs/src/main/sphinx/release/release-435.md
Assemble the release notes for the 435 release.
Fixes #19964 
* #19942 ✅ rn ✅ docs
* #19662 ✅ rn ✅ docs
* #19952 ✅ rn ✅ docs
* #19970 ✅ rn ✅ docs 
* #19957 ✅ rn ✅ docs 
* #19967 ✅ rn ✅ docs 
* #17016 ✅ rn ✅ docs 
* #19947 ❌ rn ✅ docs - reverted by #20107
* #19982 ✅ rn ✅ docs 
* #19979 ✅ rn ✅ docs 
* #19993 ✅ rn ✅ docs 
* #19860 ✅ rn ✅ docs 
* #19995 ✅ rn ✅ docs 
* #19966 ✅ rn ✅ docs 
* #19965 ✅ rn ✅ docs 
* #20001 ✅ rn ✅ docs 
* #19969 ✅ rn ✅ …
=> Add Trino 435 release notes

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
I saw that these "CREATE TABLE" test cases are taking around 40-50s each in the CI. Instead of separate 16 cases, collapse them into a single create table with all supported types case.
=> Speed-up bigquery tests

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
This behaviour fails even on the UI:
=> Disable failing bigquery test

core/trino-main/src/main/java/io/trino/operator/table/json/JsonTable.java, testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java
The concrete type declared in the JsonTableFunctionHandle is not directly serializable. The deserializer binding is only declared for the Type class.
```markdown
* Fix query failure when invoking `json_table`. ({issue}`...`)
```
=> Fix serialization failure when invoking json_table

core/trino-main/src/main/java/io/trino/operator/output/PagePartitioner.java, core/trino-main/src/main/java/io/trino/operator/output/PartitionedOutputOperator.java, core/trino-main/src/main/java/io/trino/operator/output/PositionsAppenderPageBuilder.java, core/trino-main/src/main/java/io/trino/operator/output/UnnestingPositionsAppender.java, core/trino-main/src/test/java/io/trino/operator/output/TestPartitionedOutputOperator.java, core/trino-main/src/test/java/io/trino/operator/output/TestPositionsAppenderPageBuilder.java
`PagePartitioner` instances should either flatten their dictionary-mode appenders and transition to direct mode, or force their current page to preserve the dictionary encoding and force the current page to be flushed being released to the pool for reuse since it is not possible for the appender to observe the same dictionary input when reused by a different driver.
Also fixes an issue where dictionary encoded output pages significantly under-report their output size for `PartitionedOutputOperator`.
Follows up from https://github.com/trinodb/trino/pull/19762 which mitigates similar issues for RLE blocks, but using a different strategy that's more appropriate for dictionary block handling.
( ) Release notes …
=> Flush PagePartitioner dictionaries before release

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieTableOperations.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
Spark sets the table property `NESSIE_COMMIT_ID_PROPERTY` in `NessieTableOperations#loadTableMetadata`. Then `NessieIcebergClient.commitTable` uses this property.
In Trino, this property is never set but used in `NessieIcebergClient.commitTable` as it is a common code. Hence, the commit id is old and doesn't allow new commits.
Use the common code (available From Iceberg 1.4.0) `NessieUtil.updateTableMetadataWithNessieSpecificProperties` in Trino, which handles setting the property like `"nessie.commit.id"`.
Fixes https://github.com/trinodb/trino/issues/17813   
```markdown
* …
```
=> Ensure "nessie.commit.id table" property is set when updating the table

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
Fixes https://github.com/trinodb/trino/issues/20088
Commits are taken out of https://github.com/trinodb/trino/pull/20054
```markdown
```
=> Process only files smaller than the threshold for OPTIMIZE

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java, core/trino-main/src/main/java/io/trino/cost/CostCalculatorWithEstimatedExchanges.java, core/trino-main/src/main/java/io/trino/cost/LocalCostEstimate.java, core/trino-main/src/main/java/io/trino/cost/PlanNodeStatsAndCostSummary.java, core/trino-main/src/main/java/io/trino/cost/TaskCountEstimator.java, core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java, core/trino-main/src/test/java/io/trino/sql/planner/AbstractPredicatePushdownTest.java, core/trino-main/src/test/java/io/trino/sql/planner/TestAddDynamicFilterSource.java, core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java, core/trino-main/src/test/java/io/trino/sql/planner/TestPredicatePushdown.java, core/trino-main/src/test/java/io/trino/sql/planner/TestPredicatePushdownWithoutDynamicFilter.java, core/trino-main/src/test/java/io/trino/sql/planner/TestQuantifiedComparison.java, lib/trino-cache/src/test/java/io/trino/cache/TestEvictableCache.java, lib/trino-cache/src/test/java/io/trino/cache/TestEvictableLoadingCache.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergProjectionPushdownPlans.java, testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java, testing/trino-tests/src/test/java/io/trino/tests/TestQueryPlanDeterminism.java
Assuming 0 node count, we were getting negative cost in the formula
double cpuCost = buildSideSize * (estimatedSourceDistributedTaskCount - 1);
where `estimatedSourceDistributedTaskCount` is the node count.
=> Fix negative cost estimated failure in testUnionAllAboveBroadcastJoin

.mvn/jvm.config
The build was observed failing with
Warning: [325.033s][warning][gc,alloc] mvn-builder-trino-parquet: Retried waiting for GCLocker too often allocating 4194306 words
on CI (https://github.com/trinodb/trino/actions/runs/7221312204/job/19676023973?pr=20134)
=> Increase GCLocker retries for Maven

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
Before the change, `FileHiveMetastore` would rely on `fileSystem.listFiles` to find schemas or tables within a schema. `listFiles` is recursive and, on a local file system, fails when files/directories are being modified concurrently. This commit replaces recursive `listFiles` listing with non-recursive `listDirectories` leveraging the fact that listed entities are represented as directories.
Fixes only partially https://github.com/trinodb/trino/issues/20130
=> Fix table listing concurrency in FileHiveMetastore

core/trino-main/src/test/java/io/trino/sql/query/TestWindow.java
The test sometimes failed due to a timeout on CI.
Fixes https://github.com/trinodb/trino/issues/20077
=> Increase timeout for TestWindow.testManyFunctionsWithSameWindow

.github/workflows/ci.yml, plugin/trino-bigquery/pom.xml
TestBigQueryAvroConnectorTest takes about 40 minutes. 
TestBigQueryAvroTypeMapping takes about 10 minutes. 
We shouldn't run those tests in a profile. 
=> Adjust BigQuery CI profile

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java
Just a small refactoring.
The BinPackingSimulation class reserves nodes for splits by matching available nodes against a NodeRequirements object.  This PR rewrites that logic in an equivalent but shorter and more extensible way.
```markdown
```
=> Minor refactoring of the bin-packing allocator's candidate logic

docs/src/main/sphinx/connector/oracle.md
Follow up to downgrade of JDBC driver, also fix links, adjusted requirements because we only test with 19 as min version.
Not sure to be honest.. wdyt @wendigo .. no entry, normal entry, or even breaking change entry? 
```markdown
```
=> Update requirement to Oracle 19

lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java
Reduce the time from about 120-130s to 35-37s by reducing the repetitions from 100 -> 30.
Also added a comment explaining the reason for the testCreateFileRetry test.
```markdown
```
=> Reduce repetitions of testCreateFileRetry

testing/trino-product-tests-launcher/pom.xml, testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/cli/TestInvocations.java, testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/cli/TestOptionsPrinter.java, testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/env/TestConfigurations.java, testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/local/TestManuallyJdbcOauth2.java, testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/util/TestConsoleTable.java
Convert product tests launcher's test to JUnit. This does not change product tests themselves.
=> Convert PTL tests to JUnit

plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
=> Fix Flaky BaseHiveConnectorTest.testMultipleWritersWithSkewedData

docs/src/main/sphinx/functions/aggregate.md
- Add an example for `listagg` aggregation function with `filter` keyword
-  Example provided by a test in #19871, which addressed #19869
- Lowercase the function name `LISTAGG` to `listagg` to match the naming convention followed in the other sections of the documentation.
=> Add an example for listagg with filter

docs/src/main/sphinx/routines/introduction.md
Add explicit mention what connector support storage so readers dont have to go looking through all connectors to find out.
Follow up from painpoint found during creation of SQL training material for routines.
=> Expand catalog routine docs

docs/src/main/sphinx/functions/aggregate.md
Documents the new filtering functionality for `LISTAGG` function added in https://github.com/trinodb/trino/pull/19871
=> Document filtering during aggregation for listagg

core/trino-main/src/main/java/io/trino/operator/scalar/DateTimeFunctions.java, core/trino-main/src/test/java/io/trino/operator/scalar/TestDateTimeFunctions.java
The exception is due to the value user entered hence should be reported as a TrinoException rather than a GENERIC_INTERNAL_ERROR
As per #20085, the error in `from_unixtime` is due to an invalid function argument passed by the user. Hence, it should be reported as such for statistics purposes. Currently, it is reported as a `GENERIC_INTERNAL_ERROR`. This PR fixes this by catching and throwing a `TrinoException` with the error code `INVALID_FUNCTION_ARGUMENT`.
=> Added TrinoException for millis overflow in from_unixtime

core/trino-main/src/main/java/io/trino/operator/output/PagePartitioner.java, core/trino-main/src/test/java/io/trino/operator/output/TestPagePartitioner.java
Fixes a logical error introduced by https://github.com/trinodb/trino/pull/19806 which fails to record output buffered bytes eagerly reported as output and could result in overstating the output size of partitioned output operators.
=> Fix page partitioner output bytes on release handling

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureOutputFile.java, lib/trino-filesystem-gcs/pom.xml, lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsOutputFile.java, lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/AbstractTestGcsFileSystem.java, lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3OutputFile.java, lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/AbstractTestS3FileSystem.java, lib/trino-filesystem/pom.xml, lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoOutputFile.java, lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalOutputFile.java, lib/trino-filesystem/src/main/java/io/trino/filesystem/memory/MemoryOutputFile.java, lib/trino-filesystem/src/main/java/io/trino/filesystem/tracing/TracingOutputFile.java, lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java, lib/trino-filesystem/src/test/java/io/trino/filesystem/TrackingFileSystemFactory.java, lib/trino-filesystem/src/test/java/io/trino/filesystem/memory/TestMemoryFileSystem.java, lib/trino-hdfs/pom.xml, lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsOutputFile.java, lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GcsAtomicOutputStream.java, lib/trino-hdfs/src/test/java/io/trino/filesystem/hdfs/TestHdfsFileSystemS3Mock.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/GcsTransactionLogSynchronizer.java
`GcsTransactionLogSynchronizer` requires that the new transaction log file is created exclusively and atomically. Otherwise concurrent readers of a table may see a file partially written (or not written yet, just empty) and fail. This commit:
- fixes the GCS native filesystem implementation so that it's atomic
- changes the method signature to indicate atomic creation and remove default not atomic implementation.
- makes it clear in-memory buffering occurs (previously it was implicitly done in `HdfsOutputFile` which could be considered surprising)
Fixes https://github.com/trinodb/trino/issues/20168
Required by https://github.com/trinodb/trino/pull/19991
=> Make createExclusive atomic

plugin/trino-cassandra/pom.xml, plugin/trino-elasticsearch/pom.xml, plugin/trino-pinot/pom.xml, plugin/trino-sqlserver/pom.xml
=> Remove redundant air.test.parallel property

core/trino-main/src/main/java/io/trino/sql/gen/DereferenceCodeGenerator.java, core/trino-main/src/main/java/io/trino/sql/relational/ConstantExpression.java, core/trino-main/src/main/java/io/trino/sql/relational/SqlToRowExpressionTranslator.java, core/trino-main/src/test/java/io/trino/sql/gen/TestInCodeGenerator.java, testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java
Fixes https://github.com/trinodb/trino/issues/19997
=> Fix dereference in SQL routine

testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
The test must run single-threaded and was run like that until 9a7cf10d16253d165253218ae8345f22e6d480c8.
=> Fix TestAccessControl execution

core/trino-main/src/main/java/io/trino/execution/SqlQueryManager.java
Query start may be time consuming operation and should be traced. Especially in case of `DataDefinitionExecution`, the start may cover all of the query execution.
Fixes https://github.com/trinodb/trino/issues/20193
=> Add tracing for query start

core/trino-main/src/test/java/io/trino/operator/TestExchangeOperator.java, plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestMinimalFunctionality.java, testing/trino-tests/src/test/java/io/trino/connector/informationschema/TestInformationSchemaConnector.java, testing/trino-tests/src/test/java/io/trino/connector/system/runtime/TestKillQuery.java, testing/trino-tests/src/test/java/io/trino/execution/TestBeginQuery.java, testing/trino-tests/src/test/java/io/trino/execution/TestCompletedEventWarnings.java, testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerWithSplits.java, testing/trino-tests/src/test/java/io/trino/execution/TestQueryTracker.java, testing/trino-tests/src/test/java/io/trino/execution/TestQueues.java, testing/trino-tests/src/test/java/io/trino/execution/resourcegroups/db/TestEnvironments.java, testing/trino-tests/src/test/java/io/trino/execution/resourcegroups/db/TestQueuesDb.java, testing/trino-tests/src/test/java/io/trino/memory/TestMemoryManager.java, testing/trino-tests/src/test/java/io/trino/security/TestSystemSecurityMetadata.java, testing/trino-tests/src/test/java/io/trino/tests/TestGracefulShutdown.java, testing/trino-tests/src/test/java/io/trino/tests/TestMetadataManager.java, testing/trino-tests/src/test/java/io/trino/tests/TestProcedureCall.java, testing/trino-tests/src/test/java/io/trino/tests/TestQueryManager.java
Some tests being fixed simply fail because they do not support concurrent test method execution.
Others worked, but could allocate lots of resources, potentially leading to OOM failures on CI.
The tests where found by looking at
9a7cf10d16253d165253218ae8345f22e6d480c8 commit:
git show 9a7cf10d16253d165253218ae8345f22e6d480c8 | grep -A 3 '@Test(singleThreaded = true)'
potentially relates to https://github.com/trinodb/trino/issues/20199
=> Fix incorrectly concurrent tests

core/trino-main/src/main/java/io/trino/split/SplitManager.java
Sometimes, `ConnectorSplitManager.getSplits` can take long to construct `ConnectorSplitSource`. For example, in Delta, there is IO work being done before `ConnectorSplitSource` is returned. This work would better be delayed until `ConnectorSplitSource.getNextBatch` is invoked, but currently this is not the case. Let's add tracing so that time spent in `ConnectorSplitManager.getSplits` is attributable.
=> Add tracing for SplitManager.getSplits

core/trino-main/src/main/java/io/trino/execution/FailureInjectionConfig.java
Failure injection is a for-tests functionality. Hide its config, they are not meant to be used.
=> Hide FTE tests configs

lib/trino-filesystem/src/main/java/io/trino/filesystem/memory/MemoryInputStream.java, lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java, lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsTrinoInputStream.java
[InputStream.read is expected to throw IndexOutOfBoundException when](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/io/InputStream.html#read(byte%5B%5D,int,int))
>  off is negative, len is negative, or len is greater than b.length - off
We currently don't test this, and allow using `MemoryInputStream.read` with a negative offset.
```markdown
```
=> Throw IndexOutOfBoundsException in MemoryInputStream

core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
=> Catch exception in sendUpdate

core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java
They result in very verbose logs in tests and are not actionable for anyone managing a Trino deployment
=> Adjust logging level to debug

core/trino-main/src/main/java/io/trino/sql/planner/EqualityInference.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java, core/trino-main/src/test/java/io/trino/sql/planner/AbstractPredicatePushdownTest.java, core/trino-main/src/test/java/io/trino/sql/planner/TestEqualityInference.java, core/trino-main/src/test/java/io/trino/sql/planner/TestPredicatePushdownWithoutDynamicFilter.java
When there are predicates like a1 = b1 and a2 = a1 + 1, then
equality inference would derive staddling predicate for
a2 = b1 + 1, which is redundant to a1 = b1, a2 = a1 + 1.
This commit makes sure that redundant straddling predicates
are not generated.
```markdown
* Improve performance by removing redundant predicates from plan. ({issue}`issuenumber`)
```
=> Do not generate redundant straddling predicates by equality inference

plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java, plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerTypeMapping.java
The value returned via the `microsoft.sql.DateTimeOffset` when converted to an `OffsetDateTime` is changed for old dates due to an issue in the JDBC driver (see linked issue for example).
This changes retrieving datetimeoffset types from SQL Server to use `getString` instead of `getObject` and `OffsetDateTime`.
Predicate pushdown is now disabled for this type due to test failures with `IS NOT DISTINCT FROM` predicates.
https://github.com/trinodb/trino/issues/16559
https://github.com/microsoft/mssql-jdbc/issues/2246
```markdown
* Fixed incorrect results for old DATETIMEOFFSET …
```
=> Fix SQL Server DATETIMEOFFSET for old dates

core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java, core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java
In pipelined mode, the spooling stats are always null, which fills the log needlessly.  We want to catch this nullification only in FTE mode.
https://github.com/trinodb/trino/pull/20214#discussion_r1435339288
```markdown
```
=> Only log null spooling stats in FTE mode

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
Most listing Glue APIs accept a MaxResults parameter which decides how many objects are returned in a single API call. The default values are not documented but observed behaviour is that the default values change
on some basis.
This commit adds explicit values for MaxResults in the APIs which support it to the maximum possible values.
This possibly reduces the number of Glue calls when listing tables, databases or functions in some cases.
This is similar to https://github.com/trinodb/trino/commit/4f22b0ebb52c71e07370b41f785fa88dde289c22 and https://github.com/trinodb/trino/commit/45dc37d4b68b6e7e72d2b50810fe96ebab08c0c3.
(x) Release notes …
=> Use explicit values for MaxResults in all Glue APIs

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeInputInfo.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMetadata.java
Add Delta table read version to `connectorInfo`. It will show up in the query information as:
```json
...
"inputs" : [ {
"catalogName" : "delta",
"catalogVersion" : "default",
"schema" : "test",
"table" : "test",
"connectorInfo" : {
"partitioned" : true,
"version": 1234
},
...
```
Fixes https://github.com/trinodb/trino/issues/20242
=> Add Delta table read version to connectorInfo

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
We can apply pruning logic at file level before splitting it into splits to avoid redundant operations per split
```markdown
```
=> Refactor IcebergSplitSource to reduce per split operations

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java
In case that the dynamic filter completes after scheduling of split
on the worker, the results in the split will be getting pruned in
the situation that there is a partition predicate mismatch.
```markdown
* Improve performance of queries with selective joins on partitioning columns. ({issue}`20212`)
```
=> Short circuit page source in case of partition mismatch

client/trino-jdbc/pom.xml, client/trino-jdbc/src/test/java/io/trino/jdbc/BaseTestJdbcResultSet.java, client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcResultSet.java, plugin/trino-geospatial/pom.xml, plugin/trino-hudi/pom.xml, plugin/trino-session-property-managers/pom.xml, pom.xml, testing/trino-test-jdbc-compatibility-old-server/src/test/java/io/trino/TestJdbcResultSetCompatibilityOldServer.java
`trino-re2j` is a fork of `com.google.re2j:re2j`. The forks diverged over time. It is not safe to ignore this dependency conflict e.g. because `com.google` version has `com.google.re2j.Pattern.matcher` accepting `CharSequence` or `byte[]` while Trino version accepts only `Slice`. They cannot be used interchangeably at all.
=> Unignore re2j dependency conflicts

core/trino-main/src/main/java/io/trino/execution/QueryStateMachine.java, core/trino-main/src/main/java/io/trino/execution/StageStateMachine.java, core/trino-main/src/main/java/io/trino/sql/planner/PlanFragment.java
There may be a little bit performance issue while response for api of cluster stats, if cluster has huge amounts of tasks. 
Most of time was spent on distinguish the type of fragements temporarily.
This PR can improve performance slightly while response for 'ui/api/stats' .
=> Mark wether a PlanFragement is contains TableScanNode or not

docs/src/main/sphinx/functions/geospatial.md, plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/GeoFunctions.java, plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestBingTileFunctions.java, plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestGeoFunctions.java
This is a backport from https://github.com/prestodb/presto/pull/13323/files. Made a few changes to work with recent changes in Trino, such as doc changes in md and using junit instead of testng.
with a recent fix from ESRI, we can now directly use it to find centroid 
(x ) Release notes are required, with the following suggested text:
```markdown
* fix ST_Centroid and ST_Buffer for tiny geometries
```
=> fix ST_Centroid and ST_Buffer for tiny geometries

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java
Use the effective predicate instead of the dynamic filter predicate to check for partition matching.
This change results in short circuiting the page source and not having to read anymore the data file footer in the exotic case where a partition filter acts as unenforced
predicate due to table partition spec evolution.
This PR is a follow-up of the hint https://github.com/trinodb/trino/pull/20212#discussion_r1439328687
Imagine the following scenario:
```
trino> create table iceberg.default.t1 (year integer, month integer, data integer) with (partitioning=array['year']);
CREATE TABLE
trino> insert into iceberg.default.t1 values (2023, 1, 10), (2023, 1, 11), (2023, 2, 20);
INSERT: 3 rows
trino> alter table iceberg.default.t1 set properties partitioning = array['year', 'month'];
SET …
```
=> Use the effective predicate when doing partition matching

docs/src/main/sphinx/connector/object-storage-file-formats.md, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesFunctionProcessor.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestPredicatePushdown.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetReaderConfig.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetConnectorTest.java
Add parquet_ignore_statistics session property to iceberg and delta
```markdown
* Add `parquet_ignore_statistics` catalog session property. ({issue}`20228`)
```
=> Add parquet_ignore_statistics session property to iceberg and delta

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
Count separately how much time passed since FTE scheduler processed a
meaningful event and how much time passed since debug information was
last logged.
=> Untangle debug logging frequency and scheduler stalled time

core/trino-main/src/main/java/io/trino/dispatcher/DispatchManager.java, core/trino-main/src/main/java/io/trino/dispatcher/FailedDispatchQueryFactory.java
For really bad queries, the ones that do not even parse to a proper SQL, we have the following sequence of calls:
- `EventListener.queryCompleted()`
- query is added to the `QueryTracker`
To work around incorrect sequence of these calls, an `EventListener` will typically use a retry mechanism combined with switching to a separate thread.
This PR inverts the sequence of calls so that `EventListener`s can now be coded single-threaded.
- https://github.com/trinodb/trino/issues/20225
( X ) This is not user-visible or is docs only, and no release notes are required.
=> Sometimes EventListener.queryCompleted() called too early

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeNodeLocalDynamicSplitPruning.java
In case that the dynamic filter completes after scheduling of split
on the worker, the results in the split will be getting pruned in
the situation that there is a partition predicate mismatch.
Iceberg counterpart PR https://github.com/trinodb/trino/pull/20212
```markdown
* Improve performance of queries with selective joins on partitioning columns. ({issue}`20261`)
```
=> Delta Lake: Short circuit page source in case of partition mismatch

plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHive3OnDataLake.java
Calling `flush_metadata_cache` without arguments may affect other concurrent tests. 
=> Specify table name in testPartitionProjectionIgnore

core/trino-server/src/test/java/io/trino/server/TestDummy.java
Added a dummy test in `trino-server` to prevent failures when trying to build since there are no tests in the project.
Fixes #19798 by adding a dummy test.
```markdown
```
=> Fixes the failure when building trino-server alone

.github/workflows/stale.yml
- Currently uses default 30 and thats too low
- Also update to latest version of the action
- Also configure to only process PRs
* See runs at https://github.com/trinodb/trino/actions/workflows/stale.yml 
* specifically see error message at https://github.com/trinodb/trino/actions/runs/7349673496 and other runs ... I assume we are not hitting the API limit hence enlarging the number .. docs even suggest to go to 1000 or so .. but I think this is a good first try.
* Also see https://github.com/actions/stale/issues/1112
=> Increase stale operations count

plugin/trino-accumulo/pom.xml, plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestingAccumuloServer.java, testing/trino-testing-containers/pom.xml, testing/trino-testing-containers/src/main/java/io/trino/testing/containers/junit/ReportLeakedContainers.java, testing/trino-testing-containers/src/main/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener
With TestNG, `ManageTestResources` was attempting to prevent resource leaks, including container leaks, in tests. It relied on certain common test patterns to operate (like storing resource on instance fields).
This commit attempts to provide similar functionality for JUnit. For now it's limited to containers. As an added bonus, it works regardless of how the test class is written.
=> Detect leaked containers when running with JUnit

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
Fix bug where listing namespaces was performed but non-existing namespace was provided. This is coming from discussion on #19818 https://github.com/trinodb/trino/pull/19818#discussion_r1400214440 
This change fixes a bug where if an explicit namespace was provided the listTables implementation would do a full listing of the all the namespaces even if the namespace does not exist at the time. 
( X) Release notes are required, with the following suggested text:
```markdown
* Fix bug where listing namespaces was performed but non-existing namespace was provided.  This applies when listing tables.
```
=> Iceberg Rest Catalog: Fix bug where listing namespaces was performed but non-existing namespace was provided

.github/workflows/stale.yml
New run failed due to the typo.
See https://github.com/trinodb/trino/actions/runs/7450714357
=> Fix typo in stalebot config

.github/workflows/ci.yml, README.md, core/trino-main/src/main/java/io/trino/dispatcher/DecoratingListeningExecutorService.java, core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java, core/trino-server-main/src/main/java/io/trino/server/TrinoServer.java, core/trino-server-rpm/src/main/rpm/preinstall, core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java, docs/src/main/sphinx/functions/conversion.md, docs/src/main/sphinx/functions/regexp.md, docs/src/main/sphinx/installation/deployment.md, docs/src/main/sphinx/security/tls.md, pom.xml
Release notes needed:
```
Require JDK 21.0.1 to run Trino
```
Closes https://github.com/trinodb/trino/issues/17017
=> Require JDK 21 to run Trino

docs/src/main/sphinx/admin/fault-tolerant-execution.md
Trino automatically encrypts exchange data before spooling when FTE is enabled. This should be documented so that security concerns can be addressed and users do not needlessly enable TLS.
```markdown
```
=> Document encryption of FTE spool

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
Currently we evaluate constraint on partitioning columns for every file in iceberg
split source. This change caches the result of constraint evaluation to avoid repeating
this computation for every file in a partition.
```markdown
```
=> Cache result of evaluating constraint per partition in iceberg

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestingThriftHiveMetastoreBuilder.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/AbstractTestHiveMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestBridgingHiveMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/MetastoreClientAdapterProvider.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestingTokenAwareMetastoreClientFactory.java
Ignore internal TableNotFoundException in DROP TABLE for Iceberg and Hive
Fixes https://github.com/trinodb/trino/issues/18848
```markdown
```
=> Ignore internal TableNotFoundException in DROP TABLE

core/trino-main/src/main/java/io/trino/metadata/FunctionManager.java, core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java, core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, core/trino-main/src/test/java/io/trino/dispatcher/TestLocalDispatchQuery.java, core/trino-main/src/test/java/io/trino/metadata/TestGlobalFunctionCatalog.java, core/trino-main/src/test/java/io/trino/sql/planner/TestingPlannerContext.java, core/trino-spi/src/main/java/io/trino/spi/exchange/ExchangeSourceOutputSelector.java, core/trino-spi/src/main/java/io/trino/spi/predicate/TupleDomain.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultQueryBuilder.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java, plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteClient.java, plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java, plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlClient.java
`{ throw ...; }` lambdas read very well. However, all recent IntelliJ versions insist on removing whitespace before `throw` and after final `;`. This results in checkstyle violation when IDE automatic formatting is used.
Reformat lambdas in a way that IDE automatic formatting does not violate checkstyle rules, in order to save time when working with code.
=> Fix auto formatting of throwing blocks

core/trino-main/src/main/java/io/trino/operator/scalar/timetz/VarcharToTimeWithTimeZoneCast.java
Fix cast time tz exception message
https://github.com/trinodb/trino/issues/20305
=> Fix cast time tz exception message

core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java, core/trino-main/src/test/java/io/trino/sql/planner/TestConnectorExpressionTranslator.java
Support translation of `JsonPathType` (which is not part of SPI) to `ConnectorExpression` in order to support pushdown of functions like `json_extract_scalar`.
( X ) This is not user-visible or is docs only, and no release notes are required.
=> Support translation of JsonPathType to ConnectorExpression

docs/src/main/sphinx/language/types.md
This adds an example of how to escape single quotes in string literals.
=> Document single quote escape

docs/src/main/sphinx/admin/fault-tolerant-execution.md
Fix for https://github.com/trinodb/trino/pull/20298#discussion_r1447237535 since the detail is there .. it should at least be correct.
=> Correct FTE encryption detail in docs

docs/src/main/sphinx/connector/opensearch.md
Follow up to discussion with @wendigo on https://github.com/trinodb/trino/pull/20257
Apart from commented changes everything is just reformatting, rewording, and clean up.
I can send a follow up PR for the Elasticsearch connector docs as well.
=> Clean up OpenSearch connector docs

plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestLazyMap.java
`org.testng.Assert.assertEquals(Map, Map)` does not really check  map equality when the actual map contains null values.
Migrate to AssertJ and fix the test.
=> Fix map assertion in TestLazyMap

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/expression/ConnectorExpressionRewriter.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/expression/ConnectorExpressionRule.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/GenericRewrite.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/JdbcConnectorExpressionRewriterBuilder.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/expression/TestGenericRewrite.java, plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
Add support for conditional rewrites in `JdbcConnectorExpressionRewriterBuilder`.
This allows merging `PostgreSqlClient`'s two different rewrite objects into one.
=> Conditional rewrites in JDBC complex expression pushdown

lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/simple/SimpleDeserializer.java
Reduce function calls in hot path when reading TextFile.
For some reason JVM didn't inline Slice.getByte() and that caused a performance regression (compare Trino 388 and Trino 428).
```
$ java -version
openjdk version "17.0.4.1" 2022-08-12
OpenJDK Runtime Environment Temurin-17.0.4.1+1 (build 17.0.4.1+1)
OpenJDK 64-Bit Server VM Temurin-17.0.4.1+1 (build 17.0.4.1+1, mixed mode, sharing)
CREATE TABLE test (
...
foo varchar,
err_code integer,
log_date varchar,
log_hour varchar,
log_min varchar
)
WITH (
format = 'TEXTFILE',
partitioned_by = ARRAY['log_date','log_hour','log_min'],
textfile_field_separator = U&'\0009'
)
explain analyze verbose
select
count(*) as request_count
from test
where log_date between  '20231101' and '20231130' and foo != 'bar' and err_code = 0;
```
Before:
```
└─ …
```
=> Reduce function calls in hot path

plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
Make it use unique namespace names and add cleanup.
Fixes https://github.com/trinodb/trino/issues/20324
=> Fix TestTrinoGlueCatalog.testListTables

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetConnectorTest.java
Fixes #18855. `IcebergPageSourceProvider.getParquetTupleDomain` get domain by column name. When column renamed in iceberg, this result is empty. We should use iceberg column id to match parquet column instead.
```markdown
* Fix predicate pushdown in parquet for renamed columns in Iceberg tables. (`18855`)
```
=> Add support iceberg parquet predicate pushdown with iceberg column id

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteClients.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteFunctions.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteGcs.java
In few suites `configured_features` was misspelled as `configured-features`.
=> Fix impacted features inclusion in product tests

docs/src/main/sphinx/release.md, docs/src/main/sphinx/release/release-436.md
Assemble the release notes for the upcoming Trino 436 release. Fixes #20110 
* #20106 ✅ rn ✅ docs
* #20095 ✅ rn ✅ docs
* #20097 ✅ rn ✅ docs
* #20119 ✅ rn ✅ docs
* #20122 ✅ rn ✅ docs
* #20104 ✅ rn ✅ docs
* #19806 ✅ rn ✅ docs
* #19524 ✅ rn ✅ docs
* #20127 ✅ rn ✅ docs
* #20121 ✅ rn ✅ docs
* #20059 ✅ rn ✅ docs
* #20136 ✅ rn ✅ docs
* #20135 ✅ rn ✅ docs
* #20134 ✅ rn ✅ docs
* #20137 ✅ rn ✅ docs
* #19944 ✅ rn ✅ docs
* #20124 ✅ rn ✅ docs
* #20141 ✅ rn ✅ …
=> Add Trino 436 release notes

plugin/trino-hive/src/main/java/io/trino/plugin/hive/ReaderProjectionsAdapter.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/AsyncQueue.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveReaderProjectionsUtil.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestReaderProjectionsAdapter.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeGcs.java
Maybe fixes https://github.com/trinodb/trino/issues/13995
=> Increase query timeout in testDeleteRowsConcurrently

testing/trino-testing/src/main/java/io/trino/testing/FaultTolerantExecutionConnectorTestHelper.java
While by default number of queryExecutor threads is 1000 in tests we limitted it to 10. This values was too small though. If tests are run in parallel all threads may be consumed by long running jobs running EventDrivenFaultTolerantQueryScheduler.Scheduler#run. In such case we are not able to run Future callback which use same executor and are also needed for queries to progress. If that happens test queries would hang.
=> Bump number of queryExecutor threads in tests

core/trino-main/src/main/java/io/trino/operator/scalar/StringFunctions.java, core/trino-main/src/test/java/io/trino/operator/scalar/TestStringFunctions.java
Function to_utf8 doesn't support char type. When this function is applied to the char type in Hive, an error will be reported. This PR modifies to_utf8 function to support  char type in Hive. This function is important, because it also used in ranger-trino plugin for masking.
In hive, create a table using SQL: 
CREATE TABLE char_table_test (
id INT,
name string,
description CHAR(120)
);
insert into char_table_test values(1, 'xiaoming', 'he is a student');
insert into char_table_test values(2, 'honghong', 'she is a teacher');  
When using function to_utf8 in a sql, there is an error. 
To_utf8 doesn't support char type, as below:
**SQL1:**
select to_utf8(description) from char_table_test;
Query 20231218_125526_00001_ewnva failed: line 1:8: Unexpected parameters (char(120)) for function …
=> Function to_utf8 supports char type

core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java, core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java, core/trino-main/src/test/java/io/trino/execution/TestTaskManagerConfig.java, core/trino-spi/src/main/java/io/trino/spi/block/BlockUtil.java, core/trino-spi/src/main/java/io/trino/spi/block/IntArrayList.java, lib/trino-orc/src/main/java/io/trino/orc/OrcOutputBuffer.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java, plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/BingTileFunctions.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/SizeBasedSplitWeightProvider.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java, plugin/trino-ml/src/main/java/io/trino/plugin/ml/FeatureUnitNormalizer.java
Math.clamp(value, minValue, maxValue) is easier to reason about than Math.min(Math.max(value, minValue), maxValue)
No release notes needed
=> Use Math.clamp instead of min/max

testing/trino-product-tests/src/test/java/io/trino/tests/product/TestProductTestGroups.java
The `no_from` group no longer exists.
=> Fix test failure due to logical merge conflict

core/trino-main/src/main/java/io/trino/type/JsonPath2016Type.java, pom.xml
=> Update airbase, airlift and other dependencies

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java, plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java, plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java, plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java, plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
=> Remove deprecated createTableSql method from BaseJdbcClient

docs/src/main/sphinx/connector/mariadb.md, plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java, plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestMariaDbTypeMapping.java
improvement
Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)
MariaDB connector
How would you describe this change to a non-technical end user or system administrator?
Support datetime type in MariaDB connector
Fixes #17242 
=> Test datetime type in MariaDB connector

plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/SyncPartitionMetadataProcedure.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHive3OnDataLake.java
- Currently, `sync_partition_metadata()` procedure cannot handle the table located in the root bucket path, due to bug on the `listDirectoryName()` logic
- I know, using table mapped with the root bucket path is not the best practice, but we dumped some AWS logs(like cloudfront logs) into the root path of dedicated log bucket.
- the same strategy was already in use on [trino/lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystem.java](https://github.com/trinodb/trino/blob/f7369f674384b7cde8b5eb97931d679674930c2f/lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystem.java#L175-L177)
=> Add handling for root bucket table location in sync_partition_metadata

docs/src/main/sphinx/sql/drop-table.md
folliowing https://github.com/trinodb/trino/issues/11555
documentation
no
add documentation regarding an error
* Follow https://github.com/trinodb/trino/issues/11555
```markdown …
```
=> Document "DROP TABLE IF EXISTS" throws an error if view exists

docs/src/main/sphinx/connector/delta-lake.md, docs/src/main/sphinx/connector/optimize.fragment, docs/src/main/sphinx/sql/alter-table.md
Documentation for support Iceberg OPTIMIZE with WHERE casting timestamp_tz column to a date.
Fixes https://github.com/trinodb/trino/issues/12943
=> Document casting timestamp_tz column to a date as part of Iceberg optimize #12943

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitSource.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/FileBasedTableStatisticsProvider.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TableSnapshot.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriterManager.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakeUtils.java
Instead of waiting to get in bulk the collection of all
the active data files of a table relevant to a query, 
provide a stream of active add entries so that the 
split manager can start providing to the engine splits right away.
The active add entries stream is closeable in order to ensure that
the underlying checkpoint parquet page source gets closed
even when not all the entries from the checkpoint are consumed.
These changes should provide visible improvements in terms of reduced memory requirements when dealing with Delta Lake tables having many active `add` files, because as of now these files will not be held anymore in memory within `DeltaLakeSplitManager` due to the fact that the `add` files are processed as a consequence of the current changes now one by one.
**Potential …
=> Convert the retrieval of the active data files to streaming

docs/src/main/sphinx/connector/kafka.md
This is just a quick fix. I will probably send another PR for a major clean up of that doc.
Also @Jessie212 is there some outstanding work on all those decoders/encoders to be brought into consistent fragment usage or am I remembering wrongly and that work is already complete? 
=> Fix link title in Kafka docs

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMetadata.java
Use Delta Lake table property `partitioned_by` instead of `partition_by` which is incorrect.
=> Use correct table property name

core/trino-main/src/main/java/io/trino/operator/scalar/StringFunctions.java, core/trino-main/src/test/java/io/trino/operator/scalar/TestStringFunctions.java
As a temporary solution while fixing the coercion from char to varchar, adding lpad function signature that supports CHAR as input type for the string to be compatible with previous behavior.
Related issue: https://github.com/trinodb/trino/issues/9031
```markdown
```
=> Support char type text for lpad function

core/trino-main/src/main/java/io/trino/server/HttpRemoteTaskFactory.java, core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
This allows us to extract more info than just the node ID in the future.
Pass richer info into the `HttpRemoteTask` constructor, allowing it to do more in the future.
Right now we only pass the node identifier string into `HttpRemoteTask()`.  This doesn't let the task access, eg, the node's address.
```markdown
```
=> Pass InternalNode to HttpRemoteTask constructor

plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
It's covered by BaseConnectorTest.testCommentTable.
=> Remove redundant table comment test in Hive

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetComplexTypesPredicatePushDown.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestParquetPredicates.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
From https://trino.io/blog/2020/08/14/dereference-pushdown.html: "Another future improvement will be the pushdown of predicates on subfields for data stored in Parquet format. Although the pruning of nested fields occurs with Parquet, the predicates are not yet pushed down into the reader."
This PR enables Parquet page source to use statistics for nested fields in the iceberg connector.
Related ORC commit: https://github.com/trinodb/trino/commit/5069a55252dfc0958e68c140a4c49313096e9003
Fixes https://github.com/trinodb/trino/issues/9928
Hive change PR: https://github.com/trinodb/trino/pull/15163
() This is not user-visible or docs only and no release notes are required.
() Release notes are required, please propose a release note for me. …
=> Implement predicate push down for parquet dereference column in Iceberg

core/trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java, core/trino-parser/src/main/java/io/trino/sql/ReservedIdentifiers.java, core/trino-parser/src/main/java/io/trino/sql/RowPatternFormatter.java, core/trino-parser/src/main/java/io/trino/sql/jsonpath/PathNodeRef.java, core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java, core/trino-parser/src/main/java/io/trino/sql/parser/ErrorHandler.java, core/trino-parser/src/main/java/io/trino/sql/parser/ParsingException.java, core/trino-parser/src/main/java/io/trino/sql/testing/TreeAssertions.java, core/trino-parser/src/main/java/io/trino/sql/tree/NodeRef.java, core/trino-parser/src/test/java/io/trino/sql/TestSqlFormatter.java, core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java, core/trino-parser/src/test/java/io/trino/sql/parser/TestStatementBuilder.java, core/trino-spi/src/main/java/io/trino/spi/connector/ColumnSchema.java, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorTableSchema.java, core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorTableVersion.java, core/trino-spi/src/main/java/io/trino/spi/connector/SortItem.java, core/trino-spi/src/main/java/io/trino/spi/procedure/Procedure.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcSortItem.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/IcebergTableExecuteHandle.java, plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisShardCheckpointer.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotQueryBuilder.java, pom.xml
This is a new check in Error Prone 2.20.0. Per description: Prefer string concatenation over explicitly using `StringBuilder#append`, since `+` reads better and has equivalent or better performance.
Ever since Java 9 there are specialized optimizations for String concatenation and it no longer desugars to `StringBuilder` usage. This commit fixes mostly some very old-fashioned code where `StringBuilder` never really made sense anyway.
```markdown
```
=> Enable Error Prone check: UnnecessaryStringBuilder

client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcConnection.java, core/trino-main/src/main/java/io/trino/FeaturesConfig.java, core/trino-main/src/main/java/io/trino/SystemSessionProperties.java, core/trino-main/src/main/java/io/trino/execution/buffer/CompressionCodec.java, core/trino-main/src/main/java/io/trino/execution/buffer/PageDeserializer.java, core/trino-main/src/main/java/io/trino/execution/buffer/PageSerializer.java, core/trino-main/src/main/java/io/trino/execution/buffer/PagesSerdeFactory.java, core/trino-main/src/main/java/io/trino/server/protocol/Query.java, core/trino-main/src/main/java/io/trino/spiller/FileSingleStreamSpillerFactory.java, core/trino-main/src/main/java/io/trino/spiller/NodeSpillConfig.java, core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java, core/trino-main/src/test/java/io/trino/execution/TestSqlTaskExecution.java, core/trino-main/src/test/java/io/trino/execution/buffer/BenchmarkBlockSerde.java, core/trino-main/src/test/java/io/trino/execution/buffer/BenchmarkPagesSerde.java, core/trino-main/src/test/java/io/trino/execution/buffer/TestPagesSerde.java, core/trino-main/src/test/java/io/trino/execution/buffer/TestSpoolingExchangeOutputBuffer.java, core/trino-main/src/test/java/io/trino/execution/buffer/TestingPagesSerdeFactory.java, core/trino-main/src/test/java/io/trino/operator/output/BenchmarkPartitionedOutputOperator.java, core/trino-main/src/test/java/io/trino/operator/output/TestPagePartitioner.java, core/trino-main/src/test/java/io/trino/operator/spiller/BenchmarkBinaryFileSpiller.java, core/trino-main/src/test/java/io/trino/spiller/TestBinaryFileSpiller.java, core/trino-main/src/test/java/io/trino/spiller/TestFileSingleStreamSpiller.java, core/trino-main/src/test/java/io/trino/spiller/TestFileSingleStreamSpillerFactory.java, core/trino-main/src/test/java/io/trino/spiller/TestNodeSpillConfig.java, core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java, docs/src/main/sphinx/admin/properties-exchange.md, docs/src/main/sphinx/admin/properties-spilling.md
Our community knows that ZSTD compression is better about speed and compression ratio in many scenarios, for example:  https://github.com/trinodb/trino/issues/10058  
Many blogs and test reports on the internet also mentioned that ZSTD is better than ZLIB in most cases:  https://databento.com/blog/zstd-vs-zlib
We found that if page serialization and deserialization also use ZSTD, the **compression and decompression performance** is also better, and `Fault Tolerant Execution` also uses compressed pages:  https://github.com/trinodb/trino/pull/14957
The benchmark result is shown as below, It seems that if compression is enabled, Zstd is about 10X faster than Lz4.  
Because ZSTD may not be a best choice for all scenarios, and we want to take into account the demands of different users, we …
=> Add compression codec configurations for data in exchanges and spills

.github/workflows/ci.yml
This will check for forward compatibility with newer Java version (at least for compilation and APIs used)
=> Run maven-checks with JDK 22-ea

core/trino-spi/src/main/java/io/trino/spi/block/RowBlockBuilder.java
```markdown
* Fix ArrayIndexOutOfBoundsException with RowBlockBuilder during output operations. ({issue}`20426`)
```
=> Fix array growth calculation in RowBlockBuilder

testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeInsertCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DatabricksVersion.java
Could not find a reason for this behavior change in the Databricks release notes, but the incorrect behavior in the Databricks engine seems to have stopped.
Results from the last build on `master`
```
tests               | 2024-01-19 20:03:39 INFO: FAILURE     /    io.trino.tests.product.deltalake.TestDeltaLakeInsertCompatibility.testTimestampInsertCompatibility (Groups: profile_specific_tests, delta-lake-exclude-91, delta-lake-databricks, delta-lake-oss) took 11.5 seconds
tests               | 2024-01-19 20:03:39 SEVERE: Failure cause:
tests               | java.lang.AssertionError: Could not find rows:
tests               | [1, 0001-01-03 00:00:00.000]
tests               | 
tests               | actual rows:
tests               | [1, 0001-01-01 00:00:00.000]
tests               | [2, …
```
=> Fix Databricks 13.3 timestamp compatibility test

core/trino-spi/src/main/java/io/trino/spi/function/ScalarFunctionAdapter.java, core/trino-spi/src/test/java/io/trino/spi/function/TestScalarFunctionAdapter.java
When adapting a nullable function to a BLOCK_BUILDER return, a null must be appended when the function return value is null.
Fixes #18456
```markdown
* Fix adaptation of nullable function return to `BLOCK_BUILDER`. ({issue}`18456`)
```
=> Fix adaptation of nullable return to BLOCK_BUILDER

docs/src/main/sphinx/functions/datetime.md
Improve The date_trunc function documentation add unit millisecond
Fixes https://github.com/trinodb/trino/issues/20427
=> Document millisecond unit for date_trunc function

core/docker/build.sh, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/jdk/Temurin21JdkProvider.java
=> Use jdk-21.0.2+13 in product tests and docker

lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/AvroPageDataReader.java, lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroPageDataReaderWithoutTypeManager.java
Hive/Avro: Handle all union options coersion to single type
#20310 
Hive/Avro: Handle all union options coersion to single type.
For example: can now read: `["string","bytes"]` with  schema `"string"` or `"bytes"`. 
```markdown
```
=> HIVE/AVRO: Handle all union options coersion to single type

docs/src/main/sphinx/admin/fault-tolerant-execution.md, docs/src/main/sphinx/admin/properties-exchange.md, docs/src/main/sphinx/admin/properties-spilling.md, docs/src/main/sphinx/admin/spill.md
* Update wording and related content
* Remove deprecated property
Follow up to https://github.com/trinodb/trino/pull/20274
Ideally we should get this PR in before the release since the current docs are kinda wrong.
=> Fix docs from compression codec use

docs/release-template.md, docs/src/main/sphinx/release.md, docs/src/main/sphinx/release/release-437.md
Assemble the release notes for the upcoming Trino 437 release. Fixes #20353 
* #20351 ✅ rn ✅ docs
* #20354 ✅ rn ✅ docs
* #20350 ✅ rn ✅ docs
* #20328 ✅ rn ✅ docs
* #20345 ✅ rn ✅ docs
* #20352 ✅ rn ✅ docs
* #20160 ✅ rn ✅ docs
* #20357 ✅ rn ✅ docs
* #20322 ✅ rn ✅ docs
* #20356 ✅ rn ✅ docs
* #20321 ✅ rn ✅ docs
* #20158 ✅ rn ❌ docs
* #20358 ✅ rn ✅ docs
* #20364 ✅ rn ✅ docs
* #20365 ✅ rn ✅ docs
* #20370 ✅ rn ✅ docs
* #20369 ✅ rn ✅ docs
* #20241 ✅ rn ✅ …
=> Add Trino 437 release notes

core/trino-main/src/main/java/io/trino/operator/aggregation/ReduceAggregationFunction.java, core/trino-main/src/main/java/io/trino/operator/aggregation/state/GenericSliceState.java, core/trino-main/src/main/java/io/trino/operator/aggregation/state/GenericSliceStateSerializer.java, docs/src/main/sphinx/functions/aggregate.md, testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java
I've stumbled upon `JDK-8017163` reference while going through the process of cleaning up after switching to JDK 21. Since it's solved, I've added a support to Slice serialization in the reduce_agg function.
=> Add Slice support to reduce_agg function

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMigrateProcedure.java
Remove redundant code from TestIcebergMigrateProcedure
=> Remove redundant code from TestIcebergMigrateProcedure

core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
Fix calculating `zero/zero` when setting [StageCpuDistribution average](https://github.com/trinodb/trino/blob/master/core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageCpuDistribution.java) value and set it as 0.0 value when snapshot has no info for stage. 
e.g) Sample data for `List<StageCpuDistribution>` in [QueryStatistics](https://github.com/trinodb/trino/blob/master/core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryStatistics.java#L128) shows that in some stages, tasks/p values is all zero so snapshot total/count is also zero.
> [{"stageId":"0","tasks":"0","p25":"0","p50":"0","p75":"0","p90":"0","p95":"0","p99":"0","min":"0","max":"0","total":"0","average":"NaN"},{"stageId":"1","tasks":"93","p25":"3","p50":"3","p75":"3","p90":"3","p95":"3","p99":"7","min":"1","max …
=> Fix divide by zero

core/trino-main/src/main/java/io/trino/Session.java, core/trino-main/src/main/java/io/trino/connector/CoordinatorDynamicCatalogManager.java, core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java, core/trino-main/src/main/java/io/trino/execution/RenameMaterializedViewTask.java, core/trino-main/src/main/java/io/trino/execution/RenameTableTask.java, core/trino-main/src/main/java/io/trino/execution/RenameViewTask.java, core/trino-main/src/main/java/io/trino/metadata/MetadataUtil.java, core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java, core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java, core/trino-main/src/test/java/io/trino/execution/TestDropCatalogTask.java, core/trino-main/src/test/java/io/trino/execution/TestSetPathTask.java, core/trino-main/src/test/java/io/trino/execution/TestSetRoleTask.java, core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java, core/trino-main/src/test/java/io/trino/sql/query/TestExecuteImmediate.java, testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java, testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java, testing/trino-tests/src/test/java/io/trino/tests/TestServer.java
The error code name when a catalog is not found is `CATALOG_NOT_FOUND` but the message is always `Catalog 'X' does not exist` which doesn't match the error name. This PR changes all the error messages to `Catalog 'X' not found`
=> Change catalog not found error messages to match error code name

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueTableOperationsInsertFailure.java
Fixes #20471 
Test related refactoring.
Potential follow-up: We should potentially wrap `CommitStateUnknown` exceptions (and potentially other exceptions as well) in `TrinoException` to provide the user a more meaningful error code.
Follow-up for #20048 
=> TestIcebergGlueTableOperationsInsertFailure: Adjust expectations for the thrown exception

docs/src/main/sphinx/connector/delta-lake.md, docs/src/main/sphinx/connector/object-storage-file-formats.md, lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java, lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriterOptions.java, lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriters.java, lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java, lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSessionProperties.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSessionProperties.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetFileWriterFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetWriterConfig.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/ParquetTester.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetWriterConfig.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
Allows reducing the size of pages kept in memory by parquet reader
https://trinodb.slack.com/archives/CJ6UC075E/p1703253052321499?thread_ts=1700671385.606089&cid=CJ6UC075E
```markdown
* Allow configuring maximum value count of pages written in parquet files. The default value of 60000 can be modified using the catalog configuration property `parquet.writer.page-value-count` or the corresponding catalog session property. ({issue}`20171`)
```
=> Allow configuring maximum value count of pages written in parquet

docs/src/main/sphinx/admin/properties-http-client.md
See https://trinodb.slack.com/archives/CP1MUNEUX/p1701464071442409
According to @electrum the property is not used.
Maybe we should also list all the subsystems where these properties are used .. wdyt @electrum ?
=> Remove unused property

docs/src/main/sphinx/admin/properties-spilling.md
See title. Plus https://trino.io/docs/current/admin/properties.html contains 
"Unless specified otherwise, configuration properties must be set on the coordinator and all worker nodes." 
this adds a "specified otherwise"
Fixes #4012 
=> Improve spilling docs for workers

docs/src/main/sphinx/connector/pinot.md, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTypeConverter.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/decoders/DecoderFactory.java, plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotConnectorSmokeTest.java, plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/PinotQueryRunner.java, plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConnectorTest.java, plugin/trino-pinot/src/test/resources/alltypes_realtimeSpec.json, plugin/trino-pinot/src/test/resources/customer_realtimeSpec.json, plugin/trino-pinot/src/test/resources/customer_schema.json, plugin/trino-pinot/src/test/resources/date_time_fields_realtimeSpec.json, plugin/trino-pinot/src/test/resources/dup_table_lower_case_realtimeSpec.json, plugin/trino-pinot/src/test/resources/dup_table_mixed_case_realtimeSpec.json, plugin/trino-pinot/src/test/resources/duplicate_values_in_columns_realtimeSpec.json, plugin/trino-pinot/src/test/resources/hybrid_realtimeSpec.json, plugin/trino-pinot/src/test/resources/json_realtimeSpec.json, plugin/trino-pinot/src/test/resources/mixed_case_distinct_realtimeSpec.json, plugin/trino-pinot/src/test/resources/mixed_case_realtimeSpec.json, plugin/trino-pinot/src/test/resources/mixed_case_table_name_realtimeSpec.json, plugin/trino-pinot/src/test/resources/nation_realtimeSpec.json, plugin/trino-pinot/src/test/resources/orders_realtimeSpec.json, plugin/trino-pinot/src/test/resources/orders_schema.json, plugin/trino-pinot/src/test/resources/quotes_in_column_name_realtimeSpec.json, plugin/trino-pinot/src/test/resources/realtimeSpec.json, plugin/trino-pinot/src/test/resources/region_realtimeSpec.json, plugin/trino-pinot/src/test/resources/reserved_keyword_realtimeSpec.json, plugin/trino-pinot/src/test/resources/too_many_broker_rows_realtimeSpec.json, plugin/trino-pinot/src/test/resources/too_many_rows_realtimeSpec.json
Fixes #13059
In order to pass the connector test we need to support the date type.
This is similar to what is done for the datetime fields and timestamp types for other resolutions (1 ms, 1 sec, etc.)
```markdown
* Add support for `DATE` type. ({issue}`17582`)
```
=> Add support for `DATE` type and run BaseConnectorTest in Pinot Connector

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/configs/ConfigDefault.java
The default config was excluding some tests in favor of `config-hdp3` (`ConfigHdp3`), which was faster. But the latter got removed in ceb8e1572047c7ecb8854f28ae21a5e4200c3e34. Since then the tests in affected groups were probably not run.
=> Fix never run some product tests groups

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/DeterminePartitionCount.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/JoinMatcher.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/PlanMatchPattern.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestDeterminePartitionCount.java
The notion of partitions count make sense for pipelined exection even
for arbitrary partitioned exchanges as it directly translates to number
of execution tasks.
In FTE the number of partitions for arbitrary distributed exchanges is
alwasy 1 and number of tasks comes from the bin-packing logic done in
Split assigner.
=> Only set partition count for HASH partitioned exchanges in FTE

docs/src/main/sphinx/routines/examples.md
Showcases the following aspects
- Routines can call each other
- Signature is name and parameters
- Creation of optional parameters
Added syntax-needs-review label to get confirmation that this overloading and default value creation is ok to document.
=> Add dots example routine

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMigrateProcedure.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java
Fix https://github.com/trinodb/trino/issues/17583
https://github.com/apache/iceberg/blob/master/core/src/main/java/org/apache/iceberg/TableMetadata.java#L103 Will reassign columnId start from 1, we need to reset `nextFieldId`.
```markdown
* Add support for `array`, `map` and `row` types in migrate procedure. ({issue}`17583`)
```
=> Support complex type in migrate procedure

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/TrinoNessieCatalog.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestIcebergNessieCatalogConnectorSmokeTest.java
PR [#16674](https://github.com/trinodb/trino/pull/16674) added support for dropping corrupted Iceberg tables but the Nessie catalog implementation was missing.
Similar as done in the Glue catalog implementation, we load the metadata location from Nessie and extract the table location from it. This allows us to drop the directory where the Iceberg table is located in.
This is a follow up of [#16674](https://github.com/trinodb/trino/pull/16674)
This is not user-visible or is docs only, and no release notes are required.
=> Add support for dropping corrupted tables to Iceberg Nessie Catalog

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/DataFileWithDeleteFiles.java
Previous implementation was missing equal and hashcode 
(Fixes 'splits already set to' in Iceberg optimize) Release notes are required, with the following suggested text:
```markdown
```
=> Fix IcebergSplitSource.scannedFiles set semantics

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionIntoTableScan.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java
Constant expression should not be passed to the Connector since the connector cannot do anything meaningful with it. Added fix to filter out constant expressions before being pushed to the connector.
Fixes #19988. Constant expressions are being passed on to the connector via `Metadata.applyProjection` method during planning in the rule `PushProjectionIntoTableScan`. But, the connector cannot do anything meaningful with it. Therefore, this PR filters out constant expressions before applying the projections to the connector. Also, have changed the `TestPushProjectionIntoTableScan.testPushProjection` test for verification.
( ) Release notes …
=> Fixed constant expression being passed to Connector through applyProjection

core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxbyn/TypedKeyValueHeap.java
Fix compaction of TestTypedKeyValueHeap with non-null variable-width values.
Fixes #20524
Reproducing the underlying bug requires triggering compaction in a way that triggers an array index of out bounds.  The can be reproduced with the following code in `TestTypedKeyValueHeap`, but requires a lot of rounds to reproduce.
```java
@Test
public void testCompaction()
{
int capacity = 3;
int maxSize = 1_000_000;
int chunkSize = 1000;
Slice entry = Slices.allocate(maxSize);
entry.fill((byte) 'x');
int round = 1;
while (true) {
System.out.println("test round: " + round++);
TypedKeyValueHeap heap = createTypedKeyValueHeap(BIGINT, VARCHAR, false, capacity);
BlockBuilder keyBlockBuilder = BIGINT.createBlockBuilder(null, heap.getCapacity());
BlockBuilder valueBlockBuilder = …
```
=> Fix  TypedKeyValueHeap compaction

core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java, plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java, plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java, testing/trino-tests/src/test/java/io/trino/execution/TestGrantOnSchema.java
Follow up to https://github.com/trinodb/trino/pull/20509
=> More assertion related cleanups 

core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java, core/trino-spi/src/main/java/io/trino/spi/block/RunLengthEncodedBlock.java
This is required because RowBlock is ValueBlock
but can still be lazy.
```markdown
* Fix lazy block errors while reading table data. ({issue}`issuenumber`)
```
=> Restore getLoadedBlock methods (for dictionary and RLE)

core/trino-main/src/main/java/io/trino/operator/output/RowPositionsAppender.java
RowPositionsAppender reset call was not being propigated to nested fields.  This would result in missized fields blocks that were not the correct size for the row block.
Add validation calls as row fields are built to detect bugs closer to the source.
```markdown
* Fix failure of queries over data with deeply nested rows. ({issue}`20529`)
```
=> Propagate RowPositionsAppender reset to fields

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeAlterTableCompatibility.java
Fixes #20448 
```markdown
* Add support for `ALTER COLUMN ... DROP NOT NULL` statement. ({issue}`20448`)
```
=> Add support for `ALTER COLUMN ... DROP NOT NULL` statement in Delta Lake connector

docs/src/main/sphinx/release.md, docs/src/main/sphinx/release/release-437.md, docs/src/main/sphinx/release/release-438.md
Assemble the release notes for the upcoming Trino 438 release.
* #20442 ✅ rn ✅ docs
* #20460 ✅ rn ✅ docs
* #20288 ✅ rn ✅ docs
* #20456 ✅ rn ✅ docs
* #20463 ✅ rn ✅ docs
* #20129 ✅ rn ✅ docs
* #20465 ✅ rn ✅ docs
* #20461 ✅ rn ✅ docs
* #20459 ✅ rn ✅ docs
* #20221 ✅ rn ✅ docs
* #20172 ✅ rn ✅ docs
* #20468 ✅ rn ✅ docs
* #20452 ✅ rn ✅ docs
* #20472 ✅ rn ✅ docs
* #20376 ✅ rn ✅ docs
* #20464 ✅ rn ✅ docs
* #20470 ✅ rn ✅ docs
* #20475 ✅ rn ✅ docs
* #20462 ✅ rn ✅ docs
* …
=> Add Trino 438 release notes

plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcWriterOptions.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java
I think that if table metadata does not have FPP value, default fpp value should be used for bloom filter for writing ORC files.
As of now, it returns error saying that `FPP for bloom filter is missing`, which is ironic as
1. Hive uses default bloom filter value (0.05%) if value is missing
2. Trino doc saids that default value of fpp is 0.05
Hive has default bloom filter of 0.05 (5%) 
- https://github.com/apache/hive/blob/master/storage-api/src/java/org/apache/hive/common/util/BloomFilter.java#L44
Trino doc saids that default value of fpp is 0.05
- https://trino.io/docs/current/connector/hive.html#table-properties
(x) Release notes are …
=> use default fpp for writing in Hive connector if not provided in table metadata

testing/trino-testing-containers/src/main/java/io/trino/testing/containers/junit/ReportLeakedContainers.java, testing/trino-testing-services/pom.xml, testing/trino-testing-services/src/main/java/io/trino/testing/services/junit/Listeners.java, testing/trino-testing-services/src/main/java/io/trino/testing/services/junit/LogTestDurationListener.java, testing/trino-testing-services/src/main/java/io/trino/testng/services/Listeners.java, testing/trino-testing-services/src/main/resources/META-INF/services/org.junit.platform.launcher.TestExecutionListener, testing/trino-testing-services/src/test/java/io/trino/testng/services/TestReportMultiThreadedBeforeOrAfterMethod.java, testing/trino-testing-services/src/test/java/io/trino/testng/services/TestReportPrivateMethods.java, testing/trino-testing-services/src/test/java/io/trino/testng/services/TestSharedResource.java
Copy `LogTestDurationListener` that exists for TestNG and adapt it for
JUnit. This is useful when troubleshooting tests that take long time on
CI.
=> Log long tests' duration 

core/trino-main/src/main/java/io/trino/server/HttpRequestSessionContextFactory.java, core/trino-main/src/test/java/io/trino/server/TestHttpRequestSessionContextFactory.java
When catalog name contains a dot.
Fixes https://github.com/trinodb/trino/issues/20474
Release notes: Fix `SET SESSION` handling when catalog name contains a dot
=> Fix catalog session properties parsing

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemConfig.java, lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemFactory.java, lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemConfig.java
Adds support for specifying more configuration options in `S3FileSystemConfig`. New configuration options are:
- `s3.connection-ttl` (default: none, same as S3 client default when not specified)
- `s3.connection-max-idle-time` (default: not specified, S3 client defaults to 1 minute when not specified)
- `s3.socket-connect-timeout` (default: not specified, S3 client defaults to 2 seconds when not specified)
- `s3.socket-read-timeout` (default: not specified, S3 client defaults to 5 seconds when not specified)
- `s3.tcp-keep-alive` (default: false, same as S3 client default when not specified) …
=> Add more options to S3FileSystemConfig

docs/src/main/sphinx/connector/iceberg.md
A question came up on the Trino Slack about Kerberos authentication for the Apache Iceberg connector, I've tested it and it works using the same parameters as the Hive connector. I added a short paragraph to the Iceberg connector docs referring to the Hive authentication docs.
Docs only update
=> Added docs link for Kerberos authentication with Iceberg connector

docs/src/main/sphinx/develop/connectors.md
The `REAL` type is mapped to Java `long`, not `double`.
The documentation currently states that the `REAL` type uses the Java carrier type `double`, but from what I can tell from the `RealType` implementation, the Java type used is actually `long`.
Found while working on Neo4j connector.
Sources:
[`RealType extends AbstractIntType`](https://github.com/trinodb/trino/blob/master/core/trino-spi/src/main/java/io/trino/spi/type/RealType.java#L50)
[`AbstractIntType` passes `long.class` as javaType](https://github.com/trinodb/trino/blob/master/core/trino-spi/src/main/java/io/trino/spi/type/AbstractIntType.java#L54)
( ) Release notes are required, …
=> Fix type mapping documentation error.

core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOidcDiscovery.java
Pull the part which is not supposed to throw outside of `assertThatThrownBy`.
=> Reduce assertThatThrownBy scope in TestOidcDiscovery

core/trino-main/src/main/java/io/trino/sql/planner/ExpressionExtractor.java, core/trino-main/src/main/java/io/trino/sql/planner/SubqueryPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PruneApplyColumns.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PruneApplySourceColumns.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantExists.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedInPredicateToJoin.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformExistsApplyToCorrelatedJoin.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformUncorrelatedInPredicateSubqueryToSemiJoin.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapSingleColumnRowInApply.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/SymbolMapper.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/TransformQuantifiedComparisonApplyToCorrelatedJoin.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/UnaliasSymbolReferences.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/ApplyNode.java, core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java, core/trino-main/src/main/java/io/trino/sql/planner/sanity/ValidateDependenciesChecker.java, core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/ExpressionMatcher.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/PlanMatchPattern.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/SetExpressionMatcher.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/StrictAssignedSymbolsMatcher.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneApplyColumns.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneApplyCorrelation.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneApplySourceColumns.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveRedundantExists.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRemoveUnreferencedScalarApplyNodes.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformExistsApplyToCorrelatedJoin.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformUncorrelatedInPredicateSubqueryToSemiJoin.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestUnwrapSingleColumnRowInApply.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
The set expressions in ApplyNode (IN, EXISTS and quantified comparisons) are currently modeled using AST nodes. This is not appropriate, as the expressions are not regular scalar expression -- the right hand side represents a set of values.
In this change, we introduce a new dedicated IR-specific abstraction within ApplyNode to model those expressions.
=> Decouple ApplyNode expressions from AST

plugin/trino-iceberg/pom.xml
Remove unused sqlite-jdbc from Iceberg
=> Remove unused sqlite-jdbc from Iceberg

core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java, core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/BaseViewReferenceInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/ColumnMaskReferenceInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/FilterMaskReferenceInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/MaterializedViewReferenceInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/RowFilterReferenceInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/TableInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/TableReferenceInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/ViewReferenceInfo.java, testing/trino-tests/src/test/java/io/trino/common/assertions/BaseViewReferenceInfoAssert.java, testing/trino-tests/src/test/java/io/trino/common/assertions/FilterMaskReferenceInfoAssert.java, testing/trino-tests/src/test/java/io/trino/common/assertions/TableInfoAssert.java, testing/trino-tests/src/test/java/io/trino/common/assertions/TableReferenceInfoAssert.java, testing/trino-tests/src/test/java/io/trino/common/assertions/TrinoAssertions.java, testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
In #7330, a flag `directlyReferenced` was added to `TableInfo` to indicate whether a given table or view was directly referenced, or indirectly referenced via a view/filter/mask. This is useful, but lacks the information necessary to understand what caused the indirect reference. Understanding the context can be useful for auditing purposes, as well as general lineage use cases.
As one motivating example, let us say we have have the following:
- table `foo` contains user data (PII)
- view `foo_sanitized` provides a view over `foo` with PII columns removed
- view `foo_dirty` defined as `SELECT * FROM foo`
- legal requirement that when reading user data for a certain use case `bar`, PII cannot be used
Auditing is one way to enforce that queries run for `bar` only make use of `foo_sanitized` …
=> Add view text and reference chain information to TableInfo

plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemorySplitManager.java
Add toString() method for DelayedSplitSource to make output of stuck FTE scheduler more complete.
=> Add toString for DelayedSplitSource

core/trino-main/src/test/java/io/trino/operator/scalar/TestBlockAndPositionNullConvention.java
Looks like it got lost during the refactoring in commit 98c5243898e7068b264b2fef26021b6249eff7c9. Originally it used `null` for a generic object type, but perhaps a "real" object like row is better here.
This was detected by the write-only object inspection in IDEA: the `hitBlockPositionObject` was reported as never read from.
```markdown
```
=> Add missing test case to TestBlockAndPositionNullConvention

lib/trino-orc/src/main/java/io/trino/orc/OrcWriter.java, lib/trino-orc/src/test/java/io/trino/orc/TestOrcWriter.java
Fix #20587 
```markdown
* Fix IndexOutOfBoundsException when writing huge chunk in ORC. ({issue}`20587`)
```
=> Fix error when writing huge chunk in ORC

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java, lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedSystemAccessControlTest.java
If we using FileBasedSystemAccessControl and execute or kill query using a user which is not match rule, FileBasedSystemAccessControl will throw `Cannot view query` rather than `Cannot execute query` or `Cannot kill query`
```
io.trino.spi.security.AccessDeniedException: Access Denied: Cannot view query
at io.trino.spi.security.AccessDeniedException.denyViewQuery(AccessDeniedException.java:98)
at io.trino.spi.security.AccessDeniedException.denyViewQuery(AccessDeniedException.java:93)
at io.trino.plugin.base.security.FileBasedSystemAccessControl.checkCanExecuteQuery(FileBasedSystemAccessControl.java:338)
at io.trino.security.AccessControlManager.lambda$checkCanExecuteQuery$6(AccessControlManager.java:266)
at io.trino.security.AccessControlManager.systemAuthorizationCheck(AccessControlManage …
```
=> Fix incorrect deny message in FileBasedSystemAccessControl

docs/src/main/sphinx/connector.md, docs/src/main/sphinx/connector/delta-lake.md, docs/src/main/sphinx/connector/filesystem-cache.md
Currently only for Delta Lake as in the linked PR
Powered by Alluxio.
Should be merged for same release notes as the code PR and release note entry should link to the documentation.
Code PR is https://github.com/trinodb/trino/pull/18719
Part of #20550 
=> Add docs for filesystem caching

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeModule.java
=> Remove unused TransactionalMetadataFactory in Delta Lake

core/trino-main/src/main/java/io/trino/sql/planner/LiteralEncoder.java
CAST to varchar(x) throws INTERNAL ERROR if the value doesn't fit in the bounded length due to https://github.com/trinodb/trino/pull/10172. But it would be better to treat as USER ERROR.
```sql
select CAST(now() AS VARCHAR(10));
```
This query causes INTERNAL_ERROR with the following exception:
```
java.lang.IllegalArgumentException: Value [2024-02-06 02:01:37.343 Asia/Tokyo] does not fit in type varchar(10)
at io.trino.sql.planner.LiteralEncoder.toExpression(LiteralEncoder.java:208)
at io.trino.sql.planner.iterative.rule.SimplifyExpressions.rewrite(SimplifyExpressions.java:55)
at io.trino.sql.planner.iterative.rule.SimplifyExpressions.lambda$createRewrite$0(SimplifyExpressions.java:79)
at io.trino.sql.planner.iterative.rule.ExpressionRewriteRuleSet$ProjectExpressionRewrite.lambda$apply$0( …
```
=> Treat error in cast to varchar(x) as USER_ERROR

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
Relates to https://github.com/trinodb/trino/issues/20178
=> Disable slow test temporarily in BigQuery

core/trino-spi/src/main/java/io/trino/spi/eventlistener/BaseViewReferenceInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/ColumnMaskReferenceInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/FilterMaskReferenceInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/MaterializedViewReferenceInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/RowFilterReferenceInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/TableReferenceInfo.java, core/trino-spi/src/main/java/io/trino/spi/eventlistener/ViewReferenceInfo.java, core/trino-spi/src/test/java/io/trino/spi/eventlistener/TestTableReferenceInfo.java, testing/trino-tests/src/test/java/io/trino/common/assertions/BaseViewReferenceInfoAssert.java, testing/trino-tests/src/test/java/io/trino/common/assertions/FilterMaskReferenceInfoAssert.java
Refactors `TableReferenceInfo` implementations into sealed interfaces and record classes to reduce boilerplate and the risk of implementation bugs such as mismatches between getter field names and concrete class class constructor arguments (such as was previously the case between `RowFilterReferenceInfo` and `FilterMaskReferenceInfo`).
Follows up from https://github.com/trinodb/trino/pull/18871
=> Refactor TableReferenceInfo implementing classes

core/trino-main/src/main/java/io/trino/operator/output/RowPositionsAppender.java
Removes a redundant loop over `UnnestingPositionAppenders#reset()` from `RowPositionsAppender#build()` since the subsequent call to `RowPositionsAppender#reset()` in the same method will itself perform a reset loop after https://github.com/trinodb/trino/pull/20529
=> Remove redundant PositionsAppender reset loop

pom.xml
Fixes a potential JVM crash when decompressing corrupted Snappy data.
```markdown
* Fixes potential crash when decompressing corrupted Snappy data. ({issue}`20631`)
```
=> Update aircompressor to 0.26

lib/trino-hdfs/pom.xml
I recall that we had a check that was verifying that listed provided deps are only in provided scope but I can't find it.
=> Move dependencies to provided scope for HDFS

docs/src/main/sphinx/connector/decimal-type-handling.fragment
* This PR clarifies the wording of the Decimal type handling fragment. Users should set the `decimal-mapping` config property or `decimal_mapping` session propery to `allow_overflow` to ensure that the default precision of 38 and scale of 0 are used. Failure to do so ignores `DECIMAL` types with unspecified precision.
```markdown
```
=> Clarify decimal type handling behavior

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetastoreClosure.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveColumnStatistics.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SparkMetastoreUtil.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/StatisticsUpdateMode.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/ColumnStatistics.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/PartitionMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/TableMetadata.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueColumnStatisticsProvider.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueColumnStatisticsProvider.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueStatConverter.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/BridgingHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/tracing/TracingHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/statistics/AbstractHiveStatisticsProvider.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/Statistics.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHive3OnDataLake.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestSparkMetastoreUtil.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestStatisticsUpdateMode.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/file/TestColumnStatistics.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftMetastoreUtil.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/statistics/TestMetastoreHiveStatisticsProvider.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTableStatistics.java
Trino and Hive have different stats for number of distinct values and average size.  Currently this translation is happening inside of each Hive metastore implementation, which is complex and redundant. Instead this PR moves translation to
the layer that translate connector stats to and from engine stats.
=> Hive stats adaptation from metastore implementations to SPI conversion layer

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java
- This PR changes the IO output metadata for `REFRESH MATERIALIZED VIEW` statements
* Currently the IO output metadata is registered for the MV storage table (`<mvName$materialized_view_storage>`
* Since Trino recently abstracted the Materialized View storage table to the end user, this PR changes the IO output metadata to be registered for the Materialized View itself, instead of it's storage table
```markdown
* Change the event listener output metadata for materialized view refreshes to target the materialized view definition instead of its storage table
```
=> Change IO metadata output for refresh materialized view operation

core/trino-main/src/main/java/io/trino/execution/executor/dedicated/ConcurrencyController.java, core/trino-main/src/main/java/io/trino/execution/executor/dedicated/TaskEntry.java, core/trino-main/src/main/java/io/trino/execution/executor/dedicated/ThreadPerDriverTaskExecutor.java, core/trino-main/src/test/java/io/trino/execution/TestSqlTaskManagerThreadPerDriver.java, core/trino-main/src/test/java/io/trino/execution/executor/dedicated/TestThreadPerDriverTaskExecutor.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcMetricsCollection.java
=> Limit the max number of drivers per task in thread-per-driver scheduler

core/trino-main/src/main/java/io/trino/testing/assertions/TrinoExceptionAssert.java, testing/trino-testing/src/main/java/io/trino/testing/QueryAssertions.java, testing/trino-tests/src/test/java/io/trino/tests/TestQueryAssertions.java
Change `assertQueryFails` so that it verifies the message that the
end-user would see. Before the change, `assertQueryFails` would accept
any TrinoException that has expected message somewhere in the causal
chain. However, causal chain may or may not be visible to the end user,
depending on the tooling used. This restores the behavior that used to
be before commit https://github.com/trinodb/trino/commit/0a56d09d5b30ae882a61e4a5d26bf3cc054de9e5 (https://github.com/trinodb/trino/pull/20048).
Tests that want to verify causal message should do this explicitly.
=> Verify user-visible message in assertQueryFails

docs/src/main/sphinx/release/release-437.md
The behavior described is Iceberg connector-specific. We cannot determine what would be the behavior of a connector if it implemented materialized views support, so the wording was not generally appropriate.
=> Move RN entry to connector

docs/src/main/sphinx/release/release-438.md
The original PR was not supposed to fix a query failure (otherwise it would have regression tests for that.)
=> Remove optimize failure RN entry

core/trino-main/src/main/java/io/trino/connector/WorkerDynamicCatalogManager.java
Make Catalog loading for tasks 
- Concurrent across tasks
- parallel within tasks
```markdown
```
=> Parallel Task Catalog Loading

lib/trino-filesystem/src/main/java/io/trino/filesystem/cache/CacheFileSystem.java, plugin/trino-iceberg/pom.xml, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplit.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitManager.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/cache/IcebergCacheKeyProvider.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAlluxioCacheFileOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioParquetCachingConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java, testing/trino-product-tests-groups/src/main/java/io/trino/tests/product/TestGroups.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeIcebergMinioCaching.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteIceberg.java, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-iceberg-minio-cached/iceberg.properties, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergAlluxioCaching.java
In this patch we are extending the alluxio changes which exists currently for Delta connector to also include Iceberg.
Related issue: https://github.com/trinodb/trino/issues/19829
Part of #20550
```markdown
```
=> Extend Alluxio support to Iceberg connector

core/trino-main/pom.xml
If UI was built, maven will copy `node_modules` to target-classes which takes around 20-30s.
./mvnw clean resources:resources -pl ':trino-main' -DskipTests
Before:
`Copying 9969 resources from src/main/resources to target/classes`
After:
`Copying 107 resources from src/main/resources to target/classes`
```markdown
```
=> Do not copy node_modules in trino-main

lib/trino-filesystem-cache-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioInputStream.java, lib/trino-filesystem-cache-alluxio/src/test/java/io/trino/filesystem/alluxio/TestFuzzAlluxioCacheFileSystem.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite5.java
Fix a bug in `AlluxioInputStream.read` where we might repeatedly read 0 bytes, depending on the underlying file system, causing infinite loops. Thanks to @raunaqmorarka for reporting that this happens for RCBINARY and the Hadoop file system.
What happens is:
1. We want to read byte 100.
2. We align the read to the beginning of the page (0), the external stream only returns 99 bytes.
3. We put the 99 bytes in the cache (this is not even correct, as we assume pages are always complete).
4. We return 0 bytes read to the caller.
5. Go back to step 1. when caller attempts to read byte 100 again, and we make no progress. …
=> Fix bug on streaming reads in Alluxio cache 

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
Return DatasetId and TableId lists in BigQueryClient to avoid misusage. 
=> Return DatasetId and TableId in BigQueryClient

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Environment.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentContainers.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentListener.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentModule.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentOptions.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Tracing.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/StandardMultinode.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeTls.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeTlsKerberos.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeTlsKerberosDelegation.java
It's an opt-in featured activated with `--tracing` flag added to either `test run` or `env up` launcher commands.
When environment is started, little message is printed to the console, that makes it easier to navigate to a collector UI:
=> Add OpenTracing support to product tests

pom.xml
Reverts trinodb/trino#20689
Causing a lot of noise in the CI due to the incompatible jgit version with `git-commit-id` plugin.
=> Revert "Update gib to 4.5.2"

core/trino-main/src/main/java/io/trino/execution/executor/dedicated/ConcurrencyController.java, core/trino-main/src/main/java/io/trino/execution/executor/dedicated/TaskEntry.java, core/trino-main/src/main/java/io/trino/execution/executor/dedicated/ThreadPerDriverTaskExecutor.java, core/trino-main/src/test/java/io/trino/execution/TestSqlTaskManagerThreadPerDriver.java, core/trino-main/src/test/java/io/trino/execution/executor/dedicated/TestThreadPerDriverTaskExecutor.java
Concurrency for running leaf tasks is controlled according to the following:
* Each task is guaranteed a minimum number of leaf drivers to be running at a time (controlled by task.min-drivers-per-task)
* Once the minimum is satisfied, additional leaf drivers can get scheduled up to a maximum global target concurrency (controlled by task.min-drivers) Splits get chosen from all available tasks in a round-robin manner.
* A dynamic per-task controller calculates the desired concurrency based on output buffer utilization. We call this "target concurrency". The number of leaf drivers is capped by the lowest of target concurrency and the maximum number of drivers per task (controlled by task.max-drivers-per-task)
```markdown
* …
```
=> Implement global target concurrency for thread-per-driver scheduler

lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GcsAccessTokenProvider.java, lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GcsStorageFactory.java, lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GoogleGcsConfigurationInitializer.java, pom.xml
It partially reverts update to 3.0.0 which seems to be less supported version with some critical CVEs in the shaded jar.
Alternative solutions requires https://github.com/GoogleCloudDataproc/hadoop-connectors/issues/1114
=> Downgrade (update?) gcs-connector to 2.2.19

plugin/trino-kudu/pom.xml, plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestingKuduServer.java
This also works now locally.
This solves following CVE:
But there is one new instead:
=> Update kudu to 1.17.0

core/trino-main/src/main/java/io/trino/execution/SqlTask.java
Commit ensures that for tasks which completed successfuly (task state is set to FINISHED) we construct TaskInfo/TasksStatus with state set to FINISHED only when TaskHolder transtions out of initial state when it is not referencing SqlTaskExecution.
Otherwise it is possible that coordinator would get incomplete information about the task, which is already marked as FINISHED. In such case no longer ask for updates for updates. This may happen for very short lived tasks.
One of the important things which would be missing in such a case is dynamic filter information.
```markdown
* Fix rare condition where queries could have worse performance due to dynamic filters not delivered to consumer. ({issue}`20709`)
```
=> Ensure complete TaskInfo/Status for FINISHED tasks

testing/trino-server-dev/etc/catalog/delta.properties, testing/trino-server-dev/etc/catalog/hudi.properties
[S3FileSystemConfig](https://github.com/trinodb/trino/blob/master/lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemConfig.java) doesn't support `s3.ssl.enabled` property.
=> Remove non-existing config property

docs/src/main/sphinx/admin/properties-exchange.md, docs/src/main/sphinx/admin/properties-http-client.md
- Add exchange prefix
- Add max content length property
This came up to be added in some discussion around `exchange.http-client.max-content-length` 
so I think it makes sense to add it to the list. 
However ... I am not sure if we want to add this property specifically as well. In the prior PR with @Jessie212 I think we decided NOT to add that property, but it seems to be used in the field.
https://github.com/trinodb/trino/pull/12247
=> Update HTTP client config doc

core/trino-main/src/main/java/io/trino/FeaturesConfig.java, core/trino-main/src/test/java/io/trino/sql/analyzer/TestFeaturesConfig.java
Release note: `Deprecate RE2J regex engine`
=> Mark RE2J as deprecated regex engine

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestTrinoGlueCatalog.java
It is a security hole as user can have broader access to glue than to trino and can leverage this to get access to data he should not access
```markdown
* Stop setting materialized view owner in glue catalog . ({issue}`issuenumber`)
```
=> Prevent view owner from being set when system security is used

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/StaticBigQueryCredentialsSupplier.java
Fixes https://github.com/trinodb/trino/issues/20729
https://github.com/trinodb/trino/commit/1f6757293c482f0ac3fa9d17fa1dbcb8b11a3d71 replaced `com.google.api.client.util.Base64.decodeBase64` with `java.util.Base64..getDecoder().decode`, but it led to the failure when decoding some credentials. The original method had a fallback logic to use base64 **_URL_** encoding. 
```markdown
* TBD. ({issue}`20729`)
```
=> Use Guava Base64 decoder for BigQuery credential

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
In case requested partition are not found in Glue API can return empty partitions and empty unprocessed keys.
=> Fix request partitions from Glue logic

pom.xml, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeHiveHudiRedirections.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkHive.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkHiveNoStatsFallback.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIceberg.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergJdbcCatalog.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergRest.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveSparkCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java, testing/trino-product-tests/src/main/resources/tempto-configuration.yaml
Relates to https://github.com/trinodb/docker-images/pull/184
Fixes #17562
=> Update docker-images version to 89

lib/trino-hive-formats/src/main/java/io/trino/hive/formats/ReadWriteUtils.java, lib/trino-hive-formats/src/test/java/io/trino/hive/formats/TestReadWriteUtils.java
Truncation logic for VARCHAR and CHAR can return a value outside the bounds of the input field.
```markdown
* Fix decoding of `VARCHAR` and `CHAR` with lengh in `TEXTFILE` and `SEQUENCEFILE ` formats. ({issue}`issuenumber`)
```
=> Fix character type truncation Hive LazySimpleSerDe

.github/workflows/ci.yml
There are frequent maven-checks failures for 22-ea due to the lack of disk space.
```markdown
```
=> Cleanup node when installing JDK 22-ea

plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveBlockEncodingSerde.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestHiveBlockEncodingSerde.java
Per the class level code comment, `HiveBlockEncodingSerde` is supposed to provide same encodings as the `BlockEncodingManager`.
=> Supplement HiveBlockEncodingSerde

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
The suggested replacement, the `StandardMultinode`, relies on `Standard`, so we cannot remove the class. It also provides number of constants shared across. Having it deprecated triggers many warnings in the code, with no clear intention to have them resolved.
=> Remove deprecation from Standard environment extender

pom.xml
Before:
```
./mvnw help:effective-pom -pl ':trino-mysql' | grep 'url>' | head -n 1
Running `/Users/mateuszgajewski/Projects/src/github.com/trinodb/trino/mvnw`...
<url>https://trino.io/plugin/trino-mysql</url>
```
After:
```
./mvnw help:effective-pom -pl ':trino-mysql' | grep 'url>' | head -n 1
Running `/Users/mateuszgajewski/Projects/src/github.com/trinodb/trino/mvnw`...
<url>https://trino.io</url>
```
According to the `project.url` documentation in the Maven xsd:
```
<xs:documentation source="description">
The URL to the project's homepage.
<br><b>Default value is</b>: parent value [+ path adjustment] + (artifactId or project.directory property), or just parent value if
project's <code>child.project.url.inherit.append.path="false"</code>
</xs:documentation>
```
This invalid url …
=> Do not append groupId/artifactId to the url in children

core/trino-server-rpm/pom.xml, core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java, core/trino-server-rpm/src/test/java/io/trino/server/rpm/TestDummy.java
It has superior configuration abilities and is a little faster (30 vs 45s on average).
https://ctron.github.io/rpm-builder/rpm-mojo.html
https://github.com/ctron/rpm-builder
=> Use RPM builder instead of redlinerpm

.github/actions/setup/action.yml, .github/workflows/ci.yml
* Populate the cache in the Maven Checks job
* Revert to not restoring the cache in product tests job, as it doesn't build anything and restores all required blobs from an artifact
* Only cleanup the node for JDK 22
Follow-up to f133a42e4e1df7c7dc8777edf45df71b3fa0d1b6 (merged manually from #20504)
=> Populate the cache in the Maven Checks job

lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalFileIterator.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
Files.walk method may throw an exception during the iteration. https://bugs.openjdk.org/browse/JDK-8039910
Fixes #20520
=> Suppress NoSuchFileException in LocalFileIterator

docs/src/main/sphinx/object-storage/file-system-azure.md, lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthOAuthConfig.java, lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthOauth.java, lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureAuthOAuthConfig.java
https://trinodb.slack.com/archives/CP1MUNEUX/p1708280746885969
=> Add tenantId to azure oauth2 native fs auth

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
Fixes https://github.com/trinodb/trino/issues/19799
Test was flaky because sometimes cache was invalidated due expiring TTL or not. It is failing continuously when for testing TTL is set to 60s and additional SHOW TABLE is added to fill cache before hive direct calls.
Change schema creation origin to Trino will make sure that cache is updated.
=> Add cache invalidation for testHiveViewsCannotBeAccessed

pom.xml
This updates Delta Lake version to 3.1.0.
=> Update docker-images version to 91

lib/trino-filesystem/src/test/java/io/trino/filesystem/TestLocations.java
Historically these were forbidden. The cases are interesting to test.
=> Test locations with `?` or `#`

plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConnectorFactory.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotModule.java
`MBeanServerModule` is the standard way. They are currently equivalent.
=> Refactor MBean server binding in Pinot

core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Service.java, core/trino-main/src/main/java/io/trino/server/ui/FormWebUiAuthenticationFilter.java, core/trino-main/src/main/java/io/trino/server/ui/LoginResource.java, core/trino-main/src/main/java/io/trino/server/ui/MultipartUiCookie.java, core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiAuthenticationFilter.java, core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiLogoutResource.java, core/trino-main/src/main/java/io/trino/server/ui/OAuthIdTokenCookie.java, core/trino-main/src/main/java/io/trino/server/ui/OAuthWebUiCookie.java, core/trino-main/src/test/java/io/trino/server/ui/TestMultipartUiCookie.java
If cookie value exceeds 4096 bytes (which is a limit for most of the browsers) it will be splitted into multiple cookies and then imploded on read.
Release notes: `Fix UI authentication for large authentication tokens`
=> Support multi-part UI cookies

lib/trino-filesystem-cache-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioCoordinatorFileSystemCache.java, lib/trino-filesystem-cache-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileSystemCacheModule.java, lib/trino-filesystem-cache-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioInputStream.java, lib/trino-filesystem-manager/src/main/java/io/trino/filesystem/manager/FileSystemModule.java, lib/trino-filesystem/src/main/java/io/trino/filesystem/cache/AllowFilesystemCacheOnCoordinator.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/cache/IcebergCacheKeyProvider.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAlluxioCacheFileOperations.java
Enable caching metadata files in iceberg filesystem cache
```markdown
* Improve latency of queries when filesystem caching is enabled. ({issue}`20803`)
```
=> Enable caching metadata files in iceberg filesystem cache

plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/TableInvalidationCallback.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/CachingDirectoryLister.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/TransactionScopeCachingDirectoryLister.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBackgroundHiveSplitLoader.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/FileSystemDirectoryLister.java
These changes address the problem when the new files in manifest are not visible by `directoryLister` immediately because of the caching delay (see #20344). 
The `buildManifestFileIterator()` method now verifies if the referenced file does not appear in the listing. If that is the case it tries to invalidate the cache and reload the listing.
(*) Release notes are required. Please propose a release note for me.
=> Verify the file presense for cached directory lister and retry

plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/conf/AccumuloConfig.java, plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/conf/TestAccumuloConfig.java
=> Add test for AccumuloConfig

testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Exception message changed and currently tests are not retrying with warning:
`WARNING: not retrying; stacktrace does not match pattern 'Hive table .* is corrupt. Found sub-directory in bucket directory for partition': [io.trino.tempto.query.QueryExecutionException: java.sql.SQLException: Query failed (#20240221_201727_00799_jrn62): Found file in sub-directory of ACID directory: hdfs://hadoop-master:9000/user/hive/warehouse/test_read_full_acid_true_none_p7a1xz1629/part_col=2/delete_delta_0000002_0000005/delete_delta_0000002_0000005/bucket_00000`
=> Update pattern for Flaky ACID tests

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/mapping/CachingIdentifierMapping.java
`RemoteIdentifiers.getRemoteTables` & `getRemoteTables` could throw a Trino `JDBC_ERROR`. This PR avoids wrapping them in another `TrinoException` with `GENERIC_INTERNAL_ERROR`.
```markdown
```
=> Handle TrinoException in CachingIdentifierMapping

core/trino-main/src/test/java/io/trino/sql/query/TestFilterHideInacessibleColumnsSession.java, lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java, testing/trino-product-tests-launcher/src/test/java/io/trino/tests/product/launcher/local/TestManuallyJdbcOauth2.java, testing/trino-testing-services/src/test/java/io/trino/testng/services/TestReportAfterMethodNotAlwaysRun.java
Whole test method asserts that every line of it succeeds, so using `assertThatNoException` is redundant. Of course there could be convention to clearly separate test setup and test assertions (given-when-then), but that's not a convention we use, thuse `assertThatNoException()` is redundant.
=> Remove redundant lambdas from test

lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsStorageFactory.java
This enables the use of workload identity federation.
```markdown
```
=> Add application default credentials to GcsStorageFactory

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3OutputFile.java, lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoFileSystem.java, lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoOutputFile.java
Clarify semantics for Trino filesystem.
See discussion on Slack: https://trinodb.slack.com/archives/CP1MUNEUX/p1708958482815419
=> Clarify semantics for Trino filesystem

plugin/trino-bigquery/pom.xml, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryWithProxyTest.java
This reduces the number of CreateWriteStreamRequest to 6 from 42 in the test.
=> Run minimum test for BigQuery proxy

docs/src/main/sphinx/language/sql-support.md
- To globally available statements
- but as separate section to preserve links
Reasoning is that these operations are not traditional write operations to the data source / database as all others, and it also does not depend on what connector is used .. and basically is supported by all connectors.
All connectors docs already link to the globally supported section and this move therefore fixes a docs issue. Alternative would be to add an explicit link to all connectors.. but thats kinda misleading in my opinion.
=> Move dynamic catalog mgt

docs/src/main/sphinx/connector/iceberg.md, docs/src/main/sphinx/sql/create-materialized-view.md
=> Expand MV doc around grace period

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestWriteToHiveTransactionalTableInTrino.java
Allow inserting into a full-ACID Hive table without partitions.
See that issue for a full description.
Fixes #19407.
N/A
```markdown
* Allow Allow inserting into a full-ACID Hive table without partitions. ({issue}`19407`)
```
=> Enable writing to full ACID tables in Hive connector when the table has no partitions

core/trino-spi/pom.xml, core/trino-spi/src/main/java/io/trino/spi/TrinoException.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/CorruptedDeltaLakeTableHandle.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/CorruptedIcebergTableHandle.java
=> Remove unnecessary constructor from TrinoException

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPageSink.java
Build CreateWriteStream lazily for avoiding the rate limit.
Currently, INSERT with single row creates 6 CreateWriteStream and it leads to rate limits.
=> Build CreateWriteStream lazily in BigQuery

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableProperties.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcWithBloomFilters.java
This PR fix table properties for Iceberg table with orc_bloom_filter:
Fix #20432
The correct table properties should be:
`orc.bloom.filter.columns` -> `write.orc.bloom.filter.columns`
`orc.bloom.filter.fpp` -> `write.orc.bloom.filter.fpp`.
Spec: https://iceberg.apache.org/docs/latest/configuration/#write-properties
```markdown
```
=> Fix table props for Iceberg with orc_bloom_filter

docs/src/main/sphinx/security/file-system-access-control.md
Adds a new section to the [File-based access control](https://trino.io/docs/current/security/file-system-access-control.html) documentation page, describing how to configure procedure rules.
#19488 added this feature, but missed updating the corresponding documentation.
Fixes https://github.com/trinodb/trino/issues/19593
=> Add file-based access control documentation for procedure rules

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTable.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePageSink.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestDeltaLakeSchemaSupport.java
The motivation comes from #18013. Currently, DeltaLakeMetadata class calls some `getColumn*(MetadataEntry)` methods from several places. It's a little hard to use those methods correctly.  
It would be better to manage those information in a single place.
=> Simplify DeltaLakeMetadata with new model class

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/RetryingConnectionFactory.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/RetryingConnectionFactoryModule.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestRetryingConnectionFactory.java, plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClientModule.java, plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestingOracleServer.java
Allow to define multiple retry strategies for JDBC connection
Thanks to that now Oracle connector will retry opening a JDBC connection on
any SQLRecoverableException or SQLTransientException. Previously it
retried only on the former.
=> Allow to define multiple retry strategies for JDBC connection

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, core/trino-spi/src/main/java/io/trino/spi/function/table/ConnectorTableFunction.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorTableFunction.java
Revert "Add RetryMode to ConnectorTableFunction.analyze"
=> Revert "Add RetryMode to ConnectorTableFunction.analyze"

core/docker/default/etc/jvm.config, core/trino-server-rpm/src/main/resources/dist/config/jvm.config, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-all/jvm.config, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-ignite/jvm.config, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-master-jvm.config, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-worker-jvm.config, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/jvm.config
This suppresses startup warnings generated by JOL library:
```
WARNING: A Java agent has been loaded dynamically (/tmp/jolAgent15371107136115023174.jar)
WARNING: If a serviceability tool is in use, please run with -XX:+EnableDynamicAgentLoading to hide this warning
WARNING: If a serviceability tool is not in use, please run with -Djdk.instrument.traceUsage for more information
WARNING: Dynamic loading of agents will be disallowed by default in a future release
```
=> Allow loading of dynamic agents

core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java, core/trino-main/src/test/java/io/trino/sql/query/TestCheckConstraint.java
The planner was incorrectly trying to derive the necessary coercions based on the rewritten expression instead of the original one.
```markdown
* Fix query failure when CHECK constraint is null. ({issue}`issuenumber`)
```
=> Fix failure when check constraint is null

core/trino-main/src/main/java/io/trino/operator/scalar/ArraysOverlapFunction.java, core/trino-main/src/main/java/io/trino/operator/scalar/BlockSet.java, core/trino-main/src/test/java/io/trino/operator/scalar/BenchmarkArraysOverlap.java
Use a set instead of sorted arrays for a faster implementation
```
BenchmarkArraysOverlap
(arraySize)           (name)   (type)  Mode  Cnt      Before                  After             Units
10   arrays_overlap   BIGINT  avgt   20    1833.452 ±    39.165   1130.388 ±  112.507  ns/op
10   arrays_overlap  VARCHAR  avgt   20    3507.608 ±   146.911   1476.905 ±  164.377  ns/op
100   arrays_overlap   BIGINT  avgt   20   31971.624 ±   660.772   8473.338 ±  768.726  ns/op
100   arrays_overlap  VARCHAR  avgt   20   66072.713 ±  5309.456  10928.315 ±  336.211  ns/op
1000   arrays_overlap   BIGINT  avgt   20  500618.664 ± 17615.978  79698.191 ± 5276.151  ns/op
1000   arrays_overlap  VARCHAR  avgt   20  908004.836 ± 29334.310  99256.412 ± 1329.540  ns/op
```
Supersedes …
=> Improve performance of arrays_overlap

core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/TranslationMap.java
=> Clean up planning of json expressions

lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsOutputFile.java, lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsOutputStream.java, lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java, lib/trino-filesystem/src/test/java/io/trino/filesystem/local/TestLocalFileSystem.java, lib/trino-hdfs/src/test/java/io/trino/filesystem/hdfs/TestHdfsFileSystemHdfs.java, lib/trino-hdfs/src/test/java/io/trino/filesystem/hdfs/TestHdfsFileSystemLocal.java
=> Use write api

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PreAggregateCaseAggregations.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPreAggregateCaseAggregations.java, core/trino-main/src/test/java/io/trino/sql/query/TestPreAggregateCaseAggregations.java
There can be query failures with `PreAggregateCaseAggregations`.
Repro:
```
create table t (c1 int, c2 varchar);
insert into t values (1, '1');
insert into t values (2, '2');
insert into t values (3, '3');
insert into t values (4, 'd');
select
max(case when c1 = 1 then cast(c2 as int) end) as m1,
max(case when c1 = 2 then c2 end) as m2,
max(case when c1 = 3 then c2 end) as m3,
max(case when c1 = 4 then c2 end) as m4
from t;
Query 20240209_015013_00035_6x8dz failed: Cannot cast 'd' to INT
```
The problem is due to overgeneralized application of the optimization rule. The above example shows a type compatibility issue, but other issues such as division by zero can also happen.
Note: I have not modified the test cases in `TestPreAggregateCaseAggregations` since it has many uses of `CAST`. I …
=> Wrap potentially conditional expressions with IF in PreAggregateCaseAggregations

.github/workflows/ci.yml, lib/trino-filesystem-azure/pom.xml, lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystem.java, lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java, lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemGen2Flat.java, lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemGen2Hierarchical.java, lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemOAuthGen2Flat.java, lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemOAuthGen2Hierarchical.java
The hierarchical namespaces check in the native Azure filesystem is not compatible with authentication via OAuth tokens. The existing check uses the "Get Account Information" blob service account REST API endpoint. As stated in the documentation for this endpoint, it does not support OAuth based access token authentication:
https://learn.microsoft.com/en-us/rest/api/storageservices/get-account-information?tabs=shared-access-signatures#authorization
In order to fix the Azure filesystem OAuth integration we have figured out an alternate method of checking if hierarchical namespaces are enabled for an account using other apis made available in the azure-sdk-for-java. The method used in this PR checks if the root directory exists on the account. If it exists, then HNS is enabled for the …
=> Fix Azure filesystem hierarchical namespaces check

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureOutputFile.java, lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java, lib/trino-filesystem-cache-alluxio/src/test/java/io/trino/filesystem/alluxio/TestAlluxioCacheFileSystem.java, lib/trino-filesystem-cache-alluxio/src/test/java/io/trino/filesystem/alluxio/TestAlluxioCacheFileSystemAccessOperations.java, lib/trino-filesystem-gcs/pom.xml, lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsOutputFile.java, lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemGcs.java, lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3OutputFile.java, lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/AbstractTestS3FileSystem.java, lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoOutputFile.java, lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalOutputFile.java, lib/trino-filesystem/src/main/java/io/trino/filesystem/memory/MemoryOutputFile.java, lib/trino-filesystem/src/main/java/io/trino/filesystem/tracing/TracingOutputFile.java, lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java, lib/trino-filesystem/src/test/java/io/trino/filesystem/cache/TestCacheFileSystemAccessOperations.java, lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsOutputFile.java, lib/trino-hive-formats/src/test/java/io/trino/hive/formats/avro/TestAvroBase.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/MetaDirStatisticsAccess.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriterManager.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/GcsTransactionLogSynchronizer.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/FileTestingTransactionLogSynchronizer.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeGcsConnectorSmokeTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeLocalConcurrentWritesTest.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/AcidTables.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/fileio/ForwardingOutputFile.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergFileOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java
=> Change createOrOverwrite to accept file content

core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroup.java, docs/src/main/sphinx/admin/resource-groups.md, plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupConfigurationManager.java, plugin/trino-resource-group-managers/src/test/resources/resource_groups_config.json
(x) Release notes are required, with the following suggested text: "Expose resource groups metrics by default"
=> Enable JMX metrics for resource groups by default

core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java, core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java, core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java, core/trino-main/src/test/java/io/trino/sql/planner/TestMaterializedViews.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
Temporal predicates in some MVs work differently before and after refresh. This is because for some connectors, the storage table uses a varchar instead of the original temporal type. Before a refresh, we use the original `RelationType`, but after we use the storage table's `RelationType`.
This ensures we correct the `ResolvedField`'s type according to the registered `relationCoercion`, which was previously unused by the `ExpressionAnalyzer`.
This issue was raised as a starburst jira ticket.
```markdown
```
=> Fix temporal predicates in MVs

docs/src/main/sphinx/installation/deployment.md
see title
#20891
@colebow I think we should probably add some sort of note to the release notes that the recommended JVM config changed.. lets chat about that with @martint 
```markdown
```
=> Update JVM config for JOL agent support

plugin/trino-hive/pom.xml, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/HttpThriftMetastoreClientFactory.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftHttpMetastoreClient.java, pom.xml
Support OpenTelemetry in HTTP client for Thrift metastore
Apache HttpClient 5 instrumentation was added in https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/tag/v2.1.0
=> Support OpenTelemetry in HTTP client for Thrift metastore

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3NativeTransactionLogSynchronizer.java
Follow-up work for e1784943 to ensure that transaction log files are written atomically on S3 for Delta Lake in order to avoid to end up on the storage half-baked (leading to table corruption).
https://github.com/trinodb/trino/pull/20913
=> Use createOrOverwrite to create transaction log files on s3

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveFaultTolerantExecutionConnectorTest.java, testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/iceberg/TestIcebergParquetFaultTolerantExecutionConnectorTest.java, testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
Allow JUnit to execute test classes extending from `BaseConnectorTest` in parallel. This is especially useful when running tests locally. On M1-based MacBook they may complete about 8x faster.  Before migration to JUnit, i.e. when using TestNG, there was no single-threaded execution assumption, so this change should not cause regressions. If any subclasses started to rely on isolated executions, those concrete subclasses should be annotated.
=> Allow parallel test execution in BCT

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ColumnIdentity.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergColumnHandle.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplit.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTypes.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesFunctionProcessor.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergNodeLocalDynamicSplitPruning.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
Allows pruning splits on workers using late arriving dynamic filters without opening file format footers
Also helps in avoiding unnecessary predicate pushdown into ORC/parquet
Matches delta lake connector approach of including `statisticsPredicate` in DeltaLakeSplit
```markdown
```
=> Include file statistics domain in IcebergSplit

plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/AcidTables.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestAcidTables.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestHiveAcidUtils.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
Fixes: https://github.com/trinodb/trino/issues/16315
Related: https://github.com/trinodb/trino/issues/8920
Multiple Hive minor compaction creates duplicated directoires like:
```
./delta_0000001_0000001/bucket_00000
./delta_0000001_0000001/delta_0000001_0000001
./delta_0000001_0000001/delta_0000001_0000001/bucket_00000
```
Hive is able to read such table without problem, ignoring nested delta directories. This change follows Hive behaviour.
```markdown
```
=> Ignore nested delta directories for Hive ACID

plugin/trino-opa/pom.xml, plugin/trino-opa/src/main/java/io/trino/plugin/opa/OpaAccessControl.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/OpaAccessControlFactory.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/OpaConfig.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/OpaHighLevelClient.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/schema/OpaBatchQueryResult.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/schema/OpaColumnMaskQueryResult.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/schema/OpaQueryInputAction.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/schema/OpaQueryInputResource.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/schema/OpaRowFiltersQueryResult.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/schema/OpaViewExpression.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/schema/TrinoCatalogSessionProperty.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/schema/TrinoColumn.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/schema/TrinoFunction.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/schema/TrinoGrantPrincipal.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/schema/TrinoIdentity.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/schema/TrinoSchema.java, plugin/trino-opa/src/main/java/io/trino/plugin/opa/schema/TrinoTable.java, plugin/trino-opa/src/test/java/io/trino/plugin/opa/DistributedQueryRunnerHelper.java, plugin/trino-opa/src/test/java/io/trino/plugin/opa/OpaContainer.java, plugin/trino-opa/src/test/java/io/trino/plugin/opa/QueryRunnerHelper.java, plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestConstants.java, plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestHelpers.java, plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaAccessControl.java, plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaAccessControlDataFilteringSystem.java, plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaAccessControlFiltering.java, plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaAccessControlSystem.java, plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaBatchAccessControlFiltering.java, plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaConfig.java, plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaResponseDecoding.java
Add row level filtering and column masking to the OPA System access control plugin
This was originally discussed as a side-effort of #19532 , and a first cut was added to our fork in bloomberg/trino#16
@mosabua should I create a separate PR for docs for this?
```markdown
* Added support for row filtering and column masking in the OPA access control
```
=> OPA: Implement row level filtering and column masking

core/trino-main/src/main/java/io/trino/server/DynamicFilterService.java, testing/trino-testing/src/main/java/io/trino/testing/BaseDynamicPartitionPruningTest.java
Trino will throw Exceptions "Multiple entries with same key", when the same dynamic filter applies to the same partitions key column multiple times under different conditions. E.g.
```
SELECT *
FROM tbl_a a
JOIN tbl_b b ON b.partition_key_date >= a.start_date AND b.partition_key_date <= a.start_date
```
```markdown
* Fix query failures with "Multiple entries with same key" error encountered with joins on partitioned tables. ({issue}`20917`)
```
=> Fix 'Multiple entries with same key' error with dynamic filters

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
Specify schema name in testNativeQuerySelectUnsupportedType to avoid slow tests in SaaS connectors.
=> Specify schema name in testNativeQuerySelectUnsupportedType

pom.xml
New version requires maven 3.9.5 which makes it incompatible with the latest mvnd version
```markdown
```
=> Downgrade modernizer to 2.7.0

core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushDistinctLimitIntoTableScan.java
Explicitly mark test as single threaded, having mutable state, instead of less typical resource lock annotation.
=> Mark test single-threaded

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeHistoryTable.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePropertiesTable.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/DeltaLakeMetastore.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/RegisterTableProcedure.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/UnregisterTableProcedure.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/FileBasedTableStatisticsProvider.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriterManager.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestingDeltaLakeUtils.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/statistics/TestDeltaLakeFileBasedTableStatisticsProvider.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTableSnapshot.java
Minor refactoring in Delta Lake connector
=> Minor refactoring in Delta Lake connector

lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java, lib/trino-parquet/src/test/java/io/trino/parquet/TestTupleDomainParquetPredicate.java, testing/trino-server-dev/etc/config.properties
Fixes query failure when reading parquet statistics for a short decimal
in parquet file that is read as a long decimal in Trino
```markdown
* Fix query failure due to "Corrupted statistics" when reading parquet files with a predicate on a long decimal column. ({issue}`20981`)
```
=> Fix reading parquet statistics for long decimals

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java, plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java, plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClientModule.java, plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
Support query table function in Snowflake
=> Support query table function and cleanup tests in Snowflake

plugin/trino-pinot/pom.xml, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/auth/password/PinotPasswordAuthenticationProvider.java, plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java
Remove okhttp from Pinot connector
=> Remove okhttp from Pinot connector

docs/src/main/sphinx/connector/hive-security.md, docs/src/main/sphinx/object-storage/metastores.md
As discussed with @electrum .. we should probably start a hdfs page and then move the hdfs auth there and then see where the remaining security stuff should be.
Related to a bunch of other moving docs around for object storage.
=> Move Thrift metastore authentication docs

docs/release-template.md, docs/src/main/sphinx/release.md, docs/src/main/sphinx/release/release-440.md
Assemble the release notes for the upcoming Trino 440 release.
* #20454 ✅ rn ✅ docs
* #20705 ✅ rn ✅ docs
* #20690 ✅ rn ✅ docs
* #18506 ✅ rn ✅ docs
* #20730 ✅ rn ✅ docs
* #20638 ✅ rn ✅ docs
* #20486 ✅ rn ✅ docs
* #20647 ✅ rn ✅ docs
* #20719 ✅ rn ✅ docs
* #20732 ✅ rn ✅ docs
* #20722 ✅ rn ✅ docs
* #19564 ✅ rn ✅ docs
* #20731 ✅ rn ✅ docs
* #20264 ✅ rn ✅ docs
* #20737 ✅ rn ✅ docs
* #19816 ✅ rn ✅ docs
* #20723 ✅ rn ✅ docs
* #20743 ✅ rn ✅ docs
* #20744 ✅ rn ✅ docs
* …
=> Add Trino 440 release notes

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthDefault.java, lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthDefaultModule.java, lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemConfig.java, lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemConfig.java
=> Use DefaultAzureCredential by default for Azure file system

plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPartitionManager.java, plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPartitionResult.java, plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
Clustering key constraints are ignored when there are secondary key and clustering key defined and not all the secondary keys are part of the `WHERE` clause.
Diagnosis - `clusteringKeyPredicates` is not considered when splits are created based on the token range.
https://github.com/trinodb/trino/blob/3d3a0f0a9ce1cef3acab4a3355f12be715324c78/plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSplitManager.java#L93-L102
https://github.com/trinodb/trino/blob/3d3a0f0a9ce1cef3acab4a3355f12be715324c78/plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSplitManager.java#L110-L118
Proposed fix - Keep `clusteringKeyPredicates` empty and the cluster key constraint will remain part of `unenforcedConstraint` …
=> Fix incorrect result when filtering clustering key in Cassandra

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsWriter.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergStatistics.java
Fixes https://github.com/trinodb/trino/issues/19992
=> Rewrite statistics during OPTIMIZE in Iceberg

.github/actions/setup/action.yml, .github/workflows/ci.yml
The CI cache setup is designed so that only one chosen job populates the
cache (currently the maven-checks). Adjust the default to convey the
intent.
=> Adjust default caching behavior in CI's setup 

plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/table/HudiTableFileSystemView.java
- [HUDI] Disable file creation when Partition does not exist (Fix issue 20133)
- https://github.com/trinodb/trino/issues/20133
```markdown
* Fix HUDI connector create files when partitions does not exist. ({issue}`20133`)
```
=> Disable file creation when Partition does not exist #20133

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogParser.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTransactionLogParser.java
Use the version of the table handle, instead of the version from _last_checkpoint file for finding out which is effectively the latest version of the table.
Fixes https://github.com/trinodb/trino/issues/16782
```markdown
```
=> Delta Lake: Read mandatory current version starting from table's read version

docs/src/main/sphinx/object-storage/legacy-azure.md
Azure Gen 1 and WASB are no longer supported by Microsoft .. and hence also not by Trino. As requested by @electrum and @dain 
=> Remove docs for unsupported Azure storage

testing/trino-product-tests-launcher/pom.xml, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeConfluentKafka.java, testing/trino-testing-services/src/main/java/io/trino/testing/TestingProperties.java, testing/trino-testing-services/src/main/resources/trino-testing.properties
Product Tests Launcher uses mounts various jars (JDBC drivers,
libraries) in the docker container it starts. These files are loaded at
runtime from Launcher's `target/` directory. Remove these jars from
Launcher classpath. This shrinks the launcher executable jar from 155 MB
to 63 MB.
=> Exclude unused dependencies from Launcher

pom.xml
Update to Alluxio 311, mostly to fix a CVE - Details in https://github.com/Alluxio/alluxio/commit/81bc9ddac0e24d7dc9f9397aa862b4e0b4c47168
https://github.com/Alluxio/alluxio/pull/18536
I am not sure to be honest - it should not change behavior and just remove the CVE report. Since there was no exploit however we probably dont need to add to release notes.. 
```markdown
```
=> Update to Alluxio 311

core/trino-main/src/main/java/io/trino/operator/aggregation/AccumulatorCompiler.java, core/trino-main/src/main/java/io/trino/operator/aggregation/AverageAggregations.java, core/trino-main/src/main/java/io/trino/operator/aggregation/CountAggregation.java, core/trino-main/src/main/java/io/trino/operator/aggregation/CountColumn.java, core/trino-main/src/main/java/io/trino/operator/aggregation/CountIfAggregation.java, core/trino-main/src/main/java/io/trino/operator/aggregation/DoubleSumAggregation.java, core/trino-main/src/main/java/io/trino/operator/aggregation/LongSumAggregation.java, core/trino-main/src/main/java/io/trino/operator/aggregation/RealAverageAggregation.java, core/trino-main/src/main/java/io/trino/operator/aggregation/WindowAccumulator.java, core/trino-main/src/main/java/io/trino/operator/window/AggregateWindowFunction.java, core/trino-main/src/test/java/io/trino/operator/TestRealAverageAggregation.java, core/trino-main/src/test/java/io/trino/operator/aggregation/AbstractTestAggregationFunction.java, core/trino-main/src/test/java/io/trino/operator/aggregation/TestDoubleAverageAggregation.java, core/trino-main/src/test/java/io/trino/operator/aggregation/TestDoubleSumAggregation.java, core/trino-main/src/test/java/io/trino/operator/window/AbstractTestWindowFunction.java, core/trino-main/src/test/java/io/trino/operator/window/TestAggregateWindowFunction.java, core/trino-main/src/test/java/io/trino/operator/window/WindowAssertions.java
If the input data to an aggregation window function contains Nan or infinite, the result for that window frame will be Nan/Infinite, which is expected. However, after that, the result of the window continues to be Nan/Infinite even if the input data in the window does not contain any invalid values. For the steps on reproduction, please refer to https://github.com/trinodb/trino/issues/20946.
```markdown
* Fix incorrect window aggregation results over double values in the presence of NaN or Infinite inputs ({issue}`20946`)
```
=> Handle NaN and infinite values in Aggregation Window Function

plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java, plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java, plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/OpenSearchClient.java, plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/BaseOpenSearchConnectorTest.java
Fixes https://github.com/trinodb/trino/issues/21020
```markdown
* Fix failure when listing tables having invalid fields on indexes. ({issue}`issuenumber`)
```
=> Fix failure when listing tables in Elasticsearch and OpenSearch

docs/src/main/sphinx/release.md, docs/src/main/sphinx/release/release-441.md
Assemble the release notes for the upcoming Trino 441 release.
* #20970 ✅ rn ✅ docs
* #20986 ✅ rn ✅ docs
* #20997 ✅ rn ✅ docs
* #20998 ✅ rn ✅ docs
* #20996 ✅ rn ✅ docs
* #20963 ✅ rn ✅ docs
* #20990 ✅ rn ✅ docs
* #21001 ✅ rn ✅ docs
* #20885 ✅ rn ✅ docs
* #21006 ✅ rn ✅ docs
* #20151 ✅ rn ✅ docs
* #21008 ✅ rn ✅ docs
* #21015 ✅ rn ✅ docs
* #21011 ✅ rn ✅ docs
* #21004 ✅ rn ✅ docs
* #21022 ✅ rn ✅ docs
* #21023 ✅ rn ✅ docs
* #21018 ✅ rn ✅ docs
* #21025 ✅ rn ✅ docs
* …
=> Add Trino 441 release notes

docs/src/main/sphinx/connector/opensearch.md, plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/AwsSecurityConfig.java, plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/AwsRequestSigner.java, plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/OpenSearchClient.java, plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/TestAwsSecurityConfig.java
AWS4Signer takes [different service name based on the deployment type](https://repost.aws/questions/QU5Uh7PmQERR6ysMQgrHv9AA/is-opensearch-serverless-meant-to-authenticate-like-opensearch-service)([Opensearch serverless](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/serverless.html) vs [Opensearch provisioned](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/what-is.html)). Make Opensearch deployment type configurable to populate correct service name while using AWS auth.
```markdown
Make opensearch deployment type configurable …
```
=> Make Opensearch deployment type configurable

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/TrinoParquetDataSource.java, plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSourceProvider.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
Fixes https://github.com/trinodb/trino/issues/16775
=> Reduce redundant TrinoInputFile.length call in Delta Lake

plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
If the test run slower than usual, it would fail.
=> Fix $file_modified_time time-based synchronization

plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiConnectorFactory.java
Having installation of parametrization module withing binder -> { ... } lambda does not work correctly if module passed as parameter is ConfigurationAwareModule.
=> Move installation of module parameter to top level

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/fileio/ForwardingFileIo.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/fileio/TestForwardingFileIo.java
During one of Iceberg update PRs a regression was introduced because `ForwardingFileIo` did not implement some optional method of the `FileIO` interface, resulting with suboptimal performance. Require that all methods are implemented and use default interface methods consciously.
=> Require all methods implemented for ForwardingFileIo

plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java
Workaround product problem which leads to test flakiness. Having unfixed product problem is bad, but having unfixed product problem *and* flaky tests isn't better.
Relates to https://github.com/trinodb/trino/issues/10846
Fixes https://github.com/trinodb/trino/issues/16286
Fixes https://github.com/trinodb/trino/issues/8556
=> Isolate testSelectInformationSchemaColumns for SQL Server

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
getNextBatch will return when enough splits are generated, therefore fileStatisticsDomain needs to be preserved across getNextBatch calls.
Caused by https://github.com/trinodb/trino/pull/20918 (since version 440).
```markdown
* Fix NPE errors when enumerating splits. ({issue}`issuenumber`)
```
=> Preseve fileStatisticsDomain across getNextBatch calls

core/trino-main/src/test/java/io/trino/operator/window/WindowAssertions.java
Cleanup test code in `WindowAssertions` to use text blocks instead of concatenation for multiline SQL strings.
=> Use text blocks in WindowAssertions

docs/src/main/sphinx/connector/system.md
This PR removes the owner column from the materialized view system table to reflect work completed in #9961. 
```markdown
```
=> Remove owner from materialized views metadata table in documentation

lib/trino-filesystem/src/main/java/io/trino/filesystem/tracing/TracingInputFile.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/TrinoParquetDataSource.java, plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSourceProvider.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
TrinoInputFile implementations already cache length, updated TracingInputFile to reflect that and fixed the usage of `length` introduced by https://github.com/trinodb/trino/pull/21070
```markdown
```
=> Fix usage of split length instead of file length in parquet

plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java
Same as https://github.com/trinodb/trino/pull/21054
This test also failed in https://github.com/trinodb/trino/actions/runs/8288404987/job/22682892265?pr=21091
=> Isolate testSelectInformationSchemaTables for SQL Server

plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
This test failed in https://github.com/trinodb/trino/actions/runs/8286235466/job/22675808796
testAddAndDropColumnName also failed in the above job, but I assume isolating testSelectInformationSchemaColumns is sufficient.
=> Isolate testSelectInformationSchemaColumns for Ignite

pom.xml
Relates to:
* https://github.com/trinodb/docker-images/pull/190
=> Update docker-images version to 92

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeResult.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeScannedDataFile.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitSource.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/RemoveFileEntry.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointSchemaManager.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointBuilder.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointEntryIterator.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointWriter.java
This information can be particularly useful in the context of concurrent writes operations to identify overlaps between  the partitions being read by the current operation and the partitions updated by an already committed operation.
#18506 
https://github.com/delta-io/delta/blob/master/PROTOCOL.md#add-file-and-remove-file
```markdown
```
=> Delta Lake: Add `partitionValues` information to the `remove` transaction log entries

testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
On CI we observe that sometimes tests create much higher than expected number of query runner instances and then often fail (too many resources taken or too many tests running in parallel). Logging this number helps attribute CI failure to this cause.
For https://github.com/trinodb/trino/issues/21053
=> Log number of live query runner instances

core/trino-main/src/main/java/io/trino/operator/aggregation/state/LongDecimalWithOverflowAndLongStateSerializer.java, core/trino-main/src/main/java/io/trino/operator/aggregation/state/LongDecimalWithOverflowStateSerializer.java, core/trino-main/src/test/java/io/trino/operator/aggregation/state/TestLongDecimalWithOverflowAndLongStateSerializer.java, core/trino-main/src/test/java/io/trino/operator/aggregation/state/TestLongDecimalWithOverflowStateSerializer.java, core/trino-main/src/test/java/io/trino/sql/query/TestAggregation.java
Fixes https://github.com/trinodb/trino/issues/21099
=> Fix long decimal partial aggregation below join

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergRegisterTableProcedure.java
Register procedure should accept locations which differ with trailing slash
Fixes https://github.com/trinodb/trino/issues/19143
=> Unify Iceberg registration behaviour for table location

lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsOutputFile.java, lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsOutputStream.java, lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java
Defer the file existence check to GCS API when the blob gets actually created.
```markdown
```
=> Drop explicit check for file existence while creating GCS blobs

plugin/trino-iceberg/pom.xml, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieCatalogModule.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieTableOperations.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/fileio/ForwardingFileIo.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestTrinoNessieCatalog.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergTrinoRestCatalogConnectorSmokeTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java, plugin/trino-iceberg/src/test/java/org/apache/iceberg/jdbc/TestingTrinoIcebergJdbcUtil.java, pom.xml, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java
- Bump Iceberg to 1.5.0 and Nessie to 0.77.1
- Remove deprecated class usage
- update ForwardingFileIo to handle https://github.com/apache/iceberg/pull/9592
https://iceberg.apache.org/releases/#150-release
=> Bump Iceberg and Nessie versions

core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalSumAggregation.java, core/trino-main/src/main/java/io/trino/operator/scalar/DataSizeFunctions.java, core/trino-main/src/test/java/io/trino/operator/aggregation/TestDecimalSumAggregation.java, core/trino-spi/src/main/java/io/trino/spi/type/Decimals.java
Throwing a TrinoException instead of ArithmeticException on sum aggregation of decimals
Closes #20227 
( x ) This is not user-visible or is docs only, and no release notes are required.
```markdown
```
=> Throwing a TrinoException instead of ArithmeticException on sum aggregation of decimals

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
This is to prevent listing tables failures when tables dropped concurrently. This also fixes IDE warning about synchronization not matching `@GuardedBy` annotations.
Fixes https://github.com/trinodb/trino/issues/21121
=> Synchronize listing tables in file metastore

core/trino-main/src/main/java/io/trino/operator/FlatHashStrategyCompiler.java, core/trino-main/src/test/java/io/trino/operator/TestFlatHashStrategy.java, core/trino-main/src/test/java/io/trino/operator/TestFlatHashStrategyCompiler.java
=> Support FlatHashStrategy with 100_000+ columns

testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-delta-lake-databricks/delta.properties, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-delta-lake-databricks/hive.properties
Comment become separate from the line it is about when `fs.hadoop.enabled=true` was added.
=> Fix comment location

core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java, core/trino-main/src/main/java/io/trino/server/ServerMainModule.java, core/trino-main/src/main/java/io/trino/transaction/InMemoryTransactionManagerModule.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/ClosingBinder.java, lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/TestClosingBinder.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcModule.java, plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreModule.java, plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentModule.java, plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClientModule.java
Introduce ClosingBinder
It is easy to make a mistake when closing a resource on a
method in the guice module annotated with @PreDestroy. Such method won't
be called and resource may leak. This does not affect
production, but it may leak resources during the test.
ClosingBinder is created in order to help mitigate this problem by introducing
simple utility to close resources in guice modules.
=> Introduce ClosingBinder

lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/text/TestTextLineReaderFactory.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestTextfileSymlinkInputFormat.java
This basically adds a regression test for
https://github.com/trinodb/trino/issues/21072.
Note that while the test is explicitly testing only against textfile tables same can be done against any other LinePageSourceFactory based input formats (CSV, JSON, Regex, Sequence-file and Textfile for example).
=> Add test for symlink tables using line-based input formats

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedView.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogMaterializedView.java
Fixes: https://github.com/trinodb/trino/issues/20837
As well as some other edge cases which can happen if a `CREATE MATERIALIZED VIEW` operation fails.
```markdown
* Fix dropping materialized views which were created before 433 when using a Hive catalog.
* Improve storage table cleanup when creating a materialized view fails.
```
=> Fix Iceberg materialized view storage table cleanup

core/trino-main/src/main/java/io/trino/type/DoubleOperators.java, core/trino-main/src/main/java/io/trino/type/RealOperators.java
Before this change, when casting real or double to varchar, we used DecimalFormat without specified Locale. It defaulted to user's locale, causing inconsistent formatting and test failures. For example, with locale `AU`, the `E` in scientific notation is lowercase.
```markdown
* Ensure consistent formatting when casting from double or real to varchar. ({issue}`issuenumber`)
```
=> Specify Locale for DecimalFormat

plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
=> Disable testSelectInformationSchemaColumns in Snowflake

client/trino-jdbc/pom.xml, lib/trino-cache/src/test/java/io/trino/cache/MoreFutures.java, pom.xml, testing/trino-product-tests/pom.xml
Fixes Jackson long string serialization issue (thx @losipiuk) and makes maven project infrastructure compatible with JDK 22/23.
The changes around Throwables are the result of the deprecations in Guava.
=> Update airlift to 243 and airbase to 153

plugin/trino-iceberg/pom.xml, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java
According to the nessie changelog (https://github.com/projectnessie/nessie/releases/tag/nessie-0.79.0) this version is built against Iceberg 1.5.0:
```
New Features
Iceberg bumped to 1.5.0
```
=> Update nessie to 0.79.0

plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/SyncPartitionMetadataProcedure.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHive3OnDataLake.java
Change the order of the operations in `sync_partition_metadata` operation. This change allows ALTER handling in `SemiTransactionalMetastore` when syncing a partition path case change.
e.g. `part=val` gets changed to `PART=val`
Note in the example above that the partition name and not the value has changed in case.
Relevant code snippet in reviewing this PR for highlighting that the order of operations (`DROP` first and `ADD` second) in `sync_partition_metadata`) is effective:
https://github.com/trinodb/trino/blob/06d208dea861229494ec6e793b9bce19d6ef97f3/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java#L887-L889
( ) Release notes are required. Please propose a …
=> Hive `sync_partition_metadata`: Alter partition when the synced path differs only in case

plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
Add `executeExclusively` for tests that had `@Flaky` annotation until https://github.com/trinodb/trino/commit/ff3704ce2742ea1d0cc0b476dada2d96dea896d7
Example failure: https://github.com/trinodb/trino/actions/runs/8319332902/job/22762502927
=> Isolate column operation tests in Ignite

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystem.java, lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/AbstractTestS3FileSystem.java, lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java
AWS S3 allows creating "folder" blobs with the media type "application/x-directory". These blobs should be deleted as well along with the normal blobs when deleting the contents of a directory in order to ensure that the directory corresponding to a table is actually fully deleted.
Use solution inspired from https://github.com/trinodb/trino/pull/13974
Fixes https://github.com/trinodb/trino/issues/21111
```markdown
* Delete also blobs ending in slash when deleting directory contents. ({issue}`issuenumber`)
```
=> Delete also blobs ending in slash when deleting directory contents

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
Fixes https://github.com/trinodb/trino/issues/19336
For trino type `TimestampType` automatic coercion to `TIMESTAMP_MICROS`.
Related to https://github.com/trinodb/trino/pull/13981
```markdown
```
=> Support automatic type coercion in Delta table creation

.github/workflows/ci.yml, core/trino-server-rpm/pom.xml, core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/jdk/Temurin22JdkProvider.java
Just a preparation for JDK 22.
=> JDK 22 preparations 

docs/src/main/sphinx/connector/prometheus.md, plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusClient.java, plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusConnectorConfig.java, plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusConnectorConfig.java
Allowing users to use a custom header for authorization of prometheus endpoint
Current code only support Authorization http header, just adding a new configuration property to allow a custom header name
```markdown
* Add support for a custom authorization header name.({issue}`21187`)
```
=> Allow a custom header name for authorization in Prometheus

docs/src/main/sphinx/release.md, docs/src/main/sphinx/release/release-443.md
Assemble the release notes for the upcoming Trino 443 release.
* #21077 ✅ rn ✅ docs
* #21094 ✅ rn ✅ docs
* #21095 ✅ rn ✅ docs
* #21090 ✅ rn ✅ docs
* #21091 ✅ rn ✅ docs
* #20492 ✅ rn ✅ docs
* #21097 ✅ rn ✅ docs
* #21084 ✅ rn ✅ docs
* #21044 ✅ rn ✅ docs
* #21083 ✅ rn ✅ docs
* #21096 ✅ rn ✅ docs
* #21076 ✅ rn ✅ docs 
* #21114 ✅ rn ✅ docs
* #20489 ✅ rn ✅ docs
* #21103 ✅ rn ✅ docs
* #21108 ✅ rn ✅ docs
* #21113 ✅ rn ✅ docs
* #21110 ✅ rn ✅ docs
* #21115 ✅ rn ✅ …
=> Add Trino 443 release notes

core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaMetadata.java, core/trino-main/src/main/java/io/trino/connector/system/SystemTablesMetadata.java, core/trino-main/src/main/java/io/trino/cost/CachingCostProvider.java, core/trino-main/src/main/java/io/trino/cost/CachingStatsProvider.java, core/trino-main/src/main/java/io/trino/cost/ComposableStatsCalculator.java, core/trino-main/src/main/java/io/trino/cost/FilterProjectAggregationStatsRule.java, core/trino-main/src/main/java/io/trino/cost/PlanNodeStatsEstimate.java, core/trino-main/src/main/java/io/trino/cost/RemoteSourceStatsRule.java, core/trino-main/src/main/java/io/trino/cost/ScalarStatsCalculator.java, core/trino-main/src/main/java/io/trino/cost/SimpleFilterProjectSemiJoinStatsRule.java, core/trino-main/src/main/java/io/trino/cost/StatsNormalizer.java, core/trino-main/src/main/java/io/trino/execution/StateMachine.java, core/trino-main/src/main/java/io/trino/json/PathEvaluationUtil.java, core/trino-main/src/main/java/io/trino/json/PathEvaluationVisitor.java, core/trino-main/src/main/java/io/trino/json/PathPredicateEvaluationVisitor.java, core/trino-main/src/main/java/io/trino/json/ir/SqlJsonLiteralConverter.java, core/trino-main/src/main/java/io/trino/metadata/Catalog.java, core/trino-main/src/main/java/io/trino/metadata/SessionPropertyManager.java, core/trino-main/src/main/java/io/trino/operator/Driver.java, core/trino-main/src/main/java/io/trino/sql/gen/InCodeGenerator.java, core/trino-main/src/main/java/io/trino/sql/gen/JoinCompiler.java, core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java, core/trino-main/src/main/java/io/trino/sql/planner/EffectivePredicateExtractor.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DereferencePushdown.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/InlineProjections.java
=> Use enhanced instanceof

core/trino-main/src/main/java/io/trino/sql/ir/ExpressionFormatter.java
Otherwise invalid SQL is produced when formatting
```markdown
```
=> Wrap IR IN value list in brackets

plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/ImplementAvgBigint.java, plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java, plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
```markdown
* Add support for `avg` aggregation pushdown on `bigint` type. 
```
=> Add support for `avg` aggregation pushdown on `bigint` type in Snowflake

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeHistoryTable.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePropertiesTable.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesSplitSource.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/CommitInfoEntry.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeDataFileCacheEntry.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/MetadataEntry.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/ProtocolEntry.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/RemoveFileEntry.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TableSnapshot.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionEntry.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointBuilder.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntries.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/LastCheckpoint.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TransactionLogTail.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/TransactionLogWriter.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestReadJsonTransactionLog.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointWriter.java
=> Delta Lake checkpoint cleanups

plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
The test could fail if it is run in parallel with any other test that creates schemas, e.g. `testRenameTableToUnqualifiedPreservesSchema`.
=> Fix memory connector testCreateTableInNonDefaultSchema

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ReusableConnectionFactory.java
Such exceptions are suppressed. Failure to close a connection is a problem (resource leak), so log such exceptions.
=> Do not throw from cache removal listener

plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/RaptorQueryRunner.java, plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/TestRaptorMySqlConnectorTest.java
There is a race condition between shard cleaner and query runner cleanup when baseDir is used
Fixes https://github.com/trinodb/trino/issues/12385
```markdown
```
=> Use separate directory for raptor data

core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java, core/trino-main/src/main/java/io/trino/sql/planner/GroupingOperationRewriter.java, core/trino-main/src/main/java/io/trino/sql/planner/TranslationMap.java, core/trino-main/src/main/java/io/trino/type/LikeFunctions.java, core/trino-main/src/test/java/io/trino/sql/planner/TestConnectorExpressionTranslator.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
=> Fix planning of subscript and like

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcWriteConfig.java
=> Fix jdbc write config variable typo

testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeInsertCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DatabricksVersion.java
Follow-up of https://github.com/trinodb/trino/pull/20420. 
Running the test with OSS Delta Lake seems sufficient. 
=> Run testTimestampInsertCompatibility only in OSS Delta

docs/src/main/sphinx/connector/iceberg.md, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/BaseSystemTable.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/MetadataLogEntriesTable.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/SnapshotsTable.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableType.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogAccessOperations.java
Add metadata_log_entries table to Iceberg
```
SELECT * FROM "test_table$metadata_log_entries"
timestamp                 |                                                              file                                                          | latest_snapshot_id  | latest_schema_id | latest_sequence_number
---------------------------------------+----------------------------------------------------------------------------------------------------------------------------+---------------------+------------------+------------------------
2024-01-16 15:55:31.172 Europe/Vienna | hdfs://hadoop-master:9000/user/hive/warehouse/test_table/metadata/00000-39174715-be2a-48fa-9949-35413b8b736e.metadata.json | 1221802298419195590 |                0 |                      1
2024-01-16 17:19:56.118 …
```
=> Add metadata_log_entries table to Iceberg

plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java, plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
```markdown
* Add support for top-N pushdown. ({issue}`21219`)
```
=> Support topN for Snowflake connector

core/docker/default/etc/jvm.config, core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java, core/trino-server-rpm/src/main/resources/dist/config/jvm.config, docs/src/main/sphinx/installation/deployment.md, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-all/jvm.config, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/jvm.config
Trino server behavior does generally not depend on locale settings.  Use
en_US as this is what Trino is tested with.
=> Run server with en_US locale

core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java, core/trino-main/src/main/java/io/trino/sql/planner/SymbolAllocator.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ExtractSpatialJoins.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/MultipleDistinctAggregationToMarkDistinct.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PreAggregateCaseAggregations.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownProjectionsFromPatternRecognition.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushInequalityFilterExpressionBelowJoinRuleSet.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionThroughExchange.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionThroughUnion.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/HashGenerationOptimizer.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/OptimizeMixedDistinctAggregations.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java, core/trino-main/src/main/java/io/trino/sql/planner/plan/Assignments.java, core/trino-main/src/test/java/io/trino/sql/planner/TestTypeValidator.java, core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java, plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/aggregation/ImplementCountDistinct.java
=> Normalize symbol names

docs/src/main/sphinx/connector/snowflake.md
Currently I just copied the section from PostgreSQL connector to start a discussion what is actually implemented. Only one I know of is avg for bigint since that was implemented in the linked PR. Are there others already there that are just not yet documented @dprophet @yuuteng  @ebyhr 
Another PR merged and added topn, and one activated limit testing. So I added those. Anyone if join pushdown is supported? 
* #21148
* #21219 
* #21202 
=> Add pushdown docs for Snowflake

plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java, plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
=> Enable numeric aggregation pushdown test for Snowflake connector

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/JdbcClientStats.java, plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
Improve speed of getting table comments in JDBC connectors manifold. Get them all at once.
=> Get table comments from RDBMS in bulk

core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroup.java, core/trino-main/src/main/java/io/trino/execution/resourcegroups/ResourceUsage.java
=> Remove redundant clone method 

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/RemoteLogTracingEvent.java, plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java, plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java
Add RemoteTracingEvent to support check a database event(in log) happened or not without grab all logs from container at a time.
Update Postgresql testCancellation test to use RemoteTracingEvent.
https://trinodb.slack.com/archives/CP1MUNEUX/p1710496005499909
=> Add RemoteLogTracingEvent to allow tracing the event happen or not

docs/src/main/sphinx/object-storage/file-system-s3.md, lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3Context.java, lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemConfig.java, lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemFactory.java, lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3OutputStream.java, lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemConfig.java, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-databricks-http-hms/delta.properties, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-databricks-http-hms/hive.properties, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-delta-lake-databricks/delta.properties, testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-delta-lake-databricks/hive.properties, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeJmx.java
```markdown
* Add support for acl config in native s3 filesystem
```
=> Add support for ACL config in native S3 filesystem

docs/src/main/sphinx/admin/resource-groups.md
Minor doc update only.
Replaces https://github.com/trinodb/trino/pull/20828
=> Describe rule matching selector

plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchServer.java
Cope with sporadic startup timeouts on the Elasticsearch Docker testcontainer startup:
- `elasticsearch:7.16.2 started in PT1M5.003313627S`
- `elasticsearch:7.16.2 started in PT55.318822806S`
```markdown
```
=> Increase Elasticsearch container startup timeout to 5 minutes

docs/src/main/sphinx/connector/delta-lake.md
Fixes https://github.com/trinodb/trino/issues/21271
https://github.com/trinodb/trino/blob/12eb46748fd934531933f35155ac899aca64bf16/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/thrift/DeltaLakeThriftMetastoreModule.java#L29
=> Fix requirement for renaming tables in Delta Lake documentation

plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
=> Enable Snowflake testInsertIntoNotNullColumn test

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
`canEnforceColumnConstraintInSpecs` may incorrectly return True when no partitionSpec match found. This is because stream.allMatch always returns true on empty stream.
May create incorrect query plan:
without data, plan treats `a` as partition column.
```
trino:default> explain select * FROM iceberg.tmp."jl_iceberg_0325" where a = 'a';
Query Plan
---------------------------------------------------------------------------------------------------
Trino version: 439.0
Fragment 0 [SOURCE]
Output layout: [a, ds]
Output[columnNames = [a, ds]]
│   Layout: [a:varchar, ds:varchar]
│   Estimates: {rows: 0 (0B), cpu: 0, memory: 0B, network: 0B}
└─ TableScan[table = iceberg:tmp.jl_iceberg_0325$dataFOR VERSION AS OF 6043893226421131063]
Layout: [a:varchar, ds:varchar] …
```
=> Fix incorrect partition pushdown when no partitionSpec exists in Iceberg

plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
=> Enable Snowflake testAddNotNullColumn test

docs/src/main/sphinx/object-storage/file-system-cache.md
- For file system caching
- Must be separate directories
- Based on user running into issues otherwise
https://trinodb.slack.com/archives/CP1MUNEUX/p1711449997896219
=> Clarify caching for multiple catalogs

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeCommitSummary.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeLocalConcurrentWritesTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMinioAndHmsConnectorSmokeTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java
Follow-up from https://github.com/trinodb/trino/pull/18506
Add concurrent writes reconciliation for non-blind INSERT in Delta Lake
On tables with isolation level WriteSerializable, allow committing
non-blind append INSERT operations in a concurrent context by
placing these operations right after any other previously concurrently
completed write operations.
For disambiguation, INSERT operations that contain subqueries reading the same
table are considered non-blind inserts.
Disallow committing insert operations in any of the following cases:
- table schema change has been committed in the meantime
- table protocol change has been committed in the meantime
- add files committed in the meantime should be read by
the current insert operations
- remove files committed in the meantime conflict …
=> Add concurrent writes reconciliation for non-blind INSERT in Delta Lake

plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java, plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeClient.java, plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
```markdown
* Add support for [aggregation pushdown](aggregation-pushdown) of the `count(distinct)` function. ({issue}`21130`)
```
=> Add support for count distinct pushdown for snowflake

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
The previous logic was depending on the ordering of the columns in the schema of the table and not on the ordering of the partition keys which could have produced inconsistent partition values for tables with composed partition keys.
Relates to finding https://github.com/trinodb/trino/pull/20993/files#r1536703816
```markdown
```
=> Keep consistent the ordering of partition values to the partition keys

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
Make AdaptivePlanner optional in the FTE scheduler instead of having a separate boolean field indicating whether the planner is to be used.
Reduces potential for inadvertent erroneous use; simplifies method signatures.
```markdown
```
=> Make AdaptivePlanner optional in the FTE scheduler

core/trino-spi/src/main/java/io/trino/spi/type/TypeOperators.java
Synchronizing on get() method causes planning
congestion when there is high query concurrency.
```markdown
```
=> Use double checked locking in OperatorAdaptor

testing/trino-testing-containers/src/main/java/io/trino/testing/containers/junit/ReportLeakedContainers.java
Stopped containers can be left behind when using
`withStartupAttempts()`. They should only use up disk space, not other resources, and will still be cleaned up by testcontainers on exit.
=> Ignore stopped containers in resource leak detector

docs/src/main/sphinx/installation/containers.md
=> Fix reference in Docker docs

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMergeTableHandle.java, plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergWritableTableHandle.java
Fixes https://github.com/trinodb/trino/issues/21319
=> Fix JsonProperty annotation in Iceberg

core/trino-main/src/main/java/io/trino/operator/scalar/TryFunction.java, core/trino-main/src/main/java/io/trino/sql/ir/Call.java, core/trino-main/src/main/java/io/trino/sql/ir/Comparison.java, core/trino-main/src/main/java/io/trino/sql/ir/Constant.java, core/trino-main/src/main/java/io/trino/sql/ir/ExpressionFormatter.java, core/trino-main/src/main/java/io/trino/sql/ir/In.java, core/trino-main/src/main/java/io/trino/sql/ir/IsNull.java, core/trino-main/src/main/java/io/trino/sql/ir/Logical.java, core/trino-main/src/main/java/io/trino/sql/ir/Not.java, core/trino-main/src/main/java/io/trino/sql/ir/Reference.java, core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java, core/trino-main/src/main/java/io/trino/sql/planner/EffectivePredicateExtractor.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyTableScanRedirection.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushFilterThroughCountAggregation.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateThroughProjectIntoRowNumber.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateThroughProjectIntoWindow.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushdownFilterIntoRowNumber.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushdownFilterIntoWindow.java, core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantPredicateAboveTableScan.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/IndexJoinOptimizer.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java, core/trino-main/src/main/java/io/trino/sql/planner/optimizations/WindowFilterPushDown.java, core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java, core/trino-main/src/test/java/io/trino/sql/planner/TestEffectivePredicateExtractor.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHivePlans.java
=> Simplify derived effective predicate

docs/src/main/sphinx/sql/alter-table.md
This PR adds some clarifications to what procedures are available when running `ALTER TABLE EXECUTE`. 
```markdown
```
=> Clarify docs for ALTER TABLE EXECUTE

plugin/trino-kafka/pom.xml, pom.xml
No release notes needed.
Another boring change :)
=> Update google cloud libraries-bom to 26.35.0

pom.xml
This bump contains: https://github.com/trinodb/docker-images/compare/92...93
=> Update docker-images version to 93

plugin/trino-bigquery/pom.xml, plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowToPageConverter.java, plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryArrowSerialization.java
The size of 'vectors' and 'columns' in BigQueryArrowToPageConverter can be different when columns in predicates don't exist in projection when materializing BigQuery views.
```markdown
* Fix failure when reading BigQuery views with [Apache Arrow](https://arrow.apache.org/docs/). ({issue}`issuenumber`)
```
=> Fix failure when reading BigQuery views with Arrow

plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
Example failure: https://github.com/trinodb/trino/actions/runs/8434992142/job/23099479513
=> Disable testAddColumnConcurrently in Snowflake

core/trino-main/src/main/java/io/trino/execution/SqlQueryExecution.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java, core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/StageExecutionStats.java, core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
=> Add some FTE scheduler statistics

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AdaptivePartitioning.java, core/trino-main/src/test/java/io/trino/sql/planner/TestAdaptivePlanner.java, core/trino-main/src/test/java/io/trino/sql/planner/assertions/BasePlanTest.java, core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAdaptivePartitioning.java
=> Skip AdaptivePartitioning from running multiple times

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
`BaseConnectorTest#testDropTable` ensures non-existence of the table after dropping. No need to verify that in each test.
Also, `getQueryRunner().tableExists` was misused in testPartitionedTableStatistics. The method always returns false if we pass qualified table names.
=> Remove BaseIcebergConnectorTest.dropTable method

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/functions/tablechanges/TableChangesSplitSource.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java, plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/AddFileEntry.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSplitManager.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCloneTableCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDeleteCompatibility.java
Support reading absolute paths from the Delta transaction log
Fixes https://github.com/trinodb/trino/issues/17011
```markdown
* Add support reading [shallow cloned tables](https://docs.databricks.com/sql/language-manual/delta-clone.html). ({issue}`17011`)
```
=> Add support for absolute path in Delta Lake connector

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedView.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogMaterializedView.java
Improve tests from https://github.com/trinodb/trino/pull/20211
- move them to base class
- remove singlethreadedness added in that PR
=> Move Iceberg MV with PTF tests to base class

core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java, core/trino-main/src/test/java/io/trino/cost/TestOptimizerConfig.java, docs/src/main/sphinx/admin/properties-optimizer.md
Reduces planning time for tpcds/q64 from 11.8s to 6.6s at sf1k by reducing the default of optimizer.max-reordered-joins to 8 from 9. q64 is the only TPC query affected, it has a different join order but it’s execution was not slowed compared to before.
Further reduction to 7 helps some more with planning time but the plan for q72 becomes worse, so we leave it at 8.
```markdown
* Improve planning time for queries with large number of joins. ({issue}`21360`)
```
=> Reduce optimizer.max-reordered-joins default to 8

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeLocalConcurrentWritesTest.java
In the context of concurrent operations, it may potentially happen that between the time when the version of table has been initially read for scanning and the time when the planning of the write operation begins that a new version of the table is current. Nevertheless, use in performing the write operations the version of the table initially read as reference for beginning the operation to ensure the consistency of the operation.
This strategy helps in unintentionally skipping the processing of transaction log information corresponding to other concurrent operations.
Fixes https://github.com/trinodb/trino/issues/21324 …
=> Fix potentially incorrect table read version for writes on Delta Lake

docs/src/main/sphinx/functions/map.md
This commit updates the documentation to clearly state that using the subscript operator `[]` will result in an error if the specified key does not exist. 
It also recommends using the `element_at` function as a safer alternative when there is a possibility that the key might not be present. This change aims to improve clarity and aid developers in handling potential errors more effectively.
cf. https://trinodb.slack.com/archives/CLEDR9V7G/p1702021254436669?thread_ts=1702003731.904799&cid=CLEDR9V7G
=> docs: Clarify error behavior of subscript operator and suggest element_at alternative

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedGlueMetastoreWithTableRedirections.java, plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaS3AndGlueMetastoreTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveS3AndGlueMetastoreTest.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestGlueHiveMetastore.java, plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestingGlueHiveMetastore.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergS3AndGlueMetastoreTest.java, plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestSharedGlueMetastore.java
createTempDirectory().toFile().mkdirs() will always return false as createTempDirectory() will create a directory
```markdown
```
=> Move directory existence check to TestingGlueHiveMetastore

docs/src/main/sphinx/develop.md, docs/src/main/sphinx/develop/tests.md
Add guidelines for writing tests.
Converted from google doc - follow up about role on website will come after merge.
However.. we should mention it somewhere quite prominently.
=> Add test guide

testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java, testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/util/IcebergTestUtils.java
=> Make Iceberg to Spark compatibility tests more resilient to retries

core/trino-main/src/main/java/io/trino/operator/aggregation/AggregationMaskCompiler.java
Generated AggregationMask was not properly handling dictionary encoded mask blocks.
Fixes #21272
```markdown
* Fix `IllegalArgumentException` in generated aggregation mask. ({issue}`21272`)
```
=> Fix dictionary handling in AggregationMaskCompiler

testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DeltaLakeTestUtils.java
Handle stacktraces like the following:
```
2024-03-28T17:53:19.5139785Z tests               | java.lang.RuntimeException: java.sql.SQLException: [Databricks][JDBCDriver](500593) Communication link failure. Failed to connect to server. Reason: java.net.SocketTimeoutException: Read timed out.
2024-03-28T17:53:19.5143067Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.openConnection(JdbcQueryExecutor.java:63)
2024-03-28T17:53:19.5145312Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.execute(JdbcQueryExecutor.java:103)
2024-03-28T17:53:19.5147447Z tests               | 	at io.trino.tempto.query.JdbcQueryExecutor.executeQuery(JdbcQueryExecutor.java:84)
2024-03-28T17:53:19.5149984Z tests               | 	at …
```
=> Retry on "Read timed out." in Delta Lake Databricks tests

docs/src/main/sphinx/release.md, docs/src/main/sphinx/release/release-444.md
Assemble the release notes for the upcoming Trino 443 release.
* #21193 ✅ rn ✅ docs
* #21194 ✅ rn ✅ docs
* #21197 ✅ rn ✅ docs
* #21148 ✅ rn ✅ docs
* #21202 ✅ rn ✅ docs - #21214
* #21195 ✅ rn ✅ docs
* #21208 ✅ rn ✅ docs
* #21211 ✅ rn ✅ docs
* #21213 ✅ rn ✅ docs
* #21206 ✅ rn ✅ docs
* #21215 ✅ rn ✅ docs
* #21216 ✅ rn ✅ docs
* #21217 ✅ rn ✅ docs
* #21218 ✅ rn ✅ docs
* #21220 ✅ rn ✅ docs
* #20484 ✅ rn ✅ docs
* #20410 ✅ rn ✅ docs
* #21219 ✅ rn ✅ docs - #21214
* …
=> Add Trino 444 release notes

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DriverConnectionFactory.java
Fixes https://github.com/trinodb/trino/issues/20881
=> Remove deprecated constructors from DriverConnectionFactory

core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4, core/trino-main/src/main/java/io/trino/execution/CreateViewTask.java, core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java, core/trino-main/src/test/java/io/trino/execution/TestCreateViewTask.java, core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java, core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java, core/trino-parser/src/main/java/io/trino/sql/tree/CreateView.java, core/trino-parser/src/test/java/io/trino/sql/TestSqlFormatter.java, core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
Parser set of changes for supporting creating view properties. 
The proposed syntax would be like this
```
CREATE VIEW view_name WITH (property_key = 'property_value') AS SELECT ...
```
```markdown
```
=> Support creating view with properties in parser

docs/src/main/sphinx/connector/snowflake.md, plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClient.java, plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java, plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeTypeMapping.java
Enable time type connector test and add a time type mapping test.
Also this fixes the batch writing error if the insert more than 1 rows while containing the time type column.
=> Enable time type test for Snowflake connector

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultQueryBuilder.java, plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcQueryBuilder.java
SELECT * can have special behavior in some databases and generally should be avoided. This restores to previous behavior, before 91a29a7d8d2ddb1d1e7ba9bb529160d06f4542b5 (#19996).
=> Avoid SELECT * in base JDBC query builder

docs/src/main/sphinx/object-storage/metastores.md
The metastore documentation for the JDBC catalog currently repeats a couple sentences.  In addition, the text refers to the REST metadata catalog when I think it should refer to JDBC.
=> Remove duplicate doc and clarify JDBC vs REST

core/trino-main/src/main/java/io/trino/Session.java, core/trino-main/src/main/java/io/trino/dispatcher/DispatchManager.java, core/trino-main/src/main/java/io/trino/execution/SetSessionTask.java, core/trino-main/src/main/java/io/trino/security/AccessControl.java, core/trino-main/src/main/java/io/trino/security/AccessControlManager.java, core/trino-main/src/main/java/io/trino/security/AllowAllAccessControl.java, core/trino-main/src/main/java/io/trino/security/DenyAllAccessControl.java, core/trino-main/src/main/java/io/trino/security/ForwardingAccessControl.java, core/trino-main/src/main/java/io/trino/testing/PlanTester.java, core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java, core/trino-main/src/main/java/io/trino/tracing/TracingAccessControl.java, core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java, core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java, lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ReadOnlySystemAccessControl.java, lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedSystemAccessControlTest.java
Commit 309f203804fb2bb12573d18d157b554c0b9fa3c5 made the `QueryId` mandatory, instead of `Optional`, in `SystemSecurityContext` and removed the security context from invocations which can't reliably pass it. It was also removed from these invocations, but not because it wasn't available, but because nobody actually passed it. This commit series brings it back into the SPI and makes the engine pass it to access control.
NOTE: It does not restore the full `SystemSecurityContext`, because it requires a `TransactionId`, which is truly not available. At least for `checkCanExecuteQuery` it is not, AFAICT.
(x) Release notes are required, with the …
=> Restore QueryId to two access control checks

client/trino-client/src/main/java/io/trino/client/uri/ConnectionProperties.java, core/trino-main/src/test/java/io/trino/sql/gen/TestExpressionCompiler.java, pom.xml, testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
Item documented with a `@deprecated` javadoc note should be annotated with `@Deprecated` for the deprecation to be fully effective for API consumers.
=> Require deprecation annotation on deprecated methods

plugin/trino-redis/src/test/java/io/trino/plugin/redis/util/RedisServer.java
Per https://redis.io/docs/about/releases/ only two major releases prior to the current one are considered supported. As of this writing, the latest version is 7.2, to 5.x is the oldest still supported version.
=> Drop testing with unsupported Redis version

core/trino-main/pom.xml, plugin/trino-accumulo/pom.xml, plugin/trino-elasticsearch/pom.xml, plugin/trino-exchange-filesystem/pom.xml, plugin/trino-kinesis/pom.xml, plugin/trino-opensearch/pom.xml, plugin/trino-thrift/pom.xml, pom.xml, testing/trino-product-tests/pom.xml
This brings updated Jetty to 12.0.8, Jersey to 3.1.6 and Airlift's language level to 21.
```markdown
```
=> Update airlift to 244

testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDeleteCompatibility.java
At the time of this writing, the metastore of the product test has the location for the `default` schema set to
```
hdfs://hadoop-master:9000/user/hive/warehouse
```
Use an explicit location for the cloned table in order to avoid writing the cloned table to hdfs.
=> Add explicit location for the cloned table

plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlClient.java
Currently `testConvertComparison` is applied only for `EQUAL` operator and for all the other comparison operator it is being untested.
```markdown
```
=> Fix testConvertComparison test in TestPostgreSqlClient

docs/src/main/sphinx/connector/redis.md
Recent PR upgraded testing.. adjusting docs .. but 5.0.0  (https://github.com/redis/redis/releases/tag/5.0.0) is still very old so maybe we should even go with 6.0.0 (https://github.com/redis/redis/releases/tag/6.0.0)
We could also use https://github.com/redis/redis/releases/tag/5.0.14 .. since that has a lot of security issues fixed and is a least a bit newer .. and also what we use in testing now.
https://github.com/trinodb/trino/pull/21431#issuecomment-2041156140
=> Update Redis version requirement

core/trino-main/src/main/java/io/trino/execution/executor/timesharing/PrioritizedSplitRunner.java, core/trino-main/src/main/java/io/trino/execution/executor/timesharing/TimeSharingTaskExecutor.java, core/trino-main/src/main/java/io/trino/operator/Driver.java
Exceptions thrown from processNewSources were not handled correctly. We just logged an error and marked the PrioritizedSplitRunner as finished. The for which the PSR were executing remained RUNNING and query hang indefinitely.
```markdown
* Fix rare case when queries could hang.
```
=> Fail Driver on exception from processNewSources
