plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Test adding field on corrupted Iceberg table

---

plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java

Element is not array, it should not have array dimensions set.

Fix element handle type handle

---

client/trino-jdbc/src/test/java/io/trino/jdbc/BaseTestJdbcResultSet.java

Use method reference in testMaxRowsExceedsLimit

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePreferredPartitioning.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedHiveMetastoreWithViews.java

Switch remaining Delta Lake tests to Native FS

---

plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClusteringPredicatesExtractor.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraColumnHandle.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraInsertTableHandle.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraOutputTableHandle.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPageSinkProvider.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPartitionManager.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraRecordSet.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraRecordSetProvider.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSession.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTable.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTableHandle.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/ptf/Query.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/util/CassandraCqlUtils.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraColumnHandle.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnector.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraTableHandle.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestJsonCassandraHandles.java

Convert table and column handle classes to record in Cassandra

---

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoInsertTableHandle.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoOutputTableHandle.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSinkProvider.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoTableHandle.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ptf/Query.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoProjectionPushdownPlans.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTableHandle.java

Convert table handle classes to record in MongoDB

---

plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleColumnHandle.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleInsertTableHandle.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleOutputTableHandle.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHolePageSinkProvider.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHolePageSourceProvider.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleSplitManager.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleTableHandle.java

Convert some classes to record in Blackhole connector

---

plugin/trino-memory/src/main/java/io/trino/plugin/memory/ColumnInfo.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryColumnHandle.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryOutputTableHandle.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPageSinkProvider.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPageSourceProvider.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemorySplitManager.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryTableHandle.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/TableInfo.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryMetadata.java

Convert some classes to record in Memory connector

---

plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxColumnHandle.java
plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxMetadata.java
plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxPeriodicSampler.java
plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxRecordSetProvider.java
plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxSplitManager.java
plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxTableHandle.java
plugin/trino-jmx/src/test/java/io/trino/plugin/jmx/TestJmxMetadata.java

Convert some classes to record in JMX

---

plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsClient.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsColumnHandle.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsConnectorInsertTableHandle.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsConnectorTableHandle.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsMetadata.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsNamedTableHandle.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsPageSink.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsPageSinkProvider.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsRecordCursor.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsRecordSet.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsSheetTableHandle.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsSplit.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/ptf/Sheet.java

Convert some classes to record in Google Sheets

---

core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushTopNIntoTableScan.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchColumnHandle.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchMetadata.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchNodePartitioningProvider.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchPartitioningHandle.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchRecordSet.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchRecordSetProvider.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchTableHandle.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/statistics/ColumnStatisticsData.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/statistics/StatisticsEstimator.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/statistics/TableStatisticsData.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/util/PredicateUtils.java
plugin/trino-tpch/src/test/java/io/trino/plugin/tpch/TestTpchMetadata.java
testing/trino-testing/src/main/java/io/trino/testing/H2QueryRunner.java
testing/trino-testing/src/main/java/io/trino/testing/tpch/TpchIndexMetadata.java
testing/trino-testing/src/main/java/io/trino/testing/tpch/TpchIndexProvider.java

Convert some classes to record in TPCH

---

plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisMetadata.java
plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisSplitManager.java
plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisTableDescription.java
plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisTableDescriptionSupplier.java
plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisTableFieldGroup.java
plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisTableHandle.java
plugin/trino-redis/src/test/java/io/trino/plugin/redis/AbstractTestMinimalFunctionality.java
plugin/trino-redis/src/test/java/io/trino/plugin/redis/util/RedisTestUtils.java

Convert some classes to record in Redis

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryInsertTableHandle.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryOutputTableHandle.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPageSink.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPageSinkProvider.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryQueryPageSource.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTableHandle.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTransactionHandle.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryUtil.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/RemoteTableName.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ptf/Query.java

Convert some classes to record in BigQuery

---

plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java

Fix flaky TestCassandraConnectorTest

---

.github/actions/compile-commit/action.yml
pom.xml

Update s3mock-testcontainers to 3.6.0

---

docs/src/main/sphinx/connector/iceberg.md

Documentation follow-up from f6d6b049

Add documentation for `sorted_by` table property

---

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoColumnHandle.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoInsertTableHandle.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoOutputTableHandle.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSink.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSource.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoTable.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoTransactionHandle.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/RemoteTableName.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ptf/Query.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoProjectionPushdownPlans.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoSession.java

Convert some classes to record in MongoDB

---

lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemLocalStack.java

upgrade to latest localstack (3.3.0)
https://hub.docker.com/r/localstack/localstack/tags
```markdown
```

Upgrade to localstack 3.3.0

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTableHandle.java

Include all fields in the equality.
relates
- https://github.com/trinodb/trino/pull/21574

Fix HiveTableHandle equality

---

core/trino-main/pom.xml

Remove unused benchmarks profile

---

.github/bin/build-pt-matrix-from-impacted-connectors.py

The generated matrix could be invalid if `include` items are added to `exclude`, instead of just being removed from `include`.

Fix build pt matrix script

---

docs/src/main/sphinx/client/jdbc.md

Fix list table in JDBC docs

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java

Randomize table name in BaseHiveConnectorTest
```markdown
```

Randomize table name in BaseHiveConnectorTest

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcFileWriter.java

`OrcFileWriter.orcWriter` was made `protected` in https://github.com/trinodb/trino/commit/27483269f528ab2c750b06b6e1ddcdd1f8261692 but no longer needs to be after https://github.com/trinodb/trino/commit/1dd3199b6bba4008c4e3f84755994769d5f5e37b.
- https://github.com/trinodb/trino/pull/4055
- https://github.com/trinodb/trino/pull/19667
```markdown
```

Make OrcFileWriter.orcWriter private

---

core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPageSourceProvider.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemorySplit.java

~Currently based on https://github.com/trinodb/trino/pull/21632 to avoid code conflicts.~

Convert MemorySplit to record

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java

Move testConcurrentInsertsReconciliationForBlindInserts in Delta Lake

---

plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusColumn.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusMetadata.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusQueryResponseParse.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusRecordCursor.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusSplitManager.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusStandardizedRow.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusTable.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusCaseInsensitiveNameMatching.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegration.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusRecordSet.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusSplit.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusTable.java

Convert some classes to record in Prometheus

---

core/trino-main/src/main/java/io/trino/execution/CreateCatalogTask.java
core/trino-main/src/test/java/io/trino/execution/TestCreateCatalogTask.java

Fixes https://github.com/trinodb/trino/issues/21399
```markdown
```

Normalize name when creating a new catalog

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeGcsConnectorSmokeTest.java
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/delta.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/hive.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/iceberg.properties

Switch remaining GCS tests to native file system.
```markdown
```

Switch GCS tests to native file system

---

plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotQueryBuilder.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotConnectorSmokeTest.java
plugin/trino-pinot/src/test/resources/string_realtimeSpec.json
plugin/trino-pinot/src/test/resources/string_schema.json

Fixes https://github.com/trinodb/trino/issues/21681
```markdown
```

Fix failure when single quote exists in Pinot condition

---

.github/workflows/ci.yml
docs/src/main/sphinx/connector/iceberg.md
docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/CatalogType.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/IcebergCatalogModule.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/TrinoCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/snowflake/IcebergSnowflakeCatalogConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/snowflake/IcebergSnowflakeCatalogModule.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/snowflake/SnowflakeIcebergTableOperationsProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/snowflake/TrinoSnowflakeCatalog.java
plugin/trino-iceberg/src/main/java/org/apache/iceberg/snowflake/SnowflakeIcebergTableOperations.java
plugin/trino-iceberg/src/main/java/org/apache/iceberg/snowflake/TrinoIcebergSnowflakeCatalogFactory.java
plugin/trino-iceberg/src/main/java/org/apache/iceberg/snowflake/TrinoIcebergSnowflakeCatalogFileIOFactory.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/snowflake/README.md
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/snowflake/TestIcebergSnowflakeCatalogConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/snowflake/TestIcebergSnowflakeCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/snowflake/TestingSnowflakeServer.java
plugin/trino-iceberg/src/test/java/org/apache/iceberg/snowflake/TestTrinoSnowflakeCatalog.java
plugin/trino-snowflake/pom.xml
pom.xml
testing/trino-faulttolerant-tests/pom.xml
testing/trino-tests/pom.xml

Add support for Snowflake Iceberg catalog https://www.snowflake.com/blog/iceberg-tables-catalog-support-available-now/. Implementation relies on [Iceberg snowflake catalog](https://github.com/apache/iceberg/blob/main/snowflake/src/main/java/org/apache/iceberg/snowflake/SnowflakeCatalog.java).
Fixes https://github.com/trinodb/trino/issues/19362
() Release notes are required. Please propose a release note for me.
(x ) Release notes are required, with the following suggested text:
```markdown
* Add Iceberg Snowflake catalog support
```

Add Iceberg Snowflake catalog support

---

docs/src/main/sphinx/connector/bigquery.md

Convert config properties to list-table in BigQuery documentation

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java

Fixes https://github.com/trinodb/trino/issues/21649

Append random suffix in BaseHiveConnectorTest

---

plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotBrokerPageSource.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotInsufficientServerResponseException.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotPageSourceProvider.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotSegmentPageSource.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotDataTableWithSize.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotGrpcDataFetcher.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotLegacyDataFetcher.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/AggregateExpression.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/DynamicTable.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/DynamicTablePqlExtractor.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/OrderByExpression.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotQueryInfo.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestDynamicTable.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotSplitManager.java

Convert some classes to record in Pinot

---

plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/PostgreSqlQueryRunner.java

Add TPCH tables in PostgreSqlQueryRunner main method

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcTypeHandle.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchSplit.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsSplit.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemorySplit.java
plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/OpenSearchSplit.java
pom.xml

Upgrade airlift to benefit from https://github.com/airlift/airlift/pull/1141.

Exclude record getter-like fields from JSON serialization

---

docs/src/main/sphinx/connector/delta-lake.md

* Remove extra colons from the `Delta Lake security values` table on the Delta Lake connector page.
```markdown
```

Remove extra colons

---

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystem.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureLocation.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java
lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsStorage.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAbfsConnectorSmokeTest.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeAzure.java
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-azure/hive.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-azure/update-location.sh
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAbfsSyncPartitionMetadata.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAzureBlobFileSystem.java

Fix one identified issue with paths with special characters, and switch remaining Azure tests to use the native FS.

Fix handling special characters in Azure native FS 

---

core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Close https://github.com/trinodb/trino/issues/21619
```markdown
* Fail implicitly assigning null to non-null column in MERGE. ({issue}`issuenumber`)
```

Fail implicitly assigning null to non-null column in MERGE

---

core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesScaledWriters.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java

Remove redundant empty line

---

.mvn/modernizer/violations-production-code-only.xml
core/trino-main/src/main/java/io/trino/execution/executor/dedicated/ThreadPerDriverTaskExecutor.java
core/trino-main/src/main/java/io/trino/execution/executor/scheduler/FairScheduler.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/ExponentialGrowthPartitionMemoryEstimator.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
plugin/trino-http-event-listener/pom.xml
plugin/trino-http-event-listener/src/main/java/io/trino/plugin/httpquery/HttpEventListener.java
plugin/trino-kinesis/pom.xml
plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/s3config/S3TableConfigClient.java
pom.xml
testing/trino-testing-containers/pom.xml
testing/trino-testing-containers/src/main/java/io/trino/testing/minio/MinioClient.java

Name threads in all thread pools

---

plugin/trino-iceberg/pom.xml
pom.xml

Update datasketches to 6.0.0 and other dependencies

---

plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisMetadata.java
plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisTableFieldDescription.java

Convert RedisTableFieldDescription to record

---

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryQueryRunner.java

Follow-up of https://github.com/trinodb/trino/pull/19676

Remove spurious logging in BigQuery tests

---

docs/src/main/sphinx/connector/delta-lake.md
docs/src/main/sphinx/connector/iceberg.md

This PR documents the `CREATE OR REPLACE TABLE` and `CREATE OR REPLACE TABLE AS` statements for the Iceberg and Delta lake connectors.
```markdown
```

Document replace tables for Delta Lake and update section for Iceberg

---

client/trino-jdbc/pom.xml
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionThroughJoin.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/TransformQuantifiedComparisonApplyToCorrelatedJoin.java
lib/trino-filesystem-cache-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioTracing.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/tracing/Tracing.java
pom.xml

~OpenTelemetry stuff is temporary.~

Update airbase to 156

---

plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestDatastaxConnectorSmokeTest.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestScyllaConnectorSmokeTest.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestingScyllaServer.java

Bump Cassandra flavoured supported database image versions.
```markdown
```

Bump Cassandra images

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/MetadataEntry.java

Add builder to MetadataEntry in Delta Lake

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/DockerContainer.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java

Limit product tests Trino nodes memory 

---

pom.xml

This improves reproducibility of the compressed tar.gz archives

Update provisio to 1.0.25

---

core/trino-main/src/main/java/io/trino/metadata/MaterializedViewDefinition.java

Check variable gracePeriod not null

---

core/trino-main/src/main/java/io/trino/cost/StatsCalculatorModule.java
core/trino-main/src/main/java/io/trino/cost/TopNRankingStatsRule.java
core/trino-main/src/test/java/io/trino/cost/TestTopNRankingStatsRule.java

Add support for TopNRankingStatsRule

---

core/trino-main/src/main/java/io/trino/metadata/SystemFunctionBundle.java
core/trino-main/src/main/java/io/trino/operator/aggregation/BitwiseXorAggregation.java
core/trino-main/src/test/java/io/trino/operator/aggregation/TestBitwiseAndAggregation.java
core/trino-main/src/test/java/io/trino/operator/aggregation/TestBitwiseOrAggregation.java
core/trino-main/src/test/java/io/trino/operator/aggregation/TestBitwiseXorAggregation.java
docs/src/main/sphinx/functions/aggregate.md

```markdown
* Add bitwise_xor_agg aggregation function. ({issue}`issuenumber`)
```

Add bitwise_xor_agg aggregation function

---

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PredicatePushDown.java

Fix typo in PredicatePushDown comment

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java
core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java

Export metrics from BinPackingNodeAllocatorService

---

core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorSplit.java

Follow-up of https://github.com/trinodb/trino/pull/21471

Fix message in ConnectorSplit.getInfo

---

client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverAuth.java
core/trino-main/src/main/java/io/trino/server/InternalAuthenticationManager.java
core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticator.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/JweTokenSerializer.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Service.java
core/trino-main/src/main/java/io/trino/server/ui/FormWebUiAuthenticationFilter.java
core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
core/trino-main/src/test/java/io/trino/server/security/jwt/TestJwkDecoder.java
core/trino-main/src/test/java/io/trino/server/security/oauth2/BaseOAuth2WebUiAuthenticationFilterTest.java
core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithJwt.java
core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithRefreshTokens.java
core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java

Fix some of jsonwebtoken deprecated api

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/ListTypeInfo.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/type/MapTypeInfo.java

Follow-up of https://github.com/trinodb/trino/pull/18296

Fix instance size for list and map types on Hive

---

core/trino-main/src/main/java/io/trino/operator/scalar/TryCastFunction.java
core/trino-main/src/main/java/io/trino/sql/analyzer/ConstantEvaluator.java
core/trino-main/src/main/java/io/trino/sql/ir/Cast.java
core/trino-main/src/main/java/io/trino/sql/ir/ExpressionFormatter.java
core/trino-main/src/main/java/io/trino/sql/ir/ExpressionTreeRewriter.java
core/trino-main/src/main/java/io/trino/sql/ir/IrExpressions.java
core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
core/trino-main/src/main/java/io/trino/sql/planner/IrExpressionInterpreter.java
core/trino-main/src/main/java/io/trino/sql/planner/NullabilityAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/SubqueryPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/TranslationMap.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyTableScanRedirection.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushCastIntoRow.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapRowSubscript.java
core/trino-main/src/main/java/io/trino/sql/relational/SqlToRowExpressionTranslator.java
core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutinePlanner.java
core/trino-main/src/test/java/io/trino/sql/TestExpressionInterpreter.java
core/trino-main/src/test/java/io/trino/sql/planner/TestConnectorExpressionTranslator.java
core/trino-main/src/test/java/io/trino/sql/planner/TestDynamicFilter.java
core/trino-main/src/test/java/io/trino/sql/planner/TestEqualityInference.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestSimplifyExpressions.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestUnwrapRowSubscript.java

Desugar try_cast during initial planning

---

plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/main/java/org/apache/iceberg/snowflake/TrinoIcebergSnowflakeCatalogFactory.java

Use Json Snowflake result format in Iceberg Snowflake catalog
```markdown
```

Use Json Snowflake result format in Iceberg Snowflake catalog

---

docs/src/main/sphinx/object-storage/metastores.md
docs/src/main/sphinx/security/inspect-jks.md
docs/src/main/sphinx/sql/select.md

There were several instances of repeated "the the" in the docs.
```markdown
```

Fix "the the" in docs

---

.github/workflows/docs.yml

Update Java version to 22 in docs CI

---

plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/table/HudiTableFileSystemView.java

Avoid using string concat for logger in Hudi

---

core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java

Fix typo in CoordinatorModule

---

docs/src/main/sphinx/admin/properties-optimizer.md

Document missing optimizer session properties

Document optimizer session properties

---

pom.xml

Supersedes https://github.com/trinodb/trino/pull/21802. Added @Fokko as a coauthor of the last commit.

Update airlift, drift, parquet, picocli

---

plugin/trino-mongodb/pom.xml
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoErrorCode.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSource.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ptf/Query.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java

Set air.compiler.fail-warnings as true in MongoDB

---

client/trino-cli/src/main/java/io/trino/cli/OutputHandler.java
client/trino-cli/src/main/java/io/trino/cli/QueryPreprocessor.java
core/trino-main/src/main/java/io/trino/metadata/AbstractTypedJacksonModule.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/NonceCookie.java
core/trino-main/src/main/java/io/trino/server/ui/MultipartUiCookie.java
core/trino-main/src/main/java/io/trino/util/AutoCloseableCloser.java
core/trino-main/src/test/java/io/trino/operator/aggregation/TestQuantileDigestAggregationFunction.java
core/trino-main/src/test/java/io/trino/util/TestAutoCloseableCloser.java
lib/trino-orc/src/main/java/io/trino/orc/metadata/ExceptionWrappingMetadataReader.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java

(*) This is not user-visible or is docs only, and no release notes are required.
```markdown
```

Fix use of various deprecated APIs

---

docs/src/main/sphinx/connector/phoenix.md
plugin/trino-phoenix5/pom.xml
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestingPhoenixServer.java

Remove incorrect untested time mapping from Phoenix

---

core/trino-main/src/main/java/io/trino/sql/planner/Symbol.java
core/trino-main/src/main/java/io/trino/sql/planner/SymbolAllocator.java
core/trino-main/src/test/java/io/trino/sql/planner/TestSymbolAllocator.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Fixes https://github.com/trinodb/trino/issues/21881
```markdown
```

Fix failure when reading non-alphanumeric column names

---

docs/src/main/sphinx/connector/iceberg.md

Correct in other places in the docs ...

Add docs for Avro as supported format

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java

The executor created in `GlueHiveMetastore` constructor was never shut down.

Fix thread leak in v2 GlueHiveMetastore

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePlugin.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/v1/GlueMetastoreModule.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePlugin.java

Relates to: https://github.com/trinodb/trino/pull/21908

Fix thread leak in v1 GlueHiveMetastore

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaS3AndGlueMetastoreTest.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseS3AndGlueMetastoreTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergS3AndGlueMetastoreTest.java

Fixes https://github.com/trinodb/trino/issues/21917 
probably relates to https://github.com/trinodb/trino/pull/20657

Fix Glue table listing when database deleted concurrently

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3OutputStream.java
plugin/trino-delta-lake/pom.xml
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaS3AndGlueMetastoreTest.java
plugin/trino-hive/pom.xml
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseS3AndGlueMetastoreTest.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/S3Assert.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveS3AndGlueMetastoreTest.java
plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergS3AndGlueMetastoreTest.java

For https://github.com/trinodb/trino/issues/21917

Migrate Glue/S3 tests to AWS SDK v2

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java

Move HiveMetastore to field in TestDeltaLakeConnectorTest

---

docs/src/main/sphinx/connector/hudi.md

Fix typo in Hudi connector documentation

---

plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeManager.java

Fix FS exchange manager thread leak

---

plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduSplitManager.java

Allow to wait for more than one DF in Kudu

Allow to wait for more than one DF in Kudu

---

plugin/trino-google-sheets/pom.xml
plugin/trino-iceberg/pom.xml
pom.xml

Update cloud SDKs and other dependencies

---

plugin/trino-cassandra/pom.xml
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClientModule.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSession.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraServer.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestingScyllaServer.java

Fix client threads leak in Cassandra connector shutdown

---

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java

Bring back IS DISTINCT FROM join pushdown testing

---

plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloModule.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/metadata/ZooKeeperMetadataManager.java
plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/AccumuloQueryRunner.java
plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloMetadataManager.java
plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestingAccumuloServer.java

Fix Accumulo reasource leaks 

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-448.md

Assemble the release notes for the upcoming Trino 448 release.
* #21879 ✅ rn ✅ docs
* #21883 ✅ rn ✅ docs
* #21889 ✅ rn ✅ docs
* #21891 ✅ rn ✅ docs
* #21893 ✅ rn ✅ docs
* #21899 ✅ rn ✅ docs
* #20657 ✅ rn ❌ docs
* #21887 ✅ rn ✅ docs
* #21890 ✅ rn ✅ docs
* #21509 ✅ rn ✅ docs
* #21465 ✅ rn ✅ docs
* #21915 ✅ rn ✅ docs
* #21908 ✅ rn ✅ docs
* #21910 ✅ rn ✅ docs
* #21927 ✅ rn ✅ docs
* #21912 ✅ rn ✅ docs
* #21919 ✅ rn ✅ docs
* #21918 ✅ rn ✅ docs
* #21811 ✅ rn ✅ docs
* #21762 ✅ rn ✅ docs
* #21896 ✅ rn ✅ docs
* #21562 ✅ rn ✅ docs
* #21924 ✅ rn ✅ …

Add Trino 448 release notes

---

.github/workflows/ci.yml

Cache maven in maven-checks on JDK 22

---

plugin/trino-cassandra/pom.xml
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/BackoffRetryPolicy.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraRecordCursor.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTypeManager.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/FallthroughRetryPolicy.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/ptf/Query.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnector.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java

Set air.compiler.fail-warnings as true in Cassandra

---

core/trino-spi/src/main/java/io/trino/spi/predicate/Range.java
core/trino-spi/src/test/java/io/trino/spi/predicate/TestRange.java

Improve error message for invalid range bounds

---

core/trino-main/src/main/java/io/trino/execution/CreateCatalogTask.java
core/trino-main/src/main/java/io/trino/metadata/PropertyUtil.java
core/trino-main/src/main/java/io/trino/metadata/TableProceduresPropertyManager.java
core/trino-main/src/main/java/io/trino/sql/analyzer/LiteralInterpreter.java
core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineAnalyzer.java
core/trino-main/src/test/java/io/trino/execution/TestCreateMaterializedViewTask.java
core/trino-main/src/test/java/io/trino/execution/TestCreateViewTask.java
core/trino-main/src/test/java/io/trino/sql/query/TestInlineFunctions.java
core/trino-parser/src/main/java/io/trino/sql/tree/Property.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergStatistics.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
testing/trino-tests/src/test/java/io/trino/tests/TestMockConnector.java
testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchConnectorTest.java

This also includes a few cleanup and refactoring commits.

Report error position when evaluating properties

---

lib/trino-array/pom.xml
lib/trino-geospatial-toolkit/pom.xml
lib/trino-memory-context/pom.xml
lib/trino-orc/pom.xml
lib/trino-record-decoder/pom.xml
lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/DescriptorProvider.java

Set air.compiler.fail-warnings as true in lib modules

---

plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClusteringPredicatesExtractor.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraColumnHandle.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraPartitionManager.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraRecordCursor.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSession.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraType.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTypeManager.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTypes.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnector.java

Convert CassandraType to record

---

plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotSessionProperties.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotSplitManager.java

Minor cleanup in Pinot session properties

---

plugin/trino-opensearch/pom.xml
plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/OpenSearchMetadata.java
plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/IndexMetadata.java
plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/OpenSearchClient.java

Minor cleanup in OpenSearch connector

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/SnapshotsTable.java

Avoid unnecessary unboxing in SnapshotsTable

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/OrcMetrics.java

Specify RoundingMode explicitly in OrcMetrics

---

plugin/trino-hudi/pom.xml
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java

Set air.compiler.fail-warnings as true in Hudi

---

core/trino-main/src/main/java/io/trino/server/ui/LoginResource.java

Remove unused UriInfo argument

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java

`roleSessionName` is required for STS assume role requests
```markdown
```

Provide roleSessionName for Glue metastore assume role credentials

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java

Avoid using `RewriteFiles.rewriteFiles()` that has been deprecated and will be removed in Iceberg 2.0.
https://github.com/apache/iceberg/pull/7501
```markdown
```

Avoid using deprecated method in IcebergMetadata

---

docs/src/main/sphinx/connector/snowflake.md

Still need a good example for Snowflake SQL query to pass through.
Also confirmation that this works... 

Document query passthrough to Snowflake

---

docs/src/main/sphinx/release/release-448.md

Follows https://github.com/trinodb/trino/pull/22069

Inform about ignored cache config options with Glue v2

---

core/trino-main/src/main/java/io/trino/sql/ir/IrExpressions.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PreAggregateCaseAggregations.java

Also, fix mayFail implementation for Cast
```markdown
```

Use mayFail in PreAggregateCaseAggregations

---

docs/src/main/sphinx/connector/hive.md

There is a typo on hive catalog documentation. This PR fixes it.
```markdown
```

Fix typo in hive connectors documentation

---

plugin/trino-kudu/pom.xml
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduClientSession.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduColumnHandle.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduRecordSet.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/properties/RangeBoundValueSerializer.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestingKuduServer.java

Minor refactoring in Kudu

---

plugin/trino-redis/pom.xml
plugin/trino-singlestore/pom.xml
pom.xml

Dependency updates

---

.mvn/wrapper/maven-wrapper.properties
mvnw
pom.xml

Update maven-wrapper to 3.3.2

---

plugin/trino-prometheus/pom.xml
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusMetadata.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusQueryResponseParse.java

Set air.compiler.fail-warnings as true in Prometheus

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/SortFieldUtils.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Throw TrinoException for invalid Iceberg sort field

---

plugin/trino-hudi/pom.xml

Remove unused dependencies from Hudi

---

plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloMetadata.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloMetadataManager.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloSplitManager.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloTransactionHandle.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/index/ColumnCardinalityCache.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/index/IndexLookup.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/index/Indexer.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/io/AccumuloPageSink.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/io/AccumuloRecordCursor.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/io/AccumuloRecordSet.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/metadata/AccumuloTable.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/metadata/AccumuloView.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/metadata/ZooKeeperMetadataManager.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/model/AccumuloColumnConstraint.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/model/AccumuloColumnHandle.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/model/TabletSplitMetadata.java

Convert some classes to record in Accumulo

---

plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopColumnHandle.java
plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopMetadata.java
plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopPageSourceProvider.java
plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopSplitManager.java
plugin/trino-atop/src/main/java/io/trino/plugin/atop/AtopTableHandle.java

Convert some classes to record in Atop

---

.mvn/wrapper/maven-wrapper.properties

It resolves long standing issue in the resolver: https://issues.apache.org/jira/browse/MRESOLVER-521

Update Maven to 3.9.7

---

testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Unwrap short error message

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/delete/DeletionVectors.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheFileOperations.java

Verify deletion vector checksum in Delta Lake

---

core/trino-spi/src/main/java/io/trino/spi/predicate/SortedRangeSet.java
core/trino-spi/src/test/java/io/trino/spi/predicate/BenchmarkSortedRangeSet.java
core/trino-spi/src/test/java/io/trino/spi/predicate/TestSortedRangeSet.java

Close https://github.com/trinodb/trino/issues/21992

Improve performance of SortedRangeSet discrete union

---

plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSession.java

Implement streamRelationColumns in Cassandra

---

plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java

Implement streamRelationComments in Cassandra

---

plugin/trino-pinot/pom.xml
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotConnectorSmokeTest.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/PinotQueryRunner.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConnectorTest.java

Convert PinotQueryRunner to builder

---

plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/AccumuloQueryRunner.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryQueryRunner.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraQueryRunner.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/ClickHouseQueryRunner.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchQueryRunner.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/HudiQueryRunner.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/KafkaQueryRunner.java
plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/MariaDbQueryRunner.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoQueryRunner.java
plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/OpenSearchQueryRunner.java
plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestingPhoenixServer.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/SqlServerQueryRunner.java

Reverts trinodb/trino#22186 because a BDFL is upset about that change.

Revert "Enable warning/error logs from libraries in tests"

---

pom.xml

Update trino-maven-plugin to v15

---

docs/src/main/sphinx/object-storage/metastores.md

This is a follow on PR to https://github.com/trinodb/trino/pull/19818/files for updating docs and release notes to reflect the fact that now view management via Iceberg views is supported for the REST Catalog in Trino.
View management for the Iceberg REST Catalog is supported via the Iceberg view spec.
```markdown
```

Docs: Update Iceberg REST docs to reflect that view management via Iceberg views are supported

---

plugin/trino-pinot/pom.xml
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/BasePinotConnectorSmokeTest.java

Set air.compiler.fail-warnings as true in Pinot

---

.github/workflows/ci.yml
core/trino-server/src/main/provisio/trino.xml
docs/src/main/sphinx/admin.md
docs/src/main/sphinx/admin/event-listeners-openlineage.md
plugin/trino-openlineage/pom.xml
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListener.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListenerFactory.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListenerModule.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineagePlugin.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageTransport.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageTrinoFacet.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/config/OpenLineageListenerConfig.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/config/http/OpenLineageClientHttpTransportConfig.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/transport/OpenLineageConsoleTransport.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/transport/OpenLineageTransport.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/transport/http/OpenLineageHttpTransport.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/MarquezServer.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/OpenLineageListenerQueryRunner.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineageClientHttpTransportConfig.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineageEventListenerMarquezIntegration.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineageListener.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineageListenerConfig.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TrinoEventData.java
plugin/trino-openlineage/src/test/resources/marquez.yaml
pom.xml

Adds OpenLineage plugin that uses EventListener SPI to transform and send lineage information to OpenLineage compatible API.
co-authored with @takezoe 
```markdown
* Add [OpenLineage](https://openlineage.io/) event listener plugin. ({issue}`21265`)
```

feat: add OpenLineage EventListener plugin

---

docs/src/main/sphinx/release/release-449.md

Document OpenLineage plugin in 449 release note

---

plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotPlugin.java

Add TestPinotPlugin

---

plugin/trino-openlineage/pom.xml
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListener.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListenerFactory.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListenerModule.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageTrinoFacet.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/config/OpenLineageListenerConfig.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/transport/http/OpenLineageHttpTransport.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineageListenerConfig.java

OpenLineage improvements

---

plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListener.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/transport/http/OpenLineageHttpTransport.java

OpenLineage follow-up

---

docs/src/main/sphinx/installation/query-resiliency.md

Replacement for https://github.com/trinodb/trino/pull/22244

Add missing exchange prefix in docs

---

plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotPageSourceProvider.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotDataFetcher.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotGrpcDataFetcher.java

Minor fixes in Pinot connector

---

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSink.java

Add non-null check in MongoPageSink

---

docs/src/main/sphinx/connector/postgresql.md

fix postgresql connector doc typo

---

plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java

Fix expected message in TestingPinotCluster

---

plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConnectorSmokeTest.java

Inline method in TestPinotConnectorSmokeTest

---

core/trino-server/src/main/provisio/trino.xml
plugin/trino-http-server-event-listener/pom.xml
plugin/trino-http-server-event-listener/src/main/java/io/trino/plugin/httpquery/HttpServerEventListenerFactory.java
plugin/trino-http-server-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpServerListenerPlugin.java

follow up to https://github.com/trinodb/trino/pull/22158

Add http-server event listener to trino-server.tar.gz

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java

Simplify createEmptyProjection in BigQuery

---

plugin/trino-pinot/pom.xml

Remove unnecessary exclusions from Pinot

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/BaseTestTableFormats.java

Verify spark compatibility in native-fs special chars test

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java

Remove unused method from BigQueryClient

---

plugin/trino-clickhouse/pom.xml
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestingClickHouseServer.java

Set air.compiler.fail-warnings as true in ClickHouse

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplit.java

Remove unnecessary override method isRemotelyAccessible in IcebergSplit

---

plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryConnector.java

Add non-null check in MemoryConnector

---

plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiSplitManager.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/partition/HiveHudiPartitionInfo.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/partition/HudiPartitionInfoLoader.java

Using constant to represent Hudi empty partition

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/snowflake/TestIcebergSnowflakeCatalogConnectorSmokeTest.java

Fix broken testTruncateTable in Iceberg Snowflake catalog

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java

Add Iceberg query runner with TASK retries enabled

---

plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClientConfig.java

Fix format of `@DefunctConfig` values in Cassandra

---

plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiPlugin.java

Add test for HudiPlugin

---

core/trino-main/src/main/java/io/trino/server/ResourceGroupInfo.java
core/trino-main/src/test/java/io/trino/execution/resourcegroups/TestResourceGroups.java
core/trino-main/src/test/java/io/trino/server/TestQueryStateInfo.java
testing/trino-tests/src/test/java/io/trino/execution/resourcegroups/TestResourceGroupIntegration.java
testing/trino-tests/src/test/java/io/trino/execution/resourcegroups/db/TestQueuesDb.java

Convert ResourceGroupInfo to a record class

---

lib/trino-hdfs/src/main/java/io/trino/hdfs/s3/TrinoS3FileSystem.java

Include detailed error in S3 batch delete message

---

plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisRecordCursor.java

Fix description in Redis plugin

Fix description in Redis plugin

---

core/trino-main/src/main/java/io/trino/metadata/ResolvedFunction.java

Remove redundant annotation

---

client/trino-cli/pom.xml
pom.xml

Update JLine & Parquet

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcJoinPushdownUtil.java

Clean up code comments in JdbcJoinPushdownUtil

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java

Follow-up from e5f536ef
```markdown
```

Use correct isolation level in writing the commit info for DELETE

---

client/trino-client/src/main/java/io/trino/client/uri/TrinoUri.java

Fix https://github.com/trinodb/trino/issues/21026
Similar to https://github.com/trinodb/trino/pull/21203, but that PR only fixed `Authorization: Bearer`.
`Authorization: Basic` is still not working.

Retain authorization during client redirects for basic auth

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java

Check duplicated field names in Delta Lake

---

core/trino-main/pom.xml
pom.xml
testing/trino-testing/pom.xml

Brings proper support for HTTP/2 on the server side.
Part of https://github.com/trinodb/trino/issues/22271
Fixes https://github.com/trinodb/trino/issues/21793
```markdown
```

Update airlift to 249

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/SortingFileWriter.java

Add non-null check in SortingFileWriter

---

core/trino-main/src/test/java/io/trino/operator/scalar/TestJsonStringArrayExtractScalar.java

Refactor TestJsonStringArrayExtractScalar
```markdown
```

Refactor TestJsonStringArrayExtractScalar

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/IntegerNumberToDoubleCoercer.java

Optimize IntegerNumberToDoubleCoercer#applyCoercedValue to avoid repeated reading of Block values
(1) This is not user-visible or is docs only, and no release notes are required.
(1) Release notes are required. Please propose a release note for me.
(1) Release notes are required, with the following suggested text:
```markdown
```

Optimize IntegerNumberToDoubleCoercer#applyCoercedValue to avoid repeated reading of Block values

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ConstantPopulatingPageSource.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergBucketFunction.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergInputInfo.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergParquetColumnIOConverter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTransforms.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/DeleteManager.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergBucketing.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergInputInfo.java

Convert some classes to record in Iceberg

---

core/trino-main/src/main/java/io/trino/server/DisableHttpCache.java
core/trino-main/src/main/java/io/trino/server/DisableHttpCacheDynamicFeature.java
core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
core/trino-main/src/main/java/io/trino/server/ui/UiQueryResource.java

This ensures that any sensitive information is not cached in the browser
Alternative to https://github.com/trinodb/trino/pull/22480
```markdown
```

Disable caching of /ui responses

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java

Add clarifying javadoc

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java

Small fixes

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/IcebergRestCatalogConfig.java

Move getter and setter for consistency with fields. 

Fix method order in IcebergRestCatalogConfig

---

plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Add test cases for integer type changes

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java

In case table already exists throw TrinoException with clear error type.
```  "type": "org.apache.iceberg.exceptions.AlreadyExistsException",
"message": "Requirement failed: table already exists: xxxxxx in warehouse xxxxxxxx",
"stack": [
"org.apache.iceberg.rest.ErrorHandlers$TableErrorHandler.accept(ErrorHandlers.java:115)",
"org.apache.iceberg.rest.ErrorHandlers$TableErrorHandler.accept(ErrorHandlers.java:102)",
"org.apache.iceberg.rest.HTTPClient.throwFailure(HTTPClient.java:201)",
"org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:313)",
"org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:252)",
"org.apache.iceberg.rest.HTTPClient.post(HTTPClient.java:358)",
"org.apache.iceberg.rest.RESTClient.post(RESTClient.java:112)", …
```

Throw TrinoException when creating Iceberg table that already exists

---

docs/src/main/sphinx/connector/iceberg.md

Adding documentation for: https://github.com/trinodb/trino/pull/20959
```markdown
```

Add documentation for Iceberg incremental MV refresh

---

core/trino-main/src/main/java/io/trino/execution/AddColumnTask.java
core/trino-main/src/test/java/io/trino/execution/BaseDataDefinitionTaskTest.java
core/trino-main/src/test/java/io/trino/execution/TestCreateAndAlterTableColumnTypeCoercion.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Fixes #19708
```markdown
* TBD. ({issue}`19708`)
```

Support type coercion when adding new columns

---

plugin/trino-pinot/pom.xml
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/PinotQueryRunner.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/PinotTpchTables.java

Wait until TPCH tables become visible in Pinot

---

client/trino-client/src/main/java/io/trino/client/FailureInfo.java

Add toString method to easier get information about failues.
```markdown
```

Add toString method to FailureInfo

---

plugin/trino-memory/src/main/java/io/trino/plugin/memory/ColumnInfo.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryConnector.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java

```markdown
* Add support for `NOT NULL` constraint. ({issue}`22601`)
```

Add support for not null constraint in Memory connector

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/v1/converter/GlueToTrinoConverter.java

Report exception in GlueToTrinoConverter.convertType failure

---

pom.xml

Update google cloud sdk

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/RefsTable.java

Extend BaseSystemTable in Iceberg refs table

---

plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileColumnHandle.java
plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileMetadata.java
plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileRecordCursor.java
plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileRecordSet.java
plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileTableHandle.java
plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileTables.java
plugin/trino-local-file/src/test/java/io/trino/plugin/localfile/TestLocalFilePlugin.java
plugin/trino-local-file/src/test/java/io/trino/plugin/localfile/TestLocalFileRecordSet.java

Convert some classes to record in Local File

---

plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpEventListener.java
plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpEventListenerConfig.java
plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpEventListenerPlugin.java
plugin/trino-http-server-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpServerEventListener.java
plugin/trino-http-server-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpServerListenerPlugin.java
plugin/trino-mysql-event-listener/src/test/java/io/trino/plugin/eventlistener/mysql/TestMysqlEventListener.java
plugin/trino-mysql-event-listener/src/test/java/io/trino/plugin/eventlistener/mysql/TestMysqlEventListenerConfig.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineagePlugin.java

Minor fixes in event listeners tests

---

docs/src/main/sphinx/connector/blackhole.md
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleTableHandle.java
plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/TestBlackHoleSmoke.java
testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
testing/trino-tests/src/test/java/io/trino/security/TestingSystemSecurityMetadata.java

```markdown
* Add support for adding, dropping and renaming columns. ({issue}`issuenumber`)
```

Add support for adding, dropping and renaming columns in Black Hole connector

---

docs/src/main/sphinx/connector/memory.md
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryColumnHandle.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPageSourceProvider.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPagesStore.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryPagesStore.java

```markdown
* Add support for adding new columns. ({issue}`22610`)
```

Add support for adding new columns in Memory connector

---

plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java

Simplify onRemoteDatabase in PostgreSQL

---

docs/src/main/sphinx/sql/create-view.md
docs/src/main/sphinx/sql/show-tables.md

- And related other sections in the SQL docs
Only question .. does it also show materialized views? What about the storage tables though? 
* https://github.com/trinodb/trino/issues/2999
* https://github.com/trinodb/trino/pull/22638

Improve SHOW TABLES docs

---

core/trino-main/bin/check_webui.sh

Fix file name in check_webui.sh

---

core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorMetadata.java

Remove deprecated method finishMerge from spi

---

core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java

Remove EXECUTE from privilegeOrRole

---

core/trino-main/src/main/java/io/trino/exchange/ExchangeDataSource.java
core/trino-main/src/main/java/io/trino/exchange/LazyExchangeDataSource.java
core/trino-main/src/main/java/io/trino/exchange/SpoolingExchangeDataSource.java
core/trino-main/src/main/java/io/trino/operator/ExchangeOperator.java
core/trino-spi/src/main/java/io/trino/spi/exchange/ExchangeSource.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeSource.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeStorage.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/MetricsBuilder.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/azure/AzureBlobFileSystemExchangeStorage.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/local/LocalFileSystemExchangeStorage.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorage.java
plugin/trino-exchange-hdfs/src/main/java/io/trino/plugin/exchange/hdfs/HadoopFileSystemExchangeStorage.java

Expose ExchangeSource metrics in query json

---

docs/src/main/sphinx/connector/sql-update-limitation.fragment
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Test UPDATE statement with multiple conditions

---

core/trino-main/src/main/resources/oauth2/logout.html

Replace Presto with Trino in OAuth logout page

---

core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
core/trino-main/src/main/java/io/trino/sql/relational/SqlToRowExpressionTranslator.java
core/trino-main/src/test/java/io/trino/operator/BenchmarkGroupByHash.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/rcfile/RcFilePageSource.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java
pom.xml

Enable ModifiedButNotUsed in error-prone

---

docs/src/main/sphinx/connector/singlestore.md

* Removed language and country hard codes in links.
```markdown
```

Edit links on SingleStore docs page

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/CachingDirectoryLister.java

Migrate list of table prefixes to Predicate in CachingDirectoryListener

---

core/trino-main/src/test/java/io/trino/server/testing/TestTestingTrinoServer.java

Follow-up to https://github.com/trinodb/trino/pull/22700 with @ebyhr's suggestions applied.
```markdown
```

Refactor TestTestingTrinoServer

---

pom.xml

Update Iceberg to 1.6.0

---

docs/src/main/sphinx/client/cli.md
docs/src/main/sphinx/client/jdbc.md

- CLI and JDBC driver
Feature is shipping in 453
Follow up to #22703

Add docs for sql path parameter for clients

---

core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java

Extracted from https://github.com/trinodb/trino/pull/22830

Rename pageSourceProvider to pageSourceManager

---

docs/src/main/sphinx/connector/iceberg.md

Follow up to #22540
Also fyi @okayhooni 

Improve Iceberg partition filter docs

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/SyncPartitionMetadataProcedure.java

On top of https://github.com/trinodb/trino/pull/22791
Skip building of canonical partition name when `case_sensitive = true`
Fixes https://github.com/trinodb/trino/issues/22756

Hive : Skip build of canonical partition name with case sensitive in sync_partitions_metadata

---

core/trino-main/src/main/resources/webapp/src/components/LivePlan.jsx
core/trino-main/src/main/resources/webapp/src/components/PageTitle.jsx
core/trino-main/src/main/resources/webapp/src/package-lock.json
core/trino-main/src/main/resources/webapp/src/package.json
core/trino-main/src/main/resources/webapp/src/utils.js
core/trino-main/src/main/resources/webapp/src/yarn.lock

0.148.0 is a first version supporting aarch64 on Linux
```markdown
```

Update flow to 0.241.0 to support aarch64 on linux

---

docs/src/main/sphinx/release/release-453.md

One follow up for https://trinodb.slack.com/archives/C07ABNN828M/p1721943087420349 

Add SPI change to 453 release notes

---

lib/trino-memory-context/src/main/java/io/trino/memory/context/CoarseGrainLocalMemoryContext.java

Follows up from https://github.com/trinodb/trino/pull/22841 

Add missing @GuardedBy annotation

---

plugin/trino-elasticsearch/pom.xml
pom.xml

Updates, updates, updates

---

pom.xml

Update airlift to 255

---

pom.xml

Update airlift to 256

---

plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/AvroSchemaConverter.java
pom.xml

Update avro & antlr

---

plugin/trino-exasol/pom.xml
plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java

Update airbase & airlift + several other dependencies

---

plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java

Use rewriter to reenable join pushdowns
This was probably missed in https://github.com/trinodb/trino/commit/91a29a7d8d2ddb1d1e7ba9bb529160d06f4542b5#diff-e7f2966e1e2e070e8643b5563c7ba62f7dc0652f76fbf446ef389b75ef4883fb which now is causing multiple test failures in _io.trino.plugin.redshift.TestRedshiftConnectorTest_
```markdown
```

Add missing predicate rewrites for Redshift

---

core/trino-main/src/main/java/io/trino/security/AccessControlManager.java

For SystemAccessControl loaded by files from `config.properties` SecretsResolver wasn't mapped - This was missed in this PR - https://github.com/trinodb/trino/pull/22633
```markdown
```

Use SecretsResolver for SystemAccessControl

---

core/trino-web-ui/pom.xml
core/trino-web-ui/src/main/resources/webapp/src/.npmrc
core/trino-web-ui/src/main/resources/webapp/src/.prettierrc.json
core/trino-web-ui/src/main/resources/webapp/src/components/ClusterHUD.jsx
core/trino-web-ui/src/main/resources/webapp/src/components/LivePlan.jsx
core/trino-web-ui/src/main/resources/webapp/src/components/PageTitle.jsx
core/trino-web-ui/src/main/resources/webapp/src/components/QueryDetail.jsx
core/trino-web-ui/src/main/resources/webapp/src/components/QueryHeader.jsx
core/trino-web-ui/src/main/resources/webapp/src/components/QueryList.jsx
core/trino-web-ui/src/main/resources/webapp/src/components/ReferenceDetail.jsx
core/trino-web-ui/src/main/resources/webapp/src/components/StageDetail.jsx
core/trino-web-ui/src/main/resources/webapp/src/components/WorkerList.jsx
core/trino-web-ui/src/main/resources/webapp/src/components/WorkerStatus.jsx
core/trino-web-ui/src/main/resources/webapp/src/components/WorkerThreadList.jsx
core/trino-web-ui/src/main/resources/webapp/src/package-lock.json
core/trino-web-ui/src/main/resources/webapp/src/package.json
core/trino-web-ui/src/main/resources/webapp/src/utils.js
core/trino-web-ui/src/main/resources/webapp/src/webpack.config.js
core/trino-web-ui/src/main/resources/webapp/src/yarn.lock

Add prettier to web-ui

---

core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
core/trino-spi/src/main/java/io/trino/spi/eventlistener/StageTaskStatistics.java

This allows tracking delays in split generation by coordinator

Add StageTaskStatistics#getSplitDistribution

---

plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotMetadata.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotPageSourceProvider.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotSplitManager.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotTableHandle.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotQueryBuilder.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/MockPinotClient.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestDynamicTable.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotMetadata.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotQueryBase.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotSplitManager.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotTableHandle.java

Convert PinotTableHandle to record

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java

Increase timeout for diagnostics loggin of stalled scheduler

---

core/trino-main/src/main/java/io/trino/sql/analyzer/Analyzer.java

Add copyOf check in Analyzer

---

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcFlushMetadataCacheProcedure.java
pom.xml

Except for H2 which fixes some regressions other updates are minor

Various small updates

---

docs/src/main/sphinx/release/release-451.md

It's always Jun for other June release notes, not June.

Abbreviate 451 date for consistency

---

plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListener.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListenerConfig.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListenerModule.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/transport/console/OpenLineageConsoleTransport.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/transport/http/OpenLineageHttpTransport.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/transport/http/OpenLineageHttpTransportConfig.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineageListenerConfig.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/http/TestOpenLineageHttpTransportConfig.java

Fix package and file name in OpenLineage

---

.github/config/labeler-config.yml

Fix labeler config for Web UI module

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/ExponentialGrowthPartitionMemoryEstimator.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/NoMemoryPartitionMemoryEstimator.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/PartitionMemoryEstimator.java
core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestExponentialGrowthPartitionMemoryEstimator.java
core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestNoMemoryAwarePartitionMemoryEstimator.java

Allocate full node for task on last retry due to lack of memory

---

core/trino-main/src/main/java/io/trino/operator/aggregation/LongApproximateMostFrequentStateFactory.java
core/trino-main/src/main/java/io/trino/operator/aggregation/NumericHistogramStateFactory.java
core/trino-main/src/main/java/io/trino/operator/aggregation/StringApproximateMostFrequentStateFactory.java
core/trino-main/src/main/java/io/trino/type/setdigest/SetDigestStateFactory.java
lib/trino-array/src/main/java/io/trino/array/BlockBigArray.java
lib/trino-array/src/main/java/io/trino/array/ObjectBigArray.java
lib/trino-array/src/main/java/io/trino/array/SliceBigArray.java
lib/trino-array/src/main/java/io/trino/array/SqlMapBigArray.java
lib/trino-array/src/main/java/io/trino/array/SqlRowBigArray.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/SpatialPartitioningStateFactory.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/aggregation/GeometryStateFactory.java

Adds `ObjectBigArray#getAndSet(index, value)` and updates various aggregation states to use that method instead of separate get / set pairs.

Add ObjectBigArray#getAndSet

---

docs/src/main/sphinx/connector/delta-lake.md

- Delta Lake connector docs only
- Remove future usage
- Remove unnecessary double quote
- Add sql highlighting to code blocks
Follow up to https://github.com/trinodb/trino/pull/23057

Improve grammar and style

---

core/trino-main/src/main/java/io/trino/execution/executor/dedicated/TaskEntry.java
core/trino-main/src/main/java/io/trino/execution/executor/dedicated/ThreadPerDriverTaskExecutor.java
core/trino-main/src/main/java/io/trino/execution/executor/scheduler/FairScheduler.java
core/trino-main/src/main/java/io/trino/execution/executor/scheduler/Reservation.java
core/trino-main/src/main/java/io/trino/execution/executor/scheduler/SchedulingQueue.java
core/trino-main/src/main/java/io/trino/execution/executor/scheduler/TaskControl.java

Add thread-per-driver executor diagnostics

---

.mvn/wrapper/maven-wrapper.properties

Update Maven to 3.9.9

---

docs/src/main/sphinx/object-storage/legacy-azure.md
docs/src/main/sphinx/object-storage/legacy-gcs.md
docs/src/main/sphinx/object-storage/legacy-s3.md

* Added migration guides for migrating from legacy to native file systems.
* Azure, S3, and Google

Add legacy to native migration guides

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/FilesTable.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

Based on #16232 with review comments applied - avoid reflection and use column position to read data. I preserved the commit author.
Fixes #16233
```markdown
* Fix `$files` table not showing delete files for Iceberg v2 format. ({issue}`[16233]`)
```

List delete files in Iceberg's $files metadata table

---

lib/trino-filesystem-azure/pom.xml
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystem.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java
pom.xml

Contains workaround for https://github.com/Azure/azure-sdk-for-java/issues/41393

Update Azure SDK to 1.2.27

---

pom.xml

Update google cloud SDK & parquet library

---

pom.xml

Relates to https://github.com/trinodb/trino/issues/21945

Add caution for MySQL library upgrade

---

core/trino-main/src/main/java/io/trino/json/PathEvaluationVisitor.java
core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
core/trino-main/src/main/java/io/trino/sql/planner/TranslationMap.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PlanNodeDecorrelator.java
core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionTreeRewriter.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
plugin/trino-tpch/src/test/java/io/trino/plugin/tpch/EstimateAssertion.java

Remove redundant cast

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDatabricksCreateTableCompatibility.java

Fix broken test of SHOW CREATE TABLE in Databricks

---

plugin/trino-openlineage/pom.xml
plugin/trino-redshift/pom.xml
pom.xml

```markdown
```
Fixes https://github.com/trinodb/trino/issues/23187

Update project dependencies [August 30th edition]

---

pom.xml

Update airbase to 171 and airlift to 262

---

plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/TestBlackHoleMetadata.java
plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/TestBlackHoleSmoke.java

```markdown
* Add support for replacing tables. ({issue}`issuenumber`)
```

Add support for replacing tables in BlackHole

---

.github/workflows/ci.yml

Don't run CI for markdown file changes

---

core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaColumnHandle.java
core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaMetadata.java
core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaPageSource.java
core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaTableHandle.java
core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaTransactionHandle.java
core/trino-main/src/main/java/io/trino/connector/system/GlobalSystemTransactionHandle.java
core/trino-main/src/main/java/io/trino/connector/system/SystemColumnHandle.java
core/trino-main/src/main/java/io/trino/connector/system/SystemPageSourceProvider.java
core/trino-main/src/main/java/io/trino/connector/system/SystemSplitManager.java
core/trino-main/src/main/java/io/trino/connector/system/SystemTableHandle.java
core/trino-main/src/main/java/io/trino/connector/system/SystemTablesMetadata.java
core/trino-main/src/test/java/io/trino/metadata/TestInformationSchemaMetadata.java

Convert `information_schema` and `system` connector classes to record 

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergColumnHandle.java

Fix wrong assertion in TestIcebergColumnHandle

---

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/projection/ProjectFunctionRewriter.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/projection/ProjectFunctionRule.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/rule/RewriteDotProductFunction.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/rule/RewriteStringReverseFunction.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/rule/RewriteVectorDistanceFunction.java

A table handle is helpful for changing the pushdown behavior based on the table attributes

Add table handle to ProjectFunctionRewriter.rewrite

---

plugin/trino-kafka/pom.xml
pom.xml

Batch dependencies update [September 1st edition]

---

plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMergeTableHandle.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixPageSinkProvider.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixPageSourceProvider.java

Add non-null checks for Phoenix

---

plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java

It's been fixed by https://github.com/trinodb/trino/pull/19246
```markdown
```

Remove unnecessary override test testMergeLarge in Phoenix

---

docs/src/main/sphinx/admin/fault-tolerant-execution.md
docs/src/main/sphinx/optimizer/adaptive-plan-optimizations.md

Docs for https://github.com/trinodb/trino/pull/23046

Add doc for AdaptiveReorderPartitionedJoin

---

core/trino-main/src/main/java/io/trino/metadata/MetadataUtil.java
core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
core/trino-parser/src/main/java/io/trino/sql/tree/MeasureDefinition.java
core/trino-parser/src/main/java/io/trino/sql/tree/Merge.java
core/trino-parser/src/main/java/io/trino/sql/tree/OneOrMoreQuantifier.java
core/trino-parser/src/main/java/io/trino/sql/tree/PatternAlternation.java
core/trino-parser/src/main/java/io/trino/sql/tree/PatternConcatenation.java
core/trino-parser/src/main/java/io/trino/sql/tree/PatternPermutation.java
core/trino-parser/src/main/java/io/trino/sql/tree/PatternRecognitionRelation.java
core/trino-parser/src/main/java/io/trino/sql/tree/PatternSearchMode.java
core/trino-parser/src/main/java/io/trino/sql/tree/PatternVariable.java
core/trino-parser/src/main/java/io/trino/sql/tree/PrincipalSpecification.java
core/trino-parser/src/main/java/io/trino/sql/tree/ProcessingMode.java
core/trino-parser/src/main/java/io/trino/sql/tree/QuantifiedPattern.java
core/trino-parser/src/main/java/io/trino/sql/tree/RangeQuantifier.java
core/trino-parser/src/main/java/io/trino/sql/tree/ResetSessionAuthorization.java
core/trino-parser/src/main/java/io/trino/sql/tree/SetSchemaAuthorization.java
core/trino-parser/src/main/java/io/trino/sql/tree/ShowCreate.java
core/trino-parser/src/main/java/io/trino/sql/tree/ShowGrants.java
core/trino-parser/src/main/java/io/trino/sql/tree/ShowRoleGrants.java
core/trino-parser/src/main/java/io/trino/sql/tree/SubsetDefinition.java
core/trino-parser/src/main/java/io/trino/sql/tree/TruncateTable.java
core/trino-parser/src/main/java/io/trino/sql/tree/Update.java
core/trino-parser/src/main/java/io/trino/sql/tree/Use.java
core/trino-parser/src/main/java/io/trino/sql/tree/VariableDefinition.java
core/trino-parser/src/main/java/io/trino/sql/tree/ZeroOrMoreQuantifier.java
core/trino-parser/src/main/java/io/trino/sql/tree/ZeroOrOneQuantifier.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java

Remove redundant constructors in a parser

---

core/trino-main/src/test/java/io/trino/sql/planner/TestInsert.java
core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestLimitMaxWriterNodesCount.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorMetadata.java

Don't use deprecated constructor of ConnectorTableLayout

---

core/trino-parser/src/main/java/io/trino/sql/tree/PrincipalSpecification.java

Static import Type in PrincipalSpecification

---

core/trino-main/src/main/java/io/trino/metadata/MetadataUtil.java
core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
core/trino-main/src/test/java/io/trino/execution/TestCreateSchemaTask.java
core/trino-main/src/test/java/io/trino/execution/TestDropSchemaTask.java
core/trino-main/src/test/java/io/trino/execution/TestPrepareTask.java
core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
core/trino-parser/src/main/java/io/trino/sql/tree/CreateSchema.java
core/trino-parser/src/main/java/io/trino/sql/tree/Deny.java
core/trino-parser/src/main/java/io/trino/sql/tree/DropSchema.java
core/trino-parser/src/main/java/io/trino/sql/tree/Execute.java
core/trino-parser/src/main/java/io/trino/sql/tree/GrantorSpecification.java
core/trino-parser/src/main/java/io/trino/sql/tree/LanguageCharacteristic.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParserRoutines.java

Remove redundant constructors and convert GrantorSpecification to record

---

pom.xml

Add definition of trino-kafka-event-listener in root pom

---

docs/src/main/sphinx/admin/event-listeners-openlineage.md

This PR fixes a couple typos in the `event-listener-openlineage.md` page. 
```markdown
```

Improve event-listener-openlineage documentation

---

core/trino-web-ui/src/main/resources/webapp/src/embedded_plan.jsx
core/trino-web-ui/src/main/resources/webapp/src/index.jsx
core/trino-web-ui/src/main/resources/webapp/src/package.json
core/trino-web-ui/src/main/resources/webapp/src/plan.jsx
core/trino-web-ui/src/main/resources/webapp/src/query.jsx
core/trino-web-ui/src/main/resources/webapp/src/references.jsx
core/trino-web-ui/src/main/resources/webapp/src/stage.jsx
core/trino-web-ui/src/main/resources/webapp/src/timeline.jsx
core/trino-web-ui/src/main/resources/webapp/src/worker.jsx
core/trino-web-ui/src/main/resources/webapp/src/workers.jsx

Trino web ui source formatting fixes

---

core/trino-main/src/main/java/io/trino/sql/gen/OrderingCompiler.java

Replace https://github.com/trinodb/trino/pull/22789 since we dont have a CLA and this is a trivial change anyway.

Fix log message data for sortOrders

---

plugin/trino-mongodb/pom.xml
plugin/trino-openlineage/pom.xml
pom.xml

Batch updates [sep 5th]

---

docs/src/main/sphinx/connector/hive.md

Similar to https://github.com/trinodb/trino/blob/984755f736f600b1fd4370b42617f07164b1bbfb/docs/src/main/sphinx/connector/delta-lake.md?plain=1#L177-L179

Document `hive.parquet.time-zone` configuration setting

---

docs/src/main/sphinx/admin/fault-tolerant-execution.md
docs/src/main/sphinx/admin/properties-exchange.md
docs/src/main/sphinx/admin/properties-general.md
docs/src/main/sphinx/installation/deployment.md
docs/src/main/sphinx/object-storage/file-formats.md

* Necessary since we upgraded to 3.0
* Docs for fallback switch in case there are issues
Ideally we should get this merged for 456 .. if so I will rebase release notes PR and link to the section.

Add docs for file compression config

---

pom.xml
testing/trino-testing/pom.xml

Update airlift to 265

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentUp.java

Debug startup of trino containers without timeout

---

docs/src/main/sphinx/admin/fault-tolerant-execution.md
docs/src/main/sphinx/admin/properties-exchange.md

* Edit `compression-codec` exchange property default -> `LZ4`.
* Edit compression-codec mention and add a link on FTE docs page. 
```markdown
```

Edit docs for compression-codec exchange property

---

docs/src/main/sphinx/admin/properties-http-client.md

Doc entries for Http Proxy authentication

---

core/trino-main/src/main/java/io/trino/server/protocol/ProtocolUtil.java
core/trino-main/src/main/java/io/trino/sql/analyzer/TypeSignatureTranslator.java
core/trino-parser/src/main/java/io/trino/sql/tree/DataType.java
core/trino-parser/src/main/java/io/trino/sql/tree/DateTimeDataType.java
core/trino-parser/src/main/java/io/trino/sql/tree/GenericDataType.java
core/trino-parser/src/main/java/io/trino/sql/tree/IntervalDayTimeDataType.java
core/trino-parser/src/main/java/io/trino/sql/tree/RowDataType.java

Seal AST DataType classes and use pattern matching

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogAccessOperations.java

Due to changes from https://github.com/trinodb/trino/commit/970405d754eb053b4ae509c18d045a201207891e
```markdown
```

Fix failures in TestIcebergGlueCatalogAccessOperations

---

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java

It seems that is has changed server-side and it's causing master to fail

Fix expected error message

---

lib/trino-filesystem/src/main/java/io/trino/filesystem/TrinoFileSystem.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalFileIterator.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/memory/MemoryFileSystem.java
lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java
lib/trino-hdfs/src/test/java/io/trino/filesystem/hdfs/TestHdfsFileSystemLocal.java

Test if file listings are lexicographically sorted

---

plugin/trino-google-sheets/pom.xml
pom.xml

Batch update dependencies

---

docs/src/main/sphinx/admin.md
docs/src/main/sphinx/admin/event-listeners-kafka.md

Just trying to get minimal docs off the ground.. 
fyi @marton-bod and @sopel39 .. I am just looking at the code and such. Any examples and so would be appreciated .. also review once the PR is in a better shape.
* Filling in on missed work from https://github.com/trinodb/trino/pull/22888
* Fixes https://github.com/trinodb/trino/issues/23092
* Also covers #23066

Add docs for Kafka event listener

---

docs/src/main/sphinx/release/release-457.md

Remove a duplicated entry from 457 release notes

---

core/trino-main/src/main/java/io/trino/server/ExternalUriInfo.java
core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
core/trino-web-ui/src/main/resources/webapp/login.html

Fix minor bugs in X-Forwarded-Prefix handling.
Change UI login form action to be relative so it works with path prefix.
Fixes #23028
NOTE: X-Forwarded-Prefix is not a complete feature yet, and does not work with any clients yet.
```markdown
```

Fix X-Forwarded-Prefix 

---

pom.xml

Update to provisio 1.1.1

---

lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java

Extend TTL for presigned URLs in tests

---

core/trino-main/src/test/java/io/trino/execution/TestStartTransactionTask.java
core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
core/trino-parser/src/main/java/io/trino/sql/tree/Lateral.java
core/trino-parser/src/main/java/io/trino/sql/tree/ShowCatalogs.java
core/trino-parser/src/main/java/io/trino/sql/tree/ShowColumns.java
core/trino-parser/src/main/java/io/trino/sql/tree/ShowFunctions.java
core/trino-parser/src/main/java/io/trino/sql/tree/ShowRoles.java
core/trino-parser/src/main/java/io/trino/sql/tree/ShowSchemas.java
core/trino-parser/src/main/java/io/trino/sql/tree/ShowSession.java
core/trino-parser/src/main/java/io/trino/sql/tree/ShowTables.java
core/trino-parser/src/main/java/io/trino/sql/tree/StartTransaction.java
core/trino-parser/src/test/java/io/trino/sql/TestSqlFormatter.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java

Remove redundant constructors from parser

---

plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/DatabaseMetadataModule.java

The H2 version was updated and merge conflict occurred.
Fixes https://github.com/trinodb/trino/issues/23396
```markdown
```

Remove retry from H2 connection factory

---

lib/trino-filesystem-azure/pom.xml
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuth.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthAccessKey.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystem.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java

Generate pre-signed URIs for Azure

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/TestFileSystemSegmentPruner.java

Fix logical merge conflict in s3 filesystem

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3InputStream.java

In situations like a connection being open for too long without reading any data the underlying InputStream can be closed. This attempts to reconnect the InputStream before failing the read.
This has been observed when reading Iceberg manifests after the 1.6.1 release, the Avro file reader can be held open during `planFiles` calls if the read records haven't been consumed yet.
https://github.com/apache/iceberg/pull/10691

Retry S3InputStream operations by reconnecting the underlying stream

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveGlueMetadataListing.java

Fix failing test related to filesystem migration

---

plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java

Minor cleanup in PostgreSqlClient

---

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuth.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthAccessKey.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthDefault.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthOauth.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystem.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java

Generate SAS token for OAuth2 Azure

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java

Extend catch all exception scope

---

core/trino-server-rpm/pom.xml
pom.xml

Update 2 maven plugins

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeSqlserver.java

This fixes the startup failure while running on Ubuntu 22
```markdown
```

Update SQL Server docker to 2017-latest

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-458.md

Assemble the release notes for the upcoming Trino 458 release.
* #23329 ✅ rn ✅ docs
* #23332 ✅ rn ✅ docs
* #23335 ✅ rn ✅ docs
* #23312 ✅ rn ✅ docs
* #23337 ✅ rn ✅ docs
* #23336 ✅ rn ✅ docs
* #23330 ✅ rn ✅ docs
* #23340 ✅ rn ✅ docs
* #23158 ✅ rn ✅ docs
* #23341 ✅ rn ✅ docs
* #23286 ✅ rn ✅ docs
* #23325 ✅ rn ✅ docs
* #23331 ✅ rn ✅ docs
* #23320 ✅ rn ✅ docs
* #23326 ✅ rn ✅ docs
* #23351 ✅ rn ✅ docs
* #23087 ✅ rn ✅ docs
* #23323 ✅ rn ✅ docs
* #23353 ✅ rn ✅ docs
* #23342 ✅ rn ✅ docs
* #23327 ✅ rn ✅ docs
* #23358 ✅ rn ✅ docs
* #23360 ✅ rn ✅ …

Add Trino 458 release notes

---

plugin/trino-kafka/pom.xml
plugin/trino-opensearch/pom.xml
pom.xml

 Batch update dependencies

---

plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/FileSystemSpoolingManager.java

Throw if the direct location is used with encryption

---

.github/actions/setup/action.yml
.github/workflows/ci.yml
core/docker/default/etc/jvm.config
core/jdk/current
core/jdk/temurin/jdk-23+37/amd64
core/jdk/temurin/jdk-23+37/arm64
core/jdk/temurin/jdk-23+37/ppc64le
core/trino-server-rpm/src/main/resources/dist/config/jvm.config
core/trino-server-rpm/src/main/rpm/preinstall
core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/TestRun.java
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-all/jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-ignite/jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-snowflake/jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-master-jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-worker-jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/jvm.config

Part of #21316
use same wording as for the equiv 22 update.. @mosabua will take care of that

Update JDK to 23 in the runtime

---

docs/src/main/sphinx/connector/snowflake.md

See commit messages. Added a bunch of reviewers who have more context and for visibility
Follow up to https://github.com/trinodb/trino/pull/23463

Update Snowflake connector docs

---

.github/workflows/ci.yml

Test compatibility with JDK 24-ea

---

plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraTypeMapping.java

Hopefully fixes https://github.com/trinodb/trino/issues/21032

Increase cassandra.client.read-timeout in Cassandra test

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RollbackToSnapshotProcedure.java

Other procedures exist in `io.trino.plugin.iceberg.procedure`

Move RollbackToSnapshotProcedure package

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/EvaluateEmptyIntersect.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/EvaluateZeroSample.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushFilterThroughBoolOrAggregation.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushFilterThroughCountAggregation.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateThroughProjectIntoRowNumber.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateThroughProjectIntoWindow.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushdownFilterIntoRowNumber.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushdownFilterIntoWindow.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveEmptyExceptBranches.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveEmptyUnionBranches.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantDistinctLimit.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantJoin.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantLimit.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantOffset.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantPredicateAboveTableScan.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantSort.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantTableFunction.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantTopN.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantWindow.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveTrivialFilters.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/LimitPushDown.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/WindowFilterPushDown.java
core/trino-main/src/main/java/io/trino/sql/planner/plan/ValuesNode.java
core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestEliminateCrossJoins.java
core/trino-main/src/test/java/io/trino/sql/planner/plan/TestWindowNode.java
core/trino-main/src/test/java/io/trino/sql/planner/sanity/TestVerifyOnlyOneOutputNode.java

```markdown
* Limit number of values node rows in explain plan. ({issue}`23519`)
```

Limit number of values node rows in explain plan

---

client/trino-cli/pom.xml
plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
pom.xml
testing/trino-benchto-benchmarks/pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java

Batch updates

---

core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java

Migrate assertExpression to ParserAssert.expression

---

pom.xml

Frontend updates

---

lib/trino-filesystem-gcs/pom.xml
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystem.java
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsInput.java
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsInputFile.java
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsInputStream.java
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsOutputFile.java
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsUtils.java
lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/AbstractTestGcsFileSystem.java
lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystem.java
lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemWithEncryption.java

Add SSE-C support to GCS file system

---

lib/trino-filesystem-azure/pom.xml
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystem.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureUtils.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/AbstractTestAzureFileSystem.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemGen2FlatWithEncryption.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemGen2HierarchicalWithEncryption.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemOAuthGen2FlatWithEncryption.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemOAuthGen2HierarchicalWithEncryption.java
lib/trino-filesystem/src/test/java/io/trino/filesystem/AbstractTestTrinoFileSystem.java

Add support for server-side encryption with customer key to Azure

---

testing/trino-server-dev/etc/catalog/delta.properties
testing/trino-server-dev/etc/catalog/hive.properties
testing/trino-server-dev/etc/catalog/iceberg.properties

Fix DevelopmentServer config for delta/hive/iceberg

---

client/trino-cli/src/test/java/io/trino/cli/TestQueryRunner.java
client/trino-client/src/main/java/io/trino/client/ClientSession.java
client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
client/trino-client/src/main/java/io/trino/client/uri/TrinoUri.java
client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestingTrinoClient.java
testing/trino-tests/src/test/java/io/trino/execution/TestFinalQueryInfo.java
testing/trino-tests/src/test/java/io/trino/execution/TestSetSessionAuthorization.java
testing/trino-tests/src/test/java/io/trino/execution/TestUserImpersonationAccessControl.java

Cleanup ClientSession builder

---

pom.xml

Update airbase to 180 and airlift to 269

---

plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/SnowflakeQueryRunner.java
plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestingSnowflakeServer.java

- Make a snowflake role optional in test since a snowflake role isn't a mandatory parameter in JDBC connection
() Release notes are required. Please propose a release note for me.
```markdown
```

Make a snowflake role optional in test

---

plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/expression/RewriteStringComparison.java
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/expression/RewriteStringIn.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java

- https://github.com/trinodb/trino/issues/7100
- https://github.com/trinodb/trino/pull/23460
- https://github.com/trinodb/trino/pull/22921
- https://github.com/trinodb/trino/pull/23496
- https://github.com/trinodb/trino/pull/23516
- https://github.com/trinodb/trino/pull/23455
- https://github.com/trinodb/trino/pull/23558
- https://github.com/trinodb/trino/pull/23581
- https://github.com/trinodb/trino/pull/23591
- https://github.com/trinodb/trino/pull/23459
```markdown
* Improve varchar IN pushdown for complex expression ({issue}`23581`)
```

Improve ClickHouse varchar IN pushdown for complex expression

---

docs/src/main/sphinx/release/release-459.md

Fix a link in 459 release notes

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java

Fix flaky tests in TestDeltaLakeFileOperations

---

core/trino-main/pom.xml
plugin/trino-google-sheets/pom.xml
plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
plugin/trino-mongodb/pom.xml
plugin/trino-redis/pom.xml
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java

Batch dependency updates

---

pom.xml

Update airbase to 182 and airlift to 271

---

pom.xml

Update azure-sdk to 1.2.28

---

lib/trino-filesystem-alluxio/src/test/java/io/trino/filesystem/alluxio/TestAlluxioFileSystem.java

Extend wait time of Alluxio master in tests

---

lib/trino-filesystem-alluxio/src/test/java/io/trino/filesystem/alluxio/TestAlluxioFileSystem.java

Fix master error-prone and checkstyle violations

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java

Add Nessie query runner in Iceberg

---

plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraServer.java
plugin/trino-pinot/pom.xml
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java
pom.xml

Batch update dependencies [1st of october edition]

---

core/docker/build.sh

Allow skipping docker image tests

---

.github/bin/free-disk-space.sh

This should make the logs of the setup action more readable.

Group disk cleanup output

---

core/trino-spi/src/main/java/io/trino/spi/connector/WriterScalingOptions.java
pom.xml
testing/trino-testing/pom.xml

Update airbase to 184 and airlift to 272

---

.github/pull_request_template.md

Formatted, reworded a bit, added link to process on Trino website, changed to use "core-dev" and fixed release notes suggestion.

Improve pull request description template

---

plugin/trino-opensearch/pom.xml
pom.xml

Update Netty, AWS SDK v2 and OpenSearch

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java

Relates to #23620
I didn't disable the table creation for testing purpose and such tables can be created in other query engines either way.
```markdown
* TBD. ({issue}`23653`)
```

Disallow write operations for Delta CDF and deletion vectors

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeIdentityColumnCompatibility.java

Migrate optimize product test to integration test in Delta Lake

---

core/trino-main/src/main/java/io/trino/execution/buffer/PageSerializer.java
pom.xml

Update aircompressor v3 to 3.1

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-460.md

Assemble the release notes for the upcoming Trino 460 release.
Also see https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A460
* #23577 ✅ rn ✅ docs
* #23558 ✅ rn ✅ docs
* #23574 ✅ rn ✅ docs
* #22728 ✅ rn ✅ docs
* #23569 ✅ rn ✅ docs
* #23579 ✅ rn ✅ docs
* #23580 ✅ rn ✅ docs
* #23584 ✅ rn ✅ docs
* #23587 ✅ rn ✅ docs
* #23550 ✅ rn ✅ docs
* #23578 ✅ rn ✅ docs
* #23429 ✅ rn ✅ docs
* #23483 ✅ rn ✅ docs
* #23581 ✅ rn ✅ docs
* #23507 ✅ rn ✅ docs
* #21603 ✅ rn ✅ docs
* #23269 ✅ rn ✅ docs
* #23201 ✅ rn ✅ docs
* #23597 ✅ rn ✅ …

Add Trino 460 release notes

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/expression/SparkExpressionBuilder.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/compaction/HudiCompactionOperation.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/compaction/HudiCompactionPlan.java
pom.xml

Enable ErrorProne TraditionalSwitchExpression

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeCompatibility.java
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/trino/etc/jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/trino/etc/jvm.config-initial-jdk-22

Cleanup jvm.config selection for compatibility tests

---

core/trino-main/src/main/java/io/trino/memory/RemoteNodeMemory.java
core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
core/trino-main/src/main/java/io/trino/split/BufferingSplitSource.java

Exception handling fixes

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTransactionLogParser.java

Reduce usage of deprecated `Locations.appendPath` method in Delta Lake connector

---

plugin/trino-delta-lake/pom.xml
plugin/trino-kafka/pom.xml
plugin/trino-opensearch/pom.xml
pom.xml

Update cloud SDKs and other minor dependencies

---

.github/DEVELOPMENT.md
README.md

See title
Follow up to https://github.com/trinodb/trino/pull/23201

Improve development process links

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestHiveMetastoreAccessOperations.java

Improves performance of splits generation on large partitioned hive tables by using 
dynamic filters to reduce the partitions metadata fetched by io.trino.metastore.HiveMetastore#getPartitionsByNames
```markdown
* Improve performance of queries with selective joins. ({issue}`23687`)
```

Use dynamic filters to reduce hive partitions metadata listing

---

plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ClassLoaderSafeSchemaRegistryClient.java
pom.xml

Update confluent schema registry to 7.7.1

---

plugin/trino-openlineage/pom.xml
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListener.java

Update openlineage-java to 1.23.0

---

docs/src/main/sphinx/admin/fault-tolerant-execution.md

Fix typo in FTE docs.
```markdown
```

Fix typo in property name in FTE docs

---

pom.xml

Update airbase, airlift and AWS SDK v2

---

client/trino-client/src/main/java/io/trino/client/ResultRowsDecoder.java
client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
core/trino-main/src/test/java/io/trino/server/TestQueryResource.java
core/trino-main/src/test/java/io/trino/server/protocol/TestQueryDataSerialization.java
core/trino-main/src/test/java/io/trino/server/protocol/TestQueryResultsSerialization.java
testing/trino-tests/src/test/java/io/trino/tests/TestServer.java

Simplify ResultRowsDecoder

---

core/trino-main/src/main/java/io/trino/connector/CoordinatorDynamicCatalogManager.java
core/trino-main/src/test/java/io/trino/execution/TestCreateCatalogTask.java

Fixes https://github.com/trinodb/trino/issues/23557
```markdown
* Fix handling failures while creating catalogs. ({issue}`23557`)
```

Fix handling failures while creating catalogs

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestingPolarisCatalog.java
pom.xml

Update docker image version to 102

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/UnityCatalogContainer.java

Remove redundant code

---

core/trino-main/src/test/java/io/trino/block/TestBlockBuilder.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/PageBuilder.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/line/LinePageSource.java

```markdown
* Remove unnecessary `PageBuilder``newPageBuilderLike` method. ({issue}`issuenumber`)
```

More page builder cleanup

---

pom.xml

Update airbase to 188

---

docs/src/main/sphinx/functions/datetime.md
docs/src/main/sphinx/functions/list-by-topic.md
docs/src/main/sphinx/functions/list.md
docs/src/main/sphinx/language/types.md

See title and comments in code PR. Code examples are taken from the unit tests.
https://github.com/trinodb/trino/pull/23564

Improve docs for timezone functions

---

core/trino-main/src/main/java/io/trino/metadata/CatalogTableFunctions.java
core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
core/trino-main/src/main/java/io/trino/metadata/TableFunctionRegistry.java
core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
core/trino-main/src/main/java/io/trino/testing/PlanTester.java
core/trino-main/src/test/java/io/trino/sql/query/TestShowQueries.java
core/trino-spi/src/main/java/io/trino/spi/function/FunctionMetadata.java

Fixes https://github.com/trinodb/trino/issues/12550
```markdown
* Add table functions to `SHOW FUNCTIONS` result. ({issue}`12550`)
```

Add table functions to `SHOW FUNCTIONS` result

---

pom.xml

Update airbase to 189 and airlift to 276

---

docs/src/main/sphinx/client/cli.md

See title and content changes.
Result of testing and discussion in https://github.com/trinodb/trino-gateway/issues/528

Clarify CLI docs for default catalog and schema

---

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java

Correct error code for analyze column mask

---

docs/src/main/sphinx/overview/concepts.md

Came up as gap on slack with users

Add node to concepts docs

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java
core/trino-main/src/main/java/io/trino/sql/planner/AdaptivePlanner.java

Improve debugability for https://github.com/trinodb/trino/issues/23854#issuecomment-2427356562

Make verify message more descriptive

---

plugin/trino-elasticsearch/pom.xml
pom.xml

Update Airbase and other dependencies

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreApiStats.java

Remove the workaround for JDK-8059299.
https://bugs.openjdk.org/browse/JDK-8059299 being fixed on JDK 9+

Remove workaround for JDK-8059299

---

docs/src/main/sphinx/functions/datetime.md

As discussed with @martint on slack.

Improve docs for at_timezone

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/SyncPartitionMetadataProcedure.java

```markdown
* Use `hive.metastore.partition-batch-size.max` config property value in `sync_partition_metadata` procedure. 
The default batch size is changed to 100 from 1000. ({issue}`23895`)
```

Use `hive.metastore.partition-batch-size.max` config property in Hive `sync_partition_metadata` procedure

---

plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerSplitManager.java

The host having `123` limit isn't deterministic. 
Fixes #23907

Fix flaky Faker test

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java

Re-enable tests as https://github.com/trinodb/trino/issues/21862 is fixed
```markdown
```

Re-enable Iceberg JDBC testDeleteRowsConcurrently

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestIcebergNessieCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogConnectorSmokeTest.java

Re-enable tests as https://github.com/trinodb/trino/issues/21862 is fixed
```markdown
```

Re-enable Iceberg Nessie and Polaris testDeleteRowsConcurrently

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogConnectorSmokeTest.java

Disable testDeleteRowsConcurrently for Iceberg Polaris

---

core/trino-server/src/main/provisio/trino.xml

Sort trino.xml alphabetically

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java

Add Glue metastore query runner to Hive connector

---

pom.xml

Update Cloud SDKs + airbase + airlift

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java

Report file system error as external error for refresh materialized view command
```markdown
```

Report file system error as external error

---

plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/file/FileTableDescriptionSupplier.java

Report invalid topic description file path in Kafka

---

core/trino-server/src/main/provisio/trino.xml
plugin/trino-vertica/pom.xml
plugin/trino-vertica/src/main/java/io/trino/plugin/vertica/VerticaClient.java
plugin/trino-vertica/src/main/java/io/trino/plugin/vertica/VerticaClientModule.java
plugin/trino-vertica/src/main/java/io/trino/plugin/vertica/VerticaDriver.java
plugin/trino-vertica/src/main/java/io/trino/plugin/vertica/VerticaPlugin.java
plugin/trino-vertica/src/main/java/io/trino/plugin/vertica/VerticaTableStatisticsReader.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/BaseVerticaConnectorSmokeTest.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestVerticaConnectorSmokeTest.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestVerticaConnectorTest.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestVerticaLatestConnectorSmokeTest.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestVerticaPlugin.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestVerticaTableStatistics.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestVerticaTypeMapping.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestingVerticaServer.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/VerticaQueryRunner.java
plugin/trino-vertica/src/test/resources/vmart_define_schema.sql
plugin/trino-vertica/src/test/resources/vmart_load_data.sql
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeAllConnectors.java
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-all/vertica.properties

This connector was originally written for the Starburst Enterprise platform and is now being contributed to Trino.
The documentation will be added by Manfred in a separate PR. 
The code in this PR replaces https://github.com/trinodb/trino/pull/6134
```markdown
* Add Vertica connector. ({issue}`23948`)
```

Add Vertica connector

---

core/trino-main/src/main/java/io/trino/execution/SqlQueryExecution.java
core/trino-main/src/main/java/io/trino/execution/SqlQueryManager.java
core/trino-main/src/main/java/io/trino/execution/SqlTask.java
core/trino-main/src/main/java/io/trino/execution/SqlTaskExecution.java
core/trino-main/src/main/java/io/trino/execution/SqlTaskExecutionFactory.java
core/trino-main/src/main/java/io/trino/execution/executor/dedicated/SplitProcessor.java
core/trino-main/src/main/java/io/trino/execution/executor/timesharing/TimeSharingTaskExecutor.java
core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedQueryScheduler.java
core/trino-main/src/main/java/io/trino/server/remotetask/ContinuousTaskStatusFetcher.java
core/trino-main/src/main/java/io/trino/server/remotetask/DynamicFiltersFetcher.java
core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java
pom.xml

Update airlift to 279

---

.github/workflows/upload-test-results.yml

Fix permissions of the upload results workflow

---

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/HashGenerationOptimizer.java

Remove unused method from HashGenerationOptimizer

---

plugin/trino-vertica/pom.xml
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/BaseVerticaConnectorSmokeTest.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestVerticaConnectorTest.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestVerticaPlugin.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestVerticaTableStatistics.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/VerticaQueryRunner.java

Minor cleanup in Vertica tests

---

plugin/trino-vertica/pom.xml
pom.xml

Batch dependency updates [oct 31st]

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadata.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/RetryingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcClient.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingDatabase.java
plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
plugin/trino-druid/src/test/java/io/trino/plugin/druid/TestDruidConnectorTest.java
plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMetadata.java
plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java
plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixSplitManager.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java

Refactor JdbcClient#getColumns 

---

docs/src/main/sphinx/functions/comparison.md

Existing query was just plain wrong and not working. Fixed query and added explanation.

Fix example query with IN

---

plugin/trino-vertica/src/main/java/io/trino/plugin/vertica/VerticaClient.java

Fix logical merge conflict in VerticaClient

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableProperties.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Small fixups after https://github.com/trinodb/trino/pull/20393
```markdown
```

Small extra properties fixups

---

client/trino-client/src/main/java/io/trino/client/JsonDecodingUtils.java
core/trino-main/src/main/java/io/trino/server/protocol/JsonBytesQueryData.java
core/trino-main/src/main/java/io/trino/server/protocol/JsonBytesQueryDataProducer.java
core/trino-main/src/main/java/io/trino/server/protocol/JsonEncodingUtils.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/encoding/JsonQueryDataEncoder.java

Throughput benchmark (higher is better):
```markdown
```

Do not buffer results while serializing JSON 

---

plugin/trino-kafka/pom.xml
pom.xml

Update dependencies nov 3rd

---

pom.xml

Update airbase and couple of other dependencies

---

pom.xml

Airbase 196 and Airlift 280

---

pom.xml

This enables Jackson's fast double/float/decimal parser/generator
```markdown
```

Update airlift to 281

---

plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/cassandra/CassandraTpchTableDefinitions.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/cassandra/TestSelect.java

Migrate Cassandra product test to integration test

---

testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/common/hadoop-kerberos/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/common/standard-multinode/multinode-master-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/common/standard-multinode/multinode-worker-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/common/standard/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/common/task-retries-multinode/multinode-master-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/common/task-retries-multinode/multinode-worker-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-postgresql-spooling/coordinator-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-postgresql-spooling/worker-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-tls-kerberos/config-master.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-tls-kerberos/config-worker.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-tls/config-master.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-tls/config-worker.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-oauth2-authenticated-http-proxy/trino/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-oauth2-authenticated-https-proxy/trino/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-oauth2-https-proxy/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-oauth2-refresh/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-oidc-refresh/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-oidc/config.properties

These are taking precious CPU time while writing to a local disk a log file that no one will ever read or use.
```markdown
```

Disable server http request logs in product tests

---

pom.xml

Update benchto to 0.31

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueTableOperationsInsertFailure.java

Fix Iceberg exception assertion

---

core/trino-main/pom.xml
core/trino-main/src/main/java/io/trino/server/Server.java
core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
plugin/trino-http-server-event-listener/pom.xml
plugin/trino-http-server-event-listener/src/main/java/io/trino/plugin/httpquery/HttpServerEventListenerFactory.java
pom.xml
service/trino-proxy/pom.xml
service/trino-proxy/src/main/java/io/trino/proxy/TrinoProxy.java

Remove event client leftovers
```markdown
```

Update airlift to 282

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java

Follow-up of https://github.com/trinodb/trino/pull/24049

Fix failure of Delta Lake testCaseUpdatePartitionColumnFails

---

plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiTableInfo.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiTableName.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/TableType.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/compaction/CompactionOperation.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/files/FileSlice.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/files/HudiFileGroup.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/files/HudiFileGroupId.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/model/HudiInstant.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/timeline/TimelineLayoutVersion.java

Minor cleanup in Hudi

---

plugin/trino-mongodb/pom.xml
plugin/trino-openlineage/pom.xml
plugin/trino-opensearch/pom.xml
pom.xml

Update deps nov 8th

---

docs/src/main/sphinx/connector/faker.md
docs/src/main/sphinx/connector/tpcds.md
docs/src/main/sphinx/connector/tpch.md

Just a bunch of cosmetics and style fixes, plus clarification for the function.
Follow up to #23990 and #24008

Improve Faker connector docs

---

core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
core/trino-main/src/main/java/io/trino/execution/QueryInfo.java
core/trino-main/src/main/java/io/trino/execution/StageInfo.java
core/trino-main/src/main/java/io/trino/execution/StageStateMachine.java
core/trino-main/src/main/java/io/trino/execution/StageStats.java
core/trino-main/src/main/java/io/trino/execution/TaskInfo.java
core/trino-main/src/main/java/io/trino/operator/PipelineStats.java
core/trino-main/src/main/java/io/trino/operator/TaskStats.java
core/trino-main/src/main/java/io/trino/server/ui/UiQueryResource.java
core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
core/trino-main/src/test/java/io/trino/execution/TestQueryInfo.java
core/trino-main/src/test/java/io/trino/execution/TestStageStats.java

Remove unnecessary digests from queryinfo

---

core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/plan/TableScanNode.java
core/trino-main/src/test/java/io/trino/cost/TestRemoteSourceStatsRule.java
core/trino-main/src/test/java/io/trino/execution/MockRemoteTaskFactory.java
core/trino-main/src/test/java/io/trino/execution/TaskTestUtils.java
core/trino-main/src/test/java/io/trino/execution/scheduler/TestMultiSourcePartitionedScheduler.java
core/trino-main/src/test/java/io/trino/execution/scheduler/TestScaledWriterScheduler.java
core/trino-main/src/test/java/io/trino/execution/scheduler/TestSourcePartitionedScheduler.java
core/trino-main/src/test/java/io/trino/execution/scheduler/policy/PlanUtils.java
core/trino-main/src/test/java/io/trino/server/TestDynamicFilterService.java
core/trino-main/src/test/java/io/trino/sql/planner/TestEffectivePredicateExtractor.java

Remove deprecated TableScanNode.newInstance()

---

plugin/trino-kudu/pom.xml
pom.xml

Update dependencies [nov 11th]

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConnector.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConnectorFactory.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSchemaProperties.java

Minor clean up of the `IcebergConnectorFactory` to create instances of `IcebergConnector` by guice. Reduces a lot of extra instantiation code and allows properties for the connector to be consistent and injectable.

Update iceberg connector to be created by guice

---

plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java

Updates nov 13

---

plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RewriteCast.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftCastPushdown.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConnectorTest.java

This PR adds support for cast projection pushdown for the Redshift connector for char/varchar types. 
- char -> char
- varchar -> varchar
```markdown
* Add varchar/char cast pushdown support in Redshift. ({issue}`issuenumber`)
```

Add varchar/char cast pushdown support in Redshift

---

client/trino-client/src/main/java/io/trino/client/JsonResultRows.java
client/trino-client/src/main/java/io/trino/client/OkHttpSegmentLoader.java
client/trino-client/src/main/java/io/trino/client/ResultRowsDecoder.java
client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
client/trino-client/src/main/java/io/trino/client/spooling/SegmentLoader.java
client/trino-client/src/test/java/io/trino/client/TestResultRowsDecoder.java

Iterate lazily over result rows

---

client/trino-client/src/test/java/io/trino/client/TestResultRowsDecoder.java

Check if data is read in chunks

---

core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java

no docs, no relnotes, just some clarification

Remove wrong TODO

---

docs/src/main/sphinx/connector/faker.md
docs/src/main/sphinx/functions/list-by-topic.md
docs/src/main/sphinx/functions/list.md

See commit message and diff
na

Improve random_string catalog function docs

---

plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerPageSource.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java

Fix generating real numbers from predicate list

---

core/docker/default/etc/jvm.config
core/trino-server-rpm/src/main/resources/dist/config/jvm.config
docs/src/main/sphinx/installation/deployment.md

This is related to changes made in
de64b5ec1fff9b1023fd00452dd80cc927e68e76 where the docker image and the product test configurations were updated.
Fixes #23749

Update jvm.config docs and defaults

---

pom.xml

Update dependencies nov 18th

---

core/trino-main/src/main/java/io/trino/sql/planner/AdaptivePlanner.java
core/trino-main/src/test/java/io/trino/sql/planner/TestAdaptivePlanner.java

Fixes https://github.com/trinodb/trino/issues/23854
```markdown
```

Fix adaptive planner failure if AdaptivePlanNode is root of fragment

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/TaskDescriptorStorage.java

Fix formatting and code ordering

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java

Use UNKNOWN state instead of null

---

plugin/trino-faker/pom.xml
pom.xml
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java

Update airbase, airlift and bunch of dependencies

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/TaskDescriptorStorage.java

Add compressionActive flag in TaskDescriptorStorage stats

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/TaskDescriptorStorage.java
testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
testing/trino-testing/src/main/java/io/trino/testing/FaultTolerantExecutionConnectorTestHelper.java

Test task descriptor compression/decompression during failover tests

---

docs/src/main/sphinx/connector/faker.md

Minor improvements in Faker connector docs

---

docs/src/main/sphinx/admin.md
docs/src/main/sphinx/admin/properties-query-management.md
docs/src/main/sphinx/admin/web-interface.md

As it related to the web ui, the memory storage, and what event listeners even do.
Comes up regularly in slack ..

Improve docs for query history and event listeners

---

docs/src/main/sphinx/connector/iceberg.md

Also for add_files_from_table.
Problem uncovered on slack https://trinodb.slack.com/archives/CJ6UC075E/p1731962499027129

Correct docs for add_files in Iceberg

---

docs/src/main/sphinx/client/cli.md

Add --extra-credential option to CLI doc

---

client/trino-client/src/main/java/io/trino/client/auth/kerberos/DelegatedUnconstrainedContextProvider.java

This makes JDBC driver work with Kerberos under JDK 24
```markdown
* Fix compatibility with pre-release JDK 24 ({issue}`issuenumber`)
```

Support post JDK 17 Subject.current

---

docs/src/main/sphinx/object-storage/file-system-s3.md

It's related to https://github.com/trinodb/trino/pull/22992.
```markdown
```

Doc entries for S3 server side encryption with customer key (SSE-C)

---

docs/src/main/sphinx/functions/array.md
docs/src/main/sphinx/functions/map.md
docs/src/main/sphinx/language/types.md

Follow up to recent discussion in maintainer channel.

Add docs for array and map creation

---

core/trino-main/src/main/java/io/trino/server/HttpRequestSessionContextFactory.java

Treat empty encoding header as no encoders

---

plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java

Post-release dependency updates

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergUnityRestCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestingPolarisCatalog.java
pom.xml

Update docker-image version to 105

---

core/docker/Dockerfile
core/trino-server-rpm/pom.xml
core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java
core/trino-server/src/main/provisio/trino.xml
docs/src/main/sphinx/installation/deployment.md
pom.xml

This entirely removes dependency on Python
```markdown
```

Switch to go based launcher

---

core/docker/Dockerfile
core/docker/build.sh

Prune launcher binaries for other archs

---

pom.xml

Update airbase to 201 and airlift to 287

---

core/trino-main/src/main/java/io/trino/server/protocol/JsonEncodingUtils.java
core/trino-main/src/test/java/io/trino/server/protocol/TestJsonEncodingUtils.java
core/trino-main/src/test/java/io/trino/server/protocol/spooling/TestJsonQueryDataEncoding.java

Directly write varchar slices to JSON

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogAccessOperations.java

Fix failure: https://github.com/trinodb/trino/actions/runs/12133285875/job/33828634759

Fix failing testSelectSystemTable in Iceberg Glue

---

pom.xml

Update parquet to 1.15.0

---

pom.xml

These are distributions that are tested and are known to work fine.
This requirement doesn't mean that Trino won't run on other JDK distributions.
```markdown
```

Require Temurin or Oracle JDK for development

---

plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/BaseOpenSearchConnectorTest.java

Supersedes https://github.com/trinodb/trino/pull/20815
The first commit was cherry-picked with minor conflicts resolved.
The last commit was redone since the original PR had issues + was missing some newly added tests.

Elasticsearch test cleanups

---

pom.xml

https://github.com/trinodb/trino-coral/pull/5
```markdown
```

Update coral to 2.2.49-1

---

docs/src/main/sphinx/admin/properties-client-protocol.md

see title
Follow up to https://github.com/trinodb/trino/pull/24332

Add docs for spooling compression threshold

---

plugin/trino-http-server-event-listener/pom.xml
plugin/trino-http-server-event-listener/src/main/java/io/trino/plugin/httpquery/HttpServerEventListenerFactory.java
pom.xml

Update airlift to 289

---

plugin/trino-elasticsearch/pom.xml
plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
plugin/trino-opensearch/pom.xml
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java

Update dependencies thu 5 dec

---

pom.xml

Update gib to 4.5.4

---

core/trino-main/src/main/java/io/trino/eventlistener/EventListenerContextInstance.java
core/trino-main/src/main/java/io/trino/eventlistener/EventListenerManager.java
core/trino-main/src/main/java/io/trino/testing/PlanTester.java
core/trino-main/src/main/java/io/trino/testing/TestingEventListenerContext.java
core/trino-main/src/main/java/io/trino/testing/TestingEventListenerManager.java
core/trino-main/src/test/java/io/trino/dispatcher/TestLocalDispatchQuery.java
core/trino-main/src/test/java/io/trino/eventlistener/TestEventListenerManager.java
core/trino-main/src/test/java/io/trino/execution/TaskTestUtils.java
core/trino-spi/pom.xml
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/evenlistener/TestingEventListenerContext.java
plugin/trino-http-event-listener/pom.xml
plugin/trino-http-event-listener/src/main/java/io/trino/plugin/httpquery/HttpEventListenerFactory.java
plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpEventListener.java
plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpEventListenerPlugin.java
plugin/trino-http-server-event-listener/pom.xml
plugin/trino-http-server-event-listener/src/main/java/io/trino/plugin/httpquery/HttpServerEventListenerFactory.java
plugin/trino-http-server-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpServerEventListener.java
plugin/trino-http-server-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpServerListenerPlugin.java
plugin/trino-kafka-event-listener/pom.xml
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/KafkaEventListenerFactory.java
plugin/trino-kafka-event-listener/src/test/java/io/trino/plugin/eventlistener/kafka/TestKafkaEventListenerPlugin.java
plugin/trino-mysql-event-listener/pom.xml
plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListenerFactory.java
plugin/trino-mysql-event-listener/src/test/java/io/trino/plugin/eventlistener/mysql/TestMysqlEventListener.java
plugin/trino-openlineage/pom.xml
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListenerFactory.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/OpenLineageListenerQueryRunner.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineageListener.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TestOpenLineagePlugin.java
testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerPlugin.java

Add EventListenerContext to factory

---

pom.xml

Update aircompressor to 2.0.2

---

plugin/trino-http-event-listener/src/main/java/io/trino/plugin/httpquery/HttpEventListenerFactory.java
plugin/trino-kafka-event-listener/pom.xml
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/KafkaEventListenerFactory.java
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/KafkaEventPublisher.java
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/producer/BaseKafkaProducerFactory.java
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/producer/KafkaProducerFactory.java
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/producer/PlaintextKafkaProducerFactory.java
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/producer/SSLKafkaProducerFactory.java
plugin/trino-mysql-event-listener/pom.xml
plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListenerFactory.java

```
Kafka, MySQL, HTTP event listeners
Add support for OpenTelemetry tracing
```
```markdown
```

Add telemetry to event listeners

---

testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-apache-ranger/access-control.properties

To fix build breakage on product tests in master.
https://github.com/trinodb/trino/pull/24392

Fix Ranger config for product test

---

core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
pom.xml

Update airlift to 291 and enable tracing for testing Trino servers

---

pom.xml

Update Iceberg to 1.7.1

---

docs/src/main/sphinx/release/release-467.md

Add missing PR link in 467 release notes

---

plugin/trino-hudi/pom.xml
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/TpchHudiTablesInitializer.java

Update Hudi library to 1.0.0

---

core/trino-server/src/main/provisio/trino.xml

Tested with local build and tarball run. 

Add Python UDF support to binaries

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcWriteConfig.java

Update config description for insert.non-transactional-insert.enabled

---

plugin/trino-functions-python/pom.xml

This fixes debug logging to only format arguments when in debug mode.

Improve performance of Python functions

---

docs/src/main/sphinx/connector/iceberg.md

Add iceberg.bucket-execution to documentation

---

plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java

Remove unnecessary annotation in Kudu connector test

---

core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaPageSource.java

Avoids unnecessary Integer boxing and Block[] allocations in `InformationSchemaPageSource` by using `Page#getColumns`.

Cleanup InformationSchemaPageSource projection

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestSplitPruning.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ExpressionConverter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java

Fix misspelling in Iceberg

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergLocalConcurrentWrites.java

Improve test coverage for iceberg concurrent writes
```markdown
```

Test Iceberg concurrent update without partition

---

pom.xml

Updates dec 19

---

docs/src/main/sphinx/client.md

Adding csharp client and updating links to updated website.
https://github.com/trinodb/trino.io/pull/746

Update client driver and application sections

---

plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteClient.java
plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMergeTableHandle.java
plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMetadata.java
plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java

```markdown
* Support `MERGE` for Ignite connector. ({issue}`issuenumber`)
```

Support MERGE for Ignite connector

---

core/trino-main/src/test/java/io/trino/execution/executor/timesharing/SimulationController.java

Using airlift log in SimulationController

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetWithBloomFilters.java

Verify invalid bloom filter properties in Iceberg

---

docs/src/main/sphinx/connector/faker.md

Add views support to the Faker connector docs

---

pom.xml

Should be easier to manage plugin versions.
-
```markdown
```

Extract dep.gib.version property

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java

Convert testRollbackToSnapshotWithNullArgument to integration test

---

plugin/trino-druid/pom.xml
plugin/trino-openlineage/pom.xml
pom.xml

Dependency updates dec 30

---

core/trino-main/pom.xml

Update lucene-analysis-common to 10.1.0

---

plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftUnload.java

Fix failures reported in https://github.com/trinodb/trino/actions/runs/12561997291/job/35021834281#step:19:2278
```markdown
```

Copy all TPCH tables during initialization in TestRedshiftUnload

---

docs/src/main/sphinx/udf/python.md

Minor improvements to Python UDF docs

---

plugin/trino-delta-lake/pom.xml

Update delta-kernel to 3.3.0

---

docs/src/main/sphinx/connector/redshift.md

Fixing since original PR did not address feedback.
#24117

Improve docs for Redshift parallel read

---

core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java

Expose extra stats from SqlTaskManager

---

.mvn/jvm.config

Suppress warning when building with mvnd

---

docs/src/main/sphinx/admin/properties-client-protocol.md

Add docs for spooling_protocol_enabled session property

---

core/trino-web-ui/src/main/resources/webapp-preview/package-lock.json
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/GeoFunctions.java

Fix logical merge conflict

---

docs/src/main/sphinx/connector/clickhouse.md
plugin/trino-clickhouse/pom.xml
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClientModule.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestingClickHouseServer.java
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeClickhouse.java
testing/trino-product-tests/pom.xml

Revert "Update supported clickhouse versions"

---

plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraLatestConnectorSmokeTest.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestingScyllaServer.java

Bump Cassandra and Scylla test docker image version

---

plugin/trino-google-sheets/pom.xml
plugin/trino-mongodb/pom.xml
pom.xml

Updates january 13th

---

lib/trino-filesystem-manager/src/main/java/io/trino/filesystem/manager/FileSystemModule.java
lib/trino-filesystem-manager/src/main/java/io/trino/filesystem/manager/HdfsFileSystemLoader.java
lib/trino-hdfs/src/main/java/io/trino/filesystem/hdfs/HdfsFileSystemManager.java
lib/trino-hdfs/src/test/java/io/trino/filesystem/hdfs/TestHdfsFileSystemManager.java
pom.xml

Update airlift to 295

---

docs/src/main/sphinx/connector/iceberg.md

Just fyi .. I did not look into the code or so at all.. just quickly slapped this together based on your comment and the assumption that it works the same as for all_entries.. if thats wrong please clarify.
Follow up to comment in https://github.com/trinodb/trino/pull/24686

Adjust docs for  manifests metadata table in Iceberg

---

lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/json/TestJsonFormat.java

Follows up on https://github.com/trinodb/trino/pull/24558 by adding a test that asserts that writing `NaN` / `Infinite` / `-Infinite` float and double values fails.

Add test for JsonSerializer NaN / Infinite handling

---

lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemLocalStack.java
pom.xml
testing/trino-testing-containers/src/main/java/io/trino/testing/containers/Minio.java

Update google & aws sdks + minor deps

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemMinIo.java
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Minio.java
testing/trino-testing-containers/src/main/java/io/trino/testing/containers/Minio.java

Update AWS SDK v2 to 2.30.0

---

core/trino-main/src/main/java/io/trino/operator/scalar/ArrayHistogramFunction.java

Hopefully fixes https://github.com/trinodb/trino/issues/24765
```markdown
```

Fix null check in the array_histogram

---

plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorage.java

Set validation to WHEN_REQUIRED for FTE exchange

---

client/trino-cli/pom.xml
client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
client/trino-cli/src/main/java/io/trino/cli/Query.java
client/trino-cli/src/main/java/io/trino/cli/StatusPrinter.java
client/trino-cli/src/main/java/io/trino/cli/TableNameCompleter.java
client/trino-client/pom.xml
client/trino-client/src/main/java/io/trino/client/ClientSession.java
client/trino-client/src/main/java/io/trino/client/ClientTypeSignature.java
client/trino-client/src/main/java/io/trino/client/NamedClientTypeSignature.java
client/trino-client/src/main/java/io/trino/client/QueryDataClientJacksonModule.java
client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
client/trino-client/src/main/java/io/trino/client/spooling/encoding/DecompressionUtils.java
client/trino-client/src/main/java/io/trino/client/uri/AbstractConnectionProperty.java
client/trino-client/src/main/java/io/trino/client/uri/ConnectionProperties.java
client/trino-client/src/main/java/io/trino/client/uri/ConnectionProperty.java
client/trino-client/src/main/java/io/trino/client/uri/TrinoUri.java
client/trino-client/src/main/java/okhttp3/internal/tls/DistinguishedNameParser.java
client/trino-client/src/main/java/okhttp3/internal/tls/LegacyHostnameVerifier.java
client/trino-client/src/test/java/io/trino/client/spooling/encoding/TestCompressedQueryDataDecoder.java
client/trino-jdbc/pom.xml
client/trino-jdbc/src/main/java/io/trino/jdbc/CancellableIterator.java
client/trino-jdbc/src/main/java/io/trino/jdbc/Row.java
client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoDatabaseMetaData.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriver.java

Modernize client libraries a bit

---

docs/src/main/sphinx/object-storage/legacy-s3.md

* Removed the considerations section from the S3 legacy migration guide.
https://github.com/trinodb/trino/pull/24772
```markdown
```

Remove S3 legacy migration guide considerations

---

plugin/trino-loki/src/test/java/io/trino/plugin/loki/TestLokiIntegration.java

Fixes https://github.com/trinodb/trino/issues/24831
```markdown
```

Fix Timestamp assertion test for metrics query

---

docs/src/main/sphinx/release/release-469.md

Fix a wrong issue link in 469 release notes

---

plugin/trino-exasol/src/test/java/io/trino/plugin/exasol/TestExasolConnectorTest.java

Remove unreachable code from Exasol

---

lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GcsAccessTokenProvider.java
lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GcsStorageFactory.java
lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/GoogleGcsConfigurationInitializer.java
pom.xml

Update gcs-connector to 3.0.4

---

.github/workflows/ci.yml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/snowflake/TestIcebergSnowflakeCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/org/apache/iceberg/snowflake/TestTrinoSnowflakeCatalog.java
plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeTypeMapping.java

This reverts commit 5c431491f93bc1a5c82d4780aa8220d48236eac2.
Closes https://github.com/trinodb/trino/issues/24754
```markdown
```

Reenable Snowflake tests

---

plugin/trino-loki/src/test/java/io/trino/plugin/loki/TestLokiPlugin.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeAllConnectors.java
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-all/loki.properties

Add more tests for Loki connector

---

.github/config/labeler-config.yml

Add more connectors to labeler-config

---

client/trino-cli/pom.xml
pom.xml

Update dependencies (backend+frontend)

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableProperties.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java

Fix code typo

---

pom.xml

Update cloud SDKs

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogCaseInsensitiveMapping.java

Polaris catalog be a blocker like https://github.com/trinodb/trino/pull/24713 when we update Iceberg library because our bump process is faster than theirs. 

Use delegating catalog in TestIcebergRestCatalogCaseInsensitiveMapping

---

core/trino-main/src/main/java/io/trino/server/ThrowableMapper.java
lib/trino-hdfs/src/main/java/io/trino/hdfs/azure/HiveAzureConfig.java
lib/trino-hdfs/src/main/java/io/trino/hdfs/cos/HiveCosServiceConfig.java
lib/trino-hdfs/src/main/java/io/trino/hdfs/gcs/HiveGcsConfig.java
lib/trino-hdfs/src/main/java/io/trino/hdfs/s3/HiveS3Config.java
lib/trino-hdfs/src/main/java/io/trino/hdfs/s3/HiveS3TypeConfig.java
lib/trino-hdfs/src/main/java/io/trino/hdfs/s3/S3SecurityMappingConfig.java
pom.xml

Update airlift to 302

---

core/trino-main/src/main/java/io/trino/dispatcher/DispatchManager.java

Fixes https://github.com/trinodb/trino/issues/24907
```markdown
```

Export number of fully blocked queries to JMX

---

docs/build

Add --rm option to docs/build command

---

client/trino-client/src/main/java/io/trino/client/spooling/DataAttribute.java
core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java
testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
testing/trino-testing/src/main/java/io/trino/testing/LocalSpoolingManager.java

Add expiration date time to segment metadata

---

docs/src/main/sphinx/admin/properties-client-protocol.md

See commit message.
Requested on slack

Add command to create secret for spooling

---

docs/src/main/sphinx/release/release-470.md

Fix a minor typo in release-470.md

---

.github/workflows/stale.yml

Suggested by @ebyhr on slack. I agree

Include draft PRs in stale bot flow

---

client/trino-client/src/main/java/io/trino/client/QueryData.java

Remove deprecated method

---

core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingManagerRegistry.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/TracingSpoolingManager.java
plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/FileSystemSpoolingManagerFactory.java

It should apply to all SpoolingManager implementations
```markdown
```

Move TracingSpoolingManager to main

---

plugin/trino-duckdb/pom.xml
plugin/trino-opensearch/pom.xml
pom.xml

Update bunch of dependencies

---

docs/src/main/sphinx/functions.md

Trivial grammar fix found when reviewing another PR in a different related codebase.

Fix grammar in functions overview

---

pom.xml

Update JDBI + AWS SDK v2

---

lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java

Fix typo in null check message for outputStream

---

pom.xml

Update airbase nad snakeyaml

---

client/trino-client/src/main/java/io/trino/client/JsonResponse.java
client/trino-client/src/main/java/io/trino/client/MaterializingReader.java
client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
client/trino-client/src/main/java/io/trino/client/TrinoJsonCodec.java
client/trino-client/src/main/java/io/trino/client/auth/external/HttpTokenPoller.java
client/trino-client/src/test/java/io/trino/client/TestMaterializingReader.java

Do not materialize response body to string

---

docs/src/main/sphinx/security/ranger-access-control.md

Updated documentation for Ranger access control plugin to use Kerberos authentication with Ranger admin server.
```markdown
```

Update Ranger access control documentation for Kerberos environment

---

plugin/trino-exchange-filesystem/pom.xml
pom.xml

Fixes https://github.com/trinodb/trino/issues/25063
```markdown
```

Update oidc sdk and add runtime dependency in exchange-filesystem

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java

Hive views retrieval can be easily parallelized using the same approach as in https://github.com/trinodb/trino/pull/24110/commits/64d51fc0e1ca6834c8969cfce4aeeed4e52caf1e.
```markdown
```

Parallelize Hive views retrieval

---

docs/src/main/sphinx/connector/hive.md
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveOnDataLake.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveS3AndGlueMetastoreTest.java

```markdown
* Enable `hive.partition-projection-enabled` by default ({issue}`25079`)
```

Set hive.partition-projection-enabled to true by default

---

README.md

Note the need for Rosetta on Apple Silicon

---

plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/ClickHouseQueryRunner.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestingClickHouseServer.java
pom.xml

```markdown
* Color console output for improved logs readability
* Suggest configuration for unused properties (did you mean)
```

Update airlift to 307 and other upgrades

---

docs/src/main/sphinx/release/release-471.md

Fix link in release note 471

---

docs/src/main/sphinx/functions/ai.md

Adding details for properties and some other minor improvements.
Follow up to #24963 

Improve AI function docs

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java

Fixes: https://github.com/trinodb/trino/issues/24866
Addressing testUpdateWithSortOrder flaky. For some runs number of created stripes for ORC file is 1 which causes to fail check statistics ordering (needs statistics.size() > 1). Changing sort order from metadata statistics to actual data should fix issue.
Tested locally with @RepeatedTest(300). Before change it was failing about 3 times. No failures after change.
```markdown
```

Check ORC sorting using file data

---

core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4
core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java

Limit WITH SESSION scope to SELECT statements

---

docs/src/main/sphinx/object-storage/file-system-s3.md

Fix property name in S3 file-system migration guide

---

.mvn/extensions.xml
plugin/trino-ignite/pom.xml

Circumvents https://github.com/trinodb/trino/security/dependabot/247
```markdown
```

Update apache ignite to 2.17.0

---

core/trino-main/src/main/java/io/trino/FullConnectorSession.java
core/trino-main/src/main/java/io/trino/execution/SessionPropertyEvaluator.java
core/trino-main/src/main/java/io/trino/metadata/SessionPropertyManager.java
core/trino-main/src/main/java/io/trino/sql/SessionPropertyResolver.java
core/trino-main/src/main/java/io/trino/testing/TestingConnectorSession.java
core/trino-main/src/test/java/io/trino/sql/query/TestInlineSession.java
core/trino-spi/src/main/java/io/trino/spi/predicate/ToStringSession.java
core/trino-spi/src/test/java/io/trino/spi/block/TestingSession.java

Improve consistency of invalid session properties

---

core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
core/trino-main/src/main/java/io/trino/server/protocol/ExecutingStatementResource.java
core/trino-main/src/main/java/io/trino/server/protocol/JsonBytesQueryDataProducer.java
core/trino-main/src/main/java/io/trino/server/protocol/Query.java
core/trino-main/src/main/java/io/trino/server/protocol/QueryDataProducer.java
core/trino-main/src/main/java/io/trino/server/protocol/QueryDataProducerFactory.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpooledQueryDataProducer.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingQueryDataProducer.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingServerModule.java

Spooling cleanup

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergS3TablesConnectorSmokeTest.java

Temporarily disable TestIcebergS3TablesConnectorSmokeTest until root cause is identified.
Log https://github.com/trinodb/trino/issues/25129
```markdown
```

Temporarily disable TestIcebergS3TablesConnectorSmokeTest

---

client/trino-cli/src/main/java/io/trino/cli/AlignedTablePrinter.java
client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java
client/trino-cli/src/main/java/io/trino/cli/MarkdownTablePrinter.java
client/trino-cli/src/main/java/io/trino/cli/Query.java
client/trino-cli/src/main/java/io/trino/cli/QueryPreprocessor.java
client/trino-cli/src/main/java/io/trino/cli/StatusPrinter.java
client/trino-cli/src/main/java/io/trino/cli/VerticalRecordPrinter.java
client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java
client/trino-client/src/main/java/io/trino/client/uri/ConnectionProperties.java
client/trino-client/src/test/java/io/trino/client/TestQueryResults.java
client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoStatement.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcPreparedStatement.java

Post JDK-11 client cleanup

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java

Replace URL with HTML link in  comment

---

core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java
core/trino-main/src/main/java/io/trino/server/protocol/JsonBytesQueryDataProducer.java
core/trino-main/src/main/java/io/trino/server/protocol/Query.java
core/trino-main/src/main/java/io/trino/server/protocol/QueryDataProducer.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/QueryDataEncoder.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingQueryDataProducer.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/encoding/CompressedQueryDataEncoder.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/encoding/JsonQueryDataEncoder.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java

Close QueryDataEncoder and Producer when processing is complete

---

docs/src/main/sphinx/functions/binary.md
docs/src/main/sphinx/optimizer/cost-based-optimizations.md
docs/src/main/sphinx/static/trino.css

See commit messages and please test and have a look with local build.

A bunch of docs improvements

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileFormat.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TypeConverter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/HiveSchemaUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/OrcTypeConverter.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergStatistics.java
plugin/trino-iceberg/src/test/java/org/apache/iceberg/rest/RestCatalogServlet.java
pom.xml
testing/trino-testing-containers/src/main/java/io/trino/testing/containers/IcebergRestCatalogBackendContainer.java

Update Iceberg version to 1.8.1

---

plugin/trino-opensearch/pom.xml
pom.xml

Updates dep

---

docs/src/main/sphinx/admin/fault-tolerant-execution.md

A user noticed this is also required on the coordinator: https://github.com/trinodb/charts/issues/307

Fix FTE local FS usage note

---

plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Fix test method visibility

---

pom.xml

Update airbase to 227 & AWS SDK v2

---

docs/src/main/sphinx/admin/properties-http-client.md
docs/src/main/sphinx/functions/ai.md

Found that they exist during testing. 

Document HTTP client config for AI functions

---

pom.xml

Remove unused Groovy plugin declaration

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestingPolarisCatalog.java
pom.xml
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java

Update docker-images to 110

---

lib/trino-parquet/pom.xml
plugin/trino-pinot/pom.xml

Improve maven setup

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java

Looks like a copy-paste error. The latter parts of this assertion use this one.
```markdown
```

Use a proper variable in assertion

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java

Remove nested loop to find ambiguous tables. This optimizes compute from O(n^2) to 2*O(n) when bigquery.case-insensitive-name-matching is enabled
```markdown
* Improve performance of listing tables when `bigquery.case-insensitive-name-matching` is enabled.
```

Optimize BigQuery listing tables

---

docs/src/main/sphinx/ext/download.py
docs/src/main/sphinx/installation/plugins.md

Somehow this one was omitted .. maybe I started the initial PR before the merge.. anyway..
#22597 

Add AI functions to plugin list

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAlluxioCacheFileOperations.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergFileOperations.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMemoryCacheFileOperations.java

Static import class and method in FileOperationUtils

---

plugin/trino-functions-python/pom.xml
pom.xml

Update cloud SDKs, chicory, benchto and docker-java

---

core/docker/Dockerfile
core/docker/build.sh

Allow using a different package (artifact) when building the Docker image. Use the two new options for the package and tag:
```
./core/docker/build.sh -a arm64 -p trino-server-core -t trino-core
```
This should be used in https://github.com/trinodb/release-scripts/blob/master/trino-docker.sh

Build core container

---

client/trino-client/src/main/java/io/trino/client/StatementClientV1.java

currentRows can be null and Closeables.close checks that
```markdown
```

Close currentRows silently

---

plugin/trino-faker/pom.xml
plugin/trino-vertica/pom.xml

Remove unneeded transitive dependencies

---

pom.xml

Update Jetty to 12.0.17

---

docs/src/main/sphinx/functions/json.md

Just a doc fix. Related to slack thread: https://trinodb.slack.com/archives/C0305TQ05KL/p1741764426024149

Fix docs for JSON path arguments

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java

Fix typo in CheckpointEntryIterator

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/VectorBitPackingUtils.java

Make util class VectorBitPackingUtils final

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java

Fix logical merge conflict in IcebergUtil

---

plugin/trino-ldap-group-provider/pom.xml

Fix a logical merge conflict caused by merging #23900 without rebasing it after #25291 was merged.

Add a missing dependency in LDAP group provider plugin

---

docs/src/main/sphinx/connector/iceberg.md

Add docs to the Iceberg connector for the `system.bucket` function added in previous PR - https://github.com/trinodb/trino/pull/25175

Add docs for system.bucket function in iceberg

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointSchemaManager.java

Remove unused code from Delta Lake

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/PageListBuilder.java

Remove unused code from Iceberg

---

plugin/trino-cassandra/pom.xml
plugin/trino-exasol/pom.xml
plugin/trino-opensearch/pom.xml
pom.xml

Bulk update dependencies

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/glue/DeltaLakeGlueMetastoreModule.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileMetastoreModule.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueConverter.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestingGlueHiveMetastore.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiTableName.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiSharedMetastore.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiSystemTables.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/IcebergHiveMetastoreModule.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/IcebergFileMetastoreCatalogModule.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/IcebergGlueCatalogModule.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/IcebergHiveMetastoreCatalogModule.java

Minor cleanup for lakehouse connectors

---

plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java

Fix listing Hudi tables when storage location is not set

---

core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ReplaceWindowWithRowNumber.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestReplaceWindowWithRowNumber.java

Remove unused Metadata in ReplaceWindowWithRowNumber

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveNotReadableException.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveReadOnlyException.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveViewNotSupportedException.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveWriter.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/PartitionNotFoundException.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/PartitionOfflineException.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/TableOfflineException.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewAlreadyExistsException.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/AwsApiCallStats.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSource.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveTestUtils.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/PartitionFilterBuilder.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/ParquetUtil.java

Remove unused code from Hive

---

docs/src/main/sphinx/connector/iceberg.md

Metadata columns can be quite useful to optimize only a portion of the files of the table.
I intended to document as well the behavior for Delta Lake, but stumbled on https://github.com/trinodb/trino/issues/25369
```markdown
```

Document OPTIMIZE usage with metadata columns filter

---

docs/src/main/sphinx/connector/iceberg.md

See title, dont use `#` with internal links.
Follow up to 25370

Avoid using relative link use in docs

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Use TestTable in Iceberg test testOptimizeWithFileModifiedTimeColumn

---

docs/src/main/sphinx/release/release-473.md

Trino release 473 will produce incorrect results. The fix is landed in https://github.com/trinodb/trino/pull/25381
( ) Release notes are required, with the following suggested text

Add warning to release 473

---

docs/src/main/sphinx/connector/ignite.md
docs/src/main/sphinx/connector/mysql.md

Improve docs for support create table with primary key in mysql

---

docs/src/main/sphinx/client/cli.md
docs/src/main/sphinx/client/jdbc.md

Update required Java version in client documentation

---

docs/src/main/sphinx/release/release-474.md

Fix grammar and syntax in 474 release notes

---

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSourceProvider.java

Simplify dynamic filter usage in MongoPageSourceProvider#createPageSource

---

.github/workflows/ci.yml

Add maven-checks on JDK 25-ea

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSink.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSinkProvider.java

Remove write verification dead code in Hive

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsReader.java

Rename method in IcebergUtil

---

plugin/trino-bigquery/pom.xml
plugin/trino-elasticsearch/pom.xml
plugin/trino-loki/pom.xml
plugin/trino-opensearch/pom.xml
plugin/trino-prometheus/pom.xml
pom.xml

Just some cleanups for consistency and/or tightening of versioning of transitive dependencies.
```markdown
```

Clean up versioning of httpcomponents

---

core/trino-main/src/main/java/io/trino/sql/gen/columnar/DynamicPageFilter.java
core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java

Simplify building of DynamicFilterEvaluator in DynamicPageFilter

---

docs/src/main/sphinx/object-storage/file-system-s3.md
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemConfig.java

Add remaining S3 storage classes

---

client/trino-client/src/main/java/io/trino/client/spooling/InlineSegmentIterator.java
client/trino-client/src/main/java/io/trino/client/spooling/SpooledSegmentIterator.java
client/trino-client/src/test/java/io/trino/client/TestResultRowsDecoder.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingQueryDataProducer.java

Add rows_count to inlined segments

---

pom.xml

Update azure cloud SDK to 1.2.33

---

core/trino-main/src/main/java/io/trino/operator/aggregation/DistinctWindowAccumulator.java
core/trino-main/src/test/java/io/trino/sql/query/TestWindow.java

```markdown
* Fix window functions with DISTINCT. ({issue}`25434`)
```
Fixes https://github.com/trinodb/trino/issues/25434

Fix distinct positions selection for window functions

---

README.md

Fix visible links between buttons in README

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergS3TablesConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/snowflake/TestIcebergSnowflakeCatalogConnectorSmokeTest.java

Fix failing Iceberg v3 tests

---

plugin/trino-functions-python/pom.xml
pom.xml

Airbase and Airlift dependencies improves compatibility with JDK25.

Update dependencies for JDK25 compatibility

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/DefaultThriftMetastoreClientFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftHiveMetastoreClient.java

We already removed support for Unity integration. 

Remove stale code from ThriftHiveMetastoreClient

---

.github/workflows/ci.yml

Restore cache for maven checks on 25-ea

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryQueryPageSource.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageArrowPageSource.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageAvroPageSource.java

Fixes #25423
I manually tested because preparing a large table on CI requires a long time. 
```markdown
```

Return null in BigQuery getNextSourcePage

---

core/trino-main/src/main/java/io/trino/sql/rewrite/ExplainRewrite.java
core/trino-main/src/main/java/io/trino/testing/PlanTester.java

Fixes https://github.com/trinodb/trino/issues/25489
```markdown
* Resolve WITH SESSION properties for EXPLAIN statements ({issue}`issuenumber`)
```

Fix resolving WITH SESSION in the EXPLAIN

---

core/trino-main/src/main/java/io/trino/sql/planner/SubqueryPlanner.java

Traverse nodes once while planning subqueries

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/AddFileEntry.java

Add non null check for path in AddFileEntry

---

pom.xml

Upgrade Jetty & minor deps

---

core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java

Not every output is actually a spooled output as it can also be an exchange, which needs channels to be correctly arranged.
```markdown
```

Enforce spooled layout only when physical plan contains spooled output

---

core/trino-main/src/main/java/io/trino/operator/project/MergePages.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java

Use batched block builders in MergePages

---

core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java

Simplify spooling encoding code

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestCachedHiveGlueMetastore.java

Improve logging in HiveSplitManager.getPartitionMetadata

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadataFactory.java

Remove requireNonNull check in DefaultJdbcMetadataFactory

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/procedure/TestIcebergAddFilesProcedure.java

Fix typo in TestIcebergAddFilesProcedure

---

plugin/trino-faker/pom.xml
pom.xml

Update dependencies april 8th

---

lib/trino-orc/src/main/java/io/trino/orc/metadata/statistics/DateStatisticsBuilder.java

Fix trivial typo in DateStatisticsBuilder

---

testing/trino-tests/pom.xml
testing/trino-tests/src/test/java/io/trino/server/protocol/AbstractSpooledQueryDataDistributedQueries.java

Avoid deprecated LocalStackContainer constructor

---

core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java

Use inlined encoded pages when calculating encoder efficiency

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java

Fix format in CheckpointWriter

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java

Remove redundant variables in IcebergUtil

---

core/trino-main/src/main/java/io/trino/operator/project/PageProcessor.java
core/trino-main/src/test/java/io/trino/block/TestRunLengthEncodedBlock.java

Use Arrays.fill instead of manual filling

---

core/trino-main/src/main/java/io/trino/connector/WorkerDynamicCatalogManager.java
core/trino-main/src/main/java/io/trino/eventlistener/EventListenerManager.java
core/trino-main/src/main/java/io/trino/execution/executor/dedicated/ThreadPerDriverTaskExecutor.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java
core/trino-main/src/main/java/io/trino/server/NodeStateManager.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/QueryDataEncoders.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/avro/NativeLogicalTypesAvroTypeManager.java
testing/trino-testing-containers/src/main/java/io/trino/testing/containers/MitmProxy.java

Avoid string concat in logger

---

docs/src/main/sphinx/connector/delta-lake.md

Fix the Delta Lake doc compile issue, a quick fix to https://github.com/trinodb/trino/pull/25632
Built the trino-doc
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  37.392 s (Wall Clock)
[INFO] Finished at: 2025-04-20T23:22:24-04:00
[INFO] ------------------------------------------------------------------------
```

Fix the Delta Lake doc compile issue

---

plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftTypeMapping.java

Fixes https://github.com/trinodb/trino/issues/25459
```markdown
```

Fix TestRedshiftTypeMapping#testTimestampWithTimeZoneOverflow

---

lib/trino-filesystem-cache-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioConfigurationFactory.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/Versions.java
lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/FileDescriptorProvider.java
lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/FixedSchemaDynamicMessageProvider.java
lib/trino-record-decoder/src/main/java/io/trino/decoder/protobuf/ProtobufValueProvider.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/IndexMetadata.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/FileSystemExchangeSink.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTablePartitioning.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/TimestampCoercer.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveCoercionPolicy.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaPageSink.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/encoder/protobuf/ProtobufRowEncoder.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/encoder/raw/RawRowEncoder.java
plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/OpenSearchMetadata.java
plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/IndexMetadata.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java
plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/AbstractResourceConfigurationManager.java
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Environment.java
testing/trino-testing-services/src/main/java/io/trino/testing/TestingProperties.java

New one in Error Prone 2.38.0, allows us to use formatter methods directly in more places.
Error Prone 2.38.0 was pulled in with airbase 253 (#25627).
```markdown
```

Enable PreconditionsExpensiveString Error Prone check

---

docs/src/main/sphinx/connector/hive.md

Improve the public documentation for hive.s3-glacier-filter config after https://github.com/trinodb/trino/pull/25633

Improve the public documentation for hive.s3-glacier-filter config

---

.github/workflows/ci.yml

Set check-commit timeout as 15 minutes

---

lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java

Inline page variable when pass to recordValidation

---

core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingConfig.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingManagerBridge.java
plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/FileSystemSpooledSegmentHandle.java

Spooling cleanups

---

core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
core/trino-main/src/test/java/io/trino/dispatcher/TestLocalDispatchQuery.java
core/trino-main/src/test/java/io/trino/execution/TestCreateTableTask.java
core/trino-main/src/test/java/io/trino/execution/TestCreateViewTask.java
core/trino-main/src/test/java/io/trino/execution/TestPrepareTask.java
core/trino-parser/src/main/java/io/trino/sql/tree/CreateTable.java
core/trino-parser/src/main/java/io/trino/sql/tree/CreateTableAsSelect.java
core/trino-parser/src/main/java/io/trino/sql/tree/CreateView.java
core/trino-parser/src/main/java/io/trino/sql/tree/Explain.java
core/trino-parser/src/main/java/io/trino/sql/tree/ExplainAnalyze.java
core/trino-parser/src/main/java/io/trino/sql/tree/Insert.java
core/trino-parser/src/main/java/io/trino/sql/tree/Prepare.java
core/trino-parser/src/main/java/io/trino/sql/tree/ShowStats.java
core/trino-parser/src/test/java/io/trino/sql/TestSqlFormatter.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
service/trino-verifier/src/main/java/io/trino/verifier/QueryRewriter.java

Remove deprecated constructors from some statements

---

core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java
core/trino-main/src/main/java/io/trino/operator/SpoolingController.java

Fix spooling metrics and memory accounting

---

.mvn/jvm.config

Do not warn on Unsafe usage in JDK 24 while using maven

---

docs/src/main/sphinx/connector/bigquery.md
docs/src/main/sphinx/connector/snowflake.md
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/JdkCompatibilityChecks.java
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/TestJdkCompatibilityChecks.java
plugin/trino-bigquery/pom.xml
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowBufferAllocator.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
plugin/trino-openlineage/pom.xml
plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/OpenSearchClient.java
plugin/trino-snowflake/pom.xml
plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClientModule.java
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-all/jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-snowflake/jvm.config

```markdown
* BREAKING: Require `--sun-misc-unsafe-memory-access=allow` while running Trino server ({issue}`issuenumber`)
```

Update dependencies (w/ Jackson 2.19.0)

---

plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPagesStore.java

Fix memory calculation for already purged table

---

docs/src/main/sphinx/release/release-475.md

Fix a wrong link in 475 release notes

---

plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergAvroPageSource.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TypeConverter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/SigV4AwsProperties.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/HiveSchemaUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/OrcTypeConverter.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestTrinoHiveCatalogWithHiveMetastore.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/util/EqualityDeleteUtils.java
plugin/trino-iceberg/src/test/java/org/apache/iceberg/snowflake/TestTrinoSnowflakeCatalog.java
pom.xml
testing/trino-faulttolerant-tests/pom.xml
testing/trino-tests/pom.xml

Update Iceberg to 1.9.0

---

client/trino-client/src/main/java/io/trino/client/QueryDataJacksonModule.java
client/trino-client/src/main/java/io/trino/client/spooling/DataAttributes.java
client/trino-client/src/main/java/io/trino/client/spooling/EncodedQueryData.java
client/trino-client/src/main/java/io/trino/client/spooling/InlineSegment.java
client/trino-client/src/main/java/io/trino/client/spooling/SpooledSegment.java
client/trino-client/src/test/java/io/trino/client/spooling/TestSpoolingDataSerialization.java

Simplify and test segment serialization/deserialization

---

core/trino-main/src/main/java/io/trino/operator/InterpretedHashGenerator.java

Remove unused InterpretedHashGenerator#hashPosition method

---

core/trino-main/src/main/java/io/trino/server/NodeStateManager.java
core/trino-main/src/test/java/io/trino/server/TestNodeStateManager.java

Graceful shutdown logic compared previous nodestate instead of new `SHUTTING_DOWN` nodestate and in effect it never waited in the `waitActiveTasksToFinish`. This behavior has been recreated and is covered by the new test.
NodeState is now correctly assigned before starting the shutdown sequence.
Fixes: https://github.com/trinodb/trino/issues/25690
```markdown
```

Fix graceful shutdown

---

core/trino-main/src/test/java/io/trino/server/TestNodeStateManager.java

Looks like timeouts are too strict. Increased values and corrected comment. 
https://github.com/trinodb/trino/issues/25705
```markdown
```

Flaky TestNodeStateManager Add some slack to wait time

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestingPolarisCatalog.java
pom.xml

Update docker-images to 112

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemMinIo.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorage.java
plugin/trino-functions-python/pom.xml
plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/NessieContainer.java
plugin/trino-opensearch/pom.xml
plugin/trino-redis/pom.xml
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergNessie.java

Update dependencies + S3 integrity improvements

---

core/trino-web-ui/src/main/resources/webapp-preview/README.md

it was renamed `PreviewUiQueryRunner` -> `WebUiPreviewQueryRunner` (https://github.com/trinodb/trino/commit/9327535352e386a84bda344681c9c783108b3daa)
and then moved here https://github.com/trinodb/trino/commit/9d58e58b07fcc559cbb46819121a8391d829fffb
https://github.com/trinodb/trino/issues/22697

Fix class name in preview Web UI README

---

pom.xml

Update docker-images to 113

---

pom.xml

Update project dependencies

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastore.java

Implement streamRelationColumns in Delta Lake

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java

Prune source page to consistent with expected channels in Delta Lake

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Extracted fom https://github.com/trinodb/trino/pull/22096

Run Iceberg connector tests with more parallelism

---

core/trino-main/src/test/java/io/trino/operator/scalar/TestJsonStringArrayExtractScalar.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRewriteExcludeColumnsFunctionToProjection.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeTableMetadataScheduler.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveGlueMetadataListing.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveConcurrentModificationGlueMetastore.java
plugin/trino-loki/src/test/java/io/trino/plugin/loki/TestLokiIntegration.java
pom.xml

It's way too easy for these to creep in via auto-imports in IDEs.
Also added an enforcer rule which will prevent new additions.

Use non-shaded Guava collections

---

core/trino-main/src/main/java/io/trino/server/HttpRequestSessionContextFactory.java

A [prior change ](https://github.com/trinodb/trino/commit/3b251c6015b0b5641108aa70fa3b3e2a9ee97f43)inadvertently disrupted the contract for propagating the intended role from the engine to plugins. 
This commit reinstates the expected behaviour, ensuring that the desired role is correctly enabled. While this change does not directly affect the project, it corrects functionality for third-party plugins that depend on this specific behaviour.
```markdown
```

Restore SelectedRole propagation through identity enabled roles

---

pom.xml

Update Jetty & AWS SDK v2

---

core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4
core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
core/trino-parser/src/main/java/io/trino/sql/tree/Query.java
core/trino-parser/src/main/java/io/trino/sql/tree/QuerySpecification.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestStatementBuilder.java

Various code cleanups

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/OAuth2SecurityProperties.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java

Iceberg 1.9.0 fixes

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java

* Aside from `applyFilter`, manifests are also enumerated during the process of optimizing and removing orphan files.
```markdown
```

Handle filesystem errors when reading Iceberg manifests

---

pom.xml

This keeps Jackson 2.19.0
```markdown
```

Update airbase to 261

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSink.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ReusableConnectionFactory.java

Check whether connection is closed before closing

---

pom.xml

Oracle JDBC driver to 23.8.0.25.04

---

docs/src/main/sphinx/object-storage/file-system-s3.md
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemConfig.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemAwsS3.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemConfig.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemS3Mock.java

Add signer type to native s3 filesystem

---

client/trino-cli/pom.xml
plugin/trino-openlineage/pom.xml
pom.xml

Update dependencies (w/ hibernate validator 9.0.0)

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSource.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcPageSource.java

In case a direct executor is used, the executeQuery call should happen in getNextSourcePage rather than constructor
Follow-up from https://github.com/trinodb/trino/pull/25835
```markdown
```

Move executeQuery call to JdbcPageSource#getNextSourcePage

---

plugin/trino-elasticsearch/pom.xml
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/AwsRequestSigner.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/ElasticsearchClient.java
plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchServer.java
plugin/trino-opensearch/pom.xml
plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/AwsRequestSigner.java
plugin/trino-opensearch/src/main/java/io/trino/plugin/opensearch/client/OpenSearchClient.java
plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/TestPasswordAuthentication.java

Replace usages of AWS SDK V1 with AWS SDK V2 in Elasticsearch and OpenSearch

---

core/trino-main/src/main/java/io/trino/sql/planner/AdaptivePlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmenter.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AdaptivePartitioning.java
core/trino-main/src/main/java/io/trino/sql/planner/sanity/TableExecuteStructureValidator.java
testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/hive/TestHiveRuntimeAdaptivePartitioningFaultTolerantExecutionConnectorTest.java

```markdown
* Fix a bug when queries could fail with `fault_tolerant_execution_runtime_adaptive_partitioning_enabled` set to true . ({issue}`25870`)
```

Adaptive planner fixes

---

pom.xml

Update Iceberg to 1.9.1

---

core/trino-main/src/main/java/io/trino/operator/OperatorFactories.java
core/trino-main/src/main/java/io/trino/operator/join/unspilled/LookupJoinOperatorFactory.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
core/trino-main/src/test/java/io/trino/operator/join/unspilled/BenchmarkHashBuildAndJoinOperators.java
core/trino-main/src/test/java/io/trino/operator/join/unspilled/JoinTestUtils.java
core/trino-main/src/test/java/io/trino/operator/join/unspilled/TestHashJoinOperator.java

Remove unused code from LookupJoinOperatorFactory

---

client/trino-client/src/main/java/io/trino/client/QueryData.java

Ignore rowsCount during serialization

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperationsProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergTableOperationsProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperationsProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcTableOperationsProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/IcebergNessieTableOperationsProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/snowflake/SnowflakeIcebergTableOperationsProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/fileio/ForwardingFileIo.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMergeAppend.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcMetricsCollection.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/fileio/TestForwardingFileIo.java

Improve support for use_file_size_from_metadata in Iceberg metadata IO

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergAvroFileWriter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergParquetFileWriter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/RegisterTableProcedure.java

Improve query error classification for IO failures

---

core/trino-main/src/main/java/io/trino/server/protocol/ExecutingStatementResource.java
core/trino-main/src/main/java/io/trino/server/protocol/JsonBytesQueryDataProducer.java
core/trino-main/src/main/java/io/trino/server/protocol/JsonEncodingUtils.java
core/trino-main/src/main/java/io/trino/server/protocol/Query.java
core/trino-main/src/main/java/io/trino/server/protocol/QueryDataProducer.java
core/trino-main/src/main/java/io/trino/server/protocol/QueryDataProducerFactory.java
core/trino-main/src/main/java/io/trino/server/protocol/QueryResultRows.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingQueryDataProducer.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingServerModule.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/encoding/JsonQueryDataEncoder.java

Simplify query data producer instantiation

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestCloseIdleWriters.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestCloseIdleWriters.java

fixes https://github.com/trinodb/trino/issues/21078

Unflake testCloseIdleWriters

---

core/trino-main/src/main/java/io/trino/testing/MaterializedResult.java
core/trino-main/src/main/java/io/trino/testing/PlanTester.java
core/trino-main/src/main/java/io/trino/testing/TestingDirectTrinoClient.java
core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java
testing/trino-testing/src/main/java/io/trino/testing/H2QueryRunner.java

Minor testing improvements

---

.github/workflows/ci.yml
docs/src/main/sphinx/connector/delta-lake.md
testing/trino-product-tests-groups/src/main/java/io/trino/tests/product/TestGroups.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeDatabricks164.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/SuiteDeltaLakeDatabricks164.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCaseInsensitiveMapping.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeChangeDataFeedCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCheckpointsCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCreateTableAsSelectCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeInsertCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeSelectCompatibility.java

Add support for Databricks 16.4 LTS environment to product tests

---

.github/bin/redshift/setup-aws-redshift.sh

Switch redshift node type to ra3.large

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/IcebergFunctionProvider.java

`bucket` function in `IcebergFunctionProvider` would be `deterministic`

Fix deterministic of system bucket function in iceberg

---

plugin/trino-hive/pom.xml

Such a test doesn't exist in the current codebase. 

Remove redundant test exclusion

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/AcidInfo.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceProvider.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplit.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitSource.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveWriterFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveSplit.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcDeletedRows.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OriginalFilesUtils.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/AsyncQueue.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveBucketing.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/InternalHiveSplitFactory.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBackgroundHiveSplitLoader.java

Convert some classes to record in Hive connector

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java

Fix variable name

---

docs/src/main/sphinx/admin/properties-http-client.md

Fix config property in http-client documentation

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastore.java

Bind Node instead of NodeManager in TestDeltaLakeGlueMetastore

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TemporalTimeTravelUtil.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java

```markdown
* Fix delta lake connector not closing resource streams properly ({issue}`issuenumber`)
```

Close resource streams to prevent leaks

---

plugin/trino-memory/src/main/java/io/trino/plugin/memory/TableInfo.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java

Code clean ups in Memory Connector

---

lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileSystemFactory.java
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileSystemModule.java

Fixes https://github.com/trinodb/trino/issues/26120
```markdown
* Prevent creating multiple Alluxio client which can cause excessive resource usage ({issue}`issuenumber`)
```

Create Alluxio client once

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/StaticTokenAwareMetastoreClientFactory.java

Fix typo in StaticTokenAwareMetastoreClientFactory

---

plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java

Fixes CI failure https://github.com/trinodb/trino/actions/runs/16059706453/job/45322695138

Fix error assertion message for snowflake null

---

client/trino-cli/src/main/java/io/trino/cli/Completion.java
client/trino-cli/src/main/java/io/trino/cli/InputReader.java

```markdown
* Use alt+up/alt+down to move through the history ({issue}`issuenumber`)
```

CLI improvements

---

pom.xml

Update ErrorProne rules

---

client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
client/trino-client/src/test/java/io/trino/client/TestRetry.java

Include additional client failure information in the exception

---

.mvn/wrapper/maven-wrapper.properties

Update Maven to 3.9.11

---

docs/src/main/sphinx/object-storage/file-system-s3.md

Document s3.cross-region-access config property

---

pom.xml

Relates to https://lists.apache.org/thread/6qv2p68dfw6pvk6ndynkjkb1md3l0swg

Update Iceberg to 1.9.2

---

core/trino-spi/src/main/resources/io/trino/spi/type/zone-index.properties
core/trino-spi/src/test/java/io/trino/spi/type/TestTimeZoneKey.java

[tzdata2025b](https://lists.iana.org/hyperkitty/list/tz-announce@iana.org/thread/6JVHNHLB6I2WAYTQ75L6KEPEQHFXAJK3/) added America/Coyhaique time zone.

Add America/Coyhaique time zone

---

core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-main/src/test/java/io/trino/connector/MockConnectorColumnHandle.java
core/trino-main/src/test/java/io/trino/connector/MockConnectorInsertTableHandle.java
core/trino-main/src/test/java/io/trino/connector/MockConnectorOutputTableHandle.java
core/trino-main/src/test/java/io/trino/connector/TestingTableFunctions.java
core/trino-main/src/test/java/io/trino/execution/TestSqlTaskExecution.java
core/trino-main/src/test/java/io/trino/execution/TestingFailureInjector.java
core/trino-main/src/test/java/io/trino/operator/GroupByHashYieldAssertion.java
core/trino-main/src/test/java/io/trino/operator/TestDistinctLimitOperator.java
core/trino-main/src/test/java/io/trino/operator/TestHashAggregationOperator.java
core/trino-main/src/test/java/io/trino/operator/TestMarkDistinctOperator.java
core/trino-main/src/test/java/io/trino/operator/TestRowNumberOperator.java
core/trino-main/src/test/java/io/trino/operator/TestTopNRankingOperator.java
core/trino-main/src/test/java/io/trino/server/TestSliceSerialization.java
core/trino-main/src/test/java/io/trino/server/remotetask/TestHttpRemoteTask.java
core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
core/trino-main/src/test/java/io/trino/sql/planner/TestEffectivePredicateExtractor.java
core/trino-main/src/test/java/io/trino/sql/planner/TestTableScanRedirectionWithPushdown.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestMultipleDistinctAggregationsToSubqueries.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneTableScanColumns.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushJoinIntoTableScan.java
core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesScaledWriters.java
core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddLocalExchangesForTaskScaleWriters.java
core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestLimitMaxWriterNodesCount.java
core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestRemoveEmptyUnionBranches.java
testing/trino-tests/src/test/java/io/trino/execution/TestTableRedirection.java

Convert trino-main test classes to record

---

core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java

Do not inline tail, small pages if inilining is disabled

---

plugin/trino-lakehouse/src/test/java/io/trino/plugin/lakehouse/TestLakehousePlugin.java

Add TestLakehousePlugin

---

plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/AvroSchemaConverter.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentSchemaRegistryConfig.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentSessionProperties.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/EmptyFieldStrategy.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestAvroSchemaConverter.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestConfluentSchemaRegistryConfig.java

Make EmptyFieldStrategy as a common enum

---

docs/src/main/sphinx/admin/openmetrics.md

Fix for "sbsuer" used as a sample username, plus copy edit on the same lines.
None.
```markdown
```

Doc only: fix sbsuer typo and minor copy edit

---

docs/src/main/sphinx/object-storage/file-system-azure.md
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemConfig.java

Document azure.multipart-write-enabled config property

---

core/trino-main/src/main/java/io/trino/operator/project/ConstantPageProjection.java
core/trino-main/src/main/java/io/trino/operator/project/DictionaryAwarePageProjection.java
core/trino-main/src/main/java/io/trino/operator/project/GeneratedPageProjection.java
core/trino-main/src/main/java/io/trino/operator/project/InputPageProjection.java
core/trino-main/src/main/java/io/trino/operator/project/PageProjection.java
core/trino-main/src/main/java/io/trino/sql/gen/PageFunctionCompiler.java
core/trino-main/src/test/java/io/trino/operator/project/TestDictionaryAwarePageProjection.java
core/trino-main/src/test/java/io/trino/operator/project/TestPageProcessor.java

Remove unused io.trino.operator.project.PageProjection#getType

---

pom.xml

Update airbase, airlift, AWS SDK v2

---

plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java

Implement streamRelationColumns in ElasticSearch

---

core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2AuthenticationSupportModule.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2TokenExchangeResource.java

Use separate executors for OAuth2 endpoints

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogEntries.java

The iterator was not closed when caching transaction log entries, which could lead to resource leaks
```markdown
```

Fix closing `TransactionLogEntryIterator`

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergInputInfo.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergInputInfo.java

Expose format version to IcebergInputInfo

---

docs/src/main/sphinx/connector/oracle.md

Docs for Oracle connector is a bit misleading at it mentions we support `TopN` but we don't support it eyt. 
```markdown
```

Fix documentation for Oracle connector

---

.github/actions/compile-commit/action.yml

Compile commits faster

---

pom.xml

Remove unused glue v1 dependency

---

.github/bin/free-disk-space.sh

Benchmark free disk space

---

core/trino-main/src/main/java/io/trino/sql/rewrite/DescribeInputRewrite.java
core/trino-main/src/main/java/io/trino/sql/rewrite/DescribeOutputRewrite.java

Just some minor typos
( x ) This is not user-visible or is docs only, and no release notes are required.

Fix typos in describe method names

---

plugin/trino-faker/pom.xml
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java
plugin/trino-ranger/pom.xml
pom.xml

Minor updates

---

lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsAccessTokenAuth.java
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsAuth.java
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsDefaultAuth.java
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemModule.java
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsStorageFactory.java
lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/AbstractTestGcsFileSystem.java
lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemConfig.java
lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsStorageFactory.java

Clean up `GcsStorageFactory` to improve readability and expandability of GCS authentication
```markdown
```

Introduce `GcsAuth` interface for gcs filesystem

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeCompatibility.java
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-compatibility/config-post477.properties

Tested with:
```
./testing/bin/ptl test run --environment singlenode-compatibility --option compatibility.testVersion=477 --option compatibility.testDockerImage=trinodb/trino:477 -- -g configured_features,hive_view_compatibility
```
```markdown
```

Fix suite-compatibility for Trino 477

---

core/trino-main/src/main/java/io/trino/operator/project/SelectedPositions.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureInputFile.java
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsInputFile.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3InputFile.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/cache/CacheInputFile.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/tracing/TracingInputFile.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/tracking/TrackingInputFile.java

Add toString implementations

---

.github/config/labeler-config.yml
plugin/trino-lakehouse/pom.xml
plugin/trino-lakehouse/src/test/java/io/trino/plugin/lakehouse/LakehouseQueryRunner.java

Minor improvement in Lakehouse connector

---

.github/workflows/ci.yml

Disable running redshift cloud tests

---

pom.xml

Update google-cloud-sdk to 26.69.0

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java

Fix indentation in testVariantReadNull test

---

core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
core/trino-main/src/main/java/io/trino/execution/QueryStateTimer.java

Random improvements here and there

---

testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-all/jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-snowflake/jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/trino/etc/jvm.config

Removed flag is passed via launcher
```markdown
```

Cleanup jvm flags

---

lib/trino-parquet/src/main/java/io/trino/parquet/writer/StructColumnWriter.java
lib/trino-record-decoder/src/test/java/io/trino/decoder/json/JsonFieldDecoderTester.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/FileSystemTransactionLogWriter.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/crypto/EnvironmentDecryptionKeyRetriever.java

Use methods in Guava Preconditions

---

plugin/trino-openlineage/pom.xml
pom.xml

Update minor deps

---

docs/src/main/sphinx/release/release-477.md

Minor fixes to 477 release notes

---

core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
core/trino-spi/src/main/java/io/trino/spi/resourcegroups/SelectionCriteria.java

Remove stale comment and deprecated constructor from SPI

---

core/trino-main/src/main/java/io/trino/execution/StageId.java
core/trino-main/src/main/java/io/trino/execution/TaskId.java
core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java
core/trino-main/src/test/java/io/trino/execution/TestMemoryRevokingScheduler.java
core/trino-main/src/test/java/io/trino/server/TestBasicQueryInfo.java
core/trino-main/src/test/java/io/trino/server/remotetask/TestHttpRemoteTask.java
core/trino-spi/src/main/java/io/trino/spi/QueryId.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
plugin/trino-ranger/src/main/java/io/trino/plugin/ranger/RangerSystemAccessControl.java
testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
testing/trino-tests/src/test/java/io/trino/execution/TestQueryCompletedEvent.java
testing/trino-tests/src/test/java/io/trino/memory/TestClusterMemoryLeakDetector.java

Inline fullId to toString method

---

pom.xml

Upgrade airbase to 313
