plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/FileSystemLayout.java
plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/FileSystemSegmentPruner.java
plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/FileSystemSpooledSegmentHandle.java
plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/FileSystemSpoolingConfig.java
plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/FileSystemSpoolingManager.java
plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/FileSystemSpoolingModule.java
plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/PartitionedFileSystemLayout.java
plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/PartitionedLayoutConfig.java
plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/SimpleFileSystemLayout.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/AbstractFileSystemSegmentPrunerTest.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/AbstractFileSystemSpoolingManagerTest.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/TestFileSystemSpooledSegmentHandle.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/TestFileSystemSpoolingConfig.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/TestFileSystemSpoolingManagerLocalStack.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/TestFileSystemSpoolingManagerMinio.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/TestPartitionedFileSystemLayout.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/TestPartitionedLayoutConfig.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/TestPartitionedLayoutFileSystemSegmentPruner.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/TestSimpleFileSystemLayout.java
plugin/trino-spooling-filesystem/src/test/java/io/trino/spooling/filesystem/TestSimpleLayoutFileSystemSegmentPruner.java

Add configurable spooling filesystem layout implementations

---

core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
core/trino-spi/src/main/java/module-info.java

The annotation libraries do not need to be transitive dependencies, and the logging usage isn't needed at all.

Cleanup SPI Java module dependencies 

---

core/trino-main/src/main/java/io/trino/sql/ir/optimizer/rule/SimplifyRedundantCase.java
core/trino-main/src/test/java/io/trino/sql/ir/optimizer/TestSimplifyRedundantCase.java
core/trino-main/src/test/java/io/trino/sql/query/TestIssue23787.java

Expressions such as:
```
CASE
WHEN <e1> THEN <boolean>
WHEN <e2> THEN <boolean>
...
ELSE <boolean>
END
```
were being incorrectly optimized. The terms in the rewritten boolean expression need to reflect the fact that all the preceding conditions should've evaluated to false in order for a given condition to evaluate to true. The optimization was ignoring them, which could result in incorrect results when the conditions are not exclusive.
For example:
```
CASE
WHEN a OR b THEN false
WHEN a OR c THEN true
END
```
Previously, it was being rewritten as:
```
(a OR c) ≡ true
```
However, if `a` is true, then the first branch of the CASE should be evaluated and the expression should return false.
Fixes https://github.com/trinodb/trino/issues/23787
(x) Release notes are required, with the …

Fix incorrect simplification of CASE with constant boolean results

---

docs/src/main/sphinx/admin/resource-groups.md
docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-462.md

Assemble the release notes for the upcoming Trino 462 release.
See https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A462
* #23748 ✅ rn ✅ docs
* #23743 ✅ rn ✅ docs
* #23611 ✅ rn ✅ docs
* #23751 ✅ rn ✅ docs
* #23737 ✅ rn ✅ docs
* #23754 ✅ rn ✅ docs
* #23755 ✅ rn ✅ docs
* #23302 ✅ rn ✅ docs
* #23757 ✅ rn ✅ docs
* #23769 ✅ rn ✅ docs
* #23774 ✅ rn ✅ docs
* #23771 ✅ rn ✅ docs
* #23752 ✅ rn ✅ docs
* #22632 ✅ rn ✅ docs
* #23727 ✅ rn ✅ docs
* …

Add Trino 462 release notes

---

docs/src/main/sphinx/connector/elasticsearch.md
docs/src/main/sphinx/connector/opensearch.md

For TLS to OpenSearch and Elastisearch only P12 (PKCS) is supported. Not PEM as for the TLS setup.
See discussion in https://github.com/trinodb/trino/issues/23402
Fyi @ilsaloving

Correct docs about key format

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorFactory.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPageSourceProvider.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryQueryPageSource.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitSource.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageArrowPageSource.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageAvroPageSource.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ForBigQueryPageSource.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQuerySplitManager.java

Avoid blocking in BigQuery split and page source constructors, which execute queries, by starting them in a background thread. This should reduce congestion on busy clusters. 

Avoid blocking in BigQuery split and page sources

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Position deletes are local to a partition. OPTIMIZE supports only enforced predicates which select whole partitions. Therefore, we can clean up position deletes in OPTIMIZE when there are no path or file_modified_time predicates
```markdown
* Clean up position delete files when OPTIMIZE is run on a subset of the table's partitions. ({issue}`23801`)
```

Clean up position deletes when optimizing a subset of partitions

---

core/trino-web-ui/src/main/resources/webapp/assets/trino.css

Move timestamp to the left

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantDistinctAggregation.java
core/trino-main/src/main/java/io/trino/sql/planner/plan/AggregationNode.java

Adds missing comment and check for the grouping count set as a follow up from https://github.com/trinodb/trino/pull/23776

Cleanup AggreggationNode#producesDistinctRows

---

docs/src/main/sphinx/connector/iceberg.md
docs/src/main/sphinx/object-storage/metastores.md

Document missing Iceberg properties

---

client/trino-cli/src/main/java/io/trino/cli/FormatUtils.java
client/trino-cli/src/test/java/io/trino/cli/TestFormatUtils.java

`FormatUtils.formatDataRate()` contains the following code:
```java
long rate = Math.round(dataSize.toBytes() / duration.getValue(SECONDS));
if (Double.isNaN(rate) || Double.isInfinite(rate)) {
rate = 0;
}
```
The test can never evaluate as `true`, since both functions will return false for any `long`.
The correct test is:
```java
if (rate == Long.MAX_VALUE) {
rate = 0;
}
```
It's not necessary to test for `Long.MIN_VALUE`, since neither `dataSize` nor `duration` can be negative.
I added a new class, `TestFormatUtils` to test both this fix and the rest of `FormatUtils`. The tests for this change are:
```java
assertEquals(FormatUtils.formatDataRate(DataSize.ofBytes(1), Duration.valueOf("0s"), false), "0B");
assertEquals(FormatUtils.formatDataRate(DataSize.ofBytes(1), …
```

Fix test for invalid rate in FormatUtils.formatDataRate()

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/TrinoCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/SchemaInitializer.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogNestedNamespaceConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/org/apache/iceberg/rest/DelegatingRestSessionCatalog.java

Fixes #22916 
```markdown
* Add support for nested namespaces in REST catalog. ({issue}`22916`)
```

Add support for nested namespaces in Iceberg REST catalog

---

docs/src/main/sphinx/client.md

see title, there is no release of the client yet but very soon and code is already maintained in that repo so we should link to it now.
na

Add link to js client in docs

---

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
core/trino-main/src/test/java/io/trino/sql/query/TestRowPatternMatchingInWindow.java
docs/src/main/sphinx/functions/window.md

Issue #23742 describes unexpected behavior of the `lag` function when used with a window framing clause. It turns out that the problem does not exist in the current version of Trino. This PR adds a test to confirm this. Additionally, it adds a check to verify that the window framing clause is not used with the `ntile`, `rank`, `dense_rank`, `percent_rank`, `cume_dist`, and `row_number` functions, which aligns with the SQL specification.
Fixes #23742
```markdown
* Disallow the window framing clause for {func}`ntile`, {func}`rank`, {func}`dense_rank`, {func}`percent_rank`, …
```

Disallow window framing clause for certain window functions

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDeleteCompatibility.java

Fixes https://github.com/trinodb/trino/issues/23620
When deletion vectors were enabled code that is supposed to create `update_preimage` was not executed. 
```markdown
* Add support for writing change data feed when deletion vector is enabeld. ({(https://github.com/trinodb/trino/issues/23620)}`23620`)
```

Fix change data feed with delete vectors

---

pom.xml

Enable errorprone PatternMatchingInstanceof

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java

This PR adds support for configuring max rows per "row group" in an ORC file via a session property – today this is configurable only at the catalog level. This is useful for to make it easy for different jobs in the same catalog to write files that may have different optimal row group sizes based on the shape of the underlying data they're writing. 
Also, I've submitted my CLA request via email, but looks like it hasn't been approved just yet.
Fixes https://github.com/trinodb/trino/issues/23722
```markdown
* Add support for configuring max rows per row-group in the ORC …
```

Add session property to configure ORC rowGroupMaxRowCount in Iceberg

---

docs/src/main/sphinx/security/file-system-access-control.md

This PR separates the SQL statements that were incorrectly formatted within a code block
```markdown
```

Separate sql statements in code block

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/procedure/TestIcebergAddFilesProcedure.java

```markdown
* Rename `iceberg.add_files-procedure.enabled` config property to `iceberg.add-files-procedure.enabled`. ({issue}`issuenumber`)
```

Rename `iceberg.add_files-procedure.enabled` to `iceberg.add-files-procedure.enabled`

---

core/docker/default/etc/log.properties
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Kafka.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeOauth2.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeOauth2HttpProxy.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeOauth2HttpsProxy.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeOauth2Refresh.java
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/trino/etc/log.properties

Reduce logging noise

---

core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java

E.g.
```
Fragment 1 [HASH]
CPU: 384.09ms, Scheduled: 439.31ms, Blocked 2.44s (Input: 1.24s, Output: 0.00ns), Input: 1500816 rows (25.76MB); per task: avg.: 1500816.00 std.dev.: 0.00, Output: 1500000 rows (25.75MB)
Peak memory usage: 29.70MB, Tasks count: 1; per task: max: 29.70MB
Output layout: [orderkey, count]
Aggregate[type = FINAL, keys = [orderkey]]
│   Layout: [orderkey:bigint, count:bigint]
│   Estimates: {rows: 1498948 (25.73MB), cpu: 103.02M, memory: 25.73MB, network: 0B}
│   CPU: 235.00ms (20.12%), Scheduled: 266.00ms (15.09%), Blocked: 0.00ns (0.00%), Output: 1500000 rows (25.75MB)
│   Input avg.: 750408.00 rows, Input std.dev.: 0.03%
│   count := count(count_0)
```
( …

Print peak memory usage in EXPLAIN ANALYZE output

---

plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClient.java
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/BaseSingleStoreTypeMapping.java
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreLatestTypeMapping.java
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreTypeMapping.java
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestingSingleStoreServer.java

Fixes #23780
```markdown
* TBD. ({issue}`23780`)
```

Fix incorrect string length definition in SingleStore 8.x

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-463.md

Assemble the release notes for the upcoming Trino 463 release.
See https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A463
* #23811 ✅ rn ✅ docs
* #23809 ✅ rn ✅ docs
* #23564 ✅ rn ✅ docs, see #23821
* #23741 ✅ rn ✅ docs
* #23816 ✅ rn ✅ docs
* #23459 ✅ rn ✅ docs
* #23801 ✅ rn ✅ docs
* #23821 ✅ rn ✅ docs
* #23744 ✅ rn ✅ docs
* #23825 ✅ rn ✅ docs
* #23806 ✅ rn ✅ docs
* #23393 ✅ rn ✅ docs
* #23777 ✅ rn ✅ docs
* #21000 ✅ rn ✅ docs
* #15337 ✅ …

Add Trino 463 release notes

---

docs/src/main/sphinx/admin.md
docs/src/main/sphinx/connector.md
docs/src/main/sphinx/installation/deployment.md

* see commit messages
* provides better visibility for the fact that there are a lot of pages with more details without messing up the left hand nav on properties
* improve linkage to concepts page and content about data sources, catalogs, and connectors
na

List all properties docs on admin page

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergTableOperations.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogSkipArchive.java

This is AWS Athena behavior and resetting location may break Glue crawlers.  
We should keep the existing values as much as possible. 
Additionally, set a table location when creating new tables in Glue. 

Keep table location when updating Glue tables in Iceberg

---

.mvn/modernizer/violations.xml
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/v1/converter/GlueInputConverter.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/v1/converter/GlueToTrinoConverter.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/v1/TestGlueToTrinoConverter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergTableOperations.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java

Disallows calling `Table.getStorageDescriptor` by modernizer because it returns null and it's easy to forget. 
Follow-up of #23870

Add modernizer rule to disallow Glue `Table.getStorageDescriptor` method

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenTaskSourceFactory.java

We use different configuration of HashSplitAssigner based on partitining handle used by source stage. We want to determine if we are in write stage or not. The logic was wrong.

Fix categerization of partitioning handles for writer stage

---

plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListenerConfig.java
plugin/trino-mysql-event-listener/src/test/java/io/trino/plugin/eventlistener/mysql/TestMysqlEventListenerConfig.java

Add `@ConfigSecuritySensitive` to `mysql-event-listener.db.url` config property.
The value contains password in most cases. 

Add `@ConfigSecuritySensitive` to mysql-event-listener.db.url

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java

We don't need to hold lock on SemiTransactionalHiveMetastore object for remote calls which just read metadata. Listing views/tables/databases on metastore can be potentially slow. Holding lock blocks cleanupQuery, which prevents QueryTracker#enforceTimeLimits from failing queries which exceed time limit.
```markdown
```

Reduce synchronization for metadata calls in SemiTransactionalHiveMetastore

---

docs/src/main/sphinx/release/release-440.md

The linked airlift PR removed the `http-client.max-connections` property. This was reflected in the Trino documentation with #20101 but should have been given a breaking change since the property was applied by some users.
#20966 
#20797 
(x) Release notes are required, with the following suggested text: Note in PR contents
```markdown
```

Add note about removed *.http-client.max-connections properties

---

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientModule.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoTlsConfig.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoTlsModule.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoTlsConfig.java

Rename Ssl to Tls in MongoDB connector

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java

Fixes: https://github.com/trinodb/trino/issues/21862
Currently test repetition runs in parallel which can cause query exceed 20s timeout, it's especially visible in case of Glue tests.
Analysis showed that most time is spend on:
1. Waiting for execution to be scheduled. For some queries time between beginMerge and finishMerge can vary from 3s to 16s.
2. Time of `glueClient.updateTable`, when executed in parallel and failing update throws `ConcurrentModificationException`, is about 10s
If query which consumed time on finishMerge also encounters ConcurrentModificationException, 20s is exceeded and test fails.
Running tests sequentially removes first problem and makes test more reliable. …

Run testDeleteRowsConcurrently sequentially for better reliability

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystem.java

Without this, query will fail with S3 403 when listing objects in the buckets
(X ) Release notes are required. Please propose a release note for me.
```markdown
* Fix S3 file listing of buckets that enforce requester pays ({issue}`23906`)
```

Pass in request payer for ListObjectsV2Request

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitManager.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/StructLikeWrapperWithFieldIdToIndex.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestStructLikeWrapperWithFieldIdToIndex.java

Single file without a delete in a partition can't be optimized any further.
Avoiding rewriting such files improves the performance of OPTIMIZE on
large partitioned tables
Fixes https://github.com/trinodb/trino/issues/10785
```markdown
* Improve performance of OPTIMIZE on large partitioned tables. ({issue}`10785`)
```

Skip single file in a partition from OPTIMIZE

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/avro/AvroPageSourceFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/line/LinePageSourceFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/rcfile/RcFilePageSourceFactory.java

In AWS Athena, we currently support encrypting S3 objects using CSE-KMS. The size of these encrypted object will be greater than the size when unencrypted since padding will be added. The `input.readAllBytes();` function strips the padding from an encrypted object so we have to update the `length` variable as well if we create a new in memory input file.
```markdown
```
@nineinchnick @anusudarsan

Set length of avro and rc input file after memory input file is created

---

docs/src/main/sphinx/release/release-463.md

While HTTP/2 was supported before, now it is used by default with CLI as well as the JDBC driver.
As discussed with @wendigo and @martint in maintainer call .. do we need an entry in general since I think it might be enabled for all clients ... 
#23810 
One of the commits of https://github.com/trinodb/trino/pull/23857

Add 463 release notes entries

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystem.java

Quick follow up on the previous merged commit https://github.com/trinodb/trino/pull/23906. Find this request is also missing the requesterPay header. Also just double checked all the rest of s3 requests in this module and this should be the only one left.
```markdown
```

Pass in requestPayer for ListObjectsV2Request in listObjects method

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/procedure/TestIcebergMigrateProcedure.java

Previous logic was setting all columns as non-nullable which is not valid when the data contains nulls
```markdown
* Fix migrate for tables which contain NULLs. ({issue}`23928`)
```

Fix iceberg migrate to use nullable columns

---

docs/src/main/sphinx/connector.md
docs/src/main/sphinx/connector/removed.md
docs/src/main/sphinx/redirects.txt

atop and localfile connectors were recently removed. Users that look for the docs from an old link are now redirected to a dedicated page for removed connectors.
raptor connector was also removed but there were never docs.
The page can also be used for future removals.
#23550 
#23588 
#23551 
Going forward also
#23923 
#23791 

Add redirect for removed connectors

---

core/trino-main/src/main/java/io/trino/server/protocol/JsonArrayResultsIterator.java

When a page has fewer channels than output columns, log the full stack trace, and avoid producing an empty response. This makes debugging page sources easier.
This is the stack trace produced with this change:
```
io.trino.testing.QueryFailedException: Could not serialize column '_col0' of type 'bigint' at position 1:1
at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:134)
at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:565)
at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:548)
at io.trino.testing.QueryRunner.execute(QueryRunner.java:82)
at io.trino.plugin.redshift.RedshiftQueryRunner.verifyLoadedDataHasSameSchema(RedshiftQueryRunner.java:194)
... 9 more
Suppressed: …
```

Improve exception logging when serializing invalid pages

---

client/trino-client/src/main/java/io/trino/client/JsonDecodingUtils.java
client/trino-jdbc/src/main/java/io/trino/jdbc/AsyncResultIterator.java
core/trino-main/src/main/java/io/trino/operator/OutputSpoolingController.java
core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java
core/trino-main/src/main/java/io/trino/server/protocol/JsonArrayResultsIterator.java
core/trino-main/src/main/java/io/trino/server/protocol/QueryResultRows.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpooledQueryDataProducer.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingConfig.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingManagerBridge.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingServerModule.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/encoding/JsonQueryDataEncoder.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
core/trino-main/src/main/java/io/trino/testing/PlanTester.java
core/trino-main/src/test/java/io/trino/execution/TaskTestUtils.java
core/trino-main/src/test/java/io/trino/server/protocol/spooling/TestSpoolingConfig.java
core/trino-spi/src/main/java/io/trino/spi/protocol/SpoolingManager.java
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-postgresql-spooling/coordinator-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-postgresql-spooling/worker-config.properties

Improve JDBC performance + spooling polishing

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryColumnHandle.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryNamedRelationHandle.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTableHandle.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java

The current EXPLAIN with BigQuery connector is too verbose. 
Before:
```
Trino version: testversion
Fragment 0 [SOURCE]
Output layout: [regionkey, name, comment]
Output[columnNames = [regionkey, name, comment]]
│   Layout: [regionkey:bigint, name:varchar, comment:varchar]
│   Estimates: {rows: ? (?), cpu: 0, memory: 0B, network: 0B}
└─ TableScan[table = bigquery:BigQueryTableHandle[relationHandle=BigQueryNamedRelationHandle{remoteTableName=sep-bq-cicd.tpch.region, schemaTableName=tpch.region, type=TABLE, comment=Optional.empty}, constraint={BigQueryColumnHandle[name=regionkey, dereferenceNames=[], trinoType=bigint, bigqueryType=INT64, isPushdownSupported=true, mode=NULLABLE, subColumns=[], description=null, hidden=false]=[ SortedRangeSet[type=bigint, …
```

Simplify toString of BigQuery table and column

---

docs/.vale/config/vocabularies/Base/accept.txt
docs/src/main/sphinx/connector.md
docs/src/main/sphinx/connector/faker.md

Document the Faker connector

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowToPageConverter.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryTypeMapping.java

[Bigquery] Fix array data type column returning incorrect results when `bigquery.arrow-serialization.enabled` is enabled.
Diagnosis:
`((ListVector) vector).getDataVector();` seem to return data for whole column.
https://github.com/trinodb/trino/blob/0a72a7482d93aae62f1bbdd9dc5499859b214821/plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowToPageConverter.java#L247
```markdown
* Fix array data type column returning incorrect results when `bigquery.arrow-serialization.enabled` is enabled. ({issue}`23982`)
```

Fix incorrect query results for array type column in Bigquery with `bigquery.arrow-serialization.enabled` enabled

---

docs/src/main/sphinx/connector/vertica.md

According to @ebyhr the connector does not support `analyze` .. so I think that means it doesnt support stats either.. but this is kinda a guess.
Updated now to only remove the analyze stuff
Follow up to https://github.com/trinodb/trino/pull/23967#discussion_r1823511249

Fix table stats docs for Vertica

---

docs/src/main/sphinx/admin/properties-http-server.md
docs/src/main/sphinx/security/internal-communication.md

See title, adding since we are switching to HTTP/2 by default now and need to docs for switching back if desired.
After discussion with @electrum we decided to go ahead with the second commit and remove the info about manual config for internal TLS.
Related to #21793 

Update docs for internal communication

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-464.md

Assemble the release notes for the upcoming Trino 464 release.
See https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A464
* #23783 ✅ rn ✅ docs
* #23876 ✅ rn ✅ docs
* #23870 ✅ rn ✅ docs
* #23883 ✅ rn ✅ docs
* #23887 ✅ rn ✅ docs
* #23878 ✅ rn ✅ docs
* #23892 ✅ rn ✅ docs
* #23890 ✅ rn ✅ docs
* #23691 ✅ rn ✅ docs, update in #23901 
* #23762 ✅ rn ✅ docs
* #23903 ✅ rn ✅ docs
* #23895 ✅ rn ✅ docs
* #23912 ✅ rn ✅ docs
* #23908 ✅ rn ✅ docs
* …

Add Trino 464 release notes

---

docs/src/main/sphinx/release/release-464.md

Add BigQuery release notes entry for 464

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedGlueMetastoreWithTableRedirections.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueConverter.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/v1/converter/GlueToTrinoConverter.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestGlueConverter.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/v1/TestGlueToTrinoConverter.java

Don't attempt to read Delta Lake table metadata when performing table redirect to a different catalog. This allows redirecting from incomplete or invalid Delta Lake tables.
Without the fix, queries fail with:
```
io.trino.testing.QueryFailedException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Error: type expected at the position 0 of 'timestamp_ntz' but 'timestamp_ntz' is found.
at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:134)
at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:565)
at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:548)
at io.trino.testing.AbstractTestQueryFramework.computeActual(AbstractTestQueryFramework.java: …
```

Avoid failures when redirecting from incomplete/invalid Delta Lake tables

---

docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-hive/pom.xml
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveExecutionInterceptor.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastoreConfig.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/v1/GlueHiveMetastoreConfig.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/v1/GlueMetastoreModule.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/v1/SkipArchiveRequestHandler.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestGlueHiveMetastoreConfig.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestGlueHiveMetastoreSkipArchive.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/v1/TestGlueHiveMetastoreConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/IcebergGlueCatalogConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/IcebergGlueCatalogModule.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestingIcebergGlueCatalogModule.java

When set to true, updating tables in Glue does not create an archived
version of the table. Glue tables are updated during INSERT operations,
so this option can be used to avoid reaching the limit of table
versions, when executing many such operations.
In the second commit, I also added it to the legacy v1 Glue Metastore. I don't think it's needed there, it might help when migrating Iceberg from v1 Glue to the latest one, at least to avoid binding issues in Guice modules.
This is modeled after #14336
```markdown
```

Add `hive.metastore.glue.skip-archive` config option

---

plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java

Migrate test code to rely on AWS S3 v2 client because AWS S3 v1 is deprecated.
Deprecation notice in code:
```
WARN  main  com.amazonaws.util.VersionInfoUtils   The AWS SDK for Java 1.x entere
d maintenance mode starting July 31, 2024 and will reach end of support on December 31, 2025. For more information, see
https://aws.amazon.com/blogs/developer/the-aws-sdk-for-java-1-x-is-in-maintenance-mode-effective-july-31-2024/
You can print where on the file system the AWS SDK for Java 1.x core runtime is located by setting the AWS_JAVA_V1_PRIN
T_LOCATION environment variable or aws.java.v1.printLocation system property to 'true'.
This message can be disabled by setting the AWS_JAVA_V1_DISABLE_DEPRECATION_ANNOUNCEMENT environment variable or aws.ja
va.v1.disableDeprecationAnnouncement system …
```

Use AWS S3 v2 client for testing

---

docs/src/main/sphinx/connector/faker.md
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerConnector.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerFunctionProvider.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerFunctions.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerModule.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java

Add a `random_string` function in the Faker connector that makes it easier to test generator expressions, before using it in column properties.

Add a function for testing Faker expressions

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadataFactory.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableProperties.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestTrinoGlueCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestTrinoNessieCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java
plugin/trino-iceberg/src/test/java/org/apache/iceberg/snowflake/TestTrinoSnowflakeCatalog.java
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-spark-iceberg-jdbc-catalog/iceberg.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-spark-iceberg-rest/iceberg.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-spark-iceberg/iceberg.properties
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java

This PR allows us to pass through additional properties to Iceberg when creating a table in Trino.
The additional properties can be provided in the following format
```
extra_properties = MAP(ARRAY['extra.property.one', 'extra.property.two'], ARRAY['one', 'two'])
```
The extra properties will not be exposed in SHOW CREATE.
The purpose of this feature is to add properties that can be used by catalogs or other tools. For example, in Tabular, there is a [property to optimize tables](https://docs.tabular.io/en/table-properties.html#optimizer-properties-890). For our use case, we want to create our tables with the `optimizer.enabled` value set to False, and we cannot achieve this without a way to handle arbitrary properties.
Fixes #17427 …

Add extra_properties to iceberg table properties

---

core/trino-main/src/main/java/io/trino/operator/scalar/ArrayVectorFunctions.java

```markdown
* Add `cosine_similarity(array(double), array(double))`. ({issue}`issuenumber`)
```

Add cosine_similarity(array(double), array(double))

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryRpcConfig.java

This should help to deal with Flakiness on CI with transient: 'Service is unavailable. Please retry.'
```markdown
```

Increase allowed timeouts for BigQuery service

---

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/util/AutoCloseableCloser.java
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/util/TestAutoCloseableCloser.java

Synchronizes access to the internal structure of AutoCloseableCloser, which previously allowed racey access to the underlying Deque of registered entries.
This was mostly an issue in test methods that could run concurrently with one another.

Synchronize AutoCloseableCloser

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestHiveTypeTranslator.java

"fail() + catch" pattern in testing replaced with `assertThatThrownBy()` to improve readability. Functionality is identical, second `try-catch` block is unchanged so `addSuppressed()` still executes on a non-`TrinoException` exceptions.
Partially fixes readability issues raised in #6553

Replace "fail() + catch" pattern in HiveType testing

---

docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/OAuth2SecurityConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/OAuth2SecurityProperties.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestOAuth2SecurityConfig.java

This PR adds `iceberg.rest-catalog.oauth2.server-uri` property which serves the purpose of specifying the access token endpoint of IdP in Iceberg connector.
I'm setting it as a Draft as I'm not sure if more isn't required to implement this. I'm using this patch at my job and it works but we're also fairly new to Trino and Iceberg REST catalog
Fixes #23086 
```markdown
* Allow configuring an OAuth2 server URI with the `iceberg.rest-catalog.oauth2.server-uri` config property. ({issue}`23086`)
```

Add oauth2-server-uri support to Iceberg REST catalog

---

docs/src/main/sphinx/functions/geospatial.md
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/GeoFunctions.java
plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestGeoFunctions.java

Add support for parsing EKWB format in ST_GeomFromBinary
EWKB is a popular extension to WKB. 
Closes #23824
(x) Release notes are required, with the following suggested text: Add support for EWKB in ST_GeomFromBinary

Support reading geometries in EWKB format.

---

docs/src/main/sphinx/functions/array.md
docs/src/main/sphinx/functions/list-by-topic.md
docs/src/main/sphinx/functions/list.md
docs/src/main/sphinx/functions/math.md

See title, but we need to decide how to proceed .. do we want these docs in math.md or array.md? Do we want to link from one to the other? What do we want in terms of arguments .. use x y or the array double.
Follow up to #23964

Add docs for cosine_distance

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHive3OnDataLake.java

Hive 3 does not actually replace the content of the function
https://github.com/apache/hive/blob/rel/release-3.1.2/standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java#L9310
Fall-back to using two operations: drop function followed create function for effectively handling the replace operation for the function when working with Hive Metastore.
```markdown
* Use drop & create function when replacing an existing function backed by Hive Metastore  ({issue}`issuenumber`)
```

Use drop and create to replace a function on Hive Metastore

---

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryAvroConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Code cleanup in TestBigQueryAvroConnectorTest

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Follow-up of #20393
```markdown
* Add support for setting `extra_properties` table property. ({issue}`24031`)
```

Support setting extra properties in Iceberg

---

docs/src/main/sphinx/connector/faker.md
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerPageSourceProvider.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerSplit.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerSplitManager.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java

Use a jumpable random generator and make sure to jump it a different number of times for every split.
Ref: https://docs.oracle.com/en/java/javase/23/core/choosing-prng-algorithm.html
```markdown
* Make generated data deterministic. ({issue}`24008`)
```

Make Faker deterministic

---

service/trino-verifier/pom.xml
service/trino-verifier/src/main/java/io/trino/verifier/DatabaseEventClient.java
service/trino-verifier/src/main/java/io/trino/verifier/EventConsumer.java
service/trino-verifier/src/main/java/io/trino/verifier/HumanReadableEventClient.java
service/trino-verifier/src/main/java/io/trino/verifier/JsonEventClient.java
service/trino-verifier/src/main/java/io/trino/verifier/TrinoVerifierModule.java
service/trino-verifier/src/main/java/io/trino/verifier/Verifier.java
service/trino-verifier/src/main/java/io/trino/verifier/VerifierQueryEvent.java
service/trino-verifier/src/main/java/io/trino/verifier/VerifyCommand.java
service/trino-verifier/src/test/java/io/trino/verifier/TestDatabaseEventClient.java

This is a preparation for the removal of the event module from Airlift.
Related to https://github.com/airlift/airlift/pull/1314
```markdown
```

Remove Airlift's event client from verifier

---

plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/GeoFunctions.java

This is a follow up to PR #23894 
As discussed in the original PR the WKBReader is not thread-safe. This PR removes the static instance.
PR #23894 

WKBReader is not thread-safe. Remove static field

---

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

```markdown
* Fix failure when using uppercase characters in UPDATE assignments. ({issue}`24049`)
```

Fix failure when using uppercase characters in UPDATE assignments

---

docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/IcebergRestCatalogConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogNestedNamespaceConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java

Closes https://github.com/trinodb/trino/issues/23961
```markdown
* Allow configuring whether reading nested namespaces. This is controlled by the new `iceberg.rest-catalog.nested-namespace-enabled` 
catalog configuration property and defaults to `false`. ({issue}`24016`)
```

Move nested namespace support in REST catalog behind a config

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryNamedRelationHandle.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryQueryPageSource.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryQueryRelationHandle.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryRelationHandle.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitSource.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTypeManager.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ptf/Query.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java

Fix query failure when reading views having timestamp type in BigQuery connector.
Relates to https://github.com/trinodb/trino/issues/12346
```md
* Fix failure when reading views which have `timestamp` columns. ({issue}`24004`)
```

Skip unsupported timestamp type when reading views in BigQuery

---

plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseTypeMapping.java

The time zone is not stored in the rows of the table, but is stored in the column metadata.
From ClickHouse documentation
https://clickhouse.com/docs/en/sql-reference/data-types/datetime
The point in time is saved as a Unix timestamp, regardless of the time zone or daylight saving time. The time zone affects how the values of the DateTime type values are displayed in text format and how the values specified as strings are parsed (‘2020-01-01 05:00:01’).
Timezone agnostic Unix timestamp is stored in tables, and the timezone is used to transform it to text format or back during data import/export or to make calendar calculations on the values (example: toDate, toHour functions etc.). The time zone is not stored in the rows of the table (or in resultset), but is stored in the column …

Fix insert to Clickhouse TimestampWithTimeZone

---

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoTableHandle.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/RemoteTableName.java

Implement `toString` in `MongoTableHandle` and `RemoteTableName` to improve EXPLAIN readability.
Before:
```
trino> EXPLAIN SELECT * FROM  mongodb.tpch.region WHERE name = 'X';
Query Plan
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Trino version: testversion
Fragment 0 [SOURCE]
Output layout: [regionkey, name, comment]
Output[columnNames = [regionkey, name, comment]]
│   Layout: [regionkey:bigint, name:varchar(25), comment:varchar(152)]
│ …
```

Implement `toString()` method  in `MongoTableHandle` and `RemoteTableName` classes

---

testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Hopefully, this fixes issue in BigQuery connector:
```
Error:  io.trino.plugin.bigquery.TestBigQueryAvroConnectorTest.testCommentTable -- Time elapsed: 8.318 s <<< ERROR!
io.trino.testing.QueryFailedException: Exceeded rate limits: too many table update operations for this table. For more information, see https://cloud.google.com/bigquery/docs/troubleshoot-quotas
at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:138)
at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:565)
at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:548)
at io.trino.testing.QueryRunner.execute(QueryRunner.java:82)
at io.trino.testing.sql.TestTable.close(TestTable.java:134)
at …
```

Reduce repeated operations for a table in testCommentTable

---

lib/trino-filesystem-alluxio/src/test/java/io/trino/filesystem/alluxio/TestAlluxioFileSystem.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClientModule.java
plugin/trino-kafka-event-listener/src/test/java/io/trino/plugin/eventlistener/kafka/TestUtils.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/MarquezServer.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/PrometheusServer.java
pom.xml

Enable ErrorProne CanonicalDuration

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/BinPackingNodeAllocatorService.java

We could get java.lang.IllegalArgumentException: bound must be positive when pendingAcquires was empty

Prevent IllegalArgumentException if no pending node acquires

---

core/trino-spi/src/main/java/io/trino/spi/security/SystemAccessControl.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/AllowAllSystemAccessControl.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/ForwardingSystemAccessControl.java
plugin/trino-opa/src/main/java/io/trino/plugin/opa/OpaAccessControl.java
plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestConstants.java
plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaAccessControl.java

They were deprecated in 445 when replacement methods were added; I guess 10 versions is long enough for a transition period.
Related PR: #21374
```markdown
* Removed deprecated variants of `checkCanExecuteQuery` and `checkCanSetSystemSessionProperty` that do not take `QueryId` parameter from `SystemAccessControl`. ({issue}`23244`)
```

Remove deprecated access control functions

---

docs/src/main/sphinx/connector/iceberg.md

This PR updates the Iceberg documentation to clarify that setting `iceberg.table-statistics-enabled=false` does not disable statistics gathering.
```markdown
```

Update table statistics description in Iceberg doc

---

plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java

Previous code blocked any comments. Corrected the ROW_ID condition.
```markdown
```

Faker: Fix comments on generator table

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TypeConverter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/HiveSchemaUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/OrcTypeConverter.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergFileOperations.java
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeSparkIcebergRest.java

* https://github.com/apache/iceberg/commits/apache-iceberg-1.7.0

Update Iceberg to 1.7.0

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcConnectorFactory.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPlugin.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/H2QueryRunner.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcPlugin.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJmxStats.java
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHousePlugin.java
plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcPlugin.java
plugin/trino-example-jdbc/src/main/java/io/trino/plugin/example/ExamplePlugin.java
plugin/trino-exasol/src/main/java/io/trino/plugin/exasol/ExasolPlugin.java
plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgnitePlugin.java
plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbPlugin.java
plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlPlugin.java
plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OraclePlugin.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlPlugin.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlJdbcConnectionAccesses.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlJdbcConnectionCreation.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftPlugin.java
plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStorePlugin.java
plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakePlugin.java
plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerPlugin.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerJdbcConnectionAccesses.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerJdbcConnectionCreation.java
plugin/trino-vertica/src/main/java/io/trino/plugin/vertica/VerticaPlugin.java
testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
testing/trino-tests/src/test/java/io/trino/tests/TestQueryAssertions.java

When a `JdbcPlugin` is instantiated, creating an instance of a module at that time causes the instance to be shared by all connectors provided by the plugin. This is problematic when the module extends `AbstractConfigurationAwareModule`, as it holds a reference to the `ConfigurationFactory`, which is set dynamically during bootstrap. If catalogs are loaded concurrently, this can lead to situations where a connector accesses the configuration of another connector.
```markdown
* Fix potential configuration leakage between JDBC catalogs. ({issue}`issuenumber`)
```

Ensure module instances are not shared by multiple JDBC catalogs

---

plugin/trino-faker/pom.xml
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java

Use TestTable in faker

---

docs/src/main/sphinx/connector.md
docs/src/main/sphinx/connector/tpcds.md
docs/src/main/sphinx/connector/tpch.md
docs/src/main/sphinx/optimizer/pushdown.md
docs/src/main/sphinx/overview/concepts.md
docs/src/main/sphinx/release/release-0.148.md
docs/src/main/sphinx/release/release-0.183.md
docs/src/main/sphinx/release/release-0.184.md
docs/src/main/sphinx/release/release-0.60.md

This makes the connector names more consistent with the actual name of the benchmarks.
Came up in https://github.com/trinodb/trino/pull/23987/files#r1823617713

Correct name for TPC-H and TPC-DS connectors

---

client/trino-client/src/main/java/io/trino/client/spooling/Segment.java
client/trino-client/src/main/java/io/trino/client/spooling/SegmentLoader.java
client/trino-client/src/main/java/io/trino/client/spooling/SpooledSegment.java
core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/CoordinatorSegmentResource.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpooledBlock.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpooledQueryDataProducer.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingConfig.java
core/trino-main/src/test/java/io/trino/server/protocol/TestQueryDataSerialization.java
core/trino-main/src/test/java/io/trino/server/protocol/spooling/TestSpooledBlock.java
core/trino-main/src/test/java/io/trino/server/protocol/spooling/TestSpoolingConfig.java

This allows for storage-wide expiration policies to be implemented
that doesn't require explicit API call to remove an expired segment.
```markdown
```

Allow disabling client segment acknowledgment

---

core/trino-main/src/main/java/io/trino/sql/planner/EffectivePredicateExtractor.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PruneUnnestColumns.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushDownDereferenceThroughUnnest.java
core/trino-main/src/main/java/io/trino/sql/planner/planprinter/GraphvizPrinter.java
core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java

Related change: https://github.com/trinodb/trino/pull/20994/commits/bdbdc8f8ddb21c9e06a89f6e6666267d0e409f1b 
Includes:
- logical change: extracting source predicate for relevant join types in `EffectivePredicateExtractor`
- fixes to `GraphvizPrinter` and `PlanPrinter` regarding UnnestNode's join type
- code and comment cleanup
By removing filter from `UnnestNode`, we lost distinction between Unnest being in the context of a join or standalone. Given the way Unnest is planned, it is not incorrect. However, this information sometimes cannot be restored in plan printers.
No docs or release notes needed.

Cleanup UnnestNode filter removal

---

README.md
testing/trino-server-dev/src/main/java/io/trino/server/DevelopmentPluginsProvider.java

This is an alternative approach to solve the same use case described in #23100.
This PR makes it possible to use the local `DevelopmentServer` with plugin directories, which have the same setup as a typical production plugin directory. This makes it easier to test the same setup you may have in a real production setup, but in your local development environment. This gives you the most apples-to-apples experience, and allows for easier integration of plugins developed on non-Maven builds. Some additional documentation is added to the `README` to describe the various ways to configure plugins in `plugin.bundles`. …

Enhance DevelopmentPluginsProvider to handle plugin directories

---

core/trino-main/src/test/java/io/trino/execution/scheduler/faulttolerant/TestTaskDescriptorStorage.java

Use coarser units in test to make it less dependent on environment

---

docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/IcebergJdbcCatalogConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalogFactory.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java

Allows retrying additional, JDBC driver and database specific errors
such as Postgres status codes `57000,57P03,57P04` if using Postgres.
Add iceberg.jdbc-catalog.retryable-status-codes configuration property.
Iceberg JDBC catalog uses internal connection pool which supports retrying transient
connection errors which improves Iceberg catalog resilience.
By default, only a limited set of status codes is supported: https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/jdbc/JdbcClientPool.java#L50
These codes are database-agnostic and do not include database-specific transient errors.
To configure additional status codes, Iceberg JDBC Catalog supports `retryable_status_codes` configuration
property: https://github.com/apache/iceberg/blob/main/core/src/main/java/org …

Add iceberg.jdbc-catalog.retryable-status-codes configuration property

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/FilesTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitionColumn.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTable.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/DataFileRecord.java

Relates to #24101
Add 4 missing columns Spark supports: https://iceberg.apache.org/docs/latest/spark-queries/#files
* spec_id: INTEGER
* partition: ROW(...)
* sort_order_id: INTEGER
* readable_metrics: JSON
```markdown
* Add `spec_id`, `partition`, `sort_order_id`, `readable_metrics` columns to `$files` metadata table. ({issue}`24102`)
```

Add spec_id, partition, sort_order_id, readable_metrics columns to Iceberg $files table

---

docs/src/main/sphinx/connector/faker.md
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerConfig.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerPageSourceProvider.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/FakerQueryRunner.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerConfig.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java

Allow configuring locale in the Faker connector.
```markdown
* Allow configuring locale via the `aker.locale` config property. ({issue}`24152`)
```

Allow configuring locale in the Faker connector

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/FilesTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionsTable.java

The metadata table name is `partitions`: https://trino.io/docs/current/connector/iceberg.html#partitions-table

Rename `PartitionTable` to `PartitionsTable` in Iceberg

---

docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/IcebergRestCatalogConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogCaseInsensitiveMapping.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java

Certain Rest catalog implementation(eg. Polaris) supports case-sensitive object(namespace, table, view etc.) names. This change allows querying mixed/upper case letter objects in rest catalog from Trino.
`iceberg.rest-catalog.case-insensitive-name-matching` controls whether to match lowercase object names in Trino with different case object names in rest catalog with the limitations that only single object name with the same name is supported.
Fixes https://github.com/trinodb/trino/issues/23715
```markdown
* Add support for case-insensitive name matching in REST catalog. ({issue}`23715`)
```

Add support for case-insensitive object names in Iceberg REST catalog

---

plugin/trino-pinot/pom.xml
pom.xml

The new resolver (included in maven 4.0.0-rc1) is reporting these bounds as incorrect. Fixing them eagerly to ensure forward compatibility.
```markdown
```

Settle bounds for two dependencies

---

core/trino-main/src/main/java/io/trino/operator/scalar/RepeatFunction.java
core/trino-main/src/test/java/io/trino/type/TestArrayOperators.java

Fixes #22867
```markdown
* Add support for specifying `bigint` type in `repeat` function. ({issue}`22867`)
```

Allow specifying bigint type in repeat function

---

lib/trino-parquet/src/test/java/io/trino/parquet/ParquetTestUtils.java
plugin/trino-delta-lake/pom.xml
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointSchemaManager.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
pom.xml

We should write physical column names in `partitionValues_parsed` field on checkpoint files. 
Fixes #24121
```markdown
```

Fix incorrect partitionValues_parsed with id & name column mapping in Delta Lake

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3Context.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystem.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemConfig.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3InputFile.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3OutputStream.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3SseCustomerKey.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3SseRequestConfigurator.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemAwsS3WithSseCustomerKey.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemConfig.java

The PR enables Server Side Encryption with Customer Key mode (SSE-C) for data encryption on S3 storage.
New value `CUSTOMER` for the property `s3.sse.type` - indicates that we want to use Customer Key for SSE (SSE-C mode)
New property: `s3.sse.customer-key` - Customer Key to use for S3 server-side encryption with Customer key (SSE-C)
```markdown
```

Enable SSE with customer key for S3

---

docs/src/main/sphinx/admin/properties-task.md

Specify default value for task.concurrency in docs for FTE mode

---

docs/src/main/sphinx/connector/memory.md

Remove invalid limitation since Trino doesnt support multiple coordinators.
Replaces https://github.com/trinodb/trino/pull/23968 since we never got CLA.

Correct memory connector docs

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrationUtils.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/procedure/TestIcebergAddFilesProcedure.java

Fixes #23678
```markdown
* Disallow adding duplicate files in `add_files` and `add_files_from_table` procedure. ({issue}`24188`)
```

Deny duplicate files in Iceberg `add_files` & `add_files_from_table` procedure

---

docs/src/main/sphinx/connector/postgresql.md
plugin/trino-postgresql/pom.xml
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/PostgreSqlQueryRunner.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlClient.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlGeometryType.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlPlugin.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlConnectorContext.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java

Add support for geometry type mapping in the PostgreSQL connector.
Issue: #5580
There is an old, inactive PR at #9951 
My take is slightly different when it comes to reading PostGIS geometries. The previous attempt rewrote the query and wrapped geometry columns in ST_GeomAsWKB to convert them to a Well Known Binary format. I'm using the native format which is hex encoded EWKB.
```md
* Add support for `geometry` type. ({issue}`5580`)
```

Add support for PostGIS

---

core/trino-main/src/main/java/io/trino/execution/resourcegroups/InternalResourceGroup.java
core/trino-main/src/test/java/io/trino/execution/resourcegroups/TestResourceGroups.java

Add a new `StartedQueries` stat to `InternalResourceGroup` to track the rate of queries being started/submitted to a resource group. After #22957 we have nearly all of the useful operational stats that you would want to know about a resource group (like CPU / memory, queued/running queries at any given time, etc.), but one thing that is missing is an understanding of the rate at which queries are being submitted into this resource group.
Currently we have a metric `TimeBetweenStartsSec` but it doesn't meet the needs described here:
1. It only tracks time between starts, not the count of queries
2. It doesn't count the first start after newly becoming eligible ([refer to this discussion](https://github.com/prestodb/presto/pull/10007#discussion_r171422808)), limiting its utility for …

Add StartedQueries stat to InternalResourceGroup for tracking query start rate

---

plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/QueryDao.java

Fixes #22362 
Changed the column data-type for `client_info` from `varchar(255)` to `MEDIUMTEXT` in mysql event listener. This will allow for a larger payload to be stored, and is also inline with other columns(possibly big) in the table.
( X ) Release notes are required, with the following suggested text:
```markdown
* Change data type for client_info in mysql event listener to MEDIUMTEXT ({issue}`22362`)
```

change client_info column_type to MEDIUMTEXT

---

docs/src/main/sphinx/release/release-436.md
docs/src/main/sphinx/release/release-447.md
docs/src/main/sphinx/release/release-464.md

Add info that this also requires a updated JVM configuration.
See discussion in https://github.com/trinodb/trino/pull/23482 

Update release notes with Java requirements change

---

core/trino-main/src/main/java/io/trino/sql/ir/IrExpressions.java

This allows the optimizer to be more aggressive during predicate pushdown.
```markdown
* Improve performance when using various string functions in queries involving joins. ({issue}`24182`)
```

Indicate certain string functions cannot fail

---

docs/src/main/sphinx/connector/phoenix.md
docs/src/main/sphinx/installation/deployment.md
docs/src/main/sphinx/release/release-464.md

For now we only know of the Phoenix connector being affected as a result of it loading Hadoop libraries. We do not add this for the object storage connectors since the old file system stuff with Hadoop dependencies is considered legacy. And we are not aware of other connectors with this problem.
Follow up to https://github.com/trinodb/trino/pull/24203

Clarify Phoenix requirement

---

docs/release-template.md
docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-465.md

Assemble the release notes for the upcoming Trino 465 release.
See https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A465
* #23730 ✅ rn ✅ docs
* #23817 ✅ rn ✅ docs 
* #23973 ✅ rn ✅ docs
* #23975 ✅ rn ✅ docs
* #23969 ✅ rn ✅ docs
* #23991 ✅ rn ✅ docs
* #23990 ✅ rn ✅ docs
* #23993 ✅ rn ✅ docs
* #20393 ✅ rn ✅ docs
* #23284 ✅ rn ✅ docs
* #23989 ✅ rn ✅ docs
* #23964 ✅ rn ✅ docs, https://github.com/trinodb/trino/pull/24005
* #23998 ✅ rn ✅ …

Add Trino 465 release notes

---

core/trino-main/src/main/java/io/trino/client/direct/DirectTrinoClient.java
core/trino-main/src/main/java/io/trino/testing/TestingDirectTrinoClient.java

This originted in testing code, but it is being repurposed as a general-purpose utility, so it should not be in a `testing` package.
The tests for this class are in the `testing/trino-tests` module in class `io.trino.tests.TestLocalQueries`, so they are not moved along with it.
* It's *technically* user-visible, but I don't think we're advertising this feature
```markdown
```

Move DirectTrinoClient to a non-testing package

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableProperties.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/TrinoNessieCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithObjectStore.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java

Currently, Trino is only able to write to and read from tables that use Iceberg's `ObjectStorageLocationProvider`, but is unable to create or drop tables using the location provider. 
This PR enables Trino to create tables using Iceberg's object storage by adding the following properties:
*  `iceberg.object-store.enabled` - Corresponds with Spark's `write.object-storage.enabled`, which enables use of Iceberg's ObjectStorageLocationProvider
*  `iceberg.data-location` - Corresponds to Spark's `write.data.path`, which sets where Iceberg data files will be written
Enabling the object store property and setting the data path will cause Iceberg to provide data file locations prefixed by  a deterministic hash generated from the file name in the location specified by `write.data.path`, which will …

Add support for creating and dropping tables using Iceberg object store

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableProperties.java

Set object_store_enabled as false by default in Iceberg

---

core/trino-main/src/main/java/io/trino/server/protocol/JsonEncodingUtils.java
core/trino-main/src/test/java/io/trino/server/protocol/spooling/TestJsonQueryDataEncoding.java

Fix serialization regression for varbinary map keys

---

core/trino-main/src/main/java/io/trino/cost/AggregationStatsRule.java
core/trino-main/src/test/java/io/trino/cost/TestAggregationStatsRule.java

This makes CBO estimates in the EXPLAIN plan output easier to understand
```markdown
```

Show stats in EXPLAIN/EXPLAIN ANALYZE with intermediate aggregation

---

core/trino-main/src/main/java/io/trino/connector/system/MaterializedViewSystemTable.java
core/trino-main/src/main/java/io/trino/connector/system/SystemPageSourceProvider.java
core/trino-main/src/main/java/io/trino/connector/system/SystemSplit.java
core/trino-main/src/main/java/io/trino/connector/system/SystemSplitManager.java
core/trino-main/src/main/java/io/trino/connector/system/jdbc/TableJdbcTable.java
core/trino-main/src/test/java/io/trino/connector/system/TestSystemSplit.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/connector/SystemTable.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeSystemTable.java

This PR implements parallelization of table retrieval at the catalog level by generating a split for each catalog.
Benchmark results for the following query (9 catalogs, 822 schemas, 17835 tables):
```sql
SELECT * FROM system.jdbc.tables;
```
The chart compares the execution time of the query above between `master` and the changes introduced in this PR and https://github.com/trinodb/trino/pull/24110.
Since this PR requires changes to the SPI (`io.trino.spi.connector.SystemTable`), I'm wondering how to approach them. Should I introduce a new `cursor` method to the `SystemTable` interface? Currently, I have extended an existing one.
(x) …

Parallelize tables retrieval from multiple catalogs

---

core/trino-main/src/main/java/io/trino/metadata/Metadata.java
core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
core/trino-main/src/main/java/io/trino/operator/ChangeOnlyUpdatedColumnsMergeProcessor.java
core/trino-main/src/main/java/io/trino/operator/DeleteAndInsertMergeProcessor.java
core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java
core/trino-main/src/main/java/io/trino/sql/planner/plan/TableWriterNode.java
core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
core/trino-main/src/main/java/io/trino/tracing/TracingMetadata.java
core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
core/trino-main/src/test/java/io/trino/sql/planner/TestDeleteAndInsertMergeProcessor.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
core/trino-spi/src/main/java/io/trino/spi/connector/MergePage.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduPageSink.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMergeSink.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMergeTableHandle.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java
plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestingPhoenixServer.java

Currently the `update` implementation of MERGE update updates the whole row, this pr is going to update the engine merge impl to support partial update.
The main idea is to keep the `merge case_number` of the `UpdateCase` in the output of the `MergeProcessNode`,(this value already kept in the `merge_row` symbol that in the sourceNode of the `MergeProcessNode`, so only needs to project it), and then in the `MergeWriterNode`, the `updateSink` can perform the update according to the update case.
The partial update also needs to know the mapping of the case number with the relevant columns, thus the `ConnectorMetadata#beginMerge` is refactored to hold the info.
Here use the Phoenix connector as a example to show how it works.
Prerequisites for https://github.com/trinodb/trino/pull/23034
( ) …

Refactor merge to support partial update

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultQueryBuilder.java

For consistency, `getFrom` should also be protected to allow it to be used from `prepareSelectQuery`.
```markdown
```

Convert `DefaultQueryBuilder.getFrom` to protected for easier extension

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Throw a better user facing error when doing a `CREATE OR REPLACE TABLE` operation on an iceberg table with corrupted metadata.
Previously, this operation would return this error:
```
java.lang.ClassCastException: class io.trino.plugin.iceberg.CorruptedIcebergTableHandle cannot be cast to class io.trino.plugin.iceberg.IcebergTableHandle (io.trino.plugin.iceberg.CorruptedIcebergTableHandle and io.trino.plugin.iceberg.IcebergTableHandle are in unnamed module of loader io.trino.server.PluginClassLoader @6f4201f2)
```
With this change, the error returned to the user is:
```
Metadata not found in metadata location for table <table-name>
```

Throw better error message when replacing corrupted iceberg table

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Persist the Trino user into Iceberg snapshot summary

---

plugin/trino-phoenix5/pom.xml

Update phoenix to 5.2.1

---

docs/src/main/sphinx/object-storage/metastores.md

https://github.com/trinodb/trino/blob/b519bdf7d90aeb414121788999b48930cef6d934/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/ImpersonationCachingConfig.java#L34-L39
https://github.com/trinodb/trino/blob/b519bdf7d90aeb414121788999b48930cef6d934/plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/ImpersonationCachingConfig.java#L47-L52

Document caching impersonation configuration options

---

plugin/trino-google-sheets/pom.xml
plugin/trino-iceberg/pom.xml

This fixes some ambiguous dependencies due to improved maven resolver.
```markdown
```

Maven 4.0.0 compatibility fixes

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

Fixes #22922
```markdown
* Fix failure when reading tables where a nested field has schema changes on Parquet files. ({issue}`22922`)
```

Fix failure when reading missing fields in Parquet

---

core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
core/trino-main/src/main/java/io/trino/util/DateTimeUtils.java
core/trino-main/src/test/java/io/trino/operator/scalar/interval/TestIntervalDayTime.java
core/trino-main/src/test/java/io/trino/operator/scalar/interval/TestIntervalYearMonth.java

When an INTERVAL literal is invalid, `ExpressionAnalyzer` ignores an original error and always report as `'xxxx' is not a valid INTERVAL literal` which is confusing in cases like below:
```sql
INTERVAL '12-10' YEAR TO DAY
```
In this case, `YEAR TO DAY` is invalid in the first place but still reported as `'12-10' is not a valid INTERVAL literal`.
It would be better to keep the original error message for better error reporting.
```markdown
```

Improve messages for INTERVAL literal semantic errors

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryRpcConfig.java
plugin/trino-faker/pom.xml

Reverts an un-needed and unused change in BigQuery.
Fixes pom for the trino-faker module.

Faker and BigQuery cleanups

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java

Waiting a short time for dynamic filters to arrive can be highly beneficial for some queries with selective joins
https://github.com/trinodb/trino/pull/23945 caused regressions on some TPCDS queries due to splits generation getting faster and not allowing enough time for dynamic filters to arrive.
```markdown
* Improve performance of queries with selective joins. ({issue}`24277`)
```

Add small delay for dynamic filters in iceberg scans

---

docs/src/main/sphinx/routines/loop.md

Existing example had a logical and syntactical error. 
Thanks for finding that something is wrong @findepi 

Fix and improve loop example

---

docs/src/main/sphinx/admin.md
docs/src/main/sphinx/admin/properties-client-protocol.md
docs/src/main/sphinx/admin/properties-general.md
docs/src/main/sphinx/admin/properties.md
docs/src/main/sphinx/client.md
docs/src/main/sphinx/client/cli.md
docs/src/main/sphinx/client/client-protocol.md
docs/src/main/sphinx/client/jdbc.md
docs/src/main/sphinx/develop/client-protocol.md
docs/src/main/sphinx/overview/concepts.md
plugin/trino-spooling-filesystem/src/main/java/io/trino/spooling/filesystem/FileSystemSpoolingConfig.java

Revamped client protocol docs and added spooling info. 
#22271 and various others.

Improve and expand client protocol docs

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-466.md

Assemble the release notes for the upcoming Trino 466 release.
See https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A466
* #23812 ✅ rn ✅ docs
* #24211 ✅ rn ✅ docs
* #24193 ✅ rn ✅ docs
* #24214 ✅ rn ✅ docs, #23836
* #24215 ✅ rn ✅ docs
* #20555 ✅ rn ✅ docs
* #24223 ✅ rn ✅ docs
* #24226 ✅ rn ✅ docs
* #24110 ❌ rn ✅ docs
* #24231 ✅ rn ✅ docs
* #24159 ❌ rn ✅ docs
* #24233 ✅ rn ✅ docs
* #24075 ✅ rn ✅ docs
* #24232 ✅ rn ✅ docs
* #24221 ✅ rn ✅ …

Add Trino 466 release notes

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/coercions/VarbinaryToVarcharCoercers.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/coercions/TestVarbinaryToVarcharCoercer.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCoercionOnUnpartitionedTable.java

Minor cleanups like removing assertion for un-partitioned parquet tables as we don't support in the reading them like Hive does and unifying the coercion code for non-orc tables. 
```markdown
```

Minor cleanups on varbinary to varchar coercion

---

core/trino-main/src/main/java/io/trino/server/AsyncResponseUtils.java
core/trino-main/src/main/java/io/trino/server/TaskResource.java
core/trino-main/src/main/java/io/trino/server/ThrowableMapper.java
core/trino-main/src/main/java/io/trino/server/protocol/Query.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2TokenExchangeResource.java

TaskResource fixes

---

core/docker/Dockerfile

This is the most secure and the smallest base image we can use.
Before:
```
✔ Cataloged contents                                                                                                      651b47fea90956f18d4af75da3d1c94e57ec838e417d6ba9ed2948674efe3f14
├── ✔ Packages                        [1,071 packages]
├── ✔ File digests                    [3,288 files]
├── ✔ File metadata                   [3,288 locations]
└── ✔ Executables                     [336 executables]
✔ Scanned for vulnerabilities     [37 vulnerability matches]
├── by severity: 0 critical, 2 high, 8 medium, 27 low, 0 negligible
└── by status:   5 fixed, 32 not-fixed, 0 ignored
NAME                    INSTALLED            FIXED-IN     TYPE          VULNERABILITY        SEVERITY
bzip2-libs              1.0.8-8.el9 …
```

Use Ubi 9 micro image for docker

---

core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java
core/trino-main/src/main/java/io/trino/server/InternalCommunicationConfig.java
core/trino-main/src/main/java/io/trino/server/ServerMainModule.java
core/trino-main/src/test/java/io/trino/execution/TestTaskManagerConfig.java
core/trino-main/src/test/java/io/trino/server/TestInternalCommunicationConfig.java

There were reports of cluster instability after the HTTP/2 was enabled for internal communication. This requires more investigation and testing.
```markdown
```

Disable HTTP/2 for internal communication

---

docs/src/main/sphinx/client/cli.md
docs/src/main/sphinx/client/jdbc.md

Related to the addition of the spooling protocol, adding consistency and updating content.
There might be more changes coming so I am keeping it as draft.

Clarify requirements for CLI and JDBC driver

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergLocalConcurrentWrites.java

Add concurrent write to scenarios like:
```sql
-- create test table in iceberg
create table all_defaults_partitioned
with (
partitioning = array['month(shipdate)']
)
as select * from tpch.sf1000.lineitem
-- first session
update all_defaults_partitioned
set orderkey = 654
where shipdate = date '1995-01-01'
-- second session 
update all_defaults_partitioned
set orderkey = 765
where shipdate = date '1996-12-01'
```
```markdown
* Add support for concurrent write on Iceberg transformed column
```

Add support for concurrent write on Iceberg transformed column

---

core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java

We want to distinguish 503 error in HttpRemoteTask and propagate it as ServiceUnavailableException so it is not logged in logError. 503 is expected in some situations (e.g. after worker restarts, or is yet fully started).

Special handling of 503 in HttpRemoteTask

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/CreateTableException.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/AbstractMetastoreTableOperations.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestIcebergFileMetastoreCreateTableFailure.java

Previously only metadata file was cleaned up leaving Avro manifest list files present. Now both type of files are removed.
Previously only some exceptions caused transaction files to be cleaned. Now all exceptions cause cleanup.
```markdown
* Fully cleanup table transaction files when `CREATE TABLE` fails. ({issue}`issuenumber`)
```

Cleanup manifest and metadata files when any createTable fails

---

testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

`BaseConnectorTest.testRenameMaterializedView` passes incorrect value at a certain point when checking for table existence.

Fix BaseConnectorTest.testRenameMaterializedView

---

lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsLocation.java

Simple typo fix in error message ~+ removing of null return from config class~. Sent from Trino repo instead of fork to make sure cloud tests are run.

GCS filesystem cleanups

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesFunction.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

These arguments have been deprecated since 6 months ago. 
```markdown
* Remove deprecated `schema` and `table` arguments from `table_changes` table function.
Use `schema_name` and `table_name` instead. ({issue}`24324`)
```

Remove deprecated arguments from Iceberg `table_changes` function

---

pom.xml
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java

Relates to 
* https://github.com/trinodb/docker-images/pull/217

Update docker image version to 106

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/decoders/PlainByteArrayDecoders.java

Using this is unnecessary when creating output buffer for unbounded varchars
```
Benchmark                         (encoding)  (positionLength)     (type)   Mode  Cnt     Before Score      After Score Units
BenchmarkBinaryColumnReader.read       PLAIN     VARIABLE_0_10  UNBOUNDED  thrpt   40  105.665 ± 0.948  113.374 ± 1.893 ops/s
```
```markdown
```

Reduce overhead from Slice#getInt in PlainByteArrayDecoders

---

client/trino-client/src/main/java/io/trino/client/spooling/encoding/QueryDataDecoders.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/QueryDataEncodingConfig.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/encoding/JsonQueryDataEncoder.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/encoding/Lz4QueryDataEncoder.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/encoding/ZstdQueryDataEncoder.java
core/trino-main/src/test/java/io/trino/server/protocol/spooling/TestQueryDataEncodingConfig.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/util/JsonUtils.java

Prefer compressed json variants + make threshold configurable

---

plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java

Refactor cassandra tests

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergEnvironmentContext.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

Fixes https://github.com/trinodb/trino/issues/16478

Set engine name and version in Iceberg EnvironmentContext

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/AllManifestsTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableType.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java

`all_manifests` metadata table provides data for the current snapshot as well as all snapshots.
This table will be helpful when we support rewriting manifests in the future. 
Added the null handling just in case though I couldn't find how to get NULL from `contains_nan` field. 
https://iceberg.apache.org/docs/latest/spark-queries/#all-manifests
> 2. contains_nan could return null, which indicates that this information is not available from the file's metadata. This usually occurs when reading from V1 table, where contains_nan is not populated.
Docs PR can be handled in different PR. We may want to separate a section for `all_` metadata tables. 
```markdown
* Add the `all_manifests` metadata table. ({issue}`24330`)
```

Add `all_manifests` metadata table to Iceberg

---

core/trino-spi/src/main/java/io/trino/spi/statistics/DoubleRange.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergStatistics.java

Connector objects may contain columns that contain only `NaN` values. When these values are passed to `DoubleRange` ctor, an exception occurs. Depending on the context, this may lead to either silent fallback to empty stats (e.g., `SHOW STATS` will give the user misleading values), or cause exceptions within an optimizer.
This PR fixes the problem, normalizing ranges with NaN to empty range. 
Originally this problem was observed during careful analysis of `BaseIcebergConnectorTest.testPartitionedByDoubleWithNaN` behavior. One may think that this is an Iceberg issue, which we may fix around Iceberg's `TableStatisticsReader.makeTableStatistics` class. However, other engines may also legitimately expose NaN as their stats, so it seems that it is better to fix it completely at the SPI level. …

Fix DoubleRange resolution for NaN values

---

core/trino-main/src/main/java/io/trino/operator/DirectExchangeClient.java

If the query is cancelled the existing code can result in:
```
presto-worker       | 2024-12-03T20:36:32.663+0545	INFO	page-buffer-client-callback-65	stderr	java.lang.IllegalStateException: client is already marked as completed
presto-worker       | 2024-12-03T20:36:32.663+0545	INFO	page-buffer-client-callback-65	stderr		at com.google.common.base.Preconditions.checkState(Preconditions.java:513)
presto-worker       | 2024-12-03T20:36:32.663+0545	INFO	page-buffer-client-callback-65	stderr		at io.trino.operator.DirectExchangeClient.addPages(DirectExchangeClient.java:333)
presto-worker       | 2024-12-03T20:36:32.663+0545	INFO	page-buffer-client-callback-65	stderr		at io.trino.operator.DirectExchangeClient$ExchangeClientCallback.addPages(DirectExchangeClient.java:427)
presto-worker       | …
```

Return early if http client is already closed

---

core/docker/default/etc/log.properties
core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/trino/etc/log.properties

This actually hides an issue with the tracing filter fixed in https://github.com/airlift/airlift/pull/1333
```markdown
```

Revert suppressed logging

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/BaseTransactionsTable.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeHistoryTable.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableType.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTransactionsTable.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java

This table will help us debug issues in transaction logs. 
I didn't document it because it's mainly for debug purpose and I expect most users don't use it in normal situations. 
```sql
trino> SELECT * FROM delta.tpch."region$transactions";
version |                                                                                                                                                                                      transaction                                       >
---------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------->
0 | [ { …
```

Add `$transactions` system table to Delta Lake

---

docs/src/main/sphinx/connector/delta-lake.md
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeHistoryTable.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java

```markdown
* Add `operation_metrics` column to`$history` metadata table.
```

Add operation_metrics to $history table in Delta Lake

---

docs/src/main/sphinx/connector/jdbc-case-insensitive-matching.fragment

Fix the refresh-period configuration for
`case-insensitive-name-matching.config-file`.
There are errors in the existing documentation for [Case insensitive matching](https://trino.io/docs/current/connector/oracle.html#case-insensitive-matching). The field 
`case-insensitive-name-mapping.refresh-period` is not valid, it should be `case-insensitive-name-matching.config-file.refresh-period`.

Fix refresh-period configuration documentation

---

docs/src/main/sphinx/object-storage/file-system-azure.md
docs/src/main/sphinx/object-storage/file-system-gcs.md
docs/src/main/sphinx/object-storage/file-system-s3.md
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemConfig.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemFactory.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureFileSystemConfig.java
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsStorageFactory.java
lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemConfig.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemConfig.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemConfig.java

Fixes https://github.com/trinodb/trino/issues/24328
Adds `gcs.application-id`, `azure.application-id` and `s3.application-id` to the native fs configurations. This allows for additional identification of the application on the storage side
```markdown
```

Add configurable application id to native filesystems

---

docs/src/main/sphinx/security/apache-ranger-access-control.md
plugin/trino-ranger/src/main/java/io/trino/plugin/ranger/RangerConfig.java
plugin/trino-ranger/src/main/java/io/trino/plugin/ranger/RangerSystemAccessControl.java
plugin/trino-ranger/src/main/java/io/trino/plugin/ranger/RangerSystemAccessControlFactory.java
plugin/trino-ranger/src/test/java/io/trino/plugin/ranger/TestApacheRangerPlugin.java
plugin/trino-ranger/src/test/java/io/trino/plugin/ranger/TestRangerConfig.java

These were missed when renaming the plugin module
```markdown
* TBD. ({issue}`24392`)
```

Clean up naming of ranger plugin properties

---

.github/workflows/ci.yml

The tests take ~5 minutes, so that warrants its own job, rather than running in `test-other-modules`.

Move Vertica module to separate CI job

---

core/trino-main/src/main/java/io/trino/execution/executor/dedicated/ThreadPerDriverTaskExecutor.java
core/trino-main/src/main/java/io/trino/execution/executor/scheduler/FairScheduler.java
core/trino-main/src/main/java/io/trino/server/ServerMainModule.java

Tries to expose the same information available through log diagnostics added in https://github.com/trinodb/trino/pull/23045 over JMX.

Add JMX metrics to thread-per-driver scheduler

---

docs/src/main/sphinx/redirects.txt
docs/src/main/sphinx/release/release-466.md
docs/src/main/sphinx/security.md
docs/src/main/sphinx/security/built-in-system-access-control.md
docs/src/main/sphinx/security/overview.md
docs/src/main/sphinx/security/ranger-access-control.md

Following the convention for all other plugins that are related to an Apache project.
Follow up to https://github.com/trinodb/trino/pull/24392

Rename docs to Ranger access control

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-467.md

Assemble the release notes for the upcoming Trino 467 release.
See https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A467
* #24290 ✅ rn ✅ docs
* #24274 ✅ rn ✅ docs
* #24294 ✅ rn ✅ docs
* #24296 ✅ rn ✅ docs
* #24281 ✅ rn ✅ docs
* #24299 ✅ rn ✅ docs
* #24300 ✅ rn ✅ docs
* #24288 ✅ rn ✅ docs
* #24160 ✅ rn ✅ docs
* #24311 ✅ rn ✅ docs
* #24303 ✅ rn ✅ docs
* #24279 ✅ rn ✅ docs
* #24314 ✅ rn ✅ docs
* #24318 ✅ rn ✅ docs
* #24325 ✅ rn ✅ docs
* …

Add Trino 467 release notes

---

.github/workflows/ci.yml
lib/trino-filesystem-gcs/pom.xml

Group related modules and minimize time for `test-other-modules`.
This also fixes `trino-filesystem-gcs` which wasn't running the non-cloud tests.

Test Alluxio modules as part of file system job

---

.github/DEVELOPMENT.md

Borrowed the sentence from https://iceberg.apache.org/contribute/#method-naming
We already use this approach in newly created classes. e.g. [Location.java](https://github.com/trinodb/trino/blob/master/lib/trino-filesystem/src/main/java/io/trino/filesystem/Location.java)

Document avoiding `get` prefix in method names

---

plugin/trino-functions-python/pom.xml
plugin/trino-functions-python/src/main/java/io/trino/plugin/functions/python/JdkLogger.java
plugin/trino-functions-python/src/main/java/io/trino/plugin/functions/python/LoggingOutputStream.java
plugin/trino-functions-python/src/main/java/io/trino/plugin/functions/python/PythonEngine.java
plugin/trino-functions-python/src/main/java/io/trino/plugin/functions/python/PythonFunctionEngine.java
plugin/trino-functions-python/src/main/java/io/trino/plugin/functions/python/PythonFunctionsPlugin.java
plugin/trino-functions-python/src/main/java/io/trino/plugin/functions/python/TimeZoneOffset.java
plugin/trino-functions-python/src/main/java/io/trino/plugin/functions/python/TrinoType.java
plugin/trino-functions-python/src/main/java/io/trino/plugin/functions/python/TrinoTypes.java
plugin/trino-functions-python/src/test/java/io/trino/plugin/functions/python/TestPythonFunctions.java
pom.xml

This adds support for functions using the Python language. Example:
```sql
WITH FUNCTION xor(a boolean, b boolean)
RETURNS boolean
LANGUAGE PYTHON
WITH (handler = 'bool_xor')
AS $$
import operator
def bool_xor(a, b):
return operator.xor(a, b)
$$
SELECT xor(true, false), xor(false, true)
```
The `handler` property specifies the Python function to execute when the Trino function is called.
See `TestPythonFunctions` for more examples.
Python functions are executed in the same JVM as Trino using [Chicory](https://github.com/dylibso/chicory), a native JVM [WebAssembly](https://webassembly.org/) runtime, which is secure and fully sandboxed. The Python environment is limited to 32MB of memory (with the engine creating separate environments for each concurrent function invocation). As with other …

Add Python language functions

---

docs/src/main/sphinx/release/release-467.md

In release note 467, there's a wrong issue number reference about change default protocol for internal communication. The issue #24281 is about changes the docker image, so #24299 is the right one.
```markdown
```

Fix an invalid issue reference in release 467

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogConnectorSmokeTest.java

Add nested namespace support test for Polaris

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java

The recommended way of handling storage tables is to have `iceberg.materialized-views.hide-storage-table` set to true, and not use `iceberg.materialized-views.storage-schema`. `iceberg.materialized-views.hide-storage-table` is already deprecated. We should stick with the default behavior of hiding the storage table from end users, and not having to set a schema for storing them.
```markdown
* Deprecate the `iceberg.materialized-views.storage-schema` configuration property. ({issue}`24398`)
```

Deprecate iceberg.materialized-views.storage-schema property

---

plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlJdbcConnectionAccesses.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlJdbcConnectionCreation.java

Update Postgresql merge related tests 

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestTrinoHiveCatalogWithHiveMetastore.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestTrinoHiveCatalogWithoutHiddenStorageTables.java

This is for cleaning up data files in legacy mode i.e iceberg.materialized-views.hide-storage-table is set to false. Delegating the drop table to metastore does not clean up the data files since for HMS, the iceberg table is registered as an "external" table. So to fix this instead of delegating to metastore, have the connector do the drop of the table and data files associated with it.

Fix storage table data clean up while dropping iceberg materialized view

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ManifestsTable.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java

The column name is `partition_summaries` in Spark: https://iceberg.apache.org/docs/latest/spark-queries/#manifests
It would be nice to rename the column as we usually use partition(s) name when returning partition's key and value (e.g. `{part=2021-01-12}`) with row type. 
Relates to #24101
```markdown
* Rename `partitions` column to `partition_summaries` in `manifests` metadata table. ({issue}`24103`)
```

Rename partitions to partition_summaries in Iceberg manifests table

---

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectionCreationTest.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlJdbcConnectionAccesses.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlJdbcConnectionCreation.java

Postgres connection count/access test cleanups

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergFileOperations.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergGetTableStatisticsOperations.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedView.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMergeAppend.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcMetricsCollection.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithCustomLocation.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithExternalLocation.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTableWithObjectStoreLayout.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

Extract helper method to get HiveMetastore in Iceberg tests

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/ForGlueHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveExecutionInterceptor.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveGlueMetadataListing.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveConcurrentModificationGlueMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestingGlueHiveMetastore.java

Inject execution interceptors using multibinder
The GlueMetastoreModule is not truly following the inversion of control
paradigm. Many things are created directly in the methods without using
injection. Using set multibinder for execution interceptors allows to
independently define execution interceptors and use Guice injection.
Co-authored-by: Grzegorz Kokosiński <grzegorz@starburstdata.com>

Inject execution interceptors using multibinder

---

.github/workflows/ci.yml
plugin/trino-bigquery/README.md
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryMetadata.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadSessionCreator.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
testing/trino-testing-services/src/main/java/io/trino/testing/assertions/Assert.java

Continuation of the https://github.com/trinodb/trino/pull/21017
BigQuery storage APIs support reading BigLake external tables (ie external tables with a connection). But the current implementation uses views which can be expensive, because it requires Trino issuing a SQL query against BigQuery. This PR adds support to read BigLake tables directly using the storage API.
There are no behavior changes for external tables and BQ native tables - they use the view and storage APIs respectively. Added a new test for BigLake tables.
Fixes https://github.com/trinodb/trino/issues/21016
https://cloud.google.com/bigquery/docs/biglake-intro
```markdown
* Improve performance when reading external BigLake tables. ({issue}`21016`)
```

Use BigQuery Read API for reading external BigLake tables

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java

Below is the stack trace for failure
```java
"message": "Failed to open input stream for file: s3://<bucket>/<path>/metadata/snap-xxxxxxx.avro",
"stack": [
"io.trino.plugin.iceberg.fileio.ForwardingInputFile.newStream(ForwardingInputFile.java:55)",
"org.apache.iceberg.avro.AvroIterable.newFileReader(AvroIterable.java:102)",
"org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:77)",
"org.apache.iceberg.avro.AvroIterable.iterator(AvroIterable.java:37)",
"org.apache.iceberg.relocated.com.google.common.collect.Iterables.addAll(Iterables.java:333)",
"org.apache.iceberg.relocated.com.google.common.collect.Lists.newLinkedList(Lists.java:242)",
"org.apache.iceberg.ManifestLists.read(ManifestLists.java:45)",
"org.apache.iceberg.BaseSnapshot.cacheManifests(BaseSnapshot.java:146)", …
```

Correctly categorize filesystem error in Iceberg connector

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/AllManifestsTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/BaseSystemTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/FilesTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadataFactory.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/MetadataLogEntriesTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionsTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/RefsTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/SnapshotsTable.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestTrinoGlueCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestTrinoNessieCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java
plugin/trino-iceberg/src/test/java/org/apache/iceberg/snowflake/TestTrinoSnowflakeCatalog.java

Use existing executor service for scans on system tables in iceberg to prevent excessive cpu/heap usage.
This is especially prevalent for system with high core count.
The existing code was using the threadpool of iceberg library for system tables and another threadpool provided by Trino for normal table scans.
https://trinodb.slack.com/archives/CJ6UC075E/p1733411820070579
```markdown
* Avoid excessive resource usage on coordinator from iceberg system table scans. ({issue}`24396`)
```

Use executor service for iceberg scan planning system tables

---

docs/src/main/sphinx/connector/iceberg.md

Document default value of Iceberg `object_store_enabled` table property

---

plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java

The kudu test uses the first column as the primary key if use `createTableForWrites` to create table, old test would fail because try to update primary key(here is `nationkey`) caused the failure with the duplicated value. The pr fixes this, update `regionkey` instead. Also enable the test.
```markdown
```

Fix and enable kudu update test

---

core/trino-main/src/main/java/io/trino/connector/system/NodeSystemTable.java
core/trino-main/src/main/java/io/trino/memory/ClusterMemoryManager.java
core/trino-main/src/main/java/io/trino/metadata/AllNodes.java
core/trino-main/src/main/java/io/trino/metadata/DiscoveryNodeManager.java
core/trino-main/src/main/java/io/trino/metadata/InMemoryNodeManager.java
core/trino-main/src/main/java/io/trino/metadata/NodeState.java
core/trino-main/src/main/java/io/trino/server/NodeStateManager.java
core/trino-main/src/main/java/io/trino/server/NodeStateManagerModule.java
core/trino-main/src/main/java/io/trino/server/Server.java
core/trino-main/src/main/java/io/trino/server/ServerInfoResource.java
core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
testing/trino-tests/src/test/java/io/trino/tests/TestGracefulShutdown.java

Adds new node states to enable full control over shutdown and reactivation of workers.
- state: DRAINING - a reversible shutdown,
- state: DRAINED - all tasks are finished, server can be safely and quickly stopped. Can still go back to ACTIVE.
For backwards compatibility reasons and to cooperate with shutdown initiated manually or by kubernetes two new states are added `DRAINING` and `DRAINED`. The state `SHUTTING_DOWN` is left as is, without changes. With two new states it is now possible to have a fine grained control over worker shutdown. Trino worker can go from DRAINING or DRAINED to ACTIVE. 
Any tool (for example a kubernetes operator) can now initiate the draining phase before executing a shutdown.  Worker immediately goes to a DRAINING phase and goes through almost all the steps …

Make it possible to reactivate a draining worker node

---

core/trino-main/src/test/java/io/trino/server/security/oauth2/TestingHydraIdentityProvider.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/HydraIdentityProvider.java

Fix build issues on newer OS/hardware. Use latest 1.x release since 2.x causes container start issues without further changes.
Discovered fix in https://github.com/trinodb/trino-gateway/pull/577

Update to oryd/hydra:v1.11.10 for OAuth testing

---

docs/src/main/sphinx/udf/python/examples.md
docs/src/main/sphinx/udf/sql/examples.md

I first tested catalog UDF with Python in the Trino CLI .. and that didnt work. So I completed the initial linked PR without the example that I am now adding here.
The thing I discovered is that it all works in DBeaver with the JDBC driver, so there must be some parsing issue in the CLI. Let me know if you want me to file a separate issue @electrum 
Basically if I enter the query in the CLI to create the function .. I cant press enter to run it .. it just keeps adding empty lines
So I think we ideally should fix the CLI before the release or before we merge this PR.
Update.. I tested with an old CLI .. will verify with 468-snapshot version.
Further update @electrum  - it works fine with CLI from 468 .. so.. do we need to document that somewhere ..
#24441
(x) This is not user-visible or is …

Update inline and catalog UDF docs

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-468.md

Assemble the release notes for the upcoming Trino 467 release.
See https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A468
* #24235 ✅ rn ✅ docs
* #24391 ✅ rn ✅ docs
* #23655 ✅ rn ✅ docs
* #23432 ✅ rn ✅ docs
* #24105 ✅ rn ✅ docs
* #24378 ✅ rn ✅ docs
* #23518 ✅ rn ✅ docs
* #24406 ✅ rn ✅ docs
* #24411 ✅ rn ✅ docs
* #24413 ✅ rn ✅ docs
* #23034 ✅ rn ✅ docs
* #24401 ✅ rn ✅ docs
* #24422 ✅ rn ✅ docs
* #24398 ✅ rn ✅ docs
* #24429 ✅ rn ✅ docs
* …

Add Trino 468 release notes

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushJoinIntoTableScan.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/BaseMariaDbFailureRecoveryTest.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlFailureRecoveryTest.java
plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleFailureRecoveryTest.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/BasePostgresFailureRecoveryTest.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/BaseRedshiftFailureRecoveryTest.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerFailureRecoveryTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Allow left side as update target when try to pushdown join into table scan. This can happen because the
`DELETE` or `UPDATE` is planned as the `MERGE`, it's implemented contains the logic of `target` right join on `source` part.
Close https://github.com/trinodb/trino/issues/17003
```markdown
* Allow left side as update target in join pushdown. ({issue}`issuenumber`)
```

Allow left side as update target in join pushdown

---

plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduClientSession.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduConnector.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduMetadata.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduModule.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/properties/KuduColumnProperties.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/properties/KuduTableProperties.java

Extract KuduColumnProperties from KuduTableProperties

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3InputStream.java

When the skip(n) method is called the MAX_SKIP_BYTES check is skipped, resulting in the call potentially blocking for a long time.
Instead of delegating to the underlying stream, set the nextReadPosition value. This allows the next read to decide if it is best to keep the existing s3 object stream or open a new one.
This behavior matches the implementations for [Azure](https://github.com/trinodb/trino/blob/master/lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureInputStream.java#L132) and [GCS](https://github.com/trinodb/trino/blob/master/lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsInputStream.java#L141).
( ) Release notes are required. Please propose a release note …

Fix S3InputStream's handling of large skips

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeletionVectorEntry.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java

@vkorukanti told us that we are missing deletion vector id in the key. The corresponding delta-kernel code:
* [ActiveAddFilesIterator.java#L176](https://github.com/delta-io/delta/blob/34f02d8/kernel/kernel-api/src/main/java/io/delta/kernel/internal/replay/ActiveAddFilesIterator.java#L176)
* [DeletionVectorDescriptor.java](https://github.com/delta-io/delta/blob/34f02d8/kernel/kernel-api/src/main/java/io/delta/kernel/internal/actions/DeletionVectorDescriptor.java#L167-L174)
Hopefully, solves #22972. This PR doesn't contain tests because the entire steps to reproduce is still unclear. 

Include deletion vector when filtering active add entries in Delta

---

core/trino-main/src/main/java/io/trino/operator/ExchangeOperator.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
core/trino-main/src/main/java/io/trino/testing/PlanTester.java

Refactor the PlanTester to pass the nonnull `directExchangeClientSupplier`. Also add nonnull check for the `sourceId`, `serdeFactory` in `ExchangeOperator`
```markdown
```

Add nonnull check for directExchangeClientSupplier

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/EntriesTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/FilesTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableType.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogAccessOperations.java

Add `entries` table which show all the table's current manifest entries for both data and delete files.
Spark documentation: https://iceberg.apache.org/docs/latest/spark-queries/#entries
Documentation will be added in a follow-up. 
```markdown
* Add `$entries` metadata table. ({issue}`issuenumber`)
```

Add `$entries` metadata table to Iceberg

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergLocalConcurrentWrites.java

Concurrent tests are inherently non-deterministic so they should be run multiple times for better test coverage.
```markdown
```

Run Iceberg concurrent tests multiple times

---

docs/src/main/sphinx/connector/iceberg.md

A trivial doc update to describe how users can explicitly specify sort directions or null ordering when we create a sorted table of Apache Iceberg.
We found no Trino document mentioning the advanced parameters of `sorted_by` [while developing Apache Hive](https://github.com/apache/hive/pull/5541#discussion_r1875869433). Simply, we misunderstood that Trino would not have the capability at first glance. I believe some people would love the information.

Document sort direction and null order in Iceberg

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadataFactory.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestTrinoGlueCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestTrinoNessieCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java
plugin/trino-iceberg/src/test/java/org/apache/iceberg/snowflake/TestTrinoSnowflakeCatalog.java

This PR addresses a performance issue encountered when querying column metadata from the Iceberg catalog in Trino (Issue #[23468](https://github.com/trinodb/trino/issues/23468)). The primary concern is that requests to retrieve table metadata are executed sequentially for each table, which significantly impacts query performance when dealing with a large number of tables.
The issue manifests when executing the following query on the Iceberg catalog:
```sql
SELECT * FROM iceberg.information_schema.columns;
```
In environments with a large number of tables, the query’s response time increases considerably due to the sequential execution of catalog requests.
To improve the performance, this PR introduces parallelism in the metadata retrieval process. The old code executed catalog requests …

Improve performance when listing columns in Iceberg

---

plugin/trino-opa/src/test/java/io/trino/plugin/opa/OpaContainer.java

Version 1.0.0~ doesn't pass CI. 
Fixes #24559

Pin openpolicyagent/opa version as 0.70.0

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestTrinoGlueCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/snowflake/TestIcebergSnowflakeCatalogConnectorSmokeTest.java

Fixes ci failures introduced by https://github.com/trinodb/trino/pull/24469
```markdown
```

Fix failures in iceberg cloud tests

---

testing/trino-product-tests-groups/src/main/java/io/trino/tests/product/TestGroups.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCaseInsensitiveMapping.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeChangeDataFeedCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCheckpointsCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCreateTableAsSelectCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeIdentityColumnCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeInsertCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeSelectCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeUpdateCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java

10.4 LTS is a part of `delta-lake-databricks` now. 

Remove unused delta-lake-databricks-104 test group

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/EntriesTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableType.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogAccessOperations.java

Add `$all_entries` metadata table to Iceberg. 
Docs will be added in https://github.com/trinodb/trino/pull/24542
```markdown
* Add `$all_entries` metadata table. ({issue}`24543`)
```

Add `$all_entries` metadata table to Iceberg

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractIcebergTableOperations.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAbfsConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergGcsConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/jdbc/TestIcebergJdbcCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestIcebergNessieCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogNestedNamespaceConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergTrinoRestCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergUnityRestCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergVendingRestCatalogConnectorSmokeTest.java

When using the iceberg table, the xxx-metadata.json file is generated each time commit is executed. In the iceberg table, we can automatically clean the previous metadata file through configuration.
`write.metadata.delete-after-commit.enabled = true` 
`write.metadata.previous-versions-max = 10`
However, the metadata file is not automatically cleaned in trino. A large number of metadata.json files are left on the hdfs.
Different from https://github.com/trinodb/trino/pull/20863 ，I have followed the configurations in iceberg (write.metadata.delete-after-commit.enabled and write.metadata.previous-version-max ). Instead of adding a new configuration, this keeps it compatible with iceberg.
* https://iceberg.apache.org/docs/latest/maintenance/#remove-old-metadata-files
Relates to #14128 …

Delete the oldest tracked version metadata files after commit in Iceberg

---

docs/src/main/sphinx/connector/delta-lake.md
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheFileOperations.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheMutableTransactionLog.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/AbstractSinglenodeDeltaLakeDatabricks.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeInsertCompatibility.java

```markdown
* Improve performance of reading from delta lake tables by compressing files with `ZSTD` by default ({issue}`17426`)
```

Use by default `ZSTD` Parquet compression codec for Delta Lake

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetWithBloomFilters.java

```markdown
* Allow configuring the `parquet_bloom_filter_columns` table property. ({issue}`24573`)
```

Allow configuring `parquet_bloom_filter_columns` with `SET PROPERTIES` in Iceberg

---

plugin/trino-faker/pom.xml
plugin/trino-faker/src/main/java/io/trino/plugin/faker/ColumnInfo.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/FakerQueryRunner.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerViews.java

```markdown
* Add support for views. ({issue}`24242`)
```

Support managing views in the Faker connector

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/cli/TestTrinoCli.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/cli/TestTrinoLdapCli.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCreateTableAsSelectCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeUpdateCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/BaseTestHiveCoercion.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSchemaUrl.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestGrantRevoke.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveBasicTableStatistics.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTableStatistics.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViewsLegacy.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestRoles.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/jdbc/BaseLdapJdbcTest.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/jdbc/TestLdapTrinoJdbc.java

Rename to Trino in product tests

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/EnvironmentUp.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/TestRun.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Environment.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentModule.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentOptions.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Ipv6.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/StandardMultinode.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeTls.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeTlsKerberos.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeTlsKerberosDelegation.java

Allow running product tests on IPv6 stack

---

core/trino-main/src/main/java/io/trino/util/DateTimeUtils.java

Remove unreachable code in OrderedPeriodParser

---

docs/src/main/sphinx/connector/faker.md
plugin/trino-faker/pom.xml
plugin/trino-faker/src/main/java/io/trino/plugin/faker/ColumnInfo.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerConnector.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerPageSource.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java

Support generating sequences in the Faker connector. It might be useful for columns representing primary keys, which often use sequences. Another use case would be equal distribution of values in temporal columns.
There's also no other easy way of generating sequences for timestamps, since the `sequence` function has a limit of 10k elements, and the `sequence` table function doesn't support temporal types at all.
It's a prerequisite for #24585
There are a few limitations:
* not checking for overflows for large steps
* small increments are not supported in some cases - like nanosecond steps with timestamp(9) 
(x) Release notes are required, …

Support generating sequences in the Faker connector

---

client/trino-client/src/main/java/io/trino/client/uri/HttpClientFactory.java

Unauthenticated client can connect to the Trino cluster when loading segment data. If cluster has its' own certificate chain - client needs to accept it according to the configuration.
```markdown
* Fix loading spooled segment data when cluster is secured ({issue}`issuenumber`)
```

Configure SSL for unauthenticated client

---

core/trino-main/src/main/java/io/trino/server/NodeResource.java
core/trino-main/src/main/java/io/trino/server/QueryResource.java
core/trino-main/src/main/java/io/trino/server/QueryStateInfoResource.java
core/trino-main/src/main/java/io/trino/server/ResourceGroupStateInfoResource.java
core/trino-main/src/main/java/io/trino/server/StatusResource.java
core/trino-main/src/main/java/io/trino/server/TaskExecutorResource.java
core/trino-main/src/main/java/io/trino/server/TaskResource.java
core/trino-main/src/main/java/io/trino/server/ThreadResource.java
core/trino-main/src/main/java/io/trino/server/protocol/ExecutingStatementResource.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/CoordinatorSegmentResource.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/WorkerSegmentResource.java
core/trino-main/src/main/java/io/trino/server/security/ResourceAccessType.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2CallbackResource.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2TokenExchangeResource.java
core/trino-main/src/main/java/io/trino/server/ui/ClusterResource.java
core/trino-main/src/main/java/io/trino/server/ui/ClusterStatsResource.java
core/trino-main/src/main/java/io/trino/server/ui/LoginResource.java
core/trino-main/src/main/java/io/trino/server/ui/UiQueryResource.java
core/trino-main/src/main/java/io/trino/server/ui/WebUiPreviewStaticResource.java
core/trino-main/src/main/java/io/trino/server/ui/WebUiStaticResource.java
core/trino-main/src/main/java/io/trino/server/ui/WorkerResource.java

Class-level resource access type

---

core/trino-parser/src/main/java/io/trino/sql/tree/LongLiteral.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java

Fixes https://github.com/trinodb/trino/issues/24601
```markdown
* Fix parsing of negative 0x, 0b, 0o long literals ({issue}`issuenumber`)
```

Fix parsing of negative 0x, 0b, 0o long literals

---

.github/workflows/ci.yml
core/trino-main/src/main/java/io/trino/operator/SplitOperatorInfo.java
core/trino-main/src/test/java/io/trino/operator/TestOperatorStats.java
docs/src/main/sphinx/connector/redshift.md
plugin/trino-redshift/pom.xml
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClientModule.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftConfig.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftConnector.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftConnectorFactory.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftErrorCode.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftPageSourceProvider.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftParquetPageSource.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftPlugin.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftSessionProperties.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftSplitManager.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftUnloadConnector.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftUnloadJdbcQueryEventListener.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftUnloadSplit.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftUnloadSplitSource.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/TrinoParquetDataSource.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/RedshiftQueryRunner.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftConfig.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftPlugin.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftUnload.java
plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftUnloadTypeMapping.java

Redshift supports unloading select query results to S3 using UNLOAD command. PR aims to use unload command to unload Redshift query results on S3 and to read generated redshift query results files in parallel.
Official documentation on Redshift unload command:
https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html
https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD_command_examples.html
Connector internally converts Trino SQL to Redshift's unload SQL and runs it. Resultant Parquet files containing query results will be read in parallel to generate Trino query result. Only Parquet file format is supported in Redshift unload command.
Below are certain limitations for which Trino internally force fallback to traditional JDBC even if connector is configured to use unload.
- select …

Add support for fetching Redshift query results using Redshift unload command

---

lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileIterator.java
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioFileSystem.java
lib/trino-filesystem-alluxio/src/main/java/io/trino/filesystem/alluxio/AlluxioUtils.java
lib/trino-filesystem-alluxio/src/test/java/io/trino/filesystem/alluxio/TestAlluxioFileIterator.java

When use alluxio as hive fs,cant get data from alluxio.
I finaly found that the AlluxioIterator.java didn't generate correct file location as alluxio://192...../dir/filename but alluxio:///dir/filename
Fixes #23778
```markdown
* Fix reading from tables when using alluxio filesystem. ({issue}`23815`)
```

Fix listing of files in AlluxioFileSystem

---

docs/src/main/sphinx/connector/faker.md

Add info about views in memory only

---

docs/src/main/sphinx/connector/alter-schema-limitation.fragment
docs/src/main/sphinx/connector/alter-table-limitation.fragment
docs/src/main/sphinx/connector/clickhouse.md
docs/src/main/sphinx/connector/druid.md
docs/src/main/sphinx/connector/exasol.md
docs/src/main/sphinx/connector/ignite.md
docs/src/main/sphinx/connector/mariadb.md
docs/src/main/sphinx/connector/mysql.md
docs/src/main/sphinx/connector/non-transactional-merge.fragment
docs/src/main/sphinx/connector/oracle.md
docs/src/main/sphinx/connector/phoenix.md
docs/src/main/sphinx/connector/postgresql.md
docs/src/main/sphinx/connector/redshift.md
docs/src/main/sphinx/connector/singlestore.md
docs/src/main/sphinx/connector/snowflake.md
docs/src/main/sphinx/connector/sql-delete-limitation.fragment
docs/src/main/sphinx/connector/sql-update-limitation.fragment
docs/src/main/sphinx/connector/sqlserver.md
docs/src/main/sphinx/connector/vertica.md

* First improve the MERGE limitation and make it a fragment
* Move the limitations into SQL support section, add headers, and improve overview list
* Add for Ignite and Phoenix
Follow up to #23034 and related PRs. 

Improve connector SQL support sections

---

docs/src/main/sphinx/object-storage/file-system-s3.md
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3Context.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3SecurityMapping.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3SecurityMappingConfig.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3SecurityMappingProvider.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3SecurityMappingResult.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3SecurityMapping.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3SecurityMappingConfig.java
lib/trino-filesystem-s3/src/test/resources/io/trino/filesystem/s3/security-mapping.json

Add SSE-C option on native-filesystem security mapping

---

core/trino-main/src/main/java/io/trino/server/protocol/JsonEncodingUtils.java
core/trino-main/src/test/java/io/trino/operator/aggregation/TestQuantileDigestAggregationFunction.java
core/trino-main/src/test/java/io/trino/operator/aggregation/TestQuantileDigestFunctions.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/type/SqlDate.java
core/trino-spi/src/main/java/io/trino/spi/type/SqlDecimal.java
core/trino-spi/src/main/java/io/trino/spi/type/SqlTime.java
core/trino-spi/src/main/java/io/trino/spi/type/SqlTimeWithTimeZone.java
core/trino-spi/src/main/java/io/trino/spi/type/SqlTimestamp.java
core/trino-spi/src/main/java/io/trino/spi/type/SqlTimestampWithTimeZone.java
core/trino-spi/src/main/java/io/trino/spi/type/SqlVarbinary.java
core/trino-spi/src/test/java/io/trino/spi/type/TestSqlVarbinary.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/util/JsonTypeUtil.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java

Sql types SPI cleanup

---

lib/trino-hdfs/src/main/java/io/trino/hdfs/s3/AwsSdkClientCoreStats.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/v1/AwsSdkClientCoreStats.java

For retry count metric for Trino S3 file system, we are more interested in [RetryCount](https://github.com/aws/aws-sdk-java/blob/9197e60ae6388e4b00da4cc0a444f161ad49aa6a/aws-java-sdk-core/src/main/java/com/amazonaws/util/AWSRequestMetrics.java#L97) than [HttpClientRetryCount](https://github.com/aws/aws-sdk-java/blob/9197e60ae6388e4b00da4cc0a444f161ad49aa6a/aws-java-sdk-core/src/main/java/com/amazonaws/util/AWSRequestMetrics.java#L110). But Trino was only tracking HttpClientRetryCount and not RetryCount.
Definition from aws java sdk v1 github is as follows
RetryCount - Number of retries of AWS SDK sending a request to AWS.
HttpClientRetryCount - Number of retries of the underlying http client library in sending a request to AWS.
And RetryCount count should be derived from RequestCount …

Derive aws sdk retry count from request count

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/CreateEmptyPartitionProcedure.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/DropStatsProcedure.java

This is to prevent unnecessary classcast issues when tableHandle is not always HiveTableHandle
```markdown
```

Minor cleanup in Hive Procedures

---

lib/trino-parquet/src/main/java/io/trino/parquet/metadata/ParquetMetadata.java
lib/trino-parquet/src/main/java/io/trino/parquet/predicate/PredicateUtils.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/MetadataReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
lib/trino-parquet/src/test/java/io/trino/parquet/ParquetTestUtils.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetReader.java
lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheFileOperations.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAlluxioCacheMutableTransactionLog.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSourceProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergParquetFileWriter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/ParquetUtil.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java

Optimize parsing of parquet footers for files with a large number of row groups
Extracts relevant commits from https://github.com/trinodb/trino/pull/24007 and applies review comments
```markdown
* Improve performance of reading from parquet files with a large number of row groups. ({issue}`24618`)
```

Optimize parsing of parquet footers

---

plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/TestRedshiftUnload.java

AbstractTestQueries was extended to cover different Trino query shapes.
However, it may not be necessary as there are query shape duplicates in 
AbstractTestQueries. Additionally, AbstractTestQueries doesn't cover 
different query shapes.
```markdown
```

Extend AbstractTestQueryFramework in TestRedshiftUnload

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/thrift/DeltaLakeThriftMetastoreModule.java

@electrum pointed out the class is wrong. 
The difference between `DeltaLakeFileMetastoreTableOperationsProvider` and `DeltaLakeThriftMetastoreTableOperationsProvider` is the latter has a lock mechanism. It was working without a lock in case of Thrift metastore deployment. 

Use correct table operations provider for Thrift metastore in Delta

---

lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsFileSystemConfig.java
lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsStorageFactory.java
lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsFileSystemConfig.java

```markdown
* Allow configuring service endpoint via `gcs.endpoint` property. ({issue}`issuenumber`)
```

Allow configuring gcs service endpoint

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcWithBloomFilters.java

```markdown
* Allow configuring the `orc_bloom_filter_columns` table property. ({issue}`24584`)
```

Allow configuring `orc_bloom_filter_columns` with `SET PROPERTIES` in Iceberg

---

plugin/trino-ranger/pom.xml

We are not using it for other modules which results in the build output being inconsistent
```markdown
```

Remove <name> from trino-ranger pom

---

client/trino-client/src/main/java/io/trino/client/ClientStandardTypes.java
client/trino-client/src/main/java/io/trino/client/JsonDecodingUtils.java
core/trino-main/src/main/java/io/trino/type/ColorType.java
core/trino-main/src/main/java/io/trino/type/TypeCoercion.java
core/trino-main/src/main/java/io/trino/type/setdigest/BuildSetDigestAggregation.java
core/trino-main/src/main/java/io/trino/type/setdigest/MergeSetDigestAggregation.java
core/trino-main/src/main/java/io/trino/type/setdigest/SetDigestFunctions.java
core/trino-main/src/main/java/io/trino/type/setdigest/SetDigestOperators.java
core/trino-main/src/main/java/io/trino/type/setdigest/SetDigestType.java
core/trino-spi/src/main/java/io/trino/spi/type/StandardTypes.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/BingTileFunctions.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/BingTileType.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/EncodedPolylineFunctions.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/GeoFunctions.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/GeometryType.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/KdbTreeCasts.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/KdbTreeType.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/SpatialPartitioningAggregateFunction.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/SpatialPartitioningInternalAggregateFunction.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/SphericalGeographyType.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/aggregation/ConvexHullAggregation.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/aggregation/GeometryUnionAgg.java

```markdown
* Fix deserialization of SetDigest, BingTile, Kdb Tree, Color types({issue}`issuenumber`)
```

Fix SetDigest, BingTile, Kdb Tree, Color types (de)serialization in client protocol

---

docs/src/main/sphinx/admin/properties-client-protocol.md
docs/src/main/sphinx/client/client-protocol.md

New spooling protocol documentation ought to clarify that the object storage location used for spooling must not be shared with either an object storage catalog or another Trino cluster's spooling.
N/A
```markdown
```

Clarify that spooling locations must not be shared

---

docs/src/main/sphinx/object-storage/file-system-gcs.md

Add docs for gcs.endpoint

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/phoenix/TestPhoenix.java

Enable Phoenix product tests.
HBase 2.5.10 has a fix required to stabilize Phoenix tests in the docker environment. Since Phoenix 5.2.1 with HBase 2.5.10-hadoop3 are already used by Trino, the fix is available for trino to consume.

Enable Phoenix product test

---

docs/src/main/sphinx/security/opa-access-control.md

Docs do not match implementation for the `opa.allow-permission-management-operations` configuration property
This is not user-visible or is docs only, and no release notes are required.

fix(docs): OPA allow-permission-management-operations config name

---

.github/DEVELOPMENT.md

Aplhabetize additional IDE configurations on docs

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java

We should inherit the old deletion vector entry in `remove`. 
Fixes #24648
```markdown
* Fix incorrect results when writing with deletion vectors. ({issue}`24648`)
```

Fix correctness issue when writing deletion vectors in Delta Lake

---

docs/src/main/sphinx/object-storage/file-system-gcs.md

Silly cut and paste typo we missed in review.
#24645 

Fix gcs.endpoint property name in docs

---

testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/common/hadoop-kerberos/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/common/standard-multinode/multinode-master-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/common/standard-multinode/multinode-worker-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/common/standard/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/common/task-retries-multinode/multinode-master-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/common/task-retries-multinode/multinode-worker-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-postgresql-spooling/coordinator-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-postgresql-spooling/worker-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-secrets-provider/config-master.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-secrets-provider/config-worker.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-tls-kerberos/config-master.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-tls-kerberos/config-worker.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-tls/config-master.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/multinode-tls/config-worker.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-compatibility/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-ldap-and-file/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-ldap/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-oauth2-authenticated-http-proxy/trino/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-oauth2-authenticated-https-proxy/trino/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-oauth2-http-proxy/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-oauth2-https-proxy/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-oauth2-refresh/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-oauth2/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-oidc-refresh/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-oidc/config.properties

Since this uses the default catalog store set to `file`, there should not be issues with switching it all over to dynamic catalog management.
```markdown
```

Enable dynamic catalogs for product-tests

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/DeltaLakeSchemaSupport.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogParser.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTransactionLogParser.java
pom.xml
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeColumnMappingMode.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeSystemTableCompatibility.java

Relates to https://github.com/trinodb/docker-images/pull/221
`protocol` entry has been changed when creates a table on Spark:
```
{"protocol":{"minReaderVersion":2,"minWriterVersion":5}}
```
↓
```json
{"protocol":{"minReaderVersion":2,"minWriterVersion":7,"writerFeatures":["columnMapping","changeDataFeed","appendOnly","invariants"]}}
```
Fixes #24647

Allow parsing ISO8601 timestamp in Delta lake transaction log + Update docker-images to 108

---

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
core/trino-main/src/main/java/io/trino/execution/QueryStateMachine.java

Disable spooling through session property

---

docs/src/main/sphinx/connector/iceberg.md

Follow-up of https://github.com/trinodb/trino/pull/24172

Document $entries table in Iceberg

---

docs/src/main/sphinx/connector/bigquery.md

I have no idea if the connector supports others as well, but we have to start somewhere.
Follow up to #24021 
Also fyi @jhlodin 

Document limit pushdown in BigQuery connector

---

plugin/trino-redshift/src/test/java/io/trino/plugin/redshift/RedshiftQueryRunner.java

Granting privileges on all tables may cause unintended failures, as temporary tables created in one test class may not have been fully dropped or cleaned up from internal Redshift tables while other test class executes grant privileges on all tables.
Closes https://github.com/trinodb/trino/issues/24631

Grant privileges only on TPCH tables in Redshift query runner

---

testing/trino-testing-containers/src/main/java/io/trino/testing/containers/TestContainers.java

The logic was mistakenly inverted in
a99d96ece15113d4edf204f5a5345b26f5c9721f.

Fix query runners failing to expose local ports

---

core/trino-main/src/main/java/io/trino/execution/DataDefinitionExecution.java
core/trino-main/src/main/java/io/trino/testing/StandaloneQueryRunner.java
core/trino-main/src/main/java/io/trino/testing/TestingDirectTrinoClient.java
testing/trino-tests/src/test/java/io/trino/execution/TestQueryCompletedEvent.java

Previously the event was fired because client protocol
is reading the final query info. That is brittle and theoretically
could be removed making DDL queries fail to trigger query completed event.
A slightly changed version of https://github.com/trinodb/trino/pull/24354
```markdown
```

Always fire QueryCompletedEvent for DDL queries

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcConnector.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcModule.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSourceProvider.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClientModule.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClientModule.java

Refactor JDBC module

---

docs/src/main/sphinx/connector/clickhouse.md
plugin/trino-clickhouse/pom.xml
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClientModule.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestingClickHouseServer.java
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeClickhouse.java
testing/trino-product-tests/pom.xml

() Release notes are required. Please propose a release note for me.
```markdown
* Update supported clickhouse versions. ({issue}`24515`)
```

Update supported clickhouse versions

---

client/trino-client/src/main/java/io/trino/client/uri/ConnectionProperties.java
client/trino-client/src/main/java/io/trino/client/uri/PropertyName.java
client/trino-client/src/main/java/io/trino/client/uri/TrinoUri.java
client/trino-client/src/test/java/io/trino/client/uri/TestTrinoUri.java
client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcConnection.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriver.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverUri.java
core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
docs/src/main/sphinx/client/jdbc.md

- Support `HEAD /v1/statement`, this allows client to validate authentication without submitting a query.
- Add `validateConnection` property that allows validating connection when making a JDBC connection - #16504
- Fix JDBC `Connection.isValid(int)` - fix #22684
```markdown
* Fix JDBC `Connection.isValid(int)` which does not validate connection and/or credentials. ({issue}`22684`)
* Add `validateConnection` JDBC property that allows validating connection when making a JDBC connection. ({issue}`16504`)
```

Support JDBC validate connection

---

docs/src/main/sphinx/security/built-in-system-access-control.md
docs/src/main/sphinx/security/opa-access-control.md
docs/src/main/sphinx/security/ranger-access-control.md

Centralize and clarify usage with multiple access control systems.
See https://github.com/trinodb/trino/issues/20152

Clarify docs for multiple access controls

---

core/trino-web-ui/src/main/resources/webapp/src/components/WorkerStatus.jsx

There are the list of queries on the worker status view.
It would be more useful if this list is sorted by memory to find memory consuming queries on the worker.
Before (Queries are listed randomly):
After (Queries are sorted by reserved memory):
```markdown
* Sort queries on worker status web ui by descending reserved memory. ({issue}`24475`)
```

Sort queries on worker status web ui by descending reserved memory

---

docs/src/main/sphinx/connector/iceberg.md

Look at the two commits separately when reviewing .. second commit is just trivial formatting stuff.
More general questions however is .. why do we even have two metadata tables .. if $entries is just a subset of $all_entries would it make sense to just have one table and just use a where clause or whatever when you want to limit data? Sort of reflecting the question from @raunaqmorarka at https://github.com/trinodb/trino/pull/24543#discussion_r1895888496
But maybe this is just how it works in Iceberg .. 
https://github.com/trinodb/trino/pull/24543

Docs for Iceberg $all_entries

---

core/trino-web-ui/src/main/resources/webapp-preview/package.json
core/trino-web-ui/src/main/resources/webapp-preview/src/api/base.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/api/webapp/api.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/api/webapp/auth.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/components/Auth.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/AuthContext.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/components/AuthProvider.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/CodeBlock.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/Dashboard.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/DemoComponents.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/Layout.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/Login.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/MetricCard.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/SnackbarContext.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/components/SnackbarProvider.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/Workers.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/store/config.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/store/index.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/utils/merge.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/utils/utils.ts

The TypeScript code in the preview web UI is currently not properly formatted due to an incorrect Prettier configuration, which does not include recursive formatting for `.ts` and `.tsx` files. This PR resolves the issue by updating the Prettier configuration and reformatting all files to the correct format.
No functional changes are included.
The fix involves updating the Prettier target in package.json (located [here](https://github.com/trinodb/trino/pull/24691/files#diff-2ff08f9f500a878b341f9d3f32d35221ebb4b6795774c06342d2e277f9021612R13)) by changing the pattern from `./src/*.{ts,tsx}` to `./src/**/*.{ts,tsx}` in order to include all recursive TypeScript files.
( ) Release notes are required. Please …

Fix code formatting in Preview Web UI

---

plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/properties/KuduTableProperties.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/properties/RangePartitionDefinition.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java

Fix #24661 
The current Kudu connector does not support unpartitioned tables, as it assumes the existence of partition keys. However, Kudu itself allows the creation of unpartitioned tables. Interacting with such tables may result in issues like the error partitioning information is missing, as mentioned in #24661.
Refer [IMPALA-5546](https://issues.apache.org/jira/browse/IMPALA-5546), unpartitioned tables can be handled by using range partitions without specifying any columns.
```markdown
* Support unpartitioned table. ({issue}`24661`)
```

Support unpartitioned tables in Kudu

---

core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java

Fix flaky test in TestQueryManagerConfig
This test relies on rounding large integers and will sometimes fail depending on the amount of memory available to the test runner.
This commit reuses the exact same calculation for tests as it does in the code, so that we will always get the correct value for the default.

Fix flaky TestQueryManagerConfig

---

docs/.vale/config/vocabularies/Base/accept.txt
docs/src/main/sphinx/admin/fault-tolerant-execution.md

- also fix a bunch of style and formatting issues on the page
I left a comment for the actual content changes in the PR so you can see easier

Add retry_policy session property docs

---

docs/src/main/sphinx/connector/bigquery.md
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryRpcConfig.java

Documents the settings from the https://github.com/trinodb/trino/blob/29ffc6c1c7d93bbd22ccdccb98ba39a5fab1fd68/plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryRpcConfig.java config class.
```markdown
```

Document BigQuery RPC settings

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/DeltaTableOptimizeHandle.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeLocalConcurrentWritesTest.java

Allow committing `OPTIMIZE` operations in a concurrent context
by placing these operations right after any other previously
concurrently completed write operations.
Fixes https://github.com/trinodb/trino/issues/16985
```markdown
* Add support for concurrent execution of `OPTIMIZE`. ({issue}`16985`)
```

Add concurrent writes reconciliation for OPTIMIZE in Delta Lake

---

docs/src/main/sphinx/client/client-protocol.md

To be merged after the Python client release is done.
https://github.com/trinodb/trino-python-client/pull/509

Add info about Python client spooling support

---

core/trino-main/src/main/java/io/trino/server/ThrowableMapper.java
pom.xml

Hopefully fixes https://github.com/trinodb/trino/issues/24572
```markdown
```

Update airlift to 296

---

core/trino-main/src/main/java/io/trino/server/ui/TrimmedBasicQueryInfo.java
core/trino-web-ui/src/main/resources/webapp/src/components/QueryList.jsx

Currently it is not possible to filter out queries in the Web UI by the client tags values which becomes annoying to find specific queries when there are 30 of them running in parallel. This change adds support to filter queries by client tags in Web UI by modifying the `api/query` endpoint response to include additional value and adapting the UI part to do filtering.
Add support for filtering by query client tags in the Web UI.

Add support for filtering queries by client tags in the Web UI

---

plugin/trino-exasol/src/test/java/io/trino/plugin/exasol/TestingExasolServer.java

Fixes #22698.
The CI pipeline runs several tests that boot up an Exasol container, using `testcontainers`. An Exasol container by default exposes 4 ports for different services. Docker tries to allocate and map ephemeral ports. 
Due to an issue in docker, when it fails to allocate a port in can mess up with the process that was using this port (see https://github.com/moby/moby/pull/48132)
The issue only happens when more than one port is exported, so the fix is rather simple: we only export in the container the strictly needed port for JDBC: 8563

Fix Exasol flaky tests. Avoid exposing not required ports

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultQueryBuilder.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Close #24204 
```markdown
* Fix failure when updating values with `NULL`. ({issue}`24204`)
```

Fix failure when setting NULL in UPDATE statement in JDBC-based connectors

---

docs/src/main/sphinx/functions/json.md
docs/src/main/sphinx/sql/select.md

Replaces #20338 
First released in 435 with https://github.com/trinodb/trino/pull/18017
Fix for being able to test it at all is in 436 - https://github.com/trinodb/trino/pull/20122

Add docs for json_table

---

plugin/trino-elasticsearch/pom.xml
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/BuiltinColumns.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchColumnHandle.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchMetadata.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchTableHandle.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ScanQueryPageSource.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/client/IndexMetadata.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/ArrayDecoder.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/BigintDecoder.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/BooleanDecoder.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/DoubleDecoder.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/IntegerDecoder.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/IpAddressDecoder.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/RawJsonDecoder.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/RealDecoder.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/RowDecoder.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/TimestampDecoder.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/TinyintDecoder.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/VarbinaryDecoder.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/decoders/VarcharDecoder.java
plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/ElasticsearchServer.java
plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearchComplexTypePredicatePushDown.java
plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearchProjectionPushdownPlans.java
plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearchQueryBuilder.java

Add dereference pushdown support in ElasticSearch. (Issue: https://github.com/trinodb/trino/issues/23069)
Learn more about dereference pushdown at
https://trino.io/docs/current/optimizer/pushdown.html#dereference-pushdown
https://trino.io/blog/2020/08/14/dereference-pushdown.html
The feature is enabled by default. Based on reference implementation for OpenSearch dereference pushdown in https://github.com/trinodb/trino/pull/22646
```markdown
*Improve performance of queries that reference nested fields from Elasticsearch documents. ({issue}`23069`)
```

Add support for dereference pushdown in Elasticsearch

---

core/trino-main/src/main/java/io/trino/execution/TaskManagerConfig.java
core/trino-main/src/test/java/io/trino/execution/TestTaskManagerConfig.java

Default 15m sometiems causes some significant OOM issues on workers.
Related to https://github.com/trinodb/trino/pull/24729
```markdown
```

Reduce task.info.max-age to 5m

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestThriftHttpMetastoreClient.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestingThriftHttpMetastoreServer.java

This PR adds a test for `ThriftHiveMetastoreClient::getTableMeta`.
```markdown
```

Improve test coverage for ThriftHttpMetastoreClient

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergFileOperations.java

This test showcases that there is partition pruning done at the Iceberg metadata layer even though EXPLAIN showcases that a filter that does not fully match the partition transform is not being pushed down.
Fixes https://github.com/trinodb/trino/issues/19266
Cosmetic changes applied on https://github.com/trinodb/trino/pull/24483
```markdown
```

Test the effectiveness of partial partition pruning

---

docs/src/main/sphinx/release/release-468.md
docs/src/main/sphinx/udf/python.md

The feature is essentially stable and completely usable. No need to scare users away.
Discussed with @electrum 

Remove experimental warning for Python UDF

---

.github/workflows/ci.yml
plugin/trino-bigquery/README.md
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryQueryRunner.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQuerySplitManager.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryWithDifferentProjectIdConnectorSmokeTest.java

`bigquery.credentials-key` testing config name clashes with the actual config name and hence any new bigquery catalogs created through `CREATE CATALOG` command by running BigQueryQueryRunner may not pick the different key if provided in command.

Rename BigQuery test credentials key config

---

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
core/trino-main/src/main/java/io/trino/execution/QueryStateMachine.java
core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingConfig.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingServerModule.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingSessionProperties.java

```markdown
* Allow configuring spooling behaviour via session properties ({issue}`issuenumber`)
```

Dynamically configure spooling properties

---

core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
core/trino-main/src/main/java/io/trino/testing/PlanTester.java
core/trino-main/src/test/java/io/trino/execution/TaskTestUtils.java

Remove unused argument

---

core/trino-main/src/main/java/io/trino/sql/planner/plan/TableScanNode.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestMultipleDistinctAggregationsToSubqueries.java

Before this change, only one-way match was verified: that each output symbol is backed by an assignment.
no docs or relnotes needed

Verify that TableScanNode's assignments match the output symbols

---

plugin/trino-bigquery/pom.xml
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowAllocatorStats.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowBufferAllocator.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowConfig.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorFactory.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPageSourceProvider.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageArrowPageSource.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryArrowConfig.java

Bound and measure BigQuery's Arrow buffer allocations

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/tablechanges/TableChangesSplitSource.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetConnectorTest.java

The bug in `isFinished()` could cause `table_changes` return partial data.
See unit test
```markdown
* Fix incomplete results from querying `table_changes` table function. ({issue}`24709`)
```

Fix incomplete results from iceberg table_changes function

---

core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingConfig.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingSessionProperties.java
core/trino-main/src/test/java/io/trino/server/protocol/spooling/TestSpoolingConfig.java

It makes it easier to reason about which session property maps to which configuration property.
```markdown
```

Make configuration and session property names consistent

---

docs/src/main/sphinx/language/types.md

Refine documentation on accepted literal data types
- Add that consecutive underscores in numbers (e.g., `12__34`) is not permitted
- Add that binary literals allow any number of whitespace characters
#23682 

Add more details about numeric and varbinary literals

---

docs/src/main/sphinx/admin/properties-client-protocol.md

I am also updating the release notes btw.
Follow up to #24757 and #24655 and #24781

Document spooling session properties

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java

In case Iceberg commit fails for delete or truncate throw `TrinoException` with clear `ICEBERG_COMMIT_ERROR` type.
```
"org.apache.iceberg.rest.ErrorHandlers$CommitErrorHandler.accept(ErrorHandlers.java:89)",
"org.apache.iceberg.rest.ErrorHandlers$CommitErrorHandler.accept(ErrorHandlers.java:80)",
"org.apache.iceberg.rest.HTTPClient.throwFailure(HTTPClient.java:211)",
"org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:323)",
"org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:262)",
"org.apache.iceberg.rest.HTTPClient.post(HTTPClient.java:368)",
"org.apache.iceberg.rest.RESTClient.post(RESTClient.java:112)",
"org.apache.iceberg.rest.RESTTableOperations.commit(RESTTableOperations.java:159)",
"org.apache.iceberg.SnapshotProducer.lambda$commit$2(SnapshotP …
```

Improve error handling for delete and truncate in Iceberg

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/RetryingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcMetadata.java
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
plugin/trino-exasol/src/main/java/io/trino/plugin/exasol/ExasolClient.java
plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMetadata.java
plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java
plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/BaseMariaDbConnectorTest.java
plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java

Follow up of the https://github.com/trinodb/trino/pull/20914
```markdown
* Add support for the `FIRST`, `AFTER`, and `LAST` clauses to `ALTER TABLE ...
ADD COLUMN`. ({issue}`24735`)
```

Allow add column with position for JDBC-connectors

---

.github/workflows/ci.yml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/snowflake/TestIcebergSnowflakeCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/org/apache/iceberg/snowflake/TestTrinoSnowflakeCatalog.java
plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeConnectorTest.java
plugin/trino-snowflake/src/test/java/io/trino/plugin/snowflake/TestSnowflakeTypeMapping.java

Temporarily disable Snowflake tests

---

docs/src/main/sphinx/functions/comparison.md
docs/src/main/sphinx/language/types.md

Follow up to https://trinodb.slack.com/archives/CP1MUNEUX/p1705983989648189
None

Improve char type and comparison docs

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPartitioningHandle.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java

Assign channel number based on the order of field ID.
Fixes #24628
```markdown
* Fix some things. ({issue}`24628`)
```

Fix error with multiple nested partition columns on Iceberg

---

docs/release-template.md
docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-469.md

Assemble the release notes for the upcoming Trino 469 release.
See https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A469
* #24507 ✅ rn ✅ docs
* #24447 ✅ rn ✅ docs
* #24514 ✅ rn ✅ docs
* #24520 ✅ rn ✅ docs
* #24418 ✅ rn ✅ docs
* #24501 ✅ rn ✅ docs
* #24529 ✅ rn ✅ docs
* #24527 ✅ rn ✅ docs
* #24508 ✅ rn ✅ docs
* #24521 ✅ rn ✅ docs
* #24532 ✅ rn ✅ docs
* #24536 ✅ rn ✅ docs
* #24524 ✅ rn ✅ docs
* #24504 ✅ rn ✅ docs
* #24172 ✅ rn ✅ docs
* …

 Add Trino 469 release notes

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/RetryingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java

Remove deprecated method addColumn from JdbcClient

---

docs/src/main/sphinx/connector/mysql.md
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
plugin/trino-ignite/src/test/java/io/trino/plugin/ignite/TestIgniteConnectorTest.java
plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlFailureRecoveryTest.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlGlobalTransactionMyConnectorSmokeTest.java
plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

The tests that are updated in the `BaseJdbcConnectorTest` because current the implementation of MERGE for Mysql connector requires the table has primary keys, thus modified the table creation logic to use `createTestTableForWrites`, allowing the MySQL connector test class to override it and add primary keys as needed.
```markdown
* Add support for `MERGE` statement. ({issue}`issuenumber`)
```

Support MERGE for MySQL connector

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Fixes #24813
```markdown
* Fix failure when adding a new column containing a dot. ({issue}`24813`)
```

Fix failure when adding columns with dots in Iceberg

---

client/trino-cli/pom.xml
client/trino-client/pom.xml
client/trino-jdbc/pom.xml

JDK 11 was released 6 years ago. Enough time has passed for industry to pick it up. Let's move to JDK 11.
```markdown
```

Update client libraries to JDK 11 

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcWithBloomFilters.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Sometimes the new and old way were mixed in a single method. It also makes `createTestTableForWrites` reuse this method to avoid duplication.
```markdown
```

Use newTrinoTable in more places

---

plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java

Fixes setTableProperties on Faker connector. Table properties are now read, cast and set based on the predefined property type. 
Previously it tried to set java.util.Optional values from properties map directly causing type compatibility issues. Along with the fix a test case has been added to validate intended behavior.

Cast table properties based on its type in Faker connector

---

plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java

Adding unit test coverage for renameTable method in Faker connector.

Add test for renameTable in Faker connector

---

core/trino-server/src/main/provisio/trino.xml
plugin/trino-loki/README.md
plugin/trino-loki/pom.xml
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiColumnHandle.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiConnector.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiConnectorConfig.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiConnectorFactory.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiErrorCode.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiMatrixValuePairsIterator.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiMetadata.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiModule.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiPlugin.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiQueryResultIterator.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiRecordCursor.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiRecordSet.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiRecordSetProvider.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiSplit.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiSplitManager.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiStreamEntriesIterator.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiTableFunction.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiTableFunctionProvider.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiTableHandle.java
plugin/trino-loki/src/test/java/io/trino/plugin/loki/LokiQueryRunner.java
plugin/trino-loki/src/test/java/io/trino/plugin/loki/TestLokiIntegration.java
plugin/trino-loki/src/test/java/io/trino/plugin/loki/TestingLokiServer.java
pom.xml

This change introduce a [Loki](https://grafana.com/loki) connector. It supports log and metric queries.
Currently the connector uses the older `ResultSetProvider`. A `PageSourceProvider` is planned as is predicate push down.
This is a side project. There is no official support from Grafana Labs.
```
- Add Loki connector to connect with Grafana Loki (https://grafana.com/oss/loki/)
```
Co-authored-by: Janos <janos.gub@grafana.com>

Introduce Loki connector.

---

plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/TestBlackHoleSmoke.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeRegisterTableProcedureTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergRegisterTableProcedure.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogCaseInsensitiveMapping.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/procedure/TestIcebergMigrateProcedure.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Adding test coverage for setTableProperties.  As part of the unit test `getTableComment` utility is now moved down from BaseConnectorTest to AbstractTestQueryFramework class, so that TestFakerQueries can reuse it. 

Test table comment in Faker

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java

Thus, we can connect to SaaS catalogs besides Glue more easily. 

Allow setting catalog type in Iceberg query runner

---

core/trino-main/src/test/java/io/trino/operator/scalar/time/TestExtract.java
core/trino-main/src/test/java/io/trino/operator/scalar/timestamp/TestExtract.java
core/trino-main/src/test/java/io/trino/operator/scalar/timestamptz/TestExtract.java
core/trino-main/src/test/java/io/trino/operator/scalar/timetz/TestExtract.java
core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java

Make the error message for invalid `extract` more helpful.
relates to https://github.com/trinodb/trino/issues/24175

Inform user what are extractable date/time fields

---

core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutineAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/routine/SqlRoutinePlanner.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java

fixes: https://github.com/trinodb/trino/issues/24460
```markdown
* Allow non-lower case variables in user defined functions. ({issue}`issuenumber`)
```

Support non-lower case variables in functions

---

docs/src/main/sphinx/connector/postgresql.md
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTimeMappingsWithServerTimeZone.java

Since 1350a8b8aa8079911b3d3696377b1ece14c6174a we switched testing to 12
Some follow-up from https://github.com/trinodb/trino/pull/24787
```markdown
```

Update docs with updated Postgres version

---

client/trino-client/src/main/java/io/trino/client/StatementClientV1.java

Currently, `StatementClient.close()` doesn't send a cancel request after hitting the client-side timeout because `state` is changed here:
https://github.com/trinodb/trino/blob/9662e4325d5c0878614e0e885de7e667bae644dd/client/trino-client/src/main/java/io/trino/client/StatementClientV1.java#L405-L408
while `close()` sends a cancel request only when `state` is `RUNNING`:
https://github.com/trinodb/trino/blob/9662e4325d5c0878614e0e885de7e667bae644dd/client/trino-client/src/main/java/io/trino/client/StatementClientV1.java#L553-L562
Since `close()` is called before changing `state` when the thread is interrupted, it looks like applying the same way is natural solution:
https://github.com/trinodb/trino/blob/9662e4325d5c0878614e0e885de7e667bae644dd/client/trino-client/src/main/java/io/trino/client …

Close StatementClient when hitting client-side timeout

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/AwsSdkV2HttpClientStats.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemStats.java

When s3 client was changed to use AWS SDK v2 from AWS SDK v1, the set of s3 pool metrics were missed.
With this PR, these http pool metrics are now exposed via JMX beans. The reference for the http metrics exposed by AWS SDK can be found here: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/http/HttpMetric.html
#23944 

Add JMX metrics for S3 http client usage in native FS.

---

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryCaseInsensitiveMapping.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Cleanup test schema in connector tests

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/delete/EqualityDeleteFilter.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

Fixes #18625
```markdown
* Fix failure when reading tables which equality deletes updated nested fields. ({issue}`18625`)
```

Fix failure when equality delete updated nested fields in Iceberg

---

plugin/trino-duckdb/src/main/java/io/trino/plugin/duckdb/DuckDbClient.java

I don't remember why I put this table type in the initial PR. 
Let me remove this type because all tests pass without it. 

Remove 'LOCAL TEMPORARY' from DuckDbClient

---

lib/trino-filesystem-azure/pom.xml
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystemFactory.java
plugin/trino-delta-lake/pom.xml
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
pom.xml

This solves an issue with connection leaks that are happening for Azure Storage SDK
when OkHttp is used. OkHttp is not actively maintained, which makes the default,
Netty implementation, a better choice for the future as it's actively maintained
and tested.
Fixes https://github.com/trinodb/trino/issues/24116
```markdown
```

 Fix connection leakage in native Azure filesystem

---

core/trino-main/src/main/java/io/trino/metadata/DisabledSystemSecurityMetadata.java
core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
core/trino-main/src/main/java/io/trino/metadata/SystemSecurityMetadata.java
core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java
testing/trino-tests/src/test/java/io/trino/security/TestingSystemSecurityMetadata.java

Propagate function lifecycle events sucha as create function and drop function to SystemSecurityMetadata
```markdown
* Add support for functions ownership 
```

Propagate function lifecycle events to SystemSecurityMetadata

---

lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/json/JsonDeserializer.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/line/openxjson/OpenXJsonDeserializer.java

Minor code cleanup in the Hive and OpenX JSON decoders to improve performance by flattening lists into arrays, avoiding per-row allocation overheads, and avoiding a per-value instanceof check.

Improve JSON Decoders

---

docs/src/main/sphinx/connector/jdbc-case-insensitive-matching.fragment

* Added clarification for the requirement to include the `schemas` and `tables` properties in the JSON file. 
```markdown
```

Improve case insensitive matching fragment

---

docs/src/main/sphinx/admin/preview-web-interface.md

Just a lift and shift and minor update of the content from the legacy UI .. this enables us to at some stage just remove that old page and UI. Please verify that what is written is actually true and let me know if we should remove or update anything.
Basically we should keep the docs for the preview UI separate and complete. In that realm also .. what do you think if we start adding some docs about each screen .. can be very high level
#23230 

Add docs for authentication with Preview Web UI

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogNestedNamespaceConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergTrinoRestCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergVendingRestCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java

Failing stack trace
"org.apache.iceberg.rest.ErrorHandlers$OAuthErrorHandler.accept(ErrorHandlers.java:247)",
"org.apache.iceberg.rest.ErrorHandlers$OAuthErrorHandler.accept(ErrorHandlers.java:228)",
"org.apache.iceberg.rest.HTTPClient.throwFailure(HTTPClient.java:211)",
"org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:323)",
"org.apache.iceberg.rest.HTTPClient.execute(HTTPClient.java:262)",
"org.apache.iceberg.rest.HTTPClient.postForm(HTTPClient.java:409)",
"org.apache.iceberg.rest.auth.OAuth2Util.fetchToken(OAuth2Util.java:264)",
"org.apache.iceberg.rest.auth.OAuth2Util$AuthSession.fromCredential(OAuth2Util.java:693)",
"org.apache.iceberg.rest.RESTSessionCatalog.lambda$newSession$6(RESTSessionCatalog.java:1076)",
"org.apache.iceberg.rest.RESTSessionCatalog.lambda$session$1(RES …

Correctly categorize external errors in Iceberg REST catalog

---

core/trino-main/src/main/java/io/trino/server/QueryResource.java
core/trino-main/src/test/java/io/trino/server/TestQueryResource.java

Addresses #24461. Non-breaking.
Enhancing getAllQueryInfo API to accept multiple state filters. This adds flexibility for clients to request for query infos belonging to more than one state in a single request.
```markdown
```

Support multiple state filters on getAllQueryInfo API

---

docs/src/main/sphinx/udf/python.md

Fix typo in Python docs

---

plugin/trino-faker/pom.xml
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerColumnHandle.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerSplit.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/PropertyValues.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/FakerQueryRunner.java

Return statistics for faker tables

---

plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiRecordSet.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiSplit.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiSplitManager.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiTableHandle.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/QueryRangeTableFunction.java
plugin/trino-loki/src/test/java/io/trino/plugin/loki/TestLokiIntegration.java

The Loki API allows to pass the step length in seconds. This change updates the client and adds an optional `STEP` parameter to the query range table function.
This allows us to simplify the integration test as well.
Fixes #24861

Allow to pass step length in Loki connector

---

.mvn/modernizer/violations.xml
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueConverter.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveGlueMetadataListing.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestGlueConverter.java

Fix listing Glue tables when table type is null.
Fixes: https://github.com/trinodb/trino/issues/24834
```markdown
* Fix NullPointerException when listing tables on Glue. ({issue}`24834`)
```

Fix listing Glue tables with null type

---

docs/src/main/sphinx/admin/properties-exchange.md

Correct exchange.compression-codec documentation

---

docs/src/main/sphinx/admin.md
docs/src/main/sphinx/admin/logging.md
docs/src/main/sphinx/admin/openmetrics.md
docs/src/main/sphinx/connector/kafka.md
docs/src/main/sphinx/installation/deployment.md
docs/src/main/sphinx/security/ldap.md
docs/src/main/sphinx/security/oauth2.md

Related to TCB 57
Fixes https://github.com/trinodb/trino/issues/20637

Improve logging and add OpenMetrics docs

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSinkProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/IcebergOptimizeManifestsHandle.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/IcebergProcedureHandle.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/OptimizeManifestsTableProcedure.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/procedure/TestIcebergOptimizeManifestsProcedure.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java

Add a new procedure that rewrites manifest files like [rewrite_manifests](https://iceberg.apache.org/docs/latest/spark-procedures/#rewrite_manifests) in Spark. 
```sql
ALTER TABLE {table} EXECUTE optimize_manifests;
```
Fixes #14821
```markdown
* Add `optimize_manifests ` table procedure. ({issue}`14821`)
```

Add optimize_manifests table procedure to Iceberg

---

plugin/trino-exchange-hdfs/src/main/java/io/trino/plugin/exchange/hdfs/ExchangeHdfsConfig.java
plugin/trino-exchange-hdfs/src/main/java/io/trino/plugin/exchange/hdfs/HdfsExchangeModule.java
plugin/trino-exchange-hdfs/src/test/java/io/trino/plugin/exchange/hdfs/TestExchangeHdfsConfig.java

Add exchange.hdfs.skip-directory-scheme-validation to enable use Hadoop-Compatible File System with HDFS Client.
```markdown
* Add support Hadoop-Compatible File System when use HDFS as exchange type. 
```

Add support Hadoop-Compatible File System when use HDFS as exchange type

---

plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java

This fixes an issue introduced in #24590, which hasn't been released yet.

Skip varchar columns when detecting dictionaries in Faker connector

---

plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxRecordSetProvider.java
plugin/trino-jmx/src/test/java/io/trino/plugin/jmx/TestJmxSplitManager.java

When dynamic catalogs are enabled, and multiple catalogs use the same connector, querying a metric associated with the connector may return results only from the coordinator if not all catalogs have been used yet. This happens because the corresponding MBeans haven't been registered on the workers.
With this change, the query will return results from workers for catalogs that have already been used and whose MBeans have been registered, while gracefully skipping non-existent MBeans.
```markdown
* Fix querying non-existent JMX metrics. ({issue}`issuenumber`)
```

Skip non-existent MBeans in JmxRecordSetProvider

---

core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4
core/trino-main/src/test/java/io/trino/sql/query/TestInlineSession.java
core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
docs/src/main/sphinx/sql/select.md

Make WITH SESSION appear before FUNCTION

---

client/trino-cli/src/test/java/io/trino/cli/TestQueryRunner.java
client/trino-client/src/main/java/io/trino/client/ClientTypeSignatureParameter.java
client/trino-client/src/main/java/io/trino/client/JsonResponse.java
client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
client/trino-client/src/main/java/io/trino/client/TrinoJsonCodec.java
client/trino-client/src/main/java/io/trino/client/auth/external/HttpTokenPoller.java
client/trino-client/src/test/java/io/trino/client/TestQueryResults.java
client/trino-client/src/test/java/io/trino/client/TestRetry.java
client/trino-client/src/test/java/io/trino/client/TestTrinoJsonCodec.java
core/trino-main/src/test/java/io/trino/server/protocol/TestQueryDataSerialization.java
core/trino-main/src/test/java/io/trino/server/protocol/TestQueryResultsSerialization.java
testing/trino-testing/pom.xml
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestingTrinoClient.java
testing/trino-testing/src/main/java/io/trino/testing/LocalSpoolingManager.java

Having both io.trino.client.JsonCodec and io.airlift.json.JsonCodec resulted in confusing mistakes.

Rename JsonCodec used by trino client

---

docs/src/main/sphinx/connector/faker.md
docs/src/main/sphinx/sql/select.md
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerConfig.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerConnector.java

Follow up to #24585. I ran the Vale linter and it spotted usages of `will`, so I also fixed that in the config and schema/table/column property descriptions.

Document using statistics in the Faker connector

---

docs/src/main/sphinx/connector/iceberg.md
docs/src/main/sphinx/optimizer/statistics.md

Result of chat in https://github.com/trinodb/trino/pull/24874 with @nineinchnick 

Improve docs for table statistics

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-470.md

Assemble the release notes for the upcoming Trino 470 release.
See https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A470
* #24802 ✅ rn ✅ docs
* #24428 ✅ rn ✅ docs
* #23923 ✅ rn ✅ docs
* #24816 ✅ rn ✅ docs
* #24809 ✅ rn ✅ docs
* #23639 ✅ rn ✅ docs
* #24806 ✅ rn ✅ docs
* #24767 ✅ rn ✅ docs
* #24820 ✅ rn ✅ docs
* #24822 ✅ rn ✅ docs
* #24818 ✅ rn ✅ docs
* #24825 ✅ rn ✅ docs
* #24597 ✅ rn ✅ docs
* #24599 ✅ rn ✅ docs
* #23053 ✅ rn ✅ docs, …

Add Trino 470 release notes

---

docs/src/main/sphinx/release/release-470.md
docs/src/main/sphinx/sql/select.md

Minimal docs and an example ... example is not tested but should be fine. Please confirm @wendigo .. esp about the quoting for true and such
Follow up to https://github.com/trinodb/trino/pull/24889/

Add docs for WITH SESSION

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Fix iceberg testRollbackSnapshot test to use  variable

---

core/trino-main/src/main/java/io/trino/execution/DistributionSnapshot.java
core/trino-main/src/test/java/io/trino/execution/TestDistributionSnapshot.java

Percentiles were calculated incorrectly.
As a result DistributionSnapshot stored in final query info were incorrect.

Fix TDigestHistogram -> DistributionSnapshot convertion

---

docs/src/main/sphinx/connector/bigquery.md
docs/src/main/sphinx/connector/snowflake.md
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/JdkCompatibilityChecks.java
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/TestJdkCompatibilityChecks.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
plugin/trino-snowflake/pom.xml
plugin/trino-snowflake/src/main/java/io/trino/plugin/snowflake/SnowflakeClientModule.java

Same as in BigQuery we need additional JVM args in Snowflake connector since it's using Arrow unconditionally.
```markdown
```

Verify JVM configuration in Snowflake connector

---

client/trino-client/src/main/java/io/trino/client/JsonResultRows.java
client/trino-client/src/main/java/io/trino/client/OkHttpSegmentLoader.java
client/trino-client/src/main/java/io/trino/client/QueryDataDecoder.java
client/trino-client/src/main/java/io/trino/client/ResultRows.java
client/trino-client/src/main/java/io/trino/client/ResultRowsDecoder.java
client/trino-client/src/main/java/io/trino/client/spooling/InlineSegment.java
client/trino-client/src/main/java/io/trino/client/spooling/InlineSegmentIterator.java
client/trino-client/src/main/java/io/trino/client/spooling/SpooledSegment.java
client/trino-client/src/main/java/io/trino/client/spooling/SpooledSegmentIterator.java
client/trino-client/src/main/java/io/trino/client/spooling/encoding/CompressedQueryDataDecoder.java
client/trino-client/src/main/java/io/trino/client/spooling/encoding/JsonQueryDataDecoder.java
client/trino-client/src/test/java/io/trino/client/TestResultRowsDecoder.java
client/trino-client/src/test/java/io/trino/client/spooling/encoding/TestCompressedQueryDataDecoder.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestAsyncResultIterator.java

Iterable<List<Object>> was an initial sin, as the assumption was that you can iterate over data multiple times, which isn't true anymore for spooled segments, which are downloaded and acknowledged once the data is fully read.
Two new classes are introduced: SpooledSegmentIterator which is responsible for loading, acknowledging spooled segments, closing of the input stream for the spooled segment. This encapsulates this logic now in a single place and makes this logic reusable for other use cases. This iterator is lazy, the segment is loaded on the first row read.
```markdown …
```

Refactor QueryDataDecoder to return Iterator

---

core/trino-main/src/main/java/io/trino/server/protocol/Query.java

The EOF that happened during serialization means that the client disconnected while QueryResults was serialized. This is a class of error that can be retried by the client application, as the last QueryResults is cached.
```markdown
```

Allow client to retry on the EOF while writing

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/TrinoCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/TrinoNessieCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/snowflake/TrinoSnowflakeCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogConnectorSmokeTest.java

There are some method usages casting it to `BaseTable` without its class check.
Returning `BaseTable` in `TrinoCatalog.loadTable` simplifies some logic.

Return BaseTable in TrinoCatalog.loadTable

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystem.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/AbstractTestS3FileSystem.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemAwsS3.java
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorage.java
testing/trino-testing-containers/src/main/java/io/trino/testing/containers/Minio.java

Some of the S3-compatible storage solutions are not yet compatible with it (pre-2025 Minio, Vast, Dell ECS).
These changes allow to use new SDK against not-fully-compliant-S3-compatible solutions.
Release notes: increase compatibility with S3-compatible storage solutions.

Disable strong integrity checks for S3 FS 

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/delete/DeletionVectors.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/delete/TestDeletionVectors.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeCloneTableCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeDeleteCompatibility.java

This is also a prerequirements for testing MERGE behavior with deletion vectors proposed in https://github.com/trinodb/trino/pull/24756
```markdown
* Support read 'p' type deletion vectors in Delta Lake. ({issue}`issuenumber`)
```

Support read 'p' type deletion vectors in Delta Lake

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java

We observed it may happen that final task info notification may be lost. In such case query progression will be blocked.
Commit adds a stop-gap cod to mitigate this issue and unblock or fail query until we find and fix the bug.

Prevent query blocking if final query info is lost

---

client/trino-client/src/main/java/io/trino/client/CloseableIterator.java
client/trino-client/src/main/java/io/trino/client/JsonIterators.java
client/trino-client/src/main/java/io/trino/client/JsonResultRows.java
client/trino-client/src/main/java/io/trino/client/QueryDataDecoder.java
client/trino-client/src/main/java/io/trino/client/ResultRows.java
client/trino-client/src/main/java/io/trino/client/ResultRowsDecoder.java
client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
client/trino-client/src/main/java/io/trino/client/spooling/InlineSegment.java
client/trino-client/src/main/java/io/trino/client/spooling/InlineSegmentIterator.java
client/trino-client/src/main/java/io/trino/client/spooling/SegmentsIterator.java
client/trino-client/src/main/java/io/trino/client/spooling/SpooledSegment.java
client/trino-client/src/main/java/io/trino/client/spooling/SpooledSegmentIterator.java
client/trino-client/src/main/java/io/trino/client/spooling/encoding/CompressedQueryDataDecoder.java
client/trino-client/src/main/java/io/trino/client/spooling/encoding/JsonQueryDataDecoder.java
client/trino-client/src/test/java/io/trino/client/TestResultRowsDecoder.java
client/trino-client/src/test/java/io/trino/client/spooling/encoding/TestCompressedQueryDataDecoder.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestAsyncResultIterator.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/encoding/JsonQueryDataEncoder.java

This PR streamlines the release of resources related to the spooling segments and is a preparation for the introduction of the preliminary Arrow encoding support.
Just an internal refactor being a preparation for something else ;)
```markdown
```

Make data iterators closeable

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

Remove redundant format version change in TestIcebergV2

---

docs/src/main/sphinx/client/client-protocol.md

Clarification in Trino documentation to promote a solution to the issue discussed here -
https://trinodb.slack.com/archives/CP1MUNEUX/p1738607909072639?thread_ts=1738607909.072639&cid=CP1MUNEUX
```markdown
```

Clarify Trino behavior when client does not fetch results in Client Potocol

---

.mvn/modernizer/violations.xml
core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedConnectorAccessControlTest.java
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/BaseFileBasedSystemAccessControlTest.java
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedAccessControl.java
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestHttpFileBasedAccessControl.java
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestHttpFileBasedSystemAccessControl.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/RestCatalogTestUtils.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergPolarisCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogCaseInsensitiveMapping.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogNestedNamespaceConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergTrinoRestCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergUnityRestCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java

`@TempDir` should be used where possible, and `Files` from the JDK otherwise.
There are plenty of other places where `@TempDir` could be used - left as a follow-up.
```markdown
```

Prohibit use of `Files` util class from AssertJ to create temporary directories

---

core/trino-web-ui/src/main/resources/webapp-preview/src/App.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/Dashboard.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/DemoComponents.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryHistory.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/WorkerStatus.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/WorkersList.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/constant.ts
core/trino-web-ui/src/main/resources/webapp/src/components/ClusterHUD.jsx

- Use sentence case consistently
- Use SI units
To follow material UI guidelines and style we use for docs and website.

Improve labels in preview UI

---

.github/workflows/ci.yml

Minimize the execution time for the catch-all `test-other-modules` CI job by periodically looking at the longest running modules and splitting them out to other jobs.

Split out more modules from test-other-modules CI job

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java

```hive.s3.storage-class-filter``` is still being used to filter out glacier objects when listing s3 objects. Remove the annotation to correct it
```markdown
```

Remove the Deprecated marker for S3StorageClassFilter

---

core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedStageExecution.java

Adds additional context to unexpected condition error messages in `PipelinedStageExecution`

Improve PipelinedStageExecution failure message

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystem.java

Fix an issue that causes the restoreStatus always be empty for glacier objects.
If setting READ_NON_GLACIER_AND_RESTORED as the filter, restored glacier objects will be ignored without this changing causing wrong incorrect results.
( X) Release notes are required. Please propose a release note for me.
```markdown
* Fixes an issue where restored S3 glacier objects should have been considered readable when the configuration property hive.s3.storage-class-filter is set to  READ_NON_GLACIER_AND_RESTORED, but were being skipped instead ({issue}`24947`)
```

Fix an issue that causes the restoreStatus in listing response always be empty for glacier objects

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestFileBasedConflictDetection.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergLocalConcurrentWrites.java

Currently, Iceberg's concurrent write conflict detection is based on predicates received from the engine. In more complicated cases (like joins, merges, or different type comparisons), this information is not available at the connector level.
This PR aims to take partition information from the actual written files as a source for the conflict detection system. If, during a write, created files are only for some partitions, we can check only those partitions for potential conflicts from concurrent writes.
```markdown
* Improve conflict detection to avoid failures from …
```

Add information from written files to Iceberg conflict detection

---

docs/src/main/sphinx/security/file-system-access-control.md

Also, clarify that table procedures are separate entities from regular (catalog) procedures and give example syntax to make it clear which is which.
```markdown
```

Clarify that table procedures are not supported by FBAC

---

docs/src/main/sphinx/connector/phoenix.md
plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestingPhoenixServer.java

Use various HBase Connection Registries with Phoenix JDBC url formats. Document with recommendations and use in test.
```markdown
```

HBase Connection Registry usage with Phoenix JDBC url

---

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java

The connector threw "Duplicate key {schema}.{table} (attempted merging values TABLE and TABLE)" error when tables exist with different cases like test and TEST. 
```
io.trino.testing.QueryFailedException: Error listing tables for catalog mongodb: Duplicate key test_db_fymzuxlc22.test_collection_a2p6hs64ml (attempted merging values TABLE and TABLE)
at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:138)
at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:565)
at io.trino.testing.DistributedQueryRunner.execute(DistributedQueryRunner.java:548)
at io.trino.sql.query.QueryAssertions$QueryAssert.lambda$new$1(QueryAssertions.java:317)
at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:200) …
```

Fix duplicate key due to non-lowercase collections in MongoDB

---

plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoIndex.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java

Convert MongoIndex to record

---

plugin/trino-loki/pom.xml
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiSplitManager.java

The log is redundant because the split size is always 1. 

Remove unhelpful log from LokiSplitManager

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java

The same initialization exists a few lines below. 

Remove redundant initialization from Delta test

---

core/trino-main/src/main/java/io/trino/connector/DefaultCatalogFactory.java
core/trino-main/src/main/java/io/trino/connector/system/SystemConnector.java
core/trino-main/src/main/java/io/trino/connector/system/SystemPageSourceProvider.java
core/trino-spi/src/main/java/io/trino/spi/connector/SystemTable.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeSystemTable.java

This is an initial proposal to add an option to do access control checks during system table reads.
The goal here is to open this for discussion with some concrete option on a table.
This is related to an effort to add an iceberg system table that lists only iceberg tables (https://github.com/trinodb/trino/pull/24469).
A system table like that has to filter the table list using the `AccessControl#filterTables` method but up until now, `AccessControl` was not available for system tables.
```markdown
```

Allow system tables to do system level access control

---

docs/src/main/sphinx/object-storage/file-system-s3.md
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3Context.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemConfig.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3OutputStream.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemConfig.java

This PR enhances Trino's compatibility with S3 storage classes and adds support for configuring the storage class of objects written to S3.  By introducing the s3.storage-class property, users can now specify how objects should be stored, enabling better control over storage costs and retrieval performance.
Closes issue #24698 
```markdown
* Add support for configuring s3.storage-class when writing objects to S3. ({issue}24698)
* Add support for configuring s3.storage-class when writing objects to S3. ({issue}24698)
```

S3 storage classes config support

---

plugin/trino-ranger/src/main/java/io/trino/plugin/ranger/RangerSystemAccessControl.java

This fix addresses the issue reported in #24887. 
Currently Ranger plugin configuration is intilizated with default configurations, followed by loading configurations from files specified in `access-control.properties`. Few configurations used by Ranger plugin are not overrideable after initialization, hence the configurations in files specified in `access-control.proerties` are not effective.
To address this issue, Apache Ranger 2.6.0 enhanced plugin initialization to load configurations from list of files specified in the constructor.  
```markdown …
```

Fix Ranger plugin initialization

---

core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java

Split distribution time can be a bottleneck in some scenarios. Having it in the explain makes it easier to diagnose without accessing query json. Split count is helpful to analyze query performance when there is either a big number of small splits or there is just one split like with basic jdbc connectors. Split count is visible also in the "Input rows distribution" metric but it is only available in the VERBOSE mode.
Sample output:
query
```
trino:tpch_sf10_snappy_parquet> EXPLAIN ANALYZE SELECT o.orderkey, c.name
-> FROM customer c
->  JOIN orders o ON o.custkey = c.custkey
-> WHERE c.nationkey  = 0;
```
After (has `Total split distribution time` added to the source stages and  and `Splits` added to the table scans)
```
Query Plan …
```

Print splits count and distribution time in EXPLAIN ANALYZE

---

lib/trino-filesystem-manager/src/main/java/io/trino/filesystem/manager/FileSystemConfig.java
lib/trino-filesystem-manager/src/main/java/io/trino/filesystem/manager/FileSystemModule.java
lib/trino-filesystem-manager/src/test/java/io/trino/filesystem/manager/TestFileSystemConfig.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalFileSystem.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalFileSystemConfig.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/local/LocalFileSystemFactory.java
lib/trino-filesystem/src/test/java/io/trino/filesystem/local/TestLocalFileSystemConfig.java

Docs in https://github.com/trinodb/trino/pull/25001
```markdown
* Add support for local filesystem ({issue}`issuenumber`)
```

Expose local filesystem

---

docs/src/main/sphinx/admin/properties-optimizer.md
docs/src/main/sphinx/sql/reset-session.md
docs/src/main/sphinx/sql/set-session.md

Remove doc refereces to optimize-hash-generation

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryProxyConfig.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryProxyConfig.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/v1/GlueHiveMetastoreConfig.java
plugin/trino-kafka/pom.xml
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaSecurityConfig.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/security/KafkaSslConfig.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaSecurityConfig.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaSslConfig.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotConfig.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotGrpcServerQueryClientTlsConfig.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotConfig.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotGrpcServerQueryClientTlsConfig.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusConnectorConfig.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusConnectorConfig.java

Do not use PostConstruct for config validation

---

core/trino-main/src/main/java/io/trino/operator/MergeOperator.java
core/trino-main/src/main/java/io/trino/operator/OrderByOperator.java
core/trino-main/src/main/java/io/trino/operator/SimplePageWithPositionComparator.java
core/trino-main/src/main/java/io/trino/operator/SimplePageWithPositionEqualsAndHash.java
core/trino-main/src/main/java/io/trino/operator/TopNOperator.java
core/trino-main/src/main/java/io/trino/operator/TopNProcessor.java
core/trino-main/src/main/java/io/trino/operator/TopNRankingOperator.java
core/trino-main/src/main/java/io/trino/operator/WindowOperator.java
core/trino-main/src/main/java/io/trino/operator/exchange/LocalMergeSourceOperator.java
core/trino-main/src/main/java/io/trino/sql/gen/OrderingCompiler.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
core/trino-main/src/test/java/io/trino/operator/BenchmarkGroupedTopNRankBuilder.java
core/trino-main/src/test/java/io/trino/operator/BenchmarkGroupedTopNRowNumberBuilder.java
core/trino-main/src/test/java/io/trino/operator/BenchmarkTopNOperator.java
core/trino-main/src/test/java/io/trino/operator/TestGroupedTopNRankBuilder.java
core/trino-main/src/test/java/io/trino/operator/TestGroupedTopNRowNumberBuilder.java
core/trino-main/src/test/java/io/trino/operator/TestTopNOperator.java
core/trino-main/src/test/java/io/trino/operator/TestTopNRankingOperator.java
core/trino-main/src/test/java/io/trino/util/TestMergeSortedPages.java

Improves performance of `TopNOperator` and `TopNRankingOperator` by switching them to use code generated comparators instead of `SimplePageWithPositionComparator`. Also performs small flattening improvements and adds validation checks to `OrderingCompiler` logic.
[BenchmarkTopNOperator results](https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/pettyjamesm/5fca924fd2ea456d633b5b9d3322ecb1/raw/626e2085dd1ece17f7a32923a40ea7f4a8a12507/benchmarktopnoperator_baseline.json,https://gist.githubusercontent.com/pettyjamesm/5fca924fd2ea456d633b5b9d3322ecb1/raw/626e2085dd1ece17f7a32923a40ea7f4a8a12507/benchmarktopnoperator_improved.json) show a 10-40% improvement
( ) Release notes are required. Please …

Improve TopN Performance

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java

Fixes https://github.com/trinodb/trino/issues/19461
Increase waiting time before vacuum procedure test
Vacuum procedure is relying on last modification time for files. Some storages, like ABFS report time with resolution of seconds.
In tests we wait at least 1001 ms, which in some cases may be not enough due to time truncate made by ABFS.

Increase waiting time before vacuum procedure test

---

.github/workflows/ci.yml
plugin/trino-bigquery/pom.xml
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryParentProjectId.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryWithBothProjectIdsSet.java

Increase coverage around parent project ID config property in BigQuery connector.
Test based on https://github.com/trinodb/trino/pull/23041
```markdown
```

Add parent project ID test to BigQuery

---

lib/trino-filesystem/src/main/java/io/trino/filesystem/Location.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/Locations.java
lib/trino-filesystem/src/test/java/io/trino/filesystem/TestLocations.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/TrinoCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/jdbc/TrinoJdbcCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/nessie/TrinoNessieCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/SigV4AwsProperties.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/snowflake/TrinoSnowflakeCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestTrinoHiveCatalogWithHiveMetastore.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergS3TablesConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/org/apache/iceberg/snowflake/TestTrinoSnowflakeCatalog.java

`Location` class requires a small change because it doesn't allow S3 Tables path, e.g. `s3://{random}--table-s3'`. 
Fixes #24916
cc: @jamesbornholt
```markdown
```

Support write operations for S3 Tables in Iceberg

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeGlueMetastore.java

https://github.com/trinodb/trino/actions/runs/13380158557/job/37367214390
```
Error:    TestDeltaLakeGlueMetastore.setUp:137 » Creation Unable to create injector, see the following errors:
1) [Guice/JitDisabled]: Explicit bindings are required and Boolean annotated with @UsingSystemSecurity() is not explicitly bound.
at DeltaLakeMetadataFactory.<init>(Unknown Source)
\_ for 13th parameter useSystemSecurity
at java.base/DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
```

Fix setup failure in TestDeltaLakeGlueMetastore

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestTrinoHiveCatalogWithHiveMetastore.java

Use S3FileSystemFactory in TestTrinoHiveCatalogWithHiveMetastore

---

docs/src/main/sphinx/udf/python.md
plugin/trino-functions-python/pom.xml
plugin/trino-functions-python/src/main/java/io/trino/plugin/functions/python/PythonEngine.java
pom.xml

Update python WASM + chicory + AWS SDK v2

---

core/trino-main/src/main/java/io/trino/connector/CatalogConnector.java
core/trino-main/src/main/java/io/trino/connector/DefaultCatalogFactory.java
core/trino-main/src/main/java/io/trino/memory/MemoryPool.java
core/trino-main/src/main/java/io/trino/testing/PlanTester.java
core/trino-main/src/test/java/io/trino/execution/TestSqlTaskManagerRaceWithCatalogPrune.java
core/trino-main/src/test/java/io/trino/memory/TestMemoryPools.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/connector/Connector.java

This functionality is not used by any connector in Trino, nor is it tested. This functionality should be replaced with a memory reservation API that is passed into the connector. We could then have the memory connector declare its used memory, the Hive connector could report memory used for caches, etc.
```markdown
* Remove `Connector.getInitialMemoryRequirement()`. ({issue}`25055`)
```

Remove Connector.getInitialMemoryRequirement()

---

plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java

Drop keyspaces in Cassandra tests in try-finally

---

docs/src/main/sphinx/object-storage.md
docs/src/main/sphinx/object-storage/file-system-local.md

This is based on discussions with @electrum but from what I can tell this does not yet exist in the code... looking for pointers.
Update: Code is all implemented now and PR is merged.
Related code in https://github.com/trinodb/trino/pull/25006

Add docs for local file system support

---

client/trino-cli/src/main/java/io/trino/cli/Query.java
client/trino-cli/src/test/java/io/trino/cli/TestQueryRunner.java
client/trino-client/src/main/java/io/trino/client/QueryResults.java
client/trino-client/src/main/java/io/trino/client/QueryStatusInfo.java
client/trino-client/src/test/java/io/trino/client/TestClientRedirect.java
client/trino-client/src/test/java/io/trino/client/TestResultRowsDecoder.java
client/trino-client/src/test/java/io/trino/client/TestRetry.java
client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoStatement.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestAsyncResultIterator.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestProgressMonitor.java
core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
core/trino-main/src/main/java/io/trino/server/protocol/JsonBytesQueryDataProducer.java
core/trino-main/src/main/java/io/trino/server/protocol/Query.java
core/trino-main/src/main/java/io/trino/server/protocol/QueryResultRows.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpooledQueryDataProducer.java
core/trino-main/src/test/java/io/trino/server/protocol/TestQueryDataSerialization.java
core/trino-main/src/test/java/io/trino/server/protocol/TestQueryResultsSerialization.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestingTrinoClient.java

QueryResults cleanup

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java

Close https://github.com/trinodb/trino/issues/25011
```markdown
* Fix query failures when writing to delta tables. ({issue}`25011`)
```

Support write large checkpoint in Delta Lake

---

plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraRecordCursor.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSplit.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSplitManager.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTokenSplitManager.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraTypeManager.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/ptf/Query.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraSplit.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraSplitManager.java

Minor cleanup in Cassandra

---

core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedQueryScheduler.java
core/trino-main/src/main/java/io/trino/operator/exchange/LocalExchange.java
core/trino-main/src/main/java/io/trino/operator/output/SkewedPartitionRebalancer.java
core/trino-main/src/main/java/io/trino/sql/planner/NodePartitioningManager.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
testing/trino-faulttolerant-tests/src/test/java/io/trino/faulttolerant/iceberg/TestIcebergParquetFaultTolerantExecutionConnectorTest.java

Previously optional partition count was passed to NodePartitioningManager. When partition count was unspecified, then maxHashPartitionCount was used. However, maxHashPartitionCount should only apply to intermediate stages, rather than insert stages. Insert stages are controlled via maxWriterTaskCount.
```markdown
* Make engine honor `task.max-writer-count` for Iceberg partitioned writes. ({issue}`issuenumber`)
```

Propagate correct partition count for insert stages

---

docs/src/main/sphinx/admin/properties-logging.md

Follow up to #25081 , would be good to get this merged for the same 471 release

Add docs for log.console-format

---

docs/release-template.md
docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-471.md

Assemble the release notes for the upcoming Trino 471 release.
See https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A471
Requires merge of https://github.com/trinodb/trino.io/pull/773 after the release to adjust the website for the missing RPM.
* #24917 ✅ rn ✅ docs
* #24921 ✅ rn ✅ docs
* #24923 ✅ rn ✅ docs
* #24924 ✅ rn ✅ docs
* #24915 ✅ rn ✅ docs
* #24927 ✅ rn ✅ docs
* #22403 ✅ rn ✅ docs
* #24815 ✅ rn ✅ docs
* #24933 ✅ rn ✅ docs
* …

Add Trino 471 release notes

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowBufferAllocator.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowConfig.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryArrowToPageConverter.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStorageArrowPageSource.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryArrowConfig.java

…g off heap memory staling
In BigQuery connector, allocate and release off heap memory every getNextPage call to be more multi catalog friendly. 
```markdown
```

Limit BigQuery off heap memory to split context

---

docs/src/main/sphinx/connector/bigquery.md
docs/src/main/sphinx/connector/elasticsearch.md
docs/src/main/sphinx/connector/opensearch.md

https://cloud.google.com/bigquery/docs/querying-wildcard-tables
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multiple-indices.html
https://opensearch.org/docs/latest/api-reference/multi-search/#metadata-only-options
```markdown
```

Document wildcard tables query support

---

core/trino-main/pom.xml
core/trino-main/src/main/java/io/trino/execution/SessionPropertyEvaluator.java
core/trino-main/src/main/java/io/trino/metadata/SessionPropertyManager.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestEngineOnlyQueries.java

Requires a small new dependency that does levenstein distance on strings. This dependency is already used in Airlift's bootstrap so net dependency addition is zero.
We already have the same mechanism for configuration properties.
```markdown
* Suggest valid session property names ({issue}`issuenumber`)
```

Suggest valid session property names

---

core/docker/Dockerfile

This is required by both Snappy native compression and Duckdb connector.
Fixes https://github.com/trinodb/trino/issues/25126
```markdown
```

Add libstdc++ to the docker image

---

plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/BaseOpenSearchConnectorTest.java

This contribution documents in the code that the `trino-elasticsearch` connector supports
querying wildcard tables through the `trino-elasticsearch` connector.
```
SELECT * from elasticsearch."default"."heartbeat-*"
```
Test was inspired from https://github.com/trinodb/trino/pull/12428 `trino-bigquery` effort.
Querying wildcard tables is a feature supported by ES to allow searching multiple indexes at the same time (a common pattern where people shard their data sets across indexes for retention, etc): https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multiple-indices.html …

Showcase support for reading wildcard tables in Elasticsearch & OpenSearch

---

docs/src/main/sphinx/connector/loki.md
plugin/trino-loki/pom.xml
plugin/trino-loki/src/test/java/io/trino/plugin/loki/TestingLokiServer.java

Loki 3.2.0 introduced a breaking change. Using log queries in instant queries was not allowed anymore. This broke the code checking for the expected result type. It was fixed in the loki-client-java library.
Closes #25156
```markdown
* Fix failure when connecting to Loki server version > 3.2.0. ({issue}`25156`)
```

Bump loki-client-java to 0.0.4

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java

When multiple queries are modifying the same Delta Table concurrently, conflicting Transaction Log updates are detected and automatically retried transparently to the end user.  However, if the concurrency is relatively high, the maximum number of reties (currently 5) can be easily reached, and the query will fail with a `TransactionConflictException`.
After discussing this with @findinpath, I would like to increase the maximum number of retries from 5 to 200: [the same threshold used in Spark](https://github.com/delta-io/delta/blob/1a0c9a8f4232d4603ba95823543f1be8a96c1447/kernel/kernel-api/src/main/java/io/delta/kernel/internal/TransactionBuilderImpl.java#L60-L65).
[This](https://trinodb.slack.com/archives/C03E2DYAS0J/p1739272301911389) is the link to the Slack discussion.
( ) This is …

Increase DeltaLake transaction conflict retries from 5 to 200

---

docs/src/main/sphinx/connector/faker.md
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerMetadata.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerPageSource.java
plugin/trino-faker/src/test/java/io/trino/plugin/faker/TestFakerQueries.java

Arrays, maps, and JSON are common data types, so instead of throwing
exceptions when reading from tables with columns of these types, return
empty arrays, maps, and JSON objects.
Rows can be fully supported, by using existing generators.
When running CTAS queries, exclude more types when trying to generate
random values for dictionary columns to avoid failures.
All these changes simplify copying existing schemas, without the need for excluding columns. For example, instead of running this query:
```sql
create table faker.default.unique_pulls as
select * from table(exclude_columns(input => table(trinocicd.v2.unique_pulls), columns => descriptor(label_ids, label_names, requested_reviewer_ids, requested_reviewer_logins)));
```
It's now possible to just run:
```sql
create table …
```

Allow querying Faker tables with some unsupported data types

---

core/trino-main/src/main/java/io/trino/operator/VariableWidthData.java

Previously, `VariableWidthData` would underestimate the retained size by using `ArrayList#size()` instead of the underlying array capacity.

Fix VariableWidthData#getRetainedSize() estimate

---

docs/src/main/sphinx/connector/bigquery.md

Add a section on project ID resolution.
```markdown
```

Update BigQuery connector documentation

---

client/trino-client/src/main/java/io/trino/client/JsonResponse.java
client/trino-client/src/main/java/io/trino/client/MaterializingInputStream.java
client/trino-client/src/main/java/io/trino/client/TrinoJsonCodec.java
client/trino-client/src/test/java/io/trino/client/TestMaterializingInputStream.java
core/trino-main/src/main/java/io/trino/server/protocol/spooling/SpoolingQueryDataProducer.java

Improve materializing input stream in the client

---

plugin/trino-tpch/src/main/resources/tpch/statistics/sf3000.0/customer.json
plugin/trino-tpch/src/main/resources/tpch/statistics/sf3000.0/lineitem.json
plugin/trino-tpch/src/main/resources/tpch/statistics/sf3000.0/nation.json
plugin/trino-tpch/src/main/resources/tpch/statistics/sf3000.0/orders.json
plugin/trino-tpch/src/main/resources/tpch/statistics/sf3000.0/part.json
plugin/trino-tpch/src/main/resources/tpch/statistics/sf3000.0/partsupp.json
plugin/trino-tpch/src/main/resources/tpch/statistics/sf3000.0/region.json
plugin/trino-tpch/src/main/resources/tpch/statistics/sf3000.0/supplier.json

After commit 78a3f46c8ae38f60b33e8d5753ef60b17cb9d62f, the TPCH plugin uses not a custom `ObjectMapper`, but the one created by Airlift's `ObjectMapperProvider`, which is more strict than the one with default settings, and these files become invalid because float values are not  compatible with the expected `long` Java type.
```markdown
```

Fix resource files for TPCH stats

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriterManager.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointEntryIterator.java

According to the Delta Protocol specification
https://github.com/delta-io/delta/blob/master/PROTOCOL.md#checkpoints-1, "checkpoints must not preserve commit provenance information nor change data actions"
Remove the `COMMIT` entry type from `CheckpointEntryIterator` to respect the specification
https://github.com/delta-io/delta/blob/master/PROTOCOL.md#checkpoints-1
https://github.com/delta-io/delta/blob/master/PROTOCOL.md#v2-spec
```markdown
```

Remove `COMMIT` entry type from checkpoint reader

---

core/trino-main/src/main/java/io/trino/testing/TestingMetadata.java
core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java

```markdown
* Remove deprecated `ConnectorMetadata.addColumn(ConnectorSession session, ConnectorTableHandle tableHandle, ColumnMetadata column)` method.
Use `ConnectorMetadata.addColumn(ConnectorSession session, ConnectorTableHandle tableHandle, ColumnMetadata column, ColumnPosition position)` instead. ({issue}`25163`)
```

Remove deprecated ConnectorMetadata.addColumn

---

lib/trino-parquet/src/main/java/io/trino/parquet/metadata/BlockMetadata.java
lib/trino-parquet/src/main/java/io/trino/parquet/metadata/ParquetMetadata.java
lib/trino-parquet/src/main/java/io/trino/parquet/predicate/PredicateUtils.java
lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java

Fix https://github.com/trinodb/trino/issues/25151
I found the logic for pruning in [2ef6dc1c94](https://github.com/trinodb/trino/commit/2ef6dc1c9484b6726a44e15fdaeb36853e2bcd35#diff-705548e3717786bbc076aba181f1eca081ec69200050c18100bfa959e05095df) has correctness issue which caused the problems raised in
#25151
The reason is when rowGroup is skipped, the fileRowCount in `PredicateUtils` can not be updated correctly,
this pr add the `fileRowCountOffset` into `BlockMetadata` to correctly hold this semantic of data.
```markdown
* Fix incorrect results for reads on iceberg …
```

Correct parquet row group pruning logic

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TableSnapshot.java

According to Deltalake spec: https://github.com/delta-io/delta/blob/master/PROTOCOL.md#v2-spec
Sidecar entries from V2 checkpoint have sidecar file entries like
```
{"sidecar":{"path":"3a0d65cd-4056-49b8-937b-95f9e3ee90e5.parquet","sizeInBytes":2341330,"modificationTime":1512909768000,"tags":{}}
{"sidecar":{"path":"016ae953-37a9-438e-8683-9a9a4a79a395.parquet","sizeInBytes":8468120,"modificationTime":1512909848000,"tags":{}}
```
The sidecar file is the actual parquet file that contains the add entries, and need to be read through parquet reader.
Without this fix, the checkpoint file size will be passed in instead of sidecar size. Causing parquet reader always think the file going to be read is small (because checkpoint file itself will be small) and always use …

Fixed a bug that wrong sidecar size passed into reader

---

core/trino-main/src/main/java/io/trino/operator/scalar/ArrayVectorFunctions.java
core/trino-main/src/test/java/io/trino/block/AbstractTestBlock.java
core/trino-main/src/test/java/io/trino/operator/scalar/TestArrayVectorFunctions.java
core/trino-spi/src/main/java/io/trino/spi/block/ArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/Block.java
core/trino-spi/src/main/java/io/trino/spi/block/ByteArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/Fixed12Block.java
core/trino-spi/src/main/java/io/trino/spi/block/Int128ArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/IntArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/LazyBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/LongArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/MapBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/RowBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/RunLengthEncodedBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/ShortArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlock.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlVectorType.java

Previously nulls were ignored producing in an arbitrary result.
To make the implementation easier and more performant I added a hasNull method to block.
```markdown
* Fix null handling in cosine_distance and cosine_similarity to return null when array contains null. ({issue}`issuenumber`)
```

Fix null handling in cosine_distance and cosine_similarity

---

client/trino-jdbc/pom.xml
client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcConnection.java

Information from X-Trino-Set-Role should be stored even after setting or resetting authorized user.
This is also aligned with the order of operations in trino-cli
```markdown
* Fix roles being cleared after resetting authorization
```

Set setRoles after roles are reset in trino-jdbc

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/functions/IcebergFunctionProvider.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/functions/TestBucketFunctions.java

The supported types for the 1st argument: tinyint, smallint, int, bigint, varchar, varbinary, date, timestamp, timestap tz:
```sql
system.bucket(value, integer) -> integer
```
Add a function to expose the iceberg bucket transform via SQL. This can be used to help determine what bucket a value would be placed in. This could be used with the `optimize` procedure to only optimize specific buckets once we support a pushdown of this function.
Spark has a similar UDF - https://iceberg.apache.org/javadoc/1.5.1/org/apache/iceberg/spark/functions/BucketFunction.html
```markdown
* Add `system.bucket` function. ({issue}`25175`)
```

Add `system.bucket` function to Iceberg

---

core/trino-spi/src/main/java/io/trino/spi/PageBuilder.java
core/trino-spi/src/main/java/io/trino/spi/block/ArrayBlockBuilder.java
core/trino-spi/src/main/java/io/trino/spi/block/MapBlockBuilder.java
core/trino-spi/src/main/java/io/trino/spi/block/RowBlockBuilder.java

Fix BlockBuilder resetTo() method for complex types. Previously this method would not work if the complex type was only partially constructed (e.g. an exception was thrown while constructing the ARRAY, MAP, or ROW).
Also addresses [#23160](https://github.com/trinodb/trino/issues/23160)

Fix BlockBuilder resetTo() method for complex types

---

plugin/trino-ai-functions/src/main/java/io/trino/plugin/ai/functions/AnthropicClient.java
plugin/trino-ai-functions/src/main/java/io/trino/plugin/ai/functions/OpenAiClient.java
plugin/trino-ai-functions/src/test/java/io/trino/plugin/ai/functions/AiQueryRunner.java

Now I get a messages like
```
Request from AI provider at http://localhost:11434/v1/chat/completions for model llama3.2 failed
```
if I forgot to start ollama locally .. helped me with my testing and figuring out how it works. 
Lesson learned .. make sure you download the model first before you invoke it via Trino .. some of them are BIG and SLOW on a local laptop
Maybe we should even improve more .. up to you @electrum 
Also happy to refactor to use format or whatever

Improve AI function error messages

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/AbstractDeltaLakePageSink.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeWriter.java

Fix that the `validationCpuNanos` already hold by the `FileWriter` but not pass to the `PageSink` in Delta Lake.
```markdown
```

Add validation cpu time calculation in AbstractDeltaLakePageSink

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsStorage.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeGcsConnectorSmokeTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMinioAndHmsConnectorSmokeTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedHiveMetastoreWithViews.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaS3AndGlueMetastoreTest.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveQueryRunner.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveCustomCatalogConnectorSmokeTest.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveS3AndGlueMetastoreTest.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/TestHiveMetastoreCatalogs.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/S3HiveQueryRunner.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestS3FileSystemAccessOperations.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/HudiQueryRunner.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergAbfsConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergGcsConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMinioOrcConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetWithBloomFiltersMixedCase.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergReadVersionedTableByTemporal.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestSharedHiveThriftMetastore.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergS3AndGlueMetastoreTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergS3TablesConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergVendingRestCatalogConnectorSmokeTest.java

Hadoop is disabled by default now.

Remove redundant default Hadoop FS config

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushTopNThroughProject.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushTopNThroughProject.java

Before this change, TopN was not pushed through project if TableScanNode or FilterNode(TableScanNode) was the immediate source of the project. The purpose of this limitation was to enable composing scan+project or scan+filter+project into a single operator. However, this was not the optimal choice, and additionally it blocked TopN pushdown into TableScanNode.
```markdown
* Improve performance of certain queries involving topN over a projection. ({issue}`#25138`)
```
Fixes https://github.com/trinodb/trino/pull/25193

Push TopN through non-identity projection unconditionally

---

docs/src/main/sphinx/connector/duckdb.md

fyi  @StephenOTT .. any insight from your testing?
* #23419 
* #25143 

Improve DuckDB connector docs

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-472.md

Assemble the release notes for the upcoming Trino 472 release.
See https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A472
* #25037 ✅ rn ✅ docs
* #25079 ✅ rn ✅ docs
* #25089 ✅ rn ✅ docs
* #25090 ✅ rn ✅ docs
* #24984 ✅ rn ✅ docs
* #25092 ✅ rn ✅ docs
* #25095 ✅ rn ✅ docs
* #25087 ✅ rn ✅ docs
* #25099 ✅ rn ✅ docs
* #25104 ✅ rn ✅ docs
* #25084 ✅ rn ✅ docs
* #25112 ✅ rn ✅ docs
* #25108 ✅ rn ✅ docs
no PRs merged
* #25118 ✅ rn ✅ docs
* #25115 …

Add Trino 472 release notes

---

core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java

The table column reference was registered incorrectly with the original case taken from the view definition. It then failed to match the column schema returned from `SystemAccessControl` and the mask was not applied.
Instead of sprinkling `toLowerCase()` here and there, we will associate the original `Field` with the column mask and use `Field#canResove` to do the matching. The problem with this is that there's no way to do efficient lookups by name in a case-insensitive way, so we have to iterate the list of `Field`-`Expression` pairs to find a match.
Fixes #24054.
I wonder how many more issues like that will we find...
(x) Release notes …

Fix case-sensitivity issue with views and column masks

---

docs/src/main/sphinx/connector/hudi.md
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiConfig.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiSessionProperties.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiSplitSource.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/query/HudiReadOptimizedDirectoryLister.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/split/HudiBackgroundSplitLoader.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/table/HudiTableFileSystemView.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiConfig.java

- Fix HUDI connector gets stuck when an exception occurs
- Solve HUDI connector stuck by using ExceptionCallback to ensure the asyncQueue is closed when an exception occurs.
- Optimize the handling of multiple Futures with Futures.whenAllComplete instead of for_loop.
- Add a new HUDI session property: `ignore_absent_partitions`
- Boolean property.
- When set to false, the Trino HUDI connector will report an error if the partition does not exist; when set to true, non-existing partitions will be ignored.
- #19506
```markdown
* Fix: Trino Hudi connector gets stuck while …
```

Fix hudi connector gets stuck #19506

---

core/trino-server/src/main/provisio/trino.xml
docs/src/main/sphinx/installation/plugins.md

To be consistent with all the other plugins. Best to do now while we expose how to install and remove plugins. Came up in other PR in discussion with @wendigo 
In my opinion the folder name is an implementation detail and it does not need to be exposed in the release notes as such. The doc update is sufficient.

Rename plugin folder for Ranger in binaries

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java

Limit default `bigquery.metadata.parallelism` value to 32

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java

Add debug logging to BigQuery getTable api failure

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PropertiesTable.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java

Added more properties to Iceberg $properties result for #24812
Fixes #24812
```
TABLE "test_iceberg$properties";
key               |                                               value                                           
---------------------------------+-----------------------------------------------------------------------------------------------
format                          | iceberg/PARQUET                                                                               
current-snapshot-id             | 47266285455662362                                                                             
location                        | s3://bucket/path/
format-version                  | 2 …
```

Add more properties to Iceberg $properties result

---

docs/src/main/sphinx/connector/vertica.md
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestVerticaConnectorSmokeTest.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestVerticaLatestConnectorSmokeTest.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestVerticaTableStatistics.java
plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestingVerticaServer.java

https://www.microfocus.com/productlifecycle/?term=Vertica
EOL schedule:
* Vertica 9: 31 Oct 2021
* Vertica 10: 28 Feb 2023

Update minimum Vertica version to 11

---

core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorNodePartitioningProvider.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeNodePartitioningProvider.java

Remove deprecated getSplitBucketFunction

---

core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4
core/trino-main/src/test/java/io/trino/type/TestArrayOperators.java

Support array literal using just square brackets.  For example:
```
[]
['a', 'b']
```
```markdown
* Add ARRAY literal syntax using just square brackets. For example, `['a', 'b']` ({issue}`issuenumber`)
```

Add simpler array literal syntax

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/file/TestTrinoHiveCatalogWithFileMetastore.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestTrinoHiveCatalogWithHiveMetastore.java

Trino does not set `write.<fileType>.compression-codec` table property value when creating new tables. As effect of that, all new tables created with Trino would have `"write.parquet.compression-codec"="zstd"` (Iceberg lib is setting this default):
```bash
trino> set session iceberg.compression_codec = 'SNAPPY';
SET SESSION
trino> create table iceberg.default.le_table(data integer) with (format='parquet');
CREATE TABLE
trino> select * from iceberg.default."le_table$properties";
key               |  value  
---------------------------------+---------
write.format.default            | PARQUET 
write.parquet.compression-codec | zstd    
commit.retry.num-retries        | 4       
(3 rows)
```
When a new Iceberg table is created with Trino, it will use session write compression codec to set …

Set write compression codec in Iceberg

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TestCheckpointEntryIterator.java

Ensure max values are always greater than min values by using a minimum repeat count of 1 for the "A" and "Z" prefix strings
The potentially failure is hitted in https://github.com/trinodb/trino/pull/25311
```markdown
```

Fix min/max stats generation in TestCheckpointEntryIterator

---

core/trino-main/src/main/java/io/trino/operator/FlatHashStrategyCompiler.java
core/trino-main/src/main/java/io/trino/operator/FlatSet.java
core/trino-main/src/main/java/io/trino/operator/JoinDomainBuilder.java
core/trino-main/src/main/java/io/trino/operator/aggregation/AbstractMapAggregationState.java
core/trino-main/src/main/java/io/trino/operator/aggregation/arrayagg/FlatArrayBuilder.java
core/trino-main/src/main/java/io/trino/operator/aggregation/histogram/TypedHistogram.java
core/trino-main/src/main/java/io/trino/operator/aggregation/multimapagg/AbstractMultimapAggregationState.java
core/trino-main/src/test/java/io/trino/operator/GroupByHashYieldAssertion.java
core/trino-main/src/test/java/io/trino/operator/TestFlatHashStrategyCompiler.java

Updates additional places in code to use `AppendOnlyVariableWidthData` (introduced in https://github.com/trinodb/trino/pull/25127) to reduce their memory usage as well.
Also adds a special case to `FlatHashStrategyCompiler` for generating `FlatHashStrategy` classes that have less than 500 columns. In those common cases, simpler logic can be used to in the hash method. Similarly, `FlatHashStrategy#valueIdentical` methods are changed to propagate the variableWidthOffset between calls without allocating a `MutableVariableWidthOffset` instance.

Expand use of AppendOnlyVariableWidthData

---

core/trino-main/src/main/java/io/trino/operator/join/JoinOperatorInfo.java
core/trino-main/src/main/java/io/trino/operator/join/JoinStatisticsCounter.java
core/trino-main/src/test/java/io/trino/operator/join/TestJoinOperatorInfo.java

Minor improvement to `JoinOperatorInfo` and `JoinStatisticsCounter` to use `OptionalLong` instead of boxed `Optional<Long>`.

Use OptionalLong for JoinStatisticsCounter

---

core/trino-main/src/main/java/io/trino/execution/CommentTask.java
core/trino-main/src/test/java/io/trino/execution/TestCommentTask.java

In case of using case-sensitive column alias during view creation, we are not able to add column comment.
Steps to reproduce:
- create any table
- create view with column alias with non-lower case name: 
```
CREATE VIEW some_view AS 
SELECT lower_case UPPER_CASE 
FROM some_table
```
- set column comment:
` COMMENT ON COLUMN some_view.UPPER_CASE IS 'some comment'`
- we got exception: 
`io.trino.spi.TrinoException: line 1:1: Column does not exist: upper_case`
When view is created we parse original query inside `CreateViewTask` and extract columns:
```
List<ViewColumn> columns = analysis.getOutputDescriptor(statement.getQuery())
.getVisibleFields().stream()
.map(field -> new ViewColumn(field.getName().get(), field.getType().getTypeId(), Optional.empty()))
.collect(toImmutableList());
``` …

Fix failure when commenting on non-lowercased view columns

---

lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemMoto.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreModule.java
plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMotoConnectorSmokeTest.java
testing/trino-testing-containers/pom.xml
testing/trino-testing-containers/src/main/java/io/trino/testing/containers/MotoContainer.java

[Moto](http://docs.getmoto.org/en/latest/) provides mock instances of AWS services, including S3 and Glue.
```markdown
* Fix Glue endpoint URL override. ({issue}`25324`)
* Fix Glue endpoint URL override. ({issue}`25324`)
* Fix Glue endpoint URL override. ({issue}`25324`)
* Fix Glue endpoint URL override. ({issue}`25324`)

Add Moto testcontainer with S3 and Glue tests

---

plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleCastPushdown.java

Refactor the test class `TestOracleCastPushdown` writing to follow the guidance https://trino.io/docs/current/develop/tests.html
* Use `ImmutableList.Builder` for easier future additions

Refactor TestOracleCastPushdown to align with Trino guidelines

---

core/trino-main/pom.xml
core/trino-main/src/main/java/io/trino/execution/SessionPropertyEvaluator.java

Use java-string-similarity and JaroWinkler for fuzzy matching

---

plugin/trino-hive/pom.xml
plugin/trino-iceberg/pom.xml
pom.xml
testing/trino-testing-containers/pom.xml

Move Minio exclusions to root POM

---

core/trino-main/src/main/java/io/trino/execution/scheduler/faulttolerant/EventDrivenFaultTolerantQueryScheduler.java

fixes: https://github.com/trinodb/trino/issues/25217
```markdown
* Fix a bug where queries could fail with java.lang.IllegalStateException: task ... already marked as finished when run with `retry_policy` set to `TASK`
```

Handle race conditition in receiving final task info 

---

.github/workflows/stale.yml

I wont have the bandwidth to handhold all stale PRs anymore. If anyone else could be taking up that job we can add that person but for now I think we can just send people to #core-dev and expand the time to stale and the time to close. What do you all think?
After discussion on slack and different ideas around the timing and workflow I am leaving it unchanged for now. We can figure out next steps separately. The current PR only removes the noise of notifications for me.

Direct stale PRs to core-dev channel

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-473.md

In this release: https://github.com/trinodb/trino/pulls?q=is%3Apr+milestone%3A473+is%3Aclosed+sort%3Aupdated-desc

Add 473 release notes

---

core/trino-main/src/main/java/io/trino/dispatcher/DispatchManager.java
core/trino-spi/src/main/java/io/trino/spi/resourcegroups/SelectionCriteria.java
docs/src/main/sphinx/admin/resource-groups-example.json
docs/src/main/sphinx/admin/resource-groups.md
plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/AbstractResourceConfigurationManager.java
plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/SelectorSpec.java
plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/StaticSelector.java
plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/db/DbResourceGroupConfigurationManager.java
plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/db/ResourceGroupsDao.java
plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/db/SelectorRecord.java
plugin/trino-resource-group-managers/src/main/resources/db/migration/mysql/V7__add_original_and_authenticated_user_to_selectors.sql
plugin/trino-resource-group-managers/src/main/resources/db/migration/oracle/V7__add_original_and_authenticated_user_to_selectors.sql
plugin/trino-resource-group-managers/src/main/resources/db/migration/postgresql/V7__add_original_and_authenticated_user_to_selectors.sql
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/TestFileResourceGroupConfigurationManager.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/TestResourceGroupIdTemplate.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/TestStaticSelector.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/TestingResourceGroups.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/H2ResourceGroupsDao.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupConfigurationManager.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbSourceExactMatchSelector.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestResourceGroupsDao.java
plugin/trino-resource-group-managers/src/test/resources/resource_groups_config_original_auth_user.json
testing/trino-tests/src/test/java/io/trino/execution/TestQueues.java
testing/trino-tests/src/test/java/io/trino/execution/resourcegroups/db/H2TestUtil.java
testing/trino-tests/src/test/java/io/trino/execution/resourcegroups/db/TestQueuesDb.java
testing/trino-tests/src/test/resources/resource_groups_config_original_user.json

This PR adds the [original user](https://github.com/trinodb/trino/blob/e86635d3c9e2fd1c7bd9aa430cd04e584ab435ef/core/trino-main/src/main/java/io/trino/server/SessionContext.java#L136) and [authenticated user](https://github.com/trinodb/trino/blob/e86635d3c9e2fd1c7bd9aa430cd04e584ab435ef/core/trino-main/src/main/java/io/trino/server/SessionContext.java#L126) as selectors that can be used in resource group selection, allowing for more flexible selection of resource groups based on additional context about the user's identity.
Currently, [resource group selection](https://trino.io/docs/current/admin/resource-groups.html#selector-rules) can take into account the [current session user](https://github.com/trinodb/trino/blob/e86635d3c9e2fd1c7bd9aa430cd04e584ab435ef/core/trino-main/src/main/java/i …

Add originalUser and authenticatedUser as selectors available for resource group selection

---

docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/IcebergRestCatalogConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/OAuth2SecurityConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/OAuth2SecurityProperties.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestOAuth2SecurityConfig.java

RestSessionCatalog can be configured by changing authentication session time to live and enable/disable token refresh mechanics. This change allows to configure these properties from Trino and pass to RestSessionCatalog replacing defaults
`iceberg.rest-catalog.session-timeout` sets duration to keep authentication session in cache `iceberg.rest-catalog.oauth2.token-refresh-enabled` controls whether a token should be refreshed if information about its expiration time is available
Trino has multiple options to communicate with Iceberg Rest Catalog in `OAUTH2` mode: fill credentials or token when configuring a catalog
Another case can be used when we have enabled Oauth2 for Trino itself and it would be useful to reuse the authentication when communicating with the Iceberg Rest Catalog
Trino's …

Add support for session timeout property and token refresh setting configuration in Iceberg REST catalog

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java

This constants are used only from IcebergMetadata. 

Move constants to IcebergMetadata

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

After [fix](https://github.com/trinodb/trino/pull/21253) the method `canEnforceColumnConstraintInSpecs` always returns `false` if the table is empty and there is no `partitionSpec`. But if we try to delete from partition table and use partition in filter the method should return the `true`.
For example, if we runing query
```
delete from iceberg.dev_tmp.test_reading_iceberg where date_year = date '2022-02-15'
```
for the table
```
create table iceberg.dev_tmp.test_reading_iceberg  (
launch_id	bigint,
user_id	    bigint,
badge_id	bigint,
is_active	boolean,
date_from	timestamp(6),
date_to	    timestamp(6),
date_year	date
)
with (
format = 'ORC',
partitioning = ARRAY['date_year'],
sorted_by = ARRAY['user_id']
);
```
we will have the next plan
```
Trino version: 461
Output[columnNames = …
```

Fix pushdown when no partitionSpec exists and table is partitioned

---

core/trino-main/src/main/java/io/trino/operator/FlatHash.java

One correctness fix and two small cleanups after https://github.com/trinodb/trino/pull/25127:
- **Fix**: uses a consistent control bucket hash lookup argument (parenthesizing `(hash >> 7)` in both places). The associativity of casting and shifting differences with and without the parenthesis would break the has probing logic and result in incorrect results when more than 2^25 (~33.5M) unique entries are inserted into the table.
- Adds back logic that was accidentally removed from `FlatHash` for `GroupByHashMode.PRECOMPUTED` handling. That logic is unnecessary in production since that codepath is no longer reachable except in benchmarks and tests
- Removes the unused `FlatHash#contains` methods
( ) Release …

Fix FlatHash

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-474.md

In this release: https://github.com/trinodb/trino/pulls?q=is%3Apr+milestone%3A474+is%3Aclosed+sort%3Aupdated-desc+

Add 474 release notes

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/procedure/TestIcebergOptimizeManifestsProcedure.java

Follow-up of #24678
```markdown
* Optimize manifest files by the top-level partition using the `optimize_manifests` procedure. ({issue}`25378`)
```

Optimize manifests per top-level partition in Iceberg

---

plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClientModule.java
plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlTableProperties.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java

Add MysqlTableProperties and support create table with primary key in mysql.
```markdown
* Add support for creating tables with `primary_key` table property. 
```

 Add support create table with primary key in mysql

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergConnector.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergModule.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/system/IcebergTablesSystemTable.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseSharedMetastoreTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogCaseInsensitiveMapping.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergUnityRestCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/snowflake/TestIcebergSnowflakeCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/containers/UnityCatalogContainer.java

Add the ability to list only iceberg tables from the iceberg catalog. Before this change, there was no way to list only iceberg tables. The SHOW TABLES statement, information_schema.tables, and jdbc.tables will all return all tables that exist in the underlying metastore, even if the table cannot be handled in any way by the iceberg connector. This can happen if other connectors like hive or delta, use the same metastore, catalog, and schema to store its tables. The function accepts an optional parameter with the schema name. Sample statements:
`SELECT * FROM iceberg.system.iceberg_tables;`
`SELECT * FROM iceberg.system.iceberg_tables WHERE table_schema = 'test';`
https://github.com/trinodb/trino/pull/24469 added this functionality as a table function but it was reverted as the system …

Add system.iceberg_tables system table

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/procedure/TestIcebergAddFilesProcedure.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/procedure/TestIcebergMigrateProcedure.java

This PR fixes a bug where `iceberg.system.migrate` fails when a Hive table's partition key contains special characters (e.g., `@`). The failure happens because the migration process incorrectly applies Iceberg’s partition parsing rules to Hive tables, leading to an `Invalid partition field declaration` error.
When running:
```sql
CREATE TABLE hive.tpch.test_migrate_partitioned_table
WITH (partitioned_by = ARRAY['special@col'])
AS SELECT 1 AS id, 'special1' AS "special@col";
CALL iceberg.system.migrate('tpch', 'test_migrate_partitioned_table')
```
If the Hive table has a partition key with special characters, the migration fails with:
```sql
io.trino.spi.TrinoException: Unable to parse partitioning value: Invalid partition field declaration: special@col
```
```md
* Fix failure when …
```

Fix Hive-to-Iceberg table migration errors caused by special characters.

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ForwardingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMergeSink.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMergeTableHandle.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/RetryingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/JdbcClientStats.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcFailureRecoveryTest.java
plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMergeTableHandle.java
plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteMetadata.java
plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlFailureRecoveryTest.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/BasePostgresFailureRecoveryTest.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlJdbcConnectionAccesses.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlJdbcConnectionCreation.java
testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java

Here is a simple draw to shows how it is happening in merge.
```markdown
* Support MERGE for Postgresql connector even if `retry_policy` is set to `TASK`. ({issue}`issuenumber`)
```

Support transactional MERGE for Postgresql connector

---

plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlGlobalTransactionMyConnectorSmokeTest.java

We no longer have to override the `createTestTableForWrites` to separately add the PK, and can instead provide the table definition that includes the PK.
This facility was added in #24930.
```markdown
```

Use the new facility to create tables with PK in MySQL tests

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemConfig.java
lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystemLoader.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemConfig.java

For AWS Java sdk v2, S3 bucket cross region access is restricted as a default unlike v1. To meet backward compatibility, cross region access property should be supported.
https://trinodb.slack.com/archives/CGB0QHWSW/p1740554905054189
```markdown
```

Support S3 cross region access property

---

core/trino-main/src/main/java/io/trino/sql/planner/AdaptivePlanner.java

As we are traversing initial and current plan when inserting new adaptive plan nodes we need to take into account all the changes made by multiple calls to adaptive planner; not just the recent one.
```markdown
* Fix occasional query failures when adaptive planning is used. ({issue}`issuenumber`)
```

Use cummulative set of change nodes when inserting adaptive plan node

---

client/trino-client/src/main/java/io/trino/client/ClientSession.java
client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
core/trino-main/src/main/java/io/trino/server/protocol/ExecutingStatementResource.java
testing/trino-tests/src/test/java/io/trino/tests/TestServer.java

This prevents a situation when long list of segments is returned and client slowly progresses over it which could take longer than a query abandoned timeout.
This change allows to send a heartbeat while client is progressing over data.
```markdown
```

Send query heartbeat while spooled data is downloaded

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java

There is no other "Wehn" typo. 

Fix typo in BigQueryConfig

---

docs/src/main/sphinx/connector/bigquery.md
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySessionProperties.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitSource.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadSessionCreator.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java

We made parallelism non-configurable in #22279. 
This works well in most cases, but users may still want to limit the max parallelism. 
```markdown
```

Make max parallelism configurable in BigQuery

---

core/trino-main/src/main/java/io/trino/operator/OperatorSpoolingController.java
core/trino-main/src/main/java/io/trino/operator/OutputSpoolingOperatorFactory.java
core/trino-main/src/main/java/io/trino/operator/PipelineContext.java
core/trino-main/src/main/java/io/trino/operator/PipelineSpoolingController.java
core/trino-main/src/main/java/io/trino/operator/SpoolingController.java
core/trino-main/src/test/java/io/trino/operator/TestSpoolingController.java

Limit number of inlined pages per pipeline, not operator

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java

There was an issue where the partition schema mismatched with the table schema, causing type coercion to occur. OpenX JSON was using column order-based type coercion, while the JSON format was using column name-based coercion.
When the partition schema was missing a column that existed in the table columns, the column order-based type coercion could assign incorrect types to the missing column. For example, it would attempt to parse a string column with an integer decoder, resulting in errors such as: `Character 'a' is neither a decimal digit number, decimal point, nor 'e' notation exponential mark.`
This PR makes OpenX JSON use column name based type coersion.
N/A
( ) Release notes are required. Please …

Use column name based type coersion for OpenX JSON

---

docs/src/main/sphinx/connector/delta-lake.md
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeColumnHandle.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitSource.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/statistics/FileBasedTableStatisticsProvider.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointEntryIterator.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/util/DeltaLakeDomains.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java

Introduces handling and pushdown of the metadata columns('$file_modified_time', '$path', '$file_size') in Delta Lake
Closes https://github.com/trinodb/trino/issues/25369
```markdown
* Add support for pruning splits using file_modified_time in Delta Lake. ({issue}`25369`)
```

Add support for pruning splits using metadata columns in Delta Lake

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/MockThriftMetastoreClient.java

Added unlock for case when exception occur during get connection to metastore if we don't unlock this lock, it stills in database and next locks will wait it, this lock have never removed as request finished with exception.
Without fix the one way to unlock is remove raw manually in database
```markdown
```

Fix eternal lock when hive metastore down during request with lock

---

.github/workflows/ci.yml
docs/src/main/sphinx/connector/singlestore.md
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/SingleStoreQueryRunner.java
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreConnectorTest.java
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreLatestConnectorSmokeTest.java
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreLatestTypeMapping.java
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestingSingleStoreServer.java

Switch to new dev singlestore docker image

---

docs/src/main/sphinx/object-storage/metastores.md
lib/trino-metastore/src/main/java/io/trino/metastore/HiveMetastore.java
lib/trino-metastore/src/main/java/io/trino/metastore/cache/CachingHiveMetastore.java
lib/trino-metastore/src/main/java/io/trino/metastore/tracing/TracingHiveMetastore.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/HiveMetastoreBackedDeltaLakeMetastore.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/file/DeltaLakeFileMetastoreTableOperations.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/thrift/DeltaLakeThriftMetastoreTableOperations.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/TestDeltaLakeMetastoreAccessOperations.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/TrinoViewHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveMetadataListing.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/file/FileMetastoreTableOperations.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperations.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperationsProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/IcebergHiveCatalogConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/IcebergHiveMetastoreCatalogModule.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrateProcedure.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestIcebergHiveCatalogConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestIcebergHiveCatalogWithoutLock.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/hms/TestTrinoHiveCatalogWithHiveMetastore.java

Fixes #22182
Request from Iceberg community: https://apache-iceberg.slack.com/archives/C025PH0G1D4/p1743095891453949
Iceberg documentation: https://iceberg.apache.org/docs/nightly/configuration/#hadoop-configuration
```markdown
* Add support for lock-free commit in Hive catalog. ({issue}`issuenumber`)
```

Add support for lock-free commit in Iceberg HMS catalog

---

core/trino-main/src/main/java/io/trino/sql/gen/PageFunctionCompiler.java
core/trino-main/src/test/java/io/trino/sql/planner/TestLocalExecutionPlanner.java
testing/trino-tests/src/test/java/io/trino/tests/TestServer.java

Previous exception message for MethodTooLargeException was too specific and was misleading at times.

Rephrase error message for MethodTooLargeException

---

plugin/trino-loki/src/test/java/io/trino/plugin/loki/TestLokiIntegration.java

The Loki query was selecting the second line of the test data. This is because the timestamp for the first line and start of the query were the same. All other tests move the timestamps for each line away from the start and end to avoid such a flake.
```markdown
```
Fixes #25035

Fix flaky TestLokiIntegration.testSelectTimestampLogsQuery

---

core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
core/trino-main/src/main/java/io/trino/execution/Input.java
core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
core/trino-main/src/main/java/io/trino/sql/planner/InputExtractor.java
core/trino-main/src/main/java/io/trino/tracing/TracingConnectorMetadata.java
core/trino-main/src/test/java/io/trino/execution/TestInput.java
core/trino-main/src/test/java/io/trino/execution/TestQueryInfo.java
core/trino-main/src/test/java/io/trino/execution/TestQueryStateMachine.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryInputMetadata.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergInputInfo.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergInputInfo.java
plugin/trino-mysql-event-listener/src/test/java/io/trino/plugin/eventlistener/mysql/TestMysqlEventListener.java
plugin/trino-openlineage/src/main/java/io/trino/plugin/openlineage/OpenLineageListener.java

Improve query metrics for input tables
```markdown
* Improved metrics for input tables in event listener. ({issue}`25475`)
```

Improve query metrics for input tables

---

core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RewriteExcludeColumnsFunctionToProjection.java
core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestRewriteExcludeColumnsFunctionToProjection.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/TableFunctionProcessorBuilder.java

After this change, the `exclude_columns` table function is rewritten into a projection. It enables pushdown and helps avoid memory issues related to the table function operator.
```markdown
* Improve performance of certain queries involving the `exclude_columns` table function. ({issue}`25117`)
```
Fixes https://github.com/trinodb/trino/issues/25117
cc @takezoe

Rewrite exclude_columns table function into projection

---

core/trino-main/src/main/java/io/trino/sql/planner/SubqueryPlanner.java

As the title. 
In some CPU-bound scenarios, according to the cpu-profiler result, if there is no subqueries, the method `cluster()` and `selectSubqueries()` are no need to be executed to reduce cpu usage. 
(-) This is not user-visible or is docs only, and no release notes are required.
```markdown
```

Skip subquery plan if subqueryExpression List is empty for efficiency

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergFileOperations.java

`REFRESH MATERIALIZED VIEW` https://trino.io/docs/current/sql/refresh-materialized-view.html doesn't cleanup old snapshot files which causes materialized view size to grow without having any benefit of retaining old data.
Proposed solution uses `org.apache.iceberg.ExpireSnapshots` procedure in `io.trino.plugin.iceberg.IcebergMetadata#finishRefreshMaterializedView` to cleanup previous snapshot created just before the execution of refresh materialized view command.
```markdown
* Clean up old snapshots of the storage table on refresh of materialized views. ({issue}`25343`)
```

Cleanup previous snapshot files during materialized view refresh

---

core/trino-main/src/main/java/io/trino/type/SqlIntervalDayTime.java
core/trino-main/src/main/java/io/trino/type/SqlIntervalYearMonth.java

This is no longer used as these types have special handling in the JsonEncodingUtils
```markdown
```

Remove @JsonValue from SqlInterval* types

---

docs/src/main/sphinx/connector/iceberg.md

This PR adds a section to the Iceberg connector documentation for memory file system cache. The following properties are documented:
- `fs.memory-cache.ttl`
- `fs.memory-cache.max-size`
- `fs.memory-cache.max-content-length`
```markdown
```

Add documentation for iceberg memory file system caching properties

---

plugin/trino-ignite/src/main/java/io/trino/plugin/ignite/IgniteJdbcMetadataFactory.java

DefaultJdbcMetadataFactory  will check requireNonNull. So It's redundant in IgniteJdbcMetadataFactory
```markdown
```

Remove requireNonNull check in IgniteJdbcMetadataFactory

---

plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java

The order of columns in a MySQL primary key definition is significant. 
PRIMARY KEY (A, B) is different from PRIMARY KEY (B, A)
`KEY_SEQ` is a sequence number within primary key( a value of 1 represents the first column of the primary key, a value of 2 would represent the second column within the primary key)
```markdown
```

 Fix incorrect order of primary key in MySQL connector

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionsTable.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java

The entire `data` column became null after https://github.com/trinodb/trino/commit/f8cd48cd29c78a66eccc4bfc967f15de4b946ab2. We can return known values instead likes:
```sql
CREATE TABLE test(col int);
{col -> {min -> ...}}
ALTER TABLE test ADD COLUMN new_col int;
{col -> {min -> ...}, new_col -> {NULL}}
```
Fixes #25529
```markdown
```

Return null for new columns in Iceberg `$partitions` system table

---

plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPagesStore.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryPagesStore.java

Memory connector has the max memory size limit and `MEMORY_LIMIT_EXCEEDED` is thrown if the total size of pages exceeds it. Currently, however, `TRUNCATE TABLE` doesn't reduce the memory size. Therefore, `MEMORY_LIMIT_EXCEEDED` error eventually occurs if we repeat `TRUNCATE` and `INSERT` on memory tables.
```markdown
* Fix accounting of memory usage for truncated tables. ({issue}`25564`)
```

Fix memory size calculation when memory table is truncated

---

core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/eventlistener/DynamicFilterDomainStatistics.java
core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryStatistics.java
plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpEventListener.java
plugin/trino-http-server-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpServerEventListener.java
plugin/trino-kafka-event-listener/src/test/java/io/trino/plugin/eventlistener/kafka/TestUtils.java
plugin/trino-mysql-event-listener/src/test/java/io/trino/plugin/eventlistener/mysql/TestMysqlEventListener.java
plugin/trino-openlineage/src/test/java/io/trino/plugin/openlineage/TrinoEventData.java

( X) Release notes are required, with the following suggested text:
```markdown
* Expose dynamic filter statistics in the `QueryCompletedEvent`
```

Expose dynamic filter stats in QueryCompletedEvent

---

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/MetadataQueryOptimizer.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestMetadataQueryOptimization.java

Handle `DistinctLimitNode` in `MetadataQueryOptimizer`
```markdown
```

Optimize metadata query with distinct + limit

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/LegacyHiveViewReader.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java

Only presto view reader implementation uses this field

Make view data optional parameter for view reader

---

core/trino-main/src/main/java/io/trino/operator/project/PageProcessor.java

Fixes `PageProcessor` retained bytes tracking logic broken in https://github.com/trinodb/trino/commit/99c022cde1353411a25cf1561cc29ab022778ceb
Attempts to fix https://github.com/trinodb/trino/issues/25465
```markdown
* Fix memory tracking logic that could lead to unnecessary query failures due to EXCEEDED_LOCAL_MEMORY_LIMIT ({issue}`25600`)
```

Fix PageProcessor retained bytes tracking

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

```markdown
* Fix failure when analyzing the table without any snapshots. ({issue}`25563`)
```

Fix failure when analyzing no-snapshot Iceberg table

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Fixes: https://github.com/trinodb/trino/issues/25584
Concurrency errors could occur when trino runs EXECUTE OPTIMIZE and another system writes equality deletes. See above issue for details. 
Explicitly setting RewriteFiles.dataSequenceNumber. See iceberg java doc: https://iceberg.apache.org/javadoc/1.7.0/org/apache/iceberg/RewriteFiles.html#dataSequenceNumber(long)
```
Configure the data sequence number for this rewrite operation. This data sequence number will be used for all new data files that are added in this rewrite. This method is helpful to avoid commit conflicts between data compaction and adding equality deletes.
```
(x) Release …

Set dataSequenceNumber during iceberg EXECUTE OPTIMIZE

---

docs/src/main/sphinx/admin/event-listeners-openlineage.md

OpenLineage integration docs was updated - there are no some parameters specified here, now they have different names.
```markdown
```

Fix incorrect config properties in OpenLineage docs

---

lib/trino-orc/src/main/java/io/trino/orc/writer/DictionaryBuilder.java
lib/trino-orc/src/test/java/io/trino/orc/TestDictionaryBuilder.java

https://github.com/trinodb/trino/commit/a1fcb0d23f49d13b658bdc3e414d49bcf7f2a48c introduced a change to refactor `VariableWidthBlockBuilder` out of the ORC DictionaryBuilder class. Previously the DictionaryBuilder class would report the size in bytes by calling on the underlying `elementBlock.getSizeInBytes()` whose size was calculated based off the [output slice size and the bytes stored per entry/position](https://github.com/trinodb/trino/blob/47f9fa50e1172699643fbbdb57f6fd7570c053d0/core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlockBuilder.java#L112-L113).
After this refactor, DictionaryBuilder size is now being reported as the sum of the slice output size and the size of the offsets array, which is causing the size to be over-reported as not all positions of the offset …

Fix size in bytes calculation for ORC DictionaryBuilder

---

docs/src/main/sphinx/connector/clickhouse.md
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseTypeMapping.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java

Fix #25130 
```markdown
* Map Trino `boolean` type to ClickHouse `bool` type. ({issue}`25130`)
```

Add support for Bool type for ClickHouse connector

---

docs/src/main/sphinx/installation/plugins.md

1. Fix typos in installation/plugins page
2. Fix broken anchor links in installation/plugins page
1. The plugin addresses were misrepresented for `trino-elasticsearch` & `trino-hudi` plugins.
2. The anchor linked to the `List of Plugins` section on the same page was broken.

Fix invalid link in plugins.md

---

plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java

Disable LIKE pushdown for caseinsensitive columns
Fixes https://github.com/trinodb/trino/issues/25488
```markdown
* Fix incorrect results due to `LIKE` pushdown on case-sensitive collation columns. ({issue}`25488`)
```

Disable LIKE pushdown for caseinsensitive columns

---

plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/TypeUtils.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlTypeMapping.java

Fix #25557
```markdown
* Add support for `array(uuid)` type. ({issue}`25557`)
```

Add support for UUID arrays in PostgreSQL connector

---

docs/src/main/sphinx/connector/delta-lake.md

As a quick follow up to this PR: https://github.com/trinodb/trino/pull/25469, adding documentation for Delta Lake's checkpoint processing parallelism configuration
```markdown
```

Add documentation for Delta Lake's checkpoint processing parallelism configuration 

---

core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
core/trino-main/src/test/java/io/trino/sql/planner/TestWindowClause.java

Fixes a bug where initial plans for the exact same query string are non-deterministic when the query includes window functions with different resolved windows over the same window. (Resolved window takes into account `partition by`, `order by`, etc)
Window functions with the same window are planned in the same operation (see [commit](https://github.com/trinodb/trino/commit/3661df860953167fe1954f0f29f16662f346f4b6)). `QueryPlanner::planWindowFunctions` takes in a list of windowFunctions and converts it into a map to be processed. However, HashMaps do not guarantee input order, leading to different initial query plans for the same query string. 
This PR replaces the default `HashMap` with a `LinkedHashMap` to preserve the order of resolved windows (and by extension their associated window …

Preserve input order of window functions when planning window operations

---

lib/trino-hive-formats/src/main/java/io/trino/hive/formats/HiveFormatUtils.java
lib/trino-hive-formats/src/test/java/io/trino/hive/formats/TestHiveFormatUtils.java

Regex and OpenX JSON reader has parsing issues with timestamp types:
- A timestamp with trailing whitespace `2024-11-28 21:04:54.982 ` is parsed as null
After this change, it correctly outputs `2024-11-28 21:04:54.982` instead of null
N/A
( O ) Release notes are required, with the following suggested text:
```markdown
* Fix edge case timestamp parsing issues in Regex and OpenX JSON. A timestamp with trailing spaces will be output correctly instead of null ({issue}`issuenumber`)
```

Fix timestamp parsing issue in Regex and OpenX json deserializer

---

docs/src/main/sphinx/connector/hive.md
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConfig.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/S3GlacierFilter.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/CachingDirectoryLister.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConfig.java

Rename ```hive.s3.storage-class-filter``` to ```hive.s3-glacier-filter``` and add documentation as a follow up item for PR: https://github.com/trinodb/trino/pull/24979
```
- Rename hive configuration property ``hive.s3.storage-class-filter`` to ``hive.s3-glacier-filter`` to better reflect its purpose ({issue}`25633`)
```

Rename hive.s3.storage-class-filter and add documentation

---

core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4
core/trino-grammar/src/test/java/io/trino/grammar/sql/TestSqlKeywords.java
core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
core/trino-main/src/test/java/io/trino/sql/query/TestGroupBy.java
core/trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
core/trino-parser/src/main/java/io/trino/sql/tree/AstVisitor.java
core/trino-parser/src/main/java/io/trino/sql/tree/AutoGroupBy.java
core/trino-parser/src/main/java/io/trino/sql/tree/DefaultTraversalVisitor.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParserErrorHandling.java
docs/src/main/sphinx/language/reserved.md
docs/src/main/sphinx/sql/select.md

This syntax allows omitting column positions or names after `GROUP BY`. 
For instance, `SELECT name, count(1) FROM GROUP BY AUTO ` would be translated to `SELECT name, count(1) FROM GROUP BY name`
References in other database/query engines
* BigQuery https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#group_by_all
* Snowflake https://docs.snowflake.com/en/sql-reference/constructs/group-by#label-group-by-all-columns
* Databricks https://docs.databricks.com/sql/language-manual/sql-ref-syntax-qry-select-groupby.html
* ClickHouse https://clickhouse.com/docs/en/sql-reference/statements/select/group-by#group-by-all
* Databend https://databend.rs/doc/sql-commands/query-syntax/query-group-by#group-by-all-columns
(x) Release notes are required, with the following suggested …

Add support for `GROUP BY AUTO` aggregation

---

core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4
core/trino-grammar/src/test/java/io/trino/grammar/sql/TestSqlKeywords.java
core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
core/trino-main/src/test/java/io/trino/sql/query/TestSetOperations.java
core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
core/trino-parser/src/main/java/io/trino/sql/tree/Corresponding.java
core/trino-parser/src/main/java/io/trino/sql/tree/Except.java
core/trino-parser/src/main/java/io/trino/sql/tree/Intersect.java
core/trino-parser/src/main/java/io/trino/sql/tree/SetOperation.java
core/trino-parser/src/main/java/io/trino/sql/tree/Union.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
docs/src/main/sphinx/sql/select.md

Add support for CORRESPONDING option in set operations. 
The option matches columns by name instead of by position:
```sql
SELECT * FROM (VALUES (1, 'alice')) AS t(id, name)
UNION ALL CORRESPONDING
SELECT * FROM (VALUES ('bob', 2)) AS t(name, id);
```
```
id | name
----+-------
1 | alice
2 | bob
(2 rows)
```
The option is defined in SQL spec
```
<query expression body> ::=
<query term> 
| <query expression body>  UNION [ ALL | DISTINCT ]
[ <corresponding spec>  ] <query term> 
| <query expression body>  EXCEPT [ ALL | DISTINCT ]
[ <corresponding spec>  ] <query term> 
```
```
<query term> ::=
<query primary> 
| <query term>  INTERSECT [ ALL | DISTINCT ]
[ <corresponding spec>  ] <query primary> 
```
```
<corresponding spec> ::=
CORRESPONDING [ BY <left paren>  <corresponding column list> …
```

Add support for CORRESPONDING option in set operations

---

docs/src/main/sphinx/ext/download.py
docs/src/main/sphinx/installation/containers.md
docs/src/main/sphinx/installation/deployment.md
docs/src/main/sphinx/installation/plugins.md

Most of the work is done in the trino-packages repo .. just adding a pointer to the repo and some mention of the -core artifacts.
Part of #22597 

Document core artifacts and packages repo

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-475.md

https://github.com/trinodb/trino/pulls?page=1&q=is%3Apr+is%3Aclosed+milestone%3A475

Add 475 release notes

---

plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/GeometryType.java
plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestGeoSpatialQueries.java

In PostGIS, instances of Geometry are comparable (that is, you can run `select distinct` on those columns).
This PR allows Trino to do the same and addresses #24961.
e.g. with the patch applied:
```
trino> describe postgis.public.movement;                            
Column      |     Type     | Extra | Comment 
-----------------+--------------+-------+---------
id              | integer      |       |         
thing_id        | integer      |       |         
geometry        | Geometry     |       |         
geometry_string | varchar(50)  |       |         
dt              | timestamp(6) |       |          
speed_mph       | integer      |       |         
(6 rows)                                                           
Query 20250305_174904_00016_abpcz, FINISHED, 1 node …
```

make Geometry comparable

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/AbstractTestParquetReader.java

Support reading INT32 integers annotated with integer logical annotation in parquet as DATE type in Trino
```markdown
* Fix query failures when attempting to read parquet data with integer logical annotation as a DATE column in Trino. ({issue}`issuenumber`)
```

Support reading INT32 with integer annotation as DATE in parquet

---

docs/src/main/sphinx/admin/event-listeners-kafka.md
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/KafkaEventListenerConfig.java
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/KafkaEventPublisher.java
plugin/trino-kafka-event-listener/src/test/java/io/trino/plugin/eventlistener/kafka/TestKafkaEventListenerConfig.java

Fixes https://github.com/trinodb/trino/discussions/24074 by adding ability to specify Kafka client config overrides in separate file.
```markdown
```
This is a breaking change since old config is removed but IMO it's worth to do it - makes things easier in general.
The first commit is an alternative half-way fix which improves parsing of older config.

Make it easier to pass complex config for Kafka event listener client

---

plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/db/DbResourceGroupConfig.java
plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/db/FlywayMigration.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/BaseTestDbResourceGroupsFlywayMigration.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupConfig.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupsMysqlFlywayMigration.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupsOracleFlywayMigration.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupsPostgresqlFlywayMigration.java

Adding a flag that, during startup, disables migrations for resource groups when DB resource group store is enabled.
There is a need for us to not use migrations and make database changes manually. This flag allows us to not run migrations and use the same behavior that exists in trino gateway.
```markdown
* When the configured user does not have DDL privileges we want to be able to disable migration and run SQL updates manually. 
```

Allow configuration to disable migrations

---

docs/src/main/sphinx/admin/opentelemetry.md
docs/src/main/sphinx/release/release-475.md

- Add a release note in 475 mentioning support for exporting OpenTelemetry traces using the HTTP (OTLP/HTTP) protocol.
- Document the new `tracing.exporter.protocol` configuration property.
- Note that the feature was implemented in the Airlift repository.
https://github.com/trinodb/trino/issues/25338

Add release note and documentation for OpenTelemetry HTTP export support

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java

Observed flakiness with the test. Fix by increasing table size to sf3. 
```markdown
```

Fix flaky hive test bump table size sf2->sf3

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSinkProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java

This PR is making a code change such that ```max_partitions_per_writer``` can be changed at session level for Iceberg connector. 
Release notes are required, with the following suggested text:
```markdown
*  Add `max_partitions_per_writer` session property. ({issue}`25662`)
```

Add max_partitions_per_writer session property in Iceberg Connector

---

docs/Dockerfile
docs/requirements.txt

* bump up versions of packages used in requirements.txt used in the dockerfile to resolve identified vulnerabilities.
| Package  | Version in use | Version bumped to | Vulnerabilities fixed                                          |
|----------|----------------|-------------------|----------------------------------------------------------------|
| certifi  | 2019.11.28     | 2024.7.4          | CVE-2023-37920; CVE-2022-23491                                 |
| idna     | 2.9            | 3.7               | CVE-2024-3651                                                   |
| jinja2   | 3.1.3          | 3.1.6             | CVE-2024-56201; CVE-2024-56326; CVE-2025-27516; CVE-2024-34064 |
| pillow   | 9.2.0          | 10.3.0            | CVE-2023-50447; CVE-2022-45199; CVE-2023-44271 …

Fix vulnerable python packages in trino-docs

---

core/trino-main/src/main/java/io/trino/connector/FileCatalogStore.java

Store catalog names in lower case
This makes FileCatalogStore be in line with CreateCatalogTask, where
when a new catalog is created its name is lower cased.
Trino is not well prepared to non lower cased names, there is a plenty
of places where we use lower cased names (see QualifiedName#mapIdentifier as an example)
causing that catalogs are not then found.
Without this even simple queries like SHOW SCHEMAS FROM "CASE_CATalog" where failing as "case_catalog" was not found. 
I have tested the change manually. I am not sure if and how to add good testing.

Store catalog names in lower case

---

docs/src/main/sphinx/security/jwt.md

Documentation currently defines that a placeholder `$KEYID` can be used when specifying `http-server.authentication.jwt.key-file` [while the code looks for `${KID}` instead](https://github.com/trinodb/trino/blob/8bb87dd44820774040927aa872eeaddc62830b87/core/trino-main/src/main/java/io/trino/server/security/jwt/FileSigningKeyLocator.java#L52C52-L52C58).
Also, [the JWT header field is called `kid`](https://www.rfc-editor.org/rfc/rfc7515#section-4.1.4) instead of the currently used `keyid`.
This MR adapts the documentation so it matches the actual implementation and the official field name. …

Fix wrong variable name in JWT authenticator documentation

---

core/trino-main/src/main/java/io/trino/operator/project/InputChannels.java
core/trino-main/src/main/java/io/trino/operator/project/PageProcessor.java
core/trino-main/src/main/java/io/trino/operator/project/SelectedPositions.java
core/trino-main/src/test/java/io/trino/operator/TestingSourcePage.java
core/trino-spi/src/main/java/io/trino/spi/connector/FixedSourcePage.java
core/trino-spi/src/main/java/io/trino/spi/connector/PositionCountSourcePage.java
lib/trino-array/src/main/java/io/trino/array/ReferenceCountMap.java
lib/trino-orc/src/main/java/io/trino/orc/OrcRecordReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/MappedPageSource.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/TransformConnectorPageSource.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcDeletedRows.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/rcfile/RcFilePageSource.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchPageSource.java

Follows up from https://github.com/trinodb/trino/pull/25600 by account for all necessary components of `SourcePage` implementations in `SourcePage#getRetainedBytes()` and `SourcePage#retainedBytesForEachPart` methods. Also includes `SelectedPositions` and `Block[] previouslyComputedResults` in the `PageProcessor.ProjectSelectedPositions` retained size calculation.

Improve PageProcessor retained bytes calculations

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java

Replaced ICEBERG_BAD_DATA with ICEBERG_INVALID_METADATA for invalid metadata file name
```markdown
```

Update exception type for invalid metadata file name

---

core/trino-main/src/main/java/io/trino/event/SplitMonitor.java
core/trino-main/src/main/java/io/trino/execution/SqlTaskExecution.java
core/trino-main/src/main/java/io/trino/operator/SplitOperatorInfo.java
core/trino-main/src/main/java/io/trino/operator/TableScanOperator.java
core/trino-main/src/main/java/io/trino/operator/WorkProcessorSourceOperatorAdapter.java
core/trino-main/src/main/java/io/trino/operator/index/IndexSourceOperator.java
core/trino-main/src/test/java/io/trino/operator/TestOperatorStats.java

This information is available directly without having to go through OperatorStats
```markdown
```

Simplify fetching of catalog name for SplitCompletedEvent

---

core/trino-main/src/main/java/io/trino/operator/project/PageProcessor.java
core/trino-main/src/main/java/io/trino/operator/project/PageProcessorMetrics.java

Some minor cleanup refactors for `PageProcessor`, and a fix for `PageProcessorMetrics` to ensure that dynamic filter evaluation time is included even when all rows are filtered.

Cleanup PageProcessor

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Fix the problem that missing manifest file caused incorrect exception classification during orphan file cleanup in Iceberg by catching `NotFoundException` and materialized it to external exception
The stacktrace when doing cleanup among the corrupted table:
```
Suppressed: java.lang.Exception: SQL: ALTER TABLE test_remove_orphan_files_with_missing_manifest_oe9bnvdqt3 EXECUTE REMOVE_ORPHAN_FILES
at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:572)
... 10 more
Caused by: org.apache.iceberg.exceptions.NotFoundException: Failed to open input stream for file: local:///tpch/test_remove_orphan_files_with_missing_manifest_oe9bnvdqt3-aa1fbac9a99143dea362bc718ac39b22/metadata/8f654ea3-dcf9-4a00-9379-2c07bb3986bd-m0.avro
at …
```

Fix miscategorized exception in orphan file cleanup in Iceberg

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/TransactionLogAccess.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/MetadataAndProtocolEntries.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeFileOperations.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestTransactionLogAccess.java

Close #24570 
Try read metadata or protocol from transaction tail backwards, otherwise read from checkpoint stream. 
```markdown
* Improve query planning performance on delta tables. ({issue}`24570`)
```

Read latest metadata and protocol entry backwards

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergBucketFunction.java

There's a very hard to get to code path that causes a split to have `partitionValues = [null]` (I assume). The default was 0 which raises a casting error thanks to the getFirst being able to return either null or integer. Setting to 0L fixes the bug in the environment I was seeing it in.
I was unable to reproduce this within the test suite using several combinations of what I thought would be equivalent. I was, however, able to build a version of the Trino iceberg plugin with the fix and put that onto the Trino cluster exhibiting this behavior. With that jar in place, the error goes away.
Fixes #25125
```markdown
* Fix rare failure when `iceberg.bucket-execution` is enabled. ({issue}`25125`)
```

Fix bug with iceberg bucket functions and integer to long casts

---

lib/trino-orc/src/main/java/io/trino/orc/OrcRecordReader.java
lib/trino-orc/src/main/java/io/trino/orc/OrcWriteValidation.java
lib/trino-orc/src/main/java/io/trino/orc/OrcWriterFlushStats.java
lib/trino-orc/src/main/java/io/trino/orc/OrcWriterStats.java
lib/trino-orc/src/main/java/io/trino/orc/StripeReader.java
lib/trino-orc/src/main/java/io/trino/orc/metadata/OrcMetadataReader.java
lib/trino-orc/src/main/java/io/trino/orc/metadata/StripeInformation.java
lib/trino-orc/src/test/java/io/trino/orc/metadata/TestOrcMetadataReader.java

We have tables in dds layer that look like
```
CREATE TABLE dwh.dds.some_table (
id1 bigint,
flag boolean,
id2 bigint
)
WITH (
external_location = 's3a://some_path',
format = 'ORC'
)
```
where `id1` is unique and `id2` has only two values. The data file has 70 MB size and more than 7 000 000 000 rows.
When we try to read data the error occurs
```
TrinoExternalError(type=EXTERNAL, name=HIVE_CANNOT_OPEN_SPLIT, message="Error opening Hive split s3a://some_path/some_table.orc (offset=0, length=71782995): integer overflow", query_id= 20250417_090308_49505_msr65)
```
It happens because OrcProto support `long` type, but in the trino code we have `int` type.
( ) Release notes are required. Please propose a release …

Fix issue with reading footer of orc file with large stripe

---

.github/workflows/ci.yml

The job is consistently failing. Disabling the job temporarily as we couldn't find the solution. 
* https://github.com/trinodb/trino/actions/runs/14925170935/job/41928309800
* https://github.com/trinodb/trino/actions/runs/14923315000/job/41922601481
```
The JAVA_HOME environment variable is not defined correctly,
this environment variable is needed to run this program.
```

Disable 25-ea job temporarily

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/TableInvalidationCallback.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/CachingDirectoryLister.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/TransactionDirectoryListingCacheKey.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/TransactionScopeCachingDirectoryLister.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/fs/TransactionScopeCachingDirectoryListerFactory.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/BaseCachingDirectoryListerTest.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/TestCachingDirectoryListerRecursiveFilesOnly.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/fs/TestTransactionScopeCachingDirectoryLister.java

This change updates the cache key to use both Path and
SchemaTableName, enabling more precise identification of cached entries.
It allows us to iterate over cache keys effectively and target only the
relevant entries during invalidation.
This is especially useful for partitioned tables, where coarse-grained
invalidation can lead to unnecessary cache evictions and performance
degradation.
In response to this in the `CachingDirectoryListener`
```
//TODO use a cache key based on Path & SchemaTableName and iterate over the cache keys
// to deal more efficiently with cache invalidation scenarios for partitioned tables.
``` …

Improve cache invalidation by keying on path and table name

---

docs/src/main/sphinx/object-storage/file-system-azure.md
lib/trino-filesystem-azure/pom.xml
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthDefault.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthDefaultModule.java
lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureAuthManagedIdentityConfig.java
lib/trino-filesystem-azure/src/test/java/io/trino/filesystem/azure/TestAzureAuthManagedIdentityConfig.java

This PR allows us to configure [User-Assigned Managed Identity](https://learn.microsoft.com/en-us/entra/identity/managed-identities-azure-resources/overview) for Azure FS. 
Since User Managed Identity can be tested only in a environment specified in Azure - we are restricting the test cases to config specific one. I'll be validating this change on AKS to check if the proper APIs are invoked. 
I'm open with testing on additional testing mechanisms if required. 
```markdown
* Allow configuring User-ManagedIdentity in AzureFS
```

Allow configuring User-Assigned Managed Identity in AzureFS

---

plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClusteringPredicatesExtractor.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraMetadata.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSession.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraSplitManager.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/util/TestCassandraClusteringPredicatesExtractor.java

Cassandra 2.2.0 already reached EOL and https://github.com/trinodb/trino/pull/14562 removed support for the version.

Remove code for Cassandra <= 2.2.0

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/AbstractMetastoreTableOperations.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/HiveMetastoreTableOperations.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java

Other query engines store these information with Hive catalog.

Store snapshot id and timestamp to Hive metastore in Iceberg

---

lib/trino-filesystem-s3/src/main/java/io/trino/filesystem/s3/S3FileSystem.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/AbstractTestS3FileSystem.java
lib/trino-filesystem-s3/src/test/java/io/trino/filesystem/s3/TestS3FileSystemAwsS3.java
testing/trino-testing-containers/src/main/java/io/trino/testing/containers/MotoContainer.java

It's no longer needed since AWS SDK v2 added a LegacyMd5Plugin to ensure backward compatibility with S3-compliant storage.
Should fix https://github.com/trinodb/trino/issues/25780
```markdown
```

Remove signer override

---

docs/src/main/sphinx/connector/iceberg.md

Trino engine and Iceberg connector don't support column reorder. 

Remove reorder from Iceberg schema evolution docs

---

core/trino-main/pom.xml
core/trino-main/src/main/java/io/trino/server/ThrowableMapper.java

```markdown
* Fix rare bug when server can hang under load ({issue}`issuenumber`)
```

Workaround Jetty async thread hanging under contention

---

core/trino-main/src/main/java/io/trino/execution/buffer/PageSplitterUtil.java
core/trino-main/src/main/java/io/trino/operator/output/PagePartitioner.java
core/trino-main/src/main/java/io/trino/operator/output/TaskOutputOperator.java
core/trino-main/src/test/java/io/trino/block/AbstractTestBlock.java
core/trino-main/src/test/java/io/trino/block/TestDictionaryBlock.java
core/trino-main/src/test/java/io/trino/block/TestRunLengthEncodedBlock.java
core/trino-main/src/test/java/io/trino/execution/TestPageSplitterUtil.java
core/trino-main/src/test/java/io/trino/operator/TestHashAggregationOperator.java
core/trino-main/src/test/java/io/trino/operator/output/TestPositionsAppenderPageBuilder.java
core/trino-main/src/test/java/io/trino/operator/project/BenchmarkDictionaryBlock.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/block/ArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/Block.java
core/trino-spi/src/main/java/io/trino/spi/block/ByteArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/Fixed12Block.java
core/trino-spi/src/main/java/io/trino/spi/block/Int128ArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/IntArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/LongArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/MapBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/RowBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/RunLengthEncodedBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/ShortArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlock.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/rcfile/PageSplitterUtil.java
lib/trino-orc/src/test/java/io/trino/orc/TestOrcReaderPositions.java

The Block `getSizeinBytes` method has been defined to return the "compacted" size of a block.  This means for an RLE only the size of the single value is returned, and for a dictionary block the size of each position is computed from the dictionary. This computation is quite expensive and requires Blocks to have `getPositionsSizeInBytes` and `fixedSizeInBytesPerPosition` methods. 
This PR changes the implementation to be defined as returning an estimate of the full data size of a block. This means for an RLE block the size is `value.getSizeInBytes() * positionCount` and dictionary is `(dictionary.getSizeInBytes() / dictionary.getPositionCount()) * positionCount`, which is simpler and much faster to compute.
The `getSizeinBytes` method is typically used to estimate the size needed for …

Change Block getSizeInBytes to estimate fully expanded data size

---

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystem.java

Use location directoryPath in isHierarchicalNamespaceEnabled check to fix error on Microsoft OneLake destinations.
Fixes #25453
```markdown
```

Use location directoryPath in isHierarchicalNamespaceEnabled check

---

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystem.java

Reverts trinodb/trino#25457
This broke the CI.

Revert "Use location directoryPath in isHierarchicalNamespaceEnabled check"

---

docs/src/main/sphinx/connector/delta-lake.md
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeConfig.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConfig.java

The default row group size for parquet files in delta is 128MB. 
The default for split size should match that. 
The previous smaller value of 64MB generated unnecessary splits.
```markdown
* Increase delta.max-split-size to 128MB. ({issue}`25826`)
```

Increase delta.max-split-size to 128MB

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcModule.java
plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClientModule.java

Using async executor seems to result in the connector locking up under high concurrency
Fixes https://github.com/trinodb/trino/issues/25665
Related to changes from https://github.com/trinodb/trino/commit/182744d3ddb361cb1acb77f5a2660b0919ad4ee5
```markdown
```

Avoid using background executor for oracle queries

---

core/trino-main/src/main/java/io/trino/execution/HeapSizeParser.java
core/trino-main/src/main/java/io/trino/memory/NodeMemoryConfig.java
core/trino-main/src/test/java/io/trino/execution/BaseTestSqlTaskManager.java
core/trino-main/src/test/java/io/trino/execution/TestHeapSizeParser.java
core/trino-main/src/test/java/io/trino/memory/TestLocalMemoryManager.java
core/trino-main/src/test/java/io/trino/memory/TestNodeMemoryConfig.java
docs/src/main/sphinx/admin/properties-resource-management.md
docs/src/main/sphinx/admin/properties.md

```markdown
* Allow configuring `query.max-memory-per-node` and `memory.heap-headroom-per-node` relative to maximum heap size ({issue}`issuenumber`)
```

Allow configuring heap relative to maximum

---

docs/src/main/sphinx/connector/googlesheets.md
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsClient.java
plugin/trino-google-sheets/src/main/java/io/trino/plugin/google/sheets/SheetsConfig.java
plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestSheetsConfig.java

This change lets the Google Sheets connector to authenticate by using delegated user credentials instead of raw service-account identity (which lives outside the domain). By supplying a “delegated user” email address, the connector will:
1. Obtain domain-wide delegated credentials for that user
2. Build a Sheets client under the user’s identity
Since the domain of google service account is different from the organization's Google workspace domain, this change allows to share the google sheets only within the Google workspace domain of the organization. 
1. **New Config option**: `gsheets.delegated-user-email`
2. **Auth Flow Update**: If `gsheets.delegated-user-email` is set, we load the service-account key, request the delegated credentials for that user, and build the Sheets client with …

Enable Authentication for Google Sheet Connector Using Delegated User Credentials

---

docs/src/main/sphinx/admin/event-listeners-mysql.md
docs/src/main/sphinx/connector/mysql.md

The MySQL Event Listener and MySQL Connector documentation are pointing to an incorrect page. It should be updated to link to the correct one.
Fixes #25846 

[Doc] Update MySQL Configuration Properties Link

---

core/trino-main/src/main/java/io/trino/execution/buffer/PageSplitterUtil.java
core/trino-main/src/test/java/io/trino/execution/TestPageSplitterUtil.java

Consider only the underlying value block size for RLE blocks in page splitting calculation. 
This prevents the splitting up of Pages due to getSizeInBytes of RLE blocks being a factor of positions count
Follow-up of https://github.com/trinodb/trino/pull/25256#discussion_r2093398301
```markdown
```

Reduce contribution of RLE blocks size in page splitting

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestSharedGlueMetastore.java

Relates to #25859
It seems AWS changed Glue behavior recently. The procedure throws "updating `table_type` parameter is not supported" error. 

Disable migrate procedure test on Iceberg Glue catalog

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/statistics/TestDeltaLakeFileBasedTableStatisticsProvider.java

Remove redundant variable in TestDeltaLakeFileBasedTableStatisticsProvider

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java

Fix wrong parameter in checkCanExecuteTableProcedure

---

plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClientModule.java

Extending this https://github.com/trinodb/trino/pull/22241 framework for Oracle connector.
Since Oracle has a list of schemas to be filtered during the runtime, we end up on reading more number of columns to be filtered so instead of `O(#tables)` we have simplified to `O(#schema)`.
```markdown
* Improve performance of listing table columns. ({issue}`issuenumber`)
```

Bulk fetch all columns from all tables per schema for Oracle connector

---

core/trino-main/src/main/java/io/trino/sql/ir/ExpressionTreeRewriter.java
core/trino-main/src/main/java/io/trino/sql/ir/Row.java
core/trino-main/src/main/java/io/trino/sql/ir/optimizer/IrExpressionOptimizer.java
core/trino-main/src/main/java/io/trino/sql/ir/optimizer/rule/EvaluateRow.java
core/trino-main/src/main/java/io/trino/sql/planner/TranslationMap.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushCastIntoRow.java
core/trino-main/src/test/java/io/trino/sql/query/TestIssue25864.java
core/trino-spi/src/main/java/io/trino/spi/type/RowType.java

Fixes #25864 
```markdown
* Fix failure for queries involving casts with row types. ({issue}`25864`)
```

Preserve field names in row type

---

docs/src/main/sphinx/connector/iceberg.md

Document the fact that partitions having
only one data file without any delete files
are disregarded for `OPTIMIZE` scenarios
in case of the Iceberg connector.
```markdown
```

Detail the constraints in applying OPTIMIZE in Iceberg

---

plugin/trino-exchange-filesystem/pom.xml
plugin/trino-exchange-filesystem/src/main/java/io/trino/plugin/exchange/filesystem/s3/S3FileSystemExchangeStorage.java

fixes: #25908
```markdown
* Improve retry logic for S3 operations in filesystem exchange. ({issue}`25908`)
```

Use separate S3Client instance per bucket

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeLocalConcurrentWritesTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

Disable flaky tests in Iceberg and Delta Lake connectors

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestSharedGlueMetastore.java

Reverts trinodb/trino#25860. 
AWS reverted the validation of `table_type`.

Revert "Disable migrate procedure test on Iceberg Glue catalog"

---

core/trino-main/src/main/java/io/trino/operator/GroupedTopNRankBuilder.java
core/trino-main/src/main/java/io/trino/operator/GroupedTopNRowNumberBuilder.java

Releases `GroupByHash` and associated memory from grouped top N ranking and row number operations once output begins since the hash table is no longer necessary after that point.
Similar to https://github.com/trinodb/trino/pull/25879
```markdown
* Reduce memory consumed by grouped Top N rank and row number operations ({issue}`25946`)
```

Release grouped top n memory on output

---

core/trino-main/src/main/java/io/trino/server/InternalAuthenticationManager.java
core/trino-main/src/main/java/io/trino/server/InternalCommunicationModule.java
core/trino-main/src/main/java/io/trino/sql/analyzer/TypeSignatureTranslator.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/IterativeOptimizer.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/RuleIndex.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ExpressionRewriteRuleSet.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/TestRuleIndex.java
core/trino-parser/src/main/java/io/trino/sql/ReservedIdentifiers.java
core/trino-parser/src/main/java/io/trino/sql/tree/LongLiteral.java
core/trino-parser/src/main/java/io/trino/sql/tree/NumericParameter.java
core/trino-parser/src/main/java/io/trino/sql/tree/NumericParser.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestTypeParser.java
core/trino-spi/src/main/java/io/trino/spi/block/BlockUtil.java

Random improvements to random things in random places

---

docs/src/main/sphinx/object-storage/file-formats.md
lib/trino-parquet/src/main/java/io/trino/parquet/ParquetReaderOptions.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/MetadataReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriter.java
lib/trino-parquet/src/test/java/io/trino/parquet/BenchmarkColumnarFilterParquetData.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestByteStreamSplitEncoding.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestInt96Timestamp.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestParquetReader.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestTimeMillis.java
lib/trino-parquet/src/test/java/io/trino/parquet/writer/TestParquetWriter.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMergeSink.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSourceFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetReaderConfig.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestBloomFilterStore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetReaderConfig.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSourceProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/MigrationUtils.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergTestUtils.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftPageSourceProvider.java

Reading unusually large parquet footers can lead to workers
going into full GC and crashing when decoding the footer in
org.apache.parquet.format.Util#readFileMetaData
This is usually caused by misconfigured parquet writers producing
too many row groups per file. This change adds a guard rail to
fail reads of such files gracefully.
```markdown
* Prevent workers from going into full GC or crashing when decoding unusually large parquet footers. ({issue}`25973`)
```

Avoid reading unusually large parquet footers

---

client/trino-cli/src/main/java/io/trino/cli/QueryRunner.java
client/trino-client/src/main/java/io/trino/client/StatementClientV1.java
client/trino-client/src/main/java/io/trino/client/UserAgentBuilder.java
client/trino-client/src/test/java/io/trino/client/TestUserAgentBuilder.java
client/trino-jdbc/src/main/java/io/trino/jdbc/NonRegisteringTrinoDriver.java

This sends more information about the client to the Trino cluster.
Structure is similiar to other tools like AWS SDK:
```
aws-sdk-java/2.31.42 md/io#sync md/http#Apache ua/2.1 os/Linux#5.10.236-228.935.amzn2.aarch64 lang/java#24.0.1 md/OpenJDK_64-Bit_Server_VM#24.0.1+9 md/vendor#Eclipse_Adoptium md/en_US app/Trino cfg/auth-source#stsweb m/D
```
For our own clients it will be similiar to:
```
trino-cli/1.0.0 os=Mac_OS_X os/version=15.3.1 arch=aarch64 lang/java=24+36 java/vm=OpenJDK_64-Bit_Server_VM java/vendor=Eclipse_Adoptium locale=pl-PL md/lang=en-US md/feature=experimental
```
(x) Release notes are required, with the following suggested …

Add detailed client information to User-Agent

---

docs/src/main/sphinx/admin/properties-writer-scaling.md
docs/src/main/sphinx/object-storage/file-formats.md
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSourceProvider.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiSessionProperties.java

- Update document of writer_scaling_min_data_processed
- Add session property parquet_max_read_block_row_count to Hudi connector
- The default value of writer_scaling_min_data_processed is [120MB](https://github.com/trinodb/trino/blob/master/core/trino-main/src/main/java/io/trino/FeaturesConfig.java#L90).
- This session property `parquet_max_read_block_row_count` is intended to limit the maximum number of rows read in a batch for Hudi connector.
```markdown
* Add support for `parquet_max_read_block_row_count` session property.
```

Hudi sessin property: parquet_max_read_block_row_count

---

core/trino-main/src/main/java/io/trino/sql/analyzer/AggregationAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/test/java/io/trino/sql/query/TestGroupBy.java

Fixes #25984
```markdown
* Fix failure when aggregation exists in other expressions in `GROUP BY AUTO`. ({issue}`25987`)
```

Fix failure when aggregation function is wrapped in GROUP BY AUTO

---

docs/src/main/sphinx/connector/delta-lake.md

Similar documentation section exists already for the Iceberg connector on https://trino.io/docs/current/connector/iceberg.html#schema-and-table-management
```markdown
```

Document schema evolution capabilities for Delta Lake

---

plugin/trino-memory/src/main/java/io/trino/plugin/memory/ColumnInfo.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryColumnHandle.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryTableHandle.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/TableInfo.java

Improve query plan rendering for memory connector

---

core/trino-main/src/main/java/io/trino/execution/SplitAssignment.java
core/trino-spi/src/main/java/io/trino/spi/block/BlockUtil.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchRecordSet.java

Random improvements

---

lib/trino-filesystem-gcs/src/main/java/io/trino/filesystem/gcs/GcsStorageFactory.java
lib/trino-filesystem-gcs/src/test/java/io/trino/filesystem/gcs/TestGcsStorageFactory.java

If a JSON key or key file path are not provided, and using access tokens is not enabled, do not attempt to get the Application Default Credentials, instead allowing the GCS client library to use its own default behavior.
This will allow using Trino with custom GCS-compatible endpoints without auth, such as during development and testing.
Fixes #25810
```markdown
* Add support for using GCS without credentials (#25810)
```

Allow using GCS without providing credentials

---

pom.xml

Relates to https://nvd.nist.gov/vuln/detail/CVE-2025-49146

Update PostgreSQL driver to 42.7.7

---

docs/src/main/sphinx/udf/sql/begin.md

Trying to run the code example in [this documentation page](https://trino.io/docs/current/udf/sql/begin.html#begin) raises the following exception:
```
Value of DEFAULT must evaluate to tinyint (actual: integer)
```

Fix code example in documentation

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeSystemTableCompatibility.java

Running with Spark looks sufficient. 

Run case-sensitive property test only in OSS Delta

---

core/trino-main/src/main/java/io/trino/operator/PagesRTreeIndex.java
core/trino-main/src/main/java/io/trino/operator/PagesSpatialIndexSupplier.java

Previous code was using underlying value position of one channel on another channel's block. 
This can give incorrect results when one of channels uses an RLE or Dictionary block.
Seems to be broken since https://github.com/trinodb/trino/commit/de3c1600a38040a6efdec774b0ad519b748c663c
```markdown
* Fix incorrect results with spatial joins. ({issue}`26021`)
```

Fix block positions lookups in spatial join

---

docs/src/main/sphinx/object-storage/metastores.md

Document missing properties. 
- https://github.com/trinodb/trino/pull/24815/files#r1944804037
```markdown
```

Document missing iceberg rest catalog properties

---

core/trino-main/src/main/java/io/trino/operator/AppendOnlyVariableWidthData.java
core/trino-main/src/main/java/io/trino/operator/BigintGroupByHash.java
core/trino-main/src/main/java/io/trino/operator/FlatGroupByHash.java
core/trino-main/src/main/java/io/trino/operator/FlatHash.java
core/trino-main/src/main/java/io/trino/operator/GroupByHash.java
core/trino-main/src/main/java/io/trino/operator/NoChannelGroupByHash.java
core/trino-main/src/main/java/io/trino/operator/aggregation/builder/InMemoryHashAggregationBuilder.java
core/trino-main/src/test/java/io/trino/operator/CyclingGroupByHash.java
core/trino-main/src/test/java/io/trino/operator/TestGroupByHash.java

Incrementally releases memory from `FlatGroupByHash` when `HashAggregationOperator` starts producing output. Previously, the entire hash table contents were kept in memory until output data was produced from hash aggregations.
```markdown
* Reduce memory usage of aggregations by incrementally releasing memory as output rows are are produced ({issue}`25879`)
```

Release hash aggregation memory on output

---

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/test/java/io/trino/sql/query/TestMetadataMismatch.java

In `StatementAnalyzer#createMergeAnalysis`, in cases where the connector returns a partitioning column (from the insert layout) that doesn't exist in the table's schema, currently you will get a `GENERIC_INTERNAL_ERROR` with an empty message -- very confusing for users! The `failureType` is `NullPointerException` with a stack trace like this:
```
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889)
at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:813)
at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
at …
```

Handle NullPointerException in StatementAnalyzer createMergeAnalysis

---

testing/trino-product-tests-launcher/src/main/resources/docker/trino-product-tests/conf/environment/singlenode-delta-lake-databricks/tempto-configuration.yaml

Set Databricks JDBC socket timeout to 120 seconds

---

plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiTableProperties.java

Remove unused method from HudiTableProperties

---

lib/trino-parquet/src/main/java/io/trino/parquet/metadata/ParquetMetadata.java
lib/trino-parquet/src/main/java/io/trino/parquet/predicate/PredicateUtils.java

Certain parquet writers like pyarrow can set this offset incorrectly.
That can lead to the parquet reader not idenitfying the row groups
within a split correctly. This code is changed to rely on first page
offset in ColumnChunk instead.
Fixes https://github.com/trinodb/trino/issues/26058
Related to https://github.com/trinodb/trino/pull/24618
Newer versions of pyarrow (tested parquet-cpp-arrow version 20.0.0) don't have this problem, the file showing this problem is using `parquet-cpp-arrow version 5.0.0`
```markdown
* Fix incorrect results when reading from parquet files …
```

 Avoid relying on org.apache.parquet.format.RowGroup.getFile_offset

---

client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
client/trino-cli/src/main/java/io/trino/cli/Console.java
client/trino-cli/src/main/java/io/trino/cli/OutputHandler.java
client/trino-cli/src/main/java/io/trino/cli/Query.java
client/trino-cli/src/main/java/io/trino/cli/QueryRunner.java
client/trino-cli/src/test/java/io/trino/cli/TestClientOptions.java
client/trino-cli/src/test/java/io/trino/cli/TestQueryRunner.java

This prevents OOM exception when retrieving huge results
Relates to https://github.com/trinodb/trino/pull/26013
```markdown
* Allow configuring `--max-buffered-rows` and `--max-queued-rows` in the CLI ({issue}`issuenumber`)
```

Make queued and buffered rows configurable in cli

---

testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java

Cast column to bigint in smoke test queries when selecting data for assertions, prevents potential mismatches during test validation.
```markdown
```

Add explicitly cast for merge tests in `BaseConnectorSmokeTest`

---

plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPagesStore.java

Replaces manual null appending with `RunLengthEncodedBlock` when adding columns with null values
```markdown
```

Use `RunLengthEncodedBlock` for null column appends

---

core/trino-main/src/main/java/io/trino/operator/aggregation/builder/SpillableHashAggregationBuilder.java

Setting spiller to empty (without closing) caused spill files leak. Spiller is closed when SpillableHashAggregationBuilder is closed.
```markdown
* Fix spill files leaking in aggregation queries. ({issue}`issuenumber`)
```

Do not set spiller to empty in SpillableHashAggregationBuilder

---

core/trino-main/src/main/java/io/trino/operator/join/HashBuilderOperator.java
core/trino-main/src/main/java/io/trino/operator/join/unspilled/HashBuilderOperator.java
core/trino-main/src/test/java/io/trino/operator/join/TestHashJoinOperator.java
core/trino-main/src/test/java/io/trino/operator/join/unspilled/TestHashBuilderOperator.java

Operator#finish might be called even if operator is blocked (e.g. waiting for memory). Therefore, memory available condition needs to be re-checked every time finish is called.
```markdown
* Reduce number of worker OOMs when running join queries. ({issue}`issuenumber`)
```

Recheck that operator is not waiting for memory in hash builder finish

---

plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPagesStore.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryPagesStore.java

Follows up on https://github.com/trinodb/trino/pull/26140 by addressing [this comment](https://github.com/trinodb/trino/pull/26140#discussion_r2195668539) pointing out that the wrong loop index variable was being used for the RLE blocks attached.
Marking this change as not user visible since the introduced bug has not yet been released.

Fix column type index in MemoryPagesStore

---

core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
core/trino-main/src/test/java/io/trino/util/TestColumnDefaultOptions.java

NPE happened in char, varchar, and timestamp types. 
```markdown
```

Fix NPE due to NULL default column values

---

testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Use explicit casts on bigint columns instead of relying on `skippingTypesCheck`, which is insufficient for some connectors like `Snowflake` and `Oracle`
```markdown
```

Using explicit cast on bigint columns in row level update tests

---

docs/src/main/sphinx/admin/event-listeners-kafka.md
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/KafkaEventListenerConfig.java
plugin/trino-kafka-event-listener/src/main/java/io/trino/plugin/eventlistener/kafka/producer/BaseKafkaProducerFactory.java
plugin/trino-kafka-event-listener/src/test/java/io/trino/plugin/eventlistener/kafka/TestKafkaEventListenerConfig.java

Add support for `max.request.size` and `batch.size` configuration for Kafka producer of Kafka Event Listener
Fixes https://github.com/trinodb/trino/issues/26129
```markdown
* Add support for configuring max request size with the `kafka-event-listener.max-request-size` config property. ({issue}`26129`)
* Add support for configuring batch size with the `kafka-event-listener.batch-size` config property. ({issue}`26129`)
```

Add support for `max.request.size` and `batch.size` configuration for Kafka Event Listener

---

core/trino-main/src/test/java/io/trino/connector/MockConnectorPageSource.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorPageSource.java
core/trino-spi/src/main/java/io/trino/spi/connector/EmptyPageSource.java
core/trino-spi/src/main/java/io/trino/spi/connector/FixedPageSource.java
core/trino-spi/src/main/java/io/trino/spi/connector/RecordPageSource.java

```markdown
* Remove deprecated `ConnectorPageSource.getNextPage` method. ({issue}`26222`)
```

Remove deprecated ConnectorPageSource.getNextPage

---

docs/src/main/sphinx/object-storage/metastores.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/IcebergRestCatalogConfig.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/IcebergRestCatalogModule.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/SigV4AwsProperties.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/SigV4SecurityModule.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogConfig.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergS3TablesConnectorSmokeTest.java

Iceberg library treats SigV4 as a separate auth. 
https://github.com/apache/iceberg/blob/main/core/src/main/java/org/apache/iceberg/rest/auth/AuthProperties.java
```markdown
```

Replace sigv4-enabled with security in Iceberg

---

lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/ColumnReaderFactory.java
lib/trino-parquet/src/test/java/io/trino/parquet/TestTupleDomainParquetPredicate.java

When reading statistics from FileMetadata we respect only the Trino type i.e when we map a parquet file having long decimal to a short decimal type in Trino we tend to read the statistics as short decimal type and we end up on skipping row groups when reading the data.  
```markdown
*  Fix skipping of row groups when the trino type is different from logical types in case of parquet files.({issue}`issuenumber`)
```

Respect Parquet Logical type when reading statistics

---

plugin/trino-hive/pom.xml

Remove unused S3 dependency from Hive

---

core/docker/Dockerfile

Which is RHEL10 compatible
```markdown
```

Update docker image to UBI 10

---

core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaColumnHandle.java
core/trino-main/src/main/java/io/trino/connector/informationschema/InformationSchemaTableHandle.java

This simplifies EXPLAIN result:
```
trino> explain table memory.information_schema.tables;
Query Plan
--------------------------------------------------------------------------------------------------------------------------------------------------
Trino version: testversion
Fragment 0 [SOURCE]
Output layout: [table_catalog, table_schema, table_name, table_type]
Output[columnNames = [table_catalog, table_schema, table_name, table_type]]
│   Layout: [table_catalog:varchar, table_schema:varchar, table_name:varchar, table_type:varchar]
│   Estimates: {rows: ? (?), cpu: 0, memory: 0B, network: 0B}
└─ TableScan[table = memory:InformationSchemaTableHandle[catalogName=memory, table=TABLES, prefixes=[memory.*.*], limit=OptionalLong.empty]]
Layout: …
```

Implement `toString` method in InformationSchemaTableHandle and InformationSchemaColumnHandle

---

plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/MysqlEventListenerFactory.java
plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/QueryDao.java
plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/QueryEntity.java
plugin/trino-mysql-event-listener/src/main/java/io/trino/plugin/eventlistener/mysql/RecordAndAnnotatedConstructorMapper.java

Convert QueryEntity to record in MySQL event listener

---

core/trino-grammar/src/main/antlr4/io/trino/grammar/sql/SqlBase.g4
core/trino-main/src/main/java/io/trino/metadata/TableVersion.java
core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
core/trino-main/src/test/java/io/trino/sql/query/TestBranching.java
core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
core/trino-parser/src/main/java/io/trino/sql/tree/Table.java
core/trino-parser/src/test/java/io/trino/sql/TestSqlFormatter.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java

Allow specifying a branch name like `{table}@{branch}` in INSERT/UPDATE/DELETE/MERGE statements:
```g4
| INSERT INTO qualifiedName ('@' branch=identifier)?
columnAliases? rootQuery                                        #insertInto
| DELETE FROM qualifiedName ('@' branch=identifier)?
(WHERE booleanExpression)?                                    #delete
| UPDATE qualifiedName ('@' branch=identifier)?
SET updateAssignment (',' updateAssignment)*
(WHERE where=booleanExpression)?                               #update
| MERGE INTO
qualifiedName ('@' branch=identifier)? (AS? alias=identifier)?
USING relation ON expression mergeCase+                        #merge
```
Relates to https://docs.google.com/document/d/1jEF4IkWu-2Gzk5ii2Nb0exuEnAUeo98UbiM3i0xtgWQ
```markdown
* Add support for branching …
```

Add support for write operations (INSERT/UPDATE/DELETE/MERGE) with branch

---

core/trino-main/src/main/java/io/trino/operator/aggregation/DistinctAccumulatorFactory.java
core/trino-main/src/main/java/io/trino/operator/aggregation/OrderedAccumulatorFactory.java
core/trino-main/src/main/java/io/trino/operator/aggregation/builder/InMemoryHashAggregationBuilder.java

Releases `PagesIndex` from `Ordering(Grouped)Accumulator` and `MarkDistinctHash` from `Distinct(Grouped)Accumulator` instances after `prepareFinal()` or `evaluateFinal()` is called.
This helps mitigate an issue exposed by https://github.com/trinodb/trino/pull/25879 - which was that `HashAggreationOperator` wouldn't track any changes in memory consumption after output started. However, ordered grouped aggregations significantly _increase_ their memory consumption at the beginning of output as a result of transferring the contents of their `PagesIndex` into their underlying accumulators. …

Release memory eagerly in ordering and distinct accumulators

---

pom.xml

Update Snowflake JDBC driver to 3.25.1

---

plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftColumnHandle.java
plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftConnectorSplit.java
plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftIndexHandle.java
plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftIndexPageSource.java
plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftMetadata.java
plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftPageSource.java
plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftSplitManager.java
plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftTableHandle.java
plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/ThriftTableMetadata.java
plugin/trino-thrift/src/main/java/io/trino/plugin/thrift/util/TupleDomainConversion.java
plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/TestThriftProjectionPushdown.java

Convert to record in Thrift connector

---

core/trino-main/src/main/java/io/trino/operator/PagesIndex.java
core/trino-main/src/test/java/io/trino/sql/gen/TestJoinCompiler.java

Remove unnecessary usage of SimplePagesHashStrategy

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java

Reduces bottleneck on the default iceberg worker pool
```markdown
```

Use icebergScanExecutor for reading manifests in optimize and expire_snapshots

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/BaseTransactionsTable.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/TransactionLogTail.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/reader/FileSystemTransactionLogReader.java

Refactor `TransactionLogTail#loadNewTail` to support loading transaction log to based on param `startVersion` and `endVersion` conditional. Previously, the method only supported forward traversal from head to tail, which posed a risk when early transaction logs were missing -- maybe due to cleanup. This refactor enables both forward and backward traversal, increasing robustness and flexibility in tail loading logic.
Additionally, remove `BaseTransactionsTable#loadNewTailBackward` and use the enhanced loadNewTail method.
```markdown …
```

Refactor `TransactionLogTail#loadNewTail` method

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/org/apache/iceberg/IcebergManifestUtils.java

Reduces memory usage of coordinator during iceberg remove orphan files procedure for tables with large numbers of snapshots. 
See comment for description of fix:
```
/**
* Use instead of loadAllManifestsFromSnapshot when loading manifests from multiple distinct snapshots
* Each BaseSnapshot object caches manifest files separately, so loading manifests from multiple distinct snapshots
* results in O(num_snapshots^2) copies of the same manifest file metadata in memory
*/
```
To show decreased memory usage:
1. Created a table with 1000 snapshots/1000 manifest files and ran orphan files
```
@Test
public void testRemoveOrphanFilesOnTableWithManySnapshots()
{
String tableName = "test_remove_orphan_files_on_table_with_many_snapshots_" + randomNameSuffix();
String fullyQualifiedTableName = …
```

Reduce memory usage of remove_orphan_files procedure

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadataFactory.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/BaseTrinoCatalogTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestTrinoGlueCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/nessie/TestTrinoNessieCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java
plugin/trino-iceberg/src/test/java/org/apache/iceberg/snowflake/TestTrinoSnowflakeCatalog.java

Improve parallelism in remove_orphan_files procedure
```markdown
* Improve performance of remove_orphan_files procedure. ({issue}`26326`)
```

Improve parallelism in remove_orphan_files procedure

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoIcebergRestCatalogFactory.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/rest/TrinoRestCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestTrinoRestCatalog.java

Don't call Iceberg view endpoints if disabled

---

core/trino-main/src/test/java/io/trino/operator/window/WindowAssertions.java
core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAdaptivePartitioning.java
core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestColocatedJoin.java
core/trino-main/src/test/java/io/trino/sql/query/TestIssue23787.java
core/trino-main/src/test/java/io/trino/sql/query/TestJoin.java
core/trino-main/src/test/java/io/trino/sql/query/TestRandom.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
lib/trino-hive-formats/src/test/java/io/trino/hive/formats/esri/TestEsriDeserializer.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BaseBigQueryConnectorTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeBasic.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeConnectorTest.java
plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/TestElasticsearchComplexTypePredicatePushDown.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestEsriTable.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergLocalConcurrentWrites.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/rest/TestIcebergRestCatalogCaseInsensitiveMapping.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/snowflake/TestIcebergSnowflakeCatalogConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/org/apache/iceberg/snowflake/TestTrinoSnowflakeCatalog.java
plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java
plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaAccessControl.java
plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/TestOpenSearchComplexTypePredicatePushDown.java
plugin/trino-opensearch/src/test/java/io/trino/plugin/opensearch/TestOpenSearchProjectionPushdownPlans.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java

Fix checkstyle violations

---

docs/src/main/sphinx/connector/iceberg.md
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergAvroFileWriter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSessionProperties.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergTableProperties.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractTrinoCatalog.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java

This PR makes compression_codec a table property and drops support for compression_codec iceberg session property for simplicity.
Users are able to run the following command now to specify the compression_codec to create a new table with compression_codec set to ZSTD.
```
CREATE TABLE example (
c1 INTEGER,
c2 DATE,
c3 DOUBLE
)
WITH (
format = 'AVRO',
partitioning = ARRAY['c1', 'c2'],
sorted_by = ARRAY['c3'],
compression_codec = 'ZSTD'
);
```
Users are able able to change the compression_codec via statement ```Alter Table Set Properties```.
Example
```
ALTER TABLE example SET PROPERTIES compression_codec = 'GZIP';
```
The write_compression users specify will replace the session variable ```iceberg.compression-codec```. If the user change file_format without changing write_compression, it …

Support setting compression_codec table property for Iceberg

---

lib/trino-filesystem-azure/src/main/java/io/trino/filesystem/azure/AzureFileSystem.java

According to [this comment](https://github.com/Azure/azure-sdk-for-java/issues/38912#issuecomment-3160847541) from an Azure engineer, the version 12.31.0 of the azure-storage-blob dependency now supports OAuth for the [Get Account Info endpoint](https://learn.microsoft.com/en-us/rest/api/storageservices/get-account-information?tabs=shared-access-signatures#authorization). This PR updates the check for HNS on a storage account to use the Get Account Info endpoint, rather than the "hack" introduced in  #20897.
#20897
https://github.com/Azure/azure-sdk-for-java/issues/38912#issuecomment-3160847541 …

Check if HNS is enabled for Azure storage account using Get Account Info

---

core/trino-main/src/main/java/io/trino/client/direct/DirectTrinoClient.java
core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
core/trino-main/src/main/java/io/trino/testing/StandaloneQueryRunner.java
core/trino-main/src/main/java/io/trino/testing/TestingDirectTrinoClient.java
testing/trino-tests/src/test/java/io/trino/client/direct/TestDirectTrinoClient.java

When a query being executed by DirectTrinoClient takes longer than the query.client.timeout, the query is then canceled. This client is used in some cases when executing queries from within the coordinator
The `QueryTracker` uses this timeout in its `private boolean isAbandoned(T query)` method to check it vs the last heartbeat. @lukasz-stec recommended i periodically record a heartbeat while waiting for this future to avoid falling into that case.
```markdown
```

Handle long running queries in DirectTrinoClient

---

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/ldap/JdkLdapClient.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/ldap/LdapClientConfig.java
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/ldap/TestLdapConfig.java

Missing timeouts can cause ldap client to be stuck executing request indefinitely in case of network issues.
```markdown
* Set default connection and read timeout for the LDAP client to 1 minute
```

Set default ldap client timeouts to 1m

---

client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java

We are trying to connect IBM WebSphere to Trino via the trino JDBC Driver.
WebSphere® Application Server requires JDBC providers to implement one or both data source interfaces. These interfaces enable the application to run in a single-phase or two-phase transaction protocol.
- ConnectionPoolDataSource -  For Connection Pooling (One-Phase)
- A data source that supports application participation in local and global transactions, expecting two-phase commit transactions. 
- XADataSource -  For Distributed (Two-Phase) Transactions
- A data source that supports application participation in any single-phase or two-phase transaction environment.
Currently, the Trino JDBC driver does not implement any of the above data sources. Alternatively, there is another way where we could use Apache …

Implement setTypeMap and getTypeMap in TrinoConnection

---

core/trino-main/src/main/java/io/trino/Session.java
testing/trino-tests/src/test/java/io/trino/security/TestSessionImpersonation.java

Use identity's groups instead of OriginalIdentity's groups in session. Issue is described [here](https://github.com/trinodb/trino/issues/26301)
This PR specifically resolves Option 2 in the issue
```markdown
* Fix access control check when access is granted through groups in `SET SESSION AUTHORIZATION`  ({issue}`26344`)
```

Replace originalIdentity's groups with identity's groups

---

lib/trino-hive-formats/src/main/java/io/trino/hive/formats/encodings/text/BooleanEncoding.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/encodings/text/TextColumnEncodingFactory.java
lib/trino-hive-formats/src/main/java/io/trino/hive/formats/encodings/text/TextEncodingOptions.java
lib/trino-hive-formats/src/test/java/io/trino/hive/formats/line/simple/TestSimpleFormat.java

Hive [supports](https://issues.apache.org/jira/browse/HIVE-3635) `hive.lazysimple.extended_boolean_literal` for `LazySimpleSerde`.
```
LazySimpleSerde uses this property to determine if it treats 'T', 't', 'F', 'f', '1', and '0' as extended, legal boolean literal, in addition to 'TRUE' and 'FALSE'. The default is false, which means only 'TRUE' and 'FALSE' are treated as legal boolean literal.
```
Adding the same here.
```markdown
```

Support for extended boolean literal for LazySimpleSerde

---

docs/src/main/sphinx/admin/properties-client-protocol.md
docs/src/main/sphinx/client/client-protocol.md

Clarify documentation around spooling protocol
- This adds concrete examples for S3, Azure and GCS storage URLs
- Fixes a few minor typos

docs: Clarify documentation around spooling protocol

---

core/trino-main/src/main/java/io/trino/client/direct/DirectTrinoClient.java

Minor post-merge improvements.

Random cleanups in DirectTrinoClient

---

core/trino-main/src/test/java/io/trino/execution/buffer/TestPagesSerde.java
core/trino-spi/src/main/java/io/trino/spi/block/ArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/BlockUtil.java
core/trino-spi/src/main/java/io/trino/spi/block/ByteArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/Fixed12Block.java
core/trino-spi/src/main/java/io/trino/spi/block/Int128ArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/IntArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/LongArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/MapBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/RowBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/ShortArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlock.java
core/trino-spi/src/test/java/io/trino/spi/block/TestBlockUtil.java

Opportunistically discards block `isNull` arrays during copy when the resulting block contains no null positions.

Check block isNull array on copy

---

core/trino-main/src/main/java/io/trino/operator/scalar/MathFunctions.java
core/trino-main/src/test/java/io/trino/operator/scalar/TestMathFunctions.java
docs/src/main/sphinx/functions/math.md

All good to go.
follow up to #24005 
(*) Release notes are required, with the following suggested text:
```markdown
* Add the {func}`cosine_distance` function for sparse vectors. ({issue}`tbd`)
```

Add cosine_distance for sparse vectors

---

core/trino-spi/src/main/java/io/trino/spi/block/ArrayBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/ArrayBlockEncoding.java
core/trino-spi/src/main/java/io/trino/spi/block/ByteArrayBlockEncoding.java
core/trino-spi/src/main/java/io/trino/spi/block/EncoderUtil.java
core/trino-spi/src/main/java/io/trino/spi/block/Fixed12BlockEncoding.java
core/trino-spi/src/main/java/io/trino/spi/block/Int128ArrayBlockEncoding.java
core/trino-spi/src/main/java/io/trino/spi/block/IntArrayBlockEncoding.java
core/trino-spi/src/main/java/io/trino/spi/block/LongArrayBlockEncoding.java
core/trino-spi/src/main/java/io/trino/spi/block/MapBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/MapBlockEncoding.java
core/trino-spi/src/main/java/io/trino/spi/block/RowBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/RowBlockEncoding.java
core/trino-spi/src/main/java/io/trino/spi/block/ShortArrayBlockEncoding.java
core/trino-spi/src/main/java/io/trino/spi/block/VariableWidthBlockEncoding.java

Improve block serialization logic to prefer using primitive arrays over virtual calls when checking positions for nulls.
Benchmarks: [BenchmarkBlockSerde.serialize*](https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/pettyjamesm/ed61da9bd57b3bc742bf0a55920bf78b/raw/f8237b39edca6dbc77122909ab921d2d62c7f5b8/null_packing_baseline.json,https://gist.githubusercontent.com/pettyjamesm/ed61da9bd57b3bc742bf0a55920bf78b/raw/83526f49bd05cf957663443375b79aa0283fe4d3/null_packing_improved_v3.json)

Improve BlockEncoding null bits packing

---

plugin/trino-vertica/src/test/java/io/trino/plugin/vertica/TestingVerticaServer.java

Disable Vertica tests due to missing test container

---

plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaAccessControl.java
plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaAccessControlDataFilteringSystem.java
plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaAccessControlFactory.java
plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaAccessControlFiltering.java
plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaAccessControlPermissionManagementOperations.java
plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaAccessControlPlugin.java
plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaAccessControlSystem.java
plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaBatchAccessControlFiltering.java
plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaConfig.java
plugin/trino-opa/src/test/java/io/trino/plugin/opa/TestOpaResponseDecoding.java

Minor changes in OPA plugin

---

plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentContentSchemaProvider.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentModule.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentSchemaRegistryTableDescriptionSupplier.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestConfluentContentSchemaProvider.java

Rename AvroConfluentContentSchemaProvider 

---

core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedStageExecution.java

`isAnyTaskBlocked` is called frequently during scheduling.
Avoid calling `ImmutableList.copyOf` when checking if blocked.
```markdown
```

Avoid copying tasks when checking blocked

---

docs/src/main/sphinx/admin/event-listeners-kafka.md

There is a little typo in the kafka-event-listener configuration example which leads to errors when copy-pasting the config into trino deployments leading to trino failing with following exception
```
Configuration property 'kafka.config.resources' was not used
```
Got my trino up and running and producing to kafka after setting it to the property key listed in the documentation below

fixed typo in documentation for kafka-event-listener example "kafka.config.resources"

---

core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryDetails.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryJson.tsx

Add Query JSON page to the preview UI. Partially addressing https://github.com/trinodb/trino/issues/22697
Retains the same functionality as the existing web UI, enhanced with the updated layout, design, and user experience.
```markdown
* Add query JSON page to the Preview Web UI. ({issue}`26319`)
```

Add query JSON page to Preview Web UI

---

core/trino-main/src/main/java/io/trino/operator/project/GeneratedPageProjection.java
core/trino-main/src/main/java/io/trino/sql/gen/PageFunctionCompiler.java
core/trino-main/src/main/java/io/trino/sql/gen/PageProjectionWork.java

Avoid constructing new PageProjectionWork object per page
```markdown
```

Simplify compiled page projection

---

core/trino-main/src/main/java/io/trino/operator/HashAggregationOperator.java
core/trino-main/src/main/java/io/trino/operator/aggregation/AggregatorFactory.java
core/trino-main/src/main/java/io/trino/operator/aggregation/builder/InMemoryHashAggregationBuilder.java

Avoids eager, unnecessary creation of aggregator instances just to determine their output type inside of the HashAggregationOperator constructor. 

Cleanup HashAggregationOperator types

---

core/trino-web-ui/src/main/resources/webapp-preview/package-lock.json
core/trino-web-ui/src/main/resources/webapp-preview/package.json
core/trino-web-ui/src/main/resources/webapp-preview/src/api/webapp/api.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryDetails.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryLivePlan.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/flow/HelpMessage.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/flow/OperatorNode.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/flow/PlanFragmentNode.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/flow/RemoteExchangeNode.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/flow/flowUtils.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/components/flow/layout.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/components/flow/types.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/utils/utils.ts

Add Query live plan flow page to the preview UI. Partially addressing https://github.com/trinodb/trino/issues/22697
Retains the same functionality as the existing web UI, enhanced with the updated layout, design, and user experience.
**Additional features not available in the current UI**
* Draggable stage nodes
* Toggle for horizontal and vertical auto layout
```markdown
* Add query live plan flow page to Preview Web UI. ({issue}`26392`)
```

Add query live plan flow page to Preview Web UI

---

lib/trino-parquet/src/main/java/io/trino/parquet/ParquetMetadataConverter.java
pom.xml

Update Parquet to 1.16.0

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java

This fixes flaky `testCreateTableWithHeaderAndFooter(CSV)` and `testCreateTableWithHeaderAndFooterForCsv()`. 
https://github.com/trinodb/trino/actions/runs/17478884174/job/49645203991
```
Error:  io.trino.plugin.hive.TestHiveConnectorTest.testCreateTableWithHeaderAndFooterForCsv -- Time elapsed: 0.011 s <<< ERROR!
io.trino.testing.QueryFailedException: line 1:1: Table 'hive.tpch.csv_table_skip_header' already exists
at io.trino.testing.AbstractTestingTrinoClient.execute(AbstractTestingTrinoClient.java:138)
at io.trino.testing.DistributedQueryRunner.executeInternal(DistributedQueryRunner.java:586)
at io.trino.testing.DistributedQueryRunner.executeWithPlan(DistributedQueryRunner.java:575)
at io.trino.testing.QueryAssertions.assertDistributedUpdate(QueryAssertions.java:106)
at …
```

Add random suffix to fix flaky Hive tests

---

docs/src/main/sphinx/connector/iceberg.md

Follow-up of https://github.com/trinodb/trino/pull/22340
The `sql-data-management` fragment contains TRUNCATE:
https://github.com/trinodb/trino/blob/4f50ae66de7af866c8ad354499a2503c93027be5/docs/src/main/sphinx/language/sql-support.md?plain=1#L85-L92

Document TRUNCATE statement in Iceberg

---

core/trino-web-ui/src/main/resources/webapp-preview/package-lock.json
core/trino-web-ui/src/main/resources/webapp-preview/src/api/webapp/api.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryOverview.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryStageCard.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/utils/utils.ts

Add query stages view to the preview UI. Partially addressing https://github.com/trinodb/trino/issues/22697
Retains the same functionality as the existing web UI, enhanced with the updated layout, design, and user experience.
```markdown
* Add query stages view to Preview Web UI. ({issue}`26440`)
```

Add query stages view to Preview Web UI

---

core/trino-main/src/main/java/io/trino/execution/executor/timesharing/TimeSharingTaskHandle.java

Keeping the shared variable here to have protected access makes it possible that its values get mutated outside of this class without proper synchronization

Change the visibility of shared variables in TimeSharingTaskHandle from protected to private

---

docs/src/main/sphinx/connector/exasol.md

Only Exasol documentation uses `eval-rst` hack. The generated image after this change:

Avoid eval-rst in Exasol documentation

---

docs/src/main/sphinx/connector/mongodb.md
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientConfig.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSource.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoPageSourceProvider.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/TypeUtils.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoConnectorTest.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoSession.java

Currently, reading mixed-type array type in Mongo fails with message:
```
ClassCastException on nested arrays: ArrayList cannot be cast to BSON Document
```
Reproduce by below test:
```
void testMongoMixedTypeArrayType()
{
String schema = getSession().getSchema().orElseThrow();
String table = "test_mixed_array_" + randomNameSuffix();
MongoDatabase db = client.getDatabase(schema);
db.createCollection(table);
db.getCollection(table)
.insertOne(new Document("mixed_array_col", ImmutableList.of(1, "two", 3.0, new Document("nested_arr", ImmutableList.of(4, 5)))));
assertThat(query("SHOW COLUMNS FROM " + table))
.skippingTypesCheck()
.matches("VALUES " +
"('mixed_array_col', 'row(_pos1 bigint, _pos2 varchar, _pos3 double, _pos4 row(nested_arr array(bigint)))', '', '')");
assertThat(query("SELECT …
```

Fix reading mixed-type array in Mongodb

---

core/trino-web-ui/src/main/resources/webapp-preview/src/api/webapp/api.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryDetails.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryLivePlan.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryStagePerformance.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/flow/HelpMessage.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/flow/StageOperatorNode.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/flow/StagePipelineNode.tsx
core/trino-web-ui/src/main/resources/webapp-preview/src/components/flow/flowUtils.ts
core/trino-web-ui/src/main/resources/webapp-preview/src/components/flow/layout.ts

Add Query stage performance flow page to the preview UI. Partially addressing https://github.com/trinodb/trino/issues/22697
Retains the same functionality as the existing web UI, enhanced with the updated layout, design, and user experience.
**Additional features not available in the current UI**
* Draggable stage nodes
* Toggle for horizontal and vertical auto layout
```markdown
* Add query live plan flow page to Preview Web UI. ({issue}`26610`)
```

Add query stage performance flow to Preview Web UI

---

core/trino-main/src/main/java/io/trino/operator/PageSourceOperator.java
core/trino-main/src/main/java/io/trino/operator/ScanFilterAndProjectOperator.java
core/trino-main/src/main/java/io/trino/operator/TableScanOperator.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java

Current code was missing updating metrics like physical input size and physical input read time when the page source produces only a null Page. 
This scenario is encountered when splits are pruned by predicate pushdown to parquet
```markdown
* Fix physical input metrics in output of EXPLAIN ANALYZE. ({issue}`26637`)
```

Collect page source metrics before finish

---

docs/src/main/sphinx/connector/bigquery.md

-----
This pull request updates the documentation for the BigQuery connector to include the **`bigquery.arrow-serialization.max-allocation`** property. This property allows users to increase the maximum memory usage for the Apache Arrow buffer allocator, which can help prevent memory leaks and out-of-memory errors.
-----
The issue is linked to a bug in the BigQuery connector's Arrow serialization process. Despite ample memory resources on the worker nodes, the Arrow allocator would fail to reserve memory, leading to an `OutOfMemoryException`. Disabling Arrow serialization (`bigquery.arrow-serialization.enabled=false`) resolved the issue but sacrificed performance. This fix allows us to keep the performance benefits of Arrow serialization while preventing memory allocation failures.
Fixes …

Document `bigquery.arrow-serialization.max-allocation` property

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadRowsHelper.java

The existing log statement in `ReadRowsHelper` logs the full `ReadRowsResponse` object, which can contain large and unreadable serialized Arrow batches. This clutters the logs and makes debugging difficult.
Example:
```
2025-03-25T15:37:20.578+0900	DEBUG	bigquery-bigquery-5	io.trino.plugin.bigquery.ReadRowsHelper	ReadRowsResponse from BigQuery: stats {
progress {
at_response_end: 0.001469222130253911
}
}
arrow_record_batch {
serialized_record_batch: "\377\377\377\377\360\a\000\000\024\000\000\000\000\000\000\000\f\000\030\000\006\000\005\000\b\000\f\000\f\000\000\000\000\003\004\000\034\000\000\0000)\001\000\000\000\000\000\000\000\000\000\f\000\036\000\020\000\004\000\b\000\f\000\f\000\000\000\320\005\000\000$\000\000\000\030\000\000\000\300\003\000\000\000\000\000\000\000\000\000\000\000 …
```

Improve readability of ReadRowsHelper debug log

---

core/trino-main/src/main/java/io/trino/memory/LocalMemoryManager.java
core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java

Verify that Trino has access to UnixOperatingSystemMXBean

---

.github/workflows/ci.yml

We will soon move to JDK 25 in the runtime so we can start testing with JDK 26.
```markdown
```

Switch additional testing to JDK 26

---

lib/trino-filesystem/src/main/java/io/trino/filesystem/cache/CachingHostAddressProvider.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/cache/ConsistentHashingHostAddressProvider.java
lib/trino-filesystem/src/main/java/io/trino/filesystem/cache/DefaultCachingHostAddressProvider.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeSplitManager.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitSource.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java

Allows multiple splits from a file to be scheduled on different nodes to reduce chances of a hotspot in the cluster
```markdown
* Improve uniformity of load distribution among workers when filesystem caching is enabled. ({issue}`26672`)
```

Improve distribution of splits with filesystem caching

---

core/trino-web-ui/src/main/resources/webapp/assets/js/timeline.js

Fix UI timeline aggregation The `tasks` array was always empty causing the timeline to render blank. 
Bug introduced by this PR: https://github.com/trinodb/trino/pull/26113 - It hasn’t been included in a release yet so end users are not affected. However, without this fix, the issue will appear in the next 477 release.
This happened because we incorrectly called:
```
tasks.push.apply(stage.tasks)
```
which used the wrong receiver and didn’t append anything. The fix switches to:
```
Array.prototype.push.apply(tasks, stage.tasks)
```
so that tasks is properly populated with the combined list. …

Fix UI splits timeline aggregation

---

core/trino-web-ui/src/main/resources/webapp-preview/src/components/QueryDetails.tsx

Currently the query details page (Preview UI) always keep the same URI across all tabs. As a result, refreshing the page would reset the view to the first tab.
This PR updates the implementation so that the active tab is encoded in the URL. This enables:
* Preserving the correct tab after a page refresh
* Sharing direct links to specific tabs
Example URL with a new `tab` parameter in the URL:
```
http://localhost:8080/ui/preview#/queries/20250924_200340_00000_ypahm?tab=livePlan
```
Active tab state is now synced with the URL by using `useSearchParams` hook in`react-router-dom`.
( ) Release notes are required, with the following suggested …

Preserve the active tab in the URL on the query details page in the preview UI

---

docs/src/main/sphinx/release.md
docs/src/main/sphinx/release/release-477.md

Assemble the release notes for the upcoming Trino 477 release.
See https://github.com/trinodb/trino/pulls?q=is%3Apr+is%3Aclosed+milestone%3A477
* #25892 ✅ rn ✅ docs
* #25948 ✅ rn ✅ docs
* #25951 ✅ rn ✅ docs
* #25927 ✅ rn ✅ docs
* #25946 ✅ rn ✅ docs
* #25944 ✅ rn ✅ docs
* #25945 ✅ rn ✅ docs
* #25949 ✅ rn ✅ docs
* #25959 ✅ rn ✅ docs
* #25954 ✅ rn ✅ docs
* #25962 ✅ rn ✅ docs
* #25964 ✅ rn ✅ docs
* #25965 ✅ rn ✅ docs
* #25956 ✅ rn ✅ docs
* #25971 ✅ rn ✅ docs
* …

Add Trino 477 release notes

---

core/trino-main/src/main/java/io/trino/sql/planner/SplitSourceFactory.java

The constraint passed to connector split factory does not contain the ConnectorExpression, which limits the ability to perform split time filtering.

Add full connector expression to split factory constraint

---

core/trino-main/src/main/java/io/trino/transaction/InternalConnector.java
core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
core/trino-main/src/test/java/io/trino/sql/planner/TestMaterializedViews.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/connector/Connector.java
plugin/trino-ai-functions/src/main/java/io/trino/plugin/ai/functions/AiConnector.java
plugin/trino-faker/src/main/java/io/trino/plugin/faker/FakerConnector.java
plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxConnector.java
plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxConnectorFactory.java
plugin/trino-jmx/src/main/java/io/trino/plugin/jmx/JmxPeriodicSampler.java
plugin/trino-loki/src/main/java/io/trino/plugin/loki/LokiConnector.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientModule.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoConnector.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchConnector.java
testing/trino-testing/src/main/java/io/trino/testing/tpch/IndexedTpchConnectorFactory.java
testing/trino-tests/src/test/java/io/trino/execution/AbstractTestCoordinatorDynamicFiltering.java
testing/trino-tests/src/test/java/io/trino/execution/TestBeginQuery.java

This ensures that at least every Connector will call LifeCycleManager.stop()
which is important because every Bootstrap creates one LifeCycleManager
which registers itself with the shutdown hook creating a shutdown Thread.
```markdown
```

Require implementing shutdown method on a Connector 

---

plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseTypeMapping.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestAltinityClickHouseTypeMapping.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestAltinityLatestClickHouseTypeMapping.java

Validate out of range DateTime value in clickhouse connector

Validate out of range DateTime value in clickhouse connector

---

plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java

It's currently placed inside an unrelated decimal `TestTable` block. 

Move assertions in BaseSqlServerConnectorTest

---

plugin/trino-singlestore/pom.xml
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/SingleStoreQueryRunner.java
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestingSingleStoreServer.java

The initialization takes about 2 minutes. It would be nice to allow reusing a container. 

Allow reusing SingleStore container

---

core/trino-main/src/main/java/io/trino/server/ExternalUriInfo.java

Injecting header as a String directly into the Jakarta's managed bean will use reflection to convert to desired type. Injecting managed HttpHeaders avoid that kind of a conversion.
```markdown
```

Avoid calling TypeConverters when injecting a header

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/procedure/TestIcebergAddFilesProcedure.java

```markdown
* Fix failure about number of column mismatch when executing `add_files_from_table` procedure. ({issue}`26774`)
```

Fix add_files_from_table due to wrong column count condition

---

docs/src/main/sphinx/security/group-mapping.md

Removed trailing whitespace, added defaults to ldap group-mapping.md
( x ) This is not user-visible or is docs only, and no release notes are required.

Remove trailing whitespace and add defaults to LDAP group-mapping docs

---

.github/dependabot.yml

Add dependabot for maven dependencies

---

.github/dependabot.yml

It's not really useful as usually you need to resolve conflicts one by one so having updates batched makes more work then merging individual conflict-free updates.
```markdown
```

Remove dependency group updates

---

client/trino-client/src/main/java/io/trino/client/DisallowLocalRedirectInterceptor.java
client/trino-client/src/main/java/io/trino/client/uri/ConnectionProperties.java
client/trino-client/src/main/java/io/trino/client/uri/HttpClientFactory.java
client/trino-client/src/main/java/io/trino/client/uri/PropertyName.java
client/trino-client/src/main/java/io/trino/client/uri/TrinoUri.java
client/trino-client/src/test/java/io/trino/client/TestDisallowLocalRedirectInterceptor.java

This is my first PR for Trino. We are using this patch in production to prevent the attack described below. Offering this upstream if you guys want it.
The driver will currently follow any redirects from the server. This can cause problems. For example when running on AWS there is a service running on a link-local address which provides IAM credentials (IMDS). If the server redirects to this address, the driver will return an error message with the IAM credentials.
Note: I emailed the signed CLA form last week.

Add redirect guards

---

core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/QueryId.java

Name is always `queryId`
```markdown
```

Revert SPI change

---

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
docs/src/main/sphinx/admin/fault-tolerant-execution.md

I most cases it is better if single cluster only runs queries with specific retry policy matching cluster configuration.
This PR adds new configuration property `allowed-retry-policies` so this can be enforced.
```markdown
* Add `allowed-retry-policies` configuration property to specify which retry policies can be selected by user
```

Allow specifying list of allowed retry policies

---

core/trino-main/src/main/java/io/trino/operator/output/PagePartitioner.java
core/trino-main/src/main/java/io/trino/operator/output/PositionsAppender.java
core/trino-main/src/main/java/io/trino/operator/output/PositionsAppenderPageBuilder.java
core/trino-main/src/main/java/io/trino/operator/output/RowPositionsAppender.java
core/trino-main/src/main/java/io/trino/operator/output/TypedPositionsAppender.java
core/trino-main/src/main/java/io/trino/operator/output/UnnestingPositionsAppender.java
core/trino-main/src/test/java/io/trino/operator/output/TestPagePartitioner.java
core/trino-main/src/test/java/io/trino/operator/output/TestPositionsAppender.java
core/trino-spi/pom.xml
core/trino-spi/src/main/java/io/trino/spi/block/RowBlock.java

Adds special case handling for single partition output in `PagePartitioner` such that partition calculations can be skipped when all rows will necessarily go to a single output partition. This improves performance for small queries or when running on small clusters to avoid the work of computing output page partitions.

Add fast path for single partition in PagePartitioner
