trinodb/trino

- .travis.yml
Approved by @kokosing in https://github.com/prestodb/presto/pull/12250
> Use Xenial environment on Travis

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcTypeHandle.java
- presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestingJdbcTypeHandle.java
Reviewed by @kokosing and @electrum under https://github.com/prestodb/presto/pull/12232
> Add TYPE_NAME to JdbcTypeHandle

- presto-docs/src/main/sphinx/language.rst
- presto-docs/src/main/sphinx/language/timestamp.rst
- presto-docs/src/main/sphinx/language/types.rst
Approved by @electrum under https://github.com/prestodb/presto/pull/12146
> Add section explaining legacy and new timestamp

- presto-main/src/main/java/io/prestosql/operator/aggregation/ParametricAggregation.java
Fix access to ParametricAggregation fields
> Fix access to ParametricAggregation fields

- presto-accumulo/src/main/java/io/prestosql/plugin/accumulo/AccumuloMetadata.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraMetadata.java
- presto-example-http/src/main/java/io/prestosql/plugin/example/ExampleMetadata.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
- presto-jmx/src/main/java/io/prestosql/plugin/jmx/JmxMetadata.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaMetadata.java
- presto-local-file/src/main/java/io/prestosql/plugin/localfile/LocalFileMetadata.java
- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoMetadata.java
- presto-redis/src/main/java/io/prestosql/plugin/redis/RedisMetadata.java
- presto-spi/src/main/java/io/prestosql/spi/connector/SchemaTablePrefix.java
- presto-tpcds/src/main/java/io/prestosql/plugin/tpcds/TpcdsMetadata.java
- presto-tpch/src/main/java/io/prestosql/plugin/tpch/TpchMetadata.java
Prefer SchemaTablePrefix#getSchema to create optional schema name
>  Use Optional for nullable fields in SchemaTablePrefix 

- presto-hive/src/main/java/io/prestosql/plugin/hive/RetryDriver.java
Add suppressed exceptions to exception that is thrown
> Add suppressed exceptions to exception that is thrown

- presto-main/src/main/java/io/prestosql/ExceededMemoryLimitException.java
- presto-main/src/main/java/io/prestosql/memory/DefaultQueryContext.java
- presto-main/src/main/java/io/prestosql/memory/LegacyQueryContext.java
- presto-main/src/test/java/io/prestosql/memory/TestMemoryTracking.java
- presto-main/src/test/java/io/prestosql/operator/TestHashAggregationOperator.java
- presto-main/src/test/java/io/prestosql/operator/TestOrderByOperator.java
- presto-main/src/test/java/io/prestosql/operator/TestWindowOperator.java
Code extracted from https://github.com/prestodb/presto
ref https://github.com/prestodb/presto/pull/12170
> Report top memory consumers when local memory limit is exceeded

- presto-password-authenticators/src/main/java/io/prestosql/plugin/password/LdapAuthenticator.java
- presto-product-tests/conf/docker/common/compose-commons.sh
Approved by @electrum at https://github.com/prestodb/presto/pull/11714
> Support LDAP with anonymous bind disabled

- presto-hive/src/test/java/io/prestosql/plugin/hive/HiveQueryRunner.java
> Further reduce logging

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
Add support for getTableStatistics to base-jdbc connector
> Add support for getTableStatistics to base-jdbc connector

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcSplit.java
- presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcSplit.java
Fix JsonProperty for additionalPredicate in JdbcSplit
> Fix JsonProperty for additionalPredicate in JdbcSplit

- presto-docs/src/main/sphinx/connector/kafka.rst
- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-301.rst
Resolves https://github.com/prestosql/presto/issues/22
> Add 301 release notes

- presto-docs/src/main/sphinx/security/ldap.rst
Approved by @electrum at https://github.com/prestodb/presto/pull/12184
> Document note about LDAPS and JDK Upgrade

- presto-docs/src/main/sphinx/security/server.rst
- presto-main/src/main/java/io/prestosql/server/security/KerberosConfig.java
- presto-main/src/test/java/io/prestosql/server/security/TestKerberosConfig.java
Follow-up to https://github.com/prestosql/presto/pull/146
Thanks @martint for spotting this.
> Fix inconsistencies in hostname configuration property for Kerberos auth

- presto-cli/src/main/java/io/prestosql/cli/ClientOptions.java
- presto-cli/src/test/java/io/prestosql/cli/TestClientOptions.java
Motivation
PR for to fix #56
Changes
Add traceToken and pass it to ClientSession constructor in ClientOptions.java to support CLI option --trace-token.
Add corresponding test case.
> Add CLI option --trace-token to set the trace token

- presto-docs/src/main/sphinx/connector/hive.rst
Extracted-From: https://github.com/prestodb/presto/pull/12218
> Document hive.recursive-directories

- presto-main/src/main/java/io/prestosql/operator/scalar/ArrayDistinctFromOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/annotations/ParametricScalarImplementation.java
- presto-main/src/test/java/io/prestosql/operator/TestAnnotationEngineForScalars.java
Approved by @wenleix at https://github.com/prestodb/presto/pull/12065
> Allow function implementation choices to have different dependencies

- presto-docs/src/main/sphinx/sql/select.rst
> Document LATERAL join

- presto-main/src/main/java/io/prestosql/connector/informationSchema/InformationSchemaMetadata.java
- presto-main/src/main/java/io/prestosql/connector/informationSchema/InformationSchemaPageSourceProvider.java
- presto-main/src/main/java/io/prestosql/metadata/MetadataUtil.java
- presto-tests/src/test/java/io/prestosql/tests/TestLocalQueries.java
Add hidden columns to information_schema tables to make Hue happy
> Add hidden columns to information_schema tables to make Hue happy

- presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q45.plan.txt
- presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q58.plan.txt
- presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q83.plan.txt
- presto-main/src/main/java/io/prestosql/cost/CostCalculatorWithEstimatedExchanges.java
- presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/DetermineJoinDistributionType.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/DetermineSemiJoinDistributionType.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PlanNodeWithCost.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/ReplicateSemiJoinInDelete.java
- presto-main/src/main/java/io/prestosql/sql/planner/plan/SemiJoinNode.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/JoinMatcher.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/PlanMatchPattern.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/SemiJoinMatcher.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestDetermineSemiJoinDistributionType.java
Ref https://github.com/prestodb/presto/pull/12050
> Use cost estimates to choose semi-join distribution type

- presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushLimitThroughOuterJoin.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/QueryCardinalityUtil.java
- presto-main/src/main/java/io/prestosql/sql/planner/plan/Patterns.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/LimitMatcher.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/Matcher.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/PlanMatchPattern.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPushLimitThroughOuterJoin.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/test/PlanBuilder.java
Ref https://github.com/prestodb/presto/pull/11971
> Add PushLimitThroughOuterJoin rule

- presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q04.plan.txt
- presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q11.plan.txt
- presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q49.plan.txt
- presto-benchto-benchmarks/src/test/resources/sql/presto/tpcds/q74.plan.txt
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/AddExchanges.java
- presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestAddExchanges.java
- presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestAddExchangesPlans.java
Extracted-From: https://github.com/prestodb/presto/pull/11957
> Add exchange for union with TableScan and Values

- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/ObjectIdFunctions.java
- presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoIntegrationSmokeTest.java
Fixes https://github.com/prestosql/presto/issues/139
> Implement IS DISTINCT FROM for MongoDB ObjectId

- presto-accumulo/src/main/java/io/prestosql/plugin/accumulo/conf/AccumuloTableProperties.java
- presto-accumulo/src/main/java/io/prestosql/plugin/accumulo/model/Row.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraPageSink.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraTokenSplitManager.java
- presto-client/src/main/java/io/prestosql/client/ClientTypeSignature.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/PartitionUpdate.java
- presto-main/src/main/java/io/prestosql/operator/aggregation/AggregationFromAnnotationsParser.java
- presto-main/src/main/java/io/prestosql/operator/aggregation/AggregationMetadata.java
- presto-main/src/main/java/io/prestosql/operator/project/MergingPageOutput.java
- presto-ml/src/main/java/io/prestosql/plugin/ml/ModelUtils.java
- presto-ml/src/main/java/io/prestosql/plugin/ml/StringClassifierAdapter.java
- presto-parquet/src/main/java/io/prestosql/parquet/reader/ParquetReader.java
- presto-spi/src/main/java/io/prestosql/spi/connector/InMemoryRecordSet.java
- presto-spi/src/main/java/io/prestosql/spi/type/TimeZoneKey.java
Fixes some bugs introduced in https://github.com/prestosql/presto/pull/214 (thanks @electrum for spotting this!) and some more.
> Fix format in checkArgument/checkState calls

- presto-jdbc/pom.xml
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcConnection.java
> Add test to verify extra credential delivery to ConnectorIdentity

- presto-main/src/main/java/io/prestosql/server/ServerMainModule.java
Fixes https://github.com/prestosql/presto/issues/239
> Disable Airlift admin servlet

- presto-proxy/src/main/java/io/prestosql/proxy/ProxyModule.java
Same as e9c217ae4a3e1a3c73be5bcd417bb5cf1384eaca, this time for Presto
Proxy.
Related to https://github.com/prestosql/presto/pull/260, https://github.com/prestosql/presto/issues/239
> Disable Airlift admin servlet in Proxy

- presto-main/src/main/resources/webapp/vendor/d3/LICENSE.txt
- presto-main/src/main/resources/webapp/vendor/d3/d3-3.3.4.js
This fixes broken timeline page
> Restore d3 vendor library

- presto-accumulo/src/main/java/io/prestosql/plugin/accumulo/metadata/AccumuloTable.java
- presto-accumulo/src/main/java/io/prestosql/plugin/accumulo/model/AccumuloColumnConstraint.java
- presto-accumulo/src/main/java/io/prestosql/plugin/accumulo/model/AccumuloColumnHandle.java
- presto-accumulo/src/main/java/io/prestosql/plugin/accumulo/model/AccumuloTableHandle.java
- presto-blackhole/src/main/java/io/prestosql/plugin/blackhole/BlackHoleSplit.java
- presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchPlugin.java
- presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/ElasticsearchQueryRunner.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/PermissionMetadata.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduModule.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduPageSourceProvider.java
- presto-main/src/main/java/io/prestosql/connector/system/SystemConnectorModule.java
- presto-main/src/main/java/io/prestosql/operator/OperatorStats.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/Field.java
- presto-memory/src/main/java/io/prestosql/plugin/memory/MemoryInsertTableHandle.java
- presto-memory/src/main/java/io/prestosql/plugin/memory/MemoryOutputTableHandle.java
- presto-memory/src/main/java/io/prestosql/plugin/memory/MemoryPagesStore.java
- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoClientConfig.java
- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoPageSource.java
Ref https://github.com/prestodb/presto/pull/12370 except
- Add missing throw statement (already fixed on our side)
- Rename test resources
- Update deprecated use of catchingAsync (already fixed on our side)
and with some additions
> Minor code refactors

- presto-parquet/src/main/java/io/prestosql/parquet/reader/MetadataReader.java
Cherry-picking https://github.com/prestodb/presto/pull/11395
@dain Kindly ask a review!
> Prefetch Parquet footer to reduce the number of read calls

- presto-docs/src/main/sphinx/connector/hive.rst
- presto-hive/src/main/java/io/prestosql/plugin/hive/s3/HiveS3Config.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3ConfigurationInitializer.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/s3/MockAmazonS3.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestHiveS3Config.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestPrestoS3FileSystem.java
> Allow PrestoS3FileSystem to support skipping Glacier files

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
Limit access to ThriftMetastoreUtil methods
> Limit access to ThriftMetastoreUtil methods

- presto-main/src/main/java/io/prestosql/server/PrestoServer.java
- presto-main/src/main/java/io/prestosql/server/ServerConfig.java
- presto-main/src/main/java/io/prestosql/server/ServerMainModule.java
- presto-main/src/test/java/io/prestosql/server/TestServerConfig.java
- presto-tests/src/main/java/io/prestosql/tests/DistributedQueryRunner.java
- presto-tests/src/main/java/io/prestosql/tests/StandaloneQueryRunner.java
Datasources property in ServerConfig is depricated and has not been in use for quite
a long time.
> Remove deprecated datasources config property

- presto-rcfile/pom.xml
- presto-rcfile/src/test/java/io/prestosql/rcfile/TestFullRcFileReader.java
They take less than a minute to execute with a single thread.
> Always run full RCFile tests

- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraClientConfig.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraMetadata.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraPageSink.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraPageSinkProvider.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraRecordCursor.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraType.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/util/CassandraCqlUtils.java
- presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraType.java
- presto-product-tests/conf/presto/etc/catalog/cassandra.properties
- presto-product-tests/src/main/java/io/prestosql/tests/cassandra/DataTypesTableDefinition.java
- presto-product-tests/src/main/java/io/prestosql/tests/cassandra/TestInsertIntoCassandraTable.java
- presto-product-tests/src/main/java/io/prestosql/tests/cassandra/TestSelect.java
Continuation of https://github.com/prestodb/presto/pull/7123
> Support smallint, tinyint, date type of Cassandra

- presto-docs/src/main/sphinx/connector/cassandra.rst
Sorry, forgot to update the document on https://github.com/prestosql/presto/pull/141
> Document Cassandra smallint, tinyint and date types

- presto-parquet/src/main/java/io/prestosql/parquet/ParquetEncoding.java
fix https://github.com/prestosql/presto/issues/323
@electrum @ryanrupp
> Fix Parquet Encoding check with DELTA_BINARY_PACKED support INT64

- presto-main/src/main/java/io/prestosql/cost/SortStatsRule.java
- presto-main/src/main/java/io/prestosql/cost/StatsCalculatorModule.java
- presto-main/src/test/java/io/prestosql/cost/TestSortStatsRule.java
- presto-tests/src/test/java/io/prestosql/tests/TestTpchDistributedStats.java
Ref https://github.com/prestodb/presto/pull/12347
- just stats rule
- renamed test class
> Add SortNode stats rule

- .mvn/extensions.xml
> Use safe concurrent access to local Maven repository

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ConnectionFactory.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/DriverConnectionFactory.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcIdentity.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcPageSink.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcRecordCursor.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcSplitManager.java
- presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcClient.java
- presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcRecordSetProvider.java
- presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestingDatabase.java
- presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
- presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
- presto-redshift/src/main/java/io/prestosql/plugin/redshift/RedshiftClient.java
- presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java
Pass JdbcIdentity to DriverConnectionFactory#openConnection
> Pass JdbcIdentity to DriverConnectionFactory#openConnection

- presto-main/src/test/java/io/prestosql/operator/BenchmarkScanFilterAndProjectOperator.java
It is useful to benchmark future changes in
ScanFilterAndProjectOperator
> Add ScanFilterAndProjectOperator benchmark

- presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java
> Unhide join_max_broadcast_table_size session property

- presto-main/src/main/java/io/prestosql/eventlistener/EventListenerManager.java
Before the change, certain libraries cannot be used in an event
listener implementation.
Approved by @findepi at https://github.com/prestodb/presto/pull/11951
> Set ClassLoader when calling EventListenerFactory

- presto-docs/src/main/sphinx/overview/concepts.rst
Ref https://github.com/prestodb/presto/pull/12385
> Fix a typo in docs

- pom.xml
- presto-parquet/pom.xml
- presto-parquet/src/main/java/io/prestosql/parquet/ParquetReaderUtils.java
- presto-parquet/src/main/java/io/prestosql/parquet/dictionary/DictionaryReader.java
- presto-parquet/src/main/java/io/prestosql/parquet/dictionary/DoubleDictionary.java
- presto-parquet/src/main/java/io/prestosql/parquet/dictionary/FloatDictionary.java
- presto-parquet/src/main/java/io/prestosql/parquet/dictionary/IntegerDictionary.java
- presto-parquet/src/main/java/io/prestosql/parquet/dictionary/LongDictionary.java
- presto-parquet/src/main/java/io/prestosql/parquet/reader/MetadataReader.java
- presto-parquet/src/main/java/io/prestosql/parquet/reader/PrimitiveColumnReader.java
- presto-parquet/src/test/java/io/prestosql/parquet/TestTupleDomainParquetPredicate.java
Depends on https://github.com/prestosql/presto-hive-apache/pull/4
> Update to Parquet 1.10.1

- presto-main/src/main/java/io/prestosql/memory/LocalMemoryManager.java
- presto-main/src/test/java/io/prestosql/memory/TestLocalMemoryManager.java
- presto-main/src/test/java/io/prestosql/memory/TestNodeMemoryConfig.java
Ref https://github.com/prestodb/presto/pull/12407
> Unit tests for LocalMemoryManager

- presto-resource-group-managers/src/main/java/io/prestosql/plugin/resourcegroups/db/DbResourceGroupConfigurationManager.java
Before this commit, `configuredGroups` was a `ConcurrentHashMap`
containing `List` values. The values were being mutated without any
synchronization.
> Fix unsynchronized access to configuredGroups

- presto-docs/src/main/sphinx/functions/geospatial.rst
- presto-geospatial/src/main/java/io/prestosql/plugin/geospatial/GeoFunctions.java
- presto-geospatial/src/test/java/io/prestosql/plugin/geospatial/TestGeoFunctions.java
Ref https://github.com/prestodb/presto/pull/12304 (part of)
~Ref https://github.com/prestodb/presto/pull/12334~
> Add ST_Points spatial function

- pom.xml
Depends on https://github.com/prestosql/presto-hadoop-apache/pull/2
> Update to Hadoop 2.7.7

- presto-docs/src/main/sphinx/admin/resource-groups.rst
- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-305.rst
> Add 305 release notes

- presto-docs/src/main/sphinx/connector/kafka.rst
> Fix typo in Kafka document

- presto-main/src/main/java/io/prestosql/server/PrestoServer.java
`launcher`'s `--etc-dir` is optional and so `./etc` directory may not
exist.
> Fix server startup when Etc directory does not exist

- .travis.yml
Retry downloading of Maven wrapper in Travis CI
> Retry downloading of Maven wrapper in Travis CI

- presto-hive/src/test/java/io/prestosql/plugin/hive/HiveQueryRunner.java
Do not set catalog twice in hive tests
> Do not set catalog twice in hive tests

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-306.rst
Resolves https://github.com/prestosql/presto/issues/410
> Add 306 release notes

- presto-docs/src/main/sphinx/admin/properties.rst
The property was removed in 8c770dd2ac9225b40af19e9466f111641dff9888.
> Remove obsolete property documentation

- presto-main/src/main/java/io/prestosql/operator/aggregation/AggregationImplementation.java
- presto-main/src/main/java/io/prestosql/server/PluginManagerConfig.java
REFACTORING
It removes apparently unused codes in presto-main.
> Remove unused code in presto-main

- presto-main/src/main/java/io/prestosql/execution/SqlQueryExecution.java
The version number can be missing from the stacktrace, like in https://groups.google.com/d/msg/presto-users/n_x0hhlej1k/byOrK2BRAgAJ
> Embed version in SqlQueryExecution

- presto-docs/src/main/sphinx/functions/conditional.rst
- presto-main/src/main/java/io/prestosql/type/BigintOperators.java
- presto-main/src/main/java/io/prestosql/type/DoubleOperators.java
- presto-main/src/main/java/io/prestosql/type/IntegerOperators.java
- presto-main/src/main/java/io/prestosql/type/SmallintOperators.java
- presto-main/src/main/java/io/prestosql/type/TinyintOperators.java
- presto-main/src/test/java/io/prestosql/operator/scalar/TestFailureFunction.java
- presto-tests/src/main/java/io/prestosql/tests/AbstractTestQueries.java
>  Provide message for / by zero exception deterministically

- presto-main/src/main/java/io/prestosql/server/WebUiResource.java
> Use temporary redirect to /ui/

- presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/MergeLimitWithDistinct.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/RemoveAggregationInSemiJoin.java
- presto-main/src/main/java/io/prestosql/sql/planner/plan/AggregationNode.java
- presto-main/src/main/java/io/prestosql/sql/planner/plan/Patterns.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestLogicalPlanner.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestRemoveAggregationInSemiJoin.java
Fixes https://github.com/prestodb/presto/issues/7781
> Remove DISTINCT inside IN subquery expression

- pom.xml
Requires https://github.com/airlift/airlift/pull/717
Fixes https://github.com/prestosql/presto/issues/500, fixes https://github.com/prestosql/presto/issues/540
Supersedes https://github.com/prestosql/presto/pull/527
> Redirect from /ui to /ui/

- presto-main/src/main/java/io/prestosql/connector/ConnectorManager.java
From https://github.com/prestodb/presto/pull/12575
> Remove analyze properties when removing connector

- presto-spi/src/main/java/io/prestosql/spi/Page.java
Page has 3 AtomicLong.
It seems we forgot to update INSTANCE_SIZE on
1b5af9069b5e07841c01a950c0eb592ebdd6aa67.
> Fix the INSTANCE_SIZE of Page

- presto-docs/src/main/sphinx/connector/elasticsearch.rst
Extracted from https://github.com/prestosql/presto/blob/5d384b2f1d9f458270fa2aa29d93a984ac8dd8a3/presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchConnectorConfig.java
Other connectors look fine as far as I looked into.
> Fix wrong value in elasticsearch document

- pom.xml
This fixes a compatibility issue for Java 9+
> Update to jmxutils 1.21

- .travis.yml
- presto-base-jdbc/pom.xml
- presto-cassandra/pom.xml
- presto-hive/pom.xml
- presto-kafka/pom.xml
- presto-kudu/pom.xml
- presto-main/pom.xml
- presto-orc/pom.xml
- presto-redis/pom.xml
- presto-tests/pom.xml
Certain tests are "run on CI server", but Travis is our CI server, so
they should be run there.
> Enable all tests on Travis

- presto-jdbc/src/main/java/io/prestosql/jdbc/ColumnInfo.java
Extracted-from: https://github.com/prestodb/presto/pull/10843
> Fix varchar column display size

- presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/backup/HttpBackupModule.java
- presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/backup/HttpBackupStore.java
- presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/backup/TestHttpBackupStore.java
- presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/backup/TestingHttpBackupResource.java
Summary
---
* Fixes HTTP backup store implementation for Raptor
---
> Fix dependency injection for HttpBackupModule

- presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSinkProvider.java
When write to bucketed table, each bucket will ask metastore for
partition information.
Cherry https://github.com/prestodb/presto/pull/12667
> Cache hive metastore to improve writing bucketed table

- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Test count star for hive storage formats
> Test count star for hive storage formats

- presto-main/src/main/java/io/prestosql/server/security/KerberosAuthenticator.java
- presto-main/src/main/java/io/prestosql/server/security/KerberosConfig.java
- presto-main/src/main/java/io/prestosql/server/security/KerberosNameType.java
- presto-main/src/test/java/io/prestosql/server/security/TestKerberosConfig.java
Ref: https://github.com/airlift/airlift/pull/723
> Add krb5 name type config

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-309.rst
Closes https://github.com/prestosql/presto/issues/630
> Add 309 release notes

- presto-main/src/main/java/io/prestosql/execution/scheduler/NodeScheduler.java
Log node host name resolution exception
> Log node host name resolution exception

- presto-server-rpm/pom.xml
Fix formattiong in presto-server-rpm/pom.xml
> Fix formattiong in presto-server-rpm/pom.xml

- presto-product-tests/conf/docker/files/presto-launcher-wrapper.sh
- presto-product-tests/conf/docker/multinode/docker-compose.yml
- presto-product-tests/conf/presto/etc/multinode-master-jvm.config
- presto-product-tests/conf/presto/etc/multinode-master.properties
Might help with https://github.com/prestosql/presto/issues/683
> Reduce product tests' memory footprint

- presto-cli/src/main/java/io/prestosql/cli/StatusPrinter.java
> Make query time in cli consistent with QueryStats

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-310.rst
Fixes https://github.com/prestosql/presto/issues/678
> Add 310 release notes

- presto-main/src/main/java/io/prestosql/sql/planner/QueryPlanner.java
Simplifying Planner by removing optimization.
Resulting optimized plans are unchanged
due to MergeLimitWithSort Optimizer rule.
> Remove TopNNode creation from QueryPlanner

- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraClientConfig.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraClientModule.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraMetadata.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraPageSinkProvider.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraSession.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/NativeCassandraSession.java
- presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraClientConfig.java
- presto-docs/src/main/sphinx/connector/cassandra.rst
- presto-product-tests/conf/presto/etc/catalog/cassandra.properties
- presto-product-tests/src/main/java/io/prestosql/tests/cassandra/TestSelect.java
Related to https://github.com/prestosql/presto/issues/278
@findepi Could you give me some advice to improve test coverage about protocol version?
https://github.com/ebyhr/prestosql/commit/dedc98de603b8708db89d222fa0490ef394347cf#commitcomment-33046480
> Auto-discover Cassandra protocol version

- presto-main/src/test/java/io/prestosql/cost/TestCostCalculator.java
Added some test cases missing in the `TestCostCalculator`. Though these plan nodes have its stats rules, there are no test cases for cost calculation.
- `LimitNode`
- `FilterNode`
- `EnforceSingleRow`
> Add test cases for cost calculation rules

- presto-docs/src/main/sphinx/functions/array.rst
- presto-main/src/main/java/io/prestosql/metadata/FunctionRegistry.java
- presto-main/src/main/java/io/prestosql/operator/scalar/ArrayCombinationsFunction.java
- presto-main/src/test/java/io/prestosql/operator/scalar/TestArrayCombinationsFunction.java
Fixes https://github.com/prestosql/presto/issues/714
> Add array combinations function

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-311.rst
Closes https://github.com/prestosql/presto/issues/716
> Add 311 release notes

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcRecordCursor.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/QueryBuilder.java
- presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
- presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java
~not needed if https://github.com/prestosql/presto/issues/682~
> Reuse Connection when inspecting PostgreSQL array

- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
- presto-tpch/src/main/java/io/prestosql/plugin/tpch/TpchMetadata.java
- presto-tpch/src/main/java/io/prestosql/plugin/tpch/TpchRecordSetProvider.java
- presto-tpch/src/main/java/io/prestosql/plugin/tpch/TpchSplit.java
- presto-tpch/src/main/java/io/prestosql/plugin/tpch/TpchSplitManager.java
- presto-tpch/src/main/java/io/prestosql/plugin/tpch/TpchTableHandle.java
- presto-tpch/src/test/java/io/prestosql/plugin/tpch/TestTpchMetadata.java
Removes the TableLayout for TPCH connector. (#781)
> Remove table layouts from TPCH connector

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestRoles.java
Regression test for https://github.com/prestosql/presto/pull/791
> Test SHOW GRANTS

- pom.xml
- Improve reliability due to network-related issues when using Kerberos
- Improve initialization of JMX agent on Java 9+
> Update to airlift 0.182

- presto-main/src/main/java/io/prestosql/NotInTransactionException.java
- presto-main/src/main/java/io/prestosql/Session.java
- presto-main/src/main/java/io/prestosql/transaction/InMemoryTransactionManager.java
- presto-main/src/test/java/io/prestosql/execution/TestCommitTask.java
Code is more readable with a typed exception.
> Add NotInTransactionException

- presto-client/src/main/java/io/prestosql/client/ClientStandardTypes.java
- presto-client/src/main/java/io/prestosql/client/FixJsonDataUtils.java
- presto-client/src/test/java/io/prestosql/client/TestFixJsonDataUtils.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcResultSet.java
> Fix decoding of UUID type in CLI and JDBC driver

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-313.rst
> Add 313 release notes

- presto-main/src/test/java/io/prestosql/operator/scalar/AbstractTestRegexpFunctions.java
- presto-main/src/test/java/io/prestosql/operator/scalar/TestJoniRegexpFunctions.java
- presto-main/src/test/java/io/prestosql/operator/scalar/TestRe2jRegexpFunctions.java
- presto-main/src/test/java/io/prestosql/tests/LogTestDurationListener.java
- presto-main/src/test/resources/META-INF/services/org.testng.ITestNGListener
based on https://github.com/prestosql/presto/pull/789
> Long test hangs

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestInsertIntoHiveTable.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestTextFileHiveTable.java
Related to https://github.com/prestosql/presto/pull/845 Let me separate PR.
> Disable insert into Hive table with skip property

- pom.xml
Fixes rare issue when deserializing QuantileDigest instances
> Update airlift to 0.183

- presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
- presto-tests/src/main/java/io/prestosql/tests/AbstractTestDistributedQueries.java
Add test coverage for SHOW CREATE VIEW
> Add test coverage for SHOW CREATE VIEW

- presto-orc/src/main/java/io/prestosql/orc/StripeReader.java
Fix for #921 , changing key from `StreamId` to `Integer`
> Fix ORC Bloom Filter #921

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveBucketedTables.java
- presto-product-tests/src/main/java/io/prestosql/tests/utils/TableDefinitionUtils.java
Add product-tests for bucketed hive tables
> Add product-tests for bucketed hive tables

- presto-local-file/src/main/java/io/prestosql/plugin/localfile/LocalFileConnector.java
Add missing requireNonNull for `recordSetProvider` of LocalFileConnector like other connectors.
> Add missing requireNonNull to LocalFileConnector

- presto-main/src/main/java/io/prestosql/operator/OperatorContext.java
- add `getNestedOperatorStats` to the list of concurrently invoked
methods
- add an intro sentence, so that the javadoc is a real javadoc
> Update OperatorContext javadoc

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveConnectorFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSplitManager.java
- presto-main/src/main/java/io/prestosql/connector/ConnectorContextInstance.java
- presto-main/src/main/java/io/prestosql/connector/ConnectorManager.java
- presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
- presto-main/src/main/java/io/prestosql/testing/TestingConnectorContext.java
- presto-main/src/main/java/io/prestosql/version/EmbedVersion.java
- presto-spi/src/main/java/io/prestosql/spi/VersionEmbedder.java
- presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorContext.java
Rationale: https://github.com/prestosql/presto/issues/979
> Embed version in BackgroundHiveSplitLoader

- presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/ImplementExceptAsUnion.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/ImplementIntersectAsUnion.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/SetOperationNodeTranslator.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/ImplementIntersectAndExceptAsUnion.java
- presto-main/src/main/java/io/prestosql/sql/planner/plan/Patterns.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestImplementExceptAsUnion.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestImplementIntersectAsUnion.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/test/PlanBuilder.java
> Migrate ImplementIntersectAndExceptAsUnion to rule

- presto-hive-hadoop2/bin/common.sh
- presto-product-tests/bin/run_on_docker.sh
Do not check status of processes on non existing container
> Do not check status of processes on non existing container

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveTransactionManager.java
> Remove extra constructor

- presto-docs/src/main/sphinx/sql/select.rst
Docs for https://github.com/prestosql/presto/pull/1017
Issue: https://github.com/prestosql/presto/issues/875
> Update documentation for SELECT

- presto-main/src/test/java/io/prestosql/operator/BenchmarkUnnestOperator.java
> Add benchmark for UnnestOperator

- .travis.yml
- presto-product-tests/bin/product-tests-suite-1.sh
- presto-product-tests/bin/product-tests-suite-2.sh
- presto-product-tests/bin/product-tests-suite-3.sh
Extracted from https://github.com/prestosql/presto/pull/973 so it can be merged earlier.
> Extract product tests definitions from .travis.yml

- presto-product-tests/conf/docker/multinode/docker-compose.yml
- presto-product-tests/conf/presto/etc/multinode-master-jvm.config
- presto-product-tests/conf/presto/etc/multinode-worker-jvm.config
> Fix multinode product tests stability

- presto-docs/src/main/sphinx/connector/hive.rst
> Add section on HDFS permissions to Hive connector docs

- presto-main/src/main/java/io/prestosql/operator/scalar/annotations/ParametricScalarImplementation.java
- presto-main/src/main/java/io/prestosql/operator/scalar/annotations/ScalarFromAnnotationsParser.java
Instance method is also allowed in a class annotated
with `@ScalarOperator`.
> Update error message and comment

- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoClientConfig.java
- presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoClientConfig.java
Fix https://github.com/prestodb/presto/issues/13048
> Allow special character in MongoDB password

- presto-testing-docker/src/main/java/io/prestosql/testing/docker/DockerContainer.java
Improve docker container retrying message
> Improve docker container retrying message

- presto-main/src/main/resources/webapp/src/yarn.lock
Bump lodash in /presto-main/src/main/resources/webapp/src
Bumps [lodash](https://github.com/lodash/lodash) from 4.17.10 to 4.17.14.
- [Release notes](https://github.com/lodash/lodash/releases)
- [Commits](https://github.com/lodash/lodash/compare/4.17.10...4.17.14)
Signed-off-by: dependabot[bot] <support@github.com>
> Bump lodash in /presto-main/src/main/resources/webapp/src

- presto-hive-hadoop2/bin/common.sh
Use quiet mode when downloading docker images
> Use quiet mode when downloading docker images

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ConnectionFactory.java
Make ConnectionFactory responsible for its destruction
> Make ConnectionFactory responsible for its destruction

- presto-hive/src/main/java/io/prestosql/plugin/hive/authentication/AuthenticationModules.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/authentication/CachingKerberosHadoopAuthentication.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/authentication/KerberosHadoopAuthentication.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/authentication/CachingKerberosAuthentication.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/authentication/KerberosAuthentication.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/authentication/KerberosTicketUtils.java
Move KerberosAuthentication to presto-plugin-toolkit
Thanks to this refactor it will be easier for other connectors to
support Kerberos authentication.
> Move KerberosAuthentication to presto-plugin-toolkit

- presto-main/src/main/java/io/prestosql/operator/FilterAndProjectOperator.java
- presto-tests/src/test/java/io/prestosql/tests/TestWorkProcessorPipelineQueries.java
> Port FilterAndProjectOperator to WorkProcessor

- pom.xml
Update google cloud jars to latest version.
> Update gcs version

- pom.xml
- presto-kafka/pom.xml
- presto-kafka/src/test/java/io/prestosql/plugin/kafka/util/EmbeddedKafka.java
upgrade kafka verstion to most recent version posible
> bump kafka version to 1.1.1

- presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
- presto-main/src/main/java/io/prestosql/execution/SqlTaskManager.java
- presto-main/src/main/java/io/prestosql/memory/QueryContext.java
- presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
- presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
- presto-tests/src/test/java/io/prestosql/memory/TestMemoryManager.java
- presto-tests/src/test/java/io/prestosql/memory/TestMemorySessionProperties.java
for queryMaxMemoryPerNode and queryMaxTotalMemoryPerNode
Fixes #1203
> adding session properties 

- presto-product-tests/bin/run_presto_cli_on_docker.sh
- presto-product-tests/bin/run_tempto_on_docker.sh
Add run_presto_cli_on_docker.sh and run_tempto_on_docker.sh
> Add run_presto_cli_on_docker.sh and run_tempto_on_docker.sh

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
Avoid nested try-with-resources
> Avoid nested try-with-resources

- presto-main/etc/catalog/gsheets.properties
Ref https://github.com/prestosql/presto/blob/master/presto-google-sheets/src/main/java/io/prestosql/plugin/google/sheets/SheetsConfig.java#L67
> Fix wrong value in gsheets.properties

- presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java
- presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaPageSourceProvider.java
- presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaTableHandle.java
- presto-main/src/main/java/io/prestosql/metadata/InternalTable.java
- presto-main/src/test/java/io/prestosql/metadata/TestInformationSchemaTableHandle.java
> Add limit pushdown to Information Schema Connector

- presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
read should return -1 when no data was read but EOF is reached
> Make PrestoS3InputStream#read comply with read method contract on EOF

- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
- presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
This fixes #1275 
cc: @Parth-Brahmbhatt , @electrum
> Fix duplicate field IDs when creating Iceberg tables

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
> Add missing doAs around Hive create empty bucket files

- presto-docs/src/main/sphinx/functions/datetime.rst
- presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
- presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctionsBase.java
> Add last_day_of_month function

- presto-main/src/main/java/io/prestosql/sql/analyzer/Analysis.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
- presto-main/src/main/java/io/prestosql/sql/planner/LogicalPlanner.java
- presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
Addresses a todo in LogicalPlanner.createTableWriterPlan()
> Move semantic check to StatementAnalyzer

- presto-main/src/main/java/io/prestosql/connector/system/QuerySystemTable.java
- presto-main/src/main/java/io/prestosql/dispatcher/DispatchManager.java
- presto-main/src/main/java/io/prestosql/server/QueryResource.java
Fix system.runtime.queries when some query is gone
> Fix system.runtime.queries when some query is gone

- presto-main/src/main/java/io/prestosql/sql/analyzer/Analysis.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
- presto-main/src/main/java/io/prestosql/sql/planner/LogicalPlanner.java
Add helper class in Analysis to gather information
about 'create table as select' statement
> Refactor the analysis of create statement

- presto-main/src/main/java/io/prestosql/sql/planner/iterative/Memo.java
It's just a cleanup. There shouldn't be any performance impact.
> Reduce getGroup() calls

- presto-main/src/test/java/io/prestosql/security/TestFileBasedSystemAccessControl.java
It's covered by
`io.prestosql.plugin.base.security.TestFileBasedSystemAccessControl#testEverythingImplemented`.
> Remove duplicate test

- presto-cli/src/main/java/io/prestosql/cli/Console.java
- presto-product-tests/src/main/java/io/prestosql/tests/cli/PrestoCliTests.java
> CLI will not ignore empty execute statement

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCoercion.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestRoles.java
Otherwise table dir will be left behind.
> Drop table using same session that was used to create

- presto-jmx/src/test/java/io/prestosql/plugin/jmx/TestJmxQueries.java
- presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java
- presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaPageSourceProvider.java
- presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaTable.java
- presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaTableHandle.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
- presto-main/src/test/java/io/prestosql/metadata/TestInformationSchemaTableHandle.java
- presto-tests/src/main/java/io/prestosql/tests/AbstractTestDistributedQueries.java
- presto-tests/src/main/java/io/prestosql/tests/AbstractTestQueries.java
> Some preparatory commits for the lazy data loading feature of Information Schema Connector

- presto-hive/src/test/sql/create-test.sql
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCoercion.java
Extracted from HDP3 support PR to merge quicker & avoid conflicts.
> Small tests refactor

- presto-mysql/src/test/java/io/prestosql/plugin/mysql/DockerizedMySqlServer.java
- presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestingSqlServer.java
- presto-testing-docker/src/main/java/io/prestosql/testing/docker/DockerContainer.java
Introduce DockerContainer#Builder
> Introduce DockerContainer#Builder

- presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetPageSource.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetPageSourceFactory.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergPageSourceProvider.java
- presto-parquet/src/main/java/io/prestosql/parquet/ParquetTypeUtils.java
Please see the commit message for explanations.
This is preparatory work for decoupling `ParquetPageSource` from `HiveColumnHandle` and removing `HiveColumnHandle` in Iceberg Connector (#1324 )
> Simplify ParquetPageSource

- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/HashGenerationOptimizer.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestLogicalPlanner.java
- presto-main/src/test/java/io/prestosql/sql/query/TestPrecomputedHashes.java
> Fix multiple entries failure in HashGenerationOptimizer

- presto-docs/src/main/sphinx/admin/properties.rst
- presto-main/src/main/java/io/prestosql/execution/scheduler/FileBasedNetworkTopology.java
- presto-main/src/main/java/io/prestosql/execution/scheduler/NetworkLocation.java
- presto-main/src/main/java/io/prestosql/execution/scheduler/TopologyAwareNodeSelectorConfig.java
- presto-main/src/main/java/io/prestosql/execution/scheduler/TopologyAwareNodeSelectorModule.java
- presto-main/src/main/java/io/prestosql/execution/scheduler/TopologyFileConfig.java
- presto-main/src/test/java/io/prestosql/execution/BenchmarkNodeScheduler.java
- presto-main/src/test/java/io/prestosql/execution/TestNodeScheduler.java
- presto-main/src/test/java/io/prestosql/execution/scheduler/TestFileBasedNetworkTopology.java
- presto-main/src/test/java/io/prestosql/execution/scheduler/TestTopologyFileConfig.java
- presto-main/src/test/resources/io/prestosql/execution/scheduler/topology-new.txt
- presto-main/src/test/resources/io/prestosql/execution/scheduler/topology.txt
> Implement file based topology

- presto-docs/src/main/sphinx/admin/properties.rst
- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-319.rst
> Add 319 release notes

- README.md
This is just for a start.
Preview https://github.com/findepi/presto/blob/ide/README.md#development
> Recommend IDE configuration

- presto-hive/src/main/java/io/prestosql/plugin/hive/authentication/HiveMetastoreAuthentication.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/authentication/KerberosHiveMetastoreAuthentication.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/authentication/NoHiveMetastoreAuthentication.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/MetastoreLocator.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/StaticMetastoreLocator.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastoreClient.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreClient.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreClientFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/Transport.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/MockThriftMetastoreClient.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/MockThriftMetastoreClientFactory.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/TestStaticMetastoreLocator.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/TestingMetastoreLocator.java
https://prestosql.slack.com/archives/CGB0QHWSW/p1569411493174100
Fixes #1585
> Use delegation token for kerberized metastore

- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushProjectionThroughJoin.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/joins/JoinGraph.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPushProjectionThroughJoin.java
- presto-main/src/test/java/io/prestosql/sql/query/TestJoin.java
Fixes: https://github.com/prestosql/presto/issues/1586
> Do not push projections through outer joins

- presto-main/src/main/java/io/prestosql/connector/ConnectorManager.java
- presto-main/src/main/java/io/prestosql/connector/system/SystemConnectorModule.java
- presto-main/src/main/java/io/prestosql/metadata/StaticCatalogStore.java
- presto-main/src/main/java/io/prestosql/server/testing/TestingPrestoServer.java
- presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
> Improve catalog creation methods name

- presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClientModule.java
- presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlConfig.java
- presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlConfig.java
> Make MySQL Driver's useInformationSchema configurable

- presto-postgresql/pom.xml
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/PostgreSqlQueryRunner.java
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlCaseInsensitiveMapping.java
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlDistributedQueries.java
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestingPostgreSqlServer.java
Use dockerized testing PostgreSql server
> Use dockerized testing PostgreSql server

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueMetastoreModule.java
Sorry my [previous pull request](https://github.com/prestosql/presto/pull/1571) got corrupted in rebasing. 
Issue #1487
> Add support for Glue metastore cache

- presto-atop/src/test/java/io/prestosql/plugin/atop/TestAtopSecurity.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/HiveQueryRunner.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileBasedSecurity.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveRoles.java
- presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergMetadataListing.java
- presto-kinesis/src/test/java/io/prestosql/plugin/kinesis/TestMinimalFunctionality.java
- presto-main/src/main/java/io/prestosql/Session.java
- presto-main/src/main/java/io/prestosql/SessionRepresentation.java
- presto-main/src/main/java/io/prestosql/server/HttpRequestSessionContext.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
- presto-main/src/main/java/io/prestosql/testing/TestingSession.java
- presto-main/src/test/java/io/prestosql/security/TestAccessControlManager.java
- presto-main/src/test/java/io/prestosql/security/TestFileBasedSystemAccessControl.java
- presto-main/src/test/java/io/prestosql/server/TestHttpRequestSessionContext.java
- presto-main/src/test/java/io/prestosql/server/TestSessionPropertyDefaults.java
- presto-main/src/test/java/io/prestosql/sql/query/TestSessionFunctions.java
- presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestCredentialPassthrough.java
- presto-plugin-toolkit/src/test/java/io/prestosql/plugin/base/security/TestFileBasedSystemAccessControl.java
- presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/security/TestRaptorFileBasedSecurity.java
- presto-spi/src/main/java/io/prestosql/spi/security/Identity.java
- presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/SqlServerQueryRunner.java
- presto-tests/src/main/java/io/prestosql/tests/AbstractTestDistributedQueries.java
- presto-tests/src/test/java/io/prestosql/execution/sessionpropertymanagers/TestDbSessionPropertyManagerIntegration.java
Introduce a builder for Identity
> Introduce a builder for Identity

- presto-docs/src/main/sphinx/connector/elasticsearch.rst
- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-320.rst
Closes https://github.com/prestosql/presto/issues/1570
> Add 320 release notes

- presto-product-tests/bin/lib.sh
- presto-product-tests/bin/run_on_docker.sh
- presto-product-tests/bin/run_presto_cli_on_docker.sh
- presto-product-tests/bin/run_tempto_on_docker.sh
Improve usage of run_on_docker.sh
> Improve usage of run_on_docker.sh

- presto-cassandra/pom.xml
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraClientConfig.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraClientModule.java
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraErrorCode.java
- presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraClientConfig.java
- presto-docs/src/main/sphinx/connector/cassandra.rst
Fixes https://github.com/prestosql/presto/issues/1680
> Add support for Cassandra cluster using SSL

- presto-jmx/src/main/java/io/prestosql/plugin/jmx/JmxErrorCode.java
- presto-jmx/src/main/java/io/prestosql/plugin/jmx/JmxHistoricalData.java
- presto-jmx/src/main/java/io/prestosql/plugin/jmx/JmxMetadata.java
- presto-jmx/src/test/java/io/prestosql/plugin/jmx/TestJmxHistoricalData.java
- presto-jmx/src/test/java/io/prestosql/plugin/jmx/TestJmxMetadata.java
> Add support for wildcard patterns in JMX dump tables configuration

- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/HistoryTable.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergTableHandle.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/PartitionTable.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/TableType.java
- presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
Spec: https://iceberg.apache.org/spark/
Issue: #1268 
Umbrella issue: #1324
> Add support for Iceberg history tables

- presto-main/src/main/java/io/prestosql/sql/planner/LocalDynamicFilter.java
- presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestLocalDynamicFilter.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestLocalDynamicFiltersCollector.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/BasePlanTest.java
Following https://github.com/prestosql/presto/pull/1686
> Add unit-tests for LocalDynamicFilter

- pom.xml
- presto-server/src/main/provisio/presto.xml
This includes a new version of the Takari Archiver which supports
hardlinks in archives.
> Use new version of provisio plugin

- presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveBucketAdapterRecordCursor.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveBucketFunction.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveBucketHandle.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveBucketProperty.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveNodePartitioningProvider.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSink.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSource.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HivePartitioningHandle.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSplit.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveTableProperties.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/converter/GlueToPrestoConverter.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveBucketing.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveBucketingV1.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveBucketingV2.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveUtil.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveSplit.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/TestRecordingHiveMetastore.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/util/TestHiveBucketing.java
Fixes https://github.com/prestosql/presto/issues/538
> Support Hive bucketing v2

- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDistributedJoinQueriesWithDynamicFiltering.java
Probe splits might contain dynamic filter
rows non-deterministically. Therefore the test
doesn't provide any value.
> Remove redundant Hive dynamic filtering test

- presto-docs/src/main/sphinx/release/release-318.rst
The change in 318 was specific to RCFiles.
321 provides similar change for TEXT files.
https://github.com/prestosql/presto/issues/1714, https://github.com/prestosql/presto/pull/1321
> Update release notes

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-321.rst
Closes https://github.com/prestosql/presto/issues/1681
> Add 321 release notes

- presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlTypeMapping.java
- presto-tests/src/main/java/io/prestosql/tests/datatype/CreateAndInsertDataSetup.java
- presto-tests/src/main/java/io/prestosql/tests/datatype/CreateAsSelectDataSetup.java
- presto-tests/src/main/java/io/prestosql/tests/sql/TestTable.java
Remove {TABLE_NAME} placeholder usage from TestTable
> Remove {TABLE_NAME} placeholder usage from TestTable

- presto-main/src/main/java/io/prestosql/sql/planner/EffectivePredicateExtractor.java
I forgot to restore the TODO when I merged https://github.com/prestosql/presto/pull/1673
> Restore removed TODO

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-321.rst
- presto-docs/src/main/sphinx/release/release-322.rst
> Add 322 release notes

- presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveWriteUtils.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveMaterializedView.java
based on https://github.com/prestosql/presto/pull/1615
> Support Hive materialized view

- .travis.yml
- presto-server-rpm/pom.xml
- presto-server-rpm/src/test/java/io/prestosql/server/rpm/ServerIT.java
> Add integration test for server RPM

- presto-main/src/main/java/io/prestosql/server/PrestoServer.java
Embed Presto version into main thread
> Embed Presto version into main thread

- presto-main/src/main/java/io/prestosql/connector/ConnectorManager.java
- presto-main/src/main/java/io/prestosql/metadata/HandleResolver.java
- presto-main/src/test/java/io/prestosql/server/remotetask/TestHttpRemoteTask.java
- presto-spi/src/main/java/io/prestosql/spi/connector/Connector.java
- presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorFactory.java
Add support for a per catalog handle resolver
> Add support for a per catalog handle resolver

- presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixDistributedQueries.java
Relates to https://github.com/prestosql/presto/issues/1641
> Disable TestPhoenixDistributedQueries.testLargeIn

- presto-main/src/main/java/io/prestosql/dispatcher/LocalDispatchQuery.java
Fixes https://github.com/prestosql/presto/issues/1732
> Produce fallback value lazily

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-323.rst
Fixes https://github.com/prestosql/presto/issues/1775
> Add 323 release notes

- presto-product-tests/bin/product-tests-suite-5.sh
- presto-product-tests/bin/product-tests-suite-7-non-generic.sh
Run two hives product tests with non generic suite
> Run two hives product tests with non generic suite

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
Introduced by https://github.com/prestosql/presto/commit/105d10ef7cf95c0a242278ef1adb41ae3e3c078b
> Fix broken TestHiveIntegrationSmokeTest#testNullPartitionValues

- presto-google-sheets/src/main/java/io/prestosql/plugin/google/sheets/SheetsClient.java
- Fixing logging verbosity for gsheets plugin
(Addressing a comment from previous PR - https://github.com/prestosql/presto/pull/1784 )
> Fixing logging verbosity for gsheets plugin

- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
- presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
- presto-tests/src/main/java/io/prestosql/tests/AbstractTestDistributedQueries.java
- presto-tests/src/main/java/io/prestosql/tests/AbstractTestQueries.java
A fix for access control check in show create table
https://github.com/prestosql/presto/issues/1482
> Adding access control check in show create table

- .travis.yml
Fixes https://github.com/prestosql/presto/issues/1900
> Enable PR notifications when Travis fails

- presto-docs/src/main/sphinx/release/release-321.rst
Release notes for a3604c4bb91f899ef562c8e270de8f98536e5c0f.
> Add release notes for bucketing v2

- presto-main/src/main/java/io/prestosql/dispatcher/DispatchExecutor.java
- presto-main/src/main/java/io/prestosql/dispatcher/DispatchManager.java
- presto-main/src/test/java/io/prestosql/server/TestServer.java
- presto-tpch/src/main/java/io/prestosql/plugin/tpch/TpchMetadata.java
Extracted from https://github.com/prestosql/presto/pull/1864
> Refactor TestServer

- presto-docs/src/main/sphinx/functions/geospatial.rst
- presto-geospatial/src/main/java/io/prestosql/plugin/geospatial/GeoFunctions.java
- presto-geospatial/src/test/java/io/prestosql/plugin/geospatial/TestGeoFunctions.java
Implementations of [ST_LineInterpolatePoint](https://postgis.net/docs/ST_LineInterpolatePoint.html) and [ST_LineInterpolatePoints](https://postgis.net/docs/ST_LineInterpolatePoints.html) in postgis
> Add line_interpolate_point geospatial UDFs

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-324.rst
Closes https://github.com/prestosql/presto/issues/1862
> Add 324 release notes

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcColumnHandle.java
- presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcColumnHandle.java
- presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
This will allow evolving the class in backward compatible way.
> Add JdbcColumnHandle builder

- presto-main/src/main/java/io/prestosql/operator/LookupJoinPageBuilder.java
Fix compilation error due to merge of https://github.com/prestosql/presto/pull/1256.
Simpler alternative to https://github.com/prestosql/presto/pull/1942 to get master into correct state sooner.
> Fix merge compilation error

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
Fixes https://github.com/prestosql/presto/issues/1243
> Fix insert overwrite with Glue

- presto-hive/src/main/java/io/prestosql/plugin/hive/HdfsConfig.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HdfsConfigurationInitializer.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHdfsConfig.java
Fixes https://github.com/prestosql/presto/issues/1938
> Let startup fail if file in hive.config.resources does not exist

- presto-product-tests/bin/run_on_docker.sh
`docker-compose` can create network twice and then fail saying network
name is ambiguous.
> Prevent race in docker-compose

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-325.rst
Closes https://github.com/prestosql/presto/issues/1931
> Add 325 release notes

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
Return distinct principals from listEnabledRoles
> Return distinct principals from listEnabledRoles

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestComments.java
> Allow empty column comment in Hive connector

- pom.xml
This is the same version declared in Airbase.
> Remove redundant logback version property

- presto-server-rpm/pom.xml
- presto-server-rpm/src/main/resources/dist/config/node.properties
Align it with Presto installed from .tgz
> Update plugin location in rpm

- presto-main/src/main/java/io/prestosql/execution/QueryStateTimer.java
Mark analysis as finished when analysis thread got cancelled
> Mark analysis as finished when analysis thread got cancelled

- presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
> Move dynamic filtering debug log into createDynamicFilter() method

- presto-cli/src/main/java/io/prestosql/cli/OutputHandler.java
Due to Queues.drain waiting up to 3 seconds for the minimum of 1000 elements to be available which wouldn't happen for smaller output. Use a special end token object to indicate the end of the result reading so the printing thread can unblock from poll.
> Fix lag while printing CLI output

- .github/workflows/main.yml
This fixes the spurious resolution error with minimal impact on build time.
> Install maven dependencies single threaded

- presto-docs/src/main/sphinx/admin/spill.rst
- presto-docs/src/main/sphinx/installation/deployment.rst
- presto-docs/src/main/sphinx/security/built-in-system-access-control.rst
- presto-main/src/main/java/io/prestosql/memory/MemoryManagerConfig.java
- presto-main/src/main/java/io/prestosql/memory/NodeMemoryConfig.java
- presto-main/src/test/java/io/prestosql/memory/TestLocalMemoryManager.java
- presto-main/src/test/java/io/prestosql/memory/TestMemoryManagerConfig.java
- presto-main/src/test/java/io/prestosql/memory/TestNodeMemoryConfig.java
- presto-tests/src/test/java/io/prestosql/memory/TestMemoryManager.java
This provides a better default user experience.
> Disable reserved memory pool and enable low memory killer

- presto-server-rpm/src/main/resources/dist/etc/init.d/presto
- presto-server-rpm/src/main/rpm/preinstall
> Fix incorrect variable name

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-326.rst
Closes https://github.com/prestosql/presto/issues/2014
> Add 326 release notes

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ForwardingJdbcClient.java
- presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestForwardingJdbcClient.java
- presto-main/src/main/java/io/prestosql/Session.java
- presto-main/src/main/java/io/prestosql/execution/SetRoleTask.java
- presto-main/src/main/java/io/prestosql/execution/SetSessionTask.java
- presto-main/src/main/java/io/prestosql/security/AccessControl.java
- presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
- presto-main/src/main/java/io/prestosql/security/AccessControlModule.java
- presto-main/src/main/java/io/prestosql/security/AllowAllAccessControl.java
- presto-main/src/main/java/io/prestosql/security/DenyAllAccessControl.java
- presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
- presto-main/src/main/java/io/prestosql/security/SecurityContext.java
- presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
- presto-main/src/test/java/io/prestosql/security/TestAccessControlManager.java
- presto-main/src/test/java/io/prestosql/security/TestFileBasedSystemAccessControl.java
- presto-main/src/test/java/io/prestosql/security/TestForwardingAccessControl.java
- presto-plugin-toolkit/src/test/java/io/prestosql/plugin/base/security/TestForwardingConnectorAccessControl.java
- presto-spi/src/test/java/io/prestosql/spi/testing/InterfaceTestUtils.java
> Log AccessControl invocations

- presto-google-sheets/src/main/java/io/prestosql/plugin/google/sheets/SheetsMetadata.java
- presto-google-sheets/src/test/java/io/prestosql/plugin/google/sheets/TestGoogleSheets.java
> Hide actual tables from information_schema in Google Sheets

- presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/AddExchanges.java
- presto-main/src/test/java/io/prestosql/sql/analyzer/TestFeaturesConfig.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/ExchangeMatcher.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/PlanMatchPattern.java
- presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestAddExchangesPlans.java
- presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueries.java
> Toggle usage of Parent's Preferred properties in AddExchange

- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/TypeHelper.java
- presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationDecimalColumns.java
Add support for decimal type push down in Kudu connector.
> Add support for decimal type push down in Kudu connector

- presto-main/src/test/java/io/prestosql/operator/scalar/TestWordStemFunction.java
Test for https://github.com/prestosql/presto/pull/2145
> Add a test for corner case

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSessionProperties.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/CoalescingCounter.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/TestCoalescingCounter.java
- presto-product-tests/bin/product-tests-suite-7-non-generic.sh
- presto-product-tests/conf/docker/common/standard.yml
- presto-product-tests/conf/product-tests-config-cdh5.sh
- presto-product-tests/conf/product-tests-config-hdp3.sh
- presto-product-tests/conf/product-tests-defaults.sh
- presto-product-tests/src/main/java/io/prestosql/tests/hive/HiveProductTest.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTableStatistics.java
- presto-product-tests/src/main/resources/tempto-configuration.yaml
Fixes https://github.com/prestosql/presto/issues/556
> Fix storing statistics on CDH 5

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcConnectorFactory.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcDiagnosticModule.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcModule.java
> Extract JdbcDiagnosticModule

- presto-main/src/main/java/io/prestosql/server/PluginManager.java
Do not log all plugin files per each product test setup
> Do not log all plugin files per each product test setup

- presto-server-rpm/src/test/java/io/prestosql/server/rpm/ServerIT.java
Verify java version during RPM tests
> Verify java version during RPM tests

- pom.xml
- presto-postgresql/pom.xml
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestingPostgreSqlServer.java
Use testcontainers for TestingPostgreSqlServer
> Use testcontainers for TestingPostgreSqlServer

- pom.xml
Use testcontainers-bom to define testcontainers dependencies
> Use testcontainers-bom to define testcontainers dependencies

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveTypeName.java
Fix type used for calculation HiveTypeName estimated bytes size
> Fix type used for calculation HiveTypeName estimated bytes size

- presto-server-rpm/src/test/java/io/prestosql/server/rpm/ServerIT.java
Use eventual assertion in ServerIT
> Use eventual assertion in ServerIT

- presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
> Remove outdated javadoc

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSessionProperties.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSourceFactory.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/HiveTestUtils.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileFormats.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestOrcPageSourceMemoryTracking.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/benchmark/FileFormat.java
Add orc_use_column_names hive session property
> Add orc_use_column_names hive session property

- presto-main/src/main/java/io/prestosql/connector/system/QuerySystemTable.java
- presto-product-tests/src/main/java/io/prestosql/tests/TestSystemConnector.java
- presto-product-tests/src/main/resources/sql-tests/testcases/system/selectInformationSchemaColumns.result
Add error_type and error_code columns to system.runtime.queries
> Add error_type and error_code columns to system.runtime.queries

- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduColumnHandle.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduRecordCursorWithVirtualRowId.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduRecordSet.java
- presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationSmoke.java
Fixes #2252 
I would like to include this PR in the next release if possible. The current Kudu connector may delete the wrong records.
> Fix accidental column position swap in Kudu

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
- presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
> Use CREATE TABE LIKE in MySQL copyTableSchema

- presto-docs/src/main/sphinx/themes/presto/static/presto.css_t
Had to specifically target the style to avoid side effects on normal lists.
If desired I can add l3 support as well but I believe that is not necessary at this stage.
> Remove bullets from ToC lists

- presto-cli/src/main/java/io/prestosql/cli/OutputHandler.java
Changing LinkedBlockingQueue to ArrayBlockingQueue as it is more performant in our case.
> Use ArrayBlockingQueue instead of LinkedBlockingQueue

- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
optimize for query like:
select * from kudu_table where str_column in ( 'hello', 'world');
> kudu: use in-list predicate if ranges are all single values

- presto-docs/src/main/sphinx/connector/mongodb.rst
- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoClientConfig.java
Related to https://stackoverflow.com/questions/59360176/how-to-connect-presto-to-mongodb-container/
> Fix misleading credential of MongoDB

- presto-docs/src/main/sphinx/admin/resource-groups.rst
Added one-liner for resource group 'softConcurrencyLimit'.
> Added one-liner for resource group 'softConcurrencyLimit'.

- pom.xml
Update testcontainers to 1.12.4
> Update testcontainers to 1.12.4

- presto-accumulo/src/test/java/io/prestosql/plugin/accumulo/TestAccumuloIntegrationSmokeTest.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ForwardingJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
- presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestJdbcIntegrationSmokeTest.java
- presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraIntegrationSmokeTest.java
- presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearchIntegrationSmokeTest.java
- presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationSmokeTest.java
- presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationSmoke.java
- presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoIntegrationSmokeTest.java
- presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlIntegrationSmokeTest.java
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
- presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/TestRaptorIntegrationSmokeTest.java
- presto-redis/src/test/java/io/prestosql/plugin/redis/TestRedisIntegrationSmokeTest.java
- presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java
- presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
- presto-thrift/src/test/java/io/prestosql/plugin/thrift/integration/TestThriftIntegrationSmokeTest.java
> Add support for creating schema in JDBC connector

- presto-product-tests/conf/docker/singlenode-kafka/docker-compose.yml
- presto-product-tests/src/main/resources/tempto-configuration.yaml
Do not expose Kafka docker ports
> Use same docker image for Kafka in product tests

- presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoConnection.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcConnection.java
Fixes https://github.com/prestosql/presto/issues/2338
> Allow restoring autocommit mode

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ForwardingJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
Compilation error resulted in merge of https://github.com/prestosql/presto/pull/2316 and https://github.com/prestosql/presto/pull/1874
> Fix bad merge

- presto-main/src/main/java/io/prestosql/security/AccessControlModule.java
- presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
Same as https://github.com/prestosql/presto/pull/2316, but for `ForwardingAccessControl`
> ForwardingAccessControl refactoring

- presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
For example, the S3 client can call the STS service and
receive a forbidden error, which should not be retried.
> Avoid retrying permanent errors for S3-related services

- presto-docs/src/main/sphinx/functions/regexp.rst
- presto-main/src/main/java/io/prestosql/operator/scalar/JoniRegexpFunctions.java
- presto-main/src/main/java/io/prestosql/operator/scalar/Re2JRegexpFunctions.java
- presto-main/src/main/java/io/prestosql/type/Re2JRegexp.java
- presto-main/src/test/java/io/prestosql/operator/scalar/AbstractTestRegexpFunctions.java
Fixes #2133
function list:
three regexp_instr methods
one regexp_count method
> Add regexp_position and regexp_count functions 

- pom.xml
- presto-parquet/src/test/java/io/prestosql/parquet/reader/TestMetadataReader.java
Depends on https://github.com/prestosql/presto-hive-apache/pull/6
> Update to Parquet 1.11.0

- presto-product-tests/bin/product-tests-suite-1.sh
- presto-product-tests/bin/product-tests-suite-2.sh
- presto-product-tests/bin/product-tests-suite-3.sh
- presto-product-tests/bin/product-tests-suite-5.sh
- presto-product-tests/bin/product-tests-suite-6-non-generic.sh
- presto-product-tests/bin/product-tests-suite-7-non-generic.sh
Use tests_exit_code for tests exit code
Thanks to that it is much easier to grep the logs.
> Use tests_exit_code for tests exit code

- presto-password-authenticators/src/main/java/io/prestosql/plugin/password/ldap/LdapAuthenticator.java
- presto-password-authenticators/src/test/java/io/prestosql/plugin/password/ldap/TestLdapAuthenticator.java
Fixes #2356 by encoding special LDAP characters
> Fix LDAP injection bug

- presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixIntegrationSmokeTest.java
Relates to https://github.com/prestosql/presto/issues/2348
> Disable Phoenix schema tests

- pom.xml
- presto-product-tests/pom.xml
- presto-product-tests/src/main/java/io/prestosql/tests/PrestoTemptoPlugin.java
- presto-product-tests/src/main/java/io/prestosql/tests/TemptoProductTestRunner.java
- presto-product-tests/src/main/resources/META-INF/services/io.prestosql.tempto.TemptoPlugin
Requires https://github.com/prestosql/tempto/pull/34
> Upgrade Tempto to 170

- presto-orc/src/main/java/io/prestosql/orc/OrcRecordReader.java
- presto-spi/src/main/java/io/prestosql/spi/block/LazyBlock.java
> Make sure loaded block has expected positions count 

- presto-docs/src/main/sphinx/connector/mysql.rst
- presto-docs/src/main/sphinx/connector/postgresql.rst
- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-328.rst
Closes https://github.com/prestosql/presto/issues/2329
> Add 328 release notes

- .github/workflows/ci-checks.yml
- .github/workflows/ci-product-tests.yml
- .github/workflows/ci-tests.yml
This should improve GitHub Pull Request's and Actions' web UIs
experience, while also providing a more fine-grained ability to restart
failed tasks.
> Split CI workflow into couple

- presto-docs/src/main/sphinx/functions.rst
- presto-docs/src/main/sphinx/functions/array.rst
- presto-docs/src/main/sphinx/functions/comparison.rst
- presto-docs/src/main/sphinx/functions/conditional.rst
- presto-docs/src/main/sphinx/functions/datetime.rst
- presto-docs/src/main/sphinx/functions/decimal.rst
- presto-docs/src/main/sphinx/functions/lambda.rst
- presto-docs/src/main/sphinx/functions/list.rst
- presto-docs/src/main/sphinx/functions/logical.rst
- presto-docs/src/main/sphinx/functions/math.rst
- presto-docs/src/main/sphinx/functions/session.rst
I ended up just doing it manually for now. Sphinx had a bunch of problems with overloaded methods, method signature and such. I corrected where possible and built the list manually for now. 
Imho we should ship this and can always automate later. 
https://github.com/prestosql/presto/issues/2257
> List of functions and operators

- pom.xml
- presto-main/src/main/java/io/prestosql/dispatcher/QueuedStatementResource.java
- presto-main/src/main/java/io/prestosql/server/TaskResource.java
- presto-main/src/main/java/io/prestosql/server/protocol/ExecutingStatementResource.java
- presto-proxy/src/main/java/io/prestosql/proxy/ProxyResource.java
The RPM is now `949MB`, compared to `932MB` for 327.
> Update to Airlift 0.189

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestCreateDropSchema.java
> Delete HDFS location for Hive DROP SCHEMA

- presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
- presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctionsBase.java
Fixes https://github.com/prestosql/presto/issues/2452
> Fix last_day_of_month for first day of month

- presto-product-tests/bin/run_on_docker.sh
- presto-product-tests/conf/docker/common/hadoop.yml
- presto-product-tests/conf/docker/common/standard.yml
- presto-product-tests/conf/docker/multinode-tls-kerberos/compose.sh
- presto-product-tests/conf/docker/multinode-tls/compose.sh
- presto-product-tests/conf/docker/multinode/compose.sh
- presto-product-tests/conf/docker/singlenode-cassandra/compose.sh
- presto-product-tests/conf/docker/singlenode-hdfs-impersonation/compose.sh
- presto-product-tests/conf/docker/singlenode-hdp3/compose.sh
- presto-product-tests/conf/docker/singlenode-hive-impersonation/compose.sh
- presto-product-tests/conf/docker/singlenode-kafka/compose.sh
- presto-product-tests/conf/docker/singlenode-kerberos-hdfs-impersonation-cross-realm/compose.sh
- presto-product-tests/conf/docker/singlenode-kerberos-hdfs-impersonation-with-wire-encryption/compose.sh
- presto-product-tests/conf/docker/singlenode-kerberos-hdfs-impersonation/compose.sh
- presto-product-tests/conf/docker/singlenode-kerberos-hdfs-no-impersonation/compose.sh
- presto-product-tests/conf/docker/singlenode-kerberos-hive-impersonation/compose.sh
- presto-product-tests/conf/docker/singlenode-kerberos-kms-hdfs-impersonation/compose.sh
- presto-product-tests/conf/docker/singlenode-kerberos-kms-hdfs-no-impersonation/compose.sh
- presto-product-tests/conf/docker/singlenode-ldap-referrals/compose.sh
- presto-product-tests/conf/docker/singlenode-ldap/compose.sh
- presto-product-tests/conf/docker/singlenode-mysql/compose.sh
- presto-product-tests/conf/docker/singlenode-postgresql/compose.sh
- presto-product-tests/conf/docker/singlenode-sqlserver/compose.sh
- presto-product-tests/conf/docker/singlenode/compose.sh
- presto-product-tests/conf/docker/two-kerberos-hives/compose.sh
- presto-product-tests/conf/docker/two-mixed-hives/compose.sh
Do not setup hadoop for Kafka product tests
> Do not setup hadoop for Kafka product tests

- presto-cassandra/pom.xml
- presto-cassandra/src/main/java/io/prestosql/plugin/cassandra/CassandraTokenSplitManager.java
- presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraTokenSplitManager.java
Improves exception message bugging is in https://github.com/prestosql/presto/issues/2467
> Mention actual list when unexpected size

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcAuthenticationConfig.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/credential/ExtraCredentialProvider.java
> Prefer Optional over Nullable

- presto-main/src/main/java/io/prestosql/spiller/FileSingleStreamSpillerFactory.java
- presto-main/src/test/java/io/prestosql/spiller/TestFileSingleStreamSpillerFactory.java
In a JBOD setup disk failures are quite common. In the absence of basic failure
handling, a presto worker will not recover until a config is changed and process
is restarted -- which is difficult to handle operationally.
Spill path discovery routine already handles the case when one or more paths
are out of free space, this change adds couple of additional checks to cover
out of band disk failures.
> Handle common disk failures in the spill code path

- presto-main/src/main/java/io/prestosql/server/WorkerResource.java
Worker proxy breaks now that airlift cleans up request input streams
> Fix worker resource proxying

- pom.xml
This version has no code changes but is built with Maven.
> Update to tempto 172

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveModule.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/InternalHiveConnectorFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/util/SystemTables.java
Allow to inject system tables in Hive
> Allow to inject system tables in Hive

- presto-cli/src/main/java/io/prestosql/cli/QueryRunner.java
- presto-client/src/main/java/io/prestosql/client/OkHttpUtil.java
Allow CLI to log sent network requests
> Allow inspecting network requests in CLI

- presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraConnector.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/HiveTestUtils.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileFormats.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestOrcPageSourceMemoryTracking.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/parquet/ParquetTester.java
- presto-main/src/main/java/io/prestosql/testing/TestingConnectorSession.java
- presto-main/src/test/java/io/prestosql/operator/scalar/TestDateTimeFunctionsBase.java
- presto-memory/src/test/java/io/prestosql/plugin/memory/TestMemoryPagesStore.java
- presto-orc/src/test/java/io/prestosql/orc/TestStructColumnReader.java
- presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/TestRaptorConnector.java
- presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/metadata/TestRaptorMetadata.java
Introduce builder for TestingConnectorSession
> Introduce builder for TestingConnectorSession

- presto-docs/src/main/sphinx/security/ldap.rst
- presto-password-authenticators/src/main/java/io/prestosql/plugin/password/ldap/LdapAuthenticator.java
- presto-password-authenticators/src/main/java/io/prestosql/plugin/password/ldap/LdapConfig.java
- presto-password-authenticators/src/test/java/io/prestosql/plugin/password/ldap/TestLdapConfig.java
- presto-product-tests/bin/product-tests-suite-7-non-generic.sh
- presto-product-tests/conf/docker/singlenode-ldap-bind-dn/compose.sh
- presto-product-tests/conf/docker/singlenode-ldap-bind-dn/docker-compose.yml
- presto-product-tests/conf/docker/singlenode-ldap-bind-dn/presto-master/etc/password-authenticator.properties
- presto-product-tests/src/main/java/io/prestosql/tests/cli/TestPrestoLdapCli.java
- presto-product-tests/src/main/java/io/prestosql/tests/jdbc/TestLdapPrestoJdbc.java
> Add LDAP Service user binding

- presto-docs/src/main/sphinx/connector/hive.rst
- presto-hive/src/main/java/io/prestosql/plugin/hive/DropStatsProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveProcedureModule.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
This PR adds procedure to drop hive statistics
> Procedure for dropping statistics

- presto-main/src/main/java/io/prestosql/security/ViewAccessControl.java
- presto-spi/src/test/java/io/prestosql/spi/testing/InterfaceTestUtils.java
Fix delegation call in ViewAccessControl
> Fix delegation call in ViewAccessControl

- presto-main/src/main/java/io/prestosql/sql/gen/InputReferenceCompiler.java
The existing code works, but this makes the intention more explicit.
> Add explicit cast to InputReferenceCompiler

- presto-main/src/main/java/io/prestosql/sql/gen/PageFunctionCompiler.java
- presto-main/src/main/java/io/prestosql/sql/planner/LocalExecutionPlanner.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestLocalExecutionPlanner.java
Add appropriate error message for caught MethodTooLargeException.
> Add error message for MethodTooLargeException

- presto-docs/src/main/sphinx/connector/elasticsearch.rst
- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-329.rst
Closes https://github.com/prestosql/presto/issues/2473
> Add 329 release notes

- pom.xml
- presto-hive-hadoop2/bin/run_hive_abfs_tests.sh
- presto-hive-hadoop2/bin/run_hive_adl_tests.sh
- presto-hive-hadoop2/bin/run_hive_wasb_tests.sh
- presto-hive-hadoop2/bin/run_hive_wasb_with_azure_tests.sh
- presto-hive-hadoop2/bin/run_hive_with_azure_tests.sh
- presto-hive-hadoop2/conf/files/core-site.xml.abfs-template
- presto-hive-hadoop2/conf/files/core-site.xml.adl-template
- presto-hive-hadoop2/conf/files/core-site.xml.wasb-template
- presto-hive-hadoop2/pom.xml
- presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHiveAzure.java
- presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHiveFileSystemAbfs.java
- presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHiveFileSystemAdl.java
- presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHiveFileSystemWasb.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/InternalHiveConnectorFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/azure/HiveAzureConfig.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/azure/HiveAzureModule.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/azure/PrestoAzureConfigurationInitializer.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveLocal.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/HiveTestUtils.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveAzureConfig.java
Relates to https://github.com/prestosql/presto/issues/2380
> Add azure configuration and tests

- presto-main/src/main/java/io/prestosql/dispatcher/LocalDispatchQuery.java
While working on #2537 I've noticed that exception callback on ```queryExecutionFuture``` is called when we are cancelling it a dozen of lines below in a ```stateMachine.addStateChangeListener```. This does not make sense because we are at the terminal state so transitionToFailed is ineffective.
> Do not fail on terminated query

- presto-geospatial/src/main/java/io/prestosql/plugin/geospatial/GeoFunctions.java
- presto-geospatial/src/test/java/io/prestosql/plugin/geospatial/TestGeoFunctions.java
Extend ST_Points to support POINT, LINESTRING, POLYGON, MULTIPOINT,
MULTILINESTRING, MULTIPOLYGON and GEOMETRYCOLLECTION.
> Extend ST_Points to support major Well-Known spatial objects

- presto-main/src/main/java/io/prestosql/sql/planner/TranslationMap.java
- presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueries.java
> Resolve functions when they are a part of Parameter

- presto-docs/src/main/sphinx/connector/hive.rst
> Fix typo in default value

- presto-cli/src/main/java/io/prestosql/cli/Help.java
Same as https://prestosql.io/docs/current/sql/explain.html
Fixes https://github.com/prestosql/presto/issues/2687
> Correct explain options

- pom.xml
- presto-spi/src/main/java/io/prestosql/spi/predicate/AllOrNoneValueSet.java
- presto-spi/src/test/java/io/prestosql/spi/predicate/TestAllOrNoneValueSet.java
Previously the message would say "... required Type class
java.lang.Class".
> Fix exception message

- presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java
- presto-main/src/test/java/io/prestosql/metadata/TestInformationSchemaMetadata.java
- presto-tests/src/test/java/io/prestosql/tests/TestInformationSchemaConnector.java
> Fix querying information schema with empty name as predicate

- presto-main/src/main/java/io/prestosql/security/AccessControl.java
- presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
- presto-main/src/main/java/io/prestosql/security/AllowAllAccessControl.java
- presto-main/src/main/java/io/prestosql/security/DenyAllAccessControl.java
- presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
- presto-main/src/main/java/io/prestosql/server/QuerySessionSupplier.java
- presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
- presto-main/src/test/java/io/prestosql/security/TestFileBasedSystemAccessControl.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ReadOnlySystemAccessControl.java
- presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
The matches the naming convention, and this feature hasn't been released yet.
> Rename canImpersonateUser to checkCanImpersonateUser

- presto-docs/src/main/sphinx/functions/comparison.rst
- presto-docs/src/main/sphinx/functions/string.rst
Fixes https://github.com/prestosql/presto/issues/2627
> Add documentation for SQL LIKE

- presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoPreparedStatement.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcPreparedStatement.java
Fixes https://github.com/prestosql/presto/issues/2732
> Implement PreparedStatement.setTimestamp with Calendar

- presto-main/src/main/java/io/prestosql/execution/CallTask.java
- presto-spi/src/main/java/io/prestosql/spi/procedure/Procedure.java
- presto-testing/src/main/java/io/prestosql/testing/TestingProcedures.java
- presto-tests/src/test/java/io/prestosql/tests/TestProcedureCall.java
- presto-tests/src/test/java/io/prestosql/tests/TestProcedureCreation.java
This change allow procedure arguments to be optional with default values
> Allow procedures to have optional arguments with default values

- presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
- presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
- presto-main/src/test/java/io/prestosql/sql/query/QueryAssertions.java
- presto-main/src/test/java/io/prestosql/sql/query/TestShowQueries.java
> Add bogus row to support listing empty catalogs

- presto-hive/src/main/java/io/prestosql/plugin/hive/CreateEmptyPartitionProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/DropStatsProcedure.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
> Ensure hive table exists when running Hive procedures

- presto-main/src/test/java/io/prestosql/operator/TestTopNRowNumberOperator.java
> Decrease memory usage for TestTopNRowNumberOperator

- presto-docs/src/main/sphinx/connector/hive.rst
Fixes https://github.com/prestosql/presto/issues/2695
> Add limitation for alter schema usage

- presto-main/src/main/java/io/prestosql/execution/CreateRoleTask.java
- presto-main/src/main/java/io/prestosql/execution/DropRoleTask.java
- presto-main/src/main/java/io/prestosql/execution/GrantRolesTask.java
- presto-main/src/main/java/io/prestosql/execution/RevokeRolesTask.java
- presto-main/src/main/java/io/prestosql/execution/SetRoleTask.java
- presto-main/src/main/java/io/prestosql/metadata/MetadataUtil.java
- presto-main/src/test/java/io/prestosql/execution/TestSetRoleTask.java
- presto-tests/src/test/java/io/prestosql/tests/TestDistributedEngineOnlyQueries.java
> Validate session catalog in role commands

- presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/RemoveRedundantJoin.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestLogicalPlanner.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestRemoveRedundantJoin.java
> Remove redundant joins

- presto-main/src/main/java/io/prestosql/connector/system/TaskSystemTable.java
- presto-product-tests/src/main/java/io/prestosql/tests/TestSystemConnector.java
- presto-product-tests/src/main/resources/sql-tests/testcases/system/selectInformationSchemaColumns.result
- presto-tests/src/test/java/io/prestosql/connector/system/TestSystemConnector.java
Add physical_input_bytes to system.runtime.tasks
> Add physical_input_bytes to system.runtime.tasks

- presto-docs/src/main/sphinx/connector/hive.rst
> Add docs for Hive metastore caching

- presto-docs/src/main/sphinx/connector/hive.rst
Fixes https://github.com/prestosql/presto/issues/2661
> Specify glue metastore config in Glue section

- presto-docs/src/main/sphinx/installation/deployment.rst
Fixes https://github.com/prestosql/presto/issues/2800
> Doc node.id value restriction

- presto-main/src/main/java/io/prestosql/block/BlockSerdeUtil.java
- presto-main/src/main/java/io/prestosql/metadata/LiteralFunction.java
- presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
- presto-main/src/main/java/io/prestosql/metadata/TypeRegistry.java
- presto-main/src/main/java/io/prestosql/operator/scalar/Re2JCastToRegexpFunction.java
- presto-main/src/main/java/io/prestosql/sql/planner/LiteralEncoder.java
- presto-main/src/main/java/io/prestosql/type/CodePointsType.java
- presto-main/src/main/java/io/prestosql/type/JoniRegexpType.java
- presto-main/src/main/java/io/prestosql/type/JsonPathType.java
- presto-main/src/main/java/io/prestosql/type/LikePatternType.java
- presto-main/src/main/java/io/prestosql/type/Re2JRegexpType.java
- presto-main/src/main/java/io/prestosql/type/TypeCoercion.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestLiteralEncoder.java
- presto-main/src/test/java/io/prestosql/type/AbstractTestType.java
- presto-main/src/test/java/io/prestosql/type/TestTypeCoercion.java
Remove special handling for synthetic types
> Simplify literal

- presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/s3select/S3SelectCsvRecordReader.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestPrestoS3FileSystem.java
Cleanup test warnings and make tests more extensible
> Cleanup S3 filesystem tests

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastore.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/HiveTableOperations.java
- presto-main/src/main/java/io/prestosql/testing/TestingConnectorSession.java
- presto-plugin-toolkit/src/test/java/io/prestosql/plugin/base/security/TestFileBasedAccessControl.java
- presto-spi/src/main/java/io/prestosql/spi/security/ConnectorIdentity.java
- presto-spi/src/main/java/io/prestosql/spi/security/Identity.java
- presto-spi/src/test/java/io/prestosql/spi/block/TestingSession.java
* Remove deprecated constructors in `Identity`
* Add builder to `ConnectorIdentity`
> Identity cleanup

- presto-main/src/main/resources/webapp/src/components/WorkerStatus.jsx
Fixes: https://github.com/prestosql/presto/issues/2865
Spans have invalid ids
> Fix copying worker addresses to clipboard

- presto-geospatial/src/test/java/io/prestosql/plugin/geospatial/TestSpatialJoins.java
- presto-main/src/main/java/io/prestosql/operator/SimplePagesHashStrategy.java
> Resolve IS DISTINCT FROM operator only for join columns

- presto-product-tests/README.md
Remove obsolete product tests README.md content
> Remove obsolete product tests README.md content

- presto-docs/src/main/sphinx/admin/properties.rst
Aimed to fix https://github.com/prestosql/presto/issues/2506
> Document query management properties

- presto-docs/src/main/sphinx/admin/properties.rst
- presto-docs/src/main/sphinx/installation/deployment.rst
Aimed to fix https://github.com/prestosql/presto/issues/477
Descriptions are a bit of a guess...
> Document server and HTTP server log properties

- presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaConnectorFactory.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaConnectorModule.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaConsumerModule.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaMetadata.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaPlugin.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaTableDescriptionSupplier.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/MapBasedTableDescriptionSupplier.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/PlainTextKafkaConsumerFactory.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/TableDescriptionSupplier.java
- presto-kafka/src/test/java/io/prestosql/plugin/kafka/ConfigurationAwareModules.java
- presto-kafka/src/test/java/io/prestosql/plugin/kafka/KafkaQueryRunner.java
- presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaDistributed.java
- presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationSmokeTest.java
- presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestMinimalFunctionality.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/docker/DockerFiles.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentModule.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/common/Kafka.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeKafka.java
Make Kafka connector extendable
> Make Kafka connector extendable

- presto-hive/src/main/java/io/prestosql/plugin/hive/security/LegacyAccessControl.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardAccessControl.java
- presto-main/src/main/java/io/prestosql/security/AccessControl.java
- presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
- presto-main/src/main/java/io/prestosql/security/AllowAllAccessControl.java
- presto-main/src/main/java/io/prestosql/security/DenyAllAccessControl.java
- presto-main/src/main/java/io/prestosql/security/ForwardingAccessControl.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
- presto-main/src/test/java/io/prestosql/security/TestAccessControlManager.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/classloader/ClassLoaderSafeConnectorAccessControl.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllAccessControl.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedAccessControl.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingConnectorAccessControl.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ReadOnlyAccessControl.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ReadOnlySystemAccessControl.java
- presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorAccessControl.java
- presto-spi/src/main/java/io/prestosql/spi/security/AccessDeniedException.java
- presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
Remove access control checkCanShowTablesMetadata
> Remove access control checkCanShowTablesMetadata

- presto-main/src/main/resources/webapp/assets/presto.css
Fixes https://github.com/prestosql/presto/issues/2801
> Add sort asc/desc icons to table

- presto-main/src/main/java/io/prestosql/server/ui/DisabledWebUiAuthenticationManager.java
- presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java
- presto-main/src/test/java/io/prestosql/server/TestServer.java
- presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java
Fixes https://github.com/prestosql/presto/issues/2908
> Fix redirect to /ui behind proxy

- presto-main/src/main/resources/webapp/src/components/QueryList.jsx
Fixes https://github.com/prestosql/presto/issues/2820
> Change field placeholder to reflect behaviour on UI

- presto-docs/src/main/sphinx/admin/web-interface.rst
as agreed on Slack with @martint  and @electrum
> Rename to Web UI

- presto-docs/src/main/sphinx/admin/properties.rst
> Fix typo in docs

- presto-main/src/main/java/io/prestosql/type/DateOperators.java
- presto-main/src/main/java/io/prestosql/util/DateTimeUtils.java
- presto-main/src/test/java/io/prestosql/type/TestDateTimeOperatorsBase.java
> Fail parsing dates beyond a representable range

- presto-client/src/main/java/io/prestosql/client/ClientTypeSignature.java
- presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoPreparedStatement.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcPreparedStatement.java
The original discussion happened in [this pull request](https://github.com/prestosql/presto/pull/1656).
> Implement JDBC PreparedStatement.getMetaData

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
Fixes https://github.com/prestosql/presto/issues/2790
(based on https://github.com/prestosql/presto/pull/2791)
> Throw meaningful error when accessing ACID on Hive < 3

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
Allow to pass additional JVM opts to tempto
> Allow to pass additional JVM opts to tempto

- presto-atop/src/main/java/io/prestosql/plugin/atop/AtopConnectorFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/InternalHiveConnectorFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/security/HiveSecurityModule.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedAccessControlModule.java
- presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/RaptorConnectorFactory.java
- presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/security/RaptorSecurityModule.java
Improve log message for FileBasedAccessControl
> Improve log message for FileBasedAccessControl

- presto-hive/src/test/java/io/prestosql/plugin/hive/HiveQueryRunner.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveCreateExternalTable.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveCreateExternalTableDisabled.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileBasedSecurity.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/parquet/TestParquetDecimalScaling.java
It is also handled via `extraHiveProperties`.
> Remove HiveQueryRunner factory overload taking security

- presto-cli/src/main/java/io/prestosql/cli/AlignedTablePrinter.java
- presto-cli/src/main/java/io/prestosql/cli/CsvPrinter.java
- presto-cli/src/test/java/io/prestosql/cli/TestAlignedTablePrinter.java
- presto-cli/src/test/java/io/prestosql/cli/TestCsvPrinter.java
Fixes https://github.com/prestosql/presto/issues/2858
> Format maps and lists with varbinary

- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveMetadata.java
- presto-main/src/test/java/io/prestosql/operator/TestWorkProcessor.java
- presto-main/src/test/java/io/prestosql/operator/TestWorkProcessorPipelineSourceOperator.java
Fixes https://github.com/prestosql/presto/issues/2897
> Increase test timeout to consider full GC times

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastore.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
- presto-parquet/src/main/java/io/prestosql/parquet/Field.java
- presto-parquet/src/main/java/io/prestosql/parquet/GroupField.java
- presto-parquet/src/main/java/io/prestosql/parquet/ParquetTypeUtils.java
- presto-parquet/src/main/java/io/prestosql/parquet/PrimitiveField.java
- presto-parquet/src/main/java/io/prestosql/parquet/reader/PrimitiveColumnReader.java
- presto-testing/src/main/java/io/prestosql/testing/H2QueryRunner.java
Split out from https://github.com/prestosql/presto/pull/2840
> Minor refactor of ParquetReader II

- presto-spi/src/main/java/io/prestosql/spi/connector/CatalogSchemaRoutineName.java
- presto-spi/src/main/java/io/prestosql/spi/connector/SchemaRoutineName.java
Lowercase names passed to *RoutineName
> Lowercase names passed to *RoutineName

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveConnector.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadataFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveModule.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/TransactionalMetadataFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/CreateEmptyPartitionProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/DropStatsProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/RegisterPartitionProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/SyncPartitionMetadataProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/UnregisterPartitionProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/security/HiveSecurityModule.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardSecurityModule.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
Introduce TransactionalMetadataFactory
> Introduce TransactionalMetadataFactory

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveConnector.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadataFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/TransactionalMetadataFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/CreateEmptyPartitionProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/DropStatsProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/RegisterPartitionProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/SyncPartitionMetadataProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/UnregisterPartitionProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/security/AccessControlMetadataFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/security/HiveSecurityModule.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/security/SqlStandardSecurityModule.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
Remove unused transaction handle parameter
> Remove unused transaction handle parameter

- presto-hive/src/main/java/io/prestosql/plugin/hive/HdfsConfigurationInitializer.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/util/ConfigurationUtils.java
Move readConfiguration to ConfigurationUtils
> Move readConfiguration to ConfigurationUtils

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HiveMetastoreDecorator.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/cache/CachingHiveMetastoreModule.java
Introduce HiveMetastoreDecorator
> Introduce HiveMetastoreDecorator

- presto-main/src/main/java/io/prestosql/testing/assertions/Assert.java
- presto-main/src/test/java/io/prestosql/transaction/TestTransactionManager.java
- presto-product-tests/src/main/java/io/prestosql/tests/utils/QueryAssertions.java
- presto-server-rpm/pom.xml
- presto-server-rpm/src/test/java/io/prestosql/server/rpm/ServerIT.java
- presto-testing/src/main/java/io/prestosql/testing/QueryAssertions.java
Fixes https://github.com/prestosql/presto/issues/2995
> Assert eventually in TestTransactionManager.testExpiration

- presto-hive/src/main/java/io/prestosql/plugin/hive/testing/TestingHiveConnectorFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/testing/TestingHivePlugin.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/HiveQueryRunner.java
Allow to set custom Hive module in tests
> Allow to set custom Hive module in tests

- presto-main/src/main/java/io/prestosql/operator/LookupJoinPageBuilder.java
Don't enumerate probe blocks for every appended
join row.
> Precompute probe row size estimate once

- presto-main/src/main/java/io/prestosql/server/ui/FormWebUiAuthenticationManager.java
- presto-main/src/test/java/io/prestosql/server/ui/TestWebUi.java
> Fix UI redirect with proxy

- presto-docs/src/main/sphinx/functions/aggregate.rst
Aims to fix https://github.com/prestosql/presto/issues/2889
Not sure about using the iris data set as an example here ... should I use tpch instead? 
Or do you have some other example that we can use easily.
> Document filter for aggregate functions

- presto-docs/src/main/sphinx/installation/deployment.rst
Fixes https://github.com/prestosql/presto/issues/2837
> Add note about tmp folder config for jvm

- presto-hive/src/test/java/io/prestosql/plugin/hive/HiveQueryRunner.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestShowStats.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/parquet/TestParquetDecimalScaling.java
Do not create empty schemas in HiveQueryRunner
> Do not create empty schemas in HiveQueryRunner

- .github/workflows/checks.yml
- bin/retry
Fixes https://github.com/prestosql/presto/issues/3049
Extensive testing coverage in https://github.com/prestosql/presto/pull/3097
> Fix maven checks

- presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Make assertion to be connector agnostic
This fixes TestAccumuloDistributedQueries failure.
> Make assertion to be connector agnostic

- .github/workflows/checks.yml
- .github/workflows/module-tests.yml
- .github/workflows/product-tests.yml
> Quiet fast install mvn

- .github/workflows/product-tests.yml
- presto-product-tests/bin/product-tests-suite-7-non-generic.sh
- presto-product-tests/bin/product-tests-suite-8-non-generic.sh
Extract hdp3 tests to separate suite
> Extract hdp3 tests to separate suite

- presto-server-rpm/README.md
Fix the documentation regards to #2059
> Fix documentation for presto-server-rpm

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
Prefer variable over its value
> Prefer variable over its value

- presto-kudu/pom.xml
> Remove unused profiles in kudu

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java
Return table metadata for translated Hive views
> Return table metadata for translated Hive views

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
Remove unused TEMPTO_EXTRA_CONFIG_FILE
> Remove unused TEMPTO_EXTRA_CONFIG_FILE

- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduRecordCursor.java
`RowResult` does not have `rawData` field, so `rowDataField` was always
`null`. Inline & simplify.
> Fix reflective access

- pom.xml
> Upgrade tempto to 174

- presto-hive/src/test/java/io/prestosql/plugin/hive/TestShowStats.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/ShowStatsRewrite.java
- presto-main/src/test/java/io/prestosql/sql/query/TestColumnMask.java
- presto-main/src/test/java/io/prestosql/sql/query/TestRowFilter.java
Disallow SHOW STATS for row filters and column masking
> Disallow SHOW STATS for row filters and column masking

- presto-memory/src/main/java/io/prestosql/plugin/memory/MemoryMetadata.java
- presto-memory/src/test/java/io/prestosql/plugin/memory/TestMemoryMetadata.java
> Properly list all tables in memory connector

- presto-docs/src/main/sphinx/functions/datetime.rst
- presto-docs/src/main/sphinx/functions/list.rst
- presto-docs/src/main/sphinx/functions/session.rst
> Fix display error of datetime function document

- presto-main/src/main/java/io/prestosql/connector/ConnectorManager.java
- presto-main/src/main/java/io/prestosql/eventlistener/EventListenerManager.java
- presto-main/src/main/java/io/prestosql/server/PrestoServer.java
- presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
- presto-main/src/main/java/io/prestosql/testing/TestingEventListenerManager.java
- presto-main/src/test/java/io/prestosql/connector/MockConnectorFactory.java
- presto-main/src/test/java/io/prestosql/eventlistener/TestConnectorEventListener.java
- presto-spi/src/main/java/io/prestosql/spi/connector/Connector.java
- presto-tests/src/test/java/io/prestosql/execution/EventsAwaitingQueries.java
- presto-tests/src/test/java/io/prestosql/execution/EventsBuilder.java
- presto-tests/src/test/java/io/prestosql/execution/TestCompletedEventWarnings.java
- presto-tests/src/test/java/io/prestosql/execution/TestConnectorEventListener.java
- presto-tests/src/test/java/io/prestosql/execution/TestEventListener.java
- presto-tests/src/test/java/io/prestosql/execution/TestEventListenerPlugin.java
- presto-tests/src/test/java/io/prestosql/execution/TestingEventListener.java
It adds a possibility for Connector to define its own event handlers, that will be registered
on connector creation.
> Add Connector EventListener registration

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HiveMetastoreModule.java
Use caching metastore in tests
> Use caching metastore in tests

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/QueryBuilder.java
Some connectors need better control over various parts of the query.
> Allow custom projection and relation in QueryBuilder

- presto-atop/src/main/java/io/prestosql/plugin/atop/AtopPageSourceProvider.java
- presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryPageSourceProvider.java
- presto-blackhole/src/main/java/io/prestosql/plugin/blackhole/BlackHolePageSourceProvider.java
- presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchPageSourceProvider.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHiveFileSystem.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHivePageSink.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergPageSourceProvider.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduPageSourceProvider.java
- presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaPageSourceProvider.java
- presto-main/src/main/java/io/prestosql/connector/system/SystemPageSourceProvider.java
- presto-main/src/main/java/io/prestosql/split/PageSourceManager.java
- presto-main/src/main/java/io/prestosql/split/RecordPageSourceProvider.java
- presto-main/src/test/java/io/prestosql/execution/TestingPageSourceProvider.java
- presto-memory/src/main/java/io/prestosql/plugin/memory/MemoryPageSourceProvider.java
- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoPageSourceProvider.java
- presto-raptor-legacy/src/main/java/io/prestosql/plugin/raptor/legacy/RaptorPageSourceProvider.java
- presto-spi/src/main/java/io/prestosql/spi/connector/ConnectorPageSourceProvider.java
- presto-tests/src/test/java/io/prestosql/execution/TestBeginQuery.java
- presto-thrift/src/main/java/io/prestosql/plugin/thrift/ThriftPageSourceProvider.java
- presto-tpch/src/main/java/io/prestosql/plugin/tpch/TpchPageSourceProvider.java
Deprecate the overload that doesn't take `dynamicFilter` parameter.
> Deprecate createPageSource overload

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ForwardingJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
Allow JDBC connectors to provide system tables
> Allow JDBC connectors to provide system tables

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
> Extract createTableSql

- .github/workflows/checks.yml
- .github/workflows/module-tests.yml
- .github/workflows/product-tests.yml
See https://github.com/actions/checkout#whats-new
> Update GitHub Actions checkout to v2

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/TypeHandlingJdbcConfig.java
The new order is more reasonable.
The method was added after last release, so it is a safe change to do
now.
> JDBC cleanup

- presto-main/src/main/java/io/prestosql/util/FastutilSetHelper.java
- presto-main/src/test/java/io/prestosql/operator/scalar/FunctionAssertions.java
- presto-main/src/test/java/io/prestosql/sql/gen/TestExpressionCompiler.java
- presto-spi/src/main/java/io/prestosql/spi/connector/InMemoryRecordSet.java
> Add null check for HashStrategy of CustomObjects

- presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
> Use unique table name in test

- presto-accumulo/src/test/java/io/prestosql/plugin/accumulo/TestAccumuloDistributedQueries.java
- presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Use unique table names in distributed tests
> Use unique table names in distributed tests

- presto-docs/src/main/sphinx/connector/elasticsearch.rst
- presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java
- presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchPageSource.java
- presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/decoders/IpAddressDecoder.java
- presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearchIntegrationSmokeTest.java
- presto-testing/src/main/java/io/prestosql/testing/TestingPrestoClient.java
This allow to retrieve IP fields and filter by a specific value
> Add to Elastic connector IpAddress field

- presto-docs/src/main/sphinx/connector/kafka.rst
Replaces https://github.com/prestosql/presto/pull/3088
> Add note about parallel reads from topics

- presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestPrestoS3FileSystem.java
Previously, IAM roles could only be used with the default
provider chain (typically, EC2 instance credentials).
> Allow using configured S3 credentials with IAM role

- presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/run-presto.sh
Allow to modify Presto in product tests
> Allow to modify Presto in product tests

- pom.xml
Fixes https://github.com/prestosql/presto/issues/2981
> Update to Airlift 0.195

- presto-docs/src/main/sphinx/connector/hive.rst
- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-332.rst
> Add 332 release notes

- .github/workflows/ci-tests.yml
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentModule.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentOptions.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/common/Hadoop.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/common/Kafka.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/common/Kerberos.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/common/Standard.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/AbstractSinglenodeLdap.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/MultinodeTls.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeCassandra.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeLdap.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeLdapBindDn.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeLdapReferrals.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeMysql.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodePostgresql.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeSqlserver.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/testcontainers/PortBinder.java
> Do not bind ports in product tests on CI

- presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
- presto-main/src/main/java/io/prestosql/spiller/FileSingleStreamSpillerFactory.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java
- presto-main/src/test/java/io/prestosql/sql/analyzer/TestFeaturesConfig.java
Supersedes: https://github.com/prestosql/presto/pull/3393
> Remove spill check

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/DriverConnectionFactory.java
Depend connectionUrl on JdbcIdentity
In some connectors connenction url changes depending on JdbcIdentity.
> Depend connectionUrl on JdbcIdentity

- presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java
- presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearch6IntegrationSmokeTest.java
- presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestElasticsearch7IntegrationSmokeTest.java
Added elasticsearch tests against a 7.0.0 docker image.
this will allow to test fields added in this version like  date_nanos or flattened..
> Add Elastic 7 tests

- presto-docs/src/main/sphinx/functions/list.rst
- presto-docs/src/main/sphinx/functions/string.rst
- presto-main/src/main/java/io/prestosql/operator/scalar/StringFunctions.java
- presto-main/src/test/java/io/prestosql/operator/scalar/TestStringFunctions.java
> Add starts_with function

- presto-main/src/main/java/io/prestosql/sql/planner/LocalDynamicFilter.java
Otherwise, the collection complexity is quadratic in the number of partitions.
> Optimize TupleDomain.columnWiseUnion during dynamic filtering partition collection

- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java
Fixes #3348
Reference https://docs.mongodb.com/manual/reference/command/listCollections/
> Use listCollections command to find MongoDB view

- README.md
> Add book badge

- presto-main/src/main/java/io/prestosql/connector/ConnectorManager.java
Use ConnectorFactory class to setup ThreadContextClassLoader
> Use ConnectorFactory class to setup ThreadContextClassLoader

- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
Avoid adding context symbols to expected inputs twice.
Simplify code style.
> Refactor visitJoin in PruneUnreferencedOutputs

- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
Group timestamp tests together, separately from timestamp with time zone
tests.
> Timestamp tests minor cleanup

- presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java
Relates to https://github.com/prestosql/presto/issues/2428
> Disable flaky test temporarily

- presto-server-rpm/pom.xml
- presto-server/pom.xml
> Add check to ensure server tar.gz and RPM do not go above 1GB

- presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Use unique tableName in testInsert
> Use unique tableName in testInsert

- presto-cassandra/src/test/java/io/prestosql/plugin/cassandra/TestCassandraTokenSplitManager.java
> Fix flaky TestCassandraTokenSplitManager.testNonEmptyTable

- presto-parquet/src/main/java/io/prestosql/parquet/reader/MetadataReader.java
- presto-parquet/src/test/java/io/prestosql/parquet/reader/TestMetadataReader.java
Fixes a regression introduced in 324.
Fixes https://github.com/prestosql/presto/issues/3517
> Fix string statistics recovery logic

- presto-main/src/main/resources/webapp/src/components/QueryDetail.jsx
[Issue-3511](https://github.com/prestosql/presto/issues/3511)
> Removed Blocked Time from the web ui

- presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfigurationInitializer.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixInitializer.java
> Properly initialize Hdfs configuration in RubixInitializer

- presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Many of the tests were doing this already, but this updates the few that were missed.
> Add random suffix to all tables in TestDistributedQueries

- presto-main/src/main/java/io/prestosql/sql/analyzer/Analysis.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
- presto-main/src/main/java/io/prestosql/sql/planner/RelationPlanner.java
The decision of how unnest expressions map to output fields
is now determined by the analyzer. Doing this in the planner
duplicates effort and is brittle.
> Minor cleanups in planner

- presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
- presto-main/src/test/java/io/prestosql/sql/query/TestShowQueries.java
- presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4
- presto-parser/src/main/java/io/prestosql/sql/SqlFormatter.java
- presto-parser/src/main/java/io/prestosql/sql/parser/AstBuilder.java
- presto-parser/src/main/java/io/prestosql/sql/tree/ShowColumns.java
- presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParser.java
> Add Like predicate to SHOW COLUMNS

- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/ImplementOffset.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/AddLocalExchanges.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/HashGenerationOptimizer.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PlanNodeDecorrelator.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/UnaliasSymbolReferences.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/WindowFilterPushDown.java
- presto-main/src/main/java/io/prestosql/sql/planner/plan/RowNumberNode.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/test/PlanBuilder.java
- presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestAddExchangesPlans.java
Fixes https://github.com/prestosql/presto/issues/3542
> Support order sensitivity in RowNumberNode

- presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfig.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/rubix/RubixConfigurationInitializer.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixConfig.java
Fixes https://github.com/prestosql/presto/issues/3556
> Replace hive.cache.parallel-warmup-enabled with hive.cache.read-mode

- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/TypeSignatureTranslator.java
- presto-main/src/test/java/io/prestosql/sql/analyzer/TestTypeSignatureTranslator.java
> Fix SHOW CREATE TABLE if row type column contains special character

- presto-server-rpm/pom.xml
- presto-server-rpm/src/main/script/symlink.groovy
Depends on https://github.com/airlift/redlinerpm-maven-plugin/pull/1
Fixes #3399
> Reduce RPM size using symlinks

- pom.xml
This fixes a size estimation error when updating a t-digest.
Fixes #3486
> Update to Airlift 0.196

- presto-docs/src/main/sphinx/admin/tuning.rst
- presto-docs/src/main/sphinx/installation/deployment.rst
- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-326.rst
- presto-docs/src/main/sphinx/release/release-333.rst
- presto-docs/src/main/sphinx/sql.rst
- presto-docs/src/main/sphinx/sql/show-columns.rst
- presto-docs/src/main/sphinx/sql/show-create-schema.rst
> Add 333 release notes

- presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoDistributedQueries.java
> Enable tests related to DROP TABLE in MongoDB

- presto-spi/src/main/java/io/prestosql/spi/block/ShortArrayBlockBuilder.java
Skip valueIsNull to ShortArrayBlock if possible
> Skip valueIsNull to ShortArrayBlock if possible

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveColumnHandle.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveUtil.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Taking a stab at https://github.com/prestosql/presto/issues/3611
> Change Hive $file_modified_time column to timestamp with timezone type

- presto-spi/src/main/java/io/prestosql/spi/predicate/AllOrNoneValueSet.java
- presto-spi/src/main/java/io/prestosql/spi/predicate/Domain.java
- presto-spi/src/main/java/io/prestosql/spi/predicate/EquatableValueSet.java
- presto-spi/src/main/java/io/prestosql/spi/predicate/Marker.java
- presto-spi/src/main/java/io/prestosql/spi/predicate/Range.java
- presto-spi/src/main/java/io/prestosql/spi/predicate/SortedRangeSet.java
- presto-spi/src/main/java/io/prestosql/spi/predicate/ValueSet.java
While proper `toString` requires `ConnectorSession`, a basic `toString`
is still helpful when debugging.
> Add basic Domain, ValueSet, Range and Marker #toString

- presto-jdbc/pom.xml
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDatabaseMetaData.java
- presto-testing/src/main/java/io/prestosql/testing/CountingMockConnector.java
- presto-tests/src/test/java/io/prestosql/tests/TestInformationSchemaConnector.java
Relates to https://github.com/prestosql/presto/issues/1620
> Add metadata operation counting JDBC test

- presto-docs/src/main/sphinx/functions/math.rst
- presto-main/src/main/java/io/prestosql/operator/scalar/MathFunctions.java
- presto-main/src/test/java/io/prestosql/operator/scalar/TestMathFunctions.java
> Add random-functions with range

- presto-main/src/main/java/io/prestosql/server/CoordinatorModule.java
- presto-main/src/main/java/io/prestosql/transaction/InMemoryTransactionManager.java
See https://prestosql.slack.com/archives/CGB0QHWSW/p1588924671220000 for motivation.
> Embed version in commit stacktrace

- presto-main/src/main/java/io/prestosql/sql/DynamicFilters.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/RemoveUnsupportedDynamicFilters.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/test/PlanBuilder.java
- presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestRemoveUnsupportedDynamicFilters.java
Fixes: https://github.com/prestosql/presto/issues/3569
> Remove dynamic filters from spatial joins

- presto-parquet/src/main/java/io/prestosql/parquet/predicate/TupleDomainParquetPredicate.java
- presto-spi/src/main/java/io/prestosql/spi/predicate/Domain.java
- presto-spi/src/main/java/io/prestosql/spi/predicate/EquatableValueSet.java
- presto-spi/src/main/java/io/prestosql/spi/predicate/SortedRangeSet.java
Avoid overhead of computing intersection for checking Domain overlap by short circuiting where possible
Refactor TupleDomainParquetPredicate to use Domain#overlaps
> Improve Domain#overlaps

- presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/BuiltinColumns.java
- presto-elasticsearch/src/main/java/io/prestosql/elasticsearch/ElasticsearchMetadata.java
- presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/BaseElasticsearchSmokeTest.java
Fixes #3385 
Alternative approach to  #3467
> Fix SHOW CREATE TABLE for Elastic Search

- presto-main/src/main/java/io/prestosql/type/DoubleOperators.java
- presto-main/src/main/java/io/prestosql/type/RealOperators.java
- presto-main/src/test/java/io/prestosql/type/TestDoubleOperators.java
- presto-main/src/test/java/io/prestosql/type/TestRealOperators.java
- presto-tests/src/test/java/io/prestosql/tests/AbstractTestEngineOnlyQueries.java
Fixes https://github.com/prestosql/presto/issues/3745
> Fix hash for -0

- presto-main/src/main/java/io/prestosql/metadata/InMemoryNodeManager.java
* Tag local node as coordinator to
match getCoordinators method
* Add port to local node URI
> Fix InMemoryNodeManager

- presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java
supersedes https://github.com/prestosql/presto/pull/3659
> Fix matching Hive bucket filenames without leading zeros

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveLocationService.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveOutputTableHandle.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/LocationService.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveCreateExternalTable.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHivePageSink.java
Bug fix for issue https://github.com/prestosql/presto/issues/1089
The original change @findepi and I put in a few months ago removed the error but external tables were not properly respecting the external location property. 
Original change: https://github.com/prestosql/presto/pull/2669
> Fix support for creating Hive external tables using CTAS

- presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestRemoveUnsupportedDynamicFilters.java
Fixes https://github.com/prestosql/presto/issues/3806
> Mark test class as single-threaded

- presto-product-tests-launcher/pom.xml
- presto-testing/src/main/resources/testcontainers.properties
Fixes https://github.com/prestosql/presto/issues/3815
> Fix Launcher local startup failure

- presto-docs/src/main/sphinx/functions/datetime.rst
Fixes https://github.com/prestosql/presto/issues/3695
> Add ISO date and time examples

- presto-docs/src/main/sphinx/connector/bigquery.rst
> Fix bigquery.credentials-key property in BigQuery document

- presto-docs/src/main/sphinx/connector/hive.rst
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftMetastoreConfig.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/thrift/TestThriftMetastoreConfig.java
> Add cache for delegation token in Hive thrift metastore

- presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
- presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
- presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
- presto-main/src/main/java/io/prestosql/testing/TestingEventListenerManager.java
- presto-main/src/test/java/io/prestosql/execution/TestCommitTask.java
- presto-main/src/test/java/io/prestosql/execution/TestDeallocateTask.java
- presto-main/src/test/java/io/prestosql/execution/TestPrepareTask.java
- presto-main/src/test/java/io/prestosql/execution/TestQueryStateMachine.java
- presto-main/src/test/java/io/prestosql/execution/TestStartTransactionTask.java
- presto-main/src/test/java/io/prestosql/security/TestAccessControlManager.java
- presto-main/src/test/java/io/prestosql/security/TestFileBasedSystemAccessControl.java
- presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/ForwardingSystemAccessControl.java
- presto-spi/src/main/java/io/prestosql/spi/security/SystemAccessControl.java
enhancing event driven communicaiton about
executing queries in the system to SystemLevelAccessControl
> Allow SystemAccessControl to listen to events

- presto-main/src/main/java/io/prestosql/sql/analyzer/AggregationAnalyzer.java
- presto-main/src/test/java/io/prestosql/sql/query/TestFormat.java
- presto-parser/src/main/java/io/prestosql/sql/tree/DefaultTraversalVisitor.java
fix #3829 - allow using aggregations in format() function
> Fix allow using aggregations in format()

- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergPageSource.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSplit.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergSplitSource.java
- presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
> Handle the case where a partition column has null value

- presto-hive/src/test/java/io/prestosql/plugin/hive/rubix/TestRubixCaching.java
fixes: https://github.com/prestosql/presto/issues/3861
> Make TestRubixCaching tests more resilient

- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/SyncPartitionMetadataProcedure.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestSyncPartitionMetadata.java
Fixes https://github.com/prestosql/presto/issues/3431
> Handle mixed case partition names in sync_partition_metadata

- presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
> Generate dynamic filters only during last PPD run

- presto-main/src/main/resources/webapp/src/components/WorkerStatus.jsx
> Fix the value showed in memory usage bar on worker web

- presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveWriteUtils.java
Fixes https://github.com/prestosql/presto/issues/3864
> Enable Avro Rubix tests + remove caching TODOs

- presto-main/src/main/java/io/prestosql/sql/gen/JoinCompiler.java
Certain types were handled specially because IS DISTINCT FROM was
expensive to call for these types. The was obsolete since
b845cd66da3eb1fcece50efba83ea12bc40afbaa.
> Remove type special handling in JoinCompiler

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/util/Statistics.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Fixes https://github.com/prestosql/presto/issues/2469
> Update statistics on insert to empty table in Hive connector

- presto-main/src/main/java/io/prestosql/operator/scalar/StringFunctions.java
- presto-main/src/test/java/io/prestosql/operator/scalar/TestStringFunctions.java
> Return varchar type for substr function with char argument

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
Fix minor import issue from #3771
> Fix imports

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ColumnMapping.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcPageSink.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcRecordCursor.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ObjectReadFunction.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ObjectWriteFunction.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/QueryBuilder.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/WriteMapping.java
- presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixClient.java
- presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
Follow up to https://github.com/prestosql/presto/pull/3954
> Remove generics from object functions

- presto-accumulo-iterators/pom.xml
> Fix version in the module

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCaching.java
Presto uses variable names when creating
data files. Therefore it might happen that
every data file will be cached on same node
since files are distributed based on file name
hash.
> Remove check that each node has cached data

- presto-docs/src/main/sphinx/connector/hive.rst
- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-335.rst
> Add 335 release notes

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveBucketedTables.java
`@DataProvider` can get to run before tempto variables are injected, so
it cannot use `getHiveVersionMajor()`.
Fixes https://github.com/prestosql/presto/issues/4033
> Remove @DataProvider use from TestHiveBucketedTables

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestRoles.java
The functionality under test is just granting the 'admin' role
> Relax assertion about role is_grantable

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-336.rst
Closes https://github.com/prestosql/presto/issues/4027
> Add 336 release notes

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
Due to https://issues.apache.org/jira/browse/HIVE-22554 blocking compaction will block for ~30 seconds even when the compaction finishes earlier. This change pools for compactions using Hive's `SHOW COMPACTIONS` to test whether compaction has finished.
> Don't block while compacting table on Hive

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/PathResolver.java
Extract String based PathResolver#resolvePlaceholders
> Extract String based PathResolver#resolvePlaceholders

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadataFactory.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/StatsCollecting.java
> Make @StatsCollecting public and use CachingJdbcClient in JdbcMetadataFactory

- presto-main/src/main/java/io/prestosql/server/DynamicFilterService.java
Fixes https://github.com/prestosql/presto/issues/4086
> Do not start DynamicFilterService in test

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
> Disable table auto-compaction in TestHiveTransactionalTable

- presto-docs/src/main/sphinx/security.rst
- presto-docs/src/main/sphinx/security/secrets.rst
Contributed from https://docs.starburstdata.com/latest/security/secrets.html
> Add secrets documentation

- presto-tests/src/test/java/io/prestosql/execution/TestCoordinatorDynamicFiltering.java
Fixes: https://github.com/prestosql/presto/issues/4032
> Add test for dynamic filter materialization on coordinator

- presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSmoke.java
One element of #1324   This tests that format and partitioning properties work correctly in Iceberg.  I was unable to test the location property, because it is a URL that must point to a valid Iceberg table file AFAICT.
> Test iceberg create table like

- presto-hive/src/test/java/io/prestosql/plugin/hive/optimizer/TestHiveProjectionPushdownIntoTableScan.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestDereferencePushDown.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/ExpressionVerifier.java
Fixes https://github.com/prestosql/presto/issues/3981
> Verify GenericLiteral type in ExpressionVerifier

- presto-docs/src/main/sphinx/functions/string.rst
- presto-main/src/main/java/io/prestosql/operator/scalar/StringFunctions.java
- presto-main/src/test/java/io/prestosql/operator/scalar/TestStringFunctions.java
#3313 
This implementation follows the specification used by Postgres; see the documentation section of this commit.
> Support the SQL TRANSLATE function

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/CaseSensitivity.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcTypeHandle.java
- presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestingH2JdbcClient.java
- presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestingJdbcTypeHandle.java
- presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/ImplementAvgBigint.java
- presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlClient.java
Store information about case sensitivity in JdbcTypeHandle
> Store information about case sensitivity in JdbcTypeHandle

- presto-hive/src/main/java/io/prestosql/plugin/hive/AcidInfo.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSplit.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveSplitSource.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/InternalHiveSplit.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcDeletedRows.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSourceFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/parquet/ParquetPageSourceFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/rcfile/RcFilePageSourceFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/util/InternalHiveSplitFactory.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveSplit.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/orc/TestOrcDeletedRows.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/orc/TestOrcPageSourceFactory.java
This PR adds preliminary support for reading tables where data was inserted using ACID direct insert (https://issues.apache.org/jira/browse/HIVE-21164)
> Add support for Hive ACID direct insert

- presto-main/src/main/java/io/prestosql/operator/scalar/ArrayDistinctFromOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/ArrayEqualOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/ArrayGreaterThanOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/ArrayGreaterThanOrEqualOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/ArrayHashCodeOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/ArrayLessThanOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/ArrayLessThanOrEqualOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/ArrayNotEqualOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/MapDistinctFromOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/MapEqualOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/MapGenericEquality.java
- presto-main/src/main/java/io/prestosql/operator/scalar/MapHashCodeOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/MapNotEqualOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/RowComparisonOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/RowDistinctFromOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/RowEqualOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/RowGreaterThanOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/RowGreaterThanOrEqualOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/RowHashCodeOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/RowLessThanOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/RowLessThanOrEqualOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/RowNotEqualOperator.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/DetermineSemiJoinDistributionType.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestDetermineSemiJoinDistributionType.java
- presto-parser/src/main/java/io/prestosql/sql/tree/Commit.java
- presto-parser/src/main/java/io/prestosql/sql/tree/CurrentPath.java
- presto-parser/src/main/java/io/prestosql/sql/tree/CurrentUser.java
- presto-parser/src/main/java/io/prestosql/sql/tree/Isolation.java
- presto-parser/src/main/java/io/prestosql/sql/tree/TransactionMode.java
> Fix licence header placement

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/CachingJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ForwardingJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/expression/AggregateFunctionRewriter.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/expression/AggregateFunctionRule.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
- presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestingH2JdbcClient.java
- presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlClient.java
Use session in JDBC aggregation pushdown implementation
> Use session in JDBC aggregation pushdown implementation

- presto-parquet/src/test/java/io/prestosql/parquet/TestTupleDomainParquetPredicate.java
> Fix timestamp value creation

- presto-main/src/main/java/io/prestosql/dispatcher/DispatchManager.java
- presto-main/src/main/java/io/prestosql/execution/QueryManager.java
- presto-main/src/main/java/io/prestosql/execution/QueryManagerStats.java
- presto-main/src/main/java/io/prestosql/execution/SqlQueryManager.java
- presto-main/src/main/java/io/prestosql/server/CoordinatorModule.java
- presto-main/src/main/java/io/prestosql/server/testing/TestingPrestoServer.java
- presto-tests/src/test/java/io/prestosql/execution/TestExecutionJmxMetrics.java
- presto-tests/src/test/java/io/prestosql/execution/TestQueryRunnerUtil.java
- presto-tests/src/test/resources/resource_groups_single_query.json
> Incorrect JMX stats for queued queries

- presto-main/src/test/java/io/prestosql/sql/query/TestColumnMask.java
- presto-main/src/test/java/io/prestosql/sql/query/TestDistinctAggregations.java
- presto-main/src/test/java/io/prestosql/sql/query/TestExpressions.java
- presto-main/src/test/java/io/prestosql/sql/query/TestFilteredAggregations.java
- presto-main/src/test/java/io/prestosql/sql/query/TestFormat.java
- presto-main/src/test/java/io/prestosql/sql/query/TestGrouping.java
- presto-main/src/test/java/io/prestosql/sql/query/TestGroupingSets.java
- presto-main/src/test/java/io/prestosql/sql/query/TestHaving.java
- presto-main/src/test/java/io/prestosql/sql/query/TestJoinUsing.java
- presto-main/src/test/java/io/prestosql/sql/query/TestLambdaExpressions.java
- presto-main/src/test/java/io/prestosql/sql/query/TestNumericalStability.java
- presto-main/src/test/java/io/prestosql/sql/query/TestOrderedAggregation.java
- presto-main/src/test/java/io/prestosql/sql/query/TestPrecomputedHashes.java
- presto-main/src/test/java/io/prestosql/sql/query/TestPredicatePushdown.java
- presto-main/src/test/java/io/prestosql/sql/query/TestReduceAgg.java
- presto-main/src/test/java/io/prestosql/sql/query/TestRowFilter.java
- presto-main/src/test/java/io/prestosql/sql/query/TestSelectAll.java
- presto-main/src/test/java/io/prestosql/sql/query/TestSessionFunctions.java
- presto-main/src/test/java/io/prestosql/sql/query/TestShowQueries.java
- presto-main/src/test/java/io/prestosql/sql/query/TestSubqueries.java
- presto-main/src/test/java/io/prestosql/sql/query/TestUnnest.java
#4098
I will work on `assertQueryOrdered` and `assertFails`.
> Replace usage assertQuery(actual, expect) with assertThat

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-337.rst
Closes https://github.com/prestosql/presto/issues/4058
> Add 337 release notes

- presto-product-tests/bin/product-tests-suite-5.sh
> Enable caching Avro tests

- presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
- presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlTypeMapping.java
Fixes #4146
Mapping unsigned types to wider type.
- TINYINT to SMALLINT
- SMALLINT to INTEGER
- INTEGER to BIGINT
- BIGINT to DECIMAL(20,0)
> Support mysql unsigned types

- presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoResultSet.java
See #3928.
This is the simplest solution I could come up with. Simply count the number of expected item in the queue with a Semaphore and release the Semaphore one more time at the end of the Future, hence when we can acquire the Semaphore and yet the queue is empty we know we're done.
In my testing with 100k batches I noticed some overhead from the synchronization, but I'm not 100% about my testing. What this does for sure is avoiding the busy waiting in the JDBC client.
> Avoid busy waiting in the JDBC client.

- presto-main/src/test/java/io/prestosql/server/TestServer.java
Fixes https://github.com/prestosql/presto/issues/4238 https://github.com/prestosql/presto/issues/4218
> Fix flaky TestServer.testFirstResponseColumns

- pom.xml
BadInstanceof, CompareToZero, InconsistentHashCode, ObjectToString
#4188
> Enable more error prone checkes

- presto-benchto-benchmarks/pom.xml
Fixes: https://github.com/prestosql/presto/issues/4298
> Revert benchto packaging changes

- presto-product-tests/src/main/java/io/prestosql/tests/PrestoTemptoPlugin.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/HiveProductTest.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/HiveVersion.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/HiveVersionProvider.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestAllDatatypesFromHiveConnector.java
This one is based on #4295.
Please just review top 3 commits here.
> Improve assertions in TestAllDatatypesFromHiveConnector

- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Nested array and map present in the metastore schema but missing in the parquet footer used to throw NPEs when the ParquetReader was getting the missing nested fields infos.
This got fixed by 6e272ed5f865e50dc8b1675c191fe67f49b09dfe which enrich the schema read from the parquet footer.
This test is there to ensure no regression is introduced by future changes in the ParquetPageSourceFactory.
We have a patch to avoid the NPEs thrown by `field.getChildren().get(0).get();` in Criteo's fork 
(https://github.com/criteo-forks/presto/commit/3d3260392ae2efa9ef44f3e647fd6e45925d023e)
that I can get rid of thank to the work done in https://github.com/prestosql/presto/pull/3396.
I can also submit the patch which still make sense but it would be dead code so I think just the test is enough.
> Test missing nested array in Parquet files

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
- remove `TestHiveTransactionalTable` from `storage_formats` test group,
except for one variant
- reduce test matrix, so that bucketing versions are tested once
Relates to https://github.com/prestosql/presto/issues/4176
> Reduce number of runs of TestHiveTransactionalTable

- .github/workflows/ci.yml
> Continue testing even if some intermediate modules fail

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
We've been comparing seconds with milliseconds resolution timestamps
> Fix time resolution in comparison

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
- presto-memsql/src/main/java/io/prestosql/plugin/memsql/MemSqlClient.java
- presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
- presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixClient.java
- presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
> Filter table names in hidden schema for JDBC connector

- presto-oracle/src/main/java/io/prestosql/plugin/oracle/OracleClient.java
- presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestOracleIntegrationSmokeTest.java
- presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestingOracleServer.java
> Filter internal schemas in Oracle connector

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/docker/ContainerUtil.java
Fixes https://github.com/prestosql/presto/issues/4359
> Ignore exception when deleting non existing network

- presto-docs/src/main/sphinx/connector/hive-caching.rst
Addressing the late feedback on the PR ..
> Update hive caching documentation

- presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/FeaturesConfig.java
- presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
- presto-main/src/test/java/io/prestosql/sql/analyzer/TestFeaturesConfig.java
Add session property to enable using the legacy optimizer
> Replace PruneUnreferencedOutputs with iterative rules

- presto-druid/pom.xml
> Upgrade avatica jdbc version : 1.16.0 -> 1.17.0

- presto-docs/src/main/sphinx/admin/properties.rst
Specifically I would like to be able to link to exchange properties but in this case I think it make sense to add anchors to all these sections. Some already have anchors anyway.
> Add section anchors to allow ref linking

- pom.xml
Bumping from 2.1.2 to 2.3.0 (latest stable)
> Update Alluxio client version to 2.3.0

- presto-hive/src/main/java/io/prestosql/plugin/hive/BackgroundHiveSplitLoader.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java
> Fix fails query if bucket number exceeds declared bucket size

- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Query info contains zeroes if updates haven't been applied yet.
Fixed by retrying with increasing delay between query and getQueryInfo.
This fixes #4314
> Fix flaky testParquetTimestampPredicatePushdown

- presto-kafka/pom.xml
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaPageSink.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/AbstractRowEncoder.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/EncoderModule.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/RowEncoder.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/avro/AvroRowEncoder.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/avro/AvroRowEncoderFactory.java
- presto-kafka/src/test/java/io/prestosql/plugin/kafka/KafkaQueryRunner.java
- presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationSmokeTest.java
- presto-kafka/src/test/resources/write_test/all_datatypes_avro.json
- presto-kafka/src/test/resources/write_test/all_datatypes_avro_key_schema.avsc
- presto-kafka/src/test/resources/write_test/all_datatypes_avro_message_schema.avsc
Add `AvroRowEncoder` and `AvroRowEncoderFactory`
Add test case in `io.prestosql.plugin.kafka.TestKafkaIntegrationSmokeTest#testRoundTripAllFormats`
> Add Kafka Avro encoder

- presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationSmokeTest.java
~~Missed this method in #4183, fixes error when getting value from `RawValueProvider` more than once. Need to "reset" the position each time a get method is called.~~
_Thought_ I missed `getSlice` but I did not. Instead I've just improved the test to cover every combination of presto/java types.
> Improve test coverage for raw decoder

- presto-kudu/pom.xml
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduBucketFunction.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduBucketedSplitSource.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientConfig.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduConnector.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduConnectorFactory.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduHandleResolver.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduMetadata.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduModule.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduNodePartitioningProvider.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduPartitionHandle.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduPartitioningHandle.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduSessionProperties.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduSplit.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduSplitManager.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduTableHandle.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/schema/KuduRangePartition.java
- presto-kudu/src/main/java/org/apache/kudu/client/KeyEncoderAccessor.java
- presto-kudu/src/test/java/io/prestosql/plugin/kudu/KuduQueryRunnerFactory.java
- presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationGroupedExecution.java
Add grouped execution to kudu connector, controlled by session param kudu.grouped_execution=true;
> Add grouped_execution to kudu connector

- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/RegisterPartitionProcedure.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHivePartitionProcedures.java
Fixes https://github.com/prestosql/presto/issues/4443
> Register partition from default location when location is missing in registerPartition procedure

- presto-iceberg/pom.xml
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/ManifestsTable.java
This commit updates the Iceberg libraries to release 0.9.0,
and fixes Iceberg connector to conform to the two Iceberg
API changes.
> Update Iceberg libraries to release 0.9.0

- presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcConnection.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcPreparedStatement.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcResultSet.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcWarnings.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDatabaseMetaData.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDriver.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDriverAuth.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
Follow-up to https://github.com/airlift/airlift/pull/844
> Remove TestPrestoDriver.closeQuietly

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-339.rst
> Add 339 release notes

- presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestingOracleServer.java
- presto-oracle/src/test/resources/init.sql
Fixes #4395
I will rerun several times to make sure the result.
> Fix flaky TestOracleIntegrationSmokeTest

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestCsv.java
`TestCsv` was frequently failing on CI.
Fixes https://github.com/prestosql/presto/issues/3161
Fixes https://github.com/prestosql/presto/issues/4404
> Reduce data size in TestCsv

- presto-main/src/main/java/io/prestosql/server/security/KerberosAuthenticator.java
> Removed Auth Token from Exception Message

- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/HdfsInputFile.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/HdfsOutputFile.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergFileWriterFactory.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergPageSink.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergPageSourceProvider.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergParquetFileWriter.java
- presto-product-tests/bin/product-tests-suite-2.sh
- presto-product-tests/bin/product-tests-suite-3.sh
- presto-product-tests/bin/product-tests-suite-5.sh
- presto-product-tests/bin/product-tests-suite-6-non-generic.sh
- presto-product-tests/bin/product-tests-suite-7-non-generic.sh
Manually tested with production Kerberized HMS and HDFS with impersonation enabled.
Part of #1324 
Thanks to @manishmalhotrawork for reporting and discussing on this.
> Fix HDFS impersonation in Iceberg Connector

- presto-docs/src/main/sphinx/connector/mongodb.rst
Fixes https://github.com/prestosql/presto/issues/4410
> Add known limitations

- .github/workflows/ci.yml
- pom.xml
- presto-test-jdbc-compatibility/bin/run_tests.sh
- presto-test-jdbc-compatibility/pom.xml
- presto-test-jdbc-compatibility/src/test/java/io/prestosql/JdbcDriverCapabilities.java
- presto-test-jdbc-compatibility/src/test/java/io/prestosql/TestJdbcCompatibility.java
- presto-test-jdbc-compatibility/src/test/java/io/prestosql/TestJdbcResultSetCompatibility.java
- presto-test-jdbc-compatibility/src/test/java/io/prestosql/TestingServerUtils.java
Fixes https://github.com/prestosql/presto/issues/1787
> Ensure that older JDBC clients are compatible with current Presto server

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/QueryBuilder.java
Restore customizable QueryBuilder#getRelation
> Restore customizable QueryBuilder#getRelation

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentOptions.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeSparkIceberg.java
- presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg/iceberg.properties
- presto-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-spark-iceberg/spark-defaults.conf
- presto-product-tests/bin/product-tests-suite-7-non-generic.sh
- presto-product-tests/src/main/java/io/prestosql/tests/iceberg/TestIcebergBasic.java
- presto-product-tests/src/main/java/io/prestosql/tests/utils/QueryExecutors.java
- presto-product-tests/src/main/resources/tempto-configuration.yaml
Depends on https://github.com/prestosql/docker-images/pull/64
> Iceberg product tests

- presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetSchemaConverter.java
Sets the Parquet logical type annotation for timestamp columns.
> Extend Parquet timestamp support

- presto-main/src/main/java/io/prestosql/execution/CreateTableTask.java
- presto-main/src/test/java/io/prestosql/execution/TestCreateTableTask.java
AccessControl::checkCanSelectFromColumn is now made when executing CREATE TABLE .. (LIKE ...)
> Check permission for create table like

- .gitignore
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
- presto-product-tests/bin/product-tests-suite-1.sh
- presto-product-tests/bin/product-tests-suite-2.sh
- presto-product-tests/bin/product-tests-suite-3.sh
- presto-product-tests/bin/product-tests-suite-5.sh
- presto-product-tests/bin/product-tests-suite-6-non-generic.sh
- presto-product-tests/bin/product-tests-suite-7-non-generic.sh
- presto-product-tests/bin/product-tests-suite-8-non-generic.sh
- presto-product-tests/bin/product-tests-suite-tpcds.sh
This PR will enable reporting product tests executions status back to Github checks.
> Make product tests reports available on host machine

- presto-docs/src/main/sphinx/connector/hive.rst
> Remove redundant Glue catalogid from documentation

- presto-docs/src/main/sphinx/functions/bitwise.rst
- presto-main/src/main/java/io/prestosql/operator/scalar/BitwiseFunctions.java
- presto-main/src/test/java/io/prestosql/operator/scalar/TestBitwiseFunctions.java
- presto-main/src/test/java/io/prestosql/sql/query/TestShowQueries.java
- bitwise_left_shift: Bitwise left shift function
- bitwise_right_shift: Bitwise logical right shift function
- bitwise_right_shift_arithmetic: Bitwise arithmetic right shift function
See: https://github.com/prestosql/presto/issues/722
> Support bitwise shift functions

- presto-docs/src/main/sphinx/sql/alter-table.rst
- presto-main/src/main/java/io/prestosql/execution/AddColumnTask.java
- presto-main/src/main/java/io/prestosql/execution/DropColumnTask.java
- presto-main/src/main/java/io/prestosql/execution/RenameColumnTask.java
- presto-main/src/main/java/io/prestosql/execution/RenameTableTask.java
- presto-parser/src/main/antlr4/io/prestosql/sql/parser/SqlBase.g4
- presto-parser/src/main/java/io/prestosql/sql/SqlFormatter.java
- presto-parser/src/main/java/io/prestosql/sql/parser/AstBuilder.java
- presto-parser/src/main/java/io/prestosql/sql/tree/AddColumn.java
- presto-parser/src/main/java/io/prestosql/sql/tree/DropColumn.java
- presto-parser/src/main/java/io/prestosql/sql/tree/RenameColumn.java
- presto-parser/src/main/java/io/prestosql/sql/tree/RenameTable.java
- presto-parser/src/test/java/io/prestosql/sql/parser/TestSqlParser.java
- presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Fixes https://github.com/prestosql/presto/issues/2260
> Add IF EXISTS and IF NOT EXISTS checks to ALTER TABLE

- presto-product-tests-launcher/pom.xml
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/EnvironmentUp.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/Environment.java
This PR simplifies product test environment startup by utilizing TestContainer's container dependencies.
It also adds retries/timeouts when the environment failed to start correctly.
> Product tests environments startup hardening

- presto-main/src/main/java/io/prestosql/operator/DriverStats.java
- presto-main/src/main/java/io/prestosql/operator/SetBuilderOperator.java
- presto-main/src/main/java/io/prestosql/sql/planner/SubPlan.java
- presto-main/src/main/java/io/prestosql/sql/planner/plan/OutputNode.java
- presto-main/src/main/java/io/prestosql/testing/MaterializedRow.java
- presto-main/src/main/java/io/prestosql/util/GraphvizPrinter.java
- presto-main/src/test/java/io/prestosql/metadata/TestScalarFunctionAdapter.java
- presto-main/src/test/java/io/prestosql/operator/aggregation/AbstractTestApproximateCountDistinct.java
- presto-main/src/test/java/io/prestosql/operator/scalar/BenchmarkArrayDistinct.java
- presto-main/src/test/java/io/prestosql/operator/scalar/BenchmarkArrayFilter.java
- presto-main/src/test/java/io/prestosql/operator/scalar/BenchmarkArraySort.java
- presto-main/src/test/java/io/prestosql/operator/scalar/BenchmarkArrayTransform.java
- presto-main/src/test/java/io/prestosql/sql/gen/TestExpressionCompiler.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestEffectivePredicateExtractor.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestEqualityInference.java
- presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetSchemaConverter.java
- presto-parser/src/main/java/io/prestosql/sql/tree/BooleanLiteral.java
- presto-pinot/src/main/java/io/prestosql/pinot/PinotMetrics.java
- presto-tpch/src/test/java/io/prestosql/plugin/tpch/TestTpchMetadata.java
Use static imports for Preconditions and Verify
> Use static imports for Preconditions and Verify

- presto-kudu/src/main/java/io/prestosql/plugin/kudu/RowHelper.java
- presto-kudu/src/test/java/io/prestosql/plugin/kudu/TestKuduIntegrationDecimalColumns.java
Fix error when delete by a decimal primary key column.
> Fix error when delete by a decimal primary key column.

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
- presto-product-tests/bin/product-tests-suite-1.sh
- presto-product-tests/bin/product-tests-suite-2.sh
- presto-product-tests/bin/product-tests-suite-3.sh
- presto-product-tests/bin/product-tests-suite-5.sh
- presto-product-tests/bin/product-tests-suite-6-non-generic.sh
- presto-product-tests/bin/product-tests-suite-7-non-generic.sh
- presto-product-tests/bin/product-tests-suite-8-non-generic.sh
- presto-product-tests/bin/product-tests-suite-tpcds.sh
Follow-up to https://github.com/prestosql/presto/pull/4731#discussion_r467504845
> Generate reports dir automatically

- presto-main/src/main/java/io/prestosql/server/protocol/QueryResultRows.java
- presto-main/src/test/java/io/prestosql/server/protocol/TestQueryResultRows.java
Fixes https://github.com/prestosql/presto/issues/4778
> Fix serializing row type with null field values

- presto-oracle/pom.xml
> add orai18n jar to Oracle ZHS16GBK character

- presto-docs/src/main/sphinx/functions/binary.rst
- presto-main/src/main/java/io/prestosql/operator/scalar/VarbinaryFunctions.java
- presto-main/src/test/java/io/prestosql/operator/scalar/TestVarbinaryFunctions.java
> Add reverse function for varbinary

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/EnvironmentUp.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/Environment.java
Follow-up to https://github.com/prestosql/presto/pull/4719#discussion_r467505686
> Remove product test environment startup timeout

- presto-main/src/main/java/io/prestosql/server/protocol/QueryResultRows.java
- presto-main/src/test/java/io/prestosql/server/protocol/TestQueryResultRows.java
Follow-up to https://github.com/prestosql/presto/pull/4780
> Fix serialization of NULL values in ARRAY and MAP types for legacy values

- presto-docs/src/main/sphinx/installation/cli.rst
Once more where I include the actual updated file...
- New PR for changes made in #4421
- Originally added history and troubleshooting sections
- Updated debug info
> Changes to History and Diagnostic sections in CLI file

- presto-docs/src/main/sphinx/connector/sqlserver.rst
Updated connection-url in Configuration section
Edited "Configuration" and "Multiple SQL Server Databases or Servers" sections for clarity
> Update Config connection-url

- presto-docs/src/main/sphinx/security/built-in-system-access-control.rst
> Add schema access rules documentation

- presto-pinot/src/main/java/io/prestosql/pinot/query/FilterToPqlConverter.java
- presto-pinot/src/test/java/io/prestosql/pinot/query/TestDynamicTable.java
Fixes issue where functions cannot be used in passthrough queries.
> Fix functions in pinot passthrough queries

- presto-docs/src/main/sphinx/connector/sqlserver.rst
Quick fix to earlier PR https://github.com/prestosql/presto/pull/4798
> Edit connection url

- pom.xml
- presto-main/src/main/java/io/prestosql/server/security/ServerSecurityModule.java
- presto-main/src/main/java/io/prestosql/server/ui/WebUiAuthenticationModule.java
> Only request client certificate when using certificate authentication

- presto-main/src/main/java/io/prestosql/sql/gen/CursorProcessorCompiler.java
> Add missing cast in CursorProcessorCompiler

- presto-pinot/src/main/java/io/prestosql/pinot/PinotColumn.java
- presto-pinot/src/main/java/io/prestosql/pinot/PinotSegmentPageSource.java
- presto-pinot/src/main/java/io/prestosql/pinot/decoders/DecoderFactory.java
- presto-pinot/src/main/java/io/prestosql/pinot/decoders/RealDecoder.java
- presto-pinot/src/test/java/io/prestosql/pinot/TestMinimalFunctionality.java
Add support for integer and real types.
> Support for more types

- presto-docs/src/main/sphinx/connector/hive.rst
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveWriterFactory.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Fixes https://github.com/prestosql/presto/issues/471
> Allow using temporary staging path for writing sorted files

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/CachingJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ColumnMapping.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ForwardingJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/PredicatePushdownController.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/QueryBuilder.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/JdbcClientStats.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
- presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushAggregationIntoTableScan.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushLimitIntoTableScan.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushProjectionIntoTableScan.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushSampleIntoTableScan.java
- presto-main/src/test/java/io/prestosql/sql/query/QueryAssertions.java
- presto-main/src/test/java/io/prestosql/sql/query/TestColumnMask.java
- presto-main/src/test/java/io/prestosql/sql/query/TestRowFilter.java
- presto-mysql/pom.xml
- presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
- presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlIntegrationSmokeTest.java
- presto-postgresql/pom.xml
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
- presto-sqlserver/pom.xml
- presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java
- presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java
- presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
- presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueryFramework.java
Fixes https://github.com/prestosql/presto/issues/4111
> Eliminate pushed down filters above JDBC TableScan

- presto-product-tests/pom.xml
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCaching.java
- presto-product-tests/src/main/java/io/prestosql/tests/jdbc/TestJdbc.java
- presto-product-tests/src/main/java/io/prestosql/tests/utils/QueryAssertions.java
Do not use presto-main in product tests
> Do not use presto-main in product tests

- presto-testng-services/src/main/java/io/prestosql/testng/services/ReportUnannotatedMethods.java
- presto-testng-services/src/test/java/io/prestosql/testng/services/TestReportUnannotatedMethods.java
Support overriding Object methods in tests
> Support overriding Object methods in tests

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
Mark TestHiveTransactionalTable::testReadFullAcidBucketed as flaky
> Mark TestHiveTransactionalTable::testReadFullAcidBucketed as flaky

- presto-postgresql/pom.xml
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
> Mark flaky PostgreSQL test

- presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
Test connector when running join with empty build side
> Test connector when running join with empty build side

- presto-main/src/main/java/io/prestosql/execution/SqlTask.java
Value of that field is used to populate TaskStatus#version
> Rename nextTaskInfoVersion to nextTaskStatusVersion

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
- presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
https://github.com/prestosql/presto/issues/4885
> Improve error reporting when verification fails

- presto-docs/src/main/sphinx/connector/mysql.rst
- presto-mysql/pom.xml
- presto-mysql/src/main/java/io/prestosql/plugin/mysql/ImplementAvgBigint.java
- presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
- presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlClient.java
- presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlIntegrationSmokeTest.java
> Support aggregation pushdown in MySQL connector

- presto-base-jdbc/pom.xml
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/RetryingConnectionFactory.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/credential/StaticCredentialProvider.java
- presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestRetryingConnectionFactory.java
- presto-oracle/src/main/java/io/prestosql/plugin/oracle/OracleClientModule.java
- presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestOracleTypes.java
- presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestingOracleServer.java
- presto-sqlserver/pom.xml
Allow retrying opening connection in Oracle
> Allow retrying opening connection in Oracle

- presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
- presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlSessionProperties.java
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
Fixes https://github.com/prestosql/presto/issues/4981
Fixes https://github.com/prestosql/presto/issues/4885
> Fix CONVERT_TO_VARCHAR with arrays

- presto-testng-services/src/main/java/io/prestosql/testng/services/ReportUnannotatedMethods.java
- presto-testng-services/src/test/java/io/prestosql/testng/services/TestReportUnannotatedMethods.java
Support implementing interface in tests
> Support implementing interface in tests

- presto-testing/src/main/java/io/prestosql/testing/AbstractTestIntegrationSmokeTest.java
Make testJoinWithEmptySides parametric
> Make testJoinWithEmptySides parametric

- presto-docs/src/main/sphinx/connector/hive.rst
documentation for hive.metastore-timeout config. #4663
> documentation for hive.metastore-timeout config

- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/RemoveUnsupportedDynamicFilters.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/TransformUncorrelatedInPredicateSubqueryToSemiJoin.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/HashGenerationOptimizer.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/LimitPushDown.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/ReplicateSemiJoinInDelete.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/UnaliasSymbolReferences.java
- presto-main/src/main/java/io/prestosql/sql/planner/plan/SemiJoinNode.java
- presto-main/src/main/java/io/prestosql/sql/planner/planprinter/PlanPrinter.java
- presto-main/src/main/java/io/prestosql/sql/planner/sanity/DynamicFiltersChecker.java
- presto-main/src/test/java/io/prestosql/sql/planner/AbstractPredicatePushdownTest.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestDynamicFilter.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestEffectivePredicateExtractor.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestQuantifiedComparison.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/PlanMatchPattern.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/SemiJoinMatcher.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/test/PlanBuilder.java
- presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestRemoveUnsupportedDynamicFilters.java
- presto-main/src/test/java/io/prestosql/sql/planner/sanity/TestDynamicFiltersChecker.java
Supersedes the planner part of #2190
> Dynamic filtering for semi-joins: planner

- presto-docs/src/main/sphinx/admin/session-property-managers.rst
Added a Limitations section to Session Property Manager file
Edited one header to match the google dev style guide
> Add limitation to Session Property Manager file

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/SuiteRun.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentOptions.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/common/Hadoop.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/suite/SuiteConfig.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/suite/configs/ConfigDefault.java
Hadoop init script if necessary can be copied at the SuiteConfig level
> Allow SuiteConfig to extend/configure Environment

- presto-hive/src/main/java/io/prestosql/plugin/hive/s3/PrestoS3FileSystem.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/s3/MockAmazonS3.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestPrestoS3FileSystem.java
> Allow PrestoS3FileSystem to skip DeepArchive files

- pom.xml
This PR updates Failsafe to version 2.4.0
> Update Failsafe to 2.4.0

- presto-benchmark/src/main/java/io/prestosql/benchmark/SqlConsecutiveJoinBenchmark.java
- presto-main/src/main/java/io/prestosql/SystemSessionProperties.java
- presto-main/src/test/java/io/prestosql/sql/query/TestShowQueries.java
- presto-tests/src/test/java/io/prestosql/tests/TestDictionaryAggregation.java
Remove reorder_joins session property
> Remove reorder_joins session property

- .github/workflows/ci.yml
- presto-testng-services/src/main/java/io/prestosql/testng/services/LogTestDurationListener.java
Enable LogTestDurationListener by default in GHA
> Enable LogTestDurationListener by default in GHA

- presto-docs/src/main/sphinx/connector/system.rst
> Add documentation for system table optimizer_rule_stats

- presto-docs/src/main/sphinx/connector/hive-s3.rst
- presto-hive/src/main/java/io/prestosql/plugin/hive/s3/S3SecurityMapping.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/s3/S3SecurityMappingConfigurationProvider.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/s3/TestS3SecurityMapping.java
- presto-hive/src/test/resources/io/prestosql/plugin/hive/s3/security-mapping-with-fallback-to-cluster-default.json
- presto-hive/src/test/resources/io/prestosql/plugin/hive/s3/security-mapping-without-fallback.json
- presto-hive/src/test/resources/io/prestosql/plugin/hive/s3/security-mapping.json
@kokosing @electrum please review
> Allow to use cluster default role in hive S3 Security Mapping

- presto-docs/src/main/sphinx/security.rst
- presto-docs/src/main/sphinx/security/salesforce.rst
@dain here is the documentation for the Salesforce Authenticator, #4372 .  Please advise if changes are needed.
> Added documentation for Salesforce authentication password plugin.

- presto-docs/src/main/sphinx/connector/hive.rst
Adding in hive.*.time-zone configuration properties for parquet, orc, rcfile for release 341
Reviewer: @mosabua
> Added new timezone configuration properties for the Hive connector.

- presto-main/src/main/java/io/prestosql/execution/QueryStateMachine.java
> Ensure transaction cleanup does not fail in transitionToFailed

- presto-testng-services/src/main/java/io/prestosql/testng/services/ReportUnannotatedMethods.java
- presto-testng-services/src/test/java/io/prestosql/testng/services/TestReportUnannotatedMethods.java
Allow to suppress testng checks
> Allow to suppress testng checks

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/Launcher.java
Allow to override product tests launcher
> Allow to override product tests launcher

- presto-hive/src/main/java/io/prestosql/plugin/hive/authentication/KerberosHadoopAuthentication.java
Reference Slack Discussion: https://prestosql.slack.com/archives/CP1MUNEUX/p1585603192038500?thread_ts=1585270167.019800&cid=CP1MUNEUX
> Load native libraries in createKerberosHadoopAuthentication

- presto-mysql/src/test/java/io/prestosql/plugin/mysql/BaseMySqlIntegrationSmokeTest.java
- presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestGlobalTransactionMySqlIntegrationSmokeTest.java
- presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestingMySqlServer.java
Fixes #4997
Though "Files changed" tab mixes up actual changes, "Commits" tab shows clean diff. 
→ Squashed into a commit
> Add MySQL integration test with GTID mode

- presto-benchmark-driver/src/main/java/io/prestosql/benchmark/driver/BenchmarkQueryRunner.java
As well as https://github.com/prestosql/presto/pull/4887, we need to provide `X-Presto-User` header to retrieve the process CPU time in the benchmark-driver. 
```
./presto-benchmark-driver/target/presto-benchmark-driver-341-SNAPSHOT-executable.jar --suite-config ./presto-benchmark-driver/src/test/resources/groups.json --sql ./presto-benchmark-driver/src/test/resources/sql --debug --catalog tpch
2020-09-04T10:01:41.885+0900	INFO	main	io.airlift.log.Logging	Logging to stderr
suite	query	format	scale	wallTimeP50	wallTimeMean	wallTimeStd	processCpuTimeP50	processCpuTimeMean	processCpuTimeStd	queryCpuTimeP50	queryCpuTimeMean	queryCpuTimeStd	status	error
java.lang.NumberFormatException: For input string: "Basic authentication or X-Presto-User must be sent"
at …
```
> Set X-Presto-User header to retrieve CPU usage

- presto-server-main/etc/catalog/hive.properties
Make it usable out of the box with dockerized hive.
> Update hive catalog configuration for development

- presto-docs/src/main/sphinx/connector/hive-caching.rst
Fixes some inaccuracies introduced in https://github.com/prestosql/presto/pull/5107 and https://github.com/prestosql/presto/pull/4227
> Update caching limitations

- presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
- presto-main/src/test/java/io/prestosql/sql/query/TestShowQueries.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveSchema.java
Resolving Inconsistent error with DESCRIBE. 
Fixes #3006
> Resolving Inconsistent error with DESCRIBE

- presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueryFramework.java
Fixes https://github.com/prestosql/presto/issues/5120
> Wait for final QueryInfo before using in test

- presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
> Create temporary tables in mysql without key constraints

- presto-main/src/test/java/io/prestosql/execution/TestSqlTask.java
Fixes: https://github.com/prestosql/presto/issues/5191
> Fix flaky TestSqlTask tests

- docker/Dockerfile
- docker/container-test.sh
A follow up of #4642 
The `JAVA_HOME` has been changed after using new JDK package.
> Fixes JAVA_HOME in container image

- presto-spi/src/main/java/io/prestosql/spi/type/VarbinaryType.java
Follows https://github.com/prestosql/presto/pull/5200, i missed this one.
> Deprecate isVarbinaryType

- pom.xml
Depends on https://github.com/prestosql/presto-hive-apache/pull/16
> Update to Avro 1.9.2

- presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueryFramework.java
Allow to pass AutoCloseable to closeAfterClass
> Allow to pass AutoCloseable to closeAfterClass

- presto-main/src/test/java/io/prestosql/operator/scalar/time/TestTime.java
- presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestamp.java
- presto-main/src/test/java/io/prestosql/operator/scalar/timestamptz/TestTimestampWithTimeZone.java
- presto-main/src/test/java/io/prestosql/operator/scalar/timetz/TestTimeWithTimeZone.java
- presto-main/src/test/java/io/prestosql/type/TestDecimalOperators.java
- presto-main/src/test/java/io/prestosql/type/TestDecimalParametricType.java
- presto-spi/src/main/java/io/prestosql/spi/type/DecimalType.java
- presto-spi/src/main/java/io/prestosql/spi/type/LongDecimalType.java
- presto-spi/src/main/java/io/prestosql/spi/type/ShortDecimalType.java
- presto-spi/src/main/java/io/prestosql/spi/type/TimeType.java
- presto-spi/src/main/java/io/prestosql/spi/type/TimeWithTimeZoneType.java
- presto-spi/src/main/java/io/prestosql/spi/type/TimestampType.java
- presto-spi/src/main/java/io/prestosql/spi/type/TimestampWithTimeZoneType.java
Rationale: https://github.com/prestosql/presto/issues/5295
> Report offending precision when invalid

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveBucketing.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
Fixes https://github.com/prestosql/presto/issues/5295
> Fix accessing bucketed table with timestamp column

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-343.md
Closes https://github.com/prestosql/presto/issues/5290
> Add 343 release notes

- presto-docs/src/main/sphinx/connector/sqlserver.rst
> Add docs for additional aggregate pushdown functions for sql server

- presto-docs/src/main/sphinx/functions/binary.rst
- presto-main/src/main/java/io/prestosql/operator/scalar/VarbinaryFunctions.java
- presto-main/src/test/java/io/prestosql/operator/scalar/TestVarbinaryFunctions.java
> Add murmur3_hash function

- presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
Currently, `HivePageSourceProvider` overrides the deprecate `createPageSource` method:
https://github.com/prestosql/presto/blob/423a44190328d9ea66eb064d8389b986d959c157/presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java#L88
> Use non-deprecated createPageSource() in HivePageSourceProvider

- presto-main/src/main/java/io/prestosql/operator/scalar/timestamp/TimestampToTimestampCast.java
- presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestTimestamp.java
- presto-spi/src/main/java/io/prestosql/spi/type/LongTimestamp.java
Fixes https://github.com/prestosql/presto/issues/5310
> Fix rounding in long timestamp to long timestamp cast

- presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
This reverts commit 70e6061fea6db030b3fad01830a8494c6bc4e920.
This commit breaks Hive tests
> Revert "Use non-deprecated createPageSource() in HivePageSourceProvider"

- presto-jdbc/src/test/java/io/prestosql/jdbc/BaseTestJdbcResultSet.java
- presto-test-jdbc-compatibility-old-server/pom.xml
- presto-test-jdbc-compatibility-old-server/src/main/resources/presto-test-jdbc-compatibility-old-server-version.txt
- presto-test-jdbc-compatibility-old-server/src/test/java/io/prestosql/TestJdbcResultSetCompatibilityOldServer.java
Replace `assertThrows` with `assertThatThrownBy`.
> Check expected exceptions precisely in TestJdbcResultSet

- presto-spi/src/main/java/io/prestosql/spi/function/SqlNullable.java
Provide javadoc level documentation addtional to documentation already
existing in docs in presto-docs/src/main/sphinx/develop/functions.rst
> Document @SqlNullable

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/CachingJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/ForwardingJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/JdbcMetadata.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/JdbcClientStats.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/jmx/StatisticsAwareJdbcClient.java
- presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
Implements https://stackoverflow.com/questions/64063891/postgress-column-comment-in-presto
> Add support for setting column comment in PostgreSQL

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentListener.java
It only removes warnings from launcher output.
> Cancel scheduled futures used for container statistics reporting

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/docker/ContainerUtil.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/DockerContainer.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/Environment.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/common/Hadoop.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/common/Kafka.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/common/Standard.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/AbstractSinglenodeLdap.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeCassandra.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeMysql.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodePostgresql.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeSparkIceberg.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/SinglenodeSqlserver.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/TwoMixedHives.java
Sometimes environments fail to start because containers startup depend on each other
> Harden environment startup

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/StandardColumnMappings.java
- presto-main/src/main/java/io/prestosql/operator/scalar/timestamptz/TimestampWithTimeZoneToTimestampWithTimeZoneCast.java
- presto-main/src/test/java/io/prestosql/operator/scalar/timestamptz/TestTimestampWithTimeZone.java
- presto-mysql/src/test/java/io/prestosql/plugin/mysql/TestMySqlTypeMapping.java
- presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixSqlTypeMapping.java
- presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
- presto-testing/src/main/java/io/prestosql/testing/datatype/DataType.java
- presto-testing/src/test/java/io/prestosql/testing/datatype/TestDataType.java
Fixes https://github.com/prestosql/presto/issues/5371
> Improve time/timestamp/timestamp with time zone handling in PostgreSQL connector

- presto-docs/src/main/sphinx/connector/oracle.rst
Update Oracle connector documentation
> Update Oracle connector documentation

- presto-docs/src/main/sphinx/connector/elasticsearch.rst
- remove tables with duplicate content
- add security properties
- add ignoring publish address property
- fixes https://github.com/prestosql/presto/issues/4256
- fixes https://github.com/prestosql/presto/issues/5259
> Update Elastic search properties documentation

- pom.xml
- presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestingH2JdbcModule.java
- presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
- presto-main/src/test/java/io/prestosql/sql/query/QueryAssertions.java
- presto-testing/src/main/java/io/prestosql/testing/AbstractTestingPrestoClient.java
- presto-tests/pom.xml
- presto-tests/src/test/java/io/prestosql/tests/AbstractQueryAssertionsTest.java
- presto-tests/src/test/java/io/prestosql/tests/TestDistributedQueryAssertions.java
- presto-tests/src/test/java/io/prestosql/tests/TestLocalQueryAssertions.java
Fixes https://github.com/prestosql/presto/issues/5373
> Fix isCorrectlyPushedDown with session

- pom.xml
This version contains some fixes to t-digest and is a pre-requisite
to being able to add the t-digest type.
> Update to airlift 201

- presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcDeletedRows.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSourceFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/rcfile/RcFilePageSourceFactory.java
- presto-main/src/main/java/io/prestosql/connector/system/SystemPageSourceProvider.java
- presto-tests/src/test/java/io/prestosql/execution/TestBeginQuery.java
IIUC, it should have the same effect, but the code should be clearer with `EmptyPageSource`.
> Use EmptyPageSource instead of FixedPageSource over an empty list

- presto-docs/src/main/sphinx/connector/hive-security.rst
- presto-hive/src/main/java/io/prestosql/plugin/hive/security/AllowAllSecurityModule.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/security/HiveSecurityModule.java
> Add allow-all Hive security

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/RecordingHiveMetastore.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaRecordSetProvider.java
- presto-kinesis/src/main/java/io/prestosql/plugin/kinesis/KinesisRecordSetProvider.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/properties/KuduTableProperties.java
- presto-main/src/main/java/io/prestosql/sql/planner/SubExpressionExtractor.java
- presto-main/src/test/java/io/prestosql/cost/TestCostCalculator.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/test/PlanBuilder.java
- presto-redis/src/main/java/io/prestosql/plugin/redis/RedisRecordSetProvider.java
- presto-redis/src/main/java/io/prestosql/plugin/redis/decoder/hash/HashRedisRowDecoderFactory.java
Static import for immutable collection collectors
> Static import for immutable collection collectors

- presto-docs/src/main/sphinx/installation/jdbc.rst
> Make JDBC install guide more user-friendly

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastore.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/file/FileHiveMetastoreConfig.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/HiveQueryRunner.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileMetastore.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/file/TestFileHiveMetastoreConfig.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/optimizer/TestConnectorPushdownRulesWithHive.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/optimizer/TestHiveProjectionPushdownIntoTableScan.java
- presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergMetadataListing.java
- presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergOrcMetricsCollection.java
- presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/TestIcebergSystemTables.java
Extracted from, already approved by @losipiuk in https://github.com/prestosql/presto/pull/5430
> File metastore cleanup

- presto-main/src/main/java/io/prestosql/sql/planner/LogicalPlanner.java
- presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PruneExplainAnalyzeSourceColumns.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/UnaliasSymbolReferences.java
- presto-main/src/main/java/io/prestosql/sql/planner/plan/ExplainAnalyzeNode.java
- presto-main/src/main/java/io/prestosql/sql/planner/plan/Patterns.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestLogicalPlanner.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneExplainAnalyzeSourceColumns.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/test/PlanBuilder.java
- presto-main/src/test/java/io/prestosql/sql/planner/sanity/TestVerifyOnlyOneOutputNode.java
> Add column pruning for EXPLAIN ANALYZE 

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/HiveMetastoreModule.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/MetastoreTypeConfig.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/TestMetastoreTypeConfig.java
Per https://github.com/prestosql/presto/pull/5430#discussion_r500454796 preparation to https://github.com/prestosql/presto/pull/5430
> Rename MetastoreConfig to MetastoreTypeConfig

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentDefaults.java
Update docker images to version 34
> Update docker images to version 34

- presto-oracle/src/test/java/io/prestosql/plugin/oracle/TestOracleDistributedQueries.java
- presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
Make TestOracleDistributedQueries extensible
> Add more Oracle tests

- presto-main/src/main/java/io/prestosql/security/AccessControlManager.java
- presto-main/src/main/java/io/prestosql/server/testing/TestingPrestoServer.java
- presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
- presto-testing/pom.xml
- presto-testing/src/main/java/io/prestosql/testing/DistributedQueryRunner.java
Allow to set multiple system access control in tests
> Allow to set multiple system access controls in test

- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
Introduce Builder for FileBasedSystemAccessControl
That way it will be easier to setup FileBasedSystemAccessControl
instance in tests.
> Introduce Builder for FileBasedSystemAccessControl

- presto-main/src/main/java/io/prestosql/operator/NestedLoopJoinOperator.java
- presto-main/src/main/java/io/prestosql/operator/NestedLoopJoinPagesBuilder.java
- presto-main/src/test/java/io/prestosql/operator/TestNestedLoopBuildOperator.java
- presto-main/src/test/java/io/prestosql/operator/TestNestedLoopJoinOperator.java
- presto-spi/src/main/java/io/prestosql/spi/Page.java
Also adds a constructor to the `Page` class for when no blocks are passed as arguments.
> Improve nested loop operator

- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/FileBasedSystemAccessControl.java
Allow access default in FileBasedSystemAccessControl Builder
> Allow access default in FileBasedSystemAccessControl Builder

- docker/README.md
The class got renamed in 685ae601697810d5f3a3c925480fbc8019950964.
> Update docs after class name change

- presto-main/src/main/java/io/prestosql/server/security/ServerSecurityModule.java
- presto-main/src/main/java/io/prestosql/server/ui/WebUiAuthenticationModule.java
- src/modernizer/violations.xml
Using Modules.combine() instead of ConfigurationAwareModule.combine()
results in a hard to understand exception.
> Check for the right combine() method statically

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-344.md
Closes https://github.com/prestosql/presto/issues/5302
> Add 344 release notes

- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoMetadata.java
- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java
- presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoDistributedQueries.java
> Add support for adding column in MongoDB

- presto-main/src/main/java/io/prestosql/execution/buffer/ArbitraryOutputBuffer.java
- presto-main/src/main/java/io/prestosql/execution/buffer/PartitionedOutputBuffer.java
- presto-main/src/main/java/io/prestosql/operator/PartitionedOutputOperator.java
- Adds fast path for partitioning without constant arguments
- Simplify iterating through `PartitionedOutputBuffer` pages to one pass
- Use known-size builders where possible
> Minor improvements for partitioned output buffers and operator

- presto-docs/src/main/sphinx/installation/jdbc.rst
- presto-jdbc/src/main/java/io/prestosql/jdbc/ConnectionProperties.java
- presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoConnection.java
- presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoDriverUri.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcConnection.java
> Support source connection parameter in JDBC driver

- presto-docs/src/main/sphinx/admin/dynamic-filtering.rst
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveDynamicPartitionPruning.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestDynamicFilter.java
- presto-tests/src/test/java/io/prestosql/execution/TestCoordinatorDynamicFiltering.java
Fixes https://github.com/prestosql/presto/issues/5521
> Implement dynamic filtering for RIGHT JOIN

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/docker/DockerFiles.java
Do not throw checked exception from createTemporaryDirectoryForDocker
> Do not throw checked exception from createTemporaryDirectoryForDocker

- src/modernizer/violations.xml
See https://github.com/prestosql/presto/issues/5320 for rationale
> Forbid assertThrows

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/EnvironmentUp.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/Debug.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentModule.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/common/Standard.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/Multinode.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/MultinodeHiveCaching.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/MultinodeTls.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/MultinodeTlsKerberos.java
Disable Presto health checks on debug
> Disable Presto health checks on debug

- presto-hive/src/main/java/io/prestosql/plugin/hive/ViewReaderUtil.java
See https://github.com/prestosql/presto/pull/4661#discussion_r507056215
> Restore run as DEFINER for hive views

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/docker/DockerFiles.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/DockerContainer.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/environment/Multinode.java
Introduce HostDirectory
That way it is possible to extract a common directory for many files and
still be sure that each file that is accessed exists.
> Introduce ResourceProvider

- pom.xml
Fixes https://github.com/prestosql/presto/issues/5611
> Downgrade git-commit-id plugin

- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java
> Added debug query log for MongoDB #5600

- presto-main/src/test/java/io/prestosql/operator/scalar/TestJsonExtract.java
> Missing message in assertInvalidExtract

- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java
- presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoIntegrationSmokeTest.java
- presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoSession.java
> Translate null predicate correctly in mongodb connector

- presto-memsql/pom.xml
- presto-memsql/src/main/java/io/prestosql/plugin/memsql/MemSqlClient.java
- presto-memsql/src/main/java/io/prestosql/plugin/memsql/MemSqlClientModule.java
- presto-memsql/src/test/java/io/prestosql/plugin/memsql/TestMemSqlCaseInsensitiveMapping.java
- presto-memsql/src/test/java/io/prestosql/plugin/memsql/TestMemSqlDistributedQueries.java
- presto-memsql/src/test/java/io/prestosql/plugin/memsql/TestMemSqlIntegrationSmokeTest.java
- presto-memsql/src/test/java/io/prestosql/plugin/memsql/TestMemSqlTypeMapping.java
> Add TestMemSqlDistributedQueries and implement gaps

- presto-main/src/main/java/io/prestosql/server/ui/PasswordManagerFormAuthenticator.java
Fixes https://github.com/prestosql/presto/issues/5657
> Fail form authenticator when for no  password manager

- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/HdfsInputFile.java
This will help read stacktraces as in https://github.com/prestosql/presto/issues/5201.
> Add HdfsInputFile#toString

- presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSourceFactory.java
Rel https://github.com/prestosql/presto/issues/5569
> Improve error message when wrong ACID schema

- presto-main/src/test/java/io/prestosql/sql/planner/TestDomainCoercer.java
follows https://github.com/prestosql/presto/pull/5461
> Add extra test cases for DomainCoercer

- presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/metadata/TestRaptorMetadata.java
https://github.com/prestosql/presto/issues/1977
> Mark TestRaptorMetadata.testCreateBucketedTable as @Flaky

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveBucketedTables.java
Fixes a bug introduced in 44ad4321e3f5c5d63489906ddc1f33eaccf15e8a.
> Fix data preparation in testSelectFromIncompleteBucketedTableEmptyTablesAllowed

- presto-main/src/main/java/io/prestosql/server/ServerMainModule.java
Metrics from this class seem to be useful for monitoring GC patterns.
Verified on local deployment.
> Export GCMonitor jmx mbean

- presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryMetadata.java
- presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryPageSourceProvider.java
- presto-bigquery/src/test/java/io/prestosql/plugin/bigquery/TestBigQueryIntegrationSmokeTest.java
> Fix projection pushdown in BigQuery connector

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveColumnHandle.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HivePageSourceProvider.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HivePartitionManager.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveTableHandle.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/alluxio/ProtoUtils.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveBucketing.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHivePageSink.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveTableHandle.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestNodeLocalDynamicSplitPruning.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/benchmark/FileFormat.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/alluxio/TestProtoUtils.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/optimizer/TestConnectorPushdownRulesWithHive.java
Fixes https://github.com/prestosql/presto/issues/4921
> Implement node local dynamic bucket pruning

- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueHiveMetastore.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/metastore/glue/GlueMetastoreStats.java
Extracted relevant parts from https://github.com/prestodb/presto/pull/15355 that weren't already available from https://github.com/prestosql/presto/pull/2717
> Add AWS SDK client request metrics to GlueMetastoreStats

- presto-jdbc/src/main/java/io/prestosql/jdbc/ConnectionProperties.java
- presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoDriverUri.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDriverAuth.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDriverUri.java
Fixes https://github.com/prestosql/presto/issues/5246
> Implement SSLVerification parameter to JDBC driver

- presto-hive/src/main/java/io/prestosql/plugin/hive/GenericHiveRecordCursor.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/ViewReaderUtil.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcFileWriterFactory.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/orc/OrcPageSource.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/s3select/PrestoS3ClientFactory.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHivePageSink.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestReaderProjectionsAdapter.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/util/TestHiveUtil.java
> Refactor out unused var in presto-hive

- presto-docs/src/main/sphinx/installation/jdbc.rst
cc @kokosing 
relates to https://github.com/prestosql/presto/issues/5246
relates to https://github.com/prestosql/presto/pull/5610
> Document SSLVerification parameter of JDBC driver

- presto-main/src/main/java/io/prestosql/operator/ExchangeClientConfig.java
- presto-main/src/main/java/io/prestosql/operator/scalar/DateTimeFunctions.java
- presto-main/src/main/java/io/prestosql/server/HttpRequestSessionContext.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/ScalarAggregationToJoinRewriter.java
- presto-main/src/main/java/io/prestosql/testing/DateTimeTestingUtils.java
- presto-main/src/main/java/io/prestosql/testing/MaterializedResult.java
- presto-main/src/main/java/io/prestosql/type/RealOperators.java
- presto-main/src/test/java/io/prestosql/execution/BenchmarkNodeScheduler.java
- presto-main/src/test/java/io/prestosql/execution/TestStageStateMachine.java
- presto-main/src/test/java/io/prestosql/operator/BenchmarkGroupByHash.java
- presto-main/src/test/java/io/prestosql/operator/BenchmarkScanFilterAndProjectOperator.java
- presto-main/src/test/java/io/prestosql/operator/aggregation/BenchmarkGroupedTypedHistogram.java
- presto-main/src/test/java/io/prestosql/sql/TestExpressionInterpreter.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestPredicatePushdown.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPushTopNThroughProject.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestSwapAdjacentWindowsBySpecifications.java
- presto-main/src/test/java/io/prestosql/type/BenchmarkDecimalOperators.java
> Remove unused var in presto-main

- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
> Add tests for filter by partitions in thrift hive metastore

- presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
- presto-main/src/main/java/io/prestosql/metadata/ProcedureRegistry.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/ExpressionEquivalence.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
- presto-main/src/main/java/io/prestosql/sql/planner/planprinter/JsonRenderer.java
- presto-main/src/main/java/io/prestosql/sql/planner/sanity/TypeValidator.java
- presto-main/src/main/java/io/prestosql/sql/planner/sanity/ValidateStreamingAggregations.java
- presto-main/src/test/java/io/prestosql/execution/TestSqlTaskExecution.java
> Refactor unused ctor args in presto-main

- presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
Relates to: https://github.com/prestosql/presto/issues/5758
Follows https://github.com/prestosql/presto/pull/5501
> Include exception cause

- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoColumnHandle.java
- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoPageSink.java
- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoPageSinkProvider.java
- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java
> Refactor unused var in presto-mongodb

- presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryClient.java
- presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryConnectorFactory.java
- presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQueryConnectorModule.java
- presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQuerySplitManager.java
> Refactor unused var in presto-bigquery

- presto-main/src/main/java/io/prestosql/memory/ClusterMemoryManager.java
- presto-main/src/main/java/io/prestosql/server/CoordinatorModule.java
- presto-tests/src/test/java/io/prestosql/execution/TestExecutionJmxMetrics.java
> Honor jmx.base-name when exporting MBean

- presto-spi/src/main/java/io/prestosql/spi/type/CharType.java
- presto-spi/src/main/java/io/prestosql/spi/type/Slices.java
- presto-spi/src/main/java/io/prestosql/spi/type/VarcharType.java
Relates to https://github.com/prestosql/presto/issues/5738
> Add char, varchar wellformedness checks

- presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetWriters.java
- presto-parquet/src/main/java/io/prestosql/parquet/writer/PrimitiveColumnWriter.java
- presto-parquet/src/main/java/io/prestosql/parquet/writer/StructColumnWriter.java
> Remove unused variables in presto-parquet

- presto-main/src/main/java/io/prestosql/testing/MaterializedResult.java
- presto-main/src/test/java/io/prestosql/operator/scalar/AbstractTestExtract.java
- presto-main/src/test/java/io/prestosql/operator/scalar/date/TestExtract.java
- presto-main/src/test/java/io/prestosql/operator/scalar/time/TestExtract.java
- presto-main/src/test/java/io/prestosql/operator/scalar/timestamp/TestExtract.java
- presto-main/src/test/java/io/prestosql/operator/scalar/timestamptz/TestExtract.java
- presto-main/src/test/java/io/prestosql/operator/scalar/timetz/TestExtract.java
cc @martint @choiwaiyiu 
relates to https://github.com/prestosql/presto/issues/5626
relates to https://github.com/prestosql/presto/issues/5627
> Introduce AbstractTestExtract

- presto-main/src/test/java/io/prestosql/server/remotetask/TestHttpRemoteTask.java
Fixes: https://github.com/prestosql/presto/issues/5809
> Fix flaky TestHttpRemoteTask#testDynamicFilters

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveStorageFormats.java
relates to https://github.com/prestosql/presto/issues/4936
> Mark TestHiveStorageFormats.testCreatePartitionedTableAs as @Flaky

- presto-main/src/main/java/io/prestosql/security/SecurityContext.java
- presto-spi/src/main/java/io/prestosql/spi/security/Identity.java
This yields for more useful logging with e.g.
`LoggingInvocationHandler`, as currently configured in
`io.prestosql.security.AccessControlModule#createAccessControl`.
> Add SecurityContext#toString

- pom.xml
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java
Fix #5785 
This PR is to gather early feedback on the testing. The coral version needs to be upgraded after https://github.com/linkedin/coral/pull/19 is merged and released.
> Upgrade coral to resolve catalog correctly for underlying tables

- presto-hive/src/main/java/io/prestosql/plugin/hive/statistics/MetastoreHiveStatisticsProvider.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
- presto-main/src/main/java/io/prestosql/testing/TestingSession.java
- presto-main/src/test/java/io/prestosql/execution/TestDeallocateTask.java
- presto-main/src/test/java/io/prestosql/execution/TestPrepareTask.java
- presto-main/src/test/java/io/prestosql/execution/TestQueryStateMachine.java
- presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
- presto-plugin-toolkit/src/main/java/io/prestosql/plugin/base/security/AllowAllSystemAccessControl.java
Motivation: https://github.com/prestosql/presto/pull/5756/commits/50e3fcc51c76064fe5c3f94167483609535ebb2c
> Propagate stat calculation failures in tests

- presto-kudu/src/main/java/io/prestosql/plugin/kudu/KuduClientSession.java
- presto-kudu/src/main/java/io/prestosql/plugin/kudu/properties/KuduTableProperties.java
> Remove unused var in presto-kudu

- presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/TestRaptorIntegrationSmokeTest.java
Relates to https://github.com/prestosql/presto/issues/1977
> Fix pattern in @Flaky annotation

- presto-main/src/main/java/io/prestosql/sql/planner/PlanOptimizers.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PruneUnreferencedOutputs.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/BasePlanTest.java
- presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestEliminateSorts.java
- presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestMergeWindows.java
- presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestOptimizeMixedDistinctAggregations.java
- presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestReorderWindows.java
- presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestSetFlattening.java
> Remove unused PruneUnreferencedOutputs#typeAnalyzer field

- presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationPushDown.java
make test messages orderly as expected.
add data dump when test case fail.
Signed-off-by: Li Wang <wangli@thinkingdata.cn>
> kafka connector: optimize Kafka timestamp test case.

- .github/workflows/ci.yml
- pom.xml
- presto-atop/src/test/java/io/prestosql/plugin/atop/TestAtopSecurity.java
- presto-druid/pom.xml
- presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/ElasticsearchServer.java
- presto-elasticsearch/src/test/java/io/prestosql/elasticsearch/TestPasswordAuthentication.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveFileBasedSecurity.java
- presto-main/src/main/java/io/prestosql/server/ui/LoginResource.java
- presto-main/src/test/java/io/prestosql/execution/scheduler/TestFileBasedNetworkTopology.java
- presto-memsql/pom.xml
- presto-pinot/src/test/java/io/prestosql/pinot/TestDynamicTable.java
- presto-pinot/src/test/java/io/prestosql/pinot/TestMinimalFunctionality.java
- presto-pinot/src/test/java/io/prestosql/pinot/TestingPinotCluster.java
- presto-pinot/src/test/java/io/prestosql/pinot/TestingPinotHostMapper.java
- presto-product-tests-launcher/pom.xml
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/EnvironmentUp.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/Environments.java
- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/StatisticsFetcher.java
- presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/security/TestRaptorFileBasedSecurity.java
- presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestingSqlServer.java
- presto-testing-kafka/src/main/java/io/prestosql/testing/kafka/TestingKafka.java
The RC2 version contains a fix for
https://github.com/testcontainers/testcontainers-java/issues/3166.
The update requires changes due to https://github.com/testcontainers/testcontainers-java/commit/1c97b978ac6ccfba0119986c22e4ac6d9ac955fa
> Update to testcontainers to fix running tests on Mac

- presto-geospatial/src/test/java/io/prestosql/plugin/geospatial/aggregation/TestGeometryUnionGeoAggregation.java
> Remove unused arg in TestGeometryUnionGeoAggregation#assertArrayAggAndGeometryUnion

- presto-druid/src/test/java/io/prestosql/plugin/druid/TestDruidErrorCode.java
> Fix incorrect error code in DruidErrorCode

- presto-main/src/main/java/io/prestosql/connector/informationschema/InformationSchemaMetadata.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/TypeSignatureTranslator.java
- presto-main/src/main/java/io/prestosql/sql/gen/JoinFilterFunctionCompiler.java
- presto-main/src/main/java/io/prestosql/sql/gen/PageFunctionCompiler.java
- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java
- presto-main/src/test/java/io/prestosql/block/TestColumnarRow.java
- presto-main/src/test/java/io/prestosql/server/protocol/TestQueryResultRows.java
- presto-main/src/test/java/io/prestosql/sql/gen/TestExpressionCompiler.java
> Refactor unused function args in presto-main

- presto-accumulo/src/main/java/io/prestosql/plugin/accumulo/AccumuloConnector.java
- presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/AbstractTestIcebergSmoke.java
- presto-main/src/test/java/io/prestosql/operator/TestAggregationOperator.java
- presto-main/src/test/java/io/prestosql/operator/aggregation/minmaxby/TestMinMaxByAggregation.java
- presto-main/src/test/java/io/prestosql/operator/scalar/FunctionAssertions.java
- presto-ml/src/main/java/io/prestosql/plugin/ml/ModelUtils.java
- presto-orc/src/test/java/io/prestosql/orc/TestOrcLz4.java
- presto-password-authenticators/src/main/java/io/prestosql/plugin/password/ldap/LdapConfig.java
- presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/TypeUtils.java
- presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/metadata/TestShardPredicate.java
- presto-spi/src/test/java/io/prestosql/spi/predicate/TestTupleDomain.java
- presto-tpcds/src/test/java/io/prestosql/plugin/tpcds/EstimateAssertion.java
#4188
Cleanup the remaining unused variables scattered through multiple modules.
> Remove unused variables

- presto-product-tests/src/main/java/io/prestosql/tests/iceberg/TestIcebergCreateTable.java
Relates to https://github.com/prestosql/presto/issues/4864
cc @vrozov @djsstarburst
> Mark TestIcebergCreateTable as @Flaky

- presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaInternalFieldManager.java
- presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaInternalFieldManager.java
> Fix incorrect comment in Kafka.InternalField

- presto-jdbc/pom.xml
- presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoDatabaseMetaData.java
- presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoPreparedStatement.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcPreparedStatement.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestPrestoDatabaseMetaData.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestingJdbcUtils.java
Fixes #1777 
This is initial implementation without optimization.
> Add support for batching in JDBC driver

- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoMetadata.java
- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoSession.java
- presto-mongodb/src/main/java/io/prestosql/plugin/mongodb/MongoTableHandle.java
- presto-mongodb/src/test/java/io/prestosql/plugin/mongodb/TestMongoIntegrationSmokeTest.java
> Add support for limit pushdown in MongoDB

- docker/Dockerfile
> Use CentOS 8

- presto-main/src/main/java/io/prestosql/execution/scheduler/SubnetBasedTopology.java
- presto-main/src/main/java/io/prestosql/execution/scheduler/SubnetTopologyConfig.java
- presto-main/src/main/java/io/prestosql/execution/scheduler/TopologyAwareNodeSelectorConfig.java
- presto-main/src/main/java/io/prestosql/execution/scheduler/TopologyAwareNodeSelectorModule.java
- presto-main/src/test/java/io/prestosql/execution/scheduler/TestSubnetTopology.java
- presto-main/src/test/java/io/prestosql/execution/scheduler/TestSubnetTopologyConfig.java
- presto-spi/src/main/java/io/prestosql/spi/HostAddress.java
Add a new implementation of NetworkTopology that creates segments based on CIDR prefix lengths.
> Add subnet based topology

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/cli/TestRun.java
Assume tests container is started immediately
> Assume tests container is started immediately

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/suite/suites/Suite3.java
It was working but inconsistent with the other suite definitions
> Fix suite-3 definition

- presto-spi/src/main/java/io/prestosql/spi/block/EncoderUtil.java
```
AFTER
Benchmark                                    Mode  Cnt  Score   Error  Units
BenchmarkBlockSerde.deserializeLineitem      avgt   60  1,173 ± 0,019  ns/op
BenchmarkBlockSerde.deserializeLongWithNull  avgt   60  2,286 ± 0,032  ns/op
BenchmarkBlockSerde.serializeLineitem        avgt   60  3,512 ± 0,039  ns/op
BenchmarkBlockSerde.serializeLongWithNull    avgt   60  2,425 ± 0,030  ns/op
BEFORE
Benchmark                                    Mode  Cnt  Score   Error  Units
BenchmarkBlockSerde.deserializeLineitem      avgt   60  1,187 ± 0,015  ns/op
BenchmarkBlockSerde.deserializeLongWithNull  avgt   60  2,474 ± 0,022  ns/op
BenchmarkBlockSerde.serializeLineitem        avgt   60  3,579 ± 0,046  ns/op
BenchmarkBlockSerde.serializeLongWithNull    avgt   60  3,252 ± 0,030  ns/op
```
1/3 …
> Avoid readByte and appendByte in nulls to bits serde

- README.md
- presto-docs/src/main/sphinx/installation/deployment.rst
- presto-main/src/main/java/io/prestosql/server/PrestoSystemRequirements.java
Earlier versions are affected by JDK-8206955.
> Require Java 11.0.7

- presto-docs/src/main/sphinx/installation/deployment.rst
> Clarify Java requirement

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/docker/ContainerUtil.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCoercion.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTransactionalTable.java
> Remove unused var in presto-product-tests

- presto-atop/src/main/java/io/prestosql/plugin/atop/AtopMetadata.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/AbstractTestHive.java
- presto-jmx/src/test/java/io/prestosql/plugin/jmx/TestJmxHistoricalData.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/json/JsonRowEncoder.java
- presto-main/src/main/java/io/prestosql/server/HttpRequestSessionContext.java
- presto-main/src/test/java/io/prestosql/sql/planner/BenchmarkPlanner.java
- presto-parser/src/main/java/io/prestosql/sql/parser/AstBuilder.java
- presto-parser/src/main/java/io/prestosql/sql/tree/BinaryLiteral.java
- presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixClient.java
- presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/TypeUtils.java
- presto-resource-group-managers/src/main/java/io/prestosql/plugin/resourcegroups/AbstractResourceConfigurationManager.java
- presto-resource-group-managers/src/main/java/io/prestosql/plugin/resourcegroups/ResourceGroupSpec.java
- presto-tpch/src/main/java/io/prestosql/plugin/tpch/TpchConnectorFactory.java
- presto-verifier/src/main/java/io/prestosql/verifier/VerifierConfig.java
- src/modernizer/violations.xml
This mirrors the existing rule for toLowerCase
> Add modernizer rule for String.toUpperCase

- presto-tests/src/test/java/io/prestosql/execution/EventsAwaitingQueries.java
- presto-tests/src/test/java/io/prestosql/execution/EventsCollector.java
- presto-tests/src/test/java/io/prestosql/execution/TestCompletedEventWarnings.java
- presto-tests/src/test/java/io/prestosql/execution/TestConnectorEventListener.java
- presto-tests/src/test/java/io/prestosql/execution/TestEventListener.java
- presto-tests/src/test/java/io/prestosql/execution/TestEventListenerBasic.java
- presto-tests/src/test/java/io/prestosql/execution/TestEventListenerPlugin.java
- presto-tests/src/test/java/io/prestosql/execution/TestEventListenerWithSplits.java
- presto-tests/src/test/java/io/prestosql/execution/TestingEventListener.java
Should fix (or at least highly decrease probability of)  #5928
> Improvements to TestEventListener

- presto-main/src/main/java/io/prestosql/execution/CreateMaterializedViewTask.java
- presto-main/src/main/java/io/prestosql/execution/CreateViewTask.java
- presto-main/src/main/java/io/prestosql/execution/SqlQueryExecution.java
- presto-main/src/main/java/io/prestosql/server/testing/TestingPrestoServer.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/Analyzer.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/ExpressionAnalyzer.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/QueryExplainer.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
- presto-main/src/main/java/io/prestosql/sql/planner/TypeAnalyzer.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/DescribeInputRewrite.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/DescribeOutputRewrite.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/ExplainRewrite.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/ShowStatsRewrite.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/StatementRewrite.java
- presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
- presto-main/src/main/java/io/prestosql/testing/QueryRunner.java
- presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
- presto-main/src/main/java/io/prestosql/testing/TestingGroupProvider.java
- presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
- presto-testing/src/main/java/io/prestosql/testing/AbstractTestDistributedQueries.java
- presto-testing/src/main/java/io/prestosql/testing/AbstractTestQueryFramework.java
- presto-testing/src/main/java/io/prestosql/testing/DistributedQueryRunner.java
- presto-testing/src/main/java/io/prestosql/testing/StandaloneQueryRunner.java
- presto-thrift/src/test/java/io/prestosql/plugin/thrift/integration/ThriftQueryRunner.java
> Populate view owner groups for view access control

- pom.xml
- presto-postgresql/pom.xml
Update Postgresql JDBC to 42.2.10
> Update Postgresql JDBC to 42.2.10

- presto-tests/pom.xml
- presto-tests/src/test/java/io/prestosql/tests/TestQuerySerializationFailures.java
Relates to: https://github.com/prestosql/presto/issues/4173
> Mark shouldFailOnFirstSerializationError as @Flaky

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java
Relates to: https://github.com/prestosql/presto/issues/5606
> Test Hive VIEW with JOIN and subquery

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/EnvironmentListener.java
> Remove stats fetcher to test for hangs

- pom.xml
> Bump hive-apache to 3.1.2-5

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveViews.java
A small TEXTFILE is slightly faster to write.
> Use TEXTFILE format in TestHiveViews

- presto-druid/src/test/java/io/prestosql/plugin/druid/DruidQueryRunner.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveMetadata.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveWriterFactory.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/alluxio/TestingAlluxioMetastoreObjects.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/TestGlueExpressionUtil.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/metastore/glue/TestHiveGlueMetastore.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/parquet/TestParquetDecimalScaling.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/BaseTestJdbcResultSet.java
- presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationPushDown.java
- presto-kinesis/src/test/java/io/prestosql/plugin/kinesis/TestRecordAccess.java
- presto-main/src/main/java/io/prestosql/metadata/FunctionDependencies.java
- presto-main/src/main/java/io/prestosql/metadata/FunctionDependencyDeclaration.java
- presto-main/src/main/java/io/prestosql/operator/DynamicFilterSourceOperator.java
- presto-main/src/main/java/io/prestosql/operator/scalar/timestamptz/ToIso8601.java
- presto-main/src/main/java/io/prestosql/type/DateTimes.java
- presto-parquet/src/main/java/io/prestosql/parquet/ChunkKey.java
- presto-parquet/src/main/java/io/prestosql/parquet/writer/ParquetCompressor.java
- presto-password-authenticators/src/main/java/io/prestosql/plugin/password/salesforce/SalesforceBasicAuthenticator.java
- presto-password-authenticators/src/test/java/io/prestosql/plugin/password/salesforce/TestSalesforceBasicAuthenticator.java
- presto-prometheus/src/main/java/io/prestosql/plugin/prometheus/PrometheusClient.java
- presto-spi/src/main/java/io/prestosql/spi/type/TypeOperators.java
- presto-testing/src/main/java/io/prestosql/testing/datatype/DataTypeTest.java
Use static imports for String.format
> Use static imports for String.format

- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/CreateEmptyPartitionProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/DropStatsProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/RegisterPartitionProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/SyncPartitionMetadataProcedure.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/procedure/UnregisterPartitionProcedure.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
- presto-main/src/main/java/io/prestosql/execution/CallTask.java
- presto-main/src/main/java/io/prestosql/metadata/ProcedureRegistry.java
- presto-main/src/main/java/io/prestosql/security/InjectedConnectorAccessControl.java
- presto-main/src/test/java/io/prestosql/execution/TestCallTask.java
- presto-main/src/test/java/io/prestosql/security/TestInjectedConnectorAccessControl.java
- presto-spi/src/main/java/io/prestosql/spi/procedure/Procedure.java
>  Validate user objects for HiveProcedures

- pom.xml
- presto-hive-hadoop2/src/test/java/io/prestosql/plugin/hive/TestHiveFileSystemAbfsAccessKey.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/ViewReaderUtil.java
- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/IcebergMetadata.java
- presto-main/src/main/java/io/prestosql/type/UnknownType.java
- presto-main/src/test/java/io/prestosql/execution/buffer/TestBroadcastOutputBuffer.java
- presto-main/src/test/java/io/prestosql/operator/TestAnnotationEngineForScalars.java
- presto-main/src/test/java/io/prestosql/operator/TestGroupedTopNBuilder.java
- presto-plugin-toolkit/src/test/java/io/prestosql/plugin/base/security/TestFileBasedSystemAccessControl.java
- presto-spi/src/main/java/io/prestosql/spi/type/UnscaledDecimal128Arithmetic.java
#4188 Enable `UnusedVariable` error prone check
> Enable unused variable error prone check

- presto-product-tests/src/main/java/io/prestosql/tests/iceberg/TestIcebergCreateTable.java
Rels https://github.com/prestosql/presto/issues/4864
> Attempt to fix TestIcebergCreateTable retries

- presto-main/src/test/java/io/prestosql/execution/buffer/BenchmarkBlockSerde.java
- presto-main/src/test/java/io/prestosql/execution/buffer/TestingPagesSerdeFactory.java
- presto-spi/src/test/java/io/prestosql/spi/block/TestingBlockEncodingSerde.java
Add more block types - Int96, int, short and byte
Add variable amount of nulls as a parameter.
There are no changes in the actual implementations or tests.
> Expand BenchmarkBlockSerde

- presto-testng-services/src/main/java/io/prestosql/testng/services/FlakyTestRetryAnalyzer.java
Allow to control FlakyTestRetryAnalyzer with session property
Now session property overrides CONTINUOUS_INTEGRATION. So even when
CONTINUOUS_INTEGRATION is set, FlakyTestRetryAnalyzer can be disabled
with the session property.
> Allow to control FlakyTestRetryAnalyzer with session property

- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/PostgreSqlQueryRunner.java
- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
Extracted from https://github.com/prestosql/presto/pull/6054
> Remove createPostgreSqlQueryRunner overload

- presto-docs/src/main/sphinx/connector/hive.rst
- presto-docs/src/main/sphinx/optimizer/statistics.rst
> Add link to statistics page from Hive connector

- presto-redis/src/test/java/io/prestosql/plugin/redis/TestingRedisPlugin.java
- presto-redis/src/test/java/io/prestosql/plugin/redis/util/RedisTestUtils.java
Move testing facilities out to a testing class.
> Make RedisPlugin immutable

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-347.md
Closes https://github.com/prestosql/presto/issues/5912
> Add 347 release notes

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/CachingJdbcClient.java
Utilize guava cache.get(key, loader) instead of custom way of loading.
loader is able to handle external context, which addresses constraint:
columns depend on session and session cannot be used in cache key
This pr is a small step toward merging https://github.com/prestosql/presto/pull/6067
> Simplify loading columns into cache in CachingJdbcClient

- presto-product-tests-launcher/src/main/java/io/prestosql/tests/product/launcher/env/DockerContainer.java
Fixes #6079
proposed alternative to https://github.com/prestosql/presto/pull/6080
> Fix container startup time measurements when start retried

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/CachingJdbcClient.java
Loader in cache.get(key, loader) is able to refer
to state other than that in the key.
This is a preparation step for enhancing some loaders
with necessary runtime information (e.g. query id)
which cannot be stored within cache key.
> Use Cache instead of LoadingCache

- presto-main/src/test/java/io/prestosql/execution/buffer/BenchmarkBlockSerde.java
- presto-main/src/test/java/io/prestosql/execution/buffer/BenchmarkDataGenerator.java
This PR consists of first two commits of https://github.com/prestosql/presto/pull/6077
> SImplify benchmark block serde

- presto-main/src/test/java/io/prestosql/sql/planner/TestUnwrapCastInComparison.java
> Use case sensitive alias in planner test

- presto-cli/src/main/java/io/prestosql/cli/AlignedTablePrinter.java
- presto-cli/src/main/java/io/prestosql/cli/CsvPrinter.java
- presto-client/src/main/java/io/prestosql/client/FixJsonDataUtils.java
- presto-client/src/main/java/io/prestosql/client/Row.java
- presto-client/src/main/java/io/prestosql/client/RowField.java
- presto-client/src/test/java/io/prestosql/client/TestFixJsonDataUtils.java
- presto-jdbc/src/main/java/io/prestosql/jdbc/AbstractPrestoResultSet.java
- presto-jdbc/src/main/java/io/prestosql/jdbc/Row.java
- presto-jdbc/src/main/java/io/prestosql/jdbc/RowField.java
- presto-jdbc/src/main/java/io/prestosql/jdbc/TypeConversions.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/BaseTestJdbcResultSet.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCoercion.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestReadUniontype.java
- presto-test-jdbc-compatibility-old-driver/src/test/java/io/prestosql/TestJdbcCompatibility.java
- presto-testing/src/main/java/io/prestosql/testing/TestingPrestoClient.java
Fixes https://github.com/prestosql/presto/issues/4587
> Change ROW representation on the client to avoid fake row field names

- presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/json/format/MillisecondsSinceEpochFormatter.java
- presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/json/format/SecondsSinceEpochFormatter.java
- presto-kafka/src/test/java/io/prestosql/plugin/kafka/encoder/json/TestJsonEncoder.java
- presto-kafka/src/test/java/io/prestosql/plugin/kafka/encoder/json/TestMillisecondsJsonDateTimeFormatter.java
- presto-kafka/src/test/java/io/prestosql/plugin/kafka/encoder/json/TestSecondsJsonDateTimeFormatter.java
> Support writing TIMESTAMPTZ with JSON encoder

- presto-main/src/main/java/io/prestosql/sql/planner/iterative/rule/PushAggregationThroughOuterJoin.java
- presto-main/src/main/java/io/prestosql/sql/planner/optimizations/SymbolMapper.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestHaving.java
- presto-main/src/test/java/io/prestosql/sql/planner/TestLogicalPlanner.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/AggregationMatcher.java
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/PlanMatchPattern.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestAddIntermediateAggregations.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneAggregationColumns.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneAggregationSourceColumns.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPruneOrderByInAggregation.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPushAggregationThroughOuterJoin.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestPushPartialAggregationThroughJoin.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestSingleDistinctAggregationToGroupBy.java
- presto-main/src/test/java/io/prestosql/sql/planner/iterative/rule/TestTransformFilteringSemiJoinToInnerJoin.java
- presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestOptimizeMixedDistinctAggregations.java
- presto-main/src/test/java/io/prestosql/sql/planner/optimizations/TestWindow.java
- presto-tests/src/test/java/io/prestosql/tests/AbstractTestEngineOnlyQueries.java
Fixes https://github.com/prestosql/presto/issues/6138
> Fix missing dependencies due to Aggregation through Join pushdown

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/StandardColumnMappings.java
- presto-druid/src/main/java/io/prestosql/plugin/druid/DruidJdbcClient.java
- presto-mysql/src/main/java/io/prestosql/plugin/mysql/MySqlClient.java
- presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixClient.java
- presto-postgresql/src/main/java/io/prestosql/plugin/postgresql/PostgreSqlClient.java
- presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java
Extracted from https://github.com/prestosql/presto/pull/4940
> Supplement type mappings in JDBC connectors

- presto-docs/src/main/sphinx/admin.rst
- presto-docs/src/main/sphinx/admin/graceful-shutdown.rst
This PR adds graceful shutdown documentation and  Fixes #3641. The documentation covers how to initiate a graceful shutdown, what considerations you should have when doing so, and also how the internal logic works.
> Add graceful shutdown documentation.

- presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/TestRaptorIntegrationSmokeTest.java
- presto-raptor-legacy/src/test/java/io/prestosql/plugin/raptor/legacy/metadata/TestRaptorMetadata.java
Relates to https://github.com/prestosql/presto/issues/1977
> Fix retries in TestRaptorIntegrationSmokeTest.testCreateBucketedTable

- presto-hive/pom.xml
- presto-hive/src/test/java/io/prestosql/plugin/hive/parquet/AbstractTestParquetReader.java
https://github.com/prestosql/presto/issues/4984
> Mark testArrayOfMapOfStruct and testDoubleNaNInfinity  as @Flaky

- presto-docs/src/main/sphinx/admin/properties-node-scheduler.rst
> Add documentation for subnet based topology

- presto-jdbc/src/main/java/io/prestosql/jdbc/AbstractPrestoResultSet.java
- presto-jdbc/src/main/java/io/prestosql/jdbc/ColumnInfo.java
- presto-jdbc/src/main/java/io/prestosql/jdbc/TypeConversions.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/BaseTestJdbcResultSet.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestAbstractPrestoResultSet.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcResultSet.java
- presto-product-tests/README.md
- presto-product-tests/src/main/java/io/prestosql/tests/TestSystemConnector.java
- presto-product-tests/src/main/java/io/prestosql/tests/cassandra/TestSelect.java
- presto-test-jdbc-compatibility-old-driver/src/test/java/io/prestosql/JdbcDriverCapabilities.java
- presto-test-jdbc-compatibility-old-driver/src/test/java/io/prestosql/TestJdbcCompatibility.java
Fixes https://github.com/prestosql/presto/issues/6048 and fixes https://github.com/prestosql/presto/issues/6251
Extracted from https://github.com/prestosql/presto/pull/307
> Convert array elements to proper representation

- presto-postgresql/src/test/java/io/prestosql/plugin/postgresql/TestPostgreSqlTypeMapping.java
The `key` column is not a subject of the test, so it should use the type
as declared.
> Fix test case for INSERT with unsupported type

- presto-client/src/main/java/io/prestosql/client/ClientStandardTypes.java
- presto-client/src/main/java/io/prestosql/client/FixJsonDataUtils.java
- presto-geospatial/pom.xml
- presto-geospatial/src/test/java/io/prestosql/plugin/geospatial/TestGeoSpatialQueries.java
- presto-main/src/test/java/io/prestosql/sql/query/QueryAssertions.java
- presto-testing/src/main/java/io/prestosql/testing/TestingPrestoClient.java
Fixes https://github.com/prestosql/presto/issues/6238
> Fix SphericalGeography handling on the client

- presto-main/src/main/java/io/prestosql/execution/buffer/ArbitraryOutputBuffer.java
- presto-main/src/main/java/io/prestosql/execution/buffer/BroadcastOutputBuffer.java
- presto-main/src/main/java/io/prestosql/execution/buffer/ClientBuffer.java
- presto-main/src/main/java/io/prestosql/execution/buffer/LazyOutputBuffer.java
- presto-main/src/main/java/io/prestosql/execution/buffer/PartitionedOutputBuffer.java
- presto-main/src/main/java/io/prestosql/execution/buffer/SerializedPageReference.java
- presto-main/src/test/java/io/prestosql/execution/buffer/TestClientBuffer.java
Changes extracted from https://github.com/prestodb/presto/pull/15477
Two commits attempting to reduce lock contention related to output buffers:
- Refactors LazyOutputBuffer to attempt to read the delegate OutputBuffer reference before synchronizing
- Refactor `SerializedPageReference` and usages to perform dereferencing in batches to avoid a per-page synchronization on memory manager locks
> Reduce output buffer lock contention

- presto-iceberg/src/main/java/io/prestosql/plugin/iceberg/InternalIcebergConnectorFactory.java
> Support GCS and Azure for Iceberg

- presto-iceberg/pom.xml
- presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/AbstractTestIcebergSmoke.java
Relates to https://github.com/prestosql/presto/issues/5201
> Mark TestIcebergParquetSmoke as @Flaky

- presto-main/src/main/java/io/prestosql/metadata/MetadataManager.java
- presto-tests/src/test/java/io/prestosql/tests/TestMetadataManager.java
Fixes https://github.com/prestosql/presto/issues/6239
> Return table or view when listing for tables with fully qualified name

- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcConfig.java
- presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/StandardColumnMappings.java
- presto-base-jdbc/src/test/java/io/prestosql/plugin/jdbc/TestBaseJdbcConfig.java
- presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixClient.java
- presto-phoenix/src/main/java/io/prestosql/plugin/phoenix/PhoenixConfig.java
- presto-phoenix/src/test/java/io/prestosql/plugin/phoenix/TestPhoenixConfig.java
Relates to: https://github.com/prestosql/presto/issues/4914
> Deprecate legacy generic type mappings

- presto-jdbc/src/main/java/io/prestosql/jdbc/AbstractPrestoResultSet.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/BaseTestJdbcResultSet.java
- presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcVendorCompatibility.java
Fixes https://github.com/prestosql/presto/issues/6247
> Represent VARBINARY with hex in ResultSet.getString

- presto-hive/src/test/java/io/prestosql/plugin/hive/parquet/AbstractTestParquetReader.java
https://github.com/prestosql/presto/issues/4063
> Mark TestParquetReader.testComplexNestedStructs as @Flaky

- pom.xml
- presto-main/src/test/java/io/prestosql/sql/planner/assertions/FunctionCallProvider.java
- presto-pinot/src/main/java/io/prestosql/pinot/query/PinotQueryBuilder.java
- presto-pinot/src/test/java/io/prestosql/pinot/TestDynamicTable.java
Rel https://github.com/prestosql/presto/issues/4188
> Enable more errorprone checks

- presto-main/src/test/java/io/prestosql/execution/TestSetSessionTask.java
Fixes #6082
The old PR is https://github.com/prestosql/presto/pull/6128
> Use assertThatThrownBy in TestSetSessionTask

- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveConfig.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveTimestampPrecision.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/HiveType.java
- presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveTypeTranslator.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestBackgroundHiveSplitLoader.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveConfig.java
Changes extracted from #5695 to reduce its scope.
> Minor improvements in Hive connector

- presto-hive/src/test/java/io/prestosql/plugin/hive/TestHiveIntegrationSmokeTest.java
- presto-hive/src/test/java/io/prestosql/plugin/hive/TestShowStats.java
- presto-iceberg/src/test/java/io/prestosql/plugin/iceberg/AbstractTestIcebergSmoke.java
- presto-main/src/main/java/io/prestosql/execution/CreateMaterializedViewTask.java
- presto-main/src/main/java/io/prestosql/execution/CreateViewTask.java
- presto-main/src/main/java/io/prestosql/execution/SqlQueryExecution.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/Analyzer.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/QueryExplainer.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/DescribeInputRewrite.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/DescribeOutputRewrite.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/ExplainRewrite.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/ShowQueriesRewrite.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/ShowStatsRewrite.java
- presto-main/src/main/java/io/prestosql/sql/rewrite/StatementRewrite.java
- presto-main/src/main/java/io/prestosql/testing/LocalQueryRunner.java
- presto-main/src/test/java/io/prestosql/sql/analyzer/TestAnalyzer.java
- presto-main/src/test/java/io/prestosql/sql/query/QueryAssertions.java
- presto-main/src/test/java/io/prestosql/sql/query/TestColumnMask.java
- presto-main/src/test/java/io/prestosql/sql/query/TestRowFilter.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveTableStatistics.java
- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestSqlStandardAccessControlChecks.java
- presto-tests/src/test/java/io/prestosql/security/TestAccessControl.java
Support arbitrary query in SHOW STATS
> Support arbitrary query in SHOW STATS

- presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCoercion.java
Based on the suggestion in https://github.com/prestosql/presto/pull/5575#issuecomment-713427731, this PR adds assertions for coercions in different versions of Hive in addition to Presto.
> Assert coercion behavior with Hive

- presto-docs/src/main/sphinx/release.rst
- presto-docs/src/main/sphinx/release/release-348.md
> Add 348 release notes

- presto-main/src/main/java/io/prestosql/security/ViewAccessControl.java
- presto-main/src/main/java/io/prestosql/sql/analyzer/StatementAnalyzer.java
- presto-main/src/main/java/io/prestosql/testing/TestingAccessControlManager.java
- presto-main/src/test/java/io/prestosql/sql/query/TestColumnMask.java
- presto-spi/src/main/java/io/prestosql/spi/security/AccessDeniedException.java
- presto-tests/src/test/java/io/prestosql/security/TestAccessControl.java
Add test for masking not refrenced columns
> Do not collect mask for restricted columns

- presto-memory/pom.xml
- presto-memory/src/test/java/io/prestosql/plugin/memory/TestMemorySmoke.java
Rel https://github.com/prestosql/presto/issues/6266, https://github.com/prestosql/presto/issues/5172
> Mark TestMemorySmoke#testCrossJoinDynamicFiltering as @Flaky

- presto-prometheus/src/test/java/io/prestosql/plugin/prometheus/TestPrometheusIntegrationMetrics.java
- presto-prometheus/src/test/java/io/prestosql/plugin/prometheus/TestPrometheusIntegrationSchema.java
- presto-prometheus/src/test/java/io/prestosql/plugin/prometheus/TestPrometheusIntegrationStatus.java
Fixes #6059 
* New pull request to fix incorrect issue assignment
> Give Prometheus test classes meaningful names

- presto-testing/src/main/java/io/prestosql/testing/datatype/DataType.java
Also increase existing code consistency a little.
> Add DataType for TIMESTAMP TZ, TIME TZ

- presto-docs/src/main/sphinx/connector/kafka.rst
Doc updates for https://github.com/prestosql/presto/issues/5955
> Update dataFormats supported by Kafka JSON encoder for temporal types
