presto-spi/src/main/java/io/prestosql/spi/block/ByteArrayBlock.java
presto-spi/src/main/java/io/prestosql/spi/block/ByteArrayBlockBuilder.java
presto-spi/src/main/java/io/prestosql/spi/block/ByteArrayBlockEncoding.java
presto-spi/src/main/java/io/prestosql/spi/block/EncoderUtil.java
presto-spi/src/main/java/io/prestosql/spi/block/Int128ArrayBlock.java
presto-spi/src/main/java/io/prestosql/spi/block/Int128ArrayBlockBuilder.java
presto-spi/src/main/java/io/prestosql/spi/block/Int128ArrayBlockEncoding.java
presto-spi/src/main/java/io/prestosql/spi/block/Int96ArrayBlockEncoding.java
presto-spi/src/main/java/io/prestosql/spi/block/IntArrayBlock.java
presto-spi/src/main/java/io/prestosql/spi/block/IntArrayBlockBuilder.java
presto-spi/src/main/java/io/prestosql/spi/block/IntArrayBlockEncoding.java
presto-spi/src/main/java/io/prestosql/spi/block/LongArrayBlockEncoding.java
presto-spi/src/main/java/io/prestosql/spi/block/ShortArrayBlock.java
presto-spi/src/main/java/io/prestosql/spi/block/ShortArrayBlockBuilder.java
presto-spi/src/main/java/io/prestosql/spi/block/ShortArrayBlockEncoding.java
presto-spi/src/test/java/io/prestosql/spi/block/BaseBlockEncodingTest.java

Improvement over https://github.com/prestosql/presto/pull/6018.
Added deserializing blocks of 8 at once for all blocks except int128
Benchmarks in commit messages

Improve blocks serde

---

presto-jdbc/src/main/java/io/prestosql/jdbc/PrestoPreparedStatement.java
presto-jdbc/src/test/java/io/prestosql/jdbc/BaseTestJdbcResultSet.java
presto-jdbc/src/test/java/io/prestosql/jdbc/TestJdbcPreparedStatement.java
presto-main/src/main/java/io/prestosql/sql/planner/LiteralInterpreter.java
presto-spi/src/main/java/io/prestosql/spi/type/TimeWithTimeZoneType.java

Support setting TIME WITH TIME ZONE and TIMESTAMP WITH TIME ZONE in prepared statement
Rel https://github.com/prestosql/presto/issues/6299

Support setting TIME TZ and TIMESTAMP TZ in prepared statement

---

presto-hive/src/main/java/io/prestosql/plugin/hive/HiveType.java
presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveBucketingV1.java
presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveBucketingV2.java
presto-hive/src/main/java/io/prestosql/plugin/hive/util/HiveTypeTranslator.java
presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveStorageFormats.java

Changes extracted from #5695 to reduce its scope.

Cleanup in Hive connector and tests

---

presto-base-jdbc/src/main/java/io/prestosql/plugin/jdbc/BaseJdbcClient.java
presto-sqlserver/pom.xml
presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/DataCompression.java
presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClient.java
presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerClientModule.java
presto-sqlserver/src/main/java/io/prestosql/plugin/sqlserver/SqlServerTableProperties.java
presto-sqlserver/src/test/java/io/prestosql/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java

Add data compression property to SQL Server tables

---

presto-product-tests/pom.xml
presto-product-tests/src/main/java/io/prestosql/tests/hive/HiveProductTest.java
presto-product-tests/src/main/java/io/prestosql/tests/hive/TestCsv.java
presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveBasicTableStatistics.java
presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveBucketedTables.java
presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveCreateTable.java
presto-product-tests/src/main/java/io/prestosql/tests/hive/TestHiveStorageFormats.java
presto-product-tests/src/main/java/io/prestosql/tests/hive/TestSyncPartitionMetadata.java

Rel https://github.com/prestosql/presto/issues/4936 because of https://github.com/prestosql/presto/runs/1566360715

Mark TestHiveBucketedTables as @Flaky and extend the pattern for HDP 3

---

presto-druid/pom.xml
presto-druid/src/test/java/io/prestosql/plugin/druid/DruidQueryRunner.java
presto-druid/src/test/java/io/prestosql/plugin/druid/TestDruidIntegrationSmokeTest.java
presto-druid/src/test/java/io/prestosql/plugin/druid/TestDruidIntegrationSmokeTestLatest.java

Add main method to Druid query runner

---

presto-bigquery/src/main/java/io/prestosql/plugin/bigquery/BigQuerySplitManager.java
presto-bigquery/src/test/java/io/prestosql/plugin/bigquery/TestBigQueryIntegrationSmokeTest.java

Fixes #5635
We can choose executing `SELECT count(*) FROM view` on BigQuery or reading number of rows from generated _pbc table. This PR is former.

Fix incorrect result when aggregating count BigQuery view

---

presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationPushDown.java

Remove FixedCountRetryAnalyzer
In case of flaky tests we should instad:
- try to fix flakiness
- use @Flaky annotation as last resort

Remove FixedCountRetryAnalyzer

---

.github/workflows/ci.yml

Embed --fail-at-end in MAVEN_TEST

Embed --fail-at-end in MAVEN_TEST

---

pom.xml
presto-kafka/pom.xml
presto-pinot/pom.xml
presto-testing-kafka/src/main/java/io/prestosql/testing/kafka/TestingKafka.java

Update Kafka Schema Registry to 5.5.0

Update Kafka Schema Registry to 5.5.2

---

presto-kafka/src/main/java/io/prestosql/plugin/kafka/schema/confluent/ConfluentModule.java

Pass SchemaProviders to SchemaRegistry

---

presto-tests/src/test/java/io/prestosql/execution/TestTry.java

Test for https://github.com/prestosql/presto/issues/6375, https://github.com/prestosql/presto/pull/6380

Add test with try and column with at sign

---

presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaConnectorModule.java
presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaPageSinkProvider.java
presto-kafka/src/main/java/io/prestosql/plugin/kafka/KafkaRecordSetProvider.java
presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/EncoderModule.java
presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/avro/AvroEncoderModule.java
presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/avro/AvroRowEncoder.java
presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/csv/CsvRowEncoder.java
presto-kafka/src/main/java/io/prestosql/plugin/kafka/encoder/json/JsonRowEncoder.java
presto-kafka/src/main/java/io/prestosql/plugin/kafka/schema/confluent/ConfluentModule.java
presto-kafka/src/main/java/io/prestosql/plugin/kafka/schema/file/FileTableDescriptionSupplierModule.java
presto-kafka/src/test/java/io/prestosql/plugin/kafka/KafkaQueryRunner.java
presto-kafka/src/test/java/io/prestosql/plugin/kafka/TestKafkaIntegrationSmokeTest.java
presto-kafka/src/test/java/io/prestosql/plugin/kafka/encoder/json/TestCustomJsonDateTimeFormatter.java
presto-kafka/src/test/java/io/prestosql/plugin/kafka/encoder/json/TestISO8601JsonDateTimeFormatter.java
presto-kafka/src/test/java/io/prestosql/plugin/kafka/encoder/json/TestJsonEncoder.java
presto-kafka/src/test/java/io/prestosql/plugin/kafka/encoder/json/TestMillisecondsJsonDateTimeFormatter.java
presto-kafka/src/test/java/io/prestosql/plugin/kafka/encoder/json/TestRFC2822JsonDateTimeFormatter.java
presto-kafka/src/test/java/io/prestosql/plugin/kafka/encoder/json/TestSecondsJsonDateTimeFormatter.java
presto-kafka/src/test/java/io/prestosql/plugin/kafka/schema/confluent/TestAvroConfluentRowDecoder.java
presto-kafka/src/test/java/io/prestosql/plugin/kafka/schema/confluent/TestAvroSchemaConverter.java
presto-kafka/src/test/java/io/prestosql/plugin/kafka/schema/confluent/TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java

Fail fast INSERT with Kafka Schema registry tables

Fail fast INSERT with Kafka Schema registry tables

---

pom.xml

https://github.com/testcontainers/testcontainers-java/releases/tag/1.15.1

Update testcontainers to 1.15.1

---

pom.xml
presto-kafka/pom.xml
presto-kafka/src/main/java/io/prestosql/plugin/kafka/schema/confluent/AvroConfluentContentSchemaReader.java
presto-kafka/src/main/java/io/prestosql/plugin/kafka/schema/confluent/AvroSchemaParser.java
presto-kafka/src/main/java/io/prestosql/plugin/kafka/schema/confluent/ConfluentModule.java
presto-kafka/src/main/java/io/prestosql/plugin/kafka/schema/confluent/ConfluentSchemaRegistryTableDescriptionSupplier.java
presto-kafka/src/main/java/io/prestosql/plugin/kafka/schema/confluent/SchemaParser.java
presto-kafka/src/main/java/io/prestosql/plugin/kafka/schema/file/FileContentSchemaReader.java
presto-kafka/src/test/java/io/prestosql/plugin/kafka/schema/confluent/TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java

Fail fast Kafka Schema Registry on unsupported format

Handle Kafka Schema Registry unsupported formats

---

presto-main/src/main/java/io/prestosql/sql/DynamicFilters.java
presto-main/src/main/java/io/prestosql/sql/planner/optimizations/PredicatePushDown.java
presto-main/src/test/java/io/prestosql/sql/planner/TestDynamicFilter.java
presto-main/src/test/java/io/prestosql/sql/planner/TestLocalDynamicFiltersCollector.java
presto-main/src/test/java/io/prestosql/sql/planner/assertions/JoinMatcher.java
presto-main/src/test/java/io/prestosql/sql/planner/assertions/PlanMatchPattern.java
presto-main/src/test/java/io/prestosql/sql/planner/sanity/TestDynamicFiltersChecker.java
presto-memory/src/test/java/io/prestosql/plugin/memory/TestMemorySmoke.java
presto-tests/pom.xml
presto-tests/src/test/java/io/prestosql/execution/TestCoordinatorDynamicFiltering.java

Improves performance for joins explcitly using IS NOT DISTINCT FROM condition for the join criteria.

Implement dynamic filtering for joins using IS NOT DISTINCT FROM

---

presto-docs/src/main/sphinx/release.rst
presto-docs/src/main/sphinx/release/release-349.md

Closes https://github.com/trinodb/trino/issues/6339

Add 349 release notes

---

plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/KafkaQueryRunner.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaDistributed.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationPushDown.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestKafkaIntegrationSmokeTest.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/TestMinimalFunctionality.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestMinimalFunctionality.java
testing/trino-testing-kafka/src/main/java/io/trino/testing/kafka/BasicTestingKafka.java
testing/trino-testing-kafka/src/main/java/io/trino/testing/kafka/TestingKafka.java
testing/trino-testing-kafka/src/main/java/io/trino/testing/kafka/TestingKafkaWithSchemaRegistry.java

Remove Kafka topic creation in tests
Topic are created anyway on first message creation.

Remove Kafka topic creation in tests

---

plugin/trino-kafka/pom.xml
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaConnectorModule.java
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Kafka.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/SinglenodeKafka.java
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-kafka/kafka_schema_registry.properties
testing/trino-product-tests/pom.xml
testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java
testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroWritesSmokeTest.java
testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaPushdownSmokeTest.java
testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaWritesSmokeTest.java
testing/trino-product-tests/src/main/java/io/trino/tests/utils/Cli.java

Add product for Kafka Schema Registry and Avro format

Add product for Kafka Schema Registry and Avro format

---

testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHivePartitionsTable.java

Mark TestHivePartitionsTable as flaky due to "committing"

---

core/trino-main/src/main/java/io/trino/metadata/FunctionRegistry.java
core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
core/trino-main/src/main/java/io/trino/operator/scalar/VersionFunction.java
core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
core/trino-main/src/test/java/io/trino/operator/scalar/TestVersionFunction.java
docs/src/main/sphinx/functions.rst
docs/src/main/sphinx/functions/list.rst
docs/src/main/sphinx/functions/system.rst
testing/trino-product-tests/src/main/java/io/trino/tests/TestFunctions.java

Add support for version function

---

plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerIntegrationSmokeTest.java

Get Data compression only for non-indexed SQL Server tables

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveType.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveTypeTranslator.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/SerDeUtils.java
testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveStorageFormats.java

Add support for variable precision timestamps in Hive array, map, and struct

---

core/trino-main/src/test/java/io/trino/execution/TestNodeScheduler.java
core/trino-main/src/test/java/io/trino/metadata/TestQualifiedTablePrefix.java
core/trino-main/src/test/java/io/trino/operator/TestRowReferencePageManager.java
core/trino-spi/src/test/java/io/trino/spi/predicate/TestRange.java
plugin/trino-atop/pom.xml
plugin/trino-atop/src/test/java/io/trino/plugin/atop/TestAtopHang.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveIntegrationSmokeTest.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationSchemaNotExisting.java
testing/trino-product-tests/src/main/java/io/trino/tests/jdbc/BaseLdapJdbcTest.java
testing/trino-product-tests/src/main/java/io/trino/tests/jdbc/TestLdapTrinoJdbc.java

Rel to https://github.com/trinodb/trino/issues/6553

Migrate some occurances of fail() to assertThatThrownBy

---

testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java

Use assertEventually in TestKafkaAvroReadsSmokeTest
A schema registry is cached and sometimes it may return incorrectly
return that given schema does not yet exists.

Use assertEventually in TestKafkaAvroReadsSmokeTest

---

pom.xml

It brings a lot of improvements for Java versions beyond version 8.

Update maven-shade-plugin to 3.2.4

---

lib/trino-parquet/pom.xml
lib/trino-rcfile/pom.xml
lib/trino-rcfile/src/test/java/io/trino/rcfile/RcFileTester.java
plugin/trino-hive/pom.xml
pom.xml
testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestCompression.java

Fixes https://github.com/trinodb/trino/issues/6451

Support LZO-compressed Sequencefile table

---

client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverImpersonateUser.java

Renames a test added in https://github.com/trinodb/trino/pull/6549 to use Trino

Rename test file to use Trino instead of Presto

---

client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
testing/trino-product-tests/src/main/java/io/trino/tests/cli/TestTrinoCli.java

Fixes https://github.com/trinodb/trino/issues/6567.
@findepi @alexjo2144 have you planned to test it somehow?

Allow passing --session-user in the CLI

---

core/trino-main/src/main/java/io/trino/server/security/AbstractBearerAuthenticator.java
core/trino-main/src/main/java/io/trino/server/security/ServerSecurityModule.java
core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticator.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2AuthenticationSupportModule.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Authenticator.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2CallbackResource.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2Service.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2ServiceModule.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2TokenExchange.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2TokenExchangeResource.java
core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiAuthenticationFilter.java
core/trino-main/src/main/java/io/trino/server/ui/OAuth2WebUiInstalled.java
core/trino-main/src/main/resources/oauth2/success.html
core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java

This addresses the review comments from #6594

Add token polling for query submission authenticator

---

core/trino-main/src/main/java/io/trino/execution/SqlStageExecution.java
core/trino-main/src/main/java/io/trino/sql/planner/SystemPartitioningHandle.java
lib/trino-orc/src/main/java/io/trino/orc/OrcOutputBuffer.java
lib/trino-orc/src/main/java/io/trino/orc/OrcWriteValidation.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveWriterFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HivePrincipal.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/HiveS3Module.java
pom.xml

See: http://errorprone.info/bugpattern/UseEnumSwitch

Enable UseEnumSwitch error-prone check

---

client/trino-jdbc/src/test/java/io/trino/jdbc/BaseTestJdbcResultSet.java
core/trino-main/src/test/java/io/trino/sql/planner/planprinter/TestWindowOperatorStats.java
core/trino-parser/pom.xml
pom.xml
testing/trino-test-jdbc-compatibility-old-driver/bin/run_tests.sh

Preparatory for https://github.com/trinodb/trino/pull/6627

Update assertJ core to 3.18.1

---

plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegrationMetrics.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegrationSchema.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusIntegrationStatus.java

Remove use of test priorities and dependsOnMethods from Prometheus tests

---

plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerWithoutSnapshotIsolation.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestingSqlServer.java

Fixes https://github.com/trinodb/trino/issues/6608

Detect and enable snapshot isolation if available for SqlServer

---

plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/OracleQueryRunner.java
plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleCaseInsensitiveMapping.java
plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleDistributedQueries.java
plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleIntegrationSmokeTest.java
plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOraclePoolIntegrationSmokeTest.java
plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestOracleTypeMapping.java
plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestRemarksReportingOracleDistributedQueries.java
plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/TestRemarksReportingOraclePoolIntegrationSmokeTest.java

Fixes https://github.com/trinodb/trino/issues/5721 too

Test Oracle case insensitive mapping

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastoreUtil.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControl.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/security/SqlStandardAccessControlMetadata.java

Extracted from https://github.com/trinodb/trino/pull/5496

ThriftMetastoreUtil cleanup

---

testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
testing/trino-tests/src/test/java/io/trino/connector/system/runtime/TestSystemConnector.java

add a backup Coordinator to test #6237

Add a backup Coordinator to test multi coordinators

---

core/trino-parser/src/main/java/io/trino/sql/tree/ExpressionTreeRewriter.java
pom.xml

for https://github.com/trinodb/trino/issues/4188

Enable OptionalEquality errorprone check

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementCorr.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementCovariancePop.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementCovarianceSamp.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementRegrIntercept.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementRegrSlope.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementStddevPop.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementStddevSamp.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementVariancePop.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/expression/ImplementVarianceSamp.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlIntegrationSmokeTest.java
plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/ImplementSqlServerStdev.java
plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/ImplementSqlServerVariance.java

Fixes https://github.com/trinodb/trino/issues/6736

Remove redundant case insensitive matching in aggregation pushdown

---

core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushdownFilterIntoWindow.java

TopNRanking supports both row_number and rank function. Test cases for the rank function can be also covered.

Rank test case for PushdownFilterIntoWindow

---

docs/src/main/sphinx/functions/geospatial.rst
lib/trino-geospatial-toolkit/pom.xml
lib/trino-geospatial-toolkit/src/main/java/io/trino/geospatial/GeometryUtils.java
plugin/trino-geospatial/src/main/java/io/trino/plugin/geospatial/GeoFunctions.java
plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestGeoFunctions.java
pom.xml

Co-authored-by: Rong Rong <rongr@fb.com>

Add functions to_geojson and from_geojson

---

core/trino-main/src/main/java/io/trino/sql/DynamicFilters.java
core/trino-main/src/main/java/io/trino/sql/planner/DomainCoercer.java
core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateThroughProjectIntoRowNumber.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushdownFilterIntoRowNumber.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushdownFilterIntoWindow.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/WindowFilterPushDown.java
core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
core/trino-spi/src/main/java/io/trino/spi/predicate/Range.java
core/trino-spi/src/test/java/io/trino/spi/predicate/BenchmarkSortedRangeSet.java
plugin/trino-accumulo/src/main/java/io/trino/plugin/accumulo/AccumuloClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/QueryBuilder.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryFilterQueryBuilder.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClusteringPredicatesExtractor.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ElasticsearchQueryBuilder.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/IonSqlQueryBuilder.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueExpressionUtil.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java
plugin/trino-kudu/src/main/java/io/trino/plugin/kudu/KuduClientSession.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotQueryBuilder.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusSplitManager.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/ShardPredicate.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/systemtables/PreparedStatementBuilder.java

Add convenience methods for dealing with `Range` values.

Simplify Range consumption

---

client/trino-client/src/test/java/io/trino/client/TestFixJsonDataUtils.java
core/trino-main/src/main/java/io/trino/execution/SqlStageExecution.java
core/trino-main/src/main/java/io/trino/metadata/OperatorNotFoundException.java
core/trino-main/src/main/java/io/trino/operator/aggregation/AccumulatorCompiler.java
core/trino-main/src/main/java/io/trino/operator/scalar/annotations/OperatorValidator.java
core/trino-main/src/main/java/io/trino/server/protocol/Query.java
core/trino-main/src/main/java/io/trino/sql/analyzer/QueryExplainer.java
core/trino-main/src/main/java/io/trino/sql/planner/SubqueryPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/TransformQuantifiedComparisonApplyToCorrelatedJoin.java
core/trino-main/src/main/java/io/trino/sql/planner/sanity/TypeValidator.java
core/trino-main/src/test/java/io/trino/sql/gen/TestExpressionCompiler.java
core/trino-spi/src/main/java/io/trino/spi/type/TypeOperators.java
lib/trino-orc/src/main/java/io/trino/orc/StripeReader.java
lib/trino-orc/src/main/java/io/trino/orc/checkpoint/Checkpoints.java
lib/trino-orc/src/main/java/io/trino/orc/metadata/OrcMetadataWriter.java
lib/trino-orc/src/main/java/io/trino/orc/stream/ValueStreams.java
lib/trino-orc/src/main/java/io/trino/orc/writer/ColumnWriters.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetCompressor.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveWriteUtils.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/SerDeUtils.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergFileWriterFactory.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergOrcFileWriter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/DatabaseShardManager.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/metadata/ShardPredicate.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/OrcStorageManager.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/organization/ShardOrganizerUtil.java
pom.xml

Fixes https://github.com/trinodb/trino/issues/6764
Previous discussion about _whether_ do it: https://trinodb.slack.com/archives/CP1MUNEUX/p1611921920204600

Enable MissingCasesInEnumSwitch errorprone check

---

core/docker/build-local.sh
core/docker/build-remote.sh

cp -t is not supported on MacOS

Fix building docker image on MacOS

---

.github/workflows/ci.yml

Retry dependency download for Error Prone

---

.github/workflows/ci.yml

This should fix CI not being run on new PRs.

Fix whitespace within ci.yml

---

plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/AvroConfluentContentSchemaReader.java
plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestAvroConfluentContentSchemaReader.java
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/catalog/kafka/schema_with_references.avsc
testing/trino-product-tests/src/main/java/io/trino/tests/kafka/TestKafkaAvroReadsSmokeTest.java

Resolve SchemaReferences in ConfluentContentSchemaReader

---

plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentModule.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/SchemaRegistryClientPropertiesProvider.java

- Removes optional binding of SchemaRegistryClient
- Introduce SchemaRegistryClientPropertiesProvider to pass properties to SchemaRegistryClient

Minor Cleanups for SchemaRegistry

---

docs/src/main/sphinx/connector/hive.rst

This is the Hive views documentation @findepi and myself created together.

Add Hive view documentation

---

testing/trino-product-tests/README.md

- Replace Presto with Trino
- Fix incorrect cmd in product-tests readme

Improve trino-product-tests docs

---

testing/trino-product-tests/README.md

Fix host name in product tests readme

Fix host name in product tests readme

---

lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetSchemaConverter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/PrimitiveTypeMapBuilder.java
pom.xml

Depends on https://github.com/prestosql/presto-hive-apache/pull/19

Update to Parquet 1.11.1

---

core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
testing/trino-tests/src/test/java/io/trino/tests/TestDistributedEngineOnlyQueries.java

fixes printing of:
```
create table d as  select '2020-01-01' ds;
explain select count(*) from d where date(ds) < date '2020-01-02'
```
Fixes #6655

Unresolve filter expression before printing

---

docs/src/main/sphinx/connector/kafka.rst

Replaces the stale progress on https://github.com/trinodb/trino/pull/6791 
It would be great to get this merged before 353 @kokosing

Add table descriptor and schema registry usage for Kafka connector

---

core/trino-main/src/main/java/io/trino/operator/PageUtils.java
core/trino-main/src/test/java/io/trino/operator/TestPageUtils.java
core/trino-spi/src/main/java/io/trino/spi/block/LazyBlock.java
core/trino-spi/src/test/java/io/trino/spi/block/TestLazyBlock.java

Fixes https://github.com/trinodb/trino/issues/6728

Fix lazy block loaders and simplify recordMaterializedBytes

---

docs/src/main/sphinx/security.rst

This is stage 1 of the security rework proposed for Trino docs.

Add groups to Security chapter's TOC

---

core/trino-main/src/main/java/io/trino/connector/ConnectorAwareNodeManager.java

Current node should have connector always registered.
Therefore there is no need to wait until current node
has connector registered in discovery service before
returning node in ConnectorAwareNodeManager.
Fixes: https://github.com/trinodb/trino/issues/7064

Append current node explicitly in ConnectorAwareNodeManager

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/converter/GlueInputConverter.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/glue/TestHiveGlueMetastore.java

Update partition statistics in Glue after partition is created

---

testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java

Requires: https://github.com/trinodb/trino/pull/7014

Test pivoting table with 254 columns

---

core/trino-main/src/main/java/io/trino/operator/exchange/LocalExchange.java
core/trino-main/src/main/java/io/trino/operator/exchange/PartitioningExchanger.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/NodePartitioningManager.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddLocalExchanges.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/StreamPreferredProperties.java
core/trino-main/src/test/java/io/trino/operator/TestHashJoinOperator.java
core/trino-main/src/test/java/io/trino/operator/exchange/TestLocalExchange.java
core/trino-main/src/test/java/io/trino/sql/planner/TestInsert.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveIntegrationSmokeTest.java

Based on: https://github.com/prestodb/presto/pull/13294

Improve performance of bucketed table inserts

---

testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java

fixes https://github.com/trinodb/trino/issues/7085

Fix failure in testPivotExceedingMaximumArraySize

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/StandardColumnMappings.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/TypeUtils.java

* Presto → Trino
* jdbcTypeToPrestoType → legacyDefaultColumnMapping

Update method names in StandardColumnMappings

---

core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
core/trino-main/src/test/java/io/trino/sql/BenchmarkExpressionInterpreter.java
core/trino-main/src/test/java/io/trino/sql/TestExpressionInterpreter.java

Reduce the time to reslove operator for issue #7015

Resolve operator outside loop over value list in expression interpreter

---

core/trino-server/src/main/provisio/presto.xml
docs/src/main/sphinx/connector.rst
docs/src/main/sphinx/connector/clickhouse.rst
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/StandardColumnMappings.java
plugin/trino-clickhouse/pom.xml
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClientModule.java
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseConfig.java
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHousePlugin.java
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseTableProperties.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/ClickHouseQueryRunner.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/ClickHouseSqlExecutor.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConfig.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHousePlugin.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestingClickHouseServer.java
pom.xml
testing/trino-testing/src/main/java/io/trino/testing/datatype/CreateAndInsertDataSetup.java
testing/trino-testing/src/main/java/io/trino/testing/datatype/DataTypeTest.java

Already reviewed at https://github.com/trinodb/trino/pull/4909

[CI only] Add ClickHouse connector

---

docs/src/main/sphinx/connector/hive.rst

Add docs for parameters introduced in #6178

docs for glue statistics parallelism configuration

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java

Ignore failures translating hive views while listing views

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateThroughProjectIntoWindow.java
plugin/trino-thrift-api/src/main/java/io/trino/plugin/thrift/api/valuesets/TrinoThriftRangeValueSet.java

This also avoids using a deprecated API.

Simplify conditions in PushPredicateThroughProjectIntoWindow

---

plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestingMemSqlServer.java

Resubmit of https://github.com/trinodb/trino/pull/7047

Update MemSQL docker image to 7.1.13

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/PredicatePushdownController.java

Fix error message for CASE_INSENSITIVE_PUSHDOWN to use the correct name

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/AbstractTestParquetReader.java

For https://github.com/trinodb/trino/issues/4984, see https://github.com/trinodb/trino/issues/4984#issuecomment-791276938

Mark testArrayOfArrayOfStructOfArray as @Flaky

---

core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilter.java
core/trino-main/src/test/java/io/trino/server/security/oauth2/TestingHydraIdentityProvider.java

Cosmetic change, but new name describes better this class role.

Rename TestingHydraService to TestingHydraIdentityProvider

---

pom.xml

Update include
* Code to to prevent S3 connection leaks in AvroGenericRecordReader
* Updated thrift metastore client

Update hive-apache to 3.1.2-11

---

plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java

Partially resolves https://github.com/trinodb/trino/issues/7031.
It doesn't touch other connectors or change default topN behaviour.

Fix topN pushdown for case-sensitive sort items

---

plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixConnectorTest.java
plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java

Throw SkipException for tests of unsupported features

Throw SkipException for tests of unsupported features

---

plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaAdminFactory.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaConsumerFactory.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaFilterManager.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaPageSink.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaPageSinkProvider.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaProducerFactory.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaRecordSet.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaRecordSetProvider.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaSplitManager.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/PlainTextKafkaAdminFactory.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/PlainTextKafkaConsumerFactory.java
plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/PlainTextKafkaProducerFactory.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentModule.java

Continuation of https://github.com/trinodb/trino/pull/6990

Pass the connector session to Kafka factories

---

plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlLatestConnectorSmokeTest.java

Change class name to match convention

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetastoreClosure.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/HiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/RecordingHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/alluxio/AlluxioHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/cache/CachingHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/BridgingHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/ThriftMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/DropStatsProcedure.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/TestSemiTransactionalHiveMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/UnimplementedHiveMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/InMemoryThriftMetastore.java

Extracted from https://github.com/trinodb/trino/pull/7010, already reviewed.

[CI only] Hive metastore code cleanup for ANALYZE

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataConfig.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcMetadataConfig.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java

Enable topN pushdown by default

---

core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/PlanCopier.java
core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmenter.java
core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyTableScanRedirection.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PruneTableScanColumns.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushAggregationIntoTableScan.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushJoinIntoTableScan.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushLimitIntoTableScan.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionIntoTableScan.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushSampleIntoTableScan.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushTopNIntoTableScan.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformFilteringSemiJoinToInnerJoin.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/BeginTableWrite.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/UnaliasSymbolReferences.java
core/trino-main/src/main/java/io/trino/sql/planner/plan/TableScanNode.java
core/trino-main/src/main/java/io/trino/sql/planner/plan/TableWriterNode.java
core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/InternalHiveSplitFactory.java
testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveTransactionalTable.java

Fix DELETE and UPDATE for connectors that subsume filters

---

core/trino-parser/src/main/java/io/trino/sql/parser/SqlParser.java

Fix comment typo in SqlParser

---

core/trino-spi/src/main/java/io/trino/spi/type/SqlTime.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/StandardColumnMappings.java
plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerTypeMapping.java
testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java

Support time(p) in SQL Server connector

---

docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-353.md
docs/src/main/sphinx/release/release-354.md

Closes https://github.com/trinodb/trino/issues/7186

Add 354 release notes

---

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java
core/trino-main/src/test/java/io/trino/sql/query/TestRowFilter.java

Do not allow to INSERT into a table with row filter

Do not allow to INSERT into a table with row filter

---

plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java

Prever TrinoException over RTE in MysqlClient
Fixes https://github.com/trinodb/trino/issues/7208

Prefer TrinoException over RTE in MysqlClient

---

plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/schema/confluent/TestKafkaWithConfluentSchemaRegistryMinimalFunctionality.java
testing/trino-testing-kafka/src/main/java/io/trino/testing/kafka/TestingKafka.java

Fixes https://github.com/trinodb/trino/issues/6646

Fix flaky Kafka Schema Registry tests

---

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java

Make TopN over limit test deterministic

---

plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/confluent/ConfluentSchemaRegistryTableDescriptionSupplier.java

Such topic is probably illegal, but let's make the code immune to it
anyway.

Check for subject being just -value / -key

---

core/trino-main/src/test/java/io/trino/sql/planner/TestPlanMatchingFramework.java

Fixes https://github.com/trinodb/trino/issues/7303

Replace TestPlanMatchingFramework#assertFails with assertThatThrownBy

---

plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduIntegrationDecimalColumns.java

Use unique table name for TestKuduIntegrationDecimalColumns

---

pom.xml
testing/trino-product-tests/src/main/java/io/trino/tests/hive/AbstractTestHiveViews.java
testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViewsLegacy.java

Fixes https://github.com/trinodb/trino/issues/7271
Requires https://github.com/linkedin/coral/pull/54 
cc @losipiuk

Fix Hive VIEW with expression array subscript

---

plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java

Relates to https://github.com/trinodb/trino/issues/6553

Replace fail+catch pattern with assertThatThrownBy in trino-phoenix5

---

core/trino-main/src/main/java/io/trino/split/BufferingSplitSource.java
core/trino-main/src/main/java/io/trino/split/ConnectorAwareSplitSource.java
core/trino-main/src/main/java/io/trino/split/SampledSplitSource.java
core/trino-main/src/main/java/io/trino/split/SplitManager.java
core/trino-main/src/main/java/io/trino/split/SplitSource.java
core/trino-main/src/test/java/io/trino/split/MockSplitSource.java
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorSplitSource.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorSplitSource.java

Remove ConnectorSplitSource.getMinScheduleSplitBatchSize

---

core/trino-main/src/main/java/io/trino/execution/CreateMaterializedViewTask.java
core/trino-main/src/main/java/io/trino/execution/CreateViewTask.java
core/trino-main/src/test/java/io/trino/connector/MockConnector.java
testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java

These details will be exposed in event listener.

Record input/output details when creating view/materialized view

---

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java

Set proper update type for REFRESH MATERIALIZED VIEW

Set proper update type for REFRESH MATERIALIZED VIEW

---

testing/trino-product-tests/src/main/java/io/trino/tests/hive/AbstractTestHiveViews.java
testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java
testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViewsLegacy.java

Extracted from https://github.com/trinodb/trino/pull/7420

Clean view tests

---

docs/src/main/sphinx/admin/properties-optimizer.rst

to be landed after: https://github.com/trinodb/trino/pull/7257

Add doc for table-scan-node-partitioning-min-bucket-to-task-ratio

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadata.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcTableHandle.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcRecordSetProvider.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcTableHandle.java
plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java

Fixes https://github.com/trinodb/trino/issues/6832

Cache statistics for JdbcTableHandle after complex pushdowns

---

plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestMinimalFunctionality.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java
testing/trino-testing-kafka/src/main/java/io/trino/testing/kafka/TestingKafka.java

Fixes https://github.com/trinodb/trino/issues/6412

Create a new network for each instance of TestingKafka

---

.github/workflows/ci.yml

Shorten product tests GHA titles

Shorten product tests GHA titles

---

core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
core/trino-main/src/main/java/io/trino/sql/analyzer/Output.java
core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-main/src/test/java/io/trino/connector/MockConnectorHandleResolver.java
core/trino-main/src/test/java/io/trino/connector/MockConnectorInsertTableHandle.java
core/trino-main/src/test/java/io/trino/connector/MockConnectorOutputTableHandle.java
core/trino-main/src/test/java/io/trino/sql/analyzer/TestOutput.java
core/trino-spi/src/main/java/io/trino/spi/eventlistener/QueryOutputMetadata.java
testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java

Record output column details to EventListener

---

core/trino-main/src/main/java/io/trino/execution/CreateTableTask.java
core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-main/src/test/java/io/trino/execution/TestCreateTableTask.java
testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java

Follow up of https://github.com/trinodb/trino/pull/7425

Record output for CREATE TABLE

---

testing/trino-product-tests/src/main/java/io/trino/tests/hive/TestHiveViews.java

for consistency, TEXTFILE is already used by other tests in that class.

Use TEXTFILE for a table in test

---

testing/trino-tests/src/test/java/io/trino/tests/TestDistributedSpilledQueries.java

Fixes https://github.com/trinodb/trino/issues/7463

Retry testExplainAnalyzeReportSpilledDataSize

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java

credits @sopel39 's sharp eyes. https://github.com/trinodb/trino/pull/7367#issuecomment-803901360

Avoid duplicate metastore calls in IcebergMetadata#getMaterializedView

---

client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverImpersonateUser.java
core/trino-main/src/main/java/io/trino/server/PluginManager.java
core/trino-main/src/main/java/io/trino/server/Server.java
core/trino-main/src/main/java/io/trino/server/security/AuthenticationFilter.java
core/trino-main/src/main/java/io/trino/server/security/PasswordAuthenticator.java
core/trino-main/src/main/java/io/trino/server/security/PasswordAuthenticatorConfig.java
core/trino-main/src/main/java/io/trino/server/security/PasswordAuthenticatorManager.java
core/trino-main/src/main/java/io/trino/server/security/ServerSecurityModule.java
core/trino-main/src/main/java/io/trino/server/ui/FormUiAuthenticatorModule.java
core/trino-main/src/main/java/io/trino/server/ui/PasswordManagerFormAuthenticator.java
core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
core/trino-main/src/test/java/io/trino/server/security/TestPasswordAuthenticatorConfig.java
core/trino-main/src/test/java/io/trino/server/security/TestPasswordAuthenticatorManager.java
core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/AbstractSinglenodeLdap.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/SinglenodeLdapAndFile.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/suite/suites/Suite6NonGeneric.java
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-ldap-and-file/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-ldap-and-file/file-authenticator.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-ldap-and-file/password.db
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-ldap-and-file/tempto-configuration.yaml
testing/trino-product-tests/src/main/java/io/trino/tests/TestGroups.java
testing/trino-product-tests/src/main/java/io/trino/tests/cli/TestTrinoLdapCli.java
testing/trino-product-tests/src/main/java/io/trino/tests/jdbc/BaseLdapJdbcTest.java
testing/trino-product-tests/src/main/java/io/trino/tests/jdbc/TestLdapTrinoJdbc.java
testing/trino-testing/src/test/java/io/trino/testing/TestTestingTrinoClient.java

Fixes: https://github.com/trinodb/trino/issues/1791

Support multiple password authentication plugins

---

plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/OrcStorageManager.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/RaptorPageSource.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/RaptorStorageManager.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/ShardRecoveryManager.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/ShardStats.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/storage/StorageModule.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/TestRaptorConnector.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/storage/TestRaptorStorageManager.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/storage/TestShardRecovery.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/storage/organization/TestShardCompactor.java

This avoids confusion with the one in the Hive connector.

Rename OrcPageSource to RaptorPageSource

---

docs/src/main/sphinx/admin/dynamic-filtering.rst

New content line 29-32. The other edits were text wrapping.

Add that dynamic filtering is default

---

docs/src/main/sphinx/functions/list.rst

and fix some ordering problems
This is in anticipation of Writing Day so that we can have people have a look at the list and see what is missing and then document that function. 
cc @rosewms @bitsondatadev

Add missing functions by name

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java

All existing methods in TrinoS3Filesystem list objects rooted at the
provided path. This makes listing inefficient for flat structures where
we require multiple API calls to S3 and end up filtering on the client
side. A new method is added which lists all objects whose absolute path
matches a given prefix. This makes searching for all objects matching a
provided prefix efficient. All other methods retain their existing
behavior in this commit.

Add method to list all objects matching a given prefix

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSource.java

This will not conflict with #7349 or #7523, because neither of those modifies `ParquetPageSource`.

Minor improvements in ParquetPageSource

---

core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java

Allow to configure eventListener in DistributedQueryRunner

Allow to configure eventListener in DistributedQueryRunner

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadata.java

Make JdbcMetadata::getSchemaTableName public

Make JdbcMetadata::getSchemaTableName public

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/DockerContainer.java

Ignore not existing logs when collecting log files
Fixes https://github.com/trinodb/trino/issues/7577

Ignore not existing logs when collecting log files

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/ExtraCredentialsBasedJdbcIdentityCacheMapping.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcIdentityCacheMapping.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataFactory.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/SingletonJdbcIdentityCacheMapping.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/credential/CredentialProviderModule.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestCachingJdbcClient.java

Use same user key when no impersonation is used

Use same user key when no impersonation is used

---

plugin/trino-hive/pom.xml
plugin/trino-hive/src/main/java/io/trino/plugin/hive/ViewReaderUtil.java
pom.xml

This brings no user-visible changes.

Upgrade Coral to 1.0.42

---

plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerTypeMapping.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestBaseSqlServerTypeMapping.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerTypeMapping.java

Add and refactor SQL server type mapping tests

Add and refactor SQL server type mapping tests

---

DEVELOPMENT.md

This is an enhancement of the section about IntelliJ IDEA's inspections. Proper handling of language injection is unfortunately not automatic, and there is no objective truth to how to do it. But since we're working with SQL statements a lot, I find it useful.
The text is a result of a very not-wide-ranging discussion we had about this subject. It may be seen as a kind of imposition on our part, so please share your opinion on this. Is there anything else that we can do? Is there a better way that I don't know about? Is it too wordy? Is it necessary at all?
Thanks!

Add recommendations around language injection

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/azure/HiveAzureConfig.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/azure/TrinoAzureConfigurationInitializer.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/azure/TestHiveAzureConfig.java
pom.xml

Won't build/work due to required upstream changes:  https://github.com/trinodb/trino-hadoop-apache/pull/28

 Allow setting connection proxy for ADL connection

---

core/trino-main/pom.xml
core/trino-main/src/main/java/io/trino/operator/scalar/StringFunctions.java
core/trino-main/src/test/java/io/trino/operator/scalar/TestStringFunctions.java
plugin/trino-accumulo/pom.xml
plugin/trino-bigquery/pom.xml
plugin/trino-elasticsearch/pom.xml
plugin/trino-pinot/pom.xml
plugin/trino-prometheus/pom.xml

Fixes https://github.com/prestosql/presto/issues/3889

Add Soundex function

---

plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerTypeMapping.java

Support dates<1583 for SQL server connector (BC dates not supported by SQL server)

Support dates<1583 for SQL server connector

---

plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/SinglenodePostgresql.java

Raise minimum PostgreSQL version to 9.6

---

core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java
core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
core/trino-main/src/main/java/io/trino/server/ServerConfig.java
core/trino-main/src/main/java/io/trino/server/protocol/ExecutingStatementResource.java
core/trino-main/src/main/java/io/trino/server/protocol/Query.java
core/trino-main/src/main/java/io/trino/server/protocol/QueryInfoUrlFactory.java
core/trino-main/src/test/java/io/trino/server/TestServerConfig.java

This allows URL from CLI to be redirected to an alternate system

Add query info url template

---

core/trino-main/src/main/java/io/trino/sql/planner/DomainTranslator.java
core/trino-main/src/test/java/io/trino/sql/planner/TestDomainTranslator.java

No predicate pushdown where boolean column

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcModule.java

Allow JDBC connector to invalidate statistics cache

Allow JDBC connector to invalidate statistics cache

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/docker/DockerFiles.java

Handle race condition when files are deleted externally
Fixes https://github.com/trinodb/trino/issues/7703

Handle race condition when files are deleted externally

---

docs/src/main/sphinx/security/tls.rst

Turns out the link was busted.. please merge asap.

Fix link to glossary

---

core/trino-main/src/main/java/io/trino/operator/scalar/CharacterStringCasts.java
core/trino-main/src/test/java/io/trino/type/TestCharacterStringCasts.java
testing/trino-tests/src/test/java/io/trino/execution/TestCoordinatorDynamicFiltering.java

Rebased on top of https://github.com/trinodb/trino/pull/7595

Saturated floor cast varchar to varchar

---

docs/src/main/sphinx/installation/cli.rst

Replaces https://github.com/trinodb/trino/pull/7335

Add external/SSO authentication for CLI

---

docs/src/main/sphinx/sql.rst
docs/src/main/sphinx/sql/match-recognize.rst
docs/src/main/sphinx/sql/select.rst

This PR should follow https://github.com/trinodb/trino/pull/6550

Document MATCH_RECOGNIZE

---

docs/src/main/sphinx/connector/hive-security.rst
docs/src/main/sphinx/security.rst
docs/src/main/sphinx/security/authentication-types.rst
docs/src/main/sphinx/security/cli.rst
docs/src/main/sphinx/security/kerberos.rst
docs/src/main/sphinx/security/overview.rst

- fixes https://github.com/trinodb/trino/issues/7682
As suggested to @electrum with the minimal changes for now. Pulling CLI kerberos into the cli doc to follow as separate PR.

Refactor title and name for Kerberos authentication

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
testing/trino-product-tests/src/main/java/io/trino/tests/iceberg/TestSparkCompatibility.java

Enable listing of Iceberg tables created by Spark

---

testing/trino-product-tests/src/main/java/io/trino/tests/hive/HiveProductTest.java

Ref https://github.com/trinodb/trino/runs/2440036565

Expand flaky pattern for writing to HDFS

---

bin/ptl

Add Product Test Launcher shortcut

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadataFactory.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcConnector.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadata.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcMetadataFactory.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcModule.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestDefaultJdbcMetadata.java
plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixMetadata.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixMetadata.java

Allow binding JdbcMetadata

---

plugin/trino-blackhole/src/test/java/io/trino/plugin/blackhole/TestBlackHoleSmoke.java

Relates to https://github.com/trinodb/trino/issues/6553

Replace fail+catch pattern with assertThatThrownBy in trino-blackhole

---

plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/KafkaRecordSet.java

- reformat code to match Airlift code style
- replaced deprecated method call poll(long) with poll(Duration)
- use java streams to initialize the field  `columnTypes`

Code cosmetics performed on the class io.trino.plugin.kafka.KafkaRecordSet 

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java

Fixes bug due to insert in immutable collection after https://github.com/trinodb/trino/pull/7642

Fix iceberg SHOW TABLES with MVs

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java

In 212e1bb744bb63afa79da83efaebda63d0046091 the toRemoteTable method
called listTables unconditionally instead of returning early if
case-insensitive name matching is not enabled.
That caused query failures for information_schema queries because
instead of an early return it tried to list tables in a remote schema
called `information_schema` (which isn't intended).
This change fixes the issue by making the listTables call lazy by using
a Supplier instead of a materialized iterable.

Fix information_schema query failures in BigQuery connector

---

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/main/java/io/trino/testing/TestingMetadata.java
core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
core/trino-main/src/test/java/io/trino/sql/planner/TestMaterializedViews.java
core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java

This commit:
* Ensures that fresh materialized views are also analyzed
* Improves materialized views testing

Analyze fresh materialized views

---

docs/src/main/sphinx/functions/list.rst
docs/src/main/sphinx/functions/string.rst

**What type of PR is this:**
Updates the documentation
**What this PR does / why we need it:**
To document soundex function
**Which issue(s) this PR fixes:**
Document soundex function [#7668](https://github.com/trinodb/trino/issues/7668)
**Special notes for your reviewer:**
N/A

Document soundex function

---

docs/src/main/sphinx/functions/list.rst

Add a link to the tdigest_agg function from list.rst

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/util/TestStatistics.java

Use java streams in the method createColumnToComputedStatisticsMap

Code cosmetics io.trino.plugin.hive.util.Statistics#createColumnToComputedStatisticsMap

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java

cc @martint @kasiafi @losipiuk

Reuse Filter ID when pushing predicate into Table Scan

---

docs/src/main/sphinx/functions/url.rst

@mosabua  For fix issue https://github.com/trinodb/trino/issues/7694

Document for url function 'url_extract_protocol', added some examples.

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/configs/ConfigCdh5.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/configs/ConfigHdp3.java
testing/trino-product-tests/conf/product-tests-config-cdh5.sh
testing/trino-product-tests/conf/product-tests-config-hdp3.sh

Fixes https://github.com/trinodb/trino/issues/7898

Run iceberg tests on CDH5 and HDP3

---

plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/s3config/S3TableConfigClient.java

Remove obsolete comment in S3TableConfigClient

---

core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java

Extracted from https://github.com/trinodb/trino/pull/7913 
cc @hashhar

Allow slicing QueryAssert's MaterializedResult

---

docs/src/main/sphinx/connector/iceberg.rst

https://github.com/trinodb/trino/pull/7904#discussion_r632580182

Minor cleanup in Iceberg docs

---

core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java

The `IterativeOptimizer` invocations can be run together.

Merge PushPredicateIntoTableScan with simplifyOptimizer invocations

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlClient.java
plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java

Rename legacy type mapping helper method

---

testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchConnectorTest.java
testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchDistributedQueries.java
testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchDistributedStats.java
testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchLocalStats.java
testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchTableScanRedirection.java

Add connector test for TPCH connector

---

docs/src/main/sphinx/connector/cassandra.rst

I am not sure about all the ports. Who would know more details for this connector? @findinpath @hashhar  @martint ?

Improve Cassandra requirements

---

core/trino-spi/src/main/java/io/trino/spi/type/LongTimestampWithTimeZoneType.java

Rename fraction to picosOfMilli for consistency

---

core/trino-main/src/main/java/io/trino/sql/planner/plan/TableScanNode.java

Validate TableScanNode.enforcedConstraint

---

plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java

1. Add support for querying ClickHouse table with UUID data type
2. Add support for creating ClickHouse table with Trino uuid data type on Trino server side.
Fixes https://github.com/trinodb/trino/issues/7097

Map ClickHouse UUID to Trino UUID #7097

---

docs/src/main/sphinx/connector/sqlserver.rst

Consistent with PostgreSQL now

Improve SQL Server requirements

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/CanonicalizeExpressionRewriter.java

To allow for a case when multi-parameter date function is registered in
the future.

Drop verify check

---

docs/src/main/sphinx/connector/hive.rst

Add Thrift port to requirements

---

plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestingSqlServer.java

Retry SQL Server SET READ_COMMITTED_SNAPSHOT failure

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantTableScanPredicate.java

See https://github.com/trinodb/trino/pull/7978#discussion_r635347439

Remove incorrect assumption from a rule

---

docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-357.md

Add 357 release notes

---

core/trino-parser/pom.xml

Follows https://github.com/trinodb/trino/pull/8018
cc @losipiuk @martint @electrum @kokosing @kasiafi

Enable test sanitization in trino-parser

---

core/trino-main/src/test/java/io/trino/spiller/TestBinaryFileSpiller.java
core/trino-main/src/test/java/io/trino/spiller/TestFileSingleStreamSpiller.java
core/trino-main/src/test/java/io/trino/spiller/TestFileSingleStreamSpillerFactory.java

* replacing deprecated google commons method by java nio method
* following recommendation of creating small PRs
Relates to #6908

Remove usages of deprecated Files.create in core module

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyTableScanRedirection.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushJoinIntoTableScan.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/RemoveRedundantTableScanPredicate.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/IndexJoinOptimizer.java
core/trino-main/src/main/java/io/trino/sql/planner/planprinter/IoPlanPrinter.java
core/trino-main/src/test/java/io/trino/sql/planner/TestTableScanRedirectionWithPushdown.java
core/trino-main/src/test/java/io/trino/sql/planner/assertions/TableScanMatcher.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestApplyTableScanRedirection.java
core/trino-spi/src/main/java/io/trino/spi/predicate/TupleDomain.java
core/trino-spi/src/test/java/io/trino/spi/predicate/TestTupleDomain.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/CountQueryPageSource.java
plugin/trino-elasticsearch/src/main/java/io/trino/plugin/elasticsearch/ScanQueryPageSource.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSourceProvider.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePartitionManager.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPredicates.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsMaker.java
plugin/trino-local-file/src/main/java/io/trino/plugin/localfile/LocalFileRecordSet.java
plugin/trino-raptor-legacy/src/main/java/io/trino/plugin/raptor/legacy/RaptorMetadata.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchMetadata.java

Follows https://github.com/trinodb/trino/pull/7980
cc @martint @sopel39 @kokosing

Add TupleDomain.transformKeys

---

core/trino-main/src/main/java/io/trino/sql/InterpretedFunctionInvoker.java
core/trino-main/src/main/java/io/trino/sql/planner/DesugarTryExpressionRewriter.java
core/trino-main/src/main/java/io/trino/type/FunctionParametricType.java
core/trino-main/src/test/java/io/trino/operator/aggregation/BenchmarkGroupedTypedHistogram.java
core/trino-main/src/test/java/io/trino/operator/aggregation/TestHistogram.java
core/trino-main/src/test/java/io/trino/operator/aggregation/TestMapAggAggregation.java
core/trino-main/src/test/java/io/trino/operator/aggregation/TestMapUnionAggregation.java
core/trino-main/src/test/java/io/trino/operator/aggregation/TestMultimapAggAggregation.java

Name of NAME constant is not distinct enough to be static-imported.

Remove ambiguous NAME imports

---

core/trino-main/src/main/java/io/trino/connector/system/SystemPageSourceProvider.java
core/trino-main/src/main/java/io/trino/sql/planner/EffectivePredicateExtractor.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushPredicateIntoTableScan.java
core/trino-main/src/test/java/io/trino/sql/planner/TestTableScanRedirectionWithPushdown.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryPageSourceProvider.java

@raunaqmorarka  or @sopel39 could you please also take a look?
cc @martint @kokosing 
Follows https://github.com/trinodb/trino/pull/8005

Migrate remaining usables of TupleDomain.transform to transformKeys

---

docs/src/main/sphinx/release/release-357.md

Follows https://github.com/trinodb/trino/pull/7980 
cc @martint

Add deprecation notice to release notes

---

plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerTransactionIsolationTest.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/SqlServerQueryRunner.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerCaseInsensitiveMapping.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerConnectorTest.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerTypeMapping.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerWithSnapshotIsolation.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerWithoutSnapshotIsolation.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestSqlServerWithoutSnapshotIsolationAndReadCommittedSnapshot.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/TestingSqlServer.java

cc  @wendigo @losipiuk @hashhar @electrum

More retries for SQL Server setup

---

testing/trino-tests/src/test/java/io/trino/execution/TestErrorThrowableInQuery.java

Regression test for https://github.com/trinodb/trino/pull/8017

Add test for EXPLAIN queries throwing Error throwables

---

core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
testing/trino-tests/src/test/java/io/trino/tests/TestLocalQueryAssertions.java

Supersedes https://github.com/trinodb/trino/pull/8025.

Allow skipping results verification with and without pushdown

---

plugin/trino-base-jdbc/pom.xml
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseCaseInsensitiveMappingTest.java

Suppress verbose logging in BaseCaseInsensitiveMappingTest

Suppress verbose logging in BaseCaseInsensitiveMappingTest

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/TransactionalMetadata.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/RegisterPartitionProcedure.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/SyncPartitionMetadataProcedure.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/procedure/UnregisterPartitionProcedure.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHiveFileSystem.java

Clean up runtime casts

---

core/trino-main/src/main/java/io/trino/sql/rewrite/ShowStatsRewrite.java
core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4
core/trino-parser/src/main/java/io/trino/sql/parser/AstBuilder.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestShowStats.java

cc @martint @kokosing @kasiafi @sopel39

Allow SHOW STATS for query with LIMIT

---

plugin/trino-memory/pom.xml
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryTableStatistics.java

cc @kokosing @sopel39 @martint 
For https://github.com/trinodb/trino/pull/7913

Support simple table statistics in memory connector

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ApplyTableScanRedirection.java
core/trino-main/src/test/java/io/trino/sql/planner/TestTableScanRedirectionWithPushdown.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestApplyTableScanRedirection.java
core/trino-spi/src/main/java/io/trino/spi/connector/TableScanRedirectApplicationResult.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
testing/trino-tests/src/test/java/io/trino/tests/tpch/TestTpchTableScanRedirection.java

Depends on: https://github.com/prestosql/presto/pull/6030

Add support for coercions in table scan redirections

---

docs/src/main/sphinx/sql/show-stats.rst

Follows https://github.com/trinodb/trino/pull/8026
cc @losipiuk

Update SHOW STATS docs for query support

---

core/trino-main/src/test/java/io/trino/sql/planner/TestTableScanRedirectionWithPushdown.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestApplyTableScanRedirection.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDetermineTableScanNodePartitioning.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneTableScanColumns.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushDownDereferencesRules.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionIntoTableScan.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushTopNIntoTableScan.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestConnectorPushdownRulesWithHive.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/optimizer/TestHiveProjectionPushdownIntoTableScan.java
plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/TestThriftProjectionPushdown.java

cc @sopel39 @raunaqmorarka @losipiuk

Simplify predicate

---

core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java

cc @sopel39 @kasiafi @martint @kokosing @raunaqmorarka

Build TableScanNode fluently in PlanBuilder

---

plugin/trino-memory/src/test/java/io/trino/plugin/memory/MemoryQueryRunner.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemorySmoke.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryTableStatistics.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryWorkerCrash.java
testing/trino-tests/src/test/java/io/trino/execution/TestTry.java
testing/trino-tests/src/test/java/io/trino/tests/TestDistributedEngineOnlyQueries.java

cc @hashhar @wendigo @kokosing

Define required tables when creating memory query runner

---

core/trino-main/src/main/java/io/trino/cost/ComposableStatsCalculator.java
core/trino-main/src/main/java/io/trino/cost/FilterStatsCalculator.java
core/trino-main/src/main/java/io/trino/cost/StatsCalculator.java
core/trino-main/src/main/java/io/trino/cost/StatsCalculatorModule.java
core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
core/trino-main/src/test/java/io/trino/execution/TestCreateMaterializedViewTask.java
core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java

cc @sopel39 @martint @kokosing

Refactor stats calculator initialization

---

core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java

cc @raunaqmorarka @losipiuk @electrum @kokosing

Document getTableHandle, getView, getMaterializedView border cases

---

docs/src/main/sphinx/connector/cassandra.rst
docs/src/main/sphinx/connector/kafka.rst
docs/src/main/sphinx/connector/mongodb.rst
docs/src/main/sphinx/connector/mysql.rst
docs/src/main/sphinx/connector/oracle.rst
docs/src/main/sphinx/connector/postgresql.rst
docs/src/main/sphinx/connector/sqlserver.rst

Follow up from https://github.com/trinodb/trino/pull/8006

Edit requirements section of connectors

---

docs/src/main/sphinx/functions/binary.rst
docs/src/main/sphinx/functions/list.rst

add example of function murmur3 and update the link to it in list.rst

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryResultPageSource.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryIntegrationSmokeTest.java

Fix wrong result due to column position mismatch in BigQuery

---

core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java

Handle row ambiguous dereference as semantic error

---

testing/trino-product-tests-launcher/pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/SuiteRun.java
testing/trino-testing-services/pom.xml
testing/trino-testing-services/src/main/java/io/trino/jvm/Threads.java
testing/trino-testing-services/src/main/java/io/trino/testng/services/LogTestDurationListener.java

fixes https://github.com/trinodb/trino/issues/6202 
cc @losipiuk @kokosing

Print full thread dump when tests hang

---

core/docker/default/etc/config.properties
core/trino-main/src/main/java/io/trino/server/CoordinatorDiscoveryModule.java
core/trino-main/src/main/java/io/trino/server/CoordinatorModule.java
core/trino-main/src/main/java/io/trino/server/Server.java
core/trino-main/src/test/java/io/trino/server/TestEmbeddedDiscoveryConfig.java
core/trino-server-rpm/src/main/resources/dist/config/config.properties
docs/src/main/sphinx/installation/deployment.rst
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/hadoop-kerberos/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/standard-multinode/multinode-master-config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/common/standard/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-tls-kerberos/config-master.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-tls/config-master.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-ldap-and-file/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-ldap/config.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/singlenode-oauth2/config.properties
testing/trino-server-dev/etc/config.properties

The property is now enabled by default.

Deprecate embedded discovery service config property

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/BenchmarkFileFormatsUtils.java

Missed it in https://github.com/trinodb/trino/pull/8206

Fix typo in method name

---

plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/AbstractTestOracleTypeMapping.java

relates to #6394
- In 8601794, `legacyDateTests` was removed. 
#4799 remove legacy timestamp, and modify `TestOracleTypes.java` (now is `AbstractTestOracleTypeMapping.java`) as follows.
which makes `runLegacyTimestampTestInZone` and `runTimestampTestInZone` both do the same thing and makes `legacyDateTests` became a subset of `DateTests`.
- In 63fa565, there are two test cases in `testTimestampWithTimeZoneFromOracle()` still use `DataTypeTest`.
- `'2018-10-28 01:33:17.456 America/Bahia_Banderas'`
- `'2018-10-28 03:33:33.333000000', 'Europe/Vilnius'`
Both of them are in DST which make SqlDataTypeTest fail. 
For example, `2018-10-28 01:33:17.456 America/Bahia_Banderas` is stored in oracle, when trino get it back, the value is `1540711997456` in millisecond, while in trino sql `values …

Convert oracle date/timestamp/timestamp with tz type tests to SqlDataTypeTest

---

pom.xml
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveViews.java

Fixes: https://github.com/trinodb/trino/issues/7635
Depends on Coral release which includes: https://github.com/linkedin/coral/pull/96/
cc: @findepi

Update Coral to fix translation of Hive views with nested GROUP BY

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/CachingJdbcClient.java

cc @kokosing @ssheikin @hashhar @wendigo

Retain more cached information upon insert

---

docs/src/main/sphinx/functions/list.rst
docs/src/main/sphinx/functions/string.rst

Document luhn_check function

---

core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
core/trino-main/src/main/java/io/trino/sql/planner/LiteralEncoder.java
core/trino-main/src/test/java/io/trino/sql/planner/AbstractPredicatePushdownTest.java
core/trino-main/src/test/java/io/trino/sql/planner/TestLiteralEncoder.java
core/trino-main/src/test/java/io/trino/sql/planner/TestTableScanRedirectionWithPushdown.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestApplyTableScanRedirection.java

Relates to https://github.com/trinodb/trino/pull/8275 and https://trinodb.slack.com/archives/CP1MUNEUX/p1623666956326300

Encode unbounded varchar value without a CAST

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadataFactory.java

Separate instantiation from other logic.

Refactor HiveMetadataFactory

---

lib/trino-parquet/src/main/java/io/trino/parquet/ParquetTypeUtils.java
pom.xml

Depends on https://github.com/trinodb/trino-hive-apache/pull/28

Update to Parquet 1.12.0

---

plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java

Rename `arrayToPrestoType` method to `arrayToTrinoType`

---

core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/planner/DesugarLikeRewriter.java
core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
core/trino-main/src/main/java/io/trino/type/LikeFunctions.java
core/trino-main/src/test/java/io/trino/operator/scalar/AbstractTestFunctions.java
core/trino-main/src/test/java/io/trino/sql/TestExpressionInterpreter.java
core/trino-main/src/test/java/io/trino/sql/TestLikeFunctions.java
core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
docs/src/main/sphinx/sql/match-recognize.rst
testing/trino-benchto-benchmarks/src/main/resources/sql/presto/tpcds/q91.sql
testing/trino-product-tests/src/main/resources/sql-tests/testcases/tpcds/q91.sql

Fixes https://github.com/trinodb/trino/issues/8311

Fix LIKE with char

---

docs/src/main/sphinx/connector/clickhouse.rst

Add standard requirements section for the ClickHouse connector doc.

Add requirements for ClickHouse connector

---

docs/src/main/sphinx/connector/druid.rst

Add standard requirements section for the Druid connector doc.

Add requirements for Druid connector

---

plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java

Fixes #7521
Only supports Phoenix 5, since I cannot update the Phoenix 4 client without breaking compatibility.

Push topN to Phoenix unconditionally

---

core/trino-main/src/main/java/io/trino/server/security/jwt/JwkService.java
core/trino-main/src/main/java/io/trino/server/security/jwt/JwtAuthenticatorSupportModule.java
core/trino-main/src/main/java/io/trino/server/security/oauth2/OAuth2ServiceModule.java
core/trino-main/src/test/java/io/trino/block/AbstractTestBlock.java
core/trino-main/src/test/java/io/trino/execution/TestSqlTaskManager.java
core/trino-main/src/test/java/io/trino/memory/TestTotalReservationLowMemoryKiller.java
core/trino-main/src/test/java/io/trino/memory/TestTotalReservationOnBlockedNodesLowMemoryKiller.java
core/trino-main/src/test/java/io/trino/operator/TestRowNumberOperator.java
core/trino-main/src/test/java/io/trino/operator/window/AbstractTestWindowFunction.java
core/trino-main/src/test/java/io/trino/server/security/TestResourceSecurity.java
core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilter.java
core/trino-main/src/test/java/io/trino/server/ui/TestWebUi.java
lib/trino-orc/src/test/java/io/trino/orc/TestOrcReader.java
lib/trino-rcfile/src/test/java/io/trino/rcfile/TestRcFileReader.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryIntegrationSmokeTest.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryType.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestTypeConversions.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestJsonCassandraHandles.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/TestParquetReader.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoDistributedQueries.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/TestRaptorIntegrationSmokeTestMySql.java
plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestRedisDistributedHash.java
plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestRedisPlugin.java
plugin/trino-session-property-managers/src/test/java/io/trino/plugin/session/AbstractTestSessionPropertyManager.java
testing/trino-tests/src/test/java/io/trino/memory/TestClusterMemoryLeakDetector.java

Do not inject JwkService in guice manually

Do not inject JwkService in guice manually

---

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java

Coercions for views are handled automatically
in RelationPlanner#visitTable method

Remove unnecessary addRelationCoercion call

---

docs/src/main/sphinx/functions/lambda.rst

Document lambda functions

---

docs/src/main/sphinx/connector/bigquery.rst

Reformat BigQuery connector requirements section to be more in line with other connectors.

Reformat BigQuery connector requirements section

---

docs/src/main/sphinx/connector/phoenix.rst

Add a standard section describing the requirements to use the Phoenix connector.

Add requirements for Phoenix connector

---

docs/src/main/sphinx/connector/clickhouse.rst

See https://github.com/trinodb/trino/issues/8331 for some context.

Fix ClickHouse table property documentation and examples

---

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
core/trino-main/src/main/java/io/trino/SystemSessionPropertiesProvider.java
core/trino-main/src/main/java/io/trino/dispatcher/DispatchManager.java
core/trino-main/src/main/java/io/trino/metadata/SessionPropertyManager.java
core/trino-main/src/main/java/io/trino/server/ServerMainModule.java

Add option to configure many SystemSessionPropertiesProviders
in the SessionPropertyManager

Add SystemSessionPropertiesProvider

---

testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java

Not all connector tests run within containers so any operation that
deletes data from the TPCH tables can change state of the testing
infrastructure leading to hard to diagnose failures.
So we create temporary tables to verify if deletes are supported or not.

Use a temporary table to verify if deletes are supported

---

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
core/trino-main/src/main/java/io/trino/execution/DynamicFilterConfig.java
core/trino-main/src/main/java/io/trino/execution/DynamicFiltersCollector.java
core/trino-main/src/main/java/io/trino/execution/MemoryTrackingRemoteTaskFactory.java
core/trino-main/src/main/java/io/trino/execution/RemoteTaskFactory.java
core/trino-main/src/main/java/io/trino/execution/SqlStageExecution.java
core/trino-main/src/main/java/io/trino/execution/SqlTask.java
core/trino-main/src/main/java/io/trino/execution/SqlTaskManager.java
core/trino-main/src/main/java/io/trino/execution/TaskManager.java
core/trino-main/src/main/java/io/trino/operator/TaskContext.java
core/trino-main/src/main/java/io/trino/server/DynamicFilterService.java
core/trino-main/src/main/java/io/trino/server/HttpRemoteTaskFactory.java
core/trino-main/src/main/java/io/trino/server/TaskResource.java
core/trino-main/src/main/java/io/trino/server/TaskUpdateRequest.java
core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
core/trino-main/src/main/java/io/trino/server/remotetask/RemoteTaskStats.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalDynamicFiltersCollector.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
core/trino-main/src/test/java/io/trino/execution/MockRemoteTaskFactory.java
core/trino-main/src/test/java/io/trino/execution/TaskTestUtils.java
core/trino-main/src/test/java/io/trino/execution/TestDynamicFilterConfig.java
core/trino-main/src/test/java/io/trino/execution/TestSqlTask.java
core/trino-main/src/test/java/io/trino/execution/TestSqlTaskManager.java
core/trino-main/src/test/java/io/trino/server/TestDynamicFilterService.java
core/trino-main/src/test/java/io/trino/server/remotetask/TestHttpRemoteTask.java
core/trino-main/src/test/java/io/trino/sql/planner/TestLocalDynamicFiltersCollector.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveDynamicPartitionPruning.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemorySmoke.java
testing/trino-tests/src/test/java/io/trino/execution/TestCoordinatorDynamicFiltering.java

Fixes https://github.com/prestosql/presto/issues/3972

Send dynamic filters from coordinator to workers

---

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/BaseJdbcConnectorTest.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraLatestConnectorSmokeTest.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorSmokeTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergConnectorSmokeTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorSmokeTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Extract tests to verify DELETE support

---

plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java

Filter when adding to the list and then just getOnlyElement if non-empty instead of "check if not empty, then Optional of getOnlyElement of stream filtered & collected to a list".

Simplify & clean up table handle lookup in DruidJdbcClient

---

docs/src/main/sphinx/sql.rst
docs/src/main/sphinx/sql/create-materialized-view.rst
docs/src/main/sphinx/sql/drop-materialized-view.rst
docs/src/main/sphinx/sql/refresh-materialized-view.rst
docs/src/main/sphinx/sql/show-create-materialized-view.rst

Related to the SQL support docs in the Iceberg connector. 
As a follow up after this I will update links and add more info in iceberg connector

Add documentation for materialized views

---

plugin/trino-iceberg/pom.xml
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTransforms.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergBucketing.java

This is  https://github.com/trinodb/trino/pull/8104 + my comments.
Already reviewed by me there.

Test Iceberg bucketing

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergBucketing.java

More Iceberg bucketing tests

---

plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
plugin/trino-memory/src/main/java/io/trino/plugin/memory/MemoryMetadata.java

Left over from b63e63606724dd6775586b3cf32b12a34063b70c https://github.com/trinodb/trino/pull/8598).

Remove redundant override

---

core/trino-main/src/main/java/io/trino/cost/StatsUtil.java
core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
core/trino-main/src/main/java/io/trino/sql/rewrite/ShowStatsRewrite.java
core/trino-main/src/main/java/io/trino/testing/TestingSession.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestShowStats.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsMaker.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergParquetConnectorTest.java

Fix reading Iceberg stats when transformation changes type

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java

Fixes: https://github.com/trinodb/trino/issues/5892

Enable iceberg materialized view tests

---

docs/src/main/sphinx/connector/iceberg.rst

Follow up to https://github.com/trinodb/trino/pull/8540 since docs were not updated in that PR. 
Fyi .. this links to https://github.com/trinodb/trino/blob/master/docs/src/main/sphinx/language/sql-support.rst#views-management

Add views to SQL support for Iceberg connector

---

docs/src/main/sphinx/connector/hive.rst

inserting quotes and additional text
**Closes #7572**

updating hive.rst

---

core/trino-main/src/main/java/io/trino/metadata/CatalogMetadata.java
core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Reusable test related to https://github.com/trinodb/trino/pull/8596, cc @caneGuy @hashhar

Fix SHOW CREATE SCHEMA information_schema

---

core/trino-spi/src/main/java/io/trino/spi/predicate/TupleDomain.java
core/trino-spi/src/test/java/io/trino/spi/predicate/TestTupleDomain.java

cc @martint @kokosing @sopel39 @raunaqmorarka 
Follows https://github.com/trinodb/trino/pull/8053

Remove deprecated TupleDomain.transform

---

docs/src/main/sphinx/security/internal-communication.rst

Follow up to https://github.com/trinodb/trino/pull/7954
Based on guesses on my side looking at https://github.com/airlift/airlift/commit/084ca9cfc62764c2234c20e06dadab5bebb88ae2
I tried to keep stuff untouched that did not need urgently changes .. but could rip in more to improve wording.

Document internal TLS configuration

---

docs/src/main/sphinx/connector/iceberg.rst

@anjalinorwood I used some of your info from the comments on the m views doc PR. 
Also note that all the other subsections are now moved under SQL support.

Add details about materialized views in Iceberg

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/Partition.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTable.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsMaker.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Fixes https://github.com/trinodb/trino/issues/7999

Fix reading Iceberg stats when table has nested fields

---

plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java

For varchar/char types since Postgresql has different case
sensitivity than Trino, a simplified domain should not be
pushed down if it is not a discrete set.

Fix incorrect pushdown of simplified domain in postgresql

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcPageSink.java

https://github.com/trinodb/trino/pull/8434#issuecomment-878157652

Add comment about batch size property purpose and usage

---

docs/src/main/sphinx/connector/memsql.rst

Update the SingleStore connector doc with a standardized SQL support section.

Add SQL support content to SingleStore connector

---

.github/workflows/ci.yml
pom.xml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentModule.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentOptions.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Hadoop.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/TwoKerberosHives.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/TwoMixedHives.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/testcontainers/PortBinder.java

This improves M1 Mac compatibility

Update testcontainers to 1.16.0

---

plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHivePlugin.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergPlugin.java

Test IcebergPlugin

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java

**Description**
Issue: https://github.com/trinodb/trino/issues/6738
- Test parquet optimized reader (re-using existing parquet reader tests)
- Test failures are fixed by skipping Timestamp datatypes for the optimizer reader, pending: https://github.com/trinodb/trino/issues/5357

Test optimized Parquet writer in Hive product tests

---

docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-360.md

Closes https://github.com/trinodb/trino/issues/8455

Add 360 release notes

---

lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/metrics/TestMetrics.java
plugin/trino-memory/src/test/java/io/trino/plugin/memory/TestMemoryConnectorTest.java

Following https://github.com/trinodb/trino/pull/6232#pullrequestreview-716835778.

Don't use raw Metric type outside of Metrics class

---

pom.xml

Update error-prone to 2.8.0

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergHiveTablesCompatibility.java

Test Iceberg and Hive table compatibility

---

plugin/trino-postgresql/pom.xml
pom.xml

The PostgreSQL connector is not yet updated due to incompatibilities.

Update PostgreSQL driver to 42.2.23

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/PropertiesSystemTableProvider.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHivePropertiesTable.java

Expose $properties table for views in Hive connector

---

docs/src/main/sphinx/functions/list.rst

Add link for MongoDB objectid_timestamp in function list

---

DEVELOPMENT.md

Added merge strategy to DEVELOPMENT.md

---

docs/src/main/sphinx/admin/properties-spilling.rst

ATT, just then ending letter of configure `spill-window-operator`

Doc correct spill-window-operator ending

---

core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalAverageAggregation.java
core/trino-main/src/main/java/io/trino/operator/aggregation/DecimalSumAggregation.java
core/trino-main/src/main/java/io/trino/operator/aggregation/state/LongDecimalWithOverflowAndLongStateFactory.java
core/trino-main/src/main/java/io/trino/operator/aggregation/state/LongDecimalWithOverflowAndLongStateSerializer.java
core/trino-main/src/main/java/io/trino/operator/aggregation/state/LongDecimalWithOverflowStateFactory.java
core/trino-main/src/main/java/io/trino/operator/aggregation/state/LongDecimalWithOverflowStateSerializer.java
core/trino-main/src/test/java/io/trino/operator/aggregation/BenchmarkDecimalAggregation.java
core/trino-main/src/test/java/io/trino/operator/aggregation/TestDecimalAverageAggregation.java
core/trino-main/src/test/java/io/trino/operator/aggregation/TestDecimalSumAggregation.java
lib/trino-array/src/main/java/io/trino/array/ObjectBigArray.java

Follow up from work started in https://github.com/trinodb/trino/pull/6591
Benchmarks: [link](https://jmh.morethan.io/?sources=https://gist.githubusercontent.com/pettyjamesm/3c842310a1700c981ab8578a1cae6ab4/raw/5fdf67d68567bd49e73029ccc154d9807bd0f3d7/baseline_decimals.json,https://gist.githubusercontent.com/pettyjamesm/3c842310a1700c981ab8578a1cae6ab4/raw/5fdf67d68567bd49e73029ccc154d9807bd0f3d7/improved_decimals.json)

Improve Decimal Aggregations (again)

---

plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraType.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraTestingUtils.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnector.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnectorTest.java

Supersedes #3796
Unfortunately, there was no response for a month even on Slack, but some people have waited the merging.

Support pushdown for date, tinyint and smallint types in Cassandra

---

docs/src/main/sphinx/connector/alter-table-limitation.fragment
docs/src/main/sphinx/connector/memsql.rst
docs/src/main/sphinx/connector/oracle.rst
docs/src/main/sphinx/connector/postgresql.rst
docs/src/main/sphinx/connector/sqlserver.rst

Create a fragment discussing the multi-schema rename limitation and add to applicable connectors

Add ALTER TABLE limitation fragment

---

pom.xml

Update error-prone to 2.8.1

---

core/trino-main/src/test/java/io/trino/connector/MockConnector.java
testing/trino-tests/src/test/java/io/trino/tests/TestMockConnector.java

Properly handle projection in MockConnector

Properly handle projection in MockConnector

---

docs/src/main/sphinx/connector/kafka.rst

Add a standard SQL support section that describes what SQL statements are supported by the Kafka connector

Add SQL support to Kafka connector

---

core/trino-main/src/test/java/io/trino/block/BlockAssertions.java
core/trino-main/src/test/java/io/trino/block/TestBlockAssertions.java
core/trino-main/src/test/java/io/trino/operator/PageTestUtils.java
core/trino-main/src/test/java/io/trino/operator/output/BenchmarkPartitionedOutputOperator.java

Add benchmarks for common block types
Add utils to create random pages and blocks
Use OperatorFactories in BenchmarkPartitionedOutputOperator

Improve BenchmarkPartitionedOutputOperator

---

core/trino-main/src/main/java/io/trino/type/UuidOperators.java
core/trino-spi/src/main/java/io/trino/spi/type/UuidType.java
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java

for CI, already reviewed @ https://github.com/trinodb/trino/pull/8747#issuecomment-892115846

[for CI] Add helper method for common UUID conversions

---

core/trino-main/src/test/java/io/trino/connector/MockConnector.java

Mock more functionalities in MockConnector

Mock more functionalities in MockConnector

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/UnwrapCastInComparison.java
testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java

Fixes https://github.com/trinodb/trino/issues/9036

Fix failure query casts varchar to shorter char

---

core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
core/trino-main/src/main/java/io/trino/security/AccessControlModule.java
core/trino-main/src/main/java/io/trino/security/ForDefaultSystemAccessControl.java
core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
core/trino-main/src/test/java/io/trino/execution/TestCommitTask.java
core/trino-main/src/test/java/io/trino/execution/TestDeallocateTask.java
core/trino-main/src/test/java/io/trino/execution/TestPrepareTask.java
core/trino-main/src/test/java/io/trino/execution/TestQueryStateMachine.java
core/trino-main/src/test/java/io/trino/execution/TestStartTransactionTask.java
core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java
core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java
core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java

Allow to override default system access control

Allow to override default system access control

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java

hopefully fixes https://github.com/trinodb/trino/issues/9040
Relates to https://github.com/trinodb/trino/issues/9039 and to https://github.com/trinodb/trino/issues/9041

Fix testMaterializedViewsMetadata flakiness due to lack of pruning

---

docs/src/main/sphinx/admin/spill.rst

ATT, just some window function term word change

Doc correct then term of window function

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/Conversions.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryIntegrationSmokeTest.java

Skip unsupported type in BigQuery connector

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/EnvironmentContainers.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/HadoopKerberos.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/HadoopKerberosKms.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/common/Standard.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/MultinodeKafka.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/MultinodeKafkaSsl.java
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/SinglenodeLdapAndFile.java

Deprecate CONTAINER_TEMPTO_PROFILE_CONFIG

Deprecate CONTAINER_TEMPTO_PROFILE_CONFIG

---

core/trino-main/src/main/java/io/trino/security/AccessControlManager.java
core/trino-main/src/main/java/io/trino/security/AccessControlModule.java
core/trino-main/src/main/java/io/trino/security/DefaultSystemAccessControlName.java
core/trino-main/src/main/java/io/trino/testing/TestingAccessControlManager.java
core/trino-main/src/test/java/io/trino/execution/TestCommitTask.java
core/trino-main/src/test/java/io/trino/execution/TestDeallocateTask.java
core/trino-main/src/test/java/io/trino/execution/TestPrepareTask.java
core/trino-main/src/test/java/io/trino/execution/TestQueryStateMachine.java
core/trino-main/src/test/java/io/trino/execution/TestStartTransactionTask.java
core/trino-main/src/test/java/io/trino/security/TestAccessControlManager.java
core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java
core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/DefaultSystemAccessControl.java

Restore default system access control

Restore default system access control

---

docs/src/main/sphinx/connector/memory.rst

Follow up to https://github.com/trinodb/trino/pull/8970 
Please confirm that memory is managed per catalog @hashhar

Move and correct SQL support section

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/Int64TimestampMillisColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/TimeMicrosColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/TimestampMicrosColumnReader.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCompression.java

Fixes https://github.com/trinodb/trino/issues/9143

More Parquet compression tests

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java

See https://github.com/trinodb/trino/pull/9147 for stress test results before & after change.

Mark hive views testNestedGroupBy test as @Flaky

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/ReadSessionCreator.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/BigQueryQueryRunner.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryCaseInsensitiveMapping.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/sql/TestView.java

Support case insensitive name matching to BigQuery views

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueColumnStatisticsProvider.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueColumnStatisticsProviderFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DisabledGlueColumnStatisticsProviderFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueColumnStatisticsProviderFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueMetastoreStats.java

Follow up from https://github.com/trinodb/trino/pull/8839

Record JMX metrics for calls made to the Glue statistics API

---

pom.xml

Depends on https://github.com/trinodb/trino-hive-apache/pull/30

Update to Avro 1.10.2

---

docs/src/main/sphinx/connector/hive-azure.rst

Correct connection string examples

---

plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotIntegrationSmokeTest.java

Fixes https://github.com/trinodb/trino/issues/9197.

Fix multiple flaky tests in TestPinotIntegrationSmokeTest

---

docs/src/main/sphinx/optimizer/pushdown.rst

Add Predicate and Column Projection Pushdown Section

---

docs/src/main/sphinx/security/internal-communication.rst

Add note about no Java 17 support

---

docs/src/main/sphinx/connector/bigquery.rst
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java

Document bigquery.views-cache-ttl config properties

---

core/trino-main/src/test/java/io/trino/block/TestDictionaryBlock.java
core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java

Size calculation for dictionary blocks should
do so as if the block was compacted. Dictionary
blocks are unnested during compaction.
However, calculateCompactSize used getPositionsSizeInBytes
for nested dictionaries. Therefore it did not took
dictionary unnesting into account.

Fix size calculation for nested dictionary block

---

.github/workflows/milestone.yml

Here is my sample repository having the same job: https://github.com/ebyhr/github-actions-playground

Add GitHub Actions job to set milestone for merged PR

---

docs/src/main/sphinx/connector/hive-s3.rst
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/util/JsonUtils.java
plugin/trino-hive/pom.xml
plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/FileBasedS3SecurityMappingsProvider.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/ForS3SecurityMapping.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/HiveS3Module.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/S3SecurityMappingConfig.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/S3SecurityMappingConfigurationProvider.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/S3SecurityMappingsParser.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/S3SecurityMappingsProvider.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/UriBasedS3SecurityMappingsProvider.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestS3SecurityMapping.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestS3SecurityMappingConfig.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestS3SecurityMappingsParser.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/TestUriBasedS3SecurityMappingsProvider.java

Hey guys,
this PR addresses issue #6187. The provider for the S3 security mappings is made customisable.

add option to configure s3 mappings provider

---

.github/workflows/ci.yml
bin/ptl
testing/bin/ptl
testing/trino-product-tests/README.md

This keeps the top level directory tidy.

Move bin/ptl to testing directory

---

docs/src/main/sphinx/admin/properties-exchange.rst
docs/src/main/sphinx/admin/properties-general.rst
docs/src/main/sphinx/admin/properties-logging.rst
docs/src/main/sphinx/admin/properties-memory-management.rst
docs/src/main/sphinx/admin/properties-node-scheduler.rst
docs/src/main/sphinx/admin/properties-optimizer.rst
docs/src/main/sphinx/admin/properties-query-management.rst
docs/src/main/sphinx/admin/properties-regexp-function.rst
docs/src/main/sphinx/admin/properties-spilling.rst
docs/src/main/sphinx/admin/properties-task.rst
docs/src/main/sphinx/admin/properties-web-interface.rst
docs/src/main/sphinx/admin/properties-write-partitioning.rst
docs/src/main/sphinx/admin/properties-writer-scaling.rst
docs/src/main/sphinx/admin/properties.rst

Document the supported values for configuration property types.

Define and link back to property types

---

core/trino-main/src/test/java/io/trino/type/TestTimeWithTimeZoneType.java
core/trino-spi/src/main/java/io/trino/spi/type/SqlTime.java
core/trino-spi/src/main/java/io/trino/spi/type/SqlTimestamp.java
core/trino-spi/src/main/java/io/trino/spi/type/SqlTimestampWithTimeZone.java

Extracted from https://github.com/trinodb/trino/pull/9280 while https://github.com/trinodb/trino/pull/9280#discussion_r711010103 is debated.
already reviewed by @losipiuk in https://github.com/trinodb/trino/issues/9280

Minor date/time cleanups 

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/PrimitiveColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/UuidColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetWriters.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/valuewriter/UuidValueWriter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/ExpressionConverter.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSink.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionData.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTransforms.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TypeConverter.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergBucketing.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
testing/trino-testing/src/main/java/io/trino/testing/H2QueryRunner.java

Fixes https://github.com/trinodb/trino/issues/6663 
cc @rdblue

Support Iceberg UUID type

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/GlueHiveMetastore.java

Note: PR from trinodb/trino so AWS Glue tests are run

Contraint batchUpdatePartitionAsync request size when talking to AWS Glue

---

docs/src/main/sphinx/sql/create-materialized-view.rst

Follow up to https://github.com/trinodb/trino/pull/8796/files
I am guessing at this stage... please correct me if anything is wrong or missing.

Add info about metadata table for materialized views

---

.github/workflows/milestone.yml

Sorry, I forgot to remove this condition in #9268

Remove unnecessary condition in milestone job

---

core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
core/trino-parser/src/main/java/io/trino/sql/QueryUtil.java
testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java

Fix SHOW ROLES where there are no roles to display
Fixes #9189

Fix SHOW ROLES where there are no roles to display

---

core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java

AFTER
mayHaveNull=true
BenchmarkDictionaryBlock.isNull               100000  avgt   45  52,261 ± 2,050  us/op
mayHaveNull=false
Benchmark                        (selectedPositions)  Mode  Cnt  Score   Error  Units
BenchmarkDictionaryBlock.isNull               100000  avgt   45  1,857 ± 0,099  us/op
BEFORE
BenchmarkDictionaryBlock.isNull               100000  avgt   45  54,168 ± 2,305  us/op

Skip delegating isNull call if dictionary doesn't have nulls

---

plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClientModule.java

It will return a set of properties to be passed to JDBC, derived from the configuration.

 Extract a utility method to get MySQL connection properties

---

testing/trino-testing-kafka/src/main/java/io/trino/testing/kafka/TestingKafka.java

Increase startup attempts from 1 to 3 in Kafka containers

---

plugin/trino-hive-hadoop2/src/test/java/io/trino/plugin/hive/TestHive.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveInMemoryMetastore.java

The staging directory is shared mutable state.

Run AbstractTestHive single-threaded

---

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControl.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/security/FileBasedSystemAccessControlRules.java
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedSystemAccessControl.java

Some cleanups and minor fixes to tests in and around `FileBasedSystemAccessControl`.
Extracted from #9176

Cleanup file based system access control

---

plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoServer.java

Fixes #8457 Fixes #7005
Stress test: https://github.com/trinodb/trino/runs/3700255475

Increase startup attempts from 1 to 3 in MongoDB container

---

plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java

Enable mapping to varchar and unsupported type handling in Phoenix

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/CountingAccessFileHiveMetastore.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMetastoreAccessOperations.java

For https://github.com/trinodb/trino/issues/8675

Test metastore access count for Iceberg views

---

core/trino-main/src/main/resources/webapp/src/components/QueryList.jsx

Apply limit in WebUI when query state or error type filters update

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/FilteredOffsetIndex.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetColumnChunk.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestParquetPageSkipping.java

Fixes the failure scenario identified in https://github.com/trinodb/trino/issues/9382
Fixes #9097

Fix calculateOffsetRanges in parquet page filtering

---

plugin/trino-http-event-listener/src/test/java/io/trino/plugin/httpquery/TestHttpQueryListener.java

Fixes #9432
I could reproduce this issue easily in local IDE and confirmed it was resolved by this change.

Ignore IOException in TestHttpQueryListener.teardown

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveBucketedTables.java

WITH section after table is created is Hive version dependent.

Relax assertion in testBucketingWithUnsupportedDataTypes

---

core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java

Limits in DynamicFilterSourceOperator increased when a single gather exchange is used instead of a partitioned one.
Attached tpch/tpcds benchmark results showing no regressions:
[Benchmarks comparison-increased-df-limit.pdf](https://github.com/trinodb/trino/files/7253672/Benchmarks.comparison-increased-df-limit.pdf)

Increase DynamicFilterSourceOperator limits for gather exchange

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Store column comment when adding a new column in Iceberg

---

core/trino-main/src/test/java/io/trino/spiller/TestFileSingleStreamSpillerFactory.java

Remove usage of @Test(expectedExceptions...) from TestFileSingleStreamSpillerFactory

---

core/trino-main/src/test/java/io/trino/server/protocol/TestQueryResultRows.java

Use assertThatThrownBy in TestQueryResultRows

---

core/trino-main/src/test/java/io/trino/execution/TestSetPathTask.java

Use assertThatThrownBy in TestSetPathTask

---

core/trino-main/src/test/java/io/trino/server/TestQueryStateInfoResource.java

Use assertThatThrownBy in TestQueryStateInfoResource

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryFilterQueryBuilder.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryType.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryTypeMapping.java
testing/trino-testing/src/main/java/io/trino/testing/datatype/SqlDataTypeTest.java

Disable predicate pushdown for geography, array and struct in BigQuery

---

plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/DynamicTablePqlExtractor.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/FilterToPinotSqlConverter.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/query/PinotQueryBuilder.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestDynamicTable.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestPinotIntegrationSmokeTest.java
plugin/trino-pinot/src/test/resources/reserved_keyword_realtimeSpec.json
plugin/trino-pinot/src/test/resources/reserved_keyword_schema.json

Quote identifiers when building Pinot query

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java

Replace query with onTrino.executeQuery to make sure that retry mechanism from QueryExecutors is used

Remove Flaky annotation from TestHiveStorageFormats#testInsertIntoTable, rely on QueryExecutors retry mechanism

---

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
core/trino-main/src/main/java/io/trino/execution/CreateRoleTask.java
core/trino-main/src/main/java/io/trino/execution/DropRoleTask.java
core/trino-main/src/main/java/io/trino/execution/GrantRolesTask.java
core/trino-main/src/main/java/io/trino/execution/RevokeRolesTask.java
core/trino-main/src/main/java/io/trino/execution/SetRoleTask.java
core/trino-main/src/main/java/io/trino/metadata/MetadataUtil.java
core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java
core/trino-main/src/test/java/io/trino/execution/TestSetRoleTask.java
testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java

Respect deprecated.legacy-catalog-roles=true in SHOW ROLES

Respect deprecated.legacy-catalog-roles=true in SHOW ROLES

---

core/trino-main/src/test/java/io/trino/server/security/oauth2/BaseOAuth2WebUiAuthenticationFilterTest.java
core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithJwt.java
core/trino-main/src/test/java/io/trino/server/security/oauth2/TestOAuth2WebUiAuthenticationFilterWithOpaque.java

Rename class to reflect it is abstract test class

Rename class to reflect it is abstract test class

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/BaseJdbcClient.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/StandardColumnMappings.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java

Unfortunately, there is no tests in Redshift connector.

Inline legacyColumnMapping method in Redshift

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java

Use assertThatThrownBy in TestHiveConnectorTest

---

docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-364.md

Closes https://github.com/trinodb/trino/issues/9534

Add 364 release notes

---

core/trino-parser/src/main/java/io/trino/sql/SqlFormatter.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java

Fixes https://github.com/trinodb/trino/issues/9822

Fix formatting of DROP TABLE and INSERT

---

plugin/trino-postgresql/pom.xml
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/TypeUtils.java
pom.xml

Upgrade PostgreSQL driver to 42.3.1

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitSource.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveSplit.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/InternalHiveSplitFactory.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveSplitSource.java

Perform one more dynamic partition pruning check
before split is returned to the engine

Perform one more dynamic partition pruning check

---

core/trino-main/src/main/java/io/trino/execution/SqlStageExecution.java
core/trino-main/src/main/java/io/trino/execution/StageStateMachine.java
core/trino-main/src/main/java/io/trino/operator/ExchangeClient.java
core/trino-main/src/main/java/io/trino/operator/HttpPageBufferClient.java
core/trino-main/src/main/java/io/trino/server/protocol/Query.java
core/trino-main/src/main/java/io/trino/server/remotetask/HttpRemoteTask.java
core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java
core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmenter.java
core/trino-main/src/main/java/io/trino/sql/planner/planprinter/HashCollisionPlanNodeStats.java
core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanNodeStats.java
core/trino-main/src/main/java/io/trino/sql/planner/planprinter/WindowPlanNodeStats.java
core/trino-main/src/test/java/io/trino/operator/TestExchangeClient.java
core/trino-main/src/test/java/io/trino/operator/TestHttpPageBufferClient.java
core/trino-main/src/test/java/io/trino/operator/TestingExchangeHttpClientHandler.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java

https://github.com/trinodb/trino/pull/9818

Fix various issues discovered while working on failure recovery

---

docs/src/main/sphinx/connector/cassandra.rst
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraClusteringPredicatesExtractor.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraRecordCursor.java
plugin/trino-cassandra/src/main/java/io/trino/plugin/cassandra/CassandraType.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraTestingUtils.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestCassandraConnector.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/cassandra/TestSelect.java

Support user defined type in Cassandra

---

.github/DEVELOPMENT.md

Just helpful for new people like me. Thanks @jirassimok for the tip.

Add docs on running checkstyle locally

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseTestHiveInsertOverwrite.java

Test was missing final check that all old records where removed.

Fix partition overwrite assertion

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/file/FileHiveMetastore.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestCreateDropSchema.java

Extracted from #9740, already reviewed by me.

Testing code refactors

---

core/trino-spi/src/main/java/io/trino/spi/metrics/Metrics.java

Fixes https://github.com/trinodb/trino/issues/9903

Fix raw types use in Metrics

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcWriterOptions.java
pom.xml

Fix OrcWriterOptions mapping from Hive TableProperties

---

core/trino-main/src/main/java/io/trino/Session.java
core/trino-main/src/main/java/io/trino/metadata/SessionPropertyManager.java
core/trino-main/src/main/java/io/trino/server/SessionPropertyDefaults.java
core/trino-main/src/main/java/io/trino/testing/AllowAllAccessControlManager.java
core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
core/trino-main/src/test/java/io/trino/server/TestSessionPropertyDefaults.java
plugin/trino-session-property-managers/pom.xml
plugin/trino-session-property-managers/src/test/java/io/trino/plugin/session/TestSessionPropertyManagerInTransaction.java
plugin/trino-session-property-managers/src/test/resources/io/trino/plugin/session/file/session-property-config.json
plugin/trino-session-property-managers/src/test/resources/io/trino/plugin/session/file/session-property-config.properties
testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java

Allow session properties defaults in transaction

---

docs/src/main/sphinx/connector/bigquery.rst
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryClient.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryType.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/Conversions.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryTypeMapping.java

Support reading BIGNUMERIC type in BigQuery

---

core/trino-main/src/main/java/io/trino/server/InternalCommunicationModule.java

Update internal communication automatic TLS to use IP_ENCODED_AS_HOSTNAME.  This converts the raw ip address into a hostname using facilities in airlift http.  This addresses incompatibility issues with SNI and IP address URIs.  Additionally, this adds a filter to rewrite discover client requests to use an internal name which addresses compatibility issues with K8s like setups.

Use IP_ENCODED_AS_HOSTNAME with  automatic TLS

---

lib/trino-parquet/src/main/java/io/trino/parquet/predicate/TupleDomainParquetPredicate.java
lib/trino-parquet/src/test/java/io/trino/parquet/TestTupleDomainParquetPredicate.java

Fixes https://github.com/trinodb/trino/issues/9890

Fix handling of null pages in getDomain for column index

---

docs/src/main/sphinx/installation/jdbc.rst

As requested by @lukasz-walkiewicz .. not completely sure about wording..

Clarify token caching

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitSource.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveSplitSource.java

Fixes: https://github.com/trinodb/trino/issues/9917

Fix split accounting in HiveSplitSource when split is pruned

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveConnector.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveModule.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java

Remove unused system tables from Hive connector

Remove unused system tables from Hive connector

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java

Fixes https://github.com/trinodb/trino/issues/9937

Handle null statistics in Iceberg Dynamic Filtering

---

plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlClient.java
plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlConnectorTest.java
plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java

Disable predicates pushdown to REAL type in MySQL, MemSQL and ClickHouse

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergProjectionPushdownPlans.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java

https://github.com/trinodb/trino/actions/runs/1483281172

Fix iceberg build

---

core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java

Allow MockConnector to support system roles

Allow MockConnector to support system roles

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveConnectorTest.java

Extracted from https://github.com/trinodb/trino/pull/9820

Test partition scan limit for multi-column partitioning

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java

fixes https://github.com/trinodb/trino/issues/9264

Construct RLE block with proper types for Parquet with missing struct  fields

---

core/trino-main/src/main/java/io/trino/operator/DynamicFilterSourceOperator.java
core/trino-main/src/main/java/io/trino/operator/aggregation/TypedSet.java
core/trino-main/src/main/java/io/trino/operator/aggregation/multimapagg/MultimapAggregationFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/ArrayDistinctFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/ArrayExceptFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/ArrayUnionFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/MapConcatFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/MapFromEntriesFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/MapToMapCast.java
core/trino-main/src/main/java/io/trino/operator/scalar/MapTransformKeysFunction.java
core/trino-main/src/main/java/io/trino/operator/scalar/MultimapFromEntriesFunction.java

Improve TypedSet API

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveDistributedJoinQueries.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java
testing/trino-testing/src/main/java/io/trino/testing/BaseDynamicPartitionPruningTest.java

Based on https://github.com/trinodb/trino/pull/9897

Restore dynamic partition pruning assertions

---

core/trino-main/src/main/java/io/trino/sql/analyzer/Scope.java
core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/RelationPlanner.java
core/trino-main/src/test/java/io/trino/connector/MockConnectorEntities.java
core/trino-main/src/test/java/io/trino/sql/query/TestColumnMask.java
core/trino-main/src/test/java/io/trino/sql/query/TestRowFilter.java

Support insert into a table with row filter and hidden columns

Support insert into a table with row filter and hidden columns

---

lib/trino-orc/src/main/java/io/trino/orc/OrcWriter.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Fixes https://github.com/trinodb/trino/issues/9810

Fix file_size_in_bytes in Iceberg manifest for ORC

---

plugin/trino-elasticsearch/src/test/java/io/trino/plugin/elasticsearch/BaseElasticsearchConnectorTest.java
pom.xml

Two instances of `ReturnValueIgnored` caught.

Upgrade Error Prone to 2.10.0

---

core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
core/trino-main/src/test/java/io/trino/sql/query/TestRowFilter.java

Improve error message when inserting out of the row filter

Improve error message when inserting out of the row filter

---

client/trino-jdbc/src/test/java/io/trino/jdbc/TestJdbcExternalAuthentication.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverAuth.java
client/trino-jdbc/src/test/java/io/trino/jdbc/TestTrinoDriverImpersonateUser.java
core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java
lib/trino-orc/src/test/java/io/trino/orc/TestOrcWithoutRowGroupInfo.java
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/security/TestFileBasedAccessControl.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/credential/TestCredentialProvider.java
plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/BenchmarkGeometryAggregations.java
plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/BenchmarkGeometryToBingTiles.java
plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/BenchmarkSpatialJoin.java
plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestBingTileFunctions.java
plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/TestSphericalGeoFunctions.java
plugin/trino-geospatial/src/test/java/io/trino/plugin/geospatial/aggregation/TestGeometryConvexHullGeoAggregation.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPageSourceFactory.java
testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerBasic.java

`URL#getPath` does not do any validation. The proper way to get resource
file is `URL -> #toUri -> new File(URI) -> path`, because `new
File(URI)` does all the proper validation.

Access test resources with proper validation

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java

original files rows ids were not calculated correctly

Fix DELETE with no predicate on CTAS ACID table

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/cli/TestRun.java

Add option to start product tests in debug mode with suspend. This is useful when debugging single product test which start's and ends fast. It's easy to fail to attach after product test container is started and before test ends

Add option to start product tests in debug mode with suspend

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Support Iceberg UUIDs in ORC complex types

---

docs/src/main/sphinx/connector/mongodb.rst
plugin/trino-mongodb/pom.xml
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientConfig.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoClientModule.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoMetadata.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSession.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/MongoSplitManager.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/ObjectIdFunctions.java
plugin/trino-mongodb/src/main/java/io/trino/plugin/mongodb/WriteConcernType.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/BaseMongoDistributedQueries.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoQueryRunner.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/MongoServer.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoClientConfig.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoIntegrationSmokeTest.java
plugin/trino-mongodb/src/test/java/io/trino/plugin/mongodb/TestMongoPlugin.java

Fixes #3460 Fixes #8591 Fixes #5810 Fixes #1573

Add Support for Connection URI to MongoDB Connector

---

plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConnectorModule.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/StaticBigQueryCredentialsSupplier.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/StaticCredentialsConfig.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestStaticCredentialsConfig.java

This is preparatory step to introduce new authentication methods.

Extract static credentials config for BigQuery connector

---

core/trino-main/src/main/java/io/trino/execution/scheduler/TopologyAwareNodeSelectorFactory.java
core/trino-main/src/main/java/io/trino/execution/scheduler/UniformNodeSelectorFactory.java
core/trino-main/src/main/java/io/trino/metadata/InternalNode.java
core/trino-main/src/test/java/io/trino/execution/TestNodeScheduler.java

fixes #10017 
@dain, please review

fix decoding IP based hostname

---

docs/src/main/sphinx/connector/prometheus.rst
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusClient.java
plugin/trino-prometheus/src/main/java/io/trino/plugin/prometheus/PrometheusConnectorConfig.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/PrometheusQueryRunner.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/TestPrometheusConnectorConfig.java

This will close https://github.com/trinodb/trino/issues/10101
cc@rimolive
Signed-off-by: Anish Asthana <anishasthana1@gmail.com>

Allow users to specify timeouts when connecting to Prometheus

---

pom.xml

This is the latest release on the v1.x line.

Update Coral to 1.0.121

---

plugin/trino-session-property-managers/src/test/java/io/trino/plugin/session/TestSessionPropertyManagerInTransaction.java

`TestSessionPropertyManagerInTransaction` tests session properties with
Trino transactions. It doesn't need MinIO nor HMS.

Use lighter-weight query runner in test

---

core/trino-main/src/main/java/io/trino/operator/project/DictionaryAwarePageFilter.java

Reduce branching and populate positions array in single loop to reduce
dictionary block lookups

Improve performance of selectDictionaryPositions

---

core/trino-main/src/main/java/io/trino/connector/system/SystemTablesMetadata.java
core/trino-main/src/main/java/io/trino/connector/system/jdbc/ColumnJdbcTable.java
core/trino-spi/src/main/java/io/trino/spi/connector/Constraint.java

Remove deprecated Constraint.getColumns

---

core/trino-spi/src/main/java/io/trino/spi/predicate/NullableValue.java

Print value in a more human-readable form.

Improve NullableValue.toString

---

docs/src/main/sphinx/connector/memsql.rst
plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlClient.java
plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlConnectorTest.java

I couldn't find such limitation in MemSQL. Relates to 79e5ec8a3edf41d127a0221fd2c1b22dd859233c

Allow columns with ; in MemSQL

---

docs/src/main/sphinx/sql/select.rst

This PR addresses:
fixes #3812
fixes #8471
documentation  issues

Extend UNNEST documentation with usage examples

---

plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/StandardColumnMappings.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcClient.java
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-druid/src/main/java/io/trino/plugin/druid/DruidJdbcClient.java
plugin/trino-memsql/src/main/java/io/trino/plugin/memsql/MemSqlClient.java
plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlTypeMapping.java
plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java
plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java
plugin/trino-phoenix/src/main/java/io/trino/plugin/phoenix/PhoenixClient.java
plugin/trino-phoenix5/src/main/java/io/trino/plugin/phoenix5/PhoenixClient.java
plugin/trino-postgresql/src/main/java/io/trino/plugin/postgresql/PostgreSqlClient.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlTypeMapping.java
plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerTypeMapping.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestDistributedQueries.java

Fix incorrect date result due to julian to gregorian switch in some connectors

---

core/trino-main/src/main/java/io/trino/execution/executor/TaskExecutor.java
core/trino-main/src/test/java/io/trino/execution/executor/TestTaskExecutor.java

Start more than single split in TaskExecutor#scheduleTaskIfNecessary.
Previously only single split was started. This caused
that less than task.min-drivers-per-task splits were
running for situations when buffer was underutlized
and no more splits were scheduled by coordinator.

Improve sheduling of min drivers per task

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/BinaryColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/BooleanColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/DoubleColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/FloatColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/Int64TimestampMillisColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/Int64TimestampNanosColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/IntColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/LongColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/LongDecimalColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/PrimitiveColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/ShortDecimalColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/TimeMicrosColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/TimestampColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/TimestampMicrosColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/UuidColumnReader.java

Extract common code that was identical in all subclasses

Deduplicate code in Parquet Reader

---

.github/workflows/docs.yml

Fixes #10242
Tested in https://github.com/ebyhr/gha
I couldn't find the way to skip in workflow level, so introduced https://github.com/dorny/paths-filter.

Skip docs steps if there is change in other directory

---

docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-366.md

Closes https://github.com/trinodb/trino/issues/10181

Add 366 release notes

---

core/trino-main/src/main/java/io/trino/operator/aggregation/AccumulatorCompiler.java

Based on this [issue](https://github.com/trinodb/trino/issues/10314), it appears we are getting a null state object into this aggregation input method.  This should not be possible, so this PR adds a null check when initializing the fields in the generated AccumulatorState constructor.  Also the generate copy method was doing an unsafe initialization of the class, so the second commit replaces this with a copy constructor.

Fix unsafe generated copy method in aggregation state compiler

---

core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedStageExecution.java
plugin/trino-tpch/src/main/java/io/trino/plugin/tpch/TpchConnectorFactory.java
testing/trino-tests/src/test/java/io/trino/execution/TestEventListenerWithSplits.java
testing/trino-tests/src/test/java/io/trino/execution/TestPendingStageState.java
testing/trino-tests/src/test/java/io/trino/tests/TestJoinQueries.java
testing/trino-tests/src/test/java/io/trino/tests/tpch/TpchQueryRunnerBuilder.java

Fixes https://github.com/trinodb/trino/issues/10333

Fix broadcast join scheduling

---

testing/trino-testing-services/src/main/java/io/trino/jmh/Benchmarks.java

Sometimes in a process of performance optimization, it's useful to rerun just a selected method or group of methods.
It's not straightforward when using `Benchmarks` class because it always include all benchmark methods on a give class (`.include("^\\Q" + benchmarkClass.getName() + ".\\E")`).
This PR adds an option to benchmark only the given method but defaults to the previous behavior of including all benchmarks in the class.

Add option to benchmark only selected methods

---

core/trino-main/src/test/java/io/trino/sql/query/QueryAssertions.java
testing/trino-tests/src/test/java/io/trino/tests/BaseQueryAssertionsTest.java
testing/trino-tests/src/test/java/io/trino/tests/TestLocalQueryAssertions.java

Implements https://github.com/trinodb/trino/issues/10338#issuecomment-996556897

Report query for query assertion failures

---

core/trino-main/src/main/java/io/trino/operator/aggregation/minmaxby/AbstractMinMaxBy.java
testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java

Fix intermediate type declaration

---

testing/trino-testing/src/main/java/io/trino/testing/TestingConnectorBehavior.java

Extracted from https://github.com/trinodb/trino/pull/10355

Add SUPPORTS_UPDATE testing connector behavior

---

docs/src/main/sphinx/connector/clickhouse.rst
docs/src/main/sphinx/connector/druid.rst
docs/src/main/sphinx/connector/jdbc-procedures.fragment
docs/src/main/sphinx/connector/memsql.rst
docs/src/main/sphinx/connector/mysql.rst
docs/src/main/sphinx/connector/oracle.rst
docs/src/main/sphinx/connector/phoenix.rst
docs/src/main/sphinx/connector/postgresql.rst
docs/src/main/sphinx/connector/redshift.rst
docs/src/main/sphinx/connector/sqlserver.rst
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/JdbcModule.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/CachingIdentifierMapping.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/IdentifierMappingModule.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/procedure/FlushJdbcMetadataCacheProcedure.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcCachingConnectorSmokeTest.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestJdbcTableProperties.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcClient.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcModule.java

Extracted from https://github.com/trinodb/trino/pull/10251 for clearance.

Add jdbc metadata cache flush procedure

---

docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-367.md

Closes https://github.com/trinodb/trino/issues/10301

Add 367 release notes

---

plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/TestThriftConnectorTest.java

Introduced in b77916fea29367c5b8da5bf3ab73594c1ea7b009 due to stale PR.

Fix compilation error in TestThriftConnectorTest

---

core/trino-main/src/main/java/io/trino/execution/scheduler/SqlQueryScheduler.java
testing/trino-tests/src/test/java/io/trino/execution/TestRefreshMaterializedView.java

Fixes https://github.com/trinodb/trino/issues/10359.

Fix coordinator-only query state transition

---

pom.xml

Bump mssql-jdbc driver version 

---

plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlTypeMapping.java

Migrate DataTypeTest to SqlDataTypeTest in MySQL

---

.github/workflows/docs.yml

Specify MAVEN_INSTALL_OPTS in docs-checks job

---

plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlTypeMapping.java

Some complex types (e.g. hstore and array) will be handled in another PR.

Migrate simple DataTypeTest to SqlDataTypeTest in PostgreSQL

---

plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixTypeMapping.java

I will send another PR for Phoenix 5 module after merging this PR.

Add test cases to Phoenix type mapping

---

plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixTypeMapping.java

Add test cases to Phoenix5 type mapping

---

plugin/trino-elasticsearch/pom.xml
pom.xml

Update to airlift 213

---

docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-368.md

* fixes https://github.com/trinodb/trino/issues/10389
* I will try to update daily with new commits and any info I get from maintainers and contributors
* communication occurs on #release in trino slack
Format: commit, committer/maintainer, PR/issue number [x] RN, [x] docs
[x] RN - release note added and verified, or assessed to be not necessary, set to [ ] RN before completion 
[x] docs - need for docs assessed and merge, or assessed to be not necessary, , set to [ ] docs before completion 
* https://github.com/trinodb/trino/commit/06e7b9e29facf9874f8904ebf29314e9ce5c0949 , @martint, #10051, [x] RN, [x] docs
* https://github.com/trinodb/trino/commit/fb88c0bf589db55d77223fc31aab29acbb2d0698, @martint, #10051, [x] RN, [x] docs
* https://github.com/trinodb/trino/commit/48581bdce9cbdef0deec86 …

Add Trino 368 release notes

---

lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/metrics/DurationTiming.java
lib/trino-plugin-toolkit/src/test/java/io/trino/plugin/base/metrics/TestMetrics.java

This improves serialization and formatting of DurationTiming

Display duration in most succinct time unit

---

testing/trino-tests/src/test/java/io/trino/memory/TestMemoryManager.java

It might take a while for one query to be moved
to reserved pool after it becomes blocked
Fixes: https://github.com/trinodb/trino/issues/10573

Fix flaky testClusterPools

---

docs/src/main/sphinx/connector/clickhouse.rst

Fixes #7099
* https://clickhouse.com/docs/en/sql-reference/data-types/
* https://github.com/trinodb/trino/blob/master/plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java#L359-L452

Document ClickHouse connector type mapping

---

plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorSmokeTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/ClickHouseQueryRunner.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorSmokeTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseLatestConnectorSmokeTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestingClickHouseServer.java

https://hub.docker.com/r/yandex/clickhouse-server/tags

Add smoke tests for ClickHouse with 20.8 and 21.11.10.1

---

docs/src/main/sphinx/connector/clickhouse.rst
plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseTypeMapping.java

Map ClickHouse IPv4 and IPv6 types to Trino IPADDRESS type

---

pom.xml

Enable Error Prone check: DoubleBraceInitialization

---

.github/config/labeler-config.yml

Supersedes https://github.com/trinodb/trino/pull/9121

Label PRs changing docs as such

---

pom.xml

Update testcontainers to 1.16.3

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java

This reverts commit 73837347a4666476f26dbdc62f55386360902bbf.
Unblock https://github.com/trinodb/trino/issues/10710 when we actively look into it

Revert "Pipeline buffering and upload in S3 multi-upload"

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/IdentifierMappingRules.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/RuleBasedIdentifierMapping.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/SchemaMappingRule.java
plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/mapping/TableMappingRule.java
plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/mapping/TestForwardingIdentifierMapping.java

Simple fix of wrong license headers.

Fix of licenses headers

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitManager.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergSplitSource.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java

Fixes: https://github.com/trinodb/trino/issues/10770

Fix error in Iceberg partition evolution handling

---

plugin/trino-base-jdbc/src/main/java/io/trino/plugin/jdbc/DefaultJdbcMetadata.java

The upstream issue: https://github.com/trinodb/trino/issues/9021 cannot be reproduced, see the issue for details

Remove dangling TODO that links to a resolved issue

---

docs/src/main/sphinx/release/release-366.md

Relates to: https://github.com/trinodb/trino/pull/9723, https://github.com/trinodb/trino/pull/10183.

Supplement 366 release notes

---

plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixConnectorTest.java
plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java

Enable testDataMappingSmokeTest in Phoenix 4 & 5

---

.mvn/jvm.config
pom.xml

This allows it to benefit from Maven Daemon.

Run Error Prone without forking compiler

---

plugin/trino-base-jdbc/src/test/java/io/trino/plugin/jdbc/TestingH2JdbcClient.java

Fix
`io.trino.plugin.jdbc.TestCachingJdbcClient#testConcurrentSchemaCreateAndDrop`
flakiness.
Fixes https://github.com/trinodb/trino/issues/10933

Fix testConcurrentSchemaCreateAndDrop flakiness

---

core/trino-main/src/main/java/io/trino/metadata/Metadata.java
core/trino-main/src/main/java/io/trino/metadata/MetadataListing.java
core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java

Simple refactoring of the list columns api to remove unnecessary column name in the result.
Is this change a fix, improvement, new feature, refactoring, or other?
improvement
Is this a change to the core query engine, a connector, client library, or the
SPI interfaces (be specific)?
core query engine

Simplify Metadata listTableColumns api

---

core/trino-main/src/main/java/io/trino/Session.java
core/trino-main/src/main/java/io/trino/SessionRepresentation.java
core/trino-main/src/main/java/io/trino/event/QueryMonitor.java
core/trino-main/src/main/java/io/trino/metadata/SessionPropertyManager.java
core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
core/trino-main/src/test/java/io/trino/TestSession.java
core/trino-main/src/test/java/io/trino/execution/TestQueryStateMachine.java
core/trino-main/src/test/java/io/trino/server/TestSessionPropertyDefaults.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestingTrinoClient.java
testing/trino-testing/src/main/java/io/trino/testing/TestingSessionContext.java
testing/trino-tests/src/test/java/io/trino/tests/AbstractTestEngineOnlyQueries.java

Index session catalog roles and properties using name instead of id.
Is this change a fix, improvement, new feature, refactoring, or other?
improvement
Is this a change to the core query engine, a connector, client library, or the
SPI interfaces (be specific)?
core query engine
How would you describe this change to a non-technical end user or system
administrator?
N/A

Index session catalog roles and properties using name instead of id

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

For https://github.com/trinodb/trino/issues/10976

Mark Iceberg testSelectInformationSchemaColumns as @Flaky

---

plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
plugin/trino-druid/src/test/java/io/trino/plugin/druid/BaseDruidConnectorTest.java
plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlConnectorTest.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
plugin/trino-sqlserver/src/main/java/io/trino/plugin/sqlserver/SqlServerClient.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/TestingConnectorBehavior.java

Fix incorrect negative date predicates in SQL Server

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSink.java

The `target_max_file_size` Hive session property has non-null default
value, so can never be null. The default can be configured via catalog
config, which doesn't allow unsetting the value.

Remove redundant use of Optional for target_max_file_size

---

core/trino-main/src/main/java/io/trino/sql/planner/plan/TableDeleteNode.java

```
* Fix some things. ({issue}`5678`)
```

Stop ignoring children in TableDeleteNode.replaceChildren

---

core/trino-main/src/main/java/io/trino/execution/buffer/SpoolingExchangeOutputBuffer.java

N\A
N\A
N\A
No documentation is needed.
No release notes entries required.

Add comment on SpoolingExchangeOutputBuffer thread safety

---

plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/BaseClickHouseConnectorSmokeTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java

Support showing table properties in ClickHouse.
Fix
ClickHouse
Support showing table properties.
() Sufficient documentation is included in this PR.
```
* Support showing table properties. ({issue}`11027`)
```

Expose table properties in ClickHouse

---

core/docker/container-test.sh

```
* Fix some things. ({issue}`5678`)
```

Delay removal of containers during Docker image tests

---

plugin/trino-accumulo/src/test/java/io/trino/plugin/accumulo/TestAccumuloConnectorTest.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestClickHouseConnectorTest.java
plugin/trino-druid/src/test/java/io/trino/plugin/druid/BaseDruidConnectorTest.java
plugin/trino-memsql/src/test/java/io/trino/plugin/memsql/TestMemSqlConnectorTest.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/BaseMySqlConnectorTest.java
plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Improve negative date tests
Fixes to tests
* Follow up of #10263

Improve negative date tests

---

.github/pull_request_template.md

Syntax highlight release notes in pull request template

---

plugin/trino-resource-group-managers/src/main/java/io/trino/plugin/resourcegroups/db/DbResourceGroupConfigurationManagerFactory.java

Is this change a fix, improvement, new feature, refactoring, or other?
A fix to the database resource group manager.
Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)
Update to the database resource group manager to enable the use of secrets in the configuration file.
How would you describe this change to a non-technical end user or system administrator?
Fixes #10286
```
* Fix some things. ({issue}`5678`)
```

Enable secrets in db resource group manager

---

.github/pull_request_template.md

Minor cleanups to PR template to reduce clutter and avoid placeholder issue numbers.
Improvement.
It's a change to pull request template.
Make it cleaner and less likely for stale issue numbers to appear in release notes.
( ) Release notes entries required with the following …

Minor cleanups to PR template

---

docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-371.md

* fixes #10941
* follow up to #10793
Format: commit, committer/maintainer, PR/issue number, ✅ / ❌  RN, ✅ / ❌   docs
✅  RN - release note added and verified, or assessed to be not necessary, set to ❌ RN before completion
✅  docs - need for docs assessed and merge, or assessed to be not necessary, set to ❌ docs before completion
* https://github.com/trinodb/trino/commit/43818a74cc04e3a2fa8740d82461679c41ab51dd, @electrum , #10911 , ✅  RN, ✅  docs
* https://github.com/trinodb/trino/commit/fb59c1032ef05c82a22601de3d83f60a255025ac, @dain  , #10816 , ✅ RN, ✅  docs
* https://github.com/trinodb/trino/commit/8df789cbb4eeaa1f6606e1e3aabbdcd5c5122597, @electrum  , #10913 , ✅ RN, ✅ docs
* https://github.com/trinodb/trino/commit/7d11ac142755c6d06fc96a97cc879186a56fd16d, @martint  , #10406 , ✅  RN, ✅ …

Add Trino 371 release notes

---

docs/src/main/sphinx/functions/list-by-topic.rst
docs/src/main/sphinx/functions/list.rst

Is this change a fix, improvement, new feature, refactoring, or other?
Is this a change to the core query engine, a connector, client library, or the SPI interfaces? (be specific)
How would you describe this change to a non-technical end user or system administrator?
```
* Fix some things. ({issue}`5678`)
```

#7656 Link format_datetime function in list.rst to actual docs

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/AbstractMetastoreTableOperations.java

relates to https://github.com/trinodb/trino/pull/11062#issuecomment-1047524365 cc @lzeiming

Document why Iceberg table needs to be external in metastore

---

docs/src/main/sphinx/sql/set-session.rst

Improvement 
Documentation only
Change wording in catalog session properties section
```markdown
```

Change wording in catalog session properties section

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/CachingDirectoryLister.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBackgroundHiveSplitLoader.java

Fix CachingDirectoryLister when constructed with 0 cache TTL

---

plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClient.java

Simplify MySqlClient.toColumnMapping

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java

Code cleanup
n/a
n/a
n/a
```markdown
```

Remove unnecessary block

---

plugin/trino-google-sheets/pom.xml
plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/SheetsQueryRunner.java
plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestGoogleSheets.java
plugin/trino-google-sheets/src/test/java/io/trino/plugin/google/sheets/TestSheetsPlugin.java

Extract query runner in Google Sheets connector

Extract query runner in Google Sheets connector

---

core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java

Remove unused import

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergRedirectionToHive.java

Remove extra blank line

---

plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestPostgreSqlTypeMapping.java

This migrates most tests except:
- Tests of arrays containing null values - it's affected by https://github.com/trinodb/trino/issues/11397. The tests need to reimplemented some other way to avoid `verifyPredicate` from SqlDataTypeTest.
- Tests of datetime types - these will be done in separate PR

Migrate most PostgreSQL type mapping tests to SqlDataTypeTest

---

plugin/trino-phoenix/src/test/java/io/trino/plugin/phoenix/TestPhoenixTypeMapping.java
plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixTypeMapping.java

This commit includes:
- Add separate tests for Phoenix tinyint/smallint/integer/bigint
- Add min/max/min-1/max+1 test cases
- Cover more tests using trinoCreateAndInsert in TestPhoenixTypeMapping
- Reuse trinoCreateAndInsert in TestPhoenixTypeMapping
Improvement.
Phoenix type mapping tests.
N/A.
Related #11181
(x) …

Improve Phoenix type mapping tests

---

docs/src/main/sphinx/connector/hive.rst

Add an introduction to the Procedure section in the Hive connector. Include information about call a procedure and an example.
> Is this change a fix, improvement, new feature, refactoring, or other? Improvement
> Is this a change to the core query engine, a connector, client library, or the SPI interfaces? Hive connector

Add intro to Procedure in the Hive connector

---

pom.xml

Update AWS SDK Client to recent version.
Upgrading the version of a dependent library fits in "other" category. 
It would affect certain connectors like Hive, Iceberg, Elasticsearch and Kinesis
Dependency update
( ) Release notes entries required with the following suggested …

Bump AWS SDK version to 1.12.172

---

plugin/trino-bigquery/pom.xml

Run BigQuery instance cleaner test against case insensitive project

Run BigQuery instance cleaner test against case insensitive project

---

.mvn/wrapper/maven-wrapper.properties

Release notes: https://maven.apache.org/docs/3.8.5/release-notes.html
Housekeeping.
Tooling.
Magic :)
```markdown
```

Update maven to 3.8.5

---

testing/trino-testing/src/main/java/io/trino/testing/AbstractTestQueryFramework.java

Log query state when memory pool leaks detected in tests

---

docs/src/main/sphinx/connector/kudu.rst

Change a fix
Document
Fix style in Kudu documentation
* Fixes #11380

Fix style in Kudu documentation

---

plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClient.java
plugin/trino-singlestore/src/main/java/io/trino/plugin/singlestore/SingleStoreClientModule.java
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreConnectorTest.java
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestSingleStoreTypeMapping.java
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestingSingleStoreServer.java

Rename MemSQL to SingleStore

---

core/trino-main/src/main/java/io/trino/sql/planner/PlanOptimizers.java

costCalculatorWithEstimatedExchanges should be used before AddExchanges
costCalculatorWithoutEstimatedExchanges should be used after AddExchanges

Prevent usage of wrong cost calculator before/after AddExchanges

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/hms/TrinoHiveCatalog.java

Extracted from https://github.com/trinodb/trino/pull/11356, no review needed.

Check also for materialized views before dropping Iceberg namespace

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeMinioConnectorTest.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduWithDisabledInferSchemaConnectorTest.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduWithEmptyInferSchemaConnectorTest.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/AbstractKuduWithStandardInferSchemaConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Ensure that DROP SCHEMA fails as expected when the schema to drop  contains either table, view or materialized view.
Test
Related PR: #11612

Add drop non empty schema tests

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/AbstractTestDeltaLakeCreateTableStatistics.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeCreateTableStatistics.java

improvement
a connector test
it is not important for anyone apart from engineers
```markdown
```

Replace declared IOException with Exception in DeltaLake tests

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViews.java

The test data is stored in `TestingTrinoServer`'s data dir and is
removed anyway.

Remove redundant test cleanup

---

docs/src/main/sphinx/connector/elasticsearch.rst
docs/src/main/sphinx/connector/prometheus.rst
docs/src/main/sphinx/language/types.rst

Improvement.
Changes were made in the documentation only.
Replace "for instance" with "for example" where appropriate.
```markdown
```

Replace for instance with for example

---

docs/src/main/sphinx/connector/delta-lake.rst
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeTableProperties.java

Fix description for Delta Lake location property

---

docs/src/main/sphinx/release/release-375.md

The feature name is fault-tolerant execution .. this needs to be also used in the release notes.. 
fix
documentation only
Spelling fix in the release notes
none

Fix typo to use fault-tolerant

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java

For optimal optimize result it is reasonable to create a checkpoint.

Force checkpoint in Delta's OPTIMIZE

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java

Populate TPCH tables in Delta Lake query runner

Populate TPCH tables in Delta Lake query runner

---

docs/src/main/sphinx/admin/graceful-shutdown.rst
docs/src/main/sphinx/installation/jdbc.rst
docs/src/main/sphinx/security/certificate.rst
docs/src/main/sphinx/security/cli.rst
docs/src/main/sphinx/security/kerberos.rst
docs/src/main/sphinx/security/ldap.rst
docs/src/main/sphinx/security/overview.rst
docs/src/main/sphinx/security/tls.rst

Improvement.
Changes made to documentation.
Put TLS before HTTPS in documentation for consistency across documentation,
```markdown
```

Put TLS before HTTPS

---

core/trino-main/src/main/java/io/trino/metadata/Metadata.java
core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
core/trino-main/src/main/java/io/trino/metadata/TableExecuteHandle.java
core/trino-main/src/main/java/io/trino/operator/SimpleTableExecuteOperator.java
core/trino-main/src/main/java/io/trino/sql/analyzer/Analysis.java
core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmenter.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddLocalExchanges.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PropertyDerivations.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/StreamPropertyDerivations.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/UnaliasSymbolReferences.java
core/trino-main/src/main/java/io/trino/sql/planner/plan/PlanNode.java
core/trino-main/src/main/java/io/trino/sql/planner/plan/PlanVisitor.java
core/trino-main/src/main/java/io/trino/sql/planner/plan/SimpleTableExecuteNode.java
core/trino-main/src/main/java/io/trino/sql/planner/planprinter/PlanPrinter.java
core/trino-main/src/main/java/io/trino/sql/planner/sanity/ValidateDependenciesChecker.java
core/trino-main/src/test/java/io/trino/metadata/AbstractMockMetadata.java
core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorMetadata.java
core/trino-spi/src/main/java/io/trino/spi/connector/TableProcedureExecutionMode.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorMetadata.java

Implement skeleton for coordinator-only execute

---

docs/src/main/sphinx/admin/resource-groups.rst
docs/src/main/sphinx/admin/session-property-managers.rst
docs/src/main/sphinx/functions/array.rst
docs/src/main/sphinx/release/release-0.197.rst

Improvement.
Hyphenate spelling of subgroup
```markdown
```

Hyphenate spelling of subgroup

---

service/trino-verifier/README.md
service/trino-verifier/src/main/java/io/trino/verifier/QueryPairMapper.java
service/trino-verifier/src/main/java/io/trino/verifier/Validator.java
service/trino-verifier/src/main/java/io/trino/verifier/VerifierDao.java
service/trino-verifier/src/main/java/io/trino/verifier/VerifierQueryEventDao.java

Support setting distinct session properties for test and control queries in verifier
Improvement
Verifier
Allow setting different session properties for test and control runs in verifier
`-`
```markdown
* Fix …
```

Support distinct session properties in verifier

---

core/trino-main/src/main/java/io/trino/server/TrinoSystemRequirements.java

( X) No documentation is needed.
(X ) No release notes entries required.

reasonable time check year update

---

core/trino-main/src/main/java/io/trino/memory/MemoryPool.java

Remove unused methods

---

docs/src/main/sphinx/connector/delta-lake.rst

improvement
Delta Lake connector docs
Minor improvement of documentation for Delta Lake connector
Fixes #11830

Add link to dynamic filtering docs in Delta Lake connector

---

core/trino-main/src/main/java/io/trino/server/ui/WorkerResource.java
core/trino-main/src/main/resources/webapp/src/components/ClusterHUD.jsx
core/trino-main/src/main/resources/webapp/src/components/WorkerList.jsx
core/trino-main/src/main/resources/webapp/src/webpack.config.js
core/trino-main/src/main/resources/webapp/src/workers.jsx
core/trino-main/src/main/resources/webapp/workers.html

The fact that you can't see a list of workers in the Web UI doesn't seem elegant. The goal of this PR is to improve it. The effect is shown in the figure below:
The value of active workers **became a hyperlink.**
When you click it, you will enter a new page with the contents as you run `select * from system.runtime.nodes;` the results obtained.
At the same time, each node ID and node IP supports jumping to the corresponding machine to view information.
This is the effect of having multiple nodes in a formal cluster:
Improvement.
No.
> How would you describe this change to a non-technical end user or system …

Add system.runtime.nodes information to web UI

---

core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java
core/trino-main/src/main/java/io/trino/memory/MemoryManagerConfig.java
core/trino-main/src/test/java/io/trino/execution/TestQueryManagerConfig.java
core/trino-main/src/test/java/io/trino/execution/scheduler/TestExponentialGrowthPartitionMemoryEstimator.java
core/trino-main/src/test/java/io/trino/memory/TestMemoryManagerConfig.java
docs/src/main/sphinx/admin/fault-tolerant-execution.rst

Update default values for some task-level retries related config properties

---

docs/src/main/sphinx/release/release-376.md

fix
No. The doc.
fix wrong placement which should in iceberg entry
fix #11890
(X) Documentation issue #issuenumber is filed, and can be handled later.
(X) Release notes entries required with the following suggested text:
```markdown
* Fix Iceberg entry in release note 376. ({issue}`11890`)
```

Fix Iceberg entry in release note 376

---

core/trino-main/src/main/java/io/trino/operator/aggregation/arrayagg/GroupArrayAggregationState.java
core/trino-main/src/main/java/io/trino/operator/aggregation/listagg/GroupListaggAggregationState.java
core/trino-main/src/main/java/io/trino/operator/aggregation/multimapagg/GroupedMultimapAggregationState.java
core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/planner/EffectivePredicateExtractor.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/StatsRecordingPlanOptimizer.java
core/trino-main/src/main/java/io/trino/util/LongBigArrayFIFOQueue.java
core/trino-main/src/test/java/io/trino/spiller/TestBinaryFileSpiller.java
core/trino-spi/src/main/java/io/trino/spi/QueryId.java
lib/trino-orc/src/main/java/io/trino/orc/OrcBlockFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/parquet/ParquetPageSource.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/rcfile/RcFilePageSource.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/metadata/TestShardCleaner.java

Minor cleanups

---

lib/trino-orc/src/test/java/io/trino/orc/TestSliceDictionaryColumnWriter.java

Fixes https://github.com/trinodb/trino/issues/11847

Generate only valid codepoints in TestSliceDictionaryColumnWriter.testDirectConversion

---

docs/src/main/sphinx/connector/mongodb.rst

The MongoDB connector requires write access to the schema information collection, but this requirement currently isn't documented. Added to the requirements and connection string sections.
Improvement
Documentation
Adds missing information needed to set up a MongoDB catalog
( ) …

Document MongoDB connector write access requirement

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeAdlsConnectorSmokeTest.java

Enable `TestDeltaLakeAdlsConnectorSmokeTest`
Relates to #11325

Enable TestDeltaLakeAdlsConnectorSmokeTest

---

plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java

Increase startup attempts to 3 in `TestingPostgreSqlServer`
Relates to https://github.com/trinodb/trino/runs/5999064610

Increase startup attempts to 3 in TestingPostgreSqlServer

---

docs/src/main/sphinx/sql/create-materialized-view.rst

It's not clear from the examples given for CREATE MATERIALIZED VIEW ... WITH that their syntax is for an Iceberg catalog. Added a quick note to that effect.
Improvement
Documentation
Clarify what catalogs you can use the examples for.
( ) Release notes entries required with the …

Clarify that the CREATE MV WITH example is for Iceberg

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveSparkCompatibility.java

Support reading non-ISO date partition names in Hive
```markdown
* Fix failure when `date` type partition value has time unit with zero. ({issue}`11873`)
```

Support reading non-ISO date partition names in Hive

---

docs/src/main/sphinx/connector/iceberg.rst

Remove superseeded content about metadata tables

---

docs/src/main/sphinx/functions.rst
docs/src/main/sphinx/sql/show-functions.rst

There are additional arguments available for functions beyond what is in the documentation. Rather than a large project to include all alternate arguments and behaviors for all functions, add a hint on the functions.rst page to use SHOW FUNCTIONS.
Documentation improvement.
No.
This is a simple doc change.
(x) No …

Add suggestion to use SHOW FUNCTION on functions toc page

---

docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-377.md

Assemble the release notes for the upcoming Trino 377 release.
Improvement.
Add the release notes for Trino 377 with sections for general, security, connectors and other topics as included in the release. 
* Fixes #11863
(✅ ) Sufficient documentation is included in this PR.
(✅ ) No release notes entries required.
( ) Release notes entries required …

Add Trino 377 release notes

---

core/trino-main/src/main/java/io/trino/server/ServerMainModule.java

Properly export spiller stats

---

core/trino-main/src/main/java/io/trino/cost/ScalarStatsCalculator.java
core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java
core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
core/trino-main/src/main/java/io/trino/sql/planner/LiteralInterpreter.java

Follow up of https://github.com/trinodb/trino/pull/11918

Pass explicit node type to LiteralInterpreter

---

plugin/trino-pinot/pom.xml
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/PinotSplitManager.java
plugin/trino-pinot/src/main/java/io/trino/plugin/pinot/client/PinotClient.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/AbstractPinotIntegrationSmokeTest.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java
plugin/trino-pinot/src/test/resources/hybrid_offlineSpec.json
plugin/trino-pinot/src/test/resources/hybrid_realtimeSpec.json
plugin/trino-pinot/src/test/resources/hybrid_schema.json
plugin/trino-pinot/src/test/resources/realtimeSpec.json
plugin/trino-pinot/src/test/resources/schema.json

Fix time boundary handling on hybrid Pinot tables.
Fixes https://github.com/trinodb/trino/issues/10125

Fix time boundary handling in Pinot

---

plugin/trino-exchange/src/main/java/io/trino/plugin/exchange/s3/ExchangeS3Config.java
plugin/trino-exchange/src/test/java/io/trino/plugin/exchange/s3/TestExchangeS3Config.java

Improvement.
trino-exchange
To be consistent with https://github.com/trinodb/trino/blob/39aa8bc31a1feb2f09cc4303145093c14aa85f17/plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/HiveS3Config.java#L59 …

Default exchange s3MaxErrorRetries to 10

---

core/trino-main/src/main/java/io/trino/dispatcher/QueuedStatementResource.java

Prevent the internal communications token from being used to start a query.  This is a completely internal change and has no impact on end users.  Also, this is just an extra safety precaution.
(X) No documentation is needed.
(X) No release notes entries required.

Prevent internal communications from starting queries

---

core/trino-parser/src/main/antlr4/io/trino/sql/parser/SqlBase.g4

Fix indentation.
N/A.
N/A.
```markdown
```

Fix indentation in SqlBase.g4

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSourceProvider.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/file/DeltaLakeFileMetastoreModule.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/glue/DeltaLakeGlueMetastoreTableFilterProvider.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/metastore/thrift/DeltaLakeThriftMetastoreModule.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointBuilder.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriter.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/checkpoint/CheckpointWriterManager.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/S3TransactionLogSynchronizer.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/AccessTrackingFileSystem.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/transactionlog/TestTableSnapshot.java
testing/trino-testing-containers/src/main/java/io/trino/testing/containers/wait/strategy/SelectedPortWaitStrategy.java

Add links to github issues to TODOs in code

---

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaTaskFailureRecoveryTest.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveTaskFailureRecoveryTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergTaskFailureRecoveryTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseFailureRecoveryTest.java
testing/trino-testing/src/main/java/io/trino/testing/FaultTolerantExecutionConnectorTestHelper.java

This will make it easier to re-enable once this functionality is supported
Fix
Core
`N/A`
`-`
```markdown
```

Disable dynamic filtering for task level retries

---

docs/src/main/sphinx/installation/cli.rst

Improvement.
Add Windows instructions for running the Trino CLI.
```markdown
```

Add Windows instructions for running Trino CLI

---

docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-377.md
docs/src/main/sphinx/release/release-378.md

Assemble the release notes for the upcoming Trino 378 release.
Improvement.
Add the release notes for Trino 378 with sections for general, security, connectors and other topics as included in the release. 
* Fixes https://github.com/trinodb/trino/issues/11947
(✅ ) Sufficient documentation is included in this PR.
(✅ ) No release notes entries …

Add Trino 378 release notes

---

core/trino-main/src/main/java/io/trino/sql/planner/ConnectorExpressionTranslator.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushAggregationIntoTableScan.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/PushProjectionIntoTableScan.java
core/trino-main/src/test/java/io/trino/sql/planner/TestConnectorExpressionTranslator.java

Extracted from https://github.com/trinodb/trino/pull/12085

Small code cleanup

---

plugin/trino-oracle/src/main/java/io/trino/plugin/oracle/OracleClient.java
plugin/trino-oracle/src/test/java/io/trino/plugin/oracle/BaseOracleConnectorTest.java

Extracted from https://github.com/trinodb/trino/pull/11636

Support LIMIT pushdown in Oracle connector

---

docs/src/main/sphinx/security/user-mapping.rst

Improvement. 
Change to documentation only.
Add configuration instruction.
```markdown
```

Add user mapping configuration instruction

---

plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisConnectorConfig.java

Move Redis config comment to description

Move Redis config comment to description

---

docs/src/main/sphinx/installation/cli.rst

Add a new `Batch mode` section to the CLI docs to describe all the remaining options. Also, add the new `--no-progress` variant in the interactive-mode options table.
This is a follow-up to #11894
This is how it looks like:
I intentionally made the existing `Output formats` section a subsection of `Batch mode`:
docs
docs
n/a
( ) Documentation issue #issuenumber is filed, and can be …

Document CLI batch mode

---

plugin/trino-mariadb/src/main/java/io/trino/plugin/mariadb/MariaDbClient.java
plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/BaseMariaDbConnectorTest.java

Support table comments in MariaDB

Support table comments in MariaDB

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/InternalDeltaLakeConnectorFactory.java

Fix or improvement depending on how you look at it.
delta lake connector
allows using the delta lake connector on GCS
```markdown
* Adds support for delta connector on GCS. ({issue}`issuenumber`)
```
Should I …

Add support for delta lake connector on GCS

---

docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-379.md

Assemble the release notes for the upcoming Trino 378 release.
Improvement.
Add the release notes for Trino 378 with sections for general, security, connectors and other topics as included in the release. 
* Fixes #12088
() No documentation is needed.
(✅) Sufficient documentation is included in this PR.
(✅) No release notes entries required.
( ) Release notes entries required …

Add Trino 379 release notes

---

core/trino-main/src/main/java/io/trino/sql/planner/Partitioning.java
core/trino-main/src/main/java/io/trino/sql/planner/PlanFragmenter.java
core/trino-main/src/main/java/io/trino/util/JsonUtil.java
core/trino-main/src/test/java/io/trino/cost/StatsCalculatorAssertion.java
core/trino-main/src/test/java/io/trino/cost/TestExchangeStatsRule.java
core/trino-main/src/test/java/io/trino/execution/TestCreateTableTask.java
core/trino-main/src/test/java/io/trino/sql/planner/assertions/AggregationMatcher.java
core/trino-main/src/test/java/io/trino/sql/planner/assertions/GroupIdMatcher.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPruneExchangeColumns.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestPushProjectionThroughExchange.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java
core/trino-main/src/test/java/io/trino/sql/planner/sanity/TestValidateAggregationsWithDefaultValues.java
core/trino-spi/src/main/java/io/trino/spi/connector/BasicRelationStatistics.java
lib/trino-collect/src/test/java/io/trino/collect/cache/TestEvictableCache.java
lib/trino-collect/src/test/java/io/trino/collect/cache/TestEvictableLoadingCache.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnIndexBuilder.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnIndexFilter.java
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/AbstractTestHive.java

Fix some spelling problems

---

docs/src/main/sphinx/connector/hive.rst

Add documentation for new property for Hive views.
Fix
Docs
Add missing documentation for new property for Hive views.
* Add missing docs for #12221
(✅ ) Sufficient documentation is included in this PR.
(✅ ) No release notes entries required.

Document hive.hive-views.run-as-invoker

---

docs/release-template.md

Add a markdown template file to be able to use it as skeleton for release notes creation by anyone taking on release notes task. Located outside the source tree of sphinx since build otherwise breaks.
Improvement for process only. 
Documentation helper
A template to help in creating new release notes and keep them consistent.
na
(✅ ) No documentation is needed.
( ) Documentation issue #issuenumber is filed, and can be …

Add template for release notes

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java

Change schema prefix in Iceberg Glue smoke test

Change schema prefix in Iceberg Glue smoke test

---

docs/src/main/sphinx/functions/aggregate.rst

Fixes https://github.com/trinodb/trino/issues/12276

Fix documentation of approx_percentile functions

---

plugin/trino-redis/src/test/java/io/trino/plugin/redis/BaseRedisConnectorTest.java
plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestRedisConnectorTest.java
plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestRedisLatestConnectorTest.java
plugin/trino-redis/src/test/java/io/trino/plugin/redis/util/RedisServer.java

Add Redis connector test with latest version

Add Redis connector test with latest version

---

plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisJedisManager.java
plugin/trino-redis/src/test/java/io/trino/plugin/redis/RedisQueryRunner.java
plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestRedisConnectorTest.java
plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestRedisDistributedHash.java
plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestRedisLatestConnectorTest.java
plugin/trino-redis/src/test/java/io/trino/plugin/redis/TestingRedisPlugin.java

Minor improvement to Redis

---

docs/src/main/sphinx/connector/iceberg.rst

Docs for Iceberg `UPDATE` support
Related code change: https://github.com/trinodb/trino/pull/12026

Add UPDATE to list of supported Iceberg commands

---

plugin/trino-password-authenticators/src/test/java/io/trino/plugin/password/ldap/TestingOpenLdapServer.java

Refactoring
For LDAP password authenticator testing code
It doesn't affect the non-technical end user or system administrator. 
```markdown
```

Minor cleanup in TestingOpenLdapServer

---

docs/src/main/sphinx/installation/cli.rst

Cleanup on https://github.com/trinodb/trino/pull/11671 to make sure docs are consistent & clean.
Improvement
Docs
* Relates to #11671 
```markdown
```

Clarify auto-suggestion documentation

---

plugin/trino-mysql/src/main/java/io/trino/plugin/mysql/MySqlClientModule.java

Extracted from https://github.com/trinodb/trino/pull/12400.
1 mln rows from 6 min to 9 s :)

Improve MySQL INSERT performance

---

docs/src/main/sphinx/release/release-379.md

Code change was made as a part of: https://github.com/trinodb/trino/pull/11886

Add missing Iceberg release note to 379

---

core/trino-main/src/main/java/io/trino/exchange/ExchangeManagerRegistry.java

Remove noisy exchange manager logging

---

plugin/trino-kafka/src/main/java/io/trino/plugin/kafka/schema/file/FileTableDescriptionSupplier.java
plugin/trino-redis/src/main/java/io/trino/plugin/redis/RedisTableDescriptionSupplier.java

Optimize log message in Redis and Kafka.

Optimize log message in Redis and Kafka

---

docs/src/main/sphinx/installation/jdbc.rst

Just a 5-year-old typo in the code example in the docs.
docs typo fix
docs
n/a
```markdown
```

Switch comments in example to match the correct block

---

docs/src/main/sphinx/admin/fault-tolerant-execution.rst

Change link so output renders correctly.
Fix.
Documentation.
Fix link to Google documentation.
none
(✅ ) Sufficient documentation is included in this PR.
(✅ ) No release notes entries required.

Fix link to Google documentation

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java

Ignore table already exist error in case of same query id when creating Delta Lake tables. This issue happens when client get timeout, but remote Thrift metastore operation succeeded. Ran stress tests locally since it's reproducible in my laptop.
Fixes #12300
```markdown
```

Ignore table already exist error in case of same query id for Delta Lake

---

lib/trino-orc/src/main/java/io/trino/orc/OrcWriter.java

Fix checkArgument message in `OrcWriter`

Fix checkArgument message in `OrcWriter`

---

.github/workflows/ci.yml
plugin/trino-delta-lake/pom.xml
plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakeMetadata.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeConnectorSmokeTest.java
plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeGcsConnectorSmokeTest.java
plugin/trino-delta-lake/src/test/resources/io/trino/plugin/deltalake/hdp3.1-core-site.xml.gcs-template

Not merging into master yet, testing on @findepi 's branch
ConnectorSmokeTest for Delta Lake on GCS

Run Delta Lake smoke tests against GCS

---

core/trino-spi/src/test/java/io/trino/spi/TestSpiBackwardCompatibility.java

Replace `Map<String, Set<String>>` with a `Multimap`.
This allows more convenient builder pattern, where adding new entries
doesn't need to change existing lines.

Refactor BACKWARD_INCOMPATIBLE_CHANGES definition

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java

Minor refactoring in `IcebergPageSource`.
(✓) No documentation is needed.
(✓) No release notes entries required.

Minor refactoring in `IcebergPageSource`

---

plugin/trino-sqlserver/src/test/java/io/trino/plugin/sqlserver/BaseSqlServerConnectorTest.java

Fix error message for concurrent adding column in SQL Server

Fix error message for concurrent adding column in SQL Server

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergMaterializedViewTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogMaterializedViewTest.java

Test fix, see linked PR for original code change.
Fix, test only
Test only
I would not
Related code change: https://github.com/trinodb/trino/pull/12522
We forgot to run the Glue suite for it

Fix Iceberg Glue materialized view test

---

testing/trino-tests/src/test/java/io/trino/execution/TestDenyOnTable.java

Adapt the test for `DENY` statement to test `DENY` instead of `GRANT` when being applied on a missing table.
Test fix
N/A
N/A

Adapt test to use DENY statement

---

core/trino-main/src/main/java/io/trino/sql/planner/Coercer.java

Such a cast will later be rejected in `ExpressionAnalyzer`, producing
`TrinoException` with a message that can be confusing to end user.

Prevent adding coercion to unknown

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeGcs.java
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/apply-gcs-config.sh
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/core-site-overrides-template.xml
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/delta.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/hive.properties
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-gcs/iceberg.properties

Add multinode product test environment backed by GCS

---

core/trino-main/pom.xml
core/trino-main/src/main/java/io/trino/execution/scheduler/policy/PhasedExecutionSchedule.java
core/trino-main/src/main/java/io/trino/metadata/HandleResolver.java
core/trino-main/src/test/java/io/trino/execution/buffer/BenchmarkBlockSerde.java
pom.xml

No release notes entries required

Update airlift to 216

---

docs/src/main/sphinx/connector/iceberg.rst

Docs Only
Iceberg connector
https://github.com/trinodb/trino/pull/12579

Document the Iceberg split weight property

---

docs/src/main/sphinx/connector/delta-lake.rst

Add docs for delta parameters extracted from HiveConfig

---

core/trino-main/src/main/java/io/trino/connector/system/MaterializedViewSystemTable.java
core/trino-main/src/main/java/io/trino/connector/system/TableCommentSystemTable.java
core/trino-main/src/main/java/io/trino/connector/system/jdbc/CatalogJdbcTable.java
core/trino-main/src/main/java/io/trino/sql/rewrite/ShowQueriesRewrite.java

(X) No documentation is needed.
(X) No release notes entries required.

Static import MetadataListing.listCatalogNames

---

core/trino-spi/src/main/java/io/trino/spi/ptf/TableArgumentSpecification.java
core/trino-spi/src/test/java/io/trino/spi/TestSpiBackwardCompatibility.java

This is a fix.
It changes the SPI, but the change is in an area that is not yet used.

Remove unused argument

---

core/trino-main/src/main/java/io/trino/server/ui/TrimmedBasicQueryInfo.java

Fix check message in `TrimmedBasicQueryInfo`
(✓) No documentation is needed.
(✓) No release notes entries required.

Fix check message in `TrimmedBasicQueryInfo`

---

plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestMySqlConnectorTest.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestingMySqlServer.java
plugin/trino-raptor-legacy/src/test/java/io/trino/plugin/raptor/legacy/TestRaptorMySqlConnectorTest.java
plugin/trino-resource-group-managers/src/test/java/io/trino/plugin/resourcegroups/db/TestDbResourceGroupsMysqlFlywayMigration.java
plugin/trino-session-property-managers/src/test/java/io/trino/plugin/session/db/TestingMySqlContainer.java
service/trino-verifier/src/test/java/io/trino/verifier/TestDatabaseEventClient.java

fix
NO, just mysql ut
MySql unit test will failed when use Mac Apple M1 Pro chip
Fixes [#12607 ](https://github.com/trinodb/trino/issues/12607)
( X) No documentation is needed.
```markdown
```

Upgrade mysql image to 8.0.29

---

core/trino-main/src/main/java/io/trino/metadata/MetadataManager.java
core/trino-main/src/main/java/io/trino/metadata/OutputTableHandle.java
core/trino-main/src/test/java/io/trino/operator/TestTableWriterOperator.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/test/PlanBuilder.java

Call tableCreated() after table creation is finished

---

core/trino-main/src/test/java/io/trino/operator/aggregation/listagg/TestListaggAggregationFunction.java
core/trino-main/src/test/java/io/trino/sql/query/TestListagg.java
plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestingPhoenixServer.java
pom.xml

This version prohibits shaded imports for `org.apache`.
I'll rebase once #12560 gets merged.
fix
core
n/a
```markdown
```

Update Airbase to version 127

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/SemiTransactionalHiveMetastore.java

Retry deleting failed attempt output files

---

plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/PhoenixQueryRunner.java
plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestingPhoenixServer.java

Create schema and table if not exists in Phoenix server

Create schema and table if not exists in Phoenix server

---

docs/src/main/sphinx/connector/delta-lake.rst
docs/src/main/sphinx/connector/iceberg.rst

docs fix
docs
Improve documentation
(X) Sufficient documentation is included in this PR.
(X) No release notes entries required.
```markdown
```

Add missing docs for iceberg/delta properties

---

core/trino-main/src/main/java/io/trino/execution/DynamicFilterConfig.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalDynamicFilterConsumer.java
core/trino-main/src/main/java/io/trino/sql/planner/LocalExecutionPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/plan/DynamicFilterId.java
core/trino-main/src/test/java/io/trino/execution/TestDynamicFilterConfig.java
core/trino-main/src/test/java/io/trino/sql/planner/TestLocalDynamicFilterConsumer.java

The last commit to become part of https://github.com/trinodb/trino/pull/12152

Limit total size of dynamic filters collected

---

pom.xml

Update airlift version to 217

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java

Fix testStorageSchemaProperty assertion for Glue metastore

---

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
core/trino-main/src/main/java/io/trino/sql/planner/OptimizerConfig.java
core/trino-main/src/main/java/io/trino/sql/planner/Partitioning.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/ActualProperties.java
core/trino-main/src/main/java/io/trino/sql/planner/optimizations/AddExchanges.java
core/trino-main/src/test/java/io/trino/cost/TestOptimizerConfig.java
core/trino-main/src/test/java/io/trino/sql/planner/optimizations/TestAddExchangesPlans.java

New feature
core
See description of https://github.com/trinodb/trino/issues/12495
Fixes https://github.com/trinodb/trino/issues/12495
```markdown
```

Support use-exact-partitioning

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMaterializedViewTest.java

(x ) No documentation is needed.
( x) No release notes entries required.

Fix failures in TestIcebergGlueCatalogMaterializedViewTest

---

lib/trino-parquet/src/main/java/io/trino/parquet/writer/PrimitiveColumnWriter.java
lib/trino-parquet/src/main/java/io/trino/parquet/writer/StructColumnWriter.java

improvement
Native parquet writer
Improve performance of native parquet writer
```markdown
```

Reduce overheads of calculating bufferedBytes in parquet writer

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergSplitSource.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/procedure/IcebergOptimizeHandle.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/util/DataFileWithDeleteFiles.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

Fixes: https://github.com/trinodb/trino/issues/12617
```markdown
* Cleanup delete files during optimize. ({12617}`https://github.com/trinodb/trino/issues/12617`)
```

 Always optimize iceberg files when delete are present

---

docs/src/main/sphinx/connector/delta-lake.rst

Document comment support in Delta Lake

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/RollbackToSnapshotProcedure.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java

a fix
connector
fixes a bug that didn't allow to run rollback_to_snapshot procedure
Fixes: https://github.com/trinodb/trino/issues/12887
```markdown
```

Set valid classloader for RollbackToSnapshotProcedure

---

lib/trino-parquet/src/main/java/io/trino/parquet/writer/ParquetCompressor.java
pom.xml

improvement
Upgrades version of parquet library
Upgrades version of parquet library used by Trino.
https://github.com/trinodb/trino-hive-apache/pull/44
() Release notes entries required with the following suggested text:

Upgrade Parquet version to 1.12.3

---

testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java

Enable debug logs for RetryDriver in tests

---

core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorRecordSetProvider.java
lib/trino-plugin-toolkit/src/main/java/io/trino/plugin/base/classloader/ClassLoaderSafeConnectorRecordSetProvider.java
plugin/trino-kinesis/src/main/java/io/trino/plugin/kinesis/KinesisRecordSetProvider.java

Deprecated API cleanup
SPI
Not end user facing
```markdown
* Removed deprecated version of ConnectorRecordSetProvider#getRecordSet. ({issue}`13084`)
```

Remove deprecated version of ConnectorRecordSetProvider#getRecordSet

---

core/trino-main/src/test/java/io/trino/connector/MockConnector.java
core/trino-main/src/test/java/io/trino/connector/MockConnectorFactory.java
testing/trino-tests/src/test/java/io/trino/tests/TestMockConnector.java

Test tableFunctions and tableProcedures in MockConnector

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakePlugin.java

Additional test for https://github.com/trinodb/trino/pull/13086

Test Delta plugin init with cache disabled

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveMetadata.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java

```markdown
* Fix creating empty ORC bucket files when using ZSTD. ({issue}`9775`)
```
Fixes https://github.com/trinodb/trino/issues/9775

Fix creating empty ORC files when using ZSTD

---

.github/workflows/docs.yml

Run docs test on JDK 17

---

core/trino-main/src/test/java/io/trino/operator/join/unspilled/JoinTestUtils.java
core/trino-main/src/test/java/io/trino/operator/join/unspilled/TestHashJoinOperator.java

I missed some spilling related code when removing it from the forked operator.
refactoring
tests
Nothing to see here. Move along
```markdown
```

Remove dead code from non-spilling join operator

---

core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/ReorderJoins.java

Remove unnecessary array conversion

---

docs/src/main/sphinx/security/oauth2.rst

Add documentation for OIDC discovery #9788 
#9788 

Add docs for OIDC discovery #9788

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergNodePartitioningProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSinkProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSource.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergPageSourceProvider.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergStatistics.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergWritableTableHandle.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PartitionTransforms.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/TableStatisticsMaker.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergOrcConnectorTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergV2.java

refactoring
These are preparatory commits for https://github.com/trinodb/trino/pull/13219 and https://github.com/trinodb/trino/pull/7933

Iceberg cleanup

---

core/trino-main/src/main/java/io/trino/sql/planner/LogicalPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/QueryPlanner.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DecorrelateUnnest.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/TransformCorrelatedScalarSubquery.java
core/trino-main/src/test/java/io/trino/sql/planner/TestLogicalPlanner.java
core/trino-main/src/test/java/io/trino/sql/planner/TestRecursiveCte.java
core/trino-main/src/test/java/io/trino/sql/planner/TestWindowFrameRange.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestDecorrelateUnnest.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestMergeProjectWithValues.java
core/trino-main/src/test/java/io/trino/sql/planner/iterative/rule/TestTransformCorrelatedScalarSubquery.java

refactoring
Extracted from https://github.com/trinodb/trino/pull/7933

Add utility to resolve failure function

---

core/trino-main/src/main/java/io/trino/execution/scheduler/BucketNodeMap.java
core/trino-main/src/main/java/io/trino/execution/scheduler/FixedBucketNodeMap.java
core/trino-main/src/main/java/io/trino/execution/scheduler/NodeScheduler.java
core/trino-main/src/main/java/io/trino/execution/scheduler/SqlQueryScheduler.java
core/trino-main/src/main/java/io/trino/execution/scheduler/StageTaskSourceFactory.java
core/trino-main/src/main/java/io/trino/execution/scheduler/group/DynamicBucketNodeMap.java
core/trino-main/src/main/java/io/trino/sql/planner/NodePartitioningManager.java

This refactoring removes some old code related to grouped execution.

Minor cleanup for BucketNodeMap and related

---

core/trino-main/src/main/java/io/trino/operator/TrinoOperatorFactories.java

Remove redundant else

---

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java

Just a cleanup. No docs or release notes required.

Remove deprecated comment

---

docs/src/main/sphinx/connector/hive.rst
docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-391.md

Assemble the release notes for the upcoming Trino 391 release.
Improvement
Docs only.
Add the release notes for Trino 391 with sections for general, security, connectors and other topics as included in the release.
Fixes #13187 
(✅) Sufficient documentation is included in this PR.
(✅) No release notes entries required.
( ) Release notes entries required with the …

Add Trino 391 release notes

---

docs/src/main/sphinx/release/release-391.md

Release notes were merged but we didn't actually release yesterday, so this tracks any necessary updates to the release notes before we cut the release.
4175a6aa22b2cde946da88081d8d47af0e444547 @raunaqmorarka #12956 ✅ rn ✅ docs
9b7c1b95bf1d76ee4a6c87bfcb502667c8b7f6ca @raunaqmorarka #12956 ✅ rn ✅ docs

Update Trino 391 release notes

---

plugin/trino-kafka/src/test/java/io/trino/plugin/kafka/KafkaQueryRunner.java

Minor improvement in Kafka query runner

Minor improvement in Kafka query runner

---

pom.xml

Update benchto version

---

core/trino-spi/src/main/java/io/trino/spi/connector/ConnectorNodePartitioningProvider.java

Remove obsolete TODO

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/BenchmarkHiveFileFormat.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/BenchmarkProjectionPushdownHive.java
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-master-jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode/multinode-worker-jvm.config
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/presto/etc/jvm.config

Cleanup
Configuration
Removal of no longer necessary configuration flags
```markdown
```

Cleanup JVM configuration files after moving to JDK 17

---

core/trino-main/src/main/java/io/trino/server/Server.java
core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
testing/trino-tests/src/test/java/io/trino/execution/TestConnectorEventListener.java

Fix failures in TestConnectorEventListener

Fix failures in TestConnectorEventListener

---

docs/src/main/sphinx/connector/tpch.rst

Adds a type mapping section to the TPCH connector doc. All connector docs should have type mapping sections for consistency, even when the contents are limited.
Improvement
Documentation
Describe why type mapping does not apply to the TPCH connector
( ) Release notes entries …

Add type mapping section to TPCH connector

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogConnectorSmokeTest.java

Fix Iceberg Glue smoke test testShowCreateTable
Test fix
Test only
n/a
Failure caused by: https://github.com/trinodb/trino/pull/12941/

Fix Iceberg Glue testShowCreateTable

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/cassandra/TestSelect.java

Fix query in Cassandra product test

Fix query in Cassandra product test

---

docs/src/main/sphinx/connector/delta-lake.rst

Change icberg.unique.. into delta.unique.. in delta docs

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePageSink.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HivePageSink.java

Remove obsolete sample weight comment

---

pom.xml

Upgrade ASM to 9.3

---

docs/src/main/sphinx/connector/system.rst

Improvement.
Changes made to documentation.
Edit type mapping section for Memory connector,
```markdown
```

Edit type mapping section for System connector

---

docs/src/main/sphinx/connector/tpcds.rst

Improvement.
Changes made to documentation.
Edit type mapping section for System connector.
```markdown
```

Edit type mapping section for TPCDS connector

---

docs/src/main/sphinx/connector/mysql.rst

Improvement.
Change to documentation.
Edit type mapping section for MySql connector.
```markdown
```

Edit type mapping section for MySql connector

---

pom.xml

improvement
checks
n/a
```markdown
```

Upgrade errorprone to version 2.15.0

---

core/trino-main/pom.xml
pom.xml

This version of Airlift updates the Byte Buddy library and its JNA dependency to the latest 5.12.1. This should help us to remove the JNA dependency in the new plugin being added in #12929
improvement
core
n/a
( ) Release notes entries required with the following suggested …

Update Airlift version to 218

---

plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java

Add issue link to comment in Kudu testCharVarcharComparison

Add issue link to comment in Kudu testCharVarcharComparison

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/alluxio/AlluxioMetastoreModule.java
pom.xml

Upgrade alluxio to 2.8.1 to fix security vulnerabilities
Fix the Vulnerabilities from dependencies:
[CVE-2021-43859](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-43859)
[CVE-2020-15250](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15250)
No
https://github.com/trinodb/trino/pull/13513
( ) No …

Upgrade alluxio to 2.8.1 to fix security vulnerabilities

---

docs/src/main/sphinx/connector/blackhole.rst
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMergeSink.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMergeTableHandle.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHoleMetadata.java
plugin/trino-blackhole/src/main/java/io/trino/plugin/blackhole/BlackHolePageSinkProvider.java
testing/trino-tests/src/test/java/io/trino/security/TestAccessControl.java

Support UPDATE and MERGE in Blackhole

---

docs/README.md

Fix unresovled file references in docs/README.md

---

testing/trino-testing/src/main/java/io/trino/testing/datatype/DataTypeTest.java

Fix typo and add missing final modifier in DataTypeTest

---

core/trino-main/src/main/java/io/trino/sql/planner/sanity/PlanSanityChecker.java

Fix formatting in PlanSanityChecker

---

.github/workflows/ci.yml

Follow up for #13494
fix
ci
n/a
```markdown
```

Check commits only on PR runs

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/BackgroundHiveSplitLoader.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveSplitManager.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/InternalHiveSplitFactory.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestBackgroundHiveSplitLoader.java

- Fix typo in BackgroundHiveSplitLoader
- Remove unused parameter from InternalHiveSplitFactory

Minor code cleanup

---

docs/src/main/sphinx/connector/clickhouse.rst

some extremely minor changes to update the URLs for the website, point to the JDBC driver repository for deeper compatibility information, and resolve an incorrect port in the TLS URL
Minor docs update
n/a
documentation update

Update link and port in ClickHouse documentation

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/thrift/MetastoreSupportsDateStatistics.java

Refactoring
Hive connector
Change the access modifier of the class to allows for creating `io.trino.plugin.hive.metastore.thrift.ThriftHiveMetastoreClient` from other packages.

Change the access modifier of the class

---

docs/src/main/sphinx/develop/connectors.rst

This PR also includes an introduction to different types of pushdowns. It repeats most of the info from the Javadoc comments in the `ConnectorMetadata` interface, but it also mentions how additional information can be passed between the metadata service and record set provider inside the table handle. It also describes how to properly handle "impedance mismatch", where the data source might not support all order combinations, and to return an actionable error message.
improvement
docs
n/a
* Related to #12956 which …

Document limit pushdown in the dev guide

---

plugin/trino-password-authenticators/pom.xml
pom.xml

This may help reduce test flakiness, if downloading Ryuk image is
retried.
https://github.com/testcontainers/testcontainers-java/issues/5760#issuecomment-1222228864

Update testcontainers to 1.17.3

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/s3/S3HiveQueryRunner.java

Add main method to `S3HiveQueryRunner`. The query runner is useful to confirm the behavior of Thrift metastore and S3 (MinIO). 

Add main method to S3HiveQueryRunner

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/transactionlog/writer/AzureTransactionLogSynchronizer.java

Fixes #13825
(x) No release notes entries required (this PR should be merged before releasing)

Fix tmp file path in AzureTransactionLogSynchronizer

---

plugin/trino-clickhouse/src/main/java/io/trino/plugin/clickhouse/ClickHouseClient.java

Extracting partial commits from #11148.

Fix formatting and remove obsolete TODO in ClickHouseClient

---

plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConnectorTest.java

Remove redundant overridden tests in BigQuery

Remove redundant overridden tests in BigQuery

---

docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-394.md

Assemble the release notes for the upcoming Trino 394 release.
Improvement
Docs only.
Add the release notes for Trino 394 with sections for general, security, connectors and other topics as included in the release.
Fixes #13723
(✅) Sufficient documentation is included in this PR.
(✅) No release notes entries required.
( ) Release notes entries required with the …

Add Trino 394 release notes

---

docs/src/main/sphinx/release/release-394.md

Updating 394 release notes, merged in #13813, but then #13810 was landed.

Update 394 release notes for final commit

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDatabricksWithGlueMetastoreCleanUp.java

Improve `TestDatabricksWithGlueMetastoreCleanUp` to fix flaky tests

---

core/trino-main/src/main/java/io/trino/type/LikeFunctions.java
core/trino-main/src/test/java/io/trino/operator/scalar/TestConditions.java

Remove duplicated handling of LIKE escape character

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java

When doing client side encryption (see https://docs.aws.amazon.com/AmazonS3/latest/userguide/UsingClientSideEncryption.html ), it is important to set both the region as well as the crypto AWS KMS region while building an encrypted S3 instance.
This is needed in order to ensure that the KMS key is being searched in 
the appropriate AWS region.
This is probably needed due to usage of the deprecated `AmazonS3EncryptionClientBuilder` (to be replaced by `AmazonS3EncryptionClientV2Builder`.
Not setting the AWS KMS region, while using the hive setting `hive.s3.pin-client-to-current-region=true`,  results in the following error when the AWS KMS key is placed in a different region than the default AWS KMS region `us-east-1`:
```
Caused by: com.amazonaws.services.kms.model.NotFoundException: Key …
```

Set AWS KMS region when building the S3 encrypted instance

---

core/trino-main/src/main/java/io/trino/sql/planner/TranslationMap.java

Use more precise type in TranslationMap

---

core/trino-main/src/test/java/io/trino/operator/scalar/FunctionAssertions.java

Remove duplicated code

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/IcebergQueryRunner.java

Add Glue query runner to Iceberg and Delta Lake connector. I sometimes want this query runner to check Glue behavior quickly. 

Add Glue query runner to Iceberg and Delta Lake connector

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java

Add comment and test for adding not null column in Iceberg

Add comment and test for adding not null column in Iceberg

---

core/trino-server-rpm/src/test/java/io/trino/server/rpm/ServerIT.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/CassandraServer.java
plugin/trino-cassandra/src/test/java/io/trino/plugin/cassandra/TestingScyllaServer.java
plugin/trino-clickhouse/src/test/java/io/trino/plugin/clickhouse/TestingClickHouseServer.java
plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestingKuduServer.java
plugin/trino-mariadb/src/test/java/io/trino/plugin/mariadb/TestingMariaDbServer.java
plugin/trino-mysql/src/test/java/io/trino/plugin/mysql/TestingMySqlServer.java
plugin/trino-password-authenticators/src/test/java/io/trino/plugin/password/ldap/TestingOpenLdapServer.java
plugin/trino-pinot/src/test/java/io/trino/plugin/pinot/TestingPinotCluster.java
plugin/trino-postgresql/src/test/java/io/trino/plugin/postgresql/TestingPostgreSqlServer.java
plugin/trino-prometheus/src/test/java/io/trino/plugin/prometheus/PrometheusServer.java
plugin/trino-redis/src/test/java/io/trino/plugin/redis/util/RedisServer.java
plugin/trino-singlestore/src/test/java/io/trino/plugin/singlestore/TestingSingleStoreServer.java
testing/trino-testing-containers/src/main/java/io/trino/testing/containers/wait/strategy/SelectedPortWaitStrategy.java
testing/trino-testing-kafka/src/main/java/io/trino/testing/kafka/TestingKafka.java

Minor code cleanups

---

client/trino-cli/src/main/java/io/trino/cli/ClientOptions.java
client/trino-cli/src/main/java/io/trino/cli/Console.java
client/trino-cli/src/test/java/io/trino/cli/TestQueryRunner.java
client/trino-client/src/main/java/io/trino/client/ClientSession.java
client/trino-jdbc/src/main/java/io/trino/jdbc/TrinoConnection.java
testing/trino-testing/src/main/java/io/trino/testing/AbstractTestingTrinoClient.java
testing/trino-tests/src/test/java/io/trino/execution/TestFinalQueryInfo.java
testing/trino-tests/src/test/java/io/trino/execution/TestUserImpersonationAccessControl.java

Refactor ClientSession to follow builder pattern consistently
refactoring
client library
N/A

Convert ClientSession to follow builder pattern

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/metastore/glue/TestDeltaLakeRenameToWithGlueMetastore.java

Simplify `TestDeltaLakeRenameToWithGlueMetastore`

Simplify TestDeltaLakeRenameToWithGlueMetastore

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java

Simplify Delta Lake query runner

Simplify Delta Lake query runner

---

docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-395.md

Assemble the release notes for the upcoming Trino 395 release.
Improvement
Docs only.
Add the release notes for Trino 395 with sections for general, security, connectors and other topics as included in the release.
Fixes #13913
(✅) Sufficient documentation is included in this PR.
(✅) No release notes entries required.
( ) Release notes entries required with the …

Add Trino 395 release notes

---

docs/src/main/sphinx/release/release-395.md

Link to associated issue instead of PR

Update link to issue in release notes

---

pom.xml

Update Antlr to 4.11.1

---

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/test/java/io/trino/sql/analyzer/TestAnalyzer.java

Disallow `UPDATE` , `MERGE` , `DELETE` on materialized views.
`INSERT` and `TRUNCATE` have been handled already.
Disallow `UPDATE` , `MERGE` , `DELETE` on materialized views.
```markdown
```

Disallow writes on materialized views

---

core/trino-main/src/main/java/io/trino/operator/exchange/LocalExchange.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergConnectorTest.java

Fixes #13960
```markdown
* Fix *"No bucket node map"* failure when inserting data. ({issue}`13960`)
```

Fix "No bucket node map" failure for Iceberg inserts

---

docs/src/main/sphinx/connector/clickhouse.rst
docs/src/main/sphinx/connector/delta-lake.rst
docs/src/main/sphinx/connector/mariadb.rst
docs/src/main/sphinx/connector/mysql.rst
docs/src/main/sphinx/connector/oracle.rst
docs/src/main/sphinx/connector/phoenix.rst
docs/src/main/sphinx/connector/postgresql.rst
docs/src/main/sphinx/connector/sqlserver.rst
docs/src/main/sphinx/language/types.rst

Type mapping needs a section explaining the concept as it applies to all connectors, especially the difference in mappings in each direction between Trino and any given data source. This PR adds the overview section and links back to it from connector type mapping sections (to be expanded out to all connectors as we improve type mapping documentation across the board).
Improvement
Documentation
Better explain how data type mapping works in practice in Trino connectors
* Related to/adds upon #11448 
( ) No documentation …

Add an overview section for type mapping

---

docs/src/main/sphinx/connector/bigquery.rst
docs/src/main/sphinx/connector/cassandra.rst
docs/src/main/sphinx/connector/druid.rst
docs/src/main/sphinx/connector/memsql.rst

Add links to the type mapping overview from some connector docs. Follow-up to https://github.com/trinodb/trino/pull/13738
Make it easier to find an explanation of what type mapping is.
```markdown
```

Add links to type mapping overview

---

pom.xml

Iceberg library upgrade to 0.14.1
N/A

Bump iceberg to 0.14.1

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/Environment.java

Fix incorrect error message

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/cache/TestCachingHiveMetastore.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/metastore/thrift/MockThriftMetastoreClient.java

Add unit tests for `dropTable()` in `CachingHiveMetastore`
```markdown
* Add unit tests for dropTable() in CachingHiveMetastore.  ({issue}`issuenumber`)
```

Add unit test of dropTable in CachingHiveMetastore

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/catalog/glue/TestIcebergGlueCatalogAccessOperations.java

Fix logical merge conflict between 79dc367f6ff3b2b7e893bb7c91d02d7b33acb744 (https://github.com/trinodb/trino/pull/13875) and 1dc391a6802597d51b83d614e79c8e07e2979a2c (https://github.com/trinodb/trino/pull/14145).

Fix test after logical merge conflict

---

docs/src/main/sphinx/connector/kafka.rst

Document Kafka connector log level
```markdown
```

Document Kafka connector log level

---

docs/src/main/sphinx/ext/download.py
docs/src/main/sphinx/installation.rst
docs/src/main/sphinx/installation/rpm.rst

Adds a page documenting the RPM installation process. 
Improvement
Docs
This change provides instruction for users who would like to install Trino using RPM on an RPM-supported Linux distribution.
```markdown …
```

Add documentation for RPM usage

---

docs/src/main/sphinx/security/oauth2.rst

Fix default value for oidc.use-userinfo-endpoint

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/PageReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetColumnChunk.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestColumnReader.java

Add more tests to TestColumnReader
Add more tests to TestColumnReader

Add more tests to TestColumnReader

---

core/trino-main/src/main/java/io/trino/execution/SqlTask.java
core/trino-main/src/main/java/io/trino/operator/TaskContext.java
core/trino-main/src/main/java/io/trino/server/remotetask/TaskInfoFetcher.java

See commit messages
N/A
```markdown
```

Fix small inconsistencies in RemoteTask status reporting

---

core/trino-spi/src/main/java/io/trino/spi/block/DictionaryBlock.java

Use a random dictionary source id when dictionary is unwrapped

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/DeltaLakeQueryRunner.java

Cosmetic change to delta-lake and iceberg test
NA
```markdown
```

Remove redundant variable in DeltaLakeQueryRunner

---

testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvMultinodeAllConnectors.java
testing/trino-product-tests-launcher/src/main/resources/docker/presto-product-tests/conf/environment/multinode-all/hudi.properties

Add Hudi in the smoke test to check if server starts with it enabled
n/a

Add Hudi in the smoke test to check if server starts with it enabled

---

plugin/trino-kudu/src/test/java/io/trino/plugin/kudu/TestKuduConnectorTest.java
testing/trino-testing/src/main/java/io/trino/testing/BaseConnectorTest.java

Fix typo in `BaseConnectorTest#testCreateTableWithLongColumnName` method
NA
```markdown
```

Fix typo in TestKuduConnectorTest and BaseConnectorTest

---

docs/src/main/sphinx/connector/mongodb.rst

Add type mapping section to the MongoDB connector doc.
Add a section explaining type mappings between MongoDB and Trino.
```markdown
```

Add type mapping section to MongoDB connector

---

plugin/trino-bigquery/pom.xml
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryConfig.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryPageSourceProvider.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryReadClientFactory.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplit.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQuerySplitManager.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryStoragePageSource.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConfig.java
pom.xml

Add following improvements:
1. Update all BQ dependencies
2. Add configuration for RPC/channel
3. Calculate memory for page source

Misc BigQuery improvements

---

core/trino-main/src/main/java/io/trino/operator/PageBuffer.java

Remove unused constructor

---

plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSource.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiPageSourceProvider.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/HudiSplit.java
plugin/trino-hudi/src/main/java/io/trino/plugin/hudi/split/HudiSplitFactory.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiSmokeTest.java

Fixes #14341
```markdown
* Fix failure when reading hidden columns. ({issue}`14341`)
```

Fix failure when reading hidden columns in Hudi

---

docs/src/main/sphinx/connector/googlesheets.rst

Add type mapping section to Google Sheets connector.
Add a section explaining type mappings between Google Sheets and Trino.
```markdown
```

Add type mapping section to Google Sheets connector

---

.github/workflows/ci.yml

Fix broken test-other-modules step in ci.yml
```markdown
```

Fix broken test-other-modules step in ci.yml

---

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/HashGenerationOptimizer.java

Fix typos in HashGenerationOptimizer

---

docs/src/main/sphinx/connector/kudu.rst

Add type mapping section to Kudu connector doc.
Add a section to the documentation that explains type mapping between the connector and Trino.
```markdown
```

Add type mapping section to Kudu connector

---

docs/src/main/sphinx/connector/pinot.rst

Improve type mapping documentation for Pinot connector.
Add boilerplate text and links. Reformat table for better wrapping.

Improve type mapping docs for Pinot connector

---

plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/HudiQueryRunner.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/ResourceHudiTablesInitializer.java

Fix Hudi query runners

---

docs/src/main/sphinx/security/oauth2.rst

There has been some confusion over the current wording, which is a bit stilted.
(x) This is not user-visible or IS docs only and no release notes are required.
```markdown
```

Clarify use of groups field for OAuth2

---

docs/src/main/sphinx/connector/kafka.rst

I noticed incomplete sentences, as well as punctuation and grammar issues. This PR is to correct them.
( ) This is not user-visible and no release notes are required.
```markdown
```

Review Kafka connector doc for grammar issues

---

docs/src/main/sphinx/connector/prometheus.rst

Improvement.
Add type mapping section to Prometheus connector.
```markdown
```

Add type mapping section to Prometheus connector

---

docs/src/main/sphinx/connector/iceberg.rst

Improvement.
Changes made to documentation.
Add fragments for Avro, ORC, and Parquet mappings to type mapping section.
```markdown
```

Update type mapping for Iceberg connector

---

core/trino-main/src/main/java/io/trino/server/SliceSerialization.java

Uses jackson's built-in binary encoding support to improve efficiency of `Slice` JSON serialization / deserialization by avoiding materializing the result in an intermediate `String`.
No non-technical explanation should be necessary.

Reduce overheads in SliceSerialization

---

docs/src/main/sphinx/connector/accumulo.rst

~~The Accumulo connector uses a custom plugin that's currently all named around Presto. This PR proposes that we work with the plugin owners to shift from the "Presto" name into "Trino", and outlines what this doc should look like after such a change.~~
The Bloomberg presto-accumulo repository is not maintained anymore, so the conclusion is to no longer link to it.
Improvement
Documentation
Update the Accumulo connector doc to be written for Trino.
(x) Sufficient documentation is included …

Remove references to defunct presto-accumulo tools repository

---

core/trino-main/src/main/java/io/trino/operator/OperatorFactories.java

Modifier 'public' is redundant for interface members.
Minor change in coding style.

OperatorFactories: remove unnecessary modifiers

---

core/trino-server-main/src/main/java/io/trino/server/TrinoServer.java

Simplify regexp to TrinoServer

---

docs/src/main/sphinx/connector/bigquery.rst
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryType.java
plugin/trino-bigquery/src/main/java/io/trino/plugin/bigquery/BigQueryTypeUtils.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryConnectorTest.java
plugin/trino-bigquery/src/test/java/io/trino/plugin/bigquery/TestBigQueryTypeMapping.java

Relates to #13741
```markdown
```

Support writing timestamp type in BigQuery

---

docs/src/main/sphinx/admin/properties-resource-management.rst
docs/src/main/sphinx/conf.py
docs/src/main/sphinx/installation.rst
docs/src/main/sphinx/installation/containers.rst
docs/src/main/sphinx/installation/kubernetes.rst

Adding helm chart documentation so that users can run Trino on Kubernetes.

Add helm chart documentation

---

docs/src/main/sphinx/release.rst
docs/src/main/sphinx/release/release-399.md

Assemble the release notes for the upcoming Trino 399 release. Fixes #14360 
N/A
Format: commit, committer/maintainer, PR/issue number, ✅ / ❌ rn ✅ / ❌ docs
d81ee4f7931bbde2776a130e4b5c90cdd0028e57 @findepi #14276 ✅ rn ✅ docs
8f44094f3801fa83e6429eb626a1b88b89ed7548 @findepi #14290 ✅ rn ✅ docs
09eacf9f0a2e8eb9b2fb03b2e86f504380d15a74 @findepi #14290 ✅ rn ✅ docs …

Add Trino 399 release notes

---

plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/HudiQueryRunner.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/S3HudiQueryRunner.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiCopyOnWriteMinioConnectorTest.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiMergeOnReadMinioConnectorTest.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/TestHudiSmokeTest.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/HudiTablesInitializer.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/ResourceHudiTablesInitializer.java
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/TpchHudiTablesInitializer.java

Add tests for Hudi meta columns

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/TestFunctions.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/TestSqlCancel.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestHiveAndDeltaLakeRedirect.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/util/DeltaLakeTestUtils.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/AbstractTestHiveViews.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAbfsSyncPartitionMetadata.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestAvroSchemaUrl.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestComments.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveBucketedTables.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveCompression.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHivePartitionProcedures.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveRedirectionToIceberg.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveStorageFormats.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/hive/TestHiveTransactionalTable.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergOptimize.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergPartitionEvolution.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergProcedureCalls.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergRedirectionToHive.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/TestIcebergSparkCompatibility.java
testing/trino-product-tests/src/main/java/io/trino/tests/product/iceberg/util/IcebergTestUtils.java

Fixes https://github.com/trinodb/trino/issues/14440
Use QueryResult#getOnlyValue in trino-product-tests
NA
```markdown
```

Use QueryResult#getOnlyValue in trino-product-tests

---

core/trino-spi/src/main/java/io/trino/spi/type/TypeOperators.java

Fix typo in TypeOperators

---

docs/src/main/sphinx/installation/rpm.rst

Adds a link to the Helm installation docs from the RPM installation page.
```markdown
```

Update RPM docs with a link to Helm docs

---

.github/workflows/ci.yml

Always run all product tests on master, because impacted features are not being detected there, so the filtering would exclude all PT matrix items.
A follow-up after #10984 and #14534
n/a

Always run all product tests on master

---

docs/src/main/sphinx/connector/delta-lake.rst

Document delta.metadata.cache-size configuration property

---

core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedStageExecution.java

Stage state can be updated by both updateTaskStatus and schedulingComplete methods. If in updateTaskStatus method stage state is obtined before task is added to finished or flushing list, then it leads to a race condition where neither updateTaskStatus and schedulingComplete transitions stage into finished state.
Fixes https://github.com/trinodb/trino/issues/14605

Obtain stage state after task is added to finished of flushing list

---

plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergMinioConnectorSmokeTest.java

Add `ALTER TABLE` statement to Iceberg trailing slash test

---

testing/trino-testing-containers/src/main/java/io/trino/testing/containers/Minio.java

Use the latest MinIO Docker image in order to benefit of the latests fixes on MinIO and also profit from the enhanced compatibility for the S3 API operations.
Test infrastructure change
N/A
```markdown
```

Bump minio Docker image to `RELEASE.2022-10-05T14-58-27Z`

---

docs/src/main/sphinx/security/file-system-access-control.rst

Docs fix, one-letter typo.
Docs only.

Fix typo in access control docs

---

docs/src/main/sphinx/connector/accumulo.rst

Improvement.
Changes made to documentation only.
Add type mapping sectio to Accumulo connector
```markdown
```

Add type mapping section to Accumulo connector

---

docs/src/main/sphinx/admin/fault-tolerant-execution.rst

Document exchange.s3.path-style-access configuration property

---

docs/src/main/sphinx/connector/hive-cos.rst
docs/src/main/sphinx/connector/hive.rst
plugin/trino-hive/src/main/java/io/trino/plugin/hive/InternalHiveConnectorFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/cos/CosConfigurationInitializer.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/cos/CosServiceConfigurationProvider.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/cos/HiveCosModule.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/cos/HiveCosServiceConfig.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/cos/ServiceConfig.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/cos/TrinoCosFileSystem.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/cos/TestHiveCosServiceConfig.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/cos/TestHiveCosServiceConfigurationProvider.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/cos/TestServiceConfig.java

Add IBM Cloud Object Storage support
```markdown
* Add IBM Cloud Object Storage support
```

Add Hive IBM Cloud Object Storage support

---

.github/workflows/ci.yml
testing/trino-faulttolerant-tests/pom.xml

Add default trino-faulttolerant-tests profile to CI

---

plugin/trino-hudi/pom.xml
plugin/trino-hudi/src/test/java/io/trino/plugin/hudi/testing/TpchHudiTablesInitializer.java

Fix #14430
Upgrade Hudi version for the connector 
```markdown
* Fix some things. ({issue}`14430`)
```

Upgrade Hudi 0.12.1 for the connector

---

pom.xml

Test infrastructure change
```markdown
```

Bump databricks-jdbc to 2.6.29

---

core/trino-main/src/main/java/io/trino/sql/planner/ExpressionInterpreter.java
core/trino-main/src/main/java/io/trino/sql/planner/iterative/rule/DesugarCurrentUser.java

Minor cleanup. No release notes or docs required.

Remove unused parameter

---

core/trino-main/src/test/java/io/trino/sql/planner/assertions/JoinMatcher.java
core/trino-main/src/test/java/io/trino/sql/planner/assertions/PlanMatchPattern.java

Just a minor refactor. No release notes or docs required.

Refactor JoinMatcher.Builder

---

core/trino-main/src/main/java/io/trino/execution/scheduler/PipelinedStageExecution.java

Remove unused variable

---

core/trino-main/src/main/java/io/trino/execution/scheduler/policy/PhasedExecutionSchedule.java

Register state change listener only once

---

core/trino-main/src/main/java/io/trino/server/protocol/Query.java

Typo `is the a repeated request for the last results?`

Fix typo in io/trino/server/protocol/Query.java

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSharedGlueMetastoreWithTableRedirections.java

Relates to https://github.com/trinodb/trino/pull/14940#issuecomment-1306881202

Fix broken `TestDeltaLakeSharedGlueMetastoreWithTableRedirections.testShowSchemas`

---

plugin/trino-hive/src/test/java/io/trino/plugin/hive/BaseHiveConnectorTest.java

Add test for insert which creates multiple small files

---

core/trino-main/src/main/java/io/trino/dispatcher/FailedDispatchQuery.java
core/trino-main/src/main/java/io/trino/execution/QueryInfo.java
core/trino-main/src/main/java/io/trino/execution/QueryStateMachine.java
core/trino-main/src/test/java/io/trino/execution/MockManagedQueryExecution.java
core/trino-main/src/test/java/io/trino/execution/TestQueryInfo.java
core/trino-main/src/test/java/io/trino/server/TestBasicQueryInfo.java
core/trino-main/src/test/java/io/trino/server/TestQueryStateInfo.java

Avoid repeatedly creating pruned QueryInfo when it's already pruned.
```markdown
```

Avoid repeatedly creating pruned QueryInfo when it's already pruned

---

core/trino-main/src/main/java/io/trino/execution/buffer/OutputBufferMemoryManager.java

For example, in case of aggregation buffer will be empty until final aggregation starts flushing it's data.
```
BEFORE
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Fragment 1 [HASH]
Output buffer active time: 1.90m, buffer utilization distribution (%): {p01=0.00, p05=0.00, p10=0.00, p25=0.00, p50=0.00, p75=0.00, p90=0.00, p95=0.00, p99=0.00, max=4
Aggregate[type = FINAL, keys = [suppkey]]
AFTER
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Fragment 1 [HASH]
Output buffer active time: 35.04ms, buffer utilization distribution (%): …
```

Skip recording of buffer utilization until data is put into buffer

---

core/trino-main/src/test/java/io/trino/security/TestFileBasedSystemAccessControl.java

Use assertThatThrownBy in TestFileBasedSystemAccessControl

Use assertThatThrownBy in TestFileBasedSystemAccessControl

---

core/trino-main/src/test/java/io/trino/sql/planner/TestInsert.java

Fix running TestInsert on single CPU nodes

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergTableOperations.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/GlueIcebergUtil.java
plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java

Fixes https://github.com/trinodb/trino/issues/14967
Let `GlueIcebergUtil.getTableInput` populate the table type property
NA
```markdown
```

Let `GlueIcebergUtil.getTableInput` populate the table type property

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcDeleteDeltaPageSource.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcDeleteDeltaPageSourceFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcDeletedRows.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcPageSourceFactory.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveTestUtils.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveFileFormats.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestOrcPageSourceMemoryTracking.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/benchmark/StandardFileFormats.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcDeleteDeltaPageSource.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcDeletedRows.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPageSourceFactory.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/orc/TestOrcPredicates.java

This is just to finish the port of OrcPageSourceFactory that was begun here https://github.com/trinodb/trino/pull/14627
```markdown
```

Port OrcPageSourceFactory completely to TrinoFileSystem

---

core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java

See individual commits' descriptions
Relates to https://github.com/trinodb/trino/issues/14248

Reduce tests memory footprint

---

pom.xml

To pick up https://github.com/trinodb/trino-hadoop-apache/pull/39
Fixes https://github.com/trinodb/trino/issues/15055

Update io.trino.hadoop:hadoop-apache to 3.2.0-18

---

.github/workflows/ci.yml
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/EnvSinglenodeDeltaLakeOss.java

Change AWS environment for Hive and Iceberg tests

---

core/trino-main/src/main/java/io/trino/SystemSessionProperties.java
core/trino-main/src/main/java/io/trino/execution/QueryManagerConfig.java

Fix retry_delay_scale_factor validation message
```markdown
```

Fix retry_delay_scale_factor validation message

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/AbstractHiveAcidWriters.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/AcidInfo.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveLocationService.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveTableHandle.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveUpdatablePageSource.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/HiveWriterFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/LocationHandle.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/MergeFileWriter.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/acid/AcidTransaction.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcFileWriter.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/orc/OrcFileWriterFactory.java
plugin/trino-hive/src/main/java/io/trino/plugin/hive/util/HiveUtil.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/HiveTestUtils.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHiveLocationService.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/TestHivePageSink.java

Cleanup unused methods and fields in Hive connector

---

.github/pull_request_template.md

Very few people are filling out the non-technical explanation, and frankly, someone looking on GitHub at PRs isn't going to be non-technical. However, at the Trino summit and contributor congregation, I heard from several engineers who said that they still would appreciate more context in order to understand what's happening and how it may impact them downstream.
I think engineers are more likely to write a little more if it's framed as helping other engineers, so let's re-frame it and make it a little more clear who our target audience is when we're filling out a PR bodies. The goal is to make it easier to understand and contribute to Trino.
Also going to prompt for related issues, because they tend to provide important context, too, and it's not great if we forget to link them.
change …

Update PR template to be engineer-focused

---

testing/trino-server-dev/etc/catalog/hudi.properties

Test infrastructure change
Ease up hudi testing with Trino by using the hudi configuration corresponding to the product test environment

Use hudi confiugration corresponding to the product test environment

---

docs/src/main/sphinx/release/release-397.md
docs/src/main/sphinx/sql/alter-materialized-view.rst

We've made this same typo in a few places (one of them was me...), super simple fix.
typos.

Fix 'materalized' typo

---

core/trino-main/src/main/java/io/trino/sql/analyzer/StatementAnalyzer.java
core/trino-main/src/test/java/io/trino/sql/query/TestRowFilter.java

Add tests for MERGE with row filters

---

.github/workflows/milestone.yml

This reverts commit acc2886d0725ec313a5613f84b23f3c11c455e82 and c38490bad7baa07953a24f69bc1be85da01dde00.

Revert set-milestone workflow to known-working state

---

plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/procedure/VacuumProcedure.java

Use S3 batch deletes for Delta Lake vacuum procedure
Relates to #14909
```markdown
* Improve performance and storage requirements when running the `vacuum` procedure on S3-compatible storage. ({issue}`15072`)
```

Use S3 batch deletes for Delta Lake vacuum procedure

---

docs/src/main/sphinx/connector/druid.rst
docs/src/main/sphinx/connector/mariadb.rst
docs/src/main/sphinx/connector/redshift.rst
testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java

Follow-up to https://github.com/trinodb/trino/pull/13529#issuecomment-1207298324

Add missing docs for secretly setting user credentials in JDBC connectors

---

core/trino-main/src/main/java/io/trino/server/testing/TestingTrinoServer.java
core/trino-main/src/main/java/io/trino/testing/LocalQueryRunner.java
core/trino-main/src/main/java/io/trino/testing/QueryRunner.java
plugin/trino-thrift/src/test/java/io/trino/plugin/thrift/integration/ThriftQueryRunner.java
testing/trino-testing/src/main/java/io/trino/testing/DistributedQueryRunner.java
testing/trino-testing/src/main/java/io/trino/testing/StandaloneQueryRunner.java

Expose exchange manager implementation from QueryRunner for sake of whitebox introspection from test code.

Expose exchange manager from QueryRunner

---

plugin/trino-hive/src/main/java/io/trino/plugin/hive/metastore/glue/DefaultGlueColumnStatisticsProvider.java

Remove unused method

---

.github/workflows/ci.yml
plugin/trino-delta-lake/README.md
testing/trino-product-tests-launcher/src/main/java/io/trino/tests/product/launcher/env/environment/AbstractSinglenodeDeltaLakeDatabricks.java

When running on PRs from forks, with changes only in submodules, the build-pt job needs to describe all product test environments and all required variables need to be set. Some were renamed in 8a4e55c720fbba74970550753eb25b74542c569f (#15011).
Fixes #15143
n/a

Set required env vars for build-pt CI job

---

testing/trino-product-tests/src/main/java/io/trino/tests/product/deltalake/TestDeltaLakeWriteDatabricksCompatibility.java

Closes #15173 if we allow updating partition columns in Delta Lake connector.
```markdown
```

Fix broken Delta Lake test about UPDATE partition columns

---

plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/BaseDeltaLakeRegisterTableProcedureTest.java
plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/TestIcebergRegisterTableProcedure.java

Add test for registering partitioned table in Delta Lake and Iceberg

Add test for registering partitioned table in Delta Lake and Iceberg

---

core/trino-main/src/main/java/io/trino/execution/scheduler/NodeAssignmentStats.java

Remove unused field

---

core/trino-main/src/main/java/io/trino/dispatcher/FailedDispatchQuery.java
core/trino-main/src/main/java/io/trino/dispatcher/FailedDispatchQueryFactory.java
core/trino-main/src/main/java/io/trino/dispatcher/LocalDispatchQueryFactory.java
core/trino-main/src/main/java/io/trino/execution/QueryInfo.java
core/trino-main/src/main/java/io/trino/execution/QueryStateMachine.java
core/trino-main/src/test/java/io/trino/execution/BaseDataDefinitionTaskTest.java
core/trino-main/src/test/java/io/trino/execution/MockManagedQueryExecution.java
core/trino-main/src/test/java/io/trino/execution/TestCallTask.java
core/trino-main/src/test/java/io/trino/execution/TestCommitTask.java
core/trino-main/src/test/java/io/trino/execution/TestCreateMaterializedViewTask.java
core/trino-main/src/test/java/io/trino/execution/TestDeallocateTask.java
core/trino-main/src/test/java/io/trino/execution/TestPrepareTask.java
core/trino-main/src/test/java/io/trino/execution/TestQueryInfo.java
core/trino-main/src/test/java/io/trino/execution/TestQueryStateMachine.java
core/trino-main/src/test/java/io/trino/execution/TestResetSessionTask.java
core/trino-main/src/test/java/io/trino/execution/TestRollbackTask.java
core/trino-main/src/test/java/io/trino/execution/TestSetPathTask.java
core/trino-main/src/test/java/io/trino/execution/TestSetRoleTask.java
core/trino-main/src/test/java/io/trino/execution/TestSetSessionTask.java
core/trino-main/src/test/java/io/trino/execution/TestSetTimeZoneTask.java
core/trino-main/src/test/java/io/trino/execution/TestStartTransactionTask.java
core/trino-main/src/test/java/io/trino/server/TestBasicQueryInfo.java
core/trino-main/src/test/java/io/trino/server/TestQueryStateInfo.java

This will help to diagnose issues quicker.
** NO RELEASE NOTES **

Embed Trino version in QueryInfo

---

lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java

```markdown
* Improve Parquet files reading performance. ({issue}`issuenumber`)
```

Increase Parquet page max positions

---

plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/catalog/glue/TrinoGlueCatalog.java

Iceberg version of #14746
```markdown
* Fix failure when access denied exceptions happened during listing tables or views in a Glue. ({issue}`14971`)
```

Suppress permission denied when listing tables and views in Iceberg Glue

---

plugin/trino-redshift/src/main/java/io/trino/plugin/redshift/RedshiftClient.java

Make `legacyToWriteMapping` method static

---

docs/src/main/sphinx/admin/properties-task.rst

Putting the docs into plain english to be more user-friendly.
Follow-up to #14553

Fix default values in task properties docs

---

docs/src/main/sphinx/security/overview.rst
docs/src/main/sphinx/security/password-file.rst

Adds a verification step to the Trino security overview page with a link to the steps to verify user/password configuration.
```markdown
```

Add verification step for authentication docs

---

lib/trino-parquet/src/main/java/io/trino/parquet/DictionaryPage.java
lib/trino-parquet/src/main/java/io/trino/parquet/dictionary/BinaryDictionary.java
lib/trino-parquet/src/main/java/io/trino/parquet/dictionary/Dictionary.java
lib/trino-parquet/src/main/java/io/trino/parquet/dictionary/DoubleDictionary.java
lib/trino-parquet/src/main/java/io/trino/parquet/dictionary/FloatDictionary.java
lib/trino-parquet/src/main/java/io/trino/parquet/dictionary/IntegerDictionary.java
lib/trino-parquet/src/main/java/io/trino/parquet/dictionary/LongDictionary.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/ParquetReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BinaryBuffer.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BinaryColumnAdapter.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/BooleanColumnAdapter.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ByteColumnAdapter.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ColumnAdapter.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/FlatColumnReader.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/Int128ColumnAdapter.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/IntColumnAdapter.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/LongColumnAdapter.java
lib/trino-parquet/src/main/java/io/trino/parquet/reader/flat/ShortColumnAdapter.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/BenchmarkShortDecimalColumnReader.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/TestData.java
lib/trino-parquet/src/test/java/io/trino/parquet/reader/flat/TestFlatColumnReader.java
plugin/trino-hive/src/test/java/io/trino/plugin/hive/parquet/AbstractTestParquetReader.java

Minor cleanups to parquet reader

Minor cleanups to parquet reader

---

.github/CONTRIBUTING.md

We should make it easier to find the contributing guide. Linking to it is better than creating a copy (see #15254 for more discussion).
Since the `CONTRIBUTING.md` file doesn't contain much useful context, I want to suggest linking directly to the trino.io site from the `README.md` file.

Link contributing guide

---

core/trino-parser/pom.xml
core/trino-parser/src/main/java/io/trino/sql/ExpressionFormatter.java
core/trino-parser/src/test/java/io/trino/sql/TestExpressionFormatter.java
core/trino-parser/src/test/java/io/trino/sql/parser/ParserAssert.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java

Before
```sql
INTERVAL  '2' HOUR
INTERVAL -  '2' HOUR
```
After
```sql
INTERVAL '2' HOUR
INTERVAL -'2' HOUR
```

Remove redundant spaces in interval formatting

---

core/trino-main/src/main/java/io/trino/sql/planner/optimizations/PropertyDerivations.java
core/trino-main/src/test/java/io/trino/sql/query/TestRowPatternMatching.java

Fixes https://github.com/trinodb/trino/issues/15343
```
* Fix potential failure of queries involving `MATCH_RECOGNIZE`. ({issue}`15343`)
```
Thanks @martint for the simplified repro / test case.

Fix property derivations for PatternRecognitionNode

---

plugin/trino-phoenix5/src/test/java/io/trino/plugin/phoenix5/TestPhoenixConnectorTest.java

Remove unused throws Exception in TestPhoenixConnectorTest
NA
```markdown
```

Remove unused throws Exception in TestPhoenixConnectorTest

---

core/trino-main/src/main/java/io/trino/sql/planner/planprinter/TextRenderer.java
docs/src/main/sphinx/sql/explain-analyze.rst
testing/trino-testing/src/main/java/io/trino/testing/AbstractDistributedEngineOnlyQueries.java

Filter out empty distributions in EXPLAIN ANALYZE VERBOSE

---

core/trino-parser/src/main/java/io/trino/sql/tree/CreateMaterializedView.java
core/trino-parser/src/test/java/io/trino/sql/parser/TestSqlParser.java

Extracted from https://github.com/trinodb/trino/pull/15104 to reduce the scope there.

Remove duplicate test case
